/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS "MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  WapResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *  Resource definitions.
 *
 *  Author:
 * -------
 *  Travis Tsai (MTK01624)
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef WAPRESDEF_H
#define WAPRESDEF_H

#include "MMI_features.h"   /* add if you use any compile options defined in MMI_features.h */
#include "MMIDataType.h"    /* for resource base */
#include "GlobalResDef.h"
#include "custdatares.h"

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Screen IDs */
typedef enum
{
//	  SCR_ID_WAP = WAP_BASE,
    /* add new screen ID below this line */
    WAP_SCREEN_WIDGET = WAP_BASE,
    WAP_SCREEN_WIDGET_DUMMY,
    WAP_SCREEN_FULLSCREEN_EDITOR,
    WAP_SCREEN_WCSS_EDITOR,
    WAP_SCREEN_FULLSCREEN_EDITOR_OPTION,
    WAP_SCREEN_SAVENAME_EDITOR,
    WAP_SCREEN_SAVENAME_EDITOR_OPTION,
    WAP_SCREEN_OPTION_GROUP,
    WAP_SCREEN_MULTIPLE_OPTION_GROUP,
    WAP_SCREEN_DELETE_ALL,
    WAP_SCREEN_NOT_READY,
    WAP_SCREEN_EDITOR_MESSAGE,
    WAP_SCREEN_MESSAGE_NOTIFICATION,
    WAP_SCREEN_NEW_MESSAGE_IN_KEYPAD_LOCKED_IDLE_SCREEN,
    WAP_SCREEN_SYSTEM_MESSAGE,
    WAP_SCREEN_TRANSITION_ANIMATION,
    WAP_SCREEN_WARNING_CONFIRM,
    WAP_BRA_SCREEN_TRANSITION_ANIMATION,
    WAP_WIDGET_SCREEN_TRANSITION_ANIMATION_MMS,

  	/* OWL Adp */
    OWL_ADP_SCREEN_FULLSCREEN_EDITOR,
    OWL_ADP_SCREEN_WCSS_EDITOR,
    OWL_ADP_SCREEN_FULLSCREEN_EDITOR_OPTION,

    /* add new screen ID above this line */
    SCR_ID_WAP_END
} SCR_ID_WAP_ENUM;

/* do not compile options to wrap string ids */
/* String IDs */
typedef enum
{
    WAP_STR_ID_BEGIN = WAP_BASE,
    /* add new string ID below this line */
    
    BRS_STR_ID_DEFAULT_IMODE_DLG_CANCEL_MSG,
    BRS_STR_ID_DEFAULT_IMODE_DLG_OK_MSG,
    BRS_STR_ID_DEFAULT_IMODE_DLG_USER_MSG,
    BRS_STR_ID_CANCEL,
    BRS_STR_ID_DEFAULT_INPUT_FORMAT_USER_MSG,
    BRS_STR_ID_OK,
    BRS_STR_ID_NO_MIME_MSG,
    BRS_STR_ID_ERROR_COMMUNICATION,
    MEA_STR_ID_SEND_MMS_QUERY,
    MEA_STR_ID_SIM_1,
    MEA_STR_ID_SIM_2,
    MEA_STR_ID_FROM_SIM_1,
    MEA_STR_ID_FROM_SIM_2,
    //MEA_STR_ID_CHOOSE_SIM,
    MEA_STR_ID_FORWARD_WITH_EDIT_CONTENT,
    MEA_STR_ID_SERVER_TIMEOUT,
    MEA_STR_ID_DOWNLOAD_EXPIRED_MM_CONFIRM,
    MEA_STR_ID_MSGSIZE_PROMPT_1,
    MEA_STR_ID_MSGSIZE_PROMPT_2,    
    MEA_STR_ID_CONFIG_RETRIEVE_ALLOWED,
    MEA_STR_ID_CONFIG_RETRIEVE_IM_ROAM,
    MEA_STR_ID_CONFIG_SEND_READ_REPORT_ALLOWED,
    //MEA_STR_ID_MAX_TEXT_LEN_REACHED,
    MEA_STR_ID_REMOVE_INVALID_OBJECT,
    MEA_STR_ID_REMOVE_INVALID_OBJECT_TO_ATTACH,
    MEA_STR_ID_REMOVE_INVALID_NUMBER,
    MEA_STR_ID_MOVE_TO_ARCHIVE,
    MEA_STR_ID_MOVE_TO_ARCHIVE_QUERY,
    MEA_STR_ID_DELETE_ALL_ARCHIVE,
    MEA_STR_ID_EMPTY_STRING,
    MEA_STR_ID_BACK,
    MEA_STR_ID_CANCEL,
    MEA_STR_ID_OK,
    MEA_STR_ID_SELECT,
    MEA_STR_ID_ON,
    MEA_STR_ID_OFF,
    MEA_STR_ID_VIEW,
    MEA_STR_ID_REVIEW,
    MEA_STR_ID_SAVE,
    MEA_STR_ID_EXIT,
    MEA_STR_ID_FROM,
    MEA_STR_ID_CC,
    MEA_STR_ID_TO,
    MEA_STR_ID_SUBJECT,
    //MEA_STR_ID_KB,
    //MEA_STR_ID_MESSENGER_APP,
    MEA_STR_ID_REM_MEDIA_OBJ,
    MEA_STR_ID_OPTIONS,
    MEA_STR_ID_YES,
    MEA_STR_ID_NO,
    MEA_STR_ID_EDIT,
    MEA_STR_ID_VIEW_TITLE,
    //MEA_STR_ID_ATTACH_TITLE,
    //MEA_STR_ID_VIEW_ATTACHMENTS,
    MEA_STR_ID_READ_REPORT,
    MEA_STR_ID_DELIV_REPORT,
    MEA_STR_ID_STATUS,
    //MEA_STR_ID_DATE,
    MEA_STR_ID_RECEIVE_DATE,
    MEA_STR_ID_SEND_DATE,
    MEA_STR_ID_CREATE_DATE,
    MEA_STR_ID_EXPIRED,
    MEA_STR_ID_RETRIEVED,
    MEA_STR_ID_REJECTED,
    MEA_STR_ID_DEFERRED,
    MEA_STR_ID_UNRECOGNIZED,
    MEA_STR_ID_INDETERMINATE,
    MEA_STR_ID_FORWARDED,
    MEA_STR_ID_UNKOWN,
    MEA_STR_ID_READ,
    MEA_STR_ID_NOT_READ,
    MEA_STR_ID_CONFIG_SENDING,
    MEA_STR_ID_CONFIG_MSG_FILTERS,
    MEA_STR_ID_EDIT_CONTENT,
    MEA_STR_ID_EDIT_TEXT,
    MEA_STR_ID_ME_TITLE,
    MEA_STR_ID_ADD_IMAGE,
    MEA_STR_ID_PREVIEW_SMIL,
    MEA_STR_ID_INSERT_SLIDE,
    MEA_STR_ID_ADD_SLIDE_BEFORE,
    MEA_STR_ID_ADD_SLIDE_AFTER,
    MEA_STR_ID_DELETE_SLIDE,
    MEA_STR_ID_NEXT_SLIDE,
    MEA_STR_ID_PREVIOUS_SLIDE,
    MEA_STR_ID_ADD_MEDIA_OBJECT,
    MEA_STR_ID_ADD_TEXT,
    MEA_STR_ID_ADD_BOOKMARK_TEXT,
    MEA_STR_ID_CONTENT_TRUNCATED,
    MEA_STR_ID_DURATION,
    MEA_STR_ID_NEW_MSG_FROM_TEMPL,
    //MEA_STR_ID_CONFIG_TREAT_AS_DEL,
    //MEA_STR_ID_CONFIG_IM_SIZE,
    MEA_STR_ID_CONFIG_ANONYM,
    MEA_STR_ID_CONFIG_MSG_RETRIEVAL,
    //MEA_STR_ID_CONFIG_IM_SERVER,
    MEA_STR_ID_CONFIG,
    MEA_STR_ID_NETWORK_ACCOUNT,
    MEA_STR_ID_CONN_TYPE,
    MEA_STR_ID_CONN_TYPE_HTTP,
    MEA_STR_ID_CONN_TYPE_WSP_CL,
    MEA_STR_ID_CONN_TYPE_WSP_CO,
    MEA_STR_ID_CONFIG_MMSC,
    //MEA_STR_ID_CONFIG_NETWORK,
    //MEA_STR_ID_LOGIN,
    //MEA_STR_ID_PASSWD,
    //MEA_STR_ID_REALM,
    //MEA_STR_ID_SEC_PORT,
    //MEA_STR_ID_HTTP_PORT,
    //MEA_STR_ID_WAP_GATEWAY,
    MEA_STR_ID_IM_RETRIEVAL,
    MEA_STR_ID_DEL_RETRIEVAL,
    //MEA_STR_ID_EMPTY_STRING034,
    MEA_STR_ID_CONFIG_SOS,
    MEA_STR_ID_CONFIG_RR,
    MEA_STR_ID_CONFIG_DR,
    MEA_STR_ID_UNSUPPORTED_HEADER_FIELDS,
    MEA_STR_ID_CONFIG_VAL_PER,
    MEA_STR_ID_CONFIG_PRIORITY,
    MEA_STR_ID_ALLOW,
    MEA_STR_ID_REJECT,
    MEA_STR_ID_DOWNLOADING_MM,
    //MEA_STR_ID_GENERATING_MESSAGE,
    MEA_STR_ID_SENDING_MSG,
    //MEA_STR_ID_BYTES_RECEIVED,
    //MEA_STR_ID_BYTES_SENT,
    MEA_STR_ID_CONNECTING,
    MEA_STR_ID_DELETE,
    //MEA_STR_ID_NEW_SMIL,
    MEA_STR_ID_SEND,
    //MEA_STR_ID_EDIT_MESSAGE,
    MEA_STR_ID_FORWARD,
    MEA_STR_ID_REPLY,
    MEA_STR_ID_REPLY_SMS,
    MEA_STR_ID_REPLY_TO_ALL,
    MEA_STR_ID_CONFIG_1_HOUR,
    MEA_STR_ID_CONFIG_6_HOURS,
    MEA_STR_ID_CONFIG_12_HOURS,
    MEA_STR_ID_CONFIG_1_DAY,
    MEA_STR_ID_CONFIG_1_WEEK,
    MEA_STR_ID_CONFIG_MAX,
    MEA_STR_ID_CONFIG_LOW,
    MEA_STR_ID_CONFIG_NORMAL,
    MEA_STR_ID_CONFIG_HIGH,
    MEA_STR_ID_SAVE_AS_TEMPLATE,
    MEA_STR_ID_TEMPLATES,
    MEA_STR_ID_MENU,
    MEA_STR_ID_ARCHIVE,
    MEA_STR_ID_INBOX,
    MEA_STR_ID_OUTBOX,
    MEA_STR_ID_DRAFTS,
    MEA_STR_ID_SENT,
    //MEA_STR_ID_EMPTY_STRING023,
    //MEA_STR_ID_EMPTY_STRING024,
    //MEA_STR_ID_EMPTY_STRING025,
    MEA_STR_ID_INVALID_MESSAGE,
    MEA_STR_ID_NO_PERSISTENT_STORAGE,
    MEA_STR_ID_NOT_ENOUGH_MEM,
    MEA_STR_ID_FAILED_TO_DISPLAY_JSR_MMS,
    MEA_STR_ID_FAILED_TO_DISPLAY_MM,
    MEA_STR_ID_ERROR,
    MEA_STR_ID_PANIC,
    //MEA_STR_ID_INVALID_ADDRESS,
    MEA_STR_ID_INVALID_PROXY_HOST,
    MEA_STR_ID_INVALID_PROXY_PORT,
    MEA_STR_ID_INVALID_WAP_GATEWAY,
    MEA_STR_ID_INVALID_PROXY_SCHEME,
    MEA_STR_ID_DOWNLOAD_FAILED,
    MEA_STR_ID_DOWNLOAD_FAILED_ILLEGAL_PDU,
    MEA_STR_ID_FAILED_CONNECTION,
    MEA_STR_ID_FAILED_TO_FORWARD,
    MEA_STR_ID_FAILED_TO_SEND,
    MEA_STR_ID_DELETE_MSG_QUEST,
    MEA_STR_ID_CLOSE_MEA,
    MEA_STR_ID_MESSAGE_SENT,
    MEA_STR_ID_READ_REPORT_SEND,
    MEA_STR_ID_READING_MSG,
    MEA_STR_ID_FAILED_TO_SAVE,
    MEA_STR_ID_WRONG_MESSAGE_TYPE,
    MEA_STR_ID_ATTACH_ERROR,
    MEA_STR_ID_SLIDE_LIMIT_REACHED,
    MEA_STR_ID_ME_INVALID_CONFIG,
    MEA_STR_ID_INVALID_VALUE,
    MEA_STR_ID_FAILED_TO_EDIT,
    MEA_STR_ID_FAILED_TO_REPLY,
    MEA_STR_ID_ADDRESS_FIELD_MISSING,
    MEA_STR_ID_FAILED_TO_READ_MO,
    MEA_STR_ID_FAILED_TO_ADD_EMPTY_OBJECT,
    MEA_STR_ID_FAILED_LARGE_RESOLUTION,
    MEA_STR_ID_FAILED_FILE_CORRUPT,
    MEA_STR_ID_FAILED_TO_DISPLAY_NOTIF,
    MEA_STR_ID_DOWNLOAD_REQ1,
    MEA_STR_ID_DOWNLOAD_REQ2,
    MEA_STR_ID_FAILED_TO_SEND_RR,
    MEA_STR_ID_INTERVAL_PREFIX,
    MEA_STR_ID_INTERVAL_INFIX,
    MEA_STR_ID_RETR_SIZE_EXCEEDED,
    MEA_STR_ID_RETR_SIZE_EXCEEDED_CONFIRM,
    MEA_STR_ID_DOWNLOAD_EXPIRED_MM_PROHIBIT,
    MEA_STR_ID_EDIT_FAILED_RESOURCES_EXHAUSTED,
    //MEA_STR_ID_EMPTY199,
    //MEA_STR_ID_CONFIG_PERS,
    MEA_STR_ID_CONFIG_ADVERT,
    MEA_STR_ID_CONFIG_INFO,
    MEA_STR_ID_CONFIG_AUTO,
    MEA_STR_ID_CONFIG_USER_STRING,
    //MEA_STR_ID_PHONE_BOOK,
    MEA_STR_ID_TO_MANY_RECIPIENTS,
    MEA_STR_ID_INVALID_RECIP_ADDRESS,
    MEA_STR_ID_RECIPIENTS,
    //MEA_STR_ID_ADD_RECIPIENT_QUEST,
    MEA_STR_ID_NO_OF_RECIPIENTS,
    MEA_STR_ID_FAILED_FORWARD,
    MEA_STR_ID_FAILED_FORWARD_LOCK,
    //MEA_STR_ID_EMPTY212,
    //MEA_STR_ID_EMPTY213,
    //MEA_STR_ID_EMPTY214,
    //MEA_STR_ID_EMPTY215,
    MEA_STR_ID_MAX_RETR_SIZE,
    MEA_STR_ID_RE,
    MEA_STR_ID_FW,
    MEA_STR_ID_MESSAGE_SIZE_MAXIMUM_REACHED,
    MEA_STR_ID_CREATION_MODE_MAX_MESSAGE_SIZE_REACHED,
    //MEA_STR_ID_MESSAGE_SIZE_WARNING,
    MEA_STR_ID_REPLY_CHARGING,
    MEA_STR_ID_REPLY_CHARGING_DEADLINE,
    MEA_STR_ID_REPLY_CHARGING_SIZE,
    MEA_STR_ID_TEXT_ONLY,
    MEA_STR_ID_CONFIG_1_KB,
    MEA_STR_ID_CONFIG_10_KB,
    MEA_STR_ID_SELECT_COLOR,
    //MEA_STR_ID_BG_COLOR,
    MEA_STR_ID_CONFIG_MSG_RETR_HOME_MODE,
    MEA_STR_ID_CONFIG_MSG_RETR_ROAM_MODE,
    MEA_STR_ID_AUTO_RETRIEVAL_ROAM,
    MEA_STR_ID_ASK_RETRIEVAL_ROAM,
    MEA_STR_ID_RES_RETRIEVAL_ROAM,
    //MEA_STR_ID_CONFIG_SEND_VISIBILITY,
    //MEA_STR_ID_SHOW_NUMBER,
    //MEA_STR_ID_HIDE_NUMBER,
    MEA_STR_ID_CONFIG_SEND_READ_REPORT,
    MEA_STR_ID_CONFIG_ALWAYS,
    MEA_STR_ID_CONFIG_ON_REQUEST,
    MEA_STR_ID_CONFIG_NEVER,
    MEA_STR_ID_CONFIG_DELIVERY_TIME,
    MEA_STR_ID_CONFIG_IMMEDIATE,
    MEA_STR_ID_CONFIG_IN_ONE_HOUR,
    MEA_STR_ID_CONFIG_IN_12_HOURS,
    MEA_STR_ID_CONFIG_IN_24_HOURS,
    MEA_STR_ID_PLAY_SOUND,
    MEA_STR_ID_PLAY_VIDEO,
    MEA_STR_ID_CONFIG_DELIVERY_REPORT_ALLOWED,
    MEA_STR_ID_ADD_AUDIO,
    //MEA_STR_ID_TEXT_COLOR,
    MEA_STR_ID_BCC,
    MEA_STR_ID_TEXT_MISSING,
    //MEA_STR_ID_SINGLE_OBJECT_SIZE_WARNING,
    MEA_STR_ID_FAILED_TO_INSERT_DRM,
    MEA_STR_ID_FAILED_TO_RESIZE_IMAGE,
    MEA_STR_ID_ROAM_DOWNLOAD_REQ1,
    MEA_STR_ID_ROAM_DOWNLOAD_REQ2,
    MEA_STR_ID_ROAM_SEND_REQ1,
    MEA_STR_ID_ROAM_SEND_REQ2,
    MEA_STR_ID_INVALID_NETWORK_SETTINGS,
    //MEA_STR_ID_CALL_BUSY,
    MEA_STR_ID_CALL_NO_NETWORK,
    //MEA_STR_ID_CALL_NO_ANSWER,
    //MEA_STR_ID_CALL_NOT_A_NUMBER,
    MEA_STR_ID_CALL_ERROR,
    //MEA_STR_ID_UNHANDLED_LINK,
    MEA_STR_ID_FAILED_TO_GET_MESSAGE_INFO,
    MEA_STR_ID_FAILED_TO_OPEN_WINDOW,
    MEA_STR_ID_MAX_NUMBER_OF_MSG,
    MEA_STR_ID_FAILED_TO_SEND_REFUSED,
    MEA_STR_ID_NUMBER_OF_MSG_WARNING,
    MEA_STR_ID_ADDRESS_ALREADY_EXISTS,
    MEA_STR_ID_ATTACH_MAXIMUM_REACHED,
    MEA_STR_ID_ADD_ATTACHMENT,
    MEA_STR_ID_ADD_EMAIL,
    MEA_STR_ID_ADD_NUMBER,
    MEA_STR_ID_ADD_RECIPIENT,
    MEA_STR_ID_ATTACHMENT_REMOVED,
    MEA_STR_ID_AUTO_SIGNATURE,
    MEA_STR_ID_SIGNATURE,
    MEA_STR_ID_AUTO_SIGNATURE_ERROR_TOO_MANY_SLIDES,
    MEA_STR_ID_AUTO_SIGNATURE_ERROR_SIZE_TOO_LARGE,
    MEA_STR_ID_CONFIG_COMPOSE,
    MEA_STR_ID_CREATION_MODE,
    MEA_STR_ID_BEST_SLIDE_DURATION,    
    MEA_STR_ID_CREATION_MODE_FREE,
    MEA_STR_ID_CREATION_MODE_RESTRICTED,
    MEA_STR_ID_CREATION_MODE_WARNING,
    MEA_STR_ID_RESTRICTED_MIME_ACTION_NONE,
    MEA_STR_ID_RESTRICTED_MODE_REMOVE_OBJ_REQ,
    MEA_STR_ID_RESTRICTED_MODE_FAIL_TO_EDIT,
    MEA_STR_ID_RESTRICTED_MODE_FAIL_TO_SEND,
    MEA_STR_ID_RESTRICTED_MODE_FAIL_TO_FORWARD,
    MEA_STR_ID_WARNING_MODE_CONFIRM,
    MEA_STR_ID_IMAGE_RESIZE,
    MEA_STR_ID_640x480,
    MEA_STR_ID_320x240,
    MEA_STR_ID_160x120,
    MEA_STR_ID_DELETE_ALL,
    MEA_STR_ID_DELETE_ALL_INBOX,
    MEA_STR_ID_DELETE_ALL_OUTBOX,
    MEA_STR_ID_DELETE_ALL_TEMPLATE,
    MEA_STR_ID_DELETE_ALL_SENT,
    MEA_STR_ID_DELETE_ALL_DRAFTS,
    MEA_STR_ID_DIAL,
    MEA_STR_ID_DONE,
    MEA_STR_ID_DOWNLOAD,
    MEA_STR_ID_DOWNLOAD_SIZE,
    MEA_STR_ID_NOTIFICATION_SIZE,
    MEA_STR_ID_EDIT_AUDIO,
    MEA_STR_ID_EDIT_ATTACHMENT,
    MEA_STR_ID_EDIT_IMAGE,
    MEA_STR_ID_EDIT_PROFILE,
    MEA_STR_ID_EMPTY,
    MEA_STR_ID_EMPTY_LIST,
    MEA_STR_ID_FREE,
    MEA_STR_ID_UNAUTHORIZED_ACCESS,
    MEA_STR_ID_INVALID_MMS_VERSION,
    MEA_STR_ID_LSK_READ,
    MEA_STR_ID_LSK_YES,
    MEA_STR_ID_MEMORY_STATUS,
    MEA_STR_ID_MMS,
    MEA_STR_ID_MSG,
    MEA_STR_ID_MSGS,
    MEA_STR_ID_NEW_MMS_MSG,
    MEA_STR_ID_NO_CONTENT,
    MEA_STR_ID_NO_NUMBER,
    MEA_STR_ID_NO_SUBJECT,
    MEA_STR_ID_PLY_SMIL_BUSY,
    MEA_STR_ID_PROPERTIES,
    MEA_STR_ID_REMOVE_AUDIO,
    MEA_STR_ID_REMOVE_ATTACHMENT,
    MEA_STR_ID_REMOVE_IMAGE,
    MEA_STR_ID_REMOVE_TEXT,
    MEA_STR_ID_ADD_VIDEO,
    MEA_STR_ID_EDIT_VIDEO,
    MEA_STR_ID_REMOVE_VIDEO,
    MEA_STR_ID_RESEND,
    MEA_STR_ID_RSK_NO,
    MEA_STR_ID_SAVED_AND_SENT,
    MEA_STR_ID_SAVE_AND_SEND,
    MEA_STR_ID_SAVE_TO_DRAFTS,
    MEA_STR_ID_SAVE_TO_PHONE_BOOK,
    MEA_STR_ID_SEND_ONLY,
    MEA_STR_ID_SEND_OPTIONS,
    MEA_STR_ID_SLIDE,
    MEA_STR_ID_SLIDES,
    MEA_STR_ID_STORAGE_FULL,
    MEA_STR_ID_TOO_MANY_CONNECTIONS,
    MEA_STR_ID_TOTAL,
    MEA_STR_ID_USAGE,
    MEA_STR_ID_USE_DETAILS,
    MEA_STR_ID_WRITE_MESSAGE,
    MEA_STR_ID_WRITE_MMS,
    MEA_STR_ID_MESSAGE_CORRUPT,
    MEA_STR_ID_TEMPLATE_CORRUPT,
    MEA_STR_ID_REMOVE_CORRUPT_MESSAGE_REQ,
    MEA_STR_ID_WRITE_SMS,
    MEA_STR_ID_UM_MSG,
    MEA_STR_ID_UM_MSGS,
    MEA_STR_ID_COMM_UNAVAILABLE,
    MEA_STR_ID_NOT_AVAILABLE,
    MEA_STR_ID_SERVER,
    MEA_STR_ID_MINS,
    MEA_STR_ID_MESSAGE_IS_IN_USE,
    MEA_STR_ID_SHOW_STATUS,
    MEA_STR_ID_MOVE_TO_DRAFT,
    MEA_STR_ID_MOVE_TO_DRAFT_QUERY,
    MEA_STR_ID_WAITING,
    MEA_STR_ID_NEXT_TRANS_TIME,
    MEA_STR_ID_REMAIN_QUOTA,
    //MEA_STR_ID_TEMPLATES_FOLDER_LIST,
    MEA_STR_ID_DEFAULT_TEMPLATES,
    MEA_STR_ID_USER_TEMPLATES,
    MEA_STR_ID_FAILED_SAVE_AS_TEMPLATE,
    MEA_STR_ID_FAILED_ENTER_DEF_TEMPLATE,
    MEA_STR_ID_NUMBER_TOO_LONG,
    MEA_STR_ID_COLON,
    MEA_STR_ID_CALL_IN_PROGRESS,
	MEA_STR_ID_ADDRESS_TOO_LONG,
    MEA_STR_ID_COMMON_SETTINGS,
    MEA_STR_ID_UNREAD,
    MEA_STR_ID_MIN_TIME_DURATION,
    MEA_STR_ID_URL_TOOLONG,
    MEA_STR_ID_INVALID_DTCNT_ASK_CFG,
    MEA_STR_ID_ERROR_GPRS_UNKNOWN_APN,
    MEA_STR_ID_ERROR_GPRS_AUTHENTICATION_FAILURE,
    MEA_STR_ID_ERROR_GPRS_UNSUPPORTED_SERVICE_OPTION,
    MEA_STR_ID_ERROR_GPRS_UNSUBSCRIBED_SERVICE_OPTION,
    MEA_STR_ID_ERROR_COMMUNICATION,
    MEA_STR_ID_INVALID_URL,
    MEA_STR_ID_SAVED,
    MEA_STR_ID_SAVE_ASK,
    MEA_STR_ID_DELETE_ALL_ASK,
    MEA_STR_ID_DELETED,
    MEA_STR_ID_GOTO,
    MEA_STR_ID_ADD_TO_BOOKMARKS,
    MEA_STR_ID_CANCEL_PROV,
    /* MMA */
    MMA_STR_ID_MESSAGE_CORRUPT,
    MMA_STR_ID_MMS_DELIVERY_REPORT,
    MMA_STR_ID_MMS_READ_REPORT,
    MMA_STR_ID_MMS_GROUP_MESSAGE,
    /* ////////////////////////////////////// */
    MMS_STR_ID_EMPTY_STRING,
    MMS_STR_ID_RR_TEXT_FROM,
    MMS_STR_ID_RR_TEXT_MSGID,
    MMS_STR_ID_RR_TEXT_READ,
    MMS_STR_ID_RR_TEXT_SENT,
    MMS_STR_ID_RR_TEXT_SUBJECT,
    MMS_STR_ID_RR_TEXT_TO,
    MMS_STR_ID_RR_TEXT_WAS_READ,
    MMS_STR_ID_RR_TEXT_YOUR_MSG,
    MMS_STR_ID_TEMPLATES_TITLE_01,
    MMS_STR_ID_TEMPLATES_TITLE_02,
    MMS_STR_ID_TEMPLATES_TITLE_03,
    MMS_STR_ID_TEMPLATES_TITLE_04,
    MMS_STR_ID_TEMPLATES_TITLE_05,
    MMS_STR_ID_TEMPLATES_TITLE_06,
    MMS_STR_ID_TEMPLATES_TITLE_07,
    MMS_STR_ID_TEMPLATES_TITLE_08,
    MMS_STR_ID_TEMPLATES_TITLE_09,
    MMS_STR_ID_TEMPLATES_TITLE_10,
    /* ////////////////////////////////////////// */
    MSF_STR_ID_ROOT_FOLDER_PICTURE,
    MSF_STR_ID_ROOT_FOLDER_SOUND,
    MSF_STR_ID_ROOT_FOLDER_VIDEO,
    MSF_STR_ID_ROOT_FOLDER_APP,
    MSF_STR_ID_ROOT_FOLDER_ANIM,
    MSF_STR_ID_ROOT_FOLDER_EXT,
    MSF_STR_ID_DLG_ACTION_OK,
    MSF_STR_ID_DLG_ACTION_BACK,
    MSF_STR_ID_DLG_ACTION_CANCEL,
    MSF_STR_ID_DLG_ACTION_SAVE,
    MSF_STR_ID_DLG_TEXT_EDIT_FILENAME,
    MSF_STR_ID_DLG_TEXT_ROOT_FOLDER,
    MSF_STR_ID_DLG_TEXT_SAVE_HERE,
    MSF_STR_ID_DLG_EXISTS_TEXT1,
    MSF_STR_ID_DLG_EXISTS_TEXT2,
    MSF_STR_ID_DLG_EXISTS_TITLE,
    MSF_STR_ID_DLG_NO_REPLACE_TEXT1,
    MSF_STR_ID_DLG_NO_REPLACE_TEXT2,
    MSF_STR_ID_DLG_NO_REPLACE_TITLE,
    MSF_STR_ID_DLG_SAVE_ERROR,
    MSF_STR_ID_DLG_SAVE_NOT_ALLOWED,
    MSF_STR_ID_USER_FOLDER_NATURE,
    MSF_STR_ID_USER_FOLDER_WORK,
    MSF_STR_ID_USER_FOLDER_VACATION,
    MSF_STR_ID_USER_FOLDER_MUSIC,
    MSF_STR_ID_USER_FOLDER_SOUNDS,
    MSF_STR_ID_SAS_BAR_TITLE,
    MSF_STR_ID_SAS_ACTION_CANCEL,
    MSF_STR_ID_SAS_ERROR_TITLE,
    MSF_STR_ID_SAS_ERROR_FULL,
    MSF_STR_ID_SAS_ERROR_SIZE,
    MSF_STR_ID_DAS_MEMORY_NOT_ENOUGH,
    MSF_STR_ID_MIME_ACTION_SAVE,
    MSF_STR_ID_MIME_ACTION_SEND_AS_MMS,
    MSF_STR_ID_MIME_ACTION_SET,
    MSF_STR_ID_MIME_ACTION_SET_SCREENSAVER,
    MSF_STR_ID_MIME_ACTION_SET_GREETING,
    MSF_STR_ID_MIME_ACTION_SET_WALLPAPER,
    MSF_STR_ID_DLG_ACTION_CREATE_DIR,
    MSF_STR_ID_DLG_TITLE_CREATE_DIR,
    MSF_STR_ID_DLG_ERROR_CREATE_DIR,
    MSF_STR_ID_DLG_COMMON_ERROR,
    MSF_STR_ID_DLG_ERROR_NAME,
    MSF_STR_ID_SAS_PERCENT,
    MSF_STR_ID_SAS_BYTES_SAVED,
    MSF_STR_ID_DLG_CANNOT_SAVE,
    MSF_STR_ID_PROPERTIES_SIZE2,
    MSF_STR_ID_PROPERTIES_SIZE3,
    MSF_STR_ID_PROPERTIES_SIZE4,
    MSF_STR_ID_PROPERTIES_SIZE5,
    MSF_STR_ID_DLG_MIME_ACTION_NONE,
    MSF_STR_ID_MIME_ACTION_SET_RINGTONE,
    MSF_STR_ID_ROOT_FOLDER_BKM,
    MSF_STR_ID_ROOT_FOLDER_OFLN_PGS,
    MSF_STR_ID_ROOT_FOLDER_BKM_PERS,
    MSF_STR_ID_CONNECTING,
    MSF_STR_ID_DAY_MONDAY_SHORT,
    MSF_STR_ID_DAY_TUESDAY_SHORT,
    MSF_STR_ID_DAY_WEDNESDAY_SHORT,
    MSF_STR_ID_DAY_THURSDAY_SHORT,
    MSF_STR_ID_DAY_FRIDAY_SHORT,
    MSF_STR_ID_DAY_SATURDAY_SHORT,
    MSF_STR_ID_DAY_SUNDAY_SHORT,
    MSF_STR_ID_MONTH_JANUARY_SHORT,
    MSF_STR_ID_MONTH_FEBRUARY_SHORT,
    MSF_STR_ID_MONTH_MARCH_SHORT,
    MSF_STR_ID_MONTH_APRIL_SHORT,
    MSF_STR_ID_MONTH_MAY_SHORT,
    MSF_STR_ID_MONTH_JUNE_SHORT,
    MSF_STR_ID_MONTH_JULY_SHORT,
    MSF_STR_ID_MONTH_AUGUST_SHORT,
    MSF_STR_ID_MONTH_SEPTEMBER_SHORT,
    MSF_STR_ID_MONTH_OCTOBER_SHORT,
    MSF_STR_ID_MONTH_NOVEMBER_SHORT,
    MSF_STR_ID_MONTH_DECEMBER_SHORT,
    MSF_STR_ID_INTERNAL_ERROR,
    MSF_STR_ID_CONNECTION_FAILED,
    MSF_STR_ID_SAVE_AS_FAIL,
    MSF_STR_ID_SAS_OPERATION_CANCELED,
    MSF_STR_ID_DLG_NO_MEM_CARD,
    /* //////////////////////////////////////////////////// */
    //PHS_STR_ID_ACCEPT_MSG,
    //PHS_STR_ID_CANCEL,
    //PHS_STR_ID_DECLINE_MSG,
    //PHS_STR_ID_NO_WHITELIST_MSG,
    //PHS_STR_ID_OK,
    //PHS_STR_ID_SIA_CONFIRM_MSG,
 /*PRS_STR_ID_CANCEL,
    PRS_STR_ID_EMPTY,
    PRS_STR_ID_ENTER_PIN,
    PRS_STR_ID_ENTER_PIN_AGAIN,
    PRS_STR_ID_OK,
    PRS_STR_ID_PIN_TITLE,*/
    SEC_STR_ID_CERT1,
    SEC_STR_ID_CERT10,
    SEC_STR_ID_CERT11,
    SEC_STR_ID_CERT14,
    SEC_STR_ID_CERT15,
    SEC_STR_ID_CERT16,
    SEC_STR_ID_CERT17,
    SEC_STR_ID_CERT18,
    SEC_STR_ID_CERT19,
    SEC_STR_ID_CERT2,
    SEC_STR_ID_CERT3,
    SEC_STR_ID_CERT4,
    SEC_STR_ID_CERT5,
    SEC_STR_ID_CERT7,
    SEC_STR_ID_CHOOSE_CERT_TITLE,
    SEC_STR_ID_EMPTY,
    SEC_STR_ID_OK,
    SEC_STR_ID_YES,
    SEC_STR_ID_NO,
    SEC_STR_ID_STORE_CERT,
    /* ////////////////////////////////////////////////////////////// */
    SMA_STR_ID_BACK,
    SMA_STR_ID_EMPTY_STRING,
    SMA_STR_ID_ERR_NO_MEMORY,
    SMA_STR_ID_ERR_WRITING_FILE,
    SMA_STR_ID_LINKS,
    SMA_STR_ID_MENU_NEXT,
    SMA_STR_ID_MENU_PLAY,
    SMA_STR_ID_MENU_PREVIOUS,
    SMA_STR_ID_MENU_SAVE_AUDIO,
    SMA_STR_ID_MENU_SAVE_IMAGE,
    SMA_STR_ID_OK,
    SMA_STR_ID_SLIDE_ACTION_EXIT,
    SMA_STR_ID_SLIDE_ACTION_OK,
    SMA_STR_ID_SLIDE_ACTION_PLAY,
    SMA_STR_ID_SLIDE_ACTION_STOP,
    SMA_STR_ID_SLIDE_MENU_ACTION_BACK,
    SMA_STR_ID_SLIDE_MENU_ACTION_SELECT,
    SMA_STR_ID_UNKNOWN_TEXT,
    SMA_STR_ID_MENU_SAVE_OBJECT,
    SMA_STR_ID_MENU_SAVE_VIDEO,
    SMA_STR_ID_MENU_SAVE_TEXT,
    SMA_STR_ID_FAILED_TO_SAVE,
    SMA_STR_ID_FAILED_TO_SAVE_DRM,
    SMA_STR_ID_ATTACHMENTS,
    SMA_STR_ID_ATTACHMENT_LIST,
    SMA_STR_ID_CALL_BUSY,
    SMA_STR_ID_CALL_FAILED,
    SMA_STR_ID_UI_OPEN,
    SMA_STR_ID_UI_CALL,
    SMA_STR_ID_NOT_ABLE_PLAY_ALL_SLIDES,
    SMA_STR_ID_NO_FIT_OBJECT,
    /* ////////////////////////////////////////////////////// */
    STK_STR_ID_EXIT,
    STK_STR_ID_NON_SECURE,
    STK_STR_ID_PASSWORD,
    STK_STR_ID_REALM_LABEL,
    STK_STR_ID_SAVE_PASSWORD,
    STK_STR_ID_SAVE_USERNAME,
    STK_STR_ID_OK,
    STK_STR_ID_TITLE_PROXY,
    STK_STR_ID_TITLE_SERVER,
    STK_STR_ID_USERNAME,
    //////////////////////////////////////////////////////////
    ///  WIDGET Resource
    WIDGET_STR_ID_CANCEL,
    WIDGET_STR_ID_CANT_INPUT_EMPTY_VALUE,
    WIDGET_STR_ID_CANT_SWITCH_INPUT_METHOD,
    WIDGET_STR_ID_DONE,
    WIDGET_STR_ID_INPUT_FORMAT_ERROR,
    WIDGET_STR_ID_INPUT_METHOD,
    WIDGET_STR_ID_INPUT_TITLE,
    WIDGET_STR_ID_OK,
    WIDGET_STR_ID_OPTION,
    WIDGET_STR_ID_SAVEAS_NAME_INVALID_CHARS,
    WIDGET_STR_ID_PLEASE_WAIT,
    WIDGET_STR_ID_IMAGE_RESIZE,
    WIDGET_STR_ID_SEARCH,
    WIDGET_STR_ID_RECEIVED_PUSH,
    WIDGET_STR_ID_RECEIVED_PUSH_SIM1,
    WIDGET_STR_ID_RECEIVED_PUSH_SIM2,
    WIDGET_STR_ID_RECEIVED_PROVISION,
    WIDGET_STR_ID_RECEIVED_PROVISION_SIM_1,
    WIDGET_STR_ID_RECEIVED_PROVISION_SIM_2,
    WIDGET_STR_ID_RECEIVED_MMS_MSG,
    WIDGET_STR_ID_RECEIVED_MMS_MSG_SIM_1,
    WIDGET_STR_ID_RECEIVED_MMS_MSG_SIM_2,
    WIDGET_STR_ID_RECEIVED_JAVA_MMS_MSG_SIM_1,
    WIDGET_STR_ID_RECEIVED_JAVA_MMS_MSG_SIM_2,
    WIDGET_STR_ID_RECEIVED_MMS_NOTIFICATION,
    WIDGET_STR_ID_RECEIVED_MMS_NOTIFICATION_SIM_1,
    WIDGET_STR_ID_RECEIVED_MMS_NOTIFICATION_SIM_2,
    WIDGET_STR_ID_RECEIVED_MMS_READ_REPORT,
    WIDGET_STR_ID_RECEIVED_MMS_READ_REPORT_SIM_1,
    WIDGET_STR_ID_RECEIVED_MMS_READ_REPORT_SIM_2,    
    WIDGET_STR_ID_RECEIVED_MMS_DELIVERY_REPORT,
    WIDGET_STR_ID_RECEIVED_MMS_DELIVERY_REPORT_SIM_1,
    WIDGET_STR_ID_RECEIVED_MMS_DELIVERY_REPORT_SIM_2,    
    WIDGET_STR_ID_INVALID_WCSS__UPPERCASE_A,
    WIDGET_STR_ID_INVALID_WCSS__LOWERCASE_A,
    WIDGET_STR_ID_INVALID_WCSS__UPPERCASE_X,
    WIDGET_STR_ID_INVALID_WCSS__LOWERCASE_X,
    WIDGET_STR_ID_INVALID_WCSS__LOWERCASE_N,
    WIDGET_STR_ID_INPUT_EMAIL_ERROR,
    /* MSF */
    MSF_STR_ID_MNU_BOOKMARK,
    MSF_STR_ID_ROOT_FOLDER_BOOKMARK,
    MSF_STR_ID_ROOT_FOLDER_TEMPLATES,
    MSF_STR_ID_ROOT_FOLDER_OTH_DOCS,
    MSF_STR_ID_ROOT_FOLDER_CONTACTS,
    MSF_STR_ID_ROOT_FOLDER_SCHEDULER,
    MSF_STR_ID_ROOT_FOLDER_MEMO,
    MSF_STR_ID_ROOT_FOLDER_GAMES,
    MSF_STR_ID_ROOT_FOLDER_SKINS,
    MSF_STR_ID_UILIST_LBL_SELECT,
    MSF_STR_ID_UILIST_LBL_OPTION,
    MSF_STR_ID_UILIST_LBL_BACK,
    MSF_STR_ID_UILIST_LBL_CANCEL,
    MSF_STR_ID_UI_COMP_TITLE_ERROR,
    MSF_STR_ID_UCCL_EMPTY_TITLE,
    MSF_STR_ID_UCCL_EMPTY_TEXT,
    MSF_STR_ID_UCDG_MESSAGE_ACTION_OK,
    MSF_STR_ID_UCDG_PROMPT_ACTION_OK,
    MSF_STR_ID_UCDG_PROMPT_ACTION_CANCEL,
    MSF_STR_ID_UCSL_ACTION_OK,
    MSF_STR_ID_UCSL_ACTION_CANCEL,
    MSF_STR_ID_UCFL_TEXT_ROOT_FOLDER,
    MSF_STR_ID_UCFL_SIZE,
    MSF_STR_ID_UCFL_CANNOT_OPEN_CONTENT,
    MSF_STR_ID_UCFL_CANNOT_OPEN_FOLDER,
    MSF_STR_ID_CMD_ACTION_YES,
    MSF_STR_ID_CMD_ACTION_NO,
    MSF_STR_ID_CMD_ACTION_OPTION,
    MSF_STR_ID_CMD_ACTION_SELECT,
    MSF_STR_ID_CMD_ACTION_BACK,
    MSF_STR_ID_CMD_ACTION_DELETE,
    MSF_STR_ID_CMD_ACTION_CANCEL,
    MSF_STR_ID_CMD_ACTION_UP,
    MSF_STR_ID_CMD_ACTION_PGUP,
    MSF_STR_ID_CMD_ACTION_DOWN,
    MSF_STR_ID_CMD_ACTION_PGDOWN,
    MSF_STR_ID_CMD_ACTION_LEFT,
    MSF_STR_ID_CMD_ACTION_PREV,
    MSF_STR_ID_CMD_ACTION_RIGHT,
    MSF_STR_ID_CMD_ACTION_NEXT,
    MSF_STR_ID_CMD_ACTION_PLAY,
    MSF_STR_ID_CMD_ACTION_STOP,
    MSF_STR_ID_CMD_ACTION_PAUSE,
    MSF_STR_ID_CMD_ACTION_CHECK,
    MSF_STR_ID_CMD_ACTION_UNCHECK,
    MSF_STR_ID_CMD_ACTION_CALL,
    MSF_STR_ID_CMD_ACTION_EDIT,
    MSF_STR_ID_CMD_ACTION_CLEAR,
    MSF_STR_ID_CMD_ACTION_REWIND,
    MSF_STR_ID_CMD_ACTION_REWIND_STOP,
    MSF_STR_ID_CMD_ACTION_FORWARD,
    MSF_STR_ID_CMD_ACTION_FORWARD_STOP,
    MSF_STR_ID_ACT_IMPL_SAVE,
    MSF_STR_ID_ACT_IMPL_OPEN,
    MSF_STR_ID_ACT_IMPL_DISPLAY,
    MSF_STR_ID_ACT_IMPL_PLAY,
    MSF_STR_ID_ACT_IMPL_LOAD_URL,
    MSF_STR_ID_ACT_IMPL_SET,
    MSF_STR_ID_ACT_IMPL_SET_SCREENSAVER,
    MSF_STR_ID_ACT_IMPL_SET_GREETING,
    MSF_STR_ID_ACT_IMPL_SET_WALLPAPER,
    MSF_STR_ID_ACT_IMPL_SET_RINGTONE,
    MSF_STR_ID_ACT_IMPL_SEND_AS,
    MSF_STR_ID_ACT_IMPL_MSG,
    MSF_STR_ID_ACT_IMPL_EMAIL,
    MSF_STR_ID_ACT_IMPL_BLUETOOTH,
    MSF_STR_ID_ACT_IMPL_INFRARED,
    MSF_STR_ID_ACT_IMPL_USB,
    MSF_STR_ID_ACT_IMPL_POSTCARD,
    MSF_STR_ID_ACT_IMPL_CALL,
    MSF_STR_ID_ACT_IMPL_VIDEO_CALL,
    MSF_STR_ID_ACT_IMPL_ADD_TO_CALENDAR,
    MSF_STR_ID_ACT_IMPL_ADD_TO_CONTACT,
    MSF_STR_ID_ACT_IMPL_ADD_BOOKMARK,
    MSF_STR_ID_ACT_IMPL_UPLOAD_TO_ALBUM,
    MSF_STR_ID_ACT_IMPL_MOVE_TO_ALBUM,
    MSF_STR_ID_ACT_IMPL_COPY_TO_ALBUM,
    MSF_STR_ID_ACT_IMPL_GET_PHOTO,
    MSF_STR_ID_ACT_IMPL_GET_AUDIO,
    MSF_STR_ID_ACT_IMPL_GET_VIDEO,
    MSF_STR_ID_ACT_IMPL_PICK_FROM_CONTACT,
    MSF_STR_ID_ACT_IMPL_SET_SKIN,
    MSF_STR_ID_ACT_IMPL_MT1_TEST1,
    MSF_STR_ID_ACT_IMPL_MT1_TEST2,
    MSF_STR_ID_ACT_IMPL_MT1_TEST3,
    MSF_STR_ID_DLG_ACTION_SAVE_HERE,
    MSF_STR_ID_DLG_ACTION_OPEN,
    MSF_STR_ID_DLG_SWITCH_TO_MEMCARD,
    MSF_STR_ID_DLG_SWITCH_TO_HANDSET,
    MSF_STR_ID_DLG_SWITCH_TO_MULTI,
    MSF_STR_ID_DLG_ACTION_MINIMIZE,
    MSF_STR_ID_DLG_CMD_MULTI_CHECK_ALL,
    MSF_STR_ID_DLG_CMD_MULTI_UNCHECK_ALL,
    MSF_STR_ID_DLG_CMD_MULTI_OK,
    MSF_STR_ID_DLG_CMD_MULTI_BACK,
    MSF_STR_ID_DLG_TITLE_INFORMATION,
    MSF_STR_ID_DLG_TITLE_ERROR,
    MSF_STR_ID_DLG_TITLE_CREATE_FOLDER,
    MSF_STR_ID_DLG_CREATE_FOLDER_DELAYED,
    MSF_STR_ID_DLG_CREATE_FOLDER_NOT_ALLOWED,
    MSF_STR_ID_DLG_ENTER_FOLDER_NAME,
    MSF_STR_ID_DLG_PROMPT_NAME,
    MSF_STR_ID_DLG_TITLE_FOLDER_EXISTS,
    MSF_STR_ID_DLG_FOLDER_EXISTS,
    MSF_STR_ID_DLG_TITLE_FOLDER_NAME_INVALID,
    MSF_STR_ID_DLG_FOLDER_NAME_INVALID,
    MSF_STR_ID_DLG_TITLE_NO_MEM_CARD,
    MSF_STR_ID_DLG_TEXT_NO_MEM_CARD,
    MSF_STR_ID_DLG_TITLE_MEM_CARD_READ_ONLY,
    MSF_STR_ID_DLG_TEXT_MEM_CARD_READ_ONLY,
    MSF_STR_ID_DLG_TITLE_MEM_CARD_NO_PERMISSION,
    MSF_STR_ID_DLG_TEXT_MEM_CARD_NO_PERMISSION,
    MSF_STR_ID_DLG_SAVE_NO_PERMISSION,
    MSF_STR_ID_DLG_TITLE_SAVE_FILE,
    MSF_STR_ID_DLG_ENTER_FILE_NAME,
    MSF_STR_ID_DLG_TITLE_EXISTS,
    MSF_STR_ID_DLG_TITLE_FILE_NAME_INVALID,
    MSF_STR_ID_DLG_FILE_NAME_INVALID,
    MSF_STR_ID_DLG_TITLE_NO_SLOTS,
    MSF_STR_ID_DLG_NO_SLOTS_FREE,
    MSF_STR_ID_DLG_NO_SLOTS_AT_ALL,
    MSF_STR_ID_DLG_TITLE_NOT_ENOUGH_SPACE,
    MSF_STR_ID_DLG_NOT_ENOUGH_FREE_SPACE,
    MSF_STR_ID_DLG_NOT_ENOUGH_TOTAL_SPACE,
    MSF_STR_ID_DLG_ERROR_CANNOT_SAVE_FILE,
    MSF_STR_ID_DLG_ERROR_CREATE_FOLDER,
    MSF_STR_ID_DLG_ERROR_REPLACE_FILE,
    MSF_STR_ID_DLG_ERROR_UNEXPECTED,
    MSF_STR_ID_DLG_SAVE_CANCELED,
    MSF_STR_ID_DLG_NO_FILES,
    MSF_STR_ID_DLG_MULTI_NO_ELEM_SEL,
    MSF_STR_ID_SAS_TITLE_BAR,
    MSF_STR_ID_SAS_BAR_TEXT,
    MSF_STR_ID_SAS_KBYTES_SAVED,
    MSF_STR_ID_SAS_MBYTES_SAVED,
    MSF_STR_ID_SAS_TITLE_INFORMATION,
    MSF_STR_ID_SAS_TITLE_ERROR,
    MSF_STR_ID_SAS_TITLE_CANNOT_SAVE_FILE,
    MSF_STR_ID_SAS_TITLE_NOT_ENOUGH_SPACE,
    MSF_STR_ID_SAS_ERROR_FULL_FREE,
    MSF_STR_ID_DEL_OPEN,
    MSF_STR_ID_DEL_DELETE,
    MSF_STR_ID_DEL_REMOVE_PROTECTION,
    MSF_STR_ID_DEL_QUOTA_INFO,
    MSF_STR_ID_DEL_MULTIPLE_SELECT,
    MSF_STR_ID_DEL_DELETE_SELECTED,
    MSF_STR_ID_DEL_CHECK_ALL,
    MSF_STR_ID_DEL_UNCHECK_ALL,
    MSF_STR_ID_DEL_TITLE_INFORMATION,
    MSF_STR_ID_DEL_TITLE_FREE_SPACE,
    MSF_STR_ID_DEL_TITLE_STOP_FREEING_SPACE,
    MSF_STR_ID_DEL_TITLE_REMOVE_PROTECTION,
    MSF_STR_ID_DEL_TITLE_DELETE_FILE,
    MSF_STR_ID_DEL_TITLE_DELETE_FILES,
    MSF_STR_ID_DEL_TITLE_CONTINUE,
    MSF_STR_ID_DEL_BYTES,
    MSF_STR_ID_DEL_KBYTES,
    MSF_STR_ID_DEL_MBYTES,
    MSF_STR_ID_DEL_FREE_NOW,
    MSF_STR_ID_DEL_REMOVE,
    MSF_STR_ID_DEL_REMOVE_MULTI,
    MSF_STR_ID_DEL_REMOVE_PROTECTION_DLG,
    MSF_STR_ID_DEL_NEED,
    MSF_STR_ID_DEL_SPACE,
    MSF_STR_ID_DEL_FREED,
    MSF_STR_ID_DEL_CONTINUE,
    MSF_STR_ID_DEL_STOP,
    MSF_STR_ID_DAY_MONDAY,
    MSF_STR_ID_DAY_TUESDAY,
    MSF_STR_ID_DAY_WEDNESDAY,
    MSF_STR_ID_DAY_THURSDAY,
    MSF_STR_ID_DAY_FRIDAY,
    MSF_STR_ID_DAY_SATURDAY,
    MSF_STR_ID_DAY_SUNDAY,
    MSF_STR_ID_MONTH_JANUARY,
    MSF_STR_ID_MONTH_FEBRUARY,
    MSF_STR_ID_MONTH_MARCH,
    MSF_STR_ID_MONTH_APRIL,
    MSF_STR_ID_MONTH_MAY,
    MSF_STR_ID_MONTH_JUNE,
    MSF_STR_ID_MONTH_JULY,
    MSF_STR_ID_MONTH_AUGUST,
    MSF_STR_ID_MONTH_SEPTEMBER,
    MSF_STR_ID_MONTH_OCTOBER,
    MSF_STR_ID_MONTH_NOVEMBER,
    MSF_STR_ID_MONTH_DECEMBER,
    MSF_STR_ID_ASCII_TO_UTF8,
    MSF_STR_ID_LATIN1_TO_UTF8,
    MSF_STR_ID_UTF16_TO_UTF8,
    MSF_STR_ID_UCS2_TO_UTF8,
    MSF_STR_ID_LATIN2_TO_UTF8,
    MSF_STR_ID_HEBREW_TO_UTF8,
    MSF_STR_ID_SHIFT_JIS_TO_UTF8,
    MSF_STR_ID_UTF8_TO_UTF8,
    MSF_STR_ID_BIG5_TO_UTF8,
    MSF_STR_ID_HKSCS_TO_UTF8,
    MSF_STR_ID_EUC_JP_TO_UTF8,
    MSF_STR_ID_LATIN3_TO_UTF8,
    MSF_STR_ID_LATIN4_TO_UTF8,
    MSF_STR_ID_CYRILLIC_TO_UTF8,
    MSF_STR_ID_ARABIC_TO_UTF8,
    MSF_STR_ID_GREEK_TO_UTF8,
    MSF_STR_ID_LATIN5_TO_UTF8,
    MSF_STR_ID_LATIN6_TO_UTF8,
    MSF_STR_ID_EUC_KR_TO_UTF8,
    MSF_STR_ID_THAI_TO_UTF8,
    MSF_STR_ID_LATIN7_TO_UTF8,
    MSF_STR_ID_LATIN8_TO_UTF8,
    MSF_STR_ID_LATIN9_TO_UTF8,
    MSF_STR_ID_LATIN10_TO_UTF8,
    MSF_STR_ID_WIN_1250_TO_UTF8,
    MSF_STR_ID_WIN_1251_TO_UTF8,
    MSF_STR_ID_WIN_1252_TO_UTF8,
    MSF_STR_ID_WIN_1253_TO_UTF8,
    MSF_STR_ID_WIN_1254_TO_UTF8,
    MSF_STR_ID_WIN_1255_TO_UTF8,
    MSF_STR_ID_WIN_1256_TO_UTF8,
    MSF_STR_ID_WIN_1257_TO_UTF8,
    MSF_STR_ID_WIN_1258_TO_UTF8,
    MSF_STR_ID_WIN_874_TO_UTF8,
    MSF_STR_ID_GB2312_TO_UTF8,
    MSF_STR_ID_GB18030_TO_UTF8,
    MSF_STR_ID_ISO_2022_JP_TO_UTF8,
    MSF_STR_ID_SAS_ERROR_PATH,    
	/* BRS */
	BRS_STR_ID_BUTTON,                                  
	BRS_STR_ID_CACHE_NOTIFICATION,                      
	BRS_STR_ID_CACHE_NOTIFICATION_OBJECT_1,             
	BRS_STR_ID_CACHE_NOTIFICATION_OBJECT_2,             
	BRS_STR_ID_CACHE_TITLE,                             
	BRS_STR_ID_CONFIRM_TITLE,                           
	BRS_STR_ID_ALERT_TITLE,
	BRS_STR_ID_DOWNLOAD_FAILED_TITLE,                   
	BRS_STR_ID_ENABLE_SCRIPT_DLG_MSG,                   
	BRS_STR_ID_ENABLE_SCRIPT_DLG_TITLE,                 
	BRS_STR_ID_HTTP_TO_HTTPS_DLG_MSG,                   
	BRS_STR_ID_HTTPS_TO_HTTP_DLG_MSG,                   
	BRS_STR_ID_INPUT_TITLE,                             
	BRS_STR_ID_INVALID_INPUT,                           
	BRS_STR_ID_JAM_CONFIRM,                             
	BRS_STR_ID_NOT_SUPPORT_FILE_UPLOAD,
	BRS_STR_ID_NO_MIME_MSG_1,                           
	BRS_STR_ID_NO_MIME_MSG_2,                           
	BRS_STR_ID_NO_MIME_MSG_3,                           
	BRS_STR_ID_NO_MIME_MSG_4,                           
	BRS_STR_ID_REDIRECT_POST,                           
	BRS_STR_ID_RESEND_POST,                             
	BRS_STR_ID_RESET,                                   
	BRS_STR_ID_SAS_DOWNLOAD_CANCEL,                     
	BRS_STR_ID_SAS_DOWNLOAD_ERROR,                      
	BRS_STR_ID_SAS_DOWNLOAD_SUCCESS,                    
	BRS_STR_ID_SAVE_COMPLETE_TITLE,                     
	BRS_STR_ID_SCRIPT_DISABLED_NOTIFICATION,            
	BRS_STR_ID_SECURITY,                                
	BRS_STR_ID_SUBMIT,                                  
	BRS_STR_ID_SUI_2WAY_NAVIGATION,                     
	BRS_STR_ID_SUI_4WAY_NAVIGATION,                     
	BRS_STR_ID_SUI_FRAMES_AS_LINKS,                     
	BRS_STR_ID_SUI_REND_FULL,                           
	BRS_STR_ID_SUI_REND_NARROW,                         
	BRS_STR_ID_SUI_REND_TEXT,                           
	BRS_STR_ID_SUI_REND_WRAP,                           
	BRS_STR_ID_SUI_SCROLLING_NAVIGATION,                
	BRS_STR_ID_SUI_THUMBNAIL_CREATING,                  
	BRS_STR_ID_SUI_THUMBNAIL_FRAME_PAGE,       
	BRS_STR_ID_SUI_THUMBNAIL_OUT_OF_MEMORY,         
	BRS_STR_ID_SUI_THUMBNAIL_SMALL_PAGE,                
	BRS_STR_ID_SUI_THUMBNAIL_LARGE_PAGE,
	BRS_STR_ID_SUI_ZOOM,               
	BRS_STR_ID_SUI_FONT_SIZE,      
	BRS_STR_ID_UNHANDLED_CONTENT_TYPE,                  
	BRS_STR_ID_UNSECURE_CONTENT,                        
	BRS_STR_ID_WML_SCRIPT_ALERT_TITLE,                  
	BRS_STR_ID_WML_SCRIPT_CONFIRM_TITLE = BRS_STR_ID_WML_SCRIPT_ALERT_TITLE,                
	BRS_STR_ID_WML_SCRIPT_PROMPT_TITLE = BRS_STR_ID_WML_SCRIPT_ALERT_TITLE,
	BRS_STR_ID_JS_ERR,
    BRS_STR_ID_JS_INTERNAL_ERR,
    BRS_STR_ID_JS_EVALERR,
    BRS_STR_ID_JS_RANGEERR,
    BRS_STR_ID_JS_REFERENCEERR,
    BRS_STR_ID_JS_SYNTAXERR,
    BRS_STR_ID_JS_TYPEERR,
    BRS_STR_ID_JS_URIERR,
    BRS_STR_ID_JS_LINE,
    BRS_STR_ID_JS_INLINE_SCRIPT,
    BRS_STR_ID_JS_BUF_CHAR,
    BRS_STR_ID_JS_BUF_CHAR_POS,
    BRS_STR_ID_JS_ERR_REQUEST_ABORTED,
    BRS_STR_ID_JS_ERR_HTTP_REPLY,
    BRS_STR_ID_JS_ERR_CHAR_ENCODING,
    BRS_STR_ID_JS_ERR_NOT_DEF,
    BRS_STR_ID_JS_ERR_EMRS_PERMISSION_DENIED,
    BRS_STR_ID_JS_ERR_STREAM_ERROR,
    BRS_STR_ID_JS_ERR_PIPE_CLOSED,
    BRS_STR_ID_JS_CALLED_FROM,
    BRS_STR_ID_JS_SIZE_TOO_LARGE,
    BRS_STR_ID_JS_EXECUTION_TIME_TOO_LONG,
    /* MMS */
    MMS_STR_EMPTY_STRING,
    MMS_STR_ID_READ_REPORT,
    MMS_STR_ID_YOUR_MESSAGE_BEEN_READ,
    MMS_STR_ID_RR_UNKNOWN_TO,
    /* MCL */
    MCL_STR_ID_STATUS_ERROR_CODES,
    /* PRS */
    PRS_STR_ID_ENTER_PIN_TITLE,
    PRS_STR_ID_ACCEPT_DOC_TITLE,
    PRS_STR_ID_ACCEPT_DOC_TEXT,
    PRS_STR_ID_SETTINGS_ADDED_TITLE,
    PRS_STR_ID_SETTINGS_ADDED_TEXT,
    PRS_STR_ID_GENERIC_ERROR_TITLE,
    PRS_STR_ID_GENERIC_ERROR_TEXT,
    PRS_STR_ID_ACCESSING_CPS,
    PRS_STR_ID_WRITING_TO_CPS,
    PRS_STR_ID_SETTINGS_UPDATED_TITLE,
    PRS_STR_ID_SETTINGS_UPDATED_TEXT,
    PRS_STR_ID_COMPARING_SETTINGS,
    PRS_STR_ID_ACCEPT_UPDATE_TITLE,
    PRS_STR_ID_ACCEPT_UPDATE_TEXT,
    PRS_STR_ID_INCORRECT_PIN_TITLE,
    PRS_STR_ID_INCORRECT_PIN_TEXT,
    PRS_STR_ID_UPDATE_PROFILE_TITLE,
    PRS_STR_ID_UPDATE_PROFILE_TEXT,
    PRS_STR_ID_ENTER_PIN_TEXT,
    PRS_STR_ID_SAVED,
    PRS_STR_ID_PERCENT,
    PRS_STR_ID_ACCEPT_NO_AUTHENTICATION,
    PRS_STR_ID_AUTH_FAILED_TITLE,
    PRS_STR_ID_AUTH_FAILED_TEXT,
    PRS_STR_ID_INVALID_DOC_TITLE,
    PRS_STR_ID_INVALID_DOC_TEXT,
    PRS_STR_ID_PARSE_FAILED_TITLE,
    PRS_STR_ID_PARSE_FAILED_TEXT,
    PRS_STR_ID_MEMORY_LIMIT_EXCEEDED_TITLE,
    PRS_STR_ID_MEMORY_LIMIT_EXCEEDED_TEXT,
    /* PHS */
    PHS_STR_ID_UNKNOWN_SENDER,
    PHS_STR_ID_ACCEPT_MSG,
    PHS_STR_ID_DECLINE_MSG,
    PHS_STR_ID_ADD_TO_WHITELIST,
    PHS_STR_ID_ADD_TO_BLACKLIST,
    PHS_STR_ID_PUSH_TYPE_CO,
    PHS_STR_ID_PUSH_TYPE_SIR,
    PHS_STR_ID_SIR_CONFIRM_MSG,
    /* STK */
    STK_STR_ID_CANCEL,
    STK_STR_ID_SAVE_NONE,
    /* SES */
    SES_STR_ID_MENU_VIEW_CERTIFICATES_ITEM,
    SES_STR_ID_MENU_VIEW_CONTRACTS_ITEM,
    SES_STR_ID_MENU_VIEW_SESSION_INFO_ITEM,
    SES_STR_ID_MENU_VIEW_CURRENT_CERTIFICATE_ITEM,
    SES_STR_ID_MENU_CHANGE_AUTH_PIN_ITEM,
    SES_STR_ID_MENU_CHANGE_SIGN_PIN_ITEM,
    SES_STR_ID_MENU_UNBLOCK_AUTH_PIN_ITEM,
    SES_STR_ID_MENU_UNBLOCK_SIGN_PIN_ITEM,
    SES_STR_ID_TITLE_MAIN_MENU,
    SES_STR_ID_TITLE_MISSING_KEY,
    SES_STR_ID_TITLE_STORED_CONTRACTS,
    SES_STR_ID_TITLE_CONTRACT_DETAILS,
    SES_STR_ID_TITLE_CONFIRM,
    SES_STR_ID_TITLE_GEN_PIN,
    SES_STR_ID_TITLE_HASH,
    SES_STR_ID_TITLE_CERT_DETAILS,
    SES_STR_ID_TITLE_STORE,
    SES_STR_ID_TITLE_SHOW_CERT_NAMES,
    SES_STR_ID_TITLE_CHANGE_PIN,
    SES_STR_ID_TITLE_ENTER_PIN,
    SES_STR_ID_TITLE_CHOOSE_CERT,
    SES_STR_ID_TITLE_CHOOSE_CERT_PUB_KEY,
    SES_STR_ID_TITLE_VALIDATION_ERROR,
    SES_STR_ID_TITLE_CLIENT_CERT,
    SES_STR_ID_TITLE_ERROR,
    SES_STR_ID_TITLE_OVERWRITE,
    SES_STR_ID_TITLE_MISSING_CERT,
    SES_STR_ID_TITLE_STORE_SUCCEEDED,
    SES_STR_ID_TITLE_DELETE,
    SES_STR_ID_TITLE_PIN_CHANGED,
    SES_STR_ID_TITLE_UNBLOCK_AUTH_PIN,
    SES_STR_ID_TITLE_UNBLOCK_SIGN_PIN,
    SES_STR_ID_TITLE_INVALID_PIN,
    SES_STR_ID_TITLE_INVALID_PUK,
    SES_STR_ID_TITLE_STORE_ERROR,
    SES_STR_ID_TITLE_DELETE_ERROR,
    SES_STR_ID_TITLE_SIGN_FAILED,
    SES_STR_ID_TITLE_SIGN_SUCCEEDED,
    SES_STR_ID_TITLE_PIN_BLOCKED,
    SES_STR_ID_TITLE_PIN_UNBLOCKED,
    SES_STR_ID_TITLE_PUK_BLOCKED,
    SES_STR_ID_TITLE_DIMMED,
    SES_STR_ID_TITLE_CURRENT_CERT,
    SES_STR_ID_TITLE_SESSION_INFO,
    SES_STR_ID_TITLE_EMPTY_LIST,
    SES_STR_ID_CONFIRM_STORE,
    SES_STR_ID_CONFIRM_STORE_NOT_VERIFIED,
    SES_STR_ID_CONFIRM_STORE_SAME,
    SES_STR_ID_CONFIRM_STORE_NEWER,
    SES_STR_ID_CONFIRM_STORE_OLDER,
    SES_STR_ID_CONFIRM_CONNECT,
    SES_STR_ID_CONFIRM_CONNECT_TEMP,
    SES_STR_ID_CONFIRM_CONNECT_ALWAYS,
    SES_STR_ID_CONFIRM_VIEW_CERT,
    SES_STR_ID_CONFIRM_CONNECT_NO_USER,
    SES_STR_ID_CONFIRM_DELETE_CERT,
    SES_STR_ID_CONFIRM_DELETE_CONTRACT,
    SES_STR_ID_CONFIRM_SIGN_TEXT,
    SES_STR_ID_CONFIRM_UNBLOCK_PIN1,
    SES_STR_ID_CONFIRM_UNBLOCK_PIN2,
    SES_STR_ID_CHOOSE_CERT,
    SES_STR_ID_CANCEL,
    SES_STR_ID_BACK,
    SES_STR_ID_DELETE,
    SES_STR_ID_VIEW,
    SES_STR_ID_STORE,
    SES_STR_ID_PROMPT_PIN_AUTH_PUK,
    SES_STR_ID_PROMPT_PIN_SIGN_PUK,
    SES_STR_ID_PROMPT_PIN_ENTER,
    SES_STR_ID_PROMPT_PIN_ENTER_AGAIN,
    SES_STR_ID_PROMPT_PIN_OPEN_WIM,
    SES_STR_ID_PROMPT_PIN_CONNECT,
    SES_STR_ID_PROMPT_PIN_SIGN_TEXT,
    SES_STR_ID_PROMPT_PIN_STORE_CERT,
    SES_STR_ID_PROMPT_PIN_DELETE_CERT,
    SES_STR_ID_PROMPT_PIN_DELETE_CONTRACT,
    SES_STR_ID_PROMPT_PIN_DELETE_AUTH_KEYS,
    SES_STR_ID_PROMPT_PIN_DELETE_SIGN_KEYS,
    SES_STR_ID_PROMPT_PIN_CHANGE_AUTH,
    SES_STR_ID_PROMPT_PIN_CHANGE_SIGN,
    SES_STR_ID_PROMPT_PIN_GENERATE_AUTH_KEY,
    SES_STR_ID_PROMPT_PIN_GENERATE_SIGN_KEY,
    SES_STR_ID_PROMPT_HASH_ENTER,
    SES_STR_ID_PROMPT_CERT_ENTER_NAME,
    SES_STR_ID_PROMPT_NUM_TRIES_LEFT,
    SES_STR_ID_PROMPT_LAST_PIN_TRY,
    SES_STR_ID_INFO_CERT_STORED,
    SES_STR_ID_INFO_CERT_NOT_STORED,
    SES_STR_ID_INFO_CERT_DELETED,
    SES_STR_ID_INFO_CERT_NOT_DELETED,
    SES_STR_ID_INFO_CERT_NOT_SHOWN,
    SES_STR_ID_INFO_CONTRACT_DELETED,
    SES_STR_ID_INFO_CONTRACT_NOT_DELETED,
    SES_STR_ID_INFO_CONTRACT_NOT_SHOWN,
    SES_STR_ID_INFO_AUTH_PIN_CHANGED,
    SES_STR_ID_INFO_SIGN_PIN_CHANGED,
    SES_STR_ID_INFO_AUTH_PIN_UNBLOCKED,
    SES_STR_ID_INFO_SIGN_PIN_UNBLOCKED,
    SES_STR_ID_INFO_SIGN_SUCCEEDED,
    SES_STR_ID_INFO_NO_CERTS,
    SES_STR_ID_INFO_NO_CONTRACTS,
    SES_STR_ID_SESS_CONNECTION_TYPE,
    SES_STR_ID_SESS_SSL,
    SES_STR_ID_SESS_TLS,
    SES_STR_ID_SESS_WTLS,
    SES_STR_ID_SESS_SERVER_AUTH,
    SES_STR_ID_SESS_CLIENT_AUTH,
    SES_STR_ID_SESS_YES,
    SES_STR_ID_SESS_NO,
    SES_STR_ID_SESS_HMAC_ALG,
    SES_STR_ID_SESS_SHA1,
    SES_STR_ID_SESS_MD5,
    SES_STR_ID_SESS_HMAC_KEY_LEN,
    SES_STR_ID_SESS_ENCR_ALG,
    SES_STR_ID_SESS_ENCR_NULL,
    SES_STR_ID_SESS_ENCR_RC5,
    SES_STR_ID_SESS_ENCR_RC5_40,
    SES_STR_ID_SESS_ENCR_RC5_56,
    SES_STR_ID_SESS_ENCR_RC5_64,
    SES_STR_ID_SESS_ENCR_3DES,
    SES_STR_ID_SESS_ENCR_RC4_40,
    SES_STR_ID_SESS_ENCR_RC4_128,
    SES_STR_ID_SESS_ENCR_DES_40,
    SES_STR_ID_SESS_ENCR_DES,
    SES_STR_ID_SESS_ENCR_RC4_56,
    SES_STR_ID_SESS_ENCR_AES_128,
    SES_STR_ID_SESS_ENCR_KEY_LEN,
    SES_STR_ID_SESS_KEY_EXCH_ALG,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_NULL,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_SHARED_SECRET,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_DH_ANON,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_DH_ANON_512,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_DH_ANON_768,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA_ANON,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA_ANON_512,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA_ANON_768,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA_512,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_RSA_768,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_ECDH_ANON,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_ECDH_ANON_113,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_ECDH_ANON_131,
    SES_STR_ID_SESS_WTLS_KEY_EXCH_ECDH_ECDSA,
    SES_STR_ID_SESS_TLS_KEY_EXCH_NULL,
    SES_STR_ID_SESS_TLS_KEY_EXCH_RSA,
    SES_STR_ID_SESS_TLS_KEY_EXCH_RSA_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_DSS_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_DSS,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_RSA_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_RSA,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DHE_DSS_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DHE_DSS,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DHE_RSA_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DHE_RSA,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_ANON_EXPORT,
    SES_STR_ID_SESS_TLS_KEY_EXCH_DH_ANON,
    SES_STR_ID_SESS_TLS_KEY_EXCH_RSA_EXPORT1024,
    SES_STR_ID_SESS_KEY_EXCH_KEY_LEN,
    SES_STR_ID_CERT_LOCATION,
    SES_STR_ID_CERT_PHONE,
    SES_STR_ID_CERT_SIM,
    SES_STR_ID_CERT_VAL_NOT_BEF,
    SES_STR_ID_CERT_VAL_NOT_AFT,
    SES_STR_ID_CERT_ISSUER,
    SES_STR_ID_CERT_SUBJECT,
    SES_STR_ID_CERT_SERIAL_NO,
    SES_STR_ID_CERT_FINGERPRINT,
    SES_STR_ID_CONTRACT,
    SES_STR_ID_SIGNATURE,
    SES_STR_ID_TIME,
    SES_STR_ID_ERR_PIN_TOO_LONG,
    SES_STR_ID_ERR_PIN_TOO_SHORT,
    SES_STR_ID_ERR_PIN_MISMATCH,
    SES_STR_ID_ERR_PIN_FALSE,
    SES_STR_ID_ERR_HASH_FALSE,
    SES_STR_ID_ERR_PIN1_LOCKED,
    SES_STR_ID_ERR_PIN2_LOCKED,
    SES_STR_ID_ERR_INVALID_KEY,
    SES_STR_ID_ERR_KEY_LENGTH,
    SES_STR_ID_ERR_UNKNOWN_CERTIFICATE_TYPE,
    SES_STR_ID_ERR_NO_MATCHING_ROOT_CERTIFICATE,
    SES_STR_ID_ERR_BAD_CERTIFICATE,
    SES_STR_ID_ERR_MISSING_CERTIFICATE,
    SES_STR_ID_ERR_NOT_FOUND,
    SES_STR_ID_ERR_INVALID_COMMON_NAME,
    SES_STR_ID_ERR_MISSING_PUK,
    SES_STR_ID_ERR_WRONG_PUK,
    SES_STR_ID_ERR_MISSING_AUT_KEY_OPEN_WIM,
    SES_STR_ID_ERR_MISSING_KEY_CONNECT,
    SES_STR_ID_ERR_MISSING_KEY_STORE_CERT,
    SES_STR_ID_ERR_MISSING_KEY_DELETE_CERT,
    SES_STR_ID_ERR_MISSING_KEY_DELETE_CONTRACT,
    SES_STR_ID_ERR_MISSING_KEY_CHANGE_AUTH,
    SES_STR_ID_ERR_MISSING_KEY_CHANGE_SIGN,
    SES_STR_ID_ERR_MISSING_NR_KEY_SIGN_TEXT,
    SES_STR_ID_ERR_PRIV_KEY_NOT_FOUND,
    SES_STR_ID_ERR_WIM_NOT_INITIALISED,
    SES_STR_ID_ERR_INTERNAL_ERROR,
    SES_STR_ID_ERR_SIGN_OTHER_ERROR,
    SES_STR_ID_ERR_SIGN_MISSING_CERTIFICATE,
    SES_STR_ID_ERR_CA_CERTIFICATE_EXPIRED,
    SES_STR_ID_ERR_CERTIFICATE_EXPIRED,
    SES_STR_ID_ERR_IS_ROOT_CERTIFICATE,
    SES_STR_ID_ERR_MISSING_GATEWAY_CERT,
    SES_STR_ID_ERR_PUK1_LOCKED,
    SES_STR_ID_ERR_PUK2_LOCKED,
    SES_STR_ID_ERR_PUKS_LOCKED,
    SES_STR_ID_ERR_FILE_SYSTEM,
    SES_STR_ID_ERR_GENERAL_ERROR,
    SES_STR_ID_ERR_REACHED_USER_CERT_LIMIT,
    SES_STR_ID_ERR_NO_AUTH_PIN,
    SES_STR_ID_ERR_NO_SIGN_PIN,
    SES_STR_ID_ERR_AUTH_PIN_BLOCKED,
    SES_STR_ID_ERR_SIGN_PIN_BLOCKED,
    SES_STR_ID_ERR_NO_AUTH_PUK,
    SES_STR_ID_ERR_NO_SIGN_PUK,
    SES_STR_ID_ERR_AUTH_PUK_BLOCKED,
    SES_STR_ID_ERR_SIGN_PUK_BLOCKED,
    SES_STR_ID_ERR_SESSION_INFO_MISSING,
    SES_STR_ID_ERR_SESSION_CERT_MISSING,
    SES_STR_ID_ERR_AUTH_PIN_NOT_BLOCKED,
    SES_STR_ID_ERR_SIGN_PIN_NOT_BLOCKED,
    SES_STR_ID_ERR_NO_CERTIFICATES,
    SES_STR_ID_ERR_NO_CONTRACTS,
    SES_STR_ID_ERR_LOCKED_CERTIFICATE,
        
    WIDGET_STR_ID_CLEAR,
    WIDGET_STR_ID_SELECT,
WIDGET_STR_ID_RECEIVED_DRM_RIGHT,
    WIDGET_STR_ID_RECEIVED_MMS_MSGS,
    WIDGET_STR_ID_RECEIVED_JAVA_MMS_MSG,    
    OWL_ADP_STR_ID_INVALID_WCSS__UPPERCASE_A,
    OWL_ADP_STR_ID_INVALID_WCSS__LOWERCASE_A,
    OWL_ADP_STR_ID_INVALID_WCSS__UPPERCASE_X,
    OWL_ADP_STR_ID_INVALID_WCSS__LOWERCASE_X,
    OWL_ADP_STR_ID_INVALID_WCSS__LOWERCASE_N,
    OWL_ADP_STR_ID_INPUT_FORMAT_ERROR,
    /* not really used. just leave a ID. begin */
    OWL_STR_ID_INPUT_MODE_abc,
    OWL_STR_ID_INPUT_MODE_Abc,
    OWL_STR_ID_INPUT_MODE_ABC,
    OWL_STR_ID_INPUT_MODE_Word,
    OWL_STR_ID_INPUT_MODE_WORD,
    OWL_STR_ID_INPUT_MODE_123,
    OWL_STR_ID_INPUT_MODE_word,
    OWL_STR_ID_INPUT_MODE_HEADER,
    OWL_TEXT_KEYPAD_1,
    OWL_TEXT_KEYPAD_2,
    OWL_TEXT_KEYPAD_3,
    OWL_TEXT_KEYPAD_4,
    OWL_TEXT_KEYPAD_5,
    OWL_TEXT_KEYPAD_6,
    OWL_TEXT_KEYPAD_7,
    OWL_TEXT_KEYPAD_8,
    OWL_TEXT_KEYPAD_9,
    OWL_TEXT_KEYPAD_TEXT_0,
    OWL_TEXT_KEYPAD_PHONE_0,
    OWL_TEXT_KEYPAD_TEXT_POUND,
    OWL_TEXT_KEYPAD_PHONE_POUND,
    OWL_TEXT_KEYPAD_PHONE_STAR,
    /* not really used. just leave a ID. end */
    /* OWL Adp */
    OWL_ADP_STR_ID_INPUT_TITLE,
    //OWL_ADP_STR_ID_CANT_SWITCH_INPUT_METHOD,
    WAP_STR_ID_LAST_DUMMY,
    WAP_STR_ID_SUM = WAP_STR_ID_LAST_DUMMY - WAP_STR_ID_BEGIN + 1

    /* add new string ID above this line */
} STR_ID_WAP_ENUM;

/* Image IDs */
typedef enum
{
    WAP_IMAGE_ID_BEGIN = WAP_BASE,
    
#ifdef OBIGO_Q03C

	WAP_IMAGE_SW_PUSH_CSK_VIEW,
    WAP_IMAGE_SW_LIST_NB1,
    WAP_IMAGE_SW_LIST_NB2,
    WAP_IMAGE_SW_LIST_NB3,
    WAP_IMAGE_SW_LIST_NB4,
    WAP_IMAGE_SW_LIST_NB5,
    WAP_IMAGE_SW_LIST_NB6,
    WAP_IMAGE_SW_LIST_NB7,
    WAP_IMAGE_SW_LIST_NB8,
    WAP_IMAGE_SW_LIST_NB9,
    WAP_IMAGE_SW_LIST_NB10,
    WAP_IMAGE_SW_LIST_NB11,
    WAP_IMAGE_SW_LIST_NB12,
    WAP_IMAGE_SW_LIST_NB13,
    WAP_IMAGE_SW_LIST_NB14,
    WAP_IMAGE_SW_LIST_NB15,
    WAP_IMAGE_SW_LIST_NB16,
    WAP_IMAGE_SW_LIST_NB17,
    WAP_IMAGE_SW_LIST_NB18,
    WAP_IMAGE_SW_LIST_NB19,
    WAP_IMAGE_SW_LIST_NB20,
    WAP_IMAGE_SW_LIST_NB21,
    WAP_IMAGE_SW_LIST_NB22,
    WAP_IMAGE_SW_LIST_NB23,
    WAP_IMAGE_SW_LIST_NB24,
    WAP_IMAGE_SW_LIST_NB25,
    WAP_IMAGE_SW_LIST_NB26,
    WAP_IMAGE_SW_LIST_NB27,
    WAP_IMAGE_SW_LIST_NB28,
    WAP_IMAGE_SW_LIST_NB29,
    WAP_IMAGE_SW_LIST_NB30,
#if defined(OBIGO_Q03C_MMS_V01)
    MEA_IMG_EMPTY,
    MEA_IMG_LETTER,
    MEA_IMG_LETTER_JAVA,
    MEA_IMG_LETTER_READ,
    MEA_IMG_LETTER_CREATED,
#ifdef __MMI_MMS_BGSR_SUPPORT__
    MEA_IMG_LETTER_CREATED_FAILED,
    MEA_IMG_LETTER_CREATED_DEFERRED,
#endif /*__MMI_MMS_BGSR_SUPPORT__*/
    MEA_IMG_NOTIF,
    MEA_IMG_RR,
    MEA_IMG_RR_READ,
    MEA_IMG_DR,
    MEA_IMG_DR_READ,
    MEA_IMG_BROKEN_IMAGE,
    MEA_IMG_AUDIO,
    MEA_IMG_SMIL_EDITOR_ATTACHMENT,
    //MEA_IMG_SMIL_EDITOR_FRAME,
    MEA_IMG_SMIL_EDITOR_PIC_ICON,
    MEA_IMG_SMIL_EDITOR_VIDEO_ICON,
    MEA_IMG_SMIL_SLIDING_BAR_REGION,
    //MEA_IMG_AUDIO_ERROR,
    MEA_IMG_IMAGE_ERROR,
    MEA_IMG_VIDEO_ERROR,
    //MEA_IMG_IMAGE_LOCK,
    //MEA_IMG_AUDIO_LOCK,
    MEA_IMG_AUDIO_INPUT,
#ifdef __MMI_MMS_V01_TEMPLATES_SUPPORT__
    MEA_IMG_TEMPLATE,
#endif
    MEA_IMG_FORWARD_LOCK,
    MEA_IMG_FORWARD_LOCK_READ,
    MEA_IMG_PRIO_HIGH,
    MEA_IMG_PRIO_LOW,
#ifdef __DRM_SUPPORT__
    MEA_IMG_IMAGE_DRM,
#endif
    MEA_IMG_LETTER_PRIO_HIGH,
    MEA_IMG_LETTER_PRIO_LOW,
    MEA_IMG_LETTER_READ_PRIO_HIGH,
    MEA_IMG_LETTER_READ_PRIO_LOW,
    MEA_IMG_FORWARD_LOCK_PRIO_HIGH,
    MEA_IMG_FORWARD_LOCK_PRIO_LOW,
    MEA_IMG_FORWARD_LOCK_READ_PRIO_HIGH,
    MEA_IMG_FORWARD_LOCK_READ_PRIO_LOW,
    MEA_IMG_NOTIF_PRIO_HIGH,
    MEA_IMG_NOTIF_PRIO_LOW,

    MEA_IMG_WRITE_MESSAGE,
    MEA_IMG_INBOX,
    MEA_IMG_OUTBOX,
    MEA_IMG_DRAFTS,
    MEA_IMG_SENT,
#ifdef __MMI_MMS_V01_TEMPLATES_SUPPORT__
    MEA_IMG_TEMPLATES,
#endif
        MEA_IMG_SETTINGS,

    MEA_IMG_TITLE_NORMAL,
    //MEA_IMG_TITLE_BUSY,
    MEA_IMG_TITLE_RING,
    //MEA_IMG_TITLE_ATTACHMENT,
    //MEA_IMG_EDITOR_FROM,
    MEA_IMG_EDITOR_TO,
    MEA_IMG_EDITOR_CC,
    MEA_IMG_EDITOR_BCC,
    MEA_IMG_EDITOR_SUBJECT,
    MEA_IMG_EDITOR_CONTENT,
    //MEA_IMG_EDITOR_LAYOUT,
    //MEA_IMG_EDITOR_SIZE,

    MEA_IMG_SET_SEND_PERIOD,
    MEA_IMG_SET_SEND_DR,
    MEA_IMG_SET_SEND_RR,
    MEA_IMG_SET_SEND_PRIORITY,
    MEA_IMG_SET_SEND_SLIDE_DUR,
    MEA_IMG_SET_SEND_DELIVERY_TIME,

    //MEA_IMG_SET_SIG_STATUS,
    //MEA_IMG_SET_SIG_IMAGE,
    //MEA_IMG_SET_SIG_TEXT,

    //MEA_IMG_MOB_UP_ARROW,
    //MEA_IMG_MOB_DOWN_ARROW,

    MEA_IMG_LETTER_JAVA_SIM_1,
    MEA_IMG_LETTER_JAVA_SIM_2,
    MEA_IMG_OUTBOX_SIM_1,
    MEA_IMG_OUTBOX_SIM_2,
    //MEA_IMG_LETTER_CREATED_SIM_1,
    //MEA_IMG_LETTER_CREATED_SIM_2,    
    MEA_IMG_SENT_SIM_1,
    MEA_IMG_SENT_SIM_2,    
    MEA_IMG_FORWARD_LOCK_SIM_1,
    MEA_IMG_FORWARD_LOCK_SIM_2,    
    MEA_IMG_FORWARD_LOCK_PRIO_HIGH_SIM_1,
    MEA_IMG_FORWARD_LOCK_PRIO_HIGH_SIM_2,    
    MEA_IMG_FORWARD_LOCK_PRIO_LOW_SIM_1,    
    MEA_IMG_FORWARD_LOCK_PRIO_LOW_SIM_2,    
    MEA_IMG_FORWARD_LOCK_READ_SIM_1,
    MEA_IMG_FORWARD_LOCK_READ_SIM_2,    
    MEA_IMG_FORWARD_LOCK_READ_PRIO_HIGH_SIM_1,    
    MEA_IMG_FORWARD_LOCK_READ_PRIO_HIGH_SIM_2,        
    MEA_IMG_FORWARD_LOCK_READ_PRIO_LOW_SIM_1,        
    MEA_IMG_FORWARD_LOCK_READ_PRIO_LOW_SIM_2,            
    MEA_IMG_LETTER_SIM_1,
    MEA_IMG_LETTER_SIM_2,    
    MEA_IMG_LETTER_PRIO_HIGH_SIM_1,
    MEA_IMG_LETTER_PRIO_HIGH_SIM_2,    
    MEA_IMG_LETTER_PRIO_LOW_SIM_1,
    MEA_IMG_LETTER_PRIO_LOW_SIM_2,    
    MEA_IMG_LETTER_READ_SIM_1,
    MEA_IMG_LETTER_READ_SIM_2,    
    MEA_IMG_LETTER_READ_PRIO_HIGH_SIM_1,
    MEA_IMG_LETTER_READ_PRIO_HIGH_SIM_2,    
    MEA_IMG_LETTER_READ_PRIO_LOW_SIM_1,
    MEA_IMG_LETTER_READ_PRIO_LOW_SIM_2,    
    MEA_IMG_NOTIF_SIM_1,
    MEA_IMG_NOTIF_SIM_2,    
    MEA_IMG_NOTIF_PRIO_HIGH_SIM_1,
    MEA_IMG_NOTIF_PRIO_HIGH_SIM_2,    
    MEA_IMG_NOTIF_PRIO_LOW_SIM_1,
    MEA_IMG_NOTIF_PRIO_LOW_SIM_2,    
    MEA_IMG_RR_SIM_1,
    MEA_IMG_RR_SIM_2,    
    MEA_IMG_RR_READ_SIM_1,
    MEA_IMG_RR_READ_SIM_2,    
    MEA_IMG_DR_SIM_1,
    MEA_IMG_DR_SIM_2,    
    MEA_IMG_DR_READ_SIM_1,
    MEA_IMG_DR_READ_SIM_2,    
    MEA_IMG_IMAGE_USE_DETAILS_IMAGE_NUMBER,
    MEA_IMG_IMAGE_USE_DETAILS_IMAGE_EMAIL,
    MEA_IMG_IMAGE_USE_DETAILS_IMAGE_URL,
    MEA_IMG_IMAGE_MMS_MENUENTRY,
    //for new mma
    /* MMA */
#ifdef __MMI_MMS_IN_UM__
    MMA_IMG_LOCK_MODE,
    MMA_IMG_LETTER_JAVA,
    MMA_IMG_FORWARD_LOCK_READ_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_READ_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK,
    MMA_IMG_FORWARD_LOCK_READ,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ,
    MMA_IMG_ATTACHMENT_READ_PRIO_HIGH,
    MMA_IMG_ATTACHMENT_READ_PRIO_LOW,
    MMA_IMG_ATTACHMENT_PRIO_HIGH,
    MMA_IMG_ATTACHMENT_PRIO_LOW,
    MMA_IMG_ATTACHMENT,
    MMA_IMG_ATTACHMENT_READ,
    MMA_IMG_LETTER,
    MMA_IMG_LETTER_READ,
    MMA_IMG_LETTER_READ_PRIO_HIGH,
    MMA_IMG_LETTER_READ_PRIO_LOW,
    MMA_IMG_LETTER_PRIO_HIGH,
    MMA_IMG_LETTER_PRIO_LOW,
    MMA_IMG_NOTIF,
    MMA_IMG_LETTER_CREATED,
    MMA_IMG_RR,
    MMA_IMG_RR_READ,
    MMA_IMG_DR,
    MMA_IMG_DR_READ,
    MMA_IMG_CORRUPT,
#endif
    //end MMA
#ifdef __MMI_MMS_V01_TEMPLATES_SUPPORT__
    MMS_IMG_TEMPLATES_01,
    MMS_IMG_TEMPLATES_02,
    MMS_IMG_TEMPLATES_03,
    MMS_IMG_TEMPLATES_04,
    MMS_IMG_TEMPLATES_05,
    MMS_IMG_TEMPLATES_06,
    MMS_IMG_TEMPLATES_07,
    MMS_IMG_TEMPLATES_08,
    MMS_IMG_TEMPLATES_09,
    MMS_IMG_TEMPLATES_10,
#endif
#endif /*OBIGO_Q03C_MMS_V01*/    

#ifdef  __MMI_WAP_CORE_PICTOGRAM_SUPPORT__
    /* OBIGOQ03C PICTOGRAM */
    /* The following order should match up with widget_image.c PICTOGRAM string order */
    WAP_IMG_PICT_CORE_ARROW_UP,
    WAP_IMG_PICT_CORE_ARROW_DOWN,
    WAP_IMG_PICT_CORE_ARROW_RIGHT,
    WAP_IMG_PICT_CORE_ARROW_LEFT,

    WAP_IMG_PICT_CORE_ARROW_UPPERRIGHT,
    WAP_IMG_PICT_CORE_ARROW_UPPERLEFT,
    WAP_IMG_PICT_CORE_ARROW_LOWERRIGHT,
    WAP_IMG_PICT_CORE_ARROW_LOWERLEFT,
    WAP_IMG_PICT_CORE_ARROW_FINGERUP,
    WAP_IMG_PICT_CORE_ARROW_FINGERDOWN,
    WAP_IMG_PICT_CORE_ARROW_FINGERRIGHT,
    WAP_IMG_PICT_CORE_ARROW_FINGERLEFT,

    WAP_IMG_PICT_CORE_BUTTON_1,
    WAP_IMG_PICT_CORE_BUTTON_2,
    WAP_IMG_PICT_CORE_BUTTON_3,
    WAP_IMG_PICT_CORE_BUTTON_4,
    WAP_IMG_PICT_CORE_BUTTON_5,
    WAP_IMG_PICT_CORE_BUTTON_6,
    WAP_IMG_PICT_CORE_BUTTON_7,
    WAP_IMG_PICT_CORE_BUTTON_8,
    WAP_IMG_PICT_CORE_BUTTON_9,
    WAP_IMG_PICT_CORE_BUTTON_0,

    WAP_IMG_PICT_CORE_ACTION_MAKEPHONECALL,
    WAP_IMG_PICT_CORE_ACTION_FIND,
    WAP_IMG_PICT_CORE_ACTION_USERAUTHENTICATION,
    WAP_IMG_PICT_CORE_ACTION_PASSWORD,
    WAP_IMG_PICT_CORE_ACTION_NEXTITEM,
    WAP_IMG_PICT_CORE_ACTION_CLEAR,
    WAP_IMG_PICT_CORE_ACTION_STOP,
    WAP_IMG_PICT_CORE_ACTION_TOP,
    WAP_IMG_PICT_CORE_ACTION_NEXT,
    WAP_IMG_PICT_CORE_ACTION_BACK,

    WAP_IMG_PICT_CORE_MESSAGE_RECEIVE,
    WAP_IMG_PICT_CORE_MESSAGE_SEND,
    WAP_IMG_PICT_CORE_MESSAGE_MESSAGE,
    WAP_IMG_PICT_CORE_MESSAGE_DOCUMENT,
    WAP_IMG_PICT_CORE_MESSAGE_ATTACHMENT,
    WAP_IMG_PICT_CORE_MESSAGE_FOLDER,
    WAP_IMG_PICT_CORE_MESSAGE_INBOX,
    WAP_IMG_PICT_CORE_MESSAGE_OUTBOX,

    WAP_IMG_PICT_CORE_STATE_SECURE,
    WAP_IMG_PICT_CORE_STATE_INSECURE,
    WAP_IMG_PICT_CORE_STATE_COPYRIGHT,
    WAP_IMG_PICT_CORE_STATE_TRADEMARK,
    WAP_IMG_PICT_CORE_STATE_UNDERCONSTRUCTION,
    WAP_IMG_PICT_CORE_STATE_BEGINNER,

    WAP_IMG_PICT_CORE_MEDIA_BOOK,
    WAP_IMG_PICT_CORE_MEDIA_VIDEO,
    WAP_IMG_PICT_CORE_MEDIA_CD,
    WAP_IMG_PICT_CORE_MEDIA_DVD,
    WAP_IMG_PICT_CORE_MEDIA_GAME,
    WAP_IMG_PICT_CORE_MEDIA_RADIO,
    WAP_IMG_PICT_CORE_MEDIA_TV,

    WAP_IMG_PICT_CORE_INFO_NOTICE,
    WAP_IMG_PICT_CORE_INFO_CHARGED,
    WAP_IMG_PICT_CORE_INFO_FREEOFCHARGE,
    WAP_IMG_PICT_CORE_INFO_NEW,
    WAP_IMG_PICT_CORE_INFO_POSITION,
    WAP_IMG_PICT_CORE_INFO_TOLLFREE,
    WAP_IMG_PICT_CORE_INFO_SHARPDIAL,
    WAP_IMG_PICT_CORE_INFO_RESERVED,
    WAP_IMG_PICT_CORE_INFO_SPEECHINFO,

#endif /*  __MMI_WAP_CORE_PICTOGRAM_SUPPORT__ */
    WAP_IMG_ICON_BROKEN_IMAGE,
#ifdef __MMI_WAP_MOUSE_POINTER_SUPPORT__
    WAP_IMG_ICON_MOUSE_POINTER,
    WAP_IMG_ICON_LINK_SELECT_TOOL,
#endif /* __MMI_WAP_MOUSE_POINTER_SUPPORT__ */
#endif /*OBIGO_Q03C*/

#if defined(OBIGO_Q05A)
    /* MSF */
    MSF_IMAGE_ID_0001_16_IMG_UKNOWN,
    MSF_IMAGE_ID_0001_34_IMG_UKNOWN,
    MSF_IMAGE_ID_0002_16_IMG_JPG,
    MSF_IMAGE_ID_0002_34_IMG_JPG,
    MSF_IMAGE_ID_0003_16_OTHER_DOC,
    MSF_IMAGE_ID_0003_34_OTHER_DOC,
    MSF_IMAGE_ID_0004_16_AUD_UNKNOWN,
    MSF_IMAGE_ID_0004_34_AUD_UNKNOWN,
    MSF_IMAGE_ID_0005_16_FOLDER,
    MSF_IMAGE_ID_0005_34_FOLDER,
    MSF_IMAGE_ID_0006_16_JAVA,
    MSF_IMAGE_ID_0006_34_JAVA,
    MSF_IMAGE_ID_0007_16_JAVA_RMS,
    MSF_IMAGE_ID_0007_34_JAVA_RMS,
    MSF_IMAGE_ID_0008_8_MPHONE,
    MSF_IMAGE_ID_0008_16_MPHONE,
    MSF_IMAGE_ID_0008_34_MPHONE,
    MSF_IMAGE_ID_0009_8_MEMCARD,
    MSF_IMAGE_ID_0009_16_MEMCARD,
    MSF_IMAGE_ID_0009_34_MEMCARD,
    MSF_IMAGE_ID_0010_16_UNCHECK,
    MSF_IMAGE_ID_0010_16_UNCHECK_TRAN,
    MSF_IMAGE_ID_0011_16_CHECK,
    MSF_IMAGE_ID_0011_16_CHECK_TRAN,
    MSF_IMAGE_ID_0012_16_ARROW_L,
    MSF_IMAGE_ID_0013_16_ARROW_R,
    MSF_IMAGE_ID_0014_8_KEY,
    MSF_IMAGE_ID_0014_16_KEY,
    MSF_IMAGE_ID_0015_8_KEY_X,
    MSF_IMAGE_ID_0015_16_KEY_X,
    MSF_IMAGE_ID_0016_16_VID_MP4,
    MSF_IMAGE_ID_0016_34_VID_MP4,
    MSF_IMAGE_ID_0017_16_VID_3GP,
    MSF_IMAGE_ID_0017_34_VID_3GP,
    MSF_IMAGE_ID_0018_16_VCARD,
    MSF_IMAGE_ID_0018_34_VCARD,
    MSF_IMAGE_ID_0019_16_VCALENDAR,
    MSF_IMAGE_ID_0019_34_VCALENDAR,
    MSF_IMAGE_ID_0020_16_IMG_GIF,
    MSF_IMAGE_ID_0020_34_IMG_GIF,
    MSF_IMAGE_ID_0021_16_IMG_PNG,
    MSF_IMAGE_ID_0021_34_IMG_PNG,
    MSF_IMAGE_ID_0022_16_IMG_WBMP,
    MSF_IMAGE_ID_0022_34_IMG_WBMP,
    MSF_IMAGE_ID_0023_16_AUD_MID,
    MSF_IMAGE_ID_0023_34_AUD_MID,
    MSF_IMAGE_ID_0024_16_AUD_MIDI,
    MSF_IMAGE_ID_0024_34_AUD_MIDI,
    MSF_IMAGE_ID_0025_16_AUD_MPG,
    MSF_IMAGE_ID_0025_34_AUD_MPG,
    MSF_IMAGE_ID_0026_16_AUD_WAV,
    MSF_IMAGE_ID_0026_34_AUD_WAV,
    MSF_IMAGE_ID_0027_16_IMG_SVG,
    MSF_IMAGE_ID_0027_34_IMG_SVG,
    MSF_IMAGE_ID_0028_16_JAVA_NOT_INS,
    MSF_IMAGE_ID_0028_34_JAVA_NOT_INS,
    MSF_IMAGE_ID_0029_16_FOLD_PICTURES,
    MSF_IMAGE_ID_0029_34_FOLD_PICTURES,
    MSF_IMAGE_ID_0030_16_FOLD_MOVIES,
    MSF_IMAGE_ID_0030_34_FOLD_MOVIES,
    MSF_IMAGE_ID_0031_16_FOLD_AUDIO,
    MSF_IMAGE_ID_0031_34_FOLD_AUDIO,
    MSF_IMAGE_ID_0032_16_FOLD_RINGTONE,
    MSF_IMAGE_ID_0032_34_FOLD_RINGTONE,
    MSF_IMAGE_ID_0033_16_FOLD_APPS,
    MSF_IMAGE_ID_0033_34_FOLD_APPS,
    MSF_IMAGE_ID_0034_16_FOLD_GAMES,
    MSF_IMAGE_ID_0034_34_FOLD_GAMES,
    MSF_IMAGE_ID_0035_16_FOLD_BOOKMARKS,
    MSF_IMAGE_ID_0035_34_FOLD_BOOKMARKS,
    MSF_IMAGE_ID_0036_16_FOLD_STOREDP,
    MSF_IMAGE_ID_0036_34_FOLD_STOREDP,
    MSF_IMAGE_ID_0037_16_FOLD_TEMPLAT,
    MSF_IMAGE_ID_0037_34_FOLD_TEMPLAT,
    MSF_IMAGE_ID_0038_16_FOLD_CONTACT,
    MSF_IMAGE_ID_0038_34_FOLD_CONTACT,
    MSF_IMAGE_ID_0039_16_FOLD_CALENDAR,
    MSF_IMAGE_ID_0039_34_FOLD_CALENDAR,
    MSF_IMAGE_ID_0040_16_FOLD_MEMO,
    MSF_IMAGE_ID_0040_34_FOLD_MEMO,
    MSF_IMAGE_ID_0041_16_FOLD_SKINS,
    MSF_IMAGE_ID_0041_34_FOLD_SKINS,
    MSF_IMAGE_ID_0042_16_FOLD_OTH_DOC,
    MSF_IMAGE_ID_0042_34_FOLD_OTH_DOC,
    MSF_IMAGE_ID_0043_30_DLG_INF_YN = IMG_GLOBAL_QUESTION, 
    MSF_IMAGE_ID_0044_30_DLG_INF_Y = IMG_GLOBAL_INFO,
    MSF_IMAGE_ID_0045_30_DLG_ALERT_YN = IMG_GLOBAL_QUESTION,
    MSF_IMAGE_ID_0046_30_DLG_ALERT_Y = IMG_GLOBAL_WARNING,
    MSF_IMAGE_ID_0047_30_DLG_ERROR_YN = IMG_GLOBAL_QUESTION,
    MSF_IMAGE_ID_0048_30_DLG_ERROR_Y = IMG_GLOBAL_ERROR,
    MSF_IMAGE_ID_0049_30_DLG_PROGRESS_DEF = MSF_IMAGE_ID_0042_34_FOLD_OTH_DOC + 1,
    MSF_IMAGE_ID_0050_30_DLG_EGGTIMER_DEF,
    MSF_IMAGE_ID_0051_30_DLG_PROMPT_DEF = IMG_GLOBAL_QUESTION,
    MSF_IMAGE_ID_0053_16_AUD_AMR = MSF_IMAGE_ID_0050_30_DLG_EGGTIMER_DEF + 1,
    MSF_IMAGE_ID_0053_34_AUD_AMR,
    MSF_IMAGE_ID_0055_16_AUD_3GP,
    MSF_IMAGE_ID_0055_34_AUD_3GP,
    MSF_IMAGE_ID_0056_16_AUD_MP4,
    MSF_IMAGE_ID_0056_34_AUD_MP4,
    MSF_IMAGE_ID_0064_16_VID_UNKNOWN,
    MSF_IMAGE_ID_0064_34_VID_UNKNOWN,
    MSF_IMAGE_ID_0065_TAB_BKGR_INFCS,
    MSF_IMAGE_ID_0066_TAB_BKGR_OUTFCS,
    MSF_IMAGE_ID_0067_10_TRAN_BKGR,
    MSF_IMAGE_ID_0137_16_MNU_BOOKMARKS,
    MSF_IMAGE_ID_0137_34_MNU_BOOKMARKS,
    MSF_IMAGE_ID_0137_16_PLAYLIST_FILE_M3U,
    MSF_IMAGE_ID_0137_34_PLAYLIST_FILE_M3U,
    MSF_IMAGE_ID_0244_30_DLG_SINGLE_SEL,
    MSF_IMAGE_ID_0294_16_DEFAULT_PROP,
    MSF_IMAGE_ID_0429_16_IMG_BMP,
    MSF_IMAGE_ID_0429_34_IMG_BMP,
    
    /* BRS */
    BRS_IMG_ID_ICON_RADIO_UNCHECKED,
    BRS_IMG_ID_ICON_RADIO_CHECKED,
    BRS_IMG_ID_ICON_CHECKBOX_UNCHECKED,
    BRS_IMG_ID_ICON_CHECKBOX_CHECKED,
    BRS_IMG_ID_ICON_BROKEN_IMAGE,
    BRS_IMG_ID_ICON_BGSOUND,
    BRS_IMG_ID_ICON_IMG_TO_LARGE,
    BRS_IMG_ID_ICON_RADIO_UNCHECKED_DISABLED,
    BRS_IMG_ID_ICON_RADIO_CHECKED_DISABLED,
    BRS_IMG_ID_ICON_CHECKBOX_UNCHECKED_DISABLED,
    BRS_IMG_ID_ICON_CHECKBOX_CHECKED_DISABLED,
#if defined(OBIGO_Q05A_MMS)
    /* MMA */
    MMA_IMG_LOCK_MODE,
    MMA_IMG_LETTER_JAVA,
    MMA_IMG_FORWARD_LOCK_READ_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_READ_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK,
    MMA_IMG_FORWARD_LOCK_READ,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_PRIO_HIGH,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_PRIO_LOW,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT,
    MMA_IMG_FORWARD_LOCK_ATTACHMENT_READ,
    MMA_IMG_ATTACHMENT_READ_PRIO_HIGH,
    MMA_IMG_ATTACHMENT_READ_PRIO_LOW,
    MMA_IMG_ATTACHMENT_PRIO_HIGH,
    MMA_IMG_ATTACHMENT_PRIO_LOW,
    MMA_IMG_ATTACHMENT,
    MMA_IMG_ATTACHMENT_READ,
    MMA_IMG_LETTER,
    MMA_IMG_LETTER_READ,
    MMA_IMG_LETTER_READ_PRIO_HIGH,
    MMA_IMG_LETTER_READ_PRIO_LOW,
    MMA_IMG_LETTER_PRIO_HIGH,
    MMA_IMG_LETTER_PRIO_LOW,
    MMA_IMG_NOTIF,
    MMA_IMG_LETTER_CREATED,
    MMA_IMG_RR,
    MMA_IMG_RR_READ,
    MMA_IMG_DR,
    MMA_IMG_DR_READ,
    MMA_IMG_CORRUPT,
    MMA_IMG_AUDIO,
    MMA_IMG_AUDIO_PRIO_HIGH,
    MMA_IMG_AUDIO_PRIO_LOW,
    MMA_IMG_AUDIO_READ,
    MMA_IMG_AUDIO_READ_PRIO_HIGH,
    MMA_IMG_AUDIO_READ_PRIO_LOW,
    MMA_IMG_VIDEO,
    MMA_IMG_VIDEO_PRIO_HIGH,
    MMA_IMG_VIDEO_PRIO_LOW,
    MMA_IMG_VIDEO_READ,
    MMA_IMG_VIDEO_READ_PRIO_HIGH,
    MMA_IMG_VIDEO_READ_PRIO_LOW,
    MMA_IMG_PHOTO,
    MMA_IMG_PHOTO_PRIO_HIGH,
    MMA_IMG_PHOTO_PRIO_LOW,
    MMA_IMG_PHOTO_READ,
    MMA_IMG_PHOTO_READ_PRIO_HIGH,
    MMA_IMG_PHOTO_READ_PRIO_LOW,
    MMA_IMG_GROUP,
    MMA_IMG_GROUP_PRIO_HIGH,
    MMA_IMG_GROUP_PRIO_LOW,
    MMA_IMG_GROUP_READ,
    MMA_IMG_GROUP_READ_PRIO_HIGH,
    MMA_IMG_GROUP_READ_PRIO_LOW,
    MMA_IMG_GROUP_AUDIO,
    MMA_IMG_GROUP_AUDIO_PRIO_HIGH,
    MMA_IMG_GROUP_AUDIO_PRIO_LOW,
    MMA_IMG_GROUP_AUDIO_READ,
    MMA_IMG_GROUP_AUDIO_READ_PRIO_HIGH,
    MMA_IMG_GROUP_AUDIO_READ_PRIO_LOW,
    MMA_IMG_GROUP_VIDEO,
    MMA_IMG_GROUP_VIDEO_PRIO_HIGH,
    MMA_IMG_GROUP_VIDEO_PRIO_LOW,
    MMA_IMG_GROUP_VIDEO_READ,
    MMA_IMG_GROUP_VIDEO_READ_PRIO_HIGH,
    MMA_IMG_GROUP_VIDEO_READ_PRIO_LOW,
    MMA_IMG_GROUP_PHOTO,
    MMA_IMG_GROUP_PHOTO_PRIO_HIGH,
    MMA_IMG_GROUP_PHOTO_PRIO_LOW,
    MMA_IMG_GROUP_PHOTO_READ,
    MMA_IMG_GROUP_PHOTO_READ_PRIO_HIGH,
    MMA_IMG_GROUP_PHOTO_READ_PRIO_LOW,
    MMA_IMG_POSTCARD_MMS,
#endif /*OBIGO_Q05A_MMS*/
    /* SES */
    SES_IMAGE_ID_CERT_SMALL,
    SES_IMAGE_ID_CERT_LARGE,
    SES_IMAGE_ID_ROOT_CERT_SMALL,
    SES_IMAGE_ID_ROOT_CERT_LARGE,
    SES_IMAGE_ID_USER_CERT_SMALL,
    SES_IMAGE_ID_USER_CERT_LARGE,
    SES_IMAGE_ID_VALID_SMALL,
    SES_IMAGE_ID_EXPIRED_SMALL,
        
    /* OWL PICTOGRAM */
    /* The following order should match up with owl_image.c PICTOGRAM string order */
    OWL_IMAGE_ID_PICT_CORE_ARROW_UP,
    OWL_IMAGE_ID_PICT_CORE_ARROW_DOWN,
    OWL_IMAGE_ID_PICT_CORE_ARROW_RIGHT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_LEFT,

    OWL_IMAGE_ID_PICT_CORE_ARROW_UPPERRIGHT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_UPPERLEFT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_LOWERRIGHT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_LOWERLEFT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_FINGERUP,
    OWL_IMAGE_ID_PICT_CORE_ARROW_FINGERDOWN,
    OWL_IMAGE_ID_PICT_CORE_ARROW_FINGERRIGHT,
    OWL_IMAGE_ID_PICT_CORE_ARROW_FINGERLEFT,

    OWL_IMAGE_ID_PICT_CORE_BUTTON_1,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_2,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_3,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_4,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_5,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_6,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_7,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_8,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_9,
    OWL_IMAGE_ID_PICT_CORE_BUTTON_0,

    OWL_IMAGE_ID_PICT_CORE_ACTION_MAKEPHONECALL,
    OWL_IMAGE_ID_PICT_CORE_ACTION_FIND,
    OWL_IMAGE_ID_PICT_CORE_ACTION_USERAUTHENTICATION,
    OWL_IMAGE_ID_PICT_CORE_ACTION_PASSWORD,
    OWL_IMAGE_ID_PICT_CORE_ACTION_NEXTITEM,
    OWL_IMAGE_ID_PICT_CORE_ACTION_CLEAR,
    OWL_IMAGE_ID_PICT_CORE_ACTION_STOP,
    OWL_IMAGE_ID_PICT_CORE_ACTION_TOP,
    OWL_IMAGE_ID_PICT_CORE_ACTION_NEXT,
    OWL_IMAGE_ID_PICT_CORE_ACTION_BACK,

    OWL_IMAGE_ID_PICT_CORE_MESSAGE_RECEIVE,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_SEND,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_MESSAGE,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_DOCUMENT,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_ATTACHMENT,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_FOLDER,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_INBOX,
    OWL_IMAGE_ID_PICT_CORE_MESSAGE_OUTBOX,

    OWL_IMAGE_ID_PICT_CORE_STATE_SECURE,
    OWL_IMAGE_ID_PICT_CORE_STATE_INSECURE,
    OWL_IMAGE_ID_PICT_CORE_STATE_COPYRIGHT,
    OWL_IMAGE_ID_PICT_CORE_STATE_TRADEMARK,
    OWL_IMAGE_ID_PICT_CORE_STATE_UNDERCONSTRUCTION,
    OWL_IMAGE_ID_PICT_CORE_STATE_BEGINNER,

    OWL_IMAGE_ID_PICT_CORE_MEDIA_BOOK,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_VIDEO,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_CD,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_DVD,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_GAME,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_RADIO,
    OWL_IMAGE_ID_PICT_CORE_MEDIA_TV,

    OWL_IMAGE_ID_PICT_CORE_INFO_NOTICE,
    OWL_IMAGE_ID_PICT_CORE_INFO_CHARGED,
    OWL_IMAGE_ID_PICT_CORE_INFO_FREEOFCHARGE,
    OWL_IMAGE_ID_PICT_CORE_INFO_NEW,
    OWL_IMAGE_ID_PICT_CORE_INFO_POSITION,
    OWL_IMAGE_ID_PICT_CORE_INFO_TOLLFREE,
    OWL_IMAGE_ID_PICT_CORE_INFO_SHARPDIAL,
    OWL_IMAGE_ID_PICT_CORE_INFO_RESERVED,
    OWL_IMAGE_ID_PICT_CORE_INFO_SPEECHINFO,

    /* The following order should match up with owl_rm.h OWL_RM_ACCESSKEY_BITMAP_0 */
    OWL_IMAGE_ID_ACCESSKEY_0,
    OWL_IMAGE_ID_ACCESSKEY_1,    
    OWL_IMAGE_ID_ACCESSKEY_2,
    OWL_IMAGE_ID_ACCESSKEY_3,    
    OWL_IMAGE_ID_ACCESSKEY_4,
    OWL_IMAGE_ID_ACCESSKEY_5,    
    OWL_IMAGE_ID_ACCESSKEY_6,
    OWL_IMAGE_ID_ACCESSKEY_7,    
    OWL_IMAGE_ID_ACCESSKEY_8,
    OWL_IMAGE_ID_ACCESSKEY_9,    
    OWL_IMAGE_ID_ACCESSKEY_STAR,
    OWL_IMAGE_ID_ACCESSKEY_POUND,
    OWL_IMAGE_ID_ACCESSKEY_UP,
    OWL_IMAGE_ID_ACCESSKEY_DOWN,
    OWL_IMAGE_ID_ACCESSKEY_LEFT,
    OWL_IMAGE_ID_ACCESSKEY_RIGHT,

    OWL_IMAGE_ID_CHECK_OFF,
    OWL_IMAGE_ID_CHECK_ON,
    OWL_IMAGE_ID_RADIO_OFF,
    OWL_IMAGE_ID_RADIO_ON,
    OWL_IMAGE_ID_SELECT_ITEM,
    OWL_IMAGE_ID_SELECT_ITEM_BIG,
    OWL_IMAGE_ID_TEXTINPUT_BORDER_BOTTOM,
    OWL_IMAGE_ID_TEXTINPUT_BORDER_LEFT,
    OWL_IMAGE_ID_TEXTINPUT_BORDER_RIGHT,
    OWL_IMAGE_ID_TEXTINPUT_BORDER_TOP,
    OWL_IMAGE_ID_CACHE,
    OWL_IMAGE_ID_BUSY,
    OWL_IMAGE_ID_SECURE,
    OWL_IMAGE_ID_HAS_SUB_MENU,
    OWL_IMAGE_ID_SOFT_TITLE,
    
	/* OWL Adp */
    OWL_ADP_IMAGE_WAP_LOGO,

    /* VDS */
    VDS_IMG_ID_LOADING,
    VDS_IMG_ID_PLAY,
    VDS_IMG_ID_BROKEN,
    VDS_IMG_ID_AUDIO,
    VDS_IMG_ID_VDO_INACTIVE,

#endif

    /* add new image ID above this line */
    WAP_IMAGE_ID_END
} IMG_ID_WAP_ENUM;

/* Audio files */
typedef enum
{
    WAP_AUDIO_ID_BEGIN = WAP_BASE,
#ifdef __MMI_MMS_V01_TEMPLATES_SUPPORT__
	MMS_AUDIO_TEMPLATES_01,
	MMS_AUDIO_TEMPLATES_02,
	MMS_AUDIO_TEMPLATES_03,
	MMS_AUDIO_TEMPLATES_04,
	MMS_AUDIO_TEMPLATES_05,
#endif
    WAP_AUDIO_ID_END
}AUDIO_WAP_ENUM;
#endif /* WAPRESDEF_H */ 

