#include "CustomCfg.h"
#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif
#include "MMI_features.h"
#include "MMIDataType.h"
#include "lcd_sw_inc.h"
#include "MMI_features_camcorder.h"
#include "custresdef.h"

<?xml version="1.0" encoding="UTF-8"?>

<APP id="APP_CAMCO" name="STR_ID_CAMCO_APP_NAME" type="pluto">   
</APP>

<APP id="APP_CAMCO"
#if defined(__MMI_APP_MANAGER_SUPPORT__)
#if defined(__MMI_CAMCORDER__)
    package_name = "native.mtk.camcorder"         /* Use "native.mtk." as the prefix of application name */
    name = "STR_ID_CAMCO_APP_NAME"                    /* The string to be displayed under the main menu icon */
    #if defined(__MMI_VUI_LAUNCHER__) || defined(__MMI_MAINMENU_SPREAD_SUPPORT__) //MMI_ICON
    img = "IMG_ID_CAMCO_VUI_ICON"   /* Main menu icon image */
    #endif
    launch = "mmi_camco_launch"               /* Launch function of application. When tap on the icon in main menu, the function will be invoked.
                                                     * the function prototype should be:
                                                     *
                                                     *    typedef MMI_ID (*mmi_app_launch_func) (void* param, U32 param_size);
                                                     *
                                                     * Note that the group_id of the application should be returned if launch successfully.
                                                     * If the application could not be launched for some reason, GRP_ID_INVALID should be returned. */
#endif
#else /*__MMI_APP_MANAGER_SUPPORT__&& __MMI_CAMCORDER__*/
#if defined(__MMI_CAMCORDER__)
   name = "STR_ID_CAMCO_APP_NAME"
#endif
#endif
>
#if defined(__MMI_CAMCORDER__)
    <MEMORY heap= "0" extra_base="APPMEM_CAMCO_POOL_SIZE+ max(base(SRV_MDI_VDOREC), base(SRV_MDI_VDOPLY_PREVIEW))" fg="max(max(total(SRV_MDI_CAMERA_FULL), fg(SRV_MDI_VDOREC)), fg(SRV_MDI_VDOPLY_PREVIEW))- max(base(SRV_MDI_VDOREC), base(SRV_MDI_VDOPLY_PREVIEW)) - GDI_ASM_MEM_SIZE + MED_1_SCENARIO_JPG_DECODE" inc="CamcorderGprot.h, med_mem.h"/> 
    <INCLUDE file = "PopulateRes.h"/>
    <INCLUDE file = "ImageViewerResDef.h"/>
    <INCLUDE file = "CustResDef.h"/>
                    


    <STRING id="STR_ID_CAMCO_SWITCH_TO"/>
    <STRING id="STR_ID_CAMCO_TO_ALBUMN"/>
    <STRING id="STR_ID_CAMCO_TO_VDOREC"/>
    <STRING id="STR_ID_CAMCO_TO_VDOPLY"/>
    <STRING id="STR_ID_CAMCO_TO_CAMERA"/>
    <STRING id="STR_ID_CAMCO_TO_SUBLCD"/>
    <STRING id="STR_ID_CAMCO_TO_MAIN_CAM"/>
    <STRING id="STR_ID_CAMCO_TO_SUB_CAM"/>
    <STRING id="STR_ID_CAMCO_EV"/>
    <STRING id="STR_ID_CAMCO_EVP4"/>
    <STRING id="STR_ID_CAMCO_EVP3"/>
    <STRING id="STR_ID_CAMCO_EVP2"/>
    <STRING id="STR_ID_CAMCO_EVP1"/>
    <STRING id="STR_ID_CAMCO_EVZ0"/>   
    <STRING id="STR_ID_CAMCO_EVN1"/>
    <STRING id="STR_ID_CAMCO_EVN2"/>
    <STRING id="STR_ID_CAMCO_EVN3"/>
    <STRING id="STR_ID_CAMCO_EVN4"/>     
    <STRING id="STR_ID_CAMCO_CAPMODE"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_NORMAL"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_BEST_SHOT"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_CONT_SHOT"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_BURST_SHOT_SEL"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_EV_BRACKET_SEL"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_AUTORAMA"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_ADD_FRAME"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_SMILE_SHOT"/>
    <STRING id="STR_ID_CAMCO_CAPMODE_HDR_SHOT"/>   
    <STRING id="STR_ID_CAMCO_CAPMODE_ZSD_SHOT"/> 
    <STRING id="STR_ID_CAMCO_CAPMODE_MAV"/> 
    <STRING id="STR_ID_CAMCO_CAPMODE_3D_IMAGE"/> 
    <STRING id="STR_ID_CAMCO_CAPMODE_ASD_SHOT"/> 
    <STRING id="STR_ID_CAMCO_CAPMODE_AUTORAMA"/>   
    <STRING id="STR_ID_CAMCO_SCENEMODE"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_AUTO"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_PORTRAIT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_LANDSCAPE"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_NIGHT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_SPORT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_DOCUMENT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_ANTI_SHAKE"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_BACKLIGHT_PORTRAIT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_NIGHT_PORTRAIT"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_FLOWER"/>
    <STRING id="STR_ID_CAMCO_SCENEMODE_BACKLIGHT"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_WALLPAPER"/>
#if defined(HORIZONTAL_CAMERA)
    #if defined(__MMI_MAINLCD_240X400__)
    <STRING id="STR_ID_CAMCO_CAPSIZE_HLCD">"WQVGA"</STRING>
    #elif defined(__MMI_MAINLCD_320X480__)
    <STRING id="STR_ID_CAMCO_CAPSIZE_HLCD">"HVGA"</STRING>
    #else
    <STRING id="STR_ID_CAMCO_CAPSIZE_HLCD">"QVGA"</STRING>
    #endif
#endif
    <STRING id="STR_ID_CAMCO_CAPSIZE_VGA"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_1MP"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_2MP"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_3MP"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_4MP"/>
    <STRING id="STR_ID_CAMCO_CAPSIZE_5MP"/>
    <STRING id="STR_ID_CAMCO_FLASH"/>
    <STRING id="STR_ID_CAMCO_FLASH_AUTO"/>
    <STRING id="STR_ID_CAMCO_FLASH_FORCE_ON"/>
    <STRING id="STR_ID_CAMCO_FLASH_RED_EYE"/>
    <STRING id="STR_ID_CAMCO_HIGHLIGHT"/>
    <STRING id="STR_ID_CAMCO_AFRANGE"/>
    <STRING id="STR_ID_CAMCO_AFRANGE_AUTO"/>
    <STRING id="STR_ID_CAMCO_AFRANGE_MACRO"/>
    <STRING id="STR_ID_CAMCO_AFRANGE_INFINITE"/>
    <STRING id="STR_ID_CAMCO_SELFTIMER"/>
    <STRING id="STR_ID_CAMCO_SELFTIMER_5S"/>
    <STRING id="STR_ID_CAMCO_SELFTIMER_10S"/>
    <STRING id="STR_ID_CAMCO_ISO"/>
    <STRING id="STR_ID_CAMCO_ISO_AUTO"/>
    <STRING id="STR_ID_CAMCO_ISO_100"/>
    <STRING id="STR_ID_CAMCO_ISO_200"/>
    <STRING id="STR_ID_CAMCO_ISO_400"/>
    <STRING id="STR_ID_CAMCO_ISO_800"/>
    <STRING id="STR_ID_CAMCO_ISO_1600"/>
    <STRING id="STR_ID_CAMCO_WB"/>
    <STRING id="STR_ID_CAMCO_WB_AUTO"/>
    <STRING id="STR_ID_CAMCO_WB_DAYLIGHT"/>
    <STRING id="STR_ID_CAMCO_WB_TUNGSTEN"/>
    <STRING id="STR_ID_CAMCO_WB_FLUORESCENT"/>
    <STRING id="STR_ID_CAMCO_WB_CLOUDY"/>
    <STRING id="STR_ID_CAMCO_WB_INCANDESCENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_LOMO_EFFECT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_RED_COLOR_ACCENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_BLUE_COLOR_ACCENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_GREEN_COLOR_ACCENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_YELLOW_COLOR_ACCENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_GRAYSCALE"/>
    <STRING id="STR_ID_CAMCO_EFFECT_SEPIA"/>
    <STRING id="STR_ID_CAMCO_EFFECT_SEPIA_GREEN"/>
    <STRING id="STR_ID_CAMCO_EFFECT_SEPIA_BLUE"/>
    <STRING id="STR_ID_CAMCO_EFFECT_COLOR_INVERT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_GRAY_INVERT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_BLACKBOARD"/>
    <STRING id="STR_ID_CAMCO_EFFECT_WHITEBOARD"/>
    <STRING id="STR_ID_CAMCO_EFFECT_COPPER_CARVING"/>
    <STRING id="STR_ID_CAMCO_EFFECT_BLUE_CARVING"/>
    <STRING id="STR_ID_CAMCO_EFFECT_EMBOSSMENT"/>
    <STRING id="STR_ID_CAMCO_EFFECT_CONTRAST"/>
    <STRING id="STR_ID_CAMCO_EFFECT_JEAN"/>
    <STRING id="STR_ID_CAMCO_EFFECT_SKETCH"/>
    <STRING id="STR_ID_CAMCO_EFFECT_OIL"/>
    <STRING id="STR_ID_CAMCO_CAPQTY"/>
    <STRING id="STR_ID_CAMCO_CAPQTY_FINE"/>
    <STRING id="STR_ID_CAMCO_CAPQTY_GOOD"/>
    <STRING id="STR_ID_CAMCO_CAPQTY_NORMAL"/>
    <STRING id="STR_ID_CAMCO_CAPQTY_LOW"/>    
    <STRING id="STR_ID_CAMCO_AFZONE"/>
    <STRING id="STR_ID_CAMCO_AFZONE_SINGLE"/>
    <STRING id="STR_ID_CAMCO_AFZONE_MULTI"/>
    <STRING id="STR_ID_CAMCO_AFZONE_CONTINUE"/>    
    <STRING id="STR_ID_CAMCO_AEMETER"/>
    <STRING id="STR_ID_CAMCO_AEMETER_AUTO"/>
    <STRING id="STR_ID_CAMCO_AEMETER_SPOT"/>
    <STRING id="STR_ID_CAMCO_AEMETER_CENTER_WEIGHT"/>
    <STRING id="STR_ID_CAMCO_AEMETER_AVERAGE"/>
    <STRING id="STR_ID_CAMCO_SHARPNESS"/>
    <STRING id="STR_ID_CAMCO_CONTRAST"/>
    <STRING id="STR_ID_CAMCO_SATURATION"/>
    <STRING id="STR_ID_CAMCO_ENHANCE"/>
    <STRING id="STR_ID_CAMCO_REDUCE"/>
    <STRING id="STR_ID_CAMCO_TIMESTAMP"/>
    <STRING id="STR_ID_CAMCO_SHUTTERSOUND"/>
    <STRING id="STR_ID_CAMCO_SHUTTERSOUND_SOUND_SILENT"/>    
    <STRING id="STR_ID_CAMCO_SHUTTERSOUND_SOUND_1"/>
    <STRING id="STR_ID_CAMCO_SHUTTERSOUND_SOUND_2"/>
    <STRING id="STR_ID_CAMCO_SHUTTERSOUND_SOUND_3"/>
    <STRING id="STR_ID_CAMCO_BANDING"/>
    <STRING id="STR_ID_CAMCO_BANDING_50HZ"/>
    <STRING id="STR_ID_CAMCO_BANDING_60HZ"/>
    <STRING id="STR_ID_CAMCO_TIME_LAPSE"/>
    <STRING id="STR_ID_CAMCO_RECSIZE"/>    
    <STRING id="STR_ID_CAMCO_RECSIZE_SQCIF"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_QQVGA"/>		
    <STRING id="STR_ID_CAMCO_RECSIZE_QCIF"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_QVGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_CIF"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_WQVGA"/>       
    <STRING id="STR_ID_CAMCO_RECSIZE_CIF2"/> 
    <STRING id="STR_ID_CAMCO_RECSIZE_HVGA"/>           
    <STRING id="STR_ID_CAMCO_RECSIZE_NHD"/>        
    <STRING id="STR_ID_CAMCO_RECSIZE_VGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_D1"/>    
    <STRING id="STR_ID_CAMCO_RECSIZE_D12"/>       
    <STRING id="STR_ID_CAMCO_RECSIZE_WVGA"/>      
    <STRING id="STR_ID_CAMCO_RECSIZE_SVGA"/>    
    <STRING id="STR_ID_CAMCO_RECSIZE_WVGA2"/>          
    <STRING id="STR_ID_CAMCO_RECSIZE_XGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_720P"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_4VGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_SXGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_16CIF"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_4SVGA"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_FHD"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_4CIF"/>
    <STRING id="STR_ID_CAMCO_RECSIZE_FWVGA"/>
    #ifdef MMI_CAMCO_WALLPAPER
        <STRING id="STR_ID_CAMCO_RECSIZE_WALLPAPER"/>
    #endif
    <STRING id="STR_ID_CAMCO_SIZELIMIT"/>
    <STRING id="STR_ID_CAMCO_SIZELIMIT_NO_LIMIT"/>
    <STRING id="STR_ID_CAMCO_SIZELIMIT_95K"/>
    <STRING id="STR_ID_CAMCO_SIZELIMIT_195K"/>
    <STRING id="STR_ID_CAMCO_SIZELIMIT_295K"/>
    <STRING id="STR_ID_CAMCO_TIMELIMIT"/>
    <STRING id="STR_ID_CAMCO_TIMELIMIT_NO_LIMIT"/>
    <STRING id="STR_ID_CAMCO_TIMELIMIT_15S"/>
    <STRING id="STR_ID_CAMCO_TIMELIMIT_30S"/>
    <STRING id="STR_ID_CAMCO_TIMELIMIT_60S"/>
    <STRING id="STR_ID_CAMCO_LIMIT"/>
    <STRING id="STR_ID_CAMCO_LIMIT_NO_LIMIT"/>
    <STRING id="STR_ID_CAMCO_LIMIT_TIME_15S"/>
    <STRING id="STR_ID_CAMCO_LIMIT_TIME_30S"/>
    <STRING id="STR_ID_CAMCO_LIMIT_TIME_60S"/>
    <STRING id="STR_ID_CAMCO_LIMIT_SIZE_95K"/>
    <STRING id="STR_ID_CAMCO_LIMIT_SIZE_195K"/>
    <STRING id="STR_ID_CAMCO_LIMIT_SIZE_295K"/>
    <STRING id="STR_ID_CAMCO_LIMIT_TIME_5MIN"/>
    <STRING id="STR_ID_CAMCO_LIMIT_TIME_10MIN"/>
    <STRING id="STR_ID_CAMCO_VISQTY"/>
    <STRING id="STR_ID_CAMCO_VISQTY_FINE"/>
    <STRING id="STR_ID_CAMCO_VISQTY_GOOD"/>
    <STRING id="STR_ID_CAMCO_VISQTY_NORMAL"/>
    <STRING id="STR_ID_CAMCO_VISQTY_LOW"/>    
    <STRING id="STR_ID_CAMCO_AFMODE"/>
    <STRING id="STR_ID_CAMCO_AFMODE_SINGLE"/>
    <STRING id="STR_ID_CAMCO_AFMODE_CONT"/>
    <STRING id="STR_ID_CAMCO_RECAUD"/>
    <STRING id="STR_ID_CAMCO_RECAUD_ON"/>
    <STRING id="STR_ID_CAMCO_VISCODEC"/>
    <STRING id="STR_ID_CAMCO_VISCODEC_MP4"/>
    <STRING id="STR_ID_CAMCO_VISCODEC_3GP"/>
    <STRING id="STR_ID_CAMCO_VISCODEC_MJPG"/>    
    <STRING id="STR_ID_CAMCO_VISCODEC_H264"/>        
    <STRING id="STR_ID_CAMCO_MISC"/>
    <STRING id="STR_ID_CAMCO_DEFAULT"/>
    <STRING id="STR_ID_CAMCO_DEFAULT_COMFIRM"/>
    <STRING id="STR_ID_CAMCO_APP_NAME"/>
    <STRING id="STR_ID_CAMCO_DELETE_QUERY"/>
    <STRING id="STR_ID_CAMCO_CAM_PHOTO_EDITOR"/>
    <STRING id="STR_ID_CAMCO_REC_VIDEO_EDITOR"/>
    <STRING id="STR_ID_CAMCO_TO_PHONEBOOK"/>
    <STRING id="STR_ID_CAMCO_TO_MMS"/>
    <STRING id="STR_ID_CAMCO_TO_EMAIL"/>
    <STRING id="STR_ID_CAMCO_TO_BLUETOOTH"/>
    <STRING id="STR_ID_CAMCO_TO_IRDA"/>
    <STRING id="STR_ID_CAMCO_CREATE_FOLDER_FAILED"/>
    <STRING id="STR_ID_CAMCO_PREVIEW_FAILED"/>
    <STRING id="STR_ID_CAMCO_DISK_FULL"/>
    <STRING id="STR_ID_CAMCO_CAPTURE_FAILED"/>
    <STRING id="STR_ID_CAMCO_PAUSE_FAILED"/>
    <STRING id="STR_ID_CAMCO_CAMERA_NOT_READY"/>
    <STRING id="STR_ID_CAMCO_CONTINUE"/>
    <STRING id="STR_ID_CAMCO_COUNTDOWN"/>
    <STRING id="STR_ID_CAMCO_STITCHING"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_WRITE_PROTECT"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_HW_NOT_READY"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_STORAGE_NOT_READY"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_ERROR"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_REACH_TIME_LIMIT"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_REACH_SIZE_LIMIT"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_STORAGE_TOO_SLOW"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_SYSTEM_TOO_BUSY"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_CAMCO_TOO_BUSY"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_CHANGE_LOW_RECSIZE"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_CHANGE_NORMAL_CAPTURE"/>
    <STRING id="STR_ID_CAMCO_NULL"/>
    <STRING id="STR_ID_CAMCO_MEM_CARD_REMOVE"/>
    <STRING id="STR_ID_CAMCO_MEM_CARD_INSERT"/>
    <STRING id="STR_ID_CAMCO_OTG_REMOVE"/>
    <STRING id="STR_ID_CAMCO_OTG_INSERT"/>
    <STRING id="STR_ID_CAMCO_FACE_DETECTION"/>
    <STRING id="STR_ID_CAMCO_PAN_AND_ZOOM"/>
    <STRING id="STR_ID_CAMCO_SWITCH_TO_MEM_CARD"/>
    <STRING id="STR_ID_CAMCO_NOTIFY_BT_IS_WORKING"/>
#ifdef __MMI_PICT_BRIDGE_SUPPORT__
    <STRING id="STR_ID_CAMCO_NOTIFY_PICT_IS_WORKING"/>
#endif
    <STRING id="STR_ID_CAMCO_NOTIFY_BEARER_IS_ACTIVE"/>
#ifdef __MMI_CAMCO_CAM_SUBLCD_CAPTURE__
    <STRING id="STR_ID_CAMCO_CAM_SUBLCD_SWITCH"/>
#endif
#ifdef __MMI_CAMCO_FTE__
    <STRING id="STR_ID_CAMCO_FTE_SETTING_TAB_CAMERA"/>
    <STRING id="STR_ID_CAMCO_FTE_SETTING_TAB_VIDEO"/>
    <STRING id="STR_ID_CAMCO_FTE_SETTING_TAB_MISC"/>
#endif
	<STRING id="STR_ID_CAMCO_ALL_VIDEOS"/> 


    #define CAMCO_OSD_PATH    CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\OSD\\\\"
    #define CAMCO_OSD_LANDSCAPE_PATH    CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\OSD\\\\LANDSCAPE\\\\"
    #define CAMCO_OSD_PORTRAIT_PATH    CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\OSD\\\\PORTRAIT\\\\"
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX__
    #define CAMCO_TIMESTAMP_256X192_PATH   CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\TimeStamp_256X192\\\\"
    #define CAMCO_TIMESTAMP_320X240_PATH   CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\TimeStamp_320X240\\\\"
#ifdef __MMI_CAMCO_FEATURE_CAM_IMGSZIE_SUPPORT_4M__
    #define CAMCO_TIMESTAMP_288X216_PATH   CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\TimeStamp_288X216\\\\"
#endif
#ifdef __MMI_CAMCO_FEATURE_CAM_IMGSZIE_SUPPORT_5M__
    #define CAMCO_TIMESTAMP_324X243_PATH   CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\TimeStamp_324X243\\\\"
#endif
#endif
#ifdef __MMI_APP_MANAGER_SUPPORT__
#if defined(__MMI_VUI_LAUNCHER__) || defined(__MMI_MAINMENU_SPREAD_SUPPORT__) //MMI_ICON
	  <IMAGE id="IMG_ID_CAMCO_VUI_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Launcher\\\\Mainmenu\\\\Icons\\\\Camcorder.png"</IMAGE>
#endif
#endif  
    <IMAGE id="IMG_ID_CAMCO_APP_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\SB_camera.bmp"</IMAGE>

    <IMAGE id="IMG_ID_CAMCO_FORWARD_TO_MMS">CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\CAM_to_mms.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAM_PHOTO_EDITOR">CUST_IMG_PATH"\\\\MainLCD\\\\Camcorder\\\\PA_adj_hue.gif"</IMAGE>
#ifndef HEPHAESTUS68_DEMO_BB    
    <IMAGE id="IMG_ID_CAMCO_CAMERA">CAMCO_OSD_PATH"camera.bmp"</IMAGE>
#else
    <IMAGE id="IMG_ID_CAMCO_CAMERA">CAMCO_OSD_PATH"camera_.bmp"</IMAGE>
#endif    
    <IMAGE id="IMG_ID_CAMCO_CAMERA_ONLY">CAMCO_OSD_PATH"camera_.bmp"</IMAGE>
#ifndef HEPHAESTUS68_DEMO_BB    
    <IMAGE id="IMG_ID_CAMCO_RECORDER">CAMCO_OSD_PATH"recorder.bmp"</IMAGE>
#else
    <IMAGE id="IMG_ID_CAMCO_RECORDER">CAMCO_OSD_PATH"recorder_.bmp"</IMAGE>
#endif        
    <IMAGE id="IMG_ID_CAMCO_RECORDER_ONLY">CAMCO_OSD_PATH"recorder_.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_UP">CAMCO_OSD_PATH"arrow_up.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_DOWN">CAMCO_OSD_PATH"arrow_down.bmp"</IMAGE>
    #ifdef __MMI_ZOOM_SLIDER_BAR__
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_PREVIEW_ZOOM_DISABLE_ICON">CAMCO_OSD_PATH"CAM_bt_zoom_dis.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_IND_ICON">CAMCO_OSD_PATH"CAM_adj_index.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_IND_HILITE_ICON">CAMCO_OSD_PATH"CAM_adj_index_down.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_BAR_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_bg.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_BAR_HILITE_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_bg_down.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_BAR_V_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_bg_v.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_BAR_V_HILITE_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_bg_down_v.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_ZOOM_DEC_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_dec.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_ZOOM_INC_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_inc.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_ZOOM_DEC_V_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_dec_v.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DIR_SETTING_SLIDER_ZOOM_INC_V_ICON">CAMCO_OSD_PATH"CAM_adj_zoom_inc_v.png"</IMAGE>
    #endif
    #else
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_ZOOM_HEAD">CAMCO_OSD_PATH"zoom_head.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_TAIL">CAMCO_OSD_PATH"zoom_tail.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN">CAMCO_OSD_PATH"zoom_in.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN_SEL">CAMCO_OSD_PATH"zoom_in_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN_DIS">CAMCO_OSD_PATH"zoom_in_dis.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT">CAMCO_OSD_PATH"zoom_out.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT_SEL">CAMCO_OSD_PATH"zoom_out_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT_DIS">CAMCO_OSD_PATH"zoom_out_dis.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_ZOOM_HEAD">CAMCO_OSD_PATH"zoom_head.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_TAIL">CAMCO_OSD_PATH"zoom_tail.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN">CAMCO_OSD_PATH"zoom_in.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN_SEL">CAMCO_OSD_PATH"zoom_in_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_IN_DIS">CAMCO_OSD_PATH"zoom_in_dis.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT">CAMCO_OSD_PATH"zoom_out.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT_SEL">CAMCO_OSD_PATH"zoom_out_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ZOOM_OUT_DIS">CAMCO_OSD_PATH"zoom_out_dis.bmp"</IMAGE>
    #endif
    #endif
    <IMAGE id="IMG_ID_CAMCO_ARROW_LEFT">CAMCO_OSD_PATH"arrow_left.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_RIGHT">CAMCO_OSD_PATH"arrow_right.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_PICK">CAMCO_OSD_PATH"pick.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SLASH">CAMCO_OSD_PATH"slash.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_EMPTY_CAMERA">CAMCO_OSD_PATH"trans_camera.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_UP">CAMCO_OSD_PATH"arrow_up_multishot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_DOWN">CAMCO_OSD_PATH"arrow_down_multishot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_LEFT">CAMCO_OSD_PATH"arrow_left_multishot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_RIGHT">CAMCO_OSD_PATH"arrow_right_multishot.bmp"</IMAGE>
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_SETTINGS">CAMCO_OSD_PATH"settings.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_BACK">CAMCO_OSD_PATH"back.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OPTIONS">CAMCO_OSD_PATH"options.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OK">CAMCO_OSD_PATH"ok.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SAVE">CAMCO_OSD_PATH"save.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STOP">CAMCO_OSD_PATH"stop.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_PAUSE">CAMCO_OSD_PATH"pause.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RESUME">CAMCO_OSD_PATH"resume.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_SETTINGS">CAMCO_OSD_PATH"settings.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_BACK">CAMCO_OSD_PATH"back.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OPTIONS">CAMCO_OSD_PATH"options.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OK">CAMCO_OSD_PATH"ok.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SAVE">CAMCO_OSD_PATH"save.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STOP">CAMCO_OSD_PATH"stop.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_PAUSE">CAMCO_OSD_PATH"pause.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RESUME">CAMCO_OSD_PATH"resume.bmp"</IMAGE>
    #endif
    
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_SETTINGS_SEL">CAMCO_OSD_PATH"settings_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_BACK_SEL">CAMCO_OSD_PATH"back_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OPTIONS_SEL">CAMCO_OSD_PATH"options_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OK_SEL">CAMCO_OSD_PATH"ok_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SAVE_SEL">CAMCO_OSD_PATH"save_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STOP_SEL">CAMCO_OSD_PATH"stop_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_PAUSE_SEL">CAMCO_OSD_PATH"pause_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RESUME_SEL">CAMCO_OSD_PATH"resume_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_UP_SEL">CAMCO_OSD_PATH"arrow_up_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_DOWN_SEL">CAMCO_OSD_PATH"arrow_down_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_LEFT_SEL">CAMCO_OSD_PATH"arrow_left_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ARROW_RIGHT_SEL">CAMCO_OSD_PATH"arrow_right_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_UP_SEL">CAMCO_OSD_PATH"arrow_up_multishot_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_DOWN_SEL">CAMCO_OSD_PATH"arrow_down_multishot_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_LEFT_SEL">CAMCO_OSD_PATH"arrow_left_multishot_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MULTISHOT_ARROW_RIGHT_SEL">CAMCO_OSD_PATH"arrow_right_multishot_sel.png"</IMAGE>
    #endif

    <IMAGE id="IMG_ID_CAMCO_VIDEO_PROGRESS_BG">CAMCO_OSD_PATH"video_progress_bg.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VIDEO_PROGRESS_FG">CAMCO_OSD_PATH"video_progress_fg.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_0">CAMCO_OSD_PATH"timer_num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_1">CAMCO_OSD_PATH"timer_num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_2">CAMCO_OSD_PATH"timer_num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_3">CAMCO_OSD_PATH"timer_num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_4">CAMCO_OSD_PATH"timer_num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_5">CAMCO_OSD_PATH"timer_num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_6">CAMCO_OSD_PATH"timer_num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_7">CAMCO_OSD_PATH"timer_num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_8">CAMCO_OSD_PATH"timer_num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_9">CAMCO_OSD_PATH"timer_num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_OSD_TIMER_COLON">CAMCO_OSD_PATH"timer_colon.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_XENON_SUCCESS">CAMCO_OSD_PATH"XENON_FLASH_STATE_SUCCESS.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_XENON_CHARGING">CAMCO_OSD_PATH"XENON_FLASH_STATE_CHARGING.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_XENON_LOW_BATTERY">CAMCO_OSD_PATH"XENON_FLASH_STATE_LOW_BATTERY.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_XENON_TIMEOUT">CAMCO_OSD_PATH"XENON_FLASH_STATE_TIMEOUT.bmp"</IMAGE>
    
    <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_BASE">CAMCO_OSD_PATH"CAM_frame_01.gif"</IMAGE>    
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_1__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_1">CAMCO_OSD_PATH"CAM_frame_01.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_2__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_2">CAMCO_OSD_PATH"CAM_frame_02.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_3__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_3">CAMCO_OSD_PATH"CAM_frame_03.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_4__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_4">CAMCO_OSD_PATH"CAM_frame_04.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_5__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_5">CAMCO_OSD_PATH"CAM_frame_05.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_6__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_6">CAMCO_OSD_PATH"CAM_frame_06.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_7__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_7">CAMCO_OSD_PATH"CAM_frame_07.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_8__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_8">CAMCO_OSD_PATH"CAM_frame_08.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_9__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_9">CAMCO_OSD_PATH"CAM_frame_09.gif"</IMAGE>
    #endif
    #ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX_10__
        <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_10">CAMCO_OSD_PATH"CAM_frame_10.gif"</IMAGE>
    #endif
    <IMAGE id="IMG_ID_CAMCO_ADD_FRAME_COLOR_IDX_COUNT">CAMCO_OSD_PATH"CAM_frame_10.gif"</IMAGE>
    #if defined(__MMI_CAMCORDER_SLIM__)
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_1">CAMCO_OSD_PATH"menuitem_bg.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_HL_MISC">CAMCO_OSD_PATH"menuitem_hl_misc.9slice.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENULIST_TITLE">CAMCO_OSD_PATH"menulist_title.9slice.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_1">CAMCO_OSD_PATH"menuitem_bg_01.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_2">CAMCO_OSD_PATH"menuitem_bg_02.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_3">CAMCO_OSD_PATH"menuitem_bg_03.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_4">CAMCO_OSD_PATH"menuitem_bg_04.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_5">CAMCO_OSD_PATH"menuitem_bg_05.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_6">CAMCO_OSD_PATH"menuitem_bg_06.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_BG_7">CAMCO_OSD_PATH"menuitem_bg_07.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_HL_MAIN">CAMCO_OSD_PATH"menuitem_hl_main.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENUITEM_HL_MISC">CAMCO_OSD_PATH"menuitem_hl_misc.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MENULIST_TITLE">CAMCO_OSD_PATH"menulist_title.bmp"</IMAGE>
    #endif
    <IMAGE id="IMG_ID_CAMCO_RADIO_EMPTY">CAMCO_OSD_PATH"radio_empty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RADIO_FULL">CAMCO_OSD_PATH"radio_full.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCROLLBAR_HEAD">CAMCO_OSD_PATH"scrollbar_head.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCROLLBAR_BODY">CAMCO_OSD_PATH"scrollbar_body.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCROLLBAR_TAIL">CAMCO_OSD_PATH"scrollbar_tail.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SLIDER_HEAD">CAMCO_OSD_PATH"slider_head.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SLIDER_BODY">CAMCO_OSD_PATH"slider_body.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SLIDER_TAIL">CAMCO_OSD_PATH"slider_tail.bmp"</IMAGE>
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_NUM_0">CAMCO_OSD_PATH"num_0.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_1">CAMCO_OSD_PATH"num_1.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_2">CAMCO_OSD_PATH"num_2.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_3">CAMCO_OSD_PATH"num_3.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_4">CAMCO_OSD_PATH"num_4.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_5">CAMCO_OSD_PATH"num_5.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_6">CAMCO_OSD_PATH"num_6.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_7">CAMCO_OSD_PATH"num_7.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_8">CAMCO_OSD_PATH"num_8.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_9">CAMCO_OSD_PATH"num_9.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_DOT">CAMCO_OSD_PATH"num_dot.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_NUM_0">CAMCO_OSD_PATH"num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_1">CAMCO_OSD_PATH"num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_2">CAMCO_OSD_PATH"num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_3">CAMCO_OSD_PATH"num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_4">CAMCO_OSD_PATH"num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_5">CAMCO_OSD_PATH"num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_6">CAMCO_OSD_PATH"num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_7">CAMCO_OSD_PATH"num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_8">CAMCO_OSD_PATH"num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_9">CAMCO_OSD_PATH"num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_NUM_DOT">CAMCO_OSD_PATH"num_dot.bmp"</IMAGE>
    #endif
    <IMAGE id="IMG_ID_CAMCO_FOCUSING">CAMCO_OSD_PATH"focusing.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FOCUSED">CAMCO_OSD_PATH"focused.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_REF_STATUS_ICON_SIZE">CAMCO_OSD_PATH"ref_status_icon_size.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_REF_MAIN_ICON_SIZE">CAMCO_OSD_PATH"ref_main_icon_size.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_LAPSE_SEL">CAMCO_OSD_PATH"timelaps_sel.png"</IMAGE>  
    
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_EV_SETTING_SEL">CAMCO_OSD_PATH"ev_sel.png"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_SWITCH_TO_SEL">CAMCO_OSD_PATH"switchto_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_SEL">CAMCO_OSD_PATH"capmode_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_SEL">CAMCO_OSD_PATH"scenemode_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_SEL">CAMCO_OSD_PATH"capsize_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_FLASH_SEL">CAMCO_OSD_PATH"flash_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_HIGHLIGHT_SEL">CAMCO_OSD_PATH"highlight_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFRANGE_SEL">CAMCO_OSD_PATH"afrange_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SELFTIMER_SEL">CAMCO_OSD_PATH"selftimer_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_ISO_SEL">CAMCO_OSD_PATH"iso_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_WB_SEL">CAMCO_OSD_PATH"wb_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_EFFECT_SEL">CAMCO_OSD_PATH"effect_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_SEL">CAMCO_OSD_PATH"capqty_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_STORAGE_SEL">CAMCO_OSD_PATH"storage_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFZONE_SEL">CAMCO_OSD_PATH"afzone_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AEMETER_SEL">CAMCO_OSD_PATH"aemeter_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SHARPNESS_SEL">CAMCO_OSD_PATH"sharpness_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CONTRAST_SEL">CAMCO_OSD_PATH"contrast_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SATURATION_SEL">CAMCO_OSD_PATH"saturation_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_TIMESTAMP_SEL">CAMCO_OSD_PATH"timestamp_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SHUTTERSOUND_SEL">CAMCO_OSD_PATH"shuttersound_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_BANDING_SEL">CAMCO_OSD_PATH"banding_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_SEL">CAMCO_OSD_PATH"recsize_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT_SEL">CAMCO_OSD_PATH"sizelimit_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT_SEL">CAMCO_OSD_PATH"timelimit_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_LIMIT_SEL">CAMCO_OSD_PATH"limit_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_VISQTY_SEL">CAMCO_OSD_PATH"visqty_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFMODE_SEL">CAMCO_OSD_PATH"afmode_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECAUD_SEL">CAMCO_OSD_PATH"recaud_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_VISCODEC_SEL">CAMCO_OSD_PATH"viscodec_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_MISC_SEL">CAMCO_OSD_PATH"misc_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_DEFAULT_SEL">CAMCO_OSD_PATH"reset_sel.png"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_FACEDETECT_SEL">CAMCO_OSD_PATH"tracer_sel.png"</IMAGE> 
    <IMAGE id="IMG_ID_CAMCO_NORMAL_BG">CAMCO_OSD_PATH"normal_bg.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_HIGHLIGHT_BG">CAMCO_OSD_PATH"highlight_bg.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_EV_SETTING">CAMCO_OSD_PATH"ev.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_EV_SETTING_SEL">CAMCO_OSD_PATH"ev_sel.bmp"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_SWITCH_TO">CAMCO_OSD_PATH"switchto.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SWITCH_TO_SEL">CAMCO_OSD_PATH"switchto_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPMODE">CAMCO_OSD_PATH"capmode.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_SEL">CAMCO_OSD_PATH"capmode_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE">CAMCO_OSD_PATH"scenemode.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_SEL">CAMCO_OSD_PATH"scenemode_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE">CAMCO_OSD_PATH"capsize.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_SEL">CAMCO_OSD_PATH"capsize_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_FLASH">CAMCO_OSD_PATH"flash.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FLASH_SEL">CAMCO_OSD_PATH"flash_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_HIGHLIGHT">CAMCO_OSD_PATH"highlight.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_HIGHLIGHT_SEL">CAMCO_OSD_PATH"highlight_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFRANGE">CAMCO_OSD_PATH"afrange.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFRANGE_SEL">CAMCO_OSD_PATH"afrange_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SELFTIMER">CAMCO_OSD_PATH"selftimer.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SELFTIMER_SEL">CAMCO_OSD_PATH"selftimer_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_ISO">CAMCO_OSD_PATH"iso.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_SEL">CAMCO_OSD_PATH"iso_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_WB">CAMCO_OSD_PATH"wb.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_SEL">CAMCO_OSD_PATH"wb_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_EFFECT">CAMCO_OSD_PATH"effect.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_EFFECT_SEL">CAMCO_OSD_PATH"effect_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CAPQTY">CAMCO_OSD_PATH"capqty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_SEL">CAMCO_OSD_PATH"capqty_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_STORAGE">CAMCO_OSD_PATH"storage.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STORAGE_SEL">CAMCO_OSD_PATH"storage_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFZONE">CAMCO_OSD_PATH"afzone.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFZONE_SEL">CAMCO_OSD_PATH"afzone_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AEMETER">CAMCO_OSD_PATH"aemeter.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AEMETER_SEL">CAMCO_OSD_PATH"aemeter_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SHARPNESS">CAMCO_OSD_PATH"sharpness.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SHARPNESS_SEL">CAMCO_OSD_PATH"sharpness_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_CONTRAST">CAMCO_OSD_PATH"contrast.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CONTRAST_SEL">CAMCO_OSD_PATH"contrast_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SATURATION">CAMCO_OSD_PATH"saturation.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SATURATION_SEL">CAMCO_OSD_PATH"saturation_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_TIMESTAMP">CAMCO_OSD_PATH"timestamp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMESTAMP_SEL">CAMCO_OSD_PATH"timestamp_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SHUTTERSOUND">CAMCO_OSD_PATH"shuttersound.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SHUTTERSOUND_SEL">CAMCO_OSD_PATH"shuttersound_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_BANDING">CAMCO_OSD_PATH"banding.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_BANDING_SEL">CAMCO_OSD_PATH"banding_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECSIZE">CAMCO_OSD_PATH"recsize.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_SEL">CAMCO_OSD_PATH"recsize_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT">CAMCO_OSD_PATH"sizelimit.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT_SEL">CAMCO_OSD_PATH"sizelimit_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT">CAMCO_OSD_PATH"timelimit.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT_SEL">CAMCO_OSD_PATH"timelimit_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_LIMIT">CAMCO_OSD_PATH"limit.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_LIMIT_SEL">CAMCO_OSD_PATH"limit_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_VISQTY">CAMCO_OSD_PATH"visqty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISQTY_SEL">CAMCO_OSD_PATH"visqty_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AFMODE">CAMCO_OSD_PATH"afmode.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFMODE_SEL">CAMCO_OSD_PATH"afmode_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECAUD">CAMCO_OSD_PATH"recaud.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECAUD_SEL">CAMCO_OSD_PATH"recaud_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_VISCODEC">CAMCO_OSD_PATH"viscodec.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISCODEC_SEL">CAMCO_OSD_PATH"viscodec_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_MISC">CAMCO_OSD_PATH"misc.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_MISC_SEL">CAMCO_OSD_PATH"misc_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_DEFAULT">CAMCO_OSD_PATH"reset.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_DEFAULT_SEL">CAMCO_OSD_PATH"reset_sel.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_FACEDETECT">CAMCO_OSD_PATH"tracer.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FACEDETECT_SEL">CAMCO_OSD_PATH"tracer_sel.bmp"</IMAGE>
    #endif
    
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_BEST_SHOT">CAMCO_OSD_PATH"capmode_best_shot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_CONT_SHOT">CAMCO_OSD_PATH"capmode_cont_shot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_BURST_SHOT_SEL">CAMCO_OSD_PATH"capmode_burst_shot_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_EV_BRACKET_SEL">CAMCO_OSD_PATH"capmode_ev_bracket_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_ADD_FRAME">CAMCO_OSD_PATH"capmode_add_frame.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_SMILE_SHOT">CAMCO_OSD_PATH"capmode_smile.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_HDR_SHOT">CAMCO_OSD_PATH"capmode_hdr.bmp"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV">CAMCO_OSD_PATH"capmode_mav_shot.bmp"</IMAGE>       
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_3D_IMAGE">CAMCO_OSD_PATH"capmode_3d_image_shot.bmp"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_ZSD_SHOT">CAMCO_OSD_PATH"capmode_zsd_shot_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_ASD_SHOT">CAMCO_OSD_PATH"capmode_asd_shot_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_SHOT">CAMCO_OSD_PATH"capmode_autorama_shot_sel.bmp"</IMAGE>  
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_SMILE_SHOT_DET">CAMCO_OSD_PATH"capmode_smile_detect.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_PORTRAIT">CAMCO_OSD_PATH"scenemode_portrait.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_LANDSCAPE">CAMCO_OSD_PATH"scenemode_landscape.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_NIGHT">CAMCO_OSD_PATH"scenemode_night.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_SPORT">CAMCO_OSD_PATH"scenemode_sport.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_FLOWER">CAMCO_OSD_PATH"scenemode_flower.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_DOCUMENT">CAMCO_OSD_PATH"scenemode_document.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_ANTI_SHAKE">CAMCO_OSD_PATH"scenemode_anti_shake.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_BACKLIGHT_PORTRAIT">CAMCO_OSD_PATH"scenemode_backlight_portrait.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_NIGHT_PORTRAIT">CAMCO_OSD_PATH"scenemode_night_portrait.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_BACKLIGHT">CAMCO_OSD_PATH"scenemode_backlight.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SCENEMODE_AUTO">CAMCO_OSD_PATH"scenemode_auto.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_WALLPAPER">CAMCO_OSD_PATH"capsize_wallpaper.bmp"</IMAGE>
#if defined(__MMI_MAINLCD_240X400__)
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_HLCD">CAMCO_OSD_PATH"capsize_wqvga.bmp"</IMAGE>
#elif defined(__MMI_MAINLCD_320X480__)
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_HLCD">CAMCO_OSD_PATH"capsize_hvga.bmp"</IMAGE>
#else
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_HLCD">CAMCO_OSD_PATH"capsize_qvga.bmp"</IMAGE>
#endif
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_VGA">CAMCO_OSD_PATH"capsize_vga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_1MP">CAMCO_OSD_PATH"capsize_1mp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_2MP">CAMCO_OSD_PATH"capsize_2mp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_3MP">CAMCO_OSD_PATH"capsize_3mp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_4MP">CAMCO_OSD_PATH"capsize_4mp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPSIZE_5MP">CAMCO_OSD_PATH"capsize_5mp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FLASH_AUTO">CAMCO_OSD_PATH"flash_auto.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FLASH_OFF">CAMCO_OSD_PATH"flash_off.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FLASH_FORCE_ON">CAMCO_OSD_PATH"flash_force_on.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FLASH_RED_EYE">CAMCO_OSD_PATH"flash_red_eye.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_HIGHLIGHT_ON">CAMCO_OSD_PATH"highlight_on.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFRANGE_MACRO">CAMCO_OSD_PATH"afrange_macro.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFRANGE_INFINITE">CAMCO_OSD_PATH"afrange_infinite.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SELFTIMER_5S">CAMCO_OSD_PATH"selftimer_5s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SELFTIMER_10S">CAMCO_OSD_PATH"selftimer_10s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_100">CAMCO_OSD_PATH"iso_100.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_200">CAMCO_OSD_PATH"iso_200.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_400">CAMCO_OSD_PATH"iso_400.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_800">CAMCO_OSD_PATH"iso_800.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ISO_1600">CAMCO_OSD_PATH"iso_1600.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_DAYLIGHT">CAMCO_OSD_PATH"wb_daylight.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_TUNGSTEN">CAMCO_OSD_PATH"wb_tungsten.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_FLUORESCENT">CAMCO_OSD_PATH"wb_fluorescent.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_CLOUDY">CAMCO_OSD_PATH"wb_cloudy.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_WB_INCANDESCENT">CAMCO_OSD_PATH"wb_incandescent.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STORAGE_PHONE">CAMCO_OSD_PATH"storage_phone.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STORAGE_MEMORY_CARD">CAMCO_OSD_PATH"storage_memory_card.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_STORAGE_OTG">CAMCO_OSD_PATH"storage_mass_device.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_FINE">CAMCO_OSD_PATH"capqty_fine.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_GOOD">CAMCO_OSD_PATH"capqty_good.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_NORMAL">CAMCO_OSD_PATH"capqty_normal.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPQTY_LOW">CAMCO_OSD_PATH"capqty_normal.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_AEMETER_SPOT">CAMCO_OSD_PATH"aemeter_spot.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AEMETER_CENTER_WEIGHT">CAMCO_OSD_PATH"aemeter_center_weight.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AEMETER_AVERAGE">CAMCO_OSD_PATH"aemeter_average.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMESTAMP_ON">CAMCO_OSD_PATH"time_stamp.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_SQCIF">CAMCO_OSD_PATH"recsize_sqcif.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_QQVGA">CAMCO_OSD_PATH"recsize_qqvga.bmp"</IMAGE>		
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_QCIF">CAMCO_OSD_PATH"recsize_qcif.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_QVGA">CAMCO_OSD_PATH"recsize_qvga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_CIF">CAMCO_OSD_PATH"recsize_cif.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_WQVGA">CAMCO_OSD_PATH"recsize_wqvga.bmp"</IMAGE>       
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_CIF2">CAMCO_OSD_PATH"recsize_cif2.bmp"</IMAGE> 
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_HVGA">CAMCO_OSD_PATH"recsize_hvga.bmp"</IMAGE>           
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_nHD">CAMCO_OSD_PATH"recsize_nhd.bmp"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_VGA">CAMCO_OSD_PATH"recsize_vga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_D1">CAMCO_OSD_PATH"recsize_d1.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_D12">CAMCO_OSD_PATH"recsize_d12.bmp"</IMAGE>       
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_WVGA">CAMCO_OSD_PATH"recsize_wvga.bmp"</IMAGE>      
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_SVGA">CAMCO_OSD_PATH"recsize_svga.bmp"</IMAGE>    
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_WVGA2">CAMCO_OSD_PATH"recsize_wvga2.bmp"</IMAGE>          
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_XGA">CAMCO_OSD_PATH"recsize_xga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_720P">CAMCO_OSD_PATH"recsize_720p.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_4VGA">CAMCO_OSD_PATH"recsize_4vga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_SXGA">CAMCO_OSD_PATH"recsize_sxga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_16CIF">CAMCO_OSD_PATH"recsize_16cif.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_4SVGA">CAMCO_OSD_PATH"recsize_4svga.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_FHD">CAMCO_OSD_PATH"recsize_fhd.bmp"</IMAGE>        
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_4CIF">CAMCO_OSD_PATH"recsize_4cif.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECSIZE_FWVGA">CAMCO_OSD_PATH"recsize_fwvga.bmp"</IMAGE>        
    #ifdef MMI_CAMCO_WALLPAPER      
        <IMAGE id="IMG_ID_CAMCO_RECSIZE_WALLPAPER">CAMCO_OSD_PATH"recsize_wallpaper.bmp"</IMAGE>  
    #endif
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT_95K">CAMCO_OSD_PATH"sizelimit_95k.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT_195K">CAMCO_OSD_PATH"sizelimit_195k.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SIZELIMIT_295K">CAMCO_OSD_PATH"sizelimit_295k.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT_15S">CAMCO_OSD_PATH"timelimit_15s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT_30S">CAMCO_OSD_PATH"timelimit_30s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIMELIMIT_60S">CAMCO_OSD_PATH"timelimit_60s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_TIME_15S">CAMCO_OSD_PATH"timelimit_15s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_TIME_30S">CAMCO_OSD_PATH"timelimit_30s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_TIME_60S">CAMCO_OSD_PATH"timelimit_60s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_SIZE_95K">CAMCO_OSD_PATH"sizelimit_95k.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_SIZE_195K">CAMCO_OSD_PATH"sizelimit_195k.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_SIZE_295K">CAMCO_OSD_PATH"sizelimit_295k.bmp"</IMAGE>
    
    <IMAGE id="IMG_ID_CAMCO_TIME_LAPSE_ON">CAMCO_OSD_PATH"time_lapse.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_TIME_5MIN">CAMCO_OSD_PATH"timelimit_5min.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_LIMIT_TIME_10MIN">CAMCO_OSD_PATH"timelimit_10min.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISQTY_FINE">CAMCO_OSD_PATH"visqty_fine.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISQTY_GOOD">CAMCO_OSD_PATH"visqty_good.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISQTY_NORMAL">CAMCO_OSD_PATH"visqty_normal.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_VISQTY_LOW">CAMCO_OSD_PATH"visqty_mms.bmp"</IMAGE>    
    #ifdef MMI_CAMCO_WALLPAPER
        <IMAGE id="IMG_ID_CAMCO_VISQTY_WALLPAPER">CAMCO_OSD_PATH"visqty_wallpaper.bmp"</IMAGE>  
    #endif      
    <IMAGE id="IMG_ID_CAMCO_AFMODE_SINGLE">CAMCO_OSD_PATH"afmode_single.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_AFMODE_CONT">CAMCO_OSD_PATH"afmode_cont.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_RECAUD_OFF">CAMCO_OSD_PATH"recaud_off.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_FACEDETECT_ON">CAMCO_OSD_PATH"face_tracer.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_EMPTY_MAIN_ICON">CAMCO_OSD_PATH"empty_main_icon.bmp"</IMAGE>
#ifdef __MMI_CAMCO_FEATURE_CAM_AUTORAMA_SHOT__
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_DIR_UP">CAMCO_OSD_PATH"Autorama_dir_up.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_DIR_DOWN">CAMCO_OSD_PATH"Autorama_dir_down.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_DIR_LEFT">CAMCO_OSD_PATH"Autorama_dir_left.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_DIR_RIGHT">CAMCO_OSD_PATH"Autorama_dir_right.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_DETECT_REC">CAMCO_OSD_PATH"Autorama_detect_rec.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_AUTORAMA_SHOT">CAMCO_OSD_PATH"Autorama_detect_rec.bmp"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_CAM_MULTI_ANGLE_VIEW_SHOT__
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_LATTICE_E">CAMCO_OSD_PATH"lattice_m.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_LATTICE_F">CAMCO_OSD_PATH"lattice_f.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_ARROW">CAMCO_OSD_PATH"arrow.png"</IMAGE>
     <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_PREVIEW_CENTER1">CAMCO_OSD_PATH"focus_1.png"</IMAGE>
     <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_PREVIEW_CENTER2">CAMCO_OSD_PATH"focus_2.png"</IMAGE>
     <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_PREVIEW_CENTER3">CAMCO_OSD_PATH"focus_3.png"</IMAGE>
     <IMAGE id="IMG_ID_CAMCO_CAPMODE_MAV_PREVIEW_CENTER4">CAMCO_OSD_PATH"focus_4.png"</IMAGE>
#endif
#ifdef __MMI_CAMCORDER_SLIM__
#ifdef HORIZONTAL_CAMERA
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_SEL">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_EMPTY">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la_empty.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_SEL">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_EMPTY">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra_empty.png"</IMAGE>
#else
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA">CAMCO_OSD_PORTRAIT_PATH"iconlist_la.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_empty.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_empty.png"</IMAGE>
#endif
#else
#ifdef HORIZONTAL_CAMERA
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_SEL">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_EMPTY">CAMCO_OSD_LANDSCAPE_PATH"iconlist_la_empty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_SEL">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_EMPTY">CAMCO_OSD_LANDSCAPE_PATH"iconlist_ra_empty.bmp"</IMAGE>
#else
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA">CAMCO_OSD_PORTRAIT_PATH"iconlist_la.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_LA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_empty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_ICONLIST_RA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_empty.bmp"</IMAGE>
#endif
#endif
#ifdef __MMI_SUBLCD__
    <IMAGE id="IMG_ID_CAMCO_PREVIEW_SUBLCD_ICON">CUST_IMG_PATH"\\\\SubLCD\\\\Active\\\\Camera\\\\SB_Camera.gif"</IMAGE>
#endif
#ifdef DUAL_CAMERA_SUPPORT
    #ifdef __MMI_CAMCORDER_SLIM__
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA">CAMCO_OSD_PORTRAIT_PATH"iconlist_la.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_empty.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_sel.png"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_empty.png"</IMAGE>
    #else
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA">CAMCO_OSD_PORTRAIT_PATH"iconlist_la.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_LA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_la_empty.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA_SEL">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_sel.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_SUBCAM_ICONLIST_RA_EMPTY">CAMCO_OSD_PORTRAIT_PATH"iconlist_ra_empty.bmp"</IMAGE>
    #endif
#endif
#ifdef __MMI_CAMCO_FEATURE_ADD_FRAME_COLOR_IDX__
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_0" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_1" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_2" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_3" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_4" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_5" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_6" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_7" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_8" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_9" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_COLON" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_colon.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_256X192_DASH" force_type="FORCE_BMP">CAMCO_TIMESTAMP_256X192_PATH"num_dash.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_0" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_1" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_2" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_3" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_4" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_5" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_6" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_7" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_8" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_9" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_COLON" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_colon.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_320X240_DASH" force_type="FORCE_BMP">CAMCO_TIMESTAMP_320X240_PATH"num_dash.bmp"</IMAGE>
#ifdef __MMI_CAMCO_FEATURE_CAM_IMGSZIE_SUPPORT_4M__
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_0" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_1" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_2" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_3" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_4" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_5" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_6" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_7" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_8" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_9" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_COLON" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_colon.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_288X216_DASH" force_type="FORCE_BMP">CAMCO_TIMESTAMP_288X216_PATH"num_dash.bmp"</IMAGE>
#endif
#ifdef __MMI_CAMCO_FEATURE_CAM_IMGSZIE_SUPPORT_5M__
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_0" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_1" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_2" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_3" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_4" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_4.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_5" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_5.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_6" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_6.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_7" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_7.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_8" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_8.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_9" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_9.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_COLON" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_colon.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CAMCO_TIME_STAMP_COLOR_IDX_324X243_DASH" force_type="FORCE_BMP">CAMCO_TIMESTAMP_324X243_PATH"num_dash.bmp"</IMAGE>
#endif
#endif
        
	<RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_OUT" proc="mmi_camco_removeable_storage_plug_out"/>

#ifdef __MMI_BI_DEGREE_MAIN_MENU_STYLE__    
    <MENUITEM id="MENU_ID_CAMCORDER_APP" str="MAIN_MENU_CAMCO_TEXT" img="MAIN_MENU_CAMCO_ICON" highlight="mmi_camco_hilight_app" shortcut="ON" shortcut_img="MAIN_MENU_CAMCO_ICON" launch="mmi_camco_launch"/>
    <MENUITEM id="MAIN_MENU_OPTION_CAMCORDER_APP" str="STR_ID_CAMCO_APP_NAME" img="IMG_ID_CAMCO_APP_ICON" highlight="mmi_camco_hilight_app"/>
#else   
    <MENUITEM id="MENU_ID_CAMCORDER_APP" str="STR_ID_CAMCO_APP_NAME" img="IMG_ID_CAMCO_APP_ICON" highlight="mmi_camco_hilight_app" shortcut="ON" shortcut_img="IMG_ID_CAMCO_APP_ICON" launch="mmi_camco_launch"/>    
#endif    

    <SCREEN id="SCR_ID_CAMCO_APP"/>
    <SCREEN id="SCR_ID_CAMCO_EXT_APP"/>
    <SCREEN id="SCR_GROUP_ID_CAMCO_APP"/>
    <SCREEN id="SCR_GROUP_ID_CAMCO_PARTIAL_APP"/>
    <SCREEN id="SCR_GROUP_ID_CAMCO_INT_APP"/>    
    <SCREEN id="SCR_GROUP_ID_CAMCO_EXT_APP"/>   
    
	<RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_SET_DEF_STORAGE" proc="mmi_camco_notify_storage_change_hdlr"/>    
	#ifdef __MMI_SCREEN_LOCK_ANY_TIME__   
	<RECEIVER id="EVT_ID_SCREEN_LOCK_KEY_PRE_LOCK_EVT_ROUTING" proc="mmi_camco_notify_screen_lock_hdlr"/>   
	#endif
    <AUDIO id="AUD_ID_CAMCO_COUNTDOWN">CUST_ADO_PATH"\\\\Camcorder\\\\count.wav"</AUDIO>
#if defined(MT6225) || defined(MT6253) || defined(MT6253T) || defined(MT6235) || defined(MT6235B)
    <AUDIO id="AUD_ID_CAMCO_CAPTURE_1">CUST_ADO_PATH"\\\\Camcorder\\\\pic_.wav"</AUDIO>
#else
    <AUDIO id="AUD_ID_CAMCO_CAPTURE_1">CUST_ADO_PATH"\\\\Camcorder\\\\pic.wav"</AUDIO>
#endif
    <AUDIO id="AUD_ID_CAMCO_CAPTURE_2">CUST_ADO_PATH"\\\\Camcorder\\\\pic1.wav"</AUDIO>
    <AUDIO id="AUD_ID_CAMCO_CAPTURE_3">CUST_ADO_PATH"\\\\Camcorder\\\\pic2.wav"</AUDIO>

    <CACHEDATA type="byte" id="NRRAM_CAMCO_BEFORE_SWITCH_CAPSIZE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> Byte Cache </DESCRIPTION>
    </CACHEDATA>
    

    <CACHEDATA type="short" id="NVRAM_CAM_FILENAME_SEQ_NO" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> CameraApp </DESCRIPTION>
    </CACHEDATA>    
    
    <CACHEDATA type="short" id="NVRAM_VDOREC_FILENAME_SEQ_NO">
        <DEFAULT_VALUE> [0xFF, 0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> Short Cache </DESCRIPTION>
    </CACHEDATA>    
        
#endif

</APP>
