#ifndef _BROWSER_SAP_H
#define _BROWSER_SAP_H

    MSG_ID_WAP_MMI_LAUNCH_BROWSER_REQ,
    MSG_ID_WAP_MMI_LAUNCH_BROWSER_RSP,
    MSG_ID_WAP_SELECT_BOOKMARK_REQ,
    MSG_ID_WAP_SELECT_BOOKMARK_RSP,
    MSG_ID_WAP_BROWSER_STARTUP_REQ,  /* Q03C BRA Only */
    MSG_ID_WAP_SCHEME_HANDLE_REQ,    /* Q03C BRA Only */
    MSG_ID_WAP_SCHEME_HANDLE_RSP,    /* Q03C BRA Only */
    MSG_ID_WAP_DESTROY_UI_REQ,       /* Q03C BRA Only */
    MSG_ID_WAP_DESTROY_UI_RSP,       /* Q03C BRA Only */
    MSG_ID_MMI_FULL_HTML_BROWSER_POWEROFF_REQ, /* Full HTML browser only */
    MSG_ID_MMI_FULL_HTML_BROWSER_POWEROFF_RSP, /* Full HTML browser only */
    MSG_ID_MMI_FULL_HTML_BROWSER_RESTORE_FACTORY_SETTING_REQ, /* Full HTML browser only */
    MSG_ID_MMI_FULL_HTML_BROWSER_RESTORE_FACTORY_SETTING_CNF, /* Full HTML browser only */
#endif  /* _BROWSER_SAP_H */
