#ifndef _MMS_SAP_H
#define _MMS_SAP_H

	MSG_ID_MMI_MMS_VENDOR_CREATE_REQ,
	MSG_ID_MMI_MMS_VENDOR_CREATE_RSP,
	MSG_ID_MMI_MMS_VENDOR_SEND_REQ,
	MSG_ID_MMI_MMS_VENDOR_SEND_RSP,
    MSG_ID_MMI_MMS_VENDOR_CANCEL_SEND_REQ,
	MSG_ID_MMI_MMS_VENDOR_DELETE_REQ,
	MSG_ID_MMI_MMS_VENDOR_DELETE_RSP,    
    MSG_ID_MMI_MMS_GET_ASM_MEM_PTR_REQ,
	MSG_ID_MMI_MMS_GET_ASM_MEM_PTR_RSP,
	MSG_ID_MMI_MMS_FREE_ASM_MEM_PTR_REQ,
	MSG_ID_MMI_MMS_FREE_ASM_MEM_PTR_RSP,
	MSG_ID_MMI_MMS_GET_DEINIT_SERVICE_ASM_REQ,
	MSG_ID_MMI_MMS_GET_DEINIT_SERVICE_ASM_RSP,

#endif  /* End of _MMS_SAP_H */
