#ifndef _PROFILE_SAP_H
#define _PROFILE_SAP_H

    MSG_ID_WAP_GET_PROF_LIST_REQ,
    MSG_ID_WAP_GET_PROF_LIST_RSP,
    MSG_ID_WAP_GET_PROF_CONTENT_REQ,
    MSG_ID_WAP_GET_PROF_CONTENT_RSP,	
    MSG_ID_WAP_GET_BRA_PROF_ID_REQ,	
    MSG_ID_WAP_GET_BRA_PROF_ID_RSP,	
    MSG_ID_WAP_PROF_ACCESS_REQ, /* Q03C Only, obsolete */
    
#endif  /* _PROFILE_SAP_H */
