
 
    MSG_ID_WAP_MMA_UC_START_REQ,
    MSG_ID_WAP_MMA_UC_START_RSP,

    MSG_ID_MMS_BGSR_SEND_REQ,
    MSG_ID_MMS_BGSR_SEND_RSP,

    MSG_ID_MMS_BGSR_DOWNLOAD_REQ,
    MSG_ID_MMS_BGSR_DOWNLOAD_RSP,

    MSG_ID_MMS_BGSR_NO_PROGRESSING_DOWNLOAD_REQ,

    MSG_ID_MMS_BGSR_CANCEL_SEND_REQ,
    MSG_ID_MMS_BGSR_CANCEL_SEND_RSP,

    MSG_ID_MMS_BGSR_CANCEL_DOWNLOAD_REQ,
    MSG_ID_MMS_BGSR_CANCEL_DOWNLOAD_RSP,
    
    MSG_ID_MMS_BGSR_NAV_ACTIVATE_BGSR_REQ,
    MSG_ID_MMS_BGSR_NAV_ACTIVATE_BGSR_RSP,

    MSG_ID_MMS_BGSR_CHANGE_MSG_REQ,

    MSG_ID_MMS_BGSR_DELETE_MSG_RSP,

    MSG_ID_MMS_BGSR_DELETE_ALL_INBOX_RSP,

    MSG_ID_MMS_BGSR_CANCEL_ALL_INBOX_RSP,

    MSG_ID_MMS_BGSR_DELETE_ALL_OUTBOX_RSP,
    
    MSG_ID_MMS_BGSR_MOVE_TO_FOLDER_RSP,

    MSG_ID_MMS_BGSR_CHANGE_MSG_BGSR_NOTIFY_IND,

    MSG_ID_MMS_BGSR_GET_MSG_INFO_REQ,

    MSG_ID_MMS_BGSR_UPDATE_FOLDER_IND,
    MSG_ID_MMS_BGSR_UPDATE_MENU_IND,
    MSG_ID_MEA_STARTUP_REQ,
    MSG_ID_MEA_SHUTDOWN_REQ,
    MSG_ID_MMS_LAUNCH_BROWSER_REQ,

    MSG_ID_MEA_STARTUP_NEW_MMS_REQ,
    MSG_ID_MEA_UM_ENTRY_REQ,
    MSG_ID_MEA_PHB_ADDR_INPUT_IND,
    MSG_ID_MEA_INSERT_TEXT_REQ,
    MSG_ID_MMS_NMGR_INFO_REQ,
    MSG_ID_MMS_NMGR_INFO_RSP,
	MSG_ID_MMS_OBJ_IND,
	MSG_ID_MMS_OBJ_RES,
    MSG_ID_MEA_TERMINATE_IND,
    MSG_ID_MEA_SET_PROFILE_REQ,
    MSG_ID_MEA_SET_PROFILE_RSP,
    MSG_ID_MEA_ADD_BOOKMARK_REQ,
    MSG_ID_MEA_ADD_BOOKMARK_RSP,
    MSG_ID_MMS_READY_IND,
    MSG_ID_MMS_TERMINATE_IND,

    MSG_ID_MEA_SET_SETTING_REQ,
    MSG_ID_MEA_SET_SETTING_RSP,
    MSG_ID_MEA_GET_SETTING_REQ,
    MSG_ID_MEA_GET_SETTING_RSP,
