/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   BarcodeReaderMenuItems.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Camera menu items id define. 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

    /******** Start of ID ********/
    //MENU_ID_BARCODEREADER_APP, 
    MENU_ID_BARCODEREADER_OPTION,

    MENU_ID_BARCODEREADER_OPTION_SETTINGS,
    MENU_ID_BARCODEREADER_OPTION_STORAGE,

    /******** Interface to applications *********/
    MENU_ID_BARCODEREADER_APP_TO_VCARD,
    MENU_ID_BARCODEREADER_APP_TO_DTXT,
    MENU_ID_BARCODEREADER_APP_TO_BUSINESS,
    MENU_ID_BARCODEREADER_APP_TO_WAPSELL,
    MENU_ID_BARCODEREADER_APP_TO_SMSSELL,
    MENU_ID_BARCODEREADER_APP_TO_IVRSELL,
    MENU_ID_BARCODEREADER_APP_TO_EMAIL,
    MENU_ID_BARCODEREADER_APP_TO_SMS,
    MENU_ID_BARCODEREADER_APP_TO_GENERAL,
    
    /******** functions **********/
    MENU_ID_BARCODEREADER_FUNC_EDIT_BY_SMS,
    MENU_ID_BARCODEREADER_FUNC_EDIT_BY_MMS,
    MENU_ID_BARCODEREADER_FUNC_EXIT,
    MENU_ID_BARCODEREADER_FUNC_EDIT_BY_EMAIL,
    MENU_ID_BARCODEREADER_FUNC_SAVE,
    
    /*SMS*/
    MENU_ID_BARCODEREADER_FUNC_SEND_BY_SMS_SPEC,
    MENU_ID_BARCODEREADER_FUNC_SEND_BY_SMS,
    MENU_ID_BARCODEREADER_FUNC_SAVE_SMS, 
    MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER,
    MENU_ID_BARCODEREADER_FUNC_PREVIEW,
    MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN,

    /*VCARD*/
    MENU_ID_BARCODEREADER_FUNC_SAVE_TO_PHONEBOOK,
    /*MENU_ID_BARCODEREADER_FUNC_SEND_BY_SMS*/
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW,*/
    /*MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN,*/

    /*txt*/
    /*MENU_ID_BARCODEREADER_FUNC_SEND_BY_SMS*/
    MENU_ID_BARCODEREADER_FUNC_SEND_BY_MMS,
    MENU_ID_BARCODEREADER_FUNC_SEND_BY_EMAIL,
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW*/
    /*MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN*/

    /*mail*/
    /*MENU_ID_BARCODEREADER_FUNC_SEND_BY_EMAIL*/
    MENU_ID_BARCODEREADER_FUNC_SAVE_EMAIL,
    MENU_ID_BARCODEREADER_FUNC_SEND_BY_EMAIL_SPEC,
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW*/
    /*MEN_ID_BARCODEREADER_FUNC_BACK_TO_MAIN*/

    /*wap sell*/
    MENU_ID_BARCODEREADER_FUNC_OPEN_URL, 
    MENU_ID_BARCODEREADER_FUNC_SAVE_URL,
    MENU_ID_BARCODEREADER_FUNC_COMMEND,
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW*/
    /*MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN*/

    /*sms sell*/
    MENU_ID_BARCODEREADER_FUNC_ORDER,
    /*MENU_ID_BARCODEREADER_FUNC_COMMEND*/
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW*/
    /*MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN*/

    /*ivr sell*/
    MENU_ID_BARCODEREADER_FUNC_MAKE_CALL,
    MENU_ID_BARCODEREADER_FUNC_IVR,
    /*MENU_ID_BARCODEREADER_FUNC_COMMEND*/
    /*MENU_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER*/
    /*MENU_ID_BARCODEREADER_FUNC_PREVIEW*/
    /*MENU_ID_BARCODEREADER_FUNC_BACK_TO_MAIN*/
    
    /*file list option*/
    MENU_ID_BARCODEREADER_FILE_LIST,
    MENU_ID_BARCODEREADER_FILE_OPEN,
    MENU_ID_BARCODEREADER_FILE_DELETE,
    MENU_ID_BARCODEREADER_FILE_DELETE_ALL,

    /******** filemgr **********/
    MENU_ID_BARCODEREADER_FILE_OPTION,
    MENU_ID_BARCODEREADER_FILE_OPTION_NO_SIM,
    MENU_ID_BARCODEREADER_TO_QRV_EDITOR,
    MENU_ID_BARCODEREADER_OPEN_POS,
    
    /******** bookmark **********/
    MENU_ID_BARCODEREADER_BOOKMARK,
    MENU_ID_BARCODEREADER_BOOKMARK_OPEN,
    MENU_ID_BARCODEREADER_BOOKMARK_REN,
    MENU_ID_BARCODEREADER_BOOKMARK_DEL,
    MENU_ID_BARCODEREADER_BOOKMARK_DELALL,
    MENU_ID_BARCODEREADER_BOOKMARK_EDIT_OPTION,
    MENU_ID_BARCODEREADER_BOOKMARK_EDIT_DONE,
    MENU_ID_BARCODEREADER_BOOKMARK_EDIT_METHORD,
    MENU_ID_BARCODEREADER_INPUT_WAP,
    /*menu id of new architecture */
    MENU_ID_BARCODEREADER_APP,
    MENU_ID_BARCODEREADER_HISTORY, 
    MENU_ID_BARCODEREADER_CALL,
    MENU_ID_BARCODEREADER_SMS, 
    MENU_ID_BARCODEREADER_SETTING,

    /*history submenu */
    MENU_ID_BARCODEREADER_HISTORY_SELECT,
    MENU_ID_BARCODEREADER_HISTORY_RENAME,
    MENU_ID_BARCODEREADER_HISTORY_DELETE,
    MENU_ID_BARCODEREADER_HISTORY_DELETE_ALL,
    
    /*call submenu */
    MENU_ID_BARCODEREADER_CALL_MAKE,
    MENU_ID_BARCODEREADER_CALL_SAVE_TO_PHB,
    
    /*sms submenu */
    MENU_ID_BARCODEREADER_SMS_SEND,
    MENU_ID_BARCODEREADER_SMS_SAVE,
        
    /*setting submenu */
    MENU_ID_BARCODEREADER_SETTING_DM,
    MENU_ID_BARCODEREADER_SETTING_CAMERA,
    
    
   /******** End of ID ********/

