/***********************************************
File name : MTPNP_AD_Menudef.h
Contents : dual sim menu define
History : Create by : Zhang Nan, Aug 2, 2007
************************************************/
/* #ifdef __MERCURY_MASTER__ */
MENU_MTPNP_SETTING,

/* dual mode setting begin */
MENU_MTPNP_DM_SETTING,
MENU_MTPNP_DM_DUALCARD,
MENU_MTPNP_DM_CARD1,
MENU_MTPNP_DM_CARD2,
MENU_MTPNP_DM_FLIGHT,
#ifdef __DM_PWR_ON_QUERY_SUPPORT__
/* under construction !*/
#endif /* __DM_PWR_ON_QUERY_SUPPORT__ */
/* dual mode setting end */

/* startup option begin */
#ifdef __DM_PWR_ON_QUERY_SUPPORT__
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif /* __DM_PWR_ON_QUERY_SUPPORT__ */
/* startup option end */

/* call history begin */
MENU_MTPNP_DM_CALL_HISTORY,
MENU_MTPNP_CALL_HISTORY,
MENU_MTPNP_CALL_HISTORY_MISSED,
MENU_MTPNP_CALL_HISTORY_DIALED,
MENU_MTPNP_CALL_HISTORY_RECVD,
MENU_MTPNP_CALL_HISTORY_DELETE,
MENU_MTPNP_CALL_HISTORY_CALLTIME,
MENU_MTPNP_CALL_HISTORY_CALLCOST,
MENU_MTPNP_CALL_HISTORY_SMSCOUNTER,
MENU_MTPNP_CALL_HISTORY_GPRSCOUNTER,
MENU_MTPNP_CALL_HISTORY_SENT,
MENU_MTPNP_CALL_HISTORY_RECEIVED,
MENU_MTPNP_DELLOG_MISSED_CALLS,
MENU_MTPNP_DELLOG_DIALED_CALLS, 
MENU_MTPNP_DELLOG_RECEIVED_CALLS, 
MENU_MTPNP_ALL_CALLS,
MENU_MTPNP_LAST_CALL_TIME, 
MENU_MTPNP_CALL_OUT_TIME,
MENU_MTPNP_CALL_IN_TIME, 
MENU_MTPNP_ALL_CALL_TIME, 
MENU_MTPNP_CALL_COST_LASTCALL,
MENU_MTPNP_CALL_COST_ALLCOST,
MENU_MTPNP_CALL_COST_RESETCOUNTER,
MENU_MTPNP_CALL_COST_MAXCOUNT,
MENU_MTPNP_CALL_COST_PRICEUNIT,
MENU_MTPNP_CALL_HISTORY_GPRS_LASTSENT,
MENU_MTPNP_CALL_HISTORY_GPRS_LASTRECEIVED,
MENU_MTPNP_CALL_HISTORY_GPRS_ALLSENT,
MENU_MTPNP_CALL_HISTORY_GPRS_ALLRECEIVED,
MENU_MTPNP_CALL_HISTORY_GPRS_RESETCOUNTER,

MENU_ID_MTPNP_CHIST_CALL_LIST_OPTIONS,
MENU_ID_MTPNP_CHIST_CALL_LOG_OPTIONS,
MENU_ID_MTPNP_CHIST_CALL_LIST_VIEW,
MENU_ID_MTPNP_CHIST_CALL_LIST_CALL, 
MENU_ID_MTPNP_CHIST_CALL_LIST_SENDMSG,
MENU_ID_MTPNP_CHIST_CALL_LIST_SENDSMS,
MENU_ID_MTPNP_CHIST_CALL_LIST_SENDMMS,
MENU_ID_MTPNP_CHIST_CALL_LIST_SAVE,
MENU_ID_MTPNP_CHIST_CALL_LIST_ADD_BLIST,
MENU_ID_MTPNP_CHIST_CALL_LIST_EDIT,
MENU_ID_MTPNP_CHIST_CALL_LIST_CLEAR,
MENU_ID_MTPNP_CHIST_CALL_LIST_CLEAR_ALL,
MENU_ID_MTPNP_CHIST_CALL_LIST_ADVANCED,

MENU_MTPNP_MISSED_CALL_NOTIFY,
MENU_MTPNP_MISSED_CALL_NOTIFY_MASTER,
MENU_MTPNP_MISSED_CALL_NOTIFY_SLAVE,

MENU_MTPNP_SIM1_RECEIVED_NUM_CALL,
MENU_MTPNP_SIM1_DIALED_NUM_CALL,
MENU_MTPNP_SIM1_MISSED_NUM_CALL,

MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG,
MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG_MASTER,
MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG_SLAVE,

MENU_ID_CHIST_SIM2_HS_RE_OPT,
MENU_ID_CHIST_SIM2_HS_RE_OPT_VIEW,
MENU_ID_CHIST_SIM2_HS_RE_OPT_CALL,
MENU_ID_CHIST_SIM2_HS_RE_OPT_SEND_MSG,
MENU_ID_CHIST_SIM2_HS_RE_OPT_SEND_MSG_SMS,
MENU_ID_CHIST_SIM2_HS_RE_OPT_SEND_MSG_MMS,
MENU_ID_CHIST_SIM2_HS_RE_OPT_SAVE_CONTACT,

/* call history end */

/* phone setting begin */
MENU_MTPNP_PHONE_SETTING,
/* phone setting end */

/* card2 msisdn begin */
MENU_MTPNP_CARD2_PHBEXTRA,
/* MENU_MTPNP_DM_SHOW_OWNER_NUMBER, */
/* MENU_MTPNP_SHOW_CARD2_OWNER_NUMBER, */
/* card2 msidsn end */

/* phb extra number begin */
MENU_MTPNP_CARD2_OWNER_NUMBER_OPTION,
MENU_MTPNP_CARD2_OWNER_NUMBER_ERASE,
MENU_MTPNP_CARD2_OWNER_NUMBER_EDIT,
/* phb extra number end */

/* adn begin */
MENU_MTPNP_PB_DELALL_SIM2,
MENU_MTPNP_PB_COPY_SIM2TOPHONE,
MENU_MTPNP_PB_COPY_PHONETOSIM2,
MENU_MTPNP_PB_COPY_SIM2TOSIM1,
MENU_MTPNP_PB_COPY_SIM1TOSIM2,
MENU_MTPNP_PB_COPY_SIM1TOPHONE,
MENU_MTPNP_PB_COPY_PHONETOSIM1,

MENU_MTPNP_PB_COPYALL_SIM2TOPHONE,	
MENU_MTPNP_PB_COPYALL_PHONETOSIM2,
MENU_MTPNP_PB_COPYALL_SIM1TOSIM2,		
MENU_MTPNP_PB_COPYALL_SIM2TOSIM1,
MENU_MTPNP_PB_PRE_STORAGE_SIM2,
MENU_MTPNP_PHB_NLF_SIM2,

MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1,
MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2,
/* adn end */

/* fdn begin */
MENU_MTPNP_MENU_FDN_MODE,
MENU_MTPNP_MENU_FDN_LIST,
MENU_MTPNP_FDN_VIEW_OPTIONS_MAIN,
MENU_MTPNP_FDN_VIEW_OPTIONS_ADD,
MENU_MTPNP_FDN_VIEW_OPTIONS_EDIT,
MENU_MTPNP_FDN_VIEW_OPTIONS_DELETE,
/* fdn end */

/* bdn begin */
MENU_MTPNP_MENU_BDN_MODE,
MENU_MTPNP_MENU_BDN_LIST,
MENU_MTPNP_BDN_VIEW_OPTIONS_MAIN,
MENU_MTPNP_BDN_VIEW_OPTIONS_ADD,
MENU_MTPNP_BDN_VIEW_OPTIONS_EDIT,
MENU_MTPNP_BDN_VIEW_OPTIONS_DELETE,
/* bdn end */

/* plmn begin */
MENU_MTPNP_MODE_SETTING,
MENU_MTPNP_DM_NETWORK_SETUP,
MENU_MTPNP_NETWORK_SETUP,
MENU_MTPNP_SELECTION_MODE,
MENU_MTPNP_PREFERRED_NETWORKS,
MENU_MTPNP_GPRS_CONNECTION,
MENU_MTPNP_NETSET_PCH_MODE,
MENU_MTPNP_SELECTION_MODE_MANUAL,
MENU_MTPNP_SELECTION_MODE_AUTOMATIC,
MENU_MTPNP_SELECTION_MODE_CHOICE,
MITEM_MTPNP_PRF_NWK_OPTIONS_PSEUDO,
MITEM_MTPNP_PRR_NWK_ADD,
MITEM_MTPNP_PRR_NWK_NEW,
MITEM_MTPNP_PRR_NWK_DELETE,
MITEM_MTPNP_PRR_NWK_EDIT,
MENU_MTPNP_ADD_FROM_LIST_OPTIONS,
MENU_MTPNP_ADD_FROM_LIST_DONE,
MENU_MTPNP_ADD_FROM_LIST_SORT_BY_DEFAULT,
MENU_MTPNP_ADD_FROM_LIST_SORT_BY_ALPHABET,
MENU_MTPNP_NETSET_NETWORK_INFO,
/* plmn end */

/* voice mail begin */
/* voice mail end */

/* message setup begin */
/* message setup end */

/* vcard begin */
MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM,
/* vcard end */

/* sms begin */
/* sms end */

/* sms show begin */
/* sms feature: support selce item */
/* sms feature: support selce item when save sms from other module */
/* sms show end */


SLAVE_MITEM_DG_END_ALL,

/* security setting begin */
MENU_MTPNP_DM_SECURITY_SETTING,
MENU_MTPNP_SECURITY_SETTING,
MENU_MTPNP_SIM_LOCK,
MENU_MTPNP_CHANGE_PASSWORD,
MENU_MTPNP_CP_PIN1,
MENU_MTPNP_CP_PIN2,
/* security setting end */

SLAVE_MITEM_INC_ACT_OPT_HOLD_ACT,
SLAVE_MITEM_INC_ACT_OPT_END_ACT,
SLAVE_MITEM_INC_HLD_OPT_RTRV,
SLAVE_MITEM_INC_HLD_OPT_END,
SLAVE_MITEM_IMA_OPT_HOLD_CONF,
SLAVE_MITEM_IMA_OPT_SPLIT,
SLAVE_MITEM_IMA_OPT_END_ONE_ACT,
SLAVE_MITEM_IMA_OPT_END_ALL_ACT,
SLAVE_MITEM_INC_MHLD_OPT_RTRV,
SLAVE_MITEM_INC_MHLD_OPT_END,
SLAVE_MITEM_IAH_OPT_SWAP,
SLAVE_MITEM_IAH_OPT_CONFER,
SLAVE_MITEM_IAH_OPT_END_ACT,
SLAVE_MITEM_IAH_OPT_END_HLD,
SLAVE_MITEM_IAH_OPT_END_ALL,
SLAVE_MITEM2019_CM_ALL_ACTIVE_END,
SLAVE_MITEM_IAMH_ALL_HELD_END,
SLAVE_NON_ACTIVE_CALL_NET_ACTIVE_MASTER,
SLAVE_NON_ACTIVE_CALL_NET_ACTIVE_SLAVE,
SLAVE_MENU_CALL_MASTER_INCOMING_REJECT,
SLAVE_MENU_CALL_INCOMING_OPT_ANSWER_SLAVE,
SLAVE_MENU_CALL_INCOMING_OPT_REJECT_SLAVE,
SLAVE_MENU_CALL_INCOMING_OPTION,
SLAVE_MENU_CM_INCOMING_AND_ACTIVE_MIX_OPTION,
SLAVE_MITEM_CM_SINGLE_MASTER_CALL_SWAP,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSKOPTIONS,
SLAVE_MITEM_CM_SINGLE_SLAVE_CALL_SWAP,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_ENDCALL,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_PB,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_SMS,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_DTMF,
SLAVE_NON_ACTIVE_CALL_NET_PARENT,
SLAVE_MENU_CC_MO_SELETECT_NET,
SLAVE_MENU_CC_MO_SELETECT_NET_CARD1,
SLAVE_MENU_CC_MO_SELETECT_NET_CARD2,
SLAVE_MENU_CC_CSK_SELETECT_CARD,
SLAVE_MENU_CC_CSK_SELETECT_CARD1,
SLAVE_MENU_CC_CSK_SELETECT_CARD2,
SLAVE_MENU_CALL_INCOMING_OPT_CARD1_IP_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_CARD2_IP_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_ACCEPT,
SLAVE_MENU_CALL_INCOMING_OPT_REJECT,
SLAVE_MENU_CALL_INCOMING_OPT_CARD1_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_CARD2_DIALBACK,
SLAVE_MENU_CALL_INCOMING_MIX_OPTION,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPT_BOTH,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_REJECT_BOTH,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPTCARD1,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPTCARD2,
MENU_MTPNP_SELECT_CARD,
MENU_MTPNP_SELECT_CARD_1SELECTED,
MENU_MTPNP_SELECT_CARD_2SELECTED,
/* #endif */ /* __MERCURY_MASTER__ */

