@echo off
echo ---------run copy_images.bat copy unziped images----------
echo [Dependency] plutommi\Customer\ResGenerator\%0
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JAVAAUD.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JAVAVIB.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JAVAVK.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JDATA.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JHEAP.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JNET.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_jvlogo.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JVST.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_jvstar1.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_jvstar2.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\JAVA\SB_JWPSET.* %1\MainLCD\Submenu2\Funandgame\JAVA\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Call\CC_callhistory.* %1\MainLCD\Submenu2\Call\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB1.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB10.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB11.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB12.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB13.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB14.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB15.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB16.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB17.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB18.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB19.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB2.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB20.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB21.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB22.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB23.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB24.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB25.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB26.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB27.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB28.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB29.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB3.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB30.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB4.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB5.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB6.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB7.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB8.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Listmenuicon\L_NB9.* %1\MainLCD\Submenu2\Listmenuicon\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\Inbox\SS_READ.* %1\MainLCD\Submenu2\Message\Inbox\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\Inbox\SS_UREAD.* %1\MainLCD\Submenu2\Message\Inbox\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\deliveryreport\mms_delivery.* %1\MainLCD\Submenu2\Message\MMS\deliveryreport\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\deliveryreport\mms_delivery_read.* %1\MainLCD\Submenu2\Message\MMS\deliveryreport\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\draft\mmsdraft.* %1\MainLCD\Submenu2\Message\MMS\draft\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\BCC.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\CC.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\Content.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\from.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\Layout.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\SB.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\size.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Editor\To.* %1\MainLCD\Submenu2\Message\MMS\Editor\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock_h.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock_L.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock_read.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock_read_h.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\lock\mms_lock_read_L.* %1\MainLCD\Submenu2\Message\MMS\lock\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_message.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_message_h.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_message_l.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_messageread.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_messageread_h.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\message\mms_messageread_l.* %1\MainLCD\Submenu2\Message\MMS\message\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\notification\notification.* %1\MainLCD\Submenu2\Message\MMS\notification\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\notification\notification_h.* %1\MainLCD\Submenu2\Message\MMS\notification\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\notification\notification_l.* %1\MainLCD\Submenu2\Message\MMS\notification\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\readreport\mms_read.* %1\MainLCD\Submenu2\Message\MMS\readreport\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\readreport\mms_read_read.* %1\MainLCD\Submenu2\Message\MMS\readreport\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Report\delivery_fail.* %1\MainLCD\Submenu2\Message\MMS\Report\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Report\delivery_success.* %1\MainLCD\Submenu2\Message\MMS\Report\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Report\read_fail.* %1\MainLCD\Submenu2\Message\MMS\Report\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Report\read_success.* %1\MainLCD\Submenu2\Message\MMS\Report\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Smil\attachfile.* %1\MainLCD\Submenu2\Message\MMS\Smil\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Smil\audio.* %1\MainLCD\Submenu2\Message\MMS\Smil\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\Smil\audio_mixed.* %1\MainLCD\Submenu2\Message\MMS\Smil\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\template\mmstemplate.* %1\MainLCD\Submenu2\Message\MMS\template\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\titlebar\Attachfile.* %1\MainLCD\Submenu2\Message\MMS\titlebar\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\titlebar\MMSC.* %1\MainLCD\Submenu2\Message\MMS\titlebar\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\MMS\titlebar\MMSR.* %1\MainLCD\Submenu2\Message\MMS\titlebar\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\Outbox\SS_SENT.* %1\MainLCD\Submenu2\Message\Outbox\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Message\Outbox\SS_UNSENT.* %1\MainLCD\Submenu2\Message\Outbox\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Organizer\Alarm\OA_STATU.* %1\MainLCD\Submenu2\Organizer\Alarm\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Phonebook\PBView\PV_INPH.* %1\MainLCD\Submenu2\Phonebook\PBView\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Phonebook\PBView\PV_INSIM.* %1\MainLCD\Submenu2\Phonebook\PBView\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\phonebook\SB_Search.* %1\MainLCD\Submenu2\phonebook\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\CSD.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\CSD_C.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\CSD_N.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\GPRS.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\GPRS_C.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\GPRS_N.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\KEY.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\SW_EREAD.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\SW_EUNREAD.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\SW_READ.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\wap\SW_UNREAD.* %1\MainLCD\Submenu2\Services\wap\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Services\SB_WAP.* %1\MainLCD\Submenu2\Services\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\settings\Poweronoff\ST_POFF.* %1\MainLCD\Submenu2\settings\Poweronoff\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\settings\Poweronoff\ST_PON.* %1\MainLCD\Submenu2\settings\Poweronoff\ > nul

xcopy /Y /Q /E %1\MainLCD\Submenu\settings\CertificateManager\CM_INTERMEDIATE.* %1\MainLCD\Submenu2\settings\CertificateManager\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\settings\CertificateManager\CM_PERSONAL.* %1\MainLCD\Submenu2\settings\CertificateManager\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\settings\CertificateManager\CM_ROOT.* %1\MainLCD\Submenu2\settings\CertificateManager\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\settings\CertificateManager\CM_USER.* %1\MainLCD\Submenu2\settings\CertificateManager\ > nul

xcopy /Y /Q /E %1\MainLCD\Submenu\SB_BG.* %1\MainLCD\Submenu2\ > nul

xcopy /Y /Q /E %1\MainLCD\SubMenu\Shortcut\SB_SC.* %1\MainLCD\Submenu2\Shortcut\ > nul
xcopy /Y /Q /E %1\MainLCD\SubMenu\Shortcut\arrow_up.* %1\MainLCD\Submenu2\Shortcut\ > nul
xcopy /Y /Q /E %1\MainLCD\SubMenu\Shortcut\arrow_down.* %1\MainLCD\Submenu2\Shortcut\ > nul
xcopy /Y /Q /E %1\MainLCD\SubMenu\Shortcut\arrow_left.* %1\MainLCD\Submenu2\Shortcut\ > nul
xcopy /Y /Q /E %1\MainLCD\SubMenu\Shortcut\arrow_right.* %1\MainLCD\Submenu2\Shortcut\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\UniMessage\Uni_MG.* %1\MainLCD\Submenu2\UniMessage\ > nul
xcopy /Y /Q /E %1\MainLCD\Submenu\Settings\File_corrupted.* %1\MainLCD\Submenu2\Settings\ > nul
@echo on
