/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2001
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   mmi.sap
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   l4 related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/

   /*---------------MMI_MSG_CODE_END---------------------*/
/*MTK:BEGIN:generate_mmi_msg_id_v2*/
	MSG_ID_MMI_L4_CODE_BEGIN = MSG_ID_L4A_CODE_BEGIN,
	MSG_ID_MMI_CC_RESET_ACM_REQ,
	MSG_ID_MOD_CSM_1_BEGIN	=	MSG_ID_MMI_CC_RESET_ACM_REQ,
	MSG_ID_MMI_CC_GET_ACM_REQ,
	MSG_ID_MMI_CC_SET_MAX_ACM_REQ,
	MSG_ID_MMI_CC_GET_MAX_ACM_REQ,
	MSG_ID_MMI_CC_RESET_CCM_REQ,
	MSG_ID_MMI_CC_GET_CCM_REQ,
	MSG_ID_MMI_CC_SET_CUG_REQ,
	MSG_ID_MMI_CC_CHLD_REQ,
	MSG_ID_MMI_CC_ATH_REQ,
	MSG_ID_MMI_CC_GET_CALL_LIST_REQ,
	MSG_ID_MMI_CC_CALL_DEFLECT_REQ,
	MSG_ID_MMI_CC_START_DTMF_REQ,
	MSG_ID_MMI_CC_STOP_DTMF_REQ,
	MSG_ID_MMI_CC_START_AUTO_DTMF_REQ,
	MSG_ID_MMI_CC_ATA_REQ,
	MSG_ID_MMI_CC_DIAL_REQ,
	MSG_ID_MMI_CC_REL_COMP_REQ,
	MSG_ID_MMI_CC_CALL_PRESENT_RES_REQ,
	MSG_ID_MMI_CC_CPI_REQ,
	MSG_ID_MMI_DATA_CALL_RES_REQ,
	MSG_ID_MMI_SS_EMLPP_REQ,
	MSG_ID_MMI_SS_CALL_FORWARD_REQ,
	MSG_ID_MMI_SS_CALL_WAIT_REQ,
	MSG_ID_MMI_SS_CALL_BARRING_REQ,
	MSG_ID_MMI_SS_USSD_REQ,
	MSG_ID_MMI_SS_CHANGE_PASSWORD_REQ,
	MSG_ID_MMI_SS_PARSING_STRING_REQ,
	MSG_ID_MMI_SS_OPERATION_REQ,
	MSG_ID_MMI_SS_CCBS_REQ,
	MSG_ID_MMI_SS_ABORT_REQ,
	MSG_ID_MMI_SS_SET_CLIR_FLAG_REQ,
	MSG_ID_MMI_SS_ACK_REQ,
	MSG_ID_MOD_CSM_1_END	=	MSG_ID_MMI_SS_ACK_REQ,

	MSG_ID_MMI_EQ_SET_VOLUME_REQ,
	MSG_ID_MOD_UEM_2_BEGIN	=	MSG_ID_MMI_EQ_SET_VOLUME_REQ,
	MSG_ID_MMI_EQ_SET_MUTE_REQ,
	MSG_ID_MMI_EQ_SET_GPIO_LEVEL_REQ,
	MSG_ID_MMI_EQ_GET_GPIO_LEVEL_REQ,
	MSG_ID_MMI_EQ_EXE_GPIO_LEVEL_REQ,
	MSG_ID_MMI_EQ_PLAY_AUDIO_REQ,
	MSG_ID_MMI_EQ_STOP_AUDIO_REQ,
	MSG_ID_MMI_EQ_PLAY_EXT_IMELODY_REQ,
	MSG_ID_MMI_EQ_GPIO_DETECT_RES_REQ,
	MSG_ID_MMI_EQ_SET_SPEECH_MODE_REQ,
	MSG_ID_MMI_EQ_PLAY_AUDIO_BY_NAME_REQ,
	MSG_ID_MMI_EQ_STOP_AUDIO_BY_NAME_REQ,
	MSG_ID_MMI_EQ_SET_AUDIO_PROFILE_REQ,
	MSG_ID_MMI_EQ_GET_AUDIO_PROFILE_REQ,
	MSG_ID_MMI_EQ_SET_AUDIO_PARAM_REQ,
	MSG_ID_MMI_EQ_GET_AUDIO_PARAM_REQ,
	MSG_ID_MMI_EQ_START_ADC_ALL_CHANNEL_REQ,
	MSG_ID_MMI_EQ_STOP_ADC_ALL_CHANNEL_REQ,
	MSG_ID_MMI_EQ_SET_AUDIO_MODE_REQ,
	MSG_ID_MMI_EQ_PLAY_PATTERN_REQ,
	MSG_ID_MMI_EQ_SET_HW_LEVEL_REQ,
	MSG_ID_MMI_EQ_GET_HW_LEVEL_REQ,
	MSG_ID_MMI_EQ_SET_SLEEP_MODE_REQ,
	MSG_ID_MMI_EQ_QUERY_HAND_FREE_MODE_RES_REQ,
	MSG_ID_MMI_EQ_SET_CAM_RES_REQ,
	MSG_ID_MMI_EQ_SET_AVR_RES_REQ,
	MSG_ID_MMI_EQ_SET_RTC_TIME_REQ,
	MSG_ID_MMI_EQ_EXE_RTC_TIMER_REQ,
	MSG_ID_MMI_EQ_GET_RTC_TIME_REQ,
	MSG_ID_MMI_EQ_DEL_RTC_TIMER_REQ,
	MSG_ID_MMI_EQ_EXE_DEL_RTC_TIMER_REQ,
	MSG_ID_MMI_EQ_SET_DATE_TIME_FORMAT_REQ,
	MSG_ID_MMI_AT_ALARM_QUERY_RES_REQ,
	MSG_ID_MMI_AT_ALARM_SET_RES_REQ,
	MSG_ID_MMI_AT_ALARM_DELETE_RES_REQ,
	MSG_ID_MMI_AT_CBKLT_QUERY_RES_REQ,
	MSG_ID_MMI_AT_KEYPAD_EVENT_OUTPUT_REQ,
	MSG_ID_MMI_EQ_SET_LANGUAGE_REQ,
	MSG_ID_MMI_EQ_GET_EQUIP_ID_REQ,
	MSG_ID_MMI_EQ_POWER_ON_REQ,
	MSG_ID_MMI_EQ_POWER_OFF_REQ,
	MSG_ID_MMI_EQ_CANCEL_LOCK_POWERON_REQ,
	MSG_ID_MMI_EQ_PMIC_CONFIG_REQ,
	MSG_ID_MMI_EQ_BATTERY_STATUS_RES_REQ,
	MSG_ID_MMI_EQ_RF_TEST_GSM_REQ,
	MSG_ID_MMI_EQ_FM_RADIO_CONFIG_REQ,
	MSG_ID_MMI_EQ_RF_TEST_WIFI_REQ,
	MSG_ID_MMI_EQ_CALL_STATUS_REQ,
	MSG_ID_MMI_EQ_QUERY_CAL_DATA_DL_STATUS_REQ,
	MSG_ID_MOD_UEM_2_END	=	MSG_ID_MMI_EQ_QUERY_CAL_DATA_DL_STATUS_REQ,

	MSG_ID_MMI_EQ_NVRAM_READ_REQ,
	MSG_ID_MOD_NVRAM_3_BEGIN	=	MSG_ID_MMI_EQ_NVRAM_READ_REQ,
	MSG_ID_MMI_EQ_NVRAM_WRITE_REQ,
	MSG_ID_MMI_EQ_NVRAM_RESET_REQ,
	MSG_ID_MMI_EQ_SET_UART_REQ,
	MSG_ID_MMI_EQ_GET_UART_REQ,
	MSG_ID_MMI_ATTACH_UART_PORT_REQ,
	MSG_ID_MMI_DETACH_UART_PORT_REQ,
	MSG_ID_MMI_EQ_DCM_ENABLE_REQ,
	MSG_ID_MOD_NVRAM_3_END	=	MSG_ID_MMI_EQ_DCM_ENABLE_REQ,

	MSG_ID_MMI_NW_GET_IMEI_REQ,
	MSG_ID_MOD_RAC_4_BEGIN	=	MSG_ID_MMI_NW_GET_IMEI_REQ,
	MSG_ID_MMI_NW_ABORT_PLMN_LIST_REQ,
	MSG_ID_MMI_NW_SET_ATTACH_REQ,
	MSG_ID_MMI_NW_SET_PLMN_SELECT_MODE_REQ,
	MSG_ID_MMI_NW_GET_PLMN_SELECT_MODE_REQ,
	MSG_ID_MMI_NW_SET_GPRS_TRANSFER_PREFERENCE_REQ,
	MSG_ID_MMI_NW_GET_GPRS_TRANSFER_PREFERENCE_REQ,
	MSG_ID_MMI_NW_SET_PLMN_REQ,
	MSG_ID_MMI_NW_GET_PLMN_LIST_REQ,
	MSG_ID_MMI_NW_GET_BAND_REQ,
	MSG_ID_MMI_NW_SET_PREFERRED_BAND_REQ,
	MSG_ID_MMI_NW_SET_GPRS_CONNECT_TYPE_REQ,
	MSG_ID_MMI_NW_GET_GPRS_CONNECT_TYPE_REQ,
	MSG_ID_MMI_NW_PWROFF_DETACH_REQ,
	MSG_ID_MMI_NW_CFUN_STATE_REQ,
	MSG_ID_MMI_NW_EFUN_STATE_REQ,
	MSG_ID_MMI_NW_GET_RAT_MODE_REQ,
	MSG_ID_MMI_NW_SET_RAT_MODE_REQ,
	MSG_ID_MMI_NW_GET_PREFER_RAT_REQ,
	MSG_ID_MMI_NW_SET_PREFER_RAT_REQ,
	MSG_ID_MMI_NW_SET_HSPA_MODE_REQ,
	MSG_ID_MMI_NW_GET_HSPA_MODE_REQ,
	MSG_ID_MMI_NW_SET_PLMN_LIST_PREFERENCE_REQ,
	MSG_ID_MMI_NW_GET_PLMN_LIST_PREFERENCE_REQ,
	MSG_ID_MMI_NW_END_PS_DATA_SESSION_REQ,
	MSG_ID_MOD_RAC_4_END	=	MSG_ID_MMI_NW_END_PS_DATA_SESSION_REQ,

	MSG_ID_MMI_SMU_GET_IMSI_REQ,
	MSG_ID_MOD_SMU_5_BEGIN	=	MSG_ID_MMI_SMU_GET_IMSI_REQ,
	MSG_ID_MMI_SMU_LOCK_REQ,
	MSG_ID_MMI_SMU_GET_DIAL_MODE_REQ,
	MSG_ID_MMI_SMU_VERIFY_PIN_REQ,
	MSG_ID_MMI_SMU_SET_PREFERRED_OPER_LIST_REQ,
	MSG_ID_MMI_SMU_GET_PREFERRED_OPER_LIST_REQ,
	MSG_ID_MMI_SMU_SET_PUC_REQ,
	MSG_ID_MMI_SMU_GET_PUC_REQ,
	MSG_ID_MMI_SMU_CHANGE_PASSWORD_REQ,
	MSG_ID_MMI_SMU_SET_DIAL_MODE_REQ,
	MSG_ID_MMI_SMU_WRITE_SIM_REQ,
	MSG_ID_MMI_SMU_READ_SIM_REQ,
	MSG_ID_MMI_SMU_POWER_OFF_REQ,
	MSG_ID_MMI_SIM_GET_GSMCDMA_DUALSIM_INFO_REQ,
	MSG_ID_MMI_SIM_SET_GSMCDMA_DUALSIM_MODE_REQ,
	MSG_ID_MMI_SMU_READ_FILE_INFO_REQ,
	MSG_ID_MMI_SMU_CHECK_PIN_STATUS_REQ,
	MSG_ID_MMI_SMU_SET_PERSONALIZATION_REQ,
	MSG_ID_MMI_SMU_SML_STATUS_REQ,
	MSG_ID_MMI_SMU_READ_SIM_PLMN_REQ,
	MSG_ID_MMI_SMU_WRITE_SIM_PLMN_REQ,
	MSG_ID_MMI_SMU_RESET_SIM_REQ,
	MSG_ID_MMI_SMU_SML_READY_NOTIFY_REQ,
	MSG_ID_MMI_SMU_SEARCH_RECORD_REQ,
	MSG_ID_MOD_SMU_5_END	=	MSG_ID_MMI_SMU_SEARCH_RECORD_REQ,

	MSG_ID_MMI_PHB_GET_ENTRY_BY_INDEX_REQ,
	MSG_ID_MOD_PHB_6_BEGIN	=	MSG_ID_MMI_PHB_GET_ENTRY_BY_INDEX_REQ,
	MSG_ID_MMI_PHB_SET_ENTRY_REQ,
	MSG_ID_MMI_PHB_DEL_ENTRY_REQ,
	MSG_ID_MMI_PHB_GET_LAST_NUMBER_REQ,
	MSG_ID_MMI_PHB_SET_LAST_NUMBER_REQ,
	MSG_ID_MMI_PHB_DEL_LAST_NUMBER_REQ,
	MSG_ID_MMI_PHB_STARTUP_READ_NEXT_REQ,
	MSG_ID_MMI_PHB_GET_TYPE_INFO_REQ,
	MSG_ID_MMI_PHB_APPROVE_REQ,
	MSG_ID_MMI_PHB_FDN_GET_NAME_REQ,
	MSG_ID_MMI_L4C_READ_PHB_RES_REQ,
	MSG_ID_MMI_L4C_WRITE_PHB_RES_REQ,
	MSG_ID_MMI_L4C_DELETE_PHB_RES_REQ,
	MSG_ID_MMI_L4C_PHB_INIT_RES_REQ,
	MSG_ID_MMI_L4C_PHB_UPDATE_STATUS_RES_REQ,
	MSG_ID_MMI_PHB_READ_SIM_LN_REQ,
	MSG_ID_MMI_PHB_WRITE_SIM_LN_REQ,
	MSG_ID_MMI_PHB_DELETE_SIM_LN_REQ,
	MSG_ID_MMI_PHB_GET_LN_TYPE_INFO_REQ,
	MSG_ID_MMI_L4C_READ_CLOG_RES_REQ,
	MSG_ID_MMI_L4C_WRITE_CLOG_RES_REQ,
	MSG_ID_MMI_L4C_DELETE_CLOG_RES_REQ,
	MSG_ID_MMI_L4C_CLOG_UPDATE_STATUS_RES_REQ,
	MSG_ID_MMI_PHB_READ_USIM_REQ,
	MSG_ID_MMI_PHB_WRITE_USIM_REQ,
	MSG_ID_MMI_PHB_DELETE_USIM_REQ,
	MSG_ID_MMI_PHB_CHECK_WRITE_USIM_ENTRY_REQ,
	MSG_ID_MMI_L4C_READ_ADDITIONAL_RES_REQ,
	MSG_ID_MMI_L4C_WRITE_ADDITIONAL_RES_REQ,
	MSG_ID_MMI_L4C_DELETE_ADDITIONAL_RES_REQ,
	MSG_ID_MOD_PHB_6_END	=	MSG_ID_MMI_L4C_DELETE_ADDITIONAL_RES_REQ,

	MSG_ID_MMI_SMS_SET_PROFILE_PARAMS_REQ,
	MSG_ID_MOD_SMSAL_7_BEGIN	=	MSG_ID_MMI_SMS_SET_PROFILE_PARAMS_REQ,
	MSG_ID_MMI_SMS_GET_PROFILE_PARAMS_REQ,
	MSG_ID_MMI_SMS_SET_COMMON_PARAMS_REQ,
	MSG_ID_MMI_SMS_GET_COMMON_PARAMS_REQ,
	MSG_ID_MMI_SMS_SEND_COMMAND_REQ,
	MSG_ID_MMI_SMS_DEL_MSG_REQ,
	MSG_ID_MMI_SMS_GET_MSG_REQ,
	MSG_ID_MMI_SMS_SEND_MSG_REQ,
	MSG_ID_MMI_SMS_SET_MSG_REQ,
	MSG_ID_MMI_SMS_SET_PREFERRED_STORAGE_REQ,
	MSG_ID_MMI_SMS_GET_PREFERRED_STORAGE_REQ,
	MSG_ID_MMI_SMS_REG_PORT_NUM_REQ,
	MSG_ID_MMI_SMS_GET_MSG_NUM_REQ,
	MSG_ID_MMI_SMS_GET_PROFILE_NUM_REQ,
	MSG_ID_MMI_SMS_ABORT_REQ,
	MSG_ID_MMI_SMS_SET_MAILBOX_ADDRESS_REQ,
	MSG_ID_MMI_SMS_GET_MAILBOX_ADDRESS_REQ,
	MSG_ID_MMI_SMS_SET_MBI_REQ,
	MSG_ID_MMI_SMS_GET_MBI_REQ,
	MSG_ID_MMI_SMS_SET_MSP_REQ,
	MSG_ID_MMI_SMS_GET_MSP_REQ,
	MSG_ID_MMI_SMS_SYNC_MSG_RES_REQ,
	MSG_ID_MMI_SMS_STARTUP_READ_NEXT_REQ,
	MSG_ID_MMI_SMS_COPY_MSG_REQ,
	MSG_ID_MMI_SMS_GET_MSG_LIST_REQ,
	MSG_ID_MMI_SMS_SEND_FROM_STORAGE_REQ,
	MSG_ID_MMI_SMS_SET_STATUS_REQ,
	MSG_ID_MMI_SMS_SEND_SMMA_REQ,
	MSG_ID_MMI_SMS_SET_MSG_WAITING_REQ,
	MSG_ID_MMI_SMS_READ_RAW_DATA_REQ,
	MSG_ID_MMI_SMS_WRITE_RAW_DATA_REQ,
	MSG_ID_MMI_USM_GENERAL_RCODE_REQ,
	MSG_ID_MMI_SMS_SEND_PDU_MSG_REQ,
	MSG_ID_MMI_SMS_SYNC_MSG_STORAGE_REQ,
	MSG_ID_MMI_SMS_SEND_DELIVER_REPORT_REQ,
	MSG_ID_MMI_SMS_STARTUP_READ_RES_REQ,
	MSG_ID_MMI_SMS_GET_MEM_STATUS_RES_REQ,
	MSG_ID_MMI_SMS_MEM_STATUS_REQ,
	MSG_ID_MMI_SMS_ATCMD_CMGR_RES_REQ,
	MSG_ID_MMI_SMS_ATCMD_CMGL_RES_REQ,
	MSG_ID_MMI_SMS_ATCMD_CMGD_RES_REQ,
	MSG_ID_MMI_SMS_ATCMD_CMGW_RES_REQ,
	MSG_ID_MMI_SMS_ATCMD_EQSI_RES_REQ,
	MSG_ID_MMI_SMS_ETWS_SETTING_REQ,
	MSG_ID_MOD_SMSAL_7_END	=	MSG_ID_MMI_SMS_ETWS_SETTING_REQ,

	MSG_ID_MMI_PS_ACT_TEST_REQ,
	MSG_ID_MOD_TCM_8_BEGIN	=	MSG_ID_MMI_PS_ACT_TEST_REQ,
	MSG_ID_MMI_PS_SET_DEFINITION_REQ,
	MSG_ID_MMI_PS_SET_SEC_DEFINITION_REQ,
	MSG_ID_MMI_PS_SET_TFT_REQ,
	MSG_ID_MMI_PS_GET_TFT_REQ,
	MSG_ID_MMI_PS_SET_QOS_REQ,
	MSG_ID_MMI_PS_SET_EQOS_REQ,
	MSG_ID_MMI_PS_SEND_DATA_REQ,
	MSG_ID_MMI_PS_GET_GPRS_EMPTY_PROFILE_REQ,
	MSG_ID_MMI_PS_GET_GPRS_DATA_COUNTER_REQ,
	MSG_ID_MMI_PS_SET_GPRS_DATA_ACCOUNT_REQ,
	MSG_ID_MMI_PS_GET_GPRS_DATA_ACCOUNT_REQ,
	MSG_ID_MMI_PS_RESET_GPRS_DATA_COUNTER_REQ,
	MSG_ID_MMI_PS_GET_ACL_MODE_REQ,
	MSG_ID_MMI_PS_SET_ACL_MODE_REQ,
	MSG_ID_MMI_PS_GET_ACL_ENTRIES_REQ,
	MSG_ID_MMI_PS_ADD_ACL_ENTRY_REQ,
	MSG_ID_MMI_PS_SET_ACL_ENTRY_REQ,
	MSG_ID_MMI_PS_DEL_ACL_ENTRY_REQ,
	MSG_ID_MMI_PS_LEAVE_ACL_MENU_REQ,
	MSG_ID_MOD_TCM_8_END	=	MSG_ID_MMI_PS_LEAVE_ACL_MENU_REQ,

	MSG_ID_MMI_SAT_DISPLAY_TEXT_RES_REQ,
	MSG_ID_SAT_9_BEGIN	=	MSG_ID_MMI_SAT_DISPLAY_TEXT_RES_REQ,
	MSG_ID_MMI_SAT_GET_INKEY_RES_REQ,
	MSG_ID_MMI_SAT_GET_INPUT_RES_REQ,
	MSG_ID_MMI_SAT_SETUP_MENU_RES_REQ,
	MSG_ID_MMI_SAT_SELECT_ITEM_RES_REQ,
	MSG_ID_MMI_SAT_PLAY_TONE_RES_REQ,
	MSG_ID_MMI_SAT_MENU_SELECT_REQ,
	MSG_ID_MMI_SAT_EVDL_IDLE_SCREEN_AVAILABLE_REQ,
	MSG_ID_MMI_SAT_LANGUAGE_SELECTION_REQ,
	MSG_ID_MMI_SAT_EVDL_BROWSER_TERMINATION_REQ,
	MSG_ID_MMI_SAT_CALL_SETUP_STAGE1_REQ,
	MSG_ID_MMI_SAT_CALL_SETUP_STAGE2_REQ,
	MSG_ID_MMI_SAT_SEND_SMS_STAGE1_REQ,
	MSG_ID_MMI_SAT_SEND_SMS_STAGE2_REQ,
	MSG_ID_MMI_SAT_SEND_SS_STAGE1_REQ,
	MSG_ID_MMI_SAT_SEND_SS_STAGE2_REQ,
	MSG_ID_MMI_SAT_SEND_USSD_STAGE1_REQ,
	MSG_ID_MMI_SAT_SEND_USSD_STAGE2_REQ,
	MSG_ID_MMI_SAT_SETUP_IDLE_DISPLAY_RES_REQ,
	MSG_ID_MMI_SAT_SEND_DTMF_STAGE1_REQ,
	MSG_ID_MMI_SAT_SEND_DTMF_STAGE2_REQ,
	MSG_ID_MMI_SAT_ABORT_DTMF_REQ,
	MSG_ID_MMI_SAT_LANG_NOTIFY_RES_REQ,
	MSG_ID_MMI_SAT_LAUNCH_BROWSER_RES_REQ,
	MSG_ID_MMI_SAT_PROVIDE_LANG_INFO_REQ,
	MSG_ID_MMI_SAT_FILE_CHANGE_RES_REQ,
	MSG_ID_SAT_9_END	=	MSG_ID_MMI_SAT_FILE_CHANGE_RES_REQ,

	MSG_ID_MMI_SAT_OPEN_CHANNEL_REQ,
	MSG_ID_SATCE_10_BEGIN	=	MSG_ID_MMI_SAT_OPEN_CHANNEL_REQ,
	MSG_ID_MMI_SAT_CLOSE_CHANNEL_REQ,
	MSG_ID_MMI_SAT_SEND_DATA_REQ,
	MSG_ID_MMI_SAT_RECV_DATA_REQ,
	MSG_ID_MMI_RSAT_EVDL_DATA_AVAILABLE_REQ,
	MSG_ID_MMI_RSAT_EVDL_CHANNEL_STATUS_REQ,
	MSG_ID_MMI_RSAT_OPEN_GPRS_CHANNEL_RES_REQ,
	MSG_ID_MMI_RSAT_OPEN_CSD_CHANNEL_RES_REQ,
	MSG_ID_MMI_RSAT_OPEN_SERVER_MODE_CHANNEL_RES_REQ,
	MSG_ID_MMI_RSAT_CLOSE_CHANNEL_RES_REQ,
	MSG_ID_MMI_RSAT_SEND_DATA_RES_REQ,
	MSG_ID_MMI_RSAT_RECV_DATA_RES_REQ,
	MSG_ID_MMI_RSAT_CH_STATUS_RES_REQ,
	MSG_ID_SATCE_10_END	=	MSG_ID_MMI_RSAT_CH_STATUS_RES_REQ,

	MSG_ID_MMI_CB_SUBSCRIBE_REQ,
	MSG_ID_MMI_SMS_SET_CB_MODE_REQ,
	MSG_ID_MMI_SMS_GET_CB_MODE_REQ,
	MSG_ID_MMI_EM_UPDATE_REQ,
	MSG_ID_EM_MODE_11_BEGIN	=	MSG_ID_MMI_EM_UPDATE_REQ,
	MSG_ID_MMI_VT_EM_GET_CONFIG_REQ,
	MSG_ID_MMI_VT_EM_SET_CONFIG_REQ,
	MSG_ID_EM_MODE_11_END	=	MSG_ID_MMI_VT_EM_SET_CONFIG_REQ,

	MSG_ID_MMI_EM_KEYPAD_EVENT_OUTPUT_REQ,
	MSG_ID_MMI_EM_CELL_RESEL_SUSPEND_REQ,
	MSG_ID_MMI_EM_CELL_RESEL_RESUME_REQ,
	MSG_ID_MMI_EM_GET_CELL_LOCK_REQ,
	MSG_ID_MMI_EM_SET_CELL_LOCK_REQ,
	MSG_ID_MMI_EM_EXT_GET_CELL_LOCK_REQ,
	MSG_ID_MMI_EM_EXT_SET_CELL_LOCK_REQ,
	MSG_ID_MMI_EM_NW_EVENT_NOTIFY_REQ,
	MSG_ID_MMI_EM_FEATURE_COMMAND_REQ,
	MSG_ID_MMI_EM_GET_CONFORM_TEST_PARAM_REQ,
	MSG_ID_MMI_EM_SET_CONFORM_TEST_PARAM_REQ,
	MSG_ID_MMI_EM_QUICK_TEST_REPORT_RES_REQ,
	MSG_ID_MMI_EM_SET_ESSP_REQ,
	MSG_ID_MMI_EM_GET_ESSP_REQ,
	MSG_ID_MMI_CPHS_UPDATE_ALS_REQ,
	MSG_ID_MMI_EQ_IRDA_OPEN_REQ,
	MSG_ID_IRDA_SUPPORT_12_BEGIN	=	MSG_ID_MMI_EQ_IRDA_OPEN_REQ,
	MSG_ID_MMI_EQ_IRDA_CLOSE_REQ,
	MSG_ID_IRDA_SUPPORT_12_END	=	MSG_ID_MMI_EQ_IRDA_CLOSE_REQ,

	MSG_ID_MMI_EQ_USBCONFIG_REQ,
	MSG_ID_USB_ENABLE_13_BEGIN	=	MSG_ID_MMI_EQ_USBCONFIG_REQ,
	MSG_ID_MMI_EQ_USBUART_SWITCH_PORT_REQ,
	MSG_ID_MMI_EQ_USBDETECT_RES_REQ,
	MSG_ID_USB_ENABLE_13_END	=	MSG_ID_MMI_EQ_USBDETECT_RES_REQ,

	MSG_ID_WAP_MMC_READ_FOLDER_STATUS_OUTPUT_REQ,
	MSG_ID_WAP_MMC_UPLOAD_MSG_OUTPUT_REQ,
	MSG_ID_WAP_MMC_DELETE_MSG_OUTPUT_REQ,
	MSG_ID_WAP_MMC_READ_MSG_PATH_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_GREETING_TEXT_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_LANGUAGE_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_SILENT_MODE_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_VIBRATOR_MODE_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_DATE_TIME_FORMAT_RES_REQ,
	MSG_ID_MMI_EQ_QUERY_MUTE_MODE_RES_REQ,
	MSG_ID_MMI_READY_NOTIFY_REQ,
	MSG_ID_MMI_AT_GENERAL_RES_REQ,
	MSG_ID_MMI_EQ_VCARD_RES_REQ,
	MSG_ID_MMI_EQ_VCALENDAR_RES_REQ,
	MSG_ID_MMI_EQ_STR_RES_REQ,
	MSG_ID_MMI_UCM_AT_RES_REQ,
	MSG_ID_MMI_UCM_GENERAL_RCODE_REQ,
	MSG_ID_MMI_UCM_HF_CIEV_RCODE_REQ,
	MSG_ID_MMI_EQ_RINGTONE_PLAY_RES_REQ,
	MSG_ID_MMI_JAVA_LOCAL_INSTALL_RES_REQ,
	MSG_ID_MMI_L4_BT_SET_VR_REQ,
	MSG_ID_BT_SUPPORT_14_BEGIN	=	MSG_ID_MMI_L4_BT_SET_VR_REQ,
	MSG_ID_BT_SUPPORT_14_END	=	MSG_ID_MMI_L4_BT_SET_VR_REQ,

	MSG_ID_HOMEZONE_SUPPORT_15_BEGIN	=	MSG_ID_MMI_L4_BT_SET_VR_REQ,
	MSG_ID_HOMEZONE_SUPPORT_15_END	=	MSG_ID_MMI_L4_BT_SET_VR_REQ,

	MSG_ID_MMI_CTM_SET_STATUS_REQ,
	MSG_ID_CTM_SUPPORT_16_BEGIN	=	MSG_ID_MMI_CTM_SET_STATUS_REQ,
	MSG_ID_CTM_SUPPORT_16_END	=	MSG_ID_MMI_CTM_SET_STATUS_REQ,

	MSG_ID_MMI_VOIP_AT_CALL_CTRL_APPROVE_RES_REQ,
	MSG_ID_VOIP_17_BEGIN	=	MSG_ID_MMI_VOIP_AT_CALL_CTRL_APPROVE_RES_REQ,
	MSG_ID_VOIP_17_END	=	MSG_ID_MMI_VOIP_AT_CALL_CTRL_APPROVE_RES_REQ,

	MSG_ID_MMI_SMU_SIM_STATUS_UPDATE_REQ,
	MSG_ID_GEMINI_18_BEGIN	=	MSG_ID_MMI_SMU_SIM_STATUS_UPDATE_REQ,
	MSG_ID_MMI_SMU_DUAL_SIM_TO_FLIGHT_MODE_REQ,
	MSG_ID_MMI_NW_SIM_MODE_SWITCH_START_REQ,
	MSG_ID_MMI_NW_SIM_MODE_SWITCH_STOP_REQ,
	MSG_ID_MMI_NW_SET_MONITOR_PEER_PCH_REQ,
	MSG_ID_MMI_NW_GET_MONITOR_PEER_PCH_REQ,
	MSG_ID_MMI_L4C_SET_SIM_CAPABILITY_REQ,
	MSG_ID_MMI_L4C_GET_SIM_CAPABILITY_REQ,
	MSG_ID_GEMINI_18_END	=	MSG_ID_MMI_L4C_GET_SIM_CAPABILITY_REQ,

	MSG_ID_MMI_SS_MTLR_BEGIN_RES_REQ,
	MSG_ID_AGPS_CONTROL_PLANE_19_BEGIN	=	MSG_ID_MMI_SS_MTLR_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_AERQ_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_AERP_BEGIN_REQ,
	MSG_ID_MMI_SS_AERP_END_REQ,
	MSG_ID_MMI_SS_AECL_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_MOLR_BEGIN_REQ,
	MSG_ID_MMI_SS_MOLR_END_REQ,
	MSG_ID_MMI_AGPS_ENABLE_DISABLE_REQ,
	MSG_ID_MMI_AGPS_KEY_UPDATE_REQ,
	MSG_ID_MMI_AGPS_CP_ABORT_REQ,
	MSG_ID_AGPS_CONTROL_PLANE_19_END	=	MSG_ID_MMI_AGPS_CP_ABORT_REQ,

	MSG_ID_MMI_EQ_RAM_USAGE_RES_REQ,
	MSG_ID_MMI_EQ_LAUNCH_APP_RES_REQ,
	MSG_ID_MMI_EQ_APP_INFO_OUTPUT_RES_REQ,
	MSG_ID_MMI_EQ_SCREEN_TOUCH_RES_REQ,
	MSG_ID_MMI_EQ_SCRNORIENT_RES_REQ,
	MSG_ID_MMI_EQ_SCRNSIZE_QUERY_RES_REQ,
	MSG_ID_MMI_EQ_SCRNTCH_EVENT_OUTPUT_REQ,
	MSG_ID_MMI_EQ_SCREEN_SHOT_RES_REQ,
	MSG_ID_MMI_EQ_UART_TRANSFER_REQ,
	MSG_ID_MMI_EQ_UART_RELEASE_REQ,
	MSG_ID_MMI_EQ_PLAY_AUDIO_STREAM_REQ,
	MSG_ID_MMI_EQ_STOP_AUDIO_STREAM_REQ,
	MSG_ID_MMI_EQ_LCD_SET_CONTRAST_REQ,
	MSG_ID_MMI_EQ_SET_SILENT_MODE_REQ,
	MSG_ID_NONE_USED_L4MMI_MESSAGE_20_BEGIN	=	MSG_ID_MMI_EQ_SET_SILENT_MODE_REQ,
	MSG_ID_MMI_EQ_GET_MS_IMEI_REQ,
	MSG_ID_MMI_EQ_SET_MS_IMEI_REQ,
	MSG_ID_MMI_EQ_RTC_POWERON_STATE_REQ,
	MSG_ID_MMI_EQ_START_TIMER_REQ,
	MSG_ID_MMI_EQ_STOP_TIMER_REQ,
	MSG_ID_MMI_EQ_SIMULATE_KEY_PRESS_REQ,
	MSG_ID_MMI_EQ_SET_INDICATOR_REQ,
	MSG_ID_MMI_EQ_GET_INDICATOR_REQ,
	MSG_ID_MMI_EQ_DISPLAY_TEXT_REQ,
	MSG_ID_MMI_EQ_SET_GREETING_TEXT_REQ,
	MSG_ID_MMI_EQ_SET_VIBRATOR_MODE_REQ,
	MSG_ID_MMI_EQ_SET_COUNTRY_CODE_REQ,
	MSG_ID_MMI_EQ_GET_COUNTRY_CODE_REQ,
	MSG_ID_MMI_EQ_GET_BATTERY_STATUS_REQ,
	MSG_ID_MMI_EQ_LOAD_DEFAULT_CONFIG_REQ,
	MSG_ID_MMI_EM_SET_CELL_ID_LOCK_REQ,
	MSG_ID_MMI_UPDATE_MMI_DEFAULT_PROF_VALUE_REQ,
	MSG_ID_MMI_VM_PLAY_REQ,
	MSG_ID_MMI_VM_DEL_REQ,
	MSG_ID_MMI_VM_APPEND_REQ,
	MSG_ID_MMI_VM_RENAME_REQ,
	MSG_ID_MMI_VM_GET_INFO_REQ,
	MSG_ID_MMI_VM_STOP_REQ,
	MSG_ID_MMI_VM_ABORT_REQ,
	MSG_ID_MMI_VM_PAUSE_REQ,
	MSG_ID_MMI_VM_RESUME_REQ,
	MSG_ID_MMI_VM_RECORD_REQ,
	MSG_ID_WAP_START_DTMF_REQ,
	MSG_ID_WAP_STOP_DTMF_REQ,
	MSG_ID_WAP_DIAL_REQ,
	MSG_ID_WAP_SET_ENTRY_REQ,
	MSG_ID_NONE_USED_L4MMI_MESSAGE_20_END	=	MSG_ID_WAP_SET_ENTRY_REQ,
	MSG_ID_L4A_REQ_CODE_END = MSG_ID_WAP_SET_ENTRY_REQ,

	MSG_ID_MMI_CC_RESET_ACM_RSP,
	MSG_ID_MMI_CC_GET_ACM_RSP,
	MSG_ID_MMI_CC_SET_MAX_ACM_RSP,
	MSG_ID_MMI_CC_GET_MAX_ACM_RSP,
	MSG_ID_MMI_CC_RESET_CCM_RSP,
	MSG_ID_MMI_CC_GET_CCM_RSP,
	MSG_ID_MMI_CC_SET_CUG_RSP,
	MSG_ID_MMI_CC_CHLD_RSP,
	MSG_ID_MMI_CC_ATH_RSP,
	MSG_ID_MMI_CC_GET_CALL_LIST_RSP,
	MSG_ID_MMI_CC_CALL_DEFLECT_RSP,
	MSG_ID_MMI_CC_START_DTMF_RSP,
	MSG_ID_MMI_CC_STOP_DTMF_RSP,
	MSG_ID_MMI_CC_START_AUTO_DTMF_RSP,
	MSG_ID_MMI_CC_ATA_RSP,
	MSG_ID_MMI_CC_DIAL_RSP,
	MSG_ID_MMI_CC_REL_COMP_RSP,
	MSG_ID_MMI_CC_CALL_PRESENT_RES_RSP,
	MSG_ID_MMI_CC_CPI_RSP,
	MSG_ID_MMI_DATA_CALL_RES_RSP,
	MSG_ID_MMI_SS_EMLPP_RSP,
	MSG_ID_MMI_SS_CALL_FORWARD_RSP,
	MSG_ID_MMI_SS_CALL_WAIT_RSP,
	MSG_ID_MMI_SS_CALL_BARRING_RSP,
	MSG_ID_MMI_SS_USSD_RSP,
	MSG_ID_MMI_SS_CHANGE_PASSWORD_RSP,
	MSG_ID_MMI_SS_PARSING_STRING_RSP,
	MSG_ID_MMI_SS_OPERATION_RSP,
	MSG_ID_MMI_SS_CCBS_RSP,
	MSG_ID_MMI_SS_ABORT_RSP,
	MSG_ID_MMI_SS_SET_CLIR_FLAG_RSP,
	MSG_ID_MMI_SS_ACK_RSP,
	MSG_ID_MMI_EQ_SET_VOLUME_RSP,
	MSG_ID_MMI_EQ_SET_MUTE_RSP,
	MSG_ID_MMI_EQ_SET_GPIO_LEVEL_RSP,
	MSG_ID_MMI_EQ_GET_GPIO_LEVEL_RSP,
	MSG_ID_MMI_EQ_EXE_GPIO_LEVEL_RSP,
	MSG_ID_MMI_EQ_PLAY_AUDIO_RSP,
	MSG_ID_MMI_EQ_STOP_AUDIO_RSP,
	MSG_ID_MMI_EQ_PLAY_EXT_IMELODY_RSP,
	MSG_ID_MMI_EQ_GPIO_DETECT_RES_RSP,
	MSG_ID_MMI_EQ_SET_SPEECH_MODE_RSP,
	MSG_ID_MMI_EQ_PLAY_AUDIO_BY_NAME_RSP,
	MSG_ID_MMI_EQ_STOP_AUDIO_BY_NAME_RSP,
	MSG_ID_MMI_EQ_SET_AUDIO_PROFILE_RSP,
	MSG_ID_MMI_EQ_GET_AUDIO_PROFILE_RSP,
	MSG_ID_MMI_EQ_SET_AUDIO_PARAM_RSP,
	MSG_ID_MMI_EQ_GET_AUDIO_PARAM_RSP,
	MSG_ID_MMI_EQ_START_ADC_ALL_CHANNEL_RSP,
	MSG_ID_MMI_EQ_STOP_ADC_ALL_CHANNEL_RSP,
	MSG_ID_MMI_EQ_SET_AUDIO_MODE_RSP,
	MSG_ID_MMI_EQ_PLAY_PATTERN_RSP,
	MSG_ID_MMI_EQ_SET_HW_LEVEL_RSP,
	MSG_ID_MMI_EQ_GET_HW_LEVEL_RSP,
	MSG_ID_MMI_EQ_SET_SLEEP_MODE_RSP,
	MSG_ID_MMI_EQ_QUERY_HAND_FREE_MODE_RES_RSP,
	MSG_ID_MMI_EQ_SET_CAM_RES_RSP,
	MSG_ID_MMI_EQ_SET_AVR_RES_RSP,
	MSG_ID_MMI_EQ_SET_RTC_TIME_RSP,
	MSG_ID_MMI_EQ_EXE_RTC_TIMER_RSP,
	MSG_ID_MMI_EQ_GET_RTC_TIME_RSP,
	MSG_ID_MMI_EQ_DEL_RTC_TIMER_RSP,
	MSG_ID_MMI_EQ_EXE_DEL_RTC_TIMER_RSP,
	MSG_ID_MMI_EQ_SET_DATE_TIME_FORMAT_RSP,
	MSG_ID_MMI_AT_ALARM_QUERY_RES_RSP,
	MSG_ID_MMI_AT_ALARM_SET_RES_RSP,
	MSG_ID_MMI_AT_ALARM_DELETE_RES_RSP,
	MSG_ID_MMI_AT_CBKLT_QUERY_RES_RSP,
	MSG_ID_MMI_AT_KEYPAD_EVENT_OUTPUT_RSP,
	MSG_ID_MMI_EQ_SET_LANGUAGE_RSP,
	MSG_ID_MMI_EQ_GET_EQUIP_ID_RSP,
	MSG_ID_MMI_EQ_POWER_ON_RSP,
	MSG_ID_MMI_EQ_POWER_OFF_RSP,
	MSG_ID_MMI_EQ_CANCEL_LOCK_POWERON_RSP,
	MSG_ID_MMI_EQ_PMIC_CONFIG_RSP,
	MSG_ID_MMI_EQ_BATTERY_STATUS_RES_RSP,
	MSG_ID_MMI_EQ_RF_TEST_GSM_RSP,
	MSG_ID_MMI_EQ_FM_RADIO_CONFIG_RSP,
	MSG_ID_MMI_EQ_RF_TEST_WIFI_RSP,
	MSG_ID_MMI_EQ_CALL_STATUS_RSP,
	MSG_ID_MMI_EQ_QUERY_CAL_DATA_DL_STATUS_RSP,
	MSG_ID_MMI_EQ_NVRAM_READ_RSP,
	MSG_ID_MMI_EQ_NVRAM_WRITE_RSP,
	MSG_ID_MMI_EQ_NVRAM_RESET_RSP,
	MSG_ID_MMI_EQ_SET_UART_RSP,
	MSG_ID_MMI_EQ_GET_UART_RSP,
	MSG_ID_MMI_ATTACH_UART_PORT_RSP,
	MSG_ID_MMI_DETACH_UART_PORT_RSP,
	MSG_ID_MMI_EQ_DCM_ENABLE_RSP,
	MSG_ID_MMI_NW_GET_IMEI_RSP,
	MSG_ID_MMI_NW_ABORT_PLMN_LIST_RSP,
	MSG_ID_MMI_NW_SET_ATTACH_RSP,
	MSG_ID_MMI_NW_SET_PLMN_SELECT_MODE_RSP,
	MSG_ID_MMI_NW_GET_PLMN_SELECT_MODE_RSP,
	MSG_ID_MMI_NW_SET_GPRS_TRANSFER_PREFERENCE_RSP,
	MSG_ID_MMI_NW_GET_GPRS_TRANSFER_PREFERENCE_RSP,
	MSG_ID_MMI_NW_SET_PLMN_RSP,
	MSG_ID_MMI_NW_GET_PLMN_LIST_RSP,
	MSG_ID_MMI_NW_GET_BAND_RSP,
	MSG_ID_MMI_NW_SET_PREFERRED_BAND_RSP,
	MSG_ID_MMI_NW_SET_GPRS_CONNECT_TYPE_RSP,
	MSG_ID_MMI_NW_GET_GPRS_CONNECT_TYPE_RSP,
	MSG_ID_MMI_NW_PWROFF_DETACH_RSP,
	MSG_ID_MMI_NW_CFUN_STATE_RSP,
	MSG_ID_MMI_NW_EFUN_STATE_RSP,
	MSG_ID_MMI_NW_GET_RAT_MODE_RSP,
	MSG_ID_MMI_NW_SET_RAT_MODE_RSP,
	MSG_ID_MMI_NW_GET_PREFER_RAT_RSP,
	MSG_ID_MMI_NW_SET_PREFER_RAT_RSP,
	MSG_ID_MMI_NW_SET_HSPA_MODE_RSP,
	MSG_ID_MMI_NW_GET_HSPA_MODE_RSP,
	MSG_ID_MMI_NW_SET_PLMN_LIST_PREFERENCE_RSP,
	MSG_ID_MMI_NW_GET_PLMN_LIST_PREFERENCE_RSP,
	MSG_ID_MMI_NW_END_PS_DATA_SESSION_RSP,
	MSG_ID_MMI_SMU_GET_IMSI_RSP,
	MSG_ID_MMI_SMU_LOCK_RSP,
	MSG_ID_MMI_SMU_GET_DIAL_MODE_RSP,
	MSG_ID_MMI_SMU_VERIFY_PIN_RSP,
	MSG_ID_MMI_SMU_SET_PREFERRED_OPER_LIST_RSP,
	MSG_ID_MMI_SMU_GET_PREFERRED_OPER_LIST_RSP,
	MSG_ID_MMI_SMU_SET_PUC_RSP,
	MSG_ID_MMI_SMU_GET_PUC_RSP,
	MSG_ID_MMI_SMU_CHANGE_PASSWORD_RSP,
	MSG_ID_MMI_SMU_SET_DIAL_MODE_RSP,
	MSG_ID_MMI_SMU_WRITE_SIM_RSP,
	MSG_ID_MMI_SMU_READ_SIM_RSP,
	MSG_ID_MMI_SMU_POWER_OFF_RSP,
	MSG_ID_MMI_SIM_GET_GSMCDMA_DUALSIM_INFO_RSP,
	MSG_ID_MMI_SIM_SET_GSMCDMA_DUALSIM_MODE_RSP,
	MSG_ID_MMI_SMU_READ_FILE_INFO_RSP,
	MSG_ID_MMI_SMU_CHECK_PIN_STATUS_RSP,
	MSG_ID_MMI_SMU_SET_PERSONALIZATION_RSP,
	MSG_ID_MMI_SMU_SML_STATUS_RSP,
	MSG_ID_MMI_SMU_READ_SIM_PLMN_RSP,
	MSG_ID_MMI_SMU_WRITE_SIM_PLMN_RSP,
	MSG_ID_MMI_SMU_RESET_SIM_RSP,
	MSG_ID_MMI_SMU_SML_READY_NOTIFY_RSP,
	MSG_ID_MMI_SMU_SEARCH_RECORD_RSP,
	MSG_ID_MMI_PHB_GET_ENTRY_BY_INDEX_RSP,
	MSG_ID_MMI_PHB_SET_ENTRY_RSP,
	MSG_ID_MMI_PHB_DEL_ENTRY_RSP,
	MSG_ID_MMI_PHB_GET_LAST_NUMBER_RSP,
	MSG_ID_MMI_PHB_SET_LAST_NUMBER_RSP,
	MSG_ID_MMI_PHB_DEL_LAST_NUMBER_RSP,
	MSG_ID_MMI_PHB_STARTUP_READ_NEXT_RSP,
	MSG_ID_MMI_PHB_GET_TYPE_INFO_RSP,
	MSG_ID_MMI_PHB_APPROVE_RSP,
	MSG_ID_MMI_PHB_FDN_GET_NAME_RSP,
	MSG_ID_MMI_L4C_READ_PHB_RES_RSP,
	MSG_ID_MMI_L4C_WRITE_PHB_RES_RSP,
	MSG_ID_MMI_L4C_DELETE_PHB_RES_RSP,
	MSG_ID_MMI_L4C_PHB_INIT_RES_RSP,
	MSG_ID_MMI_L4C_PHB_UPDATE_STATUS_RES_RSP,
	MSG_ID_MMI_PHB_READ_SIM_LN_RSP,
	MSG_ID_MMI_PHB_WRITE_SIM_LN_RSP,
	MSG_ID_MMI_PHB_DELETE_SIM_LN_RSP,
	MSG_ID_MMI_PHB_GET_LN_TYPE_INFO_RSP,
	MSG_ID_MMI_L4C_READ_CLOG_RES_RSP,
	MSG_ID_MMI_L4C_WRITE_CLOG_RES_RSP,
	MSG_ID_MMI_L4C_DELETE_CLOG_RES_RSP,
	MSG_ID_MMI_L4C_CLOG_UPDATE_STATUS_RES_RSP,
	MSG_ID_MMI_PHB_READ_USIM_RSP,
	MSG_ID_MMI_PHB_WRITE_USIM_RSP,
	MSG_ID_MMI_PHB_DELETE_USIM_RSP,
	MSG_ID_MMI_PHB_CHECK_WRITE_USIM_ENTRY_RSP,
	MSG_ID_MMI_L4C_READ_ADDITIONAL_RES_RSP,
	MSG_ID_MMI_L4C_WRITE_ADDITIONAL_RES_RSP,
	MSG_ID_MMI_L4C_DELETE_ADDITIONAL_RES_RSP,
	MSG_ID_MMI_SMS_SET_PROFILE_PARAMS_RSP,
	MSG_ID_MMI_SMS_GET_PROFILE_PARAMS_RSP,
	MSG_ID_MMI_SMS_SET_COMMON_PARAMS_RSP,
	MSG_ID_MMI_SMS_GET_COMMON_PARAMS_RSP,
	MSG_ID_MMI_SMS_SEND_COMMAND_RSP,
	MSG_ID_MMI_SMS_DEL_MSG_RSP,
	MSG_ID_MMI_SMS_GET_MSG_RSP,
	MSG_ID_MMI_SMS_SEND_MSG_RSP,
	MSG_ID_MMI_SMS_SET_MSG_RSP,
	MSG_ID_MMI_SMS_SET_PREFERRED_STORAGE_RSP,
	MSG_ID_MMI_SMS_GET_PREFERRED_STORAGE_RSP,
	MSG_ID_MMI_SMS_REG_PORT_NUM_RSP,
	MSG_ID_MMI_SMS_GET_MSG_NUM_RSP,
	MSG_ID_MMI_SMS_GET_PROFILE_NUM_RSP,
	MSG_ID_MMI_SMS_ABORT_RSP,
	MSG_ID_MMI_SMS_SET_MAILBOX_ADDRESS_RSP,
	MSG_ID_MMI_SMS_GET_MAILBOX_ADDRESS_RSP,
	MSG_ID_MMI_SMS_SET_MBI_RSP,
	MSG_ID_MMI_SMS_GET_MBI_RSP,
	MSG_ID_MMI_SMS_SET_MSP_RSP,
	MSG_ID_MMI_SMS_GET_MSP_RSP,
	MSG_ID_MMI_SMS_SYNC_MSG_RES_RSP,
	MSG_ID_MMI_SMS_STARTUP_READ_NEXT_RSP,
	MSG_ID_MMI_SMS_COPY_MSG_RSP,
	MSG_ID_MMI_SMS_GET_MSG_LIST_RSP,
	MSG_ID_MMI_SMS_SEND_FROM_STORAGE_RSP,
	MSG_ID_MMI_SMS_SET_STATUS_RSP,
	MSG_ID_MMI_SMS_SEND_SMMA_RSP,
	MSG_ID_MMI_SMS_SET_MSG_WAITING_RSP,
	MSG_ID_MMI_SMS_READ_RAW_DATA_RSP,
	MSG_ID_MMI_SMS_WRITE_RAW_DATA_RSP,
	MSG_ID_MMI_USM_GENERAL_RCODE_RSP,
	MSG_ID_MMI_SMS_SEND_PDU_MSG_RSP,
	MSG_ID_MMI_SMS_SYNC_MSG_STORAGE_RSP,
	MSG_ID_MMI_SMS_SEND_DELIVER_REPORT_RSP,
	MSG_ID_MMI_SMS_STARTUP_READ_RES_RSP,
	MSG_ID_MMI_SMS_GET_MEM_STATUS_RES_RSP,
	MSG_ID_MMI_SMS_MEM_STATUS_RSP,
	MSG_ID_MMI_SMS_ATCMD_CMGR_RES_RSP,
	MSG_ID_MMI_SMS_ATCMD_CMGL_RES_RSP,
	MSG_ID_MMI_SMS_ATCMD_CMGD_RES_RSP,
	MSG_ID_MMI_SMS_ATCMD_CMGW_RES_RSP,
	MSG_ID_MMI_SMS_ATCMD_EQSI_RES_RSP,
	MSG_ID_MMI_SMS_ETWS_SETTING_RSP,
	MSG_ID_MMI_PS_ACT_TEST_RSP,
	MSG_ID_MMI_PS_SET_DEFINITION_RSP,
	MSG_ID_MMI_PS_SET_SEC_DEFINITION_RSP,
	MSG_ID_MMI_PS_SET_TFT_RSP,
	MSG_ID_MMI_PS_GET_TFT_RSP,
	MSG_ID_MMI_PS_SET_QOS_RSP,
	MSG_ID_MMI_PS_SET_EQOS_RSP,
	MSG_ID_MMI_PS_SEND_DATA_RSP,
	MSG_ID_MMI_PS_GET_GPRS_EMPTY_PROFILE_RSP,
	MSG_ID_MMI_PS_GET_GPRS_DATA_COUNTER_RSP,
	MSG_ID_MMI_PS_SET_GPRS_DATA_ACCOUNT_RSP,
	MSG_ID_MMI_PS_GET_GPRS_DATA_ACCOUNT_RSP,
	MSG_ID_MMI_PS_RESET_GPRS_DATA_COUNTER_RSP,
	MSG_ID_MMI_PS_GET_ACL_MODE_RSP,
	MSG_ID_MMI_PS_SET_ACL_MODE_RSP,
	MSG_ID_MMI_PS_GET_ACL_ENTRIES_RSP,
	MSG_ID_MMI_PS_ADD_ACL_ENTRY_RSP,
	MSG_ID_MMI_PS_SET_ACL_ENTRY_RSP,
	MSG_ID_MMI_PS_DEL_ACL_ENTRY_RSP,
	MSG_ID_MMI_PS_LEAVE_ACL_MENU_RSP,
	MSG_ID_MMI_SAT_DISPLAY_TEXT_RES_RSP,
	MSG_ID_MMI_SAT_GET_INKEY_RES_RSP,
	MSG_ID_MMI_SAT_GET_INPUT_RES_RSP,
	MSG_ID_MMI_SAT_SETUP_MENU_RES_RSP,
	MSG_ID_MMI_SAT_SELECT_ITEM_RES_RSP,
	MSG_ID_MMI_SAT_PLAY_TONE_RES_RSP,
	MSG_ID_MMI_SAT_MENU_SELECT_RSP,
	MSG_ID_MMI_SAT_EVDL_IDLE_SCREEN_AVAILABLE_RSP,
	MSG_ID_MMI_SAT_LANGUAGE_SELECTION_RSP,
	MSG_ID_MMI_SAT_EVDL_BROWSER_TERMINATION_RSP,
	MSG_ID_MMI_SAT_CALL_SETUP_STAGE1_RSP,
	MSG_ID_MMI_SAT_CALL_SETUP_STAGE2_RSP,
	MSG_ID_MMI_SAT_SEND_SMS_STAGE1_RSP,
	MSG_ID_MMI_SAT_SEND_SMS_STAGE2_RSP,
	MSG_ID_MMI_SAT_SEND_SS_STAGE1_RSP,
	MSG_ID_MMI_SAT_SEND_SS_STAGE2_RSP,
	MSG_ID_MMI_SAT_SEND_USSD_STAGE1_RSP,
	MSG_ID_MMI_SAT_SEND_USSD_STAGE2_RSP,
	MSG_ID_MMI_SAT_SETUP_IDLE_DISPLAY_RES_RSP,
	MSG_ID_MMI_SAT_SEND_DTMF_STAGE1_RSP,
	MSG_ID_MMI_SAT_SEND_DTMF_STAGE2_RSP,
	MSG_ID_MMI_SAT_ABORT_DTMF_RSP,
	MSG_ID_MMI_SAT_LANG_NOTIFY_RES_RSP,
	MSG_ID_MMI_SAT_LAUNCH_BROWSER_RES_RSP,
	MSG_ID_MMI_SAT_PROVIDE_LANG_INFO_RSP,
	MSG_ID_MMI_SAT_FILE_CHANGE_RES_RSP,
	MSG_ID_MMI_SAT_OPEN_CHANNEL_RSP,
	MSG_ID_MMI_SAT_CLOSE_CHANNEL_RSP,
	MSG_ID_MMI_SAT_SEND_DATA_RSP,
	MSG_ID_MMI_SAT_RECV_DATA_RSP,
	MSG_ID_MMI_RSAT_EVDL_DATA_AVAILABLE_RSP,
	MSG_ID_MMI_RSAT_EVDL_CHANNEL_STATUS_RSP,
	MSG_ID_MMI_RSAT_OPEN_GPRS_CHANNEL_RES_RSP,
	MSG_ID_MMI_RSAT_OPEN_CSD_CHANNEL_RES_RSP,
	MSG_ID_MMI_RSAT_OPEN_SERVER_MODE_CHANNEL_RES_RSP,
	MSG_ID_MMI_RSAT_CLOSE_CHANNEL_RES_RSP,
	MSG_ID_MMI_RSAT_SEND_DATA_RES_RSP,
	MSG_ID_MMI_RSAT_RECV_DATA_RES_RSP,
	MSG_ID_MMI_RSAT_CH_STATUS_RES_RSP,
	MSG_ID_MMI_CB_SUBSCRIBE_RSP,
	MSG_ID_MMI_SMS_SET_CB_MODE_RSP,
	MSG_ID_MMI_SMS_GET_CB_MODE_RSP,
	MSG_ID_MMI_EM_UPDATE_RSP,
	MSG_ID_MMI_VT_EM_GET_CONFIG_RSP,
	MSG_ID_MMI_VT_EM_SET_CONFIG_RSP,
	MSG_ID_MMI_EM_KEYPAD_EVENT_OUTPUT_RSP,
	MSG_ID_MMI_EM_CELL_RESEL_SUSPEND_RSP,
	MSG_ID_MMI_EM_CELL_RESEL_RESUME_RSP,
	MSG_ID_MMI_EM_GET_CELL_LOCK_RSP,
	MSG_ID_MMI_EM_SET_CELL_LOCK_RSP,
	MSG_ID_MMI_EM_EXT_GET_CELL_LOCK_RSP,
	MSG_ID_MMI_EM_EXT_SET_CELL_LOCK_RSP,
	MSG_ID_MMI_EM_NW_EVENT_NOTIFY_RSP,
	MSG_ID_MMI_EM_FEATURE_COMMAND_RSP,
	MSG_ID_MMI_EM_GET_CONFORM_TEST_PARAM_RSP,
	MSG_ID_MMI_EM_SET_CONFORM_TEST_PARAM_RSP,
	MSG_ID_MMI_EM_QUICK_TEST_REPORT_RES_RSP,
	MSG_ID_MMI_EM_SET_ESSP_RSP,
	MSG_ID_MMI_EM_GET_ESSP_RSP,
	MSG_ID_MMI_CPHS_UPDATE_ALS_RSP,
	MSG_ID_MMI_EQ_IRDA_OPEN_RSP,
	MSG_ID_MMI_EQ_IRDA_CLOSE_RSP,
	MSG_ID_MMI_EQ_USBCONFIG_RSP,
	MSG_ID_MMI_EQ_USBUART_SWITCH_PORT_RSP,
	MSG_ID_MMI_EQ_USBDETECT_RES_RSP,
	MSG_ID_WAP_MMC_READ_FOLDER_STATUS_OUTPUT_RSP,
	MSG_ID_WAP_MMC_UPLOAD_MSG_OUTPUT_RSP,
	MSG_ID_WAP_MMC_DELETE_MSG_OUTPUT_RSP,
	MSG_ID_WAP_MMC_READ_MSG_PATH_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_GREETING_TEXT_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_LANGUAGE_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_SILENT_MODE_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_VIBRATOR_MODE_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_DATE_TIME_FORMAT_RES_RSP,
	MSG_ID_MMI_EQ_QUERY_MUTE_MODE_RES_RSP,
	MSG_ID_MMI_READY_NOTIFY_RSP,
	MSG_ID_MMI_AT_GENERAL_RES_RSP,
	MSG_ID_MMI_EQ_VCARD_RES_RSP,
	MSG_ID_MMI_EQ_VCALENDAR_RES_RSP,
	MSG_ID_MMI_EQ_STR_RES_RSP,
	MSG_ID_MMI_UCM_AT_RES_RSP,
	MSG_ID_MMI_UCM_GENERAL_RCODE_RSP,
	MSG_ID_MMI_UCM_HF_CIEV_RCODE_RSP,
	MSG_ID_MMI_EQ_RINGTONE_PLAY_RES_RSP,
	MSG_ID_MMI_JAVA_LOCAL_INSTALL_RES_RSP,
	MSG_ID_MMI_L4_BT_SET_VR_RSP,
	MSG_ID_MMI_CTM_SET_STATUS_RSP,
	MSG_ID_MMI_VOIP_AT_CALL_CTRL_APPROVE_RES_RSP,
	MSG_ID_MMI_SMU_SIM_STATUS_UPDATE_RSP,
	MSG_ID_MMI_SMU_DUAL_SIM_TO_FLIGHT_MODE_RSP,
	MSG_ID_MMI_NW_SIM_MODE_SWITCH_START_RSP,
	MSG_ID_MMI_NW_SIM_MODE_SWITCH_STOP_RSP,
	MSG_ID_MMI_NW_SET_MONITOR_PEER_PCH_RSP,
	MSG_ID_MMI_NW_GET_MONITOR_PEER_PCH_RSP,
	MSG_ID_MMI_L4C_SET_SIM_CAPABILITY_RSP,
	MSG_ID_MMI_L4C_GET_SIM_CAPABILITY_RSP,
	MSG_ID_MMI_SS_MTLR_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_AERQ_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_AERP_BEGIN_RSP,
	MSG_ID_MMI_SS_AERP_END_RSP,
	MSG_ID_MMI_SS_AECL_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_MOLR_BEGIN_RSP,
	MSG_ID_MMI_SS_MOLR_END_RSP,
	MSG_ID_MMI_AGPS_ENABLE_DISABLE_RSP,
	MSG_ID_MMI_AGPS_KEY_UPDATE_RSP,
	MSG_ID_MMI_AGPS_CP_ABORT_RSP,
	MSG_ID_MMI_EQ_RAM_USAGE_RES_RSP,
	MSG_ID_MMI_EQ_LAUNCH_APP_RES_RSP,
	MSG_ID_MMI_EQ_APP_INFO_OUTPUT_RES_RSP,
	MSG_ID_MMI_EQ_SCREEN_TOUCH_RES_RSP,
	MSG_ID_MMI_EQ_SCRNORIENT_RES_RSP,
	MSG_ID_MMI_EQ_SCRNSIZE_QUERY_RES_RSP,
	MSG_ID_MMI_EQ_SCRNTCH_EVENT_OUTPUT_RSP,
	MSG_ID_MMI_EQ_SCREEN_SHOT_RES_RSP,
	MSG_ID_MMI_EQ_UART_TRANSFER_RSP,
	MSG_ID_MMI_EQ_UART_RELEASE_RSP,
	MSG_ID_MMI_EQ_PLAY_AUDIO_STREAM_RSP,
	MSG_ID_MMI_EQ_STOP_AUDIO_STREAM_RSP,
	MSG_ID_MMI_EQ_LCD_SET_CONTRAST_RSP,
	MSG_ID_MMI_EQ_SET_SILENT_MODE_RSP,
	MSG_ID_MMI_EQ_GET_MS_IMEI_RSP,
	MSG_ID_MMI_EQ_SET_MS_IMEI_RSP,
	MSG_ID_MMI_EQ_RTC_POWERON_STATE_RSP,
	MSG_ID_MMI_EQ_START_TIMER_RSP,
	MSG_ID_MMI_EQ_STOP_TIMER_RSP,
	MSG_ID_MMI_EQ_SIMULATE_KEY_PRESS_RSP,
	MSG_ID_MMI_EQ_SET_INDICATOR_RSP,
	MSG_ID_MMI_EQ_GET_INDICATOR_RSP,
	MSG_ID_MMI_EQ_DISPLAY_TEXT_RSP,
	MSG_ID_MMI_EQ_SET_GREETING_TEXT_RSP,
	MSG_ID_MMI_EQ_SET_VIBRATOR_MODE_RSP,
	MSG_ID_MMI_EQ_SET_COUNTRY_CODE_RSP,
	MSG_ID_MMI_EQ_GET_COUNTRY_CODE_RSP,
	MSG_ID_MMI_EQ_GET_BATTERY_STATUS_RSP,
	MSG_ID_MMI_EQ_LOAD_DEFAULT_CONFIG_RSP,
	MSG_ID_MMI_EM_SET_CELL_ID_LOCK_RSP,
	MSG_ID_MMI_UPDATE_MMI_DEFAULT_PROF_VALUE_RSP,
	MSG_ID_MMI_VM_PLAY_RSP,
	MSG_ID_MMI_VM_DEL_RSP,
	MSG_ID_MMI_VM_APPEND_RSP,
	MSG_ID_MMI_VM_RENAME_RSP,
	MSG_ID_MMI_VM_GET_INFO_RSP,
	MSG_ID_MMI_VM_STOP_RSP,
	MSG_ID_MMI_VM_ABORT_RSP,
	MSG_ID_MMI_VM_PAUSE_RSP,
	MSG_ID_MMI_VM_RESUME_RSP,
	MSG_ID_MMI_VM_RECORD_RSP,
	MSG_ID_WAP_START_DTMF_RSP,
	MSG_ID_WAP_STOP_DTMF_RSP,
	MSG_ID_WAP_DIAL_RSP,
	MSG_ID_WAP_SET_ENTRY_RSP,

	MSG_ID_MMI_CC_START_AUTO_DTMF_IND,
	MSG_ID_MMI_CC_START_AUTO_DTMF_FINISH_IND,
	MSG_ID_MMI_CC_DIAL_REQ_IND,
	MSG_ID_MMI_CC_DIAL_IND,
	MSG_ID_MMI_CC_CCM_IND,
	MSG_ID_MMI_CC_INTERNAL_ALERT_IND,
	MSG_ID_MMI_CC_CALL_WAIT_IND,
	MSG_ID_MMI_CC_CALL_RING_IND,
	MSG_ID_MMI_CC_CALL_CONNECT_IND,
	MSG_ID_MMI_CC_CALL_DISCONNECT_IND,
	MSG_ID_MMI_CC_CALL_RELEASE_IND,
	MSG_ID_MMI_CC_SPEECH_IND,
	MSG_ID_MMI_CC_NOTIFY_SS_IND,
	MSG_ID_MMI_CC_NOTIFY_SS_ECT_IND,
	MSG_ID_MMI_CC_NOTIFY_SS_CNAP_IND,
	MSG_ID_MMI_CC_NOTIFY_SS_CCBS_IND,
	MSG_ID_MMI_CC_CALL_ACCEPT_REQ_IND,
	MSG_ID_MMI_CC_CALL_ABORT_REQ_IND,
	MSG_ID_MMI_CC_CALL_SYNC_REQ_IND,
	MSG_ID_MMI_CC_VIDEO_CALL_STATUS_IND,
	MSG_ID_MMI_CC_CALL_PRESENT_IND,
	MSG_ID_MMI_CC_CPI_IND,
	MSG_ID_MMI_DATA_CALL_REQ_IND,
	MSG_ID_MMI_SS_CLIP_INTERROGATE_IND,
	MSG_ID_MMI_SS_CLIR_INTERROGATE_IND,
	MSG_ID_MMI_SS_CNAP_INTERROGATE_IND,
	MSG_ID_MMI_SS_COLP_INTERROGATE_IND,
	MSG_ID_MMI_SS_COLR_INTERROGATE_IND,
	MSG_ID_MMI_SS_USSR_IND,
	MSG_ID_MMI_SS_USSN_IND,
	MSG_ID_MMI_SMS_CB_GS_CHANGE_IND,
	MSG_ID_MMI_EQ_EXE_VOLUME_REQ_IND,
	MSG_ID_MMI_EQ_VOLUME_CHANGE_IND,
	MSG_ID_MMI_EQ_EXE_MUTE_REQ_IND,
	MSG_ID_MMI_EQ_MUTE_CHANGE_IND,
	MSG_ID_MMI_EQ_SET_SILENT_MODE_REQ_IND,
	MSG_ID_MMI_EQ_SET_GPIO_LEVEL_REQ_IND,
	MSG_ID_MMI_EQ_EXE_GPIO_LEVEL_REQ_IND,
	MSG_ID_MMI_EQ_PLAY_AUDIO_FINISH_IND,
	MSG_ID_MMI_EQ_GPIO_DETECT_IND,
	MSG_ID_MMI_EQ_ADC_ALL_CHANNEL_IND,
	MSG_ID_MMI_EQ_SET_SLEEP_MODE_REQ_IND,
	MSG_ID_MMI_EQ_SET_HAND_FREE_MODE_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_HAND_FREE_MODE_REQ_IND,
	MSG_ID_MMI_EQ_SET_CAM_REQ_IND,
	MSG_ID_MMI_EQ_SET_AVR_REQ_IND,
	MSG_ID_MMI_EQ_SET_RTC_TIME_REQ_IND,
	MSG_ID_MMI_EQ_DEL_RTC_TIMER_REQ_IND,
	MSG_ID_MMI_EQ_SET_DATE_TIME_FORMAT_REQ_IND,
	MSG_ID_MMI_EQ_CLOCK_TICK_IND,
	MSG_ID_MMI_EQ_ALARM_IND,
	MSG_ID_MMI_AT_ALARM_QUERY_REQ_IND,
	MSG_ID_MMI_AT_ALARM_SET_REQ_IND,
	MSG_ID_MMI_AT_ALARM_DELETE_REQ_IND,
	MSG_ID_MMI_EQ_SIMULATE_KEY_PRESS_REQ_IND,
	MSG_ID_MMI_EQ_SET_INDICATOR_REQ_IND,
	MSG_ID_MMI_EQ_DISPLAY_TEXT_REQ_IND,
	MSG_ID_MMI_EQ_KEYPAD_DETECT_IND,
	MSG_ID_MMI_AT_CBKLT_QUERY_REQ_IND,
	MSG_ID_MMI_AT_KEYPAD_EVENT_ACT_IND,
	MSG_ID_MMI_EQ_SET_LANGUAGE_REQ_IND,
	MSG_ID_MMI_EQ_SET_GREETING_TEXT_REQ_IND,
	MSG_ID_MMI_EQ_SET_VIBRATOR_MODE_REQ_IND,
	MSG_ID_MMI_EQ_POWER_ON_IND,
	MSG_ID_MMI_EQ_BATTERY_STATUS_IND,
	MSG_ID_MMI_EQ_LEAVE_PRECHARGE_IND,
	MSG_ID_MMI_EQ_FM_TEST_REQ_IND,
	MSG_ID_MMI_EQ_FACTORY_RESET_IND,
	MSG_ID_MMI_EQ_NVRAM_READY_IND,
	MSG_ID_MMI_NW_ATTACH_IND,
	MSG_ID_MMI_NW_REG_CAUSE_IND,
	MSG_ID_MMI_NW_REG_STATE_IND,
	MSG_ID_MMI_NW_RX_LEVEL_IND,
	MSG_ID_MMI_NW_TIME_ZONE_IND,
	MSG_ID_MMI_NW_SEL_MODE_IND,
	MSG_ID_MMI_NW_MMRR_SERVICE_STATUS_IND,
	MSG_ID_MMI_NW_UPDATE_ECC_IND,
	MSG_ID_MMI_NW_EF_RAT_MODE_CHANGE_IND,
	MSG_ID_MMI_NW_CFUN_STATE_REQ_IND,
	MSG_ID_MMI_SMU_PASSWORD_REQUIRED_IND,
	MSG_ID_MMI_SMU_SUPPORT_PLMN_LIST_IND,
	MSG_ID_MMI_SMU_FAIL_IND,
	MSG_ID_MMI_SMU_SML_STATUS_NOTIFY_IND,
	MSG_ID_MMI_SMU_STARTUP_INFO_IND,
	MSG_ID_MMI_SMU_CIPHER_IND,
	MSG_ID_MMI_SMU_VERIFY_PIN_RESULT_IND,
	MSG_ID_MMI_SIM_O2_PREPAID_SIM_IND,
	MSG_ID_MMI_PHB_LAST_NUMBER_READY_IND,
	MSG_ID_MMI_PHB_STARTUP_FINISH_IND,
	MSG_ID_MMI_PHB_UPDATE_IND,
	MSG_ID_MMI_PHB_STARTUP_READ_IND,
	MSG_ID_MMI_PHB_STARTUP_BEGIN_IND,
	MSG_ID_MMI_L4C_READ_PHB_REQ_IND,
	MSG_ID_MMI_L4C_WRITE_PHB_REQ_IND,
	MSG_ID_MMI_L4C_DELETE_PHB_REQ_IND,
	MSG_ID_MMI_L4C_READ_CLOG_REQ_IND,
	MSG_ID_MMI_L4C_WRITE_CLOG_REQ_IND,
	MSG_ID_MMI_L4C_DELETE_CLOG_REQ_IND,
	MSG_ID_MMI_L4C_READ_ADDITIONAL_REQ_IND,
	MSG_ID_MMI_L4C_WRITE_ADDITIONAL_REQ_IND,
	MSG_ID_MMI_L4C_DELETE_ADDITIONAL_REQ_IND,
	MSG_ID_MMI_SMS_DELIVER_MSG_IND,
	MSG_ID_MMI_SMS_STATUS_REPORT_IND,
	MSG_ID_MMI_SMS_MEM_AVAILABLE_IND,
	MSG_ID_MMI_SMS_MEM_EXCEED_IND,
	MSG_ID_MMI_SMS_MEM_FULL_IND,
	MSG_ID_MMI_SMS_READY_IND,
	MSG_ID_MMI_SMS_APP_DATA_IND,
	MSG_ID_MMI_SMS_MSG_WAITING_IND,
	MSG_ID_MMI_SMS_ENHANCED_VOICE_MAIL_IND,
	MSG_ID_MMI_SMS_SYNC_MSG_IND,
	MSG_ID_MMI_SMS_SEND_ABORT_START_IND,
	MSG_ID_MMI_SMS_SEND_ABORT_FINISH_IND,
	MSG_ID_MMI_SMS_STARTUP_BEGIN_IND,
	MSG_ID_MMI_SMS_STARTUP_FINISH_IND,
	MSG_ID_MMI_SMS_STARTUP_READ_MSG_IND,
	MSG_ID_MMI_USM_AT_REQ_IND,
	MSG_ID_MMI_SMS_MT_SMS_FINAL_ACK_IND,
	MSG_ID_MMI_SMS_NEW_MSG_PDU_IND,
	MSG_ID_MMI_SMS_CB_MSG_PDU_IND,
	MSG_ID_MMI_SMS_STARTUP_READ_IND,
	MSG_ID_MMI_SMS_GET_MEM_STATUS_IND,
	MSG_ID_MMI_SMS_ATCMD_CMGR_IND,
	MSG_ID_MMI_SMS_ATCMD_CMGL_IND,
	MSG_ID_MMI_SMS_ATCMD_CMGD_IND,
	MSG_ID_MMI_SMS_ATCMD_CMGW_IND,
	MSG_ID_MMI_SMS_ATCMD_EQSI_IND,
	MSG_ID_MMI_SMS_ATCMD_CGSMS_IND,
	MSG_ID_MMI_SMS_ATCMD_CSAS_IND,
	MSG_ID_MMI_SMS_ETWS_INFO_IND,
	MSG_ID_MMI_PS_GPRS_STATUS_UPDATE_IND,
	MSG_ID_MMI_SAT_DISPLAY_TEXT_IND,
	MSG_ID_MMI_SAT_GET_INKEY_IND,
	MSG_ID_MMI_SAT_GET_INPUT_IND,
	MSG_ID_MMI_SAT_SETUP_MENU_IND,
	MSG_ID_MMI_SAT_SELECT_ITEM_IND,
	MSG_ID_MMI_SAT_PLAY_TONE_IND,
	MSG_ID_MMI_SAT_CALL_SETUP_IND,
	MSG_ID_MMI_SAT_SEND_SMS_IND,
	MSG_ID_MMI_SAT_SEND_SS_IND,
	MSG_ID_MMI_SAT_SEND_USSD_IND,
	MSG_ID_MMI_SAT_MMI_INFO_IND,
	MSG_ID_MMI_SAT_SETUP_IDLE_DISPLAY_IND,
	MSG_ID_MMI_SAT_RUN_AT_COMMAND_IND,
	MSG_ID_MMI_SAT_SEND_DTMF_IND,
	MSG_ID_MMI_SAT_LANG_NOTIFY_IND,
	MSG_ID_MMI_SAT_LAUNCH_BROWSER_IND,
	MSG_ID_MMI_SAT_NO_OTHER_CMD_IND,
	MSG_ID_MMI_SAT_SIM_FILE_CHANGE_IND,
	MSG_ID_MMI_SAT_SETUP_EVENT_LIST_IND,
	MSG_ID_MMI_SAT_PROVIDE_LANG_INFO_IND,
	MSG_ID_MMI_SAT_OPEN_CHANNEL_IND,
	MSG_ID_MMI_SAT_CLOSE_CHANNEL_IND,
	MSG_ID_MMI_SAT_SEND_DATA_IND,
	MSG_ID_MMI_SAT_RECV_DATA_IND,
	MSG_ID_MMI_SAT_NOTIFY_MMI_IND,
	MSG_ID_MMI_RSAT_OPEN_CHANNEL_IND,
	MSG_ID_MMI_RSAT_CLOSE_CHANNEL_IND,
	MSG_ID_MMI_RSAT_SEND_DATA_IND,
	MSG_ID_MMI_RSAT_RECV_DATA_IND,
	MSG_ID_MMI_RSAT_CH_STATUS_IND,
	MSG_ID_MMI_CB_MSG_IND,
	MSG_ID_MMI_EM_STATUS_IND,
	MSG_ID_MMI_EM_LCM_TEST_IND,
	MSG_ID_MMI_EM_KEYPAD_EVENT_ACT_IND,
	MSG_ID_MMI_FACTORY_TEST_IND,
	MSG_ID_MMI_SET_MMI_DEFAULT_PROF_IND,
	MSG_ID_MMI_EM_RGB_TEST_REQ_IND,
	MSG_ID_MMI_EM_LCD_TEST_REQ_IND,
	MSG_ID_MMI_EM_NW_EVENT_NOTIFY_IND,
	MSG_ID_MMI_EM_QUICK_TEST_REPORT_IND,
	MSG_ID_MMI_CPHS_DISPLAY_CFU_IND,
	MSG_ID_MMI_CPHS_MMI_INFO_IND,
	MSG_ID_MMI_CPHS_DISPLAY_ALS_IND,
	MSG_ID_MMI_EQ_IRCOMM_CONNECT_IND,
	MSG_ID_MMI_EQ_IRCOMM_DISCONNECT_IND,
	MSG_ID_MMI_EQ_USBDETECT_IND,
	MSG_ID_WAP_MMC_READ_FOLDER_STATUS_REQ_IND,
	MSG_ID_WAP_MMC_UPLOAD_MSG_REQ_IND,
	MSG_ID_WAP_MMC_DELETE_MSG_REQ_IND,
	MSG_ID_WAP_MMC_READ_MSG_PATH_IND,
	MSG_ID_MMI_EQ_QUERY_GREETING_TEXT_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_LANGUAGE_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_SILENT_MODE_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_VIBRATOR_MODE_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_DATE_TIME_FORMAT_REQ_IND,
	MSG_ID_MMI_EQ_QUERY_MUTE_MODE_REQ_IND,
	MSG_ID_MMI_POWER_RESET_IND,
	MSG_ID_MMI_FACTORY_RESTORE_REQ_IND,
	MSG_ID_MMI_EQ_VCARD_REQ_IND,
	MSG_ID_MMI_EQ_VCALENDAR_REQ_IND,
	MSG_ID_MMI_EQ_STR_ENABLE_REQ_IND,
	MSG_ID_MMI_EQ_STR_REQ_IND,
	MSG_ID_MMI_UCM_AT_REQ_IND,
	MSG_ID_MMI_EQ_RINGTONE_PLAY_REQ_IND,
	MSG_ID_MMI_JAVA_LOCAL_INSTALL_REQ_IND,
	MSG_ID_MMI_L4_BT_FCTY_SET_PARAM_IND,
	MSG_ID_MMI_L4_BT_LOOPBACK_TEST_REQ_IND,
	MSG_ID_MMI_L4_BT_SET_VR_REQ_IND,
	MSG_ID_MMI_HZ_TAG_IND,
	MSG_ID_MMI_VOIP_AT_CALL_CTRL_APPROVE_IND,
	MSG_ID_MMI_EQ_PWNON_DUAL_SIM_IND,
	MSG_ID_MMI_SMU_SIM_STATUS_UPDATE_IND,
	MSG_ID_MMI_NW_RAC_ACTIVATED_IND,
	MSG_ID_MMI_NW_SEARCH_NORMAL_FINISH_IND,
	MSG_ID_MMI_SS_MTLR_BEGIN_IND,
	MSG_ID_MMI_SS_AERQ_BEGIN_IND,
	MSG_ID_MMI_SS_AECL_BEGIN_IND,
	MSG_ID_MMI_AGPS_NEW_KEY_NEEDED_IND,
	MSG_ID_MMI_AGPS_RESET_POSITIONING_IND,
	MSG_ID_MMI_AGPS_CP_START_IND,
	MSG_ID_MMI_AGPS_CP_END_IND,
	MSG_ID_MMI_EQ_RAM_USAGE_REQ_IND,
	MSG_ID_MMI_EQ_LAUNCH_APP_REQ_IND,
	MSG_ID_MMI_EQ_APP_INFO_OUTPUT_REQ_IND,
	MSG_ID_MMI_EQ_SCREEN_TOUCH_REQ_IND,
	MSG_ID_MMI_EQ_SCRNORIENT_REQ_IND,
	MSG_ID_MMI_EQ_SCRNSIZE_QUERY_REQ_IND,
	MSG_ID_MMI_EQ_SCRNTCH_EVENT_ACT_IND,
	MSG_ID_MMI_EQ_SCREEN_SHOT_REQ_IND,
	MSG_ID_MMI_EQ_AT_QUICK_INPUT_IND,
	MSG_ID_MMI_EQ_UART_TRANSFER_IND,
	MSG_ID_MMI_EQ_EXE_DEL_RTC_TIMER_REQ_IND,
	MSG_ID_MMI_VM_PLAY_FINISH_IND,
	MSG_ID_MMI_VM_RECORD_FINISH_IND,
	MSG_ID_WAP_AUTO_DTMF_COMPLETE_IND,
#if defined (__GPS_TRACK__)
    #include "..//..//..//track//os//os_inc//track_os_msgid_sap.h"
#endif /* __GPS_TRACK__ */

	MSG_ID_L4A_CODE_END,


/*MTK:END*/
	 /*---------------L4A_MSG_CODE_END---------------------*/
/* Johnny: if MMI want to send primitive to itself, please add primitive below */
#if defined(VRSI_ENABLE)
	MSG_ID_MMI_VRSI_ADD_CENTRAL_REQ,
#endif	 

    /* MoDIS AV Simulate event indication */
    //MSG_ID_VID_MODIS_EVENT_IND,         //delete
    
    /* Wen, Start */
    //MSG_ID_MMI_MMI_THM_ACTIVE_NOTIFY,
    //MSG_ID_MMI_MMI_TDL_DEL_NOTIFY,
    /* Wen, End */

    /* QQIM, start */
    /*MSG_ID_QQ_1,
    MSG_ID_QQ_2,
    MSG_ID_QQ_3,
    MSG_ID_QQ_4,
    MSG_ID_QQ_5,
    MSG_ID_QQ_6,
    MSG_ID_QQ_7,
    MSG_ID_QQ_8,*/
    /* QQIM, end */

/* for DDTCNT deletion notification */
    /*MSG_ID_MMI_DTCNT_REGISTER_DELETION_NOTIFY_REQ,
    MSG_ID_MMI_DTCNT_REGISTER_DELETION_NOTIFY_CNF,
    MSG_ID_MMI_DTCNT_DELETION_NOTIFY_IND,*/

    /* DTCNT SRV message */
    MSG_ID_SRV_DTCNT_WLAN_ATCMD_REQ,

    /* V33 BT test mode support */ 
    MSG_ID_BT_ADV_TEST_MODE_REQ,
    MSG_ID_BT_ADV_TEST_MODE_CNF,
    /* V33 BT test mode support end */ 
   /*MRE IOT begine*/
    MSG_ID_MMI_MRE_START_APP_WITH_CMD,
    MSG_ID_MMI_MRE_STOP_APP_WITH_CMD,
   /*MRE IOT end*/
   
   /* BOOTUP&SHUTDOWN IOT begin */
   MSG_ID_MMI_EQ_REBOOT_REQ,
   /* BOOTUP&SHUTDOWN IOT end */
   
   /*Cmd processor IOT begin*/
	 MSG_ID_MMI_CUSTOMIZED_COMMAND_PASS_IND,
	 MSG_ID_MMI_WRITE_DATA_TO_UART_REQ,
	 MSG_ID_MMI_RESPONSE_ERROR_CODE_REQ,
   /*Cmd processor IOT end*/
   
   /* BTBox gpio control cmd begin */
   MSG_ID_MMI_EQ_CONTROL_GPIO_REQ,
   /* BTBox gpio control cmd end */

   /*sensor start*/
   MSG_ID_MMI_EQ_HR_SENSOR_DATA_IND,
   /*sensor end*/

   /*MRE start*/
    MSG_ID_MRE_SWITCH_TO_AP_MODE,
   /*MRE end*/  
         
    /*wifi AT releated */
    MSG_ID_MMI_SET_WIFI_MODE_REQ,
    MSG_ID_MMI_WIFI_BEGIN = MSG_ID_MMI_SET_WIFI_MODE_REQ,
    MSG_ID_MMI_SET_WIFI_MODE_CNF,

    MSG_ID_MMI_GET_WIFI_MODE_REQ,
    MSG_ID_MMI_GET_WIFI_MODE_CNF,

    MSG_ID_MMI_WIFI_ADD_PROF_REQ,
    MSG_ID_MMI_WIFI_ADD_PROF_CNF,

    MSG_ID_MMI_WIFI_PROF_CONNECT_REQ,
    MSG_ID_MMI_WIFI_PROF_CONNECT_CNF,

    MSG_ID_MMI_WIFI_DISCONNECT_REQ,
    MSG_ID_MMI_WIFI_DISCONNECT_CNF,

    MSG_ID_MMI_WIFI_START_SCAN_REQ,
    MSG_ID_MMI_WIFI_START_SCAN_CNF,

    MSG_ID_MMI_WIFI_GET_IP_INFO_REQ,
    MSG_ID_MMI_WIFI_GET_IP_INFO_CNF,

    MSG_ID_MMI_WIFI_NOTIFY_IND,  
    MSG_ID_MMI_WIFI_END = MSG_ID_MMI_WIFI_NOTIFY_IND, 
    /*wifi AT end */
        
   /*---------------MMI_MSG_CODE_END---------------------*/


