#include "MMI_features.h"
#include "custresdef.h"
#ifdef __J2ME__
#include "j2me_custom.h"
#if (defined __OPTR_NONE__) && (defined(__MMI_MAINLCD_240X320__) || defined(__MMI_MAINLCD_240X400__))
    #define JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH "_png"
#else
    #define JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH ""
#endif
<?xml version="1.0" encoding="UTF-8"?>
<APP id="APP_JAVA" 
    #if defined(__MMI_APP_MANAGER_SUPPORT__)
        package_name = "native.mtk.funandgames"         /* Use "native.mtk." as the prefix of application name */
        img = "IMG_ID_JAVA_FNG_IMAGE"   									 /* Main menu icon image */
        launch = "mmi_fng_entry_screen"                /* Launch function of application. When tap on the icon in main menu, the function will be invoked. */
    #endif /*__MMI_APP_MANAGER_SUPPORT__*/
		name ="STR_SCR_JAVA_CAPTION">
    <!--Include Area-->
    <INCLUDE file="JavaAgencyDef.h"/>
    <INCLUDE file="GlobalResDef.h"/>
    <INCLUDE file="MainMenuDef.h"/> 
    <INCLUDE file="j2me_custom.h"/>
    <INCLUDE file="JavaAgencyGProt.h"/>
    <INCLUDE file="FunAndGamesResDef.h"/>
    <INCLUDE file="FunAndGamesProts.h"/>
    <INCLUDE file="GameResDef.h"/>
    
#ifdef __COSMOS_MMI_PACKAGE__
    <MEMORY extra_base="$(DEFAULTHEAPSIZE)" fg="$(HW_LAYER_BUFFER_SIZE)+max(max(max(total(SRV_MDI_VDOPLY_QVGA), total(SRV_MDI_CAMERA_ONLY_CAP_LCD)), total(SRV_MDI_VDOREC)), total(SRV_MDI_STREAMING_QVGA))" inc="J2me_custom_param.h,GlobalResDef.h"/>
#endif    

	<MENU id="MENU3108_JAVA" type="OPTION" str="STR_SCR_JAVA_CAPTION" img="IMG_MENU3108_JAVA" highlight="mmi_java_highlight_menu"></MENU>
	<MENU id="MENU_ID_FNG_SETTING_JAVA" type="OPTION" str="STR_ID_FNG_SETTING_JAVA" img="IMG_ID_FNG_SETTING_JAVA" highlight="mmi_fng_highlight_setting_java"></MENU>

#if (MAX_VM_INSTANCE_NUM > 1) /* 20110223,SUPPORT_JAVA_SHARE_MED */
	<MENU id="MENU_ID_FNG_JAVA_TASK_MANAGER" type="OPTION" str="STR_ID_FNG_JAVA_TASK_MANAGER" img="IMG_ID_FNG_SETTING_JAVA" highlight="mmi_fng_highlight_java_task_manager"></MENU>
#endif /* MAX_VM_INSTANCE_NUM > 1 */
     
    <MENU id="MENU_ID_JAVA_EM_TCK" type="APPSUB" str="STR_JAVA_EM_TCK">
		  <MENUITEM_ID>MENU_ID_JAVA_EM_NORMAL</MENUITEM_ID>
		  <MENUITEM_ID>MENU_ID_JAVA_EM_CLDC_TCK</MENUITEM_ID>
		  <MENUITEM_ID>MENU_ID_JAVA_EM_MIDP_TCK</MENUITEM_ID>
		  <MENUITEM_ID>MENU_ID_JAVA_EM_WMAPI_TCK</MENUITEM_ID>
		  <MENUITEM_ID>MENU_ID_JAVA_EM_MMAPI_TCK</MENUITEM_ID>
#if defined(KDWP_DEBUG)
		  <MENUITEM_ID>MENU_ID_JAVA_EM_KDWP</MENUITEM_ID>
#endif
    </MENU>
	  <MENUITEM id="MENU_ID_JAVA_EM_NORMAL" str="STR_JAVA_EM_NORMAL"/>
	  <MENUITEM id="MENU_ID_JAVA_EM_CLDC_TCK" str="STR_JAVA_EM_CLDC_TCK"/>
	  <MENUITEM id="MENU_ID_JAVA_EM_MIDP_TCK" str="STR_JAVA_EM_MIDP_TCK"/>
	  <MENUITEM id="MENU_ID_JAVA_EM_WMAPI_TCK" str="STR_JAVA_EM_WMAPI_TCK"/>
	  <MENUITEM id="MENU_ID_JAVA_EM_MMAPI_TCK" str="STR_JAVA_EM_MMAPI_TCK"/>
#if defined(KDWP_DEBUG)
    <MENU id="MENU_ID_JAVA_EM_KDWP" type="APPSUB" str="STR_JAVA_EM_KDWP">
        <MENUITEM_ID>MENU_ID_JAVA_EM_KDWP_MODE</MENUITEM_ID>
     </MENU>
    <MENUITEM id="MENU_ID_JAVA_EM_KDWP_MODE" str="STR_JAVA_EM_KDWP_MODE"/>
#endif
	<MENU id="MENU_JAVA_APP_MIDS_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
	#if !defined(__MMI_APP_MANAGER_SUPPORT__)
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_SELECT</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_LAUNCH</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_DELETE</MENUITEM_ID>
	#endif		
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_UPDATE</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_SETTING</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_INFO</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_PACKAGE</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_NETWORK_SETTINGS</MENUITEM_ID>
		<MENUITEM_ID>MENU_JAVA_APP_OPTION_RESTORE</MENUITEM_ID>
	</MENU>
	#if !defined(__MMI_APP_MANAGER_SUPPORT__)
	<MENUITEM id="MENU_JAVA_APP_OPTION_SELECT" str="STR_GLOBAL_SELECT" highlight="mmi_java_highlight_opt_select"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_LAUNCH" str="STR_JAVA_APP_OPTION_LAUNCH" highlight="mmi_java_highlight_opt_launch"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_DELETE" str="STR_GLOBAL_DELETE" highlight="mmi_java_highlight_opt_delete"/>
	#endif
	<MENUITEM id="MENU_JAVA_APP_OPTION_UPDATE" str="STR_GLOBAL_UPDATE" highlight="mmi_java_highlight_opt_update"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_SETTING" str="STR_GLOBAL_SETTINGS" highlight="mmi_java_highlight_opt_setting"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_INFO" str="STR_GLOBAL_DETAILS" highlight="mmi_java_highlight_opt_info"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_PACKAGE" str="STR_GLOBAL_SEND" highlight="mmi_java_highlight_opt_package"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_NETWORK_SETTINGS" str="STR_JAVA_APP_OPTION_NETWORK_SETTINGS" highlight="mmi_java_highlight_opt_network_profile"/>
	<MENUITEM id="MENU_JAVA_APP_OPTION_RESTORE" str="STR_ID_FNG_SECURITY_JAVA_RESTORE" highlight="mmi_java_highlight_opt_restore"/>
	<MENUITEM id="MENU_ID_FMGR_JAVA_OPTION_EXECUTE" str="STR_GLOBAL_INSTALL" />
	<MENUITEM id="MENU_ID_FMGR_JAVA_OPTION_PACKAGE" str="STR_GLOBAL_SEND" />
	<STRING id ="STR_ID_FNG_SECURITY_JAVA_RESTORE"/>

	<STRING id ="STR_ID_FNG_JAVA_TASK_MANAGER"/>
	<STRING id ="STR_JAVA_ERROR_OVERMAX_LAUNCH_NUM"/>
	
	<STRING id="STR_SCR_JAVA_CAPTION"/>
	<STRING id="STR_JAVA_EM"/>
	<STRING id="STR_JAVA_EM_TCK"/>
#if defined(__MMI_JAVA_FMGR_HYPERLINK__)
    <STRING id="STR_SCR_JAVA_GAMES"/>
    <STRING id="STR_JAVA_PROGRAM"/>
    <STRING id="STR_JAVA_PROGRAMS"/>
    <STRING id="STR_JAVA_QUESTIONARY"/>
#endif
	<STRING id="STR_JAVA_APP_OPTION_LAUNCH"/>
	<STRING id="STR_JAVA_APP_OPTION_INFO"/>
	<STRING id="STR_JAVA_APP_OPTION_RESTORE"/>
	<STRING id="STR_JAVA_EM_NORMAL"/>
	<STRING id="STR_JAVA_EM_CLDC_TCK"/>
	<STRING id="STR_JAVA_EM_MIDP_TCK"/>
	<STRING id="STR_JAVA_EM_WMAPI_TCK"/>
	<STRING id="STR_JAVA_EM_MMAPI_TCK"/>
#if defined(KDWP_DEBUG)
    <STRING id="STR_JAVA_EM_KDWP"/>
    <STRING id="STR_JAVA_EM_KDWP_MODE"/>
    <STRING id="STR_JAVA_EM_KDWP_CATCHER_MODE"/>
    <STRING id="STR_JAVA_EM_KDWP_COMPORT_MODE"/>
#endif
	<STRING id="STR_JAVA_SETTING_NETWORK_ACCESS"/>
	<STRING id="STR_JAVA_SETTING_AUTO_INVOCATION"/>
	<STRING id="STR_JAVA_SETTING_MESSAGING"/>
	<STRING id="STR_JAVA_SETTING_MULTIMEDIA"/>
	<STRING id="STR_JAVA_SETTING_FILE_READ"/>
	<STRING id="STR_JAVA_SETTING_FILE_WRITE"/>
	<STRING id="STR_JAVA_SETTING_LOCAL_CONNECTIVITY"/>
#ifdef SUPPORT_JSR_179
	<STRING id="STR_JAVA_SETTING_LOCATION_ACCESS"/>
	<STRING id="STR_ID_FNG_SETTING_JAVA_LOCATION"/>
	<STRING id="STR_JAVA_AGPS_CONTROL_PLANE"/>
	<STRING id="STR_JAVA_AGPS_USER_PLANE"/>
	<STRING id="STR_JAVA_GPS_ONLY"/>
#endif
	<STRING id="STR_JAVA_INFO_NAME"/>
	<STRING id="STR_JAVA_INFO_SIZE"/>
	<STRING id="STR_JAVA_INFO_VERSION"/>
	<STRING id="STR_JAVA_INFO_VENDOR"/>
	<STRING id="STR_JAVA_INFO_DESC"/>
	<STRING id="STR_JAVA_INFO_WEB"/>
	<STRING id="STR_JAVA_INFO_AUTH"/>
	<STRING id="STR_JAVA_INFO_CONN"/>
	<STRING id="STR_JAVA_INFO_BYTES"/>
    <STRING id="STR_JAVA_INFO_BYTE"/>
	<STRING id="STR_JAVA_PERM_USERDENY"/>
	<STRING id="STR_JAVA_PERM_ONESHOT"/>
	<STRING id="STR_JAVA_PERM_SESSION"/>
	<STRING id="STR_JAVA_PERM_BLANKET"/>
	<STRING id="STR_JAVA_PERM_BLANKET_GRANTED"/>
	<STRING id="STR_JAVA_PERM_DMN_OPERATOR"/>
	<STRING id="STR_JAVA_PERM_DMN_MANUFACTURER"/>
	<STRING id="STR_JAVA_PERM_DMN_3RDPARTY"/>
	<STRING id="STR_JAVA_PERM_DMN_UNTRUSTED"/>
	<STRING id="STR_JAVA_CANCELLED"/>
	<STRING id="STR_JAVA_START_INSTALLING"/>
	<STRING id="STR_JAVA_VM_INSTALLING"/>
	<STRING id="STR_JAVA_INSTALLED"/>
	<STRING id="STR_JAVA_DELETE_ASK"/>
    <STRING id="STR_JAVA_UPDATE"/>
	<STRING id="STR_JAVA_START_UPDATING"/>
	<STRING id="STR_JAVA_UPDATED"/>
#ifdef JAVA_USE_RESERVE_STRING
	<STRING id="STR_JAVA_UPDATE_FAILED"/>
#endif
	<STRING id="STR_JAVA_LAUNCH_ASK"/>
	<STRING id="STR_JAVA_KEEP_RMS"/>
	<STRING id="STR_JAVA_STOPPED"/>
    <STRING id="STR_JAVA_RIGHT_ARRIVED"/>
#ifdef __DM_SCOMO_SUPPORT__
    <STRING id="STR_JAVA_DM_INSTALL_ARRIVED"/>
    <STRING id="STR_JAVA_DM_REMOVE_ARRIVED"/>
    <STRING id="STR_JAVA_DM_INSTALL_REQUSET"/>
    <STRING id="STR_JAVA_DM_REMOVE_REQUSET"/>
    <STRING id="STR_JAVA_DM_ASK_EXECUATE_INSTALL"/>
    <STRING id="STR_JAVA_DM_ASK_EXECUATE_REMOVE"/>
#endif
	<STRING id="STR_JAVA_VM_BUSY"/>
	<STRING id="STR_JAVA_WAIT"/>
	<STRING id="STR_JAVA_LAUNCH_AFTER_INSTALL"/>
	<STRING id="STR_JAVA_CHANGE_STATE_TITLE"/>
	<STRING id="STR_JAVA_TERMINATE_DIALOG_TITLE"/>
	<STRING id="STR_JAVA_RESUME_DIALOG_TITLE"/>
	<STRING id="STR_JAVA_TERMINATE"/>
	<STRING id="STR_JAVA_MINIMIZE"/>
	<STRING id="STR_JAVA_BUSY_FOR_PAUSE_MODE"/>
	<STRING id="STR_JAVA_BUSY_FOR_MINIMIZE_MODE"/>
	<STRING id="STR_JAVA_STOP_TIMEALARM_FOR_PAUSE_MODE"/>
	<STRING id="STR_JAVA_FORCE_TERMINATE"/>
    <STRING id="STR_JAVA_DELETE_MENU"/>
    <STRING id="STR_JAVA_MIDLET_MESSAGE"/>
	<STRING id="STR_JAVA_START_UPDATE_ASK"/>
    <STRING id="STR_JAVA_PUSH_INSTALL_ASK"/>
	<STRING id="STR_JAVA_PUSH_LAUNCH_ASK"/>
	<STRING id="STR_JAVA_PUSH_TASK_MANAGER"/>
	<STRING id="STR_JAVA_PUSH_LAUNCH_CONFIRM_IN_BGCALL"/>
	<STRING id="STR_JAVA_RESET_RMS_ASK"/>
	<STRING id="STR_JAVA_PUSH_LAUNCH_ASK_ME_LATER"/>
	<STRING id="STR_JAVA_LAUNCH_FAIL"/>
	<STRING id="STR_JAVA_LAUNCH_FAIL_CONFIRM"/>
    <STRING id="STR_JAVA_PACKAGE_CONFIRM"/>
    <STRING id="STR_JAVA_SAVE_AS_FILE"/>
	<STRING id="STR_JAVA_ALERT"/>
	<STRING id="STR_JAVA_ERROR_CODE_OLD_VERSION"/>
    <STRING id="STR_JAVA_ERROR_CODE_ALREADY_INSTALLED"/>
	<STRING id="STR_JAVA_ERROR_CODE_NEW_VERSION"/>
	<STRING id="STR_JAVA_ERROR_CODE_NOT_FOUND"/>
	<STRING id="STR_JAVA_ERROR_CODE_INVALID_JAD"/>
	<STRING id="STR_JAVA_ERROR_CODE_MISSING_INFO_JAD"/>
	<STRING id="STR_JAVA_ERROR_CODE_MISSING_INFO_JAR"/>
    <STRING id="STR_JAVA_ERROR_CODE_DEVICE_INCOMPATIBLE"/>
    <STRING id="STR_JAVA_ERROR_CODE_JAD_MOVED"/>
    <STRING id="STR_JAVA_ERROR_CODE_JAR_NOT_FOUND"/>
    <STRING id="STR_JAVA_ERROR_CODE_INVALID_JAR_URL"/>
    <STRING id="STR_JAVA_ERROR_CODE_CORRUPT_JAR"/>
    <STRING id="STR_JAVA_ERROR_CODE_INFO_MISMATCH"/>
    <STRING id="STR_JAVA_ERROR_CODE_VERIFY_FAILED"/>
    <STRING id="STR_JAVA_ERROR_CODE_AUTHORIZATION_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_PUSH_DUP_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_PUSH_PROTO_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_TRUSTED_OVERWRITE_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_DEFAULT_GAME"/>
    <STRING id="STR_JAVA_ERROR_CODE_DISK_OP_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_UNKNOWN_FAILURE"/>
    <STRING id="STR_JAVA_ERROR_CODE_CANCEL"/>
    <STRING id="STR_JAVA_ERROR_CODE_OVER_MAX_INSTALL"/>
    <STRING id="STR_JAVA_ERROR_CODE_POST_ERROR"/>
    <STRING id="STR_JAVA_ERROR_CODE_NO_CARD"/>
    <STRING id="STR_JAVA_ERROR_CODE_BT_IN_USE"/>
    <STRING id="STR_JAVA_ERROR_CODE_MIDLET_RUNNING"/>
    <STRING id="STR_JAVA_ERROR_CODE_NETWORK_FAILTURE"/>
    <STRING id="STR_JAVA_ERROR_FAIL_TO_PACKAGE"/>
    <STRING id="STR_JAVA_ERROR_CODE_WRITE_PROTECTION"/>
    <STRING id="STR_JAVA_ERROR_CODE_INCORRECT_MIDLET_DATA"/>
    <STRING id="STR_JAVA_ERROR_DISK_NOT_FOUND_WHEN_UPDATE"/>
    <STRING id="STR_JAVA_INSTALL_UNTRUSTED_MIDS_CONFIRM"/>
    <STRING id="STR_JAVA_DEFAULT_GAME_CAN_NOT_UPDATE"/>
    <STRING id="STR_JAVA_INSTALL_UPDATE_NOT_NEW_VERSION"/>
	<STRING id="STR_JAVA_INSTALL_UPDATE_LOCAL_INSTALL"/>
    <STRING id="STR_JAVA_PUSH_INSTALL"/>
    <STRING id="STR_JAVA_NORMAL_INSTALL"/>
    <STRING id="STR_JAVA_INSTALL_NA"/>
    <STRING id="STR_JAVA_TOO_MANY_MID"/>
    <STRING id="STR_JAVA_DRM_ACQUIRE_RIGHT_CONFIRM"/>
    <STRING id="STR_JAVA_WAITING_RIGHT"/>
    <STRING id="STR_JAVA_URL_TOO_LONG"/>
    <STRING id="STR_JAVA_INSTALL_DRM_NO_RIGHT"/>
    <STRING id="STR_JAVA_INFO_DOMAIN"/>
	<IMAGE id="IMG_JAVA_POWERED">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVLOGO.bmp"</IMAGE>
	<IMAGE id="IMG_JAVA_STAR1">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVSTAR1.bmp"</IMAGE>
	<IMAGE id="IMG_JAVA_STAR2">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVSTAR2.bmp"</IMAGE>
	<IMAGE id="IMG_JAVA_DONE">CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_ACT"__MMI_RES_TYPE_POPUP_SCREEN__</IMAGE>
	<IMAGE id="IMG_JAVA_LOADING">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_Loading"</IMAGE>
	<STRING id="STR_JAVA_PUSH_BUSY"/>
	<STRING id="STR_JAVA_PERMISSION_SOCKET"/>
	<STRING id="STR_JAVA_PERMISSION_HTTP"/>
	<STRING id="STR_JAVA_PERMISSION_HTTPS"/>
	<STRING id="STR_JAVA_PERMISSION_HTTPS"/>
	<STRING id="STR_JAVA_PERMISSION_SSL"/>
	<STRING id="STR_JAVA_PERMISSION_SSL"/>
        <STRING id="STR_JAVA_PERMISSION_DATAGRAM"/>
  	 <STRING id="STR_JAVA_PERMISSION_SVR_SOCKET"/>
        <STRING id="STR_JAVA_PERMISSION_SVR_DATAGRAM"/>
        <STRING id="STR_JAVA_PERMISSION_RTSP"/>
       <STRING id="STR_JAVA_PERMISSION_COMM"/>
        <STRING id="STR_JAVA_PERMISSION_PUSH"/>
       <STRING id="STR_JAVA_PERMISSION_SMS"/>
       <STRING id="STR_JAVA_PERMISSION_CBS"/>
       <STRING id="STR_JAVA_PERMISSION_MMS"/>
        <STRING id="STR_JAVA_PERMISSION_RECORD_CTRL"/>
        <STRING id="STR_JAVA_PERMISSION_SNAPSHOT"/>
        <STRING id="STR_JAVA_PERMISSION_FILE_READ"/>
	<STRING id="STR_JAVA_PERMISSION_FILE_WRITE"/>
    	<STRING id="STR_JAVA_PERMISSION_CONTACT_LIST_READ"/>
	<STRING id="STR_JAVA_PERMISSION_EXCLUSIVE_PUSH"/>
	<STRING id="STR_JAVA_PERMISSION_EXCLUSIVE_NET"/>
	<STRING id="STR_JAVA_PERMISSION_UNKNOWN"/>
	<STRING id="STR_JAVA_PERMISSION_CONTACT_LIST_WRITE"/>
	<STRING id="STR_JAVA_PERMISSION_EVENT_LIST_READ"/>
	<STRING id="STR_JAVA_PERMISSION_EVENT_LIST_WRITE"/>
	<STRING id="STR_JAVA_PERMISSION_TODO_LIST_READ"/>
	<STRING id="STR_JAVA_PERMISSION_TODO_LIST_WRITE"/>
	<STRING id="STR_JAVA_PERMISSION_OBEX_CLIENT"/>
	<STRING id="STR_JAVA_PERMISSION_OBEX_SERVER"/>
	<STRING id="STR_JAVA_PERMISSION_OBEX_CLIENT_TCP"/>
	<STRING id="STR_JAVA_PERMISSION_OBEX_SERVER_TCP"/>
	<STRING id="STR_JAVA_PERMISSION_BT_CLIENT"/>
	<STRING id="STR_JAVA_PERMISSION_BT_SERVER"/>
	<STRING id="STR_JAVA_PERMISSION_TELEPHONE"/>
	<STRING id="STR_JAVA_PERMISSION_LOCATION"/>
	<STRING id="STR_JAVA_PERMISSION_LOCATION_ORIENTATION"/>
	<STRING id="STR_JAVA_PERMISSION_LOCATION_PRXLISTENER"/>
	<STRING id="STR_JAVA_PERMISSION_LANDMARKSTORE_READ"/>
	<STRING id="STR_JAVA_PERMISSION_LANDMARKSTORE_WRITE"/>
	<STRING id="STR_JAVA_PERMISSION_LANDMARKSTORE_CATEGORY"/>
	<STRING id="STR_JAVA_PERMISSION_LANDMARKSTORE_MANAGEMENT"/>
	<STRING id="STR_ID_FNG_SETTING_JAVA"/>
    	<STRING id="STR_ID_FNG_SETTING_JAVA_AUD"/>
    	<STRING id="STR_ID_FNG_SETTING_JAVA_VIB"/>
    	<STRING id="STR_ID_FNG_SETTING_JAVA_BKLIGHT"/>
    <STRING id="STR_ID_FNG_SETTING_JAVA_NET_ICON"/>
#ifdef __MMI_FOURWAYS_KEY_DISABLE__
    <STRING id="STR_ID_FNG_SETTING_JAVA_VK"/>
#endif
    <STRING id="STR_ID_FNG_SETTING_JAVA_PROF_ID"/>
#ifdef __MMI_DUAL_SIM_MASTER__
    <STRING id="STR_ID_FNG_SETTING_JAVA_PROF1"/>
    <STRING id="STR_ID_FNG_SETTING_JAVA_PROF2"/>
#endif
    <STRING id="STR_ID_FNG_SETTING_JAVA_USER_SPECFIC"/>
    <STRING id="STR_ID_FNG_SETTING_JAVA_SYS_DEFAULT"/>
    <STRING id="STR_ID_FNG_SETTING_JAVA_PROF_MODE"/>
    <STRING id="STR_JAVA_NOTIFY_POSTING"/>
    <STRING id="STR_JAVA_REPORT_SENDING"/>
    <STRING id="STR_JAVA_DELETED_BUT_FAILED_TO_SEND_REPORT"/>
    <STRING id="STR_JAVA_INSTALLED_BUT_FAILED_TO_SEND_REPORT"/>
#ifdef JAVA_SETTING_SHOW_FREE_STORAGE
    <STRING id="STR_ID_FNG_SETTING_JAVA_STORAGE"/>
#endif
    <STRING id="STR_ID_FNG_SETTING_JAVA_HEAP"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_COMPLETION_DATE"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_NICK_NAME"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_PREFERRED_NUMBER"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_ATTR_NONE"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_TODO_STATUS"/>
    <STRING id="STR_ID_FNG_JAVA_PIM_PHOTO"/>
    <STRING id="STR_JAVA_TERMINATE_JAVA_GAME"/>
    <STRING id="STR_JAVA_TERMINATE_EUREKA"/>
    <STRING id="STR_JAVA_ERROR_UNSUPPORT_MIDLET"/>
    <STRING id="STR_JAVA_PERMISSION_SETTING_FAIL"/>
    <STRING id="STR_JAVA_PERMISSION_TITLE"/>
	<STRING id="STR_JAVA_PERMISSION_TRUSTED_TITLE"/>
	<STRING id="STR_JAVA_PERMISSION_UNTRUSTED_TITLE"/>
   	 <STRING id="STR_JAVA_MINIMIZE_NOTIFY"/>
    	<STRING id="STR_JAVA_PAUSE_NOTIFY"/>
    	<STRING id ="STR_JAVA_RESUME_NOTIFY"/>
    	<STRING id="STR_JAVA_VM_TERMINATING"/>
	<STRING id="STR_ID_JAVA_NETWORK"/>
	<STRING id="STR_ID_JAVA_NW_USE_DEFAULT"/>
	<STRING id="STR_JAVA_APP_OPTION_NETWORK_SETTINGS"/>
	<STRING id="STR_JAVA_APP_NETWORK_SETTINGS"/>
	<STRING id="STR_JAVA_ERROR_OVERMAX_LAUNCH_NUM"/>
	<STRING id="STR_JAVA_FORCE_TERMINATE_BALLOON"/>
	<IMAGE id="IMG_ID_JAVA_PLAY">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_PLAY.bmp"</IMAGE>
	<IMAGE id="IMG_MENU3108_JAVA">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_FGJAVA.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVST.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_AUD">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAAUD.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_VIB">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAVIB.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_BKLIGHT">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVALIGHT.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_NET_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JNET.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_VK">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAVK.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_PROF_ID">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JNET.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_STORAGE">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JDATA.bmp"</IMAGE>
	<IMAGE id="IMG_ID_FNG_SETTING_JAVA_HEAP">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JHEAP.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_MMS_BUSY">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_MMSB.BMP"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SMS_SENDING">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_SMSSENDING.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM1_GPRS_SERVICE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_GPRS.BMP"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM1_EDGE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_EDGE.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM2_GPRS_SERVICE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_GPRS_SIM2.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM2_EDGE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_EDGE_SIM2.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM3_GPRS_SERVICE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_GPRS_SIM3.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM3_EDGE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_EDGE_SIM3.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM4_GPRS_SERVICE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_GPRS_SIM4.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_SIM4_EDGE">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_EDGE_SIM4.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_CSD">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_CSD.bmp"</IMAGE>
	<IMAGE id="IMG_ID_JAVA_FULLSCREEN_CALL_INDICATOR">CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\StatusIcons"JAVA_FULLSCREEN_STATUS_ICON_IMAGE_FILE_PATH"\\\\JAVA\\\\SI_CallActive.bmp"</IMAGE>
#ifdef __SUPPORT_JUI_VIRTUAL_KEYPAD__
#ifndef __SUPPORT_JUI_COSMOS_SLIM_VIRTUAL_KEYPAD__
  <IMAGE id="IMG_ID_JAVA_VK_BG">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_BG.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button1_D.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_UP">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button1_N.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_DOWN">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button1_P.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_DARK_GRAY_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button2_D.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_DARK_GRAY_UP">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button2_N.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_DARK_GRAY_DOWN">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Button2_P.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LSK">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Left.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_RSK">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Right.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_NAV_LEFT">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Nav_Left.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_NAV_RIGHT">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Nav_Right.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_NAV_UP">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Nav_Up.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_NAV_DOWN">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Nav_Down.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_NAVIGATION">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Navigation.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_STAR">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Star.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_POUND">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Java_VK_Hash.png"</IMAGE>
  <STRING id="STR_JAVA_VK_123">123</STRING>
#else
  <IMAGE id="IMG_ID_JAVA_VK_BG">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Key_Support\\\\Java_VK_BG.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Key_Support\\\\Java_VK_Button1_D.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_UP">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Key_Support\\\\Java_VK_Button1_N.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LIGHT_GRAY_DOWN">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Key_Support\\\\Java_VK_Button1_P.9slice.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_LSK">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\\Key_Support\\\\LEFT.png"</IMAGE>
  <IMAGE id="IMG_ID_JAVA_VK_RSK">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\JAVA_VK\\\Key_Support\\\\\RIGHT.png"</IMAGE>
#endif
#endif
#if defined(__MMI_APP_MANAGER_SUPPORT__)
	<IMAGE id="IMG_ID_JAVA_FNG_IMAGE">CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\Launcher\\\\MainMenu\\\\Icons\\\\Java.png"</IMAGE>
#endif	
	<MENU id="J2ME_MENU_FULLSCREEN_EDITOR_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>J2ME_MENU_FULLSCREEN_EDITOR_OPTION_DONE</MENUITEM_ID>
		<MENUITEM_ID>J2ME_MENU_FULLSCREEN_EDITOR_OPTION_INPUT_METHOD</MENUITEM_ID>
	</MENU>
		<MENUITEM id="J2ME_MENU_FULLSCREEN_EDITOR_OPTION_DONE" str="STR_GLOBAL_DONE"/>
		<MENUITEM id="J2ME_MENU_FULLSCREEN_EDITOR_OPTION_INPUT_METHOD" str="STR_GLOBAL_INPUT_METHOD"/>
#ifdef OGDR_SECURITY_SETTING
<!--#ifndef __MMI_VRE_MAIN_MENU__-->
    	<MENU id="MENU_ID_FNG_SECURITY_JAVA" type="OPTION" str="STR_ID_FNG_SECURITY_JAVA" img="IMG_ID_FNG_SECURITY_JAVA" highlight="mmi_fng_highlight_security_java"></MENU>
 <!--#else -->
  <!--  <MENUITEM id="MENU_ID_FNG_SECURITY_JAVA" str="STR_ID_FNG_SECURITY_JAVA" highlight="mmi_fng_highlight_security_java" />-->
#endif

#ifdef __OP01__
	<STRING id="STR_ID_JAVA_MOBILE_STOCK"/>
	<STRING id="STR_ID_JAVA_JAD_DOWNLOAD_SUCCESS"/>
        <STRING id="STR_ID_JAVA_JAR_DOWNLOAD_SUCCESS"/>
#endif

    <STRING id="STR_ID_FNG_SECURITY_JAVA"/>
    <STRING id="STR_ID_FNG_SECURITY_JAVA_DOMAIN_CHANGE"/>
    <STRING id="STR_ID_FNG_SECURITY_JAVA_RESTORE_DEFAULT_CONFIRM"/>
    <STRING id="STR_ID_FNG_DOMAIN_STATUS_JAVA"/>
    <IMAGE id="IMG_ID_FNG_SECURITY_JAVA">CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVST.bmp"</IMAGE>
<!--#endif-->
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_SOUND" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA sound setting </DESCRIPTION>
    </CACHEDATA>
 <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_PROF_ID" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA nw profile setting </DESCRIPTION>
    </CACHEDATA>
		<CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_BKLIGHT_ID" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA backlight setting </DESCRIPTION>
    </CACHEDATA>
     <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_VIB" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA vibration setting </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_BKL">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> no use now </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_LED">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> no use now </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_VK" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA vk setting </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_NET_ICON" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> JAVA nw icon setting </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_SIM_ID">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> NVRAM_JAVA_SETTING_SIM_ID </DESCRIPTION>
    </CACHEDATA>
    <CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_PROF2_ID">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> NVRAM_JAVA_SETTING_PROF2_ID </DESCRIPTION>
    </CACHEDATA> 
	<CACHEDATA type="byte" id="NVRAM_JAVA_SETTING_LOCATION">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> NVRAM_JAVA_SETTING_LOCATION </DESCRIPTION>
    </CACHEDATA>
</APP>
<FILE_TYPES>
<FILE_OPTION_HDLR option = "MENU_ID_FMGR_JAD_TYPE_OPTIONS" enabler = "mmi_java_jad_option_enabler" />
<FILE_OPTION_HDLR option = "MENU_ID_FMGR_JAVA_OPTION_EXECUTE" handler="mmi_java_fmgr_install_hdlr" />
<FILE_OPTION_HDLR option = "MENU_ID_FMGR_JAVA_OPTION_PACKAGE" handler="mmi_java_entry_send_screen_from_fgmr" />
</FILE_TYPES>

#ifdef __MMI_USB_SUPPORT__
<RECEIVER id="EVT_ID_USB_ENTER_MS_MODE" proc="jam_enter_usb_ms_callback"/>
#endif
#ifdef __COSMOS_MMI_PACKAGE__
<RECEIVER id="EVT_ID_VAPP_HOME_ACTIVE" proc="jam_enter_idle_screen_notify"/>
#else
<RECEIVER id="EVT_ID_IDLE_GROUP_ENTER" proc="jam_enter_idle_screen_notify"/>
#endif
#endif