#include "custom_rec_config.h"
#if defined(MT6255)
#include "custom_emi_release.h"
#endif

void custom_rec_init_table(void)
{
    kal_uint32 i,j;
    for(i=0; i<MAX_CUSTOM_REC_CONFIG_TBL_CONFIG_NUM ;i++)
    {
        for(j=0; j<MAX_CUSTOM_REC_CONFIG_TBL_SETTING_NUM; j++)
        {
            custom_rec_config_table[i][j]  = SETTING_CONFIG_VALUE;
        }
    }
    for(i=0; i<SETTING_CONFIG_TARGET_END ;i++)
    {
        custom_rec_config_setting_table[i].type = SETTING_CONFIG_TYPE_VALUE;
    }
}



void custom_rec_set_table(void)
{
    /* please modify setting start from this */
#if defined( MJPG_ENCODE) && defined( MP4_ENCODE) && defined(H264_ENCODE)
#if defined (MT6255)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   #ifdef __EMI_CLK_200MHZ__
   SETTING_SET_ELEMENT(RESOLUTION, WVGA);
   #else
   SETTING_SET_ELEMENT(RESOLUTION, VGA);
   #endif
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, H264);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

#endif
#elif defined( MJPG_ENCODE) && defined( MP4_ENCODE)

#if defined(MT6253) ||defined(MT6252) || defined(MT6252H) || defined(MT6253D)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

#elif defined (MT6250) 

#ifdef __MED_VIDEO_ULC__
	 kal_uint32 i, j;

	custom_rec_init_table();

	SETTING_SET_START(0);
	SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MJPG);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(0);

	SETTING_SET_START(1);
	SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MP4);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(1);

    SETTING_SET_START(2);
	SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MP4);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(2);

    SETTING_SET_START(3);
	SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, 3GP);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(3);

    SETTING_SET_START(4);
	SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MJPG);
	SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
	SETTING_SET_END(4);

#else
   #if defined(__MPEG4_ENC_SW_SLIM__) && defined(__MJPEG_ENC_SW_SLIM__)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

   #else
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, WQVGA);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);
   #endif
   #endif
#elif defined (MT6260) 

#ifdef __MED_VIDEO_ULC__
	 kal_uint32 i, j;

	custom_rec_init_table();

	SETTING_SET_START(0);
	SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MJPG);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(0);

	SETTING_SET_START(1);
	SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MP4);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(1);

    SETTING_SET_START(2);
	SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MP4);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(2);

    SETTING_SET_START(3);
	SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, 3GP);
	SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	SETTING_SET_END(3);

    SETTING_SET_START(4);
	SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
	SETTING_SET_ELEMENT(CODEC, MJPG);
	SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
	SETTING_SET_END(4);

#else
   #if defined(__MPEG4_ENC_SW_SLIM__) && defined(__MJPEG_ENC_SW_SLIM__)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

   #else
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);
   #endif
   #endif
#elif defined (MT6235)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, CIF);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, CIF);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

#elif defined (MT6236)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);
#elif defined (MT6255)
	kal_uint32 i, j;

   custom_rec_init_table();

   SETTING_SET_START(0);
   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   #ifdef __EMI_CLK_200MHZ__
   SETTING_SET_ELEMENT(RESOLUTION, WVGA);
   #else
   SETTING_SET_ELEMENT(RESOLUTION, VGA);
   #endif
   SETTING_SET_END(0);


   SETTING_SET_START(1);
   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
   SETTING_SET_END(1);

   SETTING_SET_START(2);
   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MP4);
   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
   SETTING_SET_END(2);

   SETTING_SET_START(3);
   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, 3GP);
   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
   SETTING_SET_END(3);

   SETTING_SET_START(4);
   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
   SETTING_SET_ELEMENT(CODEC, MJPG);
   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
   SETTING_SET_END(4);

#endif

#elif defined(MJPG_ENCODE)

#if defined(MT6253) ||defined(MT6252) || defined(MT6252H) || defined(MT6253D)
    kal_uint32 i, j;

    custom_rec_init_table();

    #ifdef __LOW_COST_SUPPORT_ULC__
    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(0);
    #else
    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);
    #endif

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);

#elif defined (MT6250)  || defined (MT6260)
#ifdef __MED_VIDEO_ULC__
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#else
   #ifdef __MJPEG_ENC_SW_SLIM__
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);

	#else
	    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, HVGA);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
    #endif
#endif
#elif defined (MT6235)
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, CIF);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif defined (MT6236)
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, HVGA);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif defined (MT6255)
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    #ifdef __EMI_CLK_200MHZ__
    SETTING_SET_ELEMENT(RESOLUTION, WVGA);
    #else
    SETTING_SET_ELEMENT(RESOLUTION, VGA);
    #endif
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, VGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, VGA);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, HVGA);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
/*#else defined (MT6256)
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, nHD);
    SETTING_SET_END(0);


    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, nHD);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, nHD);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, nHD);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MJPG);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);*/
   #endif

#elif defined (MP4_ENCODE)

#if defined(MT6253)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6253D)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6253DV)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6252H)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6252)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);

#elif  defined(MT6250) 
#ifdef __MED_VIDEO_ULC__
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#else

    #ifdef __MPEG4_ENC_SW_SLIM__

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
    #else

	kal_uint32 i, j;
	
	   custom_rec_init_table();
	
	   SETTING_SET_START(0);
	   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
	   SETTING_SET_END(0);
	
	   SETTING_SET_START(1);
	   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, WQVGA);
	   SETTING_SET_END(1);
	
	   SETTING_SET_START(2);
	   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	   SETTING_SET_END(2);
	
	   SETTING_SET_START(3);
	   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, 3GP);
	   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	   SETTING_SET_END(3);
	
	   SETTING_SET_START(4);
	   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
	   SETTING_SET_END(4);

    #endif
#endif

#elif  defined (MT6260)
#ifdef __MED_VIDEO_ULC__
    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#else

    #ifdef __MPEG4_ENC_SW_SLIM__

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
    #else

	kal_uint32 i, j;
	
	   custom_rec_init_table();
	
	   SETTING_SET_START(0);
	   SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, HVGA);
	   SETTING_SET_END(0);
	
	   SETTING_SET_START(1);
	   SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, QVGA);
	   SETTING_SET_END(1);
	
	   SETTING_SET_START(2);
	   SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	   SETTING_SET_END(2);
	
	   SETTING_SET_START(3);
	   SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, 3GP);
	   SETTING_SET_ELEMENT(RESOLUTION, QCIF);
	   SETTING_SET_END(3);
	
	   SETTING_SET_START(4);
	   SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
	   SETTING_SET_ELEMENT(CODEC, MP4);
	   SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
	   SETTING_SET_END(4);

    #endif
#endif
#elif  defined(MT6235)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, CIF);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6236)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, HVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#elif  defined(MT6255)

    kal_uint32 i, j;

    custom_rec_init_table();

    SETTING_SET_START(0);
    SETTING_SET_KEY_ELEMENT(QTY, FINE, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, HVGA);
    SETTING_SET_END(0);

    SETTING_SET_START(1);
    SETTING_SET_KEY_ELEMENT(QTY, GOOD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QVGA);
    SETTING_SET_END(1);

    SETTING_SET_START(2);
    SETTING_SET_KEY_ELEMENT(QTY, NORMAL, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(2);

    SETTING_SET_START(3);
    SETTING_SET_KEY_ELEMENT(QTY, LOW, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, 3GP);
    SETTING_SET_ELEMENT(RESOLUTION, QCIF);
    SETTING_SET_END(3);

    SETTING_SET_START(4);
    SETTING_SET_KEY_ELEMENT(QTY, LCD, IS_KEY);
    SETTING_SET_ELEMENT(CODEC, MP4);
    SETTING_SET_ELEMENT(RESOLUTION, WALLPAPER);
    SETTING_SET_END(4);
#else

#endif
#endif

    /* please modify setting end before this */
}



kal_bool recorder_config_has_dependency(void)
{
    return (kal_bool)(!custom_rec_config_table_free_style);
}

kal_bool recorder_config_is_depended(recoorder_config_setting_target target)
{

    if(custom_rec_config_table_free_style)
        return KAL_FALSE;

    if(SETTING_CONFIG_TARGET_NONE == target)
        return KAL_FALSE;

    return (kal_bool)(custom_rec_config_setting_table[target].type == SETTING_CONFIG_TYPE_DEPENDED);
}


kal_bool recorder_config_is_key(recoorder_config_setting_target target)
{
    if(custom_rec_config_table_free_style)
        return KAL_FALSE;

    if(SETTING_CONFIG_TARGET_NONE == target)
        return KAL_FALSE;

    return (kal_bool)(custom_rec_config_setting_table[target].type == SETTING_CONFIG_TYPE_KEY);
}


recoorder_config_setting_target recorder_config_get_key(void)
{
    if(custom_rec_config_table_free_style)
        return SETTING_CONFIG_TARGET_NONE;

    if(!custom_rec_config_table_free_style)
    {
        return (recoorder_config_setting_target)(custom_rec_config_table_key_col);
    }

    return SETTING_CONFIG_TARGET_NONE;

}

recoorder_config_setting_value recorder_config_get_default_key_value(void)
{
    return custom_rec_config_table[0][custom_rec_config_table_key_col];
}


void recorder_config_get_setting_set(recoorder_config_setting_value key_value, recoorder_config_setting_set* set)
{
    kal_uint32 row_idx = 0;
    kal_uint32 i;

    for(i=0; i<custom_rec_config_table_real_row_num; i++)
    {
        if(custom_rec_config_table[i][custom_rec_config_table_key_col] == key_value)
        {
            row_idx = i;
        }
    }

    set->count = 0;
    for(i=0; i<SETTING_CONFIG_TARGET_END; i++)
    {
        if(custom_rec_config_setting_table[i].type == SETTING_CONFIG_TYPE_DEPENDED)
        {
            set->target[set->count] = (recoorder_config_setting_target)i;
            set->value[set->count] = custom_rec_config_table[row_idx][custom_rec_config_setting_table[i].index];
            set->count++;
        }
    }

}


recoorder_config_setting_value recorder_config_get_setting(recoorder_config_setting_value key_value, recoorder_config_setting_target target)
{
    kal_uint32 row_idx = 0;
    kal_uint32 i;
    kal_uint32 not_depended_setting = 0;

    for(i=0; i<custom_rec_config_table_real_row_num; i++)
    {
        if(custom_rec_config_table[i][custom_rec_config_table_key_col] == key_value)
        {
            row_idx = i;
        }
    }

    if(custom_rec_config_setting_table[target].type == SETTING_CONFIG_TYPE_DEPENDED)
    {
        return custom_rec_config_table[row_idx][custom_rec_config_setting_table[target].index];
    }

    ASSERT(not_depended_setting);
	return SETTING_CONFIG_VALUE;

}