/* Needed header files of the compile option in XML files */
#include "mmi_features.h"
#include "custresdef.h"

#ifndef __COSMOS_MMI_PACKAGE__

#ifdef __MMI_ZAKAT_CALCULATOR__

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>


<APP id="APP_ZAKAT_CALCULATOR">

    <INCLUDE file="GlobalResDef.h"/>

    <STRING id="STR_ID_ZAKAT_CALCULATOR"/>
    <STRING id="STR_ID_ZAKAT_CALCULATION"/>
    <STRING id="STR_ID_ZAKAT_PAYABLE"/>
    <STRING id="STR_ID_ZAKAT_ASSETS"/>
    <STRING id="STR_ID_ZAKAT_DEDUCTIONS"/>
    <STRING id="STR_ID_ZAKAT_CATTLE"/>
    <STRING id="STR_ID_ZAKAT_AGRICULTURE"/>
    <STRING id="STR_ID_ZAKAT_BULLION_CASH"/>
    <STRING id="STR_ID_ZAKAT_BURIED_TREASURES"/>
    <STRING id="STR_ID_ZAKAT_MINERALS"/>
    <STRING id="STR_ID_ZAKAT_REVENUES"/>
    <STRING id="STR_ID_ZAKAT_COMMERCIAL_COMMODITIES"/>
    <STRING id="STR_ID_ZAKAT_BUSINESS"/>
    <STRING id="STR_ID_ZAKAT_DEBTS"/>
    <STRING id="STR_ID_ZAKAT_OTHERS"/>
    <STRING id="STR_ID_ZAKAT_CAMELS"/>
    <STRING id="STR_ID_ZAKAT_COWS"/>
    <STRING id="STR_ID_ZAKAT_SHEEP"/>
    <STRING id="STR_ID_ZAKAT_TOTAL_COUNT"/>
    <STRING id="STR_ID_ZAKAT_BY_RAIN_WATER"/>
    <STRING id="STR_ID_ZAKAT_BY_IRRIGATION"/>
    <STRING id="STR_ID_ZAKAT_BY_BOTH"/>
    <STRING id="STR_ID_ZAKAT_TOTAL_AMOUNT"/>
    <STRING id="STR_ID_ZAKAT_CALCULATE"/>
    <STRING id="STR_ID_ZAKAT_GOLD"/>
    <STRING id="STR_ID_ZAKAT_SILVER"/>
    <STRING id="STR_ID_ZAKAT_CASH"/>
    <STRING id="STR_ID_ZAKAT_24_CARAT"/>
    <STRING id="STR_ID_ZAKAT_22_CARAT"/>
    <STRING id="STR_ID_ZAKAT_18_CARAT"/>
    <STRING id="STR_ID_ZAKAT_NO_OF_GMS"/>
    <STRING id="STR_ID_ZAKAT_PERSONAL_DEBTS"/>
    <STRING id="STR_ID_ZAKAT_NISAB"/>
    <STRING id="STR_ID_ZAKAT_PRICE"/>
    <STRING id="STR_ID_ZAKAT_ITEMS_NOT_EXCEED_NISAB"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_CAMELS_ONE"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_CAMELS_TWO"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_COWS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_SHEEP"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_AGRICULTURE"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_BULLION_CASH"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_BURIED_TREASURE"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_MINERALS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_REVENUES"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_COMMERCIAL_COMMODITIES"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_BUSINESS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_DEBTS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_OTHERS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_DEDUCTIONS_PERSONAL_DEBTS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_DEDUCTIONS_BUSINESS"/>
    <STRING id="STR_ID_ZAKAT_DESCRIPTION_DEDUCTIONS_OTHERS"/>
    <STRING id="STR_ID_ZAKAT_NISAB_EMPTY_WARNING"/>
    <STRING id="STR_ID_ZAKAT_RESET_CONFIRM"/>
    <STRING id="STR_ID_ZAKAT_PLEASE_INPUT"/>
    <STRING id="STR_ID_ZAKAT_1_YEAR_OLD_FEMALE_CAMEL_SI"/>
    <STRING id="STR_ID_ZAKAT_1_YEAR_OLD_FEMALE_CAMEL_PL"/>
    <STRING id="STR_ID_ZAKAT_2_YEAR_OLD_FEMALE_CAMEL_SI"/>
    <STRING id="STR_ID_ZAKAT_2_YEAR_OLD_FEMALE_CAMEL_PL"/>
    <STRING id="STR_ID_ZAKAT_3_YEAR_OLD_FEMALE_CAMEL_SI"/>
    <STRING id="STR_ID_ZAKAT_3_YEAR_OLD_FEMALE_CAMEL_PL"/>
    <STRING id="STR_ID_ZAKAT_4_YEAR_OLD_FEMALE_CAMEL_SI"/>
    <STRING id="STR_ID_ZAKAT_4_YEAR_OLD_FEMALE_CAMEL_PL"/>
    <STRING id="STR_ID_ZAKAT_1_YEAR_OLD_FEMALE_OR_MALE_COW_SI"/>
    <STRING id="STR_ID_ZAKAT_1_YEAR_OLD_FEMALE_OR_MALE_COW_PL"/>
    <STRING id="STR_ID_ZAKAT_2_YEAR_OLD_FEMALE_OR_MALE_COW_SI"/>
    <STRING id="STR_ID_ZAKAT_2_YEAR_OLD_FEMALE_OR_MALE_COW_PL"/>
    <STRING id="STR_ID_ZAKAT_SHEEP_SI_PL"/>
    <STRING id="STR_ID_ZAKAT_NO_ZAKAT_PAYABLE"/>
    <STRING id="STR_ID_ZAKAT_NO_DEDUCTIONS"/>
    <STRING id="STR_ID_ZAKAT_OUT_OF_RANGE"/>
    <STRING id="STR_ID_ZAKAT_PAYABLE_HEAD"/>
    <STRING id="STR_ID_ZAKAT_DETAIL_HEAD"/>
    <STRING id="STR_ID_ZAKAT_NISAB_GOLD"/>
    <STRING id="STR_ID_ZAKAT_NISAB_SILVER"/>
    <STRING id="STR_ID_ZAKAT_COLON"/>
    <STRING id="STR_ID_ZAKAT_AMOUNT_OUT_OF_RANGE"/>
    <STRING id="STR_ID_ZAKAT_TOTAL"/>

    <IMAGE id="IMG_ID_ZAKAT_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\ZakatCalculator\\\\Zakat.bmp"</IMAGE>


    <MENUITEM id="MENU_ID_ZAKAT_PAYABLE" str="STR_ID_ZAKAT_PAYABLE" img="IMG_GLOBAL_L2"/>

    <MENUITEM id="MENU_ID_ZAKAT_CATTLE" str="STR_ID_ZAKAT_CATTLE" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_ZAKAT_AGRICULTURE" str="STR_ID_ZAKAT_AGRICULTURE" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_BULLION_CASH" str="STR_ID_ZAKAT_BULLION_CASH" img="IMG_GLOBAL_L3"/>
    <MENUITEM id="MENU_ID_ZAKAT_BURIED_TREASURES" str="STR_ID_ZAKAT_BURIED_TREASURES" img="IMG_GLOBAL_L4"/>
    <MENUITEM id="MENU_ID_ZAKAT_MINERALS" str="STR_ID_ZAKAT_MINERALS" img="IMG_GLOBAL_L5"/>
    <MENUITEM id="MENU_ID_ZAKAT_REVENUES" str="STR_ID_ZAKAT_REVENUES" img="IMG_GLOBAL_L6"/>
    <MENUITEM id="MENU_ID_ZAKAT_COMMERCIAL_COMMODITIES" str="STR_ID_ZAKAT_COMMERCIAL_COMMODITIES" img="IMG_GLOBAL_L7"/>
    <MENUITEM id="MENU_ID_ZAKAT_BUSINESS" str="STR_ID_ZAKAT_BUSINESS" img="IMG_GLOBAL_L8"/>
    <MENUITEM id="MENU_ID_ZAKAT_DEBTS" str="STR_ID_ZAKAT_DEBTS" img="IMG_GLOBAL_L9"/>
    <MENUITEM id="MENU_ID_ZAKAT_OTHERS" str="STR_ID_ZAKAT_OTHERS" img="IMG_GLOBAL_L10"/>

    <MENUITEM id="MENU_ID_ZAKAT_CAMELS" str="STR_ID_ZAKAT_CAMELS"  img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_ZAKAT_COWS" str="STR_ID_ZAKAT_COWS" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_SHEEP" str="STR_ID_ZAKAT_SHEEP" img="IMG_GLOBAL_L3"/>

    <MENUITEM id="MENU_ID_ZAKAT_BY_RAIN_WATER" str="STR_ID_ZAKAT_BY_RAIN_WATER" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_ZAKAT_BY_IRRIGATION" str="STR_ID_ZAKAT_BY_IRRIGATION" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_BY_BOTH" str="STR_ID_ZAKAT_BY_BOTH" img="IMG_GLOBAL_L3"/>

    <MENUITEM id="MENU_ID_ZAKAT_SILVER" str="STR_ID_ZAKAT_SILVER" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_CASH" str="STR_ID_ZAKAT_CASH" img="IMG_GLOBAL_L3"/>

    <MENUITEM id="MENU_ID_ZAKAT_24_CARAT" str="STR_ID_ZAKAT_24_CARAT" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_ZAKAT_22_CARAT" str="STR_ID_ZAKAT_22_CARAT" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_18_CARAT" str="STR_ID_ZAKAT_18_CARAT" img="IMG_GLOBAL_L3"/>
    <MENUITEM id="MENU_ID_ZAKAT_OTHER_GOLD" str="STR_ID_ZAKAT_OTHERS" img="IMG_GLOBAL_L4"/>

    <MENUITEM id="MENU_ID_ZAKAT_DEDUCTIONS_PERSONAL_DEBTS" str="STR_ID_ZAKAT_PERSONAL_DEBTS" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_ZAKAT_DEDUCTIONS_BUSINESS" str="STR_ID_ZAKAT_BUSINESS" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_DEDUCTIONS_OTHERS" str="STR_ID_ZAKAT_OTHERS" img="IMG_GLOBAL_L3"/>

    <MENUITEM id="MENU_ID_ZAKAT_RESET" str="STR_GLOBAL_RESET" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_ZAKAT_NISAB" str="STR_ID_ZAKAT_NISAB" img="IMG_GLOBAL_L1"/>

    <MAINMENUITEM id="MENU_ID_ZAKAT_CALCULATOR" mm_list_img="IMG_ID_ZAKAT_ICON"/>

    <MENU id="MENU_ID_ZAKAT_CATTLE_MENUID" type="APP_MAIN" str="STR_ID_ZAKAT_CATTLE" img="IMG_GLOBAL_L1" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_CAMELS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_COWS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_SHEEP</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_AGRICULTURE_MENUID" type="APP_MAIN" str="STR_ID_ZAKAT_AGRICULTURE" img="IMG_GLOBAL_L2" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_BY_RAIN_WATER</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_BY_IRRIGATION</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_BY_BOTH</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_GOLD" type="APP_SUB" str="STR_ID_ZAKAT_GOLD" img="IMG_GLOBAL_L1" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_24_CARAT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_22_CARAT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_18_CARAT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_OTHER_GOLD</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_BULLION_CASH_MENUID" type="APP_MAIN" str="STR_ID_ZAKAT_BULLION_CASH" img="IMG_GLOBAL_L3" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_GOLD</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_SILVER</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_CASH</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_ASSETS" type="APP_SUB" str="STR_ID_ZAKAT_ASSETS" img="IMG_GLOBAL_L1" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_CATTLE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_AGRICULTURE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_BULLION_CASH</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_BURIED_TREASURES</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_MINERALS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_REVENUES</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_COMMERCIAL_COMMODITIES</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_BUSINESS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_DEBTS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_OTHERS</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_DEDUCTIONS" type="APP_SUB" str="STR_ID_ZAKAT_DEDUCTIONS" img="IMG_GLOBAL_L2" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_DEDUCTIONS_PERSONAL_DEBTS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_DEDUCTIONS_BUSINESS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_DEDUCTIONS_OTHERS</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_SETTINGS" type="APP_SUB" str="STR_GLOBAL_SETTINGS" img="IMG_GLOBAL_L3" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_NISAB</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_RESET</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_CALCULATION" type="APP_SUB" str="STR_ID_ZAKAT_CALCULATION" img="IMG_GLOBAL_L1" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE">
        <MENUITEM_ID>MENU_ID_ZAKAT_ASSETS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_DEDUCTIONS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_SETTINGS</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_ZAKAT_CALCULATOR" type="APP_MAIN" str="STR_ID_ZAKAT_CALCULATOR" img="IMG_ID_ZAKAT_ICON" flag="MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST | SHORTCUTABLE"
          highlight="mmi_zakat_calculator_hilite_hdlr" shortcut="ON" shortcut_img="IMG_ID_ZAKAT_ICON" launch="mmi_zakat_entry_main">
        <MENUITEM_ID>MENU_ID_ZAKAT_CALCULATION</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_ZAKAT_PAYABLE</MENUITEM_ID>
    </MENU>

    <SCREEN id="SCR_ID_ZAKAT_MAIN_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_CALCULATION_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_ASSETS_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_CATTLE_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_BULLION_CASH_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_GOLD_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_AGRICULTURE_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_DEDUCTIONS_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_INPUT_OPTIONS"/>
    <SCREEN id="SCR_ID_ZAKAT_DESCRIPTION"/>
    <SCREEN id="SCR_ID_ZAKAT_COMMON_INPUT"/>
    <SCREEN id="SCR_ID_ZAKAT_24K_GOLD_SILVER_INPUT"/>
    <SCREEN id="SCR_ID_ZAKAT_GOLD_INPUT"/>
    <SCREEN id="SCR_ID_ZAKAT_SETTINGS"/>
    <SCREEN id="SCR_ID_ZAKAT_NISAB_INPUT"/>
    <SCREEN id="SCR_ID_ZAKAT_PAYABLE"/>
    <SCREEN id="SCR_ID_ZAKAT_DETAIL"/>

</APP>

#endif /* __MMI_ZAKAT_CALCULATOR__ */

#endif /* __COSMOS_MMI_PACKAGE__ */

