#include "mmi_features.h"
#include "CustResDef.h"         /* for image/audio path */
<?xml version="1.0" encoding="UTF-8"?>

/* Needed header files of the compile option in XML files, if you need others need to add here */
#ifdef __MMI_MMS_2__


/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_UMMS_MMS">
#ifndef __COSMOS_MMI_PACKAGE__
    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can file the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,GlobalMenuItems.h,MessagesResDef.h" />
    <INCLUDE file="mmi_rp_app_unifiedmessage_def.h" />
            
	#if (defined(JPG_ENCODE) && defined(__MMI_MMS_2__) && !defined(__MMI_ULTRA_SLIM_MMS_2__))
		#ifndef __MMI_MMS_MEGA_PIXEL_SUPPORT__
		#define __MMI_MMS_MEGA_PIXEL_SUPPORT__
		#endif 
	#endif
            
    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    
    #ifndef __MMI_SLIM_MMS_2__	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_OK"/>
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_INCALL"/>
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_NOT_READY"/>
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_BUSY"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_INSUFFICIENT_MEMORY"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_INSUFFICIENT_STORAGE"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_FILE_NOT_FOUND"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_FILE_CORRUPTED"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_FILE_IN_USE"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_FILE_IO"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_UNSUPPORT_CONTENT"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_UNSUPPORT_CONTENT"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_CONFIG_ERROR"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_SERVER_ERROR"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_SERVER_TIMEOUT"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_SERVICE_DENIED"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_UNAUTHORIZED"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_USER_CANCEL"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_INVALID_MSGID"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_MSGID_IS_USING"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_FILE_ACCESS_IN_USB_MODE"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_MAX_MSG_SIZE_REACHED"/>	
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL"/>	
	<STRING id="STR_ID_UMMS_BGSR_MESSAGE_IS_TRANSMITTING"/>
	<STRING id="STR_ID_UMMS_BGSR_SEND_FAIL_RESEND"/>
	<STRING id="STR_ID_UMMS_BGSR_MESSAGE_SENT"/>
    <STRING id="STR_ID_UMMS_BGSR_SIM1"/>
    <STRING id="STR_ID_UMMS_BGSR_SIM2"/>
    <STRING id="STR_ID_UMMS_BGSR_COLON"/>    
    <STRING id="STR_ID_UMMS_BGSR_READ_REPORT_SEND_FAIL"/>
   #else
	<STRING id="STR_ID_UMMS_BGSR_RESULT_SEND_FAIL"/>
	<STRING id="STR_ID_UMMS_BGSR_RESULT_DOWNLOAD_FAIL"/>
   #endif
	<STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_CONNECT_ERROR"/>
	#if 0
	<STRING id="STR_ID_UMMS_BGSR_CANCELED"/>
	#endif
#ifdef __MMI_MMS_ITERATOR_VIEWER__
    <STRING id="STR_ID_UMMS_MMS_NO_CONTENT_DISPLAY"/>
#endif
#ifdef __DRM_SUPPORT__
	<STRING id="STR_ID_UMMS_NO_LCNSE_DRM_MEDIA"/>
#endif

    <STRING id="STR_ID_UMMS_BYTES"/>
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
    <STRING id="STR_ID_UMMS_BYTE"/>
#endif
    <STRING id="STR_ID_UMMS_KB"/>
    <STRING id="STR_ID_UMMS_MMS_SETTINGS"/>
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    
    <STRING id="STR_ID_UMMS_DELIVERY_REPORT"/>
   
#ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT"/>
#endif

#endif
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_COMPOSE"/>
    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL"/>
#endif
    #ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM"/>
    #endif
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_SENDING"/>
	#endif
    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_COMMON_SETTINGS"/>
#if defined( __MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__)
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE"/>
#endif
#ifdef __MMI_MMS_MSG_STORAGE_FILTER_SUPPORT__
    <STRING id="STR_ID_UMMS_MMS_MSG_FILTER"/>
#endif
    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>
    <STRING id="STR_ID_UMMS_MMS_NO_MEM_CARD"/>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_MMS_CURR_STORAGE"/>
#endif
#endif /*__MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__*/
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_DEFAULT_SLIDE_TIMING"/>
#endif
	#ifdef __LAYOUT_SUPPORT__ 
    <STRING id="STR_ID_UMMS_SETTINGS_LAYOUT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_POTRAIT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_LANDSCAPE"/>
	#endif
#ifdef __DRM_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_ADD_DRM"/>
#endif
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_CREATION_MODES"/>
#endif
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_RESTRICTED"/>
    <STRING id="STR_ID_UMMS_SETTINGS_WARNING"/>
    <STRING id="STR_ID_UMMS_SETTINGS_FREE"/>
#endif
    <STRING id="STR_ID_UMMS_MESSAGE_IS_IN_SEND"/>
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
    <STRING id="STR_ID_UMMS_READ_REPORT_IS_IN_SEND"/>
#endif
    <STRING id="STR_ID_UMMS_SETTINGS_FREE_SPACE"/>
#ifdef __OP01_0203__
    <STRING id="STR_ID_UMMS_SETTINGS_TOTAL_SPACE"/>
#endif
#ifdef __MMI_MMS_SIGNATURE__
    <STRING id="STR_ID_UMMS_CREATION_MODE_PROHIBITED"/>
#endif
	#ifndef __MMI_SLIM_MMS_2__
    <STRING id="STR_ID_UMMS_SIGNATURE_SIZE_EXCEEDS_LIMIT"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_SIZE_EXCEEDS_LIMIT_100K"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_SIZE_EXCEEDS_LIMIT_300K"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_SIZE_EXCEEDS_LIMIT_600K"/>
	#endif
	
	#ifdef __MMI_MMS_SIGNATURE__
    <STRING id="STR_ID_UMMS_MODE_WARNING_REMOVE_CONFIRM"/>
    <STRING id="STR_ID_UMMS_MODE_RESTRICTED_REMOVE_CONFIRM"/>
    <STRING id="STR_ID_UMMS_RESTRICTED_MODE"/>
    
    <STRING id="STR_ID_UMMS_SETTINGS_SIGNATURE"/>
    #endif
    <STRING id="STR_ID_UMMS_MODE_WARNING_CONFIRM"/>
    <STRING id="STR_ID_UMMS_SETTINGS_SIGNATURE_AUDIO"/>

	#ifndef __MMI_SLIM_MMS_2__
    <STRING id="STR_ID_UMMS_SIGNATURE_PATH_TOO_LONG"/>	
    <STRING id="STR_ID_UMMS_SIGNATURE_EMPTY_FILE"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_SELECT_MEDIA"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_FILE_CORRUPTED"/>
	#endif
	#ifdef __MAX_PAGE_SUPPORTED__
    <STRING id="STR_ID_UMMS_SETTINGS_MAX_NUM_PAGES"/>
	#endif
	#ifdef __MMI_MMS_BEST_PAGE_UISETTING_OPTION_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_BEST_PAGE_DURATION"/>
	#endif

#ifdef __MMI_MMS_SIGNATURE__
    <STRING id="STR_ID_UMMS_SETTINGS_AUTO_SIGNATURE"/>
    <STRING id="STR_ID_UMMS_SETTINGS_EDIT_CONTENT"/>
#endif
#ifdef __MMI_MMS_MEGA_PIXEL_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_IMAGE_RESIZE"/>
    <STRING id="STR_ID_UMMS_SETTINGS_160_X_120"/>
    <STRING id="STR_ID_UMMS_SETTINGS_320_X_240"/>
    <STRING id="STR_ID_UMMS_SETTINGS_640_X_480"/>
#endif

#ifdef __MMI_OP12_MMS_MAX_SIZE_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_SIZE_LIMIT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_100K"/>
    <STRING id="STR_ID_UMMS_SETTINGS_300K"/>
    <STRING id="STR_ID_UMMS_SETTINGS_600K"/>
    <STRING id="STR_ID_UMMS_SIZE_EXCEEDS_600K"/>
    <STRING id="STR_ID_UMMS_SIZE_EXCEEDS_300K"/>
    <STRING id="STR_ID_UMMS_SIZE_EXCEEDS_100K"/>
    <STRING id="STR_ID_UMMS_WAP_MAX_SIZE_ALLOWED"/>
#endif /*__MMI_OP12_MMS_MAX_SIZE_SUPPORT__*/
#ifdef __MMI_MMS_SETTINGS_VALIDITY_PERIOD_VISIBILITY__
    <STRING id="STR_ID_UMMS_SETTINGS_VALIDITY_PERIOD"/>

    <STRING id="STR_ID_UMMS_SETTINGS_1_HR"/>
    <STRING id="STR_ID_UMMS_SETTINGS_6_HRS"/>
    <STRING id="STR_ID_UMMS_SETTINGS_12_HRS"/>
    <STRING id="STR_ID_UMMS_SETTINGS_1_DAY"/>
    <STRING id="STR_ID_UMMS_SETTINGS_1_WEEK"/>
#endif
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
    <STRING id="STR_ID_UMMS_SETTINGS_READ_REPORT"/>
#ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT"/>
	<STRING id="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT"/>
#endif
#endif

    <STRING id="STR_ID_UMMS_SETTINGS_IMMEDIATE"/>

#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_DELIVERY_TIME"/>
    
    <STRING id="STR_ID_UMMS_SETTINGS_DELV_1_HR"/>
    <STRING id="STR_ID_UMMS_SETTINGS_DELV_12_HRS"/>
    <STRING id="STR_ID_UMMS_SETTINGS_DELV_24_HRS"/>
#endif
	#ifdef __MMI_MMS_HIDE_SENDER_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_HIDE_SENDER"/>
	#endif
    <STRING id="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE"/>
	#if 0
    <STRING id="STR_ID_UMMS_SETTINGS_REPLY_CHARGING"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REQUEST_TYPE"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REQUEST_TYPE_FULL_MMS"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REQUEST_TYPE_ONLY_TEXT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REPLY_DEADLINE"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REPLY_CHARGE_SIZE"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REPLY_DEADLINE_ERROR"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REPLY_CHARGE_SIZE_ERROR"/>
	#endif
    <STRING id="STR_ID_UMMS_SETTINGS_HOME_NETWORK"/>
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_ROAMING"/>
    
    <STRING id="STR_ID_UMMS_SETTINGS_AS_HOME"/>
    <STRING id="STR_ID_UMMS_SETTINGS_FILTERS"/>
    #endif
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_ON_REQUEST"/>
    #endif
    <STRING id="STR_ID_UMMS_RESEND"/>
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_NEVER_SEND"/>
    #endif
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SETTINGS_ANNONYMOUS"/>
    <STRING id="STR_ID_UMMS_SETTINGS_ADVERTISMENT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_ALLOW"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REJECT"/>
    <STRING id="STR_ID_UMMS_SETTINGS_REJECTIVE"/>
    #endif
	#ifdef __MAX_PAGE_SUPPORTED__
    <STRING id="STR_ID_UMMS_MAX_PAGES_LIMIT"/>
	#endif
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_SLIDE_TIME_ZERO_ERROR"/>
    #endif
#ifdef __MMI_MMS_SIGNATURE__
    <STRING id="STR_ID_UMMS_AUTO_SIGN_ERROR"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_SELECT_FILE"/>
    <STRING id="STR_ID_UMMS_SIGNATURE_DELETE_REF"/>
#endif
    <STRING id="STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_TOTAL"/>
    <STRING id="STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_USAGE"/>
#ifdef __MMI_MMS_URI_AGENT__
    <STRING id="STR_ID_UMMS_SEND_MMS_CONFIRM"/>
#endif 
#if defined (__MMI_EMAIL__)
    <STRING id="STR_ID_UMMS_SEND_EMAIL" />
#endif
    <STRING id="STR_ID_UMMS_URL_TOO_LONG" />
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_OPTIONS_PROPERTIES_PRIORITY" />
#endif

#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_TRUNCATE_NUMBER" />
    <STRING id="STR_ID_UMMS_IMG_RESIZE_AUTO" />
#endif

#ifndef __MMI_MMS_WRAP_DRM_FL_CD__
    <STRING id="STR_ID_UMMS_CORRUPT_DRM_MEDIA" />
#endif
    <STRING id="STR_ID_UMMS_USE_DETAILS_SENDER" />
    <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER" />
    <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL" />
    <STRING id="STR_ID_UMMS_RESTRICTED_MODE_MSG_SIZE_EXCEED" />
    
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <STRING id="STR_ID_UMMS_NUM_OF_RECEPIENT" />
#endif
#if defined(__MMI_OP12_MMS_SUPPORT_SETTINGS__)
    <STRING id="STR_ID_UMMS_MMS_RETRIEVAL_ALWAYS_ASK" />
    <STRING id="STR_ID_UMMS_MMS_RETRIEVAL_RESTRICTED" />
#endif
    <STRING id="STR_ID_UMMS_FROM_SIM1" />
    #if(MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_UMMS_FROM_SIM2" />
    #endif
    #if(MMI_MAX_SIM_NUM >= 3)
    <STRING id="STR_ID_UMMS_FROM_SIM3" />
    #endif
    #if(MMI_MAX_SIM_NUM >= 4)
    <STRING id="STR_ID_UMMS_FROM_SIM4" />
    #endif
    <STRING id="STR_ID_UMMS_DOWNLOAD_FROM_SIM1" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_FROM_SIM2" />
#if(MMI_MAX_SIM_NUM >=3)
    <STRING id="STR_ID_UMMS_DOWNLOAD_FROM_ANOTHER_SIM" />
#endif
#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
    <STRING id="STR_ID_UMMS_SEND_SIM1_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_SEND_SIM2_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_SEND_SIM3_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_SEND_SIM4_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_SIM1_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_SIM2_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_SIM3_UNAVAILABLE" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_SIM4_UNAVAILABLE" />
#endif
#ifdef __UNIFIED_MESSAGE_ARCHIVE_SUPPORT__
    <STRING id="STR_ID_UMMS_MOVED"/>
#endif
	#ifndef __MMI_SLIM_MMS_2__ 
    <STRING id="STR_ID_UMMS_LOCK"/>
    <STRING id="STR_ID_UMMS_UNLOCK"/>
	#endif
	#if defined(__MMI_MMS_TEMPLATE_SUPPORT__)||defined(__MMI_OP11_HOMESCREEN_0301__)||defined(__MMI_OP11_HOMESCREEN_0302__)
    <STRING id="STR_ID_UMMS_HINT_MESSAGES"/>
    <STRING id="STR_ID_UMMS_HINT_MESSAGE"/>
	#endif
    <STRING id="STR_ID_CONFM_DELETE_READ_REPORT_MMS"/>
#ifdef __MMI_OP11_MMS_SUPPORT_AUDIO_MSG__ 										
    <STRING id="STR_ID_UMMS_LISTEN" />
#endif
#ifdef __MMI_OP11_MMS_SUPPORT_PHOTO_MSG__										
    <STRING id="STR_ID_UMMS_DISPLAY" />
#endif
#if defined(__MMI_OP12_TOOLBAR__)||defined(__MMI_MMS2_MV_MANUAL_PLAY__)
    <STRING id="STR_UMMS_MANUAL_PLAY_VIEW_FROM_START" />
#endif
#if defined(__MMI_MMS_PREVIEW_GOTO__)||defined(__MMI_MMS2_MV_MANUAL_PLAY__)
    <STRING id="STR_UMMS_MANUAL_PLAY_SLIDE" />
    <STRING id="STR_UMMS_MANUAL_PLAY_SLIDE_LIST" />
#endif
    <STRING id="STR_ID_UMMS_DOWNLOAD_IN_PROGRESS" />
    <STRING id="STR_UMMS_NO_ENOUGH_WORKING_SPACE_ID" />
    #ifdef __MMI_MMS_TEMPLATE_SUPPORT__
	<STRING id="STR_ID_UMMS_TEMPLATE_USER_DEFINED" />
	
	<STRING id="STR_ID_UMMS_WRITE_MESSAGE" />
    <STRING id="STR_ID_UMMS_TEMPLATES_TITLE" />
	#endif
    <STRING id="STR_ID_UMMS_ROOT_DIR_FULL" />
    #if defined(__MMI_OP11_HOMESCREEN_0301__) || defined(__MMI_OP11_HOMESCREEN_0302__)
    <STRING id="STR_ID_UMMS_ATTACHMENTS" />
    #endif
    <STRING id="STR_ID_UMMS_CANCELED" />


   <STRING id="STR_ID_UMMS_NOTIFICATION_EXPIRED" />
#ifdef __MMI_MMS_POSTCARD__
	 <STRING id="STR_ID_UMMS_RECEPIENTS" />
#endif
#ifdef __MMI_MMS_TEMPLATE_SUPPORT__
   <STRING id="STR_ID_UMMS_MAX_TEMPLATE_ALREADY_PRESENT" />
   #endif
   #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
   <STRING id="STR_ID_UMMS_MEMORY_FULL_CLEAN" />
   #endif
   <STRING id="STR_ID_MMA_RESULT_FAIL" />
   <STRING id="STR_ID_UMMS_OPTIONS_MSG_SIZE_EXCEED" />
#ifdef __MMI_WAP_MMS_NO_REJECT_NOTIFICATION_BY_SIZE__
   <STRING id="STR_ID_UMMS_OPTIONS_MSG_SIZE_EXCEED_CONTINUE" />
#endif
    <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_MSG_NUM_REACHED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_MSG_SIZE_REACHED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_CORRUPTED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_IN_USE" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_IO" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_UNSUPPORT_CONTENT" />
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
   <STRING id="STR_ID_UMMS_MESSAGE_STATUS" />
#endif
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_LARGE" />
#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
   <STRING id="STR_ID_UMMS_MMS_STATUS" />
   <STRING id="STR_ID_UMMS_NEXT_TRMN_TIME" />
#endif
   <STRING id="STR_ID_UMMS_DEFFERED" />
#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
   <STRING id="STR_ID_UMMS_WAITING_DWNLING" />
#endif
   <STRING id="STR_ID_UMMS_CANCEL_SEND_CNFRM" />
   #ifdef __MMI_MMS_BGSR_CANCEL_PROHIBIT__
   <STRING id="STR_ID_UMMS_CANCEL_DWNLD_CNFRM" />
   #endif
#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
   <STRING id="STR_ID_UMMS_QUOTA" />
#endif
   <STRING id="STR_ID_UMMS_UPDATING_STATUS" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_PARAMETER" />
   #ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
	 <STRING id="STR_ID_UMMS_SEND_FAILED_BY_INVALID_DATA_ACCOUNT" />
	 <STRING id="STR_ID_UMMS_DOWNLOAD_FAILED_BY_INVALID_DATA_ACCOUNT" />
   #endif
   	<STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS" />
#if defined(__MMI_OP11_HOMESCREEN__) || defined(__MMI_VUI_HOMESCREEN__)
	<STRING id="STR_ID_UMMS_HS_OPTIONS_CLEAR_ALL_EVENT" />
	<STRING id="STR_ID_UMMS_HS_OPTIONS_GO_TO" />
#endif
#ifdef __MMI_OP12_TOOLBAR__
    <STRING id="STR_ID_UMMS_OP12_SETTING" />
#endif
#ifdef __UNIFIED_MESSAGE_ARCHIVE_SUPPORT__
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE" />
#endif
#if defined( __MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__) 
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_PHONE" />
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_CARD" />
	<STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE" />
	<STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_CARD" />
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_PHONE_ASK" />
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_CARD_ASK" />
	<STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE_ASK" />
	<STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_CARD_ASK" />
	<STRING id="STR_ID_UMMS_COPY_TO_CARD_DONE" />
	<STRING id="STR_ID_UMMS_COPY_TO_PHONE_DONE" />
	<STRING id="STR_ID_UMMS_MOVE_TO_CARD_DONE" />
	<STRING id="STR_ID_UMMS_MOVE_TO_PHONE_DONE" />

	<STRING id="STR_ID_UMMS_PHONE_FULL_USE_CARD_MEM" />
	<STRING id="STR_ID_UMMS_CARD_FULL_USE_PHONE_MEM" />
	<STRING id="STR_ID_UMMS_CARD_NOT_PRESENT_USE_PHONE" />
#endif
#ifdef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
<STRING id="STR_IS_UMMS_RECEIVE_FAILED_CARD_NOT_PRESENT" />
#endif

#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
	<STRING id="STR_IS_UMMS_DOWNLOAD_FAILED_CARD_NOT_PRESENT" />
#endif
#endif /*__MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__*/
#ifdef __UNIFIED_MESSAGE_ARCHIVE_SUPPORT__
	<STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE_CONRM" />
#endif
	<STRING id="STR_ID_UMMS_DELETE_CONRM" />
	#if 0
    <STRING id="STR_ID_UMMS_INBOX" />
    <STRING id="STR_ID_UMMS_OUTBOX" />
    <STRING id="STR_ID_UMMS_DRAFT" />
    <STRING id="STR_ID_UMMS_SENT" />
    #endif
#ifdef __UNIFIED_MESSAGE_ARCHIVE_SUPPORT__
    <STRING id="STR_ID_UMMS_ARCHIVE" />
	#endif
	#ifdef __MMI_MMS_TEMPLATE_SUPPORT__
    <STRING id="STR_ID_UMMS_USER_DEF_TEMPL" />
	
	<STRING id="STR_ID_UMMS_NO_SUBJECT" />
	#endif
        <STRING id="STR_ID_UMMS_USE_DETAILS_GREETING_TEXT" />
	<STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER" />
<STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL" />
	<STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_URL" />
      <STRING id="STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK" />
	<STRING id="STR_ID_UMMS_USE_DETAILS_NO_URL" />
    <STRING id="STR_ID_UMMS_USE_DETAILS_NO_NUMBER" />
    <STRING id="STR_ID_UMMS_USE_DETAILS_NO_EMAIL_ID" />
    <STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_ALL" />
    <STRING id="STR_ID_UMMS_CALL_SENDER" />

	<STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_SMS" />
	<STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_MMS" />

	<STRING id="STR_ID_UMMS_OPTIONS_SAVE_OBJECTS" />
#ifdef __MMI_MV_SUPPORT_REF_ID__
	<STRING id="STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS" />
#endif	
	<STRING id="STR_ID_UMMS_FAILED" />
	#ifdef __MMI_MMS_TEMPLATE_SUPPORT__
	<STRING id="STR_ID_UMMS_SAVE_AS_TEMPLATE" />
	#endif
	#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
	<STRING id="STR_ID_UMMS_WAITING_SENDING" />
	#endif
	<STRING id="STR_ID_UMMS_OBJECTS_ATTACHMENT_LIST" />
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
	<STRING id="STR_ID_UMMS_DR_STATUS_EXPIRED" />
	<STRING id="STR_ID_UMMS_DR_STATUS_RETRIEVED" />
	<STRING id="STR_ID_UMMS_DR_STATUS_REJECTED" />
	<STRING id="STR_ID_UMMS_DR_STATUS_UNRECOGNISED" />
	<STRING id="STR_ID_UMMS_DR_STATUS_INDETERMINATE" />
	<STRING id="STR_ID_UMMS_DR_STATUS_FORWARDED" />
	<STRING id="STR_ID_UMMS_DR_STATUS_UNREACHABLE" />
	<STRING id="STR_ID_UMMS_DR_STATUS_NO_READ" />
#endif
 <STRING id="STR_ID_UMMS_WAP_MAX_SIZE_EXCEEDS" />
#ifdef __MMI_MMS_NOT_ALLOW_USER_DOWNLOAD_CORRUPTED_MMS_MSG__
 <STRING id="STR_ID_UMMS_NOTIFICATION_CORRUPT" />
 <STRING id="STR_ID_UMMS_NOTIFICATION_UNRECOGNIZED" />
#endif
#ifdef __MMI_OP12_MMS_MAX_SIZE_SUPPORT__
    <STRING id="STR_ID_UMMS_SEND_MMS_THR_WAP_CONN_CONTINUE" />
    <STRING id="STR_ID_UMMS_MMS_SEND_EXCEED_SIZE_LIMIT" />
#endif
#ifdef __MMI_UMMS_PREVIEW_SEND__
    <STRING id="STR_ID_UMMS_PREVIEW_NO_RECEPIENT" />
#endif /* __MMI_UMMS_PREVIEW_SEND__ */
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <STRING id="STR_ID_UMMS_CANCEL_SEND_RR" />
#endif
#ifdef __UNIFIED_MESSAGE_MARK_SEVERAL_SUPPORT__
    <STRING id="STR_ID_UMMS_MARK_AS_SEVERAL" />
#endif
    <STRING id="STR_ID_UMMS_FAILED_TO_DISPLAY_JSR_MMS" />
	<STRING id="STR_ID_UMMS_EXPIRE_TIME" />
#ifndef __MMI_MMS_LOW_TIER_BGSR_SUPPORT__
	<STRING id="STR_ID_UMMS_MINS" />
#endif
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__
	<STRING id="STR_ID_UMMS_SIZE" />
#endif
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_MSG_CLASS" />
	<STRING id="STR_ID_UMMS_PERSONEL_MSG_CLASS" />
	<STRING id="STR_ID_UMMS_INFORMATIONAL_MSG_CLASS" />
	<STRING id="STR_ID_UMMS_AUTO_MSG_CLASS" />
	#endif
	#ifdef __MMI_MMS_BGSR_CANCEL_PROHIBIT__
	<STRING id="STR_UMMS_CANCEL_DOWNLOAD" />
	#endif
#ifdef __MMI_MMS_SWITCH_MSG_READ_STATUS__
	<STRING id="STR_ID_UMMS_MARK_AS_READ" />
    <STRING id="STR_ID_UMMS_MARK_AS_UNREAD" />
#endif
	<STRING id="STR_ID_MMA_RESULT_FAIL_MAX_SLIDE_NUM_REACHED" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_MAX_ATTACHMENT_NUM_REACHED" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_MSGID" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_FOLDER" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_PARSE" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_MSGID_IS_USING" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_CREATION_MODE_MAX_MSG_SIZE_REACHED" />
	<STRING id="STR_ID_MMA_RESULT_FAIL_FILE_ACCESS_IN_USB_MODE" />
	<STRING id="STR_ID_UMMS_CORRUPT_AND_DELETE" />
	<STRING id="STR_ID_UMMS_UNSUPPORTED_MMS_AND_DELETE" />
	<STRING id="STR_ID_UMMS_CANCEL_SEND" />
	<STRING id="STR_ID_UMMS_FROM" />
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_SUBJECT" />
	

	<STRING id="STR_ID_UMMS_CC" />
	#endif
	<STRING id="STR_ID_UMMS_CREATION_DATE" />
	<STRING id="STR_ID_UMMS_RECEIVE_DATE" />
	#ifndef __MMI_MMS_NO_REPORT_SUPPORT__
	<STRING id="STR_ID_UMMS_STATUS" />
	#endif
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<STRING id="STR_ID_UMMS_TO" />
	<STRING id="STR_ID_UMMS_BCC" />
	<STRING id="STR_ID_UMMS_UNKNOWN" />
	
	<STRING id="STR_ID_UMMS_APPLICATION_ID" />
	<STRING id="STR_ID_UMMS_REPLY_TO_APPLICATION_ID" />
	<STRING id="STR_ID_UMMS_NEW_JAVA_MMS" />
	#endif
    <STRING id="STR_ID_MMS_VIEWER_SEND_RR_CONFIRM" />
    <STRING id="STR_ID_MMS_VIEWER_OUT_OF_MEMORY" />
    <STRING id="STR_ID_MMS_VIEWER_FILE_ERROR" />
    <STRING id="STR_ID_MMS_VIEWER_APP" />
#if(MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_UMMS_SIM_INVALID" />
#endif /*#if(MMI_MAX_SIM_NUM >= 2)*/

#ifdef __MMI_MMS_REPORT_BOX_SUPPORT__	
	<STRING id="STR_ID_UMMS_DELETE_REPORT_CONRM"/>
	<STRING id="STR_ID_UMMS_DELIVERY_STATUS"/>
	<STRING id="STR_ID_UMMS_READ_STATUS"/>
#endif
 #ifdef __OP01__
 <STRING id="STR_ID_MMS_VIEWER_OPEN_BROWSER_CONFIRM"/>
 #endif
#ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
<STRING id="STR_UC_EDIT_CONTENT_ID"/>
<STRING id="STR_UC_EDIT_TEXT_ID"/>
<STRING id="STR_UC_INSERT_SLIDE_ID"/>
<STRING id="STR_UC_INSERT_IMAGE_ID"/>
<STRING id="STR_UC_INSERT_VIDEO_ID"/>
#ifndef __MMI_MMS_LT_NO_AUDIO_SUPPORT__
<STRING id="STR_UC_INSERT_AUDIO_ID"/>
#endif
<STRING id="STR_UC_DELETE_SLIDE_ID"/>
<STRING id="STR_UC_DELETE_VIDEO_ID"/>
<STRING id="STR_UC_DELETE_IMAGE_ID"/>
#ifndef __MMI_MMS_LT_NO_AUDIO_SUPPORT__
<STRING id="STR_UC_DELETE_AUDIO_ID"/>
#endif
<STRING id="STR_UC_DELETE_ID"/>
<STRING id="STR_UC_INSERT_ID"/>
<STRING id="STR_UC_ADD_RECIPIENT_TO"/>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
<STRING id="STR_UC_ADD_RECIPIENT_CC"/>
<STRING id="STR_UC_ADD_RECIPIENT_BCC"/>
#endif
<STRING id="STR_UC_MMS_SEND_ID"/>
<STRING id="STR_ID_UMMS_OPTIONS_RECIPIENT_TO_LIST"/>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
<STRING id="STR_ID_UMMS_OPTIONS_RECIPIENT_CC_LIST"/>
<STRING id="STR_ID_UMMS_OPTIONS_RECIPIENT_BCC_LIST"/>
#endif
<STRING id="STR_UC_ADD_ADDRESS"/>
<STRING id="STR_UC_EDIT_ADDRESS"/>
<STRING id="STR_UC_REMOVE_ADDRESS"/>
<STRING id="STR_UC_ADD_FROM_PHONEBOOK"/>
<STRING id="STR_ID_UMMS_COMPOSER_OPTION"/>
<STRING id="STR_UMMS_UC_NUMBER_LENGTH_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_REMOVED_ID"/>
<STRING id="STR_ID_UMMS_UC_RECIPIENT_NUMBER_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_MSG_SIZE_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_RESTRICTED_MODE_MSG_SIZE_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_PROHIBIT_BY_CREATION_MODE_ID"/>
<STRING id="STR_OPTION_SAVE_DRAFT_ID"/>
<STRING id="STR_OPTION_PREVIEW_MMS_ID"/>
<STRING id="STR_OPTION_EDIT_SUBJECT_ID"/>
#ifndef __MMI_MMS_LT_NO_ATTACHMENT_SUPPORT__
<STRING id="STR_UMMS_INSERT_ATTACHMENT_ID"/>
<STRING id="STR_UMMS_DELETE_ATTACHMENT_ID"/>
#endif
<STRING id="STR_UMMS_NO_RECIPIENT"/>
<STRING id="STR_UMMS_MOVE_TO_ATTACHMENT_ID"/>
<STRING id="STR_UMMS_FAILED_TO_ADD_MEDIA_ID"/>
<STRING id="STR_UMMS_REMOVE_ASK_ID"/>
<STRING id="STR_UMMS_CARD_NOT_PRESENT_CONFIRM"/>
<STRING id="STR_UMMS_MAX_MSG_CARD_CONFIRM"/>
<STRING id="STR_UMMS_MAX_MSG_PHONE_CONFIRM"/>
#ifdef __MMI_FTE_SUPPORT__
<STRING id="STR_UMMS_ADD_OBJECT"/>
#endif
#endif
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
<STRING id="STR_UMMS_FROM_LOWER_CASE"/>
#endif

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    /* Image Id and path of you Application , you can use compile option in Path, but need out of  */
    <IMAGE id="IMG_ID_UMMS_WRITE_MESSAGE">CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\SB_WRITE.bmp","mms menu icon write message"</IMAGE>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__ 
    <IMAGE id="IMG_ID_UMMS_USE_DETAILS_IMAGE_NUMBER" > CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_PHONE.bmp"</IMAGE>
    <IMAGE id="IMG_ID_UMMS_USE_DETAILS_IMAGE_EMAIL" > CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_EM.bmp"</IMAGE>
    <IMAGE id="IMG_ID_UMMS_USE_DETAILS_IMAGE_URL" > CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_URL.bmp"</IMAGE>
#endif
#ifdef __MMI_MMS_ITERATOR_VIEWER__
	<IMAGE id="IMG_ID_UMMS_TOOLBAR_IMAGE_DOWNLOAD" > CUST_IMG_PATH"\\\\MainLCD\\\\Toolbar\\\\Message\\\\TB_download.png"</IMAGE>
	<IMAGE id="IMG_ID_UMMS_TOOLBAR_IMAGE_DOWNLOAD_DIS" > CUST_IMG_PATH"\\\\MainLCD\\\\Toolbar\\\\Message\\\\TB_download_dis.png"</IMAGE>
#endif
#ifdef __MMI_MMS_UNLIMITED_USE_DETAILS_SUPPORT__
    <IMAGE id="IMG_ID_UMMS_USE_DETAIL_PROCESSING_ANI" > CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\use\\\\MMS_Processing"</IMAGE>
#ifdef __MMI_MMS2_MV_MANUAL_PLAY__
    <IMAGE id="IMG_ID_UMMS_USE_DETAIL_PROCESS_DONE" > CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\use\\\\MMS_Process_finish.PNG"</IMAGE>
#else /*__MMI_MMS2_MV_MANUAL_PLAY__*/
    <IMAGE id="IMG_ID_UMMS_USE_DETAIL_PROCESS_DONE" > CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\use\\\\MMS_Process_finish.bmp"</IMAGE>
#endif /*__MMI_MMS2_MV_MANUAL_PLAY__*/
#endif /*__MMI_MMS_UNLIMITED_USE_DETAILS_SUPPORT__*/
#ifdef __MMI_MMS_PREVIEW_GOTO__
    <IMAGE id="IMG_ID_UMMS_SLIDE_LIST" > CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\sb_Slide_list.bmp"</IMAGE>
#endif
    <IMAGE id="IMG_ID_UMMS_ATTACHMENT_LIST" > CUST_IMG_PATH"\\\\MainLCD\\\\MMS\\\\SB_LIST.bmp"</IMAGE>


<!------------------------------------------------------callback manager reciever part---------------------------------------------------------->
	#if defined(__MMI_MMS_USE_ASM__) && defined(__MMI_MMS_2__)
       <RECEIVER id="EVT_ID_SRV_ASM_SUCCESS" proc="mmi_umms_app_core_asm_success"/>   
       <RECEIVER id="EVT_ID_SRV_ASM_STOP" proc="mmi_umms_app_core_asm_stop"/>
       <RECEIVER id="EVT_ID_SRV_ASM_CANCEL" proc="mmi_umms_app_core_asm_cancel"/>
    #endif /*__MMI_MMS_USE_ASM__ && __MMI_MMS_2__*/
    
    #ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_OUT" proc="mmi_umms_uc_sd_card_plug_out_hdlr_cb"/>
    #endif
    
    #ifdef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
    <RECEIVER id="EVT_ID_SRV_NOTIFY_NMGR_RECV_FAILED" proc="mmi_umms_app_core_nmgr_alert_recv_failed"/>
    <RECEIVER id="EVT_ID_SRV_CANCEL_NMGR_RECV_FAILED" proc="mmi_umms_app_core_nmgr_cancel_recv_fail_alert"/>
	#endif
    
    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
    /* Setting Menus start */
	#ifndef __MMI_SLIM_MMS_2__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_LOCK" str="STR_ID_UMMS_LOCK"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_UNLOCK" str="STR_ID_UMMS_UNLOCK"/>
	#endif
#if((MMI_MAX_SIM_NUM == 2) || ((MMI_MAX_SIM_NUM >= 2) && defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)))
    <MENUITEM id="MENU_ID_UMMS_FROM_SIM1" str="STR_ID_UMMS_FROM_SIM1"/>
    <MENUITEM id="MENU_ID_UMMS_FROM_SIM2" str="STR_ID_UMMS_FROM_SIM2"/>
    #if(MMI_MAX_SIM_NUM >= 3) && defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
    <MENUITEM id="MENU_ID_UMMS_FROM_SIM3" str="STR_ID_UMMS_FROM_SIM3"/>
    #endif
    #if(MMI_MAX_SIM_NUM >= 4) && defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
    <MENUITEM id="MENU_ID_UMMS_FROM_SIM4" str="STR_ID_UMMS_FROM_SIM4"/>
    #endif
#endif
   
    <MENU id="MENU_ID_UMMS_MESSAGE_SETTINGS_FOR_COMMON_SETTINGS" type="ORIGINAL" str="STR_ID_UMMS_MMS_SETTINGS" img="IMG_MESSAGE_MMS_MENUENTRY" >
        <MENUITEM_ID>MENU_ID_UMMS_MMS_SETTINGS_EDIT_PROFILE</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_MMS_SETTINGS</MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_EDIT_PROFILE" str="STR_GLOBAL_DATA_ACCOUNT"/>

#ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__	
	<MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_ON" str="STR_GLOBAL_ON"/>
	<MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_OFF" str="STR_GLOBAL_OFF"/>
	
	#ifdef __LAYOUT_SUPPORT__
	<MENUITEM id="MENU_ID_COMPOSE_SETTINGS_LAYOUT_PORT" str="STR_ID_UMMS_SETTINGS_POTRAIT"/>
	<MENUITEM id="MENU_ID_COMPOSE_SETTINGS_LAYOUT_LAND" str="STR_ID_UMMS_SETTINGS_LANDSCAPE"/>
	
	<MENU id="MENU_ID_COMPOSE_SETTINGS_LAYOUT" type="OPTION" str="STR_ID_UMMS_SETTINGS_LAYOUT" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_LAYOUT_PORT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_LAYOUT_LAND </MENUITEM_ID>
    </MENU>
	#endif
	
	
	#ifdef __DRM_SUPPORT__
	<MENU id="MENU_ID_COMPOSE_SETTINGS_ADD_DRM" type="OPTION" str="STR_ID_UMMS_SETTINGS_ADD_DRM" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    #endif
	
	#ifdef __MMI_MMS_BEST_PAGE_UISETTING_OPTION_SUPPORT__
	<MENU id="MENU_ID_COMPOSE_SETTINGS_BEST_PAGE" type="OPTION" str="STR_ID_UMMS_SETTINGS_BEST_PAGE_DURATION" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    #endif
    
    #ifdef __MMI_MMS_SIGNATURE__
	<MENU id="MENU_ID_COMPOSE_SETTINGS_AUTO_SIGN" type="OPTION" str="STR_ID_UMMS_SETTINGS_AUTO_SIGNATURE" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    #endif
    
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <MENUITEM id="MENU_ID_CREAT_MODE_RESTRICTED" str="STR_ID_UMMS_SETTINGS_RESTRICTED"/>
	<MENUITEM id="MENU_ID_CREAT_MODE_WARNING" str="STR_ID_UMMS_SETTINGS_WARNING"/>
	<MENUITEM id="MENU_ID_CREAT_MODE_FREE" str="STR_ID_UMMS_SETTINGS_FREE"/>
	
    <MENU id="MENU_ID_COMPOSE_SETTINGS_CREAT_MODE" type="OPTION" str="STR_ID_UMMS_SETTINGS_CREATION_MODES" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_CREAT_MODE_RESTRICTED </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CREAT_MODE_WARNING </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CREAT_MODE_FREE </MENUITEM_ID>
    </MENU>
    #endif
    
    
    #ifdef __MMI_MMS_MEGA_PIXEL_SUPPORT__
    #ifndef __MMI_UC_AUTO_RESIZE_IMG_BASED_ON_LEFT_MMS_SIZE__
		<MENUITEM id="MENU_ID_IMAGE_RESIZE_160x120" str="STR_ID_UMMS_SETTINGS_160_X_120"/>
		<MENUITEM id="MENU_ID_IMAGE_RESIZE_320x240" str="STR_ID_UMMS_SETTINGS_320_X_240"/>
		<MENUITEM id="MENU_ID_IMAGE_RESIZE_640x480" str="STR_ID_UMMS_SETTINGS_640_X_480"/>
	#else
		<MENUITEM id="MENU_ID_IMAGE_RESIZE_AUTO" str="STR_ID_UMMS_IMG_RESIZE_AUTO"/>
	#endif
    <MENU id="MENU_ID_COMPOSE_SETTINGS_RESIZE" type="OPTION" str="STR_ID_UMMS_SETTINGS_IMAGE_RESIZE" flag = "RADIO" >
			<MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>
		#ifndef __MMI_UC_AUTO_RESIZE_IMG_BASED_ON_LEFT_MMS_SIZE__
			#if defined(__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__) && (__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__ == __160x120__)
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_160x120 </MENUITEM_ID>
			#elif defined(__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__) && (__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__ == __320x240__)
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_160x120 </MENUITEM_ID>
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_320x240 </MENUITEM_ID>
			#elif defined(__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__) && (__MMI_MMS_MAX_IMAGE_RESIZING_RESOLUTION__ == __640x480__)
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_160x120 </MENUITEM_ID>
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_160x120 </MENUITEM_ID>
				<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_640x480 </MENUITEM_ID>
			#endif 
		#else /* __MMI_UC_AUTO_RESIZE_IMG_BASED_ON_LEFT_MMS_SIZE__ */ 
			<MENUITEM_ID> MENU_ID_IMAGE_RESIZE_AUTO </MENUITEM_ID>
		#endif /* __MMI_UC_AUTO_RESIZE_IMG_BASED_ON_LEFT_MMS_SIZE__ */ 
   </MENU>
    #endif
    
    
    #ifdef __LAYOUT_SUPPORT__ 
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_LAYOUT_EXT" str="STR_ID_UMMS_SETTINGS_LAYOUT"/>
    #endif
    #ifdef __DRM_SUPPORT__
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_ADD_DRM_EXT" str="STR_ID_UMMS_SETTINGS_ADD_DRM"/>
    #endif
    #ifdef __MMI_MMS_BEST_PAGE_UISETTING_OPTION_SUPPORT__
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_BEST_PAGE_EXT" str="STR_ID_UMMS_SETTINGS_BEST_PAGE_DURATION"/>
    #endif
    #ifdef __MMI_MMS_SIGNATURE__
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_AUTO_SIGN_EXT" str="STR_ID_UMMS_SETTINGS_AUTO_SIGNATURE"/>
    #endif
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_CREAT_MODE_EXT" str="STR_ID_UMMS_SETTINGS_CREATION_MODES"/>
    #endif
    #ifdef __MMI_MMS_MEGA_PIXEL_SUPPORT__
    <MENUITEM id="MENU_ID_COMPOSE_SETTINGS_RESIZE_EXT" str="STR_ID_UMMS_SETTINGS_IMAGE_RESIZE"/>
    #endif
    
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENU id="MENU_ID_UMMS_MMS_SETTINGS_COMPOSE" type="OPTION" str="STR_ID_UMMS_MESSAGE_SETTINGS_COMPOSE" >
	#ifdef __LAYOUT_SUPPORT__ 
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_LAYOUT_EXT </MENUITEM_ID>
    #endif
    #ifdef __DRM_SUPPORT__
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_ADD_DRM_EXT </MENUITEM_ID>
    #endif
    #ifdef __MMI_MMS_BEST_PAGE_UISETTING_OPTION_SUPPORT__
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_BEST_PAGE_EXT </MENUITEM_ID>
    #endif
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_AUTO_SIGN_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_CREAT_MODE_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_COMPOSE_SETTINGS_RESIZE_EXT </MENUITEM_ID>
    </MENU>
    #endif
    
    #ifdef __MMI_MMS_SETTINGS_VALIDITY_PERIOD_VISIBILITY__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_MAX" str="STR_GLOBAL_MAXIMUM"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_1_HR" str="STR_ID_UMMS_SETTINGS_1_HR"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_6_HR" str="STR_ID_UMMS_SETTINGS_6_HRS"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_12_HR" str="STR_ID_UMMS_SETTINGS_12_HRS"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_1_DAY" str="STR_ID_UMMS_SETTINGS_1_DAY"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_1_WEEK" str="STR_ID_UMMS_SETTINGS_1_WEEK"/>
	
	<MENU id="MENU_ID_SENDING_SETTINGS_VALIDITY" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_VALIDITY_PERIOD" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_MAX </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_1_HR </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_6_HR </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_12_HR </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_1_DAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_1_WEEK </MENUITEM_ID>
    </MENU>
    #endif
	
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
	<MENU id="MENU_ID_SENDING_SETTINGS_DELIVERY_REPORT" type="ORIGINAL" str="STR_ID_UMMS_DELIVERY_REPORT" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>       
    </MENU>
#endif
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__	
	<MENU id="MENU_ID_SENDING_SETTINGS_READ_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT" flag = "RADIO">
	
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
#endif
	
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_LOW" str="STR_GLOBAL_LOW"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_HIGH" str="STR_GLOBAL_MEDIUM"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_MEDIUM" str="STR_GLOBAL_HIGH"/>
	<MENU id="MENU_ID_SENDING_SETTINGS_PRIORITY" type="ORIGINAL" str="STR_GLOBAL_PRIORITY" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_LOW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_HIGH </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_MEDIUM </MENUITEM_ID>
    </MENU>
    
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENUITEM id="MENU_ID_SENDING_IMMEDIATE" str="STR_ID_UMMS_SETTINGS_IMMEDIATE"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_DELV_1_HR" str="STR_ID_UMMS_SETTINGS_DELV_1_HR"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_DELV_12_HR" str="STR_ID_UMMS_SETTINGS_DELV_12_HRS"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_DELV_24_HR" str="STR_ID_UMMS_SETTINGS_DELV_24_HRS"/>
	<MENU id="MENU_ID_SENDING_SETTINGS_DELIVERY_TIME" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_DELIVERY_TIME" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_SENDING_IMMEDIATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_DELV_1_HR </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_DELV_12_HR </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_DELV_24_HR </MENUITEM_ID>
    </MENU>
    #endif
    
    #ifdef __MMI_MMS_HIDE_SENDER_SUPPORT__
	<MENU id="MENU_ID_SENDING_SETTINGS_HIDE_SENDER" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_HIDE_SENDER"  flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    #endif
    
	<MENU id="MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    
    #ifdef __MMI_OP12_MMS_MAX_SIZE_SUPPORT__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_100K" str="STR_ID_UMMS_SETTINGS_100K"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_300K" str="STR_ID_UMMS_SETTINGS_300K"/>
	<MENUITEM id="MENU_ID_SENDING_SETTINGS_600K" str="STR_ID_UMMS_SETTINGS_600K"/>
    <MENU id="MENU_ID_SENDING_SETTINGS_SIZE" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SIZE_LIMIT" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_100K </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_300K </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_600K </MENUITEM_ID>
    </MENU>
    #endif 
    #ifdef __MMI_MMS_SETTINGS_VALIDITY_PERIOD_VISIBILITY__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_VALIDITY_EXT" str="STR_ID_UMMS_SETTINGS_VALIDITY_PERIOD"/>
    #endif
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_DELIVERY_REPORT_EXT" str="STR_ID_UMMS_DELIVERY_REPORT"/>
    
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_READ_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT"/>
    #endif
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_PRIORITY_EXT" str="STR_GLOBAL_PRIORITY"/>
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_DELIVERY_TIME_EXT" str="STR_ID_UMMS_SETTINGS_DELIVERY_TIME"/>
    #endif
    #ifdef __MMI_MMS_HIDE_SENDER_SUPPORT__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_HIDE_SENDER_EXT" str="STR_ID_UMMS_SETTINGS_HIDE_SENDER"/>
    #endif
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE_EXT" str="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE"/>
    #ifdef __MMI_OP12_MMS_MAX_SIZE_SUPPORT__
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_SIZE_EXT" str="STR_ID_UMMS_SETTINGS_SIZE_LIMIT"/>
    #endif
    
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENU id="MENU_ID_UMMS_MMS_SETTINGS_SENDING" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_SENDING" >
	#ifdef __MMI_MMS_SETTINGS_VALIDITY_PERIOD_VISIBILITY__
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_VALIDITY_EXT </MENUITEM_ID>
    #endif
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_DELIVERY_REPORT_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_PRIORITY_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_DELIVERY_TIME_EXT</MENUITEM_ID>
    #ifdef __MMI_MMS_HIDE_SENDER_SUPPORT__
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_HIDE_SENDER_EXT </MENUITEM_ID>
    #endif
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE_EXT </MENUITEM_ID>
    #ifdef __MMI_OP12_MMS_MAX_SIZE_SUPPORT__
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_SIZE_EXT </MENUITEM_ID>
    #endif
    </MENU>
#endif
    
   
	<MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_IMMEDAITE" str="STR_ID_UMMS_SETTINGS_IMMEDIATE"/>
	<MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_DEFERRED" str="STR_ID_UMMS_DEFFERED"/>
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_AS_HOME" str="STR_ID_UMMS_SETTINGS_AS_HOME"/>
	#endif
	<MENU id="MENU_ID_RETRIEVAL_SETTINGS_HOME_NW" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_IMMEDAITE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DEFERRED </MENUITEM_ID>
    </MENU>
	
	#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENU id="MENU_ID_RETRIEVAL_SETTINGS_ROAMING" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_ROAMING" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_AS_HOME </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_IMMEDAITE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DEFERRED </MENUITEM_ID>
    </MENU>

    
	<MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_ALLOW" str="STR_ID_UMMS_SETTINGS_ALLOW"/>
	<MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_REJECT" str="STR_ID_UMMS_SETTINGS_REJECT"/>
	
	<MENU id="MENU_ID_RETRIEVAL_SETTINGS_ANON" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_ANNONYMOUS" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ALLOW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_REJECT </MENUITEM_ID>
    </MENU>
    
    
    
	<MENU id="MENU_ID_RETRIEVAL_SETTINGS_ADV" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_ADVERTISMENT" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ALLOW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_REJECT </MENUITEM_ID>
    </MENU>
     #endif
   
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
   <MENU id="MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>        
    </MENU>
    #endif
    
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_SEND" str="STR_GLOBAL_SEND"/>
	<MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_SEND_ON_REQ" str="STR_ID_UMMS_SETTINGS_ON_REQUEST"/>
	<MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_NEVER_SEND" str="STR_ID_UMMS_SETTINGS_NEVER_SEND"/>
	#endif
	
	#ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	#ifndef __MMI_MMS_NO_REPORT_SUPPORT__
	<MENU id="MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_SEND_ON_REQ </MENUITEM_ID>        
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_NEVER_SEND </MENUITEM_ID>
    </MENU>
    #endif
    #endif
   
    
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_HOME_NW_EXT" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM"/>
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_ROAMING_EXT" str="STR_ID_UMMS_SETTINGS_ROAMING"/>
   
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_ANON_EXT" str="STR_ID_UMMS_SETTINGS_ANNONYMOUS"/>
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_ADV_EXT" str="STR_ID_UMMS_SETTINGS_ADVERTISMENT"/>
    
     #endif
     
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT"/>
    
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT"/>
    #endif
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__                
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_EXT" str="STR_ID_UMMS_MMS_PREFER_STORAGE"/>
#endif 
    
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENU id="MENU_ID_UMMS_MMS_SETTINGS_RETRIEVAL" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL" >
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_HOME_NW_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ROAMING_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ANON_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ADV_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>
    </MENU>
#endif

#else /*SIMPLIFIED_UI*/
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
	<MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_COMPOSE" str="STR_ID_UMMS_MESSAGE_SETTINGS_COMPOSE"/>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_SENDING" str="STR_ID_UMMS_MESSAGE_SETTINGS_SENDING"/>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_RETRIEVAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL"/>
#endif

#endif/*SIMPLIFIED_UI*/

 <MENU id="MENU_ID_UMMS_MMS_SETTINGS" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_COMMON_SETTINGS" >
 #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_COMPOSE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_SENDING </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_RETRIEVAL </MENUITEM_ID>
 #else
 #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>
#endif /*#ifndef __RAJKAMAL_SLIM__*/        
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_HOME_NW_EXT </MENUITEM_ID>
#ifndef __MMI_MMS_NO_REPORT_SUPPORT__        
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ANON_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ADV_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>
#endif /*#ifndef __RAJKAMAL_SLIM__*/      
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE_EXT </MENUITEM_ID>
 #endif
        
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__ 
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE </MENUITEM_ID>
    #else
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_EXT </MENUITEM_ID>
    #endif
#endif 
       
#ifdef __MMI_MMS_MSG_STORAGE_FILTER_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_STORAGE_FILTER </MENUITEM_ID>
#endif
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS </MENUITEM_ID>
    </MENU>


#if(MMI_MAX_SIM_NUM >= 2)
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTING_SIM1" str="STR_GLOBAL_SIM_1"/>
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTING_SIM2" str="STR_GLOBAL_SIM_2"/>
#endif
#if(MMI_MAX_SIM_NUM >= 3)
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTING_SIM3" str="STR_GLOBAL_SIM_3"/>
#endif
#if(MMI_MAX_SIM_NUM >= 4)
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTING_SIM4" str="STR_GLOBAL_SIM_4"/>
#endif

#if(MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_UMMS_MMS_SETTING_SIM_SELECTION" type="OPTION" str="STR_GLOBAL_DATA_ACCOUNT">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTING_SIM1 </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTING_SIM2 </MENUITEM_ID>
    #if(MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTING_SIM3 </MENUITEM_ID>
    #endif
    #if(MMI_MAX_SIM_NUM >= 4)
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTING_SIM4 </MENUITEM_ID>
    #endif
    </MENU>
#endif /*#if(MMI_MAX_SIM_NUM >= 2)*/
       
#if defined( __MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__) 
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
    <MENU id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE" type="ORIGINAL" str="STR_ID_UMMS_MMS_PREFER_STORAGE" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_CARD </MENUITEM_ID>
    </MENU>
#endif
#ifdef __MMI_MMS_MSG_STORAGE_FILTER_SUPPORT__
    <MENU id="MENU_ID_UMMS_MMS_SETTINGS_STORAGE_FILTER" type="ORIGINAL" str="STR_ID_UMMS_MMS_MSG_FILTER" flag = "CHECKBOX">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_CARD </MENUITEM_ID>
    </MENU>
#endif
#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_PHONE" str="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_CARD" str="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>
#endif
    <MENU id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS" type="OPTION" str="STR_GLOBAL_MEMORY_STATUS">
    #ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_PHONE </MENUITEM_ID>
    #endif
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_CARD </MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_PHONE" str="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_CARD" str="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>

#else
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS" str="STR_GLOBAL_MEMORY_STATUS"/>
#endif /*__MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__*/


#ifdef __MMI_MMS_SIGNATURE__
    <MENU id="MENU_ID_UMMS_SIGNATURE_OPTION" type="OPTION" str="STR_ID_UMMS_SETTINGS_SIGNATURE">
        <MENUITEM_ID> MENU_ID_UMMS_SIGNATURE_OPTION_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SIGNATURE_OPTION_SELECT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SIGNATURE_OPTION_DELETE </MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_UMMS_SIGNATURE_OPTION_VIEW" str="STR_GLOBAL_VIEW"/>
    <MENUITEM id="MENU_ID_UMMS_SIGNATURE_OPTION_SELECT" str="STR_ID_UMMS_SIGNATURE_SELECT_FILE"/>
    <MENUITEM id="MENU_ID_UMMS_SIGNATURE_OPTION_DELETE" str="STR_ID_UMMS_SIGNATURE_DELETE_REF"/>
#endif
    /* Setting Menus end */

    /* templates Menus start */
    #ifdef __MMI_MMS_TEMPLATE_SUPPORT__
    <MENU id="MENU_ID_UMMS_TEMPLATE_MMS" type="ORIGINAL" str="STR_GLOBAL_MULTIMEDIA_MESSAGE" img="IMG_MESSAGE_MMS_MENUENTRY">
        <MENUITEM_ID> MENU_ID_UMMS_TEMPLATES_USER_DEFINED </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_TEMPLATES_DEFAULT </MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_UMMS_TEMPLATES_USER_DEFINED" str="STR_ID_UMMS_TEMPLATE_USER_DEFINED"/>
    <MENUITEM id="MENU_ID_UMMS_TEMPLATES_DEFAULT" str="STR_GLOBAL_DEFAULT"/>



    <MENU id="MENU_ID_UMMS_TEMPLATES_OPTIONS" type="OPTION">
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_TEMPLATES_OPTIONS_WRITE_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_TEMPLATES_OPTIONS_WRITE_MESSAGE" str="STR_ID_UMMS_WRITE_MESSAGE"/>
    #endif
    /* templates Menus end */

    /* Inbox folder options start */
#if(MMI_MAX_SIM_NUM == 2)
#ifdef __MMI_UMMS_PREVIEW_SEND__
    <MENUITEM id="MENU_ID_UMMS_PREVIEW_FROM_SIM1" str="STR_ID_UMMS_FROM_SIM1"/>
    <MENUITEM id="MENU_ID_UMMS_PREVIEW_FROM_SIM2" str="STR_ID_UMMS_FROM_SIM2"/>
    <MENU id="MENU_ID_UMMS_PREVIEW_SIM_OPTION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_FROM_SIM1 </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_FROM_SIM2 </MENUITEM_ID>
    </MENU>

#endif
#endif /*#if(MMI_MAX_SIM_NUM >= 2)*/

#ifdef __MMI_UMMS_PREVIEW_SEND__
    <MENUITEM id="MENU_ID_UMMS_PREVIEW_SEND" str="STR_GLOBAL_SEND"/>
#endif
    <MENUITEM id="MENU_ID_UMMS_PREVIEW_GO_TO" str="STR_GLOBAL_GO_TO"/>

    <MENU id="MENU_ID_UMMS_PREVIEW_OPTION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_GO_TO </MENUITEM_ID>
    </MENU>

    /* Cancel Send RR */

    <MENU id="MENU_ID_UMMS_READ_REPORT_SENDING_OPTION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
    </MENU>
    #ifndef __MMI_MMS_NO_REPORT_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_CANCEL_SEND_RR" str="STR_ID_UMMS_CANCEL_SEND_RR"/>
    #endif

/* Inbox menu Option for Normal MMS after View */
    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_NEW_MMS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        #ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        //<MENUITEM_ID> MENU_ID_UMMS_SLIM_OPTIONS_REPLY </MENUITEM_ID>
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTION_REPLY_SMS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_REPLY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_REPLY_ALL </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_CALL_SENDER </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_FORWARD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_LOCK </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_UNLOCK </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_CONTACT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_READ </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_UNREAD </MENUITEM_ID>
        #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_CARD </MENUITEM_ID>
        #endif
        #ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
        
        
    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_NOTIFICATION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTIONS_DOWNLOAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTIONS_CANCEL_DOWNLOAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif  
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_DELIVERY_REPORT" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif 
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_READ </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_UNREAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_JAVA_MMS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif 
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>


#ifdef __MMI_OP12_TOOLBAR__
    <MENU id="MENU_ID_UMMS_TB_LIVE_OPTION" type="ORIGINAL" str="STR_UMMS_MANUAL_PLAY_VIEW_FROM_START">
        <MENUITEM_ID> MENU_ID_UMMS_TB_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_TB_CALL </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_TB_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OP12_TOOL_BAR_SETTING </MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_UMMS_TB_VIEW" str="STR_GLOBAL_VIEW"/>
    <MENUITEM id="MENU_ID_UMMS_TB_CALL" str="STR_GLOBAL_DIAL"/>
    <MENUITEM id="MENU_ID_UMMS_TB_DELETE" str="STR_GLOBAL_DELETE"/>
    <MENUITEM id="MENU_ID_UMMS_OP12_TOOL_BAR_SETTING" str="STR_ID_TB_TOOLBAR_SETTINGS"/>
#endif

#ifdef __MMI_MMS2_MV_MANUAL_PLAY__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MANUAL_PLAY" str="STR_GLOBAL_PLAY"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START" str="STR_UMMS_MANUAL_PLAY_VIEW_FROM_START"/>
#endif

#ifdef __MMI_MMS_VOICE_MESSAGE_HANDLING__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MANUAL_PLAY" str="STR_GLOBAL_PLAY"/>
#endif

#ifdef __MMI_OP11_MMS_SUPPORT_AUDIO_MSG__ 										
    <MENUITEM id="MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW" str="STR_ID_UMMS_LISTEN"/>

#endif

#ifdef __MMI_OP11_MMS_SUPPORT_PHOTO_MSG__										
    <MENUITEM id="MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW" str="STR_ID_UMMS_DISPLAY"/>
#endif

#ifdef __MMI_OP11_MMS_SUPPORT_VIDEO_MSG__								
    <MENUITEM id="MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW" str="STR_GLOBAL_PLAY"/>
#endif 


#if  (defined( __MMS_STANDALONE_COMPOSER_SUPPORT__)||defined(__MMI_OP01_202_MMS_REPLY_BY_SMS_MMS_SUPPORT__) ||  defined(__MMI_MMS_SIMPLIFIED_UI_SUPPORT__))								
    <MENUITEM id="MENU_ID_UMMS_OPTION_REPLY_SMS" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_SMS"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_REPLY" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_MMS"/>
#endif

#if (defined( __UNIFIED_COMPOSER_SUPPORT__  ) && !defined(__MMI_OP01_202_MMS_REPLY_BY_SMS_MMS_SUPPORT__))
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_REPLY" str="STR_GLOBAL_REPLY"/>
#endif


#ifdef __MMI_MMS_TEMPLATE_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_SAVE_TO_TEMPLATE" str="STR_ID_UMMS_SAVE_AS_TEMPLATE"/>
#endif
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_VIEW" str="STR_GLOBAL_VIEW"/>

    <MENUITEM id="MENU_ID_UMMS_OPTIONS_REPLY_ALL" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_ALL"/>
    <MENUITEM id="MENU_ID_UMMS_CALL_SENDER" str="STR_ID_UMMS_CALL_SENDER"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_CONTACT" str="STR_GLOBAL_SAVE_TO_PHONEBOOK"/>


    <MENUITEM id="MENU_ID_UMMS_OPTIONS_FORWARD" str="STR_GLOBAL_FORWARD"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_DELETE" str="STR_GLOBAL_DELETE"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE" str="STR_GLOBAL_EDIT"/>
	
    <MENU id="MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS" type="OPTION" str="STR_ID_UMMS_OPTIONS_SAVE_OBJECTS">
        <MENUITEM_ID>MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_TEXT_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_CURRENT_ATTACHMENT_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS</MENUITEM_ID>
    </MENU>


    <MENUITEM id="MENU_ID_UMMS_OPTIONS_PROPERTIES" str="STR_GLOBAL_DETAILS"/>
#if defined(__MMI_OP11_HOMESCREEN__) || defined(__MMI_VUI_HOMESCREEN__)
    <MENUITEM id="MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT" str="STR_GLOBAL_CLEAR"/>
    <MENUITEM id="MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT" str="STR_ID_UMMS_HS_OPTIONS_CLEAR_ALL_EVENT"/>
    <MENUITEM id="MENU_ID_UMMS_HS_INBOX_GO_TO" str="STR_ID_UMMS_HS_OPTIONS_GO_TO"/>
#endif
#ifdef __UNIFIED_MESSAGE_ARCHIVE_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE" str="STR_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE"/>
#endif

#ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
#if defined( __MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__) && !defined(__MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__)
    #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MOVE_TO_PHONE" str="STR_ID_UMMS_OPTIONS_MOVE_TO_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_MOVE_TO_CARD" str="STR_ID_UMMS_OPTIONS_MOVE_TO_CARD"/>
    #endif
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE" str="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_COPY_TO_CARD" str="STR_ID_UMMS_OPTIONS_COPY_TO_CARD"/>
#endif /*__MMI_MMS_MEMORY_CARD_STORAGE_SUPPORT__*/
#endif
    <MENUITEM id="MENU_ID_UMMS_INBOX_OPTIONS_DOWNLOAD" str="STR_GLOBAL_DOWNLOAD"/>
#ifdef __MMI_MMS_BGSR_CANCEL_PROHIBIT__
    <MENUITEM id="MENU_ID_UMMS_INBOX_OPTIONS_CANCEL_DOWNLOAD" str="STR_UMMS_CANCEL_DOWNLOAD"/>
#endif
    <MENU id="MENU_ID_UMMS_OPTIONS_USE_DETAILS" type="OPTION" str="STR_ID_UMMS_OPTIONS_USE_DETAILS">
        <MENUITEM_ID>MENU_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTION_USE_DETAILS_URL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_SENDER</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL</MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_SENDER" str="STR_ID_UMMS_USE_DETAILS_SENDER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL"/>
    <MENUITEM id="MENU_ID_UMMS_OPTION_USE_DETAILS_URL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_URL"/>

    <MENU id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_USE_NUMBER" type="OPTION">
        <MENUITEM_ID>MENU_ID_UMMS_USE_DETAILS_ADDRESSES_CALL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHBOOK</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_SMS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_MMS</MENUITEM_ID>
    </MENU>
    <MENU id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_USE_EMAIL" type="OPTION">
        <MENUITEM_ID>MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_TO_CONTACT</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_EMAIL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_MMS</MENUITEM_ID>
    </MENU>

    
#if defined (__MMI_EMAIL__)	
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_SEND_EMAIL" str="STR_ID_UMMS_SEND_EMAIL"/>
#endif
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_SEND_SMS" str="STR_GLOBAL_SEND_TEXT_MESSAGE"/>
#if (defined(__UNIFIED_COMPOSER_SUPPORT__) || defined(__MMS_STANDALONE_COMPOSER_SUPPORT__))
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_SEND_MMS" str="STR_GLOBAL_SEND_MULTIMEDIA_MESSAGE"/>
#endif


    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHBOOK" str="STR_GLOBAL_SAVE_TO_PHONEBOOK"/>
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_CALL" str="STR_GLOBAL_DIAL"/>

#ifdef __MMI_PHB_OPTIONAL_FIELD__
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_TO_CONTACT" str="STR_GLOBAL_SAVE_TO_PHONEBOOK"/>
#endif

#ifdef __MMI_BRW_BKM_INTERFACE_SUPPORT__
    <MENU id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_USE_URL" type="OPTION">
        <MENUITEM_ID>MENU_ID_UMMS_USE_DETAILS_ADDRESSES_GO_TO</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK</MENUITEM_ID>
    </MENU>
#endif
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_GO_TO" str="STR_GLOBAL_GO_TO"/>
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK" str="STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK"/>
#ifdef __MMI_MMS_SWITCH_MSG_READ_STATUS__
    <MENUITEM id="MENU_ID_UMMS_INBOX_OPTION_MARK_AS_READ" str="STR_ID_UMMS_MARK_AS_READ"/>
    <MENUITEM id="MENU_ID_UMMS_INBOX_OPTION_MARK_AS_UNREAD" str="STR_ID_UMMS_MARK_AS_UNREAD"/>
#endif

    /* Inbox folder options end */
    /* Outbox folder options start */    
    <MENU id="MENU_ID_UMMS_OUTBOX_OPTIONS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_RESEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif 
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_CANCEL_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_SEND" str="STR_GLOBAL_SEND"/>
#if(MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_UMMS_OPTIONS_RESEND" type="OPTION" str="STR_ID_UMMS_RESEND">
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM1</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM2</MENUITEM_ID>
        #if(MMI_MAX_SIM_NUM >= 3) && defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM3</MENUITEM_ID>
        #endif
        #if(MMI_MAX_SIM_NUM >= 4) && defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM4</MENUITEM_ID>
        #endif
    </MENU>
#else
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_RESEND" str="STR_ID_UMMS_RESEND"/>
#endif

#ifdef __MMI_DYNAMIC_SIM_DYNAMIC_UI__
    <MENU id="MENU_ID_UMMS_SIM_SEL_DOWNLOAD" type="OPTION" str="STR_GLOBAL_DOWNLOAD">
    #if(MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM1</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM2</MENUITEM_ID>
        
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM3</MENUITEM_ID>
    #endif
    #if(MMI_MAX_SIM_NUM >= 4) 
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM4</MENUITEM_ID>
    #endif
    </MENU>
#endif 
    <MENUITEM id="MENU_ID_UMMS_OUTBOX_OPTIONS_CANCEL_SEND" str="STR_ID_UMMS_CANCEL_SEND"/>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS" str="STR_ID_UMMS_MESSAGE_STATUS"/>
#endif
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_TEXT_AS" str="STR_GLOBAL_TEXT"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS" str="STR_GLOBAL_PICTURE"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS" str="STR_ID_UMMS_SETTINGS_SIGNATURE_AUDIO"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS" str="STR_GLOBAL_VIDEO"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS" str="STR_ID_UMMS_OBJECTS_ATTACHMENT_LIST"/>

	
#ifdef __MMI_MV_SUPPORT_REF_ID__   
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_CURRENT_ATTACHMENT_AS" str="STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS"/>
#endif
    /* Outbox folder options end */
    /* Sent Items folder options start */
    <MENU id="MENU_ID_UMMS_SENT_OPTIONS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_FORWARD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        #ifdef __MMI_UM_FILTER_BY_SIM_SUPPORT__ 
        <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID> 
        #endif 
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_CARD </MENUITEM_ID>
        #endif
        #ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
		    <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
		<MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELIVERY_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_READ_STATUS </MENUITEM_ID>
    </MENU>
    /* Sent Items folder options end */
    /* Drafts folder options start */
    <MENU id="MENU_ID_UMMS_DRAFT_OPTIONS" type="OPTION" >
      
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
       
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        #ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_CARD </MENUITEM_ID>
        #endif
        #ifndef __MMI_MMS_ONLY_MEMORY_CARD_STORAGE_SUPPORT__
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>
        #endif
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
    </MENU>
    #ifdef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
    
    

	<MENU id="MENU_ID_UMMS_COMPOSER_OPTIONS" type="OPTION" >
	    <MENUITEM_ID> MENU_ID_UMMS_EDIT_TEXT </MENUITEM_ID>
		<MENU id="MENU_ID_UMMS_INSERT" type="OPTION" str="STR_UC_INSERT_ID">
			<MENUITEM_ID> MENU_ID_UMMS_INSERT_SLIDE </MENUITEM_ID>
			<MENUITEM_ID> MENU_ID_UMMS_INSERT_IMAGE </MENUITEM_ID>
			<MENUITEM_ID> MENU_ID_UMMS_INSERT_VIDEO </MENUITEM_ID>
			<MENUITEM_ID> MENU_ID_UMMS_INSERT_SOUND </MENUITEM_ID>
		#ifndef __MMI_MMS_LT_NO_ATTACHMENT_SUPPORT__
			<MENUITEM_ID> MENU_ID_UMMS_INSERT_ATTACHMENT </MENUITEM_ID>
		#endif
		</MENU>
      <MENU id="MENU_ID_UMMS_DELETE" type="OPTION" str="STR_UC_DELETE_ID">
		<MENUITEM_ID> MENU_ID_UMMS_DELETE_SLIDE </MENUITEM_ID>
		<MENUITEM_ID> MENU_ID_UMMS_DELETE_IMAGE </MENUITEM_ID>
		<MENUITEM_ID> MENU_ID_UMMS_DELETE_SOUND </MENUITEM_ID>
		<MENUITEM_ID> MENU_ID_UMMS_DELETE_VIDEO </MENUITEM_ID>
	#ifndef __MMI_MMS_LT_NO_ATTACHMENT_SUPPORT__
		<MENUITEM_ID> MENU_ID_UMMS_DELETE_ATTACHMENT </MENUITEM_ID>
	#endif
      </MENU>
	</MENU>
       // <MENUITEM id="MENU_ID_UMMS_ADD_RECIPIENT" str="STR_UC_ADD_RECIPIENT"/>
        <MENUITEM id="MENU_ID_UMMS_EDIT_CONTENT" str="STR_UC_EDIT_CONTENT_ID"/>        
        <MENUITEM id="MENU_ID_UMMS_EDIT_SUBJECT" str="STR_OPTION_EDIT_SUBJECT_ID"/>
        <MENUITEM id="MENU_ID_UMMS_SAVE_TO_DRAFT" str="STR_GLOBAL_SAVE"/>
        <MENUITEM id="MENU_ID_UMMS_PREVIEW_MMS" str="STR_OPTION_PREVIEW_MMS_ID"/>
        <MENUITEM id="MENU_ID_UMMS_EDIT_TEXT" str="STR_UC_EDIT_TEXT_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_SLIDE" str="STR_UC_INSERT_SLIDE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_IMAGE" str="STR_UC_INSERT_IMAGE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_VIDEO" str="STR_UC_INSERT_VIDEO_ID"/>
	#ifndef __MMI_MMS_LT_NO_AUDIO_SUPPORT__
        <MENUITEM id="MENU_ID_UMMS_INSERT_SOUND" str="STR_UC_INSERT_AUDIO_ID"/>
	#endif
	#ifndef __MMI_MMS_LT_NO_ATTACHMENT_SUPPORT__
        <MENUITEM id="MENU_ID_UMMS_INSERT_ATTACHMENT" str="STR_UMMS_INSERT_ATTACHMENT_ID"/>
    #endif   
        <MENUITEM id="MENU_ID_UMMS_DELETE_SLIDE" str="STR_UC_DELETE_SLIDE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_DELETE_IMAGE" str="STR_UC_DELETE_IMAGE_ID"/>
	#ifndef __MMI_MMS_LT_NO_AUDIO_SUPPORT__
        <MENUITEM id="MENU_ID_UMMS_DELETE_SOUND" str="STR_UC_DELETE_AUDIO_ID"/>
	#endif
        <MENUITEM id="MENU_ID_UMMS_DELETE_VIDEO" str="STR_UC_DELETE_VIDEO_ID"/>
	#ifndef __MMI_MMS_LT_NO_ATTACHMENT_SUPPORT__
        <MENUITEM id="MENU_ID_UMMS_DELETE_ATTACHMENT" str="STR_UMMS_DELETE_ATTACHMENT_ID"/>
	#endif

       <MENUITEM id="MENU_ID_UMMS_ADD_RECIPIENT_TO" str="STR_UC_ADD_RECIPIENT_TO"/>
#ifndef __MMI_MMS_SIMPLIFIED_UI_SUPPORT__
       <MENUITEM id="MENU_ID_UMMS_ADD_RECIPIENT_CC" str="STR_UC_ADD_RECIPIENT_CC"/>
       <MENUITEM id="MENU_ID_UMMS_ADD_RECIPIENT_BCC" str="STR_UC_ADD_RECIPIENT_BCC"/>
#endif
       #if(MMI_MAX_SIM_NUM == 2)
      <MENU id="MENU_ID_UMMS_OPTIONS_SLIM_SEND" type="OPTION" str="STR_UC_MMS_SEND_ID">
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM1</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_FROM_SIM2</MENUITEM_ID>
      </MENU>
     #else
        <MENUITEM id="MENU_ID_UMMS_OPTIONS_SLIM_SEND" str="STR_UC_MMS_SEND_ID"/>
      #endif
       <MENUITEM id="MENU_ID_UMMS_ADD_ADDRESS" str="STR_UC_ADD_ADDRESS"/>
       <MENUITEM id="MENU_ID_UMMS_EDIT_ADDRESS" str="STR_UC_EDIT_ADDRESS"/>
       <MENUITEM id="MENU_ID_UMMS_REMOVE_ADDRESS" str="STR_UC_REMOVE_ADDRESS"/>
        <MENUITEM id="MENU_ID_UMMS_ADD_FROM_PHONEBOOK_MMS" str="STR_UC_ADD_FROM_PHONEBOOK"/>
		<MENUITEM id="MENU_ID_UMMS_COMPOSER_OPTIONS" str="STR_ID_UMMS_COMPOSER_OPTION"/>      
      
            //<MENU id="MENU_ID_UMMS_TEMPLATE_MMS" type="ORIGINAL" str="STR_GLOBAL_MULTIMEDIA_MESSAGE" img="IMG_MESSAGE_MMS_MENUENTRY">
        <MENU id="MENU_ID_UMMS_OPTIONS_SLIM" type="ORIGINAL" str="STR_GLOBAL_EDIT">
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SLIM_SEND </MENUITEM_ID>
       
        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_TO </MENUITEM_ID>
        #ifndef __RAJKAMAL_SLIM__
        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_CC </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_BCC </MENUITEM_ID>
        #endif
        
        //<MENUITEM_ID>MENU_ID_UMMS_ADD_RECIPIENT  </MENUITEM_ID>
        <MENUITEM_ID>  MENU_ID_UMMS_EDIT_SUBJECT</MENUITEM_ID>
        <MENUITEM_ID>  MENU_ID_UMMS_EDIT_CONTENT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_MMS </MENUITEM_ID>
        <MENUITEM_ID>  MENU_ID_UMMS_SAVE_TO_DRAFT</MENUITEM_ID>
    </MENU>

	       <MENU id="MENU_ID_UMMS_RECIPIENT_SLIM" type="OPTION" >
	          <MENUITEM_ID>  MENU_ID_UMMS_ADD_ADDRESS</MENUITEM_ID>
            <MENUITEM_ID>  MENU_ID_UMMS_EDIT_ADDRESS</MENUITEM_ID>
            <MENUITEM_ID> MENU_ID_UMMS_REMOVE_ADDRESS </MENUITEM_ID>
            <MENUITEM_ID>  MENU_ID_UMMS_ADD_FROM_PHONEBOOK_MMS</MENUITEM_ID>
        </MENU>
	       
    /////////////////////////////////////////////////////////////////////////////////////////
           #endif

#ifdef __MMI_MMS_REPORT_STATUS_MENU_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_DELIVERY_STATUS" str="STR_ID_UMMS_DELIVERY_STATUS "/>
	<MENUITEM id="MENU_ID_UMMS_OPTIONS_READ_STATUS" str="STR_ID_UMMS_READ_STATUS "/>
#endif
#ifdef __MMI_MMS_REPORT_BOX_SUPPORT__
    <MENUITEM id="MENU_ID_UMMS_CALL" str="STR_GLOBAL_DIAL"/>
   	<MENU id="MENU_ID_UMMS_REPORT_BOX_OPTIONS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_CALL </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
    </MENU>
#endif
	
#endif  /* Cosmos  */
</APP>



#endif