/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  vapp_res.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  resource declaration for venus app
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
*------------------------------------------------------------------------------
* Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
*============================================================================
****************************************************************************/
#ifdef __MMI_VUI_ENGINE__

#include "mmi_features.h"

/***************************************************************************** 
 Definition 
*****************************************************************************/

#undef VCP_COMMON_RES_DECLARE
#define VCP_COMMON_RES_DECLARE(_cp, _range)    MMI_RES_DECLARE(_cp, _range, "..\\venusmmi\\visual\\cp\\res\\common\\")

#undef VCP_COSMOS_RES_DECLARE
#define VCP_COSMOS_RES_DECLARE(_cp, _range)    MMI_RES_DECLARE(_cp, _range, "..\\venusmmi\\visual\\cp\\res\\cosmos\\")

#undef VCP_FTE_RES_DECLARE
#define VCP_FTE_RES_DECLARE(_cp, _range)    MMI_RES_DECLARE(_cp, _range, "..\\venusmmi\\visual\\cp\\res\\fte\\")

/***************************************************************************** 
 CP resource declaration
*****************************************************************************/

// common CP
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_BUTTON, 40)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_LIST_MENU, 20)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_POPUP, 30)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_SCROLLABLE, 10)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_SEGMENT_BUTTON, 20)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_SWITCH, 20)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_TAB_BAR, 40)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_TEXT_VIEW, 30)
 
#ifdef __VENUS_3D_UI_ENGINE__
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_FRAME_EFFECT, 15)
VCP_COMMON_RES_DECLARE(SRV_VENUS_COMPONENT_PAGE_PANEL, 30)
#endif


// cosmos CP
#if defined(__MMI_VUI_COSMOS_CP__)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_ACTIVITY_INDICATOR, 5)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_BASE_PICKER, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_BUBBLE_EFFECT, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_DATE_PICKER, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_FORM, 20)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_FUNCTION_BAR, 2)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_INFO_BALLOON, 20)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_MENU_POPUP, 5)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_MENU_SEEK_BAR, 4)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_PAGE_GRID, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_PHOTO_BORDER_FRAME, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_PROGRESS_INDICATOR, 5)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_SLIDER, 6)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_TAB_TITLE_BAR, 30)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_TITLE_BAR, 20)      // Should be nav_title_bar
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_TIME_PICKER, 10)
VCP_COSMOS_RES_DECLARE(SRV_VENUS_COMPONENT_TOOL_BAR, 50)
#endif


// fte CP
#if !defined(__MMI_VUI_COSMOS_CP__)
VCP_FTE_RES_DECLARE(SRV_VENUS_COMPONENT_COMMAND_TITLE,  10)
VCP_FTE_RES_DECLARE(SRV_VENUS_COMPONENT_INLINE_MENU, 20)
VCP_FTE_RES_DECLARE(SRV_VENUS_COMPONENT_OPTION_MENU, 20)
VCP_FTE_RES_DECLARE(SRV_VENUS_COMPONENT_SOFTKEY, 10)
VCP_FTE_RES_DECLARE(SRV_VENUS_COMPONENT_WAITING_ICON, 10)
#endif
#endif
