/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    png_status.h
 *
 * Project:
 * --------
 *   Maui
 *
 * Description:
 * ------------
 *   PNG decoder API return status header
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef __PNG_STATUS_H__
#define __PNG_STATUS_H__

/// #include "drv_comm.h" 
/// #include "png_decode_enum.h"

/// #ifdef USE_HW_PNG_DECODER


typedef enum 
{
   PNG_PARSE_RET_OK = 0,
   PNG_PARSE_RET_INCOMPLETE,
   PNG_PARSE_RET_INVALID_STATE,
   PNG_PARSE_RET_INVALID_FUNCTION_POINTER,
   PNG_PARSE_RET_SIG_NOT_PNG,
   PNG_PARSE_RET_SIG_OFFSET_OVER,
   PNG_PARSE_RET_SIG_FEW_BYTE_CHECKED,
   PNG_PARSE_RET_MALLOC_ERR,
   PNG_PARSE_RET_CHUNK_LENGTH_FETCH_ERR,
   PNG_PARSE_RET_CHUNK_TYPE_FETCH_ERR,
   PNG_PARSE_RET_CHUNK_CRC_FETCH_ERR,
   PNG_PARSE_RET_CHUNK_TYPE_MISMATCH,
   PNG_PARSE_RET_INVALID_COLOR_TYPE,
   PNG_PARSE_RET_FILE_ACCESS_ERR,
   PNG_PARSE_RET_IHDR_INVALID_ORDER,
   PNG_PARSE_RET_IHDR_INVALID_DATA_LENGTH,
   PNG_PARSE_RET_IHDR_INVALID_WIDTH,
   PNG_PARSE_RET_IHDR_INVALID_HEIGHT,
   PNG_PARSE_RET_IHDR_INVALID_BIT_DEPTH,
   PNG_PARSE_RET_IHDR_INVALID_COLOR_TYPE,
   PNG_PARSE_RET_IHDR_INVALID_COMPRESSION_METHOD,
   PNG_PARSE_RET_IHDR_INVALID_FILTER_METHOD,
   PNG_PARSE_RET_IHDR_INVALID_INTERLACE_METHOD,
   PNG_PARSE_RET_PLTE_INVALID_ORDER_NO_IHDR_AHEAD,
   PNG_PARSE_RET_PLTE_INVALID_ORDER_AFTER_IDAT,
   PNG_PARSE_RET_PLTE_DUPLICATED,
   PNG_PARSE_RET_PLTE_ABSENCE_FOR_THIS_COLOR_TYPE,
   PNG_PARSE_RET_PLTE_INVALID_DATA_LENGTH,
   PNG_PARSE_RET_bKGD_INVALID_ORDER_NO_IHDR_AHEAD,
   PNG_PARSE_RET_bKGD_INVALID_ORDER_NO_PLTE_AHEAD,
   PNG_PARSE_RET_bKGD_INVALID_ORDER_AFTER_IDAT,
   PNG_PARSE_RET_bKGD_DUPLICATED,
   PNG_PARSE_RET_bKGD_INVALID_DATA_LENGTH,
   PNG_PARSE_RET_bKGD_INVALID_PALETTE_INDEX,
   PNG_PARSE_RET_tRNS_INVALID_ORDER_NO_IHDR_AHEAD,
   PNG_PARSE_RET_tRNS_INVALID_ORDER_NO_PLTE_AHEAD,
   PNG_PARSE_RET_tRNS_INVALID_ORDER_AFTER_IDAT,
   PNG_PARSE_RET_tRNS_DUPLICATED,
   PNG_PARSE_RET_tRNS_INVALID_DATA_LENGTH,
   PNG_PARSE_RET_tRNS_INVALID_FOR_THIS_COLOR_TYPE,
   PNG_PARSE_RET_IDAT_INVALID_ORDER_NO_IHDR_AHEAD,
   PNG_PARSE_RET_IDAT_INVALID_ORDER_NO_PLTE_AHEAD,
   PNG_PARSE_RET_IEND_INVALID_ORDER,
   PNG_PARSE_RET_IEND_NON_EMPTY_DATA
} PNG_PARSE_RET;


/// #endif   // #ifdef USE_HW_PNG_DECODER
#endif   // __PNG_STATUS_H__ 
