/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
#include "custresdef.h"
#include "SecSetProt.h"

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_SECURITY_SETTING">

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h"/>
    <INCLUDE file="GlobalMenuItems.h"/>
    <INCLUDE file="mmi_rp_app_mainmenu_def.h"/> <!-- MAIN_MENU_TITLE_SETTINGS_ICON -->
    <INCLUDE file="mmi_rp_app_mmi_certman_def.h"/> <!-- MENU_CERTIFICATE_MANAGER -->
    <INCLUDE file="mmi_rp_app_apn_control_def.h"/> <!-- MENU_ID_SECSET_ACL_MAIN -->

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    <STRING id="STR_ID_SECSET_APP_NAME"/>
    <STRING id="STR_ID_SECSET_CHANGE_PASSWORD"/>
    <STRING id="STR_ID_SECSET_PHONE_LOCK"/>
    <STRING id="STR_ID_SECSET_LOCKED"/>
    <STRING id="STR_ID_SECSET_UNLOCKED"/>
    <STRING id="STR_ID_SECSET_TEMP_FAIL"/>
    <STRING id="STR_ID_SECSET_INVALID_LENGTH"/>
#if (MMI_MAX_SIM_NUM == 1) || defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
    <STRING id="STR_ID_SECSET_SIM_SETTING"/>
#endif
#if (MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_SECSET_SELECT_SIM"/>
    <STRING id="STR_ID_SECSET_SIM1_SETTING"/>
    <STRING id="STR_ID_SECSET_SIM2_SETTING"/>
#endif
#if (MMI_MAX_SIM_NUM >= 3)
    <STRING id="STR_ID_SECSET_SIM3_SETTING"/>
#endif /* MMI_MAX_SIM_NUM >= 3 */
#if (MMI_MAX_SIM_NUM == 4)
    <STRING id="STR_ID_SECSET_SIM4_SETTING"/>
#endif /* MMI_MAX_SIM_NUM == 4 */

    <STRING id="STR_ID_SECSET_PHONE_SETTING"/>
    <STRING id="STR_ID_SECSET_CHV1_LOCK"/>
    <STRING id="STR_ID_SECSET_CHANGE_CHV1_PASSWORD"/>
    <STRING id="STR_ID_SECSET_CHANGE_CHV2_PASSWORD"/>
    <STRING id="STR_ID_SECSET_OLD_PHONE_PASSWORD"/>
    <STRING id="STR_ID_SECSET_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_SECSET_CONFIRM_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_SECSET_DIFF_NEW_PHONE_PASSWORD"/>
    <STRING id="STR_ID_SECSET_ENABLE_CHV1_PROMPT"/>
    <STRING id="STR_ID_SECSET_CHV2_DISABLED"/>
#if (MMI_MAX_SIM_NUM == 1) || defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
    <STRING id="STR_ID_SECSET_OLD_CHV1"/>
    <STRING id="STR_ID_SECSET_CHV2_BLOCKED"/>
    <STRING id="STR_ID_SECSET_UBCHV1_BLOCKED_ONLY"/>
    <STRING id="STR_ID_SECSET_UBCHV2_BLOCKED"/>
#endif
#if (MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_SECSET_SIMX_OLD_CHV1"/> 
    <STRING id="STR_ID_SECSET_SIMX_CHV2_BLOCKED"/>
    <STRING id="STR_ID_SECSET_SIMX_UBCHV1_BLOCKED_ONLY"/>
    <STRING id="STR_ID_SECSET_SIMX_UBCHV2_BLOCKED"/>
#ifdef __MMI_SECSET_APP_WITH_BWUI__
    <STRING id="STR_ID_SECSET_SIMX_INPUT_CHV1_BWUI"/> 
    <STRING id="STR_ID_SECSET_SIMX_OLD_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_SIMX_NEW_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_SIMX_INPUT_UBCHV1_BWUI"/>
#endif
#endif

#ifdef __MMI_DYNAMIC_SIM_DYNAMIC_UI__
    <STRING id="STR_ID_SECSET_INSERT_SIM_PROMPT"/> 
#endif
    
    /*
     * Use the resource of bootup to reduce ROM size
     * See SecSetProt.h
     */
    <STRING id="STR_ID_SECSET_WRONG_CHV2"/>
    <STRING id="STR_ID_SECSET_WRONG_UBCHV2"/>
    <STRING id="STR_ID_SECSET_CHV2_NOT_MATCH"/>
    <STRING id="STR_ID_SECSET_SIM_ERROR"/>

#if defined(__SIM_HOT_SWAP_SUPPORT__) || defined(__SIM_RECOVERY_ENHANCEMENT__)
#if (MMI_MAX_SIM_NUM == 1) || defined(__MMI_DYNAMIC_SIM_DYNAMIC_UI__)
    <STRING id="STR_ID_SECSET_SIM_READY"/>
#endif
#if (MMI_MAX_SIM_NUM >= 2)
    <STRING id="STR_ID_SECSET_SIMX_READY"/>
#endif
#endif /* defined(__SIM_HOT_SWAP_SUPPORT__) || defined(__SIM_RECOVERY_ENHANCEMENT__) */
#ifdef __MMI_SECSET_APP_WITH_BWUI__
    <STRING id="STR_ID_SECSET_INPUT_PHONE_PASSWORD_BWUI"/>
    <STRING id="STR_ID_SECSET_OLD_PHONE_PASSWORD_BWUI"/>
    <STRING id="STR_ID_SECSET_NEW_PHONE_PASSWORD_BWUI"/>
    <STRING id="STR_ID_SECSET_CONFIRM_NEW_PHONE_PASSWORD_BWUI"/>
    <STRING id="STR_ID_SECSET_INPUT_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_OLD_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_NEW_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_CONFIRM_NEW_CHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_INPUT_UBCHV1_BWUI"/>
    <STRING id="STR_ID_SECSET_INPUT_CHV2_BWUI"/>
    <STRING id="STR_ID_SECSET_OLD_CHV2_BWUI"/>
    <STRING id="STR_ID_SECSET_NEW_CHV2_BWUI"/>
    <STRING id="STR_ID_SECSET_CONFIRM_NEW_CHV2_BWUI"/>
    <STRING id="STR_ID_SECSET_INPUT_UBCHV2_BWUI"/>
#endif

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    /* Image Id and path of you Application , you can use compile option in Path, but need out of "" */
    <IMAGE id="IMG_SECSET_MENU_ENTRY">CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Settings\\\\SB_SECUR.bmp"</IMAGE>

    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
    /* Only MENUITEM need compile option, MENUITEM_ID does not need */
    <MENU id="MENU_ID_SECSET_MAIN_MENU" type="APP_MAIN" str="STR_ID_SECSET_APP_NAME"
        img="IMG_SECSET_MENU_ENTRY" highlight="mmi_secset_main_menu_highlight_hdlr">
#if defined(__MMI_TELEPHONY_SUPPORT__)
        <MENUITEM_ID>MENU_ID_SECSET_SIM1_ENTRY</MENUITEM_ID>
#if (MMI_MAX_SIM_NUM >= 2)
        <MENUITEM_ID>MENU_ID_SECSET_SIM2_ENTRY</MENUITEM_ID>
#endif
#if (MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID>MENU_ID_SECSET_SIM3_ENTRY</MENUITEM_ID>
#endif /* MMI_MAX_SIM_NUM >= 3 */
#if (MMI_MAX_SIM_NUM == 4)
        <MENUITEM_ID>MENU_ID_SECSET_SIM4_ENTRY</MENUITEM_ID>
#endif/* MMI_MAX_SIM_NUM == 4 */
#endif/*defined(__MMI_TELEPHONY_SUPPORT__)*/
        <MENUITEM_ID>MENU_ID_SECSET_PHONE_SETTING</MENUITEM_ID>
    #ifdef __CERTMAN_SUPPORT__
    	<MENUITEM_ID>MENU_CERTIFICATE_MANAGER</MENUITEM_ID>
    #endif /*__CERTMAN_SUPPORT__ */
    </MENU>

#if (MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_SECSET_SIM1_MENU" type="APP_SUB" str="STR_ID_SECSET_SIM1_SETTING">
#else
    <MENU id="MENU_ID_SECSET_SIM1_MENU" type="APP_SUB" str="STR_ID_SECSET_SIM_SETTING">
#endif
        <MENUITEM_ID>MENU_ID_SECSET_SIM1_CHV1_LOCK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_SIM1_CHANGE_CHV1</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_SIM1_CHANGE_CHV2</MENUITEM_ID>
    #ifdef __MMI_ACL_SUPPORT__
        <MENUITEM_ID>MENU_ID_SECSET_ACL_MAIN</MENUITEM_ID>
    #endif
    </MENU>
#if (MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_SECSET_SIM2_MENU" type="APP_SUB" str="STR_ID_SECSET_SIM2_SETTING">
        <MENUITEM_ID>MENU_ID_SECSET_SIM2_CHV1_LOCK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_SIM2_CHANGE_CHV1</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_SIM2_CHANGE_CHV2</MENUITEM_ID>
    #ifdef __MMI_ACL_SUPPORT__
        <MENUITEM_ID>MENU_ID_SECSET_ACL_SIM2</MENUITEM_ID>
    #endif
    </MENU>
#endif

#if (MMI_MAX_SIM_NUM >= 3)
    <MENU id="MENU_ID_SECSET_SIM3_MENU" type="APP_SUB" str="STR_ID_SECSET_SIM3_SETTING">
             <MENUITEM_ID>MENU_ID_SECSET_SIM3_CHV1_LOCK</MENUITEM_ID>
             <MENUITEM_ID>MENU_ID_SECSET_SIM3_CHANGE_CHV1</MENUITEM_ID>
             <MENUITEM_ID>MENU_ID_SECSET_SIM3_CHANGE_CHV2</MENUITEM_ID>
    #ifdef __MMI_ACL_SUPPORT__
        <MENUITEM_ID>MENU_ID_SECSET_ACL_SIM3</MENUITEM_ID>
    #endif
    </MENU>
#endif /* MMI_MAX_SIM_NUM >= 3 */

#if (MMI_MAX_SIM_NUM == 4)
    <MENU id="MENU_ID_SECSET_SIM4_MENU" type="APP_SUB" str="STR_ID_SECSET_SIM4_SETTING">
             <MENUITEM_ID>MENU_ID_SECSET_SIM4_CHV1_LOCK</MENUITEM_ID>
             <MENUITEM_ID>MENU_ID_SECSET_SIM4_CHANGE_CHV1</MENUITEM_ID>
             <MENUITEM_ID>MENU_ID_SECSET_SIM4_CHANGE_CHV2</MENUITEM_ID>
    #ifdef __MMI_ACL_SUPPORT__
        <MENUITEM_ID>MENU_ID_SECSET_ACL_SIM4</MENUITEM_ID>
    #endif
    </MENU>
#endif/* MMI_MAX_SIM_NUM == 4 */

    <MENU id="MENU_ID_SECSET_PHONE_SETTING" type="APP_SUB" str="STR_ID_SECSET_PHONE_SETTING">
        <MENUITEM_ID>MENU_ID_SECSET_PHONE_LOCK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_CHANGE_PHONE_PASSWORD</MENUITEM_ID>
    </MENU>

#if (MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_SECSET_SIM_SINGLE_SEL" type="APP_MAIN" str="STR_ID_SECSET_SELECT_SIM">
        <MENUITEM_ID>MENU_ID_SECSET_SINGLE_SEL_SIM1</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECSET_SINGLE_SEL_SIM2</MENUITEM_ID>
#if (MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID>MENU_ID_SECSET_SINGLE_SEL_SIM3</MENUITEM_ID>
#endif /* MMI_MAX_SIM_NUM >= 3 */
#if (MMI_MAX_SIM_NUM == 4)
        <MENUITEM_ID>MENU_ID_SECSET_SINGLE_SEL_SIM4</MENUITEM_ID>
#endif/* MMI_MAX_SIM_NUM == 4 */
    </MENU>
#endif /* (MMI_MAX_SIM_NUM >= 2) */

#ifdef __MMI_SECSET_APP_WITH_BWUI__
    <MENU id="MENU_ID_SECSET_SIM1_CHV1_LOCK" type="APP_SUB" str="STR_ID_SECSET_CHV1_LOCK">
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_ON</MENUITEM_ID>
    </MENU>
    <MENU id="MENU_ID_SECSET_PHONE_LOCK" type="APP_SUB" str="STR_ID_SECSET_PHONE_LOCK">
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_ON</MENUITEM_ID>
    </MENU>
#if (MMI_MAX_SIM_NUM >= 2)
    <MENU id="MENU_ID_SECSET_SIM2_CHV1_LOCK" type="APP_SUB" str="STR_ID_SECSET_CHV1_LOCK">
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_ON</MENUITEM_ID>
    </MENU>
#endif
#if (MMI_MAX_SIM_NUM >= 3)
    <MENU id="MENU_ID_SECSET_SIM3_CHV1_LOCK" type="APP_SUB" str="STR_ID_SECSET_CHV1_LOCK">
        <MENUITEM_ID>MENU_ID_SECURITY_SETTIG_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_ON</MENUITEM_ID>
    </MENU>
#endif
#if (MMI_MAX_SIM_NUM >= 4)
    <MENU id="MENU_ID_SECSET_SIM4_CHV1_LOCK" type="APP_SUB" str="STR_ID_SECSET_CHV1_LOCK">
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_SECURITY_SETTING_ON</MENUITEM_ID>
    </MENU>
#endif
#endif

//#if defined(__MMI_TELEPHONY_SUPPORT__)
#if (MMI_MAX_SIM_NUM >= 2)
    <MENUITEM id="MENU_ID_SECSET_SIM1_ENTRY" str="STR_ID_SECSET_SIM1_SETTING"/>
#else
    <MENUITEM id="MENU_ID_SECSET_SIM1_ENTRY" str="STR_ID_SECSET_SIM_SETTING"/>
#endif
//#endif/*defined(__MMI_TELEPHONY_SUPPORT__)*/

#ifndef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECSET_SIM1_CHV1_LOCK" str="STR_ID_SECSET_CHV1_LOCK"/>
#endif
    <MENUITEM id="MENU_ID_SECSET_SIM1_CHANGE_CHV1" str="STR_ID_SECSET_CHANGE_CHV1_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SIM1_CHANGE_CHV2" str="STR_ID_SECSET_CHANGE_CHV2_PASSWORD"/>

#if (MMI_MAX_SIM_NUM >= 2)
  //#if defined(__MMI_TELEPHONY_SUPPORT__)
    <MENUITEM id="MENU_ID_SECSET_SIM2_ENTRY" str="STR_ID_SECSET_SIM2_SETTING"/>
  //#endif/*defined(__MMI_TELEPHONY_SUPPORT__)*/
#ifndef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECSET_SIM2_CHV1_LOCK" str="STR_ID_SECSET_CHV1_LOCK"/>
#endif
    <MENUITEM id="MENU_ID_SECSET_SIM2_CHANGE_CHV1" str="STR_ID_SECSET_CHANGE_CHV1_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SIM2_CHANGE_CHV2" str="STR_ID_SECSET_CHANGE_CHV2_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SINGLE_SEL_SIM1" str="STR_GLOBAL_SIM_1"/>
    <MENUITEM id="MENU_ID_SECSET_SINGLE_SEL_SIM2" str="STR_GLOBAL_SIM_2"/>
#endif /* (MMI_MAX_SIM_NUM == 2) */

#if (MMI_MAX_SIM_NUM >= 3)
  //#if defined(__MMI_TELEPHONY_SUPPORT__)
    <MENUITEM id="MENU_ID_SECSET_SIM3_ENTRY" str="STR_ID_SECSET_SIM3_SETTING"/>
  //#endif/*defined(__MMI_TELEPHONY_SUPPORT__)*/
#ifndef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECSET_SIM3_CHV1_LOCK" str="STR_ID_SECSET_CHV1_LOCK"/>
#endif
    <MENUITEM id="MENU_ID_SECSET_SIM3_CHANGE_CHV1" str="STR_ID_SECSET_CHANGE_CHV1_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SIM3_CHANGE_CHV2" str="STR_ID_SECSET_CHANGE_CHV2_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SINGLE_SEL_SIM3" str="STR_GLOBAL_SIM_3"/>
#endif /* MMI_MAX_SIM_NUM >= 3 */

#if (MMI_MAX_SIM_NUM == 4)
  //#if defined(__MMI_TELEPHONY_SUPPORT__)
    <MENUITEM id="MENU_ID_SECSET_SIM4_ENTRY" str="STR_ID_SECSET_SIM4_SETTING"/>
  //#endif/*defined(__MMI_TELEPHONY_SUPPORT__)*/
#ifndef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECSET_SIM4_CHV1_LOCK" str="STR_ID_SECSET_CHV1_LOCK"/>
#endif
    <MENUITEM id="MENU_ID_SECSET_SIM4_CHANGE_CHV1" str="STR_ID_SECSET_CHANGE_CHV1_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SIM4_CHANGE_CHV2" str="STR_ID_SECSET_CHANGE_CHV2_PASSWORD"/>
    <MENUITEM id="MENU_ID_SECSET_SINGLE_SEL_SIM4" str="STR_GLOBAL_SIM_4"/>
#endif/* MMI_MAX_SIM_NUM == 4 */

#ifndef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECSET_PHONE_LOCK" str="STR_ID_SECSET_PHONE_LOCK"
        shortcut="ON" shortcut_img="IMG_SECSET_MENU_ENTRY" launch="mmi_secset_phone_set_lock_by_shortcut"/>
#endif
    <MENUITEM id="MENU_ID_SECSET_CHANGE_PHONE_PASSWORD" str="STR_ID_SECSET_CHANGE_PASSWORD"/>

#ifdef __MMI_SECSET_APP_WITH_BWUI__
    <MENUITEM id="MENU_ID_SECURITY_SETTING_ON" str="STR_GLOBAL_ON"/>
    <MENUITEM id="MENU_ID_SECURITY_SETTING_OFF" str="STR_GLOBAL_OFF"/>
#endif
    <!------------------------------------------------------Other Resource---------------------------------------------------------->
    <SCREEN id="GRP_ID_SECSET"/>
    <SCREEN id="GRP_ID_SECSET_VERIFICATION"/>
    <SCREEN id="GRP_ID_SECSET_SSC"/>
    <SCREEN id="GRP_ID_SECSET_SHORTCUT"/>
    <SCREEN id="SCR_ID_SECSET_DUMMY_WAITING"/>
#ifdef __MMI_SECSET_APP_WITH_BWUI__
    <SCREEN id="GRP_ID_SECSET_SIM_SWITCH_CHV1"/>
    <SCREEN id="GRP_ID_SECSET_PHONE_LOCK"/>
#endif

#if defined(__MMI_TELEPHONY_SUPPORT__)
	<RECEIVER id="EVT_ID_SRV_SIM_CTRL_AVAILABILITY_CHANGED" proc="mmi_secset_on_sim_availability_changed"/>
#endif
#ifdef __MMI_DYNAMIC_SIM_DYNAMIC_UI__
	<RECEIVER id="EVT_ID_SRV_SIM_CTRL_EVENT_DETECTED" proc="mmi_secset_sim_on_event_detected"/>
#endif

</APP>

