/*Needed header files of the compile option in XML files */
#include "mmi_features.h"

#if (defined(__MMI_SOUND_RECORDER__) && defined(__MMI_SNDREC_NEW__))

#include "CustResDef.h"         /* for image/audio path */

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

<APP id="APP_SOUNDRECORDER">
	<INCLUDE file="GlobalResDef.h,FileMgrResDef.h"/>
	<INCLUDE file ="mmi_rp_all_defs.h"/>
	
	<STRING id="STR_ID_SNDREC_MAIN"/>
	<STRING id="STR_ID_SNDREC_NEW_RECORD"/>
	<STRING id="STR_ID_SNDREC_AUDIO_PL"/>
	<STRING id="STR_ID_SNDREC_APPEND"/>
	<STRING id="STR_ID_SNDREC_SETTINGS_FORMAT"/>
	<STRING id="STR_ID_SNDREC_SETTING_QUALITY"/>
	<STRING id="STR_ID_SNDREC_AMR">AMR</STRING>
	<STRING id="STR_ID_SNDREC_AWB">AWB</STRING>
	<STRING id="STR_ID_SNDREC_WAV">WAV</STRING>
	<STRING id="STR_ID_SNDREC_VM">VM</STRING>
	<STRING id="STR_ID_SNDREC_QUALITY_MEDIUM"/>
	<STRING id="STR_ID_SNDREC_PLS_RECORD"/>
	<STRING id="STR_ID_SNDREC_RECORDING"/>
	<STRING id="STR_ID_SNDREC_REC_PAUSED"/>
	<STRING id="STR_ID_SNDREC_PLAYING"/>
	<STRING id="STR_ID_SNDREC_PLAY_PAUSED"/>
	<STRING id="STR_ID_SNDREC_SMS_RECORD_TIMEOUT"/>
	<STRING id="STR_ID_SNDREC_NOT_ALLOWED_IN_CTM_CALL"/>
	<STRING id="STR_ID_SNDREC_SAVE_AUDIO"/>
	<STRING id="STR_ID_SNDREC_ADD_AUDIO"/>
	<STRING id="STR_ID_SNDREC_AUTO_RECORD_ON"/>
	<STRING id="STR_ID_SNDREC_AUDIO_PLAY_FAIL"/>
	<STRING id="STR_ID_SNDREC_ERROR"/>
	<STRING id="STR_ID_SNDREC_REC_ERROR"/>
	<STRING id="STR_ID_SNDREC_COMMAND_ERROR"/>
	<STRING id="STR_ID_SNDREC_BAD_FORMAT"/>
	<STRING id="STR_ID_SNDREC_UNSUPPORTED_TYPE"/>
	<STRING id="STR_ID_SNDREC_WRITE_PROTECTION_ERROR"/>
	<STRING id="STR_ID_SNDREC_NO_CARD"/>
	<STRING id="STR_ID_SNDREC_DEVICE_BUSY"/>
	<STRING id="STR_ID_SNDREC_OPEN_FILE_ERROR"/>
	<STRING id="STR_ID_SNDREC_SPEECH_OFF"/>
	<STRING id="STR_ID_SNDREC_UNSUPPORTED_FREQ"/>
	<STRING id="STR_ID_SNDREC_DISCARD_ASK"/>

	<IMAGE id="IMG_ID_SNDREC_MAIN_ICON">CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SB_SR.bmp"</IMAGE>
#ifdef __MMI_FTE_SUPPORT__

	<IMAGE id="IMG_ID_SNDREC_FTE_BACKGROUND">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_BG.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_ANIMAL">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_ANI.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_REC_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_REC.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_REC_P_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PAUSE.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_PLAY_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PLAY.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_PLAY_P_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PAUSE.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_PREV_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PREVIOUS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_NEXT_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_NEXT.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_LIST_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_LIST.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_STOP_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_STOP.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_HIGHLIGHT">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_HIGHLIGHT.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_SKIN_LSK">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SK_OPTION.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_SKIN_RSK">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SK_BACK.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_REC_SIGN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SIGN_REC.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_REC_PAUSE_SIGN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SIGN_PAUSE.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_REC_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_REC_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_PLAY_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PLAY_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_PREV_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_PREVIOUS_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_NEXT_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_NEXT_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_LIST_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_LIST_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_BUTTON_STOP_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_STOP_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_SKIN_LSK_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SK_OPTION_DIS.png"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_FTE_SKIN_RSK_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\FTE\\\\SNDREC_SK_BACK_DIS.png"</IMAGE>

#else/*__MMI_FTE_SUPPORT__*/

#ifndef __MMI_SNDREC_SKIN__
	<IMAGE id="IMG_ID_SNDREC_ANIMAL_RECORD">CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_record.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_ANIMAL_PLAY">CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_play.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_ANIMAL_REC_PAUSE">CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_RECORD_P.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_ANIMAL_PLY_PAUSE">CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_PLAY_P.gif"</IMAGE>
#else
	<IMAGE id="IMG_ID_SNDREC_BACKGROUND">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_BG.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_ANIMAL">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_recording.gif"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_REC_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_record_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_REC_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_record_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_REC_P_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_r_pause_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_REC_P_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_r_pause_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PLAY_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_play_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PLAY_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_play_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PLAY_P_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_pause_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PLAY_P_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_pause_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PREV_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_previous_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PREV_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_previous_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_NEXT_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_NEXT_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_LIST_UP">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_up.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_LIST_DN">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_down.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_REC_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_record_disable.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PLAY_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_play_disable.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_PREV_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_previous_disable.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_NEXT_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_disable.bmp"</IMAGE>
	<IMAGE id="IMG_ID_SNDREC_BUTTON_LIST_DISABLE">CUST_IMG_PATH"\\\\MainLCD\\\\Sndrec\\\\SR_next_disable.bmp"</IMAGE>
#endif  /* __MMI_SNDREC_SKIN__ */

#endif/*__MMI_FTE_SUPPORT__*/

#if (defined(__MMI_MAINLCD_240X400__) && defined (__MMI_BI_DEGREE_MAIN_MENU_STYLE__))
<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_MAIN" str="STR_ID_SNDREC_MAIN" img="IMG_ID_SNDREC_MAIN_ICON"  highlight="mmi_sndrec_hightlight_main"/>
<MENU id="MAIN_MENU_OPTION_SNDREC_APP" str="STR_ID_SNDREC_MAIN" img="IMG_ID_SNDREC_MAIN_ICON"/>

#else
<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_MAIN" parent="MAIN_MENU_MULTIMEDIA_MENUID" str="STR_ID_SNDREC_MAIN" img="IMG_ID_SNDREC_MAIN_ICON"  highlight="mmi_sndrec_hightlight_main"/>
#endif

<!--Menu Item Area-->
<MENUITEM id="MENU_ID_SNDREC_NEW_RECORD" str="STR_ID_SNDREC_NEW_RECORD"/>
<MENUITEM id="MENU_ID_SNDREC_RECORD_PLAY" str="STR_GLOBAL_PLAY"/>
<MENUITEM id="MENU_ID_SNDREC_APPEND" str="STR_ID_SNDREC_APPEND"/>
<MENUITEM id="MENU_ID_SNDREC_RENAME" str="STR_GLOBAL_RENAME"/>
<MENUITEM id="MENU_ID_SNDREC_DELETE" str="STR_GLOBAL_DELETE"/>
<MENUITEM id="MENU_ID_SNDREC_RECORD_LIST" str="STR_GLOBAL_LIST"/>
<MENUITEM id="MENU_ID_SNDREC_SETTING" str="STR_GLOBAL_SETTINGS"/>
<MENUITEM id="MENU_ID_SNDREC_FORWARD_USE" str="STR_FMGR_USE"/>
<MENUITEM id="MENU_ID_SNDREC_FORWARD_SEND" str="STR_GLOBAL_SEND"/>


<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_OPTION" parent="0" str="STR_GLOBAL_OPTIONS" img="0">
	<MENUITEM_ID>MENU_ID_SNDREC_NEW_RECORD</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_RECORD_PLAY</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_APPEND</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_RENAME</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_DELETE</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_RECORD_LIST</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_SETTING</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_FORWARD_USE</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_FORWARD_SEND</MENUITEM_ID>
</MENU>

<!--Menu Item Area-->
<MENUITEM id="MENU_ID_SNDREC_LIST_PLAY" str="STR_GLOBAL_PLAY" highlight="mmi_sndrec_highlight_list_play"/>

<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_REC_OPTION" parent="0" str="STR_GLOBAL_OPTIONS" img="0">
	<MENUITEM_ID>MENU_ID_SNDREC_LIST_PLAY</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_APPEND</MENUITEM_ID>
	<MENUITEM_ID>@OID:MENU_ID_FMGR_GEN_OPTION_RENAME</MENUITEM_ID>
	<MENUITEM_ID>@OID:MENU_ID_FMGR_GEN_OPTION_DELETE</MENUITEM_ID>
	<MENUITEM_ID>@OID:MENU_ID_FMGR_GEN_OPTION_DELETE_ALL</MENUITEM_ID>
	<MENUITEM_ID>@OID:MENU_ID_FMGR_GEN_OPTION_FORWARD_USE</MENUITEM_ID>
	<MENUITEM_ID>@OID:MENU_ID_FMGR_GEN_OPTION_FORWARD_SEND</MENUITEM_ID>
</MENU>

<!--Menu Item Area-->
<MENUITEM id="MENU_ID_SNDREC_OPTION_SAVE" str="STR_GLOBAL_DONE" highlight="mmi_sndrec_hightlight_save"/>
<MENUITEM id="MENU_ID_SNDREC_OPTION_INPUT_METHOD" str="STR_GLOBAL_INPUT_METHOD" highlight="mmi_sndrec_hightlight_input_method"/>


<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_RENAME_OPTION" parent="0" str="STR_GLOBAL_OPTIONS" img="0">
	<MENUITEM_ID>MENU_ID_SNDREC_OPTION_SAVE</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_OPTION_INPUT_METHOD</MENUITEM_ID>
</MENU>

#ifdef __MMI_OP12_SNDREC_STYLE__
<!--Menu Item Area-->
<MENUITEM id="MENU_ID_SNDREC_SAVE_OPTION_PLAY" str="STR_GLOBAL_PREVIEW" highlight="mmi_sndrec_highlight_save_option_play"/>
<MENUITEM id="MENU_ID_SNDREC_SAVE_OPTION_SAVE" str="STR_GLOBAL_SAVE" highlight="mmi_sndrec_highlight_save_option_save"/>
<MENUITEM id="MENU_ID_SNDREC_SAVE_OPTION_DISCARD" str="STR_GLOBAL_DISCARD" highlight="mmi_sndrec_highlight_save_option_discard"/>

<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_SAVE_OPTION" parent="0" str="STR_GLOBAL_OPTIONS" img="0">
	<MENUITEM_ID>MENU_ID_SNDREC_FORWARD_SEND</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_SAVE_OPTION_PLAY</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_SAVE_OPTION_SAVE</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_SAVE_OPTION_DISCARD</MENUITEM_ID>
</MENU>

#ifdef __MMI_MMS__
<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_SAVE_OPTION_SEND" parent="MENU_ID_SNDREC_SAVE_OPTION" str="STR_GLOBAL_SEND" img="0"/>
#endif /* __MMI_MMS__ */

<!--Menu Item Area-->
<MENUITEM id="MENU_ID_SNDREC_SAVE_OPTION_RENAME_SAVE" str="STR_GLOBAL_DONE" highlight="mmi_sndrec_highlight_save_option_rename_save"/>

<!--Menu Tree Area-->
<MENU id="MENU_ID_SNDREC_SAVE_OPTION_RENAME_OPTION" parent="0" str="STR_GLOBAL_OPTIONS" img="0">
	<MENUITEM_ID>MENU_ID_SNDREC_SAVE_OPTION_RENAME_SAVE</MENUITEM_ID>
	<MENUITEM_ID>MENU_ID_SNDREC_OPTION_INPUT_METHOD</MENUITEM_ID>
</MENU>
#endif /* __MMI_OP12_SNDREC_STYLE__ */

       <SCREEN id ="GRP_ID_SNDREC_ENTRY_SETTING_SCREEN"/>
       <SCREEN id="GRP_ID_SNDREC_START_BASE"/>
	<SCREEN id="GRP_ID_SNDREC_MAIN"/>
	<SCREEN id="GRP_ID_SNDREC_OPTION"/>
	<SCREEN id="GRP_ID_SNDREC_SETTING"/>
	<SCREEN id="GRP_ID_SNDREC_PLAYER"/>
	<SCREEN id="GRP_ID_SNDREC_CREATING"/>
	<SCREEN id="GRP_ID_SNDREC_DELETE_ANIMATION"/>
	<SCREEN id="GRP_ID_SNDREC_RENAME"/>
	<SCREEN id="GRP_ID_SNDREC_RENAME_OPTION"/>
	<SCREEN id="GRP_ID_SNDREC_FORWARD_USE"/>
	<SCREEN id="GRP_ID_SNDREC_FORWARD_SEND"/>
	<SCREEN id="GRP_ID_SNDREC_AUDIO_SAVE_QUERY"/>
	<SCREEN id="GRP_ID_SNDREC_AUDIO_SAVE_OPTION"/>
	<SCREEN id="GRP_ID_SNDREC_AUDIO_SAVE_OPTION_RENAME"/>
	<SCREEN id="GRP_ID_SNDREC_AUDIO_SAVE_OPTION_RENAME_OPTION"/>
	
	<SCREEN id="SCR_ID_SNDREC_START_BASE"/>
	<SCREEN id="SCR_ID_SNDREC_MAIN"/>
	<SCREEN id="SCR_ID_SNDREC_OPTION"/>
	<SCREEN id="SCR_ID_SNDREC_SETTING"/>
	<SCREEN id="SCR_ID_SNDREC_PLAYER"/>
	<SCREEN id="SCR_ID_SNDREC_CREATING"/>
	<SCREEN id="SCR_ID_SNDREC_DELETE_ANIMATION"/>
	<SCREEN id="SCR_ID_SNDREC_RENAME"/>
	<SCREEN id="SCR_ID_SNDREC_RENAME_OPTION"/>
	<SCREEN id="SCR_ID_SNDREC_FORWARD_USE"/>
	<SCREEN id="SCR_ID_SNDREC_FORWARD_SEND"/>
	<SCREEN id="SCR_ID_SNDREC_AUDIO_SAVE_QUERY"/>
	<SCREEN id="SCR_ID_SNDREC_AUDIO_SAVE_OPTION"/>
	<SCREEN id="SCR_ID_SNDREC_AUDIO_SAVE_OPTION_RENAME"/>
	<SCREEN id="SCR_ID_SNDREC_AUDIO_SAVE_OPTION_RENAME_OPTION"/>

</APP>
#endif /* defined(__MMI_SOUND_RECORDER__) && defined(__MMI_SNDREC_NEW__) */
