#include "third_rom.h"
#include "verno.h"
#include "custom_scatstruct.h"

#if defined(__NFB_THIRD_ROM_SUPPORT__) && defined(__MTK_TARGET__)

extern kal_uint32  Load$$THIRD_ROM$$Base;
kal_uint32 maxContentNum = MAX_CONTENT_NUMBER;
enfb_indextbl_t enfb_tbl[MAX_CONTENT_NUMBER];

#pragma arm section rodata = "NFB3RDROM_HEADER_HINT"
#define ENFB_IDSTRING3  "ENFB3RDROM"   /* MUST SYNC with script tools/EnfbPack3rdRom.pl ; it add tail ! */ 
const THIRDROM_HEADER g_enfb_3rdrom_header = 
{
{
   {ENFB_IDSTRING3, ENFB_CONTENT_IMAGERES,
                   0 /* external */,
                   0 /* external */,
                   "ENFBMMIResB" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_THEMES,
                   0 /* external */,
                   0 /* external */,
                   "CustENFBThm" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_APPICONS,
                   0 /* external */,
                   0 /* external */,
                   "CustENFBIcn" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_HANDWRITING,
                   0 /* external */,
                   0 /* external */,
                   "IME_HW_DATA" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_FONT,
                   0 /* external */,
                   0 /* external */,
                   "CustENFBFnt" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_CALC,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPCALCx" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_CONV,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPCONVx" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_HEALTH,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPHEALT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_OPERA,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPOPERA" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_STOPWATCH,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPSTOPW" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_WEIBO,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPWEIBO" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_WEIBOVSM,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPWBVSM" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_OPERA_V6,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPOPAV6" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_3GT_BALL,
				   0 /* external */,
				   0 /* external */,
				   "MREAPP3GTBA" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_3GT_MOTO,
				   0 /* external */,
				   0 /* external */,
				   "MREAPP3GTMO" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
	{ENFB_IDSTRING3, ENFB_CONTENT_MRE_3GT_BOW,
				   0 /* external */,
				   0 /* external */,
				   "MREAPP3GTBO" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

    {ENFB_IDSTRING3, ENFB_CONTENT_MRE_3GT_DAN,
				   0 /* external */,
				   0 /* external */,
				   "MREAPP3GTDA" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },			   
/* prabhjot - gameloft */
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_AS6,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLAS6" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_ACR,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLACR" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_BBR,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLBBR" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_BCL,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLBCL" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_MC2,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLMC2" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GL_GLLV2,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPGLLV2" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_TWITTER,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPTWITR" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_TWITTER_VSM,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPTWVSM" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

{ENFB_IDSTRING3, ENFB_CONTENT_MRE_YMV2,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYM2XP" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YMV2_UI_VSM,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYM2UI" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YMV2_SSL_VSM,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYM2SL" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
{ENFB_IDSTRING3, ENFB_CONTENT_MRE_FBV2,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPFBV20" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_FBV2_VSM,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPFB2SM" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_FBV2_MSG,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPFBMSG" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YW,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYWAPP" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },

   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YF,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYFAPP" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YN,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPYNAPP" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_KAIXIN,
                   0 /* external */,
                   0 /* external */,
                   "MREAPPKAIXI" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_KAIXINVSM,
                   0 /* external */,
                   0 /* external */,
                   "MREAPPKXVSM" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_YOUKU,
                   0 /* external */,
                   0 /* external */,
                   "MREAPPYOUKU" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_WOCHACHA,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPWCHCH" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_ZAKAT,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPZAKAT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },   
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_ANGRYBIRD,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPAGYBD" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },    
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_FISHINGFUN,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPFISHF" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_FRUITNINJA,
				   0 /* external */,
				   0 /* external */,
				   "MREAPPFRUIT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
    {ENFB_IDSTRING3, ENFB_CONTENT_MRE_EGYPTCODE,
           0 /* external */,
           0 /* external */,
           "MREAPPEGYPT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GILRSLOT,
           0 /* external */,
           0 /* external */,
           "MREAPPGISLT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_GOLDENMINER,
           0 /* external */,
           0 /* external */,
           "MREAPPGDMNR" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_HAPPYEGG,
           0 /* external */,
           0 /* external */,
           "MREAPPHPEGG" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_HAPPYWAR,
           0 /* external */,
           0 /* external */,
           "MREAPPHPWAR" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_KINGCOMBAT,
           0 /* external */,
           0 /* external */,
           "MREAPPKCBAT" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_MOTO,
           0 /* external */,
           0 /* external */,
           "MREAPPMOTOO" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_PARKOUR,
           0 /* external */,
           0 /* external */,
           "MREAPPPARKU" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },
   {ENFB_IDSTRING3, ENFB_CONTENT_MRE_TEARDRESS,
           0 /* external */,
           0 /* external */,
           "MREAPPTEAED" /* MUST SYNC with script tools/EnfbPack3rdRom.pl */ },   
   {ENFB_IDSTRING3, ENFB_CONTENT_ENDMARKER,
                   ((kal_uint32) &Load$$THIRD_ROM$$Base),
                   0 /* Tail mark */,
                   NULL }
   },
   VERNO_STR
};
#pragma arm section rodata

#endif /* __NFB_THIRD_ROM_SUPPORT__ && __MTK_TARGET__ */


