#ifdef __PLUTO_MMI_PACKAGE__
#include "MMI_features.h"
#include "CustResDef.h"
<?xml version="1.0" encoding="UTF-8"?>

<APP id="APP_MMI_CERTMAN">

    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,GlobalMenuItems.h" />
    <INCLUDE file="SettingResDef.h" />

#ifdef __CERTMAN_SUPPORT__

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    <STRING id="STR_ID_CERTMAN_INPUT_PASSWORD"/>
    <STRING id="STR_ID_CERTMAN_PRIVATE_KEY"/>
    <STRING id="STR_ID_CERTMAN_PERSONAL_CERTIFICATE"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_INFO"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_DETAILS"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_LABEL"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_KEY_USAGE"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_PRIVATE_KEY_PROTECTION"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_PRIV_KEY_CONFIRMATION"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_CONFIRM_PWD"/>
    <STRING id="STR_ID_CERTMAN_FILE_CONTAINS"/>
    <STRING id="STR_ID_CERTMAN_CERT_TYPE"/>
    <STRING id="STR_ID_CERTMAN_CERT_SERIAL_NO"/>
    <STRING id="STR_ID_CERTMAN_CERT_VERSION"/>
    <STRING id="STR_ID_CERTMAN_CERT_ISSUER"/>
    <STRING id="STR_ID_CERTMAN_CERT_VALID_FROM"/>
    <STRING id="STR_ID_CERTMAN_CERT_VALID_UPTO"/>
    <STRING id="STR_ID_CERTMAN_CERT_FINGER_PRINT"/>
    <STRING id="STR_ID_CERTMAN_KP_ALL"/>
    <STRING id="STR_ID_CERTMAN_KP_SERVER_AUTH"/>
    <STRING id="STR_ID_CERTMAN_KP_CLIENT_AUTH"/>
    <STRING id="STR_ID_CERTMAN_KP_CODE_SIGNING"/>
    <STRING id="STR_ID_CERTMAN_KP_EMAIL_PROTECTION"/>
    <STRING id="STR_ID_CERTMAN_KP_IPSEC_ENDSYSTEM"/>
    <STRING id="STR_ID_CERTMAN_KP_IPSEC_TUNNEL"/>
    <STRING id="STR_ID_CERTMAN_KP_IPSEC_USER"/>
    <STRING id="STR_ID_CERTMAN_KP_TIME_STAMPING"/>
    <STRING id="STR_ID_CERTMAN_KP_OCSP_SIGNING"/>
    <STRING id="STR_ID_CERTMAN_MEMORY_FULL"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CONTEXT"/>
    <STRING id="STR_ID_CERTMAN_INVALID_ENCODING"/>
    <STRING id="STR_ID_CERTMAN_INCORRECT_PASSWORD"/>
    <STRING id="STR_ID_CERTMAN_NEED_PASSWORD"/>
    <STRING id="STR_ID_CERTMAN_INVALID_JOB"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CERT_ID"/>
    <STRING id="STR_ID_CERTMAN_LABEL_EXISTS"/>
    <STRING id="STR_ID_CERTMAN_INVALID_LABEL"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CERT_GROUP"/>
    <STRING id="STR_ID_CERTMAN_INVALID_KEY_PURPOSE"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_NOT_FOUND"/>
    <STRING id="STR_ID_CERTMAN_CERT_EXISTS"/>
    <STRING id="STR_ID_CERTMAN_READ_ONLY"/>
    <STRING id="STR_ID_CERTMAN_NOT_SAVED"/>
    <STRING id="STR_ID_CERTMAN_DISCARDED"/>
    <STRING id="STR_ID_CERTMAN_MISMATCHED"/>
    <STRING id="STR_ID_CERTMAN_CERTTYPE_X509"/>
    <STRING id="STR_ID_CERTMAN_NOT_VALIDATED"/>
    <STRING id="STR_ID_CERTMAN_EXPIRED_CERT"/>
    <STRING id="STR_ID_CERTMAN_MAX_LIMIT"/>
    <STRING id="STR_ID_CERTMAN_USE_PERSONAL_CERTIFICATE"/>
    <STRING id="STR_ID_CERTMAN_INVALID_INPUT"/>
    <STRING id="STR_ID_CERTMAN_TOO_MANY_CERT"/>
    <STRING id="STR_ID_CERTMAN_CORRUPTED_FILE"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATES"/>
    <STRING id="STR_ID_CERTMAN_AUTHORITY_CERT"/>
    <STRING id="STR_ID_CERTMAN_USER_CERT"/>
    <STRING id="STR_ID_CERTMAN_OPTION_KEY_USAGE"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CERTIFICATE"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CERT_ERROR"/>
    <STRING id="STR_ID_CERTMAN_INVALID_CERT_CONTINUE"/>
    <STRING id="STR_ID_CERTMAN_WARN_BCONST_NOT_CRITICAL"/>
    <STRING id="STR_ID_CERTMAN_WARN_NO_TRUSTED_CERTS"/>
    <STRING id="STR_ID_CERTMAN_WARN_UNKNOWN_CRITICAL_EXT"/>
    <STRING id="STR_ID_CERTMAN_WARN_VALIDITY"/>
    <STRING id="STR_ID_CERTMAN_WARN_KEY_MISUSE"/>
    <STRING id="STR_ID_CERTMAN_WARN_INVALID_SIGNATURE"/>
    <STRING id="STR_ID_CERTMAN_WARN_CORRUPTED_CERT"/>
    <STRING id="STR_ID_CERTMAN_WARN_NO_CERT_HASH"/>
    <STRING id="STR_ID_CERTMAN_WARN_URLS_DONT_MATCH"/>
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_IMPORTED"/>
    <STRING id="STR_ID_CERTMAN_INVALID_KEY_TYPE"/>
    <STRING id="STR_ID_CERTMAN_CERT_IN_USE"/>
    <STRING id="STR_ID_CERTMAN_INVALID_FILENAME"/>
    <STRING id="STR_ID_CERTMAN_NO_KEY_PURPOSE"/>
    <STRING id="STR_ID_CERTMAN_DELETE_CONFIRM"/>
    <STRING id="STR_ID_CERTMAN_DELETE_ALL_CONFIRM"/>
    <STRING id="STR_ID_CERTMAN_WARN_TRUSTED_EXPIRED"/>
    <STRING id="STR_ID_CERTMAN_WARN_TRUSTED_NO_KEY_USAGE"/>
    <STRING id="STR_ID_CERTMAN_COLON"/>
    <STRING id="STR_ID_CERTMAN_SEMI_COLON"/>
    <STRING id="STR_ID_CERTMAN_NO_USER_CERT_CONFIRM"/>
#ifdef __OCSP_SUPPORT__
    <STRING id="STR_ID_CERTMAN_CERTIFICATE_CHECK"/>
    <STRING id="STR_ID_CERTMAN_CERT_STATUS_SERVER"/>
    <STRING id="STR_ID_CERTMAN_MUST_BE_PASSED"/>
    <STRING id="STR_ID_CERTMAN_CERT_VALIDATION"/>    
#endif /*__OCSP_SUPPORT__*/
    <STRING id="STR_ID_CERTMAN_FILE_NOT_FOUND"/>
    <STRING id="STR_ID_CERTIFICATE_MANAGER"/>

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>

    <IMAGE id="IMG_ID_CERTMAN_INTERMEDIATE_CERT">CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Settings\\\\CertificateManager\\\\CM_INTERMEDIATE.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_PERSONAL_CERT">CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Settings\\\\CertificateManager\\\\CM_PERSONAL.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_ROOT_CERT">CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Settings\\\\CertificateManager\\\\CM_ROOT.bmp"</IMAGE>
    <IMAGE id="IMG_ID_CERTMAN_USER_CERT">CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Settings\\\\CertificateManager\\\\CM_USER.bmp"</IMAGE>
#if defined(__MMI_OP01_MENU_9MATRIX__) || defined(__MMI_OP01_MENU_12MATRIX__)
    <IMAGE id="IMG_ID_CERTMAN_CERT_MANAGER">CUST_IMG_PATH"\\\\MainLCD\\\\Titlebar\\\\TB_CM.png"</IMAGE>
#else    
    <IMAGE id="IMG_ID_CERTMAN_CERT_MANAGER">CUST_IMG_PATH"\\\\MainLCD\\\\Titlebar\\\\TB_CM.bmp"</IMAGE>
#endif

    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>

    <MENUITEM id="MENU_CERTIFICATE_MANAGER" str="STR_ID_CERTIFICATE_MANAGER"/>
    
    <MENUITEM id="MENU_ID_CERTMAN_AUTHORITY_CERT" str="STR_ID_CERTMAN_AUTHORITY_CERT" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_CERTMAN_USER_CERT" str="STR_ID_CERTMAN_USER_CERT" img="IMG_GLOBAL_L2"/>
#ifdef __OCSP_SUPPORT__
    <MENUITEM id="MENU_ID_CERTMAN_CERT_VALIDATION" str="STR_ID_CERTMAN_CERT_VALIDATION" img="IMG_GLOBAL_L3"/>
#endif /* _OCSP_SUPPORT__*/


    <MENU id="MENU_ID_CERTMAN_ALL_CERT" type="ORIGINAL" str="STR_ID_CERTIFICATE_MANAGER" img="IMG_ID_CERTMAN_CERT_MANAGER">
        <MENUITEM_ID> MENU_ID_CERTMAN_AUTHORITY_CERT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_USER_CERT </MENUITEM_ID>
#ifdef __OCSP_SUPPORT__
        <MENUITEM_ID> MENU_ID_CERTMAN_CERT_VALIDATION </MENUITEM_ID>
#endif /* _OCSP_SUPPORT__*/
    </MENU>


    <MENUITEM id="MENU_ID_CERTMAN_OPTION_VIEW_CERTIFICATE" str="STR_GLOBAL_VIEW" img="IMG_GLOBAL_L1"/>
    <MENUITEM id="MENU_ID_CERTMAN_OPTION_DELETE_CERTIFICATE" str="STR_GLOBAL_DELETE" img="IMG_GLOBAL_L2"/>
    <MENUITEM id="MENU_ID_CERTMAN_OPTION_TRUST_SETTINGS_CERTIFICATE" str="STR_ID_CERTMAN_OPTION_KEY_USAGE" img="IMG_GLOBAL_L3"/>
    
    <MENU id="MENU_ID_CERTMAN_OPTIONS" type="ORIGINAL" str="0" >
        <MENUITEM_ID> MENU_ID_CERTMAN_OPTION_VIEW_CERTIFICATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_OPTION_DELETE_CERTIFICATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_OPTION_TRUST_SETTINGS_CERTIFICATE </MENUITEM_ID>
    </MENU>


    <MENUITEM id="MENU_ID_CERTMAN_INVALID_OPTION_INSTALL" str="STR_GLOBAL_INSTALL" highlight="mmi_certman_highlight_invalid_cert_install"/>
    <MENUITEM id="MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE" str="STR_ID_CERTMAN_INVALID_CERT_CONTINUE" highlight="mmi_certman_highlight_invalid_cert_continue"/>
    <MENUITEM id="MENU_ID_CERTMAN_INVALID_OPTION_CANCEL" str="STR_GLOBAL_CANCEL" highlight="mmi_certman_highlight_invalid_cert_cancel"/>
  
    <MENU id="MENU_ID_CERTMAN_INVALID_OPTIONS1" type="ORIGINAL" str="0" >
        <MENUITEM_ID> MENU_ID_CERTMAN_INVALID_OPTION_INSTALL </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_INVALID_OPTION_CANCEL </MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_CERTMAN_INVALID_OPTIONS2" type="ORIGINAL" str="0" >
        <MENUITEM_ID> MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_INVALID_OPTION_CANCEL </MENUITEM_ID>
    </MENU>

    <!------------------------------------------------------FMGR options------------------------------------------------------>
    <MENUITEM id="MENU_FMGR_CER_OPTION_INSTALL" str="STR_GLOBAL_INSTALL"/>
    <FILE_TYPES>
        <FILE_OPTION_HDLR option="MENU_FMGR_CER_OPTION_INSTALL" handler="mmi_certman_install_handler"/>
    </FILE_TYPES>

    <MENU id="MENU_ID_FMGR_CERT_TYPE_OPTIONS" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_FMGR_CER_OPTION_INSTALL</MENUITEM_ID>
    </MENU>

    <!------------------------------------------------------Idle callback------------------------------------------------------>
    <RECEIVER id="EVT_ID_IDLE_ENTER" proc="mmi_certman_deinit"/>

    <!------------------------------------------------------NVRAM cache------------------------------------------------------>
    <CACHEDATA type="byte" id="NVRAM_CERTMAN_OCSP_SETTING" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> OCSP Settings </DESCRIPTION>
    </CACHEDATA>

    <!------------------------------------------------------Not required after Ful screen editor CUI ------------------------------------------------------>

    <MENUITEM id="MENU_ID_CERTMAN_EDITOR_OPTION_DONE" str="STR_GLOBAL_DONE"/>
    <MENUITEM id="MENU_ID_CERTMAN_EDITOR_OPTION_INPUT_METHOD" str="STR_GLOBAL_INPUT_METHOD"/>

    <MENU id="MENU_ID_CERTMAN_EDITOR_OPTION" type="ORIGINAL" str="0" >
        <MENUITEM_ID> MENU_ID_CERTMAN_EDITOR_OPTION_DONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_CERTMAN_EDITOR_OPTION_INPUT_METHOD </MENUITEM_ID>
    </MENU>


#if defined (__MMI_DOWNLOAD_AGENT__)
<RECEIVER id="EVT_ID_DLA_SRV_CERTMAN_SETTING_IND" proc="mmi_certman_install_da_file_hdlr"/>>
#endif

<TIMER id= "MMI_CERTMAN_TIMER_ID"/>

#endif /* __CERTMAN_SUPPORT__ */

</APP>
#endif /* __PLUTO_MMI_PACKAGE__ */        
