#pragma comment(linker, "/INCLUDE:_logical_data_item_table_internal")
#pragma comment(linker, "/INCLUDE:_logical_data_item_table_factory")
#pragma comment(linker, "/INCLUDE:_logical_data_item_table_core")
#pragma comment(linker, "/INCLUDE:_logical_data_item_table_adc")
#pragma comment(linker, "/INCLUDE:_logical_data_item_table_touchpanel")
#pragma comment(linker, "/INCLUDE:_g_fs_quota_init")
