#include "MMI_features.h"
#include "CustResDef.h"

<?xml version="1.0" encoding="UTF-8"?>

/* Needed header files of the compile option in XML files, if you need others need to add here */


#if defined(__WAP_PUSH_SUPPORT__) && !defined(__WAP_PUSH_SERVICE_ONLY_SUPPORT__)

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_MMI_WAP_PUSH">

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can file the ID */
    <!--Include Area--> 
    <INCLUDE file = "GlobalResDef.h"/>
    <INCLUDE file = "mmi_rp_app_mmi_wap_push_def.h"/>
    #ifdef __UM_SUPPORT__
    <INCLUDE file = "mmi_rp_app_unifiedmessage_def.h"/>
    #endif

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */



    /* String ID's Start */
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
<STRING id="STR_ID_PUSH_ENABLE_WHITE_LIST"/>
<STRING id="STR_ID_PUSH_WHITE_LIST"/>
<STRING id="STR_ID_PUSH_WL_SETTING_DISCARD"/>
<STRING id="STR_ID_PUSH_WL_SETTING_NOTIFY"/>
<STRING id="STR_ID_BRW_PUSH_CONFIRM_LIST_MODIFY"/>
<STRING id="STR_ID_BRW_PUSH_UNMATCHED_ADDRESS"/>
<STRING id="STR_ID_PUSH_NEW_UNKNOWN_MSG"/>
<STRING id="STR_ID_PUSH_ACCEPT_AND_ADD_WL"/>
<STRING id="STR_ID_PUSH_REJECT_AND_ADD_BL"/>
<STRING id="STR_ID_PUSH_INBOX_ADD_NEW "/>
<STRING id="STR_ID_PUSH_INBOX_TRUST_LIST_PHONE_NUMBER"/>
<STRING id="STR_ID_PUSH_INBOX_TRUST_LIST_IP_ADDRESS"/>
<STRING id="STR_ID_BRW_PUSH_SENDER_ADDRESS"/>
<STRING id="STR_ID_BRW_PUSH_SMSC_ADDR"/>
<STRING id="STR_ID_PUSH_ATLEAST_ONE_FIELD_REQUIRED"/>
<STRING id="STR_ID_PUSH_SETTING_INVALID_SENDER"/>
<STRING id="STR_ID_PUSH_SETTING_INVALID_SMSC"/>
<STRING id="STR_ID_PUSH_INVALID_IP"/>
<STRING id="STR_ID_PUSH_SAME_ITEM_EXIST"/>
<STRING id="STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST"/>
<STRING id="STR_ID_PUSH_TRUST_LIST_FULL"/>
<STRING id="STR_ID_PUSH_ENABLE_SETTING_ACCEPT_AUTHENTICATED"/>
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */

#ifdef __MMI_WAP_PUSH_BLACK_LIST__
<STRING id="STR_ID_PUSH_ENABLE_BLACK_LIST"/>
<STRING id="STR_ID_PUSH_BLACK_LIST"/>
<STRING id="STR_ID_PUSH_REJECT_AND_ADD_BL"/>
<STRING id="STR_ID_PUSH_INBOX_ADD_TO_BLACK_LIST"/>
<STRING id="STR_ID_PUSH_BLACK_LIST_FULL"/>
#endif /* __MMI_WAP_PUSH_BLACK_LIST__ */

<STRING id="STR_ID_PUSH_ENABLE_SERVICE_LOADING"/>
<STRING id="STR_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL"/>
<STRING id="STR_ID_PUSH_DISABLE"/>
<STRING id="STR_ID_PUSH_SL_SETTING_PROMPT"/>
<STRING id="STR_ID_PUSH_SL_SETTING_AUTO_LAUNCH"/>
#if !defined(__MMI_WAP_PUSH_SIA_SLIM__) || defined(__MMI_WAP_PUSH_WHITE_LIST__)
<STRING id="STR_ID_BRW_PUSH_CONFIRM_SIA_REQ"/>
<STRING id="STR_ID_BRW_PUSH_HOST_ADDR"/>
<STRING id="STR_ID_BRW_PUSH_HOST_PORT"/>
<STRING id="STR_ID_BRW_PUSH_SIA_REQ_TITLE"/>
<STRING id="STR_ID_PUSH_MAIN_MENU_MESSAGES_TEXT"/>
#endif


<STRING id="STR_ID_PUSH_INBOX_SETTING "/>
<STRING id="STR_ID_PUSH_INBOX_ENABLE_PUSH "/>

<STRING id="STR_ID_BRW_PUSH_DELETE_CONFIRM"/>
<STRING id="STR_ID_BRW_PUSH_PRIORITY_TITLE"/>
<STRING id="STR_ID_BRW_PUSH_MESSAGE_TITLE"/>
<STRING id="STR_ID_BRW_PUSH_URL_TITLE"/>
<STRING id="STR_ID_BRW_PUSH_SENDER_ADDR"/>
<STRING id="STR_ID_PUSH_INBOX"/>

<STRING id="STR_ID_PUSH_INBOX_ADD_BOOKMARK"/>
<STRING id="STR_ID_PUSH_SERVICE_MESSAGE_RCVD"/>
<STRING id="STR_ID_BRW_PUSH_CREATED_TIME"/>
<STRING id="STR_ID_BRW_PUSH_EXPIRY_TIME"/>

<STRING id="STR_ID_PUSH_MESSAGE"/>
<STRING id="STR_ID_BRW_NEW_PUSH_MESSAGE"/>
<STRING id="STR_ID_PUSH_INBOX_MODIFIED"/>

<STRING id="STR_ID_BRW_PUSH_MESSAGE_EXPIRED"/>
<STRING id="STR_ID_PUSH_STORAGE_FULL"/>
<STRING id="STR_ID_PUSH_DELETE_ALL_INBOX_MSG"/>

#ifdef __MMI_WAP_PUSH_WHITE_LIST__
<STRING id="STR_ID_PUSH_REJECT"/>
<STRING id="STR_ID_BRW_PUSH_CO_REQ"/>
<STRING id="STR_ID_BRW_PUSH_SERVICE_MSG_FROM"/>
<STRING id="STR_ID_BRW_PUSH_DELETE_ALL_CONFIRM"/>
#endif /*__MMI_WAP_PUSH_WHITE_LIST__*/

#ifdef __MMI_BRW_PUSH_CONNECT_CONF__
<STRING id="STR_ID_PUSH_CONNECT_ASK"/>
#endif /*__MMI_BRW_PUSH_CONNECT_CONF__*/

#ifdef __MMI_BRW_DISABLE_PUSH_URL_DISPLAY__
<STRING id="STR_ID_PUSH_NO_SUBJECT"/>
#endif /*__MMI_BRW_DISABLE_PUSH_URL_DISPLAY__*/



#ifdef __MMI_BRW_PUSH_WHITELIST_OTA_SUPPORT__
<STRING id="STR_ID_BRW_PUSH_OTA_SKIP_WHITELIST"/>
<STRING id="STR_ID_BRW_PUSH_COLON_CHAR"/>
#endif /*__MMI_BRW_PUSH_WHITELIST_OTA_SUPPORT__*/


<STRING id="STR_ID_BRW_PUSH_TB_SETTINGS"/>

    /* Unified push new string ID */

<STRING id="STR_ID_BRW_PUSH_TITLE"/>

<STRING id="STR_ID_BRW_PUSH_UNREAD"/>
<STRING id="STR_ID_BRW_PUSH_SIM1"/>
<STRING id="STR_ID_BRW_PUSH_SIM2"/>
<STRING id="STR_ID_BRW_PUSH_NEW_SIM1_PUSH_MESSAGE"/>
<STRING id="STR_ID_BRW_PUSH_NEW_SIM2_PUSH_MESSAGE"/>
<STRING id="STR_ID_BRW_PUSH_NEW_SIM3_PUSH_MESSAGE"/>
<STRING id="STR_ID_BRW_PUSH_NEW_SIM4_PUSH_MESSAGE"/>

<STRING id="STR_ID_BRW_PUSH_MSG_DELETED"/>
<STRING id="STR_ID_WAP_PUSH_UNREAD_MSG"/>

<STRING id="STR_ID_PUSH_TITLE_URL_TOO_LONG"/>
<STRING id="STR_ID_PUSH_BKM_NOT_AVAILABLE"/>
<STRING id="STR_ID_PUSH_BKM_LIST_FULL"/>
	/* For PMG display error */
<STRING id="STR_ID_BRW_PUSH_ERROR_FULL"/>
<STRING id="STR_ID_BRW_PUSH_REQUEST_TIMED_OUT"/>
<STRING id="STR_ID_BRW_PUSH_ERROR_SIZE"/>
<STRING id="STR_ID_BRW_PUSH_DLG_SAVE_ERROR"/>
<STRING id="STR_ID_PUSH_SERVICE_MESSAGE"/>
<STRING id="STR_ID_PUSH_SERVICE_MESSAG"/>
    /* String ID's End */

#ifdef __MMI_PUSH_IN_MSG__
<STRING id="STR_ID_WAP_PUSH_UNREAD_MSG_NUMBER_ID"/>
#endif


#ifdef __MMI_WAP_PUSH_WHITE_LIST__
<STRING id="STR_ID_PUSH_UNMATCHED_ADDR_NOTIFICATION"/>
#endif /*__MMI_WAP_PUSH_WHITE_LIST__*/
<STRING id="STR_ID_PUSH_SIA_NOTIFICATION"/>

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    /* Image Id and path of you Application , you can use compile option in Path, but need out of CUST_IMG_PATH"" */




    /* Image ID's Start */
#ifdef __MMI_WGUI_CSK_ENABLE__
<IMAGE id="IMG_ID_BRW_PUSH_CSK_VIEW">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\Centerkey\\\\Read.bmp"</IMAGE>
#endif /* __MMI_WGUI_CSK_ENABLE__ */




#ifdef __SLIM_PUSH_FEATURE_SUPPORT__
<IMAGE id="IMG_ID_BRW_PUSH_READ">CUST_IMG_PATH"\\\\MainLCD\\\\Sms\\\\Submenu\\\\inbox\\\\SS_READ.bmp"</IMAGE>
<IMAGE id="IMG_ID_BRW_PUSH_UNREAD">CUST_IMG_PATH"\\\\MainLCD\\\\Sms\\\\Submenu\\\\inbox\\\\SS_UREAD.bmp"</IMAGE>
#else
<IMAGE id="IMG_ID_BRW_PUSH_READ">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_READ.bmp"</IMAGE>
<IMAGE id="IMG_ID_BRW_PUSH_UNREAD">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_UNREAD.bmp"</IMAGE>
#endif
<IMAGE id="IMG_ID_BRW_PUSH_EXPIRED_READ">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_EREAD.bmp"</IMAGE>
<IMAGE id="IMG_ID_BRW_PUSH_EXPIRED_UNREAD">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_EUNREAD.bmp"</IMAGE>
<IMAGE id="IMG_BRW_PUSH_CAPTION">CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_MG.bmp"</IMAGE>



#if defined (__MMI_FTE_SUPPORT__ ) && defined (__MMI_ICON_BAR_SUPPORT__)
<IMAGE id="IMG_ID_BRW_PUSH_TOOLBAR_GOTO">CUST_IMG_PATH"\\\\MainLCD\\\\ToolBar\\\\WapPush\\\\TB_goto.png"</IMAGE>
<IMAGE id="IMG_ID_BRW_PUSH_TOOLBAR_GOTO_DISABLED">CUST_IMG_PATH"\\\\MainLCD\\\\ToolBar\\\\WapPush\\\\TB_goto_dis.png"</IMAGE>
#endif /* __MMI_FTE_SUPPORT__ */

<IMAGE id="IMG_ID_WAP_PUSH_INBOX">CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_INBOX.bmp"</IMAGE>

    /* Image ID's End */


#ifndef __COSMOS_MMI__ 
    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
    /* Only MENUITEM need compile option, MENUITEM_ID does not need */

    <MENU id="MENU_ID_PUSH_INBOX" str="STR_ID_PUSH_INBOX"/>

#ifdef __MMI_PUSH_IN_UM__
    <MENU id="MENU_ID_PUSH_INBOX_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_READ</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_UM_COMPILE_OPTION_MSG_DELETE</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_UM_DEL_ALL_OPT</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_UM_MS_OPT</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_UM_SORT_BY_OPT</MENUITEM_ID>
#if defined(__MMI_UM_FILTER_BY_SIM_SUPPORT__)
            <MENUITEM_ID>MENU_ID_UM_FILTER_BY_OPT</MENUITEM_ID>
#endif
    </MENU>        

    <MENU id="MENU_ID_PUSH_SERVICE_MSG_READ" str="STR_GLOBAL_READ" />
	<MENU id="MENU_ID_PUSH_UM_COMPILE_OPTION_MSG_DELETE" str="STR_GLOBAL_DELETE" />
	
#endif /* __MMI_PUSH_IN_UM__ */

    <MENU id="MENU_ID_PUSH_MSG_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_GOTO</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_ADD_TO_BLACK_LIST</MENUITEM_ID>
		#ifdef __MMI_BRW_BKM_INTERFACE_SUPPORT__ 
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK</MENUITEM_ID>
		#endif
	 #ifndef __MMI_WAP_PUSH_ADVANCED_FEATURE_SLIM__
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_SEND_BY</MENUITEM_ID>
		 #endif
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_DELETE</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_SERVICE_MSG_GOTO" str="STR_GLOBAL_GO_TO" />
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST" str="STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST" />
#endif
#ifdef __MMI_WAP_PUSH_BLACK_LIST__
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_ADD_TO_BLACK_LIST" str="STR_ID_PUSH_INBOX_ADD_TO_BLACK_LIST" />
#endif
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK" str="STR_ID_PUSH_INBOX_ADD_BOOKMARK" />
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_DELETE" str="STR_GLOBAL_DELETE" />
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL" str="STR_GLOBAL_DELETE_ALL" />
#ifndef __MMI_WAP_PUSH_ADVANCED_FEATURE_SLIM__
    <MENU id="MENU_ID_PUSH_SERVICE_MSG_SEND_BY" type="OPTION" str="STR_GLOBAL_SEND" >
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_SEND_BY_SMS</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_SEND_BY_MMS</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SERVICE_MSG_SEND_BY_EMAIL</MENUITEM_ID>
    </MENU>

	<MENU id="MENU_ID_PUSH_SERVICE_MSG_SEND_BY_SMS" str="STR_GLOBAL_AS_TEXT_MESSAGE" />
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_SEND_BY_MMS" str="STR_GLOBAL_AS_MULTIMEDIA_MSG" />
	<MENU id="MENU_ID_PUSH_SERVICE_MSG_SEND_BY_EMAIL" str="STR_GLOBAL_AS_EMAIL" />
#endif	

#if (MMI_MAX_SIM_NUM == 2)
    <MENU id="MENU_ID_BRW_PUSH_CONNECT_SIM_MENU" type="OPTION" str="STR_GLOBAL_SEND">
            <MENUITEM_ID>MENU_ID_BRW_PUSH_SIM1</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_BRW_PUSH_SIM2</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_BRW_PUSH_WLAN</MENUITEM_ID>
    </MENU>
	<MENU id="MENU_ID_BRW_PUSH_SIM1" str="STR_ID_BRW_PUSH_SIM1" />
    <MENU id="MENU_ID_BRW_PUSH_SIM2" str="STR_ID_BRW_PUSH_SIM2" />
#endif /* __MMI_WAP_DUAL_SIM__ */

#ifdef __MMI_PUSH_IN_MSG__ 
    <MENU id="MENU_ID_SERVICE_MESSAGE" type="APP_SUB" str="STR_ID_PUSH_SERVICE_MESSAGE" img="IMG_ID_WAP_PUSH_INBOX">
            <MENUITEM_ID>MENU_ID_WAP_PUSH_INBOX</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_SERVICE_MSG_SETTING</MENUITEM_ID>
	</MENU>
    <MENU id="MENU_ID_WAP_PUSH_INBOX" str="STR_GLOBAL_INBOX"/>

#endif /* __MMI_PUSH_IN_MSG__  */

    <MENU id="MENU_ID_SERVICE_MSG_SETTING" type="APP_SUB" str="STR_ID_PUSH_INBOX_SETTING" img="IMG_BRW_PUSH_CAPTION" >
            <MENUITEM_ID>MENU_ID_SERVICE_MSG_ENABLE</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_SERVICE_MSG_SL_SETTING</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_ENABLE_WHITE_LIST</MENUITEM_ID>
			<MENUITEM_ID>MENU_ID_PUSH_ENABLE_BLACK_LIST</MENUITEM_ID>
			<MENUITEM_ID>MENU_ID_PUSH_WHITE_LIST</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_BLACK_LIST</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_SERVICE_MSG_ENABLE" type="OPTION" str="STR_ID_PUSH_INBOX_ENABLE_PUSH" img="IMG_BRW_PUSH_CAPTION"  hint="mmi_wap_push_enable_push_hint_hdlr">
            <MENUITEM_ID>MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_AUTHENTICATED</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_ENABLE_SETTING_DISABLE</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_SERVICE_MSG_SL_SETTING" type="OPTION" str="STR_ID_PUSH_ENABLE_SERVICE_LOADING" img="IMG_BRW_PUSH_CAPTION"  hint="mmi_wap_push_sl_setting_hint_hdlr">
            <MENUITEM_ID>MENU_ID_PUSH_SL_SETTING_PROMPT</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SL_SETTING_AUTO_LAUNCH</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_SL_SETTING_DISABLE</MENUITEM_ID>
    </MENU>

#ifdef __MMI_WAP_PUSH_WHITE_LIST__
    <MENU id="MENU_ID_PUSH_ENABLE_WHITE_LIST" type="OPTION" str="STR_ID_PUSH_ENABLE_WHITE_LIST" img="IMG_BRW_PUSH_CAPTION"  hint="mmi_wap_push_enable_wl_hint_hdlr">
            <MENUITEM_ID>MENU_ID_PUSH_WL_SETTING_DISCARD</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_WL_SETTING_NOTIFY</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_WL_SETTING_DISABLE</MENUITEM_ID>
    </MENU>
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */

#ifdef __MMI_WAP_PUSH_BLACK_LIST__
    <MENU id="MENU_ID_PUSH_ENABLE_BLACK_LIST" type="OPTION" str="STR_ID_PUSH_ENABLE_BLACK_LIST" img="IMG_BRW_PUSH_CAPTION"  hint="mmi_wap_push_enable_bl_hint_hdlr">
            <MENUITEM_ID>MENU_ID_PUSH_BL_SETTING_NOTIFY</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_BL_SETTING_DISABLE</MENUITEM_ID>
    </MENU>
#endif /* __MMI_WAP_PUSH_BLACK_LIST__ */

#ifdef __MMI_WAP_PUSH_WHITE_LIST__
    <MENU id="MENU_ID_PUSH_ADD_NEW" type="APP_SUB" str="STR_ID_PUSH_INBOX_ADD_NEW" img="IMG_BRW_PUSH_CAPTION" >
            <MENUITEM_ID>MENU_ID_PUSH_ADD_NEW_PHONE_NUMBER</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_ADD_NEW_IP_ADDR</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_ADDR_LIST_OPTIONS" type="OPTION" str="STR_GLOBAL_OPTIONS" img="IMG_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_MODIFY_ADDR_LIST</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_DELETE_ADDR_LIST</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_DELETE_ALL_ADDR_LIST</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_UNKNOWN_ADDR_OPTIONS" type="OPTION" str="STR_ID_BRW_PUSH_UNMATCHED_ADDRESS" img="IMG_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_UNKNOWN_ADDR_ACCEPT</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_UNKNOWN_ADDR_REJECT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_PUSH_UNKNOWN_ADDR_ACCEPT_AND_ADD_TO_WL</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_PUSH_UNKNOWN_ADDR_REJECT_AND_ADD_TO_BL</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_ADD_NEW_PHONE_NUMBER" str="STR_ID_PUSH_INBOX_TRUST_LIST_PHONE_NUMBER" />
    <MENU id="MENU_ID_PUSH_ADD_NEW_IP_ADDR" str="STR_ID_PUSH_INBOX_TRUST_LIST_IP_ADDRESS" />
    <MENU id="MENU_ID_PUSH_MODIFY_ADDR_LIST" str="STR_GLOBAL_EDIT" />
    <MENU id="MENU_ID_PUSH_DELETE_ADDR_LIST" str="STR_GLOBAL_DELETE" />
    <MENU id="MENU_ID_PUSH_DELETE_ALL_ADDR_LIST" str="STR_GLOBAL_DELETE_ALL" />
    <MENU id="MENU_ID_PUSH_WHITE_LIST" str="STR_ID_PUSH_WHITE_LIST" />
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */
#ifdef __MMI_WAP_PUSH_BLACK_LIST__
    <MENU id="MENU_ID_PUSH_BLACK_LIST" str="STR_ID_PUSH_BLACK_LIST"/>
#endif /* __MMI_WAP_PUSH_BLACK_LIST__ */

    <MENU id="MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL" str="STR_ID_PUSH_ENABLE_SETTING_ACCEPT_ALL" />

#ifdef __MMI_WAP_PUSH_WHITE_LIST__
    <MENU id="MENU_ID_PUSH_ENABLE_SETTING_ACCEPT_AUTHENTICATED" str="STR_ID_PUSH_ENABLE_SETTING_ACCEPT_AUTHENTICATED" />
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */
    <MENU id="MENU_ID_PUSH_ENABLE_SETTING_DISABLE" str="STR_ID_PUSH_DISABLE" />
    <MENU id="MENU_ID_PUSH_SL_SETTING_PROMPT" str="STR_ID_PUSH_SL_SETTING_PROMPT" />
    <MENU id="MENU_ID_PUSH_SL_SETTING_AUTO_LAUNCH" str="STR_ID_PUSH_SL_SETTING_AUTO_LAUNCH" />
    <MENU id="MENU_ID_PUSH_SL_SETTING_DISABLE" str="STR_ID_PUSH_DISABLE" />
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
    <MENU id="MENU_ID_PUSH_WL_SETTING_DISCARD" str="STR_ID_PUSH_WL_SETTING_DISCARD" />
    <MENU id="MENU_ID_PUSH_WL_SETTING_NOTIFY" str="STR_ID_PUSH_WL_SETTING_NOTIFY" />
    <MENU id="MENU_ID_PUSH_WL_SETTING_DISABLE" str="STR_ID_PUSH_DISABLE" />
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */
#ifdef __MMI_WAP_PUSH_BLACK_LIST__
    <MENU id="MENU_ID_PUSH_BL_SETTING_NOTIFY" str="STR_ID_PUSH_WL_SETTING_NOTIFY" />
    <MENU id="MENU_ID_PUSH_BL_SETTING_DISABLE" str="STR_ID_PUSH_DISABLE" />
#endif /* __MMI_WAP_PUSH_BLACK_LIST__ */
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
    <MENU id="MENU_ID_PUSH_UNKNOWN_ADDR_ACCEPT" str="STR_GLOBAL_ACCEPT" />
    <MENU id="MENU_ID_PUSH_UNKNOWN_ADDR_REJECT" str="STR_ID_PUSH_REJECT" />
    <MENU id="MENU_ID_PUSH_UNKNOWN_ADDR_ACCEPT_AND_ADD_TO_WL" str="STR_ID_PUSH_ACCEPT_AND_ADD_WL" />
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */
#ifdef __MMI_WAP_PUSH_BLACK_LIST__
    <MENU id="MENU_ID_PUSH_UNKNOWN_ADDR_REJECT_AND_ADD_TO_BL" str="STR_ID_PUSH_REJECT_AND_ADD_BL" />
#endif
    <MENU id="MENU_ID_PUSH_TB_LIVE_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS" img="IMG_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_TB_VIEW</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_TB_CALL</MENUITEM_ID>
			<MENUITEM_ID>MENU_ID_PUSH_TB_DELETE</MENUITEM_ID>
			<MENUITEM_ID>MENU_ID_PUSH_OP12_TOOL_BAR_SETTING</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_TB_LIVE_OPTION_IN_CALL" type="OPTION" str="STR_GLOBAL_OPTIONS" img="IMG_GLOBAL_OPTIONS">
            <MENUITEM_ID>MENU_ID_PUSH_TB_VIEW_IN_CALL</MENUITEM_ID>
            <MENUITEM_ID>MENU_ID_PUSH_TB_DELETE_IN_CALL</MENUITEM_ID>
			<MENUITEM_ID>MENU_ID_PUSH_OP12_TOOL_BAR_SETTING_IN_CALL</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_PUSH_TB_CALL" str="STR_GLOBAL_DIAL"/>
    <MENU id="MENU_ID_PUSH_TB_VIEW" str="STR_GLOBAL_VIEW"/>
    <MENU id="MENU_ID_PUSH_TB_VIEW_IN_CALL" str="STR_GLOBAL_VIEW"/>
    <MENU id="MENU_ID_PUSH_TB_DELETE" str="STR_GLOBAL_DELETE"/>
    <MENU id="MENU_ID_PUSH_TB_DELETE_IN_CALL" str="STR_GLOBAL_DELETE"/>
    <MENU id="MENU_ID_PUSH_OP12_TOOL_BAR_SETTING" str="STR_ID_BRW_PUSH_TB_SETTINGS"/>
    <MENU id="MENU_ID_PUSH_OP12_TOOL_BAR_SETTING_IN_CALL" str="STR_ID_BRW_PUSH_TB_SETTINGS"/>

#endif

    <!------------------------------------------------------Other Resource---------------------------------------------------------->


    <SCREEN id="SCR_ID_BRW_WAP_PUSH_POPUP_DUMMY_SCREEN"/>
    /* please add all screen IDs below this line */

    <SCREEN id="SCR_ID_BRW_NEW_PUSH_MESSAGE_IND"/>
    <SCREEN id="SCR_ID_BRW_INVALID_PUSH_MESSAGE"/>
    <SCREEN id="SCR_ID_PUSH_DISPALY_CONFIRMATION"/>
    <SCREEN id="SCR_ID_PUSH_SERIVCE_UNKNOWN_ADDR"/>
    <SCREEN id="SCR_ID_PSH_ENTRY_ADD_TRUST_SC_ADDR"/>
    <SCREEN id="SCR_ID_PUSH_SETTING"/>
    <SCREEN id="SCR_ID_PUSH_ENABLE_PUSH"/>
    <SCREEN id="SCR_ID_PUSH_SL_SETTING"/>
    <SCREEN id="SCR_ID_PUSH_ENABLE_WL_SETTING"/>
    <SCREEN id="SCR_ID_PUSH_ENABLE_BL_SETTING"/>
    <SCREEN id="SCR_ID_PUSH_WHITE_LIST"/>
    <SCREEN id="SCR_ID_PUSH_WHITE_LIST_ADD_NEW"/>
    <SCREEN id="SCR_ID_PUSH_WHITE_LIST_ADD_NEW_PHONE_NUM"/>
    <SCREEN id="SCR_ID_PUSH_WHITE_LIST_ADD_NEW_IP_ADDR"/>
    <SCREEN id="SCR_ID_PUSH_WHITE_LIST_OPTIONS"/>
    <SCREEN id="SCR_ID_PUSH_DISPALY_SIA_CNF"/>
    <SCREEN id="SCR_ID_PUSH_UNKNWN_ADDR_OPTIONS"/>
    <SCREEN id="SCR_ID_BRW_PUSH_OTA_INFO_DISPLAY"/>
    <SCREEN id="SCR_ID_PUSH_TB_PROCESSING"/>
    <SCREEN id="SCR_ID_PUSH_UM_SORT_BY_OPTIONS"/>
    <SCREEN id="SCR_ID_PUSH_INBOX"/>
    <SCREEN id="SCR_ID_PUSH_PROCESSING"/>
    <SCREEN id="SCR_ID_BRW_READ_SERVICE_MESSAGE"/>
    <SCREEN id="SCR_ID_PUSH_POPUP_SCREEN"/>
    <SCREEN id="SCR_ID_BRW_PUSH_DUMMY_SCREEN"/>
    <SCREEN id="SCR_ID_PUSH_ASYNC_PROCESSING"/>
    <SCREEN id="SCR_ID_PUSH_GENERIC_PROCESSING"/>
    <SCREEN id="SCR_ID_UM_MESSAGE_OPTIONS"/>
    <SCREEN id="SCR_ID_BRW_READ_SERVICE_MESSAGE_OPTIONS"/>
    <SCREEN id="SCR_ID_BRW_SEND_BY_OPTIONS"/>
    <SCREEN id="SCR_ID_BRW_PUSH_ADD_BOOKMARK"/>
    <SCREEN id="SCR_ID_BRW_PUSH_CONNECT_SIM_OPTIONS"/>
    <SCREEN id="SCR_ID_BRW_PUSH_MSG_DELETED"/>
    <SCREEN id="SCR_ID_PUSH_BLACK_LIST"/>
    <SCREEN id="SCR_ID_PUSH_ENTRY_SERVICE_MSG"/>

    <SCREEN id="SCR_ID_PUSH_END"/>
    #ifndef __COSMOS_MMI__ 
    /*********************************************Push Srv events begin*****************************************************************/
	<SENDER id="EVT_ID_SRV_PUSH_SHOW_PROGRESS" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_SHOW_POPUP" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_NEW_SERVICE_MSG" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_MSG_DELETED_BY_SERVER_IND" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_DELETE_PUSH_SETTING" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_FULL_MSG" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_MSG_LIST_REPLY" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_MSG_COUNT_RSP" hfile="WAPPushSrvGprots.h"/>
 #ifdef __MMI_WAP_PUSH_WHITE_LIST__
	<SENDER id="EVT_ID_SRV_PUSH_DRAW_UNKNOWN" hfile="WAPPushSrvGprots.h"/>
#endif
#ifndef __MMI_WAP_PUSH_SIA_SLIM__
	<SENDER id="EVT_ID_SRV_PUSH_SERVICE_INIT" hfile="WAPPushSrvGprots.h"/>
#endif 
#if !defined(__MMI_WAP_PUSH_SIA_SLIM__) || defined(__MMI_WAP_PUSH_WHITE_LIST__)	
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_DLG_DATA_RSP" hfile="WAPPushSrvGprots.h"/>
#endif
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_STORAGE_FULL_IND" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_DELETE_FOLDER_IND" hfile="WAPPushSrvGprots.h"/>
 #ifndef __MMI_NCENTER_SUPPORT__
	<SENDER id="EVT_ID_SRV_PUSH_HANDLE_PENDIG_EVENT_ON_IDLE" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_FETCH_DLG_QUEUE" hfile="WAPPushSrvGprots.h"/>
#endif
	<SENDER id="EVT_ID_SRV_PUSH_PROV_CUI_CREATE" hfile="WAPPushSrvGprots.h"/>
	<SENDER id="EVT_ID_SRV_PUSH_PROV_CUI_REDISPLAY" hfile="WAPPushSrvGprots.h"/>
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
	<SENDER id="EVT_ID_SRV_PUSH_UNKNOWN_ADDR_REQ" hfile="WAPPushSrvGprots.h"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_UNKNOWN_ADDR_REQ" proc="mmi_wap_push_service_unknown_addr_req"/>
#endif /* __MMI_WAP_PUSH_WHITE_LIST__ */
	<SENDER id="EVT_ID_SRV_PUSH_INBOX_INIT" hfile="WAPPushSrvGprots.h"/>
	
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
	<SENDER id="EVT_ID_SRV_PUSH_OTA_LIST_ENTRY" hfile="WAPPushSrvGprots.h"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_OTA_LIST_ENTRY" proc="mmi_wap_push_ota_list_entry_evt"/>
#endif

	<RECEIVER id="EVT_ID_SRV_PUSH_SHOW_PROGRESS" proc="mmi_wap_push_handle_progress_evt"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_SHOW_POPUP" proc="mmi_wap_push_handle_popup_evt"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_NEW_SERVICE_MSG" proc="mmi_wap_push_handle_new_service_msg"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_MSG_DELETED_BY_SERVER_IND" proc="mmi_wap_push_handle_msg_deleted_by_server_ind_evt"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_FULL_MSG" proc="mmi_wap_push_handle_full_msg_evt"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_DELETE_PUSH_SETTING" proc="mmi_wap_push_del_push_setting_evt"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_MSG_LIST_REPLY" proc="mmi_wap_push_msg_list_reply"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_MSG_COUNT_RSP" proc="mmi_wap_push_handle_msg_cnt_rsp"/>
#ifdef __MMI_WAP_PUSH_WHITE_LIST__
	<RECEIVER id="EVT_ID_SRV_PUSH_DRAW_UNKNOWN" proc="mmi_wap_push_draw_unknown_scren"/>
#endif
#ifndef __MMI_WAP_PUSH_SIA_SLIM__
	<RECEIVER id="EVT_ID_SRV_PUSH_SERVICE_INIT" proc="mmi_wap_push_service_initiation_req"/>
#endif
#if !defined(__MMI_WAP_PUSH_SIA_SLIM__) || defined(__MMI_WAP_PUSH_WHITE_LIST__) 
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_DLG_DATA_RSP" proc="mmi_wap_push_handle_dlg_data_rsp"/>
#endif
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_STORAGE_FULL_IND" proc="mmi_wap_push_handle_storage_full_ind"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_DELETE_FOLDER_IND" proc="mmi_wap_push_handle_delete_folder_ind"/>
#ifndef __MMI_NCENTER_SUPPORT__
	<RECEIVER id="EVT_ID_SRV_PUSH_HANDLE_PENDIG_EVENT_ON_IDLE" proc="mmi_wap_push_handle_pendig_event_on_idle"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_FETCH_DLG_QUEUE" proc="mmi_wap_push_fetch_dlg_from_queue"/>
#endif	
<RECEIVER id="EVT_ID_SRV_PUSH_INBOX_INIT" proc="mmi_wap_push_inbox_init"/>
#ifdef __MMI_BRW_PUSH_WHITELIST_OTA_SUPPORT__
	<RECEIVER id="EVT_ID_SRV_PUSH_PROV_CUI_CREATE" proc="mmi_wap_push_ota_ui_entry_proc"/>
	<RECEIVER id="EVT_ID_SRV_PUSH_PROV_CUI_REDISPLAY" proc="mmi_wap_push_ota_trustlist_prov_ui_done_proc"/>
#endif
	<RECEIVER id="EVT_ID_SRV_MODE_SWITCH_FINISH_NOTIFY" proc="mmi_wap_push_mode_finish_switch_event_hdlr"/>


#ifdef __MMI_UM_ITERATOR_VIEWER__
#ifdef __MMI_PUSH_IN_UM__
	<RECEIVER id="EVT_ID_MMI_UM_REFRESH" proc="mmi_wap_push_update_indexing_data_from_um"/>
#endif
#endif
#ifdef __MMI_PUSH_IN_UM__
	<RECEIVER id="EVT_ID_MMI_UM_ENTRY_FOLDER" proc="mmi_wap_push_handle_um_enter_folder"/>
#endif /* __MMI_PUSH_IN_UM__ */

#ifdef __SIM_HOT_SWAP_SUPPORT__
	<RECEIVER id="EVT_ID_SRV_SIM_CTRL_EVENT_DETECTED" proc="mmi_wap_push_if_sim_event_detected_proc"/>
#endif
#endif /* __COSMOS_MMI__ */ 

</APP>
#endif /* WAP_SUPPORT */