@echo off
copy /Y          .\applib\asn1\include\applib_asn_common.h						 %1
copy /Y          .\applib\asn1\include\applib_asn_memory.h						 %1
copy /Y          .\applib\asn1\include\applib_asn_uper_common.h						 %1
copy /Y          .\applib\asn1\include\applib_mtkasn_global.h						 %1
copy /Y          .\applib\kazlib\dict.h						 %1
copy /Y          .\applib\mem\include\app_mem.h						 %1
copy /Y          .\applib\mem\include\app_mem_define.h						 %1
copy /Y          .\applib\mem\include\app_mem_med.h						 %1
copy /Y          .\applib\misc\include\app_asyncfile.h						 %1
copy /Y          .\applib\misc\include\app_base64.h						 %1
copy /Y          .\applib\misc\include\app_datetime.h						 %1
copy /Y          .\applib\misc\include\app_html.h						 %1
copy /Y          .\applib\misc\include\app_md5.h						 %1
copy /Y          .\applib\misc\include\app_mine.h						 %1
copy /Y          .\applib\misc\include\app_plmn.h						 %1
copy /Y          .\applib\misc\include\app_qp.h						 %1
copy /Y          .\applib\misc\include\app_str.h						 %1
copy /Y          .\applib\misc\include\app_ua.h						 %1
copy /Y          .\applib\misc\include\app_url.h						 %1
copy /Y          .\applib\misc\include\app_usedetails.h						 %1
copy /Y          .\bcm\adp\inc\bcm_event_handler.h						 %1
copy /Y          .\bcm\adp\inc\bcmadp.h						 %1
copy /Y          .\bcm\adp\inc\comm_post_event.h						 %1
copy /Y          .\bcm\bcm_trc.h						 %1
copy /Y          .\bcm\ble_profiles\bcm_gattsrv.h						 %1
copy /Y          .\bcm\ble_profiles\fmp\bcm_fmpcommon.h						 %1
copy /Y          .\bcm\ble_profiles\fmp\fmpt\inc\bcm_fmpt_def.h						 %1
copy /Y          .\bcm\ble_profiles\fmp\fmpt\inc\bcm_fmptapp.h						 %1
copy /Y          .\bcm\ble_profiles\fmp\fmpt\inc\bcm_fmptsrv.h						 %1
copy /Y          .\bcm\ble_profiles\gattc\inc\bcm_gattcgprot.h						 %1
copy /Y          .\bcm\ble_profiles\gattc\inc\bcm_gattcsrv.h						 %1
copy /Y          .\bcm\ble_profiles\gatts\inc\bcm_gattprofilesrvdeclaration.h						 %1
copy /Y          .\bcm\ble_profiles\gatts\inc\bcm_gattservicesfactorysrv.h						 %1
copy /Y          .\bcm\ble_profiles\gatts\inc\bcm_gattsgprot.h						 %1
copy /Y          .\bcm\ble_profiles\gatts\inc\bcm_gattssrv.h						 %1
copy /Y          .\bcm\ble_profiles\pxp\bcm_prxcommon.h						 %1
copy /Y          .\bcm\ble_profiles\pxp\prxr\inc\bcm_prxr_def.h						 %1
copy /Y          .\bcm\ble_profiles\pxp\prxr\inc\bcm_prxrapp.h						 %1
copy /Y          .\bcm\ble_profiles\pxp\prxr\inc\bcm_prxrsrv.h						 %1
copy /Y          .\bcm\cm\inc\bcm_btcmapp.h						 %1
copy /Y          .\bcm\cm\inc\bcm_btcmcmd.h						 %1
copy /Y          .\bcm\cm\inc\bcm_btcmsrvgprot.h						 %1
copy /Y          .\bcm\cm\inc\bcm_btcmsrvprot.h						 %1
copy /Y          .\bcm\cm\inc\bcm_btcmutility.h						 %1
copy /Y          .\bcm\cm\inc\custom_bcm_btcm_config.h						 %1
copy /Y          .\bcm\profile\spp\inc\bcm_spp_app.h						 %1
copy /Y          .\bcm\profile\spp\inc\bcmsppsrv.h						 %1
copy /Y          .\bcm\profile\spp\inc\bcmsppsrvgprot.h						 %1
copy /Y          .\bcm\profile\spp\inc\bcmspputility.h						 %1
copy /Y          .\blueangel\btcore\btutils\inc\bt_maui_utility.h						 %1
copy /Y          .\config\include\app\app_task_config.h						 %1
copy /Y          .\config\include\app\mthl_sap.h						 %1
copy /Y          .\config\include\app\user_msgid_app.h						 %1
copy /Y          .\config\include\hal\ctrl_buff_pool.h						 %1
copy /Y          .\config\include\hal\fctycomp_config.h						 %1
copy /Y          .\config\include\hal\hal_task_config.h						 %1
copy /Y          .\config\include\hal\hisr_config.h						 %1
copy /Y          .\config\include\hal\hisr_config_internal.h						 %1
copy /Y          .\config\include\hal\kal_user_mem.h						 %1
copy /Y          .\config\include\hal\multiboot_config.h						 %1
copy /Y          .\config\include\hal\stack_config.h						 %1
copy /Y          .\config\include\hal\stack_msgs.h						 %1
copy /Y          .\config\include\hal\syscomp_config.h						 %1
copy /Y          .\config\include\hal\sysconf_statistics.h						 %1
copy /Y          .\config\include\hal\system_inc.h						 %1
copy /Y          .\config\include\hal\task_config.h						 %1
copy /Y          .\config\include\hal\tiny_trace_config.h						 %1
copy /Y          .\config\include\hal\usbmscomp_config.h						 %1
copy /Y          .\config\include\hal\user_msgid_hal.h						 %1
copy /Y          .\drm\include\drm_def.h						 %1
copy /Y          .\drm\include\drm_errcode.h						 %1
copy /Y          .\drm\include\drm_gprot.h						 %1
copy /Y          .\drv\include\bc_drv.h						 %1
copy /Y          .\drv\include\drv_trc.h						 %1
copy /Y          .\drv\include\msdc_lsd.h						 %1
copy /Y          .\fmr\inc\fm_radio.h						 %1
copy /Y          .\fmr\inc\fmr_main.h						 %1
copy /Y          .\fmr\inc\fmr_sap.h						 %1
copy /Y          .\fmr\inc\fmr_trc.h						 %1
copy /Y          .\fs\common\include\fs_internal_api.h						 %1
copy /Y          .\fs\common\include\fs_internal_def.h						 %1
copy /Y          .\fs\common\include\fs_iprot.h						 %1
copy /Y          .\fs\common\include\fs_trc.h						 %1
copy /Y          .\fs\efs\include\fs_internal.h						 %1
copy /Y          .\fs\efs\include\fs_utility.h						 %1
copy /Y          .\fs\fat\include\fs_kal.h						 %1
copy /Y          .\fs\fat\include\rtfbuf.h						 %1
copy /Y          .\fs\fat\include\rtfex.h						 %1
copy /Y          .\fs\fat\include\rtfiles.h						 %1
copy /Y          .\gps\inc\agps_struct.h						 %1
copy /Y          .\gps\inc\gps_agps_process.h						 %1
copy /Y          .\gps\inc\gps_common.h						 %1
copy /Y          .\gps\inc\gps_init.h						 %1
copy /Y          .\gps\inc\gps_main.h						 %1
copy /Y          .\gps\inc\gps_modem.h						 %1
copy /Y          .\gps\inc\gps_sm.h						 %1
copy /Y          .\gps\inc\gps_time_sync.h						 %1
copy /Y          .\gps\inc\gps_trc.h						 %1
copy /Y          .\gps\inc\gps_uart.h						 %1
copy /Y          .\gps\inc\gps_uart_hdlr.h						 %1
copy /Y          .\gps\inc\wepodownload.h						 %1
copy /Y          .\gps\mnl\include\mtk_gps.h						 %1
copy /Y          .\gps\mnl\include\mtk_gps_type.h						 %1
copy /Y          .\gps\mnl\mnl_oil\mtk_gps_task.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\audio_iirhpf_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\bescf_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\bessound_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\blisrc_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\cvsd_codec_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\dtmf_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\mp3_dec_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\sph_enh_exp.h						 %1
copy /Y          .\hal\audio\lib\mtkinc\wav_codec_exp.h						 %1
copy /Y          .\hal\audio\src\common\inc\audcom.h						 %1
copy /Y          .\hal\audio\src\common\inc\audcomutil.h						 %1
copy /Y          .\hal\audio\src\common\inc\daf_codec.h						 %1
copy /Y          .\hal\audio\src\common\inc\medadapt.h						 %1
copy /Y          .\hal\audio\src\common\inc\omx_core.h						 %1
copy /Y          .\hal\audio\src\common\inc\omx_index.h						 %1
copy /Y          .\hal\audio\src\common\inc\omx_types.h						 %1
copy /Y          .\hal\audio\src\common\inc\pcmsource.h						 %1
copy /Y          .\hal\audio\src\common\inc\postprocess.h						 %1
copy /Y          .\hal\audio\src\common\inc\sphprocess.h						 %1
copy /Y          .\hal\audio\src\common\inc\wav_codec.h						 %1
copy /Y          .\hal\audio\src\v1\inc\afe.h						 %1
copy /Y          .\hal\audio\src\v1\inc\afe_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\am.h						 %1
copy /Y          .\hal\audio\src\v1\inc\apm_task.h						 %1
copy /Y          .\hal\audio\src\v1\inc\ast.h						 %1
copy /Y          .\hal\audio\src\v1\inc\audio_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\audio_dsp_d2c_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\audio_sherif_bit_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\audlp2_drv.h						 %1
copy /Y          .\hal\audio\src\v1\inc\bt_sco_app.h						 %1
copy /Y          .\hal\audio\src\v1\inc\bt_sco_drv.h						 %1
copy /Y          .\hal\audio\src\v1\inc\common_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\daf_drv.h						 %1
copy /Y          .\hal\audio\src\v1\inc\dpmgr.h						 %1
copy /Y          .\hal\audio\src\v1\inc\dpram_6261.h						 %1
copy /Y          .\hal\audio\src\v1\inc\draexport.h						 %1
copy /Y          .\hal\audio\src\v1\inc\l1audio_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\l1audio_sph_trc.h						 %1
copy /Y          .\hal\audio\src\v1\inc\l1sp_trc.h						 %1
copy /Y          .\hal\audio\src\v1\inc\media.h						 %1
copy /Y          .\hal\audio\src\v1\inc\pcm4way.h						 %1
copy /Y          .\hal\audio\src\v1\inc\pcmmixer.h						 %1
copy /Y          .\hal\audio\src\v1\inc\pcmrb.h						 %1
copy /Y          .\hal\audio\src\v1\inc\pcmsink.h						 %1
copy /Y          .\hal\audio\src\v1\inc\speech_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\speech_enh_def.h						 %1
copy /Y          .\hal\audio\src\v1\inc\tone_drv.h						 %1
copy /Y          .\hal\audio\src\v1\inc\tonedect.h						 %1
copy /Y          .\hal\audio\src\v1\inc\tonesyn.h						 %1
copy /Y          .\hal\audio\src\v1\inc\vmi.h						 %1
copy /Y          .\hal\audio\src\v1\inc\wav.h						 %1
copy /Y          .\hal\bluetooth\btif\include\btif_sw.h						 %1
copy /Y          .\hal\bluetooth\mt6261\common\include\btdrv_common.h						 %1
copy /Y          .\hal\camera\cal\inc\cal_task_msg_if.h						 %1
copy /Y          .\hal\camera\isp\inc\aaa_nvram.h						 %1
copy /Y          .\hal\camera\isp\inc\isp_comm_if.h						 %1
copy /Y          .\hal\camera\isp\inc\isp_hw_feature_def.h						 %1
copy /Y          .\hal\camera\isp\inc\isp_nvram.h						 %1
copy /Y          .\hal\camera\mdp_cam_if\inc\idp_cam_if.h						 %1
copy /Y          .\hal\cipher\include\che_hw.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\otg_drv.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\upll_ctrl.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_comm.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_custom.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_drv.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_drv_pri.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_hcd.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_hcd_pri.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_hw.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_memory_def.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_msdisk.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usb_phy_drv.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usblog_drv.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usblog_hw.h						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usbvideo_custom.h						 %1
copy /Y          .\hal\display\common\include\display_io_internal.h						 %1
copy /Y          .\hal\display\common\include\lcd_if_6260_series_hw.h						 %1
copy /Y          .\hal\display\common\include\lcd_if_hw.h						 %1
copy /Y          .\hal\display\common\owfnativestream.h						 %1
copy /Y          .\hal\display\debug\inc\lcd_catcher_log.h						 %1
copy /Y          .\hal\display\flatten\inc\flatten_api_internal.h						 %1
copy /Y          .\hal\display\flatten\inc\hw_6236\flatten_api_internal_6236.h						 %1
copy /Y          .\hal\display\flatten\inc\hw_6250\flatten_api_internal_6250.h						 %1
copy /Y          .\hal\display\flatten\inc\hw_6255\flatten_api_internal_6255.h						 %1
copy /Y          .\hal\display\flatten\inc\hw_6260\flatten_api_internal_6260.h						 %1
copy /Y          .\hal\display\flatten\inc\hw_6276\flatten_api_internal_6276.h						 %1
copy /Y          .\hal\display\lcd_power_manager\inc\lcd_power_mgr_utility.h						 %1
copy /Y          .\hal\display\lcd_tear_manager\inc\lcd_tear_manager.h						 %1
copy /Y          .\hal\display\lcd_tear_manager\inc\lcd_tear_manager_internal.h						 %1
copy /Y          .\hal\display\wfc\inc\wfc_internal.h						 %1
copy /Y          .\hal\display\wfc\inc\wfc_internal_debug.h						 %1
copy /Y          .\hal\display\wfc\inc\wfc_mm_api.h						 %1
copy /Y          .\hal\display\wfd\inc\hw_6250\wfd_lcd_6250.h						 %1
copy /Y          .\hal\display\wfd\inc\hw_6260\govl_if_6260_hw.h						 %1
copy /Y          .\hal\display\wfd\inc\hw_6260\wfd_lcd_6260.h						 %1
copy /Y          .\hal\display\wfd\inc\wfd.h						 %1
copy /Y          .\hal\display\wfd\inc\wfd_common.h						 %1
copy /Y          .\hal\display\wfd\inc\wfd_hwdevice.h						 %1
copy /Y          .\hal\display\wfd\inc\wfd_lcd_chip_select.h						 %1
copy /Y          .\hal\display\wfd\inc\wfd_lcd_internal.h						 %1
copy /Y          .\hal\display\wfd\inc\wfdext.h						 %1
copy /Y          .\hal\display\wfd\inc\wfdplatform.h						 %1
copy /Y          .\hal\drv_def\drv_features.h						 %1
copy /Y          .\hal\drv_def\drv_features_6261.h						 %1
copy /Y          .\hal\drv_def\drv_features_accdet.h						 %1
copy /Y          .\hal\drv_def\drv_features_adc.h						 %1
copy /Y          .\hal\drv_def\drv_features_bmt.h						 %1
copy /Y          .\hal\drv_def\drv_features_chip_select.h						 %1
copy /Y          .\hal\drv_def\drv_features_chr_det.h						 %1
copy /Y          .\hal\drv_def\drv_features_color.h						 %1
copy /Y          .\hal\drv_def\drv_features_display.h						 %1
copy /Y          .\hal\drv_def\drv_features_f32k.h						 %1
copy /Y          .\hal\drv_def\drv_features_g2d.h						 %1
copy /Y          .\hal\drv_def\drv_features_gcu.h						 %1
copy /Y          .\hal\drv_def\drv_features_gif.h						 %1
copy /Y          .\hal\drv_def\drv_features_gpio.h						 %1
copy /Y          .\hal\drv_def\drv_features_gpt.h						 %1
copy /Y          .\hal\drv_def\drv_features_hif.h						 %1
copy /Y          .\hal\drv_def\drv_features_i2c.h						 %1
copy /Y          .\hal\drv_def\drv_features_irda.h						 %1
copy /Y          .\hal\drv_def\drv_features_isp.h						 %1
copy /Y          .\hal\drv_def\drv_features_jpeg.h						 %1
copy /Y          .\hal\drv_def\drv_features_kbd.h						 %1
copy /Y          .\hal\drv_def\drv_features_mdp.h						 %1
copy /Y          .\hal\drv_def\drv_features_misc.h						 %1
copy /Y          .\hal\drv_def\drv_features_mmsysmisc.h						 %1
copy /Y          .\hal\drv_def\drv_features_msdc.h						 %1
copy /Y          .\hal\drv_def\drv_features_opengles.h						 %1
copy /Y          .\hal\drv_def\drv_features_pfc.h						 %1
copy /Y          .\hal\drv_def\drv_features_png.h						 %1
copy /Y          .\hal\drv_def\drv_features_pwm.h						 %1
copy /Y          .\hal\drv_def\drv_features_resizer.h						 %1
copy /Y          .\hal\drv_def\drv_features_rotator.h						 %1
copy /Y          .\hal\drv_def\drv_features_rtc.h						 %1
copy /Y          .\hal\drv_def\drv_features_sim.h						 %1
copy /Y          .\hal\drv_def\drv_features_spi.h						 %1
copy /Y          .\hal\drv_def\drv_features_spislave.h						 %1
copy /Y          .\hal\drv_def\drv_features_stack_switch.h						 %1
copy /Y          .\hal\drv_def\drv_features_tp.h						 %1
copy /Y          .\hal\drv_def\drv_features_uart.h						 %1
copy /Y          .\hal\drv_def\drv_features_usb.h						 %1
copy /Y          .\hal\drv_def\drv_features_vcodec.h						 %1
copy /Y          .\hal\drv_def\drv_features_video.h						 %1
copy /Y          .\hal\drv_def\drv_features_wdt.h						 %1
copy /Y          .\hal\dsp_ram\ddload.h						 %1
copy /Y          .\hal\graphics\bfc\inc\bfc_decode_int.h						 %1
copy /Y          .\hal\graphics\color\hw\inc\color_drv_6260_series.h						 %1
copy /Y          .\hal\graphics\color\hw\inc\color_drv_api.h						 %1
copy /Y          .\hal\graphics\g2d\common\inc\g2d_macro.h						 %1
copy /Y          .\hal\graphics\g2d\common\inc\g2d_mutex.h						 %1
copy /Y          .\hal\graphics\g2d\common\inc\g2d_structure.h						 %1
copy /Y          .\hal\graphics\g2d\hw\inc\g2d_drv_6260_series.h						 %1
copy /Y          .\hal\graphics\g2d\hw\inc\g2d_drv_api.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_1bpp.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_argb8888.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_raster.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_rgb565.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_rgb888.h						 %1
copy /Y          .\hal\graphics\gfx_core\bfc\inc\bfc_decode_structure.h						 %1
copy /Y          .\hal\graphics\gfx_core\g2d\inc\sw_rectfill.h						 %1
copy /Y          .\hal\graphics\gfx_core\ipp\inc\swipp_enum.h						 %1
copy /Y          .\hal\graphics\gfx_core\ipp\inc\swipp_interface.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\decode\inc\swjd_dequant_idct_unit.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\decode\inc\swjd_fragment_processor.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\decode\inc\swjd_huffman_decoder.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\encode\inc\swje_structure.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_dec_id.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_dec_structure.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_enc_data.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_enc_entry.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_enc_mem.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_enc_tag.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\exif\inc\exif_enc_utility.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\jaia\inc\jaia_exif.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\jaia\inc\jaia_int.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\jaia\inc\jaia_qvi.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\jaia\inc\jaia_structure_int.h						 %1
copy /Y          .\hal\graphics\gfx_core\jpeg\jaia\inc\jaia_tn.h						 %1
copy /Y          .\hal\graphics\gfx_core\png\inc\img_resizer.h						 %1
copy /Y          .\hal\graphics\gfx_core\png\inc\png.h						 %1
copy /Y          .\hal\graphics\gfx_core\png\inc\pngconf.h						 %1
copy /Y          .\hal\graphics\gfx_core\resizer\rgb_resizer\inc\sw_rgb_resizer_bilinear.h						 %1
copy /Y          .\hal\graphics\gfx_core\resizer\rgb_resizer\inc\sw_rgb_resizer_box.h						 %1
copy /Y          .\hal\graphics\gfx_core\resizer\rgb_resizer\inc\sw_rgb_resizer_nearest.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\rgb_rotator\inc\sw_rgb_rotator_argb6666.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\rgb_rotator\inc\sw_rgb_rotator_argb8888.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\rgb_rotator\inc\sw_rgb_rotator_gray.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\rgb_rotator\inc\sw_rgb_rotator_rgb565.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\rgb_rotator\inc\sw_rgb_rotator_rgb888.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\yuv_rotator\inc\sw_yuv_rotator_uyvy422.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\yuv_rotator\inc\sw_yuv_rotator_yuv420b4x4p.h						 %1
copy /Y          .\hal\graphics\gfx_core\rotator\yuv_rotator\inc\sw_yuv_rotator_yuv420p.h						 %1
copy /Y          .\hal\graphics\ipp\inc\ipp_features.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_drv_api.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_enum_int.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_mem_6235_series.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_mem_int.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_mem_sw.h						 %1
copy /Y          .\hal\graphics\jpeg\common\inc\jpeg_misc_api.h						 %1
copy /Y          .\hal\graphics\jpeg\decode\common\inc\jpeg_decode_structure.h						 %1
copy /Y          .\hal\graphics\jpeg\decode\common\inc\jpeg_parse_structure.h						 %1
copy /Y          .\hal\graphics\jpeg\encode\common\inc\jpeg_encode_structure.h						 %1
copy /Y          .\hal\graphics\jpeg\encode\common\inc\jpeg_encode_wrapper.h						 %1
copy /Y          .\hal\graphics\jpeg\exif\inc\exif_enc_api.h						 %1
copy /Y          .\hal\graphics\jpeg\exif\inc\exif_enc_enum.h						 %1
copy /Y          .\hal\graphics\jpeg\exif\inc\exif_enc_structure.h						 %1
copy /Y          .\hal\graphics\misc\inc\drv_gfx_dct_control.h						 %1
copy /Y          .\hal\graphics\misc\inc\drv_gfx_dynamic_switch.h						 %1
copy /Y          .\hal\graphics\misc\inc\drv_gfx_hisr_ctrl.h						 %1
copy /Y          .\hal\graphics\misc\inc\drv_gfx_l1sm_ctrl.h						 %1
copy /Y          .\hal\graphics\misc\inc\rs_buffer.h						 %1
copy /Y          .\hal\graphics\png\common\inc\png_decode_structure.h						 %1
copy /Y          .\hal\graphics\png\common\inc\png_decoder_int.h						 %1
copy /Y          .\hal\graphics\png\hw\inc\png_decode.h						 %1
copy /Y          .\hal\graphics\png\hw\inc\png_drv_common.h						 %1
copy /Y          .\hal\graphics\png\hw\inc\png_info.h						 %1
copy /Y          .\hal\graphics\png\hw\inc\png_status.h						 %1
copy /Y          .\hal\graphics\png\sw\inc\png_decoder.h						 %1
copy /Y          .\hal\graphics\resizer\rgb_resizer\common\inc\rgb_resizer_int.h						 %1
copy /Y          .\hal\graphics\resizer\rgb_resizer\common\inc\rgb_resizer_structure.h						 %1
copy /Y          .\hal\graphics\rotator\rgb_rotator\common\inc\rgb_rotator_int.h						 %1
copy /Y          .\hal\graphics\rotator\rgb_rotator\common\inc\rgb_rotator_structure.h						 %1
copy /Y          .\hal\graphics\rotator\yuv_rotator\common\inc\yuv_rotator_int.h						 %1
copy /Y          .\hal\graphics\rotator\yuv_rotator\common\inc\yuv_rotator_structure.h						 %1
copy /Y          .\hal\lqt\include\lcd_lqt.h						 %1
copy /Y          .\hal\mdp\include\mt6252\idp_hw\idp_hw_common.h						 %1
copy /Y          .\hal\mdp\include\mt6252\idp_hw\idp_imgdma.h						 %1
copy /Y          .\hal\mdp\include\mt6252\idp_hw\idp_imgdma_rotdma0.h						 %1
copy /Y          .\hal\mdp\include\mt6252\idp_hw\idp_resz.h						 %1
copy /Y          .\hal\mdp\include\mt6252\idp_hw\idp_resz_crz.h						 %1
copy /Y          .\hal\mm_comm\inc\visual_comm.h						 %1
copy /Y          .\hal\mm_comm\inc\visualhisr.h						 %1
copy /Y          .\hal\peripheral\inc\accdet_hw.h						 %1
copy /Y          .\hal\peripheral\inc\accdet_sw.h						 %1
copy /Y          .\hal\peripheral\inc\adc_hw.h						 %1
copy /Y          .\hal\peripheral\inc\adc_msg_handle.h						 %1
copy /Y          .\hal\peripheral\inc\adc_sw.h						 %1
copy /Y          .\hal\peripheral\inc\adcsche.h						 %1
copy /Y          .\hal\peripheral\inc\alerter_hw.h						 %1
copy /Y          .\hal\peripheral\inc\alerter_sw.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_chr_setting.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_hw.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_linear_li.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_sw.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_sw_chip_setting.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_timer_control.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_trc.h						 %1
copy /Y          .\hal\peripheral\inc\bmt_utility.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_common_config.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_gpt_hw.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_hts.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_mixedsys6261_reg.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_mixedsys_reg.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmic_features.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmu6261_hw.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmu6261_sw.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmu_common_sw.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmu_hw.h						 %1
copy /Y          .\hal\peripheral\inc\dcl_pmu_sw.h						 %1
copy /Y          .\hal\peripheral\inc\f32k_clk_hw.h						 %1
copy /Y          .\hal\peripheral\inc\f32k_clk_sw.h						 %1
copy /Y          .\hal\peripheral\inc\gpio_hw.h						 %1
copy /Y          .\hal\peripheral\inc\gpio_hw_mt6261.h						 %1
copy /Y          .\hal\peripheral\inc\gpio_sw.h						 %1
copy /Y          .\hal\peripheral\inc\gpt_hw.h						 %1
copy /Y          .\hal\peripheral\inc\gpt_sw.h						 %1
copy /Y          .\hal\peripheral\inc\hif_legacy_internal.h						 %1
copy /Y          .\hal\peripheral\inc\hif_v1_internal.h						 %1
copy /Y          .\hal\peripheral\inc\hif_v2_internal.h						 %1
copy /Y          .\hal\peripheral\inc\i2c.h						 %1
copy /Y          .\hal\peripheral\inc\i2c2.h						 %1
copy /Y          .\hal\peripheral\inc\keypad.h						 %1
copy /Y          .\hal\peripheral\inc\keypad_hw.h						 %1
copy /Y          .\hal\peripheral\inc\nli_arb.h						 %1
copy /Y          .\hal\peripheral\inc\pw.h						 %1
copy /Y          .\hal\peripheral\inc\pwm_hw.h						 %1
copy /Y          .\hal\peripheral\inc\pwm_sw.h						 %1
copy /Y          .\hal\peripheral\inc\rtc_hw.h						 %1
copy /Y          .\hal\peripheral\inc\rtc_sw_new.h						 %1
copy /Y          .\hal\peripheral\inc\rwg_sw.h						 %1
copy /Y          .\hal\peripheral\inc\spi.h						 %1
copy /Y          .\hal\peripheral\inc\spi_define.h						 %1
copy /Y          .\hal\peripheral\inc\spi_internal.h						 %1
copy /Y          .\hal\peripheral\inc\spi_slave_hw.h						 %1
copy /Y          .\hal\peripheral\inc\spi_slave_sw.h						 %1
copy /Y          .\hal\peripheral\inc\sw_keypad.h						 %1
copy /Y          .\hal\peripheral\inc\touch_panel.h						 %1
copy /Y          .\hal\peripheral\inc\touch_panel_.h						 %1
copy /Y          .\hal\peripheral\inc\ts_hw.h						 %1
copy /Y          .\hal\peripheral\inc\uart_hw.h						 %1
copy /Y          .\hal\peripheral\inc\uart_internal.h						 %1
copy /Y          .\hal\peripheral\inc\wdt_hw.h						 %1
copy /Y          .\hal\peripheral\inc\wdt_sw.h						 %1
copy /Y          .\hal\sleep_drv\public\inc\rm_public.h						 %1
copy /Y          .\hal\storage\flash\fdm\inc\drvflash.h						 %1
copy /Y          .\hal\storage\flash\fdm\inc\drvflash_ut.h						 %1
copy /Y          .\hal\storage\flash\fdm\inc\nand_fdm.h						 %1
copy /Y          .\hal\storage\flash\fdm\inc\nor_profile.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_cfi_internal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_disk_internal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_mtd_internal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_mtd_pf_dal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_mtd_sf_dal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_mtd_sf_ut.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_mtd_ut.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\flash_sf.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\nand_dal_internal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\nand_dal_version.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\nand_devconfig.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\nand_mtd_fdm50_internal.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\nfi_hw_info.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\sfi_hw.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\snand_hw.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\spi_nand_devconfig.h						 %1
copy /Y          .\hal\storage\flash\mtd\inc\spi_nand_mtd_fdm50_internal.h						 %1
copy /Y          .\hal\storage\mc\inc\msdc_def.h						 %1
copy /Y          .\hal\storage\mc\inc\msdc_reg_adap.h						 %1
copy /Y          .\hal\storage\mc\inc\sd_def.h						 %1
copy /Y          .\hal\storage\mc\inc\sdio_def.h						 %1
copy /Y          .\hal\system\ap_btss\inc\ap_btss.h						 %1
copy /Y          .\hal\system\cache\inc\cache_hw_int.h						 %1
copy /Y          .\hal\system\cache\inc\cache_sw_int.h						 %1
copy /Y          .\hal\system\cache\inc\mmu_int.h						 %1
copy /Y          .\hal\system\cbr\inc\cbr.h						 %1
copy /Y          .\hal\system\cbr\inc\cbr_record_def.h						 %1
copy /Y          .\hal\system\cirq\inc\adie_eint.h						 %1
copy /Y          .\hal\system\cirq\inc\adie_intrctrl.h						 %1
copy /Y          .\hal\system\cirq\inc\adie_intrctrl_mt6261.h						 %1
copy /Y          .\hal\system\cirq\inc\cirq_internal.h						 %1
copy /Y          .\hal\system\cirq\inc\eint_internal.h						 %1
copy /Y          .\hal\system\cirq\inc\intrctrl_mt6261.h						 %1
copy /Y          .\hal\system\cirq\inc\intrctrl_mt6261_sw_handle.h						 %1
copy /Y          .\hal\system\cirq\inc\intrctrl_sw_handle.h						 %1
copy /Y          .\hal\system\compression\inc\viva.h						 %1
copy /Y          .\hal\system\counter\inc\us_timer.h						 %1
copy /Y          .\hal\system\csci\inc\ap_csci_dynamic.h						 %1
copy /Y          .\hal\system\csci\inc\csci_struct.h						 %1
copy /Y          .\hal\system\dcm\inc\dcm.h						 %1
copy /Y          .\hal\system\dcmgr\inc\dcmgr.h						 %1
copy /Y          .\hal\system\dcmgr\inc\dcmgr_comp.h						 %1
copy /Y          .\hal\system\dma\inc\dma_config_mt6261.h						 %1
copy /Y          .\hal\system\dma\inc\dma_hw.h						 %1
copy /Y          .\hal\system\dma\inc\dma_hw_v2.h						 %1
copy /Y          .\hal\system\dma\inc\dma_sw.h						 %1
copy /Y          .\hal\system\dma\inc\dma_sw_v2.h						 %1
copy /Y          .\hal\system\dp\inc\page.h						 %1
copy /Y          .\hal\system\emi\inc\emi_hw_internal.h						 %1
copy /Y          .\hal\system\emi\inc\emi_sw_internal.h						 %1
copy /Y          .\hal\system\excep_hdlr\inc\excep_hdlr.h						 %1
copy /Y          .\hal\system\fota\inc\fue.h						 %1
copy /Y          .\hal\system\fota\inc\fue_err.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_anti_clone.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_arm_bl_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_binary_location.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_bl_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_cbr_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_cbr_record_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_cmem_id_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_cmem_nor_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_emi_list.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_emmc_booting_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_epp_param.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_error.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_file_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_flash_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_fota_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_maui_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_maui_sec.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_mba_info.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_parser.h						 %1
copy /Y          .\hal\system\gfh\public\br_gfh_secure_ro_info.h						 %1
copy /Y          .\hal\system\gfh\public\gfh_defs.h						 %1
copy /Y          .\hal\system\gfh\public\maui_gfh_body.h						 %1
copy /Y          .\hal\system\init\inc\boot_cert_pattern.h						 %1
copy /Y          .\hal\system\init\inc\bootarm.h						 %1
copy /Y          .\hal\system\init\inc\config_hw.h						 %1
copy /Y          .\hal\system\init\inc\feature_def.h						 %1
copy /Y          .\hal\system\init\inc\init.h						 %1
copy /Y          .\hal\system\init\inc\init_trc_api.h						 %1
copy /Y          .\hal\system\init\inc\nfb_loader.h						 %1
copy /Y          .\hal\system\init\inc\system_trc.h						 %1
copy /Y          .\hal\system\init\inc\third_rom.h						 %1
copy /Y          .\hal\system\ipc\inc\ccci.h						 %1
copy /Y          .\hal\system\pdn\inc\drvpdn.h						 %1
copy /Y          .\hal\system\pdn\inc\pdn_def.h						 %1
copy /Y          .\hal\system\pdn\inc\pdn_def_mt6261_series.h						 %1
copy /Y          .\hal\system\pdn\inc\pdn_hw_mt6261_series.h						 %1
copy /Y          .\hal\system\pdn\inc\pdn_hw_series.h						 %1
copy /Y          .\hal\system\pll\inc\pll.h						 %1
copy /Y          .\hal\system\profile\inc\br_time_stamp.h						 %1
copy /Y          .\hal\system\profile\inc\br_time_stamp_cb.h						 %1
copy /Y          .\hal\system\profile\inc\maui_time_stamp_id.h						 %1
copy /Y          .\hal\system\profile\inc\maui_time_stamp_util.h						 %1
copy /Y          .\hal\system\regbase\inc\reg_base.h						 %1
copy /Y          .\hal\system\regbase\inc\reg_base_mt6261.h						 %1
copy /Y          .\hal\system\region\inc\init_memory_stack_int.h						 %1
copy /Y          .\hal\video\common\include\media_provider_mem_usage_internal.h						 %1
copy /Y          .\hal\video\common\include\sw_video_resizer.h						 %1
copy /Y          .\hal\video\common\include\vcodec_v2_trc.h						 %1
copy /Y          .\hal\video\common\include\vfile_main.h						 %1
copy /Y          .\hal\video\common\include\video_buffer_management_v2.h						 %1
copy /Y          .\hal\video\common\include\video_codec_utility_v2.h						 %1
copy /Y          .\hal\video\common\include\video_comm_v2.h						 %1
copy /Y          .\hal\video\common\include\video_dbg_v2.h						 %1
copy /Y          .\hal\video\common\include\video_muxer_if_v2.h						 %1
copy /Y          .\hal\video\common\include\video_recorder_source_component_if_v2.h						 %1
copy /Y          .\hal\video\common\include\video_subtitle_decoder_custom_if.h						 %1
copy /Y          .\hal\video\common\include\video_subtitle_decoder_if.h						 %1
copy /Y          .\hal\video\common\include\video_types_v2.h						 %1
copy /Y          .\hal\video\demuxer\mp4_parser\inc\mp4_common.h						 %1
copy /Y          .\hal\video\demuxer\mp4_parser\inc\mp4_parser.h						 %1
copy /Y          .\hal\video\demuxer\provider\inc\mp4_provider.h						 %1
copy /Y          .\hal\video\demuxer\provider\inc\source_provider_if.h						 %1
copy /Y          .\hal\video\fluency\include\swdecodeframeheader.h						 %1
copy /Y          .\hal\video\fluency\include\video_fluency_if.h						 %1
copy /Y          .\hal\video\fluency\include\video_fluency_utility.h						 %1
copy /Y          .\hal\video\mpl\inc\media_player.h						 %1
copy /Y          .\hal\video\mpl\inc\media_session.h						 %1
copy /Y          .\hal\video\mpl\inc\mpl_session_mem.h						 %1
copy /Y          .\hal\video\mpl\inc\mpl_utility.h						 %1
copy /Y          .\hal\video\renderer\include\video_renderer_task_thread_pool.h						 %1
copy /Y          .\hal\video_codec\interface\inc\h264swdeccustomize.h						 %1
copy /Y          .\hal\video_codec\interface\inc\mp4swdeccustomize.h						 %1
copy /Y          .\hal\video_codec\interface\inc\mp4swencdefs.h						 %1
copy /Y          .\hal\video_codec\interface\inc\mp4swencmem.h						 %1
copy /Y          .\hal\video_codec\interface\inc\vcodec_if.h						 %1
copy /Y          .\hal\video_codec\interface\inc\vp8swdeccustomize.h						 %1
copy /Y          .\hal\video_codec\video_codec_sec\sw_mp4_dec\include\mp4dec_basetype.h						 %1
copy /Y          .\inc\l1cal.h						 %1
copy /Y          .\inet_ps\abm\include\abm_def.h						 %1
copy /Y          .\inet_ps\abm\include\abm_feature.h						 %1
copy /Y          .\inet_ps\abm\include\abm_main.h						 %1
copy /Y          .\inet_ps\abm\include\abm_trc.h						 %1
copy /Y          .\inet_ps\abm\include\abm_util.h						 %1
copy /Y          .\inet_ps\interfaces\enum\abm_soc_enums.h						 %1
copy /Y          .\inet_ps\interfaces\local_inc\abm2soc_struct.h						 %1
copy /Y          .\inet_ps\interfaces\local_inc\app2cbm_struct.h						 %1
copy /Y          .\inet_ps\interfaces\local_inc\app2soc_struct.h						 %1
copy /Y          .\inet_ps\interfaces\local_inc\mmi2abm_struct.h						 %1
copy /Y          .\inet_ps\interfaces\local_inc\mmi2ntpd_struct.h						 %1
copy /Y          .\inet_ps\mthl\include\mthl.h						 %1
copy /Y          .\inet_ps\ntpd\include\list.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntp_fp.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntp_lists.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntp_types.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntpd_comm.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntpd_mem.h						 %1
copy /Y          .\inet_ps\ntpd\include\ntpd_trc.h						 %1
copy /Y          .\inet_ps\ntpd\include\recvbuff.h						 %1
copy /Y          .\inet_ps\tcpip\include\if.h						 %1
copy /Y          .\inet_ps\tcpip\include\in.h						 %1
copy /Y          .\inet_ps\tcpip\include\in_pcb.h						 %1
copy /Y          .\inet_ps\tcpip\include\ip.h						 %1
copy /Y          .\inet_ps\tcpip\include\mbuf.h						 %1
copy /Y          .\inet_ps\tcpip\include\route.h						 %1
copy /Y          .\inet_ps\tcpip\include\tcp.h						 %1
copy /Y          .\inet_ps\tcpip\include\tcpip_config.h						 %1
copy /Y          .\init\include\info.h						 %1
copy /Y          .\init\include\task_main_func.h						 %1
copy /Y          .\interface\ata\ata_external.h						 %1
copy /Y          .\interface\bcm\bcm_sap.h						 %1
copy /Y          .\interface\bcm\bcm_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_a2dp_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_avrcp_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_bm_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_gap_message.h						 %1
copy /Y          .\interface\bt\bluetooth_gap_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_gattc_message.h						 %1
copy /Y          .\interface\bt\bluetooth_gattc_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_gatts_message.h						 %1
copy /Y          .\interface\bt\bluetooth_gatts_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_goepc_message.h						 %1
copy /Y          .\interface\bt\bluetooth_goeps_message.h						 %1
copy /Y          .\interface\bt\bluetooth_pbap_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_pbapc_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_sap.h						 %1
copy /Y          .\interface\bt\bluetooth_sdp_message.h						 %1
copy /Y          .\interface\bt\bluetooth_sdp_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_simap_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_spp_message.h						 %1
copy /Y          .\interface\bt\bluetooth_spp_struct.h						 %1
copy /Y          .\interface\bt\bluetooth_struct.h						 %1
copy /Y          .\interface\bt\bt_api.h						 %1
copy /Y          .\interface\bt\bt_config.h						 %1
copy /Y          .\interface\bt\bt_dm_struct.h						 %1
copy /Y          .\interface\bt\bt_message.h						 %1
copy /Y          .\interface\bt\bt_mmi.h						 %1
copy /Y          .\interface\bt\bt_types.h						 %1
copy /Y          .\interface\bt\btostypes.h						 %1
copy /Y          .\interface\bt\btostypes_int.h						 %1
copy /Y          .\interface\common\global_def.h						 %1
copy /Y          .\interface\fota\fota_error.h						 %1
copy /Y          .\interface\fs\fat_fs.h						 %1
copy /Y          .\interface\fs\fs_errcode.h						 %1
copy /Y          .\interface\fs\fs_func.h						 %1
copy /Y          .\interface\fs\fs_gprot.h						 %1
copy /Y          .\interface\fs\fs_sap.h						 %1
copy /Y          .\interface\fs\fs_task.h						 %1
copy /Y          .\interface\fs\fs_type.h						 %1
copy /Y          .\interface\fs\fsal.h						 %1
copy /Y          .\interface\gps\gps2lcsp_enum.h						 %1
copy /Y          .\interface\gps\gps2lcsp_struct.h						 %1
copy /Y          .\interface\gps\gps_meta_struct.h						 %1
copy /Y          .\interface\gps\gps_sap.h						 %1
copy /Y          .\interface\gps\gps_struct.h						 %1
copy /Y          .\interface\gps\mnl_sap.h						 %1
copy /Y          .\interface\hal\audio\audio_enum.h						 %1
copy /Y          .\interface\hal\audio\l1audio.h						 %1
copy /Y          .\interface\hal\audio\l1audio_sph_srv_sap.h						 %1
copy /Y          .\interface\hal\bluetooth\bt_feature.h						 %1
copy /Y          .\interface\hal\bluetooth\btdrv_config.h						 %1
copy /Y          .\interface\hal\bluetooth\btdrv_types.h						 %1
copy /Y          .\interface\hal\bluetooth\xastatus.h						 %1
copy /Y          .\interface\hal\bluetooth\xatypes.h						 %1
copy /Y          .\interface\hal\camera\cal_api.h						 %1
copy /Y          .\interface\hal\camera\cal_comm_def.h						 %1
copy /Y          .\interface\hal\camera\cal_feature_option.h						 %1
copy /Y          .\interface\hal\camera\cal_mem_def.h						 %1
copy /Y          .\interface\hal\camera\cal_sap.h						 %1
copy /Y          .\interface\hal\camera\cct_comm_def.h						 %1
copy /Y          .\interface\hal\camera\isp_comm_def.h						 %1
copy /Y          .\interface\hal\camera\isp_mem.h						 %1
copy /Y          .\interface\hal\camera\lens_comm_def.h						 %1
copy /Y          .\interface\hal\camera\mm_comm_def.h						 %1
copy /Y          .\interface\hal\camera\sensor_comm_def.h						 %1
copy /Y          .\interface\hal\cipher\include\che_api.h						 %1
copy /Y          .\interface\hal\cipher\include\che_trick.h						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_otg_drv.h						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_usb_drv.h						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_usb_hcd.h						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\otg_if.h						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\usbvideo_if.h						 %1
copy /Y          .\interface\hal\display\common\display_io.h						 %1
copy /Y          .\interface\hal\display\common\lcd_em.h						 %1
copy /Y          .\interface\hal\display\common\lcd_if_common.h						 %1
copy /Y          .\interface\hal\display\common\owfimage.h						 %1
copy /Y          .\interface\hal\display\common\owftypes.h						 %1
copy /Y          .\interface\hal\display\ddv1\lcd_if.h						 %1
copy /Y          .\interface\hal\display\exception\lcd_exception_api.h						 %1
copy /Y          .\interface\hal\display\flatten\flatten_api.h						 %1
copy /Y          .\interface\hal\display\lcd_if_manager.h						 %1
copy /Y          .\interface\hal\display\lcd_power_mgr.h						 %1
copy /Y          .\interface\hal\display\lcm_if\lcm_if.h						 %1
copy /Y          .\interface\hal\display\wfc\wfc.h						 %1
copy /Y          .\interface\hal\display\wfc\wfcext.h						 %1
copy /Y          .\interface\hal\display\wfc\wfcplatform.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_color.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_display.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_g2d.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_gif.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_jpeg.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_kbd.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_mdp.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_mmsysmisc.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_opengles.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_png.h						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_usb.h						 %1
copy /Y          .\interface\hal\fmr\fmr_common_api.h						 %1
copy /Y          .\interface\hal\fmr\fmr_rds_api.h						 %1
copy /Y          .\interface\hal\graphics\app_zlib.h						 %1
copy /Y          .\interface\hal\graphics\bfc_enum.h						 %1
copy /Y          .\interface\hal\graphics\color_api.h						 %1
copy /Y          .\interface\hal\graphics\color_enum.h						 %1
copy /Y          .\interface\hal\graphics\color_structure.h						 %1
copy /Y          .\interface\hal\graphics\drv_gfx_codec_limitation.h						 %1
copy /Y          .\interface\hal\graphics\drv_gfx_stack_switch_manager.h						 %1
copy /Y          .\interface\hal\graphics\g2d_bitblt_api.h						 %1
copy /Y          .\interface\hal\graphics\g2d_common_api.h						 %1
copy /Y          .\interface\hal\graphics\g2d_enum.h						 %1
copy /Y          .\interface\hal\graphics\g2d_font_api.h						 %1
copy /Y          .\interface\hal\graphics\g2d_lt_api.h						 %1
copy /Y          .\interface\hal\graphics\g2d_rectfill_api.h						 %1
copy /Y          .\interface\hal\graphics\gfx_cache_switch_behavior_enum.h						 %1
copy /Y          .\interface\hal\graphics\ipp_enum.h						 %1
copy /Y          .\interface\hal\graphics\iul_color_convert.h						 %1
copy /Y          .\interface\hal\graphics\iul_common_struct.h						 %1
copy /Y          .\interface\hal\graphics\iul_csc_macros.h						 %1
copy /Y          .\interface\hal\graphics\iul_csc_y2r.h						 %1
copy /Y          .\interface\hal\graphics\iul_x_math.h						 %1
copy /Y          .\interface\hal\graphics\ivlw_common.h						 %1
copy /Y          .\interface\hal\graphics\ivlw_decoder.h						 %1
copy /Y          .\interface\hal\graphics\ivlw_encoder.h						 %1
copy /Y          .\interface\hal\graphics\jaia_api.h						 %1
copy /Y          .\interface\hal\graphics\jaia_enum.h						 %1
copy /Y          .\interface\hal\graphics\jaia_mem.h						 %1
copy /Y          .\interface\hal\graphics\jaia_structure.h						 %1
copy /Y          .\interface\hal\graphics\jpeg_decode_api.h						 %1
copy /Y          .\interface\hal\graphics\jpeg_encode_api.h						 %1
copy /Y          .\interface\hal\graphics\jpeg_enum.h						 %1
copy /Y          .\interface\hal\graphics\jpeg_mem.h						 %1
copy /Y          .\interface\hal\graphics\lwp_decoder.h						 %1
copy /Y          .\interface\hal\graphics\lzmadec.h						 %1
copy /Y          .\interface\hal\graphics\lzmatypes.h						 %1
copy /Y          .\interface\hal\graphics\mav_common.h						 %1
copy /Y          .\interface\hal\graphics\mav_decoder.h						 %1
copy /Y          .\interface\hal\graphics\mav_encoder.h						 %1
copy /Y          .\interface\hal\graphics\mav_mem.h						 %1
copy /Y          .\interface\hal\graphics\png_decode_api.h						 %1
copy /Y          .\interface\hal\graphics\png_decode_enum.h						 %1
copy /Y          .\interface\hal\graphics\png_memory_usage.h						 %1
copy /Y          .\interface\hal\graphics\resizer_enum.h						 %1
copy /Y          .\interface\hal\graphics\rgb_rotator_api.h						 %1
copy /Y          .\interface\hal\graphics\rotator_enum.h						 %1
copy /Y          .\interface\hal\graphics\simple_memory_manager.h						 %1
copy /Y          .\interface\hal\graphics\yuv_rotator_api.h						 %1
copy /Y          .\interface\hal\l1\hal_l1_sap.h						 %1
copy /Y          .\interface\hal\mdp\idp_mem_def.h						 %1
copy /Y          .\interface\hal\mdp\idp_val.h						 %1
copy /Y          .\interface\hal\mdp\img_common_enum.h						 %1
copy /Y          .\interface\hal\mm_comm\mm_power_ctrl.h						 %1
copy /Y          .\interface\hal\mm_comm\mm_pwrmgr_def_mt6250.h						 %1
copy /Y          .\interface\hal\mm_comm\mmsys_pq_path.h						 %1
copy /Y          .\interface\hal\mm_comm\mmsys_pwrmgr.h						 %1
copy /Y          .\interface\hal\mm_comm\mmsys_pwrmgr_def.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\egl.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\egladapt.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\egldefinition.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\eglext.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\eglplatform.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\eglprototypes.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\egl\fbdev_window.h						 %1
copy /Y          .\interface\hal\opengles\mali400mp\khronos\khr\khrplatform.h						 %1
copy /Y          .\interface\hal\peripheral\accessory_sw.h						 %1
copy /Y          .\interface\hal\peripheral\adc.h						 %1
copy /Y          .\interface\hal\peripheral\adc_cali.h						 %1
copy /Y          .\interface\hal\peripheral\bmd.h						 %1
copy /Y          .\interface\hal\peripheral\bmt.h						 %1
copy /Y          .\interface\hal\peripheral\dcl.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_adc.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_aux.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_bmt.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_chr_det.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_common.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_eint.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_f32k_clk.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_gpio.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_gpt.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_i2c.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_i2c_owner.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_irda.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_msdc.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_pfc.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_pmu.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_pw.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_pwm.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_pxs.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_rtc.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_sim.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_spi_slave.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_sts.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_uart.h						 %1
copy /Y          .\interface\hal\peripheral\dcl_wdt.h						 %1
copy /Y          .\interface\hal\peripheral\dclh_kbd.h						 %1
copy /Y          .\interface\hal\peripheral\dcls_kbd.h						 %1
copy /Y          .\interface\hal\peripheral\drv_comm.h						 %1
copy /Y          .\interface\hal\peripheral\drv_hisr.h						 %1
copy /Y          .\interface\hal\peripheral\drv_sap.h						 %1
copy /Y          .\interface\hal\peripheral\drvsignals.h						 %1
copy /Y          .\interface\hal\peripheral\hif_hal.h						 %1
copy /Y          .\interface\hal\peripheral\kbd_table.h						 %1
copy /Y          .\interface\hal\peripheral\keypad_sw.h						 %1
copy /Y          .\interface\hal\peripheral\lpwr.h						 %1
copy /Y          .\interface\hal\peripheral\motion_sensor.h						 %1
copy /Y          .\interface\hal\peripheral\pmic6318_sw.h						 %1
copy /Y          .\interface\hal\peripheral\spi_hal.h						 %1
copy /Y          .\interface\hal\peripheral\uart_sw.h						 %1
copy /Y          .\interface\hal\postproc\asd_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\autocap_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\fd_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\hdr_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\mav_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\mavcap_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\pano_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\pp_comm_def.h						 %1
copy /Y          .\interface\hal\postproc\pp_feature_def.h						 %1
copy /Y          .\interface\hal\postproc\pp_mem_def.h						 %1
copy /Y          .\interface\hal\postproc\sd_comm_def.h						 %1
copy /Y          .\interface\hal\security\certman_sap.h						 %1
copy /Y          .\interface\hal\sleep_drv\l1sm_public.h						 %1
copy /Y          .\interface\hal\sleep_drv\ostd_public.h						 %1
copy /Y          .\interface\hal\storage\flash_cfi.h						 %1
copy /Y          .\interface\hal\storage\flash_disk.h						 %1
copy /Y          .\interface\hal\storage\flash_mtd.h						 %1
copy /Y          .\interface\hal\storage\flash_sfi_release.h						 %1
copy /Y          .\interface\hal\storage\mc\msdc_api.h						 %1
copy /Y          .\interface\hal\storage\nand_dal.h						 %1
copy /Y          .\interface\hal\storage\nand_mtd.h						 %1
copy /Y          .\interface\hal\system\cache_hw.h						 %1
copy /Y          .\interface\hal\system\cache_sw.h						 %1
copy /Y          .\interface\hal\system\code_decompression.h						 %1
copy /Y          .\interface\hal\system\cp15.h						 %1
copy /Y          .\interface\hal\system\csci.h						 %1
copy /Y          .\interface\hal\system\eint.h						 %1
copy /Y          .\interface\hal\system\emi_hw.h						 %1
copy /Y          .\interface\hal\system\emi_sw.h						 %1
copy /Y          .\interface\hal\system\ex_public.h						 %1
copy /Y          .\interface\hal\system\ftl.h						 %1
copy /Y          .\interface\hal\system\init_memory_stack.h						 %1
copy /Y          .\interface\hal\system\init_public.h						 %1
copy /Y          .\interface\hal\system\intrctrl.h						 %1
copy /Y          .\interface\hal\system\isrentry.h						 %1
copy /Y          .\interface\hal\system\mba_resource.h						 %1
copy /Y          .\interface\hal\system\mmu.h						 %1
copy /Y          .\interface\hal\system\sync_data.h						 %1
copy /Y          .\interface\hal\video\custom_video_enc_if.h						 %1
copy /Y          .\interface\hal\video\med_status.h						 %1
copy /Y          .\interface\hal\video\media_provider_mem_usage.h						 %1
copy /Y          .\interface\hal\video\media_session_mem_usage.h						 %1
copy /Y          .\interface\hal\video\mpl_clipper.h						 %1
copy /Y          .\interface\hal\video\mpl_common.h						 %1
copy /Y          .\interface\hal\video\mpl_omx_core.h						 %1
copy /Y          .\interface\hal\video\mpl_parser.h						 %1
copy /Y          .\interface\hal\video\mpl_player.h						 %1
copy /Y          .\interface\hal\video\mpl_recorder.h						 %1
copy /Y          .\interface\hal\video\mpl_sap.h						 %1
copy /Y          .\interface\hal\video\subtitlefont_if.h						 %1
copy /Y          .\interface\hal\video\val_if.h						 %1
copy /Y          .\interface\hal\video\val_recorder_if.h						 %1
copy /Y          .\interface\hal\video\vcodec_sap.h						 %1
copy /Y          .\interface\hal\video\vcodec_v2_sap.h						 %1
copy /Y          .\interface\hal\video\vfile_sap.h						 %1
copy /Y          .\interface\hal\video\vsrc_sap.h						 %1
copy /Y          .\interface\hal\video_codec\hal_custom_video_codec_if.h						 %1
copy /Y          .\interface\hwdrv\melody.h						 %1
copy /Y          .\interface\hwdrv\rtc_sw.h						 %1
copy /Y          .\interface\hwdrv\sccb.h						 %1
copy /Y          .\interface\hwdrv\sdio_sw.h						 %1
copy /Y          .\interface\inet_ps\abm_api.h						 %1
copy /Y          .\interface\inet_ps\cardav_sap.h						 %1
copy /Y          .\interface\inet_ps\cbm_api.h						 %1
copy /Y          .\interface\inet_ps\cbm_consts.h						 %1
copy /Y          .\interface\inet_ps\dhcpd_sap.h						 %1
copy /Y          .\interface\inet_ps\dm_sap.h						 %1
copy /Y          .\interface\inet_ps\email_sap.h						 %1
copy /Y          .\interface\inet_ps\emlst_sap.h						 %1
copy /Y          .\interface\inet_ps\imps_sap.h						 %1
copy /Y          .\interface\inet_ps\iperf_sap.h						 %1
copy /Y          .\interface\inet_ps\mthl_struct.h						 %1
copy /Y          .\interface\inet_ps\ntpd_sap.h						 %1
copy /Y          .\interface\inet_ps\rtsp_sap.h						 %1
copy /Y          .\interface\inet_ps\saf_sap.h						 %1
copy /Y          .\interface\inet_ps\sip_sap.h						 %1
copy /Y          .\interface\inet_ps\soc_api.h						 %1
copy /Y          .\interface\inet_ps\soc_consts.h						 %1
copy /Y          .\interface\inet_ps\syncml_sap.h						 %1
copy /Y          .\interface\inet_ps\xdm_sap.h						 %1
copy /Y          .\interface\l1interface\external\l1_kal.h						 %1
copy /Y          .\interface\l1interface\external\l1_types_public.h						 %1
copy /Y          .\interface\l1interface\external\mph_types.h						 %1
copy /Y          .\interface\l1interface\internal\l1_fh_interface.h						 %1
copy /Y          .\interface\l1interface\internal\l1_interface.h						 %1
copy /Y          .\interface\l1interface\sap\ft_sap.h						 %1
copy /Y          .\interface\l1interface\sap\l1_ext_sap.h						 %1
copy /Y          .\interface\l1interface\sap\l1_sap.h						 %1
copy /Y          .\interface\l1interface\sap\l1hisr_sap.h						 %1
copy /Y          .\interface\media\custom_vrender.h						 %1
copy /Y          .\interface\media\hal\med_aud_hal_struct.h						 %1
copy /Y          .\interface\media\hal\med_hal_sap.h						 %1
copy /Y          .\interface\media\med_sap.h						 %1
copy /Y          .\interface\media\med_struct.h						 %1
copy /Y          .\interface\media\med_v_sap.h						 %1
copy /Y          .\interface\media\med_v_struct.h						 %1
copy /Y          .\interface\media\video\med_vid_clip_struct.h						 %1
copy /Y          .\interface\meta\ft_msg.h						 %1
copy /Y          .\interface\meta\ft_msg_audio.h						 %1
copy /Y          .\interface\meta\ft_msg_bt.h						 %1
copy /Y          .\interface\meta\ft_msg_cmmb.h						 %1
copy /Y          .\interface\meta\ft_msg_common.h						 %1
copy /Y          .\interface\meta\ft_msg_fm.h						 %1
copy /Y          .\interface\meta\ft_msg_fta.h						 %1
copy /Y          .\interface\meta\ft_msg_ftc.h						 %1
copy /Y          .\interface\meta\ft_msg_gps.h						 %1
copy /Y          .\interface\meta\ft_msg_l1rf.h						 %1
copy /Y          .\interface\meta\ft_msg_matv.h						 %1
copy /Y          .\interface\meta\ft_msg_misc.h						 %1
copy /Y          .\interface\meta\ft_msg_misc_ex.h						 %1
copy /Y          .\interface\meta\ft_msg_nfc.h						 %1
copy /Y          .\interface\meta\ft_msg_tdmb.h						 %1
copy /Y          .\interface\meta\ft_msg_ul1rf.h						 %1
copy /Y          .\interface\meta\ft_msg_util.h						 %1
copy /Y          .\interface\meta\ft_msg_wifi.h						 %1
copy /Y          .\interface\meta\ft_public.h						 %1
copy /Y          .\interface\meta\ftc_msg.h						 %1
copy /Y          .\interface\meta\l1tst_public.h						 %1
copy /Y          .\interface\middleware\ircomm_sap.h						 %1
copy /Y          .\interface\middleware\irda_sap.h						 %1
copy /Y          .\interface\middleware\mexe_sap.h						 %1
copy /Y          .\interface\middleware\nvram_config.h						 %1
copy /Y          .\interface\middleware\nvram_editor_data_item.h						 %1
copy /Y          .\interface\misc_ps\obex_sap.h						 %1
copy /Y          .\interface\misc_ps\udx_sap.h						 %1
copy /Y          .\interface\mmi\drmt_sap.h						 %1
copy /Y          .\interface\mmi\mmi_um_sap.h						 %1
copy /Y          .\interface\mmi\mmiapi_sap.h						 %1
copy /Y          .\interface\nfc\nfc_app_sap.h						 %1
copy /Y          .\interface\nfc\nfc_reader_sap.h						 %1
copy /Y          .\interface\nfc\nfc_sap.h						 %1
copy /Y          .\interface\nvram\nvram_data_items.h						 %1
copy /Y          .\interface\nvram\nvram_defs.h						 %1
copy /Y          .\interface\nvram\nvram_enums.h						 %1
copy /Y          .\interface\nvram\nvram_interface.h						 %1
copy /Y          .\interface\nvram\nvram_sap.h						 %1
copy /Y          .\interface\nvram\nvram_struct.h						 %1
copy /Y          .\interface\os\sysservice_sap.h						 %1
copy /Y          .\interface\ps\enum\csmcc_common_enums.h						 %1
copy /Y          .\interface\ps\enum\csmcc_enums.h						 %1
copy /Y          .\interface\ps\enum\mmi_l3_enums.h						 %1
copy /Y          .\interface\ps\enum\ps_em_enum.h						 %1
copy /Y          .\interface\ps\enum\ps_public_enum.h						 %1
copy /Y          .\interface\ps\enum\sim_public_enum.h						 %1
copy /Y          .\interface\ps\include\cmux_vp_num.h						 %1
copy /Y          .\interface\ps\include\device.h						 %1
copy /Y          .\interface\ps\include\ems.h						 %1
copy /Y          .\interface\ps\include\flc2_config.h						 %1
copy /Y          .\interface\ps\include\flc2_ent_functions.h						 %1
copy /Y          .\interface\ps\include\flc2_mem_mngr_config.h						 %1
copy /Y          .\interface\ps\include\flc2_tunable_para.h						 %1
copy /Y          .\interface\ps\include\flc_api.h						 %1
copy /Y          .\interface\ps\include\ps_public_utility.h						 %1
copy /Y          .\interface\ps\include\sim_public_api.h						 %1
copy /Y          .\interface\ps\include\smslib_def.h						 %1
copy /Y          .\interface\ps\include\tcm_api.h						 %1
copy /Y          .\interface\ps\local_inc\em_public_struct.h						 %1
copy /Y          .\interface\ps\local_inc\l4c2abm_struct.h						 %1
copy /Y          .\interface\ps\local_inc\mcd_l3_inc_gprs_struct.h						 %1
copy /Y          .\interface\ps\local_inc\mcd_l4_common.h						 %1
copy /Y          .\interface\ps\local_inc\nbr_public_struct.h						 %1
copy /Y          .\interface\ps\local_inc\ps_public_struct.h						 %1
copy /Y          .\interface\ps\local_inc\rmmi_struct.h						 %1
copy /Y          .\interface\ps\local_inc\sim_public_struct.h						 %1
copy /Y          .\interface\ps\local_inc\soc2tcpip_struct.h						 %1
copy /Y          .\interface\ps\sap\abm_sap.h						 %1
copy /Y          .\interface\ps\sap\dhcp_sap.h						 %1
copy /Y          .\interface\ps\sap\mmi_sap.h						 %1
copy /Y          .\interface\ps\sap\ps_public_l4_sap.h						 %1
copy /Y          .\interface\ps\sap\sim_public_sap.h						 %1
copy /Y          .\interface\ps\sap\soc_sap.h						 %1
copy /Y          .\interface\ps\sap\tcpip_sap.h						 %1
copy /Y          .\interface\security\certmanmmi_sap.h						 %1
copy /Y          .\interface\security\tls_sap.h						 %1
copy /Y          .\interface\wap\bam_sap.h						 %1
copy /Y          .\interface\wap\browser_sap.h						 %1
copy /Y          .\interface\wap\das_sap.h						 %1
copy /Y          .\interface\wap\mma_sap.h						 %1
copy /Y          .\interface\wap\mmc_sap.h						 %1
copy /Y          .\interface\wap\mms_adp_sap.h						 %1
copy /Y          .\interface\wap\mms_sap.h						 %1
copy /Y          .\interface\wap\pmg_sap.h						 %1
copy /Y          .\interface\wap\profile_sap.h						 %1
copy /Y          .\interface\wap\q03c_mms_v01_adp_sap.h						 %1
copy /Y          .\interface\wap\ua_sap.h						 %1
copy /Y          .\interface\wap\wap_adp_sap.h						 %1
copy /Y          .\interface\wap\wap_sap.h						 %1
copy /Y          .\interface\wap\wps_sap.h						 %1
copy /Y          .\interface\wap\wps_struct.h						 %1
copy /Y          .\interface\wifi\hostap_abm_msgs.h						 %1
copy /Y          .\interface\wifi\supc_abm_msgs.h						 %1
copy /Y          .\interface\wifi\supc_sap.h						 %1
copy /Y          .\interface\wifi\wndrv_abm_msg.h						 %1
copy /Y          .\interface\wifi\wndrv_api.h						 %1
copy /Y          .\interface\wifi\wndrv_cal.h						 %1
copy /Y          .\interface\wifi\wndrv_cnst.h						 %1
copy /Y          .\interface\wifi\wndrv_ft_msg.h						 %1
copy /Y          .\interface\wifi\wndrv_ft_types.h						 %1
copy /Y          .\interface\wifi\wndrv_sap.h						 %1
copy /Y          .\interface\wifi\wndrv_supc_msg.h						 %1
copy /Y          .\interface\wifi\wndrv_supc_types.h						 %1
copy /Y          .\interface\wmt\wmt_sap.h						 %1
copy /Y          .\j2me\interface\j2me_sap.h						 %1
copy /Y          .\kal\adaptation\include\app_ltlcom.h						 %1
copy /Y          .\kal\adaptation\include\data_buff_pool.h						 %1
copy /Y          .\kal\adaptation\include\stack_buff_pool.h						 %1
copy /Y          .\kal\adaptation\include\stack_common.h						 %1
copy /Y          .\kal\adaptation\include\stack_internal_macros.h						 %1
copy /Y          .\kal\adaptation\include\stack_ltlcom.h						 %1
copy /Y          .\kal\adaptation\include\stack_types.h						 %1
copy /Y          .\kal\common\include\event_shed.h						 %1
copy /Y          .\kal\common\include\kal_adm.h						 %1
copy /Y          .\kal\common\include\kal_afm.h						 %1
copy /Y          .\kal\common\include\kal_debug_common_defs.h						 %1
copy /Y          .\kal\common\include\kal_error_code.h						 %1
copy /Y          .\kal\common\include\kal_vm.h						 %1
copy /Y          .\kal\common\include\stack_timer.h						 %1
copy /Y          .\kal\include\app_buff_alloc.h						 %1
copy /Y          .\kal\include\clib.h						 %1
copy /Y          .\kal\include\clib_list.h						 %1
copy /Y          .\kal\include\kal_active_module.h						 %1
copy /Y          .\kal\include\kal_common_defs.h						 %1
copy /Y          .\kal\include\kal_debug.h						 %1
copy /Y          .\kal\include\kal_general_types.h						 %1
copy /Y          .\kal\include\kal_internal_api.h						 %1
copy /Y          .\kal\include\kal_non_specific_general_types.h						 %1
copy /Y          .\kal\include\kal_public_api.h						 %1
copy /Y          .\kal\include\kal_public_defs.h						 %1
copy /Y          .\kal\include\kal_release.h						 %1
copy /Y          .\kal\include\kal_trace.h						 %1
copy /Y          .\kal\mlib\include\mlib_dll.h						 %1
copy /Y          .\kal\nucleus\include\kal_debug_nucleus.h						 %1
copy /Y          .\kal\nucleus\include\kal_nucleus.h						 %1
copy /Y          .\kal\nucleus\include\kal_nucleus_common_defs.h						 %1
copy /Y          .\kal\stacklib\include\lcd.h						 %1
copy /Y          .\kal\stacklib\include\lcd_cqueue.h						 %1
copy /Y          .\kal\stacklib\include\lcd_dll.h						 %1
copy /Y          .\kal\stacklib\include\lcd_ip_cqueue.h						 %1
copy /Y          .\kal\stacklib\include\lcd_lqueue.h						 %1
copy /Y          .\kal\stacklib\include\stacklib.h						 %1
copy /Y          .\l1_dm\l1d_ext\l1d_cid.h						 %1
copy /Y          .\l1_dm\l1d_ext\l1d_data.h						 %1
copy /Y          .\l1_dm\l1d_ext\l1d_reg.h						 %1
copy /Y          .\l1_dm\l1d_ext\l1d_rf.h						 %1
copy /Y          .\l1_dm\l1d_ext\m12190.h						 %1
copy /Y          .\l1_dm\l1d_ext\m12193.h						 %1
copy /Y          .\l1_dm\l1d_ext\m12197.h						 %1
copy /Y          .\matv\inc\matvctrl.h						 %1
copy /Y          .\media\audio\include\aud_bt_hfp.h						 %1
copy /Y          .\media\audio\include\aud_daf_parser.h						 %1
copy /Y          .\media\audio\include\aud_defs.h						 %1
copy /Y          .\media\audio\include\aud_id3_parser.h						 %1
copy /Y          .\media\audio\include\aud_input_stream.h						 %1
copy /Y          .\media\audio\include\aud_main.h						 %1
copy /Y          .\media\audio\include\aud_player.h						 %1
copy /Y          .\media\audio\include\aud_player_media.h						 %1
copy /Y          .\media\audio\include\aud_player_mma.h						 %1
copy /Y          .\media\audio\include\aud_player_mp4.h						 %1
copy /Y          .\media\audio\include\aud_recorder.h						 %1
copy /Y          .\media\camera\include\cam_main.h						 %1
copy /Y          .\media\camera\include\cam_v_main.h						 %1
copy /Y          .\media\common\include\bytestream_hw.h						 %1
copy /Y          .\media\common\include\med_api.h						 %1
copy /Y          .\media\common\include\med_appmem_config.h						 %1
copy /Y          .\media\common\include\med_context.h						 %1
copy /Y          .\media\common\include\med_global.h						 %1
copy /Y          .\media\common\include\med_main.h						 %1
copy /Y          .\media\common\include\med_mem.h						 %1
copy /Y          .\media\common\include\med_smalloc.h						 %1
copy /Y          .\media\common\include\med_trc.h						 %1
copy /Y          .\media\common\include\med_utility.h						 %1
copy /Y          .\media\common\include\med_v_context.h						 %1
copy /Y          .\media\common\include\med_v_main.h						 %1
copy /Y          .\media\image\include\img_main.h						 %1
copy /Y          .\media\metatag\include\ape_parser.h						 %1
copy /Y          .\media\metatag\include\id3_v1_parser.h						 %1
copy /Y          .\media\metatag\include\id3_v2_parser.h						 %1
copy /Y          .\media\metatag\include\lyrics_parser.h						 %1
copy /Y          .\media\metatag\include\meta_tag_api.h						 %1
copy /Y          .\media\metatag\include\meta_tag_parser.h						 %1
copy /Y          .\media\tvout\include\tvo_main.h						 %1
copy /Y          .\media\video\include\med_vid_clip_context.h						 %1
copy /Y          .\media\video\include\med_vid_clip_features.h						 %1
copy /Y          .\media\video\include\vid_if.h						 %1
copy /Y          .\media\video\include\vid_main.h						 %1
copy /Y          .\media\webcam\include\webcam_main.h						 %1
copy /Y          .\meta\cct\ft_fnc_cct.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_audio.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_aux.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_bt.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_cmmb.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_custom.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_fat.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_fm.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_gps.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_l1rf.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_matv.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_misc.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_misc_ex.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_nfc.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_nvram.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_wcdma.h						 %1
copy /Y          .\meta\ft\inc\ft_fnc_wifi.h						 %1
copy /Y          .\meta\ft\inc\ft_mem.h						 %1
copy /Y          .\meta\ft\inc\ft_private.h						 %1
copy /Y          .\meta\ft\inc\ft_report.h						 %1
copy /Y          .\meta\ftc\ftc_private.h						 %1
copy /Y          .\nucleus\inc\cs_defs.h						 %1
copy /Y          .\nucleus\inc\dm_defs.h						 %1
copy /Y          .\nucleus\inc\ev_defs.h						 %1
copy /Y          .\nucleus\inc\mb_defs.h						 %1
copy /Y          .\nucleus\inc\nucleus.h						 %1
copy /Y          .\nucleus\inc\pi_defs.h						 %1
copy /Y          .\nucleus\inc\pm_defs.h						 %1
copy /Y          .\nucleus\inc\qu_defs.h						 %1
copy /Y          .\nucleus\inc\sm_defs.h						 %1
copy /Y          .\nucleus\inc\tc_defs.h						 %1
copy /Y          .\nucleus\inc\tm_defs.h						 %1
copy /Y          .\nvram\include\nvram_drval_fat.h						 %1
copy /Y          .\nvram\include\nvram_handler_read.h						 %1
copy /Y          .\nvram\include\nvram_handler_reset.h						 %1
copy /Y          .\nvram\include\nvram_handler_startup.h						 %1
copy /Y          .\nvram\include\nvram_handler_tst.h						 %1
copy /Y          .\nvram\include\nvram_handler_write.h						 %1
copy /Y          .\nvram\include\nvram_ilm.h						 %1
copy /Y          .\nvram\include\nvram_internal.h						 %1
copy /Y          .\nvram\include\nvram_io.h						 %1
copy /Y          .\nvram\include\nvram_l1def.h						 %1
copy /Y          .\nvram\include\nvram_ltable.h						 %1
copy /Y          .\nvram\include\nvram_main.h						 %1
copy /Y          .\nvram\include\nvram_msg_handler.h						 %1
copy /Y          .\nvram\include\nvram_multi_folder.h						 %1
copy /Y          .\nvram\include\nvram_pseudo_merge.h						 %1
copy /Y          .\nvram\include\nvram_sec.h						 %1
copy /Y          .\nvram\include\nvram_trc.h						 %1
copy /Y          .\nvram\include\nvram_util.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\depreciation\nvramenum.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\depreciation\nvramgprot.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\depreciation\nvramtype.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\mmi_frm_event_flag_gprot.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\mmi_frm_events_gprot.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\mmi_frm_nvram_gprot.h						 %1
copy /Y          .\plutommi\framework\commonfiles\commoninc\mmi_frm_utility_gprot.h						 %1
copy /Y          .\plutommi\framework\debuglevels\debuglevelinc\debuginitdef_int.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_const.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_datatype.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_features.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_image_alpha_bmp_v2.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_image_alpha_bmp_v2_internal.h						 %1
copy /Y          .\plutommi\framework\gdi\gdiinc\gdi_lcd_config.h						 %1
copy /Y          .\plutommi\framework\interface\mmidatatype.h						 %1
copy /Y          .\plutommi\mmi\inc\custdatares.h						 %1
copy /Y          .\plutommi\mmi\inc\globalconstants.h						 %1
copy /Y          .\plutommi\mmi\inc\globaldefs.h						 %1
copy /Y          .\plutommi\mmi\inc\globalresdef.h						 %1
copy /Y          .\plutommi\mmi\inc\mmi_features.h						 %1
copy /Y          .\plutommi\mmi\inc\mmi_lib_res_range_def.h						 %1
copy /Y          .\plutommi\mmi\inc\mmi_pluto_res_range_def.h						 %1
copy /Y          .\plutommi\mmi\inc\mmi_res_range_def.h						 %1
copy /Y          .\plutommi\mmi\inc\timerevents.h						 %1
copy /Y          .\plutommi\mmi\organizer\organizerinc\alarmslim.h						 %1
copy /Y          .\plutommi\mtkapp\mtkappinc\mmiapi_enum.h						 %1
copy /Y          .\plutommi\service\inc\emailsrvgprot.h						 %1
copy /Y          .\plutommi\service\inc\modeswitchsrvgprot.h						 %1
copy /Y          .\ps\interfaces\enum\l3_inc_enums.h						 %1
copy /Y          .\ps\interfaces\enum\l4c2phb_enums.h						 %1
copy /Y          .\ps\interfaces\enum\mmi_sm_enums.h						 %1
copy /Y          .\ps\interfaces\enum\sim_common_enums.h						 %1
copy /Y          .\ps\interfaces\enum\sim_ps_enum.h						 %1
copy /Y          .\ps\interfaces\enum\smsal_l4c_enum.h						 %1
copy /Y          .\ps\interfaces\include\l4_ps_api.h						 %1
copy /Y          .\ps\interfaces\include\sim_ps_api.h						 %1
copy /Y          .\ps\interfaces\local_inc\as2l4c_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\em_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\l4c2phb_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\l4c2smsal_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\l4c2smu_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\l4c2uem_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\mnsms_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\ps2sat_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\ps2sim_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\sim_ps_struct.h						 %1
copy /Y          .\ps\interfaces\local_inc\smsal_peer_struct.h						 %1
copy /Y          .\ps\interfaces\mcd\include\mcd_l3_inc_struct.h						 %1
copy /Y          .\ps\interfaces\mcd\include\mcd_ps2sat_peer.h						 %1
copy /Y          .\ps\interfaces\sap\cc_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ciss_sap.h						 %1
copy /Y          .\ps\interfaces\sap\cmux_sap.h						 %1
copy /Y          .\ps\interfaces\sap\data_sap.h						 %1
copy /Y          .\ps\interfaces\sap\dt_sap.h						 %1
copy /Y          .\ps\interfaces\sap\em_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ext_modem_sap.h						 %1
copy /Y          .\ps\interfaces\sap\l4_sap.h						 %1
copy /Y          .\ps\interfaces\sap\llc_sap.h						 %1
copy /Y          .\ps\interfaces\sap\mm_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ndis_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ppp_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ratcm_sap.h						 %1
copy /Y          .\ps\interfaces\sap\ratdm_sap.h						 %1
copy /Y          .\ps\interfaces\sap\rr_sap.h						 %1
copy /Y          .\ps\interfaces\sap\sim_ps_sap.h						 %1
copy /Y          .\ps\interfaces\sap\sm_sap.h						 %1
copy /Y          .\ps\interfaces\sap\sms_sap.h						 %1
copy /Y          .\ps\interfaces\sap\sndcp_sap.h						 %1
copy /Y          .\ps\l4\atci\include\rmmi_common_enum.h						 %1
copy /Y          .\ps\l4\atci\include\rmmi_context.h						 %1
copy /Y          .\ps\l4\csm\csm_trc.h						 %1
copy /Y          .\ps\l4\include\csmcc_defs.h						 %1
copy /Y          .\ps\l4\include\csmss_common_enums.h						 %1
copy /Y          .\ps\l4\include\l4_defs.h						 %1
copy /Y          .\ps\l4\include\l4_trc.h						 %1
copy /Y          .\ps\l4\include\l4c_aux_struct.h						 %1
copy /Y          .\ps\l4\include\l4c_common_enum.h						 %1
copy /Y          .\ps\l4\include\l4c_context.h						 %1
copy /Y          .\ps\l4\include\l4c_hz_context.h						 %1
copy /Y          .\ps\l4\include\layer4_context.h						 %1
copy /Y          .\ps\l4\include\smsal_l4c_defs.h						 %1
copy /Y          .\ps\l4\include\smu_common_enums.h						 %1
copy /Y          .\ps\l4\l4c\include\common\l4c_msg_hdlr_defs.h						 %1
copy /Y          .\ps\l4\l4c\include\common\l4c_utility.h						 %1
copy /Y          .\ps\l4\l4c\include\proc\l4c_eq_cmd.h						 %1
copy /Y          .\ps\l4\l4c\include\proc\l4c_eq_msg.h						 %1
copy /Y          .\ps\l4\phb\include\phb_common.h						 %1
copy /Y          .\ps\l4\phb\include\phb_config.h						 %1
copy /Y          .\ps\l4\phb\include\phb_context.h						 %1
copy /Y          .\ps\l4\phb\include\phb_control_block.h						 %1
copy /Y          .\ps\l4\phb\include\phb_data_desc.h						 %1
copy /Y          .\ps\l4\phb\include\phb_data_entry_table.h						 %1
copy /Y          .\ps\l4\phb\include\phb_defs.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_approve.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_delete.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_delete_ln.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_read.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_read_ln.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_sat.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_search.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_startup.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_startup_ln.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_write.h						 %1
copy /Y          .\ps\l4\phb\include\phb_handler_write_ln.h						 %1
copy /Y          .\ps\l4\phb\include\phb_ilm.h						 %1
copy /Y          .\ps\l4\phb\include\phb_main.h						 %1
copy /Y          .\ps\l4\phb\include\phb_name_num_index.h						 %1
copy /Y          .\ps\l4\phb\include\phb_nvram_access.h						 %1
copy /Y          .\ps\l4\phb\include\phb_pindex.h						 %1
copy /Y          .\ps\l4\phb\include\phb_sap.h						 %1
copy /Y          .\ps\l4\phb\include\phb_se.h						 %1
copy /Y          .\ps\l4\phb\include\phb_sim_access.h						 %1
copy /Y          .\ps\l4\phb\include\phb_trc.h						 %1
copy /Y          .\ps\l4\phb\include\phb_utils.h						 %1
copy /Y          .\ps\l4\smsal\include\smsal_defs.h						 %1
copy /Y          .\ps\l4\smsal\include\smsal_structs.h						 %1
copy /Y          .\ps\l4\tcm\include\tcm_common_enums.h						 %1
copy /Y          .\ps\l4\uem\include\uem_at_cmd.h						 %1
copy /Y          .\ps\l4\uem\include\uem_context.h						 %1
copy /Y          .\ps\l4\uem\include\uem_gpio_ctrl.h						 %1
copy /Y          .\ps\l4\uem\include\uem_main.h						 %1
copy /Y          .\ps\l4\uem\include\uem_msg_hdlr.h						 %1
copy /Y          .\ps\l4\uem\include\uem_proc_cmd.h						 %1
copy /Y          .\ps\l4\uem\include\uem_proc_msg.h						 %1
copy /Y          .\ps\l4\uem\include\uem_trc.h						 %1
copy /Y          .\ps\l4\uem\include\uem_utility.h						 %1
copy /Y          .\ps\sim2\include\sim_trc.h						 %1
copy /Y          .\security\sds\sds_type.h						 %1
copy /Y          .\ssf\inc\ssf_rominfo.h						 %1
copy /Y          .\ssf\inc\ssf_rominfo_type.h						 %1
copy /Y          .\sst\include\ex_item.h						 %1
copy /Y          .\sst\include\sst_concurrent_utility.h						 %1
copy /Y          .\sst\include\sst_init.h						 %1
copy /Y          .\sst\include\sst_intrctrl.h						 %1
copy /Y          .\sst\include\sst_secure.h						 %1
copy /Y          .\sst\include\sst_sla.h						 %1
copy /Y          .\sst\include\swtr.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\abm_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\bcm_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\bmt_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\csm_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\drv_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\fmr_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\fs_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\gps_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\l1audio_sph_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\l1sp_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\l4_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\med_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\ntpd_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\nvram_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\phb_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\sim_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\system_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\uem_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\usb_trc_gen.h						 %1
copy /Y          .\tst\database_classb\pstrace_db\vcodec_v2_trc_gen.h						 %1
copy /Y          .\tst\include\dcxo_div_trace1.h						 %1
copy /Y          .\tst\include\gv.h						 %1
copy /Y          .\tst\include\l1audio_trace.h						 %1
copy /Y          .\tst\include\l1c2_trace.h						 %1
copy /Y          .\tst\include\l1c3_trace.h						 %1
copy /Y          .\tst\include\l1c4_trace.h						 %1
copy /Y          .\tst\include\l1c5_trace.h						 %1
copy /Y          .\tst\include\l1c_csd_trace.h						 %1
copy /Y          .\tst\include\l1c_egprs_trace.h						 %1
copy /Y          .\tst\include\l1c_trace.h						 %1
copy /Y          .\tst\include\l1d2_trace.h						 %1
copy /Y          .\tst\include\l1d3_trace.h						 %1
copy /Y          .\tst\include\l1d_edge_trace.h						 %1
copy /Y          .\tst\include\l1d_trace.h						 %1
copy /Y          .\tst\include\l1i_amr_trace.h						 %1
copy /Y          .\tst\include\l1i_cs_trace.h						 %1
copy /Y          .\tst\include\l1i_egprs_trace.h						 %1
copy /Y          .\tst\include\l1i_ps_trace.h						 %1
copy /Y          .\tst\include\l1sc_trace.h						 %1
copy /Y          .\tst\include\l1sm_trace1.h						 %1
copy /Y          .\tst\include\l1t_amr_trace.h						 %1
copy /Y          .\tst\include\l1trc.h						 %1
copy /Y          .\tst\include\md_topsm_trace1.h						 %1
copy /Y          .\tst\include\ostd_trace1.h						 %1
copy /Y          .\tst\include\sleepdrv_trace1.h						 %1
copy /Y          .\tst\include\trcmod.h						 %1
copy /Y          .\tst\include\tst.h						 %1
copy /Y          .\tst\include\tst_def.h						 %1
copy /Y          .\tst\include\tst_lmu_hw.h						 %1
copy /Y          .\tst\include\tst_sap.h						 %1
copy /Y          .\tst\include\tstsap.h						 %1
copy /Y          .\tst\local_inc\dspsys_statistics.h						 %1
copy /Y          .\tst\local_inc\tst_ext.h						 %1
copy /Y          .\tst\local_inc\tst_hal_internal_wrapper_defs.h						 %1
copy /Y          .\usb\include\usb.h						 %1
copy /Y          .\usb\include\usb_adap.h						 %1
copy /Y          .\usb\include\usb_debug_tool.h						 %1
copy /Y          .\usb\include\usb_mode.h						 %1
copy /Y          .\usb\include\usb_resource.h						 %1
copy /Y          .\usb\include\usb_task.h						 %1
copy /Y          .\usb\include\usb_trc.h						 %1
copy /Y          .\usb\include\usbacm_adap.h						 %1
copy /Y          .\usb\include\usbacm_drv.h						 %1
copy /Y          .\usb\include\usbacm_ft.h						 %1
copy /Y          .\usb\include\usbms_adap.h						 %1
copy /Y          .\usb\include\usbms_drv.h						 %1
copy /Y          .\usb\include\usbms_state.h						 %1
copy /Y          .\vcard\include\vcard_builder.h						 %1
copy /Y          .\vcard\include\vcard_lib.h						 %1
copy /Y          .\vcard\include\vcard_parser.h						 %1
copy /Y          .\vcard\include\vcard_utility.h						 %1
copy /Y          .\venusmmi\app\common\interface\vapp_res.h						 %1
copy /Y          .\venusmmi\app\cosmos\interface\app\vapp_worldclock_gprot.h						 %1
copy /Y          .\venusmmi\visual\cp\res\vcp_res_range.h						 %1
copy /Y          .\wapadp\include\wap_cmmn_utils.h						 %1
copy /Y          .\xmlp\include\xml_def.h						 %1
copy /Y          .\xmlp\include\xmlgen.h						 %1
copy /Y          .\xmlp\include\xmlgen_common.h						 %1
copy /Y          .\xmlp\include\xmlgen_def.h						 %1
