/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
/* #include "custresdef.h" */

/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_FONT_EFFECTS">
		<INTEGER id="FE1_1_1_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_1_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_1_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_1_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_1_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_2_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_2_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_2_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_2_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_2_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_3_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_3_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_3_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_3_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_3_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_4_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_4_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_4_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_4_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_4_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_5_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_5_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_5_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_5_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_5_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_6_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_6_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_6_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_6_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_6_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_7_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_7_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_7_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_7_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_7_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_8_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_8_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_8_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_8_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_8_SHADOW_COLOR"/>
		
		<INTEGER id="FE1_1_9_SHADOW_DEGREE"/>
		<INTEGER id="FE1_1_9_SHADOW_DISTANT"/>
		<INTEGER id="FE1_1_9_SHADOW_RANGE"/>
		<INTEGER id="FE1_1_9_SHADOW_TRANSPARENCY"/>
		<COLOR id="FE1_1_9_SHADOW_COLOR"/>
		
		<INTEGER id="FE2_2_1_OUTER_GLOW_RANGE"/>
		<INTEGER id="FE2_2_2_OUTER_GLOW_TRANSPARENCY"/>
		<COLOR id="FE2_2_3_OUTER_GLOW_COLOR"/>

		<INTEGER id="FE3_3_1_ENGRAVED_DEGREE"/>
		<INTEGER id="FE3_3_2_ENGRAVED_TRANSPARENCY"/>
		<COLOR id="FE3_3_3_UPPER_ENGRAVED_COLOR"/>
		<COLOR id="FE3_3_4_LOWER_ENGRAVED_COLOR"/>	
				
		<INTEGER id="FE4_4_1_GRADIENT_DIRECTION"/>	
		<INTEGER id="FE4_4_2_GRADIENT_TRANSPARENCY"/>	
		<COLOR id="FE4_4_3_FIRST_GRADIENT_COLOR"/>	
		<COLOR id="FE4_4_4_SECOND_GRADIENT_COLOR"/>	
				
		<INTEGER id="FE5_5_1_BORDER_SIZE"/>	
		<INTEGER id="FE5_5_2_BORDER_TRANSPARENCY"/>	
		<COLOR id="FE5_5_3_BORDER_COLOR"/>			
</APP>

