#ifndef _ABM_TRC_GEN_H_
#define _ABM_TRC_GEN_H_

// STATE_ABM_TRANSITION
#define STATE_ABM_TRANSITION_size "dc"
#define STATE_ABM_TRANSITION STATE_ABM_TRANSITION__enum,STATE_ABM_TRANSITION_size

// STATE_ABM_ENTER_ACTIVE
#define STATE_ABM_ENTER_ACTIVE_size NULL
#define STATE_ABM_ENTER_ACTIVE STATE_ABM_ENTER_ACTIVE__enum,STATE_ABM_ENTER_ACTIVE_size

// STATE_ABM_ENTER_INACTIVE
#define STATE_ABM_ENTER_INACTIVE_size NULL
#define STATE_ABM_ENTER_INACTIVE STATE_ABM_ENTER_INACTIVE__enum,STATE_ABM_ENTER_INACTIVE_size

// STATE_ABM_APP_HDLR
#define STATE_ABM_APP_HDLR_size "c"
#define STATE_ABM_APP_HDLR STATE_ABM_APP_HDLR__enum,STATE_ABM_APP_HDLR_size

// STATE_ABM_BEARER_HDLR
#define STATE_ABM_BEARER_HDLR_size "c"
#define STATE_ABM_BEARER_HDLR STATE_ABM_BEARER_HDLR__enum,STATE_ABM_BEARER_HDLR_size

// STATE_ABM_SOC_ACTIVE_REQ
#define STATE_ABM_SOC_ACTIVE_REQ_size "‚d"
#define STATE_ABM_SOC_ACTIVE_REQ STATE_ABM_SOC_ACTIVE_REQ__enum,STATE_ABM_SOC_ACTIVE_REQ_size

// STATE_ABM_SOC_DEACTIVE_REQ
#define STATE_ABM_SOC_DEACTIVE_REQ_size "d"
#define STATE_ABM_SOC_DEACTIVE_REQ STATE_ABM_SOC_DEACTIVE_REQ__enum,STATE_ABM_SOC_DEACTIVE_REQ_size

// STATE_ABM_CSD_SETUP_REQ
#define STATE_ABM_CSD_SETUP_REQ_size "d"
#define STATE_ABM_CSD_SETUP_REQ STATE_ABM_CSD_SETUP_REQ__enum,STATE_ABM_CSD_SETUP_REQ_size

// STATE_ABM_CSD_DISC_REQ
#define STATE_ABM_CSD_DISC_REQ_size "d"
#define STATE_ABM_CSD_DISC_REQ STATE_ABM_CSD_DISC_REQ__enum,STATE_ABM_CSD_DISC_REQ_size

// STATE_ABM_GPRS_SETUP_REQ
#define STATE_ABM_GPRS_SETUP_REQ_size "d"
#define STATE_ABM_GPRS_SETUP_REQ STATE_ABM_GPRS_SETUP_REQ__enum,STATE_ABM_GPRS_SETUP_REQ_size

// STATE_ABM_GPRS_DISC_REQ
#define STATE_ABM_GPRS_DISC_REQ_size "d"
#define STATE_ABM_GPRS_DISC_REQ STATE_ABM_GPRS_DISC_REQ__enum,STATE_ABM_GPRS_DISC_REQ_size

// STATE_ABM_L4C_GPRS_DISC_RSP
#define STATE_ABM_L4C_GPRS_DISC_RSP_size "‚d"
#define STATE_ABM_L4C_GPRS_DISC_RSP STATE_ABM_L4C_GPRS_DISC_RSP__enum,STATE_ABM_L4C_GPRS_DISC_RSP_size

// STATE_ABM_L4C_GPRS_DISC_IND
#define STATE_ABM_L4C_GPRS_DISC_IND_size "‚d"
#define STATE_ABM_L4C_GPRS_DISC_IND STATE_ABM_L4C_GPRS_DISC_IND__enum,STATE_ABM_L4C_GPRS_DISC_IND_size

// STATE_ABM_L4C_CSD_SETUP_RSP
#define STATE_ABM_L4C_CSD_SETUP_RSP_size "dh"
#define STATE_ABM_L4C_CSD_SETUP_RSP STATE_ABM_L4C_CSD_SETUP_RSP__enum,STATE_ABM_L4C_CSD_SETUP_RSP_size

// STATE_ABM_L4C_CSD_DISC_RSP
#define STATE_ABM_L4C_CSD_DISC_RSP_size "‚d"
#define STATE_ABM_L4C_CSD_DISC_RSP STATE_ABM_L4C_CSD_DISC_RSP__enum,STATE_ABM_L4C_CSD_DISC_RSP_size

// STATE_ABM_L4C_CSD_DISC_IND
#define STATE_ABM_L4C_CSD_DISC_IND_size "‚d"
#define STATE_ABM_L4C_CSD_DISC_IND STATE_ABM_L4C_CSD_DISC_IND__enum,STATE_ABM_L4C_CSD_DISC_IND_size

// STATE_ABM_CBM_DISC_REQ
#define STATE_ABM_CBM_DISC_REQ_size "‚d"
#define STATE_ABM_CBM_DISC_REQ STATE_ABM_CBM_DISC_REQ__enum,STATE_ABM_CBM_DISC_REQ_size

// STATE_ABM_CBM_SET_DISC_MODE
#define STATE_ABM_CBM_SET_DISC_MODE_size "„d"
#define STATE_ABM_CBM_SET_DISC_MODE STATE_ABM_CBM_SET_DISC_MODE__enum,STATE_ABM_CBM_SET_DISC_MODE_size

// STATE_ABM_CBM_GET_DISC_MODE
#define STATE_ABM_CBM_GET_DISC_MODE_size "ƒd"
#define STATE_ABM_CBM_GET_DISC_MODE STATE_ABM_CBM_GET_DISC_MODE__enum,STATE_ABM_CBM_GET_DISC_MODE_size

// STATE_ABM_CBM_ALLOW_ACTIVATE_REQ
#define STATE_ABM_CBM_ALLOW_ACTIVATE_REQ_size NULL
#define STATE_ABM_CBM_ALLOW_ACTIVATE_REQ STATE_ABM_CBM_ALLOW_ACTIVATE_REQ__enum,STATE_ABM_CBM_ALLOW_ACTIVATE_REQ_size

// STATE_ABM_CBM_ALLOW_ACTIVATE_RSP
#define STATE_ABM_CBM_ALLOW_ACTIVATE_RSP_size NULL
#define STATE_ABM_CBM_ALLOW_ACTIVATE_RSP STATE_ABM_CBM_ALLOW_ACTIVATE_RSP__enum,STATE_ABM_CBM_ALLOW_ACTIVATE_RSP_size

// STATE_ABM_CBM_DISALLOW_ACTIVATE_REQ
#define STATE_ABM_CBM_DISALLOW_ACTIVATE_REQ_size NULL
#define STATE_ABM_CBM_DISALLOW_ACTIVATE_REQ STATE_ABM_CBM_DISALLOW_ACTIVATE_REQ__enum,STATE_ABM_CBM_DISALLOW_ACTIVATE_REQ_size

// STATE_ABM_CBM_DISALLOW_ACTIVATE_RSP
#define STATE_ABM_CBM_DISALLOW_ACTIVATE_RSP_size NULL
#define STATE_ABM_CBM_DISALLOW_ACTIVATE_RSP STATE_ABM_CBM_DISALLOW_ACTIVATE_RSP__enum,STATE_ABM_CBM_DISALLOW_ACTIVATE_RSP_size

// ABM_AP_ACCT_STATE
#define ABM_AP_ACCT_STATE_size "dchd"
#define ABM_AP_ACCT_STATE ABM_AP_ACCT_STATE__enum,ABM_AP_ACCT_STATE_size

// ERROR_ABM_L4C_CSD_SETUP_RSP
#define ERROR_ABM_L4C_CSD_SETUP_RSP_size "c"
#define ERROR_ABM_L4C_CSD_SETUP_RSP ERROR_ABM_L4C_CSD_SETUP_RSP__enum,ERROR_ABM_L4C_CSD_SETUP_RSP_size

// ERROR_ABM_MSG_1
#define ERROR_ABM_MSG_1_size "h"
#define ERROR_ABM_MSG_1 ERROR_ABM_MSG_1__enum,ERROR_ABM_MSG_1_size

// ERROR_ABM_MSG_2
#define ERROR_ABM_MSG_2_size "hc"
#define ERROR_ABM_MSG_2 ERROR_ABM_MSG_2__enum,ERROR_ABM_MSG_2_size

// ERROR_ABM_MSG_3
#define ERROR_ABM_MSG_3_size "hcd"
#define ERROR_ABM_MSG_3 ERROR_ABM_MSG_3__enum,ERROR_ABM_MSG_3_size

// ERROR_ABM_APP_SLOT
#define ERROR_ABM_APP_SLOT_size NULL
#define ERROR_ABM_APP_SLOT ERROR_ABM_APP_SLOT__enum,ERROR_ABM_APP_SLOT_size

// ERROR_ABM_APP_FB_OPTION
#define ERROR_ABM_APP_FB_OPTION_size "d"
#define ERROR_ABM_APP_FB_OPTION ERROR_ABM_APP_FB_OPTION__enum,ERROR_ABM_APP_FB_OPTION_size

// ERROR_ABM_INVALID_NWK_ID
#define ERROR_ABM_INVALID_NWK_ID_size NULL
#define ERROR_ABM_INVALID_NWK_ID ERROR_ABM_INVALID_NWK_ID__enum,ERROR_ABM_INVALID_NWK_ID_size

// ABM_GET_TIMER_PTR_FAIL
#define ABM_GET_TIMER_PTR_FAIL_size "c‚d"
#define ABM_GET_TIMER_PTR_FAIL ABM_GET_TIMER_PTR_FAIL__enum,ABM_GET_TIMER_PTR_FAIL_size

// ABM_NO_FREE_TIMER
#define ABM_NO_FREE_TIMER_size NULL
#define ABM_NO_FREE_TIMER ABM_NO_FREE_TIMER__enum,ABM_NO_FREE_TIMER_size

// ABM_NO_FREE_APP_SLOT
#define ABM_NO_FREE_APP_SLOT_size "hd"
#define ABM_NO_FREE_APP_SLOT ABM_NO_FREE_APP_SLOT__enum,ABM_NO_FREE_APP_SLOT_size

// ABM_INVALID_MTU_SIZE
#define ABM_INVALID_MTU_SIZE_size NULL
#define ABM_INVALID_MTU_SIZE ABM_INVALID_MTU_SIZE__enum,ABM_INVALID_MTU_SIZE_size

// ABM_INVALID_IP_ADDR
#define ABM_INVALID_IP_ADDR_size NULL
#define ABM_INVALID_IP_ADDR ABM_INVALID_IP_ADDR__enum,ABM_INVALID_IP_ADDR_size

// ABM_INVALID_WIFI_PROFILE_NUM
#define ABM_INVALID_WIFI_PROFILE_NUM_size "d"
#define ABM_INVALID_WIFI_PROFILE_NUM ABM_INVALID_WIFI_PROFILE_NUM__enum,ABM_INVALID_WIFI_PROFILE_NUM_size

// ABM_INVALID_WIFI_SEL_MODE
#define ABM_INVALID_WIFI_SEL_MODE_size "d"
#define ABM_INVALID_WIFI_SEL_MODE ABM_INVALID_WIFI_SEL_MODE__enum,ABM_INVALID_WIFI_SEL_MODE_size

// ABM_INVALID_CALL_NUM
#define ABM_INVALID_CALL_NUM_size NULL
#define ABM_INVALID_CALL_NUM ABM_INVALID_CALL_NUM__enum,ABM_INVALID_CALL_NUM_size

// ABM_INVALID_SIM_ID
#define ABM_INVALID_SIM_ID_size "‚d"
#define ABM_INVALID_SIM_ID ABM_INVALID_SIM_ID__enum,ABM_INVALID_SIM_ID_size

// ABM_INVALID_UPDATE_INFO
#define ABM_INVALID_UPDATE_INFO_size "d"
#define ABM_INVALID_UPDATE_INFO ABM_INVALID_UPDATE_INFO__enum,ABM_INVALID_UPDATE_INFO_size

// CON_MNG_ACCT_SLOT_RESET
#define CON_MNG_ACCT_SLOT_RESET_size "‚d"
#define CON_MNG_ACCT_SLOT_RESET CON_MNG_ACCT_SLOT_RESET__enum,CON_MNG_ACCT_SLOT_RESET_size

// CON_MNG_ACCT_SET_SLOT
#define CON_MNG_ACCT_SET_SLOT_size "‚d"
#define CON_MNG_ACCT_SET_SLOT CON_MNG_ACCT_SET_SLOT__enum,CON_MNG_ACCT_SET_SLOT_size

// ABM_INFO_DISABLE_BEARER_INFO
#define ABM_INFO_DISABLE_BEARER_INFO_size "h‚d"
#define ABM_INFO_DISABLE_BEARER_INFO ABM_INFO_DISABLE_BEARER_INFO__enum,ABM_INFO_DISABLE_BEARER_INFO_size

// ABM_BYPASS_BEARER_INFO
#define ABM_BYPASS_BEARER_INFO_size "hd"
#define ABM_BYPASS_BEARER_INFO ABM_BYPASS_BEARER_INFO__enum,ABM_BYPASS_BEARER_INFO_size

// ABM_BEARER_REQ_TO_TCPIP
#define ABM_BEARER_REQ_TO_TCPIP_size "c†d"
#define ABM_BEARER_REQ_TO_TCPIP ABM_BEARER_REQ_TO_TCPIP__enum,ABM_BEARER_REQ_TO_TCPIP_size

// ABM_ACTIVATE_BEARER_AGAIN
#define ABM_ACTIVATE_BEARER_AGAIN_size NULL
#define ABM_ACTIVATE_BEARER_AGAIN ABM_ACTIVATE_BEARER_AGAIN__enum,ABM_ACTIVATE_BEARER_AGAIN_size

// ABM_PS_TIMER_CAUSE_FB_L1
#define ABM_PS_TIMER_CAUSE_FB_L1_size "hd"
#define ABM_PS_TIMER_CAUSE_FB_L1 ABM_PS_TIMER_CAUSE_FB_L1__enum,ABM_PS_TIMER_CAUSE_FB_L1_size

// ABM_ACCT_IS_HOLD
#define ABM_ACCT_IS_HOLD_size "dhd"
#define ABM_ACCT_IS_HOLD ABM_ACCT_IS_HOLD__enum,ABM_ACCT_IS_HOLD_size

// ABM_RESET_APP_SLOT
#define ABM_RESET_APP_SLOT_size "d"
#define ABM_RESET_APP_SLOT ABM_RESET_APP_SLOT__enum,ABM_RESET_APP_SLOT_size

// ABM_APP_FLAG_STATE
#define ABM_APP_FLAG_STATE_size "d"
#define ABM_APP_FLAG_STATE ABM_APP_FLAG_STATE__enum,ABM_APP_FLAG_STATE_size

// ABM_UPDATE_BEARER_TYPE
#define ABM_UPDATE_BEARER_TYPE_size "‚h"
#define ABM_UPDATE_BEARER_TYPE ABM_UPDATE_BEARER_TYPE__enum,ABM_UPDATE_BEARER_TYPE_size

// ABM_IS_INIT
#define ABM_IS_INIT_size "d"
#define ABM_IS_INIT ABM_IS_INIT__enum,ABM_IS_INIT_size

// ABM_FREE_NWK_NEG_QOS
#define ABM_FREE_NWK_NEG_QOS_size "d"
#define ABM_FREE_NWK_NEG_QOS ABM_FREE_NWK_NEG_QOS__enum,ABM_FREE_NWK_NEG_QOS_size

// ABM_UPDATE_NWK_NEG_QOS
#define ABM_UPDATE_NWK_NEG_QOS_size "„d"
#define ABM_UPDATE_NWK_NEG_QOS ABM_UPDATE_NWK_NEG_QOS__enum,ABM_UPDATE_NWK_NEG_QOS_size

// ABM_FIND_NWK_NEG_QOS
#define ABM_FIND_NWK_NEG_QOS_size "‚d"
#define ABM_FIND_NWK_NEG_QOS ABM_FIND_NWK_NEG_QOS__enum,ABM_FIND_NWK_NEG_QOS_size

// ABM_NWK_PROFILE_INFO
#define ABM_NWK_PROFILE_INFO_size "dh"
#define ABM_NWK_PROFILE_INFO ABM_NWK_PROFILE_INFO__enum,ABM_NWK_PROFILE_INFO_size

// ABM_CHECK_BEARER_INFO
#define ABM_CHECK_BEARER_INFO_size "…d"
#define ABM_CHECK_BEARER_INFO ABM_CHECK_BEARER_INFO__enum,ABM_CHECK_BEARER_INFO_size

// CBM_ABORT_BEARER_EVT
#define CBM_ABORT_BEARER_EVT_size "d"
#define CBM_ABORT_BEARER_EVT CBM_ABORT_BEARER_EVT__enum,CBM_ABORT_BEARER_EVT_size

// CBM_ENCODE_APP_ID
#define CBM_ENCODE_APP_ID_size "ƒd"
#define CBM_ENCODE_APP_ID CBM_ENCODE_APP_ID__enum,CBM_ENCODE_APP_ID_size

// CBM_ENCODE_ONE_ACCT_ID
#define CBM_ENCODE_ONE_ACCT_ID_size "…d"
#define CBM_ENCODE_ONE_ACCT_ID CBM_ENCODE_ONE_ACCT_ID__enum,CBM_ENCODE_ONE_ACCT_ID_size

// CBM_DECODE_ACCT_ID
#define CBM_DECODE_ACCT_ID_size "d"
#define CBM_DECODE_ACCT_ID CBM_DECODE_ACCT_ID__enum,CBM_DECODE_ACCT_ID_size

// CBM_IS_ALWAYS_ASK_ACCT_ID
#define CBM_IS_ALWAYS_ASK_ACCT_ID_size "d"
#define CBM_IS_ALWAYS_ASK_ACCT_ID CBM_IS_ALWAYS_ASK_ACCT_ID__enum,CBM_IS_ALWAYS_ASK_ACCT_ID_size

// CBM_GET_SIM_ID_BY_ONE_ACCT
#define CBM_GET_SIM_ID_BY_ONE_ACCT_size "d"
#define CBM_GET_SIM_ID_BY_ONE_ACCT CBM_GET_SIM_ID_BY_ONE_ACCT__enum,CBM_GET_SIM_ID_BY_ONE_ACCT_size

// CBM_GET_APP_ID
#define CBM_GET_APP_ID_size "d"
#define CBM_GET_APP_ID CBM_GET_APP_ID__enum,CBM_GET_APP_ID_size

// CBM_GET_ONE_ACCT_ID
#define CBM_GET_ONE_ACCT_ID_size "d"
#define CBM_GET_ONE_ACCT_ID CBM_GET_ONE_ACCT_ID__enum,CBM_GET_ONE_ACCT_ID_size

// CBM_REG_APP_ID
#define CBM_REG_APP_ID_size "„d"
#define CBM_REG_APP_ID CBM_REG_APP_ID__enum,CBM_REG_APP_ID_size

// CBM_ENCODE_MULTI_ACCT_ID
#define CBM_ENCODE_MULTI_ACCT_ID_size "‚d"
#define CBM_ENCODE_MULTI_ACCT_ID CBM_ENCODE_MULTI_ACCT_ID__enum,CBM_ENCODE_MULTI_ACCT_ID_size

// CBM_DECODE_MULTI_ACCT_ID
#define CBM_DECODE_MULTI_ACCT_ID_size "ˆd"
#define CBM_DECODE_MULTI_ACCT_ID CBM_DECODE_MULTI_ACCT_ID__enum,CBM_DECODE_MULTI_ACCT_ID_size

// CBM_SET_FALLBACK_OPT
#define CBM_SET_FALLBACK_OPT_size "dhc"
#define CBM_SET_FALLBACK_OPT CBM_SET_FALLBACK_OPT__enum,CBM_SET_FALLBACK_OPT_size

// CBM_HOLD_BEARER
#define CBM_HOLD_BEARER_size "d"
#define CBM_HOLD_BEARER CBM_HOLD_BEARER__enum,CBM_HOLD_BEARER_size

// CBM_REL_BEARER
#define CBM_REL_BEARER_size "d"
#define CBM_REL_BEARER CBM_REL_BEARER__enum,CBM_REL_BEARER_size

// CBM_OPEN_BEARER
#define CBM_OPEN_BEARER_size "d"
#define CBM_OPEN_BEARER CBM_OPEN_BEARER__enum,CBM_OPEN_BEARER_size

// CBM_CHK_VALID_ACCT
#define CBM_CHK_VALID_ACCT_size "d"
#define CBM_CHK_VALID_ACCT CBM_CHK_VALID_ACCT__enum,CBM_CHK_VALID_ACCT_size

// CBM_REG_BEARER_INFO
#define CBM_REG_BEARER_INFO_size "dh‚d"
#define CBM_REG_BEARER_INFO CBM_REG_BEARER_INFO__enum,CBM_REG_BEARER_INFO_size

// CBM_DEREG_BEARER_INFO
#define CBM_DEREG_BEARER_INFO_size "dh"
#define CBM_DEREG_BEARER_INFO CBM_DEREG_BEARER_INFO__enum,CBM_DEREG_BEARER_INFO_size

// CBM_GET_REG_BEARER_INFO
#define CBM_GET_REG_BEARER_INFO_size "dh‚d"
#define CBM_GET_REG_BEARER_INFO CBM_GET_REG_BEARER_INFO__enum,CBM_GET_REG_BEARER_INFO_size

// CBM_ALLOW_NWK_SRV
#define CBM_ALLOW_NWK_SRV_size "‚d"
#define CBM_ALLOW_NWK_SRV CBM_ALLOW_NWK_SRV__enum,CBM_ALLOW_NWK_SRV_size

// CBM_DISALLOW_NWK_SRV
#define CBM_DISALLOW_NWK_SRV_size "‚d"
#define CBM_DISALLOW_NWK_SRV CBM_DISALLOW_NWK_SRV__enum,CBM_DISALLOW_NWK_SRV_size

// CBM_GET_BEARER_STATUS_EXT
#define CBM_GET_BEARER_STATUS_EXT_size "‡d"
#define CBM_GET_BEARER_STATUS_EXT CBM_GET_BEARER_STATUS_EXT__enum,CBM_GET_BEARER_STATUS_EXT_size

// ABM_GET_REG_APP_INFO
#define ABM_GET_REG_APP_INFO_size "‚d"
#define ABM_GET_REG_APP_INFO ABM_GET_REG_APP_INFO__enum,ABM_GET_REG_APP_INFO_size

// ABM_REG_ACCT_SELECT_NOTIFY
#define ABM_REG_ACCT_SELECT_NOTIFY_size "„d"
#define ABM_REG_ACCT_SELECT_NOTIFY ABM_REG_ACCT_SELECT_NOTIFY__enum,ABM_REG_ACCT_SELECT_NOTIFY_size

// ABM_DEREG_ACCT_SELECT_NOTIFY
#define ABM_DEREG_ACCT_SELECT_NOTIFY_size "d"
#define ABM_DEREG_ACCT_SELECT_NOTIFY ABM_DEREG_ACCT_SELECT_NOTIFY__enum,ABM_DEREG_ACCT_SELECT_NOTIFY_size

// ABM_DEL_BEARER_STATUS_IDX
#define ABM_DEL_BEARER_STATUS_IDX_size "‚d"
#define ABM_DEL_BEARER_STATUS_IDX ABM_DEL_BEARER_STATUS_IDX__enum,ABM_DEL_BEARER_STATUS_IDX_size

// ABM_START_TIMER
#define ABM_START_TIMER_size "cd"
#define ABM_START_TIMER ABM_START_TIMER__enum,ABM_START_TIMER_size

// ABM_STOP_TIMER
#define ABM_STOP_TIMER_size "c"
#define ABM_STOP_TIMER ABM_STOP_TIMER__enum,ABM_STOP_TIMER_size

// ABM_GET_BEARER_STATUS
#define ABM_GET_BEARER_STATUS_size "dc"
#define ABM_GET_BEARER_STATUS ABM_GET_BEARER_STATUS__enum,ABM_GET_BEARER_STATUS_size

// ABM_GET_BEARER_TYPE
#define ABM_GET_BEARER_TYPE_size "dh"
#define ABM_GET_BEARER_TYPE ABM_GET_BEARER_TYPE__enum,ABM_GET_BEARER_TYPE_size

// ABM_GET_PROFILE_TYPE
#define ABM_GET_PROFILE_TYPE_size "‚dcd"
#define ABM_GET_PROFILE_TYPE ABM_GET_PROFILE_TYPE__enum,ABM_GET_PROFILE_TYPE_size

// ABM_RESET_DATA
#define ABM_RESET_DATA_size NULL
#define ABM_RESET_DATA ABM_RESET_DATA__enum,ABM_RESET_DATA_size

// CBM_DEREG_APP_ID
#define CBM_DEREG_APP_ID_size "‚d"
#define CBM_DEREG_APP_ID CBM_DEREG_APP_ID__enum,CBM_DEREG_APP_ID_size

// CBM_REG_STATIC_QOS_ID
#define CBM_REG_STATIC_QOS_ID_size "‚d"
#define CBM_REG_STATIC_QOS_ID CBM_REG_STATIC_QOS_ID__enum,CBM_REG_STATIC_QOS_ID_size

// CBM_DEREG_STATIC_QOS_ID
#define CBM_DEREG_STATIC_QOS_ID_size "d"
#define CBM_DEREG_STATIC_QOS_ID CBM_DEREG_STATIC_QOS_ID__enum,CBM_DEREG_STATIC_QOS_ID_size

// CBM_REG_DYNAMIC_QOS_ID
#define CBM_REG_DYNAMIC_QOS_ID_size "‚d"
#define CBM_REG_DYNAMIC_QOS_ID CBM_REG_DYNAMIC_QOS_ID__enum,CBM_REG_DYNAMIC_QOS_ID_size

// CBM_DEREG_DYNAMIC_QOS_ID
#define CBM_DEREG_DYNAMIC_QOS_ID_size "d"
#define CBM_DEREG_DYNAMIC_QOS_ID CBM_DEREG_DYNAMIC_QOS_ID__enum,CBM_DEREG_DYNAMIC_QOS_ID_size

// CBM_SET_QOS_PROFILE
#define CBM_SET_QOS_PROFILE_size "dh"
#define CBM_SET_QOS_PROFILE CBM_SET_QOS_PROFILE__enum,CBM_SET_QOS_PROFILE_size

// ABM_GET_BEARER_AVAILABLE_STATUS
#define ABM_GET_BEARER_AVAILABLE_STATUS_size "‚d"
#define ABM_GET_BEARER_AVAILABLE_STATUS ABM_GET_BEARER_AVAILABLE_STATUS__enum,ABM_GET_BEARER_AVAILABLE_STATUS_size

// ABM_GET_SWITCHABLE_APP_ID
#define ABM_GET_SWITCHABLE_APP_ID_size "d"
#define ABM_GET_SWITCHABLE_APP_ID ABM_GET_SWITCHABLE_APP_ID__enum,ABM_GET_SWITCHABLE_APP_ID_size

// ABM_GET_BEARER_STATUS_BY_APP_TYPE
#define ABM_GET_BEARER_STATUS_BY_APP_TYPE_size "„d"
#define ABM_GET_BEARER_STATUS_BY_APP_TYPE ABM_GET_BEARER_STATUS_BY_APP_TYPE__enum,ABM_GET_BEARER_STATUS_BY_APP_TYPE_size

// ABM_CHECK_CSD_STATE
#define ABM_CHECK_CSD_STATE_size "d"
#define ABM_CHECK_CSD_STATE ABM_CHECK_CSD_STATE__enum,ABM_CHECK_CSD_STATE_size

// ABM_DISCONNECT_CSD
#define ABM_DISCONNECT_CSD_size "d"
#define ABM_DISCONNECT_CSD ABM_DISCONNECT_CSD__enum,ABM_DISCONNECT_CSD_size

// ABM_DISCONNECT_PS
#define ABM_DISCONNECT_PS_size "ƒd"
#define ABM_DISCONNECT_PS ABM_DISCONNECT_PS__enum,ABM_DISCONNECT_PS_size

// ABM_PS_DETACHED
#define ABM_PS_DETACHED_size "‚d"
#define ABM_PS_DETACHED ABM_PS_DETACHED__enum,ABM_PS_DETACHED_size

// ABM_PS_NOT_DETACHED
#define ABM_PS_NOT_DETACHED_size "‚d"
#define ABM_PS_NOT_DETACHED ABM_PS_NOT_DETACHED__enum,ABM_PS_NOT_DETACHED_size

// ABM_CHECK_PS_STATE
#define ABM_CHECK_PS_STATE_size "‚d"
#define ABM_CHECK_PS_STATE ABM_CHECK_PS_STATE__enum,ABM_CHECK_PS_STATE_size

// ABM_CHECK_IS_WLAN_USED
#define ABM_CHECK_IS_WLAN_USED_size "„d"
#define ABM_CHECK_IS_WLAN_USED ABM_CHECK_IS_WLAN_USED__enum,ABM_CHECK_IS_WLAN_USED_size


#endif // ABM_TRC_GEN.H
