#ifndef _BMT_TRC_GEN_H_
#define _BMT_TRC_GEN_H_

// BMT_CTRL_CHARGE_TRC
#define BMT_CTRL_CHARGE_TRC_size "d"
#define BMT_CTRL_CHARGE_TRC BMT_CTRL_CHARGE_TRC__enum,BMT_CTRL_CHARGE_TRC_size

// BMT_CHARGING_ALREADY_ON_TRC
#define BMT_CHARGING_ALREADY_ON_TRC_size NULL
#define BMT_CHARGING_ALREADY_ON_TRC BMT_CHARGING_ALREADY_ON_TRC__enum,BMT_CHARGING_ALREADY_ON_TRC_size

// BMT_CALL_STATE_TRC
#define BMT_CALL_STATE_TRC_size "d"
#define BMT_CALL_STATE_TRC BMT_CALL_STATE_TRC__enum,BMT_CALL_STATE_TRC_size

// BMT_INVALID_CHARGER_TRC
#define BMT_INVALID_CHARGER_TRC_size NULL
#define BMT_INVALID_CHARGER_TRC BMT_INVALID_CHARGER_TRC__enum,BMT_INVALID_CHARGER_TRC_size

// BMT_ICHARGE_OVER_TRC
#define BMT_ICHARGE_OVER_TRC_size NULL
#define BMT_ICHARGE_OVER_TRC BMT_ICHARGE_OVER_TRC__enum,BMT_ICHARGE_OVER_TRC_size

// BMT_ICHARGE_LOW_TRC
#define BMT_ICHARGE_LOW_TRC_size NULL
#define BMT_ICHARGE_LOW_TRC BMT_ICHARGE_LOW_TRC__enum,BMT_ICHARGE_LOW_TRC_size

// BMT_VBAT_OVER_TRC
#define BMT_VBAT_OVER_TRC_size NULL
#define BMT_VBAT_OVER_TRC BMT_VBAT_OVER_TRC__enum,BMT_VBAT_OVER_TRC_size

// BMT_VTEMP_OVER_TRC
#define BMT_VTEMP_OVER_TRC_size NULL
#define BMT_VTEMP_OVER_TRC BMT_VTEMP_OVER_TRC__enum,BMT_VTEMP_OVER_TRC_size

// BMT_VTEMP_LOW_TRC
#define BMT_VTEMP_LOW_TRC_size NULL
#define BMT_VTEMP_LOW_TRC BMT_VTEMP_LOW_TRC__enum,BMT_VTEMP_LOW_TRC_size

// BMT_CHR_HOLD_TRC
#define BMT_CHR_HOLD_TRC_size NULL
#define BMT_CHR_HOLD_TRC BMT_CHR_HOLD_TRC__enum,BMT_CHR_HOLD_TRC_size

// BMT_VBAT_TRC
#define BMT_VBAT_TRC_size "d"
#define BMT_VBAT_TRC BMT_VBAT_TRC__enum,BMT_VBAT_TRC_size

// BMT_VBATTMP_TRC
#define BMT_VBATTMP_TRC_size "d"
#define BMT_VBATTMP_TRC BMT_VBATTMP_TRC__enum,BMT_VBATTMP_TRC_size

// BMT_BATTMP_TRC
#define BMT_BATTMP_TRC_size "d"
#define BMT_BATTMP_TRC BMT_BATTMP_TRC__enum,BMT_BATTMP_TRC_size

// BMT_ICHARGE_TRC
#define BMT_ICHARGE_TRC_size "d"
#define BMT_ICHARGE_TRC BMT_ICHARGE_TRC__enum,BMT_ICHARGE_TRC_size

// BMT_VSENSE_TRC
#define BMT_VSENSE_TRC_size "d"
#define BMT_VSENSE_TRC BMT_VSENSE_TRC__enum,BMT_VSENSE_TRC_size

// BMT_VSENSE_VBAT_OFFSET_TRC
#define BMT_VSENSE_VBAT_OFFSET_TRC_size "d"
#define BMT_VSENSE_VBAT_OFFSET_TRC BMT_VSENSE_VBAT_OFFSET_TRC__enum,BMT_VSENSE_VBAT_OFFSET_TRC_size

// BMT_VCHARGER_TRC
#define BMT_VCHARGER_TRC_size "d"
#define BMT_VCHARGER_TRC BMT_VCHARGER_TRC__enum,BMT_VCHARGER_TRC_size

// BMT_CHRPRE_ON_STATE_TRC
#define BMT_CHRPRE_ON_STATE_TRC_size NULL
#define BMT_CHRPRE_ON_STATE_TRC BMT_CHRPRE_ON_STATE_TRC__enum,BMT_CHRPRE_ON_STATE_TRC_size

// BMT_CHRPRE_OFF_STATE_TRC
#define BMT_CHRPRE_OFF_STATE_TRC_size NULL
#define BMT_CHRPRE_OFF_STATE_TRC BMT_CHRPRE_OFF_STATE_TRC__enum,BMT_CHRPRE_OFF_STATE_TRC_size

// BMT_FAST_CHARGE_CHANGE_TRC
#define BMT_FAST_CHARGE_CHANGE_TRC_size NULL
#define BMT_FAST_CHARGE_CHANGE_TRC BMT_FAST_CHARGE_CHANGE_TRC__enum,BMT_FAST_CHARGE_CHANGE_TRC_size

// BMT_FAST_ON_STATE_TRC
#define BMT_FAST_ON_STATE_TRC_size NULL
#define BMT_FAST_ON_STATE_TRC BMT_FAST_ON_STATE_TRC__enum,BMT_FAST_ON_STATE_TRC_size

// BMT_FAST_OFF_STATE_TRC
#define BMT_FAST_OFF_STATE_TRC_size NULL
#define BMT_FAST_OFF_STATE_TRC BMT_FAST_OFF_STATE_TRC__enum,BMT_FAST_OFF_STATE_TRC_size

// BMT_PMU_PULSECHR_TRC
#define BMT_PMU_PULSECHR_TRC_size NULL
#define BMT_PMU_PULSECHR_TRC BMT_PMU_PULSECHR_TRC__enum,BMT_PMU_PULSECHR_TRC_size

// BMT_CHR_POSTFULL_CHANGE_TRC
#define BMT_CHR_POSTFULL_CHANGE_TRC_size NULL
#define BMT_CHR_POSTFULL_CHANGE_TRC BMT_CHR_POSTFULL_CHANGE_TRC__enum,BMT_CHR_POSTFULL_CHANGE_TRC_size

// BMT_CHR_BATFULL_CHANGE_TRC
#define BMT_CHR_BATFULL_CHANGE_TRC_size NULL
#define BMT_CHR_BATFULL_CHANGE_TRC BMT_CHR_BATFULL_CHANGE_TRC__enum,BMT_CHR_BATFULL_CHANGE_TRC_size

// BMT_CHR_UNDER_EXTREMETMP_TRC
#define BMT_CHR_UNDER_EXTREMETMP_TRC_size NULL
#define BMT_CHR_UNDER_EXTREMETMP_TRC BMT_CHR_UNDER_EXTREMETMP_TRC__enum,BMT_CHR_UNDER_EXTREMETMP_TRC_size

// BMT_CHR_EXTREMETMP_BATFULL_CHANGE_TRC
#define BMT_CHR_EXTREMETMP_BATFULL_CHANGE_TRC_size NULL
#define BMT_CHR_EXTREMETMP_BATFULL_CHANGE_TRC BMT_CHR_EXTREMETMP_BATFULL_CHANGE_TRC__enum,BMT_CHR_EXTREMETMP_BATFULL_CHANGE_TRC_size

// BMT_CHR_EXTREMETMP_CHARGE_RECHARGE_TRC
#define BMT_CHR_EXTREMETMP_CHARGE_RECHARGE_TRC_size NULL
#define BMT_CHR_EXTREMETMP_CHARGE_RECHARGE_TRC BMT_CHR_EXTREMETMP_CHARGE_RECHARGE_TRC__enum,BMT_CHR_EXTREMETMP_CHARGE_RECHARGE_TRC_size

// BMT_CHR_TOPOFF_CHANGE_TRC
#define BMT_CHR_TOPOFF_CHANGE_TRC_size NULL
#define BMT_CHR_TOPOFF_CHANGE_TRC BMT_CHR_TOPOFF_CHANGE_TRC__enum,BMT_CHR_TOPOFF_CHANGE_TRC_size

// BMT_CHRTOPOFF_ON_STATE_TRC
#define BMT_CHRTOPOFF_ON_STATE_TRC_size NULL
#define BMT_CHRTOPOFF_ON_STATE_TRC BMT_CHRTOPOFF_ON_STATE_TRC__enum,BMT_CHRTOPOFF_ON_STATE_TRC_size

// BMT_CHR_FAST_CHANGE_TRC
#define BMT_CHR_FAST_CHANGE_TRC_size NULL
#define BMT_CHR_FAST_CHANGE_TRC BMT_CHR_FAST_CHANGE_TRC__enum,BMT_CHR_FAST_CHANGE_TRC_size

// BMT_CHRTOPOFF_OFF_STATE_TRC
#define BMT_CHRTOPOFF_OFF_STATE_TRC_size NULL
#define BMT_CHRTOPOFF_OFF_STATE_TRC BMT_CHRTOPOFF_OFF_STATE_TRC__enum,BMT_CHRTOPOFF_OFF_STATE_TRC_size

// BMT_CHRBATPOSTFULL_ON_STATE_TRC
#define BMT_CHRBATPOSTFULL_ON_STATE_TRC_size NULL
#define BMT_CHRBATPOSTFULL_ON_STATE_TRC BMT_CHRBATPOSTFULL_ON_STATE_TRC__enum,BMT_CHRBATPOSTFULL_ON_STATE_TRC_size

// BMT_CHRBATPOSTFULL_OFF_STATE_TRC
#define BMT_CHRBATPOSTFULL_OFF_STATE_TRC_size NULL
#define BMT_CHRBATPOSTFULL_OFF_STATE_TRC BMT_CHRBATPOSTFULL_OFF_STATE_TRC__enum,BMT_CHRBATPOSTFULL_OFF_STATE_TRC_size

// BMT_CHRBATFULL_ON_STATE_TRC
#define BMT_CHRBATFULL_ON_STATE_TRC_size NULL
#define BMT_CHRBATFULL_ON_STATE_TRC BMT_CHRBATFULL_ON_STATE_TRC__enum,BMT_CHRBATFULL_ON_STATE_TRC_size

// BMT_CHRBATFULL_OFF_STATE_TRC
#define BMT_CHRBATFULL_OFF_STATE_TRC_size NULL
#define BMT_CHRBATFULL_OFF_STATE_TRC BMT_CHRBATFULL_OFF_STATE_TRC__enum,BMT_CHRBATFULL_OFF_STATE_TRC_size

// BMT_CHRHOLD_STATE_TRC
#define BMT_CHRHOLD_STATE_TRC_size NULL
#define BMT_CHRHOLD_STATE_TRC BMT_CHRHOLD_STATE_TRC__enum,BMT_CHRHOLD_STATE_TRC_size

// BMT_HIGH_BAT_FULL_TRC
#define BMT_HIGH_BAT_FULL_TRC_size NULL
#define BMT_HIGH_BAT_FULL_TRC BMT_HIGH_BAT_FULL_TRC__enum,BMT_HIGH_BAT_FULL_TRC_size

// BMT_MEASURE_STOP_TRC
#define BMT_MEASURE_STOP_TRC_size NULL
#define BMT_MEASURE_STOP_TRC BMT_MEASURE_STOP_TRC__enum,BMT_MEASURE_STOP_TRC_size

// BMT_PWRON_TRC
#define BMT_PWRON_TRC_size "d"
#define BMT_PWRON_TRC BMT_PWRON_TRC__enum,BMT_PWRON_TRC_size

// BMT_TASK_MAIN_TRC
#define BMT_TASK_MAIN_TRC_size NULL
#define BMT_TASK_MAIN_TRC BMT_TASK_MAIN_TRC__enum,BMT_TASK_MAIN_TRC_size

// BMT_CHARGE_GUARD_TIMER_EXPIRE_TRC
#define BMT_CHARGE_GUARD_TIMER_EXPIRE_TRC_size "d"
#define BMT_CHARGE_GUARD_TIMER_EXPIRE_TRC BMT_CHARGE_GUARD_TIMER_EXPIRE_TRC__enum,BMT_CHARGE_GUARD_TIMER_EXPIRE_TRC_size

// BMT_SAFETY_TIMER_EXPIRE_TRC
#define BMT_SAFETY_TIMER_EXPIRE_TRC_size "d"
#define BMT_SAFETY_TIMER_EXPIRE_TRC BMT_SAFETY_TIMER_EXPIRE_TRC__enum,BMT_SAFETY_TIMER_EXPIRE_TRC_size

// BMT_SAFETY_TIMER_START_TRC
#define BMT_SAFETY_TIMER_START_TRC_size "d"
#define BMT_SAFETY_TIMER_START_TRC BMT_SAFETY_TIMER_START_TRC__enum,BMT_SAFETY_TIMER_START_TRC_size

// BMT_SAFETY_AND_GUARD_TIMER_START_TRC
#define BMT_SAFETY_AND_GUARD_TIMER_START_TRC_size "‚d"
#define BMT_SAFETY_AND_GUARD_TIMER_START_TRC BMT_SAFETY_AND_GUARD_TIMER_START_TRC__enum,BMT_SAFETY_AND_GUARD_TIMER_START_TRC_size

// BMT_SAFETY_TIMER_STOP_TRC
#define BMT_SAFETY_TIMER_STOP_TRC_size "d"
#define BMT_SAFETY_TIMER_STOP_TRC BMT_SAFETY_TIMER_STOP_TRC__enum,BMT_SAFETY_TIMER_STOP_TRC_size

// BMT_STOP_TIMER_EXPIRE_TRC
#define BMT_STOP_TIMER_EXPIRE_TRC_size NULL
#define BMT_STOP_TIMER_EXPIRE_TRC BMT_STOP_TIMER_EXPIRE_TRC__enum,BMT_STOP_TIMER_EXPIRE_TRC_size

// BMT_STOP_TIMER_START_TRC
#define BMT_STOP_TIMER_START_TRC_size NULL
#define BMT_STOP_TIMER_START_TRC BMT_STOP_TIMER_START_TRC__enum,BMT_STOP_TIMER_START_TRC_size

// BMT_STOP_TIMER_STOP_TRC
#define BMT_STOP_TIMER_STOP_TRC_size NULL
#define BMT_STOP_TIMER_STOP_TRC BMT_STOP_TIMER_STOP_TRC__enum,BMT_STOP_TIMER_STOP_TRC_size

// BMT_TOP_OFF_TIMER_EXPIRE_TRC
#define BMT_TOP_OFF_TIMER_EXPIRE_TRC_size NULL
#define BMT_TOP_OFF_TIMER_EXPIRE_TRC BMT_TOP_OFF_TIMER_EXPIRE_TRC__enum,BMT_TOP_OFF_TIMER_EXPIRE_TRC_size

// BMT_TOP_OFF_TIMER_START_TRC
#define BMT_TOP_OFF_TIMER_START_TRC_size NULL
#define BMT_TOP_OFF_TIMER_START_TRC BMT_TOP_OFF_TIMER_START_TRC__enum,BMT_TOP_OFF_TIMER_START_TRC_size

// BMT_TOP_OFF_TIMER_STOP_TRC
#define BMT_TOP_OFF_TIMER_STOP_TRC_size NULL
#define BMT_TOP_OFF_TIMER_STOP_TRC BMT_TOP_OFF_TIMER_STOP_TRC__enum,BMT_TOP_OFF_TIMER_STOP_TRC_size

// BMT_ERROR_CHECK_TRC
#define BMT_ERROR_CHECK_TRC_size NULL
#define BMT_ERROR_CHECK_TRC BMT_ERROR_CHECK_TRC__enum,BMT_ERROR_CHECK_TRC_size

// BMT_ULC_SW_PLUGOUT_TRC
#define BMT_ULC_SW_PLUGOUT_TRC_size NULL
#define BMT_ULC_SW_PLUGOUT_TRC BMT_ULC_SW_PLUGOUT_TRC__enum,BMT_ULC_SW_PLUGOUT_TRC_size

// BMT_OBTAIN_PHY_STAT_TRC
#define BMT_OBTAIN_PHY_STAT_TRC_size NULL
#define BMT_OBTAIN_PHY_STAT_TRC BMT_OBTAIN_PHY_STAT_TRC__enum,BMT_OBTAIN_PHY_STAT_TRC_size

// BMT_CHARGE_ENABLE_TRC
#define BMT_CHARGE_ENABLE_TRC_size "d"
#define BMT_CHARGE_ENABLE_TRC BMT_CHARGE_ENABLE_TRC__enum,BMT_CHARGE_ENABLE_TRC_size

// BMT_RECHARGE_START_TRC
#define BMT_RECHARGE_START_TRC_size NULL
#define BMT_RECHARGE_START_TRC BMT_RECHARGE_START_TRC__enum,BMT_RECHARGE_START_TRC_size

// BMT_CHARGE_FULL_TRC
#define BMT_CHARGE_FULL_TRC_size "d"
#define BMT_CHARGE_FULL_TRC BMT_CHARGE_FULL_TRC__enum,BMT_CHARGE_FULL_TRC_size

// BMT_PMU_DO_NOT_SUPPORT_TRC
#define BMT_PMU_DO_NOT_SUPPORT_TRC_size "d"
#define BMT_PMU_DO_NOT_SUPPORT_TRC BMT_PMU_DO_NOT_SUPPORT_TRC__enum,BMT_PMU_DO_NOT_SUPPORT_TRC_size

// BMT_ERRORCHECK_AT_CHARGE_ON_TRC
#define BMT_ERRORCHECK_AT_CHARGE_ON_TRC_size NULL
#define BMT_ERRORCHECK_AT_CHARGE_ON_TRC BMT_ERRORCHECK_AT_CHARGE_ON_TRC__enum,BMT_ERRORCHECK_AT_CHARGE_ON_TRC_size

// BMT_ERRORCHECK_AT_CHARGE_OFF_TRC
#define BMT_ERRORCHECK_AT_CHARGE_OFF_TRC_size NULL
#define BMT_ERRORCHECK_AT_CHARGE_OFF_TRC BMT_ERRORCHECK_AT_CHARGE_OFF_TRC__enum,BMT_ERRORCHECK_AT_CHARGE_OFF_TRC_size

// BMT_ERRORCHECK_ON_COUNT_TRC
#define BMT_ERRORCHECK_ON_COUNT_TRC_size "d"
#define BMT_ERRORCHECK_ON_COUNT_TRC BMT_ERRORCHECK_ON_COUNT_TRC__enum,BMT_ERRORCHECK_ON_COUNT_TRC_size

// BMT_ERRORCHECK_OFF_COUNT_TRC
#define BMT_ERRORCHECK_OFF_COUNT_TRC_size "d"
#define BMT_ERRORCHECK_OFF_COUNT_TRC BMT_ERRORCHECK_OFF_COUNT_TRC__enum,BMT_ERRORCHECK_OFF_COUNT_TRC_size

// BMT_SW_WORKAROUND_FLAG_TRUE_TRC
#define BMT_SW_WORKAROUND_FLAG_TRUE_TRC_size NULL
#define BMT_SW_WORKAROUND_FLAG_TRUE_TRC BMT_SW_WORKAROUND_FLAG_TRUE_TRC__enum,BMT_SW_WORKAROUND_FLAG_TRUE_TRC_size

// BMT_SW_WORKAROUND_FLAG_FALSE_TRC
#define BMT_SW_WORKAROUND_FLAG_FALSE_TRC_size NULL
#define BMT_SW_WORKAROUND_FLAG_FALSE_TRC BMT_SW_WORKAROUND_FLAG_FALSE_TRC__enum,BMT_SW_WORKAROUND_FLAG_FALSE_TRC_size

// BMT_INSIDE_SW_WORKAROUND_RANGE_TRC
#define BMT_INSIDE_SW_WORKAROUND_RANGE_TRC_size NULL
#define BMT_INSIDE_SW_WORKAROUND_RANGE_TRC BMT_INSIDE_SW_WORKAROUND_RANGE_TRC__enum,BMT_INSIDE_SW_WORKAROUND_RANGE_TRC_size

// BMT_OUTSIDE_SW_WORKAROUND_RANGE_TRC
#define BMT_OUTSIDE_SW_WORKAROUND_RANGE_TRC_size NULL
#define BMT_OUTSIDE_SW_WORKAROUND_RANGE_TRC BMT_OUTSIDE_SW_WORKAROUND_RANGE_TRC__enum,BMT_OUTSIDE_SW_WORKAROUND_RANGE_TRC_size

// BMT_MISSING_HW_PLUG_OUT_TRC
#define BMT_MISSING_HW_PLUG_OUT_TRC_size NULL
#define BMT_MISSING_HW_PLUG_OUT_TRC BMT_MISSING_HW_PLUG_OUT_TRC__enum,BMT_MISSING_HW_PLUG_OUT_TRC_size

// BMT_SW_PLUG_OUT_TRC
#define BMT_SW_PLUG_OUT_TRC_size NULL
#define BMT_SW_PLUG_OUT_TRC BMT_SW_PLUG_OUT_TRC__enum,BMT_SW_PLUG_OUT_TRC_size

// BMT_PLUG_OUT_FALSE_ALARM_TRC
#define BMT_PLUG_OUT_FALSE_ALARM_TRC_size NULL
#define BMT_PLUG_OUT_FALSE_ALARM_TRC BMT_PLUG_OUT_FALSE_ALARM_TRC__enum,BMT_PLUG_OUT_FALSE_ALARM_TRC_size

// BMT_ENABLE_CHARGE_AT_CHARGE_ON_TRC
#define BMT_ENABLE_CHARGE_AT_CHARGE_ON_TRC_size NULL
#define BMT_ENABLE_CHARGE_AT_CHARGE_ON_TRC BMT_ENABLE_CHARGE_AT_CHARGE_ON_TRC__enum,BMT_ENABLE_CHARGE_AT_CHARGE_ON_TRC_size

// BMT_DISABLE_CHARGE_AT_CHARGE_ON_TRC
#define BMT_DISABLE_CHARGE_AT_CHARGE_ON_TRC_size NULL
#define BMT_DISABLE_CHARGE_AT_CHARGE_ON_TRC BMT_DISABLE_CHARGE_AT_CHARGE_ON_TRC__enum,BMT_DISABLE_CHARGE_AT_CHARGE_ON_TRC_size

// BMT_POSSIBLE_PLUG_OUT_TRC
#define BMT_POSSIBLE_PLUG_OUT_TRC_size NULL
#define BMT_POSSIBLE_PLUG_OUT_TRC BMT_POSSIBLE_PLUG_OUT_TRC__enum,BMT_POSSIBLE_PLUG_OUT_TRC_size

// BMT_LOW_CHARGE_CURRENT_AT_CHARGE_OFF_TRC
#define BMT_LOW_CHARGE_CURRENT_AT_CHARGE_OFF_TRC_size NULL
#define BMT_LOW_CHARGE_CURRENT_AT_CHARGE_OFF_TRC BMT_LOW_CHARGE_CURRENT_AT_CHARGE_OFF_TRC__enum,BMT_LOW_CHARGE_CURRENT_AT_CHARGE_OFF_TRC_size

// BMT_SW_POLLING_CHARGER_OV_TRC
#define BMT_SW_POLLING_CHARGER_OV_TRC_size NULL
#define BMT_SW_POLLING_CHARGER_OV_TRC BMT_SW_POLLING_CHARGER_OV_TRC__enum,BMT_SW_POLLING_CHARGER_OV_TRC_size

// BMT_SW_ENABLE_SLEEP_MODE
#define BMT_SW_ENABLE_SLEEP_MODE_size NULL
#define BMT_SW_ENABLE_SLEEP_MODE BMT_SW_ENABLE_SLEEP_MODE__enum,BMT_SW_ENABLE_SLEEP_MODE_size

// BMT_SW_DISABLE_SLEEP_MODE
#define BMT_SW_DISABLE_SLEEP_MODE_size NULL
#define BMT_SW_DISABLE_SLEEP_MODE BMT_SW_DISABLE_SLEEP_MODE__enum,BMT_SW_DISABLE_SLEEP_MODE_size

// BMT_SET_CUSTOMIZED_CURRENT_TRC
#define BMT_SET_CUSTOMIZED_CURRENT_TRC_size NULL
#define BMT_SET_CUSTOMIZED_CURRENT_TRC BMT_SET_CUSTOMIZED_CURRENT_TRC__enum,BMT_SET_CUSTOMIZED_CURRENT_TRC_size

// BMT_SET_AC_CHARGE_CURRENT_TRC
#define BMT_SET_AC_CHARGE_CURRENT_TRC_size NULL
#define BMT_SET_AC_CHARGE_CURRENT_TRC BMT_SET_AC_CHARGE_CURRENT_TRC__enum,BMT_SET_AC_CHARGE_CURRENT_TRC_size

// BMT_SET_USB_CHARGE_CURRENT_TRC
#define BMT_SET_USB_CHARGE_CURRENT_TRC_size NULL
#define BMT_SET_USB_CHARGE_CURRENT_TRC BMT_SET_USB_CHARGE_CURRENT_TRC__enum,BMT_SET_USB_CHARGE_CURRENT_TRC_size

// BMT_FIND_AND_SET_THE_NEAREST_CURRENT_TRC
#define BMT_FIND_AND_SET_THE_NEAREST_CURRENT_TRC_size "d"
#define BMT_FIND_AND_SET_THE_NEAREST_CURRENT_TRC BMT_FIND_AND_SET_THE_NEAREST_CURRENT_TRC__enum,BMT_FIND_AND_SET_THE_NEAREST_CURRENT_TRC_size

// BMT_CHARGE_CURRENT_AND_LEVEL_TRC
#define BMT_CHARGE_CURRENT_AND_LEVEL_TRC_size "‚d"
#define BMT_CHARGE_CURRENT_AND_LEVEL_TRC BMT_CHARGE_CURRENT_AND_LEVEL_TRC__enum,BMT_CHARGE_CURRENT_AND_LEVEL_TRC_size

// BMT_TOTAL_CHARGE_CURRENT_LEVEL_TRC
#define BMT_TOTAL_CHARGE_CURRENT_LEVEL_TRC_size "d"
#define BMT_TOTAL_CHARGE_CURRENT_LEVEL_TRC BMT_TOTAL_CHARGE_CURRENT_LEVEL_TRC__enum,BMT_TOTAL_CHARGE_CURRENT_LEVEL_TRC_size

// BMT_MIN_CHARGE_CURRENT_TRC
#define BMT_MIN_CHARGE_CURRENT_TRC_size "d"
#define BMT_MIN_CHARGE_CURRENT_TRC BMT_MIN_CHARGE_CURRENT_TRC__enum,BMT_MIN_CHARGE_CURRENT_TRC_size

// BMT_MAX_CHARGE_CURRENT_TRC
#define BMT_MAX_CHARGE_CURRENT_TRC_size "d"
#define BMT_MAX_CHARGE_CURRENT_TRC BMT_MAX_CHARGE_CURRENT_TRC__enum,BMT_MAX_CHARGE_CURRENT_TRC_size

// BMT_CURRENT_CHARGE_CURRENT_TRC
#define BMT_CURRENT_CHARGE_CURRENT_TRC_size "d"
#define BMT_CURRENT_CHARGE_CURRENT_TRC BMT_CURRENT_CHARGE_CURRENT_TRC__enum,BMT_CURRENT_CHARGE_CURRENT_TRC_size

// BMT_PHY_CHECK_OVER_CHARGER_COUNT_TRC
#define BMT_PHY_CHECK_OVER_CHARGER_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_OVER_CHARGER_COUNT_TRC BMT_PHY_CHECK_OVER_CHARGER_COUNT_TRC__enum,BMT_PHY_CHECK_OVER_CHARGER_COUNT_TRC_size

// BMT_PHY_CHECK_OVER_CURRENT_COUNT_TRC
#define BMT_PHY_CHECK_OVER_CURRENT_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_OVER_CURRENT_COUNT_TRC BMT_PHY_CHECK_OVER_CURRENT_COUNT_TRC__enum,BMT_PHY_CHECK_OVER_CURRENT_COUNT_TRC_size

// BMT_PHY_CHECK_LOW_CURRENT_COUNT_TRC
#define BMT_PHY_CHECK_LOW_CURRENT_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_LOW_CURRENT_COUNT_TRC BMT_PHY_CHECK_LOW_CURRENT_COUNT_TRC__enum,BMT_PHY_CHECK_LOW_CURRENT_COUNT_TRC_size

// BMT_PHY_CHECK_LOW_TRMPER_COUNT_TRC
#define BMT_PHY_CHECK_LOW_TRMPER_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_LOW_TRMPER_COUNT_TRC BMT_PHY_CHECK_LOW_TRMPER_COUNT_TRC__enum,BMT_PHY_CHECK_LOW_TRMPER_COUNT_TRC_size

// BMT_PHY_CHECK_OVER_TEMPER_COUNT_TRC
#define BMT_PHY_CHECK_OVER_TEMPER_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_OVER_TEMPER_COUNT_TRC BMT_PHY_CHECK_OVER_TEMPER_COUNT_TRC__enum,BMT_PHY_CHECK_OVER_TEMPER_COUNT_TRC_size

// BMT_PHY_CHECK_RECHARGE_TEMPER_COUNT_TRC
#define BMT_PHY_CHECK_RECHARGE_TEMPER_COUNT_TRC_size "d"
#define BMT_PHY_CHECK_RECHARGE_TEMPER_COUNT_TRC BMT_PHY_CHECK_RECHARGE_TEMPER_COUNT_TRC__enum,BMT_PHY_CHECK_RECHARGE_TEMPER_COUNT_TRC_size

// BMT_ADC_MEASURE_WARNING_TRC
#define BMT_ADC_MEASURE_WARNING_TRC_size "ƒd"
#define BMT_ADC_MEASURE_WARNING_TRC BMT_ADC_MEASURE_WARNING_TRC__enum,BMT_ADC_MEASURE_WARNING_TRC_size

// BMT_ILLEGAL_PHY_ADC_CHANNEL_TRC
#define BMT_ILLEGAL_PHY_ADC_CHANNEL_TRC_size NULL
#define BMT_ILLEGAL_PHY_ADC_CHANNEL_TRC BMT_ILLEGAL_PHY_ADC_CHANNEL_TRC__enum,BMT_ILLEGAL_PHY_ADC_CHANNEL_TRC_size

// BMT_ADC_CALIBRATION_FAIL_TRC
#define BMT_ADC_CALIBRATION_FAIL_TRC_size "d"
#define BMT_ADC_CALIBRATION_FAIL_TRC BMT_ADC_CALIBRATION_FAIL_TRC__enum,BMT_ADC_CALIBRATION_FAIL_TRC_size

// BMT_ADC_NO_CALIBRATION_TRC
#define BMT_ADC_NO_CALIBRATION_TRC_size "‚d"
#define BMT_ADC_NO_CALIBRATION_TRC BMT_ADC_NO_CALIBRATION_TRC__enum,BMT_ADC_NO_CALIBRATION_TRC_size

// BMT_ADC_CALLBACK_INFO_TRC
#define BMT_ADC_CALLBACK_INFO_TRC_size "ƒd"
#define BMT_ADC_CALLBACK_INFO_TRC BMT_ADC_CALLBACK_INFO_TRC__enum,BMT_ADC_CALLBACK_INFO_TRC_size

// BMT_ADC_SW_RESET_TRC
#define BMT_ADC_SW_RESET_TRC_size "d"
#define BMT_ADC_SW_RESET_TRC BMT_ADC_SW_RESET_TRC__enum,BMT_ADC_SW_RESET_TRC_size

// BMT_ADC_BUSY_STATUS_TRC
#define BMT_ADC_BUSY_STATUS_TRC_size "ƒd"
#define BMT_ADC_BUSY_STATUS_TRC BMT_ADC_BUSY_STATUS_TRC__enum,BMT_ADC_BUSY_STATUS_TRC_size

// BMT_ADC_RAW_DATA
#define BMT_ADC_RAW_DATA_size "„d"
#define BMT_ADC_RAW_DATA BMT_ADC_RAW_DATA__enum,BMT_ADC_RAW_DATA_size

// BMT_ADC_INVALD_VBAT_RESET
#define BMT_ADC_INVALD_VBAT_RESET_size "d"
#define BMT_ADC_INVALD_VBAT_RESET BMT_ADC_INVALD_VBAT_RESET__enum,BMT_ADC_INVALD_VBAT_RESET_size

// BMT_OAM_DELTA_TIME
#define BMT_OAM_DELTA_TIME_size "ƒd"
#define BMT_OAM_DELTA_TIME BMT_OAM_DELTA_TIME__enum,BMT_OAM_DELTA_TIME_size

// BMT_OAM_IMP_TRACKING
#define BMT_OAM_IMP_TRACKING_size "„d"
#define BMT_OAM_IMP_TRACKING BMT_OAM_IMP_TRACKING__enum,BMT_OAM_IMP_TRACKING_size

// BMT_OAM_INIT_INF
#define BMT_OAM_INIT_INF_size "†d"
#define BMT_OAM_INIT_INF BMT_OAM_INIT_INF__enum,BMT_OAM_INIT_INF_size

// BMT_OAM_INIT_RAW_INF
#define BMT_OAM_INIT_RAW_INF_size "†d"
#define BMT_OAM_INIT_RAW_INF BMT_OAM_INIT_RAW_INF__enum,BMT_OAM_INIT_RAW_INF_size

// BMT_OAM_RUN_INF1
#define BMT_OAM_RUN_INF1_size "‡d"
#define BMT_OAM_RUN_INF1 BMT_OAM_RUN_INF1__enum,BMT_OAM_RUN_INF1_size

// BMT_OAM_RUN_RAW_INF1
#define BMT_OAM_RUN_RAW_INF1_size "‡d"
#define BMT_OAM_RUN_RAW_INF1 BMT_OAM_RUN_RAW_INF1__enum,BMT_OAM_RUN_RAW_INF1_size

// BMT_OAM_RUN_INF2
#define BMT_OAM_RUN_INF2_size "„d"
#define BMT_OAM_RUN_INF2 BMT_OAM_RUN_INF2__enum,BMT_OAM_RUN_INF2_size

// BMT_OAM_RUN_RAW_INF2
#define BMT_OAM_RUN_RAW_INF2_size "„d"
#define BMT_OAM_RUN_RAW_INF2 BMT_OAM_RUN_RAW_INF2__enum,BMT_OAM_RUN_RAW_INF2_size

// BMT_OAM_RESULT_INF
#define BMT_OAM_RESULT_INF_size "‡d"
#define BMT_OAM_RESULT_INF BMT_OAM_RESULT_INF__enum,BMT_OAM_RESULT_INF_size

// BMT_OAM_RESULT_RAW_INF
#define BMT_OAM_RESULT_RAW_INF_size "‡d"
#define BMT_OAM_RESULT_RAW_INF BMT_OAM_RESULT_RAW_INF__enum,BMT_OAM_RESULT_RAW_INF_size

// BMT_OAM_R_V_TABLE
#define BMT_OAM_R_V_TABLE_size "ƒd"
#define BMT_OAM_R_V_TABLE BMT_OAM_R_V_TABLE__enum,BMT_OAM_R_V_TABLE_size

// BMT_OAM_DOD_V_TABLE
#define BMT_OAM_DOD_V_TABLE_size "ƒd"
#define BMT_OAM_DOD_V_TABLE BMT_OAM_DOD_V_TABLE__enum,BMT_OAM_DOD_V_TABLE_size

// BMT_OAM_FULL_RESET
#define BMT_OAM_FULL_RESET_size NULL
#define BMT_OAM_FULL_RESET BMT_OAM_FULL_RESET__enum,BMT_OAM_FULL_RESET_size

// BMT_OAM_100_TRACKING
#define BMT_OAM_100_TRACKING_size "‚d"
#define BMT_OAM_100_TRACKING BMT_OAM_100_TRACKING__enum,BMT_OAM_100_TRACKING_size

// BMT_OAM_0_TRACKING
#define BMT_OAM_0_TRACKING_size "‚d"
#define BMT_OAM_0_TRACKING BMT_OAM_0_TRACKING__enum,BMT_OAM_0_TRACKING_size

// BMT_OAM_RESET_DOD
#define BMT_OAM_RESET_DOD_size "‚d"
#define BMT_OAM_RESET_DOD BMT_OAM_RESET_DOD__enum,BMT_OAM_RESET_DOD_size

// BMT_OAM_RECHARGE
#define BMT_OAM_RECHARGE_size "d"
#define BMT_OAM_RECHARGE BMT_OAM_RECHARGE__enum,BMT_OAM_RECHARGE_size

// BMT_OAM_SYNC_SOC
#define BMT_OAM_SYNC_SOC_size "ƒd"
#define BMT_OAM_SYNC_SOC BMT_OAM_SYNC_SOC__enum,BMT_OAM_SYNC_SOC_size

// BMT_OAM_QMAX_UPDATE
#define BMT_OAM_QMAX_UPDATE_size "„d"
#define BMT_OAM_QMAX_UPDATE BMT_OAM_QMAX_UPDATE__enum,BMT_OAM_QMAX_UPDATE_size

// BMT_OAM_SOC_INIT
#define BMT_OAM_SOC_INIT_size "ƒd"
#define BMT_OAM_SOC_INIT BMT_OAM_SOC_INIT__enum,BMT_OAM_SOC_INIT_size

// BMT_OAM_GET_QMAX
#define BMT_OAM_GET_QMAX_size "d"
#define BMT_OAM_GET_QMAX BMT_OAM_GET_QMAX__enum,BMT_OAM_GET_QMAX_size

// BMT_OAM_CONSTRUCT_TABLE
#define BMT_OAM_CONSTRUCT_TABLE_size "‚d"
#define BMT_OAM_CONSTRUCT_TABLE BMT_OAM_CONSTRUCT_TABLE__enum,BMT_OAM_CONSTRUCT_TABLE_size

// BMT_CABLE_IN_TRC
#define BMT_CABLE_IN_TRC_size NULL
#define BMT_CABLE_IN_TRC BMT_CABLE_IN_TRC__enum,BMT_CABLE_IN_TRC_size

// BMT_AC_IN_TRC
#define BMT_AC_IN_TRC_size NULL
#define BMT_AC_IN_TRC BMT_AC_IN_TRC__enum,BMT_AC_IN_TRC_size

// BMT_NON_AC_IN_TRC
#define BMT_NON_AC_IN_TRC_size NULL
#define BMT_NON_AC_IN_TRC BMT_NON_AC_IN_TRC__enum,BMT_NON_AC_IN_TRC_size

// BMT_CABLE_OUT_TRC
#define BMT_CABLE_OUT_TRC_size NULL
#define BMT_CABLE_OUT_TRC BMT_CABLE_OUT_TRC__enum,BMT_CABLE_OUT_TRC_size

// BMT_INV_AC_IN_TRC
#define BMT_INV_AC_IN_TRC_size NULL
#define BMT_INV_AC_IN_TRC BMT_INV_AC_IN_TRC__enum,BMT_INV_AC_IN_TRC_size

// BMT_AC_OUT_TRC
#define BMT_AC_OUT_TRC_size NULL
#define BMT_AC_OUT_TRC BMT_AC_OUT_TRC__enum,BMT_AC_OUT_TRC_size

// BMT_USB_IN_TRC
#define BMT_USB_IN_TRC_size NULL
#define BMT_USB_IN_TRC BMT_USB_IN_TRC__enum,BMT_USB_IN_TRC_size

// BMT_USB_CHARGING_HOST_IN_TRC
#define BMT_USB_CHARGING_HOST_IN_TRC_size NULL
#define BMT_USB_CHARGING_HOST_IN_TRC BMT_USB_CHARGING_HOST_IN_TRC__enum,BMT_USB_CHARGING_HOST_IN_TRC_size

// BMT_USB_IN_WAIT_500_TRC
#define BMT_USB_IN_WAIT_500_TRC_size NULL
#define BMT_USB_IN_WAIT_500_TRC BMT_USB_IN_WAIT_500_TRC__enum,BMT_USB_IN_WAIT_500_TRC_size

// BMT_USB_OUT_TRC
#define BMT_USB_OUT_TRC_size NULL
#define BMT_USB_OUT_TRC BMT_USB_OUT_TRC__enum,BMT_USB_OUT_TRC_size

// BMT_USB_100_TRC
#define BMT_USB_100_TRC_size NULL
#define BMT_USB_100_TRC BMT_USB_100_TRC__enum,BMT_USB_100_TRC_size

// BMT_USB_500_TRC
#define BMT_USB_500_TRC_size NULL
#define BMT_USB_500_TRC BMT_USB_500_TRC__enum,BMT_USB_500_TRC_size

// BMT_CHR_STATUS_CHARGE_IN_TRC
#define BMT_CHR_STATUS_CHARGE_IN_TRC_size NULL
#define BMT_CHR_STATUS_CHARGE_IN_TRC BMT_CHR_STATUS_CHARGE_IN_TRC__enum,BMT_CHR_STATUS_CHARGE_IN_TRC_size

// BMT_CHR_STATUS_CHARGE_OUT_TRC
#define BMT_CHR_STATUS_CHARGE_OUT_TRC_size NULL
#define BMT_CHR_STATUS_CHARGE_OUT_TRC BMT_CHR_STATUS_CHARGE_OUT_TRC__enum,BMT_CHR_STATUS_CHARGE_OUT_TRC_size

// BMT_USB_STATE_TRC
#define BMT_USB_STATE_TRC_size "d"
#define BMT_USB_STATE_TRC BMT_USB_STATE_TRC__enum,BMT_USB_STATE_TRC_size

// BMT_HW_PLUG_OUT_INSIDE_SW_WORKAROUND_RANGE_TRC
#define BMT_HW_PLUG_OUT_INSIDE_SW_WORKAROUND_RANGE_TRC_size NULL
#define BMT_HW_PLUG_OUT_INSIDE_SW_WORKAROUND_RANGE_TRC BMT_HW_PLUG_OUT_INSIDE_SW_WORKAROUND_RANGE_TRC__enum,BMT_HW_PLUG_OUT_INSIDE_SW_WORKAROUND_RANGE_TRC_size

// BMT_CHARGING_START_TRC
#define BMT_CHARGING_START_TRC_size NULL
#define BMT_CHARGING_START_TRC BMT_CHARGING_START_TRC__enum,BMT_CHARGING_START_TRC_size

// BMT_CHARGING_END_TRC
#define BMT_CHARGING_END_TRC_size NULL
#define BMT_CHARGING_END_TRC BMT_CHARGING_END_TRC__enum,BMT_CHARGING_END_TRC_size

// BMT_CHARGING_CURRENT_NOT_SUPPORTED_STOP_CHARGING_TRC
#define BMT_CHARGING_CURRENT_NOT_SUPPORTED_STOP_CHARGING_TRC_size NULL
#define BMT_CHARGING_CURRENT_NOT_SUPPORTED_STOP_CHARGING_TRC BMT_CHARGING_CURRENT_NOT_SUPPORTED_STOP_CHARGING_TRC__enum,BMT_CHARGING_CURRENT_NOT_SUPPORTED_STOP_CHARGING_TRC_size

// BMT_CHARGING_WDT_CLR_TRC
#define BMT_CHARGING_WDT_CLR_TRC_size NULL
#define BMT_CHARGING_WDT_CLR_TRC BMT_CHARGING_WDT_CLR_TRC__enum,BMT_CHARGING_WDT_CLR_TRC_size

// BMT_AC_IN_AND_START_CHARGE_TRC
#define BMT_AC_IN_AND_START_CHARGE_TRC_size NULL
#define BMT_AC_IN_AND_START_CHARGE_TRC BMT_AC_IN_AND_START_CHARGE_TRC__enum,BMT_AC_IN_AND_START_CHARGE_TRC_size

// BMT_INV_AC_IN_AND_START_CHARGE_TRC
#define BMT_INV_AC_IN_AND_START_CHARGE_TRC_size NULL
#define BMT_INV_AC_IN_AND_START_CHARGE_TRC BMT_INV_AC_IN_AND_START_CHARGE_TRC__enum,BMT_INV_AC_IN_AND_START_CHARGE_TRC_size

// BMT_USB_IN_AND_START_CHARGE_TRC
#define BMT_USB_IN_AND_START_CHARGE_TRC_size NULL
#define BMT_USB_IN_AND_START_CHARGE_TRC BMT_USB_IN_AND_START_CHARGE_TRC__enum,BMT_USB_IN_AND_START_CHARGE_TRC_size

// BMT_USB_500_AND_START_CHARGE_TRC
#define BMT_USB_500_AND_START_CHARGE_TRC_size NULL
#define BMT_USB_500_AND_START_CHARGE_TRC BMT_USB_500_AND_START_CHARGE_TRC__enum,BMT_USB_500_AND_START_CHARGE_TRC_size

// BMT_AC_OUT_AND_STOP_CHARGE_TRC
#define BMT_AC_OUT_AND_STOP_CHARGE_TRC_size NULL
#define BMT_AC_OUT_AND_STOP_CHARGE_TRC BMT_AC_OUT_AND_STOP_CHARGE_TRC__enum,BMT_AC_OUT_AND_STOP_CHARGE_TRC_size

// BMT_USB_OUT_AND_STOP_CHARGE_TRC
#define BMT_USB_OUT_AND_STOP_CHARGE_TRC_size NULL
#define BMT_USB_OUT_AND_STOP_CHARGE_TRC BMT_USB_OUT_AND_STOP_CHARGE_TRC__enum,BMT_USB_OUT_AND_STOP_CHARGE_TRC_size

// BMT_USB_500_OUT_AND_STOP_CHARGE_TRC
#define BMT_USB_500_OUT_AND_STOP_CHARGE_TRC_size NULL
#define BMT_USB_500_OUT_AND_STOP_CHARGE_TRC BMT_USB_500_OUT_AND_STOP_CHARGE_TRC__enum,BMT_USB_500_OUT_AND_STOP_CHARGE_TRC_size

// BMT_USB_100_OUT_AND_STOP_CHARGE_TRC
#define BMT_USB_100_OUT_AND_STOP_CHARGE_TRC_size NULL
#define BMT_USB_100_OUT_AND_STOP_CHARGE_TRC BMT_USB_100_OUT_AND_STOP_CHARGE_TRC__enum,BMT_USB_100_OUT_AND_STOP_CHARGE_TRC_size

// BMT_USB_100_OUT_TRC
#define BMT_USB_100_OUT_TRC_size NULL
#define BMT_USB_100_OUT_TRC BMT_USB_100_OUT_TRC__enum,BMT_USB_100_OUT_TRC_size

// BMT_AC_OUT_USB_STILL_IN_KEEP_CHARGING_TRC
#define BMT_AC_OUT_USB_STILL_IN_KEEP_CHARGING_TRC_size NULL
#define BMT_AC_OUT_USB_STILL_IN_KEEP_CHARGING_TRC BMT_AC_OUT_USB_STILL_IN_KEEP_CHARGING_TRC__enum,BMT_AC_OUT_USB_STILL_IN_KEEP_CHARGING_TRC_size

// BMT_AC_OUT_USB_500_STILL_IN_KEEP_CHARGING_TRC
#define BMT_AC_OUT_USB_500_STILL_IN_KEEP_CHARGING_TRC_size NULL
#define BMT_AC_OUT_USB_500_STILL_IN_KEEP_CHARGING_TRC BMT_AC_OUT_USB_500_STILL_IN_KEEP_CHARGING_TRC__enum,BMT_AC_OUT_USB_500_STILL_IN_KEEP_CHARGING_TRC_size

// BMT_USB_OUT_AC_STILL_IN_KEEP_CHARGING_TRC
#define BMT_USB_OUT_AC_STILL_IN_KEEP_CHARGING_TRC_size NULL
#define BMT_USB_OUT_AC_STILL_IN_KEEP_CHARGING_TRC BMT_USB_OUT_AC_STILL_IN_KEEP_CHARGING_TRC__enum,BMT_USB_OUT_AC_STILL_IN_KEEP_CHARGING_TRC_size

// BMT_USB_IN_AC_ALREAY_IN_TRC
#define BMT_USB_IN_AC_ALREAY_IN_TRC_size NULL
#define BMT_USB_IN_AC_ALREAY_IN_TRC BMT_USB_IN_AC_ALREAY_IN_TRC__enum,BMT_USB_IN_AC_ALREAY_IN_TRC_size

// BMT_USB_500_AC_ALREAY_IN_TRC
#define BMT_USB_500_AC_ALREAY_IN_TRC_size NULL
#define BMT_USB_500_AC_ALREAY_IN_TRC BMT_USB_500_AC_ALREAY_IN_TRC__enum,BMT_USB_500_AC_ALREAY_IN_TRC_size

// BMT_MSG_TIMER_EXPIRE_TRC
#define BMT_MSG_TIMER_EXPIRE_TRC_size NULL
#define BMT_MSG_TIMER_EXPIRE_TRC BMT_MSG_TIMER_EXPIRE_TRC__enum,BMT_MSG_TIMER_EXPIRE_TRC_size

// BMT_MSG_CHARGER_TRC
#define BMT_MSG_CHARGER_TRC_size NULL
#define BMT_MSG_CHARGER_TRC BMT_MSG_CHARGER_TRC__enum,BMT_MSG_CHARGER_TRC_size

// BMT_MSG_USB_B_OUT
#define BMT_MSG_USB_B_OUT_size NULL
#define BMT_MSG_USB_B_OUT BMT_MSG_USB_B_OUT__enum,BMT_MSG_USB_B_OUT_size

// BMT_MSG_USB_B_IN
#define BMT_MSG_USB_B_IN_size NULL
#define BMT_MSG_USB_B_IN BMT_MSG_USB_B_IN__enum,BMT_MSG_USB_B_IN_size

// BMT_MSG_USB
#define BMT_MSG_USB_size NULL
#define BMT_MSG_USB BMT_MSG_USB__enum,BMT_MSG_USB_size

// BMT_MSG_ADC_ADD
#define BMT_MSG_ADC_ADD_size NULL
#define BMT_MSG_ADC_ADD BMT_MSG_ADC_ADD__enum,BMT_MSG_ADC_ADD_size

// BMT_MSG_ADC_REMOVE
#define BMT_MSG_ADC_REMOVE_size NULL
#define BMT_MSG_ADC_REMOVE BMT_MSG_ADC_REMOVE__enum,BMT_MSG_ADC_REMOVE_size

// BMT_MSG_ADC_PARAM
#define BMT_MSG_ADC_PARAM_size NULL
#define BMT_MSG_ADC_PARAM BMT_MSG_ADC_PARAM__enum,BMT_MSG_ADC_PARAM_size

// BMT_MSG_ADC_PARAM_SLOPE_OFFSET
#define BMT_MSG_ADC_PARAM_SLOPE_OFFSET_size "‚d"
#define BMT_MSG_ADC_PARAM_SLOPE_OFFSET BMT_MSG_ADC_PARAM_SLOPE_OFFSET__enum,BMT_MSG_ADC_PARAM_SLOPE_OFFSET_size

// BMT_MSG_ADC_NVRAM_READ_CNF
#define BMT_MSG_ADC_NVRAM_READ_CNF_size NULL
#define BMT_MSG_ADC_NVRAM_READ_CNF BMT_MSG_ADC_NVRAM_READ_CNF__enum,BMT_MSG_ADC_NVRAM_READ_CNF_size

// BMT_MSG_ADC_NVRAM_SLOPE_OFFSET
#define BMT_MSG_ADC_NVRAM_SLOPE_OFFSET_size "‚d"
#define BMT_MSG_ADC_NVRAM_SLOPE_OFFSET BMT_MSG_ADC_NVRAM_SLOPE_OFFSET__enum,BMT_MSG_ADC_NVRAM_SLOPE_OFFSET_size

// BMT_MSG_ADC_EFUSE
#define BMT_MSG_ADC_EFUSE_size NULL
#define BMT_MSG_ADC_EFUSE BMT_MSG_ADC_EFUSE__enum,BMT_MSG_ADC_EFUSE_size

// BMT_MSG_ADC_EFUSE_SLOPE_OFFSET
#define BMT_MSG_ADC_EFUSE_SLOPE_OFFSET_size "‚d"
#define BMT_MSG_ADC_EFUSE_SLOPE_OFFSET BMT_MSG_ADC_EFUSE_SLOPE_OFFSET__enum,BMT_MSG_ADC_EFUSE_SLOPE_OFFSET_size

// BMT_MSG_ADC_EFUSE_AB
#define BMT_MSG_ADC_EFUSE_AB_size "‚d"
#define BMT_MSG_ADC_EFUSE_AB BMT_MSG_ADC_EFUSE_AB__enum,BMT_MSG_ADC_EFUSE_AB_size

// BMT_MSG_ADC_EFUSE_ADC_SLOPE_OFFSET
#define BMT_MSG_ADC_EFUSE_ADC_SLOPE_OFFSET_size "‚d"
#define BMT_MSG_ADC_EFUSE_ADC_SLOPE_OFFSET BMT_MSG_ADC_EFUSE_ADC_SLOPE_OFFSET__enum,BMT_MSG_ADC_EFUSE_ADC_SLOPE_OFFSET_size

// BMT_MSG_ADC_EFUSE_ADC_CALIBRATION_SLOPE_OFFSET
#define BMT_MSG_ADC_EFUSE_ADC_CALIBRATION_SLOPE_OFFSET_size "„d"
#define BMT_MSG_ADC_EFUSE_ADC_CALIBRATION_SLOPE_OFFSET BMT_MSG_ADC_EFUSE_ADC_CALIBRATION_SLOPE_OFFSET__enum,BMT_MSG_ADC_EFUSE_ADC_CALIBRATION_SLOPE_OFFSET_size

// BMT_MSG_BATT_ON_DET
#define BMT_MSG_BATT_ON_DET_size "d"
#define BMT_MSG_BATT_ON_DET BMT_MSG_BATT_ON_DET__enum,BMT_MSG_BATT_ON_DET_size

// BMT_MSG_BATT_OFF_BLOCK
#define BMT_MSG_BATT_OFF_BLOCK_size NULL
#define BMT_MSG_BATT_OFF_BLOCK BMT_MSG_BATT_OFF_BLOCK__enum,BMT_MSG_BATT_OFF_BLOCK_size

// BMT_MSG_EXT_CABLE_INTR_ENABLE
#define BMT_MSG_EXT_CABLE_INTR_ENABLE_size "d"
#define BMT_MSG_EXT_CABLE_INTR_ENABLE BMT_MSG_EXT_CABLE_INTR_ENABLE__enum,BMT_MSG_EXT_CABLE_INTR_ENABLE_size

// BMT_MSG_EXT_CABLE_IN
#define BMT_MSG_EXT_CABLE_IN_size NULL
#define BMT_MSG_EXT_CABLE_IN BMT_MSG_EXT_CABLE_IN__enum,BMT_MSG_EXT_CABLE_IN_size

// BMT_MSG_EXT_CABLE_OUT
#define BMT_MSG_EXT_CABLE_OUT_size NULL
#define BMT_MSG_EXT_CABLE_OUT BMT_MSG_EXT_CABLE_OUT__enum,BMT_MSG_EXT_CABLE_OUT_size

// BMT_MSG_EXT_CABLE_DBG_1
#define BMT_MSG_EXT_CABLE_DBG_1_size "d"
#define BMT_MSG_EXT_CABLE_DBG_1 BMT_MSG_EXT_CABLE_DBG_1__enum,BMT_MSG_EXT_CABLE_DBG_1_size

// BMT_MSG_EXT_CABLE_DBG_2
#define BMT_MSG_EXT_CABLE_DBG_2_size "‚d"
#define BMT_MSG_EXT_CABLE_DBG_2 BMT_MSG_EXT_CABLE_DBG_2__enum,BMT_MSG_EXT_CABLE_DBG_2_size

// BMT_MSG_EXT_CABLE_DBG_3
#define BMT_MSG_EXT_CABLE_DBG_3_size "‚d"
#define BMT_MSG_EXT_CABLE_DBG_3 BMT_MSG_EXT_CABLE_DBG_3__enum,BMT_MSG_EXT_CABLE_DBG_3_size

// BMT_MSG_EXT_CABLE_DBG_4
#define BMT_MSG_EXT_CABLE_DBG_4_size "„d"
#define BMT_MSG_EXT_CABLE_DBG_4 BMT_MSG_EXT_CABLE_DBG_4__enum,BMT_MSG_EXT_CABLE_DBG_4_size

// BMT_MSG_EXT_CABLE_REPEATED_IN
#define BMT_MSG_EXT_CABLE_REPEATED_IN_size NULL
#define BMT_MSG_EXT_CABLE_REPEATED_IN BMT_MSG_EXT_CABLE_REPEATED_IN__enum,BMT_MSG_EXT_CABLE_REPEATED_IN_size

// BMT_MSG_EXT_CABLE_REPEATED_OUT
#define BMT_MSG_EXT_CABLE_REPEATED_OUT_size NULL
#define BMT_MSG_EXT_CABLE_REPEATED_OUT BMT_MSG_EXT_CABLE_REPEATED_OUT__enum,BMT_MSG_EXT_CABLE_REPEATED_OUT_size

// BMT_MSG_EXT_CABLE_USB_IN
#define BMT_MSG_EXT_CABLE_USB_IN_size NULL
#define BMT_MSG_EXT_CABLE_USB_IN BMT_MSG_EXT_CABLE_USB_IN__enum,BMT_MSG_EXT_CABLE_USB_IN_size

// BMT_MSG_EXT_CABLE_USB_OUT
#define BMT_MSG_EXT_CABLE_USB_OUT_size NULL
#define BMT_MSG_EXT_CABLE_USB_OUT BMT_MSG_EXT_CABLE_USB_OUT__enum,BMT_MSG_EXT_CABLE_USB_OUT_size

// BMT_MSG_EXT_CABLE_AC_IN
#define BMT_MSG_EXT_CABLE_AC_IN_size NULL
#define BMT_MSG_EXT_CABLE_AC_IN BMT_MSG_EXT_CABLE_AC_IN__enum,BMT_MSG_EXT_CABLE_AC_IN_size

// BMT_MSG_EXT_CABLE_AC_OUT
#define BMT_MSG_EXT_CABLE_AC_OUT_size NULL
#define BMT_MSG_EXT_CABLE_AC_OUT BMT_MSG_EXT_CABLE_AC_OUT__enum,BMT_MSG_EXT_CABLE_AC_OUT_size

// BMT_MSG_EXT_CABLE_LGTA_IN
#define BMT_MSG_EXT_CABLE_LGTA_IN_size NULL
#define BMT_MSG_EXT_CABLE_LGTA_IN BMT_MSG_EXT_CABLE_LGTA_IN__enum,BMT_MSG_EXT_CABLE_LGTA_IN_size

// BMT_MSG_EXT_CABLE_LGTA_OUT
#define BMT_MSG_EXT_CABLE_LGTA_OUT_size NULL
#define BMT_MSG_EXT_CABLE_LGTA_OUT BMT_MSG_EXT_CABLE_LGTA_OUT__enum,BMT_MSG_EXT_CABLE_LGTA_OUT_size

// BMT_MSG_EXT_CABLE_FAC_USB_IN
#define BMT_MSG_EXT_CABLE_FAC_USB_IN_size NULL
#define BMT_MSG_EXT_CABLE_FAC_USB_IN BMT_MSG_EXT_CABLE_FAC_USB_IN__enum,BMT_MSG_EXT_CABLE_FAC_USB_IN_size

// BMT_MSG_EXT_CABLE_FAC_USB_OUT
#define BMT_MSG_EXT_CABLE_FAC_USB_OUT_size NULL
#define BMT_MSG_EXT_CABLE_FAC_USB_OUT BMT_MSG_EXT_CABLE_FAC_USB_OUT__enum,BMT_MSG_EXT_CABLE_FAC_USB_OUT_size

// BMT_MSG_EXT_CABLE_FAC_UART_IN
#define BMT_MSG_EXT_CABLE_FAC_UART_IN_size NULL
#define BMT_MSG_EXT_CABLE_FAC_UART_IN BMT_MSG_EXT_CABLE_FAC_UART_IN__enum,BMT_MSG_EXT_CABLE_FAC_UART_IN_size

// BMT_MSG_EXT_CABLE_FAC_UART_OUT
#define BMT_MSG_EXT_CABLE_FAC_UART_OUT_size NULL
#define BMT_MSG_EXT_CABLE_FAC_UART_OUT BMT_MSG_EXT_CABLE_FAC_UART_OUT__enum,BMT_MSG_EXT_CABLE_FAC_UART_OUT_size

// BMT_MSG_EXT_CABLE_EARPHONE_IN
#define BMT_MSG_EXT_CABLE_EARPHONE_IN_size NULL
#define BMT_MSG_EXT_CABLE_EARPHONE_IN BMT_MSG_EXT_CABLE_EARPHONE_IN__enum,BMT_MSG_EXT_CABLE_EARPHONE_IN_size

// BMT_MSG_EXT_CABLE_EARPHONE_OUT
#define BMT_MSG_EXT_CABLE_EARPHONE_OUT_size NULL
#define BMT_MSG_EXT_CABLE_EARPHONE_OUT BMT_MSG_EXT_CABLE_EARPHONE_OUT__enum,BMT_MSG_EXT_CABLE_EARPHONE_OUT_size

// BMT_MSG_EXT_CABLE_KEY_PRESSED
#define BMT_MSG_EXT_CABLE_KEY_PRESSED_size NULL
#define BMT_MSG_EXT_CABLE_KEY_PRESSED BMT_MSG_EXT_CABLE_KEY_PRESSED__enum,BMT_MSG_EXT_CABLE_KEY_PRESSED_size

// BMT_MSG_EXT_CABLE_KEY_RELEASED
#define BMT_MSG_EXT_CABLE_KEY_RELEASED_size NULL
#define BMT_MSG_EXT_CABLE_KEY_RELEASED BMT_MSG_EXT_CABLE_KEY_RELEASED__enum,BMT_MSG_EXT_CABLE_KEY_RELEASED_size

// BMT_MSG_EXT_CABLE_VIDEO_IN
#define BMT_MSG_EXT_CABLE_VIDEO_IN_size NULL
#define BMT_MSG_EXT_CABLE_VIDEO_IN BMT_MSG_EXT_CABLE_VIDEO_IN__enum,BMT_MSG_EXT_CABLE_VIDEO_IN_size

// BMT_MSG_EXT_CABLE_VIDEO_OUT
#define BMT_MSG_EXT_CABLE_VIDEO_OUT_size NULL
#define BMT_MSG_EXT_CABLE_VIDEO_OUT BMT_MSG_EXT_CABLE_VIDEO_OUT__enum,BMT_MSG_EXT_CABLE_VIDEO_OUT_size

// BMT_MSG_EXT_CABLE_OTG_IN
#define BMT_MSG_EXT_CABLE_OTG_IN_size NULL
#define BMT_MSG_EXT_CABLE_OTG_IN BMT_MSG_EXT_CABLE_OTG_IN__enum,BMT_MSG_EXT_CABLE_OTG_IN_size

// BMT_MSG_EXT_CABLE_OTG_OUT
#define BMT_MSG_EXT_CABLE_OTG_OUT_size NULL
#define BMT_MSG_EXT_CABLE_OTG_OUT BMT_MSG_EXT_CABLE_OTG_OUT__enum,BMT_MSG_EXT_CABLE_OTG_OUT_size

// BMT_MSG_EXT_CABLE_UNKNOWN_IN
#define BMT_MSG_EXT_CABLE_UNKNOWN_IN_size NULL
#define BMT_MSG_EXT_CABLE_UNKNOWN_IN BMT_MSG_EXT_CABLE_UNKNOWN_IN__enum,BMT_MSG_EXT_CABLE_UNKNOWN_IN_size

// BMT_MSG_EXT_CABLE_UNKNOWN_OUT
#define BMT_MSG_EXT_CABLE_UNKNOWN_OUT_size NULL
#define BMT_MSG_EXT_CABLE_UNKNOWN_OUT BMT_MSG_EXT_CABLE_UNKNOWN_OUT__enum,BMT_MSG_EXT_CABLE_UNKNOWN_OUT_size

// BMT_MSG_EXT_CABLE_FAC_MODE
#define BMT_MSG_EXT_CABLE_FAC_MODE_size NULL
#define BMT_MSG_EXT_CABLE_FAC_MODE BMT_MSG_EXT_CABLE_FAC_MODE__enum,BMT_MSG_EXT_CABLE_FAC_MODE_size

// BMT_MSG_EXT_CABLE_FAC_MODE_AC_IN
#define BMT_MSG_EXT_CABLE_FAC_MODE_AC_IN_size NULL
#define BMT_MSG_EXT_CABLE_FAC_MODE_AC_IN BMT_MSG_EXT_CABLE_FAC_MODE_AC_IN__enum,BMT_MSG_EXT_CABLE_FAC_MODE_AC_IN_size

// BMT_MSG_EXT_CABLE_FAC_MODE_AC_OUT
#define BMT_MSG_EXT_CABLE_FAC_MODE_AC_OUT_size NULL
#define BMT_MSG_EXT_CABLE_FAC_MODE_AC_OUT BMT_MSG_EXT_CABLE_FAC_MODE_AC_OUT__enum,BMT_MSG_EXT_CABLE_FAC_MODE_AC_OUT_size

// BMT_MSG_EXT_CABLE_REPEATED_IN_HISR
#define BMT_MSG_EXT_CABLE_REPEATED_IN_HISR_size NULL
#define BMT_MSG_EXT_CABLE_REPEATED_IN_HISR BMT_MSG_EXT_CABLE_REPEATED_IN_HISR__enum,BMT_MSG_EXT_CABLE_REPEATED_IN_HISR_size

// BMT_MSG_EXT_CABLE_FAC_MODE_DIS_SLEEP
#define BMT_MSG_EXT_CABLE_FAC_MODE_DIS_SLEEP_size NULL
#define BMT_MSG_EXT_CABLE_FAC_MODE_DIS_SLEEP BMT_MSG_EXT_CABLE_FAC_MODE_DIS_SLEEP__enum,BMT_MSG_EXT_CABLE_FAC_MODE_DIS_SLEEP_size

// BMT_MSG_EXT_CABLE_FAC_MODE_EN_SLEEP
#define BMT_MSG_EXT_CABLE_FAC_MODE_EN_SLEEP_size NULL
#define BMT_MSG_EXT_CABLE_FAC_MODE_EN_SLEEP BMT_MSG_EXT_CABLE_FAC_MODE_EN_SLEEP__enum,BMT_MSG_EXT_CABLE_FAC_MODE_EN_SLEEP_size

// BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_REQ
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_REQ_size NULL
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_REQ BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_REQ__enum,BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_REQ_size

// BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_REQ
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_REQ_size NULL
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_REQ BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_REQ__enum,BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_REQ_size

// BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_size NULL
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE__enum,BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_OFF_EARPHONE_size

// BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_size NULL
#define BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE__enum,BMT_MSG_EXT_CABLE_EXT_AUDIO_WA_TURN_ON_EARPHONE_size

// BMT_HIGH_VCHG_ENABLED_TRC
#define BMT_HIGH_VCHG_ENABLED_TRC_size NULL
#define BMT_HIGH_VCHG_ENABLED_TRC BMT_HIGH_VCHG_ENABLED_TRC__enum,BMT_HIGH_VCHG_ENABLED_TRC_size

// BMT_HIGH_VCHG_FIRST_TIME_VCHG_TRC
#define BMT_HIGH_VCHG_FIRST_TIME_VCHG_TRC_size "d"
#define BMT_HIGH_VCHG_FIRST_TIME_VCHG_TRC BMT_HIGH_VCHG_FIRST_TIME_VCHG_TRC__enum,BMT_HIGH_VCHG_FIRST_TIME_VCHG_TRC_size

// BMT_HIGH_VCHG_FIRST_TIME_CHARGER_ON_TRC
#define BMT_HIGH_VCHG_FIRST_TIME_CHARGER_ON_TRC_size NULL
#define BMT_HIGH_VCHG_FIRST_TIME_CHARGER_ON_TRC BMT_HIGH_VCHG_FIRST_TIME_CHARGER_ON_TRC__enum,BMT_HIGH_VCHG_FIRST_TIME_CHARGER_ON_TRC_size

// BMT_HIGH_VCHG_CURRENT_VCHG_TRC
#define BMT_HIGH_VCHG_CURRENT_VCHG_TRC_size "d"
#define BMT_HIGH_VCHG_CURRENT_VCHG_TRC BMT_HIGH_VCHG_CURRENT_VCHG_TRC__enum,BMT_HIGH_VCHG_CURRENT_VCHG_TRC_size

// BMT_HIGH_VCHG_AVERAGE_TRC
#define BMT_HIGH_VCHG_AVERAGE_TRC_size "d"
#define BMT_HIGH_VCHG_AVERAGE_TRC BMT_HIGH_VCHG_AVERAGE_TRC__enum,BMT_HIGH_VCHG_AVERAGE_TRC_size

// BMT_HIGH_VCHG_TOO_HIGH_TRC
#define BMT_HIGH_VCHG_TOO_HIGH_TRC_size NULL
#define BMT_HIGH_VCHG_TOO_HIGH_TRC BMT_HIGH_VCHG_TOO_HIGH_TRC__enum,BMT_HIGH_VCHG_TOO_HIGH_TRC_size

// BMT_HIGH_VCHG_LOWEST_THRESHOLD_TRC
#define BMT_HIGH_VCHG_LOWEST_THRESHOLD_TRC_size "d"
#define BMT_HIGH_VCHG_LOWEST_THRESHOLD_TRC BMT_HIGH_VCHG_LOWEST_THRESHOLD_TRC__enum,BMT_HIGH_VCHG_LOWEST_THRESHOLD_TRC_size

// BMT_HIGH_VCHG_UPPER_THRESHOLD_TRC
#define BMT_HIGH_VCHG_UPPER_THRESHOLD_TRC_size "d"
#define BMT_HIGH_VCHG_UPPER_THRESHOLD_TRC BMT_HIGH_VCHG_UPPER_THRESHOLD_TRC__enum,BMT_HIGH_VCHG_UPPER_THRESHOLD_TRC_size

// BMT_HIGH_VCHG_LOWER_THRESHOLD_TRC
#define BMT_HIGH_VCHG_LOWER_THRESHOLD_TRC_size "d"
#define BMT_HIGH_VCHG_LOWER_THRESHOLD_TRC BMT_HIGH_VCHG_LOWER_THRESHOLD_TRC__enum,BMT_HIGH_VCHG_LOWER_THRESHOLD_TRC_size

// BMT_HIGH_VCHG_TABLE_INDEX_TRC
#define BMT_HIGH_VCHG_TABLE_INDEX_TRC_size "d"
#define BMT_HIGH_VCHG_TABLE_INDEX_TRC BMT_HIGH_VCHG_TABLE_INDEX_TRC__enum,BMT_HIGH_VCHG_TABLE_INDEX_TRC_size

// BMT_HIGH_VCHG_SET_USB_CHARGE_CURRENT_TRC
#define BMT_HIGH_VCHG_SET_USB_CHARGE_CURRENT_TRC_size "d"
#define BMT_HIGH_VCHG_SET_USB_CHARGE_CURRENT_TRC BMT_HIGH_VCHG_SET_USB_CHARGE_CURRENT_TRC__enum,BMT_HIGH_VCHG_SET_USB_CHARGE_CURRENT_TRC_size

// BMT_HIGH_VCHG_USB_IN_USE_CUSTOM_CHARGE_CURRENT_TRC
#define BMT_HIGH_VCHG_USB_IN_USE_CUSTOM_CHARGE_CURRENT_TRC_size NULL
#define BMT_HIGH_VCHG_USB_IN_USE_CUSTOM_CHARGE_CURRENT_TRC BMT_HIGH_VCHG_USB_IN_USE_CUSTOM_CHARGE_CURRENT_TRC__enum,BMT_HIGH_VCHG_USB_IN_USE_CUSTOM_CHARGE_CURRENT_TRC_size

// BMT_HIGH_VCHG_CHARGE_CURRENT_TRC
#define BMT_HIGH_VCHG_CHARGE_CURRENT_TRC_size "d"
#define BMT_HIGH_VCHG_CHARGE_CURRENT_TRC BMT_HIGH_VCHG_CHARGE_CURRENT_TRC__enum,BMT_HIGH_VCHG_CHARGE_CURRENT_TRC_size

// BMT_HIGH_VCHG_RUNTIME_APPLY_CHARGE_CURRENT_TRC
#define BMT_HIGH_VCHG_RUNTIME_APPLY_CHARGE_CURRENT_TRC_size "d"
#define BMT_HIGH_VCHG_RUNTIME_APPLY_CHARGE_CURRENT_TRC BMT_HIGH_VCHG_RUNTIME_APPLY_CHARGE_CURRENT_TRC__enum,BMT_HIGH_VCHG_RUNTIME_APPLY_CHARGE_CURRENT_TRC_size

// BMT_HIGH_VCHG_MAX_RESET_TO_ZERO_TRC
#define BMT_HIGH_VCHG_MAX_RESET_TO_ZERO_TRC_size NULL
#define BMT_HIGH_VCHG_MAX_RESET_TO_ZERO_TRC BMT_HIGH_VCHG_MAX_RESET_TO_ZERO_TRC__enum,BMT_HIGH_VCHG_MAX_RESET_TO_ZERO_TRC_size

// BMT_HIGH_VCHG_CUR_VCHG_MAX_TRC
#define BMT_HIGH_VCHG_CUR_VCHG_MAX_TRC_size "d"
#define BMT_HIGH_VCHG_CUR_VCHG_MAX_TRC BMT_HIGH_VCHG_CUR_VCHG_MAX_TRC__enum,BMT_HIGH_VCHG_CUR_VCHG_MAX_TRC_size

// BMT_HIGH_VCHG_VCHG_DIFF_TRC
#define BMT_HIGH_VCHG_VCHG_DIFF_TRC_size "d"
#define BMT_HIGH_VCHG_VCHG_DIFF_TRC BMT_HIGH_VCHG_VCHG_DIFF_TRC__enum,BMT_HIGH_VCHG_VCHG_DIFF_TRC_size

// BMT_HIGH_VCHG_TOTAL_VCHG_TRC
#define BMT_HIGH_VCHG_TOTAL_VCHG_TRC_size "d"
#define BMT_HIGH_VCHG_TOTAL_VCHG_TRC BMT_HIGH_VCHG_TOTAL_VCHG_TRC__enum,BMT_HIGH_VCHG_TOTAL_VCHG_TRC_size

// BMT_HIGH_VCHG_CS_VTH_TRC
#define BMT_HIGH_VCHG_CS_VTH_TRC_size "d"
#define BMT_HIGH_VCHG_CS_VTH_TRC BMT_HIGH_VCHG_CS_VTH_TRC__enum,BMT_HIGH_VCHG_CS_VTH_TRC_size

// BMT_HIGH_VCHG_PRE_CURRENT_LEVEL_TRC
#define BMT_HIGH_VCHG_PRE_CURRENT_LEVEL_TRC_size "d"
#define BMT_HIGH_VCHG_PRE_CURRENT_LEVEL_TRC BMT_HIGH_VCHG_PRE_CURRENT_LEVEL_TRC__enum,BMT_HIGH_VCHG_PRE_CURRENT_LEVEL_TRC_size

// BMT_HIGH_VCHG_CUR_CURRENT_LEVEL_TRC
#define BMT_HIGH_VCHG_CUR_CURRENT_LEVEL_TRC_size "d"
#define BMT_HIGH_VCHG_CUR_CURRENT_LEVEL_TRC BMT_HIGH_VCHG_CUR_CURRENT_LEVEL_TRC__enum,BMT_HIGH_VCHG_CUR_CURRENT_LEVEL_TRC_size

// BMT_HIGH_VCHG_HYSTERESIS_UPPER_BOUND_TRC
#define BMT_HIGH_VCHG_HYSTERESIS_UPPER_BOUND_TRC_size "d"
#define BMT_HIGH_VCHG_HYSTERESIS_UPPER_BOUND_TRC BMT_HIGH_VCHG_HYSTERESIS_UPPER_BOUND_TRC__enum,BMT_HIGH_VCHG_HYSTERESIS_UPPER_BOUND_TRC_size

// BMT_HIGH_VCHG_HYSTERESIS_LOWER_BOUND_TRC
#define BMT_HIGH_VCHG_HYSTERESIS_LOWER_BOUND_TRC_size "d"
#define BMT_HIGH_VCHG_HYSTERESIS_LOWER_BOUND_TRC BMT_HIGH_VCHG_HYSTERESIS_LOWER_BOUND_TRC__enum,BMT_HIGH_VCHG_HYSTERESIS_LOWER_BOUND_TRC_size

// BMT_CURRENT_PMIC_STATE_TRC
#define BMT_CURRENT_PMIC_STATE_TRC_size "d"
#define BMT_CURRENT_PMIC_STATE_TRC BMT_CURRENT_PMIC_STATE_TRC__enum,BMT_CURRENT_PMIC_STATE_TRC_size

// BMT_EXT_INVALID_CHARGER_TRC
#define BMT_EXT_INVALID_CHARGER_TRC_size NULL
#define BMT_EXT_INVALID_CHARGER_TRC BMT_EXT_INVALID_CHARGER_TRC__enum,BMT_EXT_INVALID_CHARGER_TRC_size

// BMT_EXT_ICHARGE_OVER_TRC
#define BMT_EXT_ICHARGE_OVER_TRC_size NULL
#define BMT_EXT_ICHARGE_OVER_TRC BMT_EXT_ICHARGE_OVER_TRC__enum,BMT_EXT_ICHARGE_OVER_TRC_size

// BMT_EXT_ICHARGE_LOW_TRC
#define BMT_EXT_ICHARGE_LOW_TRC_size NULL
#define BMT_EXT_ICHARGE_LOW_TRC BMT_EXT_ICHARGE_LOW_TRC__enum,BMT_EXT_ICHARGE_LOW_TRC_size

// BMT_EXT_VBAT_OVER_TRC
#define BMT_EXT_VBAT_OVER_TRC_size NULL
#define BMT_EXT_VBAT_OVER_TRC BMT_EXT_VBAT_OVER_TRC__enum,BMT_EXT_VBAT_OVER_TRC_size

// BMT_EXT_VTEMP_OVER_TRC
#define BMT_EXT_VTEMP_OVER_TRC_size NULL
#define BMT_EXT_VTEMP_OVER_TRC BMT_EXT_VTEMP_OVER_TRC__enum,BMT_EXT_VTEMP_OVER_TRC_size

// BMT_EXT_VTEMP_LOW_TRC
#define BMT_EXT_VTEMP_LOW_TRC_size NULL
#define BMT_EXT_VTEMP_LOW_TRC BMT_EXT_VTEMP_LOW_TRC__enum,BMT_EXT_VTEMP_LOW_TRC_size

// BMT_EXT_CHR_HOLD_TRC
#define BMT_EXT_CHR_HOLD_TRC_size NULL
#define BMT_EXT_CHR_HOLD_TRC BMT_EXT_CHR_HOLD_TRC__enum,BMT_EXT_CHR_HOLD_TRC_size

// BMT_EXT_VBAT_TRC
#define BMT_EXT_VBAT_TRC_size "d"
#define BMT_EXT_VBAT_TRC BMT_EXT_VBAT_TRC__enum,BMT_EXT_VBAT_TRC_size

// BMT_EXT_BATTMP_TRC
#define BMT_EXT_BATTMP_TRC_size "d"
#define BMT_EXT_BATTMP_TRC BMT_EXT_BATTMP_TRC__enum,BMT_EXT_BATTMP_TRC_size

// BMT_EXT_ICHARGE_TRC
#define BMT_EXT_ICHARGE_TRC_size "d"
#define BMT_EXT_ICHARGE_TRC BMT_EXT_ICHARGE_TRC__enum,BMT_EXT_ICHARGE_TRC_size

// BMT_EXT_VCHARGER_TRC
#define BMT_EXT_VCHARGER_TRC_size "d"
#define BMT_EXT_VCHARGER_TRC BMT_EXT_VCHARGER_TRC__enum,BMT_EXT_VCHARGER_TRC_size

// BMT_SOFT_START_CURRENT_LEVEL
#define BMT_SOFT_START_CURRENT_LEVEL_size "d"
#define BMT_SOFT_START_CURRENT_LEVEL BMT_SOFT_START_CURRENT_LEVEL__enum,BMT_SOFT_START_CURRENT_LEVEL_size


#endif // BMT_TRC_GEN.H
