#ifndef _CISS_TRC_GEN_H_
#define _CISS_TRC_GEN_H_

// Release_Indication_Message_is_received_
#define Release_Indication_Message_is_received__size NULL
#define Release_Indication_Message_is_received_ Release_Indication_Message_is_received___enum,Release_Indication_Message_is_received__size

// Transaction_Identifier_value_is___d
#define Transaction_Identifier_value_is___d_size "d"
#define Transaction_Identifier_value_is___d Transaction_Identifier_value_is___d__enum,Transaction_Identifier_value_is___d_size

// Request_for_New_Mobile_Initiated_Transaction
#define Request_for_New_Mobile_Initiated_Transaction_size NULL
#define Request_for_New_Mobile_Initiated_Transaction Request_for_New_Mobile_Initiated_Transaction__enum,Request_for_New_Mobile_Initiated_Transaction_size

// Timer_Expiry_Message_is_received
#define Timer_Expiry_Message_is_received_size NULL
#define Timer_Expiry_Message_is_received Timer_Expiry_Message_is_received__enum,Timer_Expiry_Message_is_received_size

// ciss_d
#define ciss_d_size "d"
#define ciss_d ciss_d__enum,ciss_d_size

// ciss_dd
#define ciss_dd_size "‚d"
#define ciss_dd ciss_dd__enum,ciss_dd_size

// ciss_ddd
#define ciss_ddd_size "ƒd"
#define ciss_ddd ciss_ddd__enum,ciss_ddd_size

// ciss_dddd
#define ciss_dddd_size "„d"
#define ciss_dddd ciss_dddd__enum,ciss_dddd_size

// ciss_ddddd
#define ciss_ddddd_size "…d"
#define ciss_ddddd ciss_ddddd__enum,ciss_ddddd_size

// ciss_mcd_info
#define ciss_mcd_info_size "ƒd"
#define ciss_mcd_info ciss_mcd_info__enum,ciss_mcd_info_size

// CISS_CONTEXT_INVOKE
#define CISS_CONTEXT_INVOKE_size "cdcd"
#define CISS_CONTEXT_INVOKE CISS_CONTEXT_INVOKE__enum,CISS_CONTEXT_INVOKE_size

// FN_ciss_clear_the_call_with_end_ind
#define FN_ciss_clear_the_call_with_end_ind_size NULL
#define FN_ciss_clear_the_call_with_end_ind FN_ciss_clear_the_call_with_end_ind__enum,FN_ciss_clear_the_call_with_end_ind_size

// FN_ciss_mm_est_intr_handler
#define FN_ciss_mm_est_intr_handler_size NULL
#define FN_ciss_mm_est_intr_handler FN_ciss_mm_est_intr_handler__enum,FN_ciss_mm_est_intr_handler_size

// FN_ciss_send_facility_msg_to_peer
#define FN_ciss_send_facility_msg_to_peer_size NULL
#define FN_ciss_send_facility_msg_to_peer FN_ciss_send_facility_msg_to_peer__enum,FN_ciss_send_facility_msg_to_peer_size

// FN_ciss_deinit
#define FN_ciss_deinit_size NULL
#define FN_ciss_deinit FN_ciss_deinit__enum,FN_ciss_deinit_size

// FN_ciss_form_peer_cause_ie
#define FN_ciss_form_peer_cause_ie_size NULL
#define FN_ciss_form_peer_cause_ie FN_ciss_form_peer_cause_ie__enum,FN_ciss_form_peer_cause_ie_size

// FN_ciss_syntact_err_check_for_rlc
#define FN_ciss_syntact_err_check_for_rlc_size NULL
#define FN_ciss_syntact_err_check_for_rlc FN_ciss_syntact_err_check_for_rlc__enum,FN_ciss_syntact_err_check_for_rlc_size

// FN_ciss_get_causeval_from_peercause
#define FN_ciss_get_causeval_from_peercause_size NULL
#define FN_ciss_get_causeval_from_peercause FN_ciss_get_causeval_from_peercause__enum,FN_ciss_get_causeval_from_peercause_size

// FN_ciss_send_rlc_with_err_comp
#define FN_ciss_send_rlc_with_err_comp_size NULL
#define FN_ciss_send_rlc_with_err_comp FN_ciss_send_rlc_with_err_comp__enum,FN_ciss_send_rlc_with_err_comp_size

// FN_ciss_send_register_msg_hdlr
#define FN_ciss_send_register_msg_hdlr_size NULL
#define FN_ciss_send_register_msg_hdlr FN_ciss_send_register_msg_hdlr__enum,FN_ciss_send_register_msg_hdlr_size

// FN_ciss_send_end_ind_with_peercause
#define FN_ciss_send_end_ind_with_peercause_size NULL
#define FN_ciss_send_end_ind_with_peercause FN_ciss_send_end_ind_with_peercause__enum,FN_ciss_send_end_ind_with_peercause_size

// FN_ciss_form_app_cause_ie
#define FN_ciss_form_app_cause_ie_size NULL
#define FN_ciss_form_app_cause_ie FN_ciss_form_app_cause_ie__enum,FN_ciss_form_app_cause_ie_size

// FN_ciss_covert_as_error_component
#define FN_ciss_covert_as_error_component_size NULL
#define FN_ciss_covert_as_error_component FN_ciss_covert_as_error_component__enum,FN_ciss_covert_as_error_component_size

// FN_ciss_facility_req_handler
#define FN_ciss_facility_req_handler_size NULL
#define FN_ciss_facility_req_handler FN_ciss_facility_req_handler__enum,FN_ciss_facility_req_handler_size

// FN_ciss_end_req_handler
#define FN_ciss_end_req_handler_size NULL
#define FN_ciss_end_req_handler FN_ciss_end_req_handler__enum,FN_ciss_end_req_handler_size

// FN_ciss_release_ind_handler
#define FN_ciss_release_ind_handler_size NULL
#define FN_ciss_release_ind_handler FN_ciss_release_ind_handler__enum,FN_ciss_release_ind_handler_size

// FN_ciss_create_timer
#define FN_ciss_create_timer_size NULL
#define FN_ciss_create_timer FN_ciss_create_timer__enum,FN_ciss_create_timer_size

// FN_ciss_peer_rreject_hdlr
#define FN_ciss_peer_rreject_hdlr_size NULL
#define FN_ciss_peer_rreject_hdlr FN_ciss_peer_rreject_hdlr__enum,FN_ciss_peer_rreject_hdlr_size

// FN_ciss_app_rresult_hdlr
#define FN_ciss_app_rresult_hdlr_size NULL
#define FN_ciss_app_rresult_hdlr FN_ciss_app_rresult_hdlr__enum,FN_ciss_app_rresult_hdlr_size

// FN_ciss_app_invoke_hdlr
#define FN_ciss_app_invoke_hdlr_size NULL
#define FN_ciss_app_invoke_hdlr FN_ciss_app_invoke_hdlr__enum,FN_ciss_app_invoke_hdlr_size

// FN_ciss_syntact_err_check_for_reg
#define FN_ciss_syntact_err_check_for_reg_size NULL
#define FN_ciss_syntact_err_check_for_reg FN_ciss_syntact_err_check_for_reg__enum,FN_ciss_syntact_err_check_for_reg_size

// FN_ciss_get_free_ti
#define FN_ciss_get_free_ti_size NULL
#define FN_ciss_get_free_ti FN_ciss_get_free_ti__enum,FN_ciss_get_free_ti_size

// FN_ciss_get_timeout_value
#define FN_ciss_get_timeout_value_size NULL
#define FN_ciss_get_timeout_value FN_ciss_get_timeout_value__enum,FN_ciss_get_timeout_value_size

// FN_ciss_send_rel_msg_to_app_peer
#define FN_ciss_send_rel_msg_to_app_peer_size NULL
#define FN_ciss_send_rel_msg_to_app_peer FN_ciss_send_rel_msg_to_app_peer__enum,FN_ciss_send_rel_msg_to_app_peer_size

// FN_ciss_send_end_ind_msg_to_app
#define FN_ciss_send_end_ind_msg_to_app_size NULL
#define FN_ciss_send_end_ind_msg_to_app FN_ciss_send_end_ind_msg_to_app__enum,FN_ciss_send_end_ind_msg_to_app_size

// FN_ciss_check_active_ti
#define FN_ciss_check_active_ti_size NULL
#define FN_ciss_check_active_ti FN_ciss_check_active_ti__enum,FN_ciss_check_active_ti_size

// FN_ciss_send_mm_rel_req_hdlr
#define FN_ciss_send_mm_rel_req_hdlr_size NULL
#define FN_ciss_send_mm_rel_req_hdlr FN_ciss_send_mm_rel_req_hdlr__enum,FN_ciss_send_mm_rel_req_hdlr_size

// FN_ciss_init
#define FN_ciss_init_size NULL
#define FN_ciss_init FN_ciss_init__enum,FN_ciss_init_size

// FN_ciss_app_rerror_hdlr
#define FN_ciss_app_rerror_hdlr_size NULL
#define FN_ciss_app_rerror_hdlr FN_ciss_app_rerror_hdlr__enum,FN_ciss_app_rerror_hdlr_size

// FN_ciss_start_timer
#define FN_ciss_start_timer_size NULL
#define FN_ciss_start_timer FN_ciss_start_timer__enum,FN_ciss_start_timer_size

// FN_ciss_main
#define FN_ciss_main_size NULL
#define FN_ciss_main FN_ciss_main__enum,FN_ciss_main_size

// FN_ciss_establish_req_handler
#define FN_ciss_establish_req_handler_size NULL
#define FN_ciss_establish_req_handler FN_ciss_establish_req_handler__enum,FN_ciss_establish_req_handler_size

// FN_ciss_send_end_ind_with_cause
#define FN_ciss_send_end_ind_with_cause_size NULL
#define FN_ciss_send_end_ind_with_cause FN_ciss_send_end_ind_with_cause__enum,FN_ciss_send_end_ind_with_cause_size

// FN_ciss_mm_est_rej_handler
#define FN_ciss_mm_est_rej_handler_size NULL
#define FN_ciss_mm_est_rej_handler FN_ciss_mm_est_rej_handler__enum,FN_ciss_mm_est_rej_handler_size

// FN_ciss_semantic_err_check_for_fac
#define FN_ciss_semantic_err_check_for_fac_size NULL
#define FN_ciss_semantic_err_check_for_fac FN_ciss_semantic_err_check_for_fac__enum,FN_ciss_semantic_err_check_for_fac_size

// FN_ciss_validate_ti
#define FN_ciss_validate_ti_size NULL
#define FN_ciss_validate_ti FN_ciss_validate_ti__enum,FN_ciss_validate_ti_size

// FN_ciss_allocate_invoke_index
#define FN_ciss_allocate_invoke_index_size NULL
#define FN_ciss_allocate_invoke_index FN_ciss_allocate_invoke_index__enum,FN_ciss_allocate_invoke_index_size

// FN_ciss_stop_timer
#define FN_ciss_stop_timer_size NULL
#define FN_ciss_stop_timer FN_ciss_stop_timer__enum,FN_ciss_stop_timer_size

// FN_ciss_fill_ss_version_ind_hdlr
#define FN_ciss_fill_ss_version_ind_hdlr_size NULL
#define FN_ciss_fill_ss_version_ind_hdlr FN_ciss_fill_ss_version_ind_hdlr__enum,FN_ciss_fill_ss_version_ind_hdlr_size

// FN_ciss_send_end_ind_hdlr
#define FN_ciss_send_end_ind_hdlr_size NULL
#define FN_ciss_send_end_ind_hdlr FN_ciss_send_end_ind_hdlr__enum,FN_ciss_send_end_ind_hdlr_size

// FN_ciss_send_rel_compl_msg_to_peer
#define FN_ciss_send_rel_compl_msg_to_peer_size NULL
#define FN_ciss_send_rel_compl_msg_to_peer FN_ciss_send_rel_compl_msg_to_peer__enum,FN_ciss_send_rel_compl_msg_to_peer_size

// FN_ciss_call_tear_down_hdlr
#define FN_ciss_call_tear_down_hdlr_size NULL
#define FN_ciss_call_tear_down_hdlr FN_ciss_call_tear_down_hdlr__enum,FN_ciss_call_tear_down_hdlr_size

// FN_ciss_mm_est_cnf_handler
#define FN_ciss_mm_est_cnf_handler_size NULL
#define FN_ciss_mm_est_cnf_handler FN_ciss_mm_est_cnf_handler__enum,FN_ciss_mm_est_cnf_handler_size

// FN_ciss_get_invoke_id_and_op_code
#define FN_ciss_get_invoke_id_and_op_code_size NULL
#define FN_ciss_get_invoke_id_and_op_code FN_ciss_get_invoke_id_and_op_code__enum,FN_ciss_get_invoke_id_and_op_code_size

// FN_ciss_send_end_ind_without_cause
#define FN_ciss_send_end_ind_without_cause_size NULL
#define FN_ciss_send_end_ind_without_cause FN_ciss_send_end_ind_without_cause__enum,FN_ciss_send_end_ind_without_cause_size

// FN_ciss_is_operation_valid
#define FN_ciss_is_operation_valid_size NULL
#define FN_ciss_is_operation_valid FN_ciss_is_operation_valid__enum,FN_ciss_is_operation_valid_size

// FN_ciss_peer_rresult_hdlr
#define FN_ciss_peer_rresult_hdlr_size NULL
#define FN_ciss_peer_rresult_hdlr FN_ciss_peer_rresult_hdlr__enum,FN_ciss_peer_rresult_hdlr_size

// FN_ciss_covert_as_reject_component
#define FN_ciss_covert_as_reject_component_size NULL
#define FN_ciss_covert_as_reject_component FN_ciss_covert_as_reject_component__enum,FN_ciss_covert_as_reject_component_size

// FN_ciss_send_ilm
#define FN_ciss_send_ilm_size NULL
#define FN_ciss_send_ilm FN_ciss_send_ilm__enum,FN_ciss_send_ilm_size

// FN_ciss_send_rlc_msg_to_peer_app
#define FN_ciss_send_rlc_msg_to_peer_app_size NULL
#define FN_ciss_send_rlc_msg_to_peer_app FN_ciss_send_rlc_msg_to_peer_app__enum,FN_ciss_send_rlc_msg_to_peer_app_size

// FN_ciss_block_ti
#define FN_ciss_block_ti_size NULL
#define FN_ciss_block_ti FN_ciss_block_ti__enum,FN_ciss_block_ti_size

// FN_ciss_semantic_err_check_for_rlc
#define FN_ciss_semantic_err_check_for_rlc_size NULL
#define FN_ciss_semantic_err_check_for_rlc FN_ciss_semantic_err_check_for_rlc__enum,FN_ciss_semantic_err_check_for_rlc_size

// FN_ciss_free_ti
#define FN_ciss_free_ti_size NULL
#define FN_ciss_free_ti FN_ciss_free_ti__enum,FN_ciss_free_ti_size

// FN_ciss_send_begin_ind_msg_to_app
#define FN_ciss_send_begin_ind_msg_to_app_size NULL
#define FN_ciss_send_begin_ind_msg_to_app FN_ciss_send_begin_ind_msg_to_app__enum,FN_ciss_send_begin_ind_msg_to_app_size

// FN_ciss_app_facility_component_hdlr
#define FN_ciss_app_facility_component_hdlr_size NULL
#define FN_ciss_app_facility_component_hdlr FN_ciss_app_facility_component_hdlr__enum,FN_ciss_app_facility_component_hdlr_size

// FN_ciss_reset
#define FN_ciss_reset_size NULL
#define FN_ciss_reset FN_ciss_reset__enum,FN_ciss_reset_size

// FN_ciss_release_complete_hdlr
#define FN_ciss_release_complete_hdlr_size NULL
#define FN_ciss_release_complete_hdlr FN_ciss_release_complete_hdlr__enum,FN_ciss_release_complete_hdlr_size

// FN_ciss_timer_expiry_hdlr
#define FN_ciss_timer_expiry_hdlr_size NULL
#define FN_ciss_timer_expiry_hdlr FN_ciss_timer_expiry_hdlr__enum,FN_ciss_timer_expiry_hdlr_size

// FN_ciss_peer_invoke_hdlr
#define FN_ciss_peer_invoke_hdlr_size NULL
#define FN_ciss_peer_invoke_hdlr FN_ciss_peer_invoke_hdlr__enum,FN_ciss_peer_invoke_hdlr_size

// FN_ciss_data_ind_hdlr
#define FN_ciss_data_ind_hdlr_size NULL
#define FN_ciss_data_ind_hdlr FN_ciss_data_ind_hdlr__enum,FN_ciss_data_ind_hdlr_size

// FN_ciss_free_invoke_ids
#define FN_ciss_free_invoke_ids_size NULL
#define FN_ciss_free_invoke_ids FN_ciss_free_invoke_ids__enum,FN_ciss_free_invoke_ids_size

// FN_ciss_free_invoke_structs
#define FN_ciss_free_invoke_structs_size NULL
#define FN_ciss_free_invoke_structs FN_ciss_free_invoke_structs__enum,FN_ciss_free_invoke_structs_size

// FN_ciss_send_fac_ind_msg_to_app
#define FN_ciss_send_fac_ind_msg_to_app_size NULL
#define FN_ciss_send_fac_ind_msg_to_app FN_ciss_send_fac_ind_msg_to_app__enum,FN_ciss_send_fac_ind_msg_to_app_size

// FN_ciss_context_initialize
#define FN_ciss_context_initialize_size NULL
#define FN_ciss_context_initialize FN_ciss_context_initialize__enum,FN_ciss_context_initialize_size

// FN_ciss_peer_rerror_hdlr
#define FN_ciss_peer_rerror_hdlr_size NULL
#define FN_ciss_peer_rerror_hdlr FN_ciss_peer_rerror_hdlr__enum,FN_ciss_peer_rerror_hdlr_size

// FN_ciss_app_rreject_hdlr
#define FN_ciss_app_rreject_hdlr_size NULL
#define FN_ciss_app_rreject_hdlr FN_ciss_app_rreject_hdlr__enum,FN_ciss_app_rreject_hdlr_size

// FN_ciss_semantic_err_check_for_reg
#define FN_ciss_semantic_err_check_for_reg_size NULL
#define FN_ciss_semantic_err_check_for_reg FN_ciss_semantic_err_check_for_reg__enum,FN_ciss_semantic_err_check_for_reg_size

// FN_ciss_init_ti_pool
#define FN_ciss_init_ti_pool_size NULL
#define FN_ciss_init_ti_pool FN_ciss_init_ti_pool__enum,FN_ciss_init_ti_pool_size

// FN_ciss_send_end_ind_with_reject
#define FN_ciss_send_end_ind_with_reject_size NULL
#define FN_ciss_send_end_ind_with_reject FN_ciss_send_end_ind_with_reject__enum,FN_ciss_send_end_ind_with_reject_size

// FN_ciss_establish_ind_handler
#define FN_ciss_establish_ind_handler_size NULL
#define FN_ciss_establish_ind_handler FN_ciss_establish_ind_handler__enum,FN_ciss_establish_ind_handler_size

// FN_ciss_syntact_err_check_for_fac
#define FN_ciss_syntact_err_check_for_fac_size NULL
#define FN_ciss_syntact_err_check_for_fac FN_ciss_syntact_err_check_for_fac__enum,FN_ciss_syntact_err_check_for_fac_size

// FN_ciss_facility_hdlr
#define FN_ciss_facility_hdlr_size NULL
#define FN_ciss_facility_hdlr FN_ciss_facility_hdlr__enum,FN_ciss_facility_hdlr_size

// FN_ciss_begin_req_handler
#define FN_ciss_begin_req_handler_size NULL
#define FN_ciss_begin_req_handler FN_ciss_begin_req_handler__enum,FN_ciss_begin_req_handler_size

// FN_ciss_send_register_msg_to_peer
#define FN_ciss_send_register_msg_to_peer_size NULL
#define FN_ciss_send_register_msg_to_peer FN_ciss_send_register_msg_to_peer__enum,FN_ciss_send_register_msg_to_peer_size

// FN_ciss_send_rel_compl_with_cause
#define FN_ciss_send_rel_compl_with_cause_size NULL
#define FN_ciss_send_rel_compl_with_cause FN_ciss_send_rel_compl_with_cause__enum,FN_ciss_send_rel_compl_with_cause_size

// FN_ciss_peer_fac_component_hdlr
#define FN_ciss_peer_fac_component_hdlr_size NULL
#define FN_ciss_peer_fac_component_hdlr FN_ciss_peer_fac_component_hdlr__enum,FN_ciss_peer_fac_component_hdlr_size

// CISS_NW_TO_MS_PEER_MSG
#define CISS_NW_TO_MS_PEER_MSG_size "c"
#define CISS_NW_TO_MS_PEER_MSG CISS_NW_TO_MS_PEER_MSG__enum,CISS_NW_TO_MS_PEER_MSG_size

// CISS_MS_TO_NW_PEER_MSG
#define CISS_MS_TO_NW_PEER_MSG_size "c"
#define CISS_MS_TO_NW_PEER_MSG CISS_MS_TO_NW_PEER_MSG__enum,CISS_MS_TO_NW_PEER_MSG_size


#endif // CISS_TRC_GEN.H
