#ifndef _CSM_TRC_GEN_H_
#define _CSM_TRC_GEN_H_

// FN_ENTRY_csmcc_dtmf_pause_timeout_handler
#define FN_ENTRY_csmcc_dtmf_pause_timeout_handler_size NULL
#define FN_ENTRY_csmcc_dtmf_pause_timeout_handler FN_ENTRY_csmcc_dtmf_pause_timeout_handler__enum,FN_ENTRY_csmcc_dtmf_pause_timeout_handler_size

// FN_EXIT_csmcc_dtmf_pause_timeout_handler
#define FN_EXIT_csmcc_dtmf_pause_timeout_handler_size NULL
#define FN_EXIT_csmcc_dtmf_pause_timeout_handler FN_EXIT_csmcc_dtmf_pause_timeout_handler__enum,FN_EXIT_csmcc_dtmf_pause_timeout_handler_size

// FN_ENTRY_csmcc_start_dtmf_pause_timer
#define FN_ENTRY_csmcc_start_dtmf_pause_timer_size NULL
#define FN_ENTRY_csmcc_start_dtmf_pause_timer FN_ENTRY_csmcc_start_dtmf_pause_timer__enum,FN_ENTRY_csmcc_start_dtmf_pause_timer_size

// FN_ENTRY_csmcc_aoc_timeout_handler
#define FN_ENTRY_csmcc_aoc_timeout_handler_size NULL
#define FN_ENTRY_csmcc_aoc_timeout_handler FN_ENTRY_csmcc_aoc_timeout_handler__enum,FN_ENTRY_csmcc_aoc_timeout_handler_size

// FN_EXIT_csmcc_aoc_timeout_handler
#define FN_EXIT_csmcc_aoc_timeout_handler_size NULL
#define FN_EXIT_csmcc_aoc_timeout_handler FN_EXIT_csmcc_aoc_timeout_handler__enum,FN_EXIT_csmcc_aoc_timeout_handler_size

// FN_ENTRY_csmcc_start_aoc_timer
#define FN_ENTRY_csmcc_start_aoc_timer_size NULL
#define FN_ENTRY_csmcc_start_aoc_timer FN_ENTRY_csmcc_start_aoc_timer__enum,FN_ENTRY_csmcc_start_aoc_timer_size

// FN_ENTRY_csmcc_stop_aoc_timer
#define FN_ENTRY_csmcc_stop_aoc_timer_size NULL
#define FN_ENTRY_csmcc_stop_aoc_timer FN_ENTRY_csmcc_stop_aoc_timer__enum,FN_ENTRY_csmcc_stop_aoc_timer_size

// FN_ENTRY_csmcc_rlc_timeout_handler
#define FN_ENTRY_csmcc_rlc_timeout_handler_size NULL
#define FN_ENTRY_csmcc_rlc_timeout_handler FN_ENTRY_csmcc_rlc_timeout_handler__enum,FN_ENTRY_csmcc_rlc_timeout_handler_size

// FN_EXIT_csmcc_rlc_timeout_handler
#define FN_EXIT_csmcc_rlc_timeout_handler_size NULL
#define FN_EXIT_csmcc_rlc_timeout_handler FN_EXIT_csmcc_rlc_timeout_handler__enum,FN_EXIT_csmcc_rlc_timeout_handler_size

// FN_ENTRY_csmcc_start_rlc_timer
#define FN_ENTRY_csmcc_start_rlc_timer_size NULL
#define FN_ENTRY_csmcc_start_rlc_timer FN_ENTRY_csmcc_start_rlc_timer__enum,FN_ENTRY_csmcc_start_rlc_timer_size

// FN_ENTRY_csmcc_stop_rlc_timer
#define FN_ENTRY_csmcc_stop_rlc_timer_size NULL
#define FN_ENTRY_csmcc_stop_rlc_timer FN_ENTRY_csmcc_stop_rlc_timer__enum,FN_ENTRY_csmcc_stop_rlc_timer_size

// FN_ENTRY_csmcc_mncc_rel_cnf_handler
#define FN_ENTRY_csmcc_mncc_rel_cnf_handler_size NULL
#define FN_ENTRY_csmcc_mncc_rel_cnf_handler FN_ENTRY_csmcc_mncc_rel_cnf_handler__enum,FN_ENTRY_csmcc_mncc_rel_cnf_handler_size

// FN_EXIT_csmcc_mncc_rel_cnf_handler
#define FN_EXIT_csmcc_mncc_rel_cnf_handler_size NULL
#define FN_EXIT_csmcc_mncc_rel_cnf_handler FN_EXIT_csmcc_mncc_rel_cnf_handler__enum,FN_EXIT_csmcc_mncc_rel_cnf_handler_size

// FN_ENTRY_l4ccsm_cc_get_cnap_info
#define FN_ENTRY_l4ccsm_cc_get_cnap_info_size NULL
#define FN_ENTRY_l4ccsm_cc_get_cnap_info FN_ENTRY_l4ccsm_cc_get_cnap_info__enum,FN_ENTRY_l4ccsm_cc_get_cnap_info_size

// FN_ENTRY_csmcc_start_call_confirm_timer
#define FN_ENTRY_csmcc_start_call_confirm_timer_size NULL
#define FN_ENTRY_csmcc_start_call_confirm_timer FN_ENTRY_csmcc_start_call_confirm_timer__enum,FN_ENTRY_csmcc_start_call_confirm_timer_size

// FN_ENTRY_csmcc_call_confirm_timeout_handler
#define FN_ENTRY_csmcc_call_confirm_timeout_handler_size NULL
#define FN_ENTRY_csmcc_call_confirm_timeout_handler FN_ENTRY_csmcc_call_confirm_timeout_handler__enum,FN_ENTRY_csmcc_call_confirm_timeout_handler_size

// FN_ENTRY_csmcc_stop_call_confirm_timer
#define FN_ENTRY_csmcc_stop_call_confirm_timer_size NULL
#define FN_ENTRY_csmcc_stop_call_confirm_timer FN_ENTRY_csmcc_stop_call_confirm_timer__enum,FN_ENTRY_csmcc_stop_call_confirm_timer_size

// CSMCC_TRACE_STATE_CHANGE
#define CSMCC_TRACE_STATE_CHANGE_size "„d"
#define CSMCC_TRACE_STATE_CHANGE CSMCC_TRACE_STATE_CHANGE__enum,CSMCC_TRACE_STATE_CHANGE_size

// CSMCC_TRACE_MPTY_STATE_CHANGE
#define CSMCC_TRACE_MPTY_STATE_CHANGE_size "„d"
#define CSMCC_TRACE_MPTY_STATE_CHANGE CSMCC_TRACE_MPTY_STATE_CHANGE__enum,CSMCC_TRACE_MPTY_STATE_CHANGE_size

// CSMCC_TRACE_STATE_INFO
#define CSMCC_TRACE_STATE_INFO_size "„d"
#define CSMCC_TRACE_STATE_INFO CSMCC_TRACE_STATE_INFO__enum,CSMCC_TRACE_STATE_INFO_size

// CSMCC_TRACE_REQUEST_SAVE
#define CSMCC_TRACE_REQUEST_SAVE_size "c‚d"
#define CSMCC_TRACE_REQUEST_SAVE CSMCC_TRACE_REQUEST_SAVE__enum,CSMCC_TRACE_REQUEST_SAVE_size

// CSMCC_TRACE_REQUEST_UPDATE
#define CSMCC_TRACE_REQUEST_UPDATE_size "ƒd"
#define CSMCC_TRACE_REQUEST_UPDATE CSMCC_TRACE_REQUEST_UPDATE__enum,CSMCC_TRACE_REQUEST_UPDATE_size

// CSMCC_TRACE_AUX_REQUEST_SAVE
#define CSMCC_TRACE_AUX_REQUEST_SAVE_size "ƒd"
#define CSMCC_TRACE_AUX_REQUEST_SAVE CSMCC_TRACE_AUX_REQUEST_SAVE__enum,CSMCC_TRACE_AUX_REQUEST_SAVE_size

// CSMCC_TRACE_CHANNEL_ATTACH_STATUS
#define CSMCC_TRACE_CHANNEL_ATTACH_STATUS_size "‚d"
#define CSMCC_TRACE_CHANNEL_ATTACH_STATUS CSMCC_TRACE_CHANNEL_ATTACH_STATUS__enum,CSMCC_TRACE_CHANNEL_ATTACH_STATUS_size

// CSMCC_TRACE_SYNC_IND
#define CSMCC_TRACE_SYNC_IND_size "d‚c"
#define CSMCC_TRACE_SYNC_IND CSMCC_TRACE_SYNC_IND__enum,CSMCC_TRACE_SYNC_IND_size

// CSMCC_TRACE_RAT_IND
#define CSMCC_TRACE_RAT_IND_size "‚d"
#define CSMCC_TRACE_RAT_IND CSMCC_TRACE_RAT_IND__enum,CSMCC_TRACE_RAT_IND_size

// CSMCC_TRACE_RAT_MODE
#define CSMCC_TRACE_RAT_MODE_size "‚d"
#define CSMCC_TRACE_RAT_MODE CSMCC_TRACE_RAT_MODE__enum,CSMCC_TRACE_RAT_MODE_size

// CSMCC_TRACE_IS_SIM_REPLACED
#define CSMCC_TRACE_IS_SIM_REPLACED_size "d"
#define CSMCC_TRACE_IS_SIM_REPLACED CSMCC_TRACE_IS_SIM_REPLACED__enum,CSMCC_TRACE_IS_SIM_REPLACED_size

// CSMCC_TRACE_TI_AND_CALL_ID
#define CSMCC_TRACE_TI_AND_CALL_ID_size "‚d"
#define CSMCC_TRACE_TI_AND_CALL_ID CSMCC_TRACE_TI_AND_CALL_ID__enum,CSMCC_TRACE_TI_AND_CALL_ID_size

// CSMCC_TRACE_CTM_STATUS
#define CSMCC_TRACE_CTM_STATUS_size "d"
#define CSMCC_TRACE_CTM_STATUS CSMCC_TRACE_CTM_STATUS__enum,CSMCC_TRACE_CTM_STATUS_size

// CSMCC_TRACE_CCBS_STATUS
#define CSMCC_TRACE_CCBS_STATUS_size "‚d"
#define CSMCC_TRACE_CCBS_STATUS CSMCC_TRACE_CCBS_STATUS__enum,CSMCC_TRACE_CCBS_STATUS_size

// CSMCC_TRACE_CNAP_STATUS
#define CSMCC_TRACE_CNAP_STATUS_size "c„d"
#define CSMCC_TRACE_CNAP_STATUS CSMCC_TRACE_CNAP_STATUS__enum,CSMCC_TRACE_CNAP_STATUS_size

// CSMCC_TRACE_RLC_STATUS
#define CSMCC_TRACE_RLC_STATUS_size "dc"
#define CSMCC_TRACE_RLC_STATUS CSMCC_TRACE_RLC_STATUS__enum,CSMCC_TRACE_RLC_STATUS_size

// CSMCC_TRACE_TIMER_STATUS
#define CSMCC_TRACE_TIMER_STATUS_size "ƒd"
#define CSMCC_TRACE_TIMER_STATUS CSMCC_TRACE_TIMER_STATUS__enum,CSMCC_TRACE_TIMER_STATUS_size

// CSMCC_TRACE_ACM_VALUE
#define CSMCC_TRACE_ACM_VALUE_size "ƒd"
#define CSMCC_TRACE_ACM_VALUE CSMCC_TRACE_ACM_VALUE__enum,CSMCC_TRACE_ACM_VALUE_size

// CSMCC_TRACE_BC1_CHECK_FAILURE
#define CSMCC_TRACE_BC1_CHECK_FAILURE_size "d"
#define CSMCC_TRACE_BC1_CHECK_FAILURE CSMCC_TRACE_BC1_CHECK_FAILURE__enum,CSMCC_TRACE_BC1_CHECK_FAILURE_size

// CSMCC_TRACE_BC2_CHECK_FAILURE
#define CSMCC_TRACE_BC2_CHECK_FAILURE_size "d"
#define CSMCC_TRACE_BC2_CHECK_FAILURE CSMCC_TRACE_BC2_CHECK_FAILURE__enum,CSMCC_TRACE_BC2_CHECK_FAILURE_size

// CSMCC_TRACE_ILLEGAL_INV_ID_RECEIVE
#define CSMCC_TRACE_ILLEGAL_INV_ID_RECEIVE_size "d"
#define CSMCC_TRACE_ILLEGAL_INV_ID_RECEIVE CSMCC_TRACE_ILLEGAL_INV_ID_RECEIVE__enum,CSMCC_TRACE_ILLEGAL_INV_ID_RECEIVE_size

// CSMCC_TRACE_DERIVABLE_INV_ID
#define CSMCC_TRACE_DERIVABLE_INV_ID_size NULL
#define CSMCC_TRACE_DERIVABLE_INV_ID CSMCC_TRACE_DERIVABLE_INV_ID__enum,CSMCC_TRACE_DERIVABLE_INV_ID_size

// CSMCC_TRACE_DUPLICATE_L4C_REQ
#define CSMCC_TRACE_DUPLICATE_L4C_REQ_size "d"
#define CSMCC_TRACE_DUPLICATE_L4C_REQ CSMCC_TRACE_DUPLICATE_L4C_REQ__enum,CSMCC_TRACE_DUPLICATE_L4C_REQ_size

// CSMCC_TRACE_ATTACH_WITHOUT_SYNC_IND
#define CSMCC_TRACE_ATTACH_WITHOUT_SYNC_IND_size NULL
#define CSMCC_TRACE_ATTACH_WITHOUT_SYNC_IND CSMCC_TRACE_ATTACH_WITHOUT_SYNC_IND__enum,CSMCC_TRACE_ATTACH_WITHOUT_SYNC_IND_size

// CSMCC_TRACE_FILE_CHANGE_FOR_SIM_REFRESH
#define CSMCC_TRACE_FILE_CHANGE_FOR_SIM_REFRESH_size NULL
#define CSMCC_TRACE_FILE_CHANGE_FOR_SIM_REFRESH CSMCC_TRACE_FILE_CHANGE_FOR_SIM_REFRESH__enum,CSMCC_TRACE_FILE_CHANGE_FOR_SIM_REFRESH_size

// CSMCC_TRACE_CALL_IS_RELEASED
#define CSMCC_TRACE_CALL_IS_RELEASED_size NULL
#define CSMCC_TRACE_CALL_IS_RELEASED CSMCC_TRACE_CALL_IS_RELEASED__enum,CSMCC_TRACE_CALL_IS_RELEASED_size

// CSMCC_TRACE_COMMAND_TO_DIFF_SIM
#define CSMCC_TRACE_COMMAND_TO_DIFF_SIM_size "‚h"
#define CSMCC_TRACE_COMMAND_TO_DIFF_SIM CSMCC_TRACE_COMMAND_TO_DIFF_SIM__enum,CSMCC_TRACE_COMMAND_TO_DIFF_SIM_size

// CSMCC_TRACE_WRONG_CHECK_STATE
#define CSMCC_TRACE_WRONG_CHECK_STATE_size "d"
#define CSMCC_TRACE_WRONG_CHECK_STATE CSMCC_TRACE_WRONG_CHECK_STATE__enum,CSMCC_TRACE_WRONG_CHECK_STATE_size

// CSMCC_TRACE_CALL_ID_NOT_MATCHED
#define CSMCC_TRACE_CALL_ID_NOT_MATCHED_size NULL
#define CSMCC_TRACE_CALL_ID_NOT_MATCHED CSMCC_TRACE_CALL_ID_NOT_MATCHED__enum,CSMCC_TRACE_CALL_ID_NOT_MATCHED_size

// CSMCC_TRACE_INVALID_DTMF_DIGIT
#define CSMCC_TRACE_INVALID_DTMF_DIGIT_size "d"
#define CSMCC_TRACE_INVALID_DTMF_DIGIT CSMCC_TRACE_INVALID_DTMF_DIGIT__enum,CSMCC_TRACE_INVALID_DTMF_DIGIT_size

// CSMCC_TRACE_SAT_TYPE_OF_MODIFICATION
#define CSMCC_TRACE_SAT_TYPE_OF_MODIFICATION_size "d"
#define CSMCC_TRACE_SAT_TYPE_OF_MODIFICATION CSMCC_TRACE_SAT_TYPE_OF_MODIFICATION__enum,CSMCC_TRACE_SAT_TYPE_OF_MODIFICATION_size

// CSMCC_TRACE_NO_CALL
#define CSMCC_TRACE_NO_CALL_size NULL
#define CSMCC_TRACE_NO_CALL CSMCC_TRACE_NO_CALL__enum,CSMCC_TRACE_NO_CALL_size

// CSMCC_TRACE_INVALID_RAT
#define CSMCC_TRACE_INVALID_RAT_size "d"
#define CSMCC_TRACE_INVALID_RAT CSMCC_TRACE_INVALID_RAT__enum,CSMCC_TRACE_INVALID_RAT_size

// CSMCC_TRACE_INVALID_ADDR_LEN
#define CSMCC_TRACE_INVALID_ADDR_LEN_size "d"
#define CSMCC_TRACE_INVALID_ADDR_LEN CSMCC_TRACE_INVALID_ADDR_LEN__enum,CSMCC_TRACE_INVALID_ADDR_LEN_size

// CSMCC_TRACE_MCD_UNPACK_ERROR
#define CSMCC_TRACE_MCD_UNPACK_ERROR_size "‚d"
#define CSMCC_TRACE_MCD_UNPACK_ERROR CSMCC_TRACE_MCD_UNPACK_ERROR__enum,CSMCC_TRACE_MCD_UNPACK_ERROR_size

// CSMCC_TRACE_CLEAR_DTMF
#define CSMCC_TRACE_CLEAR_DTMF_size "d"
#define CSMCC_TRACE_CLEAR_DTMF CSMCC_TRACE_CLEAR_DTMF__enum,CSMCC_TRACE_CLEAR_DTMF_size

// CSMCC_CALL_INFO
#define CSMCC_CALL_INFO_size "…d"
#define CSMCC_CALL_INFO CSMCC_CALL_INFO__enum,CSMCC_CALL_INFO_size

// CSMCC_SET_PRE_STATE
#define CSMCC_SET_PRE_STATE_size "‚d"
#define CSMCC_SET_PRE_STATE CSMCC_SET_PRE_STATE__enum,CSMCC_SET_PRE_STATE_size

// CSMCC_RLC_REQ_CALL_ID
#define CSMCC_RLC_REQ_CALL_ID_size "d"
#define CSMCC_RLC_REQ_CALL_ID CSMCC_RLC_REQ_CALL_ID__enum,CSMCC_RLC_REQ_CALL_ID_size

// CSMCC_NOT_REL_SAT_CALL
#define CSMCC_NOT_REL_SAT_CALL_size NULL
#define CSMCC_NOT_REL_SAT_CALL CSMCC_NOT_REL_SAT_CALL__enum,CSMCC_NOT_REL_SAT_CALL_size

// CSMCC_VT_CALL_FROM_AT
#define CSMCC_VT_CALL_FROM_AT_size NULL
#define CSMCC_VT_CALL_FROM_AT CSMCC_VT_CALL_FROM_AT__enum,CSMCC_VT_CALL_FROM_AT_size

// CSMCC_CALL_TYPE_AND_MODE
#define CSMCC_CALL_TYPE_AND_MODE_size "‚d"
#define CSMCC_CALL_TYPE_AND_MODE CSMCC_CALL_TYPE_AND_MODE__enum,CSMCC_CALL_TYPE_AND_MODE_size

// CSMCC_CH_TYPE_AND_CH_MODE
#define CSMCC_CH_TYPE_AND_CH_MODE_size "‚d"
#define CSMCC_CH_TYPE_AND_CH_MODE CSMCC_CH_TYPE_AND_CH_MODE__enum,CSMCC_CH_TYPE_AND_CH_MODE_size

// CSMCC_ACTIVATE_FAX
#define CSMCC_ACTIVATE_FAX_size NULL
#define CSMCC_ACTIVATE_FAX CSMCC_ACTIVATE_FAX__enum,CSMCC_ACTIVATE_FAX_size

// CSMCC_READ_CSD_PROF_FROM_NVRAM
#define CSMCC_READ_CSD_PROF_FROM_NVRAM_size "‚d"
#define CSMCC_READ_CSD_PROF_FROM_NVRAM CSMCC_READ_CSD_PROF_FROM_NVRAM__enum,CSMCC_READ_CSD_PROF_FROM_NVRAM_size

// CSMCC_SAT_CSD_PROF_CONTEXT
#define CSMCC_SAT_CSD_PROF_CONTEXT_size "…d"
#define CSMCC_SAT_CSD_PROF_CONTEXT CSMCC_SAT_CSD_PROF_CONTEXT__enum,CSMCC_SAT_CSD_PROF_CONTEXT_size

// CSMCC_TRACE_NVRAM_CSD_INFO
#define CSMCC_TRACE_NVRAM_CSD_INFO_size "„d"
#define CSMCC_TRACE_NVRAM_CSD_INFO CSMCC_TRACE_NVRAM_CSD_INFO__enum,CSMCC_TRACE_NVRAM_CSD_INFO_size

// CSMCC_TRACE_CSD_CALL
#define CSMCC_TRACE_CSD_CALL_size "cd"
#define CSMCC_TRACE_CSD_CALL CSMCC_TRACE_CSD_CALL__enum,CSMCC_TRACE_CSD_CALL_size

// CSMCC_CSD_PROF_CONTEXT
#define CSMCC_CSD_PROF_CONTEXT_size "c…d"
#define CSMCC_CSD_PROF_CONTEXT CSMCC_CSD_PROF_CONTEXT__enum,CSMCC_CSD_PROF_CONTEXT_size

// FN_ENTRY_csmss_startup_req_hdlr
#define FN_ENTRY_csmss_startup_req_hdlr_size NULL
#define FN_ENTRY_csmss_startup_req_hdlr FN_ENTRY_csmss_startup_req_hdlr__enum,FN_ENTRY_csmss_startup_req_hdlr_size

// FN_ENTRY_csmss_ss_parse_req_hdlr
#define FN_ENTRY_csmss_ss_parse_req_hdlr_size NULL
#define FN_ENTRY_csmss_ss_parse_req_hdlr FN_ENTRY_csmss_ss_parse_req_hdlr__enum,FN_ENTRY_csmss_ss_parse_req_hdlr_size

// FN_ENTRY_csmss_ss_ctrl_cnf_hdlr
#define FN_ENTRY_csmss_ss_ctrl_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_ss_ctrl_cnf_hdlr FN_ENTRY_csmss_ss_ctrl_cnf_hdlr__enum,FN_ENTRY_csmss_ss_ctrl_cnf_hdlr_size

// FN_ENTRY_csmss_cf_begin_req_hdlr
#define FN_ENTRY_csmss_cf_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_cf_begin_req_hdlr FN_ENTRY_csmss_cf_begin_req_hdlr__enum,FN_ENTRY_csmss_cf_begin_req_hdlr_size

// FN_ENTRY_csmss_cw_begin_req_hdlr
#define FN_ENTRY_csmss_cw_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_cw_begin_req_hdlr FN_ENTRY_csmss_cw_begin_req_hdlr__enum,FN_ENTRY_csmss_cw_begin_req_hdlr_size

// FN_ENTRY_csmss_cb_begin_req_hdlr
#define FN_ENTRY_csmss_cb_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_cb_begin_req_hdlr FN_ENTRY_csmss_cb_begin_req_hdlr__enum,FN_ENTRY_csmss_cb_begin_req_hdlr_size

// FN_ENTRY_csmss_emlpp_begin_req_hdlr
#define FN_ENTRY_csmss_emlpp_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_emlpp_begin_req_hdlr FN_ENTRY_csmss_emlpp_begin_req_hdlr__enum,FN_ENTRY_csmss_emlpp_begin_req_hdlr_size

// FN_ENTRY_csmss_cli_begin_req_hdlr
#define FN_ENTRY_csmss_cli_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_cli_begin_req_hdlr FN_ENTRY_csmss_cli_begin_req_hdlr__enum,FN_ENTRY_csmss_cli_begin_req_hdlr_size

// FN_ENTRY_csmss_ccbs_begin_req_hdlr
#define FN_ENTRY_csmss_ccbs_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_ccbs_begin_req_hdlr FN_ENTRY_csmss_ccbs_begin_req_hdlr__enum,FN_ENTRY_csmss_ccbs_begin_req_hdlr_size

// FN_ENTRY_csmss_pussr_begin_req_hdlr
#define FN_ENTRY_csmss_pussr_begin_req_hdlr_size NULL
#define FN_ENTRY_csmss_pussr_begin_req_hdlr FN_ENTRY_csmss_pussr_begin_req_hdlr__enum,FN_ENTRY_csmss_pussr_begin_req_hdlr_size

// FN_ENTRY_csmss_begin_ind_hdlr
#define FN_ENTRY_csmss_begin_ind_hdlr_size NULL
#define FN_ENTRY_csmss_begin_ind_hdlr FN_ENTRY_csmss_begin_ind_hdlr__enum,FN_ENTRY_csmss_begin_ind_hdlr_size

// FN_ENTRY_csmss_cf_end_cnf_hdlr
#define FN_ENTRY_csmss_cf_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_cf_end_cnf_hdlr FN_ENTRY_csmss_cf_end_cnf_hdlr__enum,FN_ENTRY_csmss_cf_end_cnf_hdlr_size

// FN_ENTRY_csmss_cw_end_cnf_hdlr
#define FN_ENTRY_csmss_cw_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_cw_end_cnf_hdlr FN_ENTRY_csmss_cw_end_cnf_hdlr__enum,FN_ENTRY_csmss_cw_end_cnf_hdlr_size

// FN_ENTRY_csmss_cb_end_cnf_hdlr
#define FN_ENTRY_csmss_cb_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_cb_end_cnf_hdlr FN_ENTRY_csmss_cb_end_cnf_hdlr__enum,FN_ENTRY_csmss_cb_end_cnf_hdlr_size

// FN_ENTRY_csmss_emlpp_end_cnf_hdlr
#define FN_ENTRY_csmss_emlpp_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_emlpp_end_cnf_hdlr FN_ENTRY_csmss_emlpp_end_cnf_hdlr__enum,FN_ENTRY_csmss_emlpp_end_cnf_hdlr_size

// FN_ENTRY_csmss_cli_end_cnf_hdlr
#define FN_ENTRY_csmss_cli_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_cli_end_cnf_hdlr FN_ENTRY_csmss_cli_end_cnf_hdlr__enum,FN_ENTRY_csmss_cli_end_cnf_hdlr_size

// FN_ENTRY_csmss_ccbs_end_cnf_hdlr
#define FN_ENTRY_csmss_ccbs_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_ccbs_end_cnf_hdlr FN_ENTRY_csmss_ccbs_end_cnf_hdlr__enum,FN_ENTRY_csmss_ccbs_end_cnf_hdlr_size

// FN_ENTRY_csmss_pussr_end_cnf_hdlr
#define FN_ENTRY_csmss_pussr_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_pussr_end_cnf_hdlr FN_ENTRY_csmss_pussr_end_cnf_hdlr__enum,FN_ENTRY_csmss_pussr_end_cnf_hdlr_size

// FN_ENTRY_csmss_ussr_end_cnf_hdlr
#define FN_ENTRY_csmss_ussr_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_ussr_end_cnf_hdlr FN_ENTRY_csmss_ussr_end_cnf_hdlr__enum,FN_ENTRY_csmss_ussr_end_cnf_hdlr_size

// FN_ENTRY_csmss_ussn_end_cnf_hdlr
#define FN_ENTRY_csmss_ussn_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_ussn_end_cnf_hdlr FN_ENTRY_csmss_ussn_end_cnf_hdlr__enum,FN_ENTRY_csmss_ussn_end_cnf_hdlr_size

// FN_ENTRY_csmss_sim_end_cnf_hdlr
#define FN_ENTRY_csmss_sim_end_cnf_hdlr_size NULL
#define FN_ENTRY_csmss_sim_end_cnf_hdlr FN_ENTRY_csmss_sim_end_cnf_hdlr__enum,FN_ENTRY_csmss_sim_end_cnf_hdlr_size

// FN_ENTRY_csmss_cb_fac_ind_hdlr
#define FN_ENTRY_csmss_cb_fac_ind_hdlr_size NULL
#define FN_ENTRY_csmss_cb_fac_ind_hdlr FN_ENTRY_csmss_cb_fac_ind_hdlr__enum,FN_ENTRY_csmss_cb_fac_ind_hdlr_size

// FN_ENTRY_csmss_ussr_fac_ind_hdlr
#define FN_ENTRY_csmss_ussr_fac_ind_hdlr_size NULL
#define FN_ENTRY_csmss_ussr_fac_ind_hdlr FN_ENTRY_csmss_ussr_fac_ind_hdlr__enum,FN_ENTRY_csmss_ussr_fac_ind_hdlr_size

// FN_ENTRY_csmss_ussn_fac_ind_hdlr
#define FN_ENTRY_csmss_ussn_fac_ind_hdlr_size NULL
#define FN_ENTRY_csmss_ussn_fac_ind_hdlr FN_ENTRY_csmss_ussn_fac_ind_hdlr__enum,FN_ENTRY_csmss_ussn_fac_ind_hdlr_size

// FN_ENTRY_csmss_cb_fac_res_hdlr
#define FN_ENTRY_csmss_cb_fac_res_hdlr_size NULL
#define FN_ENTRY_csmss_cb_fac_res_hdlr FN_ENTRY_csmss_cb_fac_res_hdlr__enum,FN_ENTRY_csmss_cb_fac_res_hdlr_size

// FN_ENTRY_csmss_ussr_fac_res_hdlr
#define FN_ENTRY_csmss_ussr_fac_res_hdlr_size NULL
#define FN_ENTRY_csmss_ussr_fac_res_hdlr FN_ENTRY_csmss_ussr_fac_res_hdlr__enum,FN_ENTRY_csmss_ussr_fac_res_hdlr_size

// FN_ENTRY_csmss_ussn_fac_res_hdlr
#define FN_ENTRY_csmss_ussn_fac_res_hdlr_size NULL
#define FN_ENTRY_csmss_ussn_fac_res_hdlr FN_ENTRY_csmss_ussn_fac_res_hdlr__enum,FN_ENTRY_csmss_ussn_fac_res_hdlr_size

// FN_ENTRY_csmss_end_res_hdlr
#define FN_ENTRY_csmss_end_res_hdlr_size NULL
#define FN_ENTRY_csmss_end_res_hdlr FN_ENTRY_csmss_end_res_hdlr__enum,FN_ENTRY_csmss_end_res_hdlr_size

// FN_ENTRY_csmss_cphs_deactivate_cfu_hdlr
#define FN_ENTRY_csmss_cphs_deactivate_cfu_hdlr_size NULL
#define FN_ENTRY_csmss_cphs_deactivate_cfu_hdlr FN_ENTRY_csmss_cphs_deactivate_cfu_hdlr__enum,FN_ENTRY_csmss_cphs_deactivate_cfu_hdlr_size

// FN_ENTRY_csmss_cphs_start_cfu_hdlr
#define FN_ENTRY_csmss_cphs_start_cfu_hdlr_size NULL
#define FN_ENTRY_csmss_cphs_start_cfu_hdlr FN_ENTRY_csmss_cphs_start_cfu_hdlr__enum,FN_ENTRY_csmss_cphs_start_cfu_hdlr_size

// FN_ENTRY_csmss_ss_src_call_forward_req
#define FN_ENTRY_csmss_ss_src_call_forward_req_size NULL
#define FN_ENTRY_csmss_ss_src_call_forward_req FN_ENTRY_csmss_ss_src_call_forward_req__enum,FN_ENTRY_csmss_ss_src_call_forward_req_size

// FN_ENTRY_csmss_ss_src_call_wait_req
#define FN_ENTRY_csmss_ss_src_call_wait_req_size NULL
#define FN_ENTRY_csmss_ss_src_call_wait_req FN_ENTRY_csmss_ss_src_call_wait_req__enum,FN_ENTRY_csmss_ss_src_call_wait_req_size

// FN_ENTRY_csmss_ss_src_call_barring_req
#define FN_ENTRY_csmss_ss_src_call_barring_req_size NULL
#define FN_ENTRY_csmss_ss_src_call_barring_req FN_ENTRY_csmss_ss_src_call_barring_req__enum,FN_ENTRY_csmss_ss_src_call_barring_req_size

// FN_ENTRY_csmss_ss_src_emlpp_req
#define FN_ENTRY_csmss_ss_src_emlpp_req_size NULL
#define FN_ENTRY_csmss_ss_src_emlpp_req FN_ENTRY_csmss_ss_src_emlpp_req__enum,FN_ENTRY_csmss_ss_src_emlpp_req_size

// FN_ENTRY_csmss_ss_src_interrogate_req
#define FN_ENTRY_csmss_ss_src_interrogate_req_size NULL
#define FN_ENTRY_csmss_ss_src_interrogate_req FN_ENTRY_csmss_ss_src_interrogate_req__enum,FN_ENTRY_csmss_ss_src_interrogate_req_size

// FN_ENTRY_csmss_ss_src_ccbs_req
#define FN_ENTRY_csmss_ss_src_ccbs_req_size NULL
#define FN_ENTRY_csmss_ss_src_ccbs_req FN_ENTRY_csmss_ss_src_ccbs_req__enum,FN_ENTRY_csmss_ss_src_ccbs_req_size

// FN_ENTRY_csmss_ss_src_ussd_req
#define FN_ENTRY_csmss_ss_src_ussd_req_size NULL
#define FN_ENTRY_csmss_ss_src_ussd_req FN_ENTRY_csmss_ss_src_ussd_req__enum,FN_ENTRY_csmss_ss_src_ussd_req_size

// FN_ENTRY_csmss_send_ss_ctrl_req
#define FN_ENTRY_csmss_send_ss_ctrl_req_size NULL
#define FN_ENTRY_csmss_send_ss_ctrl_req FN_ENTRY_csmss_send_ss_ctrl_req__enum,FN_ENTRY_csmss_send_ss_ctrl_req_size

// FN_ENTRY_csmss_send_ss_parse_cnf
#define FN_ENTRY_csmss_send_ss_parse_cnf_size NULL
#define FN_ENTRY_csmss_send_ss_parse_cnf FN_ENTRY_csmss_send_ss_parse_cnf__enum,FN_ENTRY_csmss_send_ss_parse_cnf_size

// FN_ENTRY_csmss_ss_exe_call_forward_req
#define FN_ENTRY_csmss_ss_exe_call_forward_req_size NULL
#define FN_ENTRY_csmss_ss_exe_call_forward_req FN_ENTRY_csmss_ss_exe_call_forward_req__enum,FN_ENTRY_csmss_ss_exe_call_forward_req_size

// FN_ENTRY_csmss_ss_exe_call_wait_req
#define FN_ENTRY_csmss_ss_exe_call_wait_req_size NULL
#define FN_ENTRY_csmss_ss_exe_call_wait_req FN_ENTRY_csmss_ss_exe_call_wait_req__enum,FN_ENTRY_csmss_ss_exe_call_wait_req_size

// FN_ENTRY_csmss_ss_exe_call_barring_req
#define FN_ENTRY_csmss_ss_exe_call_barring_req_size NULL
#define FN_ENTRY_csmss_ss_exe_call_barring_req FN_ENTRY_csmss_ss_exe_call_barring_req__enum,FN_ENTRY_csmss_ss_exe_call_barring_req_size

// FN_ENTRY_csmss_ss_exe_emlpp_req
#define FN_ENTRY_csmss_ss_exe_emlpp_req_size NULL
#define FN_ENTRY_csmss_ss_exe_emlpp_req FN_ENTRY_csmss_ss_exe_emlpp_req__enum,FN_ENTRY_csmss_ss_exe_emlpp_req_size

// FN_ENTRY_csmss_ss_exe_interrogate_req
#define FN_ENTRY_csmss_ss_exe_interrogate_req_size NULL
#define FN_ENTRY_csmss_ss_exe_interrogate_req FN_ENTRY_csmss_ss_exe_interrogate_req__enum,FN_ENTRY_csmss_ss_exe_interrogate_req_size

// FN_ENTRY_csmss_ss_exe_ccbs_req
#define FN_ENTRY_csmss_ss_exe_ccbs_req_size NULL
#define FN_ENTRY_csmss_ss_exe_ccbs_req FN_ENTRY_csmss_ss_exe_ccbs_req__enum,FN_ENTRY_csmss_ss_exe_ccbs_req_size

// FN_ENTRY_csmss_ss_exe_ussd_req
#define FN_ENTRY_csmss_ss_exe_ussd_req_size NULL
#define FN_ENTRY_csmss_ss_exe_ussd_req FN_ENTRY_csmss_ss_exe_ussd_req__enum,FN_ENTRY_csmss_ss_exe_ussd_req_size

// CSMSS_D
#define CSMSS_D_size "d"
#define CSMSS_D CSMSS_D__enum,CSMSS_D_size

// CSMSS_DD
#define CSMSS_DD_size "‚d"
#define CSMSS_DD CSMSS_DD__enum,CSMSS_DD_size

// CSMSS_DDD
#define CSMSS_DDD_size "ƒd"
#define CSMSS_DDD CSMSS_DDD__enum,CSMSS_DDD_size

// CSMSS_DDDD
#define CSMSS_DDDD_size "„d"
#define CSMSS_DDDD CSMSS_DDDD__enum,CSMSS_DDDD_size

// CSMSS_DDDDD
#define CSMSS_DDDDD_size "…d"
#define CSMSS_DDDDD CSMSS_DDDDD__enum,CSMSS_DDDDD_size

// CSMSS_ERR_UNEXPECTED_MESSAGE_SUBOP
#define CSMSS_ERR_UNEXPECTED_MESSAGE_SUBOP_size "d"
#define CSMSS_ERR_UNEXPECTED_MESSAGE_SUBOP CSMSS_ERR_UNEXPECTED_MESSAGE_SUBOP__enum,CSMSS_ERR_UNEXPECTED_MESSAGE_SUBOP_size

// CSMSS_ERR_MSG_CORRUPTED_SUBOP
#define CSMSS_ERR_MSG_CORRUPTED_SUBOP_size NULL
#define CSMSS_ERR_MSG_CORRUPTED_SUBOP CSMSS_ERR_MSG_CORRUPTED_SUBOP__enum,CSMSS_ERR_MSG_CORRUPTED_SUBOP_size

// CSMSS_ERR_NO_FREE_CALL_ID_IN_POOL
#define CSMSS_ERR_NO_FREE_CALL_ID_IN_POOL_size NULL
#define CSMSS_ERR_NO_FREE_CALL_ID_IN_POOL CSMSS_ERR_NO_FREE_CALL_ID_IN_POOL__enum,CSMSS_ERR_NO_FREE_CALL_ID_IN_POOL_size

// CSMSS_ERR_ALLOC_NULL_STRING
#define CSMSS_ERR_ALLOC_NULL_STRING_size NULL
#define CSMSS_ERR_ALLOC_NULL_STRING CSMSS_ERR_ALLOC_NULL_STRING__enum,CSMSS_ERR_ALLOC_NULL_STRING_size

// CSMSS_LCS_DISCARD_DECODE_FAILED
#define CSMSS_LCS_DISCARD_DECODE_FAILED_size NULL
#define CSMSS_LCS_DISCARD_DECODE_FAILED CSMSS_LCS_DISCARD_DECODE_FAILED__enum,CSMSS_LCS_DISCARD_DECODE_FAILED_size

// CSMSS_LCS_ENCODE_FAILED
#define CSMSS_LCS_ENCODE_FAILED_size NULL
#define CSMSS_LCS_ENCODE_FAILED CSMSS_LCS_ENCODE_FAILED__enum,CSMSS_LCS_ENCODE_FAILED_size


#endif // CSM_TRC_GEN.H
