#ifndef _DHCP_TRC_GEN_H_
#define _DHCP_TRC_GEN_H_

// FUNC_DHCP_MAIN
#define FUNC_DHCP_MAIN_size "ch"
#define FUNC_DHCP_MAIN FUNC_DHCP_MAIN__enum,FUNC_DHCP_MAIN_size

// FUNC_DHCP_PACK
#define FUNC_DHCP_PACK_size "c"
#define FUNC_DHCP_PACK FUNC_DHCP_PACK__enum,FUNC_DHCP_PACK_size

// FUNC_DHCP_FILLHEADERS
#define FUNC_DHCP_FILLHEADERS_size NULL
#define FUNC_DHCP_FILLHEADERS FUNC_DHCP_FILLHEADERS__enum,FUNC_DHCP_FILLHEADERS_size

// FUNC_DHCP_INSERTOPTIONS
#define FUNC_DHCP_INSERTOPTIONS_size NULL
#define FUNC_DHCP_INSERTOPTIONS FUNC_DHCP_INSERTOPTIONS__enum,FUNC_DHCP_INSERTOPTIONS_size

// FUNC_DHCP_UNPACK
#define FUNC_DHCP_UNPACK_size NULL
#define FUNC_DHCP_UNPACK FUNC_DHCP_UNPACK__enum,FUNC_DHCP_UNPACK_size

// FUNC_DHCP_PARSEHEADERS
#define FUNC_DHCP_PARSEHEADERS_size NULL
#define FUNC_DHCP_PARSEHEADERS FUNC_DHCP_PARSEHEADERS__enum,FUNC_DHCP_PARSEHEADERS_size

// FUNC_DHCP_DOOPTIONS
#define FUNC_DHCP_DOOPTIONS_size NULL
#define FUNC_DHCP_DOOPTIONS FUNC_DHCP_DOOPTIONS__enum,FUNC_DHCP_DOOPTIONS_size

// FUNC_DHCP_PARSEOPT
#define FUNC_DHCP_PARSEOPT_size "c"
#define FUNC_DHCP_PARSEOPT FUNC_DHCP_PARSEOPT__enum,FUNC_DHCP_PARSEOPT_size

// FUNC_DHCP_DNS2STR
#define FUNC_DHCP_DNS2STR_size NULL
#define FUNC_DHCP_DNS2STR FUNC_DHCP_DNS2STR__enum,FUNC_DHCP_DNS2STR_size

// FUNC_DHCP_CLOSED
#define FUNC_DHCP_CLOSED_size "h"
#define FUNC_DHCP_CLOSED FUNC_DHCP_CLOSED__enum,FUNC_DHCP_CLOSED_size

// FUNC_DHCP_INITREBOOT
#define FUNC_DHCP_INITREBOOT_size "h"
#define FUNC_DHCP_INITREBOOT FUNC_DHCP_INITREBOOT__enum,FUNC_DHCP_INITREBOOT_size

// FUNC_DHCP_REBOOTING
#define FUNC_DHCP_REBOOTING_size "h"
#define FUNC_DHCP_REBOOTING FUNC_DHCP_REBOOTING__enum,FUNC_DHCP_REBOOTING_size

// FUNC_DHCP_INIT
#define FUNC_DHCP_INIT_size "hd"
#define FUNC_DHCP_INIT FUNC_DHCP_INIT__enum,FUNC_DHCP_INIT_size

// FUNC_DHCP_SELECTING
#define FUNC_DHCP_SELECTING_size "h"
#define FUNC_DHCP_SELECTING FUNC_DHCP_SELECTING__enum,FUNC_DHCP_SELECTING_size

// FUNC_DHCP_REQUESTING
#define FUNC_DHCP_REQUESTING_size "h"
#define FUNC_DHCP_REQUESTING FUNC_DHCP_REQUESTING__enum,FUNC_DHCP_REQUESTING_size

// FUNC_DHCP_BOUND
#define FUNC_DHCP_BOUND_size "h"
#define FUNC_DHCP_BOUND FUNC_DHCP_BOUND__enum,FUNC_DHCP_BOUND_size

// FUNC_DHCP_RENEWING
#define FUNC_DHCP_RENEWING_size "h"
#define FUNC_DHCP_RENEWING FUNC_DHCP_RENEWING__enum,FUNC_DHCP_RENEWING_size

// FUNC_DHCP_REBINDING
#define FUNC_DHCP_REBINDING_size "h"
#define FUNC_DHCP_REBINDING FUNC_DHCP_REBINDING__enum,FUNC_DHCP_REBINDING_size

// FUNC_DHCP_TIMER_EXPIRY
#define FUNC_DHCP_TIMER_EXPIRY_size "d"
#define FUNC_DHCP_TIMER_EXPIRY FUNC_DHCP_TIMER_EXPIRY__enum,FUNC_DHCP_TIMER_EXPIRY_size

// FUNC_DHCP_SET_TIMER
#define FUNC_DHCP_SET_TIMER_size "c‚d"
#define FUNC_DHCP_SET_TIMER FUNC_DHCP_SET_TIMER__enum,FUNC_DHCP_SET_TIMER_size

// FUNC_DHCP_CANCEL_TIMER
#define FUNC_DHCP_CANCEL_TIMER_size "cd"
#define FUNC_DHCP_CANCEL_TIMER FUNC_DHCP_CANCEL_TIMER__enum,FUNC_DHCP_CANCEL_TIMER_size

// FUNC_DHCP_CANCELALLTIMERS
#define FUNC_DHCP_CANCELALLTIMERS_size NULL
#define FUNC_DHCP_CANCELALLTIMERS FUNC_DHCP_CANCELALLTIMERS__enum,FUNC_DHCP_CANCELALLTIMERS_size

// FUNC_DHCP_TIMEOUT_HDLR
#define FUNC_DHCP_TIMEOUT_HDLR_size "c"
#define FUNC_DHCP_TIMEOUT_HDLR FUNC_DHCP_TIMEOUT_HDLR__enum,FUNC_DHCP_TIMEOUT_HDLR_size

// FUNC_DHCP_ABORT
#define FUNC_DHCP_ABORT_size NULL
#define FUNC_DHCP_ABORT FUNC_DHCP_ABORT__enum,FUNC_DHCP_ABORT_size

// FUNC_DHCP_RELEASE
#define FUNC_DHCP_RELEASE_size NULL
#define FUNC_DHCP_RELEASE FUNC_DHCP_RELEASE__enum,FUNC_DHCP_RELEASE_size

// FUNC_DHCP_CLI
#define FUNC_DHCP_CLI_size "ƒc‚d"
#define FUNC_DHCP_CLI FUNC_DHCP_CLI__enum,FUNC_DHCP_CLI_size

// FUNC_DHCP_CLI_ESTABLISH
#define FUNC_DHCP_CLI_ESTABLISH_size NULL
#define FUNC_DHCP_CLI_ESTABLISH FUNC_DHCP_CLI_ESTABLISH__enum,FUNC_DHCP_CLI_ESTABLISH_size

// FUNC_DHCP_CLI_SENDTO
#define FUNC_DHCP_CLI_SENDTO_size "d‚c"
#define FUNC_DHCP_CLI_SENDTO FUNC_DHCP_CLI_SENDTO__enum,FUNC_DHCP_CLI_SENDTO_size

// FUNC_DHCP_CLI_CLOSE
#define FUNC_DHCP_CLI_CLOSE_size NULL
#define FUNC_DHCP_CLI_CLOSE FUNC_DHCP_CLI_CLOSE__enum,FUNC_DHCP_CLI_CLOSE_size

// FUNC_DHCP_READ_FILE
#define FUNC_DHCP_READ_FILE_size NULL
#define FUNC_DHCP_READ_FILE FUNC_DHCP_READ_FILE__enum,FUNC_DHCP_READ_FILE_size

// FUNC_DHCP_WRITE_FILE
#define FUNC_DHCP_WRITE_FILE_size NULL
#define FUNC_DHCP_WRITE_FILE FUNC_DHCP_WRITE_FILE__enum,FUNC_DHCP_WRITE_FILE_size

// FUNC_DHCP_PROBE_HOST
#define FUNC_DHCP_PROBE_HOST_size "„d"
#define FUNC_DHCP_PROBE_HOST FUNC_DHCP_PROBE_HOST__enum,FUNC_DHCP_PROBE_HOST_size

// FUNC_DHCP_SEND_ABM_GET_CNF
#define FUNC_DHCP_SEND_ABM_GET_CNF_size "c"
#define FUNC_DHCP_SEND_ABM_GET_CNF FUNC_DHCP_SEND_ABM_GET_CNF__enum,FUNC_DHCP_SEND_ABM_GET_CNF_size

// FUNC_DHCP_SEND_ABM_REL_CNF
#define FUNC_DHCP_SEND_ABM_REL_CNF_size NULL
#define FUNC_DHCP_SEND_ABM_REL_CNF FUNC_DHCP_SEND_ABM_REL_CNF__enum,FUNC_DHCP_SEND_ABM_REL_CNF_size

// FUNC_DHCP_SEND_ABM_NOTIFY_IND
#define FUNC_DHCP_SEND_ABM_NOTIFY_IND_size "c"
#define FUNC_DHCP_SEND_ABM_NOTIFY_IND FUNC_DHCP_SEND_ABM_NOTIFY_IND__enum,FUNC_DHCP_SEND_ABM_NOTIFY_IND_size

// FUNC_DHCP_SEND_SIP_NOTIFY_IND
#define FUNC_DHCP_SEND_SIP_NOTIFY_IND_size "c"
#define FUNC_DHCP_SEND_SIP_NOTIFY_IND FUNC_DHCP_SEND_SIP_NOTIFY_IND__enum,FUNC_DHCP_SEND_SIP_NOTIFY_IND_size

// FUNC_DHCP_SEND_TCPIP_ARP_PROBE_REQ
#define FUNC_DHCP_SEND_TCPIP_ARP_PROBE_REQ_size NULL
#define FUNC_DHCP_SEND_TCPIP_ARP_PROBE_REQ FUNC_DHCP_SEND_TCPIP_ARP_PROBE_REQ__enum,FUNC_DHCP_SEND_TCPIP_ARP_PROBE_REQ_size

// FUNC_DHCP_SEND_TCPIP_GW_ARP_PROBE_REQ
#define FUNC_DHCP_SEND_TCPIP_GW_ARP_PROBE_REQ_size NULL
#define FUNC_DHCP_SEND_TCPIP_GW_ARP_PROBE_REQ FUNC_DHCP_SEND_TCPIP_GW_ARP_PROBE_REQ__enum,FUNC_DHCP_SEND_TCPIP_GW_ARP_PROBE_REQ_size

// FUNC_DHCP_SEND_TCPIP_ARP_QUERY_REQ
#define FUNC_DHCP_SEND_TCPIP_ARP_QUERY_REQ_size NULL
#define FUNC_DHCP_SEND_TCPIP_ARP_QUERY_REQ FUNC_DHCP_SEND_TCPIP_ARP_QUERY_REQ__enum,FUNC_DHCP_SEND_TCPIP_ARP_QUERY_REQ_size

// FUNC_DHCP_RESET_CNTX
#define FUNC_DHCP_RESET_CNTX_size NULL
#define FUNC_DHCP_RESET_CNTX FUNC_DHCP_RESET_CNTX__enum,FUNC_DHCP_RESET_CNTX_size

// FUNC_DHCP_SET_CNTX
#define FUNC_DHCP_SET_CNTX_size NULL
#define FUNC_DHCP_SET_CNTX FUNC_DHCP_SET_CNTX__enum,FUNC_DHCP_SET_CNTX_size

// FUNC_DHCP_SET_CANDI
#define FUNC_DHCP_SET_CANDI_size NULL
#define FUNC_DHCP_SET_CANDI FUNC_DHCP_SET_CANDI__enum,FUNC_DHCP_SET_CANDI_size

// STATE_DHCP_TRANSITSTATE
#define STATE_DHCP_TRANSITSTATE_size "c"
#define STATE_DHCP_TRANSITSTATE STATE_DHCP_TRANSITSTATE__enum,STATE_DHCP_TRANSITSTATE_size

// INFO_RECV_EXT_Q
#define INFO_RECV_EXT_Q_size "h"
#define INFO_RECV_EXT_Q INFO_RECV_EXT_Q__enum,INFO_RECV_EXT_Q_size

// INFO_DHCP_SOCID
#define INFO_DHCP_SOCID_size "d"
#define INFO_DHCP_SOCID INFO_DHCP_SOCID__enum,INFO_DHCP_SOCID_size

// INFO_DHCP_TIME
#define INFO_DHCP_TIME_size "d"
#define INFO_DHCP_TIME INFO_DHCP_TIME__enum,INFO_DHCP_TIME_size

// INFO_DHCP_GET_BUFF
#define INFO_DHCP_GET_BUFF_size "d"
#define INFO_DHCP_GET_BUFF INFO_DHCP_GET_BUFF__enum,INFO_DHCP_GET_BUFF_size

// INFO_COMP_OFFER
#define INFO_COMP_OFFER_size "‚d"
#define INFO_COMP_OFFER INFO_COMP_OFFER__enum,INFO_COMP_OFFER_size

// INFO_DHCP_GOTACK
#define INFO_DHCP_GOTACK_size NULL
#define INFO_DHCP_GOTACK INFO_DHCP_GOTACK__enum,INFO_DHCP_GOTACK_size

// INFO_DHCP_GOTNAK
#define INFO_DHCP_GOTNAK_size NULL
#define INFO_DHCP_GOTNAK INFO_DHCP_GOTNAK__enum,INFO_DHCP_GOTNAK_size

// INFO_DHCP_READFILE_RET
#define INFO_DHCP_READFILE_RET_size "c"
#define INFO_DHCP_READFILE_RET INFO_DHCP_READFILE_RET__enum,INFO_DHCP_READFILE_RET_size

// INFO_DHCP_WRITEFILE_RET
#define INFO_DHCP_WRITEFILE_RET_size "c"
#define INFO_DHCP_WRITEFILE_RET INFO_DHCP_WRITEFILE_RET__enum,INFO_DHCP_WRITEFILE_RET_size

// INFO_VALIDATE_RCVDMSG_XID
#define INFO_VALIDATE_RCVDMSG_XID_size "c‚d"
#define INFO_VALIDATE_RCVDMSG_XID INFO_VALIDATE_RCVDMSG_XID__enum,INFO_VALIDATE_RCVDMSG_XID_size

// INFO_VALIDATE_RCVDMSG_MAC
#define INFO_VALIDATE_RCVDMSG_MAC_size "c"
#define INFO_VALIDATE_RCVDMSG_MAC INFO_VALIDATE_RCVDMSG_MAC__enum,INFO_VALIDATE_RCVDMSG_MAC_size

// INFO_DHCP_GOTEXPECTED
#define INFO_DHCP_GOTEXPECTED_size NULL
#define INFO_DHCP_GOTEXPECTED INFO_DHCP_GOTEXPECTED__enum,INFO_DHCP_GOTEXPECTED_size

// INFO_DHCP_LEASE_TIME
#define INFO_DHCP_LEASE_TIME_size "ƒd"
#define INFO_DHCP_LEASE_TIME INFO_DHCP_LEASE_TIME__enum,INFO_DHCP_LEASE_TIME_size

// INFO_DHCP_SERVER
#define INFO_DHCP_SERVER_size "„d"
#define INFO_DHCP_SERVER INFO_DHCP_SERVER__enum,INFO_DHCP_SERVER_size

// INFO_DHCP_RESIDUAL_TIME
#define INFO_DHCP_RESIDUAL_TIME_size "ƒd"
#define INFO_DHCP_RESIDUAL_TIME INFO_DHCP_RESIDUAL_TIME__enum,INFO_DHCP_RESIDUAL_TIME_size

// WARN_BAD_DHCPMSGTYPE
#define WARN_BAD_DHCPMSGTYPE_size "c"
#define WARN_BAD_DHCPMSGTYPE WARN_BAD_DHCPMSGTYPE__enum,WARN_BAD_DHCPMSGTYPE_size

// WARN_DHCP_HITRETXLIMIT
#define WARN_DHCP_HITRETXLIMIT_size NULL
#define WARN_DHCP_HITRETXLIMIT WARN_DHCP_HITRETXLIMIT__enum,WARN_DHCP_HITRETXLIMIT_size

// WARN_DHCP_HITRETRYLIMIT
#define WARN_DHCP_HITRETRYLIMIT_size NULL
#define WARN_DHCP_HITRETRYLIMIT WARN_DHCP_HITRETRYLIMIT__enum,WARN_DHCP_HITRETRYLIMIT_size

// WARN_NO_DHCPACKNAK
#define WARN_NO_DHCPACKNAK_size NULL
#define WARN_NO_DHCPACKNAK WARN_NO_DHCPACKNAK__enum,WARN_NO_DHCPACKNAK_size

// WARN_DHCP_HEADER_ERROR
#define WARN_DHCP_HEADER_ERROR_size "d"
#define WARN_DHCP_HEADER_ERROR WARN_DHCP_HEADER_ERROR__enum,WARN_DHCP_HEADER_ERROR_size

// WARN_DHCP_OPTION_ERROR
#define WARN_DHCP_OPTION_ERROR_size "d"
#define WARN_DHCP_OPTION_ERROR WARN_DHCP_OPTION_ERROR__enum,WARN_DHCP_OPTION_ERROR_size

// WARN_DHCP_NO_OPTION
#define WARN_DHCP_NO_OPTION_size NULL
#define WARN_DHCP_NO_OPTION WARN_DHCP_NO_OPTION__enum,WARN_DHCP_NO_OPTION_size

// WARN_DHCP_DELETEFILE
#define WARN_DHCP_DELETEFILE_size NULL
#define WARN_DHCP_DELETEFILE WARN_DHCP_DELETEFILE__enum,WARN_DHCP_DELETEFILE_size

// ERROR_DHCP_GET_BUFF_FAIL
#define ERROR_DHCP_GET_BUFF_FAIL_size NULL
#define ERROR_DHCP_GET_BUFF_FAIL ERROR_DHCP_GET_BUFF_FAIL__enum,ERROR_DHCP_GET_BUFF_FAIL_size

// ERROR_NONSUPPORT_MSG
#define ERROR_NONSUPPORT_MSG_size "h"
#define ERROR_NONSUPPORT_MSG ERROR_NONSUPPORT_MSG__enum,ERROR_NONSUPPORT_MSG_size

// ERROR_NONSUPPORT_OPT
#define ERROR_NONSUPPORT_OPT_size "c"
#define ERROR_NONSUPPORT_OPT ERROR_NONSUPPORT_OPT__enum,ERROR_NONSUPPORT_OPT_size

// ERROR_DHCP_FSOPEN
#define ERROR_DHCP_FSOPEN_size "d"
#define ERROR_DHCP_FSOPEN ERROR_DHCP_FSOPEN__enum,ERROR_DHCP_FSOPEN_size

// ERROR_DHCP_FSREAD
#define ERROR_DHCP_FSREAD_size "„d"
#define ERROR_DHCP_FSREAD ERROR_DHCP_FSREAD__enum,ERROR_DHCP_FSREAD_size

// ERROR_DHCP_FSWRITE
#define ERROR_DHCP_FSWRITE_size "„d"
#define ERROR_DHCP_FSWRITE ERROR_DHCP_FSWRITE__enum,ERROR_DHCP_FSWRITE_size

// ERROR_DHCP_DELETEFILE_FAIL
#define ERROR_DHCP_DELETEFILE_FAIL_size "d"
#define ERROR_DHCP_DELETEFILE_FAIL ERROR_DHCP_DELETEFILE_FAIL__enum,ERROR_DHCP_DELETEFILE_FAIL_size

// ERROR_DHCP_SOCCREATE
#define ERROR_DHCP_SOCCREATE_size NULL
#define ERROR_DHCP_SOCCREATE ERROR_DHCP_SOCCREATE__enum,ERROR_DHCP_SOCCREATE_size

// ERROR_DHCP_SOCSETSOCKOPT
#define ERROR_DHCP_SOCSETSOCKOPT_size NULL
#define ERROR_DHCP_SOCSETSOCKOPT ERROR_DHCP_SOCSETSOCKOPT__enum,ERROR_DHCP_SOCSETSOCKOPT_size

// ERROR_DHCP_SOCBIND
#define ERROR_DHCP_SOCBIND_size NULL
#define ERROR_DHCP_SOCBIND ERROR_DHCP_SOCBIND__enum,ERROR_DHCP_SOCBIND_size

// ERROR_DHCP_SOCSENDTO
#define ERROR_DHCP_SOCSENDTO_size NULL
#define ERROR_DHCP_SOCSENDTO ERROR_DHCP_SOCSENDTO__enum,ERROR_DHCP_SOCSENDTO_size

// ERROR_DHCP_RECV
#define ERROR_DHCP_RECV_size NULL
#define ERROR_DHCP_RECV ERROR_DHCP_RECV__enum,ERROR_DHCP_RECV_size

// ERROR_DHCP_SERVERID
#define ERROR_DHCP_SERVERID_size NULL
#define ERROR_DHCP_SERVERID ERROR_DHCP_SERVERID__enum,ERROR_DHCP_SERVERID_size

// ERROR_CLOSEINVALIDSOCKET
#define ERROR_CLOSEINVALIDSOCKET_size "cd"
#define ERROR_CLOSEINVALIDSOCKET ERROR_CLOSEINVALIDSOCKET__enum,ERROR_CLOSEINVALIDSOCKET_size

// ERROR_WRONG_SOCEVENT
#define ERROR_WRONG_SOCEVENT_size "c"
#define ERROR_WRONG_SOCEVENT ERROR_WRONG_SOCEVENT__enum,ERROR_WRONG_SOCEVENT_size

// ERROR_DHCPSENDTO_WOULDBLOCK
#define ERROR_DHCPSENDTO_WOULDBLOCK_size NULL
#define ERROR_DHCPSENDTO_WOULDBLOCK ERROR_DHCPSENDTO_WOULDBLOCK__enum,ERROR_DHCPSENDTO_WOULDBLOCK_size

// ERROR_WRONG_TIMER
#define ERROR_WRONG_TIMER_size NULL
#define ERROR_WRONG_TIMER ERROR_WRONG_TIMER__enum,ERROR_WRONG_TIMER_size

// ERROR_BAD_MSGID
#define ERROR_BAD_MSGID_size "h"
#define ERROR_BAD_MSGID ERROR_BAD_MSGID__enum,ERROR_BAD_MSGID_size

// ERROR_DHCP_PARSEOPT_FAIL
#define ERROR_DHCP_PARSEOPT_FAIL_size "c"
#define ERROR_DHCP_PARSEOPT_FAIL ERROR_DHCP_PARSEOPT_FAIL__enum,ERROR_DHCP_PARSEOPT_FAIL_size

// ERROR_DHCPPACK
#define ERROR_DHCPPACK_size NULL
#define ERROR_DHCPPACK ERROR_DHCPPACK__enum,ERROR_DHCPPACK_size

// GROUP1_DHCP_XID
#define GROUP1_DHCP_XID_size "d"
#define GROUP1_DHCP_XID GROUP1_DHCP_XID__enum,GROUP1_DHCP_XID_size

// GROUP1_DHCP_CIADDR
#define GROUP1_DHCP_CIADDR_size "„d"
#define GROUP1_DHCP_CIADDR GROUP1_DHCP_CIADDR__enum,GROUP1_DHCP_CIADDR_size

// GROUP1_DHCP_YIADDR
#define GROUP1_DHCP_YIADDR_size "„d"
#define GROUP1_DHCP_YIADDR GROUP1_DHCP_YIADDR__enum,GROUP1_DHCP_YIADDR_size

// GROUP1_DHCP_SIADDR
#define GROUP1_DHCP_SIADDR_size "„d"
#define GROUP1_DHCP_SIADDR GROUP1_DHCP_SIADDR__enum,GROUP1_DHCP_SIADDR_size

// GROUP1_DHCP_GIADDR
#define GROUP1_DHCP_GIADDR_size "„d"
#define GROUP1_DHCP_GIADDR GROUP1_DHCP_GIADDR__enum,GROUP1_DHCP_GIADDR_size

// GROUP1_DHCP_CHADDR
#define GROUP1_DHCP_CHADDR_size "†d"
#define GROUP1_DHCP_CHADDR GROUP1_DHCP_CHADDR__enum,GROUP1_DHCP_CHADDR_size

// GROUP1_DHCP_NETMASK
#define GROUP1_DHCP_NETMASK_size "„d"
#define GROUP1_DHCP_NETMASK GROUP1_DHCP_NETMASK__enum,GROUP1_DHCP_NETMASK_size

// GROUP1_DHCP_ROUTER
#define GROUP1_DHCP_ROUTER_size "„d"
#define GROUP1_DHCP_ROUTER GROUP1_DHCP_ROUTER__enum,GROUP1_DHCP_ROUTER_size

// GROUP1_DHCP_DNS1
#define GROUP1_DHCP_DNS1_size "„d"
#define GROUP1_DHCP_DNS1 GROUP1_DHCP_DNS1__enum,GROUP1_DHCP_DNS1_size

// GROUP1_DHCP_DNS2
#define GROUP1_DHCP_DNS2_size "„d"
#define GROUP1_DHCP_DNS2 GROUP1_DHCP_DNS2__enum,GROUP1_DHCP_DNS2_size

// GROUP1_DHCP_MTU
#define GROUP1_DHCP_MTU_size "d"
#define GROUP1_DHCP_MTU GROUP1_DHCP_MTU__enum,GROUP1_DHCP_MTU_size

// GROUP1_DHCP_IPADDR
#define GROUP1_DHCP_IPADDR_size "„d"
#define GROUP1_DHCP_IPADDR GROUP1_DHCP_IPADDR__enum,GROUP1_DHCP_IPADDR_size

// GROUP1_DHCP_LEASETIME
#define GROUP1_DHCP_LEASETIME_size "d"
#define GROUP1_DHCP_LEASETIME GROUP1_DHCP_LEASETIME__enum,GROUP1_DHCP_LEASETIME_size

// GROUP1_DHCP_OPTOVERLOAD
#define GROUP1_DHCP_OPTOVERLOAD_size "d"
#define GROUP1_DHCP_OPTOVERLOAD GROUP1_DHCP_OPTOVERLOAD__enum,GROUP1_DHCP_OPTOVERLOAD_size

// GROUP1_DHCP_MSGTYPE
#define GROUP1_DHCP_MSGTYPE_size "c"
#define GROUP1_DHCP_MSGTYPE GROUP1_DHCP_MSGTYPE__enum,GROUP1_DHCP_MSGTYPE_size

// GROUP1_DHCP_SERVERID
#define GROUP1_DHCP_SERVERID_size "„d"
#define GROUP1_DHCP_SERVERID GROUP1_DHCP_SERVERID__enum,GROUP1_DHCP_SERVERID_size

// GROUP1_DHCP_MSGSIZE
#define GROUP1_DHCP_MSGSIZE_size "d"
#define GROUP1_DHCP_MSGSIZE GROUP1_DHCP_MSGSIZE__enum,GROUP1_DHCP_MSGSIZE_size

// GROUP1_DHCP_T1
#define GROUP1_DHCP_T1_size "d"
#define GROUP1_DHCP_T1 GROUP1_DHCP_T1__enum,GROUP1_DHCP_T1_size

// GROUP1_DHCP_T2
#define GROUP1_DHCP_T2_size "d"
#define GROUP1_DHCP_T2 GROUP1_DHCP_T2__enum,GROUP1_DHCP_T2_size

// GROUP1_DHCP_SIP
#define GROUP1_DHCP_SIP_size "d"
#define GROUP1_DHCP_SIP GROUP1_DHCP_SIP__enum,GROUP1_DHCP_SIP_size

// GROUP4_DHCPFILE_ACCOUNTID
#define GROUP4_DHCPFILE_ACCOUNTID_size "d"
#define GROUP4_DHCPFILE_ACCOUNTID GROUP4_DHCPFILE_ACCOUNTID__enum,GROUP4_DHCPFILE_ACCOUNTID_size

// GROUP4_DHCPFILE_SOCKISCREATED
#define GROUP4_DHCPFILE_SOCKISCREATED_size "c"
#define GROUP4_DHCPFILE_SOCKISCREATED GROUP4_DHCPFILE_SOCKISCREATED__enum,GROUP4_DHCPFILE_SOCKISCREATED_size

// GROUP4_DHCPFILE_SOCKETID
#define GROUP4_DHCPFILE_SOCKETID_size "d"
#define GROUP4_DHCPFILE_SOCKETID GROUP4_DHCPFILE_SOCKETID__enum,GROUP4_DHCPFILE_SOCKETID_size

// GROUP4_DHCPFILE_MACADDR
#define GROUP4_DHCPFILE_MACADDR_size "†d"
#define GROUP4_DHCPFILE_MACADDR GROUP4_DHCPFILE_MACADDR__enum,GROUP4_DHCPFILE_MACADDR_size

// GROUP4_DHCPFILE_MAXDHCPMSGSIZE
#define GROUP4_DHCPFILE_MAXDHCPMSGSIZE_size "d"
#define GROUP4_DHCPFILE_MAXDHCPMSGSIZE GROUP4_DHCPFILE_MAXDHCPMSGSIZE__enum,GROUP4_DHCPFILE_MAXDHCPMSGSIZE_size

// GROUP4_DHCPFILE_CHANGESTATE
#define GROUP4_DHCPFILE_CHANGESTATE_size "c"
#define GROUP4_DHCPFILE_CHANGESTATE GROUP4_DHCPFILE_CHANGESTATE__enum,GROUP4_DHCPFILE_CHANGESTATE_size

// GROUP4_DHCPFILE_STATE
#define GROUP4_DHCPFILE_STATE_size "c"
#define GROUP4_DHCPFILE_STATE GROUP4_DHCPFILE_STATE__enum,GROUP4_DHCPFILE_STATE_size

// GROUP4_DHCPFILE_SERVERID
#define GROUP4_DHCPFILE_SERVERID_size "„d"
#define GROUP4_DHCPFILE_SERVERID GROUP4_DHCPFILE_SERVERID__enum,GROUP4_DHCPFILE_SERVERID_size

// GROUP4_DHCPFILE_CLIENTID
#define GROUP4_DHCPFILE_CLIENTID_size "ˆd"
#define GROUP4_DHCPFILE_CLIENTID GROUP4_DHCPFILE_CLIENTID__enum,GROUP4_DHCPFILE_CLIENTID_size

// GROUP4_DHCPFILE_XID
#define GROUP4_DHCPFILE_XID_size "d"
#define GROUP4_DHCPFILE_XID GROUP4_DHCPFILE_XID__enum,GROUP4_DHCPFILE_XID_size

// GROUP4_DHCPFILE_STARTTIME
#define GROUP4_DHCPFILE_STARTTIME_size "d"
#define GROUP4_DHCPFILE_STARTTIME GROUP4_DHCPFILE_STARTTIME__enum,GROUP4_DHCPFILE_STARTTIME_size

// GROUP4_DHCPFILE_T1
#define GROUP4_DHCPFILE_T1_size "d"
#define GROUP4_DHCPFILE_T1 GROUP4_DHCPFILE_T1__enum,GROUP4_DHCPFILE_T1_size

// GROUP4_DHCPFILE_T2
#define GROUP4_DHCPFILE_T2_size "d"
#define GROUP4_DHCPFILE_T2 GROUP4_DHCPFILE_T2__enum,GROUP4_DHCPFILE_T2_size

// GROUP4_DHCPFILE_LEASETIME
#define GROUP4_DHCPFILE_LEASETIME_size "d"
#define GROUP4_DHCPFILE_LEASETIME GROUP4_DHCPFILE_LEASETIME__enum,GROUP4_DHCPFILE_LEASETIME_size

// GROUP4_DHCPFILE_OPTOVERLOAD
#define GROUP4_DHCPFILE_OPTOVERLOAD_size "d"
#define GROUP4_DHCPFILE_OPTOVERLOAD GROUP4_DHCPFILE_OPTOVERLOAD__enum,GROUP4_DHCPFILE_OPTOVERLOAD_size

// GROUP4_DHCPFILE_DHCPMSGTYPE
#define GROUP4_DHCPFILE_DHCPMSGTYPE_size "c"
#define GROUP4_DHCPFILE_DHCPMSGTYPE GROUP4_DHCPFILE_DHCPMSGTYPE__enum,GROUP4_DHCPFILE_DHCPMSGTYPE_size

// GROUP4_DHCPFILE_IPADDR
#define GROUP4_DHCPFILE_IPADDR_size "„d"
#define GROUP4_DHCPFILE_IPADDR GROUP4_DHCPFILE_IPADDR__enum,GROUP4_DHCPFILE_IPADDR_size

// GROUP4_DHCPFILE_NETMASK
#define GROUP4_DHCPFILE_NETMASK_size "„d"
#define GROUP4_DHCPFILE_NETMASK GROUP4_DHCPFILE_NETMASK__enum,GROUP4_DHCPFILE_NETMASK_size

// GROUP4_DHCPFILE_ROUTER
#define GROUP4_DHCPFILE_ROUTER_size "„d"
#define GROUP4_DHCPFILE_ROUTER GROUP4_DHCPFILE_ROUTER__enum,GROUP4_DHCPFILE_ROUTER_size

// GROUP4_DHCPFILE_DNS1
#define GROUP4_DHCPFILE_DNS1_size "„d"
#define GROUP4_DHCPFILE_DNS1 GROUP4_DHCPFILE_DNS1__enum,GROUP4_DHCPFILE_DNS1_size

// GROUP4_DHCPFILE_DNS2
#define GROUP4_DHCPFILE_DNS2_size "„d"
#define GROUP4_DHCPFILE_DNS2 GROUP4_DHCPFILE_DNS2__enum,GROUP4_DHCPFILE_DNS2_size

// GROUP4_DHCPFILE_MTU
#define GROUP4_DHCPFILE_MTU_size "d"
#define GROUP4_DHCPFILE_MTU GROUP4_DHCPFILE_MTU__enum,GROUP4_DHCPFILE_MTU_size

// GROUP4_DHCPFILE_SIPENC
#define GROUP4_DHCPFILE_SIPENC_size "c"
#define GROUP4_DHCPFILE_SIPENC GROUP4_DHCPFILE_SIPENC__enum,GROUP4_DHCPFILE_SIPENC_size

// GROUP4_DHCPFILE_SIP1
#define GROUP4_DHCPFILE_SIP1_size "„d"
#define GROUP4_DHCPFILE_SIP1 GROUP4_DHCPFILE_SIP1__enum,GROUP4_DHCPFILE_SIP1_size

// GROUP4_DHCPFILE_SIP2
#define GROUP4_DHCPFILE_SIP2_size "„d"
#define GROUP4_DHCPFILE_SIP2 GROUP4_DHCPFILE_SIP2__enum,GROUP4_DHCPFILE_SIP2_size

// GROUP4_DHCPFILE_RCVDEXPECTED
#define GROUP4_DHCPFILE_RCVDEXPECTED_size "c"
#define GROUP4_DHCPFILE_RCVDEXPECTED GROUP4_DHCPFILE_RCVDEXPECTED__enum,GROUP4_DHCPFILE_RCVDEXPECTED_size

// GROUP4_DHCPFILE_TXCOUNTER
#define GROUP4_DHCPFILE_TXCOUNTER_size "d"
#define GROUP4_DHCPFILE_TXCOUNTER GROUP4_DHCPFILE_TXCOUNTER__enum,GROUP4_DHCPFILE_TXCOUNTER_size

// GROUP4_DHCPFILE_TRIES
#define GROUP4_DHCPFILE_TRIES_size "d"
#define GROUP4_DHCPFILE_TRIES GROUP4_DHCPFILE_TRIES__enum,GROUP4_DHCPFILE_TRIES_size

// GROUP4_DHCPFILE_SNDBUF
#define GROUP4_DHCPFILE_SNDBUF_size "d"
#define GROUP4_DHCPFILE_SNDBUF GROUP4_DHCPFILE_SNDBUF__enum,GROUP4_DHCPFILE_SNDBUF_size

// GROUP4_DHCPFILE_SNDBUFSIZE
#define GROUP4_DHCPFILE_SNDBUFSIZE_size "d"
#define GROUP4_DHCPFILE_SNDBUFSIZE GROUP4_DHCPFILE_SNDBUFSIZE__enum,GROUP4_DHCPFILE_SNDBUFSIZE_size

// GROUP4_DHCPFILE_RCVBUF
#define GROUP4_DHCPFILE_RCVBUF_size "d"
#define GROUP4_DHCPFILE_RCVBUF GROUP4_DHCPFILE_RCVBUF__enum,GROUP4_DHCPFILE_RCVBUF_size


#endif // DHCP_TRC_GEN.H
