#ifndef _EMS_TRC_GEN_H_
#define _EMS_TRC_GEN_H_

// EMS_SET_EDIT_SEG_NUM
#define EMS_SET_EDIT_SEG_NUM_size "d"
#define EMS_SET_EDIT_SEG_NUM EMS_SET_EDIT_SEG_NUM__enum,EMS_SET_EDIT_SEG_NUM_size

// EMS_SET_EDIT_SEG_ERROR
#define EMS_SET_EDIT_SEG_ERROR_size "d"
#define EMS_SET_EDIT_SEG_ERROR EMS_SET_EDIT_SEG_ERROR__enum,EMS_SET_EDIT_SEG_ERROR_size


#endif // EMS_TRC_GEN.H
