#ifndef _FLC_TRC_GEN_H_
#define _FLC_TRC_GEN_H_

// POOL_INIT
#define POOL_INIT_size "cƒdc"
#define POOL_INIT POOL_INIT__enum,POOL_INIT_size

// POOL_DEINIT
#define POOL_DEINIT_size "cƒdc"
#define POOL_DEINIT POOL_DEINIT__enum,POOL_DEINIT_size

// MB_INIT
#define MB_INIT_size "cdcd"
#define MB_INIT MB_INIT__enum,MB_INIT_size

// MB_DEINIT
#define MB_DEINIT_size "cdcd"
#define MB_DEINIT MB_DEINIT__enum,MB_DEINIT_size

// RET_RESULT
#define RET_RESULT_size "cd"
#define RET_RESULT RET_RESULT__enum,RET_RESULT_size

// MB_NO_MEM
#define MB_NO_MEM_size "cd"
#define MB_NO_MEM MB_NO_MEM__enum,MB_NO_MEM_size

// FLC2_GROW_POOL
#define FLC2_GROW_POOL_size "c‚d"
#define FLC2_GROW_POOL FLC2_GROW_POOL__enum,FLC2_GROW_POOL_size

// FLC2_SHRINK_POOL
#define FLC2_SHRINK_POOL_size "c‚d"
#define FLC2_SHRINK_POOL FLC2_SHRINK_POOL__enum,FLC2_SHRINK_POOL_size

// FLC2_UNACK_PSPDU_DL_EXCEED_PKT_NO
#define FLC2_UNACK_PSPDU_DL_EXCEED_PKT_NO_size "cd"
#define FLC2_UNACK_PSPDU_DL_EXCEED_PKT_NO FLC2_UNACK_PSPDU_DL_EXCEED_PKT_NO__enum,FLC2_UNACK_PSPDU_DL_EXCEED_PKT_NO_size

// FLC2_MDI_DBG_INFO_POOL
#define FLC2_MDI_DBG_INFO_POOL_size "cƒd"
#define FLC2_MDI_DBG_INFO_POOL FLC2_MDI_DBG_INFO_POOL__enum,FLC2_MDI_DBG_INFO_POOL_size

// FLC2_MDI_DBG_INFO_MB
#define FLC2_MDI_DBG_INFO_MB_size "cƒd"
#define FLC2_MDI_DBG_INFO_MB FLC2_MDI_DBG_INFO_MB__enum,FLC2_MDI_DBG_INFO_MB_size

// FLC2_MDI_ALLOC_LIST
#define FLC2_MDI_ALLOC_LIST_size "dhd"
#define FLC2_MDI_ALLOC_LIST FLC2_MDI_ALLOC_LIST__enum,FLC2_MDI_ALLOC_LIST_size

// FLC2_MDI_FREE_LIST
#define FLC2_MDI_FREE_LIST_size "dhd"
#define FLC2_MDI_FREE_LIST FLC2_MDI_FREE_LIST__enum,FLC2_MDI_FREE_LIST_size

// FLC2_RECONFIG_PROFILE
#define FLC2_RECONFIG_PROFILE_size "ƒc"
#define FLC2_RECONFIG_PROFILE FLC2_RECONFIG_PROFILE__enum,FLC2_RECONFIG_PROFILE_size

// FLC2_TST_STRING
#define FLC2_TST_STRING_size "‚d"
#define FLC2_TST_STRING FLC2_TST_STRING__enum,FLC2_TST_STRING_size

// FLC2_RECONFIG_101
#define FLC2_RECONFIG_101_size "ƒc"
#define FLC2_RECONFIG_101 FLC2_RECONFIG_101__enum,FLC2_RECONFIG_101_size

// FLC2_RECONFIG_102
#define FLC2_RECONFIG_102_size "ƒc"
#define FLC2_RECONFIG_102 FLC2_RECONFIG_102__enum,FLC2_RECONFIG_102_size

// FLC2_RECONFIG_103
#define FLC2_RECONFIG_103_size "‚c"
#define FLC2_RECONFIG_103 FLC2_RECONFIG_103__enum,FLC2_RECONFIG_103_size

// FLC2_RECONFIG_104
#define FLC2_RECONFIG_104_size "ƒc"
#define FLC2_RECONFIG_104 FLC2_RECONFIG_104__enum,FLC2_RECONFIG_104_size

// FLC2_RECONFIG_105
#define FLC2_RECONFIG_105_size "‚c"
#define FLC2_RECONFIG_105 FLC2_RECONFIG_105__enum,FLC2_RECONFIG_105_size

// FLC2_ASSERT_API
#define FLC2_ASSERT_API_size "c"
#define FLC2_ASSERT_API FLC2_ASSERT_API__enum,FLC2_ASSERT_API_size

// FLC2_ASSERT_FILENAME
#define FLC2_ASSERT_FILENAME_size "•c"
#define FLC2_ASSERT_FILENAME FLC2_ASSERT_FILENAME__enum,FLC2_ASSERT_FILENAME_size

// FLC2_ASSERT_LINE
#define FLC2_ASSERT_LINE_size "d"
#define FLC2_ASSERT_LINE FLC2_ASSERT_LINE__enum,FLC2_ASSERT_LINE_size

// FLC2_POOL_STATISTIC_TRACE
#define FLC2_POOL_STATISTIC_TRACE_size "c„d"
#define FLC2_POOL_STATISTIC_TRACE FLC2_POOL_STATISTIC_TRACE__enum,FLC2_POOL_STATISTIC_TRACE_size

// REASON
#define REASON_size "c"
#define REASON REASON__enum,REASON_size

// FLC2_WRONG_CONFIG
#define FLC2_WRONG_CONFIG_size "c"
#define FLC2_WRONG_CONFIG FLC2_WRONG_CONFIG__enum,FLC2_WRONG_CONFIG_size

// FLC2_RECONFIG_NOT_ON
#define FLC2_RECONFIG_NOT_ON_size NULL
#define FLC2_RECONFIG_NOT_ON FLC2_RECONFIG_NOT_ON__enum,FLC2_RECONFIG_NOT_ON_size

// FLC2_RECONFIG_ERR
#define FLC2_RECONFIG_ERR_size NULL
#define FLC2_RECONFIG_ERR FLC2_RECONFIG_ERR__enum,FLC2_RECONFIG_ERR_size

// POOL_INFO_1
#define POOL_INFO_1_size "c…d"
#define POOL_INFO_1 POOL_INFO_1__enum,POOL_INFO_1_size

// POOL_INFO_2
#define POOL_INFO_2_size "c„d"
#define POOL_INFO_2 POOL_INFO_2__enum,POOL_INFO_2_size

// MB_INFO
#define MB_INFO_size "c‚dcd"
#define MB_INFO MB_INFO__enum,MB_INFO_size

// PROFILE_INFO
#define PROFILE_INFO_size "dcƒd"
#define PROFILE_INFO PROFILE_INFO__enum,PROFILE_INFO_size

// PROFILE_INFO_1
#define PROFILE_INFO_1_size "cdcƒd"
#define PROFILE_INFO_1 PROFILE_INFO_1__enum,PROFILE_INFO_1_size

// PROFILE_INFO_2
#define PROFILE_INFO_2_size "„d"
#define PROFILE_INFO_2 PROFILE_INFO_2__enum,PROFILE_INFO_2_size

// ADM_MB_INFO
#define ADM_MB_INFO_size "d"
#define ADM_MB_INFO ADM_MB_INFO__enum,ADM_MB_INFO_size

// FIX_SIZE_MB_INFO
#define FIX_SIZE_MB_INFO_size "‡d"
#define FIX_SIZE_MB_INFO FIX_SIZE_MB_INFO__enum,FIX_SIZE_MB_INFO_size

// FLC2_GROW_FAIL
#define FLC2_GROW_FAIL_size "c‚d"
#define FLC2_GROW_FAIL FLC2_GROW_FAIL__enum,FLC2_GROW_FAIL_size

// FLC2_SHRINK_FAIL
#define FLC2_SHRINK_FAIL_size "c"
#define FLC2_SHRINK_FAIL FLC2_SHRINK_FAIL__enum,FLC2_SHRINK_FAIL_size

// FLC2_QUERY_FAIL
#define FLC2_QUERY_FAIL_size "c"
#define FLC2_QUERY_FAIL FLC2_QUERY_FAIL__enum,FLC2_QUERY_FAIL_size

// FLC2_HIGH_THRES
#define FLC2_HIGH_THRES_size "cƒd"
#define FLC2_HIGH_THRES FLC2_HIGH_THRES__enum,FLC2_HIGH_THRES_size

// FLC2_LOW_THRES
#define FLC2_LOW_THRES_size "cƒd"
#define FLC2_LOW_THRES FLC2_LOW_THRES__enum,FLC2_LOW_THRES_size

// FLC2_GET_MEM
#define FLC2_GET_MEM_size "c…d"
#define FLC2_GET_MEM FLC2_GET_MEM__enum,FLC2_GET_MEM_size

// FLC2_GET_MEM_ASSERT
#define FLC2_GET_MEM_ASSERT_size "c…d"
#define FLC2_GET_MEM_ASSERT FLC2_GET_MEM_ASSERT__enum,FLC2_GET_MEM_ASSERT_size

// FLC2_NEW_GET_MEM
#define FLC2_NEW_GET_MEM_size "c…dc…dc…dc…d"
#define FLC2_NEW_GET_MEM FLC2_NEW_GET_MEM__enum,FLC2_NEW_GET_MEM_size

// FLC2_NEW_GET_MEM_NEWLINE_1
#define FLC2_NEW_GET_MEM_NEWLINE_1_size "c…dc…dc…dc…d"
#define FLC2_NEW_GET_MEM_NEWLINE_1 FLC2_NEW_GET_MEM_NEWLINE_1__enum,FLC2_NEW_GET_MEM_NEWLINE_1_size

// FLC2_NEW_GET_MEM_NEWLINE_2
#define FLC2_NEW_GET_MEM_NEWLINE_2_size "c…dc…dc…dc…d"
#define FLC2_NEW_GET_MEM_NEWLINE_2 FLC2_NEW_GET_MEM_NEWLINE_2__enum,FLC2_NEW_GET_MEM_NEWLINE_2_size

// FLC2_NEW_GET_MEM_NEWLINE_3
#define FLC2_NEW_GET_MEM_NEWLINE_3_size "c…dc…dc…dc…d"
#define FLC2_NEW_GET_MEM_NEWLINE_3 FLC2_NEW_GET_MEM_NEWLINE_3__enum,FLC2_NEW_GET_MEM_NEWLINE_3_size

// FLC2_NEW_GET_MEM_NEWLINE_4
#define FLC2_NEW_GET_MEM_NEWLINE_4_size "c…dc…dc…dc…d"
#define FLC2_NEW_GET_MEM_NEWLINE_4 FLC2_NEW_GET_MEM_NEWLINE_4__enum,FLC2_NEW_GET_MEM_NEWLINE_4_size

// FLC2_FREE_MEM
#define FLC2_FREE_MEM_size "c„d"
#define FLC2_FREE_MEM FLC2_FREE_MEM__enum,FLC2_FREE_MEM_size

// FLC2_FREE_MEM_ASSERT
#define FLC2_FREE_MEM_ASSERT_size "c„d"
#define FLC2_FREE_MEM_ASSERT FLC2_FREE_MEM_ASSERT__enum,FLC2_FREE_MEM_ASSERT_size

// FLC2_NEW_FREE_MEM
#define FLC2_NEW_FREE_MEM_size "c„dc„dc„dc„d"
#define FLC2_NEW_FREE_MEM FLC2_NEW_FREE_MEM__enum,FLC2_NEW_FREE_MEM_size

// FLC2_NEW_FREE_MEM_NEWLINE_1
#define FLC2_NEW_FREE_MEM_NEWLINE_1_size "c„dc„dc„dc„d"
#define FLC2_NEW_FREE_MEM_NEWLINE_1 FLC2_NEW_FREE_MEM_NEWLINE_1__enum,FLC2_NEW_FREE_MEM_NEWLINE_1_size

// FLC2_NEW_FREE_MEM_NEWLINE_2
#define FLC2_NEW_FREE_MEM_NEWLINE_2_size "c„dc„dc„dc„d"
#define FLC2_NEW_FREE_MEM_NEWLINE_2 FLC2_NEW_FREE_MEM_NEWLINE_2__enum,FLC2_NEW_FREE_MEM_NEWLINE_2_size

// FLC2_NEW_FREE_MEM_NEWLINE_3
#define FLC2_NEW_FREE_MEM_NEWLINE_3_size "c„dc„dc„dc„d"
#define FLC2_NEW_FREE_MEM_NEWLINE_3 FLC2_NEW_FREE_MEM_NEWLINE_3__enum,FLC2_NEW_FREE_MEM_NEWLINE_3_size

// FLC2_NEW_FREE_MEM_NEWLINE_4
#define FLC2_NEW_FREE_MEM_NEWLINE_4_size "c„dc„dc„dc„d"
#define FLC2_NEW_FREE_MEM_NEWLINE_4 FLC2_NEW_FREE_MEM_NEWLINE_4__enum,FLC2_NEW_FREE_MEM_NEWLINE_4_size


#endif // FLC_TRC_GEN.H
