#ifndef _FS_TRC_GEN_H_
#define _FS_TRC_GEN_H_

// FS_API_FS_OPEN_S
#define FS_API_FS_OPEN_S_size "hÇd"
#define FS_API_FS_OPEN_S FS_API_FS_OPEN_S__enum,FS_API_FS_OPEN_S_size

// FS_API_FS_OPEN_E
#define FS_API_FS_OPEN_E_size "hd"
#define FS_API_FS_OPEN_E FS_API_FS_OPEN_E__enum,FS_API_FS_OPEN_E_size

// FS_API_FS_OPEN_E_TIME
#define FS_API_FS_OPEN_E_TIME_size "hÇd"
#define FS_API_FS_OPEN_E_TIME FS_API_FS_OPEN_E_TIME__enum,FS_API_FS_OPEN_E_TIME_size

// FS_API_FS_OPEN_E_TIME_0
#define FS_API_FS_OPEN_E_TIME_0_size "hd"
#define FS_API_FS_OPEN_E_TIME_0 FS_API_FS_OPEN_E_TIME_0__enum,FS_API_FS_OPEN_E_TIME_0_size

// FS_API_FS_CLOSE_S
#define FS_API_FS_CLOSE_S_size "hÇd"
#define FS_API_FS_CLOSE_S FS_API_FS_CLOSE_S__enum,FS_API_FS_CLOSE_S_size

// FS_API_FS_CLOSE_E
#define FS_API_FS_CLOSE_E_size "hÇd"
#define FS_API_FS_CLOSE_E FS_API_FS_CLOSE_E__enum,FS_API_FS_CLOSE_E_size

// FS_API_FS_READ_S
#define FS_API_FS_READ_S_size "håcÉd"
#define FS_API_FS_READ_S FS_API_FS_READ_S__enum,FS_API_FS_READ_S_size

// FS_API_FS_READ_E
#define FS_API_FS_READ_E_size "hÑd"
#define FS_API_FS_READ_E FS_API_FS_READ_E__enum,FS_API_FS_READ_E_size

// FS_API_FS_WRITE_S
#define FS_API_FS_WRITE_S_size "håcÉd"
#define FS_API_FS_WRITE_S FS_API_FS_WRITE_S__enum,FS_API_FS_WRITE_S_size

// FS_API_FS_WRITE_E
#define FS_API_FS_WRITE_E_size "hÑd"
#define FS_API_FS_WRITE_E FS_API_FS_WRITE_E__enum,FS_API_FS_WRITE_E_size

// FS_API_FS_SEEK_S
#define FS_API_FS_SEEK_S_size "hÇdc"
#define FS_API_FS_SEEK_S FS_API_FS_SEEK_S__enum,FS_API_FS_SEEK_S_size

// FS_API_FS_SEEK_E
#define FS_API_FS_SEEK_E_size "hÇd"
#define FS_API_FS_SEEK_E FS_API_FS_SEEK_E__enum,FS_API_FS_SEEK_E_size

// FS_API_FS_SEEKLARGEFILE_S
#define FS_API_FS_SEEKLARGEFILE_S_size "hÉdc"
#define FS_API_FS_SEEKLARGEFILE_S FS_API_FS_SEEKLARGEFILE_S__enum,FS_API_FS_SEEKLARGEFILE_S_size

// FS_API_FS_SEEKLARGEFILE_E
#define FS_API_FS_SEEKLARGEFILE_E_size "hd"
#define FS_API_FS_SEEKLARGEFILE_E FS_API_FS_SEEKLARGEFILE_E__enum,FS_API_FS_SEEKLARGEFILE_E_size

// FS_API_FS_COMMIT_S
#define FS_API_FS_COMMIT_S_size "håcd"
#define FS_API_FS_COMMIT_S FS_API_FS_COMMIT_S__enum,FS_API_FS_COMMIT_S_size

// FS_API_FS_COMMIT_E
#define FS_API_FS_COMMIT_E_size "hd"
#define FS_API_FS_COMMIT_E FS_API_FS_COMMIT_E__enum,FS_API_FS_COMMIT_E_size

// FS_API_FS_GETFILESIZE_S
#define FS_API_FS_GETFILESIZE_S_size "hd"
#define FS_API_FS_GETFILESIZE_S FS_API_FS_GETFILESIZE_S__enum,FS_API_FS_GETFILESIZE_S_size

// FS_API_FS_GETFILESIZE_E
#define FS_API_FS_GETFILESIZE_E_size "hd"
#define FS_API_FS_GETFILESIZE_E FS_API_FS_GETFILESIZE_E__enum,FS_API_FS_GETFILESIZE_E_size

// FS_API_FS_DELETEEX_S
#define FS_API_FS_DELETEEX_S_size "h"
#define FS_API_FS_DELETEEX_S FS_API_FS_DELETEEX_S__enum,FS_API_FS_DELETEEX_S_size

// FS_API_FS_DELETEEX_E
#define FS_API_FS_DELETEEX_E_size "hd"
#define FS_API_FS_DELETEEX_E FS_API_FS_DELETEEX_E__enum,FS_API_FS_DELETEEX_E_size

// FS_API_FS_DELETE_S
#define FS_API_FS_DELETE_S_size "h"
#define FS_API_FS_DELETE_S FS_API_FS_DELETE_S__enum,FS_API_FS_DELETE_S_size

// FS_API_FS_DELETE_E
#define FS_API_FS_DELETE_E_size "hd"
#define FS_API_FS_DELETE_E FS_API_FS_DELETE_E__enum,FS_API_FS_DELETE_E_size

// FS_API_FS_CREATEDIR_S
#define FS_API_FS_CREATEDIR_S_size "h"
#define FS_API_FS_CREATEDIR_S FS_API_FS_CREATEDIR_S__enum,FS_API_FS_CREATEDIR_S_size

// FS_API_FS_CREATEDIR_E
#define FS_API_FS_CREATEDIR_E_size "hd"
#define FS_API_FS_CREATEDIR_E FS_API_FS_CREATEDIR_E__enum,FS_API_FS_CREATEDIR_E_size

// FS_API_FS_GETCLUSTERSIZE_S
#define FS_API_FS_GETCLUSTERSIZE_S_size "hd"
#define FS_API_FS_GETCLUSTERSIZE_S FS_API_FS_GETCLUSTERSIZE_S__enum,FS_API_FS_GETCLUSTERSIZE_S_size

// FS_API_FS_GETCLUSTERSIZE_E
#define FS_API_FS_GETCLUSTERSIZE_E_size "hd"
#define FS_API_FS_GETCLUSTERSIZE_E FS_API_FS_GETCLUSTERSIZE_E__enum,FS_API_FS_GETCLUSTERSIZE_E_size

// FS_API_FS_SHUTDOWN_S
#define FS_API_FS_SHUTDOWN_S_size "h"
#define FS_API_FS_SHUTDOWN_S FS_API_FS_SHUTDOWN_S__enum,FS_API_FS_SHUTDOWN_S_size

// FS_API_FS_CLEARDISKFLAG_S
#define FS_API_FS_CLEARDISKFLAG_S_size "h"
#define FS_API_FS_CLEARDISKFLAG_S FS_API_FS_CLEARDISKFLAG_S__enum,FS_API_FS_CLEARDISKFLAG_S_size

// FS_API_FS_UNLOCKALL_S
#define FS_API_FS_UNLOCKALL_S_size "h"
#define FS_API_FS_UNLOCKALL_S FS_API_FS_UNLOCKALL_S__enum,FS_API_FS_UNLOCKALL_S_size

// FS_API_FS_GETDISKINFO_S
#define FS_API_FS_GETDISKINFO_S_size "hcd"
#define FS_API_FS_GETDISKINFO_S FS_API_FS_GETDISKINFO_S__enum,FS_API_FS_GETDISKINFO_S_size

// FS_API_FS_GETDISKINFO_E
#define FS_API_FS_GETDISKINFO_E_size "hd"
#define FS_API_FS_GETDISKINFO_E FS_API_FS_GETDISKINFO_E__enum,FS_API_FS_GETDISKINFO_E_size

// FS_API_FS_GETDISKINFO_E_DEV
#define FS_API_FS_GETDISKINFO_E_DEV_size "hdc"
#define FS_API_FS_GETDISKINFO_E_DEV FS_API_FS_GETDISKINFO_E_DEV__enum,FS_API_FS_GETDISKINFO_E_DEV_size

// FS_API_FS_OPENHINT_S
#define FS_API_FS_OPENHINT_S_size "hÇd"
#define FS_API_FS_OPENHINT_S FS_API_FS_OPENHINT_S__enum,FS_API_FS_OPENHINT_S_size

// FS_API_FS_OPENHINT_S_HINT
#define FS_API_FS_OPENHINT_S_HINT_size "hÑd"
#define FS_API_FS_OPENHINT_S_HINT FS_API_FS_OPENHINT_S_HINT__enum,FS_API_FS_OPENHINT_S_HINT_size

// FS_API_FS_OPENHINT_E
#define FS_API_FS_OPENHINT_E_size "hd"
#define FS_API_FS_OPENHINT_E FS_API_FS_OPENHINT_E__enum,FS_API_FS_OPENHINT_E_size

// FS_API_FS_FINDFIRST_S
#define FS_API_FS_FINDFIRST_S_size "hÑd"
#define FS_API_FS_FINDFIRST_S FS_API_FS_FINDFIRST_S__enum,FS_API_FS_FINDFIRST_S_size

// FS_API_FS_FINDFIRST_E
#define FS_API_FS_FINDFIRST_E_size "hd"
#define FS_API_FS_FINDFIRST_E FS_API_FS_FINDFIRST_E__enum,FS_API_FS_FINDFIRST_E_size

// FS_API_FS_FINDFIRST_E_INFO
#define FS_API_FS_FINDFIRST_E_INFO_size "hÉd"
#define FS_API_FS_FINDFIRST_E_INFO FS_API_FS_FINDFIRST_E_INFO__enum,FS_API_FS_FINDFIRST_E_INFO_size

// FS_API_FS_FINDNEXT_S
#define FS_API_FS_FINDNEXT_S_size "hÇd"
#define FS_API_FS_FINDNEXT_S FS_API_FS_FINDNEXT_S__enum,FS_API_FS_FINDNEXT_S_size

// FS_API_FS_FINDNEXT_E
#define FS_API_FS_FINDNEXT_E_size "h"
#define FS_API_FS_FINDNEXT_E FS_API_FS_FINDNEXT_E__enum,FS_API_FS_FINDNEXT_E_size

// FS_API_FS_FINDNEXT_E_INFO
#define FS_API_FS_FINDNEXT_E_INFO_size "hÇd"
#define FS_API_FS_FINDNEXT_E_INFO FS_API_FS_FINDNEXT_E_INFO__enum,FS_API_FS_FINDNEXT_E_INFO_size

// FS_API_FS_FINDCLOSE_S
#define FS_API_FS_FINDCLOSE_S_size "hd"
#define FS_API_FS_FINDCLOSE_S FS_API_FS_FINDCLOSE_S__enum,FS_API_FS_FINDCLOSE_S_size

// FS_API_FS_GETDEVSTATUS_S_DRIVE
#define FS_API_FS_GETDEVSTATUS_S_DRIVE_size "hÇc"
#define FS_API_FS_GETDEVSTATUS_S_DRIVE FS_API_FS_GETDEVSTATUS_S_DRIVE__enum,FS_API_FS_GETDEVSTATUS_S_DRIVE_size

// FS_API_FS_GETDEVSTATUS_S_TYPE
#define FS_API_FS_GETDEVSTATUS_S_TYPE_size "hdc"
#define FS_API_FS_GETDEVSTATUS_S_TYPE FS_API_FS_GETDEVSTATUS_S_TYPE__enum,FS_API_FS_GETDEVSTATUS_S_TYPE_size

// FS_API_FS_GETDEVSTATUS_E
#define FS_API_FS_GETDEVSTATUS_E_size "hd"
#define FS_API_FS_GETDEVSTATUS_E FS_API_FS_GETDEVSTATUS_E__enum,FS_API_FS_GETDEVSTATUS_E_size

// FS_API_FS_XDELETEEX_S
#define FS_API_FS_XDELETEEX_S_size "hd"
#define FS_API_FS_XDELETEEX_S FS_API_FS_XDELETEEX_S__enum,FS_API_FS_XDELETEEX_S_size

// FS_API_FS_XDELETEEX_E
#define FS_API_FS_XDELETEEX_E_size "hd"
#define FS_API_FS_XDELETEEX_E FS_API_FS_XDELETEEX_E__enum,FS_API_FS_XDELETEEX_E_size

// FS_API_FS_GETDRIVE_S
#define FS_API_FS_GETDRIVE_S_size "hÉd"
#define FS_API_FS_GETDRIVE_S FS_API_FS_GETDRIVE_S__enum,FS_API_FS_GETDRIVE_S_size

// FS_API_FS_GETDRIVE_E
#define FS_API_FS_GETDRIVE_E_size "hc"
#define FS_API_FS_GETDRIVE_E FS_API_FS_GETDRIVE_E__enum,FS_API_FS_GETDRIVE_E_size

// FS_API_FS_GETFILEPOSITION_S
#define FS_API_FS_GETFILEPOSITION_S_size "hd"
#define FS_API_FS_GETFILEPOSITION_S FS_API_FS_GETFILEPOSITION_S__enum,FS_API_FS_GETFILEPOSITION_S_size

// FS_API_FS_GETFILEPOSITION_E
#define FS_API_FS_GETFILEPOSITION_E_size "hd"
#define FS_API_FS_GETFILEPOSITION_E FS_API_FS_GETFILEPOSITION_E__enum,FS_API_FS_GETFILEPOSITION_E_size

// FS_API_FS_GETATTRIBUTES_S
#define FS_API_FS_GETATTRIBUTES_S_size "h"
#define FS_API_FS_GETATTRIBUTES_S FS_API_FS_GETATTRIBUTES_S__enum,FS_API_FS_GETATTRIBUTES_S_size

// FS_API_FS_GETATTRIBUTES_E
#define FS_API_FS_GETATTRIBUTES_E_size "hd"
#define FS_API_FS_GETATTRIBUTES_E FS_API_FS_GETATTRIBUTES_E__enum,FS_API_FS_GETATTRIBUTES_E_size

// FS_API_FS_GETFILEINFO_S
#define FS_API_FS_GETFILEINFO_S_size "hÇd"
#define FS_API_FS_GETFILEINFO_S FS_API_FS_GETFILEINFO_S__enum,FS_API_FS_GETFILEINFO_S_size

// FS_API_FS_GETFILEINFO_E
#define FS_API_FS_GETFILEINFO_E_size "h"
#define FS_API_FS_GETFILEINFO_E FS_API_FS_GETFILEINFO_E__enum,FS_API_FS_GETFILEINFO_E_size

// FS_API_FS_GETDEVTYPE_S
#define FS_API_FS_GETDEVTYPE_S_size "h"
#define FS_API_FS_GETDEVTYPE_S FS_API_FS_GETDEVTYPE_S__enum,FS_API_FS_GETDEVTYPE_S_size

// FS_API_FS_GETDEVTYPE_E
#define FS_API_FS_GETDEVTYPE_E_size "hd"
#define FS_API_FS_GETDEVTYPE_E FS_API_FS_GETDEVTYPE_E__enum,FS_API_FS_GETDEVTYPE_E_size

// FS_API_FS_SETSEEKHINT_S
#define FS_API_FS_SETSEEKHINT_S_size "hÇd"
#define FS_API_FS_SETSEEKHINT_S FS_API_FS_SETSEEKHINT_S__enum,FS_API_FS_SETSEEKHINT_S_size

// FS_API_FS_SETSEEKHINT_E
#define FS_API_FS_SETSEEKHINT_E_size "hd"
#define FS_API_FS_SETSEEKHINT_E FS_API_FS_SETSEEKHINT_E__enum,FS_API_FS_SETSEEKHINT_E_size

// FS_API_FS_SETSEEKHINTEX_S
#define FS_API_FS_SETSEEKHINTEX_S_size "hÑd"
#define FS_API_FS_SETSEEKHINTEX_S FS_API_FS_SETSEEKHINTEX_S__enum,FS_API_FS_SETSEEKHINTEX_S_size

// FS_API_FS_SETSEEKHINTEX_E
#define FS_API_FS_SETSEEKHINTEX_E_size "hd"
#define FS_API_FS_SETSEEKHINTEX_E FS_API_FS_SETSEEKHINTEX_E__enum,FS_API_FS_SETSEEKHINTEX_E_size

// FS_API_FS_ENABLESMARTSEEK_S
#define FS_API_FS_ENABLESMARTSEEK_S_size "hd"
#define FS_API_FS_ENABLESMARTSEEK_S FS_API_FS_ENABLESMARTSEEK_S__enum,FS_API_FS_ENABLESMARTSEEK_S_size

// FS_API_FS_TRUNCATE_S
#define FS_API_FS_TRUNCATE_S_size "hd"
#define FS_API_FS_TRUNCATE_S FS_API_FS_TRUNCATE_S__enum,FS_API_FS_TRUNCATE_S_size

// FS_API_FS_TRUNCATE_E
#define FS_API_FS_TRUNCATE_E_size "h"
#define FS_API_FS_TRUNCATE_E FS_API_FS_TRUNCATE_E__enum,FS_API_FS_TRUNCATE_E_size

// FS_API_FS_RENAME_S_OLDNAME
#define FS_API_FS_RENAME_S_OLDNAME_size "h"
#define FS_API_FS_RENAME_S_OLDNAME FS_API_FS_RENAME_S_OLDNAME__enum,FS_API_FS_RENAME_S_OLDNAME_size

// FS_API_FS_RENAME_S_NEWNAME
#define FS_API_FS_RENAME_S_NEWNAME_size "h"
#define FS_API_FS_RENAME_S_NEWNAME FS_API_FS_RENAME_S_NEWNAME__enum,FS_API_FS_RENAME_S_NEWNAME_size

// FS_API_FS_RENAME_E
#define FS_API_FS_RENAME_E_size "hd"
#define FS_API_FS_RENAME_E FS_API_FS_RENAME_E__enum,FS_API_FS_RENAME_E_size

// FS_API_FS_IOCTRL_S
#define FS_API_FS_IOCTRL_S_size "hcd"
#define FS_API_FS_IOCTRL_S FS_API_FS_IOCTRL_S__enum,FS_API_FS_IOCTRL_S_size

// FS_API_FS_IOCTRL_E
#define FS_API_FS_IOCTRL_E_size "hd"
#define FS_API_FS_IOCTRL_E FS_API_FS_IOCTRL_E__enum,FS_API_FS_IOCTRL_E_size

// FS_API_FS_COMPACTDIR_S
#define FS_API_FS_COMPACTDIR_S_size "hd"
#define FS_API_FS_COMPACTDIR_S FS_API_FS_COMPACTDIR_S__enum,FS_API_FS_COMPACTDIR_S_size

// FS_API_FS_COMPACTDIR_E
#define FS_API_FS_COMPACTDIR_E_size "hd"
#define FS_API_FS_COMPACTDIR_E FS_API_FS_COMPACTDIR_E__enum,FS_API_FS_COMPACTDIR_E_size

// FS_API_FS_CLOSEALL_S
#define FS_API_FS_CLOSEALL_S_size "h"
#define FS_API_FS_CLOSEALL_S FS_API_FS_CLOSEALL_S__enum,FS_API_FS_CLOSEALL_S_size

// FS_API_FS_CLOSEALL_E
#define FS_API_FS_CLOSEALL_E_size "h"
#define FS_API_FS_CLOSEALL_E FS_API_FS_CLOSEALL_E__enum,FS_API_FS_CLOSEALL_E_size

// FS_API_FS_RELEASEFH_S_TASKID
#define FS_API_FS_RELEASEFH_S_TASKID_size "hd"
#define FS_API_FS_RELEASEFH_S_TASKID FS_API_FS_RELEASEFH_S_TASKID__enum,FS_API_FS_RELEASEFH_S_TASKID_size

// FS_API_FS_RELEASEFH_S_ALLTASK
#define FS_API_FS_RELEASEFH_S_ALLTASK_size "h"
#define FS_API_FS_RELEASEFH_S_ALLTASK FS_API_FS_RELEASEFH_S_ALLTASK__enum,FS_API_FS_RELEASEFH_S_ALLTASK_size

// FS_API_FS_RELEASEFH_E
#define FS_API_FS_RELEASEFH_E_size "h"
#define FS_API_FS_RELEASEFH_E FS_API_FS_RELEASEFH_E__enum,FS_API_FS_RELEASEFH_E_size

// FS_API_FS_ABORT_S
#define FS_API_FS_ABORT_S_size "hd"
#define FS_API_FS_ABORT_S FS_API_FS_ABORT_S__enum,FS_API_FS_ABORT_S_size

// FS_API_FS_ABORT_E
#define FS_API_FS_ABORT_E_size "h"
#define FS_API_FS_ABORT_E FS_API_FS_ABORT_E__enum,FS_API_FS_ABORT_E_size

// FS_API_FS_PARSEFH_S
#define FS_API_FS_PARSEFH_S_size "hd"
#define FS_API_FS_PARSEFH_S FS_API_FS_PARSEFH_S__enum,FS_API_FS_PARSEFH_S_size

// FS_API_FS_PARSEFH_E
#define FS_API_FS_PARSEFH_E_size "hd"
#define FS_API_FS_PARSEFH_E FS_API_FS_PARSEFH_E__enum,FS_API_FS_PARSEFH_E_size

// FS_API_FS_SETFILETIME_S
#define FS_API_FS_SETFILETIME_S_size "hÇd"
#define FS_API_FS_SETFILETIME_S FS_API_FS_SETFILETIME_S__enum,FS_API_FS_SETFILETIME_S_size

// FS_API_FS_SETFILETIME_E
#define FS_API_FS_SETFILETIME_E_size "hd"
#define FS_API_FS_SETFILETIME_E FS_API_FS_SETFILETIME_E__enum,FS_API_FS_SETFILETIME_E_size

// FS_API_FS_PSEUDOMERGE_S_FILE1
#define FS_API_FS_PSEUDOMERGE_S_FILE1_size "h"
#define FS_API_FS_PSEUDOMERGE_S_FILE1 FS_API_FS_PSEUDOMERGE_S_FILE1__enum,FS_API_FS_PSEUDOMERGE_S_FILE1_size

// FS_API_FS_PSEUDOMERGE_S_FILE2
#define FS_API_FS_PSEUDOMERGE_S_FILE2_size "h"
#define FS_API_FS_PSEUDOMERGE_S_FILE2 FS_API_FS_PSEUDOMERGE_S_FILE2__enum,FS_API_FS_PSEUDOMERGE_S_FILE2_size

// FS_API_FS_PSEUDOMERGE_E
#define FS_API_FS_PSEUDOMERGE_E_size "hd"
#define FS_API_FS_PSEUDOMERGE_E FS_API_FS_PSEUDOMERGE_E__enum,FS_API_FS_PSEUDOMERGE_E_size

// FS_API_FS_CHECKFILE_S
#define FS_API_FS_CHECKFILE_S_size "h"
#define FS_API_FS_CHECKFILE_S FS_API_FS_CHECKFILE_S__enum,FS_API_FS_CHECKFILE_S_size

// FS_API_FS_CHECKFILE_E
#define FS_API_FS_CHECKFILE_E_size "hd"
#define FS_API_FS_CHECKFILE_E FS_API_FS_CHECKFILE_E__enum,FS_API_FS_CHECKFILE_E_size

// FS_API_FS_GETCURRENTDIR_S
#define FS_API_FS_GETCURRENTDIR_S_size "hd"
#define FS_API_FS_GETCURRENTDIR_S FS_API_FS_GETCURRENTDIR_S__enum,FS_API_FS_GETCURRENTDIR_S_size

// FS_API_FS_GETCURRENTDIR_E
#define FS_API_FS_GETCURRENTDIR_E_size "hd"
#define FS_API_FS_GETCURRENTDIR_E FS_API_FS_GETCURRENTDIR_E__enum,FS_API_FS_GETCURRENTDIR_E_size

// FS_API_FS_GETCURRENTDIRBYDRIVE_S
#define FS_API_FS_GETCURRENTDIRBYDRIVE_S_size "hcd"
#define FS_API_FS_GETCURRENTDIRBYDRIVE_S FS_API_FS_GETCURRENTDIRBYDRIVE_S__enum,FS_API_FS_GETCURRENTDIRBYDRIVE_S_size

// FS_API_FS_GETCURRENTDIRBYDRIVE_E
#define FS_API_FS_GETCURRENTDIRBYDRIVE_E_size "hd"
#define FS_API_FS_GETCURRENTDIRBYDRIVE_E FS_API_FS_GETCURRENTDIRBYDRIVE_E__enum,FS_API_FS_GETCURRENTDIRBYDRIVE_E_size

// FS_API_FS_SETCURRENTDIR_S
#define FS_API_FS_SETCURRENTDIR_S_size "h"
#define FS_API_FS_SETCURRENTDIR_S FS_API_FS_SETCURRENTDIR_S__enum,FS_API_FS_SETCURRENTDIR_S_size

// FS_API_FS_SETCURRENTDIR_E
#define FS_API_FS_SETCURRENTDIR_E_size "hd"
#define FS_API_FS_SETCURRENTDIR_E FS_API_FS_SETCURRENTDIR_E__enum,FS_API_FS_SETCURRENTDIR_E_size

// FS_API_FS_EXTEND_S
#define FS_API_FS_EXTEND_S_size "hÇd"
#define FS_API_FS_EXTEND_S FS_API_FS_EXTEND_S__enum,FS_API_FS_EXTEND_S_size

// FS_API_FS_EXTEND_E
#define FS_API_FS_EXTEND_E_size "hd"
#define FS_API_FS_EXTEND_E FS_API_FS_EXTEND_E__enum,FS_API_FS_EXTEND_E_size

// FS_API_FS_MAKEFILENAME_S
#define FS_API_FS_MAKEFILENAME_S_size "hÉd"
#define FS_API_FS_MAKEFILENAME_S FS_API_FS_MAKEFILENAME_S__enum,FS_API_FS_MAKEFILENAME_S_size

// FS_API_FS_MAKEFILENAME_E
#define FS_API_FS_MAKEFILENAME_E_size "hd"
#define FS_API_FS_MAKEFILENAME_E FS_API_FS_MAKEFILENAME_E__enum,FS_API_FS_MAKEFILENAME_E_size

// FS_API_FS_FINDFIRSTN_S
#define FS_API_FS_FINDFIRSTN_S_size "hÖd"
#define FS_API_FS_FINDFIRSTN_S FS_API_FS_FINDFIRSTN_S__enum,FS_API_FS_FINDFIRSTN_S_size

// FS_API_FS_FINDFIRSTN_E
#define FS_API_FS_FINDFIRSTN_E_size "hd"
#define FS_API_FS_FINDFIRSTN_E FS_API_FS_FINDFIRSTN_E__enum,FS_API_FS_FINDFIRSTN_E_size

// FS_API_FS_FINDFIRSTN_E_HINT
#define FS_API_FS_FINDFIRSTN_E_HINT_size "hÉd"
#define FS_API_FS_FINDFIRSTN_E_HINT FS_API_FS_FINDFIRSTN_E_HINT__enum,FS_API_FS_FINDFIRSTN_E_HINT_size

// FS_API_FS_FINDNEXTN_S
#define FS_API_FS_FINDNEXTN_S_size "hÑd"
#define FS_API_FS_FINDNEXTN_S FS_API_FS_FINDNEXTN_S__enum,FS_API_FS_FINDNEXTN_S_size

// FS_API_FS_FINDNEXTN_E
#define FS_API_FS_FINDNEXTN_E_size "hd"
#define FS_API_FS_FINDNEXTN_E FS_API_FS_FINDNEXTN_E__enum,FS_API_FS_FINDNEXTN_E_size

// FS_API_FS_FINDNEXTN_E_HINT
#define FS_API_FS_FINDNEXTN_E_HINT_size "hÉd"
#define FS_API_FS_FINDNEXTN_E_HINT FS_API_FS_FINDNEXTN_E_HINT__enum,FS_API_FS_FINDNEXTN_E_HINT_size

// FS_API_FS_XFINDRESET_S
#define FS_API_FS_XFINDRESET_S_size "hÇd"
#define FS_API_FS_XFINDRESET_S FS_API_FS_XFINDRESET_S__enum,FS_API_FS_XFINDRESET_S_size

// FS_API_FS_XFINDRESET_E
#define FS_API_FS_XFINDRESET_E_size "hd"
#define FS_API_FS_XFINDRESET_E FS_API_FS_XFINDRESET_E__enum,FS_API_FS_XFINDRESET_E_size

// FS_API_FS_XFINDSTART_S
#define FS_API_FS_XFINDSTART_S_size "hÉd"
#define FS_API_FS_XFINDSTART_S FS_API_FS_XFINDSTART_S__enum,FS_API_FS_XFINDSTART_S_size

// FS_API_FS_XFINDSTART_E_INFO
#define FS_API_FS_XFINDSTART_E_INFO_size "hd"
#define FS_API_FS_XFINDSTART_E_INFO FS_API_FS_XFINDSTART_E_INFO__enum,FS_API_FS_XFINDSTART_E_INFO_size

// FS_API_FS_XFINDSTART_E
#define FS_API_FS_XFINDSTART_E_size "h"
#define FS_API_FS_XFINDSTART_E FS_API_FS_XFINDSTART_E__enum,FS_API_FS_XFINDSTART_E_size

// FS_API_FS_XFINDCLOSE_S
#define FS_API_FS_XFINDCLOSE_S_size "hd"
#define FS_API_FS_XFINDCLOSE_S FS_API_FS_XFINDCLOSE_S__enum,FS_API_FS_XFINDCLOSE_S_size

// FS_API_FS_XFINDCLOSE_E
#define FS_API_FS_XFINDCLOSE_E_size "h"
#define FS_API_FS_XFINDCLOSE_E FS_API_FS_XFINDCLOSE_E__enum,FS_API_FS_XFINDCLOSE_E_size

// FS_API_FS_GETPARTITIONINFO_S
#define FS_API_FS_GETPARTITIONINFO_S_size "hcd"
#define FS_API_FS_GETPARTITIONINFO_S FS_API_FS_GETPARTITIONINFO_S__enum,FS_API_FS_GETPARTITIONINFO_S_size

// FS_API_FS_GETPARTITIONINFO_E
#define FS_API_FS_GETPARTITIONINFO_E_size "hd"
#define FS_API_FS_GETPARTITIONINFO_E FS_API_FS_GETPARTITIONINFO_E__enum,FS_API_FS_GETPARTITIONINFO_E_size

// FS_API_FS_COMMITALL_S
#define FS_API_FS_COMMITALL_S_size "hc"
#define FS_API_FS_COMMITALL_S FS_API_FS_COMMITALL_S__enum,FS_API_FS_COMMITALL_S_size

// FS_API_FS_COMMITALL_E
#define FS_API_FS_COMMITALL_E_size "hd"
#define FS_API_FS_COMMITALL_E FS_API_FS_COMMITALL_E__enum,FS_API_FS_COMMITALL_E_size

// FS_API_FS_MAPPINGDRIVE_S
#define FS_API_FS_MAPPINGDRIVE_S_size "hÇc"
#define FS_API_FS_MAPPINGDRIVE_S FS_API_FS_MAPPINGDRIVE_S__enum,FS_API_FS_MAPPINGDRIVE_S_size

// FS_API_FS_MAPPINGDRIVE_E
#define FS_API_FS_MAPPINGDRIVE_E_size "hd"
#define FS_API_FS_MAPPINGDRIVE_E FS_API_FS_MAPPINGDRIVE_E__enum,FS_API_FS_MAPPINGDRIVE_E_size

// FS_API_FS_GENERALFORMAT_S
#define FS_API_FS_GENERALFORMAT_S_size "hdcd"
#define FS_API_FS_GENERALFORMAT_S FS_API_FS_GENERALFORMAT_S__enum,FS_API_FS_GENERALFORMAT_S_size

// FS_API_FS_GENERALFORMAT_E
#define FS_API_FS_GENERALFORMAT_E_size "hd"
#define FS_API_FS_GENERALFORMAT_E FS_API_FS_GENERALFORMAT_E__enum,FS_API_FS_GENERALFORMAT_E_size

// FS_API_FS_QMGETFREE_S
#define FS_API_FS_QMGETFREE_S_size "h"
#define FS_API_FS_QMGETFREE_S FS_API_FS_QMGETFREE_S__enum,FS_API_FS_QMGETFREE_S_size

// FS_API_FS_QMGETFREE_E
#define FS_API_FS_QMGETFREE_E_size "hd"
#define FS_API_FS_QMGETFREE_E FS_API_FS_QMGETFREE_E__enum,FS_API_FS_QMGETFREE_E_size

// FS_API_FS_CHECKDISKFLAG_S
#define FS_API_FS_CHECKDISKFLAG_S_size "h"
#define FS_API_FS_CHECKDISKFLAG_S FS_API_FS_CHECKDISKFLAG_S__enum,FS_API_FS_CHECKDISKFLAG_S_size

// FS_API_FS_CHECKDISKFLAG_E
#define FS_API_FS_CHECKDISKFLAG_E_size "h"
#define FS_API_FS_CHECKDISKFLAG_E FS_API_FS_CHECKDISKFLAG_E__enum,FS_API_FS_CHECKDISKFLAG_E_size

// FS_API_FS_LOCKFAT_S
#define FS_API_FS_LOCKFAT_S_size "h"
#define FS_API_FS_LOCKFAT_S FS_API_FS_LOCKFAT_S__enum,FS_API_FS_LOCKFAT_S_size

// FS_API_FS_LOCKFAT_E
#define FS_API_FS_LOCKFAT_E_size "hd"
#define FS_API_FS_LOCKFAT_E FS_API_FS_LOCKFAT_E__enum,FS_API_FS_LOCKFAT_E_size

// FS_API_FS_TESTMSDC_S
#define FS_API_FS_TESTMSDC_S_size "hd"
#define FS_API_FS_TESTMSDC_S FS_API_FS_TESTMSDC_S__enum,FS_API_FS_TESTMSDC_S_size

// FS_API_FS_TESTMSDC_S_DRIVELIST
#define FS_API_FS_TESTMSDC_S_DRIVELIST_size "hÉd"
#define FS_API_FS_TESTMSDC_S_DRIVELIST FS_API_FS_TESTMSDC_S_DRIVELIST__enum,FS_API_FS_TESTMSDC_S_DRIVELIST_size

// FS_API_FS_TESTMSDC_E
#define FS_API_FS_TESTMSDC_E_size "hd"
#define FS_API_FS_TESTMSDC_E FS_API_FS_TESTMSDC_E__enum,FS_API_FS_TESTMSDC_E_size

// FS_API_FS_TESTMSDC_E_DRIVELIST
#define FS_API_FS_TESTMSDC_E_DRIVELIST_size "hÇd"
#define FS_API_FS_TESTMSDC_E_DRIVELIST FS_API_FS_TESTMSDC_E_DRIVELIST__enum,FS_API_FS_TESTMSDC_E_DRIVELIST_size

// FS_API_FS_CLOSEMSDC_S
#define FS_API_FS_CLOSEMSDC_S_size "hcd"
#define FS_API_FS_CLOSEMSDC_S FS_API_FS_CLOSEMSDC_S__enum,FS_API_FS_CLOSEMSDC_S_size

// FS_API_FS_CLOSEMSDC_E
#define FS_API_FS_CLOSEMSDC_E_size "hd"
#define FS_API_FS_CLOSEMSDC_E FS_API_FS_CLOSEMSDC_E__enum,FS_API_FS_CLOSEMSDC_E_size

// FS_API_FS_SWITCHDRIVEMODE_S
#define FS_API_FS_SWITCHDRIVEMODE_S_size "hcd"
#define FS_API_FS_SWITCHDRIVEMODE_S FS_API_FS_SWITCHDRIVEMODE_S__enum,FS_API_FS_SWITCHDRIVEMODE_S_size

// FS_API_FS_SWITCHDRIVEMODE_E
#define FS_API_FS_SWITCHDRIVEMODE_E_size "hd"
#define FS_API_FS_SWITCHDRIVEMODE_E FS_API_FS_SWITCHDRIVEMODE_E__enum,FS_API_FS_SWITCHDRIVEMODE_E_size

// FS_API_FS_GENVIRTUALFILENAME_S
#define FS_API_FS_GENVIRTUALFILENAME_S_size "hÑd"
#define FS_API_FS_GENVIRTUALFILENAME_S FS_API_FS_GENVIRTUALFILENAME_S__enum,FS_API_FS_GENVIRTUALFILENAME_S_size

// FS_API_FS_GENVIRTUALFILENAME_E
#define FS_API_FS_GENVIRTUALFILENAME_E_size "hd"
#define FS_API_FS_GENVIRTUALFILENAME_E FS_API_FS_GENVIRTUALFILENAME_E__enum,FS_API_FS_GENVIRTUALFILENAME_E_size

// FS_API_FS_CONFIGEXTDEVICE_S
#define FS_API_FS_CONFIGEXTDEVICE_S_size "hÉd"
#define FS_API_FS_CONFIGEXTDEVICE_S FS_API_FS_CONFIGEXTDEVICE_S__enum,FS_API_FS_CONFIGEXTDEVICE_S_size

// FS_API_FS_CONFIGEXTDEVICE_E
#define FS_API_FS_CONFIGEXTDEVICE_E_size "hd"
#define FS_API_FS_CONFIGEXTDEVICE_E FS_API_FS_CONFIGEXTDEVICE_E__enum,FS_API_FS_CONFIGEXTDEVICE_E_size

// FS_API_FS_CHECKDRIVE_S
#define FS_API_FS_CHECKDRIVE_S_size "hcÇd"
#define FS_API_FS_CHECKDRIVE_S FS_API_FS_CHECKDRIVE_S__enum,FS_API_FS_CHECKDRIVE_S_size

// FS_API_FS_CHECKDRIVE_E
#define FS_API_FS_CHECKDRIVE_E_size "hd"
#define FS_API_FS_CHECKDRIVE_E FS_API_FS_CHECKDRIVE_E__enum,FS_API_FS_CHECKDRIVE_E_size

// FS_API_FS_SETDIRCACHE_S
#define FS_API_FS_SETDIRCACHE_S_size "hÇd"
#define FS_API_FS_SETDIRCACHE_S FS_API_FS_SETDIRCACHE_S__enum,FS_API_FS_SETDIRCACHE_S_size

// FS_API_FS_SETDIRCACHE_E
#define FS_API_FS_SETDIRCACHE_E_size "h"
#define FS_API_FS_SETDIRCACHE_E FS_API_FS_SETDIRCACHE_E__enum,FS_API_FS_SETDIRCACHE_E_size

// FS_API_FS_GETDIRCACHE_S
#define FS_API_FS_GETDIRCACHE_S_size "hd"
#define FS_API_FS_GETDIRCACHE_S FS_API_FS_GETDIRCACHE_S__enum,FS_API_FS_GETDIRCACHE_S_size

// FS_API_FS_GETDIRCACHE_E
#define FS_API_FS_GETDIRCACHE_E_size "hÇd"
#define FS_API_FS_GETDIRCACHE_E FS_API_FS_GETDIRCACHE_E__enum,FS_API_FS_GETDIRCACHE_E_size

// FS_API_FS_EXPIREDIRCACHE_S
#define FS_API_FS_EXPIREDIRCACHE_S_size "hd"
#define FS_API_FS_EXPIREDIRCACHE_S FS_API_FS_EXPIREDIRCACHE_S__enum,FS_API_FS_EXPIREDIRCACHE_S_size

// FS_API_FS_EXPIREDIRCACHE_E
#define FS_API_FS_EXPIREDIRCACHE_E_size "h"
#define FS_API_FS_EXPIREDIRCACHE_E FS_API_FS_EXPIREDIRCACHE_E__enum,FS_API_FS_EXPIREDIRCACHE_E_size

// FS_API_FS_GETFOLDERSIZE_S
#define FS_API_FS_GETFOLDERSIZE_S_size "hÉd"
#define FS_API_FS_GETFOLDERSIZE_S FS_API_FS_GETFOLDERSIZE_S__enum,FS_API_FS_GETFOLDERSIZE_S_size

// FS_API_FS_GETFOLDERSIZE_E
#define FS_API_FS_GETFOLDERSIZE_E_size "hd"
#define FS_API_FS_GETFOLDERSIZE_E FS_API_FS_GETFOLDERSIZE_E__enum,FS_API_FS_GETFOLDERSIZE_E_size

// FS_API_FS_MOVE_S_SRCFILE
#define FS_API_FS_MOVE_S_SRCFILE_size "hd"
#define FS_API_FS_MOVE_S_SRCFILE FS_API_FS_MOVE_S_SRCFILE__enum,FS_API_FS_MOVE_S_SRCFILE_size

// FS_API_FS_MOVE_S_DSTFILE
#define FS_API_FS_MOVE_S_DSTFILE_size "h"
#define FS_API_FS_MOVE_S_DSTFILE FS_API_FS_MOVE_S_DSTFILE__enum,FS_API_FS_MOVE_S_DSTFILE_size

// FS_API_FS_MOVE_E
#define FS_API_FS_MOVE_E_size "hd"
#define FS_API_FS_MOVE_E FS_API_FS_MOVE_E__enum,FS_API_FS_MOVE_E_size

// FS_API_FS_GETFIRSTCLUSTER_S
#define FS_API_FS_GETFIRSTCLUSTER_S_size "hd"
#define FS_API_FS_GETFIRSTCLUSTER_S FS_API_FS_GETFIRSTCLUSTER_S__enum,FS_API_FS_GETFIRSTCLUSTER_S_size

// FS_API_FS_GETFIRSTCLUSTER_E
#define FS_API_FS_GETFIRSTCLUSTER_E_size "hÇd"
#define FS_API_FS_GETFIRSTCLUSTER_E FS_API_FS_GETFIRSTCLUSTER_E__enum,FS_API_FS_GETFIRSTCLUSTER_E_size

// FS_API_FS_OTPREAD_S
#define FS_API_FS_OTPREAD_S_size "hÑd"
#define FS_API_FS_OTPREAD_S FS_API_FS_OTPREAD_S__enum,FS_API_FS_OTPREAD_S_size

// FS_API_FS_OTPREAD_E
#define FS_API_FS_OTPREAD_E_size "hd"
#define FS_API_FS_OTPREAD_E FS_API_FS_OTPREAD_E__enum,FS_API_FS_OTPREAD_E_size

// FS_API_FS_OTPWRITE_S
#define FS_API_FS_OTPWRITE_S_size "hÑd"
#define FS_API_FS_OTPWRITE_S FS_API_FS_OTPWRITE_S__enum,FS_API_FS_OTPWRITE_S_size

// FS_API_FS_OTPWRITE_E
#define FS_API_FS_OTPWRITE_E_size "hd"
#define FS_API_FS_OTPWRITE_E FS_API_FS_OTPWRITE_E__enum,FS_API_FS_OTPWRITE_E_size

// FS_API_FS_OTPLOCK_S
#define FS_API_FS_OTPLOCK_S_size "hd"
#define FS_API_FS_OTPLOCK_S FS_API_FS_OTPLOCK_S__enum,FS_API_FS_OTPLOCK_S_size

// FS_API_FS_OTPLOCK_E
#define FS_API_FS_OTPLOCK_E_size "hd"
#define FS_API_FS_OTPLOCK_E FS_API_FS_OTPLOCK_E__enum,FS_API_FS_OTPLOCK_E_size

// FS_API_FS_OTPQUERYLENGTH_S
#define FS_API_FS_OTPQUERYLENGTH_S_size "hd"
#define FS_API_FS_OTPQUERYLENGTH_S FS_API_FS_OTPQUERYLENGTH_S__enum,FS_API_FS_OTPQUERYLENGTH_S_size

// FS_API_FS_OTPQUERYLENGTH_E
#define FS_API_FS_OTPQUERYLENGTH_E_size "hÇd"
#define FS_API_FS_OTPQUERYLENGTH_E FS_API_FS_OTPQUERYLENGTH_E__enum,FS_API_FS_OTPQUERYLENGTH_E_size

// FS_API_FS_SWEEPDEVICE_S
#define FS_API_FS_SWEEPDEVICE_S_size "hd"
#define FS_API_FS_SWEEPDEVICE_S FS_API_FS_SWEEPDEVICE_S__enum,FS_API_FS_SWEEPDEVICE_S_size

// FS_API_FS_SWEEPDEVICE_E_DONE
#define FS_API_FS_SWEEPDEVICE_E_DONE_size "h"
#define FS_API_FS_SWEEPDEVICE_E_DONE FS_API_FS_SWEEPDEVICE_E_DONE__enum,FS_API_FS_SWEEPDEVICE_E_DONE_size

// FS_API_FS_SWEEPDEVICE_E_RETRY
#define FS_API_FS_SWEEPDEVICE_E_RETRY_size "h"
#define FS_API_FS_SWEEPDEVICE_E_RETRY FS_API_FS_SWEEPDEVICE_E_RETRY__enum,FS_API_FS_SWEEPDEVICE_E_RETRY_size

// FS_API_FS_COUNTUSEDFH_S
#define FS_API_FS_COUNTUSEDFH_S_size "hd"
#define FS_API_FS_COUNTUSEDFH_S FS_API_FS_COUNTUSEDFH_S__enum,FS_API_FS_COUNTUSEDFH_S_size

// FS_API_FS_COUNTUSEDFH_E
#define FS_API_FS_COUNTUSEDFH_E_size "hÇd"
#define FS_API_FS_COUNTUSEDFH_E FS_API_FS_COUNTUSEDFH_E__enum,FS_API_FS_COUNTUSEDFH_E_size

// FS_API_FS_GETDEVPARTITIONS_S_DRIVE
#define FS_API_FS_GETDEVPARTITIONS_S_DRIVE_size "hc"
#define FS_API_FS_GETDEVPARTITIONS_S_DRIVE FS_API_FS_GETDEVPARTITIONS_S_DRIVE__enum,FS_API_FS_GETDEVPARTITIONS_S_DRIVE_size

// FS_API_FS_GETDEVPARTITIONS_S_TYPE
#define FS_API_FS_GETDEVPARTITIONS_S_TYPE_size "hdc"
#define FS_API_FS_GETDEVPARTITIONS_S_TYPE FS_API_FS_GETDEVPARTITIONS_S_TYPE__enum,FS_API_FS_GETDEVPARTITIONS_S_TYPE_size

// FS_API_FS_GETDEVPARTITIONS_E
#define FS_API_FS_GETDEVPARTITIONS_E_size "hd"
#define FS_API_FS_GETDEVPARTITIONS_E FS_API_FS_GETDEVPARTITIONS_E__enum,FS_API_FS_GETDEVPARTITIONS_E_size

// FS_API_FS_RECOVERDEVICE_S
#define FS_API_FS_RECOVERDEVICE_S_size "hc"
#define FS_API_FS_RECOVERDEVICE_S FS_API_FS_RECOVERDEVICE_S__enum,FS_API_FS_RECOVERDEVICE_S_size

// FS_API_FS_RECOVERDEVICE_E
#define FS_API_FS_RECOVERDEVICE_E_size "hd"
#define FS_API_FS_RECOVERDEVICE_E FS_API_FS_RECOVERDEVICE_E__enum,FS_API_FS_RECOVERDEVICE_E_size

// FS_API_FS_SETVOLUMELABEL_S
#define FS_API_FS_SETVOLUMELABEL_S_size "hc"
#define FS_API_FS_SETVOLUMELABEL_S FS_API_FS_SETVOLUMELABEL_S__enum,FS_API_FS_SETVOLUMELABEL_S_size

// FS_API_FS_SETVOLUMELABEL_E
#define FS_API_FS_SETVOLUMELABEL_E_size "hd"
#define FS_API_FS_SETVOLUMELABEL_E FS_API_FS_SETVOLUMELABEL_E__enum,FS_API_FS_SETVOLUMELABEL_E_size

// FS_API_FS_REMOVEDIR_S
#define FS_API_FS_REMOVEDIR_S_size "h"
#define FS_API_FS_REMOVEDIR_S FS_API_FS_REMOVEDIR_S__enum,FS_API_FS_REMOVEDIR_S_size

// FS_API_FS_REMOVEDIR_E
#define FS_API_FS_REMOVEDIR_E_size "hd"
#define FS_API_FS_REMOVEDIR_E FS_API_FS_REMOVEDIR_E__enum,FS_API_FS_REMOVEDIR_E_size

// FS_API_FS_SETATTRIBUTES_S
#define FS_API_FS_SETATTRIBUTES_S_size "hd"
#define FS_API_FS_SETATTRIBUTES_S FS_API_FS_SETATTRIBUTES_S__enum,FS_API_FS_SETATTRIBUTES_S_size

// FS_API_FS_SETATTRIBUTES_E
#define FS_API_FS_SETATTRIBUTES_E_size "hd"
#define FS_API_FS_SETATTRIBUTES_E FS_API_FS_SETATTRIBUTES_E__enum,FS_API_FS_SETATTRIBUTES_E_size

// FS_API_FS_COUNT_S
#define FS_API_FS_COUNT_S_size "hÉd"
#define FS_API_FS_COUNT_S FS_API_FS_COUNT_S__enum,FS_API_FS_COUNT_S_size

// FS_API_FS_COUNT_E
#define FS_API_FS_COUNT_E_size "hd"
#define FS_API_FS_COUNT_E FS_API_FS_COUNT_E__enum,FS_API_FS_COUNT_E_size

// FS_API_FS_MAKEFILEPATHBYHINT_S
#define FS_API_FS_MAKEFILEPATHBYHINT_S_size "hcÉd"
#define FS_API_FS_MAKEFILEPATHBYHINT_S FS_API_FS_MAKEFILEPATHBYHINT_S__enum,FS_API_FS_MAKEFILEPATHBYHINT_S_size

// FS_API_FS_MAKEFILEPATHBYHINT_E
#define FS_API_FS_MAKEFILEPATHBYHINT_E_size "hd"
#define FS_API_FS_MAKEFILEPATHBYHINT_E FS_API_FS_MAKEFILEPATHBYHINT_E__enum,FS_API_FS_MAKEFILEPATHBYHINT_E_size

// FS_API_FS_OPENFILEPATHBYHINT_S
#define FS_API_FS_OPENFILEPATHBYHINT_S_size "hdcÉd"
#define FS_API_FS_OPENFILEPATHBYHINT_S FS_API_FS_OPENFILEPATHBYHINT_S__enum,FS_API_FS_OPENFILEPATHBYHINT_S_size

// FS_API_FS_OPENFILEPATHBYHINT_E
#define FS_API_FS_OPENFILEPATHBYHINT_E_size "hd"
#define FS_API_FS_OPENFILEPATHBYHINT_E FS_API_FS_OPENFILEPATHBYHINT_E__enum,FS_API_FS_OPENFILEPATHBYHINT_E_size

// FS_API_FS_DELETEBYHINT_S
#define FS_API_FS_DELETEBYHINT_S_size "hcÇd"
#define FS_API_FS_DELETEBYHINT_S FS_API_FS_DELETEBYHINT_S__enum,FS_API_FS_DELETEBYHINT_S_size

// FS_API_FS_DELETEBYHINT_E
#define FS_API_FS_DELETEBYHINT_E_size "hd"
#define FS_API_FS_DELETEBYHINT_E FS_API_FS_DELETEBYHINT_E__enum,FS_API_FS_DELETEBYHINT_E_size

// FS_API_FS_GETATTRIBUTESBYHINT_S
#define FS_API_FS_GETATTRIBUTESBYHINT_S_size "hcÇd"
#define FS_API_FS_GETATTRIBUTESBYHINT_S FS_API_FS_GETATTRIBUTESBYHINT_S__enum,FS_API_FS_GETATTRIBUTESBYHINT_S_size

// FS_API_FS_GETATTRIBUTESBYHINT_E
#define FS_API_FS_GETATTRIBUTESBYHINT_E_size "hd"
#define FS_API_FS_GETATTRIBUTESBYHINT_E FS_API_FS_GETATTRIBUTESBYHINT_E__enum,FS_API_FS_GETATTRIBUTESBYHINT_E_size

// FS_API_FS_SETATTRIBUTESBYHINT_S
#define FS_API_FS_SETATTRIBUTESBYHINT_S_size "hcÉd"
#define FS_API_FS_SETATTRIBUTESBYHINT_S FS_API_FS_SETATTRIBUTESBYHINT_S__enum,FS_API_FS_SETATTRIBUTESBYHINT_S_size

// FS_API_FS_SETATTRIBUTESBYHINT_E
#define FS_API_FS_SETATTRIBUTESBYHINT_E_size "hd"
#define FS_API_FS_SETATTRIBUTESBYHINT_E FS_API_FS_SETATTRIBUTESBYHINT_E__enum,FS_API_FS_SETATTRIBUTESBYHINT_E_size

// FS_API_FS_HINTGETPARENT_S
#define FS_API_FS_HINTGETPARENT_S_size "hcÇd"
#define FS_API_FS_HINTGETPARENT_S FS_API_FS_HINTGETPARENT_S__enum,FS_API_FS_HINTGETPARENT_S_size

// FS_API_FS_HINTGETPARENT_E
#define FS_API_FS_HINTGETPARENT_E_size "hÉd"
#define FS_API_FS_HINTGETPARENT_E FS_API_FS_HINTGETPARENT_E__enum,FS_API_FS_HINTGETPARENT_E_size

// FS_API_FS_DUMPFHTABLE_S
#define FS_API_FS_DUMPFHTABLE_S_size "h"
#define FS_API_FS_DUMPFHTABLE_S FS_API_FS_DUMPFHTABLE_S__enum,FS_API_FS_DUMPFHTABLE_S_size

// FS_API_FS_DUMPFHTABLE_E
#define FS_API_FS_DUMPFHTABLE_E_size "h"
#define FS_API_FS_DUMPFHTABLE_E FS_API_FS_DUMPFHTABLE_E__enum,FS_API_FS_DUMPFHTABLE_E_size

// FS_API_FS_DIRCTRL_E
#define FS_API_FS_DIRCTRL_E_size "hdcd"
#define FS_API_FS_DIRCTRL_E FS_API_FS_DIRCTRL_E__enum,FS_API_FS_DIRCTRL_E_size

// FS_API_FS_CHECKFILENAME_E
#define FS_API_FS_CHECKFILENAME_E_size "h"
#define FS_API_FS_CHECKFILENAME_E FS_API_FS_CHECKFILENAME_E__enum,FS_API_FS_CHECKFILENAME_E_size

// FS_API_FS_CHECKVOLUMELABEL_E
#define FS_API_FS_CHECKVOLUMELABEL_E_size "h"
#define FS_API_FS_CHECKVOLUMELABEL_E FS_API_FS_CHECKVOLUMELABEL_E__enum,FS_API_FS_CHECKVOLUMELABEL_E_size

// FS_API_FS_ASYNC_OPEN_S
#define FS_API_FS_ASYNC_OPEN_S_size "hcd"
#define FS_API_FS_ASYNC_OPEN_S FS_API_FS_ASYNC_OPEN_S__enum,FS_API_FS_ASYNC_OPEN_S_size

// FS_API_FS_ASYNC_OPEN_E
#define FS_API_FS_ASYNC_OPEN_E_size "hd"
#define FS_API_FS_ASYNC_OPEN_E FS_API_FS_ASYNC_OPEN_E__enum,FS_API_FS_ASYNC_OPEN_E_size

// FS_API_FS_ASYNC_READ_S
#define FS_API_FS_ASYNC_READ_S_size "hçcÉd"
#define FS_API_FS_ASYNC_READ_S FS_API_FS_ASYNC_READ_S__enum,FS_API_FS_ASYNC_READ_S_size

// FS_API_FS_ASYNC_READ_E
#define FS_API_FS_ASYNC_READ_E_size "hd"
#define FS_API_FS_ASYNC_READ_E FS_API_FS_ASYNC_READ_E__enum,FS_API_FS_ASYNC_READ_E_size

// FS_API_FS_ASYNC_WRITE_S
#define FS_API_FS_ASYNC_WRITE_S_size "hçcÉd"
#define FS_API_FS_ASYNC_WRITE_S FS_API_FS_ASYNC_WRITE_S__enum,FS_API_FS_ASYNC_WRITE_S_size

// FS_API_FS_ASYNC_WRITE_E
#define FS_API_FS_ASYNC_WRITE_E_size "hd"
#define FS_API_FS_ASYNC_WRITE_E FS_API_FS_ASYNC_WRITE_E__enum,FS_API_FS_ASYNC_WRITE_E_size

// FS_API_FS_ASYNC_SEEK_S
#define FS_API_FS_ASYNC_SEEK_S_size "hcÇdc"
#define FS_API_FS_ASYNC_SEEK_S FS_API_FS_ASYNC_SEEK_S__enum,FS_API_FS_ASYNC_SEEK_S_size

// FS_API_FS_ASYNC_SEEK_E
#define FS_API_FS_ASYNC_SEEK_E_size "hd"
#define FS_API_FS_ASYNC_SEEK_E FS_API_FS_ASYNC_SEEK_E__enum,FS_API_FS_ASYNC_SEEK_E_size

// FS_API_FS_ASYNC_DELETE_S
#define FS_API_FS_ASYNC_DELETE_S_size "hc"
#define FS_API_FS_ASYNC_DELETE_S FS_API_FS_ASYNC_DELETE_S__enum,FS_API_FS_ASYNC_DELETE_S_size

// FS_API_FS_ASYNC_DELETE_E
#define FS_API_FS_ASYNC_DELETE_E_size "hd"
#define FS_API_FS_ASYNC_DELETE_E FS_API_FS_ASYNC_DELETE_E__enum,FS_API_FS_ASYNC_DELETE_E_size

// FS_API_FS_ASYNC_FINDFIRST_S
#define FS_API_FS_ASYNC_FINDFIRST_S_size "hcÉd"
#define FS_API_FS_ASYNC_FINDFIRST_S FS_API_FS_ASYNC_FINDFIRST_S__enum,FS_API_FS_ASYNC_FINDFIRST_S_size

// FS_API_FS_ASYNC_FINDFIRST_E
#define FS_API_FS_ASYNC_FINDFIRST_E_size "hd"
#define FS_API_FS_ASYNC_FINDFIRST_E FS_API_FS_ASYNC_FINDFIRST_E__enum,FS_API_FS_ASYNC_FINDFIRST_E_size

// FS_API_FS_ASYNC_FINDFIRSTN_S
#define FS_API_FS_ASYNC_FINDFIRSTN_S_size "hcÉd"
#define FS_API_FS_ASYNC_FINDFIRSTN_S FS_API_FS_ASYNC_FINDFIRSTN_S__enum,FS_API_FS_ASYNC_FINDFIRSTN_S_size

// FS_API_FS_ASYNC_FINDFIRSTN_E
#define FS_API_FS_ASYNC_FINDFIRSTN_E_size "hd"
#define FS_API_FS_ASYNC_FINDFIRSTN_E FS_API_FS_ASYNC_FINDFIRSTN_E__enum,FS_API_FS_ASYNC_FINDFIRSTN_E_size

// FS_API_FS_ASYNC_GETFOLDERSIZE_S
#define FS_API_FS_ASYNC_GETFOLDERSIZE_S_size "hcÉd"
#define FS_API_FS_ASYNC_GETFOLDERSIZE_S FS_API_FS_ASYNC_GETFOLDERSIZE_S__enum,FS_API_FS_ASYNC_GETFOLDERSIZE_S_size

// FS_API_FS_ASYNC_GETFOLDERSIZE_E
#define FS_API_FS_ASYNC_GETFOLDERSIZE_E_size "h"
#define FS_API_FS_ASYNC_GETFOLDERSIZE_E FS_API_FS_ASYNC_GETFOLDERSIZE_E__enum,FS_API_FS_ASYNC_GETFOLDERSIZE_E_size

// FS_API_FS_ASYNC_ABORT_S
#define FS_API_FS_ASYNC_ABORT_S_size "hd"
#define FS_API_FS_ASYNC_ABORT_S FS_API_FS_ASYNC_ABORT_S__enum,FS_API_FS_ASYNC_ABORT_S_size

// FS_API_FS_ASYNC_JOB_REGISTER
#define FS_API_FS_ASYNC_JOB_REGISTER_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_REGISTER FS_API_FS_ASYNC_JOB_REGISTER__enum,FS_API_FS_ASYNC_JOB_REGISTER_size

// FS_API_FS_ASYNC_JOB_DISPATCH_START
#define FS_API_FS_ASYNC_JOB_DISPATCH_START_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_DISPATCH_START FS_API_FS_ASYNC_JOB_DISPATCH_START__enum,FS_API_FS_ASYNC_JOB_DISPATCH_START_size

// FS_API_FS_ASYNC_JOB_DISPATCH_FINISH
#define FS_API_FS_ASYNC_JOB_DISPATCH_FINISH_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_DISPATCH_FINISH FS_API_FS_ASYNC_JOB_DISPATCH_FINISH__enum,FS_API_FS_ASYNC_JOB_DISPATCH_FINISH_size

// FS_API_FS_ASYNC_JOB_DISPATCH_ABORT
#define FS_API_FS_ASYNC_JOB_DISPATCH_ABORT_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_DISPATCH_ABORT FS_API_FS_ASYNC_JOB_DISPATCH_ABORT__enum,FS_API_FS_ASYNC_JOB_DISPATCH_ABORT_size

// FS_API_FS_ASYNC_JOB_INSERT_S
#define FS_API_FS_ASYNC_JOB_INSERT_S_size "hÇd"
#define FS_API_FS_ASYNC_JOB_INSERT_S FS_API_FS_ASYNC_JOB_INSERT_S__enum,FS_API_FS_ASYNC_JOB_INSERT_S_size

// FS_API_FS_ASYNC_JOB_INSERT_E
#define FS_API_FS_ASYNC_JOB_INSERT_E_size "h"
#define FS_API_FS_ASYNC_JOB_INSERT_E FS_API_FS_ASYNC_JOB_INSERT_E__enum,FS_API_FS_ASYNC_JOB_INSERT_E_size

// FS_API_FS_ASYNC_JOB_REMOVE_S
#define FS_API_FS_ASYNC_JOB_REMOVE_S_size "hd"
#define FS_API_FS_ASYNC_JOB_REMOVE_S FS_API_FS_ASYNC_JOB_REMOVE_S__enum,FS_API_FS_ASYNC_JOB_REMOVE_S_size

// FS_API_FS_ASYNC_JOB_REMOVE_E
#define FS_API_FS_ASYNC_JOB_REMOVE_E_size "hd"
#define FS_API_FS_ASYNC_JOB_REMOVE_E FS_API_FS_ASYNC_JOB_REMOVE_E__enum,FS_API_FS_ASYNC_JOB_REMOVE_E_size

// FS_API_FS_ASYNC_JOB_GET_FIRST_S
#define FS_API_FS_ASYNC_JOB_GET_FIRST_S_size "hd"
#define FS_API_FS_ASYNC_JOB_GET_FIRST_S FS_API_FS_ASYNC_JOB_GET_FIRST_S__enum,FS_API_FS_ASYNC_JOB_GET_FIRST_S_size

// FS_API_FS_ASYNC_JOB_GET_FIRST_E
#define FS_API_FS_ASYNC_JOB_GET_FIRST_E_size "hd"
#define FS_API_FS_ASYNC_JOB_GET_FIRST_E FS_API_FS_ASYNC_JOB_GET_FIRST_E__enum,FS_API_FS_ASYNC_JOB_GET_FIRST_E_size

// FS_API_FS_ASYNC_JOB_RUNNING_JOB
#define FS_API_FS_ASYNC_JOB_RUNNING_JOB_size "hÇd"
#define FS_API_FS_ASYNC_JOB_RUNNING_JOB FS_API_FS_ASYNC_JOB_RUNNING_JOB__enum,FS_API_FS_ASYNC_JOB_RUNNING_JOB_size

// FS_API_FS_ASYNC_JOB_LIST_ENTRY
#define FS_API_FS_ASYNC_JOB_LIST_ENTRY_size "hÇd"
#define FS_API_FS_ASYNC_JOB_LIST_ENTRY FS_API_FS_ASYNC_JOB_LIST_ENTRY__enum,FS_API_FS_ASYNC_JOB_LIST_ENTRY_size

// FS_API_FS_ASYNC_JOB_RESPONSE_ILM
#define FS_API_FS_ASYNC_JOB_RESPONSE_ILM_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_RESPONSE_ILM FS_API_FS_ASYNC_JOB_RESPONSE_ILM__enum,FS_API_FS_ASYNC_JOB_RESPONSE_ILM_size

// FS_API_FS_ASYNC_JOB_RESPONSE_CBF
#define FS_API_FS_ASYNC_JOB_RESPONSE_CBF_size "hÇdÇc"
#define FS_API_FS_ASYNC_JOB_RESPONSE_CBF FS_API_FS_ASYNC_JOB_RESPONSE_CBF__enum,FS_API_FS_ASYNC_JOB_RESPONSE_CBF_size

// FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_RUNNING
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_RUNNING_size "hd"
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_RUNNING FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_RUNNING__enum,FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_RUNNING_size

// FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_EXIST
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_EXIST_size "hd"
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_EXIST FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_EXIST__enum,FS_API_FS_ASYNC_JOB_LIST_ERROR_JOBPTR_EXIST_size

// FS_API_FS_ASYNC_JOB_LIST_ERROR_ENDLESS_LINK
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_ENDLESS_LINK_size "h"
#define FS_API_FS_ASYNC_JOB_LIST_ERROR_ENDLESS_LINK FS_API_FS_ASYNC_JOB_LIST_ERROR_ENDLESS_LINK__enum,FS_API_FS_ASYNC_JOB_LIST_ERROR_ENDLESS_LINK_size

// FS_API_FS_ASYNC_JOB_ERROR_UNEXPECTED_STATE
#define FS_API_FS_ASYNC_JOB_ERROR_UNEXPECTED_STATE_size "hcÇd"
#define FS_API_FS_ASYNC_JOB_ERROR_UNEXPECTED_STATE FS_API_FS_ASYNC_JOB_ERROR_UNEXPECTED_STATE__enum,FS_API_FS_ASYNC_JOB_ERROR_UNEXPECTED_STATE_size

// FS_API_FS_ASYNC_JOB_ERROR_UNKNOW_API
#define FS_API_FS_ASYNC_JOB_ERROR_UNKNOW_API_size "hdcÇd"
#define FS_API_FS_ASYNC_JOB_ERROR_UNKNOW_API FS_API_FS_ASYNC_JOB_ERROR_UNKNOW_API__enum,FS_API_FS_ASYNC_JOB_ERROR_UNKNOW_API_size

// FS_API_FS_STARTIOLOG_S
#define FS_API_FS_STARTIOLOG_S_size "hd"
#define FS_API_FS_STARTIOLOG_S FS_API_FS_STARTIOLOG_S__enum,FS_API_FS_STARTIOLOG_S_size

// FS_API_FS_STARTIOLOG_E
#define FS_API_FS_STARTIOLOG_E_size "hd"
#define FS_API_FS_STARTIOLOG_E FS_API_FS_STARTIOLOG_E__enum,FS_API_FS_STARTIOLOG_E_size

// FS_API_FS_ENDIOLOG_S
#define FS_API_FS_ENDIOLOG_S_size "hd"
#define FS_API_FS_ENDIOLOG_S FS_API_FS_ENDIOLOG_S__enum,FS_API_FS_ENDIOLOG_S_size

// FS_API_FS_ENDIOLOG_E
#define FS_API_FS_ENDIOLOG_E_size "hd"
#define FS_API_FS_ENDIOLOG_E FS_API_FS_ENDIOLOG_E__enum,FS_API_FS_ENDIOLOG_E_size

// FS_TRC_FS_LISTOPEN_S
#define FS_TRC_FS_LISTOPEN_S_size "hÇd"
#define FS_TRC_FS_LISTOPEN_S FS_TRC_FS_LISTOPEN_S__enum,FS_TRC_FS_LISTOPEN_S_size

// FS_TRC_FS_LISTOPEN_E
#define FS_TRC_FS_LISTOPEN_E_size "hÇd"
#define FS_TRC_FS_LISTOPEN_E FS_TRC_FS_LISTOPEN_E__enum,FS_TRC_FS_LISTOPEN_E_size

// FS_TRC_FS_LISTNEXT_S
#define FS_TRC_FS_LISTNEXT_S_size "hÇd"
#define FS_TRC_FS_LISTNEXT_S FS_TRC_FS_LISTNEXT_S__enum,FS_TRC_FS_LISTNEXT_S_size

// FS_TRC_FS_LISTNEXT_E
#define FS_TRC_FS_LISTNEXT_E_size "hd"
#define FS_TRC_FS_LISTNEXT_E FS_TRC_FS_LISTNEXT_E__enum,FS_TRC_FS_LISTNEXT_E_size

// FS_TRC_FS_LISTCLOSE_S
#define FS_TRC_FS_LISTCLOSE_S_size "hd"
#define FS_TRC_FS_LISTCLOSE_S FS_TRC_FS_LISTCLOSE_S__enum,FS_TRC_FS_LISTCLOSE_S_size

// FS_TRC_FS_LISTOPEN_FILL
#define FS_TRC_FS_LISTOPEN_FILL_size "hÉd"
#define FS_TRC_FS_LISTOPEN_FILL FS_TRC_FS_LISTOPEN_FILL__enum,FS_TRC_FS_LISTOPEN_FILL_size

// FS_TRC_DIRCACHE_SET
#define FS_TRC_DIRCACHE_SET_size "hÑd"
#define FS_TRC_DIRCACHE_SET FS_TRC_DIRCACHE_SET__enum,FS_TRC_DIRCACHE_SET_size

// FS_TRC_DIRCACHE_GET
#define FS_TRC_DIRCACHE_GET_size "hÑd"
#define FS_TRC_DIRCACHE_GET FS_TRC_DIRCACHE_GET__enum,FS_TRC_DIRCACHE_GET_size

// FS_TRC_DIRCACHE_EXPIRE
#define FS_TRC_DIRCACHE_EXPIRE_size "hÑd"
#define FS_TRC_DIRCACHE_EXPIRE FS_TRC_DIRCACHE_EXPIRE__enum,FS_TRC_DIRCACHE_EXPIRE_size

// FS_TRC_RTF_OPEN_FILE_HINT
#define FS_TRC_RTF_OPEN_FILE_HINT_size "hc"
#define FS_TRC_RTF_OPEN_FILE_HINT FS_TRC_RTF_OPEN_FILE_HINT__enum,FS_TRC_RTF_OPEN_FILE_HINT_size

// FS_TRC_RTF_FIRST_S
#define FS_TRC_RTF_FIRST_S_size "hÑd"
#define FS_TRC_RTF_FIRST_S FS_TRC_RTF_FIRST_S__enum,FS_TRC_RTF_FIRST_S_size

// FS_TRC_RTF_NEXT
#define FS_TRC_RTF_NEXT_size "h"
#define FS_TRC_RTF_NEXT FS_TRC_RTF_NEXT__enum,FS_TRC_RTF_NEXT_size

// FS_TRC_RTF_NEXT_DIR
#define FS_TRC_RTF_NEXT_DIR_size "hÉd"
#define FS_TRC_RTF_NEXT_DIR FS_TRC_RTF_NEXT_DIR__enum,FS_TRC_RTF_NEXT_DIR_size

// FS_TRC_RTF_NEXT_E
#define FS_TRC_RTF_NEXT_E_size "hd"
#define FS_TRC_RTF_NEXT_E FS_TRC_RTF_NEXT_E__enum,FS_TRC_RTF_NEXT_E_size

// FS_TRC_RTF_NEXT_E_HINT
#define FS_TRC_RTF_NEXT_E_HINT_size "hÉd"
#define FS_TRC_RTF_NEXT_E_HINT FS_TRC_RTF_NEXT_E_HINT__enum,FS_TRC_RTF_NEXT_E_HINT_size

// FS_TRC_RTF_GETNAMEBYPOS
#define FS_TRC_RTF_GETNAMEBYPOS_size "hÉd"
#define FS_TRC_RTF_GETNAMEBYPOS FS_TRC_RTF_GETNAMEBYPOS__enum,FS_TRC_RTF_GETNAMEBYPOS_size

// FS_TRC_RTF_SEARCHFILE
#define FS_TRC_RTF_SEARCHFILE_size "hÇd"
#define FS_TRC_RTF_SEARCHFILE FS_TRC_RTF_SEARCHFILE__enum,FS_TRC_RTF_SEARCHFILE_size

// FS_TRC_RTF_GETBUFFER
#define FS_TRC_RTF_GETBUFFER_size "hd"
#define FS_TRC_RTF_GETBUFFER FS_TRC_RTF_GETBUFFER__enum,FS_TRC_RTF_GETBUFFER_size

// FS_TRC_RTF_GETCLUSTERVALUE
#define FS_TRC_RTF_GETCLUSTERVALUE_size "hd"
#define FS_TRC_RTF_GETCLUSTERVALUE FS_TRC_RTF_GETCLUSTERVALUE__enum,FS_TRC_RTF_GETCLUSTERVALUE_size

// FS_TRC_RTF_NEXTDIR
#define FS_TRC_RTF_NEXTDIR_size "h"
#define FS_TRC_RTF_NEXTDIR FS_TRC_RTF_NEXTDIR__enum,FS_TRC_RTF_NEXTDIR_size

// FS_TRC_RTF_GETDIR
#define FS_TRC_RTF_GETDIR_size "hd"
#define FS_TRC_RTF_GETDIR FS_TRC_RTF_GETDIR__enum,FS_TRC_RTF_GETDIR_size

// FS_TRC_RTF_INCDIR
#define FS_TRC_RTF_INCDIR_size "hÇd"
#define FS_TRC_RTF_INCDIR FS_TRC_RTF_INCDIR__enum,FS_TRC_RTF_INCDIR_size

// FS_API_FS_ERR
#define FS_API_FS_ERR_size "hdcd"
#define FS_API_FS_ERR FS_API_FS_ERR__enum,FS_API_FS_ERR_size

// FS_API_FS_ERR_FILE
#define FS_API_FS_ERR_FILE_size "hdcdåc"
#define FS_API_FS_ERR_FILE FS_API_FS_ERR_FILE__enum,FS_API_FS_ERR_FILE_size

// FS_TRC_ERR_VF_PARENT_CLOSED
#define FS_TRC_ERR_VF_PARENT_CLOSED_size "h"
#define FS_TRC_ERR_VF_PARENT_CLOSED FS_TRC_ERR_VF_PARENT_CLOSED__enum,FS_TRC_ERR_VF_PARENT_CLOSED_size

// FS_ERR_DRIVER_NOT_FOUND
#define FS_ERR_DRIVER_NOT_FOUND_size "h"
#define FS_ERR_DRIVER_NOT_FOUND FS_ERR_DRIVER_NOT_FOUND__enum,FS_ERR_DRIVER_NOT_FOUND_size

// FS_ERR_MESSAGEACK_NOT_FOUND
#define FS_ERR_MESSAGEACK_NOT_FOUND_size "h"
#define FS_ERR_MESSAGEACK_NOT_FOUND FS_ERR_MESSAGEACK_NOT_FOUND__enum,FS_ERR_MESSAGEACK_NOT_FOUND_size

// FS_ERR_FS_MOVE_DELETE_FILE_ERROR
#define FS_ERR_FS_MOVE_DELETE_FILE_ERROR_size "h"
#define FS_ERR_FS_MOVE_DELETE_FILE_ERROR FS_ERR_FS_MOVE_DELETE_FILE_ERROR__enum,FS_ERR_FS_MOVE_DELETE_FILE_ERROR_size

// FS_ERR_QMAX_OVER_DISK
#define FS_ERR_QMAX_OVER_DISK_size "hÇd"
#define FS_ERR_QMAX_OVER_DISK FS_ERR_QMAX_OVER_DISK__enum,FS_ERR_QMAX_OVER_DISK_size

// FS_ERR_QMIN_OVER_DISK
#define FS_ERR_QMIN_OVER_DISK_size "hÇd"
#define FS_ERR_QMIN_OVER_DISK FS_ERR_QMIN_OVER_DISK__enum,FS_ERR_QMIN_OVER_DISK_size

// FS_ERR_QRFS_OVER_DFS
#define FS_ERR_QRFS_OVER_DFS_size "hÇd"
#define FS_ERR_QRFS_OVER_DFS FS_ERR_QRFS_OVER_DFS__enum,FS_ERR_QRFS_OVER_DFS_size

// FS_ERR_ACCESS_DENIED
#define FS_ERR_ACCESS_DENIED_size "hÉcÇd"
#define FS_ERR_ACCESS_DENIED FS_ERR_ACCESS_DENIED__enum,FS_ERR_ACCESS_DENIED_size

// FS_ERR_NULL_PTR_1
#define FS_ERR_NULL_PTR_1_size "hcd"
#define FS_ERR_NULL_PTR_1 FS_ERR_NULL_PTR_1__enum,FS_ERR_NULL_PTR_1_size

// FS_ERR_REC_TRAV_START
#define FS_ERR_REC_TRAV_START_size "h"
#define FS_ERR_REC_TRAV_START FS_ERR_REC_TRAV_START__enum,FS_ERR_REC_TRAV_START_size

// FS_ERR_REC_TRAV_CORE
#define FS_ERR_REC_TRAV_CORE_size "h"
#define FS_ERR_REC_TRAV_CORE FS_ERR_REC_TRAV_CORE__enum,FS_ERR_REC_TRAV_CORE_size

// FS_ERR_REC_TRAV_ACTION
#define FS_ERR_REC_TRAV_ACTION_size "h"
#define FS_ERR_REC_TRAV_ACTION FS_ERR_REC_TRAV_ACTION__enum,FS_ERR_REC_TRAV_ACTION_size

// FS_ERR_MEDIA_NOT_PRESENT
#define FS_ERR_MEDIA_NOT_PRESENT_size "hc"
#define FS_ERR_MEDIA_NOT_PRESENT FS_ERR_MEDIA_NOT_PRESENT__enum,FS_ERR_MEDIA_NOT_PRESENT_size

// FS_ERR_MOUNTDEVICE_DRIVER_MOUNT_FAIL
#define FS_ERR_MOUNTDEVICE_DRIVER_MOUNT_FAIL_size "hc"
#define FS_ERR_MOUNTDEVICE_DRIVER_MOUNT_FAIL FS_ERR_MOUNTDEVICE_DRIVER_MOUNT_FAIL__enum,FS_ERR_MOUNTDEVICE_DRIVER_MOUNT_FAIL_size

// FS_ERR_MOUNTDEVICE_INVALID_SECTOR_SIZE
#define FS_ERR_MOUNTDEVICE_INVALID_SECTOR_SIZE_size "hc"
#define FS_ERR_MOUNTDEVICE_INVALID_SECTOR_SIZE FS_ERR_MOUNTDEVICE_INVALID_SECTOR_SIZE__enum,FS_ERR_MOUNTDEVICE_INVALID_SECTOR_SIZE_size

// FS_ERR_MOUNTDEVICE_MSDC_NOT_PRESENT
#define FS_ERR_MOUNTDEVICE_MSDC_NOT_PRESENT_size "h"
#define FS_ERR_MOUNTDEVICE_MSDC_NOT_PRESENT FS_ERR_MOUNTDEVICE_MSDC_NOT_PRESENT__enum,FS_ERR_MOUNTDEVICE_MSDC_NOT_PRESENT_size

// FS_ERR_READSECTORS_DEVICE_ERROR
#define FS_ERR_READSECTORS_DEVICE_ERROR_size "hÇdc"
#define FS_ERR_READSECTORS_DEVICE_ERROR FS_ERR_READSECTORS_DEVICE_ERROR__enum,FS_ERR_READSECTORS_DEVICE_ERROR_size

// FS_ERR_READSECTORS_DEV_NOT_READY
#define FS_ERR_READSECTORS_DEV_NOT_READY_size "hÉdc"
#define FS_ERR_READSECTORS_DEV_NOT_READY FS_ERR_READSECTORS_DEV_NOT_READY__enum,FS_ERR_READSECTORS_DEV_NOT_READY_size

// FS_ERR_READSECTORS_OUT_OF_RANGE
#define FS_ERR_READSECTORS_OUT_OF_RANGE_size "hÉdc"
#define FS_ERR_READSECTORS_OUT_OF_RANGE FS_ERR_READSECTORS_OUT_OF_RANGE__enum,FS_ERR_READSECTORS_OUT_OF_RANGE_size

// FS_ERR_READSECTORS_DRIVER_FAIL
#define FS_ERR_READSECTORS_DRIVER_FAIL_size "hÇdc"
#define FS_ERR_READSECTORS_DRIVER_FAIL FS_ERR_READSECTORS_DRIVER_FAIL__enum,FS_ERR_READSECTORS_DRIVER_FAIL_size

// FS_ERR_WRITESECTORS_DEVICE_ERROR
#define FS_ERR_WRITESECTORS_DEVICE_ERROR_size "hÇdc"
#define FS_ERR_WRITESECTORS_DEVICE_ERROR FS_ERR_WRITESECTORS_DEVICE_ERROR__enum,FS_ERR_WRITESECTORS_DEVICE_ERROR_size

// FS_ERR_WRITESECTORS_DEV_NOT_READY
#define FS_ERR_WRITESECTORS_DEV_NOT_READY_size "hÉdc"
#define FS_ERR_WRITESECTORS_DEV_NOT_READY FS_ERR_WRITESECTORS_DEV_NOT_READY__enum,FS_ERR_WRITESECTORS_DEV_NOT_READY_size

// FS_ERR_WRITESECTORS_OUT_OF_RANGE
#define FS_ERR_WRITESECTORS_OUT_OF_RANGE_size "hÉdc"
#define FS_ERR_WRITESECTORS_OUT_OF_RANGE FS_ERR_WRITESECTORS_OUT_OF_RANGE__enum,FS_ERR_WRITESECTORS_OUT_OF_RANGE_size

// FS_ERR_WRITESECTORS_NO_PROTECTION_MODE
#define FS_ERR_WRITESECTORS_NO_PROTECTION_MODE_size "hc"
#define FS_ERR_WRITESECTORS_NO_PROTECTION_MODE FS_ERR_WRITESECTORS_NO_PROTECTION_MODE__enum,FS_ERR_WRITESECTORS_NO_PROTECTION_MODE_size

// FS_ERR_WRITESECTORS_BAD_SECTOR
#define FS_ERR_WRITESECTORS_BAD_SECTOR_size "hÇdc"
#define FS_ERR_WRITESECTORS_BAD_SECTOR FS_ERR_WRITESECTORS_BAD_SECTOR__enum,FS_ERR_WRITESECTORS_BAD_SECTOR_size

// FS_ERR_WRITESECTORS_DRIVER_FAIL
#define FS_ERR_WRITESECTORS_DRIVER_FAIL_size "hÇdc"
#define FS_ERR_WRITESECTORS_DRIVER_FAIL FS_ERR_WRITESECTORS_DRIVER_FAIL__enum,FS_ERR_WRITESECTORS_DRIVER_FAIL_size

// FS_ERR_WRITESECTORS_SYSTEM_CRASH
#define FS_ERR_WRITESECTORS_SYSTEM_CRASH_size "hÇdc"
#define FS_ERR_WRITESECTORS_SYSTEM_CRASH FS_ERR_WRITESECTORS_SYSTEM_CRASH__enum,FS_ERR_WRITESECTORS_SYSTEM_CRASH_size

// FS_ERR_GETBUFFER_OUT_OF_BUFFERS
#define FS_ERR_GETBUFFER_OUT_OF_BUFFERS_size "hdc"
#define FS_ERR_GETBUFFER_OUT_OF_BUFFERS FS_ERR_GETBUFFER_OUT_OF_BUFFERS__enum,FS_ERR_GETBUFFER_OUT_OF_BUFFERS_size

// FS_ERR_LOCKDEVICE_DEVICE_BUSY
#define FS_ERR_LOCKDEVICE_DEVICE_BUSY_size "hc"
#define FS_ERR_LOCKDEVICE_DEVICE_BUSY FS_ERR_LOCKDEVICE_DEVICE_BUSY__enum,FS_ERR_LOCKDEVICE_DEVICE_BUSY_size

// FS_ERR_NONBLOCKLOCKDEVICE_DEVICE_BUSY
#define FS_ERR_NONBLOCKLOCKDEVICE_DEVICE_BUSY_size "hc"
#define FS_ERR_NONBLOCKLOCKDEVICE_DEVICE_BUSY FS_ERR_NONBLOCKLOCKDEVICE_DEVICE_BUSY__enum,FS_ERR_NONBLOCKLOCKDEVICE_DEVICE_BUSY_size

// FS_ERR_NONBLOCKLOCKDEVICE_LOCK_DEV_FAIL
#define FS_ERR_NONBLOCKLOCKDEVICE_LOCK_DEV_FAIL_size "hc"
#define FS_ERR_NONBLOCKLOCKDEVICE_LOCK_DEV_FAIL FS_ERR_NONBLOCKLOCKDEVICE_LOCK_DEV_FAIL__enum,FS_ERR_NONBLOCKLOCKDEVICE_LOCK_DEV_FAIL_size

// FS_ERR_NONBLOCKLOCKDEVICE_LOCK_RTF_FAIL
#define FS_ERR_NONBLOCKLOCKDEVICE_LOCK_RTF_FAIL_size "hc"
#define FS_ERR_NONBLOCKLOCKDEVICE_LOCK_RTF_FAIL FS_ERR_NONBLOCKLOCKDEVICE_LOCK_RTF_FAIL__enum,FS_ERR_NONBLOCKLOCKDEVICE_LOCK_RTF_FAIL_size

// FS_ERR_PARSEFH_OUT_OF_RANGE
#define FS_ERR_PARSEFH_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_PARSEFH_OUT_OF_RANGE FS_ERR_PARSEFH_OUT_OF_RANGE__enum,FS_ERR_PARSEFH_OUT_OF_RANGE_size

// FS_ERR_PARSEFH_UNLOCKED
#define FS_ERR_PARSEFH_UNLOCKED_size "hd"
#define FS_ERR_PARSEFH_UNLOCKED FS_ERR_PARSEFH_UNLOCKED__enum,FS_ERR_PARSEFH_UNLOCKED_size

// FS_ERR_PARSEFH_UNIQUE_NOT_MATCHED
#define FS_ERR_PARSEFH_UNIQUE_NOT_MATCHED_size "hd"
#define FS_ERR_PARSEFH_UNIQUE_NOT_MATCHED FS_ERR_PARSEFH_UNIQUE_NOT_MATCHED__enum,FS_ERR_PARSEFH_UNIQUE_NOT_MATCHED_size

// FS_ERR_PARSEFH_NULL_DEV
#define FS_ERR_PARSEFH_NULL_DEV_size "hd"
#define FS_ERR_PARSEFH_NULL_DEV FS_ERR_PARSEFH_NULL_DEV__enum,FS_ERR_PARSEFH_NULL_DEV_size

// FS_ERR_PARSEFH_INVALID_AFTER_DEV_LOCKED
#define FS_ERR_PARSEFH_INVALID_AFTER_DEV_LOCKED_size "hd"
#define FS_ERR_PARSEFH_INVALID_AFTER_DEV_LOCKED FS_ERR_PARSEFH_INVALID_AFTER_DEV_LOCKED__enum,FS_ERR_PARSEFH_INVALID_AFTER_DEV_LOCKED_size

// FS_ERR_PARSEFH_EXPORTED
#define FS_ERR_PARSEFH_EXPORTED_size "hd"
#define FS_ERR_PARSEFH_EXPORTED FS_ERR_PARSEFH_EXPORTED__enum,FS_ERR_PARSEFH_EXPORTED_size

// FS_ERR_PARSEFH_MEDIA_CHANGED
#define FS_ERR_PARSEFH_MEDIA_CHANGED_size "hd"
#define FS_ERR_PARSEFH_MEDIA_CHANGED FS_ERR_PARSEFH_MEDIA_CHANGED__enum,FS_ERR_PARSEFH_MEDIA_CHANGED_size

// FS_ERR_NBPARSEFH_OUT_OF_RANGE
#define FS_ERR_NBPARSEFH_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_NBPARSEFH_OUT_OF_RANGE FS_ERR_NBPARSEFH_OUT_OF_RANGE__enum,FS_ERR_NBPARSEFH_OUT_OF_RANGE_size

// FS_ERR_NBPARSEFH_UNLOCKED
#define FS_ERR_NBPARSEFH_UNLOCKED_size "hd"
#define FS_ERR_NBPARSEFH_UNLOCKED FS_ERR_NBPARSEFH_UNLOCKED__enum,FS_ERR_NBPARSEFH_UNLOCKED_size

// FS_ERR_NBPARSEFH_UNIQUE_NOT_MATCHED
#define FS_ERR_NBPARSEFH_UNIQUE_NOT_MATCHED_size "hd"
#define FS_ERR_NBPARSEFH_UNIQUE_NOT_MATCHED FS_ERR_NBPARSEFH_UNIQUE_NOT_MATCHED__enum,FS_ERR_NBPARSEFH_UNIQUE_NOT_MATCHED_size

// FS_ERR_NBPARSEFH_NULL_DEV
#define FS_ERR_NBPARSEFH_NULL_DEV_size "hd"
#define FS_ERR_NBPARSEFH_NULL_DEV FS_ERR_NBPARSEFH_NULL_DEV__enum,FS_ERR_NBPARSEFH_NULL_DEV_size

// FS_ERR_NBPARSEFH_INVALID_AFTER_DEV_LOCKED
#define FS_ERR_NBPARSEFH_INVALID_AFTER_DEV_LOCKED_size "hd"
#define FS_ERR_NBPARSEFH_INVALID_AFTER_DEV_LOCKED FS_ERR_NBPARSEFH_INVALID_AFTER_DEV_LOCKED__enum,FS_ERR_NBPARSEFH_INVALID_AFTER_DEV_LOCKED_size

// FS_ERR_NBPARSEFH_EXPORTED
#define FS_ERR_NBPARSEFH_EXPORTED_size "hd"
#define FS_ERR_NBPARSEFH_EXPORTED FS_ERR_NBPARSEFH_EXPORTED__enum,FS_ERR_NBPARSEFH_EXPORTED_size

// FS_ERR_NBPARSEFH_MEDIA_CHANGED
#define FS_ERR_NBPARSEFH_MEDIA_CHANGED_size "hd"
#define FS_ERR_NBPARSEFH_MEDIA_CHANGED FS_ERR_NBPARSEFH_MEDIA_CHANGED__enum,FS_ERR_NBPARSEFH_MEDIA_CHANGED_size

// FS_ERR_MOUNTDRIVE_DEV_MOUNT_FAIL
#define FS_ERR_MOUNTDRIVE_DEV_MOUNT_FAIL_size "hcd"
#define FS_ERR_MOUNTDRIVE_DEV_MOUNT_FAIL FS_ERR_MOUNTDRIVE_DEV_MOUNT_FAIL__enum,FS_ERR_MOUNTDRIVE_DEV_MOUNT_FAIL_size

// FS_ERR_MOUNTDRIVE_DRV_MOUNT_FAIL
#define FS_ERR_MOUNTDRIVE_DRV_MOUNT_FAIL_size "hcd"
#define FS_ERR_MOUNTDRIVE_DRV_MOUNT_FAIL FS_ERR_MOUNTDRIVE_DRV_MOUNT_FAIL__enum,FS_ERR_MOUNTDRIVE_DRV_MOUNT_FAIL_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_SIG
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SIG_size "hÇdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SIG FS_ERR_MOUNTDRIVE_INVALID_FS_SIG__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_SIG_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_SEC
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SEC_size "hdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SEC FS_ERR_MOUNTDRIVE_INVALID_FS_SEC__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_SEC_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_SPC
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SPC_size "hdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_SPC FS_ERR_MOUNTDRIVE_INVALID_FS_SPC__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_SPC_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_TYPE
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_TYPE_size "hdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_TYPE FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_TYPE__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_TYPE_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_FAT32_VER
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT32_VER_size "hdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT32_VER FS_ERR_MOUNTDRIVE_INVALID_FS_FAT32_VER__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_FAT32_VER_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_RESERVED_SEC
#define FS_ERR_MOUNTDRIVE_INVALID_FS_RESERVED_SEC_size "hc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_RESERVED_SEC FS_ERR_MOUNTDRIVE_INVALID_FS_RESERVED_SEC__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_RESERVED_SEC_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_CNT
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_CNT_size "hdc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_CNT FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_CNT__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_CNT_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_SIZE
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_SIZE_size "hc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_SIZE FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_SIZE__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_FAT_SIZE_size

// FS_ERR_MOUNTDRIVE_INVALID_FS_ZERO_SPC
#define FS_ERR_MOUNTDRIVE_INVALID_FS_ZERO_SPC_size "hc"
#define FS_ERR_MOUNTDRIVE_INVALID_FS_ZERO_SPC FS_ERR_MOUNTDRIVE_INVALID_FS_ZERO_SPC__enum,FS_ERR_MOUNTDRIVE_INVALID_FS_ZERO_SPC_size

// FS_ERR_MOUNTDRIVE_TOO_MANY_LOGI_SEC
#define FS_ERR_MOUNTDRIVE_TOO_MANY_LOGI_SEC_size "hc"
#define FS_ERR_MOUNTDRIVE_TOO_MANY_LOGI_SEC FS_ERR_MOUNTDRIVE_TOO_MANY_LOGI_SEC__enum,FS_ERR_MOUNTDRIVE_TOO_MANY_LOGI_SEC_size

// FS_ERR_MOUNTDRIVE_MEDIA_CHANGED
#define FS_ERR_MOUNTDRIVE_MEDIA_CHANGED_size "hc"
#define FS_ERR_MOUNTDRIVE_MEDIA_CHANGED FS_ERR_MOUNTDRIVE_MEDIA_CHANGED__enum,FS_ERR_MOUNTDRIVE_MEDIA_CHANGED_size

// FS_ERR_SCANPTABLE_MBR_SIG
#define FS_ERR_SCANPTABLE_MBR_SIG_size "hdc"
#define FS_ERR_SCANPTABLE_MBR_SIG FS_ERR_SCANPTABLE_MBR_SIG__enum,FS_ERR_SCANPTABLE_MBR_SIG_size

// FS_ERR_SCANPTABLE_BOOT_INDICATOR
#define FS_ERR_SCANPTABLE_BOOT_INDICATOR_size "hdc"
#define FS_ERR_SCANPTABLE_BOOT_INDICATOR FS_ERR_SCANPTABLE_BOOT_INDICATOR__enum,FS_ERR_SCANPTABLE_BOOT_INDICATOR_size

// FS_ERR_SCANPTABLE_EXT_MBR_SIG
#define FS_ERR_SCANPTABLE_EXT_MBR_SIG_size "hdc"
#define FS_ERR_SCANPTABLE_EXT_MBR_SIG FS_ERR_SCANPTABLE_EXT_MBR_SIG__enum,FS_ERR_SCANPTABLE_EXT_MBR_SIG_size

// FS_ERR_SCANPTABLE_RELATIVE_SECTOR
#define FS_ERR_SCANPTABLE_RELATIVE_SECTOR_size "hdc"
#define FS_ERR_SCANPTABLE_RELATIVE_SECTOR FS_ERR_SCANPTABLE_RELATIVE_SECTOR__enum,FS_ERR_SCANPTABLE_RELATIVE_SECTOR_size

// FS_ERR_LOCATEDRIVE_DRVIDX_OUT_OF_RANGE
#define FS_ERR_LOCATEDRIVE_DRVIDX_OUT_OF_RANGE_size "hd"
#define FS_ERR_LOCATEDRIVE_DRVIDX_OUT_OF_RANGE FS_ERR_LOCATEDRIVE_DRVIDX_OUT_OF_RANGE__enum,FS_ERR_LOCATEDRIVE_DRVIDX_OUT_OF_RANGE_size

// FS_ERR_LOCATEDRIVE_EXPORTED
#define FS_ERR_LOCATEDRIVE_EXPORTED_size "hc"
#define FS_ERR_LOCATEDRIVE_EXPORTED FS_ERR_LOCATEDRIVE_EXPORTED__enum,FS_ERR_LOCATEDRIVE_EXPORTED_size

// FS_ERR_LOCATEDRIVE_MEDIA_CHANGED
#define FS_ERR_LOCATEDRIVE_MEDIA_CHANGED_size "hc"
#define FS_ERR_LOCATEDRIVE_MEDIA_CHANGED FS_ERR_LOCATEDRIVE_MEDIA_CHANGED__enum,FS_ERR_LOCATEDRIVE_MEDIA_CHANGED_size

// FS_ERR_GETCLUSTERVALUE_INVALID_IN_CLUSTER
#define FS_ERR_GETCLUSTERVALUE_INVALID_IN_CLUSTER_size "hd"
#define FS_ERR_GETCLUSTERVALUE_INVALID_IN_CLUSTER FS_ERR_GETCLUSTERVALUE_INVALID_IN_CLUSTER__enum,FS_ERR_GETCLUSTERVALUE_INVALID_IN_CLUSTER_size

// FS_ERR_GETCLUSTERVALUE_INVALID_OUT_CLUSTER
#define FS_ERR_GETCLUSTERVALUE_INVALID_OUT_CLUSTER_size "hÑd"
#define FS_ERR_GETCLUSTERVALUE_INVALID_OUT_CLUSTER FS_ERR_GETCLUSTERVALUE_INVALID_OUT_CLUSTER__enum,FS_ERR_GETCLUSTERVALUE_INVALID_OUT_CLUSTER_size

// FS_ERR_SETCLUSTERVALUE_INVALID_IN_CLUSTER
#define FS_ERR_SETCLUSTERVALUE_INVALID_IN_CLUSTER_size "hd"
#define FS_ERR_SETCLUSTERVALUE_INVALID_IN_CLUSTER FS_ERR_SETCLUSTERVALUE_INVALID_IN_CLUSTER__enum,FS_ERR_SETCLUSTERVALUE_INVALID_IN_CLUSTER_size

// FS_ERR_SETCLUSTERVALUE_INVALID_OUT_CLUSTER
#define FS_ERR_SETCLUSTERVALUE_INVALID_OUT_CLUSTER_size "hÇd"
#define FS_ERR_SETCLUSTERVALUE_INVALID_OUT_CLUSTER FS_ERR_SETCLUSTERVALUE_INVALID_OUT_CLUSTER__enum,FS_ERR_SETCLUSTERVALUE_INVALID_OUT_CLUSTER_size

// FS_ERR_ALLOCFATSEGPERMIT_DISK_FULL
#define FS_ERR_ALLOCFATSEGPERMIT_DISK_FULL_size "hc"
#define FS_ERR_ALLOCFATSEGPERMIT_DISK_FULL FS_ERR_ALLOCFATSEGPERMIT_DISK_FULL__enum,FS_ERR_ALLOCFATSEGPERMIT_DISK_FULL_size

// FS_ERR_ALLOCFATSEGPERMIT_APP_QERR
#define FS_ERR_ALLOCFATSEGPERMIT_APP_QERR_size "hd"
#define FS_ERR_ALLOCFATSEGPERMIT_APP_QERR FS_ERR_ALLOCFATSEGPERMIT_APP_QERR__enum,FS_ERR_ALLOCFATSEGPERMIT_APP_QERR_size

// FS_ERR_ALLOCFATSEG_DISK_FULL
#define FS_ERR_ALLOCFATSEG_DISK_FULL_size "hc"
#define FS_ERR_ALLOCFATSEG_DISK_FULL FS_ERR_ALLOCFATSEG_DISK_FULL__enum,FS_ERR_ALLOCFATSEG_DISK_FULL_size

// FS_ERR_MOVEFILEPTR_WRAP_AROUND
#define FS_ERR_MOVEFILEPTR_WRAP_AROUND_size "hÇd"
#define FS_ERR_MOVEFILEPTR_WRAP_AROUND FS_ERR_MOVEFILEPTR_WRAP_AROUND__enum,FS_ERR_MOVEFILEPTR_WRAP_AROUND_size

// FS_ERR_MOVEFILEPTR_BEYOND_LAST_CLUSTER
#define FS_ERR_MOVEFILEPTR_BEYOND_LAST_CLUSTER_size "hd"
#define FS_ERR_MOVEFILEPTR_BEYOND_LAST_CLUSTER FS_ERR_MOVEFILEPTR_BEYOND_LAST_CLUSTER__enum,FS_ERR_MOVEFILEPTR_BEYOND_LAST_CLUSTER_size

// FS_ERR_STARTDIRSEARCH_BEYOND_LAST_CLUSTER
#define FS_ERR_STARTDIRSEARCH_BEYOND_LAST_CLUSTER_size "hÇdc"
#define FS_ERR_STARTDIRSEARCH_BEYOND_LAST_CLUSTER FS_ERR_STARTDIRSEARCH_BEYOND_LAST_CLUSTER__enum,FS_ERR_STARTDIRSEARCH_BEYOND_LAST_CLUSTER_size

// FS_ERR_RTFRENAME_DRIVE_NOT_THE_SAME
#define FS_ERR_RTFRENAME_DRIVE_NOT_THE_SAME_size "h"
#define FS_ERR_RTFRENAME_DRIVE_NOT_THE_SAME FS_ERR_RTFRENAME_DRIVE_NOT_THE_SAME__enum,FS_ERR_RTFRENAME_DRIVE_NOT_THE_SAME_size

// FS_ERR_RTFREAD_FPTR_OUT_OF_RANGE
#define FS_ERR_RTFREAD_FPTR_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_RTFREAD_FPTR_OUT_OF_RANGE FS_ERR_RTFREAD_FPTR_OUT_OF_RANGE__enum,FS_ERR_RTFREAD_FPTR_OUT_OF_RANGE_size

// FS_ERR_RTFREAD_FPTR_WRAP_AROUND
#define FS_ERR_RTFREAD_FPTR_WRAP_AROUND_size "hÇd"
#define FS_ERR_RTFREAD_FPTR_WRAP_AROUND FS_ERR_RTFREAD_FPTR_WRAP_AROUND__enum,FS_ERR_RTFREAD_FPTR_WRAP_AROUND_size

// FS_ERR_RTFREAD_MUST_READ_SECTOR_ALIGNED
#define FS_ERR_RTFREAD_MUST_READ_SECTOR_ALIGNED_size "hd"
#define FS_ERR_RTFREAD_MUST_READ_SECTOR_ALIGNED FS_ERR_RTFREAD_MUST_READ_SECTOR_ALIGNED__enum,FS_ERR_RTFREAD_MUST_READ_SECTOR_ALIGNED_size

// FS_ERR_RTFREAD_INVALID_FMAPED_HANDLE
#define FS_ERR_RTFREAD_INVALID_FMAPED_HANDLE_size "hd"
#define FS_ERR_RTFREAD_INVALID_FMAPED_HANDLE FS_ERR_RTFREAD_INVALID_FMAPED_HANDLE__enum,FS_ERR_RTFREAD_INVALID_FMAPED_HANDLE_size

// FS_ERR_RTFWRITE_FPTR_OUT_OF_RANGE
#define FS_ERR_RTFWRITE_FPTR_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_RTFWRITE_FPTR_OUT_OF_RANGE FS_ERR_RTFWRITE_FPTR_OUT_OF_RANGE__enum,FS_ERR_RTFWRITE_FPTR_OUT_OF_RANGE_size

// FS_ERR_RTFWRITE_FPTR_WRAP_AROUND
#define FS_ERR_RTFWRITE_FPTR_WRAP_AROUND_size "hÇd"
#define FS_ERR_RTFWRITE_FPTR_WRAP_AROUND FS_ERR_RTFWRITE_FPTR_WRAP_AROUND__enum,FS_ERR_RTFWRITE_FPTR_WRAP_AROUND_size

// FS_ERR_RTFWRITE_MUST_READ_SECTOR_ALIGNED
#define FS_ERR_RTFWRITE_MUST_READ_SECTOR_ALIGNED_size "hd"
#define FS_ERR_RTFWRITE_MUST_READ_SECTOR_ALIGNED FS_ERR_RTFWRITE_MUST_READ_SECTOR_ALIGNED__enum,FS_ERR_RTFWRITE_MUST_READ_SECTOR_ALIGNED_size

// FS_ERR_RTFWRITE_INVALID_FMAPED_HANDLE
#define FS_ERR_RTFWRITE_INVALID_FMAPED_HANDLE_size "hd"
#define FS_ERR_RTFWRITE_INVALID_FMAPED_HANDLE FS_ERR_RTFWRITE_INVALID_FMAPED_HANDLE__enum,FS_ERR_RTFWRITE_INVALID_FMAPED_HANDLE_size

// FS_ERR_RTFTRUNCATE_NORMAL_FILE_ONLY
#define FS_ERR_RTFTRUNCATE_NORMAL_FILE_ONLY_size "h"
#define FS_ERR_RTFTRUNCATE_NORMAL_FILE_ONLY FS_ERR_RTFTRUNCATE_NORMAL_FILE_ONLY__enum,FS_ERR_RTFTRUNCATE_NORMAL_FILE_ONLY_size

// FS_ERR_RTFTRUNCATE_FPTR_OUT_OF_RANGE
#define FS_ERR_RTFTRUNCATE_FPTR_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_RTFTRUNCATE_FPTR_OUT_OF_RANGE FS_ERR_RTFTRUNCATE_FPTR_OUT_OF_RANGE__enum,FS_ERR_RTFTRUNCATE_FPTR_OUT_OF_RANGE_size

// FS_ERR_RTFSEEK_FPTR_OUT_OF_RANGE
#define FS_ERR_RTFSEEK_FPTR_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_RTFSEEK_FPTR_OUT_OF_RANGE FS_ERR_RTFSEEK_FPTR_OUT_OF_RANGE__enum,FS_ERR_RTFSEEK_FPTR_OUT_OF_RANGE_size

// FS_ERR_RTFSEEK_INVALID_WHENCE
#define FS_ERR_RTFSEEK_INVALID_WHENCE_size "hd"
#define FS_ERR_RTFSEEK_INVALID_WHENCE FS_ERR_RTFSEEK_INVALID_WHENCE__enum,FS_ERR_RTFSEEK_INVALID_WHENCE_size

// FS_ERR_RTFSEEK_FPTR_WRAP_AROUND
#define FS_ERR_RTFSEEK_FPTR_WRAP_AROUND_size "hÉd"
#define FS_ERR_RTFSEEK_FPTR_WRAP_AROUND FS_ERR_RTFSEEK_FPTR_WRAP_AROUND__enum,FS_ERR_RTFSEEK_FPTR_WRAP_AROUND_size

// FS_ERR_RTFSEEK_MUST_READ_SECTOR_ALIGNED
#define FS_ERR_RTFSEEK_MUST_READ_SECTOR_ALIGNED_size "hÉd"
#define FS_ERR_RTFSEEK_MUST_READ_SECTOR_ALIGNED FS_ERR_RTFSEEK_MUST_READ_SECTOR_ALIGNED__enum,FS_ERR_RTFSEEK_MUST_READ_SECTOR_ALIGNED_size

// FS_ERR_RTFSEEK_INVALID_FMAPED_HANDLE
#define FS_ERR_RTFSEEK_INVALID_FMAPED_HANDLE_size "hd"
#define FS_ERR_RTFSEEK_INVALID_FMAPED_HANDLE FS_ERR_RTFSEEK_INVALID_FMAPED_HANDLE__enum,FS_ERR_RTFSEEK_INVALID_FMAPED_HANDLE_size

// FS_ERR_RTFSEEK_CANT_EXTEND_READ_ONLY_FILE
#define FS_ERR_RTFSEEK_CANT_EXTEND_READ_ONLY_FILE_size "hÇd"
#define FS_ERR_RTFSEEK_CANT_EXTEND_READ_ONLY_FILE FS_ERR_RTFSEEK_CANT_EXTEND_READ_ONLY_FILE__enum,FS_ERR_RTFSEEK_CANT_EXTEND_READ_ONLY_FILE_size

// FS_ERR_RTFSEEK_CANT_EXTEND_ROOT_DIR
#define FS_ERR_RTFSEEK_CANT_EXTEND_ROOT_DIR_size "hÇd"
#define FS_ERR_RTFSEEK_CANT_EXTEND_ROOT_DIR FS_ERR_RTFSEEK_CANT_EXTEND_ROOT_DIR__enum,FS_ERR_RTFSEEK_CANT_EXTEND_ROOT_DIR_size

// FS_ERR_RTFSEEK_INVALID_CLUSTER
#define FS_ERR_RTFSEEK_INVALID_CLUSTER_size "hd"
#define FS_ERR_RTFSEEK_INVALID_CLUSTER FS_ERR_RTFSEEK_INVALID_CLUSTER__enum,FS_ERR_RTFSEEK_INVALID_CLUSTER_size

// FS_ERR_RTFEXTEND_FPTR_OUT_OF_RANGE
#define FS_ERR_RTFEXTEND_FPTR_OUT_OF_RANGE_size "hÇd"
#define FS_ERR_RTFEXTEND_FPTR_OUT_OF_RANGE FS_ERR_RTFEXTEND_FPTR_OUT_OF_RANGE__enum,FS_ERR_RTFEXTEND_FPTR_OUT_OF_RANGE_size

// FS_ERR_RTFEXTEND_FSIZE_WRAP_AROUND
#define FS_ERR_RTFEXTEND_FSIZE_WRAP_AROUND_size "hÇd"
#define FS_ERR_RTFEXTEND_FSIZE_WRAP_AROUND FS_ERR_RTFEXTEND_FSIZE_WRAP_AROUND__enum,FS_ERR_RTFEXTEND_FSIZE_WRAP_AROUND_size

// FS_ERR_RTFRESETDISK_FILE_NOT_CLOSED
#define FS_ERR_RTFRESETDISK_FILE_NOT_CLOSED_size "hd"
#define FS_ERR_RTFRESETDISK_FILE_NOT_CLOSED FS_ERR_RTFRESETDISK_FILE_NOT_CLOSED__enum,FS_ERR_RTFRESETDISK_FILE_NOT_CLOSED_size

// FS_ERR_COPYSECTORS_DEV_ERROR
#define FS_ERR_COPYSECTORS_DEV_ERROR_size "hÉd"
#define FS_ERR_COPYSECTORS_DEV_ERROR FS_ERR_COPYSECTORS_DEV_ERROR__enum,FS_ERR_COPYSECTORS_DEV_ERROR_size

// FS_ERR_COPYSECTORS_DEV_NOT_MOUNTED
#define FS_ERR_COPYSECTORS_DEV_NOT_MOUNTED_size "hÉd"
#define FS_ERR_COPYSECTORS_DEV_NOT_MOUNTED FS_ERR_COPYSECTORS_DEV_NOT_MOUNTED__enum,FS_ERR_COPYSECTORS_DEV_NOT_MOUNTED_size

// FS_ERR_COPYSECTORS_DRIVER_FAILED
#define FS_ERR_COPYSECTORS_DRIVER_FAILED_size "hÉd"
#define FS_ERR_COPYSECTORS_DRIVER_FAILED FS_ERR_COPYSECTORS_DRIVER_FAILED__enum,FS_ERR_COPYSECTORS_DRIVER_FAILED_size

// FS_ERR_FILENAME_INVALID_CHAR
#define FS_ERR_FILENAME_INVALID_CHAR_size "hd"
#define FS_ERR_FILENAME_INVALID_CHAR FS_ERR_FILENAME_INVALID_CHAR__enum,FS_ERR_FILENAME_INVALID_CHAR_size

// FS_ERR_FILENAME_INVALID_LEADING_BLANK
#define FS_ERR_FILENAME_INVALID_LEADING_BLANK_size "h"
#define FS_ERR_FILENAME_INVALID_LEADING_BLANK FS_ERR_FILENAME_INVALID_LEADING_BLANK__enum,FS_ERR_FILENAME_INVALID_LEADING_BLANK_size

// FS_ERR_FILENAME_INVALID_TAILING_DOT
#define FS_ERR_FILENAME_INVALID_TAILING_DOT_size "h"
#define FS_ERR_FILENAME_INVALID_TAILING_DOT FS_ERR_FILENAME_INVALID_TAILING_DOT__enum,FS_ERR_FILENAME_INVALID_TAILING_DOT_size

// FS_ERR_VOLUMELABEL_TOO_LONG
#define FS_ERR_VOLUMELABEL_TOO_LONG_size "h"
#define FS_ERR_VOLUMELABEL_TOO_LONG FS_ERR_VOLUMELABEL_TOO_LONG__enum,FS_ERR_VOLUMELABEL_TOO_LONG_size

// FS_ERR_DIRENTRY_INVALID_START_CLUSTER
#define FS_ERR_DIRENTRY_INVALID_START_CLUSTER_size "hÑd"
#define FS_ERR_DIRENTRY_INVALID_START_CLUSTER FS_ERR_DIRENTRY_INVALID_START_CLUSTER__enum,FS_ERR_DIRENTRY_INVALID_START_CLUSTER_size

// FS_CACHE_LIST_INSERT
#define FS_CACHE_LIST_INSERT_size "hÉd"
#define FS_CACHE_LIST_INSERT FS_CACHE_LIST_INSERT__enum,FS_CACHE_LIST_INSERT_size

// FS_CACHE_LIST_REMOVE
#define FS_CACHE_LIST_REMOVE_size "hÉd"
#define FS_CACHE_LIST_REMOVE FS_CACHE_LIST_REMOVE__enum,FS_CACHE_LIST_REMOVE_size

// FS_CACHE_HIT
#define FS_CACHE_HIT_size "hÉd"
#define FS_CACHE_HIT FS_CACHE_HIT__enum,FS_CACHE_HIT_size

// FS_CACHE_DISCARD
#define FS_CACHE_DISCARD_size "hÉd"
#define FS_CACHE_DISCARD FS_CACHE_DISCARD__enum,FS_CACHE_DISCARD_size

// FS_CACHE_WRITE
#define FS_CACHE_WRITE_size "hÉd"
#define FS_CACHE_WRITE FS_CACHE_WRITE__enum,FS_CACHE_WRITE_size

// FS_CACHE_READ
#define FS_CACHE_READ_size "hÉd"
#define FS_CACHE_READ FS_CACHE_READ__enum,FS_CACHE_READ_size

// FS_CACHE_LRU
#define FS_CACHE_LRU_size "hÉd"
#define FS_CACHE_LRU FS_CACHE_LRU__enum,FS_CACHE_LRU_size

// FS_CACHE_LIST
#define FS_CACHE_LIST_size "hÑd"
#define FS_CACHE_LIST FS_CACHE_LIST__enum,FS_CACHE_LIST_size

// FS_CACHE_FLUSH_ALL
#define FS_CACHE_FLUSH_ALL_size "h"
#define FS_CACHE_FLUSH_ALL FS_CACHE_FLUSH_ALL__enum,FS_CACHE_FLUSH_ALL_size

// FS_CACHE_CONFIG
#define FS_CACHE_CONFIG_size "hd"
#define FS_CACHE_CONFIG FS_CACHE_CONFIG__enum,FS_CACHE_CONFIG_size

// FS_INFO_FT_TITLE
#define FS_INFO_FT_TITLE_size NULL
#define FS_INFO_FT_TITLE FS_INFO_FT_TITLE__enum,FS_INFO_FT_TITLE_size

// FS_INFO_FT_SLOT
#define FS_INFO_FT_SLOT_size "ÇdÉcÇdåc"
#define FS_INFO_FT_SLOT FS_INFO_FT_SLOT__enum,FS_INFO_FT_SLOT_size

// FS_INFO_FT_LFN
#define FS_INFO_FT_LFN_size NULL
#define FS_INFO_FT_LFN FS_INFO_FT_LFN__enum,FS_INFO_FT_LFN_size

// FS_INFO_FT_TAIL
#define FS_INFO_FT_TAIL_size NULL
#define FS_INFO_FT_TAIL FS_INFO_FT_TAIL__enum,FS_INFO_FT_TAIL_size

// FS_INFO_DIR_ENTRY_WALKED
#define FS_INFO_DIR_ENTRY_WALKED_size "hd"
#define FS_INFO_DIR_ENTRY_WALKED FS_INFO_DIR_ENTRY_WALKED__enum,FS_INFO_DIR_ENTRY_WALKED_size

// FS_INFO_COPY_FILE_BUFFER_SIZE
#define FS_INFO_COPY_FILE_BUFFER_SIZE_size "hd"
#define FS_INFO_COPY_FILE_BUFFER_SIZE FS_INFO_COPY_FILE_BUFFER_SIZE__enum,FS_INFO_COPY_FILE_BUFFER_SIZE_size

// FS_INFO_QUOTA_DELETE
#define FS_INFO_QUOTA_DELETE_size "hÇd"
#define FS_INFO_QUOTA_DELETE FS_INFO_QUOTA_DELETE__enum,FS_INFO_QUOTA_DELETE_size

// FS_INFO_QUOTA_STATUS_NOW_FATDELETE
#define FS_INFO_QUOTA_STATUS_NOW_FATDELETE_size "hÇd"
#define FS_INFO_QUOTA_STATUS_NOW_FATDELETE FS_INFO_QUOTA_STATUS_NOW_FATDELETE__enum,FS_INFO_QUOTA_STATUS_NOW_FATDELETE_size

// FS_INFO_QUOTA_STATUS_NOW_ALLOCFATSEG
#define FS_INFO_QUOTA_STATUS_NOW_ALLOCFATSEG_size "hÇd"
#define FS_INFO_QUOTA_STATUS_NOW_ALLOCFATSEG FS_INFO_QUOTA_STATUS_NOW_ALLOCFATSEG__enum,FS_INFO_QUOTA_STATUS_NOW_ALLOCFATSEG_size

// FS_INFO_QUOTA_STATUS_NOW_RTFEXTEND
#define FS_INFO_QUOTA_STATUS_NOW_RTFEXTEND_size "hÇd"
#define FS_INFO_QUOTA_STATUS_NOW_RTFEXTEND FS_INFO_QUOTA_STATUS_NOW_RTFEXTEND__enum,FS_INFO_QUOTA_STATUS_NOW_RTFEXTEND_size

// FS_INFO_QUOTA_BEFORE_ALLOC
#define FS_INFO_QUOTA_BEFORE_ALLOC_size "hÇd"
#define FS_INFO_QUOTA_BEFORE_ALLOC FS_INFO_QUOTA_BEFORE_ALLOC__enum,FS_INFO_QUOTA_BEFORE_ALLOC_size

// FS_INFO_LFN
#define FS_INFO_LFN_size NULL
#define FS_INFO_LFN FS_INFO_LFN__enum,FS_INFO_LFN_size

// FS_INFO_LFN_ERR
#define FS_INFO_LFN_ERR_size NULL
#define FS_INFO_LFN_ERR FS_INFO_LFN_ERR__enum,FS_INFO_LFN_ERR_size

// FS_INFO_FAT_SECTOR
#define FS_INFO_FAT_SECTOR_size NULL
#define FS_INFO_FAT_SECTOR FS_INFO_FAT_SECTOR__enum,FS_INFO_FAT_SECTOR_size

// FS_INFO_DIR_ENTRY
#define FS_INFO_DIR_ENTRY_size NULL
#define FS_INFO_DIR_ENTRY FS_INFO_DIR_ENTRY__enum,FS_INFO_DIR_ENTRY_size

// FS_INFO_DISK_ERROR
#define FS_INFO_DISK_ERROR_size "h"
#define FS_INFO_DISK_ERROR FS_INFO_DISK_ERROR__enum,FS_INFO_DISK_ERROR_size

// FS_INFO_DISK_ERROR2
#define FS_INFO_DISK_ERROR2_size "hc"
#define FS_INFO_DISK_ERROR2 FS_INFO_DISK_ERROR2__enum,FS_INFO_DISK_ERROR2_size

// FS_INFO_TOP_FH_USER_TITLE
#define FS_INFO_TOP_FH_USER_TITLE_size NULL
#define FS_INFO_TOP_FH_USER_TITLE FS_INFO_TOP_FH_USER_TITLE__enum,FS_INFO_TOP_FH_USER_TITLE_size

// FS_INFO_TOP_FH_USER
#define FS_INFO_TOP_FH_USER_size "dÉcÇd"
#define FS_INFO_TOP_FH_USER FS_INFO_TOP_FH_USER__enum,FS_INFO_TOP_FH_USER_size

// FS_INFO_TOP_FH_USER_TAIL
#define FS_INFO_TOP_FH_USER_TAIL_size NULL
#define FS_INFO_TOP_FH_USER_TAIL FS_INFO_TOP_FH_USER_TAIL__enum,FS_INFO_TOP_FH_USER_TAIL_size

// FS_INFO_IO_STAT_START
#define FS_INFO_IO_STAT_START_size NULL
#define FS_INFO_IO_STAT_START FS_INFO_IO_STAT_START__enum,FS_INFO_IO_STAT_START_size

// FS_INFO_IO_STAT_TITLE
#define FS_INFO_IO_STAT_TITLE_size NULL
#define FS_INFO_IO_STAT_TITLE FS_INFO_IO_STAT_TITLE__enum,FS_INFO_IO_STAT_TITLE_size

// FS_INFO_IO_STAT_ENTRY
#define FS_INFO_IO_STAT_ENTRY_size "dÉcÑd"
#define FS_INFO_IO_STAT_ENTRY FS_INFO_IO_STAT_ENTRY__enum,FS_INFO_IO_STAT_ENTRY_size

// FS_INFO_IO_STAT_LINE
#define FS_INFO_IO_STAT_LINE_size NULL
#define FS_INFO_IO_STAT_LINE FS_INFO_IO_STAT_LINE__enum,FS_INFO_IO_STAT_LINE_size

// FS_INFO_IO_STAT_TOTAL
#define FS_INFO_IO_STAT_TOTAL_size "Éd"
#define FS_INFO_IO_STAT_TOTAL FS_INFO_IO_STAT_TOTAL__enum,FS_INFO_IO_STAT_TOTAL_size

// FS_INFO_IO_STAT_TAIL
#define FS_INFO_IO_STAT_TAIL_size NULL
#define FS_INFO_IO_STAT_TAIL FS_INFO_IO_STAT_TAIL__enum,FS_INFO_IO_STAT_TAIL_size

// FS_INFO_IO_STAT_DISABLE
#define FS_INFO_IO_STAT_DISABLE_size NULL
#define FS_INFO_IO_STAT_DISABLE FS_INFO_IO_STAT_DISABLE__enum,FS_INFO_IO_STAT_DISABLE_size

// FS_INFO_GR1_READSECTORS
#define FS_INFO_GR1_READSECTORS_size "hcÑd"
#define FS_INFO_GR1_READSECTORS FS_INFO_GR1_READSECTORS__enum,FS_INFO_GR1_READSECTORS_size

// FS_INFO_GR1_WRITESECTORS
#define FS_INFO_GR1_WRITESECTORS_size "hcÑd"
#define FS_INFO_GR1_WRITESECTORS FS_INFO_GR1_WRITESECTORS__enum,FS_INFO_GR1_WRITESECTORS_size

// FS_INFO_GR2_READSECTORS
#define FS_INFO_GR2_READSECTORS_size "hcÑd"
#define FS_INFO_GR2_READSECTORS FS_INFO_GR2_READSECTORS__enum,FS_INFO_GR2_READSECTORS_size

// FS_INFO_GR2_WRITESECTORS
#define FS_INFO_GR2_WRITESECTORS_size "hcÑd"
#define FS_INFO_GR2_WRITESECTORS FS_INFO_GR2_WRITESECTORS__enum,FS_INFO_GR2_WRITESECTORS_size

// FS_INFO_READSECTORS_S
#define FS_INFO_READSECTORS_S_size "hd"
#define FS_INFO_READSECTORS_S FS_INFO_READSECTORS_S__enum,FS_INFO_READSECTORS_S_size

// FS_INFO_WRITESECTORS_S
#define FS_INFO_WRITESECTORS_S_size "hd"
#define FS_INFO_WRITESECTORS_S FS_INFO_WRITESECTORS_S__enum,FS_INFO_WRITESECTORS_S_size

// FSAL_TRACE_OPEN_ERROR
#define FSAL_TRACE_OPEN_ERROR_size "Çd"
#define FSAL_TRACE_OPEN_ERROR FSAL_TRACE_OPEN_ERROR__enum,FSAL_TRACE_OPEN_ERROR_size

// FSAL_TRACE_CLOSE_ERROR
#define FSAL_TRACE_CLOSE_ERROR_size "Çd"
#define FSAL_TRACE_CLOSE_ERROR FSAL_TRACE_CLOSE_ERROR__enum,FSAL_TRACE_CLOSE_ERROR_size

// FSAL_TRACE_READ_ERROR
#define FSAL_TRACE_READ_ERROR_size "Çd"
#define FSAL_TRACE_READ_ERROR FSAL_TRACE_READ_ERROR__enum,FSAL_TRACE_READ_ERROR_size

// FSAL_TRACE_READ_ERROR_OUT_OF_RANGE
#define FSAL_TRACE_READ_ERROR_OUT_OF_RANGE_size "d"
#define FSAL_TRACE_READ_ERROR_OUT_OF_RANGE FSAL_TRACE_READ_ERROR_OUT_OF_RANGE__enum,FSAL_TRACE_READ_ERROR_OUT_OF_RANGE_size

// FSAL_TRACE_WRITE_ERROR
#define FSAL_TRACE_WRITE_ERROR_size "Éd"
#define FSAL_TRACE_WRITE_ERROR FSAL_TRACE_WRITE_ERROR__enum,FSAL_TRACE_WRITE_ERROR_size

// FSAL_TRACE_SEEK_ERROR
#define FSAL_TRACE_SEEK_ERROR_size "Çd"
#define FSAL_TRACE_SEEK_ERROR FSAL_TRACE_SEEK_ERROR__enum,FSAL_TRACE_SEEK_ERROR_size

// FSAL_TRACE_SEEK_ERROR_OUT_OF_RANGE
#define FSAL_TRACE_SEEK_ERROR_OUT_OF_RANGE_size "d"
#define FSAL_TRACE_SEEK_ERROR_OUT_OF_RANGE FSAL_TRACE_SEEK_ERROR_OUT_OF_RANGE__enum,FSAL_TRACE_SEEK_ERROR_OUT_OF_RANGE_size

// FSAL_TRACE_GET_FILE_POSITION_ERROR
#define FSAL_TRACE_GET_FILE_POSITION_ERROR_size "Çd"
#define FSAL_TRACE_GET_FILE_POSITION_ERROR FSAL_TRACE_GET_FILE_POSITION_ERROR__enum,FSAL_TRACE_GET_FILE_POSITION_ERROR_size

// FSAL_TRACE_GET_FILE_SIZE_ERROR
#define FSAL_TRACE_GET_FILE_SIZE_ERROR_size "Çd"
#define FSAL_TRACE_GET_FILE_SIZE_ERROR FSAL_TRACE_GET_FILE_SIZE_ERROR__enum,FSAL_TRACE_GET_FILE_SIZE_ERROR_size

// FSAL_TRACE_BUF_READ_BLK_ERROR
#define FSAL_TRACE_BUF_READ_BLK_ERROR_size "Ñd"
#define FSAL_TRACE_BUF_READ_BLK_ERROR FSAL_TRACE_BUF_READ_BLK_ERROR__enum,FSAL_TRACE_BUF_READ_BLK_ERROR_size

// FSAL_TRACE_BUF_READ_ERROR
#define FSAL_TRACE_BUF_READ_ERROR_size "Çd"
#define FSAL_TRACE_BUF_READ_ERROR FSAL_TRACE_BUF_READ_ERROR__enum,FSAL_TRACE_BUF_READ_ERROR_size

// FSAL_TRACE_ERROR_FSAL_C
#define FSAL_TRACE_ERROR_FSAL_C_size "hd"
#define FSAL_TRACE_ERROR_FSAL_C FSAL_TRACE_ERROR_FSAL_C__enum,FSAL_TRACE_ERROR_FSAL_C_size

// FSAL_TRACE_ERROR_FSAL_BUF_C
#define FSAL_TRACE_ERROR_FSAL_BUF_C_size "hd"
#define FSAL_TRACE_ERROR_FSAL_BUF_C FSAL_TRACE_ERROR_FSAL_BUF_C__enum,FSAL_TRACE_ERROR_FSAL_BUF_C_size

// FS_TEST_ITERATION_START
#define FS_TEST_ITERATION_START_size NULL
#define FS_TEST_ITERATION_START FS_TEST_ITERATION_START__enum,FS_TEST_ITERATION_START_size

// FS_TEST_ITERATION_END
#define FS_TEST_ITERATION_END_size NULL
#define FS_TEST_ITERATION_END FS_TEST_ITERATION_END__enum,FS_TEST_ITERATION_END_size

// FS_SST_ASSERT_INFO1
#define FS_SST_ASSERT_INFO1_size "cd"
#define FS_SST_ASSERT_INFO1 FS_SST_ASSERT_INFO1__enum,FS_SST_ASSERT_INFO1_size

// FS_SST_ASSERT_INFO2
#define FS_SST_ASSERT_INFO2_size "Éd"
#define FS_SST_ASSERT_INFO2 FS_SST_ASSERT_INFO2__enum,FS_SST_ASSERT_INFO2_size

// FS_SST_ASSERT_GUIDELINE
#define FS_SST_ASSERT_GUIDELINE_size NULL
#define FS_SST_ASSERT_GUIDELINE FS_SST_ASSERT_GUIDELINE__enum,FS_SST_ASSERT_GUIDELINE_size

// FS_SST_USER_ERROR_TITLE
#define FS_SST_USER_ERROR_TITLE_size NULL
#define FS_SST_USER_ERROR_TITLE FS_SST_USER_ERROR_TITLE__enum,FS_SST_USER_ERROR_TITLE_size

// FS_SST_INTERNAL_ERROR_TITLE
#define FS_SST_INTERNAL_ERROR_TITLE_size NULL
#define FS_SST_INTERNAL_ERROR_TITLE FS_SST_INTERNAL_ERROR_TITLE__enum,FS_SST_INTERNAL_ERROR_TITLE_size

// FS_SST_API_CLOSE_ALL
#define FS_SST_API_CLOSE_ALL_size NULL
#define FS_SST_API_CLOSE_ALL FS_SST_API_CLOSE_ALL__enum,FS_SST_API_CLOSE_ALL_size

// FS_SST_BUFFER_02
#define FS_SST_BUFFER_02_size NULL
#define FS_SST_BUFFER_02 FS_SST_BUFFER_02__enum,FS_SST_BUFFER_02_size

// FS_SST_HANDLE_01
#define FS_SST_HANDLE_01_size NULL
#define FS_SST_HANDLE_01 FS_SST_HANDLE_01__enum,FS_SST_HANDLE_01_size

// FS_SST_CLUSTER_01
#define FS_SST_CLUSTER_01_size "d"
#define FS_SST_CLUSTER_01 FS_SST_CLUSTER_01__enum,FS_SST_CLUSTER_01_size

// FS_SST_CLUSTER_03
#define FS_SST_CLUSTER_03_size "d"
#define FS_SST_CLUSTER_03 FS_SST_CLUSTER_03__enum,FS_SST_CLUSTER_03_size

// FS_SST_CLUSTER_05
#define FS_SST_CLUSTER_05_size "d"
#define FS_SST_CLUSTER_05 FS_SST_CLUSTER_05__enum,FS_SST_CLUSTER_05_size

// FS_SST_CLUSTER_06
#define FS_SST_CLUSTER_06_size "d"
#define FS_SST_CLUSTER_06 FS_SST_CLUSTER_06__enum,FS_SST_CLUSTER_06_size

// FS_SST_CLUSTER_08
#define FS_SST_CLUSTER_08_size "d"
#define FS_SST_CLUSTER_08 FS_SST_CLUSTER_08__enum,FS_SST_CLUSTER_08_size

// FS_SST_DIRENTRY_01
#define FS_SST_DIRENTRY_01_size NULL
#define FS_SST_DIRENTRY_01 FS_SST_DIRENTRY_01__enum,FS_SST_DIRENTRY_01_size

// FS_SST_EXCEPTION_04
#define FS_SST_EXCEPTION_04_size NULL
#define FS_SST_EXCEPTION_04 FS_SST_EXCEPTION_04__enum,FS_SST_EXCEPTION_04_size

// FS_SST_TLS_02
#define FS_SST_TLS_02_size "d"
#define FS_SST_TLS_02 FS_SST_TLS_02__enum,FS_SST_TLS_02_size

// FS_SST_MUTEX_01
#define FS_SST_MUTEX_01_size "d"
#define FS_SST_MUTEX_01 FS_SST_MUTEX_01__enum,FS_SST_MUTEX_01_size

// FS_SST_TOO_MANY_OPENED_FILES
#define FS_SST_TOO_MANY_OPENED_FILES_size NULL
#define FS_SST_TOO_MANY_OPENED_FILES FS_SST_TOO_MANY_OPENED_FILES__enum,FS_SST_TOO_MANY_OPENED_FILES_size


#endif // FS_TRC_GEN.H
