#ifndef _GPS_TRC_GEN_H_
#define _GPS_TRC_GEN_H_

// GPS_UART_TRC_MSG_HDLR
#define GPS_UART_TRC_MSG_HDLR_size "d"
#define GPS_UART_TRC_MSG_HDLR GPS_UART_TRC_MSG_HDLR__enum,GPS_UART_TRC_MSG_HDLR_size

// GPS_UART_TRC_DROP_ONE_SENTENCE
#define GPS_UART_TRC_DROP_ONE_SENTENCE_size "d"
#define GPS_UART_TRC_DROP_ONE_SENTENCE GPS_UART_TRC_DROP_ONE_SENTENCE__enum,GPS_UART_TRC_DROP_ONE_SENTENCE_size

// GPS_UART_TRC_BUFFER_READ_SIZE
#define GPS_UART_TRC_BUFFER_READ_SIZE_size "„d"
#define GPS_UART_TRC_BUFFER_READ_SIZE GPS_UART_TRC_BUFFER_READ_SIZE__enum,GPS_UART_TRC_BUFFER_READ_SIZE_size

// GPS_UART_TRC_NEED_INDICATION
#define GPS_UART_TRC_NEED_INDICATION_size "‚d"
#define GPS_UART_TRC_NEED_INDICATION GPS_UART_TRC_NEED_INDICATION__enum,GPS_UART_TRC_NEED_INDICATION_size

// GPS_UART_TRC_OPEN_REQ_HDLR
#define GPS_UART_TRC_OPEN_REQ_HDLR_size NULL
#define GPS_UART_TRC_OPEN_REQ_HDLR GPS_UART_TRC_OPEN_REQ_HDLR__enum,GPS_UART_TRC_OPEN_REQ_HDLR_size

// GPS_UART_TRC_OPEN_REQ_HDLR_SET_EVENT
#define GPS_UART_TRC_OPEN_REQ_HDLR_SET_EVENT_size NULL
#define GPS_UART_TRC_OPEN_REQ_HDLR_SET_EVENT GPS_UART_TRC_OPEN_REQ_HDLR_SET_EVENT__enum,GPS_UART_TRC_OPEN_REQ_HDLR_SET_EVENT_size

// GPS_UART_TRC_OPEN_ERROR
#define GPS_UART_TRC_OPEN_ERROR_size NULL
#define GPS_UART_TRC_OPEN_ERROR GPS_UART_TRC_OPEN_ERROR__enum,GPS_UART_TRC_OPEN_ERROR_size

// GPS_UART_TRC_OPEN_ADD_TO_SLOT
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_size "‚d"
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT GPS_UART_TRC_OPEN_ADD_TO_SLOT__enum,GPS_UART_TRC_OPEN_ADD_TO_SLOT_size

// GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_MOD
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_MOD_size NULL
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_MOD GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_MOD__enum,GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_MOD_size

// GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_SLOT
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_SLOT_size "d"
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_SLOT GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_SLOT__enum,GPS_UART_TRC_OPEN_ADD_TO_SLOT_FIND_SLOT_size

// GPS_UART_TRC_OPEN_ADD_TO_SLOT_NO_SLOT
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_NO_SLOT_size NULL
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_NO_SLOT GPS_UART_TRC_OPEN_ADD_TO_SLOT_NO_SLOT__enum,GPS_UART_TRC_OPEN_ADD_TO_SLOT_NO_SLOT_size

// GPS_UART_TRC_OPEN_ADD_TO_SLOT_SUCCESS
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_SUCCESS_size NULL
#define GPS_UART_TRC_OPEN_ADD_TO_SLOT_SUCCESS GPS_UART_TRC_OPEN_ADD_TO_SLOT_SUCCESS__enum,GPS_UART_TRC_OPEN_ADD_TO_SLOT_SUCCESS_size

// GPS_UART_TRC_OPEN_FIND_PORT
#define GPS_UART_TRC_OPEN_FIND_PORT_size "d"
#define GPS_UART_TRC_OPEN_FIND_PORT GPS_UART_TRC_OPEN_FIND_PORT__enum,GPS_UART_TRC_OPEN_FIND_PORT_size

// GPS_UART_TRC_OPEN_NEW_PORT
#define GPS_UART_TRC_OPEN_NEW_PORT_size "d"
#define GPS_UART_TRC_OPEN_NEW_PORT GPS_UART_TRC_OPEN_NEW_PORT__enum,GPS_UART_TRC_OPEN_NEW_PORT_size

// GPS_UART_TRC_OPEN_PORT_STATE
#define GPS_UART_TRC_OPEN_PORT_STATE_size "d"
#define GPS_UART_TRC_OPEN_PORT_STATE GPS_UART_TRC_OPEN_PORT_STATE__enum,GPS_UART_TRC_OPEN_PORT_STATE_size

// GPS_UART_TRC_OPEN_GPS_PORT
#define GPS_UART_TRC_OPEN_GPS_PORT_size NULL
#define GPS_UART_TRC_OPEN_GPS_PORT GPS_UART_TRC_OPEN_GPS_PORT__enum,GPS_UART_TRC_OPEN_GPS_PORT_size

// GPS_UART_TRC_OPEN_REQUEST_PORT
#define GPS_UART_TRC_OPEN_REQUEST_PORT_size "d"
#define GPS_UART_TRC_OPEN_REQUEST_PORT GPS_UART_TRC_OPEN_REQUEST_PORT__enum,GPS_UART_TRC_OPEN_REQUEST_PORT_size

// GPS_UART_TRC_OPEN_PORT_FINAL_STATE
#define GPS_UART_TRC_OPEN_PORT_FINAL_STATE_size "d"
#define GPS_UART_TRC_OPEN_PORT_FINAL_STATE GPS_UART_TRC_OPEN_PORT_FINAL_STATE__enum,GPS_UART_TRC_OPEN_PORT_FINAL_STATE_size

// GPS_UART_TRC_OPEN_RAW_OK
#define GPS_UART_TRC_OPEN_RAW_OK_size NULL
#define GPS_UART_TRC_OPEN_RAW_OK GPS_UART_TRC_OPEN_RAW_OK__enum,GPS_UART_TRC_OPEN_RAW_OK_size

// GPS_UART_TRC_OPEN_LCT_OK
#define GPS_UART_TRC_OPEN_LCT_OK_size NULL
#define GPS_UART_TRC_OPEN_LCT_OK GPS_UART_TRC_OPEN_LCT_OK__enum,GPS_UART_TRC_OPEN_LCT_OK_size

// GPS_UART_TRC_OPEN_QOP_OK
#define GPS_UART_TRC_OPEN_QOP_OK_size NULL
#define GPS_UART_TRC_OPEN_QOP_OK GPS_UART_TRC_OPEN_QOP_OK__enum,GPS_UART_TRC_OPEN_QOP_OK_size

// GPS_UART_TRC_OPEN_FIND_MOD_CMP
#define GPS_UART_TRC_OPEN_FIND_MOD_CMP_size "ƒd"
#define GPS_UART_TRC_OPEN_FIND_MOD_CMP GPS_UART_TRC_OPEN_FIND_MOD_CMP__enum,GPS_UART_TRC_OPEN_FIND_MOD_CMP_size

// GPS_UART_TRC_OPEN_FIND_EMP_MOD
#define GPS_UART_TRC_OPEN_FIND_EMP_MOD_size "‚d"
#define GPS_UART_TRC_OPEN_FIND_EMP_MOD GPS_UART_TRC_OPEN_FIND_EMP_MOD__enum,GPS_UART_TRC_OPEN_FIND_EMP_MOD_size

// GPS_UART_TRC_EVENT_IND
#define GPS_UART_TRC_EVENT_IND_size "d"
#define GPS_UART_TRC_EVENT_IND GPS_UART_TRC_EVENT_IND__enum,GPS_UART_TRC_EVENT_IND_size

// GPS_UART_TRC_ERROR
#define GPS_UART_TRC_ERROR_size "‚d"
#define GPS_UART_TRC_ERROR GPS_UART_TRC_ERROR__enum,GPS_UART_TRC_ERROR_size

// GPS_UART_TRC_MODE_READY
#define GPS_UART_TRC_MODE_READY_size "d"
#define GPS_UART_TRC_MODE_READY GPS_UART_TRC_MODE_READY__enum,GPS_UART_TRC_MODE_READY_size

// GPS_UART_TRC_GPS_START_FINISH
#define GPS_UART_TRC_GPS_START_FINISH_size "d"
#define GPS_UART_TRC_GPS_START_FINISH GPS_UART_TRC_GPS_START_FINISH__enum,GPS_UART_TRC_GPS_START_FINISH_size

// GPS_UART_TRC_NEXT_JOB
#define GPS_UART_TRC_NEXT_JOB_size "‚d"
#define GPS_UART_TRC_NEXT_JOB GPS_UART_TRC_NEXT_JOB__enum,GPS_UART_TRC_NEXT_JOB_size

// GPS_UART_TRC_CLOSE_HDLR
#define GPS_UART_TRC_CLOSE_HDLR_size "‚d"
#define GPS_UART_TRC_CLOSE_HDLR GPS_UART_TRC_CLOSE_HDLR__enum,GPS_UART_TRC_CLOSE_HDLR_size

// GPS_UART_TRC_CLOSE_FIND_RAW
#define GPS_UART_TRC_CLOSE_FIND_RAW_size NULL
#define GPS_UART_TRC_CLOSE_FIND_RAW GPS_UART_TRC_CLOSE_FIND_RAW__enum,GPS_UART_TRC_CLOSE_FIND_RAW_size

// GPS_UART_TRC_CLOSE_FIND_LCT
#define GPS_UART_TRC_CLOSE_FIND_LCT_size NULL
#define GPS_UART_TRC_CLOSE_FIND_LCT GPS_UART_TRC_CLOSE_FIND_LCT__enum,GPS_UART_TRC_CLOSE_FIND_LCT_size

// GPS_UART_TRC_CLOSE_FIND_QOP
#define GPS_UART_TRC_CLOSE_FIND_QOP_size NULL
#define GPS_UART_TRC_CLOSE_FIND_QOP GPS_UART_TRC_CLOSE_FIND_QOP__enum,GPS_UART_TRC_CLOSE_FIND_QOP_size

// GPS_UART_TRC_CLOSE_CHECK_PORT_CLOSE
#define GPS_UART_TRC_CLOSE_CHECK_PORT_CLOSE_size NULL
#define GPS_UART_TRC_CLOSE_CHECK_PORT_CLOSE GPS_UART_TRC_CLOSE_CHECK_PORT_CLOSE__enum,GPS_UART_TRC_CLOSE_CHECK_PORT_CLOSE_size

// GPS_UART_TRC_CLOSE_GPS_POWER_DOWN
#define GPS_UART_TRC_CLOSE_GPS_POWER_DOWN_size NULL
#define GPS_UART_TRC_CLOSE_GPS_POWER_DOWN GPS_UART_TRC_CLOSE_GPS_POWER_DOWN__enum,GPS_UART_TRC_CLOSE_GPS_POWER_DOWN_size

// GPS_UART_TRC_CLOSE_UART_PORT
#define GPS_UART_TRC_CLOSE_UART_PORT_size "d"
#define GPS_UART_TRC_CLOSE_UART_PORT GPS_UART_TRC_CLOSE_UART_PORT__enum,GPS_UART_TRC_CLOSE_UART_PORT_size

// GPS_UART_TRC_CLOSE_EXIT
#define GPS_UART_TRC_CLOSE_EXIT_size NULL
#define GPS_UART_TRC_CLOSE_EXIT GPS_UART_TRC_CLOSE_EXIT__enum,GPS_UART_TRC_CLOSE_EXIT_size

// GPS_UART_TRC_CLOSE_SWITCH_MOD_ID
#define GPS_UART_TRC_CLOSE_SWITCH_MOD_ID_size "ƒd"
#define GPS_UART_TRC_CLOSE_SWITCH_MOD_ID GPS_UART_TRC_CLOSE_SWITCH_MOD_ID__enum,GPS_UART_TRC_CLOSE_SWITCH_MOD_ID_size

// GPS_UART_TRC_CLOSE_SWITCH_REQ_COUNT
#define GPS_UART_TRC_CLOSE_SWITCH_REQ_COUNT_size "ƒd"
#define GPS_UART_TRC_CLOSE_SWITCH_REQ_COUNT GPS_UART_TRC_CLOSE_SWITCH_REQ_COUNT__enum,GPS_UART_TRC_CLOSE_SWITCH_REQ_COUNT_size

// GPS_UART_TRC_CLOSE_SWITCH_ABORT_REQ_MOD
#define GPS_UART_TRC_CLOSE_SWITCH_ABORT_REQ_MOD_size "ƒd"
#define GPS_UART_TRC_CLOSE_SWITCH_ABORT_REQ_MOD GPS_UART_TRC_CLOSE_SWITCH_ABORT_REQ_MOD__enum,GPS_UART_TRC_CLOSE_SWITCH_ABORT_REQ_MOD_size

// GPS_UART_TRC_CLOSE_SWITCH_ABORT_MOD_ID
#define GPS_UART_TRC_CLOSE_SWITCH_ABORT_MOD_ID_size "‚d"
#define GPS_UART_TRC_CLOSE_SWITCH_ABORT_MOD_ID GPS_UART_TRC_CLOSE_SWITCH_ABORT_MOD_ID__enum,GPS_UART_TRC_CLOSE_SWITCH_ABORT_MOD_ID_size

// GPS_UART_TRC_CLOSE_PORT_ALREADY_CLOSED
#define GPS_UART_TRC_CLOSE_PORT_ALREADY_CLOSED_size "d"
#define GPS_UART_TRC_CLOSE_PORT_ALREADY_CLOSED GPS_UART_TRC_CLOSE_PORT_ALREADY_CLOSED__enum,GPS_UART_TRC_CLOSE_PORT_ALREADY_CLOSED_size

// GPS_UART_TRC_INTERNAL_WRITE
#define GPS_UART_TRC_INTERNAL_WRITE_size "‚d"
#define GPS_UART_TRC_INTERNAL_WRITE GPS_UART_TRC_INTERNAL_WRITE__enum,GPS_UART_TRC_INTERNAL_WRITE_size

// GPS_UART_TRC_WRITE_HDLR
#define GPS_UART_TRC_WRITE_HDLR_size "…d"
#define GPS_UART_TRC_WRITE_HDLR GPS_UART_TRC_WRITE_HDLR__enum,GPS_UART_TRC_WRITE_HDLR_size

// GPS_UART_TRC_GPS_CMD_WARMSTART
#define GPS_UART_TRC_GPS_CMD_WARMSTART_size NULL
#define GPS_UART_TRC_GPS_CMD_WARMSTART GPS_UART_TRC_GPS_CMD_WARMSTART__enum,GPS_UART_TRC_GPS_CMD_WARMSTART_size

// GPS_UART_TRC_GPS_CMD_HOTSTART
#define GPS_UART_TRC_GPS_CMD_HOTSTART_size NULL
#define GPS_UART_TRC_GPS_CMD_HOTSTART GPS_UART_TRC_GPS_CMD_HOTSTART__enum,GPS_UART_TRC_GPS_CMD_HOTSTART_size

// GPS_UART_TRC_GPS_CMD_COLDSTART
#define GPS_UART_TRC_GPS_CMD_COLDSTART_size NULL
#define GPS_UART_TRC_GPS_CMD_COLDSTART GPS_UART_TRC_GPS_CMD_COLDSTART__enum,GPS_UART_TRC_GPS_CMD_COLDSTART_size

// GPS_UART_TRC_GPS_CMD_VERSION
#define GPS_UART_TRC_GPS_CMD_VERSION_size NULL
#define GPS_UART_TRC_GPS_CMD_VERSION GPS_UART_TRC_GPS_CMD_VERSION__enum,GPS_UART_TRC_GPS_CMD_VERSION_size

// GPS_UART_TRC_GPS_CMD_ENABLE_DEBUG_INFO
#define GPS_UART_TRC_GPS_CMD_ENABLE_DEBUG_INFO_size NULL
#define GPS_UART_TRC_GPS_CMD_ENABLE_DEBUG_INFO GPS_UART_TRC_GPS_CMD_ENABLE_DEBUG_INFO__enum,GPS_UART_TRC_GPS_CMD_ENABLE_DEBUG_INFO_size

// GPS_UART_TRC_GPS_CMD_SWITCH_MA
#define GPS_UART_TRC_GPS_CMD_SWITCH_MA_size NULL
#define GPS_UART_TRC_GPS_CMD_SWITCH_MA GPS_UART_TRC_GPS_CMD_SWITCH_MA__enum,GPS_UART_TRC_GPS_CMD_SWITCH_MA_size

// GPS_UART_TRC_GPS_CMD_SWITCH_MB
#define GPS_UART_TRC_GPS_CMD_SWITCH_MB_size NULL
#define GPS_UART_TRC_GPS_CMD_SWITCH_MB GPS_UART_TRC_GPS_CMD_SWITCH_MB__enum,GPS_UART_TRC_GPS_CMD_SWITCH_MB_size

// GPS_UART_TRC_GPS_CMD_SWITCH_MB_TYPE
#define GPS_UART_TRC_GPS_CMD_SWITCH_MB_TYPE_size "d"
#define GPS_UART_TRC_GPS_CMD_SWITCH_MB_TYPE GPS_UART_TRC_GPS_CMD_SWITCH_MB_TYPE__enum,GPS_UART_TRC_GPS_CMD_SWITCH_MB_TYPE_size

// GPS_UART_TRC_GPS_CMD_SWITCH_NORMAL
#define GPS_UART_TRC_GPS_CMD_SWITCH_NORMAL_size NULL
#define GPS_UART_TRC_GPS_CMD_SWITCH_NORMAL GPS_UART_TRC_GPS_CMD_SWITCH_NORMAL__enum,GPS_UART_TRC_GPS_CMD_SWITCH_NORMAL_size

// GPS_UART_TRC_GPS_CMD_POS_QUERY
#define GPS_UART_TRC_GPS_CMD_POS_QUERY_size NULL
#define GPS_UART_TRC_GPS_CMD_POS_QUERY GPS_UART_TRC_GPS_CMD_POS_QUERY__enum,GPS_UART_TRC_GPS_CMD_POS_QUERY_size

// GPS_UART_TRC_GPS_CMD_MEAS_QUERY
#define GPS_UART_TRC_GPS_CMD_MEAS_QUERY_size NULL
#define GPS_UART_TRC_GPS_CMD_MEAS_QUERY GPS_UART_TRC_GPS_CMD_MEAS_QUERY__enum,GPS_UART_TRC_GPS_CMD_MEAS_QUERY_size

// GPS_UART_TRC_GPS_CMD_CLEAR_NVRAM
#define GPS_UART_TRC_GPS_CMD_CLEAR_NVRAM_size NULL
#define GPS_UART_TRC_GPS_CMD_CLEAR_NVRAM GPS_UART_TRC_GPS_CMD_CLEAR_NVRAM__enum,GPS_UART_TRC_GPS_CMD_CLEAR_NVRAM_size

// GPS_UART_TRC_GPS_CMD_SLEEP
#define GPS_UART_TRC_GPS_CMD_SLEEP_size NULL
#define GPS_UART_TRC_GPS_CMD_SLEEP GPS_UART_TRC_GPS_CMD_SLEEP__enum,GPS_UART_TRC_GPS_CMD_SLEEP_size

// GPS_UART_TRC_GPS_CMD_STOP
#define GPS_UART_TRC_GPS_CMD_STOP_size NULL
#define GPS_UART_TRC_GPS_CMD_STOP GPS_UART_TRC_GPS_CMD_STOP__enum,GPS_UART_TRC_GPS_CMD_STOP_size

// GPS_UART_TRC_GPS_CMD_WAKE_UP
#define GPS_UART_TRC_GPS_CMD_WAKE_UP_size NULL
#define GPS_UART_TRC_GPS_CMD_WAKE_UP GPS_UART_TRC_GPS_CMD_WAKE_UP__enum,GPS_UART_TRC_GPS_CMD_WAKE_UP_size

// GPS_UART_TRC_GPS_CMD_WRITTEN
#define GPS_UART_TRC_GPS_CMD_WRITTEN_size "d"
#define GPS_UART_TRC_GPS_CMD_WRITTEN GPS_UART_TRC_GPS_CMD_WRITTEN__enum,GPS_UART_TRC_GPS_CMD_WRITTEN_size

// GPS_UART_TRC_GPS_CMD_NUMBER
#define GPS_UART_TRC_GPS_CMD_NUMBER_size "d"
#define GPS_UART_TRC_GPS_CMD_NUMBER GPS_UART_TRC_GPS_CMD_NUMBER__enum,GPS_UART_TRC_GPS_CMD_NUMBER_size

// GPS_UART_TRC_GPS_CMD_UNPROCESSED_CMD
#define GPS_UART_TRC_GPS_CMD_UNPROCESSED_CMD_size "d"
#define GPS_UART_TRC_GPS_CMD_UNPROCESSED_CMD GPS_UART_TRC_GPS_CMD_UNPROCESSED_CMD__enum,GPS_UART_TRC_GPS_CMD_UNPROCESSED_CMD_size

// GPS_UART_TRC_ENABLE_SENTENCE
#define GPS_UART_TRC_ENABLE_SENTENCE_size NULL
#define GPS_UART_TRC_ENABLE_SENTENCE GPS_UART_TRC_ENABLE_SENTENCE__enum,GPS_UART_TRC_ENABLE_SENTENCE_size

// GPS_UART_TRC_DISABLE_SENTENCE
#define GPS_UART_TRC_DISABLE_SENTENCE_size NULL
#define GPS_UART_TRC_DISABLE_SENTENCE GPS_UART_TRC_DISABLE_SENTENCE__enum,GPS_UART_TRC_DISABLE_SENTENCE_size

// GPS_UART_TRC_ENABLE_PARSER
#define GPS_UART_TRC_ENABLE_PARSER_size NULL
#define GPS_UART_TRC_ENABLE_PARSER GPS_UART_TRC_ENABLE_PARSER__enum,GPS_UART_TRC_ENABLE_PARSER_size

// GPS_UART_TRC_DISABLE_PARSER
#define GPS_UART_TRC_DISABLE_PARSER_size NULL
#define GPS_UART_TRC_DISABLE_PARSER GPS_UART_TRC_DISABLE_PARSER__enum,GPS_UART_TRC_DISABLE_PARSER_size

// GPS_PARSER_TRC_SUB_FIELD
#define GPS_PARSER_TRC_SUB_FIELD_size "‚d"
#define GPS_PARSER_TRC_SUB_FIELD GPS_PARSER_TRC_SUB_FIELD__enum,GPS_PARSER_TRC_SUB_FIELD_size

// GPS_TRC_EER_OVER_CMD_MAX_FILED
#define GPS_TRC_EER_OVER_CMD_MAX_FILED_size "‚d"
#define GPS_TRC_EER_OVER_CMD_MAX_FILED GPS_TRC_EER_OVER_CMD_MAX_FILED__enum,GPS_TRC_EER_OVER_CMD_MAX_FILED_size

// GPS_PARSER_TRC_SUB_FIELD_STAR
#define GPS_PARSER_TRC_SUB_FIELD_STAR_size NULL
#define GPS_PARSER_TRC_SUB_FIELD_STAR GPS_PARSER_TRC_SUB_FIELD_STAR__enum,GPS_PARSER_TRC_SUB_FIELD_STAR_size

// GPS_PARSER_TRC_GGA_FAILED
#define GPS_PARSER_TRC_GGA_FAILED_size NULL
#define GPS_PARSER_TRC_GGA_FAILED GPS_PARSER_TRC_GGA_FAILED__enum,GPS_PARSER_TRC_GGA_FAILED_size

// GPS_PARSER_TRC_GLL_FAILED
#define GPS_PARSER_TRC_GLL_FAILED_size NULL
#define GPS_PARSER_TRC_GLL_FAILED GPS_PARSER_TRC_GLL_FAILED__enum,GPS_PARSER_TRC_GLL_FAILED_size

// GPS_PARSER_TRC_GSA_FAILED
#define GPS_PARSER_TRC_GSA_FAILED_size NULL
#define GPS_PARSER_TRC_GSA_FAILED GPS_PARSER_TRC_GSA_FAILED__enum,GPS_PARSER_TRC_GSA_FAILED_size

// GPS_PARSER_TRC_GSV_FAILED
#define GPS_PARSER_TRC_GSV_FAILED_size NULL
#define GPS_PARSER_TRC_GSV_FAILED GPS_PARSER_TRC_GSV_FAILED__enum,GPS_PARSER_TRC_GSV_FAILED_size

// GPS_PARSER_TRC_RMC_FAILED
#define GPS_PARSER_TRC_RMC_FAILED_size NULL
#define GPS_PARSER_TRC_RMC_FAILED GPS_PARSER_TRC_RMC_FAILED__enum,GPS_PARSER_TRC_RMC_FAILED_size

// GPS_PARSER_TRC_VTG_FAILED
#define GPS_PARSER_TRC_VTG_FAILED_size NULL
#define GPS_PARSER_TRC_VTG_FAILED GPS_PARSER_TRC_VTG_FAILED__enum,GPS_PARSER_TRC_VTG_FAILED_size

// GPS_PARSER_TRC_ACC_FAILED
#define GPS_PARSER_TRC_ACC_FAILED_size NULL
#define GPS_PARSER_TRC_ACC_FAILED GPS_PARSER_TRC_ACC_FAILED__enum,GPS_PARSER_TRC_ACC_FAILED_size

// GPS_PARSER_TRC_P_RELEASE_FAILED
#define GPS_PARSER_TRC_P_RELEASE_FAILED_size NULL
#define GPS_PARSER_TRC_P_RELEASE_FAILED GPS_PARSER_TRC_P_RELEASE_FAILED__enum,GPS_PARSER_TRC_P_RELEASE_FAILED_size

// GPS_PARSER_TRC_P_ACQ_FAILED
#define GPS_PARSER_TRC_P_ACQ_FAILED_size NULL
#define GPS_PARSER_TRC_P_ACQ_FAILED GPS_PARSER_TRC_P_ACQ_FAILED__enum,GPS_PARSER_TRC_P_ACQ_FAILED_size

// GPS_PARSER_TRC_P_BITSYNC_FAILED
#define GPS_PARSER_TRC_P_BITSYNC_FAILED_size NULL
#define GPS_PARSER_TRC_P_BITSYNC_FAILED GPS_PARSER_TRC_P_BITSYNC_FAILED__enum,GPS_PARSER_TRC_P_BITSYNC_FAILED_size

// GPS_PARSER_TRC_P_SIGNAL_FAILED
#define GPS_PARSER_TRC_P_SIGNAL_FAILED_size NULL
#define GPS_PARSER_TRC_P_SIGNAL_FAILED GPS_PARSER_TRC_P_SIGNAL_FAILED__enum,GPS_PARSER_TRC_P_SIGNAL_FAILED_size

// GPS_PARSER_TRC_P_FIX_CONTRL_FAILED
#define GPS_PARSER_TRC_P_FIX_CONTRL_FAILED_size NULL
#define GPS_PARSER_TRC_P_FIX_CONTRL_FAILED GPS_PARSER_TRC_P_FIX_CONTRL_FAILED__enum,GPS_PARSER_TRC_P_FIX_CONTRL_FAILED_size

// GPS_PARSER_TRC_P_CW_RESULT_FAILED
#define GPS_PARSER_TRC_P_CW_RESULT_FAILED_size NULL
#define GPS_PARSER_TRC_P_CW_RESULT_FAILED GPS_PARSER_TRC_P_CW_RESULT_FAILED__enum,GPS_PARSER_TRC_P_CW_RESULT_FAILED_size

// GPS_PARSER_TRC_P_CW_SUB_FIELD_INVALID
#define GPS_PARSER_TRC_P_CW_SUB_FIELD_INVALID_size NULL
#define GPS_PARSER_TRC_P_CW_SUB_FIELD_INVALID GPS_PARSER_TRC_P_CW_SUB_FIELD_INVALID__enum,GPS_PARSER_TRC_P_CW_SUB_FIELD_INVALID_size

// GPS_PARSER_TRC_PRO_SENTENCE
#define GPS_PARSER_TRC_PRO_SENTENCE_size NULL
#define GPS_PARSER_TRC_PRO_SENTENCE GPS_PARSER_TRC_PRO_SENTENCE__enum,GPS_PARSER_TRC_PRO_SENTENCE_size

// GPS_PARSER_TRC_PARSER_STR
#define GPS_PARSER_TRC_PARSER_STR_size NULL
#define GPS_PARSER_TRC_PARSER_STR GPS_PARSER_TRC_PARSER_STR__enum,GPS_PARSER_TRC_PARSER_STR_size

// GPS_PARSER_TRC_PARSER_CHK_SUM
#define GPS_PARSER_TRC_PARSER_CHK_SUM_size NULL
#define GPS_PARSER_TRC_PARSER_CHK_SUM GPS_PARSER_TRC_PARSER_CHK_SUM__enum,GPS_PARSER_TRC_PARSER_CHK_SUM_size

// GPS_PARSER_TRC_PARSER_NEED_END_CR
#define GPS_PARSER_TRC_PARSER_NEED_END_CR_size NULL
#define GPS_PARSER_TRC_PARSER_NEED_END_CR GPS_PARSER_TRC_PARSER_NEED_END_CR__enum,GPS_PARSER_TRC_PARSER_NEED_END_CR_size

// GPS_PARSER_TRC_PARSER_END_CR_OK
#define GPS_PARSER_TRC_PARSER_END_CR_OK_size NULL
#define GPS_PARSER_TRC_PARSER_END_CR_OK GPS_PARSER_TRC_PARSER_END_CR_OK__enum,GPS_PARSER_TRC_PARSER_END_CR_OK_size

// GPS_PARSER_TRC_PARSER_CHK_SUM_OK
#define GPS_PARSER_TRC_PARSER_CHK_SUM_OK_size NULL
#define GPS_PARSER_TRC_PARSER_CHK_SUM_OK GPS_PARSER_TRC_PARSER_CHK_SUM_OK__enum,GPS_PARSER_TRC_PARSER_CHK_SUM_OK_size

// GPS_PARSER_TRC_CB_GGA
#define GPS_PARSER_TRC_CB_GGA_size "d"
#define GPS_PARSER_TRC_CB_GGA GPS_PARSER_TRC_CB_GGA__enum,GPS_PARSER_TRC_CB_GGA_size

// GPS_PARSER_TRC_CB_GLL
#define GPS_PARSER_TRC_CB_GLL_size "d"
#define GPS_PARSER_TRC_CB_GLL GPS_PARSER_TRC_CB_GLL__enum,GPS_PARSER_TRC_CB_GLL_size

// GPS_PARSER_TRC_CB_GSA
#define GPS_PARSER_TRC_CB_GSA_size "d"
#define GPS_PARSER_TRC_CB_GSA GPS_PARSER_TRC_CB_GSA__enum,GPS_PARSER_TRC_CB_GSA_size

// GPS_PARSER_TRC_CB_GNGSA
#define GPS_PARSER_TRC_CB_GNGSA_size "d"
#define GPS_PARSER_TRC_CB_GNGSA GPS_PARSER_TRC_CB_GNGSA__enum,GPS_PARSER_TRC_CB_GNGSA_size

// GPS_PARSER_TRC_CB_GLGSA
#define GPS_PARSER_TRC_CB_GLGSA_size "d"
#define GPS_PARSER_TRC_CB_GLGSA GPS_PARSER_TRC_CB_GLGSA__enum,GPS_PARSER_TRC_CB_GLGSA_size

// GPS_PARSER_TRC_CB_GAGSA
#define GPS_PARSER_TRC_CB_GAGSA_size "d"
#define GPS_PARSER_TRC_CB_GAGSA GPS_PARSER_TRC_CB_GAGSA__enum,GPS_PARSER_TRC_CB_GAGSA_size

// GPS_PARSER_TRC_CB_BDGSA
#define GPS_PARSER_TRC_CB_BDGSA_size "d"
#define GPS_PARSER_TRC_CB_BDGSA GPS_PARSER_TRC_CB_BDGSA__enum,GPS_PARSER_TRC_CB_BDGSA_size

// GPS_PARSER_TRC_CB_GSV
#define GPS_PARSER_TRC_CB_GSV_size "‚d"
#define GPS_PARSER_TRC_CB_GSV GPS_PARSER_TRC_CB_GSV__enum,GPS_PARSER_TRC_CB_GSV_size

// GPS_PARSER_TRC_CB_GLGSV
#define GPS_PARSER_TRC_CB_GLGSV_size "‚d"
#define GPS_PARSER_TRC_CB_GLGSV GPS_PARSER_TRC_CB_GLGSV__enum,GPS_PARSER_TRC_CB_GLGSV_size

// GPS_PARSER_TRC_CB_GAGSV
#define GPS_PARSER_TRC_CB_GAGSV_size "‚d"
#define GPS_PARSER_TRC_CB_GAGSV GPS_PARSER_TRC_CB_GAGSV__enum,GPS_PARSER_TRC_CB_GAGSV_size

// GPS_PARSER_TRC_CB_BDGSV
#define GPS_PARSER_TRC_CB_BDGSV_size "‚d"
#define GPS_PARSER_TRC_CB_BDGSV GPS_PARSER_TRC_CB_BDGSV__enum,GPS_PARSER_TRC_CB_BDGSV_size

// GPS_PARSER_TRC_CB_RMC
#define GPS_PARSER_TRC_CB_RMC_size "d"
#define GPS_PARSER_TRC_CB_RMC GPS_PARSER_TRC_CB_RMC__enum,GPS_PARSER_TRC_CB_RMC_size

// GPS_PARSER_TRC_CB_GNRMC
#define GPS_PARSER_TRC_CB_GNRMC_size "d"
#define GPS_PARSER_TRC_CB_GNRMC GPS_PARSER_TRC_CB_GNRMC__enum,GPS_PARSER_TRC_CB_GNRMC_size

// GPS_PARSER_TRC_CB_VTG
#define GPS_PARSER_TRC_CB_VTG_size "d"
#define GPS_PARSER_TRC_CB_VTG GPS_PARSER_TRC_CB_VTG__enum,GPS_PARSER_TRC_CB_VTG_size

// GPS_PARSER_TRC_FIX_POSITION_OVER
#define GPS_PARSER_TRC_FIX_POSITION_OVER_size NULL
#define GPS_PARSER_TRC_FIX_POSITION_OVER GPS_PARSER_TRC_FIX_POSITION_OVER__enum,GPS_PARSER_TRC_FIX_POSITION_OVER_size

// GPS_LOG_TRC_SWITCH
#define GPS_LOG_TRC_SWITCH_size "ƒd"
#define GPS_LOG_TRC_SWITCH GPS_LOG_TRC_SWITCH__enum,GPS_LOG_TRC_SWITCH_size

// GPS_LOG_TRC_SENTENCE_TYPE
#define GPS_LOG_TRC_SENTENCE_TYPE_size "‚d"
#define GPS_LOG_TRC_SENTENCE_TYPE GPS_LOG_TRC_SENTENCE_TYPE__enum,GPS_LOG_TRC_SENTENCE_TYPE_size

// GPS_LOG_TRC_STC_CALLBACK
#define GPS_LOG_TRC_STC_CALLBACK_size "d"
#define GPS_LOG_TRC_STC_CALLBACK GPS_LOG_TRC_STC_CALLBACK__enum,GPS_LOG_TRC_STC_CALLBACK_size

// GPS_LOG_TRC_SET_GGA_CALLBACK
#define GPS_LOG_TRC_SET_GGA_CALLBACK_size "d"
#define GPS_LOG_TRC_SET_GGA_CALLBACK GPS_LOG_TRC_SET_GGA_CALLBACK__enum,GPS_LOG_TRC_SET_GGA_CALLBACK_size

// GPS_LOG_TRC_SET_RMC_CALLBACK
#define GPS_LOG_TRC_SET_RMC_CALLBACK_size "d"
#define GPS_LOG_TRC_SET_RMC_CALLBACK GPS_LOG_TRC_SET_RMC_CALLBACK__enum,GPS_LOG_TRC_SET_RMC_CALLBACK_size

// GPS_LOG_TRC_SET_GSA_CALLBACK
#define GPS_LOG_TRC_SET_GSA_CALLBACK_size "d"
#define GPS_LOG_TRC_SET_GSA_CALLBACK GPS_LOG_TRC_SET_GSA_CALLBACK__enum,GPS_LOG_TRC_SET_GSA_CALLBACK_size

// GPS_LOG_TRC_SET_GSV_CALLBACK
#define GPS_LOG_TRC_SET_GSV_CALLBACK_size "d"
#define GPS_LOG_TRC_SET_GSV_CALLBACK GPS_LOG_TRC_SET_GSV_CALLBACK__enum,GPS_LOG_TRC_SET_GSV_CALLBACK_size

// GPS_LOG_TRC_SET_STC_CALLBACK
#define GPS_LOG_TRC_SET_STC_CALLBACK_size "d"
#define GPS_LOG_TRC_SET_STC_CALLBACK GPS_LOG_TRC_SET_STC_CALLBACK__enum,GPS_LOG_TRC_SET_STC_CALLBACK_size

// GPS_LOG_TRC_MAKE_PATH_CARD_DRIVER
#define GPS_LOG_TRC_MAKE_PATH_CARD_DRIVER_size "d"
#define GPS_LOG_TRC_MAKE_PATH_CARD_DRIVER GPS_LOG_TRC_MAKE_PATH_CARD_DRIVER__enum,GPS_LOG_TRC_MAKE_PATH_CARD_DRIVER_size

// GPS_LOG_TRC_MAKE_PATH_USER_DRIVER
#define GPS_LOG_TRC_MAKE_PATH_USER_DRIVER_size "d"
#define GPS_LOG_TRC_MAKE_PATH_USER_DRIVER GPS_LOG_TRC_MAKE_PATH_USER_DRIVER__enum,GPS_LOG_TRC_MAKE_PATH_USER_DRIVER_size

// GPS_LOG_TRC_SET_CATCHER_LOGGING
#define GPS_LOG_TRC_SET_CATCHER_LOGGING_size "d"
#define GPS_LOG_TRC_SET_CATCHER_LOGGING GPS_LOG_TRC_SET_CATCHER_LOGGING__enum,GPS_LOG_TRC_SET_CATCHER_LOGGING_size

// GPS_LOG_TRC_SET_CATCHER_LOGGING_RES
#define GPS_LOG_TRC_SET_CATCHER_LOGGING_RES_size "d"
#define GPS_LOG_TRC_SET_CATCHER_LOGGING_RES GPS_LOG_TRC_SET_CATCHER_LOGGING_RES__enum,GPS_LOG_TRC_SET_CATCHER_LOGGING_RES_size

// GPS_LOG_TRC_SET_FILE_LOGGING
#define GPS_LOG_TRC_SET_FILE_LOGGING_size "d"
#define GPS_LOG_TRC_SET_FILE_LOGGING GPS_LOG_TRC_SET_FILE_LOGGING__enum,GPS_LOG_TRC_SET_FILE_LOGGING_size

// GPS_LOG_TRC_SET_FILE_LOGGING_RES
#define GPS_LOG_TRC_SET_FILE_LOGGING_RES_size "d"
#define GPS_LOG_TRC_SET_FILE_LOGGING_RES GPS_LOG_TRC_SET_FILE_LOGGING_RES__enum,GPS_LOG_TRC_SET_FILE_LOGGING_RES_size

// GPS_LOG_TRC_SET_AGENT_LOGGING
#define GPS_LOG_TRC_SET_AGENT_LOGGING_size "d"
#define GPS_LOG_TRC_SET_AGENT_LOGGING GPS_LOG_TRC_SET_AGENT_LOGGING__enum,GPS_LOG_TRC_SET_AGENT_LOGGING_size

// GPS_LOG_TRC_SET_AGENT_LOGGING_RES
#define GPS_LOG_TRC_SET_AGENT_LOGGING_RES_size "d"
#define GPS_LOG_TRC_SET_AGENT_LOGGING_RES GPS_LOG_TRC_SET_AGENT_LOGGING_RES__enum,GPS_LOG_TRC_SET_AGENT_LOGGING_RES_size

// GPS_LOG_TRC_GET_SETTING
#define GPS_LOG_TRC_GET_SETTING_size "ƒd"
#define GPS_LOG_TRC_GET_SETTING GPS_LOG_TRC_GET_SETTING__enum,GPS_LOG_TRC_GET_SETTING_size

// GPS_LOG_TRC_GET_CATCHER_LOGGING
#define GPS_LOG_TRC_GET_CATCHER_LOGGING_size "d"
#define GPS_LOG_TRC_GET_CATCHER_LOGGING GPS_LOG_TRC_GET_CATCHER_LOGGING__enum,GPS_LOG_TRC_GET_CATCHER_LOGGING_size

// GPS_LOG_TRC_GET_FILE_LOGGING
#define GPS_LOG_TRC_GET_FILE_LOGGING_size "d"
#define GPS_LOG_TRC_GET_FILE_LOGGING GPS_LOG_TRC_GET_FILE_LOGGING__enum,GPS_LOG_TRC_GET_FILE_LOGGING_size

// GPS_LOG_TRC_GET_AGENT_LOGGING
#define GPS_LOG_TRC_GET_AGENT_LOGGING_size "d"
#define GPS_LOG_TRC_GET_AGENT_LOGGING GPS_LOG_TRC_GET_AGENT_LOGGING__enum,GPS_LOG_TRC_GET_AGENT_LOGGING_size

// GPS_LOG_TRC_OPEN_FILE_HANDLE
#define GPS_LOG_TRC_OPEN_FILE_HANDLE_size "d"
#define GPS_LOG_TRC_OPEN_FILE_HANDLE GPS_LOG_TRC_OPEN_FILE_HANDLE__enum,GPS_LOG_TRC_OPEN_FILE_HANDLE_size

// GPS_LOG_TRC_CLOSE_FILE_HANDLE
#define GPS_LOG_TRC_CLOSE_FILE_HANDLE_size "d"
#define GPS_LOG_TRC_CLOSE_FILE_HANDLE GPS_LOG_TRC_CLOSE_FILE_HANDLE__enum,GPS_LOG_TRC_CLOSE_FILE_HANDLE_size

// GPS_LOG_TRC_OPEN_FILE_ERROR
#define GPS_LOG_TRC_OPEN_FILE_ERROR_size "d"
#define GPS_LOG_TRC_OPEN_FILE_ERROR GPS_LOG_TRC_OPEN_FILE_ERROR__enum,GPS_LOG_TRC_OPEN_FILE_ERROR_size

// GPS_LOG_TRC_AGENT_WRITE_REQ
#define GPS_LOG_TRC_AGENT_WRITE_REQ_size "‚d"
#define GPS_LOG_TRC_AGENT_WRITE_REQ GPS_LOG_TRC_AGENT_WRITE_REQ__enum,GPS_LOG_TRC_AGENT_WRITE_REQ_size

// GPS_LOG_TRC_AGENT_WRITE_REQ_RET
#define GPS_LOG_TRC_AGENT_WRITE_REQ_RET_size "d"
#define GPS_LOG_TRC_AGENT_WRITE_REQ_RET GPS_LOG_TRC_AGENT_WRITE_REQ_RET__enum,GPS_LOG_TRC_AGENT_WRITE_REQ_RET_size

// GPS_LOG_TRC_SET_WORK_PORT
#define GPS_LOG_TRC_SET_WORK_PORT_size "d"
#define GPS_LOG_TRC_SET_WORK_PORT GPS_LOG_TRC_SET_WORK_PORT__enum,GPS_LOG_TRC_SET_WORK_PORT_size

// GPS_LOG_TRC_SET_AGENT_ENABLE
#define GPS_LOG_TRC_SET_AGENT_ENABLE_size NULL
#define GPS_LOG_TRC_SET_AGENT_ENABLE GPS_LOG_TRC_SET_AGENT_ENABLE__enum,GPS_LOG_TRC_SET_AGENT_ENABLE_size

// GPS_LOG_TRC_SET_AGENT_DISABLE
#define GPS_LOG_TRC_SET_AGENT_DISABLE_size NULL
#define GPS_LOG_TRC_SET_AGENT_DISABLE GPS_LOG_TRC_SET_AGENT_DISABLE__enum,GPS_LOG_TRC_SET_AGENT_DISABLE_size

// GPS_LOG_TRC_SET_CATCHER_ENABLE
#define GPS_LOG_TRC_SET_CATCHER_ENABLE_size NULL
#define GPS_LOG_TRC_SET_CATCHER_ENABLE GPS_LOG_TRC_SET_CATCHER_ENABLE__enum,GPS_LOG_TRC_SET_CATCHER_ENABLE_size

// GPS_LOG_TRC_SET_CATCHER_DISABLE
#define GPS_LOG_TRC_SET_CATCHER_DISABLE_size NULL
#define GPS_LOG_TRC_SET_CATCHER_DISABLE GPS_LOG_TRC_SET_CATCHER_DISABLE__enum,GPS_LOG_TRC_SET_CATCHER_DISABLE_size

// GPS_LOG_TRC_SET_FILE_ENABLE
#define GPS_LOG_TRC_SET_FILE_ENABLE_size NULL
#define GPS_LOG_TRC_SET_FILE_ENABLE GPS_LOG_TRC_SET_FILE_ENABLE__enum,GPS_LOG_TRC_SET_FILE_ENABLE_size

// GPS_LOG_TRC_SET_FILE_DISABLE
#define GPS_LOG_TRC_SET_FILE_DISABLE_size NULL
#define GPS_LOG_TRC_SET_FILE_DISABLE GPS_LOG_TRC_SET_FILE_DISABLE__enum,GPS_LOG_TRC_SET_FILE_DISABLE_size

// GPS_LOG_TRC_SET_DEBUG_ENABLE
#define GPS_LOG_TRC_SET_DEBUG_ENABLE_size NULL
#define GPS_LOG_TRC_SET_DEBUG_ENABLE GPS_LOG_TRC_SET_DEBUG_ENABLE__enum,GPS_LOG_TRC_SET_DEBUG_ENABLE_size

// GPS_LOG_TRC_SET_DEBUG_DISABLE
#define GPS_LOG_TRC_SET_DEBUG_DISABLE_size NULL
#define GPS_LOG_TRC_SET_DEBUG_DISABLE GPS_LOG_TRC_SET_DEBUG_DISABLE__enum,GPS_LOG_TRC_SET_DEBUG_DISABLE_size

// GPS_AGPS_TRC_P_RSP_FAILED
#define GPS_AGPS_TRC_P_RSP_FAILED_size NULL
#define GPS_AGPS_TRC_P_RSP_FAILED GPS_AGPS_TRC_P_RSP_FAILED__enum,GPS_AGPS_TRC_P_RSP_FAILED_size

// GPS_TIMER_TRC_TIMEOUT_ID
#define GPS_TIMER_TRC_TIMEOUT_ID_size "d"
#define GPS_TIMER_TRC_TIMEOUT_ID GPS_TIMER_TRC_TIMEOUT_ID__enum,GPS_TIMER_TRC_TIMEOUT_ID_size

// GPS_SLEEP_TRC_ENABLE_SLEEP
#define GPS_SLEEP_TRC_ENABLE_SLEEP_size "d"
#define GPS_SLEEP_TRC_ENABLE_SLEEP GPS_SLEEP_TRC_ENABLE_SLEEP__enum,GPS_SLEEP_TRC_ENABLE_SLEEP_size

// GPS_SLEEP_TRC_DISABLE_SLEEP
#define GPS_SLEEP_TRC_DISABLE_SLEEP_size "d"
#define GPS_SLEEP_TRC_DISABLE_SLEEP GPS_SLEEP_TRC_DISABLE_SLEEP__enum,GPS_SLEEP_TRC_DISABLE_SLEEP_size

// GPS_SLEEP_TRC_START_TIMER
#define GPS_SLEEP_TRC_START_TIMER_size "ƒd"
#define GPS_SLEEP_TRC_START_TIMER GPS_SLEEP_TRC_START_TIMER__enum,GPS_SLEEP_TRC_START_TIMER_size

// GPS_SLEEP_TRC_STOP_TIMER
#define GPS_SLEEP_TRC_STOP_TIMER_size "‚d"
#define GPS_SLEEP_TRC_STOP_TIMER GPS_SLEEP_TRC_STOP_TIMER__enum,GPS_SLEEP_TRC_STOP_TIMER_size

// GPS_SLEEP_TRC_UART_DATA
#define GPS_SLEEP_TRC_UART_DATA_size NULL
#define GPS_SLEEP_TRC_UART_DATA GPS_SLEEP_TRC_UART_DATA__enum,GPS_SLEEP_TRC_UART_DATA_size

// GPS_SLEEP_TRC_SEND_ACK
#define GPS_SLEEP_TRC_SEND_ACK_size NULL
#define GPS_SLEEP_TRC_SEND_ACK GPS_SLEEP_TRC_SEND_ACK__enum,GPS_SLEEP_TRC_SEND_ACK_size

// GPS_RTC_TRC_UTC_INVALID_TIME
#define GPS_RTC_TRC_UTC_INVALID_TIME_size NULL
#define GPS_RTC_TRC_UTC_INVALID_TIME GPS_RTC_TRC_UTC_INVALID_TIME__enum,GPS_RTC_TRC_UTC_INVALID_TIME_size

// GPS_RTC_TRC_FIRST_POWERON
#define GPS_RTC_TRC_FIRST_POWERON_size NULL
#define GPS_RTC_TRC_FIRST_POWERON GPS_RTC_TRC_FIRST_POWERON__enum,GPS_RTC_TRC_FIRST_POWERON_size

// GPS_RTC_TRC_CALIBRATE_RTC
#define GPS_RTC_TRC_CALIBRATE_RTC_size NULL
#define GPS_RTC_TRC_CALIBRATE_RTC GPS_RTC_TRC_CALIBRATE_RTC__enum,GPS_RTC_TRC_CALIBRATE_RTC_size

// GPS_RTC_TRC_ADJUST_RTC_DIFF
#define GPS_RTC_TRC_ADJUST_RTC_DIFF_size NULL
#define GPS_RTC_TRC_ADJUST_RTC_DIFF GPS_RTC_TRC_ADJUST_RTC_DIFF__enum,GPS_RTC_TRC_ADJUST_RTC_DIFF_size

// GPS_RTC_TRC_GSM_CURRENT_TIME
#define GPS_RTC_TRC_GSM_CURRENT_TIME_size "†d"
#define GPS_RTC_TRC_GSM_CURRENT_TIME GPS_RTC_TRC_GSM_CURRENT_TIME__enum,GPS_RTC_TRC_GSM_CURRENT_TIME_size

// GPS_RTC_TRC_GSM_CURRENT_GPS_TIME
#define GPS_RTC_TRC_GSM_CURRENT_GPS_TIME_size "‚d"
#define GPS_RTC_TRC_GSM_CURRENT_GPS_TIME GPS_RTC_TRC_GSM_CURRENT_GPS_TIME__enum,GPS_RTC_TRC_GSM_CURRENT_GPS_TIME_size

// GPS_RTC_TRC_GPS_CURRENT_TIME
#define GPS_RTC_TRC_GPS_CURRENT_TIME_size "†d"
#define GPS_RTC_TRC_GPS_CURRENT_TIME GPS_RTC_TRC_GPS_CURRENT_TIME__enum,GPS_RTC_TRC_GPS_CURRENT_TIME_size

// GPS_RTC_TRC_GPS_CURRENT_GPS_TIME
#define GPS_RTC_TRC_GPS_CURRENT_GPS_TIME_size "‚d"
#define GPS_RTC_TRC_GPS_CURRENT_GPS_TIME GPS_RTC_TRC_GPS_CURRENT_GPS_TIME__enum,GPS_RTC_TRC_GPS_CURRENT_GPS_TIME_size

// GPS_RTC_TRC_DIFF_CURRENT_GPS_TIME
#define GPS_RTC_TRC_DIFF_CURRENT_GPS_TIME_size "‚d"
#define GPS_RTC_TRC_DIFF_CURRENT_GPS_TIME GPS_RTC_TRC_DIFF_CURRENT_GPS_TIME__enum,GPS_RTC_TRC_DIFF_CURRENT_GPS_TIME_size

// GPS_UTC_TRC_AGE_TOW_RANGE
#define GPS_UTC_TRC_AGE_TOW_RANGE_size NULL
#define GPS_UTC_TRC_AGE_TOW_RANGE GPS_UTC_TRC_AGE_TOW_RANGE__enum,GPS_UTC_TRC_AGE_TOW_RANGE_size

// GPS_UTC_TRC_CALIBRATE_CLOCK_DRIFT_FAIL
#define GPS_UTC_TRC_CALIBRATE_CLOCK_DRIFT_FAIL_size NULL
#define GPS_UTC_TRC_CALIBRATE_CLOCK_DRIFT_FAIL GPS_UTC_TRC_CALIBRATE_CLOCK_DRIFT_FAIL__enum,GPS_UTC_TRC_CALIBRATE_CLOCK_DRIFT_FAIL_size

// GPS_UTC_TRC_GPS_CLOCK_DRIFT
#define GPS_UTC_TRC_GPS_CLOCK_DRIFT_size "‚d"
#define GPS_UTC_TRC_GPS_CLOCK_DRIFT GPS_UTC_TRC_GPS_CLOCK_DRIFT__enum,GPS_UTC_TRC_GPS_CLOCK_DRIFT_size

// GPS_RTC_TRC_PREVIOUS_RTC
#define GPS_RTC_TRC_PREVIOUS_RTC_size "†d"
#define GPS_RTC_TRC_PREVIOUS_RTC GPS_RTC_TRC_PREVIOUS_RTC__enum,GPS_RTC_TRC_PREVIOUS_RTC_size

// GPS_RTC_TRC_NEW_RTC
#define GPS_RTC_TRC_NEW_RTC_size "†d"
#define GPS_RTC_TRC_NEW_RTC GPS_RTC_TRC_NEW_RTC__enum,GPS_RTC_TRC_NEW_RTC_size

// GPS_TRC_MNL_HW_CHECK_SIZE
#define GPS_TRC_MNL_HW_CHECK_SIZE_size "d"
#define GPS_TRC_MNL_HW_CHECK_SIZE GPS_TRC_MNL_HW_CHECK_SIZE__enum,GPS_TRC_MNL_HW_CHECK_SIZE_size

// GPS_TRC_MNL_HW_CHECK_DATA
#define GPS_TRC_MNL_HW_CHECK_DATA_size "d"
#define GPS_TRC_MNL_HW_CHECK_DATA GPS_TRC_MNL_HW_CHECK_DATA__enum,GPS_TRC_MNL_HW_CHECK_DATA_size

// GPS_TRC_MNL_HW_CHECK_OK
#define GPS_TRC_MNL_HW_CHECK_OK_size NULL
#define GPS_TRC_MNL_HW_CHECK_OK GPS_TRC_MNL_HW_CHECK_OK__enum,GPS_TRC_MNL_HW_CHECK_OK_size

// GPS_TRC_MNL_HW_CHECK_FAIL
#define GPS_TRC_MNL_HW_CHECK_FAIL_size NULL
#define GPS_TRC_MNL_HW_CHECK_FAIL GPS_TRC_MNL_HW_CHECK_FAIL__enum,GPS_TRC_MNL_HW_CHECK_FAIL_size

// GPS_TRC_MNL_HW_CHECK_32K_CLOCK
#define GPS_TRC_MNL_HW_CHECK_32K_CLOCK_size "‚d"
#define GPS_TRC_MNL_HW_CHECK_32K_CLOCK GPS_TRC_MNL_HW_CHECK_32K_CLOCK__enum,GPS_TRC_MNL_HW_CHECK_32K_CLOCK_size

// GPS_TRC_MNL_HW_CHECK_POWER_PIN
#define GPS_TRC_MNL_HW_CHECK_POWER_PIN_size "‚d"
#define GPS_TRC_MNL_HW_CHECK_POWER_PIN GPS_TRC_MNL_HW_CHECK_POWER_PIN__enum,GPS_TRC_MNL_HW_CHECK_POWER_PIN_size

// GPS_TRC_MNL_HW_CHECK_RXD_PIN
#define GPS_TRC_MNL_HW_CHECK_RXD_PIN_size "‚d"
#define GPS_TRC_MNL_HW_CHECK_RXD_PIN GPS_TRC_MNL_HW_CHECK_RXD_PIN__enum,GPS_TRC_MNL_HW_CHECK_RXD_PIN_size

// GPS_TRC_MNL_HW_CHECK_TXD_PIN
#define GPS_TRC_MNL_HW_CHECK_TXD_PIN_size "‚d"
#define GPS_TRC_MNL_HW_CHECK_TXD_PIN GPS_TRC_MNL_HW_CHECK_TXD_PIN__enum,GPS_TRC_MNL_HW_CHECK_TXD_PIN_size

// GPS_TRC_MNL_HW_CHECK_EINT_PIN
#define GPS_TRC_MNL_HW_CHECK_EINT_PIN_size "‚d"
#define GPS_TRC_MNL_HW_CHECK_EINT_PIN GPS_TRC_MNL_HW_CHECK_EINT_PIN__enum,GPS_TRC_MNL_HW_CHECK_EINT_PIN_size

// GPS_TRC_MNL_INIT_GPS_STATUS
#define GPS_TRC_MNL_INIT_GPS_STATUS_size "d"
#define GPS_TRC_MNL_INIT_GPS_STATUS GPS_TRC_MNL_INIT_GPS_STATUS__enum,GPS_TRC_MNL_INIT_GPS_STATUS_size

// GPS_TRC_MNL_INIT
#define GPS_TRC_MNL_INIT_size NULL
#define GPS_TRC_MNL_INIT GPS_TRC_MNL_INIT__enum,GPS_TRC_MNL_INIT_size

// GPS_TRC_READ_GPS_DSP_BIN_SECCUSS
#define GPS_TRC_READ_GPS_DSP_BIN_SECCUSS_size NULL
#define GPS_TRC_READ_GPS_DSP_BIN_SECCUSS GPS_TRC_READ_GPS_DSP_BIN_SECCUSS__enum,GPS_TRC_READ_GPS_DSP_BIN_SECCUSS_size

// GPS_TRC_READ_GPS_DSP_BIN_FAIL
#define GPS_TRC_READ_GPS_DSP_BIN_FAIL_size NULL
#define GPS_TRC_READ_GPS_DSP_BIN_FAIL GPS_TRC_READ_GPS_DSP_BIN_FAIL__enum,GPS_TRC_READ_GPS_DSP_BIN_FAIL_size

// GPS_TRC_MNL_INIT_OK
#define GPS_TRC_MNL_INIT_OK_size NULL
#define GPS_TRC_MNL_INIT_OK GPS_TRC_MNL_INIT_OK__enum,GPS_TRC_MNL_INIT_OK_size

// GPS_TRC_MNL_INIT_FAIL
#define GPS_TRC_MNL_INIT_FAIL_size NULL
#define GPS_TRC_MNL_INIT_FAIL GPS_TRC_MNL_INIT_FAIL__enum,GPS_TRC_MNL_INIT_FAIL_size

// GPS_TRC_MNL_SHUTDOWN_GPS_STATUS
#define GPS_TRC_MNL_SHUTDOWN_GPS_STATUS_size "d"
#define GPS_TRC_MNL_SHUTDOWN_GPS_STATUS GPS_TRC_MNL_SHUTDOWN_GPS_STATUS__enum,GPS_TRC_MNL_SHUTDOWN_GPS_STATUS_size

// GPS_TRC_MNL_SHUTDOWN
#define GPS_TRC_MNL_SHUTDOWN_size NULL
#define GPS_TRC_MNL_SHUTDOWN GPS_TRC_MNL_SHUTDOWN__enum,GPS_TRC_MNL_SHUTDOWN_size

// GPS_TRC_GPS_STOP_TIMER
#define GPS_TRC_GPS_STOP_TIMER_size NULL
#define GPS_TRC_GPS_STOP_TIMER GPS_TRC_GPS_STOP_TIMER__enum,GPS_TRC_GPS_STOP_TIMER_size

// GPS_INJECT_CMD_TRC_UART_BAUDRATE_SETTING_INVALID
#define GPS_INJECT_CMD_TRC_UART_BAUDRATE_SETTING_INVALID_size NULL
#define GPS_INJECT_CMD_TRC_UART_BAUDRATE_SETTING_INVALID GPS_INJECT_CMD_TRC_UART_BAUDRATE_SETTING_INVALID__enum,GPS_INJECT_CMD_TRC_UART_BAUDRATE_SETTING_INVALID_size

// GPS_INJECT_CMD_TRC_GPS_OPEN_NOTIFY
#define GPS_INJECT_CMD_TRC_GPS_OPEN_NOTIFY_size NULL
#define GPS_INJECT_CMD_TRC_GPS_OPEN_NOTIFY GPS_INJECT_CMD_TRC_GPS_OPEN_NOTIFY__enum,GPS_INJECT_CMD_TRC_GPS_OPEN_NOTIFY_size

// GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_OPEN_GPS
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_OPEN_GPS_size "d"
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_OPEN_GPS GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_OPEN_GPS__enum,GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_OPEN_GPS_size

// GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_CLOSE_GPS
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_CLOSE_GPS_size "d"
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_CLOSE_GPS GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_CLOSE_GPS__enum,GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_CLOSE_GPS_size

// GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_COUNT
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_COUNT_size "ƒd"
#define GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_COUNT GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_COUNT__enum,GPS_INJECT_CMD_TRC_GPS_POWER_ON_OFF_COUNT_size

// GPS_TRC_GPS_ENTER_POWER_SAVEING_MODE
#define GPS_TRC_GPS_ENTER_POWER_SAVEING_MODE_size NULL
#define GPS_TRC_GPS_ENTER_POWER_SAVEING_MODE GPS_TRC_GPS_ENTER_POWER_SAVEING_MODE__enum,GPS_TRC_GPS_ENTER_POWER_SAVEING_MODE_size

// GPS_TRC_GPS_ENTER_NORMAL_FIX_MODE
#define GPS_TRC_GPS_ENTER_NORMAL_FIX_MODE_size NULL
#define GPS_TRC_GPS_ENTER_NORMAL_FIX_MODE GPS_TRC_GPS_ENTER_NORMAL_FIX_MODE__enum,GPS_TRC_GPS_ENTER_NORMAL_FIX_MODE_size

// GPS_TRC_GPS_NORMAL_FIX_COUNT
#define GPS_TRC_GPS_NORMAL_FIX_COUNT_size "d"
#define GPS_TRC_GPS_NORMAL_FIX_COUNT GPS_TRC_GPS_NORMAL_FIX_COUNT__enum,GPS_TRC_GPS_NORMAL_FIX_COUNT_size

// GPS_TRC_GPS_NO_FIX_COUNT
#define GPS_TRC_GPS_NO_FIX_COUNT_size "d"
#define GPS_TRC_GPS_NO_FIX_COUNT GPS_TRC_GPS_NO_FIX_COUNT__enum,GPS_TRC_GPS_NO_FIX_COUNT_size

// GPS_TRC_GPS_SPEED_LOW_NORMAL_FIX_COUNT
#define GPS_TRC_GPS_SPEED_LOW_NORMAL_FIX_COUNT_size "d"
#define GPS_TRC_GPS_SPEED_LOW_NORMAL_FIX_COUNT GPS_TRC_GPS_SPEED_LOW_NORMAL_FIX_COUNT__enum,GPS_TRC_GPS_SPEED_LOW_NORMAL_FIX_COUNT_size

// GPS_TRC_GPS_SPEED_HIGHNORMAL_FIX_COUNT
#define GPS_TRC_GPS_SPEED_HIGHNORMAL_FIX_COUNT_size "d"
#define GPS_TRC_GPS_SPEED_HIGHNORMAL_FIX_COUNT GPS_TRC_GPS_SPEED_HIGHNORMAL_FIX_COUNT__enum,GPS_TRC_GPS_SPEED_HIGHNORMAL_FIX_COUNT_size

// GPS_TRC_IS_GSM_GPS_REF_TIME_NEEDED
#define GPS_TRC_IS_GSM_GPS_REF_TIME_NEEDED_size "d"
#define GPS_TRC_IS_GSM_GPS_REF_TIME_NEEDED GPS_TRC_IS_GSM_GPS_REF_TIME_NEEDED__enum,GPS_TRC_IS_GSM_GPS_REF_TIME_NEEDED_size

// GPS_TRC_IS_UTRAN_GPS_REF_TIME_NEEDED
#define GPS_TRC_IS_UTRAN_GPS_REF_TIME_NEEDED_size "d"
#define GPS_TRC_IS_UTRAN_GPS_REF_TIME_NEEDED GPS_TRC_IS_UTRAN_GPS_REF_TIME_NEEDED__enum,GPS_TRC_IS_UTRAN_GPS_REF_TIME_NEEDED_size

// GPS_PARSER_TRC_NMEA_CRC_CHECK_FAILD
#define GPS_PARSER_TRC_NMEA_CRC_CHECK_FAILD_size "s"
#define GPS_PARSER_TRC_NMEA_CRC_CHECK_FAILD GPS_PARSER_TRC_NMEA_CRC_CHECK_FAILD__enum,GPS_PARSER_TRC_NMEA_CRC_CHECK_FAILD_size

// GPS_INJECT_TRC_OPERATE_AND_CMD
#define GPS_INJECT_TRC_OPERATE_AND_CMD_size "ƒd"
#define GPS_INJECT_TRC_OPERATE_AND_CMD GPS_INJECT_TRC_OPERATE_AND_CMD__enum,GPS_INJECT_TRC_OPERATE_AND_CMD_size

// GPS_META_TRC_OP_TYPE
#define GPS_META_TRC_OP_TYPE_size "d"
#define GPS_META_TRC_OP_TYPE GPS_META_TRC_OP_TYPE__enum,GPS_META_TRC_OP_TYPE_size

// GPS_META_TRC_INALID_OP_TYPE
#define GPS_META_TRC_INALID_OP_TYPE_size "d"
#define GPS_META_TRC_INALID_OP_TYPE GPS_META_TRC_INALID_OP_TYPE__enum,GPS_META_TRC_INALID_OP_TYPE_size

// GPS_META_TRC_GPS_HAS_NOT_START_YET
#define GPS_META_TRC_GPS_HAS_NOT_START_YET_size NULL
#define GPS_META_TRC_GPS_HAS_NOT_START_YET GPS_META_TRC_GPS_HAS_NOT_START_YET__enum,GPS_META_TRC_GPS_HAS_NOT_START_YET_size

// GPS_META_TRC_INVALID_SV_ID
#define GPS_META_TRC_INVALID_SV_ID_size "d"
#define GPS_META_TRC_INVALID_SV_ID GPS_META_TRC_INVALID_SV_ID__enum,GPS_META_TRC_INVALID_SV_ID_size

// GPS_META_TRC_INVALID_CMD_BITMAP
#define GPS_META_TRC_INVALID_CMD_BITMAP_size "d"
#define GPS_META_TRC_INVALID_CMD_BITMAP GPS_META_TRC_INVALID_CMD_BITMAP__enum,GPS_META_TRC_INVALID_CMD_BITMAP_size

// GPS_META_TRC_QUERY_BITMAP_MASK
#define GPS_META_TRC_QUERY_BITMAP_MASK_size "d"
#define GPS_META_TRC_QUERY_BITMAP_MASK GPS_META_TRC_QUERY_BITMAP_MASK__enum,GPS_META_TRC_QUERY_BITMAP_MASK_size

// GPS_META_TRC_GPS_CLOSE
#define GPS_META_TRC_GPS_CLOSE_size NULL
#define GPS_META_TRC_GPS_CLOSE GPS_META_TRC_GPS_CLOSE__enum,GPS_META_TRC_GPS_CLOSE_size

// GPS_MNL_TRC_GPS_RECEIVED_INIT_REP_FROM_MNL
#define GPS_MNL_TRC_GPS_RECEIVED_INIT_REP_FROM_MNL_size NULL
#define GPS_MNL_TRC_GPS_RECEIVED_INIT_REP_FROM_MNL GPS_MNL_TRC_GPS_RECEIVED_INIT_REP_FROM_MNL__enum,GPS_MNL_TRC_GPS_RECEIVED_INIT_REP_FROM_MNL_size

// GPS_META_TRC_IS_GPS_INIT_OK
#define GPS_META_TRC_IS_GPS_INIT_OK_size "d"
#define GPS_META_TRC_IS_GPS_INIT_OK GPS_META_TRC_IS_GPS_INIT_OK__enum,GPS_META_TRC_IS_GPS_INIT_OK_size

// GPS_META_TRC_MP_TEST_SIGNAL
#define GPS_META_TRC_MP_TEST_SIGNAL_size "‡d"
#define GPS_META_TRC_MP_TEST_SIGNAL GPS_META_TRC_MP_TEST_SIGNAL__enum,GPS_META_TRC_MP_TEST_SIGNAL_size

// GPS_META_TRC_MP_TEST_BITSYNC
#define GPS_META_TRC_MP_TEST_BITSYNC_size "‚d"
#define GPS_META_TRC_MP_TEST_BITSYNC GPS_META_TRC_MP_TEST_BITSYNC__enum,GPS_META_TRC_MP_TEST_BITSYNC_size

// GPS_META_TRC_MP_TEST_ACQ
#define GPS_META_TRC_MP_TEST_ACQ_size "‚d"
#define GPS_META_TRC_MP_TEST_ACQ GPS_META_TRC_MP_TEST_ACQ__enum,GPS_META_TRC_MP_TEST_ACQ_size

// GPS_META_TRC_MP_TEST_FIX_CTRL
#define GPS_META_TRC_MP_TEST_FIX_CTRL_size "…d"
#define GPS_META_TRC_MP_TEST_FIX_CTRL GPS_META_TRC_MP_TEST_FIX_CTRL__enum,GPS_META_TRC_MP_TEST_FIX_CTRL_size

// GPS_META_TRC_MP_TEST_FINISHED
#define GPS_META_TRC_MP_TEST_FINISHED_size NULL
#define GPS_META_TRC_MP_TEST_FINISHED GPS_META_TRC_MP_TEST_FINISHED__enum,GPS_META_TRC_MP_TEST_FINISHED_size

// GPS_META_TRC_UNPROCESSED_CMD
#define GPS_META_TRC_UNPROCESSED_CMD_size "d"
#define GPS_META_TRC_UNPROCESSED_CMD GPS_META_TRC_UNPROCESSED_CMD__enum,GPS_META_TRC_UNPROCESSED_CMD_size

// GPS_TRC_INF_UART_INIT_FIN
#define GPS_TRC_INF_UART_INIT_FIN_size NULL
#define GPS_TRC_INF_UART_INIT_FIN GPS_TRC_INF_UART_INIT_FIN__enum,GPS_TRC_INF_UART_INIT_FIN_size

// GPS_TRC_INF_UART_RESET_FIN
#define GPS_TRC_INF_UART_RESET_FIN_size NULL
#define GPS_TRC_INF_UART_RESET_FIN GPS_TRC_INF_UART_RESET_FIN__enum,GPS_TRC_INF_UART_RESET_FIN_size

// GPS_TRC_INF_UART_OPEN_NEW
#define GPS_TRC_INF_UART_OPEN_NEW_size "‚d"
#define GPS_TRC_INF_UART_OPEN_NEW GPS_TRC_INF_UART_OPEN_NEW__enum,GPS_TRC_INF_UART_OPEN_NEW_size

// GPS_TRC_INF_UART_OPEN_NEW_MODU
#define GPS_TRC_INF_UART_OPEN_NEW_MODU_size "‚d"
#define GPS_TRC_INF_UART_OPEN_NEW_MODU GPS_TRC_INF_UART_OPEN_NEW_MODU__enum,GPS_TRC_INF_UART_OPEN_NEW_MODU_size

// GPS_TRC_INF_UART_OPEN_SET_MODE
#define GPS_TRC_INF_UART_OPEN_SET_MODE_size "‚d"
#define GPS_TRC_INF_UART_OPEN_SET_MODE GPS_TRC_INF_UART_OPEN_SET_MODE__enum,GPS_TRC_INF_UART_OPEN_SET_MODE_size

// GPS_TRC_WRN_UART_OPEN_NO_SLOT
#define GPS_TRC_WRN_UART_OPEN_NO_SLOT_size "d"
#define GPS_TRC_WRN_UART_OPEN_NO_SLOT GPS_TRC_WRN_UART_OPEN_NO_SLOT__enum,GPS_TRC_WRN_UART_OPEN_NO_SLOT_size

// GPS_TRC_WRN_UART_OPEN_SEND_ERR_PORT
#define GPS_TRC_WRN_UART_OPEN_SEND_ERR_PORT_size "‚d"
#define GPS_TRC_WRN_UART_OPEN_SEND_ERR_PORT GPS_TRC_WRN_UART_OPEN_SEND_ERR_PORT__enum,GPS_TRC_WRN_UART_OPEN_SEND_ERR_PORT_size

// GPS_TRC_WRN_UART_OPEN_INIT_ERR_PORT
#define GPS_TRC_WRN_UART_OPEN_INIT_ERR_PORT_size "d"
#define GPS_TRC_WRN_UART_OPEN_INIT_ERR_PORT GPS_TRC_WRN_UART_OPEN_INIT_ERR_PORT__enum,GPS_TRC_WRN_UART_OPEN_INIT_ERR_PORT_size

// GPS_TRC_INF_UART_CLOSE_CLR_MODE
#define GPS_TRC_INF_UART_CLOSE_CLR_MODE_size "‚d"
#define GPS_TRC_INF_UART_CLOSE_CLR_MODE GPS_TRC_INF_UART_CLOSE_CLR_MODE__enum,GPS_TRC_INF_UART_CLOSE_CLR_MODE_size

// GPS_TRC_INF_UART_CLOSE_DEL_MODU
#define GPS_TRC_INF_UART_CLOSE_DEL_MODU_size "‚d"
#define GPS_TRC_INF_UART_CLOSE_DEL_MODU GPS_TRC_INF_UART_CLOSE_DEL_MODU__enum,GPS_TRC_INF_UART_CLOSE_DEL_MODU_size

// GPS_TRC_INF_UART_CLOSE_ALL
#define GPS_TRC_INF_UART_CLOSE_ALL_size NULL
#define GPS_TRC_INF_UART_CLOSE_ALL GPS_TRC_INF_UART_CLOSE_ALL__enum,GPS_TRC_INF_UART_CLOSE_ALL_size

// GPS_TRC_WRN_UART_CLOSE_SEND_ERR_PORT
#define GPS_TRC_WRN_UART_CLOSE_SEND_ERR_PORT_size "ƒd"
#define GPS_TRC_WRN_UART_CLOSE_SEND_ERR_PORT GPS_TRC_WRN_UART_CLOSE_SEND_ERR_PORT__enum,GPS_TRC_WRN_UART_CLOSE_SEND_ERR_PORT_size

// GPS_TRC_WRN_UART_CLOSE_CNTX_ERR_PORT
#define GPS_TRC_WRN_UART_CLOSE_CNTX_ERR_PORT_size "d"
#define GPS_TRC_WRN_UART_CLOSE_CNTX_ERR_PORT GPS_TRC_WRN_UART_CLOSE_CNTX_ERR_PORT__enum,GPS_TRC_WRN_UART_CLOSE_CNTX_ERR_PORT_size

// GPS_TRC_WRN_UART_WRITE_SEND_ERR_PORT
#define GPS_TRC_WRN_UART_WRITE_SEND_ERR_PORT_size "‚d"
#define GPS_TRC_WRN_UART_WRITE_SEND_ERR_PORT GPS_TRC_WRN_UART_WRITE_SEND_ERR_PORT__enum,GPS_TRC_WRN_UART_WRITE_SEND_ERR_PORT_size

// GPS_TRC_INF_UART_WRITE_CMD
#define GPS_TRC_INF_UART_WRITE_CMD_size "‚d"
#define GPS_TRC_INF_UART_WRITE_CMD GPS_TRC_INF_UART_WRITE_CMD__enum,GPS_TRC_INF_UART_WRITE_CMD_size

// GPS_TRC_WRN_UART_READ_SEND_ERR_PORT
#define GPS_TRC_WRN_UART_READ_SEND_ERR_PORT_size "‚d"
#define GPS_TRC_WRN_UART_READ_SEND_ERR_PORT GPS_TRC_WRN_UART_READ_SEND_ERR_PORT__enum,GPS_TRC_WRN_UART_READ_SEND_ERR_PORT_size

// GPS_TRC_WRN_UART_READ_LOSE_DBG
#define GPS_TRC_WRN_UART_READ_LOSE_DBG_size "d"
#define GPS_TRC_WRN_UART_READ_LOSE_DBG GPS_TRC_WRN_UART_READ_LOSE_DBG__enum,GPS_TRC_WRN_UART_READ_LOSE_DBG_size

// GPS_TRC_INF_UART_NMEA_GET_FIXED
#define GPS_TRC_INF_UART_NMEA_GET_FIXED_size NULL
#define GPS_TRC_INF_UART_NMEA_GET_FIXED GPS_TRC_INF_UART_NMEA_GET_FIXED__enum,GPS_TRC_INF_UART_NMEA_GET_FIXED_size

// GPS_TRC_WRN_UART_NMEA_CHK_ERR
#define GPS_TRC_WRN_UART_NMEA_CHK_ERR_size NULL
#define GPS_TRC_WRN_UART_NMEA_CHK_ERR GPS_TRC_WRN_UART_NMEA_CHK_ERR__enum,GPS_TRC_WRN_UART_NMEA_CHK_ERR_size

// GPS_TRC_WRN_UART_NMEA_PMTK_RESP
#define GPS_TRC_WRN_UART_NMEA_PMTK_RESP_size "‚d"
#define GPS_TRC_WRN_UART_NMEA_PMTK_RESP GPS_TRC_WRN_UART_NMEA_PMTK_RESP__enum,GPS_TRC_WRN_UART_NMEA_PMTK_RESP_size

// GPS_TRC_EER_UART_NMEA_BUF_OVERFLOW
#define GPS_TRC_EER_UART_NMEA_BUF_OVERFLOW_size NULL
#define GPS_TRC_EER_UART_NMEA_BUF_OVERFLOW GPS_TRC_EER_UART_NMEA_BUF_OVERFLOW__enum,GPS_TRC_EER_UART_NMEA_BUF_OVERFLOW_size

// GPS_TRC_WRN_FILE_GET_DRIVE_FAIL
#define GPS_TRC_WRN_FILE_GET_DRIVE_FAIL_size NULL
#define GPS_TRC_WRN_FILE_GET_DRIVE_FAIL GPS_TRC_WRN_FILE_GET_DRIVE_FAIL__enum,GPS_TRC_WRN_FILE_GET_DRIVE_FAIL_size

// GPS_TRC_WRN_FILE_PRE_ALLOC_FAIL
#define GPS_TRC_WRN_FILE_PRE_ALLOC_FAIL_size NULL
#define GPS_TRC_WRN_FILE_PRE_ALLOC_FAIL GPS_TRC_WRN_FILE_PRE_ALLOC_FAIL__enum,GPS_TRC_WRN_FILE_PRE_ALLOC_FAIL_size

// GPS_TRC_WRN_FILE_WRITE_DBG_FAIL
#define GPS_TRC_WRN_FILE_WRITE_DBG_FAIL_size NULL
#define GPS_TRC_WRN_FILE_WRITE_DBG_FAIL GPS_TRC_WRN_FILE_WRITE_DBG_FAIL__enum,GPS_TRC_WRN_FILE_WRITE_DBG_FAIL_size

// GPS_TRC_WRN_FILE_WRITE_NMA_FAIL
#define GPS_TRC_WRN_FILE_WRITE_NMA_FAIL_size NULL
#define GPS_TRC_WRN_FILE_WRITE_NMA_FAIL GPS_TRC_WRN_FILE_WRITE_NMA_FAIL__enum,GPS_TRC_WRN_FILE_WRITE_NMA_FAIL_size

// GPS_TRC_INF_FILE_OPEN_DBG
#define GPS_TRC_INF_FILE_OPEN_DBG_size "‚d"
#define GPS_TRC_INF_FILE_OPEN_DBG GPS_TRC_INF_FILE_OPEN_DBG__enum,GPS_TRC_INF_FILE_OPEN_DBG_size

// GPS_TRC_INF_FILE_OPEN_NMA
#define GPS_TRC_INF_FILE_OPEN_NMA_size "‚d"
#define GPS_TRC_INF_FILE_OPEN_NMA GPS_TRC_INF_FILE_OPEN_NMA__enum,GPS_TRC_INF_FILE_OPEN_NMA_size

// GPS_TRC_INF_FILE_CLOSE_DBG
#define GPS_TRC_INF_FILE_CLOSE_DBG_size "d"
#define GPS_TRC_INF_FILE_CLOSE_DBG GPS_TRC_INF_FILE_CLOSE_DBG__enum,GPS_TRC_INF_FILE_CLOSE_DBG_size

// GPS_TRC_INF_FILE_CLOSE_NMA
#define GPS_TRC_INF_FILE_CLOSE_NMA_size "d"
#define GPS_TRC_INF_FILE_CLOSE_NMA GPS_TRC_INF_FILE_CLOSE_NMA__enum,GPS_TRC_INF_FILE_CLOSE_NMA_size

// GPS_TRC_INF_POWER_NOT_1ST_ON
#define GPS_TRC_INF_POWER_NOT_1ST_ON_size NULL
#define GPS_TRC_INF_POWER_NOT_1ST_ON GPS_TRC_INF_POWER_NOT_1ST_ON__enum,GPS_TRC_INF_POWER_NOT_1ST_ON_size

// GPS_TRC_INF_POWER_ALREADY_ON
#define GPS_TRC_INF_POWER_ALREADY_ON_size NULL
#define GPS_TRC_INF_POWER_ALREADY_ON GPS_TRC_INF_POWER_ALREADY_ON__enum,GPS_TRC_INF_POWER_ALREADY_ON_size

// GPS_TRC_INF_POWER_ALREADY_OFF
#define GPS_TRC_INF_POWER_ALREADY_OFF_size NULL
#define GPS_TRC_INF_POWER_ALREADY_OFF GPS_TRC_INF_POWER_ALREADY_OFF__enum,GPS_TRC_INF_POWER_ALREADY_OFF_size

// GPS_TRC_INF_POWER_EINT_INIT_OK
#define GPS_TRC_INF_POWER_EINT_INIT_OK_size "‚d"
#define GPS_TRC_INF_POWER_EINT_INIT_OK GPS_TRC_INF_POWER_EINT_INIT_OK__enum,GPS_TRC_INF_POWER_EINT_INIT_OK_size

// GPS_TRC_INF_POWER_SET_BAUD
#define GPS_TRC_INF_POWER_SET_BAUD_size "d"
#define GPS_TRC_INF_POWER_SET_BAUD GPS_TRC_INF_POWER_SET_BAUD__enum,GPS_TRC_INF_POWER_SET_BAUD_size

// GPS_TRC_INF_FILE_OPEN_DSP
#define GPS_TRC_INF_FILE_OPEN_DSP_size "c‚d"
#define GPS_TRC_INF_FILE_OPEN_DSP GPS_TRC_INF_FILE_OPEN_DSP__enum,GPS_TRC_INF_FILE_OPEN_DSP_size

// GPS_TRC_WRN_FILE_GET_DRIVER_FAIL
#define GPS_TRC_WRN_FILE_GET_DRIVER_FAIL_size NULL
#define GPS_TRC_WRN_FILE_GET_DRIVER_FAIL GPS_TRC_WRN_FILE_GET_DRIVER_FAIL__enum,GPS_TRC_WRN_FILE_GET_DRIVER_FAIL_size

// GPS_TRC_ERR_POWER_EINT_PIN_NUM
#define GPS_TRC_ERR_POWER_EINT_PIN_NUM_size NULL
#define GPS_TRC_ERR_POWER_EINT_PIN_NUM GPS_TRC_ERR_POWER_EINT_PIN_NUM__enum,GPS_TRC_ERR_POWER_EINT_PIN_NUM_size

// GPS_TRC_ERR_POWER_GPIO_PIN_NUM
#define GPS_TRC_ERR_POWER_GPIO_PIN_NUM_size NULL
#define GPS_TRC_ERR_POWER_GPIO_PIN_NUM GPS_TRC_ERR_POWER_GPIO_PIN_NUM__enum,GPS_TRC_ERR_POWER_GPIO_PIN_NUM_size

// GPS_TRC_ERR_POWER_MNL_INIT_FAIL
#define GPS_TRC_ERR_POWER_MNL_INIT_FAIL_size NULL
#define GPS_TRC_ERR_POWER_MNL_INIT_FAIL GPS_TRC_ERR_POWER_MNL_INIT_FAIL__enum,GPS_TRC_ERR_POWER_MNL_INIT_FAIL_size

// GPS_TRC_INF_RTC_REGISTER
#define GPS_TRC_INF_RTC_REGISTER_size "d"
#define GPS_TRC_INF_RTC_REGISTER GPS_TRC_INF_RTC_REGISTER__enum,GPS_TRC_INF_RTC_REGISTER_size

// GPS_TRC_INF_NVRAM_WRITE_REQ
#define GPS_TRC_INF_NVRAM_WRITE_REQ_size NULL
#define GPS_TRC_INF_NVRAM_WRITE_REQ GPS_TRC_INF_NVRAM_WRITE_REQ__enum,GPS_TRC_INF_NVRAM_WRITE_REQ_size

// GPS_TRC_INF_NVRAM_WRITE_CNF_OK
#define GPS_TRC_INF_NVRAM_WRITE_CNF_OK_size NULL
#define GPS_TRC_INF_NVRAM_WRITE_CNF_OK GPS_TRC_INF_NVRAM_WRITE_CNF_OK__enum,GPS_TRC_INF_NVRAM_WRITE_CNF_OK_size

// GPS_TRC_WRN_NVRAM_WRITE_CNF_ERR
#define GPS_TRC_WRN_NVRAM_WRITE_CNF_ERR_size NULL
#define GPS_TRC_WRN_NVRAM_WRITE_CNF_ERR GPS_TRC_WRN_NVRAM_WRITE_CNF_ERR__enum,GPS_TRC_WRN_NVRAM_WRITE_CNF_ERR_size

// GPS_TRC_INF_SLEEP_AUTO_POWER_SAVING
#define GPS_TRC_INF_SLEEP_AUTO_POWER_SAVING_size "d"
#define GPS_TRC_INF_SLEEP_AUTO_POWER_SAVING GPS_TRC_INF_SLEEP_AUTO_POWER_SAVING__enum,GPS_TRC_INF_SLEEP_AUTO_POWER_SAVING_size

// GPS_TRC_INF_SLEEP_START_WAKEUP_TIMER
#define GPS_TRC_INF_SLEEP_START_WAKEUP_TIMER_size "‚d"
#define GPS_TRC_INF_SLEEP_START_WAKEUP_TIMER GPS_TRC_INF_SLEEP_START_WAKEUP_TIMER__enum,GPS_TRC_INF_SLEEP_START_WAKEUP_TIMER_size

// GPS_TRC_INF_STATE_CHANGE_MNL_DEBUG
#define GPS_TRC_INF_STATE_CHANGE_MNL_DEBUG_size "‚d"
#define GPS_TRC_INF_STATE_CHANGE_MNL_DEBUG GPS_TRC_INF_STATE_CHANGE_MNL_DEBUG__enum,GPS_TRC_INF_STATE_CHANGE_MNL_DEBUG_size

// GPS_TRC_INF_STATE_CHANGE_SlEEP_FLAG
#define GPS_TRC_INF_STATE_CHANGE_SlEEP_FLAG_size "‚d"
#define GPS_TRC_INF_STATE_CHANGE_SlEEP_FLAG GPS_TRC_INF_STATE_CHANGE_SlEEP_FLAG__enum,GPS_TRC_INF_STATE_CHANGE_SlEEP_FLAG_size

// GPS_TRC_INF_STATE_CHANGE_POWER_FLAG
#define GPS_TRC_INF_STATE_CHANGE_POWER_FLAG_size "‚d"
#define GPS_TRC_INF_STATE_CHANGE_POWER_FLAG GPS_TRC_INF_STATE_CHANGE_POWER_FLAG__enum,GPS_TRC_INF_STATE_CHANGE_POWER_FLAG_size

// GPS_TRC_INF_STATE_CHANGE_POWER_TYPE
#define GPS_TRC_INF_STATE_CHANGE_POWER_TYPE_size "‚d"
#define GPS_TRC_INF_STATE_CHANGE_POWER_TYPE GPS_TRC_INF_STATE_CHANGE_POWER_TYPE__enum,GPS_TRC_INF_STATE_CHANGE_POWER_TYPE_size

// GPS_TRC_INF_STATE_ENABLE_AUTH
#define GPS_TRC_INF_STATE_ENABLE_AUTH_size NULL
#define GPS_TRC_INF_STATE_ENABLE_AUTH GPS_TRC_INF_STATE_ENABLE_AUTH__enum,GPS_TRC_INF_STATE_ENABLE_AUTH_size

// GPS_TRC_WRN_INJECT_ILLEGAL_CMD
#define GPS_TRC_WRN_INJECT_ILLEGAL_CMD_size "d"
#define GPS_TRC_WRN_INJECT_ILLEGAL_CMD GPS_TRC_WRN_INJECT_ILLEGAL_CMD__enum,GPS_TRC_WRN_INJECT_ILLEGAL_CMD_size

// GPS_TRC_WRN_INJECT_ILLEGAL_STRING
#define GPS_TRC_WRN_INJECT_ILLEGAL_STRING_size NULL
#define GPS_TRC_WRN_INJECT_ILLEGAL_STRING GPS_TRC_WRN_INJECT_ILLEGAL_STRING__enum,GPS_TRC_WRN_INJECT_ILLEGAL_STRING_size

// GPS_TRC_INF_UART_OPEN_INJECT_SEND_MSG
#define GPS_TRC_INF_UART_OPEN_INJECT_SEND_MSG_size NULL
#define GPS_TRC_INF_UART_OPEN_INJECT_SEND_MSG GPS_TRC_INF_UART_OPEN_INJECT_SEND_MSG__enum,GPS_TRC_INF_UART_OPEN_INJECT_SEND_MSG_size

// GPS_TRC_INF_UART_CLOSE_INJECT_SEND_MSG
#define GPS_TRC_INF_UART_CLOSE_INJECT_SEND_MSG_size NULL
#define GPS_TRC_INF_UART_CLOSE_INJECT_SEND_MSG GPS_TRC_INF_UART_CLOSE_INJECT_SEND_MSG__enum,GPS_TRC_INF_UART_CLOSE_INJECT_SEND_MSG_size

// GPS_TRC_INF_SLEEP_INJECT_SET_POWER_SAVING
#define GPS_TRC_INF_SLEEP_INJECT_SET_POWER_SAVING_size "d"
#define GPS_TRC_INF_SLEEP_INJECT_SET_POWER_SAVING GPS_TRC_INF_SLEEP_INJECT_SET_POWER_SAVING__enum,GPS_TRC_INF_SLEEP_INJECT_SET_POWER_SAVING_size

// GPS_TRC_WRN_MSG_INVALID_ID
#define GPS_TRC_WRN_MSG_INVALID_ID_size "d"
#define GPS_TRC_WRN_MSG_INVALID_ID GPS_TRC_WRN_MSG_INVALID_ID__enum,GPS_TRC_WRN_MSG_INVALID_ID_size

// GPS_TRC_EPO_DOWNLOAD_FINISH_CONNECTION
#define GPS_TRC_EPO_DOWNLOAD_FINISH_CONNECTION_size NULL
#define GPS_TRC_EPO_DOWNLOAD_FINISH_CONNECTION GPS_TRC_EPO_DOWNLOAD_FINISH_CONNECTION__enum,GPS_TRC_EPO_DOWNLOAD_FINISH_CONNECTION_size

// GPS_TRC_EPO_DOWNLOAD_ERROR_HANDLE
#define GPS_TRC_EPO_DOWNLOAD_ERROR_HANDLE_size "ƒd"
#define GPS_TRC_EPO_DOWNLOAD_ERROR_HANDLE GPS_TRC_EPO_DOWNLOAD_ERROR_HANDLE__enum,GPS_TRC_EPO_DOWNLOAD_ERROR_HANDLE_size

// GPS_TRC_EPO_DOWNLOAD_START_TIMER
#define GPS_TRC_EPO_DOWNLOAD_START_TIMER_size "ƒd"
#define GPS_TRC_EPO_DOWNLOAD_START_TIMER GPS_TRC_EPO_DOWNLOAD_START_TIMER__enum,GPS_TRC_EPO_DOWNLOAD_START_TIMER_size

// GPS_TRC_EPO_DOWNLOAD_FILE_OPEN
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_size "‚d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN GPS_TRC_EPO_DOWNLOAD_FILE_OPEN__enum,GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_size

// GPS_TRC_EPO_DOWNLOAD_FILE_HANDLE
#define GPS_TRC_EPO_DOWNLOAD_FILE_HANDLE_size "d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_HANDLE GPS_TRC_EPO_DOWNLOAD_FILE_HANDLE__enum,GPS_TRC_EPO_DOWNLOAD_FILE_HANDLE_size

// GPS_TRC_EPO_DOWNLOAD_FILE_DELETE
#define GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_size "‚d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_DELETE GPS_TRC_EPO_DOWNLOAD_FILE_DELETE__enum,GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_size

// GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_RET
#define GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_RET_size "d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_RET GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_RET__enum,GPS_TRC_EPO_DOWNLOAD_FILE_DELETE_RET_size

// GPS_TRC_EPO_DOWNLOAD_FILE_RENAME
#define GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_size "ƒd"
#define GPS_TRC_EPO_DOWNLOAD_FILE_RENAME GPS_TRC_EPO_DOWNLOAD_FILE_RENAME__enum,GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_size

// GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_RET
#define GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_RET_size "d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_RET GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_RET__enum,GPS_TRC_EPO_DOWNLOAD_FILE_RENAME_RET_size

// GPS_TRC_EPO_DOWNLOAD_UTC_TO_GPS_HOUR
#define GPS_TRC_EPO_DOWNLOAD_UTC_TO_GPS_HOUR_size "„d"
#define GPS_TRC_EPO_DOWNLOAD_UTC_TO_GPS_HOUR GPS_TRC_EPO_DOWNLOAD_UTC_TO_GPS_HOUR__enum,GPS_TRC_EPO_DOWNLOAD_UTC_TO_GPS_HOUR_size

// GPS_TRC_EPO_DOWNLOAD_CURR_GPS_HOUR
#define GPS_TRC_EPO_DOWNLOAD_CURR_GPS_HOUR_size "d"
#define GPS_TRC_EPO_DOWNLOAD_CURR_GPS_HOUR GPS_TRC_EPO_DOWNLOAD_CURR_GPS_HOUR__enum,GPS_TRC_EPO_DOWNLOAD_CURR_GPS_HOUR_size

// GPS_TRC_EPO_DOWNLOAD_GET_MAX_GPS_HOURS
#define GPS_TRC_EPO_DOWNLOAD_GET_MAX_GPS_HOURS_size NULL
#define GPS_TRC_EPO_DOWNLOAD_GET_MAX_GPS_HOURS GPS_TRC_EPO_DOWNLOAD_GET_MAX_GPS_HOURS__enum,GPS_TRC_EPO_DOWNLOAD_GET_MAX_GPS_HOURS_size

// GPS_TRC_EPO_DOWNLOAD_MAX_GPS_HOURS
#define GPS_TRC_EPO_DOWNLOAD_MAX_GPS_HOURS_size "d"
#define GPS_TRC_EPO_DOWNLOAD_MAX_GPS_HOURS GPS_TRC_EPO_DOWNLOAD_MAX_GPS_HOURS__enum,GPS_TRC_EPO_DOWNLOAD_MAX_GPS_HOURS_size

// GPS_TRC_EPO_DOWNLOAD_CHECK_FILE_EXPIRED
#define GPS_TRC_EPO_DOWNLOAD_CHECK_FILE_EXPIRED_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CHECK_FILE_EXPIRED GPS_TRC_EPO_DOWNLOAD_CHECK_FILE_EXPIRED__enum,GPS_TRC_EPO_DOWNLOAD_CHECK_FILE_EXPIRED_size

// GPS_TRC_EPO_DOWNLOAD_FILE_GPS_HOURS
#define GPS_TRC_EPO_DOWNLOAD_FILE_GPS_HOURS_size "‚d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_GPS_HOURS GPS_TRC_EPO_DOWNLOAD_FILE_GPS_HOURS__enum,GPS_TRC_EPO_DOWNLOAD_FILE_GPS_HOURS_size

// GPS_TRC_EPO_DOWNLOAD_CHECK_DOWNLOAD_FINISH
#define GPS_TRC_EPO_DOWNLOAD_CHECK_DOWNLOAD_FINISH_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CHECK_DOWNLOAD_FINISH GPS_TRC_EPO_DOWNLOAD_CHECK_DOWNLOAD_FINISH__enum,GPS_TRC_EPO_DOWNLOAD_CHECK_DOWNLOAD_FINISH_size

// GPS_TRC_EPO_DOWNLOAD_START_CHECK_SUM
#define GPS_TRC_EPO_DOWNLOAD_START_CHECK_SUM_size NULL
#define GPS_TRC_EPO_DOWNLOAD_START_CHECK_SUM GPS_TRC_EPO_DOWNLOAD_START_CHECK_SUM__enum,GPS_TRC_EPO_DOWNLOAD_START_CHECK_SUM_size

// GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_OK
#define GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_OK_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_OK GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_OK__enum,GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_OK_size

// GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_FAIL
#define GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_FAIL GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_CHECK_SUM_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_START_CONNECTION
#define GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_size NULL
#define GPS_TRC_EPO_DOWNLOAD_START_CONNECTION GPS_TRC_EPO_DOWNLOAD_START_CONNECTION__enum,GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_size

// GPS_TRC_EPO_DOWNLOAD_CONNECT_FAIL
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_FAIL GPS_TRC_EPO_DOWNLOAD_CONNECT_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_CONNECT_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND__enum,GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_size

// GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_FAIL
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_FAIL GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_CONNECT_SEND_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_SAVE_RECIEVE_DATA
#define GPS_TRC_EPO_DOWNLOAD_SAVE_RECIEVE_DATA_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SAVE_RECIEVE_DATA GPS_TRC_EPO_DOWNLOAD_SAVE_RECIEVE_DATA__enum,GPS_TRC_EPO_DOWNLOAD_SAVE_RECIEVE_DATA_size

// GPS_TRC_EPO_DOWNLOAD_FILE_WRITE_FAIL
#define GPS_TRC_EPO_DOWNLOAD_FILE_WRITE_FAIL_size "d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_WRITE_FAIL GPS_TRC_EPO_DOWNLOAD_FILE_WRITE_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_FILE_WRITE_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_PEOCESS_HEADER
#define GPS_TRC_EPO_DOWNLOAD_PEOCESS_HEADER_size NULL
#define GPS_TRC_EPO_DOWNLOAD_PEOCESS_HEADER GPS_TRC_EPO_DOWNLOAD_PEOCESS_HEADER__enum,GPS_TRC_EPO_DOWNLOAD_PEOCESS_HEADER_size

// GPS_TRC_EPO_DOWNLOAD_CONTENT_LENGH_WRONE
#define GPS_TRC_EPO_DOWNLOAD_CONTENT_LENGH_WRONE_size "d"
#define GPS_TRC_EPO_DOWNLOAD_CONTENT_LENGH_WRONE GPS_TRC_EPO_DOWNLOAD_CONTENT_LENGH_WRONE__enum,GPS_TRC_EPO_DOWNLOAD_CONTENT_LENGH_WRONE_size

// GPS_TRC_EPO_DOWNLOAD_ETAG_ERROR
#define GPS_TRC_EPO_DOWNLOAD_ETAG_ERROR_size NULL
#define GPS_TRC_EPO_DOWNLOAD_ETAG_ERROR GPS_TRC_EPO_DOWNLOAD_ETAG_ERROR__enum,GPS_TRC_EPO_DOWNLOAD_ETAG_ERROR_size

// GPS_TRC_EPO_DOWNLOAD_RECIEVING_BODY
#define GPS_TRC_EPO_DOWNLOAD_RECIEVING_BODY_size NULL
#define GPS_TRC_EPO_DOWNLOAD_RECIEVING_BODY GPS_TRC_EPO_DOWNLOAD_RECIEVING_BODY__enum,GPS_TRC_EPO_DOWNLOAD_RECIEVING_BODY_size

// GPS_TRC_EPO_DOWNLOAD_RECIEVING_HEAD
#define GPS_TRC_EPO_DOWNLOAD_RECIEVING_HEAD_size NULL
#define GPS_TRC_EPO_DOWNLOAD_RECIEVING_HEAD GPS_TRC_EPO_DOWNLOAD_RECIEVING_HEAD__enum,GPS_TRC_EPO_DOWNLOAD_RECIEVING_HEAD_size

// GPS_TRC_EPO_DOWNLOAD_CONNECTION_RECIEVE
#define GPS_TRC_EPO_DOWNLOAD_CONNECTION_RECIEVE_size NULL
#define GPS_TRC_EPO_DOWNLOAD_CONNECTION_RECIEVE GPS_TRC_EPO_DOWNLOAD_CONNECTION_RECIEVE__enum,GPS_TRC_EPO_DOWNLOAD_CONNECTION_RECIEVE_size

// GPS_TRC_EPO_DOWNLOAD_SOCKET_ID_ERROR
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_ID_ERROR_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_ID_ERROR GPS_TRC_EPO_DOWNLOAD_SOCKET_ID_ERROR__enum,GPS_TRC_EPO_DOWNLOAD_SOCKET_ID_ERROR_size

// GPS_TRC_EPO_DOWNLOAD_SOCKET_READ_FAIL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_READ_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_READ_FAIL GPS_TRC_EPO_DOWNLOAD_SOCKET_READ_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_SOCKET_READ_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_TRY_FINISH_CURR_DOWNLOAD
#define GPS_TRC_EPO_DOWNLOAD_TRY_FINISH_CURR_DOWNLOAD_size NULL
#define GPS_TRC_EPO_DOWNLOAD_TRY_FINISH_CURR_DOWNLOAD GPS_TRC_EPO_DOWNLOAD_TRY_FINISH_CURR_DOWNLOAD__enum,GPS_TRC_EPO_DOWNLOAD_TRY_FINISH_CURR_DOWNLOAD_size

// GPS_TRC_EPO_DOWNLOAD_SOCKET_NOTIFY
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_NOTIFY_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_NOTIFY GPS_TRC_EPO_DOWNLOAD_SOCKET_NOTIFY__enum,GPS_TRC_EPO_DOWNLOAD_SOCKET_NOTIFY_size

// GPS_TRC_EPO_DOWNLOAD_WRONG_SOCKET_ID
#define GPS_TRC_EPO_DOWNLOAD_WRONG_SOCKET_ID_size NULL
#define GPS_TRC_EPO_DOWNLOAD_WRONG_SOCKET_ID GPS_TRC_EPO_DOWNLOAD_WRONG_SOCKET_ID__enum,GPS_TRC_EPO_DOWNLOAD_WRONG_SOCKET_ID_size

// GPS_TRC_EPO_DOWNLOAD_ENVENT_FILE_TYPE
#define GPS_TRC_EPO_DOWNLOAD_ENVENT_FILE_TYPE_size "‚d"
#define GPS_TRC_EPO_DOWNLOAD_ENVENT_FILE_TYPE GPS_TRC_EPO_DOWNLOAD_ENVENT_FILE_TYPE__enum,GPS_TRC_EPO_DOWNLOAD_ENVENT_FILE_TYPE_size

// GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_AGAIN
#define GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_AGAIN_size NULL
#define GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_AGAIN GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_AGAIN__enum,GPS_TRC_EPO_DOWNLOAD_START_CONNECTION_AGAIN_size

// GPS_TRC_EPO_DOWNLOAD_SOCKET_CLOSE_ERROR
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_CLOSE_ERROR_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_CLOSE_ERROR GPS_TRC_EPO_DOWNLOAD_SOCKET_CLOSE_ERROR__enum,GPS_TRC_EPO_DOWNLOAD_SOCKET_CLOSE_ERROR_size

// GPS_TRC_EPO_DOWNLOAD_EPO_CONNECTIVTY_MESSAGE_HANDLER
#define GPS_TRC_EPO_DOWNLOAD_EPO_CONNECTIVTY_MESSAGE_HANDLER_size NULL
#define GPS_TRC_EPO_DOWNLOAD_EPO_CONNECTIVTY_MESSAGE_HANDLER GPS_TRC_EPO_DOWNLOAD_EPO_CONNECTIVTY_MESSAGE_HANDLER__enum,GPS_TRC_EPO_DOWNLOAD_EPO_CONNECTIVTY_MESSAGE_HANDLER_size

// GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_INT
#define GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_INT_size NULL
#define GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_INT GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_INT__enum,GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_INT_size

// GPS_TRC_EPO_DOWNLOAD_ALREADY_GET_IP
#define GPS_TRC_EPO_DOWNLOAD_ALREADY_GET_IP_size NULL
#define GPS_TRC_EPO_DOWNLOAD_ALREADY_GET_IP GPS_TRC_EPO_DOWNLOAD_ALREADY_GET_IP__enum,GPS_TRC_EPO_DOWNLOAD_ALREADY_GET_IP_size

// GPS_TRC_EPO_DOWNLOAD_IP_ADDR
#define GPS_TRC_EPO_DOWNLOAD_IP_ADDR_size "„d"
#define GPS_TRC_EPO_DOWNLOAD_IP_ADDR GPS_TRC_EPO_DOWNLOAD_IP_ADDR__enum,GPS_TRC_EPO_DOWNLOAD_IP_ADDR_size

// GPS_TRC_EPO_DOWNLOAD_GET_IP_FAIL
#define GPS_TRC_EPO_DOWNLOAD_GET_IP_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_GET_IP_FAIL GPS_TRC_EPO_DOWNLOAD_GET_IP_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_GET_IP_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME
#define GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_size NULL
#define GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME__enum,GPS_TRC_EPO_DOWNLOAD_GET_HOST_BY_NAME_size

// GPS_TRC_EPO_DOWNLOAD_CREATE_AND_START_CONNECTION
#define GPS_TRC_EPO_DOWNLOAD_CREATE_AND_START_CONNECTION_size "d"
#define GPS_TRC_EPO_DOWNLOAD_CREATE_AND_START_CONNECTION GPS_TRC_EPO_DOWNLOAD_CREATE_AND_START_CONNECTION__enum,GPS_TRC_EPO_DOWNLOAD_CREATE_AND_START_CONNECTION_size

// GPS_TRC_EPO_DOWNLOAD_SOCKET_CREATE_FAIL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_CREATE_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_SOCKET_CREATE_FAIL GPS_TRC_EPO_DOWNLOAD_SOCKET_CREATE_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_SOCKET_CREATE_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_3_DAY_SINGLE_CHUNK
#define GPS_TRC_EPO_DOWNLOAD_3_DAY_SINGLE_CHUNK_size NULL
#define GPS_TRC_EPO_DOWNLOAD_3_DAY_SINGLE_CHUNK GPS_TRC_EPO_DOWNLOAD_3_DAY_SINGLE_CHUNK__enum,GPS_TRC_EPO_DOWNLOAD_3_DAY_SINGLE_CHUNK_size

// GPS_TRC_EPO_DOWNLOAD_IS_EXCEED_ONE_DAY
#define GPS_TRC_EPO_DOWNLOAD_IS_EXCEED_ONE_DAY_size NULL
#define GPS_TRC_EPO_DOWNLOAD_IS_EXCEED_ONE_DAY GPS_TRC_EPO_DOWNLOAD_IS_EXCEED_ONE_DAY__enum,GPS_TRC_EPO_DOWNLOAD_IS_EXCEED_ONE_DAY_size

// GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_ERROR
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_ERROR_size "d"
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_ERROR GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_ERROR__enum,GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_ERROR_size

// GPS_TRC_EPO_DOWNLOAD_CURR_MAX_GPS_HOURS
#define GPS_TRC_EPO_DOWNLOAD_CURR_MAX_GPS_HOURS_size "‚d"
#define GPS_TRC_EPO_DOWNLOAD_CURR_MAX_GPS_HOURS GPS_TRC_EPO_DOWNLOAD_CURR_MAX_GPS_HOURS__enum,GPS_TRC_EPO_DOWNLOAD_CURR_MAX_GPS_HOURS_size

// GPS_TRC_EPO_DOWNLOAD_TIMER_CALLBACK
#define GPS_TRC_EPO_DOWNLOAD_TIMER_CALLBACK_size NULL
#define GPS_TRC_EPO_DOWNLOAD_TIMER_CALLBACK GPS_TRC_EPO_DOWNLOAD_TIMER_CALLBACK__enum,GPS_TRC_EPO_DOWNLOAD_TIMER_CALLBACK_size

// GPS_TRC_EPO_DOWNLOAD_START_3_DAY_TIMER
#define GPS_TRC_EPO_DOWNLOAD_START_3_DAY_TIMER_size NULL
#define GPS_TRC_EPO_DOWNLOAD_START_3_DAY_TIMER GPS_TRC_EPO_DOWNLOAD_START_3_DAY_TIMER__enum,GPS_TRC_EPO_DOWNLOAD_START_3_DAY_TIMER_size

// GPS_TRC_EPO_DOWNLOAD_EXPIRY_TIME
#define GPS_TRC_EPO_DOWNLOAD_EXPIRY_TIME_size "d"
#define GPS_TRC_EPO_DOWNLOAD_EXPIRY_TIME GPS_TRC_EPO_DOWNLOAD_EXPIRY_TIME__enum,GPS_TRC_EPO_DOWNLOAD_EXPIRY_TIME_size

// GPS_TRC_EPO_DOWNLOAD_3_DAY
#define GPS_TRC_EPO_DOWNLOAD_3_DAY_size "d"
#define GPS_TRC_EPO_DOWNLOAD_3_DAY GPS_TRC_EPO_DOWNLOAD_3_DAY__enum,GPS_TRC_EPO_DOWNLOAD_3_DAY_size

// GPS_TRC_EPO_DOWNLOAD_DELAY_DOWNLOAD
#define GPS_TRC_EPO_DOWNLOAD_DELAY_DOWNLOAD_size NULL
#define GPS_TRC_EPO_DOWNLOAD_DELAY_DOWNLOAD GPS_TRC_EPO_DOWNLOAD_DELAY_DOWNLOAD__enum,GPS_TRC_EPO_DOWNLOAD_DELAY_DOWNLOAD_size

// GPS_TRC_EPO_DOWNLOAD_QEPO_GET_INDEX
#define GPS_TRC_EPO_DOWNLOAD_QEPO_GET_INDEX_size NULL
#define GPS_TRC_EPO_DOWNLOAD_QEPO_GET_INDEX GPS_TRC_EPO_DOWNLOAD_QEPO_GET_INDEX__enum,GPS_TRC_EPO_DOWNLOAD_QEPO_GET_INDEX_size

// GPS_TRC_EPO_DOWNLOAD_INDEX
#define GPS_TRC_EPO_DOWNLOAD_INDEX_size "d"
#define GPS_TRC_EPO_DOWNLOAD_INDEX GPS_TRC_EPO_DOWNLOAD_INDEX__enum,GPS_TRC_EPO_DOWNLOAD_INDEX_size

// GPS_TRC_EPO_DOWNLOAD_DOWNLOAD_SUCCESS_HANDLE
#define GPS_TRC_EPO_DOWNLOAD_DOWNLOAD_SUCCESS_HANDLE_size NULL
#define GPS_TRC_EPO_DOWNLOAD_DOWNLOAD_SUCCESS_HANDLE GPS_TRC_EPO_DOWNLOAD_DOWNLOAD_SUCCESS_HANDLE__enum,GPS_TRC_EPO_DOWNLOAD_DOWNLOAD_SUCCESS_HANDLE_size

// GPS_TRC_EPO_DOWNLOAD_NEXT_CHUNK
#define GPS_TRC_EPO_DOWNLOAD_NEXT_CHUNK_size NULL
#define GPS_TRC_EPO_DOWNLOAD_NEXT_CHUNK GPS_TRC_EPO_DOWNLOAD_NEXT_CHUNK__enum,GPS_TRC_EPO_DOWNLOAD_NEXT_CHUNK_size

// GPS_TRC_EPO_DOWNLOAD_FINISH
#define GPS_TRC_EPO_DOWNLOAD_FINISH_size NULL
#define GPS_TRC_EPO_DOWNLOAD_FINISH GPS_TRC_EPO_DOWNLOAD_FINISH__enum,GPS_TRC_EPO_DOWNLOAD_FINISH_size

// GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_SUCESS_HANDLE
#define GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_SUCESS_HANDLE_size NULL
#define GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_SUCESS_HANDLE GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_SUCESS_HANDLE__enum,GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_SUCESS_HANDLE_size

// GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD
#define GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_size "d"
#define GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD__enum,GPS_TRC_EPO_DOWNLOAD_QEPO_DOWNLOAD_size

// GPS_TRC_EPO_DOWNLOAD_DELETE_ALL
#define GPS_TRC_EPO_DOWNLOAD_DELETE_ALL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_DELETE_ALL GPS_TRC_EPO_DOWNLOAD_DELETE_ALL__enum,GPS_TRC_EPO_DOWNLOAD_DELETE_ALL_size

// GPS_TRC_EPO_DOWNLOAD_TRY_3_DAY_EPO_AIDING
#define GPS_TRC_EPO_DOWNLOAD_TRY_3_DAY_EPO_AIDING_size NULL
#define GPS_TRC_EPO_DOWNLOAD_TRY_3_DAY_EPO_AIDING GPS_TRC_EPO_DOWNLOAD_TRY_3_DAY_EPO_AIDING__enum,GPS_TRC_EPO_DOWNLOAD_TRY_3_DAY_EPO_AIDING_size

// GPS_TRC_EPO_DOWNLOAD_AIDING_FAIL
#define GPS_TRC_EPO_DOWNLOAD_AIDING_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_AIDING_FAIL GPS_TRC_EPO_DOWNLOAD_AIDING_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_AIDING_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_TRY_QEPO_AIDING
#define GPS_TRC_EPO_DOWNLOAD_TRY_QEPO_AIDING_size NULL
#define GPS_TRC_EPO_DOWNLOAD_TRY_QEPO_AIDING GPS_TRC_EPO_DOWNLOAD_TRY_QEPO_AIDING__enum,GPS_TRC_EPO_DOWNLOAD_TRY_QEPO_AIDING_size

// GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_FAIL
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_FAIL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_FAIL GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_FAIL__enum,GPS_TRC_EPO_DOWNLOAD_FILE_OPEN_FAIL_size

// GPS_TRC_EPO_DOWNLOAD_EPO_AIDING
#define GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_size NULL
#define GPS_TRC_EPO_DOWNLOAD_EPO_AIDING GPS_TRC_EPO_DOWNLOAD_EPO_AIDING__enum,GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_size

// GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_INTERNAL
#define GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_INTERNAL_size NULL
#define GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_INTERNAL GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_INTERNAL__enum,GPS_TRC_EPO_DOWNLOAD_EPO_AIDING_INTERNAL_size

// GPS_TRC_EPO_DOWNLOAD_EPO_INIT
#define GPS_TRC_EPO_DOWNLOAD_EPO_INIT_size NULL
#define GPS_TRC_EPO_DOWNLOAD_EPO_INIT GPS_TRC_EPO_DOWNLOAD_EPO_INIT__enum,GPS_TRC_EPO_DOWNLOAD_EPO_INIT_size

// GPS_TRC_EPO_DOWNLOAD_CURR_SEG
#define GPS_TRC_EPO_DOWNLOAD_CURR_SEG_size "d"
#define GPS_TRC_EPO_DOWNLOAD_CURR_SEG GPS_TRC_EPO_DOWNLOAD_CURR_SEG__enum,GPS_TRC_EPO_DOWNLOAD_CURR_SEG_size

// GPSADAPOOR_AGPS_SET_STATE
#define GPSADAPOOR_AGPS_SET_STATE_size "‚d"
#define GPSADAPOOR_AGPS_SET_STATE GPSADAPOOR_AGPS_SET_STATE__enum,GPSADAPOOR_AGPS_SET_STATE_size

// GPSADAPOOR_AGPS_SEND_CMD
#define GPSADAPOOR_AGPS_SEND_CMD_size "d"
#define GPSADAPOOR_AGPS_SEND_CMD GPSADAPOOR_AGPS_SEND_CMD__enum,GPSADAPOOR_AGPS_SEND_CMD_size

// GPSADAPOOR_AGPS_SEND_START_REQ
#define GPSADAPOOR_AGPS_SEND_START_REQ_size NULL
#define GPSADAPOOR_AGPS_SEND_START_REQ GPSADAPOOR_AGPS_SEND_START_REQ__enum,GPSADAPOOR_AGPS_SEND_START_REQ_size

// GPSADAPOOR_AGPS_RECEIVE_ACTIVATED_STATUS
#define GPSADAPOOR_AGPS_RECEIVE_ACTIVATED_STATUS_size NULL
#define GPSADAPOOR_AGPS_RECEIVE_ACTIVATED_STATUS GPSADAPOOR_AGPS_RECEIVE_ACTIVATED_STATUS__enum,GPSADAPOOR_AGPS_RECEIVE_ACTIVATED_STATUS_size

// GPSADAPOOR_AGPS_GET_MCCMNC
#define GPSADAPOOR_AGPS_GET_MCCMNC_size "s"
#define GPSADAPOOR_AGPS_GET_MCCMNC GPSADAPOOR_AGPS_GET_MCCMNC__enum,GPSADAPOOR_AGPS_GET_MCCMNC_size

// GPSADAPOOR_AGPS_ALLOC_FAILURE
#define GPSADAPOOR_AGPS_ALLOC_FAILURE_size NULL
#define GPSADAPOOR_AGPS_ALLOC_FAILURE GPSADAPOOR_AGPS_ALLOC_FAILURE__enum,GPSADAPOOR_AGPS_ALLOC_FAILURE_size

// GPSADAPOOR_AGPS_NO_NETWORK
#define GPSADAPOOR_AGPS_NO_NETWORK_size NULL
#define GPSADAPOOR_AGPS_NO_NETWORK GPSADAPOOR_AGPS_NO_NETWORK__enum,GPSADAPOOR_AGPS_NO_NETWORK_size

// GPSADAPOOR_AGPS_STATE_MACHINE_WRONG
#define GPSADAPOOR_AGPS_STATE_MACHINE_WRONG_size "d"
#define GPSADAPOOR_AGPS_STATE_MACHINE_WRONG GPSADAPOOR_AGPS_STATE_MACHINE_WRONG__enum,GPSADAPOOR_AGPS_STATE_MACHINE_WRONG_size

// GPSADAPOOR_AGPS_SEND_STOP_REQ
#define GPSADAPOOR_AGPS_SEND_STOP_REQ_size NULL
#define GPSADAPOOR_AGPS_SEND_STOP_REQ GPSADAPOOR_AGPS_SEND_STOP_REQ__enum,GPSADAPOOR_AGPS_SEND_STOP_REQ_size

// GPSADAPOOR_AGPS_SEND_ERR_RESPONSE
#define GPSADAPOOR_AGPS_SEND_ERR_RESPONSE_size NULL
#define GPSADAPOOR_AGPS_SEND_ERR_RESPONSE GPSADAPOOR_AGPS_SEND_ERR_RESPONSE__enum,GPSADAPOOR_AGPS_SEND_ERR_RESPONSE_size

// GPSADAPOOR_AGPS_GET_PLMN_FAIL
#define GPSADAPOOR_AGPS_GET_PLMN_FAIL_size NULL
#define GPSADAPOOR_AGPS_GET_PLMN_FAIL GPSADAPOOR_AGPS_GET_PLMN_FAIL__enum,GPSADAPOOR_AGPS_GET_PLMN_FAIL_size

// GPSADAPOOR_AGPS_GET_AGPS_UP_SETTING
#define GPSADAPOOR_AGPS_GET_AGPS_UP_SETTING_size "„d"
#define GPSADAPOOR_AGPS_GET_AGPS_UP_SETTING GPSADAPOOR_AGPS_GET_AGPS_UP_SETTING__enum,GPSADAPOOR_AGPS_GET_AGPS_UP_SETTING_size

// GPSADAPOOR_AGPS_GET_AGPS_PROFILE_SETTING
#define GPSADAPOOR_AGPS_GET_AGPS_PROFILE_SETTING_size "sd"
#define GPSADAPOOR_AGPS_GET_AGPS_PROFILE_SETTING GPSADAPOOR_AGPS_GET_AGPS_PROFILE_SETTING__enum,GPSADAPOOR_AGPS_GET_AGPS_PROFILE_SETTING_size

// GPSADAPOOR_AGPS_GET_AGPS_CONFIG_SETTING
#define GPSADAPOOR_AGPS_GET_AGPS_CONFIG_SETTING_size "s‚d"
#define GPSADAPOOR_AGPS_GET_AGPS_CONFIG_SETTING GPSADAPOOR_AGPS_GET_AGPS_CONFIG_SETTING__enum,GPSADAPOOR_AGPS_GET_AGPS_CONFIG_SETTING_size

// GPSADAPOOR_AGPS_GET_AGPS_ONOFF
#define GPSADAPOOR_AGPS_GET_AGPS_ONOFF_size "d"
#define GPSADAPOOR_AGPS_GET_AGPS_ONOFF GPSADAPOOR_AGPS_GET_AGPS_ONOFF__enum,GPSADAPOOR_AGPS_GET_AGPS_ONOFF_size

// GPSADAPTOR_AGPS_UART_P_CALLBACK
#define GPSADAPTOR_AGPS_UART_P_CALLBACK_size "d"
#define GPSADAPTOR_AGPS_UART_P_CALLBACK GPSADAPTOR_AGPS_UART_P_CALLBACK__enum,GPSADAPTOR_AGPS_UART_P_CALLBACK_size


#endif // GPS_TRC_GEN.H
