#ifndef _L1A_TRACE_GEN_H_
#define _L1A_TRACE_GEN_H_

// ERROR_l1a_error_msg_rpt_ID
#define ERROR_l1a_error_msg_rpt_ID_size "d"
#define ERROR_l1a_error_msg_rpt_ID ERROR_l1a_error_msg_rpt_ID__enum,ERROR_l1a_error_msg_rpt_ID_size

// ERROR_l1a_error_msg_ID
#define ERROR_l1a_error_msg_ID_size "‚d"
#define ERROR_l1a_error_msg_ID ERROR_l1a_error_msg_ID__enum,ERROR_l1a_error_msg_ID_size

// ERROR_l1a_error_rpt_ID
#define ERROR_l1a_error_rpt_ID_size "‚d"
#define ERROR_l1a_error_rpt_ID ERROR_l1a_error_rpt_ID__enum,ERROR_l1a_error_rpt_ID_size

// ERROR_l1a_delayed_report_rach_in_dedicated_ID
#define ERROR_l1a_delayed_report_rach_in_dedicated_ID_size NULL
#define ERROR_l1a_delayed_report_rach_in_dedicated_ID ERROR_l1a_delayed_report_rach_in_dedicated_ID__enum,ERROR_l1a_delayed_report_rach_in_dedicated_ID_size

// WARNING_l1a_delayed_report_rach_in_idle_ID
#define WARNING_l1a_delayed_report_rach_in_idle_ID_size NULL
#define WARNING_l1a_delayed_report_rach_in_idle_ID WARNING_l1a_delayed_report_rach_in_idle_ID__enum,WARNING_l1a_delayed_report_rach_in_idle_ID_size

// INFO_l1a_repeated_FACCH_dch_ID
#define INFO_l1a_repeated_FACCH_dch_ID_size NULL
#define INFO_l1a_repeated_FACCH_dch_ID INFO_l1a_repeated_FACCH_dch_ID__enum,INFO_l1a_repeated_FACCH_dch_ID_size

// ERROR_l1a_gprs_state_info_ID
#define ERROR_l1a_gprs_state_info_ID_size "†d"
#define ERROR_l1a_gprs_state_info_ID ERROR_l1a_gprs_state_info_ID__enum,ERROR_l1a_gprs_state_info_ID_size

// WARNING_l1a_stop_pbcch_ID
#define WARNING_l1a_stop_pbcch_ID_size NULL
#define WARNING_l1a_stop_pbcch_ID WARNING_l1a_stop_pbcch_ID__enum,WARNING_l1a_stop_pbcch_ID_size

// WARNING_l1a_stop_npbcch_ID
#define WARNING_l1a_stop_npbcch_ID_size NULL
#define WARNING_l1a_stop_npbcch_ID WARNING_l1a_stop_npbcch_ID__enum,WARNING_l1a_stop_npbcch_ID_size

// WARNING_idle_ccch_start_pa_ID
#define WARNING_idle_ccch_start_pa_ID_size NULL
#define WARNING_idle_ccch_start_pa_ID WARNING_idle_ccch_start_pa_ID__enum,WARNING_idle_ccch_start_pa_ID_size

// WARNING_idle_ccch_start_pt_ID
#define WARNING_idle_ccch_start_pt_ID_size NULL
#define WARNING_idle_ccch_start_pt_ID WARNING_idle_ccch_start_pt_ID__enum,WARNING_idle_ccch_start_pt_ID_size

// WARNING_pdch_fail_tbf_pend_ID
#define WARNING_pdch_fail_tbf_pend_ID_size NULL
#define WARNING_pdch_fail_tbf_pend_ID WARNING_pdch_fail_tbf_pend_ID__enum,WARNING_pdch_fail_tbf_pend_ID_size

// INFO_l1a_poll_response_on_pccch_ID
#define INFO_l1a_poll_response_on_pccch_ID_size NULL
#define INFO_l1a_poll_response_on_pccch_ID INFO_l1a_poll_response_on_pccch_ID__enum,INFO_l1a_poll_response_on_pccch_ID_size

// INFO_l1a_poll_response_on_pacch_ID
#define INFO_l1a_poll_response_on_pacch_ID_size NULL
#define INFO_l1a_poll_response_on_pacch_ID INFO_l1a_poll_response_on_pacch_ID__enum,INFO_l1a_poll_response_on_pacch_ID_size

// INFO_l1a_poll_response_on_singledl_ID
#define INFO_l1a_poll_response_on_singledl_ID_size NULL
#define INFO_l1a_poll_response_on_singledl_ID INFO_l1a_poll_response_on_singledl_ID__enum,INFO_l1a_poll_response_on_singledl_ID_size

// INFO_l1a_set_pbcch_priority_ID
#define INFO_l1a_set_pbcch_priority_ID_size "d"
#define INFO_l1a_set_pbcch_priority_ID INFO_l1a_set_pbcch_priority_ID__enum,INFO_l1a_set_pbcch_priority_ID_size

// INFO_l1a_pbcch_synctimeslot_ID
#define INFO_l1a_pbcch_synctimeslot_ID_size "d"
#define INFO_l1a_pbcch_synctimeslot_ID INFO_l1a_pbcch_synctimeslot_ID__enum,INFO_l1a_pbcch_synctimeslot_ID_size

// INFO_l1a_set_npbcch_priority_ID
#define INFO_l1a_set_npbcch_priority_ID_size "d"
#define INFO_l1a_set_npbcch_priority_ID INFO_l1a_set_npbcch_priority_ID__enum,INFO_l1a_set_npbcch_priority_ID_size

// INFO_l1a_starting_time_expire_ID
#define INFO_l1a_starting_time_expire_ID_size NULL
#define INFO_l1a_starting_time_expire_ID INFO_l1a_starting_time_expire_ID__enum,INFO_l1a_starting_time_expire_ID_size

// INFO_l1a_tbf_synctimeslot_ID
#define INFO_l1a_tbf_synctimeslot_ID_size "d"
#define INFO_l1a_tbf_synctimeslot_ID INFO_l1a_tbf_synctimeslot_ID__enum,INFO_l1a_tbf_synctimeslot_ID_size

// INFO_l1a_2phase_start_pacch_ID
#define INFO_l1a_2phase_start_pacch_ID_size NULL
#define INFO_l1a_2phase_start_pacch_ID INFO_l1a_2phase_start_pacch_ID__enum,INFO_l1a_2phase_start_pacch_ID_size

// INFO_l1a_not_receive_singledl_ID
#define INFO_l1a_not_receive_singledl_ID_size NULL
#define INFO_l1a_not_receive_singledl_ID INFO_l1a_not_receive_singledl_ID__enum,INFO_l1a_not_receive_singledl_ID_size

// INFO_l1a_pbcch_usf_decode_ID
#define INFO_l1a_pbcch_usf_decode_ID_size "d"
#define INFO_l1a_pbcch_usf_decode_ID INFO_l1a_pbcch_usf_decode_ID__enum,INFO_l1a_pbcch_usf_decode_ID_size


#endif // L1A_TRACE_GEN.H
