#ifndef _L2R_TRC_GEN_H_
#define _L2R_TRC_GEN_H_

// IN_l2r_module_deinit
#define IN_l2r_module_deinit_size NULL
#define IN_l2r_module_deinit IN_l2r_module_deinit__enum,IN_l2r_module_deinit_size

// OUT_l2r_module_deinit
#define OUT_l2r_module_deinit_size NULL
#define OUT_l2r_module_deinit OUT_l2r_module_deinit__enum,OUT_l2r_module_deinit_size

// IN_l2r_module_init
#define IN_l2r_module_init_size NULL
#define IN_l2r_module_init IN_l2r_module_init__enum,IN_l2r_module_init_size

// OUT_l2r_module_init
#define OUT_l2r_module_init_size NULL
#define OUT_l2r_module_init OUT_l2r_module_init__enum,OUT_l2r_module_init_size

// IN_l2r_csm_activate_req_hdlr
#define IN_l2r_csm_activate_req_hdlr_size NULL
#define IN_l2r_csm_activate_req_hdlr IN_l2r_csm_activate_req_hdlr__enum,IN_l2r_csm_activate_req_hdlr_size

// OUT_l2r_csm_activate_req_hdlr
#define OUT_l2r_csm_activate_req_hdlr_size "d"
#define OUT_l2r_csm_activate_req_hdlr OUT_l2r_csm_activate_req_hdlr__enum,OUT_l2r_csm_activate_req_hdlr_size

// IN_l2r_rlp_conn_cnf_hdlr
#define IN_l2r_rlp_conn_cnf_hdlr_size NULL
#define IN_l2r_rlp_conn_cnf_hdlr IN_l2r_rlp_conn_cnf_hdlr__enum,IN_l2r_rlp_conn_cnf_hdlr_size

// OUT_l2r_rlp_conn_cnf_hdlr
#define OUT_l2r_rlp_conn_cnf_hdlr_size NULL
#define OUT_l2r_rlp_conn_cnf_hdlr OUT_l2r_rlp_conn_cnf_hdlr__enum,OUT_l2r_rlp_conn_cnf_hdlr_size

// IN_l2r_rlp_conn_ind_hdlr
#define IN_l2r_rlp_conn_ind_hdlr_size NULL
#define IN_l2r_rlp_conn_ind_hdlr IN_l2r_rlp_conn_ind_hdlr__enum,IN_l2r_rlp_conn_ind_hdlr_size

// OUT_l2r_rlp_conn_ind_hdlr
#define OUT_l2r_rlp_conn_ind_hdlr_size NULL
#define OUT_l2r_rlp_conn_ind_hdlr OUT_l2r_rlp_conn_ind_hdlr__enum,OUT_l2r_rlp_conn_ind_hdlr_size

// IN_l2r_rlp_xid_ind_hdlr
#define IN_l2r_rlp_xid_ind_hdlr_size NULL
#define IN_l2r_rlp_xid_ind_hdlr IN_l2r_rlp_xid_ind_hdlr__enum,IN_l2r_rlp_xid_ind_hdlr_size

// OUT_l2r_rlp_xid_ind_hdlr
#define OUT_l2r_rlp_xid_ind_hdlr_size "d"
#define OUT_l2r_rlp_xid_ind_hdlr OUT_l2r_rlp_xid_ind_hdlr__enum,OUT_l2r_rlp_xid_ind_hdlr_size

// IN_l2r_csm_deactivate_req_hdlr
#define IN_l2r_csm_deactivate_req_hdlr_size NULL
#define IN_l2r_csm_deactivate_req_hdlr IN_l2r_csm_deactivate_req_hdlr__enum,IN_l2r_csm_deactivate_req_hdlr_size

// OUT_l2r_csm_deactivate_req_hdlr
#define OUT_l2r_csm_deactivate_req_hdlr_size "d"
#define OUT_l2r_csm_deactivate_req_hdlr OUT_l2r_csm_deactivate_req_hdlr__enum,OUT_l2r_csm_deactivate_req_hdlr_size

// IN_l2r_rlp_disc_cnf_hdlr
#define IN_l2r_rlp_disc_cnf_hdlr_size NULL
#define IN_l2r_rlp_disc_cnf_hdlr IN_l2r_rlp_disc_cnf_hdlr__enum,IN_l2r_rlp_disc_cnf_hdlr_size

// OUT_l2r_rlp_disc_cnf_hdlr
#define OUT_l2r_rlp_disc_cnf_hdlr_size "d"
#define OUT_l2r_rlp_disc_cnf_hdlr OUT_l2r_rlp_disc_cnf_hdlr__enum,OUT_l2r_rlp_disc_cnf_hdlr_size

// IN_l2r_rlp_disc_ind_hdlr
#define IN_l2r_rlp_disc_ind_hdlr_size NULL
#define IN_l2r_rlp_disc_ind_hdlr IN_l2r_rlp_disc_ind_hdlr__enum,IN_l2r_rlp_disc_ind_hdlr_size

// OUT_l2r_rlp_disc_ind_hdlr
#define OUT_l2r_rlp_disc_ind_hdlr_size "d"
#define OUT_l2r_rlp_disc_ind_hdlr OUT_l2r_rlp_disc_ind_hdlr__enum,OUT_l2r_rlp_disc_ind_hdlr_size

// IN_l2r_rlp_detach_cnf_hdlr
#define IN_l2r_rlp_detach_cnf_hdlr_size NULL
#define IN_l2r_rlp_detach_cnf_hdlr IN_l2r_rlp_detach_cnf_hdlr__enum,IN_l2r_rlp_detach_cnf_hdlr_size

// OUT_l2r_rlp_detach_cnf_hdlr
#define OUT_l2r_rlp_detach_cnf_hdlr_size "d"
#define OUT_l2r_rlp_detach_cnf_hdlr OUT_l2r_rlp_detach_cnf_hdlr__enum,OUT_l2r_rlp_detach_cnf_hdlr_size

// IN_l2r_rlp_error_ind_hdlr
#define IN_l2r_rlp_error_ind_hdlr_size NULL
#define IN_l2r_rlp_error_ind_hdlr IN_l2r_rlp_error_ind_hdlr__enum,IN_l2r_rlp_error_ind_hdlr_size

// OUT_l2r_rlp_error_ind_hdlr
#define OUT_l2r_rlp_error_ind_hdlr_size "d"
#define OUT_l2r_rlp_error_ind_hdlr OUT_l2r_rlp_error_ind_hdlr__enum,OUT_l2r_rlp_error_ind_hdlr_size

// IN_l2r_rlp_reset_cnf_hdlr
#define IN_l2r_rlp_reset_cnf_hdlr_size NULL
#define IN_l2r_rlp_reset_cnf_hdlr IN_l2r_rlp_reset_cnf_hdlr__enum,IN_l2r_rlp_reset_cnf_hdlr_size

// OUT_l2r_rlp_reset_cnf_hdlr
#define OUT_l2r_rlp_reset_cnf_hdlr_size "d"
#define OUT_l2r_rlp_reset_cnf_hdlr OUT_l2r_rlp_reset_cnf_hdlr__enum,OUT_l2r_rlp_reset_cnf_hdlr_size

// IN_l2r_rlp_reset_ind_hdlr
#define IN_l2r_rlp_reset_ind_hdlr_size NULL
#define IN_l2r_rlp_reset_ind_hdlr IN_l2r_rlp_reset_ind_hdlr__enum,IN_l2r_rlp_reset_ind_hdlr_size

// OUT_l2r_rlp_reset_ind_hdlr
#define OUT_l2r_rlp_reset_ind_hdlr_size "d"
#define OUT_l2r_rlp_reset_ind_hdlr OUT_l2r_rlp_reset_ind_hdlr__enum,OUT_l2r_rlp_reset_ind_hdlr_size

// IN_l2r_rlp_data_ind_hdlr
#define IN_l2r_rlp_data_ind_hdlr_size NULL
#define IN_l2r_rlp_data_ind_hdlr IN_l2r_rlp_data_ind_hdlr__enum,IN_l2r_rlp_data_ind_hdlr_size

// OUT_l2r_rlp_data_ind_hdlr
#define OUT_l2r_rlp_data_ind_hdlr_size NULL
#define OUT_l2r_rlp_data_ind_hdlr OUT_l2r_rlp_data_ind_hdlr__enum,OUT_l2r_rlp_data_ind_hdlr_size

// IN_l2r_uart_ready_to_write_ind_hdlr
#define IN_l2r_uart_ready_to_write_ind_hdlr_size NULL
#define IN_l2r_uart_ready_to_write_ind_hdlr IN_l2r_uart_ready_to_write_ind_hdlr__enum,IN_l2r_uart_ready_to_write_ind_hdlr_size

// OUT_l2r_uart_ready_to_write_ind_hdlr
#define OUT_l2r_uart_ready_to_write_ind_hdlr_size "d"
#define OUT_l2r_uart_ready_to_write_ind_hdlr OUT_l2r_uart_ready_to_write_ind_hdlr__enum,OUT_l2r_uart_ready_to_write_ind_hdlr_size

// IN_l2r_rlp_ready_ind_hdlr
#define IN_l2r_rlp_ready_ind_hdlr_size NULL
#define IN_l2r_rlp_ready_ind_hdlr IN_l2r_rlp_ready_ind_hdlr__enum,IN_l2r_rlp_ready_ind_hdlr_size

// OUT_l2r_rlp_ready_ind_hdlr
#define OUT_l2r_rlp_ready_ind_hdlr_size "d"
#define OUT_l2r_rlp_ready_ind_hdlr OUT_l2r_rlp_ready_ind_hdlr__enum,OUT_l2r_rlp_ready_ind_hdlr_size

// IN_l2r_uart_ready_to_read_ind_hdlr
#define IN_l2r_uart_ready_to_read_ind_hdlr_size NULL
#define IN_l2r_uart_ready_to_read_ind_hdlr IN_l2r_uart_ready_to_read_ind_hdlr__enum,IN_l2r_uart_ready_to_read_ind_hdlr_size

// OUT_l2r_uart_ready_to_read_ind_hdlr
#define OUT_l2r_uart_ready_to_read_ind_hdlr_size NULL
#define OUT_l2r_uart_ready_to_read_ind_hdlr OUT_l2r_uart_ready_to_read_ind_hdlr__enum,OUT_l2r_uart_ready_to_read_ind_hdlr_size

// IN_l2r_uart_esc_on_ind_hdlr
#define IN_l2r_uart_esc_on_ind_hdlr_size NULL
#define IN_l2r_uart_esc_on_ind_hdlr IN_l2r_uart_esc_on_ind_hdlr__enum,IN_l2r_uart_esc_on_ind_hdlr_size

// OUT_l2r_uart_esc_on_ind_hdlr
#define OUT_l2r_uart_esc_on_ind_hdlr_size NULL
#define OUT_l2r_uart_esc_on_ind_hdlr OUT_l2r_uart_esc_on_ind_hdlr__enum,OUT_l2r_uart_esc_on_ind_hdlr_size

// IN_l2r_csm_esc_off_req_hdlr
#define IN_l2r_csm_esc_off_req_hdlr_size NULL
#define IN_l2r_csm_esc_off_req_hdlr IN_l2r_csm_esc_off_req_hdlr__enum,IN_l2r_csm_esc_off_req_hdlr_size

// OUT_l2r_csm_esc_off_req_hdlr
#define OUT_l2r_csm_esc_off_req_hdlr_size NULL
#define OUT_l2r_csm_esc_off_req_hdlr OUT_l2r_csm_esc_off_req_hdlr__enum,OUT_l2r_csm_esc_off_req_hdlr_size

// IN_l2r_csm_uart_setowner_req_hdlr
#define IN_l2r_csm_uart_setowner_req_hdlr_size NULL
#define IN_l2r_csm_uart_setowner_req_hdlr IN_l2r_csm_uart_setowner_req_hdlr__enum,IN_l2r_csm_uart_setowner_req_hdlr_size

// OUT_l2r_csm_uart_setowner_req_hdlr
#define OUT_l2r_csm_uart_setowner_req_hdlr_size NULL
#define OUT_l2r_csm_uart_setowner_req_hdlr OUT_l2r_csm_uart_setowner_req_hdlr__enum,OUT_l2r_csm_uart_setowner_req_hdlr_size

// IN_l2r_rlp_prepare_remap_ind_hdlr
#define IN_l2r_rlp_prepare_remap_ind_hdlr_size NULL
#define IN_l2r_rlp_prepare_remap_ind_hdlr IN_l2r_rlp_prepare_remap_ind_hdlr__enum,IN_l2r_rlp_prepare_remap_ind_hdlr_size

// OUT_l2r_rlp_prepare_remap_ind_hdlr
#define OUT_l2r_rlp_prepare_remap_ind_hdlr_size "d"
#define OUT_l2r_rlp_prepare_remap_ind_hdlr OUT_l2r_rlp_prepare_remap_ind_hdlr__enum,OUT_l2r_rlp_prepare_remap_ind_hdlr_size

// IN_l2r_rlp_remap_ind_hdlr
#define IN_l2r_rlp_remap_ind_hdlr_size NULL
#define IN_l2r_rlp_remap_ind_hdlr IN_l2r_rlp_remap_ind_hdlr__enum,IN_l2r_rlp_remap_ind_hdlr_size

// OUT_l2r_rlp_remap_ind_hdlr
#define OUT_l2r_rlp_remap_ind_hdlr_size "d"
#define OUT_l2r_rlp_remap_ind_hdlr OUT_l2r_rlp_remap_ind_hdlr__enum,OUT_l2r_rlp_remap_ind_hdlr_size

// IN_l2r_rlp_change_rate_ind_hdlr
#define IN_l2r_rlp_change_rate_ind_hdlr_size NULL
#define IN_l2r_rlp_change_rate_ind_hdlr IN_l2r_rlp_change_rate_ind_hdlr__enum,IN_l2r_rlp_change_rate_ind_hdlr_size

// OUT_l2r_rlp_change_rate_ind_hdlr
#define OUT_l2r_rlp_change_rate_ind_hdlr_size NULL
#define OUT_l2r_rlp_change_rate_ind_hdlr OUT_l2r_rlp_change_rate_ind_hdlr__enum,OUT_l2r_rlp_change_rate_ind_hdlr_size

// IN_l2r_frame_to_be_send_timer_expiry_hdlr
#define IN_l2r_frame_to_be_send_timer_expiry_hdlr_size NULL
#define IN_l2r_frame_to_be_send_timer_expiry_hdlr IN_l2r_frame_to_be_send_timer_expiry_hdlr__enum,IN_l2r_frame_to_be_send_timer_expiry_hdlr_size

// OUT_l2r_frame_to_be_send_timer_expiry_hdlr
#define OUT_l2r_frame_to_be_send_timer_expiry_hdlr_size NULL
#define OUT_l2r_frame_to_be_send_timer_expiry_hdlr OUT_l2r_frame_to_be_send_timer_expiry_hdlr__enum,OUT_l2r_frame_to_be_send_timer_expiry_hdlr_size

// IN_l2r_app_data_req_hdlr
#define IN_l2r_app_data_req_hdlr_size NULL
#define IN_l2r_app_data_req_hdlr IN_l2r_app_data_req_hdlr__enum,IN_l2r_app_data_req_hdlr_size

// OUT_l2r_app_data_req_hdlr
#define OUT_l2r_app_data_req_hdlr_size NULL
#define OUT_l2r_app_data_req_hdlr OUT_l2r_app_data_req_hdlr__enum,OUT_l2r_app_data_req_hdlr_size

// L2R_STATE
#define L2R_STATE_size "d"
#define L2R_STATE L2R_STATE__enum,L2R_STATE_size

// BREAK_DETECTED
#define BREAK_DETECTED_size NULL
#define BREAK_DETECTED BREAK_DETECTED__enum,BREAK_DETECTED_size

// L2R_UART_APP_FULL
#define L2R_UART_APP_FULL_size "‚d"
#define L2R_UART_APP_FULL L2R_UART_APP_FULL__enum,L2R_UART_APP_FULL_size

// L2R_DROP_DATA
#define L2R_DROP_DATA_size NULL
#define L2R_DROP_DATA L2R_DROP_DATA__enum,L2R_DROP_DATA_size

// L2R_ADAPTION_DROP_DATA
#define L2R_ADAPTION_DROP_DATA_size NULL
#define L2R_ADAPTION_DROP_DATA L2R_ADAPTION_DROP_DATA__enum,L2R_ADAPTION_DROP_DATA_size

// WRONG_STATE
#define WRONG_STATE_size "‚d"
#define WRONG_STATE WRONG_STATE__enum,WRONG_STATE_size

// initiate_flc_memory_error
#define initiate_flc_memory_error_size NULL
#define initiate_flc_memory_error initiate_flc_memory_error__enum,initiate_flc_memory_error_size

// NO_UPLINK_BUFF
#define NO_UPLINK_BUFF_size NULL
#define NO_UPLINK_BUFF NO_UPLINK_BUFF__enum,NO_UPLINK_BUFF_size

// receive_error_PDU
#define receive_error_PDU_size "‚d"
#define receive_error_PDU receive_error_PDU__enum,receive_error_PDU_size

// L2R_RECV_DISC_CNF_IN_DETACHED_STATE
#define L2R_RECV_DISC_CNF_IN_DETACHED_STATE_size NULL
#define L2R_RECV_DISC_CNF_IN_DETACHED_STATE L2R_RECV_DISC_CNF_IN_DETACHED_STATE__enum,L2R_RECV_DISC_CNF_IN_DETACHED_STATE_size


#endif // L2R_TRC_GEN.H
