#ifndef _MPAL_TRACE_GEN_H_
#define _MPAL_TRACE_GEN_H_

// ERROR_mpal_received_unexpected_msg_in_wrong_state
#define ERROR_mpal_received_unexpected_msg_in_wrong_state_size "hc"
#define ERROR_mpal_received_unexpected_msg_in_wrong_state ERROR_mpal_received_unexpected_msg_in_wrong_state__enum,ERROR_mpal_received_unexpected_msg_in_wrong_state_size

// GROUP2_QUEUE_MSG_REASON
#define GROUP2_QUEUE_MSG_REASON_size "c"
#define GROUP2_QUEUE_MSG_REASON GROUP2_QUEUE_MSG_REASON__enum,GROUP2_QUEUE_MSG_REASON_size

// GROUP2_DEQUEUE_MPAL_QUEUE
#define GROUP2_DEQUEUE_MPAL_QUEUE_size NULL
#define GROUP2_DEQUEUE_MPAL_QUEUE GROUP2_DEQUEUE_MPAL_QUEUE__enum,GROUP2_DEQUEUE_MPAL_QUEUE_size

// GROUP2_NUM_OF_MSG_IN_MPAL_QUEUE
#define GROUP2_NUM_OF_MSG_IN_MPAL_QUEUE_size "h"
#define GROUP2_NUM_OF_MSG_IN_MPAL_QUEUE GROUP2_NUM_OF_MSG_IN_MPAL_QUEUE__enum,GROUP2_NUM_OF_MSG_IN_MPAL_QUEUE_size

// ERROR_mpal_queue_full
#define ERROR_mpal_queue_full_size "ch"
#define ERROR_mpal_queue_full ERROR_mpal_queue_full__enum,ERROR_mpal_queue_full_size

// STATE_mpal_state
#define STATE_mpal_state_size "‚c"
#define STATE_mpal_state STATE_mpal_state__enum,STATE_mpal_state_size

// WARNING_mpal_mphc_power_scan_cnf_handler_ID
#define WARNING_mpal_mphc_power_scan_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_power_scan_cnf_handler_ID WARNING_mpal_mphc_power_scan_cnf_handler_ID__enum,WARNING_mpal_mphc_power_scan_cnf_handler_ID_size

// WARNING_mpal_mphc_manusel_pwrscan_cnf_handler_ID
#define WARNING_mpal_mphc_manusel_pwrscan_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_manusel_pwrscan_cnf_handler_ID WARNING_mpal_mphc_manusel_pwrscan_cnf_handler_ID__enum,WARNING_mpal_mphc_manusel_pwrscan_cnf_handler_ID_size

// WARNING_mpal_mphc_bsic_sync_cnf_handler_ID
#define WARNING_mpal_mphc_bsic_sync_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_bsic_sync_cnf_handler_ID WARNING_mpal_mphc_bsic_sync_cnf_handler_ID__enum,WARNING_mpal_mphc_bsic_sync_cnf_handler_ID_size

// WARNING_mpal_mphc_unitdata_ind_handler_ID
#define WARNING_mpal_mphc_unitdata_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_unitdata_ind_handler_ID WARNING_mpal_mphc_unitdata_ind_handler_ID__enum,WARNING_mpal_mphc_unitdata_ind_handler_ID_size

// WARNING_mpal_mphc_block_quality_ind_handler_ID
#define WARNING_mpal_mphc_block_quality_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_block_quality_ind_handler_ID WARNING_mpal_mphc_block_quality_ind_handler_ID__enum,WARNING_mpal_mphc_block_quality_ind_handler_ID_size

// WARNING_mpal_mphc_random_access_cnf_handler_ID
#define WARNING_mpal_mphc_random_access_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_random_access_cnf_handler_ID WARNING_mpal_mphc_random_access_cnf_handler_ID__enum,WARNING_mpal_mphc_random_access_cnf_handler_ID_size

// WARNING_mpal_mphc_immed_assign_cnf_handler_ID
#define WARNING_mpal_mphc_immed_assign_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_immed_assign_cnf_handler_ID WARNING_mpal_mphc_immed_assign_cnf_handler_ID__enum,WARNING_mpal_mphc_immed_assign_cnf_handler_ID_size

// WARNING_mpal_mphc_channel_assign_cnf_handler_ID
#define WARNING_mpal_mphc_channel_assign_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_channel_assign_cnf_handler_ID WARNING_mpal_mphc_channel_assign_cnf_handler_ID__enum,WARNING_mpal_mphc_channel_assign_cnf_handler_ID_size

// WARNING_mpal_mphc_channel_release_cnf_handler_ID
#define WARNING_mpal_mphc_channel_release_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_channel_release_cnf_handler_ID WARNING_mpal_mphc_channel_release_cnf_handler_ID__enum,WARNING_mpal_mphc_channel_release_cnf_handler_ID_size

// WARNING_mpal_mphc_handover_cnf_handler_ID
#define WARNING_mpal_mphc_handover_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_handover_cnf_handler_ID WARNING_mpal_mphc_handover_cnf_handler_ID__enum,WARNING_mpal_mphc_handover_cnf_handler_ID_size

// WARNING_mpal_mphc_handover_access_start_ind_handler_ID
#define WARNING_mpal_mphc_handover_access_start_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_handover_access_start_ind_handler_ID WARNING_mpal_mphc_handover_access_start_ind_handler_ID__enum,WARNING_mpal_mphc_handover_access_start_ind_handler_ID_size

// WARNING_mpal_mphc_handover_connected_ind_handler_ID
#define WARNING_mpal_mphc_handover_connected_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_handover_connected_ind_handler_ID WARNING_mpal_mphc_handover_connected_ind_handler_ID__enum,WARNING_mpal_mphc_handover_connected_ind_handler_ID_size

// WARNING_mpal_mphc_handover_access_stop_cnf_handler_ID
#define WARNING_mpal_mphc_handover_access_stop_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_handover_access_stop_cnf_handler_ID WARNING_mpal_mphc_handover_access_stop_cnf_handler_ID__enum,WARNING_mpal_mphc_handover_access_stop_cnf_handler_ID_size

// WARNING_mpal_mphc_channel_reconnect_cnf_handler_ID
#define WARNING_mpal_mphc_channel_reconnect_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_channel_reconnect_cnf_handler_ID WARNING_mpal_mphc_channel_reconnect_cnf_handler_ID__enum,WARNING_mpal_mphc_channel_reconnect_cnf_handler_ID_size

// WARNING_mpal_mphc_frequency_redefinition_cnf_handler_ID
#define WARNING_mpal_mphc_frequency_redefinition_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_frequency_redefinition_cnf_handler_ID WARNING_mpal_mphc_frequency_redefinition_cnf_handler_ID__enum,WARNING_mpal_mphc_frequency_redefinition_cnf_handler_ID_size

// WARNING_mpal_mphc_channel_mode_modify_cnf_handler_ID
#define WARNING_mpal_mphc_channel_mode_modify_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_channel_mode_modify_cnf_handler_ID WARNING_mpal_mphc_channel_mode_modify_cnf_handler_ID__enum,WARNING_mpal_mphc_channel_mode_modify_cnf_handler_ID_size

// WARNING_mpal_mphc_ciphering_mode_command_cnf_handler_ID
#define WARNING_mpal_mphc_ciphering_mode_command_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_ciphering_mode_command_cnf_handler_ID WARNING_mpal_mphc_ciphering_mode_command_cnf_handler_ID__enum,WARNING_mpal_mphc_ciphering_mode_command_cnf_handler_ID_size

// WARNING_mpal_mphc_close_tch_loop_cnf_handler_ID
#define WARNING_mpal_mphc_close_tch_loop_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_close_tch_loop_cnf_handler_ID WARNING_mpal_mphc_close_tch_loop_cnf_handler_ID__enum,WARNING_mpal_mphc_close_tch_loop_cnf_handler_ID_size

// WARNING_mpal_mphc_open_tch_loop_cnf_handler_ID
#define WARNING_mpal_mphc_open_tch_loop_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_open_tch_loop_cnf_handler_ID WARNING_mpal_mphc_open_tch_loop_cnf_handler_ID__enum,WARNING_mpal_mphc_open_tch_loop_cnf_handler_ID_size

// WARNING_mpal_mphc_deactivate_cnf_handler_ID
#define WARNING_mpal_mphc_deactivate_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_deactivate_cnf_handler_ID WARNING_mpal_mphc_deactivate_cnf_handler_ID__enum,WARNING_mpal_mphc_deactivate_cnf_handler_ID_size

// WARNING_mpal_mphc_extended_meas_ind_handler_ID
#define WARNING_mpal_mphc_extended_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_extended_meas_ind_handler_ID WARNING_mpal_mphc_extended_meas_ind_handler_ID__enum,WARNING_mpal_mphc_extended_meas_ind_handler_ID_size

// WARNING_mpal_mphc_serv_idle_meas_ind_handler_ID
#define WARNING_mpal_mphc_serv_idle_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_serv_idle_meas_ind_handler_ID WARNING_mpal_mphc_serv_idle_meas_ind_handler_ID__enum,WARNING_mpal_mphc_serv_idle_meas_ind_handler_ID_size

// WARNING_mpal_mphc_serv_dedi_meas_ind_handler_ID
#define WARNING_mpal_mphc_serv_dedi_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_serv_dedi_meas_ind_handler_ID WARNING_mpal_mphc_serv_dedi_meas_ind_handler_ID__enum,WARNING_mpal_mphc_serv_dedi_meas_ind_handler_ID_size

// WARNING_mpal_neighbor_meas_ind_handler_ID
#define WARNING_mpal_neighbor_meas_ind_handler_ID_size NULL
#define WARNING_mpal_neighbor_meas_ind_handler_ID WARNING_mpal_neighbor_meas_ind_handler_ID__enum,WARNING_mpal_neighbor_meas_ind_handler_ID_size

// WARNING_mpal_mphc_neighbor_bsic_ind_handler_ID
#define WARNING_mpal_mphc_neighbor_bsic_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_neighbor_bsic_ind_handler_ID WARNING_mpal_mphc_neighbor_bsic_ind_handler_ID__enum,WARNING_mpal_mphc_neighbor_bsic_ind_handler_ID_size

// WARNING_mpal_mphc_cell_bsic_ind_handler_ID
#define WARNING_mpal_mphc_cell_bsic_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_cell_bsic_ind_handler_ID WARNING_mpal_mphc_cell_bsic_ind_handler_ID__enum,WARNING_mpal_mphc_cell_bsic_ind_handler_ID_size

// WARNING_mpal_mphc_cell_selection_init_cnf_handler_ID
#define WARNING_mpal_mphc_cell_selection_init_cnf_handler_ID_size NULL
#define WARNING_mpal_mphc_cell_selection_init_cnf_handler_ID WARNING_mpal_mphc_cell_selection_init_cnf_handler_ID__enum,WARNING_mpal_mphc_cell_selection_init_cnf_handler_ID_size

// WARNING_mpal_mphc_blind_handover_bsic_ind_handler_ID
#define WARNING_mpal_mphc_blind_handover_bsic_ind_handler_ID_size NULL
#define WARNING_mpal_mphc_blind_handover_bsic_ind_handler_ID WARNING_mpal_mphc_blind_handover_bsic_ind_handler_ID__enum,WARNING_mpal_mphc_blind_handover_bsic_ind_handler_ID_size

// GROUP1_mpal_sacch_downlink_ID
#define GROUP1_mpal_sacch_downlink_ID_size NULL
#define GROUP1_mpal_sacch_downlink_ID GROUP1_mpal_sacch_downlink_ID__enum,GROUP1_mpal_sacch_downlink_ID_size

// GROUP1_mpal_facch_downlink_ID
#define GROUP1_mpal_facch_downlink_ID_size NULL
#define GROUP1_mpal_facch_downlink_ID GROUP1_mpal_facch_downlink_ID__enum,GROUP1_mpal_facch_downlink_ID_size

// GROUP1_mpal_sdcch_downlink_ID
#define GROUP1_mpal_sdcch_downlink_ID_size NULL
#define GROUP1_mpal_sdcch_downlink_ID GROUP1_mpal_sdcch_downlink_ID__enum,GROUP1_mpal_sdcch_downlink_ID_size

// WARNING_mpal_timer_expiry_handler_ID
#define WARNING_mpal_timer_expiry_handler_ID_size NULL
#define WARNING_mpal_timer_expiry_handler_ID WARNING_mpal_timer_expiry_handler_ID__enum,WARNING_mpal_timer_expiry_handler_ID_size

// WARNING_mpal_packet_downlink_common_ID_RR
#define WARNING_mpal_packet_downlink_common_ID_RR_size "h"
#define WARNING_mpal_packet_downlink_common_ID_RR WARNING_mpal_packet_downlink_common_ID_RR__enum,WARNING_mpal_packet_downlink_common_ID_RR_size

// WARNING_mpal_packet_downlink_common_ID_L1
#define WARNING_mpal_packet_downlink_common_ID_L1_size NULL
#define WARNING_mpal_packet_downlink_common_ID_L1 WARNING_mpal_packet_downlink_common_ID_L1__enum,WARNING_mpal_packet_downlink_common_ID_L1_size

// GROUP4_mtbf_put_into_data_tbf_index
#define GROUP4_mtbf_put_into_data_tbf_index_size "h"
#define GROUP4_mtbf_put_into_data_tbf_index GROUP4_mtbf_put_into_data_tbf_index__enum,GROUP4_mtbf_put_into_data_tbf_index_size

// GROUP4_mtbf_flush_tbf_index
#define GROUP4_mtbf_flush_tbf_index_size "h"
#define GROUP4_mtbf_flush_tbf_index GROUP4_mtbf_flush_tbf_index__enum,GROUP4_mtbf_flush_tbf_index_size

// WARNING_is_ta_valid
#define WARNING_is_ta_valid_size NULL
#define WARNING_is_ta_valid WARNING_is_ta_valid__enum,WARNING_is_ta_valid_size

// GROUP4_ctrl_blks_to_l1
#define GROUP4_ctrl_blks_to_l1_size "h"
#define GROUP4_ctrl_blks_to_l1 GROUP4_ctrl_blks_to_l1__enum,GROUP4_ctrl_blks_to_l1_size

// GROUP4_data_blks_to_l1
#define GROUP4_data_blks_to_l1_size "h"
#define GROUP4_data_blks_to_l1 GROUP4_data_blks_to_l1__enum,GROUP4_data_blks_to_l1_size

// WARNING_is_rrbp_fail_to_send
#define WARNING_is_rrbp_fail_to_send_size NULL
#define WARNING_is_rrbp_fail_to_send WARNING_is_rrbp_fail_to_send__enum,WARNING_is_rrbp_fail_to_send_size

// GROUP4_rrbp_timeslot_mask
#define GROUP4_rrbp_timeslot_mask_size "h"
#define GROUP4_rrbp_timeslot_mask GROUP4_rrbp_timeslot_mask__enum,GROUP4_rrbp_timeslot_mask_size

// GROUP5_fn_from_l1c
#define GROUP5_fn_from_l1c_size "d"
#define GROUP5_fn_from_l1c GROUP5_fn_from_l1c__enum,GROUP5_fn_from_l1c_size

// GROUP5_rrbp_frame_number
#define GROUP5_rrbp_frame_number_size "d"
#define GROUP5_rrbp_frame_number GROUP5_rrbp_frame_number__enum,GROUP5_rrbp_frame_number_size

// GROUP5_no_of_rrbp_from_mac
#define GROUP5_no_of_rrbp_from_mac_size "h"
#define GROUP5_no_of_rrbp_from_mac GROUP5_no_of_rrbp_from_mac__enum,GROUP5_no_of_rrbp_from_mac_size

// GROUP4_mtbf_rrbp_index
#define GROUP4_mtbf_rrbp_index_size "h"
#define GROUP4_mtbf_rrbp_index GROUP4_mtbf_rrbp_index__enum,GROUP4_mtbf_rrbp_index_size

// GROUP5_mtbf_no_data_ctrl_txed_in_rrbp_index
#define GROUP5_mtbf_no_data_ctrl_txed_in_rrbp_index_size "h"
#define GROUP5_mtbf_no_data_ctrl_txed_in_rrbp_index GROUP5_mtbf_no_data_ctrl_txed_in_rrbp_index__enum,GROUP5_mtbf_no_data_ctrl_txed_in_rrbp_index_size

// GROUP4_mtbf_no_ctrl_txed_in_rrbp_index
#define GROUP4_mtbf_no_ctrl_txed_in_rrbp_index_size "h"
#define GROUP4_mtbf_no_ctrl_txed_in_rrbp_index GROUP4_mtbf_no_ctrl_txed_in_rrbp_index__enum,GROUP4_mtbf_no_ctrl_txed_in_rrbp_index_size

// GROUP4_mtbf_no_data_txed_in_rrbp_index
#define GROUP4_mtbf_no_data_txed_in_rrbp_index_size "h"
#define GROUP4_mtbf_no_data_txed_in_rrbp_index GROUP4_mtbf_no_data_txed_in_rrbp_index__enum,GROUP4_mtbf_no_data_txed_in_rrbp_index_size

// GROUP4_mtbf_flush_happened
#define GROUP4_mtbf_flush_happened_size NULL
#define GROUP4_mtbf_flush_happened GROUP4_mtbf_flush_happened__enum,GROUP4_mtbf_flush_happened_size

// GROUP5_mtbf_no_data_txed
#define GROUP5_mtbf_no_data_txed_size "h"
#define GROUP5_mtbf_no_data_txed GROUP5_mtbf_no_data_txed__enum,GROUP5_mtbf_no_data_txed_size

// WARNING_mpal_mphp_packet_data_ind_handler_ID
#define WARNING_mpal_mphp_packet_data_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_data_ind_handler_ID WARNING_mpal_mphp_packet_data_ind_handler_ID__enum,WARNING_mpal_mphp_packet_data_ind_handler_ID_size

// WARNING_mpal_mphp_packet_block_quality_ind_handler_ID
#define WARNING_mpal_mphp_packet_block_quality_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_block_quality_ind_handler_ID WARNING_mpal_mphp_packet_block_quality_ind_handler_ID__enum,WARNING_mpal_mphp_packet_block_quality_ind_handler_ID_size

// WARNING_mpal_mphp_packet_serv_meas_ind_handler_ID
#define WARNING_mpal_mphp_packet_serv_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_serv_meas_ind_handler_ID WARNING_mpal_mphp_packet_serv_meas_ind_handler_ID__enum,WARNING_mpal_mphp_packet_serv_meas_ind_handler_ID_size

// WARNING_mpal_mphp_packet_nc_meas_ind_handler_ID
#define WARNING_mpal_mphp_packet_nc_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_nc_meas_ind_handler_ID WARNING_mpal_mphp_packet_nc_meas_ind_handler_ID__enum,WARNING_mpal_mphp_packet_nc_meas_ind_handler_ID_size

// WARNING_mpal_mphp_interference_meas_ind_handler_ID
#define WARNING_mpal_mphp_interference_meas_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_interference_meas_ind_handler_ID WARNING_mpal_mphp_interference_meas_ind_handler_ID__enum,WARNING_mpal_mphp_interference_meas_ind_handler_ID_size

// WARNING_mpal_mphp_poll_response_cnf_handler_ID
#define WARNING_mpal_mphp_poll_response_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_poll_response_cnf_handler_ID WARNING_mpal_mphp_poll_response_cnf_handler_ID__enum,WARNING_mpal_mphp_poll_response_cnf_handler_ID_size

// WARNING_mpal_mphp_packet_random_access_cnf_handler_ID
#define WARNING_mpal_mphp_packet_random_access_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_random_access_cnf_handler_ID WARNING_mpal_mphp_packet_random_access_cnf_handler_ID__enum,WARNING_mpal_mphp_packet_random_access_cnf_handler_ID_size

// WARNING_mpal_mphp_packet_uplink_assignment_cnf_handler_ID
#define WARNING_mpal_mphp_packet_uplink_assignment_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_uplink_assignment_cnf_handler_ID WARNING_mpal_mphp_packet_uplink_assignment_cnf_handler_ID__enum,WARNING_mpal_mphp_packet_uplink_assignment_cnf_handler_ID_size

// WARNING_mpal_mphp_uplink_single_block_cnf_handler_ID
#define WARNING_mpal_mphp_uplink_single_block_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_uplink_single_block_cnf_handler_ID WARNING_mpal_mphp_uplink_single_block_cnf_handler_ID__enum,WARNING_mpal_mphp_uplink_single_block_cnf_handler_ID_size

// WARNING_mpal_mphp_packet_downlink_assignment_cnf_handler_ID
#define WARNING_mpal_mphp_packet_downlink_assignment_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_downlink_assignment_cnf_handler_ID WARNING_mpal_mphp_packet_downlink_assignment_cnf_handler_ID__enum,WARNING_mpal_mphp_packet_downlink_assignment_cnf_handler_ID_size

// WARNING_mpal_mphp_downlink_single_block_cnf_handler_ID
#define WARNING_mpal_mphp_downlink_single_block_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_downlink_single_block_cnf_handler_ID WARNING_mpal_mphp_downlink_single_block_cnf_handler_ID__enum,WARNING_mpal_mphp_downlink_single_block_cnf_handler_ID_size

// WARNING_mpal_mphp_packet_timeslot_reconfigure_cnf_handler_ID
#define WARNING_mpal_mphp_packet_timeslot_reconfigure_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_timeslot_reconfigure_cnf_handler_ID WARNING_mpal_mphp_packet_timeslot_reconfigure_cnf_handler_ID__enum,WARNING_mpal_mphp_packet_timeslot_reconfigure_cnf_handler_ID_size

// WARNING_mpal_mphp_repeat_allocation_ind_handler_ID
#define WARNING_mpal_mphp_repeat_allocation_ind_handler_ID_size NULL
#define WARNING_mpal_mphp_repeat_allocation_ind_handler_ID WARNING_mpal_mphp_repeat_allocation_ind_handler_ID__enum,WARNING_mpal_mphp_repeat_allocation_ind_handler_ID_size

// WARNING_mpal_mphp_packet_unassignment_cnf_handler_ID
#define WARNING_mpal_mphp_packet_unassignment_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_packet_unassignment_cnf_handler_ID WARNING_mpal_mphp_packet_unassignment_cnf_handler_ID__enum,WARNING_mpal_mphp_packet_unassignment_cnf_handler_ID_size

// WARNING_mpal_mphp_pdch_fail_reconnect_cnf_handler_ID
#define WARNING_mpal_mphp_pdch_fail_reconnect_cnf_handler_ID_size NULL
#define WARNING_mpal_mphp_pdch_fail_reconnect_cnf_handler_ID WARNING_mpal_mphp_pdch_fail_reconnect_cnf_handler_ID__enum,WARNING_mpal_mphp_pdch_fail_reconnect_cnf_handler_ID_size


#endif // MPAL_TRACE_GEN.H
