#ifndef _NTPD_TRC_GEN_H_
#define _NTPD_TRC_GEN_H_

// FUNC_NTPD_NETWORK_INIT
#define FUNC_NTPD_NETWORK_INIT_size NULL
#define FUNC_NTPD_NETWORK_INIT FUNC_NTPD_NETWORK_INIT__enum,FUNC_NTPD_NETWORK_INIT_size

// FUNC_NTPD_CREATE_MEM
#define FUNC_NTPD_CREATE_MEM_size NULL
#define FUNC_NTPD_CREATE_MEM FUNC_NTPD_CREATE_MEM__enum,FUNC_NTPD_CREATE_MEM_size

// FUNC_NTPD_NOTIFY_APP
#define FUNC_NTPD_NOTIFY_APP_size NULL
#define FUNC_NTPD_NOTIFY_APP FUNC_NTPD_NOTIFY_APP__enum,FUNC_NTPD_NOTIFY_APP_size

// FUNC_NTPD_ADD_SERVER
#define FUNC_NTPD_ADD_SERVER_size NULL
#define FUNC_NTPD_ADD_SERVER FUNC_NTPD_ADD_SERVER__enum,FUNC_NTPD_ADD_SERVER_size

// FUNC_NTPD_SERVER_SEND
#define FUNC_NTPD_SERVER_SEND_size NULL
#define FUNC_NTPD_SERVER_SEND FUNC_NTPD_SERVER_SEND__enum,FUNC_NTPD_SERVER_SEND_size

// FUNC_NTPD_FIND_SERVER
#define FUNC_NTPD_FIND_SERVER_size NULL
#define FUNC_NTPD_FIND_SERVER FUNC_NTPD_FIND_SERVER__enum,FUNC_NTPD_FIND_SERVER_size

// FUNC_NTPD_RECV_PROC
#define FUNC_NTPD_RECV_PROC_size NULL
#define FUNC_NTPD_RECV_PROC FUNC_NTPD_RECV_PROC__enum,FUNC_NTPD_RECV_PROC_size

// FUNC_NTPD_RECV_PROC_NO
#define FUNC_NTPD_RECV_PROC_NO_size "d"
#define FUNC_NTPD_RECV_PROC_NO FUNC_NTPD_RECV_PROC_NO__enum,FUNC_NTPD_RECV_PROC_NO_size

// FUNC_NTPD_INPUT
#define FUNC_NTPD_INPUT_size NULL
#define FUNC_NTPD_INPUT FUNC_NTPD_INPUT__enum,FUNC_NTPD_INPUT_size

// FUNC_NTPD_HDLR_SOC_NOTIFY_IND
#define FUNC_NTPD_HDLR_SOC_NOTIFY_IND_size "d"
#define FUNC_NTPD_HDLR_SOC_NOTIFY_IND FUNC_NTPD_HDLR_SOC_NOTIFY_IND__enum,FUNC_NTPD_HDLR_SOC_NOTIFY_IND_size

// FUNC_NTPD_HDLR_BEARER_INFO_IND
#define FUNC_NTPD_HDLR_BEARER_INFO_IND_size "d"
#define FUNC_NTPD_HDLR_BEARER_INFO_IND FUNC_NTPD_HDLR_BEARER_INFO_IND__enum,FUNC_NTPD_HDLR_BEARER_INFO_IND_size

// FUNC_NTPD_START_TIMER
#define FUNC_NTPD_START_TIMER_size NULL
#define FUNC_NTPD_START_TIMER FUNC_NTPD_START_TIMER__enum,FUNC_NTPD_START_TIMER_size

// FUNC_NTPD_SEND_PACKET
#define FUNC_NTPD_SEND_PACKET_size NULL
#define FUNC_NTPD_SEND_PACKET FUNC_NTPD_SEND_PACKET__enum,FUNC_NTPD_SEND_PACKET_size

// FUNC_NTP_TRANSMIT_PACKET
#define FUNC_NTP_TRANSMIT_PACKET_size NULL
#define FUNC_NTP_TRANSMIT_PACKET FUNC_NTP_TRANSMIT_PACKET__enum,FUNC_NTP_TRANSMIT_PACKET_size

// FUNC_NTP_TRANSMIT_PACKET_NO
#define FUNC_NTP_TRANSMIT_PACKET_NO_size "d"
#define FUNC_NTP_TRANSMIT_PACKET_NO FUNC_NTP_TRANSMIT_PACKET_NO__enum,FUNC_NTP_TRANSMIT_PACKET_NO_size

// FUNC_NTPD_HDLR_GET_HOST_BY_NAME_IND
#define FUNC_NTPD_HDLR_GET_HOST_BY_NAME_IND_size NULL
#define FUNC_NTPD_HDLR_GET_HOST_BY_NAME_IND FUNC_NTPD_HDLR_GET_HOST_BY_NAME_IND__enum,FUNC_NTPD_HDLR_GET_HOST_BY_NAME_IND_size

// FUNC_NTPD_HDLR_GET_HOST_NO
#define FUNC_NTPD_HDLR_GET_HOST_NO_size "d"
#define FUNC_NTPD_HDLR_GET_HOST_NO FUNC_NTPD_HDLR_GET_HOST_NO__enum,FUNC_NTPD_HDLR_GET_HOST_NO_size

// FUNC_NTPD_GETHOSTBYNAME
#define FUNC_NTPD_GETHOSTBYNAME_size NULL
#define FUNC_NTPD_GETHOSTBYNAME FUNC_NTPD_GETHOSTBYNAME__enum,FUNC_NTPD_GETHOSTBYNAME_size

// FUNC_NTPD_GETHOSTBYNAME_NO
#define FUNC_NTPD_GETHOSTBYNAME_NO_size "d"
#define FUNC_NTPD_GETHOSTBYNAME_NO FUNC_NTPD_GETHOSTBYNAME_NO__enum,FUNC_NTPD_GETHOSTBYNAME_NO_size

// FUNC_NTPD_CREATE_SOCKET
#define FUNC_NTPD_CREATE_SOCKET_size NULL
#define FUNC_NTPD_CREATE_SOCKET FUNC_NTPD_CREATE_SOCKET__enum,FUNC_NTPD_CREATE_SOCKET_size

// FUNC_NTPD_SOCKET_BIND
#define FUNC_NTPD_SOCKET_BIND_size NULL
#define FUNC_NTPD_SOCKET_BIND FUNC_NTPD_SOCKET_BIND__enum,FUNC_NTPD_SOCKET_BIND_size

// FUNC_NTPD_SOCKET_BIND_NO
#define FUNC_NTPD_SOCKET_BIND_NO_size "d"
#define FUNC_NTPD_SOCKET_BIND_NO FUNC_NTPD_SOCKET_BIND_NO__enum,FUNC_NTPD_SOCKET_BIND_NO_size

// FUNC_NTPD_OPEN
#define FUNC_NTPD_OPEN_size NULL
#define FUNC_NTPD_OPEN FUNC_NTPD_OPEN__enum,FUNC_NTPD_OPEN_size

// FUNC_NTPD_OPEN_NO
#define FUNC_NTPD_OPEN_NO_size "d"
#define FUNC_NTPD_OPEN_NO FUNC_NTPD_OPEN_NO__enum,FUNC_NTPD_OPEN_NO_size

// FUNC_NTPD_SYNC
#define FUNC_NTPD_SYNC_size NULL
#define FUNC_NTPD_SYNC FUNC_NTPD_SYNC__enum,FUNC_NTPD_SYNC_size

// FUNC_NTPD_SYNC_NO
#define FUNC_NTPD_SYNC_NO_size "d"
#define FUNC_NTPD_SYNC_NO FUNC_NTPD_SYNC_NO__enum,FUNC_NTPD_SYNC_NO_size

// FUNC_NTPD_SERVER_SYNC
#define FUNC_NTPD_SERVER_SYNC_size NULL
#define FUNC_NTPD_SERVER_SYNC FUNC_NTPD_SERVER_SYNC__enum,FUNC_NTPD_SERVER_SYNC_size

// FUNC_NTPD_SERVER_SYNC_NO
#define FUNC_NTPD_SERVER_SYNC_NO_size "d"
#define FUNC_NTPD_SERVER_SYNC_NO FUNC_NTPD_SERVER_SYNC_NO__enum,FUNC_NTPD_SERVER_SYNC_NO_size

// FUNC_NTPD_SYNC_ABORT
#define FUNC_NTPD_SYNC_ABORT_size NULL
#define FUNC_NTPD_SYNC_ABORT FUNC_NTPD_SYNC_ABORT__enum,FUNC_NTPD_SYNC_ABORT_size

// FUNC_NTPD_CLOSE
#define FUNC_NTPD_CLOSE_size NULL
#define FUNC_NTPD_CLOSE FUNC_NTPD_CLOSE__enum,FUNC_NTPD_CLOSE_size

// NTPD_ENTER_CLOCK_FILTER
#define NTPD_ENTER_CLOCK_FILTER_size "‚d"
#define NTPD_ENTER_CLOCK_FILTER NTPD_ENTER_CLOCK_FILTER__enum,NTPD_ENTER_CLOCK_FILTER_size

// NTPD_CLOCK_FILTER_OFFSET
#define NTPD_CLOCK_FILTER_OFFSET_size "‚d"
#define NTPD_CLOCK_FILTER_OFFSET NTPD_CLOCK_FILTER_OFFSET__enum,NTPD_CLOCK_FILTER_OFFSET_size

// NTPD_PEER_DISPERSION
#define NTPD_PEER_DISPERSION_size "d"
#define NTPD_PEER_DISPERSION NTPD_PEER_DISPERSION__enum,NTPD_PEER_DISPERSION_size

// NTPD_REACH_NUM
#define NTPD_REACH_NUM_size "d"
#define NTPD_REACH_NUM NTPD_REACH_NUM__enum,NTPD_REACH_NUM_size

// NTPD_ENTER_CLOCK_INTERSECTION
#define NTPD_ENTER_CLOCK_INTERSECTION_size NULL
#define NTPD_ENTER_CLOCK_INTERSECTION NTPD_ENTER_CLOCK_INTERSECTION__enum,NTPD_ENTER_CLOCK_INTERSECTION_size

// NTPD_CLOCK_SELECT_OFFSET
#define NTPD_CLOCK_SELECT_OFFSET_size "‚d"
#define NTPD_CLOCK_SELECT_OFFSET NTPD_CLOCK_SELECT_OFFSET__enum,NTPD_CLOCK_SELECT_OFFSET_size

// NTPD_CLOCK_INTERSECTION_BOUNDARY
#define NTPD_CLOCK_INTERSECTION_BOUNDARY_size "‚d"
#define NTPD_CLOCK_INTERSECTION_BOUNDARY NTPD_CLOCK_INTERSECTION_BOUNDARY__enum,NTPD_CLOCK_INTERSECTION_BOUNDARY_size

// NTPD_CLOCK_INTERSECTION_NO_SERVER
#define NTPD_CLOCK_INTERSECTION_NO_SERVER_size NULL
#define NTPD_CLOCK_INTERSECTION_NO_SERVER NTPD_CLOCK_INTERSECTION_NO_SERVER__enum,NTPD_CLOCK_INTERSECTION_NO_SERVER_size

// NTPD_ENTER_CLOCK_CLUSTER_SELECT
#define NTPD_ENTER_CLOCK_CLUSTER_SELECT_size NULL
#define NTPD_ENTER_CLOCK_CLUSTER_SELECT NTPD_ENTER_CLOCK_CLUSTER_SELECT__enum,NTPD_ENTER_CLOCK_CLUSTER_SELECT_size

// NTPD_CLOCK_CLUSTER_SELECT_NO_SERVER
#define NTPD_CLOCK_CLUSTER_SELECT_NO_SERVER_size NULL
#define NTPD_CLOCK_CLUSTER_SELECT_NO_SERVER NTPD_CLOCK_CLUSTER_SELECT_NO_SERVER__enum,NTPD_CLOCK_CLUSTER_SELECT_NO_SERVER_size

// NTPD_ENTER_CLOCK_SLECT
#define NTPD_ENTER_CLOCK_SLECT_size NULL
#define NTPD_ENTER_CLOCK_SLECT NTPD_ENTER_CLOCK_SLECT__enum,NTPD_ENTER_CLOCK_SLECT_size

// NTPD_SELECT_SYNC_SERVER
#define NTPD_SELECT_SYNC_SERVER_size "d"
#define NTPD_SELECT_SYNC_SERVER NTPD_SELECT_SYNC_SERVER__enum,NTPD_SELECT_SYNC_SERVER_size

// NTPD_RECV_TIMESTAMP_ORG
#define NTPD_RECV_TIMESTAMP_ORG_size "‚d"
#define NTPD_RECV_TIMESTAMP_ORG NTPD_RECV_TIMESTAMP_ORG__enum,NTPD_RECV_TIMESTAMP_ORG_size

// NTPD_RECV_TIMESTAMP_REC
#define NTPD_RECV_TIMESTAMP_REC_size "‚d"
#define NTPD_RECV_TIMESTAMP_REC NTPD_RECV_TIMESTAMP_REC__enum,NTPD_RECV_TIMESTAMP_REC_size

// NTPD_RECV_TIMESTAMP_SORG
#define NTPD_RECV_TIMESTAMP_SORG_size "‚d"
#define NTPD_RECV_TIMESTAMP_SORG NTPD_RECV_TIMESTAMP_SORG__enum,NTPD_RECV_TIMESTAMP_SORG_size

// NTPD_RECV_TIMESTAMP_DEST
#define NTPD_RECV_TIMESTAMP_DEST_size "‚d"
#define NTPD_RECV_TIMESTAMP_DEST NTPD_RECV_TIMESTAMP_DEST__enum,NTPD_RECV_TIMESTAMP_DEST_size

// SRV_NTP_INIT
#define SRV_NTP_INIT_size "d"
#define SRV_NTP_INIT SRV_NTP_INIT__enum,SRV_NTP_INIT_size

// SRV_NTP_CONFIG_INIT
#define SRV_NTP_CONFIG_INIT_size "d"
#define SRV_NTP_CONFIG_INIT SRV_NTP_CONFIG_INIT__enum,SRV_NTP_CONFIG_INIT_size

// SRV_NTP_SYS_DRIVE_INIT
#define SRV_NTP_SYS_DRIVE_INIT_size "c"
#define SRV_NTP_SYS_DRIVE_INIT SRV_NTP_SYS_DRIVE_INIT__enum,SRV_NTP_SYS_DRIVE_INIT_size

// SRV_NTP_APP_ID_INIT
#define SRV_NTP_APP_ID_INIT_size "d"
#define SRV_NTP_APP_ID_INIT SRV_NTP_APP_ID_INIT__enum,SRV_NTP_APP_ID_INIT_size

// SRV_NTP_AUTO_SYNC_TIMER_START
#define SRV_NTP_AUTO_SYNC_TIMER_START_size NULL
#define SRV_NTP_AUTO_SYNC_TIMER_START SRV_NTP_AUTO_SYNC_TIMER_START__enum,SRV_NTP_AUTO_SYNC_TIMER_START_size

// SRV_NTP_AUTO_SYNC_RESULT_PROC
#define SRV_NTP_AUTO_SYNC_RESULT_PROC_size "‚d"
#define SRV_NTP_AUTO_SYNC_RESULT_PROC SRV_NTP_AUTO_SYNC_RESULT_PROC__enum,SRV_NTP_AUTO_SYNC_RESULT_PROC_size

// SRV_NTP_AUTO_SYNC_TIMER_PROC
#define SRV_NTP_AUTO_SYNC_TIMER_PROC_size NULL
#define SRV_NTP_AUTO_SYNC_TIMER_PROC SRV_NTP_AUTO_SYNC_TIMER_PROC__enum,SRV_NTP_AUTO_SYNC_TIMER_PROC_size

// SRV_NTP_CONFIG_RESET
#define SRV_NTP_CONFIG_RESET_size "…d"
#define SRV_NTP_CONFIG_RESET SRV_NTP_CONFIG_RESET__enum,SRV_NTP_CONFIG_RESET_size

// SRV_NTP_CONFIG_READ_WRITE
#define SRV_NTP_CONFIG_READ_WRITE_size "‚d"
#define SRV_NTP_CONFIG_READ_WRITE SRV_NTP_CONFIG_READ_WRITE__enum,SRV_NTP_CONFIG_READ_WRITE_size

// SRV_NTP_AVAILABILITY_SET
#define SRV_NTP_AVAILABILITY_SET_size "‚d"
#define SRV_NTP_AVAILABILITY_SET SRV_NTP_AVAILABILITY_SET__enum,SRV_NTP_AVAILABILITY_SET_size

// SRV_NTP_DATA_ACCT_SET
#define SRV_NTP_DATA_ACCT_SET_size "ƒd"
#define SRV_NTP_DATA_ACCT_SET SRV_NTP_DATA_ACCT_SET__enum,SRV_NTP_DATA_ACCT_SET_size

// SRV_NTP_UPDATE_TIME_TO_PHONE
#define SRV_NTP_UPDATE_TIME_TO_PHONE_size "†d"
#define SRV_NTP_UPDATE_TIME_TO_PHONE SRV_NTP_UPDATE_TIME_TO_PHONE__enum,SRV_NTP_UPDATE_TIME_TO_PHONE_size

// SRV_NTP_SYNC_CALLBACK
#define SRV_NTP_SYNC_CALLBACK_size "‚d"
#define SRV_NTP_SYNC_CALLBACK SRV_NTP_SYNC_CALLBACK__enum,SRV_NTP_SYNC_CALLBACK_size

// SRV_NTP_SYNC
#define SRV_NTP_SYNC_size "‚d"
#define SRV_NTP_SYNC SRV_NTP_SYNC__enum,SRV_NTP_SYNC_size

// SRV_NTP_EVT_HDLR
#define SRV_NTP_EVT_HDLR_size "d"
#define SRV_NTP_EVT_HDLR SRV_NTP_EVT_HDLR__enum,SRV_NTP_EVT_HDLR_size


#endif // NTPD_TRC_GEN.H
