#ifndef _NVRAM_TRC_GEN_H_
#define _NVRAM_TRC_GEN_H_

// FUNC_NVRAM_STARTUP
#define FUNC_NVRAM_STARTUP_size NULL
#define FUNC_NVRAM_STARTUP FUNC_NVRAM_STARTUP__enum,FUNC_NVRAM_STARTUP_size

// FUNC_NVRAM_STARTUP_CNF
#define FUNC_NVRAM_STARTUP_CNF_size "d"
#define FUNC_NVRAM_STARTUP_CNF FUNC_NVRAM_STARTUP_CNF__enum,FUNC_NVRAM_STARTUP_CNF_size

// FUNC_NVRAM_READ
#define FUNC_NVRAM_READ_size NULL
#define FUNC_NVRAM_READ FUNC_NVRAM_READ__enum,FUNC_NVRAM_READ_size

// FUNC_NVRAM_READ_CNF
#define FUNC_NVRAM_READ_CNF_size "…d"
#define FUNC_NVRAM_READ_CNF FUNC_NVRAM_READ_CNF__enum,FUNC_NVRAM_READ_CNF_size

// FUNC_NVRAM_WRITE
#define FUNC_NVRAM_WRITE_size NULL
#define FUNC_NVRAM_WRITE FUNC_NVRAM_WRITE__enum,FUNC_NVRAM_WRITE_size

// FUNC_NVRAM_WRITE_CNF
#define FUNC_NVRAM_WRITE_CNF_size "d"
#define FUNC_NVRAM_WRITE_CNF FUNC_NVRAM_WRITE_CNF__enum,FUNC_NVRAM_WRITE_CNF_size

// FUNC_NVRAM_WRITE_IMEI
#define FUNC_NVRAM_WRITE_IMEI_size NULL
#define FUNC_NVRAM_WRITE_IMEI FUNC_NVRAM_WRITE_IMEI__enum,FUNC_NVRAM_WRITE_IMEI_size

// FUNC_NVRAM_WRITE_IMEI_CNF
#define FUNC_NVRAM_WRITE_IMEI_CNF_size "d"
#define FUNC_NVRAM_WRITE_IMEI_CNF FUNC_NVRAM_WRITE_IMEI_CNF__enum,FUNC_NVRAM_WRITE_IMEI_CNF_size

// FUNC_NVRAM_RESET
#define FUNC_NVRAM_RESET_size NULL
#define FUNC_NVRAM_RESET FUNC_NVRAM_RESET__enum,FUNC_NVRAM_RESET_size

// FUNC_NVRAM_RESET_CNF
#define FUNC_NVRAM_RESET_CNF_size "d"
#define FUNC_NVRAM_RESET_CNF FUNC_NVRAM_RESET_CNF__enum,FUNC_NVRAM_RESET_CNF_size

// FUNC_NVRAM_TST
#define FUNC_NVRAM_TST_size NULL
#define FUNC_NVRAM_TST FUNC_NVRAM_TST__enum,FUNC_NVRAM_TST_size

// FUNC_NVRAM_READ_SM
#define FUNC_NVRAM_READ_SM_size NULL
#define FUNC_NVRAM_READ_SM FUNC_NVRAM_READ_SM__enum,FUNC_NVRAM_READ_SM_size

// FUNC_NVRAM_READ_SM_CNF
#define FUNC_NVRAM_READ_SM_CNF_size "…d"
#define FUNC_NVRAM_READ_SM_CNF FUNC_NVRAM_READ_SM_CNF__enum,FUNC_NVRAM_READ_SM_CNF_size

// FUNC_NVRAM_WRITE_SM
#define FUNC_NVRAM_WRITE_SM_size NULL
#define FUNC_NVRAM_WRITE_SM FUNC_NVRAM_WRITE_SM__enum,FUNC_NVRAM_WRITE_SM_size

// FUNC_NVRAM_WRITE_SM_CNF
#define FUNC_NVRAM_WRITE_SM_CNF_size "d"
#define FUNC_NVRAM_WRITE_SM_CNF FUNC_NVRAM_WRITE_SM_CNF__enum,FUNC_NVRAM_WRITE_SM_CNF_size

// STATE_NVRAM_NULL
#define STATE_NVRAM_NULL_size NULL
#define STATE_NVRAM_NULL STATE_NVRAM_NULL__enum,STATE_NVRAM_NULL_size

// STATE_NVRAM_NOT_READY
#define STATE_NVRAM_NOT_READY_size NULL
#define STATE_NVRAM_NOT_READY STATE_NVRAM_NOT_READY__enum,STATE_NVRAM_NOT_READY_size

// STATE_NVRAM_READY
#define STATE_NVRAM_READY_size NULL
#define STATE_NVRAM_READY STATE_NVRAM_READY__enum,STATE_NVRAM_READY_size

// INFO_NVRAM_DRV_INIT
#define INFO_NVRAM_DRV_INIT_size NULL
#define INFO_NVRAM_DRV_INIT INFO_NVRAM_DRV_INIT__enum,INFO_NVRAM_DRV_INIT_size

// INFO_NVRAM_DRV_UNFORMATTED
#define INFO_NVRAM_DRV_UNFORMATTED_size NULL
#define INFO_NVRAM_DRV_UNFORMATTED INFO_NVRAM_DRV_UNFORMATTED__enum,INFO_NVRAM_DRV_UNFORMATTED_size

// INFO_NVRAM_LOCK_STATUS
#define INFO_NVRAM_LOCK_STATUS_size "d"
#define INFO_NVRAM_LOCK_STATUS INFO_NVRAM_LOCK_STATUS__enum,INFO_NVRAM_LOCK_STATUS_size

// WARNING_NVRAM_SYS_RECORD
#define WARNING_NVRAM_SYS_RECORD_size "d"
#define WARNING_NVRAM_SYS_RECORD WARNING_NVRAM_SYS_RECORD__enum,WARNING_NVRAM_SYS_RECORD_size

// WARNING_NVRAM_ALL_LDI_INIT
#define WARNING_NVRAM_ALL_LDI_INIT_size "d"
#define WARNING_NVRAM_ALL_LDI_INIT WARNING_NVRAM_ALL_LDI_INIT__enum,WARNING_NVRAM_ALL_LDI_INIT_size

// ERROR_NVRAM_CANNOT_STARTUP
#define ERROR_NVRAM_CANNOT_STARTUP_size NULL
#define ERROR_NVRAM_CANNOT_STARTUP ERROR_NVRAM_CANNOT_STARTUP__enum,ERROR_NVRAM_CANNOT_STARTUP_size

// ERROR_NVRAM_STATE
#define ERROR_NVRAM_STATE_size NULL
#define ERROR_NVRAM_STATE ERROR_NVRAM_STATE__enum,ERROR_NVRAM_STATE_size

// ERROR_NVRAM_TST_INVALID_COMM
#define ERROR_NVRAM_TST_INVALID_COMM_size NULL
#define ERROR_NVRAM_TST_INVALID_COMM ERROR_NVRAM_TST_INVALID_COMM__enum,ERROR_NVRAM_TST_INVALID_COMM_size

// FUNC_NVRAM_NOTIFY_EXCEPTION1
#define FUNC_NVRAM_NOTIFY_EXCEPTION1_size NULL
#define FUNC_NVRAM_NOTIFY_EXCEPTION1 FUNC_NVRAM_NOTIFY_EXCEPTION1__enum,FUNC_NVRAM_NOTIFY_EXCEPTION1_size

// FUNC_NVRAM_NOTIFY_STATISTICS
#define FUNC_NVRAM_NOTIFY_STATISTICS_size NULL
#define FUNC_NVRAM_NOTIFY_STATISTICS FUNC_NVRAM_NOTIFY_STATISTICS__enum,FUNC_NVRAM_NOTIFY_STATISTICS_size

// FUNC_NVRAM_NOTIFY_EXCEPTION2
#define FUNC_NVRAM_NOTIFY_EXCEPTION2_size "‚ds„d"
#define FUNC_NVRAM_NOTIFY_EXCEPTION2 FUNC_NVRAM_NOTIFY_EXCEPTION2__enum,FUNC_NVRAM_NOTIFY_EXCEPTION2_size

// FUNC_NVRAM_WRITE_EXCEPTION1
#define FUNC_NVRAM_WRITE_EXCEPTION1_size NULL
#define FUNC_NVRAM_WRITE_EXCEPTION1 FUNC_NVRAM_WRITE_EXCEPTION1__enum,FUNC_NVRAM_WRITE_EXCEPTION1_size

// FUNC_NVRAM_WRITE_EXCEPTION2
#define FUNC_NVRAM_WRITE_EXCEPTION2_size "d"
#define FUNC_NVRAM_WRITE_EXCEPTION2 FUNC_NVRAM_WRITE_EXCEPTION2__enum,FUNC_NVRAM_WRITE_EXCEPTION2_size

// IO_READ_DATA_ITEM_START
#define IO_READ_DATA_ITEM_START_size "„d"
#define IO_READ_DATA_ITEM_START IO_READ_DATA_ITEM_START__enum,IO_READ_DATA_ITEM_START_size

// IO_READ_DATA_ITEM_RESULT
#define IO_READ_DATA_ITEM_RESULT_size "ƒd"
#define IO_READ_DATA_ITEM_RESULT IO_READ_DATA_ITEM_RESULT__enum,IO_READ_DATA_ITEM_RESULT_size

// IO_READ_DATA_ITEM_SINGLE
#define IO_READ_DATA_ITEM_SINGLE_size "„d"
#define IO_READ_DATA_ITEM_SINGLE IO_READ_DATA_ITEM_SINGLE__enum,IO_READ_DATA_ITEM_SINGLE_size

// IO_READ_DATA_ITEM_MULTIPLE
#define IO_READ_DATA_ITEM_MULTIPLE_size "„d"
#define IO_READ_DATA_ITEM_MULTIPLE IO_READ_DATA_ITEM_MULTIPLE__enum,IO_READ_DATA_ITEM_MULTIPLE_size

// IO_WRITE_DATA_ITEM_START
#define IO_WRITE_DATA_ITEM_START_size "ƒd"
#define IO_WRITE_DATA_ITEM_START IO_WRITE_DATA_ITEM_START__enum,IO_WRITE_DATA_ITEM_START_size

// IO_WRITE_DATA_ITEM_RESULT
#define IO_WRITE_DATA_ITEM_RESULT_size "„d"
#define IO_WRITE_DATA_ITEM_RESULT IO_WRITE_DATA_ITEM_RESULT__enum,IO_WRITE_DATA_ITEM_RESULT_size

// IO_WRITE_DATA_ITEM_SINGLE
#define IO_WRITE_DATA_ITEM_SINGLE_size "„d"
#define IO_WRITE_DATA_ITEM_SINGLE IO_WRITE_DATA_ITEM_SINGLE__enum,IO_WRITE_DATA_ITEM_SINGLE_size

// IO_WRITE_DATA_ITEM_MULTIPLE
#define IO_WRITE_DATA_ITEM_MULTIPLE_size "„d"
#define IO_WRITE_DATA_ITEM_MULTIPLE IO_WRITE_DATA_ITEM_MULTIPLE__enum,IO_WRITE_DATA_ITEM_MULTIPLE_size

// IO_RESET_DATA_ITEM
#define IO_RESET_DATA_ITEM_size "‚d"
#define IO_RESET_DATA_ITEM IO_RESET_DATA_ITEM__enum,IO_RESET_DATA_ITEM_size

// EX_IO_RECOVER_IMAGE_BY_LID
#define EX_IO_RECOVER_IMAGE_BY_LID_size "ƒd"
#define EX_IO_RECOVER_IMAGE_BY_LID EX_IO_RECOVER_IMAGE_BY_LID__enum,EX_IO_RECOVER_IMAGE_BY_LID_size

// FUNC_NVRAM_GET_DEFAULT_VALUE
#define FUNC_NVRAM_GET_DEFAULT_VALUE_size "ƒds"
#define FUNC_NVRAM_GET_DEFAULT_VALUE FUNC_NVRAM_GET_DEFAULT_VALUE__enum,FUNC_NVRAM_GET_DEFAULT_VALUE_size

// INFO_NVRAM_INIT_SDS_STATUS
#define INFO_NVRAM_INIT_SDS_STATUS_size "‚d"
#define INFO_NVRAM_INIT_SDS_STATUS INFO_NVRAM_INIT_SDS_STATUS__enum,INFO_NVRAM_INIT_SDS_STATUS_size

// FUNC_NVRAM_SDS_READ_DATA_ITEM
#define FUNC_NVRAM_SDS_READ_DATA_ITEM_size "‚d"
#define FUNC_NVRAM_SDS_READ_DATA_ITEM FUNC_NVRAM_SDS_READ_DATA_ITEM__enum,FUNC_NVRAM_SDS_READ_DATA_ITEM_size

// FUNC_NVRAM_SDS_FLUSH_IN
#define FUNC_NVRAM_SDS_FLUSH_IN_size "d"
#define FUNC_NVRAM_SDS_FLUSH_IN FUNC_NVRAM_SDS_FLUSH_IN__enum,FUNC_NVRAM_SDS_FLUSH_IN_size

// FUNC_NVRAM_SDS_FLUSH_OUT
#define FUNC_NVRAM_SDS_FLUSH_OUT_size NULL
#define FUNC_NVRAM_SDS_FLUSH_OUT FUNC_NVRAM_SDS_FLUSH_OUT__enum,FUNC_NVRAM_SDS_FLUSH_OUT_size

// FUNC_NVRAM_SDS_THROW_EXCEPTION
#define FUNC_NVRAM_SDS_THROW_EXCEPTION_size "‚d"
#define FUNC_NVRAM_SDS_THROW_EXCEPTION FUNC_NVRAM_SDS_THROW_EXCEPTION__enum,FUNC_NVRAM_SDS_THROW_EXCEPTION_size

// OTP_INIT
#define OTP_INIT_size NULL
#define OTP_INIT OTP_INIT__enum,OTP_INIT_size

// OTP_FAKE_WRITE
#define OTP_FAKE_WRITE_size "‚d"
#define OTP_FAKE_WRITE OTP_FAKE_WRITE__enum,OTP_FAKE_WRITE_size

// OTP_AREA_ALLOW
#define OTP_AREA_ALLOW_size "‚d"
#define OTP_AREA_ALLOW OTP_AREA_ALLOW__enum,OTP_AREA_ALLOW_size

// OTP_PROGRAM_TWICE
#define OTP_PROGRAM_TWICE_size "‚d"
#define OTP_PROGRAM_TWICE OTP_PROGRAM_TWICE__enum,OTP_PROGRAM_TWICE_size

// OTP_OVERSCOPE
#define OTP_OVERSCOPE_size "‚d"
#define OTP_OVERSCOPE OTP_OVERSCOPE__enum,OTP_OVERSCOPE_size

// OTP_READ_RESULT
#define OTP_READ_RESULT_size "ƒd"
#define OTP_READ_RESULT OTP_READ_RESULT__enum,OTP_READ_RESULT_size

// OTP_WRITE_RESULT
#define OTP_WRITE_RESULT_size "d"
#define OTP_WRITE_RESULT OTP_WRITE_RESULT__enum,OTP_WRITE_RESULT_size

// MERGE_WRITE_TEMP_RESULT
#define MERGE_WRITE_TEMP_RESULT_size "„d"
#define MERGE_WRITE_TEMP_RESULT MERGE_WRITE_TEMP_RESULT__enum,MERGE_WRITE_TEMP_RESULT_size

// MERGE_TRUNK_STATUS
#define MERGE_TRUNK_STATUS_size "d"
#define MERGE_TRUNK_STATUS MERGE_TRUNK_STATUS__enum,MERGE_TRUNK_STATUS_size

// MERGE_OPEN_PKG_FILE_RESULT
#define MERGE_OPEN_PKG_FILE_RESULT_size "d"
#define MERGE_OPEN_PKG_FILE_RESULT MERGE_OPEN_PKG_FILE_RESULT__enum,MERGE_OPEN_PKG_FILE_RESULT_size

// TEST_RESET_OK
#define TEST_RESET_OK_size NULL
#define TEST_RESET_OK TEST_RESET_OK__enum,TEST_RESET_OK_size

// TEST_RESET_FAIL
#define TEST_RESET_FAIL_size NULL
#define TEST_RESET_FAIL TEST_RESET_FAIL__enum,TEST_RESET_FAIL_size

// TEST_RESET_ALL_OK
#define TEST_RESET_ALL_OK_size NULL
#define TEST_RESET_ALL_OK TEST_RESET_ALL_OK__enum,TEST_RESET_ALL_OK_size

// TEST_RESET_ALL_FAIL
#define TEST_RESET_ALL_FAIL_size NULL
#define TEST_RESET_ALL_FAIL TEST_RESET_ALL_FAIL__enum,TEST_RESET_ALL_FAIL_size

// TEST_RESET_INVALID_LID
#define TEST_RESET_INVALID_LID_size NULL
#define TEST_RESET_INVALID_LID TEST_RESET_INVALID_LID__enum,TEST_RESET_INVALID_LID_size

// TEST_RESET_CERTAIN_OK
#define TEST_RESET_CERTAIN_OK_size NULL
#define TEST_RESET_CERTAIN_OK TEST_RESET_CERTAIN_OK__enum,TEST_RESET_CERTAIN_OK_size

// TEST_RESET_CERTAIN_FAIL
#define TEST_RESET_CERTAIN_FAIL_size NULL
#define TEST_RESET_CERTAIN_FAIL TEST_RESET_CERTAIN_FAIL__enum,TEST_RESET_CERTAIN_FAIL_size

// TEST_VALID_EXCEPTIONS
#define TEST_VALID_EXCEPTIONS_size "d"
#define TEST_VALID_EXCEPTIONS TEST_VALID_EXCEPTIONS__enum,TEST_VALID_EXCEPTIONS_size

// TEST_INVALID_EXCEPTIONS
#define TEST_INVALID_EXCEPTIONS_size "d"
#define TEST_INVALID_EXCEPTIONS TEST_INVALID_EXCEPTIONS__enum,TEST_INVALID_EXCEPTIONS_size

// TEST_REC_NUM_OUT_RANGE
#define TEST_REC_NUM_OUT_RANGE_size NULL
#define TEST_REC_NUM_OUT_RANGE TEST_REC_NUM_OUT_RANGE__enum,TEST_REC_NUM_OUT_RANGE_size

// TEST_RESET_STAT_OK
#define TEST_RESET_STAT_OK_size NULL
#define TEST_RESET_STAT_OK TEST_RESET_STAT_OK__enum,TEST_RESET_STAT_OK_size

// TEST_RESET_STAT_FAIL
#define TEST_RESET_STAT_FAIL_size NULL
#define TEST_RESET_STAT_FAIL TEST_RESET_STAT_FAIL__enum,TEST_RESET_STAT_FAIL_size

// TEST_RESET_ALLOC_FAIL
#define TEST_RESET_ALLOC_FAIL_size NULL
#define TEST_RESET_ALLOC_FAIL TEST_RESET_ALLOC_FAIL__enum,TEST_RESET_ALLOC_FAIL_size

// TEST_GET_STAT_FAIL
#define TEST_GET_STAT_FAIL_size NULL
#define TEST_GET_STAT_FAIL TEST_GET_STAT_FAIL__enum,TEST_GET_STAT_FAIL_size

// TEST_SYSINFO_DETAIL1
#define TEST_SYSINFO_DETAIL1_size "†d"
#define TEST_SYSINFO_DETAIL1 TEST_SYSINFO_DETAIL1__enum,TEST_SYSINFO_DETAIL1_size

// TEST_SYSINFO_DETAIL2
#define TEST_SYSINFO_DETAIL2_size "dsdsdsdsdsd"
#define TEST_SYSINFO_DETAIL2 TEST_SYSINFO_DETAIL2__enum,TEST_SYSINFO_DETAIL2_size

// TEST_SYSINFO_STATUS
#define TEST_SYSINFO_STATUS_size "d"
#define TEST_SYSINFO_STATUS TEST_SYSINFO_STATUS__enum,TEST_SYSINFO_STATUS_size

// TEST_SYSINFO_MAX_SYSMEM
#define TEST_SYSINFO_MAX_SYSMEM_size "d"
#define TEST_SYSINFO_MAX_SYSMEM TEST_SYSINFO_MAX_SYSMEM__enum,TEST_SYSINFO_MAX_SYSMEM_size

// TEST_SYSINFO_MAX_SYSDBGMEM
#define TEST_SYSINFO_MAX_SYSDBGMEM_size "d"
#define TEST_SYSINFO_MAX_SYSDBGMEM TEST_SYSINFO_MAX_SYSDBGMEM__enum,TEST_SYSINFO_MAX_SYSDBGMEM_size

// TEST_SYSINFO_MAX_TASK_STACK_USED
#define TEST_SYSINFO_MAX_TASK_STACK_USED_size NULL
#define TEST_SYSINFO_MAX_TASK_STACK_USED TEST_SYSINFO_MAX_TASK_STACK_USED__enum,TEST_SYSINFO_MAX_TASK_STACK_USED_size

// TEST_SYSINFO_MAX_HISR_STACK_USED
#define TEST_SYSINFO_MAX_HISR_STACK_USED_size NULL
#define TEST_SYSINFO_MAX_HISR_STACK_USED TEST_SYSINFO_MAX_HISR_STACK_USED__enum,TEST_SYSINFO_MAX_HISR_STACK_USED_size

// TEST_SYSINFO_MAX_TASK_EXTQ_ENQED
#define TEST_SYSINFO_MAX_TASK_EXTQ_ENQED_size NULL
#define TEST_SYSINFO_MAX_TASK_EXTQ_ENQED TEST_SYSINFO_MAX_TASK_EXTQ_ENQED__enum,TEST_SYSINFO_MAX_TASK_EXTQ_ENQED_size

// TEST_SYSINFO_CTRLBUFF_ALLOC
#define TEST_SYSINFO_CTRLBUFF_ALLOC_size NULL
#define TEST_SYSINFO_CTRLBUFF_ALLOC TEST_SYSINFO_CTRLBUFF_ALLOC__enum,TEST_SYSINFO_CTRLBUFF_ALLOC_size

// TEST_SYSINFO_CTRLBUFF_LIST
#define TEST_SYSINFO_CTRLBUFF_LIST_size NULL
#define TEST_SYSINFO_CTRLBUFF_LIST TEST_SYSINFO_CTRLBUFF_LIST__enum,TEST_SYSINFO_CTRLBUFF_LIST_size

// L1_SEND_UNINIT_LID
#define L1_SEND_UNINIT_LID_size "d"
#define L1_SEND_UNINIT_LID L1_SEND_UNINIT_LID__enum,L1_SEND_UNINIT_LID_size

// L1_SEND_UNINIT_LID_PKG
#define L1_SEND_UNINIT_LID_PKG_size "d"
#define L1_SEND_UNINIT_LID_PKG L1_SEND_UNINIT_LID_PKG__enum,L1_SEND_UNINIT_LID_PKG_size

// ABNORMAL_RETURN
#define ABNORMAL_RETURN_size "d"
#define ABNORMAL_RETURN ABNORMAL_RETURN__enum,ABNORMAL_RETURN_size

// UNZIP_SIZE
#define UNZIP_SIZE_size "d"
#define UNZIP_SIZE UNZIP_SIZE__enum,UNZIP_SIZE_size

// UNZIP_SIZE_RESULT
#define UNZIP_SIZE_RESULT_size "‚d"
#define UNZIP_SIZE_RESULT UNZIP_SIZE_RESULT__enum,UNZIP_SIZE_RESULT_size

// UNZIP_RESULT
#define UNZIP_RESULT_size "ƒd"
#define UNZIP_RESULT UNZIP_RESULT__enum,UNZIP_RESULT_size

// FUNC_NVRAM_VERSION_CONFLICT_RESOLVE
#define FUNC_NVRAM_VERSION_CONFLICT_RESOLVE_size "d"
#define FUNC_NVRAM_VERSION_CONFLICT_RESOLVE FUNC_NVRAM_VERSION_CONFLICT_RESOLVE__enum,FUNC_NVRAM_VERSION_CONFLICT_RESOLVE_size

// FUNC_NVRAM_SUPPLEMENTARY_CHECK
#define FUNC_NVRAM_SUPPLEMENTARY_CHECK_size "d"
#define FUNC_NVRAM_SUPPLEMENTARY_CHECK FUNC_NVRAM_SUPPLEMENTARY_CHECK__enum,FUNC_NVRAM_SUPPLEMENTARY_CHECK_size

// FUNC_NVRAM_INIT_ALL
#define FUNC_NVRAM_INIT_ALL_size "d"
#define FUNC_NVRAM_INIT_ALL FUNC_NVRAM_INIT_ALL__enum,FUNC_NVRAM_INIT_ALL_size

// FUNC_NVRAM_INIT
#define FUNC_NVRAM_INIT_size "‚d"
#define FUNC_NVRAM_INIT FUNC_NVRAM_INIT__enum,FUNC_NVRAM_INIT_size

// FUNC_NVRAM_DRV_FAT_THROW_EXCEPTION
#define FUNC_NVRAM_DRV_FAT_THROW_EXCEPTION_size "‚d"
#define FUNC_NVRAM_DRV_FAT_THROW_EXCEPTION FUNC_NVRAM_DRV_FAT_THROW_EXCEPTION__enum,FUNC_NVRAM_DRV_FAT_THROW_EXCEPTION_size

// FUNC_NVRAM_RESET_DATA_ITEMS
#define FUNC_NVRAM_RESET_DATA_ITEMS_size "…d"
#define FUNC_NVRAM_RESET_DATA_ITEMS FUNC_NVRAM_RESET_DATA_ITEMS__enum,FUNC_NVRAM_RESET_DATA_ITEMS_size

// FUNC_NVRAM_CREATE_ALL_FOLDER
#define FUNC_NVRAM_CREATE_ALL_FOLDER_size "d"
#define FUNC_NVRAM_CREATE_ALL_FOLDER FUNC_NVRAM_CREATE_ALL_FOLDER__enum,FUNC_NVRAM_CREATE_ALL_FOLDER_size

// FUNC_NVRAM_DELETE_ALL_NVRAM_FILES
#define FUNC_NVRAM_DELETE_ALL_NVRAM_FILES_size "d"
#define FUNC_NVRAM_DELETE_ALL_NVRAM_FILES FUNC_NVRAM_DELETE_ALL_NVRAM_FILES__enum,FUNC_NVRAM_DELETE_ALL_NVRAM_FILES_size

// INFO_NVRAM_DATA_ITEM
#define INFO_NVRAM_DATA_ITEM_size "hd"
#define INFO_NVRAM_DATA_ITEM INFO_NVRAM_DATA_ITEM__enum,INFO_NVRAM_DATA_ITEM_size


#endif // NVRAM_TRC_GEN.H
