#ifndef _PHB_TRC_GEN_H_
#define _PHB_TRC_GEN_H_

// FUNC_PHB_STARTUP
#define FUNC_PHB_STARTUP_size NULL
#define FUNC_PHB_STARTUP FUNC_PHB_STARTUP__enum,FUNC_PHB_STARTUP_size

// FUNC_PHB_STARTUP_ERR
#define FUNC_PHB_STARTUP_ERR_size NULL
#define FUNC_PHB_STARTUP_ERR FUNC_PHB_STARTUP_ERR__enum,FUNC_PHB_STARTUP_ERR_size

// FUNC_PHB_STARTUP_CNF
#define FUNC_PHB_STARTUP_CNF_size "d"
#define FUNC_PHB_STARTUP_CNF FUNC_PHB_STARTUP_CNF__enum,FUNC_PHB_STARTUP_CNF_size

// FUNC_PHB_IS_SIM_FILE_SUPPORT
#define FUNC_PHB_IS_SIM_FILE_SUPPORT_size "d"
#define FUNC_PHB_IS_SIM_FILE_SUPPORT FUNC_PHB_IS_SIM_FILE_SUPPORT__enum,FUNC_PHB_IS_SIM_FILE_SUPPORT_size

// FUNC_PHB_STARTUP_SYNC_LN_TYPE_SEQ
#define FUNC_PHB_STARTUP_SYNC_LN_TYPE_SEQ_size NULL
#define FUNC_PHB_STARTUP_SYNC_LN_TYPE_SEQ FUNC_PHB_STARTUP_SYNC_LN_TYPE_SEQ__enum,FUNC_PHB_STARTUP_SYNC_LN_TYPE_SEQ_size

// FUNC_PHB_STARTUP_ERASE_LN
#define FUNC_PHB_STARTUP_ERASE_LN_size NULL
#define FUNC_PHB_STARTUP_ERASE_LN FUNC_PHB_STARTUP_ERASE_LN__enum,FUNC_PHB_STARTUP_ERASE_LN_size

// FUNC_PHB_READ
#define FUNC_PHB_READ_size NULL
#define FUNC_PHB_READ FUNC_PHB_READ__enum,FUNC_PHB_READ_size

// FUNC_PHB_READ_USIM
#define FUNC_PHB_READ_USIM_size NULL
#define FUNC_PHB_READ_USIM FUNC_PHB_READ_USIM__enum,FUNC_PHB_READ_USIM_size

// FUNC_PHB_READ_ERR
#define FUNC_PHB_READ_ERR_size "d"
#define FUNC_PHB_READ_ERR FUNC_PHB_READ_ERR__enum,FUNC_PHB_READ_ERR_size

// FUNC_PHB_READ_CNF
#define FUNC_PHB_READ_CNF_size "„d"
#define FUNC_PHB_READ_CNF FUNC_PHB_READ_CNF__enum,FUNC_PHB_READ_CNF_size

// FUNC_PHB_READ_FAKE
#define FUNC_PHB_READ_FAKE_size NULL
#define FUNC_PHB_READ_FAKE FUNC_PHB_READ_FAKE__enum,FUNC_PHB_READ_FAKE_size

// FUNC_PHB_WRITE
#define FUNC_PHB_WRITE_size NULL
#define FUNC_PHB_WRITE FUNC_PHB_WRITE__enum,FUNC_PHB_WRITE_size

// FUNC_PHB_WRITE_USIM
#define FUNC_PHB_WRITE_USIM_size NULL
#define FUNC_PHB_WRITE_USIM FUNC_PHB_WRITE_USIM__enum,FUNC_PHB_WRITE_USIM_size

// FUNC_PHB_WRITE_ERR
#define FUNC_PHB_WRITE_ERR_size NULL
#define FUNC_PHB_WRITE_ERR FUNC_PHB_WRITE_ERR__enum,FUNC_PHB_WRITE_ERR_size

// FUNC_PHB_WRITE_CONT
#define FUNC_PHB_WRITE_CONT_size NULL
#define FUNC_PHB_WRITE_CONT FUNC_PHB_WRITE_CONT__enum,FUNC_PHB_WRITE_CONT_size

// FUNC_PHB_WRITE_CNF
#define FUNC_PHB_WRITE_CNF_size "ƒd"
#define FUNC_PHB_WRITE_CNF FUNC_PHB_WRITE_CNF__enum,FUNC_PHB_WRITE_CNF_size

// FUNC_PHB_DELETE
#define FUNC_PHB_DELETE_size NULL
#define FUNC_PHB_DELETE FUNC_PHB_DELETE__enum,FUNC_PHB_DELETE_size

// FUNC_PHB_DELETE_USIM
#define FUNC_PHB_DELETE_USIM_size NULL
#define FUNC_PHB_DELETE_USIM FUNC_PHB_DELETE_USIM__enum,FUNC_PHB_DELETE_USIM_size

// FUNC_PHB_DELETE_ERR
#define FUNC_PHB_DELETE_ERR_size NULL
#define FUNC_PHB_DELETE_ERR FUNC_PHB_DELETE_ERR__enum,FUNC_PHB_DELETE_ERR_size

// FUNC_PHB_DELETE_CONT
#define FUNC_PHB_DELETE_CONT_size NULL
#define FUNC_PHB_DELETE_CONT FUNC_PHB_DELETE_CONT__enum,FUNC_PHB_DELETE_CONT_size

// FUNC_PHB_DELETE_CNF
#define FUNC_PHB_DELETE_CNF_size "ƒd"
#define FUNC_PHB_DELETE_CNF FUNC_PHB_DELETE_CNF__enum,FUNC_PHB_DELETE_CNF_size

// FUNC_PHB_SEARCH
#define FUNC_PHB_SEARCH_size NULL
#define FUNC_PHB_SEARCH FUNC_PHB_SEARCH__enum,FUNC_PHB_SEARCH_size

// FUNC_PHB_SEARCH_ERR
#define FUNC_PHB_SEARCH_ERR_size NULL
#define FUNC_PHB_SEARCH_ERR FUNC_PHB_SEARCH_ERR__enum,FUNC_PHB_SEARCH_ERR_size

// FUNC_PHB_SEARCH_CONT
#define FUNC_PHB_SEARCH_CONT_size NULL
#define FUNC_PHB_SEARCH_CONT FUNC_PHB_SEARCH_CONT__enum,FUNC_PHB_SEARCH_CONT_size

// FUNC_PHB_SEARCH_CNF
#define FUNC_PHB_SEARCH_CNF_size "„d"
#define FUNC_PHB_SEARCH_CNF FUNC_PHB_SEARCH_CNF__enum,FUNC_PHB_SEARCH_CNF_size

// FUNC_PHB_SEARCH_FAKE
#define FUNC_PHB_SEARCH_FAKE_size NULL
#define FUNC_PHB_SEARCH_FAKE FUNC_PHB_SEARCH_FAKE__enum,FUNC_PHB_SEARCH_FAKE_size

// FUNC_PHB_APPROVE
#define FUNC_PHB_APPROVE_size NULL
#define FUNC_PHB_APPROVE FUNC_PHB_APPROVE__enum,FUNC_PHB_APPROVE_size

// FUNC_PHB_APPROVE_ERR
#define FUNC_PHB_APPROVE_ERR_size NULL
#define FUNC_PHB_APPROVE_ERR FUNC_PHB_APPROVE_ERR__enum,FUNC_PHB_APPROVE_ERR_size

// FUNC_PHB_APPROVE_CONT
#define FUNC_PHB_APPROVE_CONT_size NULL
#define FUNC_PHB_APPROVE_CONT FUNC_PHB_APPROVE_CONT__enum,FUNC_PHB_APPROVE_CONT_size

// FUNC_PHB_APPROVE_CNF
#define FUNC_PHB_APPROVE_CNF_size "ƒd"
#define FUNC_PHB_APPROVE_CNF FUNC_PHB_APPROVE_CNF__enum,FUNC_PHB_APPROVE_CNF_size

// FUNC_PHB_APPROVE_ECC_LENGTH_ONE
#define FUNC_PHB_APPROVE_ECC_LENGTH_ONE_size NULL
#define FUNC_PHB_APPROVE_ECC_LENGTH_ONE FUNC_PHB_APPROVE_ECC_LENGTH_ONE__enum,FUNC_PHB_APPROVE_ECC_LENGTH_ONE_size

// FUNC_PHB_APPROVE_ECC_NW_ECC
#define FUNC_PHB_APPROVE_ECC_NW_ECC_size NULL
#define FUNC_PHB_APPROVE_ECC_NW_ECC FUNC_PHB_APPROVE_ECC_NW_ECC__enum,FUNC_PHB_APPROVE_ECC_NW_ECC_size

// FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_size "ƒd"
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP__enum,FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_size

// FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_TRUE
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_TRUE_size "d"
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_TRUE FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_TRUE__enum,FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_TRUE_size

// FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_EQUAL
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_EQUAL_size "d"
#define FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_EQUAL FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_EQUAL__enum,FUNC_PHB_APPROVE_ECC_NW_ECC_LEN_COMP_EQUAL_size

// FUNC_PHB_APPROVE_ECC_IS_NW_ECC
#define FUNC_PHB_APPROVE_ECC_IS_NW_ECC_size "‚d"
#define FUNC_PHB_APPROVE_ECC_IS_NW_ECC FUNC_PHB_APPROVE_ECC_IS_NW_ECC__enum,FUNC_PHB_APPROVE_ECC_IS_NW_ECC_size

// FUNC_PHB_APPROVE_ECC_NOT_NW_ECC
#define FUNC_PHB_APPROVE_ECC_NOT_NW_ECC_size NULL
#define FUNC_PHB_APPROVE_ECC_NOT_NW_ECC FUNC_PHB_APPROVE_ECC_NOT_NW_ECC__enum,FUNC_PHB_APPROVE_ECC_NOT_NW_ECC_size

// FUNC_PHB_UPDATE_NW_ECC_LIST
#define FUNC_PHB_UPDATE_NW_ECC_LIST_size NULL
#define FUNC_PHB_UPDATE_NW_ECC_LIST FUNC_PHB_UPDATE_NW_ECC_LIST__enum,FUNC_PHB_UPDATE_NW_ECC_LIST_size

// FUNC_PHB_UPDATE_NW_ECC_LIST_NUM
#define FUNC_PHB_UPDATE_NW_ECC_LIST_NUM_size "d"
#define FUNC_PHB_UPDATE_NW_ECC_LIST_NUM FUNC_PHB_UPDATE_NW_ECC_LIST_NUM__enum,FUNC_PHB_UPDATE_NW_ECC_LIST_NUM_size

// FUNC_PHB_UPDATE_NW_ECC_LIST_CATEGORY
#define FUNC_PHB_UPDATE_NW_ECC_LIST_CATEGORY_size "‚d"
#define FUNC_PHB_UPDATE_NW_ECC_LIST_CATEGORY FUNC_PHB_UPDATE_NW_ECC_LIST_CATEGORY__enum,FUNC_PHB_UPDATE_NW_ECC_LIST_CATEGORY_size

// FUNC_PHB_SAT_FILE_CHANGE
#define FUNC_PHB_SAT_FILE_CHANGE_size NULL
#define FUNC_PHB_SAT_FILE_CHANGE FUNC_PHB_SAT_FILE_CHANGE__enum,FUNC_PHB_SAT_FILE_CHANGE_size

// FUNC_PHB_SAT_FILE_CHANGE_CNF
#define FUNC_PHB_SAT_FILE_CHANGE_CNF_size "‚d"
#define FUNC_PHB_SAT_FILE_CHANGE_CNF FUNC_PHB_SAT_FILE_CHANGE_CNF__enum,FUNC_PHB_SAT_FILE_CHANGE_CNF_size

// FUNC_PHB_IO_RETURN
#define FUNC_PHB_IO_RETURN_size NULL
#define FUNC_PHB_IO_RETURN FUNC_PHB_IO_RETURN__enum,FUNC_PHB_IO_RETURN_size

// FUNC_PHB_IS_TYPE_VALID
#define FUNC_PHB_IS_TYPE_VALID_size NULL
#define FUNC_PHB_IS_TYPE_VALID FUNC_PHB_IS_TYPE_VALID__enum,FUNC_PHB_IS_TYPE_VALID_size

// FUNC_PHB_ISSUE_IO_DELETE
#define FUNC_PHB_ISSUE_IO_DELETE_size NULL
#define FUNC_PHB_ISSUE_IO_DELETE FUNC_PHB_ISSUE_IO_DELETE__enum,FUNC_PHB_ISSUE_IO_DELETE_size

// FUNC_PHB_ISSUE_IO_READ
#define FUNC_PHB_ISSUE_IO_READ_size NULL
#define FUNC_PHB_ISSUE_IO_READ FUNC_PHB_ISSUE_IO_READ__enum,FUNC_PHB_ISSUE_IO_READ_size

// FUNC_PHB_ISSUE_IO_WRITE
#define FUNC_PHB_ISSUE_IO_WRITE_size NULL
#define FUNC_PHB_ISSUE_IO_WRITE FUNC_PHB_ISSUE_IO_WRITE__enum,FUNC_PHB_ISSUE_IO_WRITE_size

// FUNC_PHB_PREPARE_DATA_TO_WRITE
#define FUNC_PHB_PREPARE_DATA_TO_WRITE_size NULL
#define FUNC_PHB_PREPARE_DATA_TO_WRITE FUNC_PHB_PREPARE_DATA_TO_WRITE__enum,FUNC_PHB_PREPARE_DATA_TO_WRITE_size

// FUNC_PHB_DATA_DESC_ENTRY_NEW
#define FUNC_PHB_DATA_DESC_ENTRY_NEW_size NULL
#define FUNC_PHB_DATA_DESC_ENTRY_NEW FUNC_PHB_DATA_DESC_ENTRY_NEW__enum,FUNC_PHB_DATA_DESC_ENTRY_NEW_size

// FUNC_PHB_DATA_DESC_ENTRY_RESET
#define FUNC_PHB_DATA_DESC_ENTRY_RESET_size NULL
#define FUNC_PHB_DATA_DESC_ENTRY_RESET FUNC_PHB_DATA_DESC_ENTRY_RESET__enum,FUNC_PHB_DATA_DESC_ENTRY_RESET_size

// FUNC_PHB_DATA_DESC_FIND_NEXT_FREE
#define FUNC_PHB_DATA_DESC_FIND_NEXT_FREE_size NULL
#define FUNC_PHB_DATA_DESC_FIND_NEXT_FREE FUNC_PHB_DATA_DESC_FIND_NEXT_FREE__enum,FUNC_PHB_DATA_DESC_FIND_NEXT_FREE_size

// FUNC_PHB_DATA_DESC_GET_FREE_COUNT
#define FUNC_PHB_DATA_DESC_GET_FREE_COUNT_size NULL
#define FUNC_PHB_DATA_DESC_GET_FREE_COUNT FUNC_PHB_DATA_DESC_GET_FREE_COUNT__enum,FUNC_PHB_DATA_DESC_GET_FREE_COUNT_size

// FUNC_PHB_DATA_DESC_GET_DESC_BY_ID
#define FUNC_PHB_DATA_DESC_GET_DESC_BY_ID_size NULL
#define FUNC_PHB_DATA_DESC_GET_DESC_BY_ID FUNC_PHB_DATA_DESC_GET_DESC_BY_ID__enum,FUNC_PHB_DATA_DESC_GET_DESC_BY_ID_size

// FUNC_PHB_DATA_DESC_GET_ID_BY_DESC
#define FUNC_PHB_DATA_DESC_GET_ID_BY_DESC_size NULL
#define FUNC_PHB_DATA_DESC_GET_ID_BY_DESC FUNC_PHB_DATA_DESC_GET_ID_BY_DESC__enum,FUNC_PHB_DATA_DESC_GET_ID_BY_DESC_size

// FUNC_PHB_DATA_DESC_GET_RECORD_NUM
#define FUNC_PHB_DATA_DESC_GET_RECORD_NUM_size NULL
#define FUNC_PHB_DATA_DESC_GET_RECORD_NUM FUNC_PHB_DATA_DESC_GET_RECORD_NUM__enum,FUNC_PHB_DATA_DESC_GET_RECORD_NUM_size

// FUNC_PHB_DATA_DESC_GET_RECORD_SIZE
#define FUNC_PHB_DATA_DESC_GET_RECORD_SIZE_size NULL
#define FUNC_PHB_DATA_DESC_GET_RECORD_SIZE FUNC_PHB_DATA_DESC_GET_RECORD_SIZE__enum,FUNC_PHB_DATA_DESC_GET_RECORD_SIZE_size

// FUNC_PHB_DATA_DESC_IS_FREE
#define FUNC_PHB_DATA_DESC_IS_FREE_size "ƒd"
#define FUNC_PHB_DATA_DESC_IS_FREE FUNC_PHB_DATA_DESC_IS_FREE__enum,FUNC_PHB_DATA_DESC_IS_FREE_size

// PHB_TRC_DESC_MARK_FREE
#define PHB_TRC_DESC_MARK_FREE_size "…d"
#define PHB_TRC_DESC_MARK_FREE PHB_TRC_DESC_MARK_FREE__enum,PHB_TRC_DESC_MARK_FREE_size

// PHB_TRC_DESC_MARK_FREE_RESULT
#define PHB_TRC_DESC_MARK_FREE_RESULT_size "‚d"
#define PHB_TRC_DESC_MARK_FREE_RESULT PHB_TRC_DESC_MARK_FREE_RESULT__enum,PHB_TRC_DESC_MARK_FREE_RESULT_size

// FUNC_PHB_DATA_DESC_NEW
#define FUNC_PHB_DATA_DESC_NEW_size NULL
#define FUNC_PHB_DATA_DESC_NEW FUNC_PHB_DATA_DESC_NEW__enum,FUNC_PHB_DATA_DESC_NEW_size

// FUNC_PHB_DATA_DESC_RESET
#define FUNC_PHB_DATA_DESC_RESET_size NULL
#define FUNC_PHB_DATA_DESC_RESET FUNC_PHB_DATA_DESC_RESET__enum,FUNC_PHB_DATA_DESC_RESET_size

// FUNC_PHB_DATA_DESC_RESET_FREE_COUNT
#define FUNC_PHB_DATA_DESC_RESET_FREE_COUNT_size NULL
#define FUNC_PHB_DATA_DESC_RESET_FREE_COUNT FUNC_PHB_DATA_DESC_RESET_FREE_COUNT__enum,FUNC_PHB_DATA_DESC_RESET_FREE_COUNT_size

// FUNC_PHB_DATA_DESC_SET
#define FUNC_PHB_DATA_DESC_SET_size NULL
#define FUNC_PHB_DATA_DESC_SET FUNC_PHB_DATA_DESC_SET__enum,FUNC_PHB_DATA_DESC_SET_size

// FUNC_PHB_DATA_DESC_SET_IS_SUPPORT
#define FUNC_PHB_DATA_DESC_SET_IS_SUPPORT_size NULL
#define FUNC_PHB_DATA_DESC_SET_IS_SUPPORT FUNC_PHB_DATA_DESC_SET_IS_SUPPORT__enum,FUNC_PHB_DATA_DESC_SET_IS_SUPPORT_size

// FUNC_PHB_DET_APPEND
#define FUNC_PHB_DET_APPEND_size "‚d"
#define FUNC_PHB_DET_APPEND FUNC_PHB_DET_APPEND__enum,FUNC_PHB_DET_APPEND_size

// FUNC_PHB_DET_DELETE
#define FUNC_PHB_DET_DELETE_size "‚d"
#define FUNC_PHB_DET_DELETE FUNC_PHB_DET_DELETE__enum,FUNC_PHB_DET_DELETE_size

// FUNC_PHB_DET_GET
#define FUNC_PHB_DET_GET_size NULL
#define FUNC_PHB_DET_GET FUNC_PHB_DET_GET__enum,FUNC_PHB_DET_GET_size

// FUNC_PHB_DET_GET_SIZE
#define FUNC_PHB_DET_GET_SIZE_size NULL
#define FUNC_PHB_DET_GET_SIZE FUNC_PHB_DET_GET_SIZE__enum,FUNC_PHB_DET_GET_SIZE_size

// FUNC_PHB_DET_NEW
#define FUNC_PHB_DET_NEW_size NULL
#define FUNC_PHB_DET_NEW FUNC_PHB_DET_NEW__enum,FUNC_PHB_DET_NEW_size

// FUNC_PHB_DET_RESET
#define FUNC_PHB_DET_RESET_size NULL
#define FUNC_PHB_DET_RESET FUNC_PHB_DET_RESET__enum,FUNC_PHB_DET_RESET_size

// FUNC_PHB_DET_SET
#define FUNC_PHB_DET_SET_size NULL
#define FUNC_PHB_DET_SET FUNC_PHB_DET_SET__enum,FUNC_PHB_DET_SET_size

// PHB_TRC_DET_SET_DETAILS
#define PHB_TRC_DET_SET_DETAILS_size "†d"
#define PHB_TRC_DET_SET_DETAILS PHB_TRC_DET_SET_DETAILS__enum,PHB_TRC_DET_SET_DETAILS_size

// FUNC_PHB_DET_GET_POS_BY_RECORD_INDEX
#define FUNC_PHB_DET_GET_POS_BY_RECORD_INDEX_size NULL
#define FUNC_PHB_DET_GET_POS_BY_RECORD_INDEX FUNC_PHB_DET_GET_POS_BY_RECORD_INDEX__enum,FUNC_PHB_DET_GET_POS_BY_RECORD_INDEX_size

// FUNC_PHB_SEND_ILM
#define FUNC_PHB_SEND_ILM_size NULL
#define FUNC_PHB_SEND_ILM FUNC_PHB_SEND_ILM__enum,FUNC_PHB_SEND_ILM_size

// FUNC_PHB_ISTRING_ICMP
#define FUNC_PHB_ISTRING_ICMP_size NULL
#define FUNC_PHB_ISTRING_ICMP FUNC_PHB_ISTRING_ICMP__enum,FUNC_PHB_ISTRING_ICMP_size

// FUNC_PHB_BINARY_SEARCH
#define FUNC_PHB_BINARY_SEARCH_size NULL
#define FUNC_PHB_BINARY_SEARCH FUNC_PHB_BINARY_SEARCH__enum,FUNC_PHB_BINARY_SEARCH_size

// FUNC_PHB_COMPARE_BY_ALPHA_ID
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_size NULL
#define FUNC_PHB_COMPARE_BY_ALPHA_ID FUNC_PHB_COMPARE_BY_ALPHA_ID__enum,FUNC_PHB_COMPARE_BY_ALPHA_ID_size

// FUNC_PHB_COMPARE_BY_ALPHA_ID_FOR_SORT
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_FOR_SORT_size NULL
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_FOR_SORT FUNC_PHB_COMPARE_BY_ALPHA_ID_FOR_SORT__enum,FUNC_PHB_COMPARE_BY_ALPHA_ID_FOR_SORT_size

// FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_size NULL
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE__enum,FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_size

// FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_FOR_SORT
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_FOR_SORT_size NULL
#define FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_FOR_SORT FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_FOR_SORT__enum,FUNC_PHB_COMPARE_BY_ALPHA_ID_STORAGE_FOR_SORT_size

// FUNC_PHB_COMPARE_BY_KEY_ALPHA_ID
#define FUNC_PHB_COMPARE_BY_KEY_ALPHA_ID_size NULL
#define FUNC_PHB_COMPARE_BY_KEY_ALPHA_ID FUNC_PHB_COMPARE_BY_KEY_ALPHA_ID__enum,FUNC_PHB_COMPARE_BY_KEY_ALPHA_ID_size

// FUNC_PHB_COMPARE_BY_TEL_NUM_SIG
#define FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_size NULL
#define FUNC_PHB_COMPARE_BY_TEL_NUM_SIG FUNC_PHB_COMPARE_BY_TEL_NUM_SIG__enum,FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_size

// FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_FOR_SORT
#define FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_FOR_SORT_size NULL
#define FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_FOR_SORT FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_FOR_SORT__enum,FUNC_PHB_COMPARE_BY_TEL_NUM_SIG_FOR_SORT_size

// FUNC_PHB_FAST_QUICKSORT
#define FUNC_PHB_FAST_QUICKSORT_size NULL
#define FUNC_PHB_FAST_QUICKSORT FUNC_PHB_FAST_QUICKSORT__enum,FUNC_PHB_FAST_QUICKSORT_size

// FUNC_PHB_INSERTION_SORT
#define FUNC_PHB_INSERTION_SORT_size NULL
#define FUNC_PHB_INSERTION_SORT FUNC_PHB_INSERTION_SORT__enum,FUNC_PHB_INSERTION_SORT_size

// FUNC_PHB_NAME_NUM_INDEX_APPEND
#define FUNC_PHB_NAME_NUM_INDEX_APPEND_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_APPEND FUNC_PHB_NAME_NUM_INDEX_APPEND__enum,FUNC_PHB_NAME_NUM_INDEX_APPEND_size

// FUNC_PHB_NAME_NUM_INDEX_DELETE
#define FUNC_PHB_NAME_NUM_INDEX_DELETE_size "d"
#define FUNC_PHB_NAME_NUM_INDEX_DELETE FUNC_PHB_NAME_NUM_INDEX_DELETE__enum,FUNC_PHB_NAME_NUM_INDEX_DELETE_size

// FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID__enum,FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_size

// FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_STORAGE
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_STORAGE_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_STORAGE FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_STORAGE__enum,FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_ALPHA_ID_STORAGE_size

// FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG__enum,FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_size

// FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_EXACT_MATCH
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_EXACT_MATCH_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_EXACT_MATCH FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_EXACT_MATCH__enum,FUNC_PHB_NAME_NUM_INDEX_FIND_INDEX_BY_NUM_SIG_EXACT_MATCH_size

// FUNC_PHB_NAME_NUM_INDEX_GET_DATA_ENTRY
#define FUNC_PHB_NAME_NUM_INDEX_GET_DATA_ENTRY_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_GET_DATA_ENTRY FUNC_PHB_NAME_NUM_INDEX_GET_DATA_ENTRY__enum,FUNC_PHB_NAME_NUM_INDEX_GET_DATA_ENTRY_size

// FUNC_PHB_NAME_NUM_INDEX_GET_SIZE
#define FUNC_PHB_NAME_NUM_INDEX_GET_SIZE_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_GET_SIZE FUNC_PHB_NAME_NUM_INDEX_GET_SIZE__enum,FUNC_PHB_NAME_NUM_INDEX_GET_SIZE_size

// FUNC_PHB_NAME_NUM_INDEX_NEW
#define FUNC_PHB_NAME_NUM_INDEX_NEW_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_NEW FUNC_PHB_NAME_NUM_INDEX_NEW__enum,FUNC_PHB_NAME_NUM_INDEX_NEW_size

// FUNC_PHB_NAME_NUM_INDEX_RESET
#define FUNC_PHB_NAME_NUM_INDEX_RESET_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_RESET FUNC_PHB_NAME_NUM_INDEX_RESET__enum,FUNC_PHB_NAME_NUM_INDEX_RESET_size

// FUNC_PHB_NAME_NUM_INDEX_SORT
#define FUNC_PHB_NAME_NUM_INDEX_SORT_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_SORT FUNC_PHB_NAME_NUM_INDEX_SORT__enum,FUNC_PHB_NAME_NUM_INDEX_SORT_size

// FUNC_PHB_NAME_NUM_INDEX_UPDATE
#define FUNC_PHB_NAME_NUM_INDEX_UPDATE_size NULL
#define FUNC_PHB_NAME_NUM_INDEX_UPDATE FUNC_PHB_NAME_NUM_INDEX_UPDATE__enum,FUNC_PHB_NAME_NUM_INDEX_UPDATE_size

// FUNC_PHB_QUICKSORT
#define FUNC_PHB_QUICKSORT_size NULL
#define FUNC_PHB_QUICKSORT FUNC_PHB_QUICKSORT__enum,FUNC_PHB_QUICKSORT_size

// FUNC_PHB_SWAP
#define FUNC_PHB_SWAP_size NULL
#define FUNC_PHB_SWAP FUNC_PHB_SWAP__enum,FUNC_PHB_SWAP_size

// FUNC_PHB_NVRAM_DELETE
#define FUNC_PHB_NVRAM_DELETE_size NULL
#define FUNC_PHB_NVRAM_DELETE FUNC_PHB_NVRAM_DELETE__enum,FUNC_PHB_NVRAM_DELETE_size

// FUNC_PHB_NVRAM_DELETE_CNF
#define FUNC_PHB_NVRAM_DELETE_CNF_size NULL
#define FUNC_PHB_NVRAM_DELETE_CNF FUNC_PHB_NVRAM_DELETE_CNF__enum,FUNC_PHB_NVRAM_DELETE_CNF_size

// FUNC_PHB_NVRAM_READ
#define FUNC_PHB_NVRAM_READ_size NULL
#define FUNC_PHB_NVRAM_READ FUNC_PHB_NVRAM_READ__enum,FUNC_PHB_NVRAM_READ_size

// FUNC_PHB_NVRAM_READ_CNF
#define FUNC_PHB_NVRAM_READ_CNF_size NULL
#define FUNC_PHB_NVRAM_READ_CNF FUNC_PHB_NVRAM_READ_CNF__enum,FUNC_PHB_NVRAM_READ_CNF_size

// FUNC_PHB_NVRAM_READ_RECORD
#define FUNC_PHB_NVRAM_READ_RECORD_size NULL
#define FUNC_PHB_NVRAM_READ_RECORD FUNC_PHB_NVRAM_READ_RECORD__enum,FUNC_PHB_NVRAM_READ_RECORD_size

// FUNC_PHB_NVRAM_WRITE
#define FUNC_PHB_NVRAM_WRITE_size NULL
#define FUNC_PHB_NVRAM_WRITE FUNC_PHB_NVRAM_WRITE__enum,FUNC_PHB_NVRAM_WRITE_size

// FUNC_PHB_NVRAM_WRITE_CNF
#define FUNC_PHB_NVRAM_WRITE_CNF_size NULL
#define FUNC_PHB_NVRAM_WRITE_CNF FUNC_PHB_NVRAM_WRITE_CNF__enum,FUNC_PHB_NVRAM_WRITE_CNF_size

// FUNC_PHB_NVRAM_WRITE_RECORD
#define FUNC_PHB_NVRAM_WRITE_RECORD_size NULL
#define FUNC_PHB_NVRAM_WRITE_RECORD FUNC_PHB_NVRAM_WRITE_RECORD__enum,FUNC_PHB_NVRAM_WRITE_RECORD_size

// FUNC_PHB_PINDEX_APPEND
#define FUNC_PHB_PINDEX_APPEND_size NULL
#define FUNC_PHB_PINDEX_APPEND FUNC_PHB_PINDEX_APPEND__enum,FUNC_PHB_PINDEX_APPEND_size

// FUNC_PHB_PINDEX_DELETE
#define FUNC_PHB_PINDEX_DELETE_size "‚d"
#define FUNC_PHB_PINDEX_DELETE FUNC_PHB_PINDEX_DELETE__enum,FUNC_PHB_PINDEX_DELETE_size

// FUNC_PHB_PINDEX_GET_POS
#define FUNC_PHB_PINDEX_GET_POS_size "d"
#define FUNC_PHB_PINDEX_GET_POS FUNC_PHB_PINDEX_GET_POS__enum,FUNC_PHB_PINDEX_GET_POS_size

// FUNC_PHB_PINDEX_GET_SIZE
#define FUNC_PHB_PINDEX_GET_SIZE_size NULL
#define FUNC_PHB_PINDEX_GET_SIZE FUNC_PHB_PINDEX_GET_SIZE__enum,FUNC_PHB_PINDEX_GET_SIZE_size

// FUNC_PHB_PINDEX_INSERT
#define FUNC_PHB_PINDEX_INSERT_size NULL
#define FUNC_PHB_PINDEX_INSERT FUNC_PHB_PINDEX_INSERT__enum,FUNC_PHB_PINDEX_INSERT_size

// FUNC_PHB_PINDEX_NEW
#define FUNC_PHB_PINDEX_NEW_size NULL
#define FUNC_PHB_PINDEX_NEW FUNC_PHB_PINDEX_NEW__enum,FUNC_PHB_PINDEX_NEW_size

// FUNC_PHB_PINDEX_RELINK
#define FUNC_PHB_PINDEX_RELINK_size NULL
#define FUNC_PHB_PINDEX_RELINK FUNC_PHB_PINDEX_RELINK__enum,FUNC_PHB_PINDEX_RELINK_size

// FUNC_PHB_PINDEX_RESET
#define FUNC_PHB_PINDEX_RESET_size NULL
#define FUNC_PHB_PINDEX_RESET FUNC_PHB_PINDEX_RESET__enum,FUNC_PHB_PINDEX_RESET_size

// FUNC_PHB_PINDEX_UPDATE
#define FUNC_PHB_PINDEX_UPDATE_size NULL
#define FUNC_PHB_PINDEX_UPDATE FUNC_PHB_PINDEX_UPDATE__enum,FUNC_PHB_PINDEX_UPDATE_size

// FUNC_PHB_PINDEX_GET_INDEX_BY_POSITION
#define FUNC_PHB_PINDEX_GET_INDEX_BY_POSITION_size NULL
#define FUNC_PHB_PINDEX_GET_INDEX_BY_POSITION FUNC_PHB_PINDEX_GET_INDEX_BY_POSITION__enum,FUNC_PHB_PINDEX_GET_INDEX_BY_POSITION_size

// FUNC_L4CPHB_MODE_REQ
#define FUNC_L4CPHB_MODE_REQ_size NULL
#define FUNC_L4CPHB_MODE_REQ FUNC_L4CPHB_MODE_REQ__enum,FUNC_L4CPHB_MODE_REQ_size

// FUNC_L4CPHB_STATUS_REQ
#define FUNC_L4CPHB_STATUS_REQ_size NULL
#define FUNC_L4CPHB_STATUS_REQ FUNC_L4CPHB_STATUS_REQ__enum,FUNC_L4CPHB_STATUS_REQ_size

// FUNC_L4CPHB_GET_FILE_INFO
#define FUNC_L4CPHB_GET_FILE_INFO_size "‚d"
#define FUNC_L4CPHB_GET_FILE_INFO FUNC_L4CPHB_GET_FILE_INFO__enum,FUNC_L4CPHB_GET_FILE_INFO_size

// FUNC_L4CPHB_GET_FILE_INFO_DETAIL
#define FUNC_L4CPHB_GET_FILE_INFO_DETAIL_size "…d"
#define FUNC_L4CPHB_GET_FILE_INFO_DETAIL FUNC_L4CPHB_GET_FILE_INFO_DETAIL__enum,FUNC_L4CPHB_GET_FILE_INFO_DETAIL_size

// FUNC_L4CPHB_TEST_INDEX
#define FUNC_L4CPHB_TEST_INDEX_size NULL
#define FUNC_L4CPHB_TEST_INDEX FUNC_L4CPHB_TEST_INDEX__enum,FUNC_L4CPHB_TEST_INDEX_size

// FUNC_L4CPHB_TEST_STORAGE
#define FUNC_L4CPHB_TEST_STORAGE_size NULL
#define FUNC_L4CPHB_TEST_STORAGE FUNC_L4CPHB_TEST_STORAGE__enum,FUNC_L4CPHB_TEST_STORAGE_size

// FUNC_L4CPHB_TEST_TEXT
#define FUNC_L4CPHB_TEST_TEXT_size NULL
#define FUNC_L4CPHB_TEST_TEXT FUNC_L4CPHB_TEST_TEXT__enum,FUNC_L4CPHB_TEST_TEXT_size

// FUNC_L4CPHB_TEST_WRITE_PARAMETER
#define FUNC_L4CPHB_TEST_WRITE_PARAMETER_size NULL
#define FUNC_L4CPHB_TEST_WRITE_PARAMETER FUNC_L4CPHB_TEST_WRITE_PARAMETER__enum,FUNC_L4CPHB_TEST_WRITE_PARAMETER_size

// FUNC_L4CPHB_ALLOC_PEER_BUF
#define FUNC_L4CPHB_ALLOC_PEER_BUF_size NULL
#define FUNC_L4CPHB_ALLOC_PEER_BUF FUNC_L4CPHB_ALLOC_PEER_BUF__enum,FUNC_L4CPHB_ALLOC_PEER_BUF_size

// FUNC_PHB_BINARY_SEARCH_COUNTRY_CODE
#define FUNC_PHB_BINARY_SEARCH_COUNTRY_CODE_size NULL
#define FUNC_PHB_BINARY_SEARCH_COUNTRY_CODE FUNC_PHB_BINARY_SEARCH_COUNTRY_CODE__enum,FUNC_PHB_BINARY_SEARCH_COUNTRY_CODE_size

// FUNC_PHB_COMPARE_COUNTRY_CODE
#define FUNC_PHB_COMPARE_COUNTRY_CODE_size NULL
#define FUNC_PHB_COMPARE_COUNTRY_CODE FUNC_PHB_COMPARE_COUNTRY_CODE__enum,FUNC_PHB_COMPARE_COUNTRY_CODE_size

// FUNC_PHB_SE_APPEND
#define FUNC_PHB_SE_APPEND_size NULL
#define FUNC_PHB_SE_APPEND FUNC_PHB_SE_APPEND__enum,FUNC_PHB_SE_APPEND_size

// FUNC_PHB_SE_CAL_SIGNATURE_NUM
#define FUNC_PHB_SE_CAL_SIGNATURE_NUM_size NULL
#define FUNC_PHB_SE_CAL_SIGNATURE_NUM FUNC_PHB_SE_CAL_SIGNATURE_NUM__enum,FUNC_PHB_SE_CAL_SIGNATURE_NUM_size

// FUNC_PHB_SE_DELETE
#define FUNC_PHB_SE_DELETE_size NULL
#define FUNC_PHB_SE_DELETE FUNC_PHB_SE_DELETE__enum,FUNC_PHB_SE_DELETE_size

// FUNC_PHB_SE_FINISH_BUILD
#define FUNC_PHB_SE_FINISH_BUILD_size NULL
#define FUNC_PHB_SE_FINISH_BUILD FUNC_PHB_SE_FINISH_BUILD__enum,FUNC_PHB_SE_FINISH_BUILD_size

// FUNC_PHB_SE_GET_DIFFERNTIABLE_DIGITS
#define FUNC_PHB_SE_GET_DIFFERNTIABLE_DIGITS_size NULL
#define FUNC_PHB_SE_GET_DIFFERNTIABLE_DIGITS FUNC_PHB_SE_GET_DIFFERNTIABLE_DIGITS__enum,FUNC_PHB_SE_GET_DIFFERNTIABLE_DIGITS_size

// FUNC_PHB_SE_GET_INDEX_VALUES
#define FUNC_PHB_SE_GET_INDEX_VALUES_size NULL
#define FUNC_PHB_SE_GET_INDEX_VALUES FUNC_PHB_SE_GET_INDEX_VALUES__enum,FUNC_PHB_SE_GET_INDEX_VALUES_size

// FUNC_PHB_SE_GET_RECORD_INDEX
#define FUNC_PHB_SE_GET_RECORD_INDEX_size NULL
#define FUNC_PHB_SE_GET_RECORD_INDEX FUNC_PHB_SE_GET_RECORD_INDEX__enum,FUNC_PHB_SE_GET_RECORD_INDEX_size

// FUNC_PHB_SE_GET_TOTAL_OF_TYPE
#define FUNC_PHB_SE_GET_TOTAL_OF_TYPE_size NULL
#define FUNC_PHB_SE_GET_TOTAL_OF_TYPE FUNC_PHB_SE_GET_TOTAL_OF_TYPE__enum,FUNC_PHB_SE_GET_TOTAL_OF_TYPE_size

// FUNC_PHB_SE_IS_IN_RANGE
#define FUNC_PHB_SE_IS_IN_RANGE_size "„d"
#define FUNC_PHB_SE_IS_IN_RANGE FUNC_PHB_SE_IS_IN_RANGE__enum,FUNC_PHB_SE_IS_IN_RANGE_size

// FUNC_PHB_SE_IS_NEXT_ALSO_CANDIDATE
#define FUNC_PHB_SE_IS_NEXT_ALSO_CANDIDATE_size NULL
#define FUNC_PHB_SE_IS_NEXT_ALSO_CANDIDATE FUNC_PHB_SE_IS_NEXT_ALSO_CANDIDATE__enum,FUNC_PHB_SE_IS_NEXT_ALSO_CANDIDATE_size

// FUNC_PHB_SE_NEW
#define FUNC_PHB_SE_NEW_size NULL
#define FUNC_PHB_SE_NEW FUNC_PHB_SE_NEW__enum,FUNC_PHB_SE_NEW_size

// FUNC_PHB_SE_RESET
#define FUNC_PHB_SE_RESET_size NULL
#define FUNC_PHB_SE_RESET FUNC_PHB_SE_RESET__enum,FUNC_PHB_SE_RESET_size

// FUNC_PHB_SE_SEARCH_BY_NAME
#define FUNC_PHB_SE_SEARCH_BY_NAME_size NULL
#define FUNC_PHB_SE_SEARCH_BY_NAME FUNC_PHB_SE_SEARCH_BY_NAME__enum,FUNC_PHB_SE_SEARCH_BY_NAME_size

// FUNC_PHB_SE_SEARCH_BY_RECORD_INDEX_NAME
#define FUNC_PHB_SE_SEARCH_BY_RECORD_INDEX_NAME_size NULL
#define FUNC_PHB_SE_SEARCH_BY_RECORD_INDEX_NAME FUNC_PHB_SE_SEARCH_BY_RECORD_INDEX_NAME__enum,FUNC_PHB_SE_SEARCH_BY_RECORD_INDEX_NAME_size

// FUNC_PHB_SE_SEARCH_BY_TEL_NUM
#define FUNC_PHB_SE_SEARCH_BY_TEL_NUM_size NULL
#define FUNC_PHB_SE_SEARCH_BY_TEL_NUM FUNC_PHB_SE_SEARCH_BY_TEL_NUM__enum,FUNC_PHB_SE_SEARCH_BY_TEL_NUM_size

// FUNC_PHB_SE_SET_CONTROL_BLOCK
#define FUNC_PHB_SE_SET_CONTROL_BLOCK_size "ƒd"
#define FUNC_PHB_SE_SET_CONTROL_BLOCK FUNC_PHB_SE_SET_CONTROL_BLOCK__enum,FUNC_PHB_SE_SET_CONTROL_BLOCK_size

// FUNC_PHB_SE_SET_CONTROL_BLOCK_TRANSLATE_INDEX
#define FUNC_PHB_SE_SET_CONTROL_BLOCK_TRANSLATE_INDEX_size "„d"
#define FUNC_PHB_SE_SET_CONTROL_BLOCK_TRANSLATE_INDEX FUNC_PHB_SE_SET_CONTROL_BLOCK_TRANSLATE_INDEX__enum,FUNC_PHB_SE_SET_CONTROL_BLOCK_TRANSLATE_INDEX_size

// PHB_TRC_SE_SET_INDEX
#define PHB_TRC_SE_SET_INDEX_size "…d"
#define PHB_TRC_SE_SET_INDEX PHB_TRC_SE_SET_INDEX__enum,PHB_TRC_SE_SET_INDEX_size

// PHB_TRC_SE_SET_INDEX_DEL
#define PHB_TRC_SE_SET_INDEX_DEL_size NULL
#define PHB_TRC_SE_SET_INDEX_DEL PHB_TRC_SE_SET_INDEX_DEL__enum,PHB_TRC_SE_SET_INDEX_DEL_size

// FUNC_PHB_SE_UPDATE
#define FUNC_PHB_SE_UPDATE_size NULL
#define FUNC_PHB_SE_UPDATE FUNC_PHB_SE_UPDATE__enum,FUNC_PHB_SE_UPDATE_size

// FUNC_PHB_SE_BUILD_INDEX
#define FUNC_PHB_SE_BUILD_INDEX_size NULL
#define FUNC_PHB_SE_BUILD_INDEX FUNC_PHB_SE_BUILD_INDEX__enum,FUNC_PHB_SE_BUILD_INDEX_size

// FUNC_PHB_SIM_DELETE
#define FUNC_PHB_SIM_DELETE_size NULL
#define FUNC_PHB_SIM_DELETE FUNC_PHB_SIM_DELETE__enum,FUNC_PHB_SIM_DELETE_size

// FUNC_PHB_SIM_DELETE_CNF
#define FUNC_PHB_SIM_DELETE_CNF_size NULL
#define FUNC_PHB_SIM_DELETE_CNF FUNC_PHB_SIM_DELETE_CNF__enum,FUNC_PHB_SIM_DELETE_CNF_size

// FUNC_PHB_SIM_FILE_INFO
#define FUNC_PHB_SIM_FILE_INFO_size NULL
#define FUNC_PHB_SIM_FILE_INFO FUNC_PHB_SIM_FILE_INFO__enum,FUNC_PHB_SIM_FILE_INFO_size

// FUNC_PHB_SIM_FILE_INFO_CNF
#define FUNC_PHB_SIM_FILE_INFO_CNF_size NULL
#define FUNC_PHB_SIM_FILE_INFO_CNF FUNC_PHB_SIM_FILE_INFO_CNF__enum,FUNC_PHB_SIM_FILE_INFO_CNF_size

// FUNC_PHB_SIM_READ
#define FUNC_PHB_SIM_READ_size NULL
#define FUNC_PHB_SIM_READ FUNC_PHB_SIM_READ__enum,FUNC_PHB_SIM_READ_size

// FUNC_PHB_SIM_READ_CNF
#define FUNC_PHB_SIM_READ_CNF_size NULL
#define FUNC_PHB_SIM_READ_CNF FUNC_PHB_SIM_READ_CNF__enum,FUNC_PHB_SIM_READ_CNF_size

// FUNC_PHB_SIM_READ_RECORD
#define FUNC_PHB_SIM_READ_RECORD_size "hd"
#define FUNC_PHB_SIM_READ_RECORD FUNC_PHB_SIM_READ_RECORD__enum,FUNC_PHB_SIM_READ_RECORD_size

// FUNC_PHB_SIM_REASSEMBLE_TEL_NUM
#define FUNC_PHB_SIM_REASSEMBLE_TEL_NUM_size NULL
#define FUNC_PHB_SIM_REASSEMBLE_TEL_NUM FUNC_PHB_SIM_REASSEMBLE_TEL_NUM__enum,FUNC_PHB_SIM_REASSEMBLE_TEL_NUM_size

// FUNC_PHB_SIM_WRITE
#define FUNC_PHB_SIM_WRITE_size NULL
#define FUNC_PHB_SIM_WRITE FUNC_PHB_SIM_WRITE__enum,FUNC_PHB_SIM_WRITE_size

// PHB_TRC_SIM_WRT_EXT_REC
#define PHB_TRC_SIM_WRT_EXT_REC_size "‚d"
#define PHB_TRC_SIM_WRT_EXT_REC PHB_TRC_SIM_WRT_EXT_REC__enum,PHB_TRC_SIM_WRT_EXT_REC_size

// FUNC_PHB_SIM_WRITE_CNF
#define FUNC_PHB_SIM_WRITE_CNF_size NULL
#define FUNC_PHB_SIM_WRITE_CNF FUNC_PHB_SIM_WRITE_CNF__enum,FUNC_PHB_SIM_WRITE_CNF_size

// FUNC_PHB_SIM_WRITE_FIRST_RECORD
#define FUNC_PHB_SIM_WRITE_FIRST_RECORD_size NULL
#define FUNC_PHB_SIM_WRITE_FIRST_RECORD FUNC_PHB_SIM_WRITE_FIRST_RECORD__enum,FUNC_PHB_SIM_WRITE_FIRST_RECORD_size

// FUNC_PHB_SIM_WRITE_RECORD
#define FUNC_PHB_SIM_WRITE_RECORD_size NULL
#define FUNC_PHB_SIM_WRITE_RECORD FUNC_PHB_SIM_WRITE_RECORD__enum,FUNC_PHB_SIM_WRITE_RECORD_size

// PHB_TRC_SIM_WRT_REC
#define PHB_TRC_SIM_WRT_REC_size "hd"
#define PHB_TRC_SIM_WRT_REC PHB_TRC_SIM_WRT_REC__enum,PHB_TRC_SIM_WRT_REC_size

// PHB_TRC_SIM_WRT_REC_MULTI
#define PHB_TRC_SIM_WRT_REC_MULTI_size "hd"
#define PHB_TRC_SIM_WRT_REC_MULTI PHB_TRC_SIM_WRT_REC_MULTI__enum,PHB_TRC_SIM_WRT_REC_MULTI_size

// FUNC_PHB_SIM_WRITE_SEGMENTED_RECORD
#define FUNC_PHB_SIM_WRITE_SEGMENTED_RECORD_size NULL
#define FUNC_PHB_SIM_WRITE_SEGMENTED_RECORD FUNC_PHB_SIM_WRITE_SEGMENTED_RECORD__enum,FUNC_PHB_SIM_WRITE_SEGMENTED_RECORD_size

// FUNC_PHB_CONTEXT_SELECTION
#define FUNC_PHB_CONTEXT_SELECTION_size "d"
#define FUNC_PHB_CONTEXT_SELECTION FUNC_PHB_CONTEXT_SELECTION__enum,FUNC_PHB_CONTEXT_SELECTION_size

// FUNC_PHB_WHICH_SIM_EX
#define FUNC_PHB_WHICH_SIM_EX_size "d"
#define FUNC_PHB_WHICH_SIM_EX FUNC_PHB_WHICH_SIM_EX__enum,FUNC_PHB_WHICH_SIM_EX_size

// PHB_TRC_SIM_MULTI_EF
#define PHB_TRC_SIM_MULTI_EF_size "‚d"
#define PHB_TRC_SIM_MULTI_EF PHB_TRC_SIM_MULTI_EF__enum,PHB_TRC_SIM_MULTI_EF_size

// FUNC_PHB_SIM_IO_CHECK
#define FUNC_PHB_SIM_IO_CHECK_size "ƒd"
#define FUNC_PHB_SIM_IO_CHECK FUNC_PHB_SIM_IO_CHECK__enum,FUNC_PHB_SIM_IO_CHECK_size

// STATE_PHB_NULL
#define STATE_PHB_NULL_size NULL
#define STATE_PHB_NULL STATE_PHB_NULL__enum,STATE_PHB_NULL_size

// STATE_PHB_LN_NOT_READY
#define STATE_PHB_LN_NOT_READY_size NULL
#define STATE_PHB_LN_NOT_READY STATE_PHB_LN_NOT_READY__enum,STATE_PHB_LN_NOT_READY_size

// STATE_PHB_NOT_READY
#define STATE_PHB_NOT_READY_size NULL
#define STATE_PHB_NOT_READY STATE_PHB_NOT_READY__enum,STATE_PHB_NOT_READY_size

// STATE_PHB_READY
#define STATE_PHB_READY_size NULL
#define STATE_PHB_READY STATE_PHB_READY__enum,STATE_PHB_READY_size

// STATE_PHB_DEFINE_RECORD_LN_TYPE_SEQ
#define STATE_PHB_DEFINE_RECORD_LN_TYPE_SEQ_size NULL
#define STATE_PHB_DEFINE_RECORD_LN_TYPE_SEQ STATE_PHB_DEFINE_RECORD_LN_TYPE_SEQ__enum,STATE_PHB_DEFINE_RECORD_LN_TYPE_SEQ_size

// STATE_PHB_NOT_DEFINE_RECORD_LN_TYPE_SEQ
#define STATE_PHB_NOT_DEFINE_RECORD_LN_TYPE_SEQ_size NULL
#define STATE_PHB_NOT_DEFINE_RECORD_LN_TYPE_SEQ STATE_PHB_NOT_DEFINE_RECORD_LN_TYPE_SEQ__enum,STATE_PHB_NOT_DEFINE_RECORD_LN_TYPE_SEQ_size

// INFO_PHB_STARTUP_MODE
#define INFO_PHB_STARTUP_MODE_size "d"
#define INFO_PHB_STARTUP_MODE INFO_PHB_STARTUP_MODE__enum,INFO_PHB_STARTUP_MODE_size

// INFO_PHB_FILE_INFO_BEGIN
#define INFO_PHB_FILE_INFO_BEGIN_size NULL
#define INFO_PHB_FILE_INFO_BEGIN INFO_PHB_FILE_INFO_BEGIN__enum,INFO_PHB_FILE_INFO_BEGIN_size

// INFO_PHB_FILE_INFO_GOT
#define INFO_PHB_FILE_INFO_GOT_size NULL
#define INFO_PHB_FILE_INFO_GOT INFO_PHB_FILE_INFO_GOT__enum,INFO_PHB_FILE_INFO_GOT_size

// PHB_TRC_GET_INFO
#define PHB_TRC_GET_INFO_size "h"
#define PHB_TRC_GET_INFO PHB_TRC_GET_INFO__enum,PHB_TRC_GET_INFO_size

// PHB_TRC_GET_INFO_NOT_SUPPORT
#define PHB_TRC_GET_INFO_NOT_SUPPORT_size "d"
#define PHB_TRC_GET_INFO_NOT_SUPPORT PHB_TRC_GET_INFO_NOT_SUPPORT__enum,PHB_TRC_GET_INFO_NOT_SUPPORT_size

// PHB_TRC_GET_INFO_ADN
#define PHB_TRC_GET_INFO_ADN_size "ƒd"
#define PHB_TRC_GET_INFO_ADN PHB_TRC_GET_INFO_ADN__enum,PHB_TRC_GET_INFO_ADN_size

// INFO_PHB_INDICES_BEGIN
#define INFO_PHB_INDICES_BEGIN_size NULL
#define INFO_PHB_INDICES_BEGIN INFO_PHB_INDICES_BEGIN__enum,INFO_PHB_INDICES_BEGIN_size

// INFO_PHB_INDICES_BUILT
#define INFO_PHB_INDICES_BUILT_size NULL
#define INFO_PHB_INDICES_BUILT INFO_PHB_INDICES_BUILT__enum,INFO_PHB_INDICES_BUILT_size

// INFO_PHB_APPROVE_ECC_SIM_CARD_STATUS
#define INFO_PHB_APPROVE_ECC_SIM_CARD_STATUS_size "d"
#define INFO_PHB_APPROVE_ECC_SIM_CARD_STATUS INFO_PHB_APPROVE_ECC_SIM_CARD_STATUS__enum,INFO_PHB_APPROVE_ECC_SIM_CARD_STATUS_size

// INFO_PHB_STARTUP_SYNC_LN_TYPE_SEQ_SIM_STATUS
#define INFO_PHB_STARTUP_SYNC_LN_TYPE_SEQ_SIM_STATUS_size "d"
#define INFO_PHB_STARTUP_SYNC_LN_TYPE_SEQ_SIM_STATUS INFO_PHB_STARTUP_SYNC_LN_TYPE_SEQ_SIM_STATUS__enum,INFO_PHB_STARTUP_SYNC_LN_TYPE_SEQ_SIM_STATUS_size

// INFO_PHB_STARTUP_ERASE_SIM_STATUS
#define INFO_PHB_STARTUP_ERASE_SIM_STATUS_size "d"
#define INFO_PHB_STARTUP_ERASE_SIM_STATUS INFO_PHB_STARTUP_ERASE_SIM_STATUS__enum,INFO_PHB_STARTUP_ERASE_SIM_STATUS_size

// WARNING_PHB
#define WARNING_PHB_size NULL
#define WARNING_PHB WARNING_PHB__enum,WARNING_PHB_size

// ERROR_PHB_SIM_IO_STATE_FILE_INFO
#define ERROR_PHB_SIM_IO_STATE_FILE_INFO_size NULL
#define ERROR_PHB_SIM_IO_STATE_FILE_INFO ERROR_PHB_SIM_IO_STATE_FILE_INFO__enum,ERROR_PHB_SIM_IO_STATE_FILE_INFO_size

// ERROR_PHB_SIM_IO_STATE_READ
#define ERROR_PHB_SIM_IO_STATE_READ_size NULL
#define ERROR_PHB_SIM_IO_STATE_READ ERROR_PHB_SIM_IO_STATE_READ__enum,ERROR_PHB_SIM_IO_STATE_READ_size

// ERROR_PHB_SIM_IO_STATE_WRITE
#define ERROR_PHB_SIM_IO_STATE_WRITE_size NULL
#define ERROR_PHB_SIM_IO_STATE_WRITE ERROR_PHB_SIM_IO_STATE_WRITE__enum,ERROR_PHB_SIM_IO_STATE_WRITE_size

// ERROR_PHB_SIM_IO_STATE_DELETE
#define ERROR_PHB_SIM_IO_STATE_DELETE_size NULL
#define ERROR_PHB_SIM_IO_STATE_DELETE ERROR_PHB_SIM_IO_STATE_DELETE__enum,ERROR_PHB_SIM_IO_STATE_DELETE_size

// ERROR_PHB_NVRAM_IO_STATE_READ
#define ERROR_PHB_NVRAM_IO_STATE_READ_size NULL
#define ERROR_PHB_NVRAM_IO_STATE_READ ERROR_PHB_NVRAM_IO_STATE_READ__enum,ERROR_PHB_NVRAM_IO_STATE_READ_size

// ERROR_PHB_NVRAM_IO_STATE_WRITE
#define ERROR_PHB_NVRAM_IO_STATE_WRITE_size NULL
#define ERROR_PHB_NVRAM_IO_STATE_WRITE ERROR_PHB_NVRAM_IO_STATE_WRITE__enum,ERROR_PHB_NVRAM_IO_STATE_WRITE_size

// ERROR_PHB_NVRAM_IO_STATE_DELETE
#define ERROR_PHB_NVRAM_IO_STATE_DELETE_size NULL
#define ERROR_PHB_NVRAM_IO_STATE_DELETE ERROR_PHB_NVRAM_IO_STATE_DELETE__enum,ERROR_PHB_NVRAM_IO_STATE_DELETE_size

// ERROR_PHB_ABNORMAL
#define ERROR_PHB_ABNORMAL_size NULL
#define ERROR_PHB_ABNORMAL ERROR_PHB_ABNORMAL__enum,ERROR_PHB_ABNORMAL_size

// ERROR_PHB_STATE
#define ERROR_PHB_STATE_size NULL
#define ERROR_PHB_STATE ERROR_PHB_STATE__enum,ERROR_PHB_STATE_size

// FUNC_PHB_SAT_FILE_CHANGE_CONTROL_BLOCK
#define FUNC_PHB_SAT_FILE_CHANGE_CONTROL_BLOCK_size "d"
#define FUNC_PHB_SAT_FILE_CHANGE_CONTROL_BLOCK FUNC_PHB_SAT_FILE_CHANGE_CONTROL_BLOCK__enum,FUNC_PHB_SAT_FILE_CHANGE_CONTROL_BLOCK_size

// FUNC_PHB_ISSUE_IO_WRITE_LN
#define FUNC_PHB_ISSUE_IO_WRITE_LN_size NULL
#define FUNC_PHB_ISSUE_IO_WRITE_LN FUNC_PHB_ISSUE_IO_WRITE_LN__enum,FUNC_PHB_ISSUE_IO_WRITE_LN_size

// FUNC_PHB_ISSUE_IO_READ_LN
#define FUNC_PHB_ISSUE_IO_READ_LN_size NULL
#define FUNC_PHB_ISSUE_IO_READ_LN FUNC_PHB_ISSUE_IO_READ_LN__enum,FUNC_PHB_ISSUE_IO_READ_LN_size

// FUNC_PHB_DELETE_SIM_LN
#define FUNC_PHB_DELETE_SIM_LN_size NULL
#define FUNC_PHB_DELETE_SIM_LN FUNC_PHB_DELETE_SIM_LN__enum,FUNC_PHB_DELETE_SIM_LN_size

// FUNC_PHB_DELETE_SIM_LN_ERR
#define FUNC_PHB_DELETE_SIM_LN_ERR_size NULL
#define FUNC_PHB_DELETE_SIM_LN_ERR FUNC_PHB_DELETE_SIM_LN_ERR__enum,FUNC_PHB_DELETE_SIM_LN_ERR_size

// FUNC_PHB_READ_SIM_LN
#define FUNC_PHB_READ_SIM_LN_size NULL
#define FUNC_PHB_READ_SIM_LN FUNC_PHB_READ_SIM_LN__enum,FUNC_PHB_READ_SIM_LN_size

// FUNC_PHB_READ_SIM_LN_ERR
#define FUNC_PHB_READ_SIM_LN_ERR_size NULL
#define FUNC_PHB_READ_SIM_LN_ERR FUNC_PHB_READ_SIM_LN_ERR__enum,FUNC_PHB_READ_SIM_LN_ERR_size

// FUNC_PHB_IS_LN_SIM_FILE_SUPPORT
#define FUNC_PHB_IS_LN_SIM_FILE_SUPPORT_size NULL
#define FUNC_PHB_IS_LN_SIM_FILE_SUPPORT FUNC_PHB_IS_LN_SIM_FILE_SUPPORT__enum,FUNC_PHB_IS_LN_SIM_FILE_SUPPORT_size

// FUNC_PHB_GET_LN_INFO_SET_VALUE
#define FUNC_PHB_GET_LN_INFO_SET_VALUE_size NULL
#define FUNC_PHB_GET_LN_INFO_SET_VALUE FUNC_PHB_GET_LN_INFO_SET_VALUE__enum,FUNC_PHB_GET_LN_INFO_SET_VALUE_size

// FUNC_PHB_GET_LN_INFO_ERR
#define FUNC_PHB_GET_LN_INFO_ERR_size NULL
#define FUNC_PHB_GET_LN_INFO_ERR FUNC_PHB_GET_LN_INFO_ERR__enum,FUNC_PHB_GET_LN_INFO_ERR_size

// FUNC_PHB_GET_LN_INFO
#define FUNC_PHB_GET_LN_INFO_size NULL
#define FUNC_PHB_GET_LN_INFO FUNC_PHB_GET_LN_INFO__enum,FUNC_PHB_GET_LN_INFO_size

// FUNC_PHB_NO_CALL_LOG_INIT_LN
#define FUNC_PHB_NO_CALL_LOG_INIT_LN_size NULL
#define FUNC_PHB_NO_CALL_LOG_INIT_LN FUNC_PHB_NO_CALL_LOG_INIT_LN__enum,FUNC_PHB_NO_CALL_LOG_INIT_LN_size

// FUNC_PHB_WRITE_SIM_LN_ERR
#define FUNC_PHB_WRITE_SIM_LN_ERR_size NULL
#define FUNC_PHB_WRITE_SIM_LN_ERR FUNC_PHB_WRITE_SIM_LN_ERR__enum,FUNC_PHB_WRITE_SIM_LN_ERR_size

// FUNC_PHB_WRITE_SIM_LN
#define FUNC_PHB_WRITE_SIM_LN_size NULL
#define FUNC_PHB_WRITE_SIM_LN FUNC_PHB_WRITE_SIM_LN__enum,FUNC_PHB_WRITE_SIM_LN_size

// FUNC_L4CPHB_GET_LN_FILE_INFO
#define FUNC_L4CPHB_GET_LN_FILE_INFO_size NULL
#define FUNC_L4CPHB_GET_LN_FILE_INFO FUNC_L4CPHB_GET_LN_FILE_INFO__enum,FUNC_L4CPHB_GET_LN_FILE_INFO_size

// FUNC_PHB_SE_SET_LN_CONTROL_BLOCK
#define FUNC_PHB_SE_SET_LN_CONTROL_BLOCK_size "d"
#define FUNC_PHB_SE_SET_LN_CONTROL_BLOCK FUNC_PHB_SE_SET_LN_CONTROL_BLOCK__enum,FUNC_PHB_SE_SET_LN_CONTROL_BLOCK_size

// FUNC_PHB_SIM_PREPARE_LN_DATA_TO_WRITE
#define FUNC_PHB_SIM_PREPARE_LN_DATA_TO_WRITE_size NULL
#define FUNC_PHB_SIM_PREPARE_LN_DATA_TO_WRITE FUNC_PHB_SIM_PREPARE_LN_DATA_TO_WRITE__enum,FUNC_PHB_SIM_PREPARE_LN_DATA_TO_WRITE_size

// FUNC_PHB_SIM_WRITE_LN_CNF
#define FUNC_PHB_SIM_WRITE_LN_CNF_size NULL
#define FUNC_PHB_SIM_WRITE_LN_CNF FUNC_PHB_SIM_WRITE_LN_CNF__enum,FUNC_PHB_SIM_WRITE_LN_CNF_size

// FUNC_PHB_SIM_WRITE_LN_FIRST_RECORD
#define FUNC_PHB_SIM_WRITE_LN_FIRST_RECORD_size NULL
#define FUNC_PHB_SIM_WRITE_LN_FIRST_RECORD FUNC_PHB_SIM_WRITE_LN_FIRST_RECORD__enum,FUNC_PHB_SIM_WRITE_LN_FIRST_RECORD_size

// FUNC_PHB_SIM_WRITE_LN
#define FUNC_PHB_SIM_WRITE_LN_size NULL
#define FUNC_PHB_SIM_WRITE_LN FUNC_PHB_SIM_WRITE_LN__enum,FUNC_PHB_SIM_WRITE_LN_size

// FUNC_PHB_SIM_READ_LN_CNF
#define FUNC_PHB_SIM_READ_LN_CNF_size NULL
#define FUNC_PHB_SIM_READ_LN_CNF FUNC_PHB_SIM_READ_LN_CNF__enum,FUNC_PHB_SIM_READ_LN_CNF_size

// FUNC_PHB_SIM_READ_LN
#define FUNC_PHB_SIM_READ_LN_size NULL
#define FUNC_PHB_SIM_READ_LN FUNC_PHB_SIM_READ_LN__enum,FUNC_PHB_SIM_READ_LN_size

// FUNC_PHB_COMPARE_BCD_FOR_WILD_CHAR
#define FUNC_PHB_COMPARE_BCD_FOR_WILD_CHAR_size NULL
#define FUNC_PHB_COMPARE_BCD_FOR_WILD_CHAR FUNC_PHB_COMPARE_BCD_FOR_WILD_CHAR__enum,FUNC_PHB_COMPARE_BCD_FOR_WILD_CHAR_size

// PHB_TRC_DEL_FIND_NEXT
#define PHB_TRC_DEL_FIND_NEXT_size "d"
#define PHB_TRC_DEL_FIND_NEXT PHB_TRC_DEL_FIND_NEXT__enum,PHB_TRC_DEL_FIND_NEXT_size

// PHB_TRC_DEL_CONT_MSISDN
#define PHB_TRC_DEL_CONT_MSISDN_size "ƒd"
#define PHB_TRC_DEL_CONT_MSISDN PHB_TRC_DEL_CONT_MSISDN__enum,PHB_TRC_DEL_CONT_MSISDN_size

// PHB_TRC_DEL_CONT_TOTAL
#define PHB_TRC_DEL_CONT_TOTAL_size "ƒd"
#define PHB_TRC_DEL_CONT_TOTAL PHB_TRC_DEL_CONT_TOTAL__enum,PHB_TRC_DEL_CONT_TOTAL_size

// PHB_TRC_SE_GET_IDX
#define PHB_TRC_SE_GET_IDX_size "d"
#define PHB_TRC_SE_GET_IDX PHB_TRC_SE_GET_IDX__enum,PHB_TRC_SE_GET_IDX_size

// PHB_TRC_SIM_DEL_CNF
#define PHB_TRC_SIM_DEL_CNF_size "‚d"
#define PHB_TRC_SIM_DEL_CNF PHB_TRC_SIM_DEL_CNF__enum,PHB_TRC_SIM_DEL_CNF_size

// PHB_TRC_READ_CONT
#define PHB_TRC_READ_CONT_size "„d"
#define PHB_TRC_READ_CONT PHB_TRC_READ_CONT__enum,PHB_TRC_READ_CONT_size

// PHB_TRC_CB_SET_STATE
#define PHB_TRC_CB_SET_STATE_size "‚d"
#define PHB_TRC_CB_SET_STATE PHB_TRC_CB_SET_STATE__enum,PHB_TRC_CB_SET_STATE_size

// PHB_TRC_CB_GET_STATE
#define PHB_TRC_CB_GET_STATE_size "‚d"
#define PHB_TRC_CB_GET_STATE PHB_TRC_CB_GET_STATE__enum,PHB_TRC_CB_GET_STATE_size

// PHB_SE_SET_INDEX_TRACE
#define PHB_SE_SET_INDEX_TRACE_size "d"
#define PHB_SE_SET_INDEX_TRACE PHB_SE_SET_INDEX_TRACE__enum,PHB_SE_SET_INDEX_TRACE_size

// PHB_TRC_SE_C
#define PHB_TRC_SE_C_size "d"
#define PHB_TRC_SE_C PHB_TRC_SE_C__enum,PHB_TRC_SE_C_size


#endif // PHB_TRC_GEN.H
