#ifndef _RAC_TRC_GEN_H_
#define _RAC_TRC_GEN_H_

// RAC_INFO_BEFORE_MAIN
#define RAC_INFO_BEFORE_MAIN_size "ƒc"
#define RAC_INFO_BEFORE_MAIN RAC_INFO_BEFORE_MAIN__enum,RAC_INFO_BEFORE_MAIN_size

// RAC_INFO
#define RAC_INFO_size "ƒc"
#define RAC_INFO RAC_INFO__enum,RAC_INFO_size

// RAC_MULTI_BAND
#define RAC_MULTI_BAND_size "ƒd"
#define RAC_MULTI_BAND RAC_MULTI_BAND__enum,RAC_MULTI_BAND_size

// RAC_INFO_GET_SEL_MOD
#define RAC_INFO_GET_SEL_MOD_size "d"
#define RAC_INFO_GET_SEL_MOD RAC_INFO_GET_SEL_MOD__enum,RAC_INFO_GET_SEL_MOD_size

// RAC_INFO_TST_INJECT_CMD_STRING
#define RAC_INFO_TST_INJECT_CMD_STRING_size "‚d"
#define RAC_INFO_TST_INJECT_CMD_STRING RAC_INFO_TST_INJECT_CMD_STRING__enum,RAC_INFO_TST_INJECT_CMD_STRING_size

// RAC_ABNORMAL_ASSERT
#define RAC_ABNORMAL_ASSERT_size NULL
#define RAC_ABNORMAL_ASSERT RAC_ABNORMAL_ASSERT__enum,RAC_ABNORMAL_ASSERT_size

// RAC_CHANGE_MS_CLASS
#define RAC_CHANGE_MS_CLASS_size "‚c"
#define RAC_CHANGE_MS_CLASS RAC_CHANGE_MS_CLASS__enum,RAC_CHANGE_MS_CLASS_size

// RAC_RECEIVE_DETACH_IND
#define RAC_RECEIVE_DETACH_IND_size "„c"
#define RAC_RECEIVE_DETACH_IND RAC_RECEIVE_DETACH_IND__enum,RAC_RECEIVE_DETACH_IND_size

// RAC_ACTIVATING_IGNORE
#define RAC_ACTIVATING_IGNORE_size NULL
#define RAC_ACTIVATING_IGNORE RAC_ACTIVATING_IGNORE__enum,RAC_ACTIVATING_IGNORE_size

// RAC_FN_rac_handle_class_change
#define RAC_FN_rac_handle_class_change_size NULL
#define RAC_FN_rac_handle_class_change RAC_FN_rac_handle_class_change__enum,RAC_FN_rac_handle_class_change_size

// RAC_CURRENT_ACTION
#define RAC_CURRENT_ACTION_size "c"
#define RAC_CURRENT_ACTION RAC_CURRENT_ACTION__enum,RAC_CURRENT_ACTION_size

// UNEXPECTED_MESSAGE
#define UNEXPECTED_MESSAGE_size "d"
#define UNEXPECTED_MESSAGE UNEXPECTED_MESSAGE__enum,UNEXPECTED_MESSAGE_size

// PLMN_LIST_FLAG_ERROR
#define PLMN_LIST_FLAG_ERROR_size "d"
#define PLMN_LIST_FLAG_ERROR PLMN_LIST_FLAG_ERROR__enum,PLMN_LIST_FLAG_ERROR_size

// RAC_RECV_PS_DETACH_WHEN_PLMN_SEL
#define RAC_RECV_PS_DETACH_WHEN_PLMN_SEL_size "‚d"
#define RAC_RECV_PS_DETACH_WHEN_PLMN_SEL RAC_RECV_PS_DETACH_WHEN_PLMN_SEL__enum,RAC_RECV_PS_DETACH_WHEN_PLMN_SEL_size

// RAC_L4C_GET_ATTACH_STATUS
#define RAC_L4C_GET_ATTACH_STATUS_size "„c"
#define RAC_L4C_GET_ATTACH_STATUS RAC_L4C_GET_ATTACH_STATUS__enum,RAC_L4C_GET_ATTACH_STATUS_size

// RAC_GET_STATE_STATUS_INFO
#define RAC_GET_STATE_STATUS_INFO_size "„c"
#define RAC_GET_STATE_STATUS_INFO RAC_GET_STATE_STATUS_INFO__enum,RAC_GET_STATE_STATUS_INFO_size

// RAC_NVRAM_WRITE_COUNT
#define RAC_NVRAM_WRITE_COUNT_size "‚d"
#define RAC_NVRAM_WRITE_COUNT RAC_NVRAM_WRITE_COUNT__enum,RAC_NVRAM_WRITE_COUNT_size

// RAC_PLMN_LIST_SEL_OR_BAND_X_WHEN_OTHER_ACTIONS
#define RAC_PLMN_LIST_SEL_OR_BAND_X_WHEN_OTHER_ACTIONS_size "c"
#define RAC_PLMN_LIST_SEL_OR_BAND_X_WHEN_OTHER_ACTIONS RAC_PLMN_LIST_SEL_OR_BAND_X_WHEN_OTHER_ACTIONS__enum,RAC_PLMN_LIST_SEL_OR_BAND_X_WHEN_OTHER_ACTIONS_size

// RAC_NOT_SEND_ATTACH_REQ_WHEN_RECV_PS_REG_REQ
#define RAC_NOT_SEND_ATTACH_REQ_WHEN_RECV_PS_REG_REQ_size "‚c"
#define RAC_NOT_SEND_ATTACH_REQ_WHEN_RECV_PS_REG_REQ RAC_NOT_SEND_ATTACH_REQ_WHEN_RECV_PS_REG_REQ__enum,RAC_NOT_SEND_ATTACH_REQ_WHEN_RECV_PS_REG_REQ_size

// RAC_SAME_SEND_REG_IND
#define RAC_SAME_SEND_REG_IND_size NULL
#define RAC_SAME_SEND_REG_IND RAC_SAME_SEND_REG_IND__enum,RAC_SAME_SEND_REG_IND_size

// RAC_SEND_ATTACH_UNEXPECTEDLY
#define RAC_SEND_ATTACH_UNEXPECTEDLY_size "‚c"
#define RAC_SEND_ATTACH_UNEXPECTEDLY RAC_SEND_ATTACH_UNEXPECTEDLY__enum,RAC_SEND_ATTACH_UNEXPECTEDLY_size

// SAT_LOCATION_INFO_MM_STATUS
#define SAT_LOCATION_INFO_MM_STATUS_size "c"
#define SAT_LOCATION_INFO_MM_STATUS SAT_LOCATION_INFO_MM_STATUS__enum,SAT_LOCATION_INFO_MM_STATUS_size

// SAT_EQUAL_LAST_LOCATION_INFO
#define SAT_EQUAL_LAST_LOCATION_INFO_size "d"
#define SAT_EQUAL_LAST_LOCATION_INFO SAT_EQUAL_LAST_LOCATION_INFO__enum,SAT_EQUAL_LAST_LOCATION_INFO_size

// RAC_RECEIVE_MM_SAME_LAI_IMSI_ATTACHING
#define RAC_RECEIVE_MM_SAME_LAI_IMSI_ATTACHING_size NULL
#define RAC_RECEIVE_MM_SAME_LAI_IMSI_ATTACHING RAC_RECEIVE_MM_SAME_LAI_IMSI_ATTACHING__enum,RAC_RECEIVE_MM_SAME_LAI_IMSI_ATTACHING_size

// RAC_AUTO_ATTACH
#define RAC_AUTO_ATTACH_size "‚d"
#define RAC_AUTO_ATTACH RAC_AUTO_ATTACH__enum,RAC_AUTO_ATTACH_size

// RAC_START_TIMER
#define RAC_START_TIMER_size "c"
#define RAC_START_TIMER RAC_START_TIMER__enum,RAC_START_TIMER_size

// RAC_CANCEL_TIMER
#define RAC_CANCEL_TIMER_size "c"
#define RAC_CANCEL_TIMER RAC_CANCEL_TIMER__enum,RAC_CANCEL_TIMER_size

// RAC_TIMEOUT
#define RAC_TIMEOUT_size "‚c"
#define RAC_TIMEOUT RAC_TIMEOUT__enum,RAC_TIMEOUT_size

// RAC_GPRS_TRANSFER_PREFERENCE
#define RAC_GPRS_TRANSFER_PREFERENCE_size "c"
#define RAC_GPRS_TRANSFER_PREFERENCE RAC_GPRS_TRANSFER_PREFERENCE__enum,RAC_GPRS_TRANSFER_PREFERENCE_size

// RAC_NASRAT_PREFERENCE
#define RAC_NASRAT_PREFERENCE_size "c"
#define RAC_NASRAT_PREFERENCE RAC_NASRAT_PREFERENCE__enum,RAC_NASRAT_PREFERENCE_size

// RAC_IRAT_PREFERENCE
#define RAC_IRAT_PREFERENCE_size "c"
#define RAC_IRAT_PREFERENCE RAC_IRAT_PREFERENCE__enum,RAC_IRAT_PREFERENCE_size


#endif // RAC_TRC_GEN.H
