#ifndef _RLP_TRC_GEN_H_
#define _RLP_TRC_GEN_H_

// FUNC_RLP_INIT_LINK_VARS
#define FUNC_RLP_INIT_LINK_VARS_size NULL
#define FUNC_RLP_INIT_LINK_VARS FUNC_RLP_INIT_LINK_VARS__enum,FUNC_RLP_INIT_LINK_VARS_size

// IN_RLP_CHECK_XID_PARAMS
#define IN_RLP_CHECK_XID_PARAMS_size NULL
#define IN_RLP_CHECK_XID_PARAMS IN_RLP_CHECK_XID_PARAMS__enum,IN_RLP_CHECK_XID_PARAMS_size

// OUT_RLP_CHECK_XID_PARAMS
#define OUT_RLP_CHECK_XID_PARAMS_size NULL
#define OUT_RLP_CHECK_XID_PARAMS OUT_RLP_CHECK_XID_PARAMS__enum,OUT_RLP_CHECK_XID_PARAMS_size

// IN_RLP_TEST_HDLR
#define IN_RLP_TEST_HDLR_size NULL
#define IN_RLP_TEST_HDLR IN_RLP_TEST_HDLR__enum,IN_RLP_TEST_HDLR_size

// IN_RLP_START_REMAP
#define IN_RLP_START_REMAP_size NULL
#define IN_RLP_START_REMAP IN_RLP_START_REMAP__enum,IN_RLP_START_REMAP_size

// OUT_RLP_START_REMAP
#define OUT_RLP_START_REMAP_size NULL
#define OUT_RLP_START_REMAP OUT_RLP_START_REMAP__enum,OUT_RLP_START_REMAP_size

// IN_RLP_STOP_REMAP
#define IN_RLP_STOP_REMAP_size NULL
#define IN_RLP_STOP_REMAP IN_RLP_STOP_REMAP__enum,IN_RLP_STOP_REMAP_size

// OUT_RLP_STOP_REMAP
#define OUT_RLP_STOP_REMAP_size NULL
#define OUT_RLP_STOP_REMAP OUT_RLP_STOP_REMAP__enum,OUT_RLP_STOP_REMAP_size

// state_RLP_STATE
#define state_RLP_STATE_size "d"
#define state_RLP_STATE state_RLP_STATE__enum,state_RLP_STATE_size

// state_RLP_ADM_DETACHED_STATE
#define state_RLP_ADM_DETACHED_STATE_size NULL
#define state_RLP_ADM_DETACHED_STATE state_RLP_ADM_DETACHED_STATE__enum,state_RLP_ADM_DETACHED_STATE_size

// state_RLP_ADM_ATTACHED_STATE
#define state_RLP_ADM_ATTACHED_STATE_size NULL
#define state_RLP_ADM_ATTACHED_STATE state_RLP_ADM_ATTACHED_STATE__enum,state_RLP_ADM_ATTACHED_STATE_size

// state_RLP_PENDING_CONN_REQ_STATE
#define state_RLP_PENDING_CONN_REQ_STATE_size NULL
#define state_RLP_PENDING_CONN_REQ_STATE state_RLP_PENDING_CONN_REQ_STATE__enum,state_RLP_PENDING_CONN_REQ_STATE_size

// state_RLP_PENDING_CONN_IND_STATE
#define state_RLP_PENDING_CONN_IND_STATE_size NULL
#define state_RLP_PENDING_CONN_IND_STATE state_RLP_PENDING_CONN_IND_STATE__enum,state_RLP_PENDING_CONN_IND_STATE_size

// state_RLP_CONNECTED_STATE
#define state_RLP_CONNECTED_STATE_size NULL
#define state_RLP_CONNECTED_STATE state_RLP_CONNECTED_STATE__enum,state_RLP_CONNECTED_STATE_size

// state_RLP_DISCONNECTING_STATE
#define state_RLP_DISCONNECTING_STATE_size NULL
#define state_RLP_DISCONNECTING_STATE state_RLP_DISCONNECTING_STATE__enum,state_RLP_DISCONNECTING_STATE_size

// state_RLP_PENDING_RESET_REQ_STATE
#define state_RLP_PENDING_RESET_REQ_STATE_size NULL
#define state_RLP_PENDING_RESET_REQ_STATE state_RLP_PENDING_RESET_REQ_STATE__enum,state_RLP_PENDING_RESET_REQ_STATE_size

// state_RLP_PENDING_RESET_IND_STATE
#define state_RLP_PENDING_RESET_IND_STATE_size NULL
#define state_RLP_PENDING_RESET_IND_STATE state_RLP_PENDING_RESET_IND_STATE__enum,state_RLP_PENDING_RESET_IND_STATE_size

// INFO_RLP_FRAME_TYPE
#define INFO_RLP_FRAME_TYPE_size "d"
#define INFO_RLP_FRAME_TYPE INFO_RLP_FRAME_TYPE__enum,INFO_RLP_FRAME_TYPE_size

// RLP_SREJ_TIMER_TIMEOUT
#define RLP_SREJ_TIMER_TIMEOUT_size "d"
#define RLP_SREJ_TIMER_TIMEOUT RLP_SREJ_TIMER_TIMEOUT__enum,RLP_SREJ_TIMER_TIMEOUT_size

// RLP_XID_COLLISION
#define RLP_XID_COLLISION_size NULL
#define RLP_XID_COLLISION RLP_XID_COLLISION__enum,RLP_XID_COLLISION_size

// RLP_NUM_OF_LOST_I_FRAMS
#define RLP_NUM_OF_LOST_I_FRAMS_size "ƒd"
#define RLP_NUM_OF_LOST_I_FRAMS RLP_NUM_OF_LOST_I_FRAMS__enum,RLP_NUM_OF_LOST_I_FRAMS_size

// RLP_NS_VR_VA_VALUES
#define RLP_NS_VR_VA_VALUES_size "ƒd"
#define RLP_NS_VR_VA_VALUES RLP_NS_VR_VA_VALUES__enum,RLP_NS_VR_VA_VALUES_size

// RLP_NR_VA_VALUES
#define RLP_NR_VA_VALUES_size "‚d"
#define RLP_NR_VA_VALUES RLP_NR_VA_VALUES__enum,RLP_NR_VA_VALUES_size

// RLP_NUM_OF_DEST_REMAP_FRAMS
#define RLP_NUM_OF_DEST_REMAP_FRAMS_size "d"
#define RLP_NUM_OF_DEST_REMAP_FRAMS RLP_NUM_OF_DEST_REMAP_FRAMS__enum,RLP_NUM_OF_DEST_REMAP_FRAMS_size

// RLP_LOCAL_RX_READY
#define RLP_LOCAL_RX_READY_size "d"
#define RLP_LOCAL_RX_READY RLP_LOCAL_RX_READY__enum,RLP_LOCAL_RX_READY_size

// RLP_N2_INFO
#define RLP_N2_INFO_size "‚d"
#define RLP_N2_INFO RLP_N2_INFO__enum,RLP_N2_INFO_size

// RLP_RAT_CHANGE_SUSPEND
#define RLP_RAT_CHANGE_SUSPEND_size NULL
#define RLP_RAT_CHANGE_SUSPEND RLP_RAT_CHANGE_SUSPEND__enum,RLP_RAT_CHANGE_SUSPEND_size

// RLP_SEND_QUEUE_FULL
#define RLP_SEND_QUEUE_FULL_size NULL
#define RLP_SEND_QUEUE_FULL RLP_SEND_QUEUE_FULL__enum,RLP_SEND_QUEUE_FULL_size

// RLP_UP_WINDOW_FULL
#define RLP_UP_WINDOW_FULL_size "‚d"
#define RLP_UP_WINDOW_FULL RLP_UP_WINDOW_FULL__enum,RLP_UP_WINDOW_FULL_size

// RLP_V2_ROLLBACK_TO_V0
#define RLP_V2_ROLLBACK_TO_V0_size NULL
#define RLP_V2_ROLLBACK_TO_V0 RLP_V2_ROLLBACK_TO_V0__enum,RLP_V2_ROLLBACK_TO_V0_size

// RLP_VER_NUM
#define RLP_VER_NUM_size "d"
#define RLP_VER_NUM RLP_VER_NUM__enum,RLP_VER_NUM_size

// ERROR_ACTIVATE_RA
#define ERROR_ACTIVATE_RA_size NULL
#define ERROR_ACTIVATE_RA ERROR_ACTIVATE_RA__enum,ERROR_ACTIVATE_RA_size

// ERROR_RLP_VD_STATE
#define ERROR_RLP_VD_STATE_size NULL
#define ERROR_RLP_VD_STATE ERROR_RLP_VD_STATE__enum,ERROR_RLP_VD_STATE_size

// ERROR_RLP_NO_CTRL_BUFF
#define ERROR_RLP_NO_CTRL_BUFF_size NULL
#define ERROR_RLP_NO_CTRL_BUFF ERROR_RLP_NO_CTRL_BUFF__enum,ERROR_RLP_NO_CTRL_BUFF_size

// ERROR_RLP_TIMEOUT_AT_ERROR_STATE
#define ERROR_RLP_TIMEOUT_AT_ERROR_STATE_size "d"
#define ERROR_RLP_TIMEOUT_AT_ERROR_STATE ERROR_RLP_TIMEOUT_AT_ERROR_STATE__enum,ERROR_RLP_TIMEOUT_AT_ERROR_STATE_size

// ERROR_RLP_RA_DL_SIZE_MISMATCH
#define ERROR_RLP_RA_DL_SIZE_MISMATCH_size "‚d"
#define ERROR_RLP_RA_DL_SIZE_MISMATCH ERROR_RLP_RA_DL_SIZE_MISMATCH__enum,ERROR_RLP_RA_DL_SIZE_MISMATCH_size

// ERROR_RLP_L2R_UL_SIZE_MISMATCH
#define ERROR_RLP_L2R_UL_SIZE_MISMATCH_size "‚d"
#define ERROR_RLP_L2R_UL_SIZE_MISMATCH ERROR_RLP_L2R_UL_SIZE_MISMATCH__enum,ERROR_RLP_L2R_UL_SIZE_MISMATCH_size

// ERROR_RLP_INVALID_I_FRAME
#define ERROR_RLP_INVALID_I_FRAME_size NULL
#define ERROR_RLP_INVALID_I_FRAME ERROR_RLP_INVALID_I_FRAME__enum,ERROR_RLP_INVALID_I_FRAME_size

// ERROR_RLP_INVALID_FRAME
#define ERROR_RLP_INVALID_FRAME_size NULL
#define ERROR_RLP_INVALID_FRAME ERROR_RLP_INVALID_FRAME__enum,ERROR_RLP_INVALID_FRAME_size

// ERROR_RLP_INVALID_FRAME_SIZE
#define ERROR_RLP_INVALID_FRAME_SIZE_size "‚d"
#define ERROR_RLP_INVALID_FRAME_SIZE ERROR_RLP_INVALID_FRAME_SIZE__enum,ERROR_RLP_INVALID_FRAME_SIZE_size

// ERROR_RLP_DL_NO_MEM
#define ERROR_RLP_DL_NO_MEM_size NULL
#define ERROR_RLP_DL_NO_MEM ERROR_RLP_DL_NO_MEM__enum,ERROR_RLP_DL_NO_MEM_size

// RLP_RX_S_FRAME_WITH_INVALID_NR
#define RLP_RX_S_FRAME_WITH_INVALID_NR_size "‚d"
#define RLP_RX_S_FRAME_WITH_INVALID_NR RLP_RX_S_FRAME_WITH_INVALID_NR__enum,RLP_RX_S_FRAME_WITH_INVALID_NR_size

// RLP_RX_INVALID_CONBI_FRAME
#define RLP_RX_INVALID_CONBI_FRAME_size "ƒd"
#define RLP_RX_INVALID_CONBI_FRAME RLP_RX_INVALID_CONBI_FRAME__enum,RLP_RX_INVALID_CONBI_FRAME_size

// RLP_RX_FCS_ERROR
#define RLP_RX_FCS_ERROR_size NULL
#define RLP_RX_FCS_ERROR RLP_RX_FCS_ERROR__enum,RLP_RX_FCS_ERROR_size

// ERROR_RLP_INVALID_XID
#define ERROR_RLP_INVALID_XID_size NULL
#define ERROR_RLP_INVALID_XID ERROR_RLP_INVALID_XID__enum,ERROR_RLP_INVALID_XID_size

// RLP_UPLINK_FRAME
#define RLP_UPLINK_FRAME_size "d"
#define RLP_UPLINK_FRAME RLP_UPLINK_FRAME__enum,RLP_UPLINK_FRAME_size

// RLP_UPLINK_FRAME_INFO
#define RLP_UPLINK_FRAME_INFO_size "d‰h"
#define RLP_UPLINK_FRAME_INFO RLP_UPLINK_FRAME_INFO__enum,RLP_UPLINK_FRAME_INFO_size

// RLP_SEND_REMAP_FRAME
#define RLP_SEND_REMAP_FRAME_size NULL
#define RLP_SEND_REMAP_FRAME RLP_SEND_REMAP_FRAME__enum,RLP_SEND_REMAP_FRAME_size

// RLP_DELAY_TICKS
#define RLP_DELAY_TICKS_size "d"
#define RLP_DELAY_TICKS RLP_DELAY_TICKS__enum,RLP_DELAY_TICKS_size

// RLP_DL_FRAME_INFO
#define RLP_DL_FRAME_INFO_size "…d"
#define RLP_DL_FRAME_INFO RLP_DL_FRAME_INFO__enum,RLP_DL_FRAME_INFO_size

// RLP_TIMER_EXPIRY_HDLR
#define RLP_TIMER_EXPIRY_HDLR_size "d"
#define RLP_TIMER_EXPIRY_HDLR RLP_TIMER_EXPIRY_HDLR__enum,RLP_TIMER_EXPIRY_HDLR_size

// RLP_START_TIMER
#define RLP_START_TIMER_size "‚d"
#define RLP_START_TIMER RLP_START_TIMER__enum,RLP_START_TIMER_size

// RLP_STOP_TIMER
#define RLP_STOP_TIMER_size "‚d"
#define RLP_STOP_TIMER RLP_STOP_TIMER__enum,RLP_STOP_TIMER_size

// RLP_RETRANS_COUNT
#define RLP_RETRANS_COUNT_size "‚d"
#define RLP_RETRANS_COUNT RLP_RETRANS_COUNT__enum,RLP_RETRANS_COUNT_size

// RLP_NO_FRAMES_WAIT_SENT
#define RLP_NO_FRAMES_WAIT_SENT_size "ƒd"
#define RLP_NO_FRAMES_WAIT_SENT RLP_NO_FRAMES_WAIT_SENT__enum,RLP_NO_FRAMES_WAIT_SENT_size

// RLP_UL_HEDER
#define RLP_UL_HEDER_size "‚d"
#define RLP_UL_HEDER RLP_UL_HEDER__enum,RLP_UL_HEDER_size

// RLP_DL_HEDER
#define RLP_DL_HEDER_size "‚d"
#define RLP_DL_HEDER RLP_DL_HEDER__enum,RLP_DL_HEDER_size


#endif // RLP_TRC_GEN.H
