#ifndef _SECLIB_TRC_GEN_H_
#define _SECLIB_TRC_GEN_H_

// SECLIB_MEM_INIT
#define SECLIB_MEM_INIT_size NULL
#define SECLIB_MEM_INIT SECLIB_MEM_INIT__enum,SECLIB_MEM_INIT_size

// SECLIB_OSSL_MEM_INIT
#define SECLIB_OSSL_MEM_INIT_size NULL
#define SECLIB_OSSL_MEM_INIT SECLIB_OSSL_MEM_INIT__enum,SECLIB_OSSL_MEM_INIT_size

// OSSL_ADP_MEM_LOG_INIT
#define OSSL_ADP_MEM_LOG_INIT_size NULL
#define OSSL_ADP_MEM_LOG_INIT OSSL_ADP_MEM_LOG_INIT__enum,OSSL_ADP_MEM_LOG_INIT_size

// OSSL_ADP_MALLOC
#define OSSL_ADP_MALLOC_size "sƒd"
#define OSSL_ADP_MALLOC OSSL_ADP_MALLOC__enum,OSSL_ADP_MALLOC_size

// OSSL_ADP_REALLOC_START
#define OSSL_ADP_REALLOC_START_size "d"
#define OSSL_ADP_REALLOC_START OSSL_ADP_REALLOC_START__enum,OSSL_ADP_REALLOC_START_size

// OSSL_ADP_REALLOC_END
#define OSSL_ADP_REALLOC_END_size "sƒd"
#define OSSL_ADP_REALLOC_END OSSL_ADP_REALLOC_END__enum,OSSL_ADP_REALLOC_END_size

// OSSL_ADP_FREE
#define OSSL_ADP_FREE_size "d"
#define OSSL_ADP_FREE OSSL_ADP_FREE__enum,OSSL_ADP_FREE_size

// OSSL_ADP_MEM_STAT_FREE_FOUND
#define OSSL_ADP_MEM_STAT_FREE_FOUND_size "ƒdsd"
#define OSSL_ADP_MEM_STAT_FREE_FOUND OSSL_ADP_MEM_STAT_FREE_FOUND__enum,OSSL_ADP_MEM_STAT_FREE_FOUND_size

// OSSL_ADP_MEM_STAT_ALLOC_FOUND
#define OSSL_ADP_MEM_STAT_ALLOC_FOUND_size "ƒdsd"
#define OSSL_ADP_MEM_STAT_ALLOC_FOUND OSSL_ADP_MEM_STAT_ALLOC_FOUND__enum,OSSL_ADP_MEM_STAT_ALLOC_FOUND_size

// OSSL_ADP_MEM_STAT_ALLOC_EXCEED
#define OSSL_ADP_MEM_STAT_ALLOC_EXCEED_size NULL
#define OSSL_ADP_MEM_STAT_ALLOC_EXCEED OSSL_ADP_MEM_STAT_ALLOC_EXCEED__enum,OSSL_ADP_MEM_STAT_ALLOC_EXCEED_size

// OSSL_ADP_MEM_STAT_LOG
#define OSSL_ADP_MEM_STAT_LOG_size "ƒd"
#define OSSL_ADP_MEM_STAT_LOG OSSL_ADP_MEM_STAT_LOG__enum,OSSL_ADP_MEM_STAT_LOG_size

// OSSL_ADP_MEM_USER_FOUND
#define OSSL_ADP_MEM_USER_FOUND_size "„d"
#define OSSL_ADP_MEM_USER_FOUND OSSL_ADP_MEM_USER_FOUND__enum,OSSL_ADP_MEM_USER_FOUND_size

// OSSL_ADP_MEM_USER_NEW
#define OSSL_ADP_MEM_USER_NEW_size "‚d"
#define OSSL_ADP_MEM_USER_NEW OSSL_ADP_MEM_USER_NEW__enum,OSSL_ADP_MEM_USER_NEW_size

// SECLIB_MALLOC
#define SECLIB_MALLOC_size "d"
#define SECLIB_MALLOC SECLIB_MALLOC__enum,SECLIB_MALLOC_size

// SECLIB_FREE
#define SECLIB_FREE_size "d"
#define SECLIB_FREE SECLIB_FREE__enum,SECLIB_FREE_size

// SECLIB_MEM_LOG
#define SECLIB_MEM_LOG_size NULL
#define SECLIB_MEM_LOG SECLIB_MEM_LOG__enum,SECLIB_MEM_LOG_size

// SECLIB_MEM_GET_MAX_AVAIL_SIZE
#define SECLIB_MEM_GET_MAX_AVAIL_SIZE_size "‚d"
#define SECLIB_MEM_GET_MAX_AVAIL_SIZE SECLIB_MEM_GET_MAX_AVAIL_SIZE__enum,SECLIB_MEM_GET_MAX_AVAIL_SIZE_size

// SECLIB_MEM_PEAK_SIZE
#define SECLIB_MEM_PEAK_SIZE_size "d"
#define SECLIB_MEM_PEAK_SIZE SECLIB_MEM_PEAK_SIZE__enum,SECLIB_MEM_PEAK_SIZE_size

// SECLIB_MEM_CURR_SIZE
#define SECLIB_MEM_CURR_SIZE_size "d"
#define SECLIB_MEM_CURR_SIZE SECLIB_MEM_CURR_SIZE__enum,SECLIB_MEM_CURR_SIZE_size

// SECLIB_MEM_MAX_CHUNK
#define SECLIB_MEM_MAX_CHUNK_size "d"
#define SECLIB_MEM_MAX_CHUNK SECLIB_MEM_MAX_CHUNK__enum,SECLIB_MEM_MAX_CHUNK_size

// SECLIB_MEM_ALLOC_ENTRIES
#define SECLIB_MEM_ALLOC_ENTRIES_size "d"
#define SECLIB_MEM_ALLOC_ENTRIES SECLIB_MEM_ALLOC_ENTRIES__enum,SECLIB_MEM_ALLOC_ENTRIES_size


#endif // SECLIB_TRC_GEN.H
