#ifndef _SMS_TRC_GEN_H_
#define _SMS_TRC_GEN_H_

// SMS_NW_TO_MS_PEER_MSG
#define SMS_NW_TO_MS_PEER_MSG_size "cd"
#define SMS_NW_TO_MS_PEER_MSG SMS_NW_TO_MS_PEER_MSG__enum,SMS_NW_TO_MS_PEER_MSG_size

// SMS_MS_TO_NW_PEER_MSG
#define SMS_MS_TO_NW_PEER_MSG_size "cd"
#define SMS_MS_TO_NW_PEER_MSG SMS_MS_TO_NW_PEER_MSG__enum,SMS_MS_TO_NW_PEER_MSG_size

// FUNC_SMS_INIT
#define FUNC_SMS_INIT_size NULL
#define FUNC_SMS_INIT FUNC_SMS_INIT__enum,FUNC_SMS_INIT_size

// SMS_SUBMIT_HDLR
#define SMS_SUBMIT_HDLR_size "d"
#define SMS_SUBMIT_HDLR SMS_SUBMIT_HDLR__enum,SMS_SUBMIT_HDLR_size

// SMMA_FUNC
#define SMMA_FUNC_size NULL
#define SMMA_FUNC SMMA_FUNC__enum,SMMA_FUNC_size

// SMS_DELIVER_REPORT_FUNC
#define SMS_DELIVER_REPORT_FUNC_size "d"
#define SMS_DELIVER_REPORT_FUNC SMS_DELIVER_REPORT_FUNC__enum,SMS_DELIVER_REPORT_FUNC_size

// SMS_SUBMIT_ABORT_HDLR_FUNC
#define SMS_SUBMIT_ABORT_HDLR_FUNC_size "d"
#define SMS_SUBMIT_ABORT_HDLR_FUNC SMS_SUBMIT_ABORT_HDLR_FUNC__enum,SMS_SUBMIT_ABORT_HDLR_FUNC_size

// SMS_RP_MO_DATA_FUNC
#define SMS_RP_MO_DATA_FUNC_size "d"
#define SMS_RP_MO_DATA_FUNC SMS_RP_MO_DATA_FUNC__enum,SMS_RP_MO_DATA_FUNC_size

// SMS_RL_REPORT_FUNC
#define SMS_RL_REPORT_FUNC_size "d"
#define SMS_RL_REPORT_FUNC SMS_RL_REPORT_FUNC__enum,SMS_RL_REPORT_FUNC_size

// SMS_RL_TRY_ABORT_FUNC
#define SMS_RL_TRY_ABORT_FUNC_size "d"
#define SMS_RL_TRY_ABORT_FUNC SMS_RL_TRY_ABORT_FUNC__enum,SMS_RL_TRY_ABORT_FUNC_size

// SMS_RL_ABORT_SUCC
#define SMS_RL_ABORT_SUCC_size "d"
#define SMS_RL_ABORT_SUCC SMS_RL_ABORT_SUCC__enum,SMS_RL_ABORT_SUCC_size

// SMS_CP_MO_DATA_IDLE_CS_FUNC
#define SMS_CP_MO_DATA_IDLE_CS_FUNC_size "d"
#define SMS_CP_MO_DATA_IDLE_CS_FUNC SMS_CP_MO_DATA_IDLE_CS_FUNC__enum,SMS_CP_MO_DATA_IDLE_CS_FUNC_size

// SMS_CP_MO_EST_REQ_FUNC
#define SMS_CP_MO_EST_REQ_FUNC_size "cd"
#define SMS_CP_MO_EST_REQ_FUNC SMS_CP_MO_EST_REQ_FUNC__enum,SMS_CP_MO_EST_REQ_FUNC_size

// SMS_MM_CONN_EST_FUNC
#define SMS_MM_CONN_EST_FUNC_size "cd"
#define SMS_MM_CONN_EST_FUNC SMS_MM_CONN_EST_FUNC__enum,SMS_MM_CONN_EST_FUNC_size

// SMS_RECV_CP_DATA_FIRST_FUNC
#define SMS_RECV_CP_DATA_FIRST_FUNC_size "d"
#define SMS_RECV_CP_DATA_FIRST_FUNC SMS_RECV_CP_DATA_FIRST_FUNC__enum,SMS_RECV_CP_DATA_FIRST_FUNC_size

// SMS_MO_CP_ERROR_FUNC
#define SMS_MO_CP_ERROR_FUNC_size "d"
#define SMS_MO_CP_ERROR_FUNC SMS_MO_CP_ERROR_FUNC__enum,SMS_MO_CP_ERROR_FUNC_size

// SMS_MO_EST_FUNC
#define SMS_MO_EST_FUNC_size "d"
#define SMS_MO_EST_FUNC SMS_MO_EST_FUNC__enum,SMS_MO_EST_FUNC_size

// SMS_REL_MM_CONN
#define SMS_REL_MM_CONN_size "d"
#define SMS_REL_MM_CONN SMS_REL_MM_CONN__enum,SMS_REL_MM_CONN_size

// SMS_SEND_CP_ACK_FUNC
#define SMS_SEND_CP_ACK_FUNC_size "cd"
#define SMS_SEND_CP_ACK_FUNC SMS_SEND_CP_ACK_FUNC__enum,SMS_SEND_CP_ACK_FUNC_size

// SMS_SEND_CP_ERROR_FUNC
#define SMS_SEND_CP_ERROR_FUNC_size "c‚d"
#define SMS_SEND_CP_ERROR_FUNC SMS_SEND_CP_ERROR_FUNC__enum,SMS_SEND_CP_ERROR_FUNC_size

// SMS_SEND_CP_DATA_FUNC
#define SMS_SEND_CP_DATA_FUNC_size "‚cd"
#define SMS_SEND_CP_DATA_FUNC SMS_SEND_CP_DATA_FUNC__enum,SMS_SEND_CP_DATA_FUNC_size

// RECV_CP_DATA_FIRST_FUNC
#define RECV_CP_DATA_FIRST_FUNC_size "cd"
#define RECV_CP_DATA_FIRST_FUNC RECV_CP_DATA_FIRST_FUNC__enum,RECV_CP_DATA_FIRST_FUNC_size

// SMS_MT_MM_EST_FUNC
#define SMS_MT_MM_EST_FUNC_size NULL
#define SMS_MT_MM_EST_FUNC SMS_MT_MM_EST_FUNC__enum,SMS_MT_MM_EST_FUNC_size

// SMS_ABORT_MSG_IN_CM_QUEUE_FUNC
#define SMS_ABORT_MSG_IN_CM_QUEUE_FUNC_size NULL
#define SMS_ABORT_MSG_IN_CM_QUEUE_FUNC SMS_ABORT_MSG_IN_CM_QUEUE_FUNC__enum,SMS_ABORT_MSG_IN_CM_QUEUE_FUNC_size

// SMS_CP_MO_ABORT_MSG_FUNC
#define SMS_CP_MO_ABORT_MSG_FUNC_size "cd"
#define SMS_CP_MO_ABORT_MSG_FUNC SMS_CP_MO_ABORT_MSG_FUNC__enum,SMS_CP_MO_ABORT_MSG_FUNC_size

// SMS_CM_GMM_EST_RECNF
#define SMS_CM_GMM_EST_RECNF_size "d"
#define SMS_CM_GMM_EST_RECNF SMS_CM_GMM_EST_RECNF__enum,SMS_CM_GMM_EST_RECNF_size

// SMS_START_TIMER_FUNC
#define SMS_START_TIMER_FUNC_size "c‚d"
#define SMS_START_TIMER_FUNC SMS_START_TIMER_FUNC__enum,SMS_START_TIMER_FUNC_size

// SMS_STOP_TIMER_FUNC
#define SMS_STOP_TIMER_FUNC_size "cd"
#define SMS_STOP_TIMER_FUNC SMS_STOP_TIMER_FUNC__enum,SMS_STOP_TIMER_FUNC_size

// TR1M_TIMEOUT
#define TR1M_TIMEOUT_size "d"
#define TR1M_TIMEOUT TR1M_TIMEOUT__enum,TR1M_TIMEOUT_size

// TR2M_TIMEOUT
#define TR2M_TIMEOUT_size "d"
#define TR2M_TIMEOUT TR2M_TIMEOUT__enum,TR2M_TIMEOUT_size

// TRAM_TIMEOUT
#define TRAM_TIMEOUT_size "d"
#define TRAM_TIMEOUT TRAM_TIMEOUT__enum,TRAM_TIMEOUT_size

// TC1M_TIMEOUT
#define TC1M_TIMEOUT_size "d"
#define TC1M_TIMEOUT TC1M_TIMEOUT__enum,TC1M_TIMEOUT_size

// TL_RETRY_TIMEOUT
#define TL_RETRY_TIMEOUT_size "d"
#define TL_RETRY_TIMEOUT TL_RETRY_TIMEOUT__enum,TL_RETRY_TIMEOUT_size

// RL_MMS_TIMEOUT
#define RL_MMS_TIMEOUT_size "d"
#define RL_MMS_TIMEOUT RL_MMS_TIMEOUT__enum,RL_MMS_TIMEOUT_size

// SMS_SMC_MO_STATE
#define SMS_SMC_MO_STATE_size "cdc"
#define SMS_SMC_MO_STATE SMS_SMC_MO_STATE__enum,SMS_SMC_MO_STATE_size

// SMS_SMR_STATE
#define SMS_SMR_STATE_size "dc"
#define SMS_SMR_STATE SMS_SMR_STATE__enum,SMS_SMR_STATE_size

// SMS_SMTL_STATE
#define SMS_SMTL_STATE_size "dc"
#define SMS_SMTL_STATE SMS_SMTL_STATE__enum,SMS_SMTL_STATE_size

// SMS_MMS_STATE
#define SMS_MMS_STATE_size "cd"
#define SMS_MMS_STATE SMS_MMS_STATE__enum,SMS_MMS_STATE_size

// USE_THE_SAME_RR_CONN
#define USE_THE_SAME_RR_CONN_size NULL
#define USE_THE_SAME_RR_CONN USE_THE_SAME_RR_CONN__enum,USE_THE_SAME_RR_CONN_size

// TL_FSM_MSG
#define TL_FSM_MSG_size "dc"
#define TL_FSM_MSG TL_FSM_MSG__enum,TL_FSM_MSG_size

// RL_FSM_MSG
#define RL_FSM_MSG_size "dc"
#define RL_FSM_MSG RL_FSM_MSG__enum,RL_FSM_MSG_size

// CM_MO_FSM_MSG
#define CM_MO_FSM_MSG_size "dc"
#define CM_MO_FSM_MSG CM_MO_FSM_MSG__enum,CM_MO_FSM_MSG_size

// CM_MT_FSM_MSG
#define CM_MT_FSM_MSG_size "dc"
#define CM_MT_FSM_MSG CM_MT_FSM_MSG__enum,CM_MT_FSM_MSG_size

// BEAR_SERVICE
#define BEAR_SERVICE_size "„c"
#define BEAR_SERVICE BEAR_SERVICE__enum,BEAR_SERVICE_size

// RL_MSG_DEQUEUE
#define RL_MSG_DEQUEUE_size "d"
#define RL_MSG_DEQUEUE RL_MSG_DEQUEUE__enum,RL_MSG_DEQUEUE_size

// RL_MSG_ENQUEUE
#define RL_MSG_ENQUEUE_size "d"
#define RL_MSG_ENQUEUE RL_MSG_ENQUEUE__enum,RL_MSG_ENQUEUE_size

// MT_RECEIVE_WRONG_CP_MESSAGE_BY_EST_IND
#define MT_RECEIVE_WRONG_CP_MESSAGE_BY_EST_IND_size "cd"
#define MT_RECEIVE_WRONG_CP_MESSAGE_BY_EST_IND MT_RECEIVE_WRONG_CP_MESSAGE_BY_EST_IND__enum,MT_RECEIVE_WRONG_CP_MESSAGE_BY_EST_IND_size

// MT_RECEIVE_CP_DATA_IN_WRONG_STATE
#define MT_RECEIVE_CP_DATA_IN_WRONG_STATE_size "cd"
#define MT_RECEIVE_CP_DATA_IN_WRONG_STATE MT_RECEIVE_CP_DATA_IN_WRONG_STATE__enum,MT_RECEIVE_CP_DATA_IN_WRONG_STATE_size

// MT_RECEIVE_NEW_CP_DATA_WITHOUT_CP_ACK
#define MT_RECEIVE_NEW_CP_DATA_WITHOUT_CP_ACK_size "cd"
#define MT_RECEIVE_NEW_CP_DATA_WITHOUT_CP_ACK MT_RECEIVE_NEW_CP_DATA_WITHOUT_CP_ACK__enum,MT_RECEIVE_NEW_CP_DATA_WITHOUT_CP_ACK_size

// SMS_RL_ERR_IGNORE_PEER_HDLR_FUNC
#define SMS_RL_ERR_IGNORE_PEER_HDLR_FUNC_size "d"
#define SMS_RL_ERR_IGNORE_PEER_HDLR_FUNC SMS_RL_ERR_IGNORE_PEER_HDLR_FUNC__enum,SMS_RL_ERR_IGNORE_PEER_HDLR_FUNC_size

// SMS_WRONG_PARA
#define SMS_WRONG_PARA_size NULL
#define SMS_WRONG_PARA SMS_WRONG_PARA__enum,SMS_WRONG_PARA_size

// SMS_ERROR_NO_SERVICE
#define SMS_ERROR_NO_SERVICE_size "‚c"
#define SMS_ERROR_NO_SERVICE SMS_ERROR_NO_SERVICE__enum,SMS_ERROR_NO_SERVICE_size

// SMS_EXCEED_CP_RETRY_CNT
#define SMS_EXCEED_CP_RETRY_CNT_size "d"
#define SMS_EXCEED_CP_RETRY_CNT SMS_EXCEED_CP_RETRY_CNT__enum,SMS_EXCEED_CP_RETRY_CNT_size

// SET_CM_SMI_ERROR
#define SET_CM_SMI_ERROR_size "cd"
#define SET_CM_SMI_ERROR SET_CM_SMI_ERROR__enum,SET_CM_SMI_ERROR_size

// FIND_CM_ID_ERROR
#define FIND_CM_ID_ERROR_size "cd"
#define FIND_CM_ID_ERROR FIND_CM_ID_ERROR__enum,FIND_CM_ID_ERROR_size

// FIND_CM_ID_BY_TI_ERROR
#define FIND_CM_ID_BY_TI_ERROR_size "d"
#define FIND_CM_ID_BY_TI_ERROR FIND_CM_ID_BY_TI_ERROR__enum,FIND_CM_ID_BY_TI_ERROR_size

// SMS_RL_ERR_HDLR_FUNC
#define SMS_RL_ERR_HDLR_FUNC_size "d"
#define SMS_RL_ERR_HDLR_FUNC SMS_RL_ERR_HDLR_FUNC__enum,SMS_RL_ERR_HDLR_FUNC_size

// SMS_TL_ERR_HDLR_FUNC
#define SMS_TL_ERR_HDLR_FUNC_size "d"
#define SMS_TL_ERR_HDLR_FUNC SMS_TL_ERR_HDLR_FUNC__enum,SMS_TL_ERR_HDLR_FUNC_size

// SMS_TL_ERR_IGNORE_PEER_HDLR_FUNC
#define SMS_TL_ERR_IGNORE_PEER_HDLR_FUNC_size "d"
#define SMS_TL_ERR_IGNORE_PEER_HDLR_FUNC SMS_TL_ERR_IGNORE_PEER_HDLR_FUNC__enum,SMS_TL_ERR_IGNORE_PEER_HDLR_FUNC_size

// SMS_CM_ERR_HDLR_FUNC
#define SMS_CM_ERR_HDLR_FUNC_size "d"
#define SMS_CM_ERR_HDLR_FUNC SMS_CM_ERR_HDLR_FUNC__enum,SMS_CM_ERR_HDLR_FUNC_size

// SMS_CM_ERR_IGNORE_PEER_HDLR_FUNC
#define SMS_CM_ERR_IGNORE_PEER_HDLR_FUNC_size "d"
#define SMS_CM_ERR_IGNORE_PEER_HDLR_FUNC SMS_CM_ERR_IGNORE_PEER_HDLR_FUNC__enum,SMS_CM_ERR_IGNORE_PEER_HDLR_FUNC_size

// MT_TI_ERROR
#define MT_TI_ERROR_size "c‚d"
#define MT_TI_ERROR MT_TI_ERROR__enum,MT_TI_ERROR_size

// WRONG_MSG_IN_MAIN_FUNC
#define WRONG_MSG_IN_MAIN_FUNC_size "d"
#define WRONG_MSG_IN_MAIN_FUNC WRONG_MSG_IN_MAIN_FUNC__enum,WRONG_MSG_IN_MAIN_FUNC_size

// WRONG_MSG_IN_TL_ENTRY_FUNC
#define WRONG_MSG_IN_TL_ENTRY_FUNC_size "d"
#define WRONG_MSG_IN_TL_ENTRY_FUNC WRONG_MSG_IN_TL_ENTRY_FUNC__enum,WRONG_MSG_IN_TL_ENTRY_FUNC_size

// WRONG_MSG_IN_CM_ENTRY_FUNC
#define WRONG_MSG_IN_CM_ENTRY_FUNC_size "d"
#define WRONG_MSG_IN_CM_ENTRY_FUNC WRONG_MSG_IN_CM_ENTRY_FUNC__enum,WRONG_MSG_IN_CM_ENTRY_FUNC_size

// WRONG_TI_IN_CP_HDR
#define WRONG_TI_IN_CP_HDR_size NULL
#define WRONG_TI_IN_CP_HDR WRONG_TI_IN_CP_HDR__enum,WRONG_TI_IN_CP_HDR_size

// WRONG_PD_IN_CP_HDR
#define WRONG_PD_IN_CP_HDR_size NULL
#define WRONG_PD_IN_CP_HDR WRONG_PD_IN_CP_HDR__enum,WRONG_PD_IN_CP_HDR_size

// DATA_TOO_SHORT_IN_CP_HDR
#define DATA_TOO_SHORT_IN_CP_HDR_size "d"
#define DATA_TOO_SHORT_IN_CP_HDR DATA_TOO_SHORT_IN_CP_HDR__enum,DATA_TOO_SHORT_IN_CP_HDR_size

// WRONG_ACK_LEN_IN_CP_HDR
#define WRONG_ACK_LEN_IN_CP_HDR_size "d"
#define WRONG_ACK_LEN_IN_CP_HDR WRONG_ACK_LEN_IN_CP_HDR__enum,WRONG_ACK_LEN_IN_CP_HDR_size

// WRONG_ERROR_LEN_IN_CP_HDR
#define WRONG_ERROR_LEN_IN_CP_HDR_size "d"
#define WRONG_ERROR_LEN_IN_CP_HDR WRONG_ERROR_LEN_IN_CP_HDR__enum,WRONG_ERROR_LEN_IN_CP_HDR_size

// WRONG_MTI_IN_CP_HDR
#define WRONG_MTI_IN_CP_HDR_size NULL
#define WRONG_MTI_IN_CP_HDR WRONG_MTI_IN_CP_HDR__enum,WRONG_MTI_IN_CP_HDR_size

// WRONG_MR_IN_RP_HDR
#define WRONG_MR_IN_RP_HDR_size "d"
#define WRONG_MR_IN_RP_HDR WRONG_MR_IN_RP_HDR__enum,WRONG_MR_IN_RP_HDR_size

// MSG_TOO_SHORT_IN_RP_HDR
#define MSG_TOO_SHORT_IN_RP_HDR_size "d"
#define MSG_TOO_SHORT_IN_RP_HDR MSG_TOO_SHORT_IN_RP_HDR__enum,MSG_TOO_SHORT_IN_RP_HDR_size

// WRONG_MTI_IN_RP_HDR
#define WRONG_MTI_IN_RP_HDR_size NULL
#define WRONG_MTI_IN_RP_HDR WRONG_MTI_IN_RP_HDR__enum,WRONG_MTI_IN_RP_HDR_size

// SMS_NO_FREE_TIMER
#define SMS_NO_FREE_TIMER_size NULL
#define SMS_NO_FREE_TIMER SMS_NO_FREE_TIMER__enum,SMS_NO_FREE_TIMER_size

// SMS_GET_TIMER_PTR_FAIL
#define SMS_GET_TIMER_PTR_FAIL_size "cd"
#define SMS_GET_TIMER_PTR_FAIL SMS_GET_TIMER_PTR_FAIL__enum,SMS_GET_TIMER_PTR_FAIL_size


#endif // SMS_TRC_GEN.H
