#ifndef _SYSTEM_TRC_GEN_H_
#define _SYSTEM_TRC_GEN_H_

// SST_INIT_ALICE_ENTER
#define SST_INIT_ALICE_ENTER_size NULL
#define SST_INIT_ALICE_ENTER SST_INIT_ALICE_ENTER__enum,SST_INIT_ALICE_ENTER_size

// SST_INIT_ALICE_EXIT
#define SST_INIT_ALICE_EXIT_size NULL
#define SST_INIT_ALICE_EXIT SST_INIT_ALICE_EXIT__enum,SST_INIT_ALICE_EXIT_size

// SST_INIT_L1CACHE_ENTER
#define SST_INIT_L1CACHE_ENTER_size NULL
#define SST_INIT_L1CACHE_ENTER SST_INIT_L1CACHE_ENTER__enum,SST_INIT_L1CACHE_ENTER_size

// SST_INIT_L1CACHE_EXIT
#define SST_INIT_L1CACHE_EXIT_size NULL
#define SST_INIT_L1CACHE_EXIT SST_INIT_L1CACHE_EXIT__enum,SST_INIT_L1CACHE_EXIT_size

// SST_INIT_MMU_ENTER
#define SST_INIT_MMU_ENTER_size NULL
#define SST_INIT_MMU_ENTER SST_INIT_MMU_ENTER__enum,SST_INIT_MMU_ENTER_size

// SST_INIT_MMU_EXIT
#define SST_INIT_MMU_EXIT_size NULL
#define SST_INIT_MMU_EXIT SST_INIT_MMU_EXIT__enum,SST_INIT_MMU_EXIT_size

// SST_INIT_L2CACHE_ENTER
#define SST_INIT_L2CACHE_ENTER_size NULL
#define SST_INIT_L2CACHE_ENTER SST_INIT_L2CACHE_ENTER__enum,SST_INIT_L2CACHE_ENTER_size

// SST_INIT_L2CACHE_EXIT
#define SST_INIT_L2CACHE_EXIT_size NULL
#define SST_INIT_L2CACHE_EXIT SST_INIT_L2CACHE_EXIT__enum,SST_INIT_L2CACHE_EXIT_size

// SST_INIT_APPINIT_START
#define SST_INIT_APPINIT_START_size NULL
#define SST_INIT_APPINIT_START SST_INIT_APPINIT_START__enum,SST_INIT_APPINIT_START_size

// SST_INIT_CLIB1_ENTER
#define SST_INIT_CLIB1_ENTER_size NULL
#define SST_INIT_CLIB1_ENTER SST_INIT_CLIB1_ENTER__enum,SST_INIT_CLIB1_ENTER_size

// SST_INIT_CLIB1_EXIT
#define SST_INIT_CLIB1_EXIT_size NULL
#define SST_INIT_CLIB1_EXIT SST_INIT_CLIB1_EXIT__enum,SST_INIT_CLIB1_EXIT_size

// SST_INIT_CCCIHS1_ENTER
#define SST_INIT_CCCIHS1_ENTER_size NULL
#define SST_INIT_CCCIHS1_ENTER SST_INIT_CCCIHS1_ENTER__enum,SST_INIT_CCCIHS1_ENTER_size

// SST_INIT_CCCIHS1_EXIT
#define SST_INIT_CCCIHS1_EXIT_size NULL
#define SST_INIT_CCCIHS1_EXIT SST_INIT_CCCIHS1_EXIT__enum,SST_INIT_CCCIHS1_EXIT_size

// SST_INIT_MDCIHS1_ENTER
#define SST_INIT_MDCIHS1_ENTER_size NULL
#define SST_INIT_MDCIHS1_ENTER SST_INIT_MDCIHS1_ENTER__enum,SST_INIT_MDCIHS1_ENTER_size

// SST_INIT_MDCIHS1_EXIT
#define SST_INIT_MDCIHS1_EXIT_size NULL
#define SST_INIT_MDCIHS1_EXIT SST_INIT_MDCIHS1_EXIT__enum,SST_INIT_MDCIHS1_EXIT_size

// SST_INIT_L1DINITMODE_ENTER
#define SST_INIT_L1DINITMODE_ENTER_size NULL
#define SST_INIT_L1DINITMODE_ENTER SST_INIT_L1DINITMODE_ENTER__enum,SST_INIT_L1DINITMODE_ENTER_size

// SST_INIT_L1DINITMODE_EXIT
#define SST_INIT_L1DINITMODE_EXIT_size "d"
#define SST_INIT_L1DINITMODE_EXIT SST_INIT_L1DINITMODE_EXIT__enum,SST_INIT_L1DINITMODE_EXIT_size

// SST_INIT_SYSTEMINIT_ENTER
#define SST_INIT_SYSTEMINIT_ENTER_size NULL
#define SST_INIT_SYSTEMINIT_ENTER SST_INIT_SYSTEMINIT_ENTER__enum,SST_INIT_SYSTEMINIT_ENTER_size

// SST_INIT_SYSTEMINIT_EXIT
#define SST_INIT_SYSTEMINIT_EXIT_size "d"
#define SST_INIT_SYSTEMINIT_EXIT SST_INIT_SYSTEMINIT_EXIT__enum,SST_INIT_SYSTEMINIT_EXIT_size

// SST_INIT_NVRAM_ENTER
#define SST_INIT_NVRAM_ENTER_size NULL
#define SST_INIT_NVRAM_ENTER SST_INIT_NVRAM_ENTER__enum,SST_INIT_NVRAM_ENTER_size

// SST_INIT_NVRAM_EXIT
#define SST_INIT_NVRAM_EXIT_size "d"
#define SST_INIT_NVRAM_EXIT SST_INIT_NVRAM_EXIT__enum,SST_INIT_NVRAM_EXIT_size

// SST_INIT_USC_ENTER
#define SST_INIT_USC_ENTER_size NULL
#define SST_INIT_USC_ENTER SST_INIT_USC_ENTER__enum,SST_INIT_USC_ENTER_size

// SST_INIT_USC_EXIT
#define SST_INIT_USC_EXIT_size "d"
#define SST_INIT_USC_EXIT SST_INIT_USC_EXIT__enum,SST_INIT_USC_EXIT_size

// SST_INIT_OSTD_ENTER
#define SST_INIT_OSTD_ENTER_size NULL
#define SST_INIT_OSTD_ENTER SST_INIT_OSTD_ENTER__enum,SST_INIT_OSTD_ENTER_size

// SST_INIT_OSTD_EXIT
#define SST_INIT_OSTD_EXIT_size "d"
#define SST_INIT_OSTD_EXIT SST_INIT_OSTD_EXIT__enum,SST_INIT_OSTD_EXIT_size

// SST_INIT_L1SM_ENTER
#define SST_INIT_L1SM_ENTER_size NULL
#define SST_INIT_L1SM_ENTER SST_INIT_L1SM_ENTER__enum,SST_INIT_L1SM_ENTER_size

// SST_INIT_L1SM_EXIT
#define SST_INIT_L1SM_EXIT_size "d"
#define SST_INIT_L1SM_EXIT SST_INIT_L1SM_EXIT__enum,SST_INIT_L1SM_EXIT_size

// SST_INIT_UL1SM_ENTER
#define SST_INIT_UL1SM_ENTER_size NULL
#define SST_INIT_UL1SM_ENTER SST_INIT_UL1SM_ENTER__enum,SST_INIT_UL1SM_ENTER_size

// SST_INIT_UL1SM_EXIT
#define SST_INIT_UL1SM_EXIT_size "d"
#define SST_INIT_UL1SM_EXIT SST_INIT_UL1SM_EXIT__enum,SST_INIT_UL1SM_EXIT_size

// SST_INIT_HWDIVIDER_ENTER
#define SST_INIT_HWDIVIDER_ENTER_size NULL
#define SST_INIT_HWDIVIDER_ENTER SST_INIT_HWDIVIDER_ENTER__enum,SST_INIT_HWDIVIDER_ENTER_size

// SST_INIT_HWDIVIDER_EXIT
#define SST_INIT_HWDIVIDER_EXIT_size "d"
#define SST_INIT_HWDIVIDER_EXIT SST_INIT_HWDIVIDER_EXIT__enum,SST_INIT_HWDIVIDER_EXIT_size

// SST_INIT_IDMALOAD_ENTER
#define SST_INIT_IDMALOAD_ENTER_size NULL
#define SST_INIT_IDMALOAD_ENTER SST_INIT_IDMALOAD_ENTER__enum,SST_INIT_IDMALOAD_ENTER_size

// SST_INIT_IDMALOAD_EXIT
#define SST_INIT_IDMALOAD_EXIT_size "d"
#define SST_INIT_IDMALOAD_EXIT SST_INIT_IDMALOAD_EXIT__enum,SST_INIT_IDMALOAD_EXIT_size

// SST_INIT_NFIRESET_ENTER
#define SST_INIT_NFIRESET_ENTER_size NULL
#define SST_INIT_NFIRESET_ENTER SST_INIT_NFIRESET_ENTER__enum,SST_INIT_NFIRESET_ENTER_size

// SST_INIT_NFIRESET_EXIT
#define SST_INIT_NFIRESET_EXIT_size "d"
#define SST_INIT_NFIRESET_EXIT SST_INIT_NFIRESET_EXIT__enum,SST_INIT_NFIRESET_EXIT_size

// SST_INIT_ZIMAGE_ENTER
#define SST_INIT_ZIMAGE_ENTER_size NULL
#define SST_INIT_ZIMAGE_ENTER SST_INIT_ZIMAGE_ENTER__enum,SST_INIT_ZIMAGE_ENTER_size

// SST_INIT_ZIMAGE_EXIT
#define SST_INIT_ZIMAGE_EXIT_size "d"
#define SST_INIT_ZIMAGE_EXIT SST_INIT_ZIMAGE_EXIT__enum,SST_INIT_ZIMAGE_EXIT_size

// SST_INIT_DRV1_START
#define SST_INIT_DRV1_START_size NULL
#define SST_INIT_DRV1_START SST_INIT_DRV1_START__enum,SST_INIT_DRV1_START_size

// SST_INIT_DRV1_DRVHISR_ENTER
#define SST_INIT_DRV1_DRVHISR_ENTER_size NULL
#define SST_INIT_DRV1_DRVHISR_ENTER SST_INIT_DRV1_DRVHISR_ENTER__enum,SST_INIT_DRV1_DRVHISR_ENTER_size

// SST_INIT_DRV1_DRVHISR_EXIT
#define SST_INIT_DRV1_DRVHISR_EXIT_size "d"
#define SST_INIT_DRV1_DRVHISR_EXIT SST_INIT_DRV1_DRVHISR_EXIT__enum,SST_INIT_DRV1_DRVHISR_EXIT_size

// SST_INIT_DRV1_MDCIHW_ENTER
#define SST_INIT_DRV1_MDCIHW_ENTER_size NULL
#define SST_INIT_DRV1_MDCIHW_ENTER SST_INIT_DRV1_MDCIHW_ENTER__enum,SST_INIT_DRV1_MDCIHW_ENTER_size

// SST_INIT_DRV1_MDCIHW_EXIT
#define SST_INIT_DRV1_MDCIHW_EXIT_size "d"
#define SST_INIT_DRV1_MDCIHW_EXIT SST_INIT_DRV1_MDCIHW_EXIT__enum,SST_INIT_DRV1_MDCIHW_EXIT_size

// SST_INIT_DRV1_CCCI_ENTER
#define SST_INIT_DRV1_CCCI_ENTER_size NULL
#define SST_INIT_DRV1_CCCI_ENTER SST_INIT_DRV1_CCCI_ENTER__enum,SST_INIT_DRV1_CCCI_ENTER_size

// SST_INIT_DRV1_CCCI_EXIT
#define SST_INIT_DRV1_CCCI_EXIT_size "d"
#define SST_INIT_DRV1_CCCI_EXIT SST_INIT_DRV1_CCCI_EXIT__enum,SST_INIT_DRV1_CCCI_EXIT_size

// SST_INIT_DRV1_EMIMPU_ENTER
#define SST_INIT_DRV1_EMIMPU_ENTER_size NULL
#define SST_INIT_DRV1_EMIMPU_ENTER SST_INIT_DRV1_EMIMPU_ENTER__enum,SST_INIT_DRV1_EMIMPU_ENTER_size

// SST_INIT_DRV1_EMIMPU_EXIT
#define SST_INIT_DRV1_EMIMPU_EXIT_size "d"
#define SST_INIT_DRV1_EMIMPU_EXIT SST_INIT_DRV1_EMIMPU_EXIT__enum,SST_INIT_DRV1_EMIMPU_EXIT_size

// SST_INIT_DRV1_LPWR_ENTER
#define SST_INIT_DRV1_LPWR_ENTER_size NULL
#define SST_INIT_DRV1_LPWR_ENTER SST_INIT_DRV1_LPWR_ENTER__enum,SST_INIT_DRV1_LPWR_ENTER_size

// SST_INIT_DRV1_LPWR_EXIT
#define SST_INIT_DRV1_LPWR_EXIT_size "d"
#define SST_INIT_DRV1_LPWR_EXIT SST_INIT_DRV1_LPWR_EXIT__enum,SST_INIT_DRV1_LPWR_EXIT_size

// SST_INIT_DRV1_DRVPDN_ENTER
#define SST_INIT_DRV1_DRVPDN_ENTER_size NULL
#define SST_INIT_DRV1_DRVPDN_ENTER SST_INIT_DRV1_DRVPDN_ENTER__enum,SST_INIT_DRV1_DRVPDN_ENTER_size

// SST_INIT_DRV1_DRVPDN_EXIT
#define SST_INIT_DRV1_DRVPDN_EXIT_size "d"
#define SST_INIT_DRV1_DRVPDN_EXIT SST_INIT_DRV1_DRVPDN_EXIT__enum,SST_INIT_DRV1_DRVPDN_EXIT_size

// SST_INIT_DRV1_PWM_ENTER
#define SST_INIT_DRV1_PWM_ENTER_size NULL
#define SST_INIT_DRV1_PWM_ENTER SST_INIT_DRV1_PWM_ENTER__enum,SST_INIT_DRV1_PWM_ENTER_size

// SST_INIT_DRV1_PWM_EXIT
#define SST_INIT_DRV1_PWM_EXIT_size "d"
#define SST_INIT_DRV1_PWM_EXIT SST_INIT_DRV1_PWM_EXIT__enum,SST_INIT_DRV1_PWM_EXIT_size

// SST_INIT_DRV1_CUSTOM_ENTER
#define SST_INIT_DRV1_CUSTOM_ENTER_size NULL
#define SST_INIT_DRV1_CUSTOM_ENTER SST_INIT_DRV1_CUSTOM_ENTER__enum,SST_INIT_DRV1_CUSTOM_ENTER_size

// SST_INIT_DRV1_CUSTOM_EXIT
#define SST_INIT_DRV1_CUSTOM_EXIT_size "d"
#define SST_INIT_DRV1_CUSTOM_EXIT SST_INIT_DRV1_CUSTOM_EXIT__enum,SST_INIT_DRV1_CUSTOM_EXIT_size

// SST_INIT_DRV1_GPT3_ENTER
#define SST_INIT_DRV1_GPT3_ENTER_size NULL
#define SST_INIT_DRV1_GPT3_ENTER SST_INIT_DRV1_GPT3_ENTER__enum,SST_INIT_DRV1_GPT3_ENTER_size

// SST_INIT_DRV1_GPT3_EXIT
#define SST_INIT_DRV1_GPT3_EXIT_size "d"
#define SST_INIT_DRV1_GPT3_EXIT SST_INIT_DRV1_GPT3_EXIT__enum,SST_INIT_DRV1_GPT3_EXIT_size

// SST_INIT_DRV1_VISUAL_ENTER
#define SST_INIT_DRV1_VISUAL_ENTER_size NULL
#define SST_INIT_DRV1_VISUAL_ENTER SST_INIT_DRV1_VISUAL_ENTER__enum,SST_INIT_DRV1_VISUAL_ENTER_size

// SST_INIT_DRV1_VISUAL_EXIT
#define SST_INIT_DRV1_VISUAL_EXIT_size "d"
#define SST_INIT_DRV1_VISUAL_EXIT SST_INIT_DRV1_VISUAL_EXIT__enum,SST_INIT_DRV1_VISUAL_EXIT_size

// SST_INIT_DRV1_GPTI_ENTER
#define SST_INIT_DRV1_GPTI_ENTER_size NULL
#define SST_INIT_DRV1_GPTI_ENTER SST_INIT_DRV1_GPTI_ENTER__enum,SST_INIT_DRV1_GPTI_ENTER_size

// SST_INIT_DRV1_GPTI_EXIT
#define SST_INIT_DRV1_GPTI_EXIT_size "d"
#define SST_INIT_DRV1_GPTI_EXIT SST_INIT_DRV1_GPTI_EXIT__enum,SST_INIT_DRV1_GPTI_EXIT_size

// SST_INIT_DRV1_WDT_ENTER
#define SST_INIT_DRV1_WDT_ENTER_size NULL
#define SST_INIT_DRV1_WDT_ENTER SST_INIT_DRV1_WDT_ENTER__enum,SST_INIT_DRV1_WDT_ENTER_size

// SST_INIT_DRV1_WDT_EXIT
#define SST_INIT_DRV1_WDT_EXIT_size "d"
#define SST_INIT_DRV1_WDT_EXIT SST_INIT_DRV1_WDT_EXIT__enum,SST_INIT_DRV1_WDT_EXIT_size

// SST_INIT_DRV1_DMA_ENTER
#define SST_INIT_DRV1_DMA_ENTER_size NULL
#define SST_INIT_DRV1_DMA_ENTER SST_INIT_DRV1_DMA_ENTER__enum,SST_INIT_DRV1_DMA_ENTER_size

// SST_INIT_DRV1_DMA_EXIT
#define SST_INIT_DRV1_DMA_EXIT_size "d"
#define SST_INIT_DRV1_DMA_EXIT SST_INIT_DRV1_DMA_EXIT__enum,SST_INIT_DRV1_DMA_EXIT_size

// SST_INIT_DRV1_XOSC_ENTER
#define SST_INIT_DRV1_XOSC_ENTER_size NULL
#define SST_INIT_DRV1_XOSC_ENTER SST_INIT_DRV1_XOSC_ENTER__enum,SST_INIT_DRV1_XOSC_ENTER_size

// SST_INIT_DRV1_XOSC_EXIT
#define SST_INIT_DRV1_XOSC_EXIT_size "d"
#define SST_INIT_DRV1_XOSC_EXIT SST_INIT_DRV1_XOSC_EXIT__enum,SST_INIT_DRV1_XOSC_EXIT_size

// SST_INIT_DRV1_ADC_ENTER
#define SST_INIT_DRV1_ADC_ENTER_size NULL
#define SST_INIT_DRV1_ADC_ENTER SST_INIT_DRV1_ADC_ENTER__enum,SST_INIT_DRV1_ADC_ENTER_size

// SST_INIT_DRV1_ADC_EXIT
#define SST_INIT_DRV1_ADC_EXIT_size "d"
#define SST_INIT_DRV1_ADC_EXIT SST_INIT_DRV1_ADC_EXIT__enum,SST_INIT_DRV1_ADC_EXIT_size

// SST_INIT_DRV1_CSFACDET_ENTER
#define SST_INIT_DRV1_CSFACDET_ENTER_size NULL
#define SST_INIT_DRV1_CSFACDET_ENTER SST_INIT_DRV1_CSFACDET_ENTER__enum,SST_INIT_DRV1_CSFACDET_ENTER_size

// SST_INIT_DRV1_CSFACDET_EXIT
#define SST_INIT_DRV1_CSFACDET_EXIT_size "d"
#define SST_INIT_DRV1_CSFACDET_EXIT SST_INIT_DRV1_CSFACDET_EXIT__enum,SST_INIT_DRV1_CSFACDET_EXIT_size

// SST_INIT_DRV1_ACCDET_ENTER
#define SST_INIT_DRV1_ACCDET_ENTER_size NULL
#define SST_INIT_DRV1_ACCDET_ENTER SST_INIT_DRV1_ACCDET_ENTER__enum,SST_INIT_DRV1_ACCDET_ENTER_size

// SST_INIT_DRV1_ACCDET_EXIT
#define SST_INIT_DRV1_ACCDET_EXIT_size "d"
#define SST_INIT_DRV1_ACCDET_EXIT SST_INIT_DRV1_ACCDET_EXIT__enum,SST_INIT_DRV1_ACCDET_EXIT_size

// SST_INIT_DRV1_LCD_ENTER
#define SST_INIT_DRV1_LCD_ENTER_size NULL
#define SST_INIT_DRV1_LCD_ENTER SST_INIT_DRV1_LCD_ENTER__enum,SST_INIT_DRV1_LCD_ENTER_size

// SST_INIT_DRV1_LCD_EXIT
#define SST_INIT_DRV1_LCD_EXIT_size "d"
#define SST_INIT_DRV1_LCD_EXIT SST_INIT_DRV1_LCD_EXIT__enum,SST_INIT_DRV1_LCD_EXIT_size

// SST_INIT_DRV1_RTCHW_ENTER
#define SST_INIT_DRV1_RTCHW_ENTER_size NULL
#define SST_INIT_DRV1_RTCHW_ENTER SST_INIT_DRV1_RTCHW_ENTER__enum,SST_INIT_DRV1_RTCHW_ENTER_size

// SST_INIT_DRV1_RTCHW_EXIT
#define SST_INIT_DRV1_RTCHW_EXIT_size "d"
#define SST_INIT_DRV1_RTCHW_EXIT SST_INIT_DRV1_RTCHW_EXIT__enum,SST_INIT_DRV1_RTCHW_EXIT_size

// SST_INIT_DRV1_PMIC_ENTER
#define SST_INIT_DRV1_PMIC_ENTER_size NULL
#define SST_INIT_DRV1_PMIC_ENTER SST_INIT_DRV1_PMIC_ENTER__enum,SST_INIT_DRV1_PMIC_ENTER_size

// SST_INIT_DRV1_PMIC_EXIT
#define SST_INIT_DRV1_PMIC_EXIT_size "d"
#define SST_INIT_DRV1_PMIC_EXIT SST_INIT_DRV1_PMIC_EXIT__enum,SST_INIT_DRV1_PMIC_EXIT_size

// SST_INIT_DRV1_PW_ENTER
#define SST_INIT_DRV1_PW_ENTER_size NULL
#define SST_INIT_DRV1_PW_ENTER SST_INIT_DRV1_PW_ENTER__enum,SST_INIT_DRV1_PW_ENTER_size

// SST_INIT_DRV1_PW_EXIT
#define SST_INIT_DRV1_PW_EXIT_size "d"
#define SST_INIT_DRV1_PW_EXIT SST_INIT_DRV1_PW_EXIT__enum,SST_INIT_DRV1_PW_EXIT_size

// SST_INIT_DRV1_DMAVFIFO_ENTER
#define SST_INIT_DRV1_DMAVFIFO_ENTER_size NULL
#define SST_INIT_DRV1_DMAVFIFO_ENTER SST_INIT_DRV1_DMAVFIFO_ENTER__enum,SST_INIT_DRV1_DMAVFIFO_ENTER_size

// SST_INIT_DRV1_DMAVFIFO_EXIT
#define SST_INIT_DRV1_DMAVFIFO_EXIT_size "d"
#define SST_INIT_DRV1_DMAVFIFO_EXIT SST_INIT_DRV1_DMAVFIFO_EXIT__enum,SST_INIT_DRV1_DMAVFIFO_EXIT_size

// SST_INIT_DRV1_UART1_ENTER
#define SST_INIT_DRV1_UART1_ENTER_size NULL
#define SST_INIT_DRV1_UART1_ENTER SST_INIT_DRV1_UART1_ENTER__enum,SST_INIT_DRV1_UART1_ENTER_size

// SST_INIT_DRV1_UART1_EXIT
#define SST_INIT_DRV1_UART1_EXIT_size "d"
#define SST_INIT_DRV1_UART1_EXIT SST_INIT_DRV1_UART1_EXIT__enum,SST_INIT_DRV1_UART1_EXIT_size

// SST_INIT_DRV1_UART2_ENTER
#define SST_INIT_DRV1_UART2_ENTER_size NULL
#define SST_INIT_DRV1_UART2_ENTER SST_INIT_DRV1_UART2_ENTER__enum,SST_INIT_DRV1_UART2_ENTER_size

// SST_INIT_DRV1_UART2_EXIT
#define SST_INIT_DRV1_UART2_EXIT_size "d"
#define SST_INIT_DRV1_UART2_EXIT SST_INIT_DRV1_UART2_EXIT__enum,SST_INIT_DRV1_UART2_EXIT_size

// SST_INIT_DRV1_UART3_ENTER
#define SST_INIT_DRV1_UART3_ENTER_size NULL
#define SST_INIT_DRV1_UART3_ENTER SST_INIT_DRV1_UART3_ENTER__enum,SST_INIT_DRV1_UART3_ENTER_size

// SST_INIT_DRV1_UART3_EXIT
#define SST_INIT_DRV1_UART3_EXIT_size "d"
#define SST_INIT_DRV1_UART3_EXIT SST_INIT_DRV1_UART3_EXIT__enum,SST_INIT_DRV1_UART3_EXIT_size

// SST_INIT_DRV1_OK
#define SST_INIT_DRV1_OK_size NULL
#define SST_INIT_DRV1_OK SST_INIT_DRV1_OK__enum,SST_INIT_DRV1_OK_size

// SST_INIT_PREFOTA_ENTER
#define SST_INIT_PREFOTA_ENTER_size NULL
#define SST_INIT_PREFOTA_ENTER SST_INIT_PREFOTA_ENTER__enum,SST_INIT_PREFOTA_ENTER_size

// SST_INIT_PREFOTA_EXIT
#define SST_INIT_PREFOTA_EXIT_size "d"
#define SST_INIT_PREFOTA_EXIT SST_INIT_PREFOTA_EXIT__enum,SST_INIT_PREFOTA_EXIT_size

// SST_INIT_THIRDROM_ENTER
#define SST_INIT_THIRDROM_ENTER_size NULL
#define SST_INIT_THIRDROM_ENTER SST_INIT_THIRDROM_ENTER__enum,SST_INIT_THIRDROM_ENTER_size

// SST_INIT_THIRDROM_EXIT
#define SST_INIT_THIRDROM_EXIT_size "d"
#define SST_INIT_THIRDROM_EXIT SST_INIT_THIRDROM_EXIT__enum,SST_INIT_THIRDROM_EXIT_size

// SST_INIT_LOADSECMAUI_ENTER
#define SST_INIT_LOADSECMAUI_ENTER_size NULL
#define SST_INIT_LOADSECMAUI_ENTER SST_INIT_LOADSECMAUI_ENTER__enum,SST_INIT_LOADSECMAUI_ENTER_size

// SST_INIT_LOADSECMAUI_EXIT
#define SST_INIT_LOADSECMAUI_EXIT_size "d"
#define SST_INIT_LOADSECMAUI_EXIT SST_INIT_LOADSECMAUI_EXIT__enum,SST_INIT_LOADSECMAUI_EXIT_size

// SST_INIT_DEMP_ENTER
#define SST_INIT_DEMP_ENTER_size NULL
#define SST_INIT_DEMP_ENTER SST_INIT_DEMP_ENTER__enum,SST_INIT_DEMP_ENTER_size

// SST_INIT_DEMP_EXIT
#define SST_INIT_DEMP_EXIT_size NULL
#define SST_INIT_DEMP_EXIT SST_INIT_DEMP_EXIT__enum,SST_INIT_DEMP_EXIT_size

// SST_PW_POWERINIT_FACTOR_PWRKEY
#define SST_PW_POWERINIT_FACTOR_PWRKEY_size "d"
#define SST_PW_POWERINIT_FACTOR_PWRKEY SST_PW_POWERINIT_FACTOR_PWRKEY__enum,SST_PW_POWERINIT_FACTOR_PWRKEY_size

// SST_PW_POWERINIT_FACTOR_CHRIN
#define SST_PW_POWERINIT_FACTOR_CHRIN_size "d"
#define SST_PW_POWERINIT_FACTOR_CHRIN SST_PW_POWERINIT_FACTOR_CHRIN__enum,SST_PW_POWERINIT_FACTOR_CHRIN_size

// SST_PW_POWERINIT_FACTOR_USBIN
#define SST_PW_POWERINIT_FACTOR_USBIN_size "d"
#define SST_PW_POWERINIT_FACTOR_USBIN SST_PW_POWERINIT_FACTOR_USBIN__enum,SST_PW_POWERINIT_FACTOR_USBIN_size

// SST_PW_POWERINIT_FACTOR_RTCALARM
#define SST_PW_POWERINIT_FACTOR_RTCALARM_size "d"
#define SST_PW_POWERINIT_FACTOR_RTCALARM SST_PW_POWERINIT_FACTOR_RTCALARM__enum,SST_PW_POWERINIT_FACTOR_RTCALARM_size

// SST_PW_POWERINIT_FACTOR_WDT
#define SST_PW_POWERINIT_FACTOR_WDT_size "d"
#define SST_PW_POWERINIT_FACTOR_WDT SST_PW_POWERINIT_FACTOR_WDT__enum,SST_PW_POWERINIT_FACTOR_WDT_size

// SST_PW_POWERINIT_FACTOR_NORMAL_RST
#define SST_PW_POWERINIT_FACTOR_NORMAL_RST_size "d"
#define SST_PW_POWERINIT_FACTOR_NORMAL_RST SST_PW_POWERINIT_FACTOR_NORMAL_RST__enum,SST_PW_POWERINIT_FACTOR_NORMAL_RST_size

// SST_PW_POWERINIT_FACTOR_CHR_PWRON_FG
#define SST_PW_POWERINIT_FACTOR_CHR_PWRON_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_CHR_PWRON_FG SST_PW_POWERINIT_FACTOR_CHR_PWRON_FG__enum,SST_PW_POWERINIT_FACTOR_CHR_PWRON_FG_size

// SST_PW_POWERINIT_FACTOR_USBMS_PWRON_FG
#define SST_PW_POWERINIT_FACTOR_USBMS_PWRON_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_USBMS_PWRON_FG SST_PW_POWERINIT_FACTOR_USBMS_PWRON_FG__enum,SST_PW_POWERINIT_FACTOR_USBMS_PWRON_FG_size

// SST_PW_POWERINIT_FACTOR_RTC_PWRON_FG
#define SST_PW_POWERINIT_FACTOR_RTC_PWRON_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_RTC_PWRON_FG SST_PW_POWERINIT_FACTOR_RTC_PWRON_FG__enum,SST_PW_POWERINIT_FACTOR_RTC_PWRON_FG_size

// SST_PW_POWERINIT_FACTOR_PRECHR_PWRON_FG
#define SST_PW_POWERINIT_FACTOR_PRECHR_PWRON_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_PRECHR_PWRON_FG SST_PW_POWERINIT_FACTOR_PRECHR_PWRON_FG__enum,SST_PW_POWERINIT_FACTOR_PRECHR_PWRON_FG_size

// SST_PW_POWERINIT_FACTOR_FC2IDLE_FG
#define SST_PW_POWERINIT_FACTOR_FC2IDLE_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_FC2IDLE_FG SST_PW_POWERINIT_FACTOR_FC2IDLE_FG__enum,SST_PW_POWERINIT_FACTOR_FC2IDLE_FG_size

// SST_PW_POWERINIT_FACTOR_FC2CHR_FG
#define SST_PW_POWERINIT_FACTOR_FC2CHR_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_FC2CHR_FG SST_PW_POWERINIT_FACTOR_FC2CHR_FG__enum,SST_PW_POWERINIT_FACTOR_FC2CHR_FG_size

// SST_PW_POWERINIT_FACTOR_FC2USB_FG
#define SST_PW_POWERINIT_FACTOR_FC2USB_FG_size "d"
#define SST_PW_POWERINIT_FACTOR_FC2USB_FG SST_PW_POWERINIT_FACTOR_FC2USB_FG__enum,SST_PW_POWERINIT_FACTOR_FC2USB_FG_size

// SST_PW_POWERINIT_PWRON_REASON
#define SST_PW_POWERINIT_PWRON_REASON_size "d"
#define SST_PW_POWERINIT_PWRON_REASON SST_PW_POWERINIT_PWRON_REASON__enum,SST_PW_POWERINIT_PWRON_REASON_size

// SST_PW_POWERINIT_ABNORMAL_PWRON
#define SST_PW_POWERINIT_ABNORMAL_PWRON_size NULL
#define SST_PW_POWERINIT_ABNORMAL_PWRON SST_PW_POWERINIT_ABNORMAL_PWRON__enum,SST_PW_POWERINIT_ABNORMAL_PWRON_size

// SST_PW_POWERINIT_META_PWRON
#define SST_PW_POWERINIT_META_PWRON_size NULL
#define SST_PW_POWERINIT_META_PWRON SST_PW_POWERINIT_META_PWRON__enum,SST_PW_POWERINIT_META_PWRON_size

// SST_INIT_DRV2_START
#define SST_INIT_DRV2_START_size NULL
#define SST_INIT_DRV2_START SST_INIT_DRV2_START__enum,SST_INIT_DRV2_START_size

// SST_INIT_DRV2_USB2UART_ENTER
#define SST_INIT_DRV2_USB2UART_ENTER_size NULL
#define SST_INIT_DRV2_USB2UART_ENTER SST_INIT_DRV2_USB2UART_ENTER__enum,SST_INIT_DRV2_USB2UART_ENTER_size

// SST_INIT_DRV2_USB2UART_EXIT
#define SST_INIT_DRV2_USB2UART_EXIT_size "d"
#define SST_INIT_DRV2_USB2UART_EXIT SST_INIT_DRV2_USB2UART_EXIT__enum,SST_INIT_DRV2_USB2UART_EXIT_size

// SST_INIT_DRV2_KBD_ENTER
#define SST_INIT_DRV2_KBD_ENTER_size NULL
#define SST_INIT_DRV2_KBD_ENTER SST_INIT_DRV2_KBD_ENTER__enum,SST_INIT_DRV2_KBD_ENTER_size

// SST_INIT_DRV2_KBD_EXIT
#define SST_INIT_DRV2_KBD_EXIT_size "d"
#define SST_INIT_DRV2_KBD_EXIT SST_INIT_DRV2_KBD_EXIT__enum,SST_INIT_DRV2_KBD_EXIT_size

// SST_INIT_DRV2_RTCSW_ENTER
#define SST_INIT_DRV2_RTCSW_ENTER_size NULL
#define SST_INIT_DRV2_RTCSW_ENTER SST_INIT_DRV2_RTCSW_ENTER__enum,SST_INIT_DRV2_RTCSW_ENTER_size

// SST_INIT_DRV2_RTCSW_EXIT
#define SST_INIT_DRV2_RTCSW_EXIT_size "d"
#define SST_INIT_DRV2_RTCSW_EXIT SST_INIT_DRV2_RTCSW_EXIT__enum,SST_INIT_DRV2_RTCSW_EXIT_size

// SST_INIT_DRV2_SIM_ENTER
#define SST_INIT_DRV2_SIM_ENTER_size NULL
#define SST_INIT_DRV2_SIM_ENTER SST_INIT_DRV2_SIM_ENTER__enum,SST_INIT_DRV2_SIM_ENTER_size

// SST_INIT_DRV2_SIM_EXIT
#define SST_INIT_DRV2_SIM_EXIT_size "d"
#define SST_INIT_DRV2_SIM_EXIT SST_INIT_DRV2_SIM_EXIT__enum,SST_INIT_DRV2_SIM_EXIT_size

// SST_INIT_DRV2_SIMMT6302_ENTER
#define SST_INIT_DRV2_SIMMT6302_ENTER_size NULL
#define SST_INIT_DRV2_SIMMT6302_ENTER SST_INIT_DRV2_SIMMT6302_ENTER__enum,SST_INIT_DRV2_SIMMT6302_ENTER_size

// SST_INIT_DRV2_SIMMT6302_EXIT
#define SST_INIT_DRV2_SIMMT6302_EXIT_size "d"
#define SST_INIT_DRV2_SIMMT6302_EXIT SST_INIT_DRV2_SIMMT6302_EXIT__enum,SST_INIT_DRV2_SIMMT6302_EXIT_size

// SST_INIT_DRV2_MSDC_ENTER
#define SST_INIT_DRV2_MSDC_ENTER_size NULL
#define SST_INIT_DRV2_MSDC_ENTER SST_INIT_DRV2_MSDC_ENTER__enum,SST_INIT_DRV2_MSDC_ENTER_size

// SST_INIT_DRV2_MSDC_EXIT
#define SST_INIT_DRV2_MSDC_EXIT_size "d"
#define SST_INIT_DRV2_MSDC_EXIT SST_INIT_DRV2_MSDC_EXIT__enum,SST_INIT_DRV2_MSDC_EXIT_size

// SST_INIT_DRV2_MSDC2_ENTER
#define SST_INIT_DRV2_MSDC2_ENTER_size NULL
#define SST_INIT_DRV2_MSDC2_ENTER SST_INIT_DRV2_MSDC2_ENTER__enum,SST_INIT_DRV2_MSDC2_ENTER_size

// SST_INIT_DRV2_MSDC2_EXIT
#define SST_INIT_DRV2_MSDC2_EXIT_size "d"
#define SST_INIT_DRV2_MSDC2_EXIT SST_INIT_DRV2_MSDC2_EXIT__enum,SST_INIT_DRV2_MSDC2_EXIT_size

// SST_INIT_DRV2_EINTSWDBNC_ENTER
#define SST_INIT_DRV2_EINTSWDBNC_ENTER_size NULL
#define SST_INIT_DRV2_EINTSWDBNC_ENTER SST_INIT_DRV2_EINTSWDBNC_ENTER__enum,SST_INIT_DRV2_EINTSWDBNC_ENTER_size

// SST_INIT_DRV2_EINTSWDBNC_EXIT
#define SST_INIT_DRV2_EINTSWDBNC_EXIT_size "d"
#define SST_INIT_DRV2_EINTSWDBNC_EXIT SST_INIT_DRV2_EINTSWDBNC_EXIT__enum,SST_INIT_DRV2_EINTSWDBNC_EXIT_size

// SST_INIT_DRV2_SWDBG_ENTER
#define SST_INIT_DRV2_SWDBG_ENTER_size NULL
#define SST_INIT_DRV2_SWDBG_ENTER SST_INIT_DRV2_SWDBG_ENTER__enum,SST_INIT_DRV2_SWDBG_ENTER_size

// SST_INIT_DRV2_SWDBG_EXIT
#define SST_INIT_DRV2_SWDBG_EXIT_size "d"
#define SST_INIT_DRV2_SWDBG_EXIT SST_INIT_DRV2_SWDBG_EXIT__enum,SST_INIT_DRV2_SWDBG_EXIT_size

// SST_INIT_DRV2_CHE_ENTER
#define SST_INIT_DRV2_CHE_ENTER_size NULL
#define SST_INIT_DRV2_CHE_ENTER SST_INIT_DRV2_CHE_ENTER__enum,SST_INIT_DRV2_CHE_ENTER_size

// SST_INIT_DRV2_CHE_EXIT
#define SST_INIT_DRV2_CHE_EXIT_size "d"
#define SST_INIT_DRV2_CHE_EXIT SST_INIT_DRV2_CHE_EXIT__enum,SST_INIT_DRV2_CHE_EXIT_size

// SST_INIT_DRV2_IMGSENS_ENTER
#define SST_INIT_DRV2_IMGSENS_ENTER_size NULL
#define SST_INIT_DRV2_IMGSENS_ENTER SST_INIT_DRV2_IMGSENS_ENTER__enum,SST_INIT_DRV2_IMGSENS_ENTER_size

// SST_INIT_DRV2_IMGSENS_EXIT
#define SST_INIT_DRV2_IMGSENS_EXIT_size "d"
#define SST_INIT_DRV2_IMGSENS_EXIT SST_INIT_DRV2_IMGSENS_EXIT__enum,SST_INIT_DRV2_IMGSENS_EXIT_size

// SST_INIT_DRV2_CIS_ENTER
#define SST_INIT_DRV2_CIS_ENTER_size NULL
#define SST_INIT_DRV2_CIS_ENTER SST_INIT_DRV2_CIS_ENTER__enum,SST_INIT_DRV2_CIS_ENTER_size

// SST_INIT_DRV2_CIS_EXIT
#define SST_INIT_DRV2_CIS_EXIT_size "d"
#define SST_INIT_DRV2_CIS_EXIT SST_INIT_DRV2_CIS_EXIT__enum,SST_INIT_DRV2_CIS_EXIT_size

// SST_INIT_DRV2_MSENS_ENTER
#define SST_INIT_DRV2_MSENS_ENTER_size NULL
#define SST_INIT_DRV2_MSENS_ENTER SST_INIT_DRV2_MSENS_ENTER__enum,SST_INIT_DRV2_MSENS_ENTER_size

// SST_INIT_DRV2_MSENS_EXIT
#define SST_INIT_DRV2_MSENS_EXIT_size "d"
#define SST_INIT_DRV2_MSENS_EXIT SST_INIT_DRV2_MSENS_EXIT__enum,SST_INIT_DRV2_MSENS_EXIT_size

// SST_INIT_DRV2_WN_ENTER
#define SST_INIT_DRV2_WN_ENTER_size NULL
#define SST_INIT_DRV2_WN_ENTER SST_INIT_DRV2_WN_ENTER__enum,SST_INIT_DRV2_WN_ENTER_size

// SST_INIT_DRV2_WN_EXIT
#define SST_INIT_DRV2_WN_EXIT_size "d"
#define SST_INIT_DRV2_WN_EXIT SST_INIT_DRV2_WN_EXIT__enum,SST_INIT_DRV2_WN_EXIT_size

// SST_INIT_DRV2_I2C_ENTER
#define SST_INIT_DRV2_I2C_ENTER_size NULL
#define SST_INIT_DRV2_I2C_ENTER SST_INIT_DRV2_I2C_ENTER__enum,SST_INIT_DRV2_I2C_ENTER_size

// SST_INIT_DRV2_I2C_EXIT
#define SST_INIT_DRV2_I2C_EXIT_size "d"
#define SST_INIT_DRV2_I2C_EXIT SST_INIT_DRV2_I2C_EXIT__enum,SST_INIT_DRV2_I2C_EXIT_size

// SST_INIT_DRV2_ICC_ENTER
#define SST_INIT_DRV2_ICC_ENTER_size NULL
#define SST_INIT_DRV2_ICC_ENTER SST_INIT_DRV2_ICC_ENTER__enum,SST_INIT_DRV2_ICC_ENTER_size

// SST_INIT_DRV2_ICC_EXIT
#define SST_INIT_DRV2_ICC_EXIT_size "d"
#define SST_INIT_DRV2_ICC_EXIT SST_INIT_DRV2_ICC_EXIT__enum,SST_INIT_DRV2_ICC_EXIT_size

// SST_INIT_DRV2_BTIF_ENTER
#define SST_INIT_DRV2_BTIF_ENTER_size NULL
#define SST_INIT_DRV2_BTIF_ENTER SST_INIT_DRV2_BTIF_ENTER__enum,SST_INIT_DRV2_BTIF_ENTER_size

// SST_INIT_DRV2_BTIF_EXIT
#define SST_INIT_DRV2_BTIF_EXIT_size "d"
#define SST_INIT_DRV2_BTIF_EXIT SST_INIT_DRV2_BTIF_EXIT__enum,SST_INIT_DRV2_BTIF_EXIT_size

// SST_INIT_DRV2_PFC_ENTER
#define SST_INIT_DRV2_PFC_ENTER_size NULL
#define SST_INIT_DRV2_PFC_ENTER SST_INIT_DRV2_PFC_ENTER__enum,SST_INIT_DRV2_PFC_ENTER_size

// SST_INIT_DRV2_PFC_EXIT
#define SST_INIT_DRV2_PFC_EXIT_size "d"
#define SST_INIT_DRV2_PFC_EXIT SST_INIT_DRV2_PFC_EXIT__enum,SST_INIT_DRV2_PFC_EXIT_size

// SST_INIT_DRV2_OK
#define SST_INIT_DRV2_OK_size NULL
#define SST_INIT_DRV2_OK SST_INIT_DRV2_OK__enum,SST_INIT_DRV2_OK_size

// SST_INIT_RESINIT_ENTER
#define SST_INIT_RESINIT_ENTER_size NULL
#define SST_INIT_RESINIT_ENTER SST_INIT_RESINIT_ENTER__enum,SST_INIT_RESINIT_ENTER_size

// SST_INIT_RESINIT_EXIT
#define SST_INIT_RESINIT_EXIT_size "d"
#define SST_INIT_RESINIT_EXIT SST_INIT_RESINIT_EXIT__enum,SST_INIT_RESINIT_EXIT_size

// SST_INIT_CHECKMSGID_ENTER
#define SST_INIT_CHECKMSGID_ENTER_size NULL
#define SST_INIT_CHECKMSGID_ENTER SST_INIT_CHECKMSGID_ENTER__enum,SST_INIT_CHECKMSGID_ENTER_size

// SST_INIT_CHECKMSGID_EXIT
#define SST_INIT_CHECKMSGID_EXIT_size "d"
#define SST_INIT_CHECKMSGID_EXIT SST_INIT_CHECKMSGID_EXIT__enum,SST_INIT_CHECKMSGID_EXIT_size

// SST_INIT_CLIB2_ENTER
#define SST_INIT_CLIB2_ENTER_size NULL
#define SST_INIT_CLIB2_ENTER SST_INIT_CLIB2_ENTER__enum,SST_INIT_CLIB2_ENTER_size

// SST_INIT_CLIB2_EXIT
#define SST_INIT_CLIB2_EXIT_size "d"
#define SST_INIT_CLIB2_EXIT SST_INIT_CLIB2_EXIT__enum,SST_INIT_CLIB2_EXIT_size

// SST_INIT_DMDSP1_ENTER
#define SST_INIT_DMDSP1_ENTER_size NULL
#define SST_INIT_DMDSP1_ENTER SST_INIT_DMDSP1_ENTER__enum,SST_INIT_DMDSP1_ENTER_size

// SST_INIT_DMDSP1_EXIT
#define SST_INIT_DMDSP1_EXIT_size "d"
#define SST_INIT_DMDSP1_EXIT SST_INIT_DMDSP1_EXIT__enum,SST_INIT_DMDSP1_EXIT_size

// SST_INIT_CCCIHS2_ENTER
#define SST_INIT_CCCIHS2_ENTER_size NULL
#define SST_INIT_CCCIHS2_ENTER SST_INIT_CCCIHS2_ENTER__enum,SST_INIT_CCCIHS2_ENTER_size

// SST_INIT_CCCIHS2_EXIT
#define SST_INIT_CCCIHS2_EXIT_size "d"
#define SST_INIT_CCCIHS2_EXIT SST_INIT_CCCIHS2_EXIT__enum,SST_INIT_CCCIHS2_EXIT_size

// SST_INIT_MDCIHS2_ENTER
#define SST_INIT_MDCIHS2_ENTER_size NULL
#define SST_INIT_MDCIHS2_ENTER SST_INIT_MDCIHS2_ENTER__enum,SST_INIT_MDCIHS2_ENTER_size

// SST_INIT_MDCIHS2_EXIT
#define SST_INIT_MDCIHS2_EXIT_size "d"
#define SST_INIT_MDCIHS2_EXIT SST_INIT_MDCIHS2_EXIT__enum,SST_INIT_MDCIHS2_EXIT_size

// SST_INIT_DMDSP2_ENTER
#define SST_INIT_DMDSP2_ENTER_size NULL
#define SST_INIT_DMDSP2_ENTER SST_INIT_DMDSP2_ENTER__enum,SST_INIT_DMDSP2_ENTER_size

// SST_INIT_DMDSP2_EXIT
#define SST_INIT_DMDSP2_EXIT_size "d"
#define SST_INIT_DMDSP2_EXIT SST_INIT_DMDSP2_EXIT__enum,SST_INIT_DMDSP2_EXIT_size

// SST_INIT_RTFINIT_ENTER
#define SST_INIT_RTFINIT_ENTER_size NULL
#define SST_INIT_RTFINIT_ENTER SST_INIT_RTFINIT_ENTER__enum,SST_INIT_RTFINIT_ENTER_size

// SST_INIT_RTFINIT_EXIT
#define SST_INIT_RTFINIT_EXIT_size "d"
#define SST_INIT_RTFINIT_EXIT SST_INIT_RTFINIT_EXIT__enum,SST_INIT_RTFINIT_EXIT_size

// SST_INIT_RTFSANITY_ENTER
#define SST_INIT_RTFSANITY_ENTER_size NULL
#define SST_INIT_RTFSANITY_ENTER SST_INIT_RTFSANITY_ENTER__enum,SST_INIT_RTFSANITY_ENTER_size

// SST_INIT_RTFSANITY_EXIT
#define SST_INIT_RTFSANITY_EXIT_size "d"
#define SST_INIT_RTFSANITY_EXIT SST_INIT_RTFSANITY_EXIT__enum,SST_INIT_RTFSANITY_EXIT_size

// SST_INIT_TASKINIT
#define SST_INIT_TASKINIT_size NULL
#define SST_INIT_TASKINIT SST_INIT_TASKINIT__enum,SST_INIT_TASKINIT_size

// SST_INIT_TASKINIT_INDX_ENTER
#define SST_INIT_TASKINIT_INDX_ENTER_size "c"
#define SST_INIT_TASKINIT_INDX_ENTER SST_INIT_TASKINIT_INDX_ENTER__enum,SST_INIT_TASKINIT_INDX_ENTER_size

// SST_INIT_TASKINIT_INDX_EXIT
#define SST_INIT_TASKINIT_INDX_EXIT_size "cd"
#define SST_INIT_TASKINIT_INDX_EXIT SST_INIT_TASKINIT_INDX_EXIT__enum,SST_INIT_TASKINIT_INDX_EXIT_size

// SST_INIT_APPINIT_OK
#define SST_INIT_APPINIT_OK_size NULL
#define SST_INIT_APPINIT_OK SST_INIT_APPINIT_OK__enum,SST_INIT_APPINIT_OK_size

// DEMP_PAGE_FAULT_ENTER
#define DEMP_PAGE_FAULT_ENTER_size "c…d"
#define DEMP_PAGE_FAULT_ENTER DEMP_PAGE_FAULT_ENTER__enum,DEMP_PAGE_FAULT_ENTER_size

// DEMP_ERR_CODE
#define DEMP_ERR_CODE_size "d"
#define DEMP_ERR_CODE DEMP_ERR_CODE__enum,DEMP_ERR_CODE_size

// DEMP_PAGE_ALLOC_ENTER
#define DEMP_PAGE_ALLOC_ENTER_size NULL
#define DEMP_PAGE_ALLOC_ENTER DEMP_PAGE_ALLOC_ENTER__enum,DEMP_PAGE_ALLOC_ENTER_size

// DEMP_PAGE_ALLOC_EXIT
#define DEMP_PAGE_ALLOC_EXIT_size "ƒd"
#define DEMP_PAGE_ALLOC_EXIT DEMP_PAGE_ALLOC_EXIT__enum,DEMP_PAGE_ALLOC_EXIT_size

// DEMP_PAGE_SWAPOUT_ENTER
#define DEMP_PAGE_SWAPOUT_ENTER_size "‚d"
#define DEMP_PAGE_SWAPOUT_ENTER DEMP_PAGE_SWAPOUT_ENTER__enum,DEMP_PAGE_SWAPOUT_ENTER_size

// DEMP_PAGE_SWAPOUT_EXIT
#define DEMP_PAGE_SWAPOUT_EXIT_size NULL
#define DEMP_PAGE_SWAPOUT_EXIT DEMP_PAGE_SWAPOUT_EXIT__enum,DEMP_PAGE_SWAPOUT_EXIT_size

// DEMP_PAGE_SWAPIN_ENTER
#define DEMP_PAGE_SWAPIN_ENTER_size "ƒd"
#define DEMP_PAGE_SWAPIN_ENTER DEMP_PAGE_SWAPIN_ENTER__enum,DEMP_PAGE_SWAPIN_ENTER_size

// DEMP_PAGE_LOCK_TAKEN
#define DEMP_PAGE_LOCK_TAKEN_size "cd"
#define DEMP_PAGE_LOCK_TAKEN DEMP_PAGE_LOCK_TAKEN__enum,DEMP_PAGE_LOCK_TAKEN_size

// DEMP_PAGE_LOCK_AVAILABLE
#define DEMP_PAGE_LOCK_AVAILABLE_size NULL
#define DEMP_PAGE_LOCK_AVAILABLE DEMP_PAGE_LOCK_AVAILABLE__enum,DEMP_PAGE_LOCK_AVAILABLE_size

// DEMP_PAGE_GET_LOCK
#define DEMP_PAGE_GET_LOCK_size "cd"
#define DEMP_PAGE_GET_LOCK DEMP_PAGE_GET_LOCK__enum,DEMP_PAGE_GET_LOCK_size

// DEMP_PAGE_FREE_LOCK
#define DEMP_PAGE_FREE_LOCK_size "cd"
#define DEMP_PAGE_FREE_LOCK DEMP_PAGE_FREE_LOCK__enum,DEMP_PAGE_FREE_LOCK_size

// DEMP_PAGE_SWAPIN_EXIT
#define DEMP_PAGE_SWAPIN_EXIT_size "ƒd"
#define DEMP_PAGE_SWAPIN_EXIT DEMP_PAGE_SWAPIN_EXIT__enum,DEMP_PAGE_SWAPIN_EXIT_size

// DEMP_PTABLE_UPDATE_ENTER
#define DEMP_PTABLE_UPDATE_ENTER_size "‚d"
#define DEMP_PTABLE_UPDATE_ENTER DEMP_PTABLE_UPDATE_ENTER__enum,DEMP_PTABLE_UPDATE_ENTER_size

// DEMP_PTABLE_UPDATE_EXIT
#define DEMP_PTABLE_UPDATE_EXIT_size "‚d"
#define DEMP_PTABLE_UPDATE_EXIT DEMP_PTABLE_UPDATE_EXIT__enum,DEMP_PTABLE_UPDATE_EXIT_size

// DEMP_PAGE_FAULT_EXIT
#define DEMP_PAGE_FAULT_EXIT_size "c„d"
#define DEMP_PAGE_FAULT_EXIT DEMP_PAGE_FAULT_EXIT__enum,DEMP_PAGE_FAULT_EXIT_size

// DEMP_LOCK_ENTER
#define DEMP_LOCK_ENTER_size "ƒd"
#define DEMP_LOCK_ENTER DEMP_LOCK_ENTER__enum,DEMP_LOCK_ENTER_size

// DEMP_LOCK
#define DEMP_LOCK_size "d"
#define DEMP_LOCK DEMP_LOCK__enum,DEMP_LOCK_size

// DEMP_LOCK_EXIT
#define DEMP_LOCK_EXIT_size "ƒd"
#define DEMP_LOCK_EXIT DEMP_LOCK_EXIT__enum,DEMP_LOCK_EXIT_size

// DEMP_UNLOCK_ENTER
#define DEMP_UNLOCK_ENTER_size "ƒd"
#define DEMP_UNLOCK_ENTER DEMP_UNLOCK_ENTER__enum,DEMP_UNLOCK_ENTER_size

// DEMP_UNLOCK
#define DEMP_UNLOCK_size "d"
#define DEMP_UNLOCK DEMP_UNLOCK__enum,DEMP_UNLOCK_size

// DEMP_UNLOCK_EXIT
#define DEMP_UNLOCK_EXIT_size "ƒd"
#define DEMP_UNLOCK_EXIT DEMP_UNLOCK_EXIT__enum,DEMP_UNLOCK_EXIT_size

// SYSMEM_ALLOC_FORMAT
#define SYSMEM_ALLOC_FORMAT_size "‚d"
#define SYSMEM_ALLOC_FORMAT SYSMEM_ALLOC_FORMAT__enum,SYSMEM_ALLOC_FORMAT_size

// ADM_CREATE2_FORMAT
#define ADM_CREATE2_FORMAT_size "ˆd"
#define ADM_CREATE2_FORMAT ADM_CREATE2_FORMAT__enum,ADM_CREATE2_FORMAT_size

// ADM_DELETE_FORMAT
#define ADM_DELETE_FORMAT_size "‚d"
#define ADM_DELETE_FORMAT ADM_DELETE_FORMAT__enum,ADM_DELETE_FORMAT_size

// ADM_ALLOC_FORMAT
#define ADM_ALLOC_FORMAT_size "„ds‚d"
#define ADM_ALLOC_FORMAT ADM_ALLOC_FORMAT__enum,ADM_ALLOC_FORMAT_size

// ADM_FREE_FORMAT
#define ADM_FREE_FORMAT_size "‚d"
#define ADM_FREE_FORMAT ADM_FREE_FORMAT__enum,ADM_FREE_FORMAT_size

// FLMM_ALLOC_FORMAT
#define FLMM_ALLOC_FORMAT_size "„d"
#define FLMM_ALLOC_FORMAT FLMM_ALLOC_FORMAT__enum,FLMM_ALLOC_FORMAT_size

// FLMM_FREE_FORMAT
#define FLMM_FREE_FORMAT_size "ƒd"
#define FLMM_FREE_FORMAT FLMM_FREE_FORMAT__enum,FLMM_FREE_FORMAT_size

// SLMM_DROP_FORMAT
#define SLMM_DROP_FORMAT_size "ƒd"
#define SLMM_DROP_FORMAT SLMM_DROP_FORMAT__enum,SLMM_DROP_FORMAT_size

// PROFILE_CPUUSAGE_FORMAT
#define PROFILE_CPUUSAGE_FORMAT_size "d"
#define PROFILE_CPUUSAGE_FORMAT PROFILE_CPUUSAGE_FORMAT__enum,PROFILE_CPUUSAGE_FORMAT_size

// TP_OVER_200QB
#define TP_OVER_200QB_size "„d"
#define TP_OVER_200QB TP_OVER_200QB__enum,TP_OVER_200QB_size

// EVSHED_CREATE
#define EVSHED_CREATE_size "†dˆc"
#define EVSHED_CREATE EVSHED_CREATE__enum,EVSHED_CREATE_size

// EVSHED_SET_EVENT
#define EVSHED_SET_EVENT_size "†d"
#define EVSHED_SET_EVENT EVSHED_SET_EVENT__enum,EVSHED_SET_EVENT_size

// EVSHED_SET_INDEX
#define EVSHED_SET_INDEX_size "„d"
#define EVSHED_SET_INDEX EVSHED_SET_INDEX__enum,EVSHED_SET_INDEX_size

// EVSHED_GET_INDEX
#define EVSHED_GET_INDEX_size "ƒd"
#define EVSHED_GET_INDEX EVSHED_GET_INDEX__enum,EVSHED_GET_INDEX_size

// EVSHED_CANCEL_EVENT
#define EVSHED_CANCEL_EVENT_size "„d"
#define EVSHED_CANCEL_EVENT EVSHED_CANCEL_EVENT__enum,EVSHED_CANCEL_EVENT_size

// EVSHED_SUSPEND
#define EVSHED_SUSPEND_size "ƒd"
#define EVSHED_SUSPEND EVSHED_SUSPEND__enum,EVSHED_SUSPEND_size

// EVSHED_RESUME
#define EVSHED_RESUME_size "ƒd"
#define EVSHED_RESUME EVSHED_RESUME__enum,EVSHED_RESUME_size

// EVSHED_HANDLER
#define EVSHED_HANDLER_size "…d"
#define EVSHED_HANDLER EVSHED_HANDLER__enum,EVSHED_HANDLER_size

// EVSHED_DEL
#define EVSHED_DEL_size "ƒd"
#define EVSHED_DEL EVSHED_DEL__enum,EVSHED_DEL_size

// EVSHED_SET_ALIGN
#define EVSHED_SET_ALIGN_size "ƒd"
#define EVSHED_SET_ALIGN EVSHED_SET_ALIGN__enum,EVSHED_SET_ALIGN_size

// EVSHED_UNSET_ALIGN
#define EVSHED_UNSET_ALIGN_size "‚d"
#define EVSHED_UNSET_ALIGN EVSHED_UNSET_ALIGN__enum,EVSHED_UNSET_ALIGN_size

// DCM_COUNTER
#define DCM_COUNTER_size "d"
#define DCM_COUNTER DCM_COUNTER__enum,DCM_COUNTER_size

// DCM_ACTIVE_CYCLES
#define DCM_ACTIVE_CYCLES_size "d"
#define DCM_ACTIVE_CYCLES DCM_ACTIVE_CYCLES__enum,DCM_ACTIVE_CYCLES_size


#endif // SYSTEM_TRC_GEN.H
