#ifndef _TDT_TRC_GEN_H_
#define _TDT_TRC_GEN_H_

// IN_tdt_activate_req_hdlr
#define IN_tdt_activate_req_hdlr_size NULL
#define IN_tdt_activate_req_hdlr IN_tdt_activate_req_hdlr__enum,IN_tdt_activate_req_hdlr_size

// OUT_tdt_activate_req_hdlr
#define OUT_tdt_activate_req_hdlr_size "d"
#define OUT_tdt_activate_req_hdlr OUT_tdt_activate_req_hdlr__enum,OUT_tdt_activate_req_hdlr_size

// IN_tdt_deactivate_req_hdlr
#define IN_tdt_deactivate_req_hdlr_size NULL
#define IN_tdt_deactivate_req_hdlr IN_tdt_deactivate_req_hdlr__enum,IN_tdt_deactivate_req_hdlr_size

// OUT_tdt_deactivate_req_hdlr
#define OUT_tdt_deactivate_req_hdlr_size NULL
#define OUT_tdt_deactivate_req_hdlr OUT_tdt_deactivate_req_hdlr__enum,OUT_tdt_deactivate_req_hdlr_size

// IN_tdt_esc_off_req_hdlr
#define IN_tdt_esc_off_req_hdlr_size NULL
#define IN_tdt_esc_off_req_hdlr IN_tdt_esc_off_req_hdlr__enum,IN_tdt_esc_off_req_hdlr_size

// OUT_tdt_esc_off_req_hdlr
#define OUT_tdt_esc_off_req_hdlr_size NULL
#define OUT_tdt_esc_off_req_hdlr OUT_tdt_esc_off_req_hdlr__enum,OUT_tdt_esc_off_req_hdlr_size

// IN_tdt_esc_on_req_hdlr
#define IN_tdt_esc_on_req_hdlr_size NULL
#define IN_tdt_esc_on_req_hdlr IN_tdt_esc_on_req_hdlr__enum,IN_tdt_esc_on_req_hdlr_size

// OUT_tdt_esc_on_req_hdlr
#define OUT_tdt_esc_on_req_hdlr_size NULL
#define OUT_tdt_esc_on_req_hdlr OUT_tdt_esc_on_req_hdlr__enum,OUT_tdt_esc_on_req_hdlr_size

// IN_tdt_uart_setowner_req_hdlr
#define IN_tdt_uart_setowner_req_hdlr_size NULL
#define IN_tdt_uart_setowner_req_hdlr IN_tdt_uart_setowner_req_hdlr__enum,IN_tdt_uart_setowner_req_hdlr_size

// OUT_tdt_uart_setowner_req_hdlr
#define OUT_tdt_uart_setowner_req_hdlr_size NULL
#define OUT_tdt_uart_setowner_req_hdlr OUT_tdt_uart_setowner_req_hdlr__enum,OUT_tdt_uart_setowner_req_hdlr_size

// IN_tdt_ready_to_write_hdlr
#define IN_tdt_ready_to_write_hdlr_size NULL
#define IN_tdt_ready_to_write_hdlr IN_tdt_ready_to_write_hdlr__enum,IN_tdt_ready_to_write_hdlr_size

// OUT_tdt_ready_to_write_hdlr
#define OUT_tdt_ready_to_write_hdlr_size NULL
#define OUT_tdt_ready_to_write_hdlr OUT_tdt_ready_to_write_hdlr__enum,OUT_tdt_ready_to_write_hdlr_size

// IN_tdt_ready_to_read_hdlr
#define IN_tdt_ready_to_read_hdlr_size NULL
#define IN_tdt_ready_to_read_hdlr IN_tdt_ready_to_read_hdlr__enum,IN_tdt_ready_to_read_hdlr_size

// OUT_tdt_ready_to_read_hdlr
#define OUT_tdt_ready_to_read_hdlr_size NULL
#define OUT_tdt_ready_to_read_hdlr OUT_tdt_ready_to_read_hdlr__enum,OUT_tdt_ready_to_read_hdlr_size

// IN_tdt_downlink_tick_hdlr
#define IN_tdt_downlink_tick_hdlr_size NULL
#define IN_tdt_downlink_tick_hdlr IN_tdt_downlink_tick_hdlr__enum,IN_tdt_downlink_tick_hdlr_size

// OUT_tdt_downlink_tick_hdlr
#define OUT_tdt_downlink_tick_hdlr_size NULL
#define OUT_tdt_downlink_tick_hdlr OUT_tdt_downlink_tick_hdlr__enum,OUT_tdt_downlink_tick_hdlr_size

// IN_tdt_uplink_tick_hdlr
#define IN_tdt_uplink_tick_hdlr_size NULL
#define IN_tdt_uplink_tick_hdlr IN_tdt_uplink_tick_hdlr__enum,IN_tdt_uplink_tick_hdlr_size

// OUT_tdt_uplink_tick_hdlr
#define OUT_tdt_uplink_tick_hdlr_size NULL
#define OUT_tdt_uplink_tick_hdlr OUT_tdt_uplink_tick_hdlr__enum,OUT_tdt_uplink_tick_hdlr_size

// IN_tdt_activate_timer_expiry_hdlr
#define IN_tdt_activate_timer_expiry_hdlr_size NULL
#define IN_tdt_activate_timer_expiry_hdlr IN_tdt_activate_timer_expiry_hdlr__enum,IN_tdt_activate_timer_expiry_hdlr_size

// OUT_tdt_activate_timer_expiry_hdlr
#define OUT_tdt_activate_timer_expiry_hdlr_size NULL
#define OUT_tdt_activate_timer_expiry_hdlr OUT_tdt_activate_timer_expiry_hdlr__enum,OUT_tdt_activate_timer_expiry_hdlr_size

// IN_tdt_exit_loopmode_hdlr
#define IN_tdt_exit_loopmode_hdlr_size NULL
#define IN_tdt_exit_loopmode_hdlr IN_tdt_exit_loopmode_hdlr__enum,IN_tdt_exit_loopmode_hdlr_size

// OUT_tdt_exit_loopmode_hdlr
#define OUT_tdt_exit_loopmode_hdlr_size NULL
#define OUT_tdt_exit_loopmode_hdlr OUT_tdt_exit_loopmode_hdlr__enum,OUT_tdt_exit_loopmode_hdlr_size

// IN_tdt_ppp_data_req_hdlr
#define IN_tdt_ppp_data_req_hdlr_size NULL
#define IN_tdt_ppp_data_req_hdlr IN_tdt_ppp_data_req_hdlr__enum,IN_tdt_ppp_data_req_hdlr_size

// OUT_tdt_ppp_data_req_hdlr
#define OUT_tdt_ppp_data_req_hdlr_size NULL
#define OUT_tdt_ppp_data_req_hdlr OUT_tdt_ppp_data_req_hdlr__enum,OUT_tdt_ppp_data_req_hdlr_size

// TDT_STATE
#define TDT_STATE_size "d"
#define TDT_STATE TDT_STATE__enum,TDT_STATE_size

// UART_FULL
#define UART_FULL_size NULL
#define UART_FULL UART_FULL__enum,UART_FULL_size

// TDT_ADAPTION_DROP_DATA
#define TDT_ADAPTION_DROP_DATA_size NULL
#define TDT_ADAPTION_DROP_DATA TDT_ADAPTION_DROP_DATA__enum,TDT_ADAPTION_DROP_DATA_size

// RA_tick_in_idle_state
#define RA_tick_in_idle_state_size NULL
#define RA_tick_in_idle_state RA_tick_in_idle_state__enum,RA_tick_in_idle_state_size

// DOWNLINK_L1_TICK_INFO
#define DOWNLINK_L1_TICK_INFO_size "‚d"
#define DOWNLINK_L1_TICK_INFO DOWNLINK_L1_TICK_INFO__enum,DOWNLINK_L1_TICK_INFO_size

// UPLINK_L1_TICK_INFO
#define UPLINK_L1_TICK_INFO_size "‚d"
#define UPLINK_L1_TICK_INFO UPLINK_L1_TICK_INFO__enum,UPLINK_L1_TICK_INFO_size


#endif // TDT_TRC_GEN.H
