#ifndef _TLS_TRC_GEN_H_
#define _TLS_TRC_GEN_H_

// FUNC_TLS_NEW_CTX
#define FUNC_TLS_NEW_CTX_size "dcd"
#define FUNC_TLS_NEW_CTX FUNC_TLS_NEW_CTX__enum,FUNC_TLS_NEW_CTX_size

// FUNC_TLS_DELETE_CTX
#define FUNC_TLS_DELETE_CTX_size "d"
#define FUNC_TLS_DELETE_CTX FUNC_TLS_DELETE_CTX__enum,FUNC_TLS_DELETE_CTX_size

// FUNC_TLS_SET_CIPHER
#define FUNC_TLS_SET_CIPHER_size "‚d"
#define FUNC_TLS_SET_CIPHER FUNC_TLS_SET_CIPHER__enum,FUNC_TLS_SET_CIPHER_size

// FUNC_TLS_SET_VERIFY
#define FUNC_TLS_SET_VERIFY_size "„d"
#define FUNC_TLS_SET_VERIFY FUNC_TLS_SET_VERIFY__enum,FUNC_TLS_SET_VERIFY_size

// FUNC_TLS_SET_CLIENT_AUTH
#define FUNC_TLS_SET_CLIENT_AUTH_size "‚d"
#define FUNC_TLS_SET_CLIENT_AUTH FUNC_TLS_SET_CLIENT_AUTH__enum,FUNC_TLS_SET_CLIENT_AUTH_size

// FUNC_TLS_SET_PASSWD_CALLBACK
#define FUNC_TLS_SET_PASSWD_CALLBACK_size "ƒd"
#define FUNC_TLS_SET_PASSWD_CALLBACK FUNC_TLS_SET_PASSWD_CALLBACK__enum,FUNC_TLS_SET_PASSWD_CALLBACK_size

// FUNC_TLS_SET_IDENTITY
#define FUNC_TLS_SET_IDENTITY_size "‚d"
#define FUNC_TLS_SET_IDENTITY FUNC_TLS_SET_IDENTITY__enum,FUNC_TLS_SET_IDENTITY_size

// FUNC_TLS_NEW_CONN
#define FUNC_TLS_NEW_CONN_size "‚d"
#define FUNC_TLS_NEW_CONN FUNC_TLS_NEW_CONN__enum,FUNC_TLS_NEW_CONN_size

// FUNC_TLS_DELETE_CONN
#define FUNC_TLS_DELETE_CONN_size "d"
#define FUNC_TLS_DELETE_CONN FUNC_TLS_DELETE_CONN__enum,FUNC_TLS_DELETE_CONN_size

// FUNC_TLS_AUTO_REHANDSHAKE
#define FUNC_TLS_AUTO_REHANDSHAKE_size "dc"
#define FUNC_TLS_AUTO_REHANDSHAKE FUNC_TLS_AUTO_REHANDSHAKE__enum,FUNC_TLS_AUTO_REHANDSHAKE_size

// FUNC_TLS_HANDSHAKE
#define FUNC_TLS_HANDSHAKE_size "d"
#define FUNC_TLS_HANDSHAKE FUNC_TLS_HANDSHAKE__enum,FUNC_TLS_HANDSHAKE_size

// FUNC_TLS_REHANDSHAKE
#define FUNC_TLS_REHANDSHAKE_size "d"
#define FUNC_TLS_REHANDSHAKE FUNC_TLS_REHANDSHAKE__enum,FUNC_TLS_REHANDSHAKE_size

// FUNC_TLS_READ
#define FUNC_TLS_READ_size "‚d"
#define FUNC_TLS_READ FUNC_TLS_READ__enum,FUNC_TLS_READ_size

// FUNC_TLS_WRITE
#define FUNC_TLS_WRITE_size "‚d"
#define FUNC_TLS_WRITE FUNC_TLS_WRITE__enum,FUNC_TLS_WRITE_size

// FUNC_TLS_SHUTDOWN
#define FUNC_TLS_SHUTDOWN_size "d"
#define FUNC_TLS_SHUTDOWN FUNC_TLS_SHUTDOWN__enum,FUNC_TLS_SHUTDOWN_size

// FUNC_TLS_CONNECT
#define FUNC_TLS_CONNECT_size "†d"
#define FUNC_TLS_CONNECT FUNC_TLS_CONNECT__enum,FUNC_TLS_CONNECT_size

// TLS_MALLOC
#define TLS_MALLOC_size "d"
#define TLS_MALLOC TLS_MALLOC__enum,TLS_MALLOC_size

// TLS_MALLOC_FAIL
#define TLS_MALLOC_FAIL_size "‚d"
#define TLS_MALLOC_FAIL TLS_MALLOC_FAIL__enum,TLS_MALLOC_FAIL_size

// TLS_MALLOC_OK
#define TLS_MALLOC_OK_size "„d"
#define TLS_MALLOC_OK TLS_MALLOC_OK__enum,TLS_MALLOC_OK_size

// TLS_MFREE
#define TLS_MFREE_size NULL
#define TLS_MFREE TLS_MFREE__enum,TLS_MFREE_size

// TLS_MFREE_OK
#define TLS_MFREE_OK_size "‚d"
#define TLS_MFREE_OK TLS_MFREE_OK__enum,TLS_MFREE_OK_size

// TLS_STATE
#define TLS_STATE_size "‚d"
#define TLS_STATE TLS_STATE__enum,TLS_STATE_size

// TLS_STATE_TRANSITION
#define TLS_STATE_TRANSITION_size "ƒd"
#define TLS_STATE_TRANSITION TLS_STATE_TRANSITION__enum,TLS_STATE_TRANSITION_size

// INFO_RECV_EXT_Q
#define INFO_RECV_EXT_Q_size "h"
#define INFO_RECV_EXT_Q INFO_RECV_EXT_Q__enum,INFO_RECV_EXT_Q_size

// RCVD_INVALID_CERT_RSP
#define RCVD_INVALID_CERT_RSP_size "ƒd"
#define RCVD_INVALID_CERT_RSP RCVD_INVALID_CERT_RSP__enum,RCVD_INVALID_CERT_RSP_size

// RCVD_SELECT_USER_CERT_RSP
#define RCVD_SELECT_USER_CERT_RSP_size "ƒd"
#define RCVD_SELECT_USER_CERT_RSP RCVD_SELECT_USER_CERT_RSP__enum,RCVD_SELECT_USER_CERT_RSP_size

// TLS_NEW_CTX_RETURN
#define TLS_NEW_CTX_RETURN_size "d"
#define TLS_NEW_CTX_RETURN TLS_NEW_CTX_RETURN__enum,TLS_NEW_CTX_RETURN_size

// TLS_READ_BYTES
#define TLS_READ_BYTES_size "d"
#define TLS_READ_BYTES TLS_READ_BYTES__enum,TLS_READ_BYTES_size

// TLS_WRITE_RETURN
#define TLS_WRITE_RETURN_size "‚d"
#define TLS_WRITE_RETURN TLS_WRITE_RETURN__enum,TLS_WRITE_RETURN_size

// TLS_VERIFY_CALLBACK_EXT_ERR
#define TLS_VERIFY_CALLBACK_EXT_ERR_size "‚d"
#define TLS_VERIFY_CALLBACK_EXT_ERR TLS_VERIFY_CALLBACK_EXT_ERR__enum,TLS_VERIFY_CALLBACK_EXT_ERR_size

// TLS_VERIFY_CALLBACK_RETURN
#define TLS_VERIFY_CALLBACK_RETURN_size "d"
#define TLS_VERIFY_CALLBACK_RETURN TLS_VERIFY_CALLBACK_RETURN__enum,TLS_VERIFY_CALLBACK_RETURN_size

// TLS_HANDSHAKE_RETURN
#define TLS_HANDSHAKE_RETURN_size "‚d"
#define TLS_HANDSHAKE_RETURN TLS_HANDSHAKE_RETURN__enum,TLS_HANDSHAKE_RETURN_size

// TLS_WRITE_INVOKES_SEC_SSL_WRITE_RETURN
#define TLS_WRITE_INVOKES_SEC_SSL_WRITE_RETURN_size "ƒd"
#define TLS_WRITE_INVOKES_SEC_SSL_WRITE_RETURN TLS_WRITE_INVOKES_SEC_SSL_WRITE_RETURN__enum,TLS_WRITE_INVOKES_SEC_SSL_WRITE_RETURN_size

// TLS_WRITE_WANT_WRITE
#define TLS_WRITE_WANT_WRITE_size "d"
#define TLS_WRITE_WANT_WRITE TLS_WRITE_WANT_WRITE__enum,TLS_WRITE_WANT_WRITE_size

// TLS_MEM_PEAK_SIZE
#define TLS_MEM_PEAK_SIZE_size "d"
#define TLS_MEM_PEAK_SIZE TLS_MEM_PEAK_SIZE__enum,TLS_MEM_PEAK_SIZE_size

// TLS_MEM_CURR_SIZE
#define TLS_MEM_CURR_SIZE_size "d"
#define TLS_MEM_CURR_SIZE TLS_MEM_CURR_SIZE__enum,TLS_MEM_CURR_SIZE_size

// TLS_LOG_PLAINTEXT
#define TLS_LOG_PLAINTEXT_size "c"
#define TLS_LOG_PLAINTEXT TLS_LOG_PLAINTEXT__enum,TLS_LOG_PLAINTEXT_size

// TLS_LOG_PLAINTEXT_ERROR
#define TLS_LOG_PLAINTEXT_ERROR_size NULL
#define TLS_LOG_PLAINTEXT_ERROR TLS_LOG_PLAINTEXT_ERROR__enum,TLS_LOG_PLAINTEXT_ERROR_size

// TLS_SIM_SUPC_PRIVKEY_ORIG
#define TLS_SIM_SUPC_PRIVKEY_ORIG_size "d"
#define TLS_SIM_SUPC_PRIVKEY_ORIG TLS_SIM_SUPC_PRIVKEY_ORIG__enum,TLS_SIM_SUPC_PRIVKEY_ORIG_size

// TLS_SIM_SUPC_PRIVKEY_ENCODED
#define TLS_SIM_SUPC_PRIVKEY_ENCODED_size "d"
#define TLS_SIM_SUPC_PRIVKEY_ENCODED TLS_SIM_SUPC_PRIVKEY_ENCODED__enum,TLS_SIM_SUPC_PRIVKEY_ENCODED_size

// TLS_SIM_SUPC_PRIVKEY_ENCODE_FAILED
#define TLS_SIM_SUPC_PRIVKEY_ENCODE_FAILED_size "d"
#define TLS_SIM_SUPC_PRIVKEY_ENCODE_FAILED TLS_SIM_SUPC_PRIVKEY_ENCODE_FAILED__enum,TLS_SIM_SUPC_PRIVKEY_ENCODE_FAILED_size

// TLS_CURRENT_TIME
#define TLS_CURRENT_TIME_size "†d"
#define TLS_CURRENT_TIME TLS_CURRENT_TIME__enum,TLS_CURRENT_TIME_size

// TLS_TRIM_VERSION
#define TLS_TRIM_VERSION_size "‚d"
#define TLS_TRIM_VERSION TLS_TRIM_VERSION__enum,TLS_TRIM_VERSION_size

// TLS_IS_BLOCKING_SOCKET
#define TLS_IS_BLOCKING_SOCKET_size "d"
#define TLS_IS_BLOCKING_SOCKET TLS_IS_BLOCKING_SOCKET__enum,TLS_IS_BLOCKING_SOCKET_size

// TLS_FW_NOT_SOCKET_NOTIFY
#define TLS_FW_NOT_SOCKET_NOTIFY_size "h"
#define TLS_FW_NOT_SOCKET_NOTIFY TLS_FW_NOT_SOCKET_NOTIFY__enum,TLS_FW_NOT_SOCKET_NOTIFY_size

// TLS_DROP_SOCKET_NOTIFY
#define TLS_DROP_SOCKET_NOTIFY_size "d"
#define TLS_DROP_SOCKET_NOTIFY TLS_DROP_SOCKET_NOTIFY__enum,TLS_DROP_SOCKET_NOTIFY_size

// TLS_DELETE_HANGING_CONN
#define TLS_DELETE_HANGING_CONN_size "d"
#define TLS_DELETE_HANGING_CONN TLS_DELETE_HANGING_CONN__enum,TLS_DELETE_HANGING_CONN_size

// TLS_WARN_OVERWRITE_CA_PATH
#define TLS_WARN_OVERWRITE_CA_PATH_size "d"
#define TLS_WARN_OVERWRITE_CA_PATH TLS_WARN_OVERWRITE_CA_PATH__enum,TLS_WARN_OVERWRITE_CA_PATH_size

// CERTMAN_CERT_ID_CNF_WRONG_CERT_TYPE
#define CERTMAN_CERT_ID_CNF_WRONG_CERT_TYPE_size "‚d"
#define CERTMAN_CERT_ID_CNF_WRONG_CERT_TYPE CERTMAN_CERT_ID_CNF_WRONG_CERT_TYPE__enum,CERTMAN_CERT_ID_CNF_WRONG_CERT_TYPE_size

// CERTMAN_CERT_CHAIN_CNF_WRONG_CERT_TYPE
#define CERTMAN_CERT_CHAIN_CNF_WRONG_CERT_TYPE_size "‚d"
#define CERTMAN_CERT_CHAIN_CNF_WRONG_CERT_TYPE CERTMAN_CERT_CHAIN_CNF_WRONG_CERT_TYPE__enum,CERTMAN_CERT_CHAIN_CNF_WRONG_CERT_TYPE_size

// CERTMAN_PRIVKEY_CNF_WRONG_CERT_TYPE
#define CERTMAN_PRIVKEY_CNF_WRONG_CERT_TYPE_size "‚d"
#define CERTMAN_PRIVKEY_CNF_WRONG_CERT_TYPE CERTMAN_PRIVKEY_CNF_WRONG_CERT_TYPE__enum,CERTMAN_PRIVKEY_CNF_WRONG_CERT_TYPE_size

// TLS_READ_ERROR
#define TLS_READ_ERROR_size "d"
#define TLS_READ_ERROR TLS_READ_ERROR__enum,TLS_READ_ERROR_size

// TLS_SKIP_HANDSHAKE_DONE
#define TLS_SKIP_HANDSHAKE_DONE_size "d"
#define TLS_SKIP_HANDSHAKE_DONE TLS_SKIP_HANDSHAKE_DONE__enum,TLS_SKIP_HANDSHAKE_DONE_size

// TLS_RCVD_INVALID_CERT
#define TLS_RCVD_INVALID_CERT_size "d"
#define TLS_RCVD_INVALID_CERT TLS_RCVD_INVALID_CERT__enum,TLS_RCVD_INVALID_CERT_size

// TLS_SKIP_RCVD_INVALID_CERT
#define TLS_SKIP_RCVD_INVALID_CERT_size "d"
#define TLS_SKIP_RCVD_INVALID_CERT TLS_SKIP_RCVD_INVALID_CERT__enum,TLS_SKIP_RCVD_INVALID_CERT_size

// TLS_RCVD_INVALID_CERT_WAIT_USER_RSP
#define TLS_RCVD_INVALID_CERT_WAIT_USER_RSP_size "d"
#define TLS_RCVD_INVALID_CERT_WAIT_USER_RSP TLS_RCVD_INVALID_CERT_WAIT_USER_RSP__enum,TLS_RCVD_INVALID_CERT_WAIT_USER_RSP_size

// TLS_RCVD_CLIENT_AUTH
#define TLS_RCVD_CLIENT_AUTH_size "d"
#define TLS_RCVD_CLIENT_AUTH TLS_RCVD_CLIENT_AUTH__enum,TLS_RCVD_CLIENT_AUTH_size

// TLS_SKIP_RCVD_CLIENT_AUTH
#define TLS_SKIP_RCVD_CLIENT_AUTH_size "d"
#define TLS_SKIP_RCVD_CLIENT_AUTH TLS_SKIP_RCVD_CLIENT_AUTH__enum,TLS_SKIP_RCVD_CLIENT_AUTH_size

// TLS_RCVD_CLIENT_AUTH_WAIT_USER_RSP
#define TLS_RCVD_CLIENT_AUTH_WAIT_USER_RSP_size "d"
#define TLS_RCVD_CLIENT_AUTH_WAIT_USER_RSP TLS_RCVD_CLIENT_AUTH_WAIT_USER_RSP__enum,TLS_RCVD_CLIENT_AUTH_WAIT_USER_RSP_size

// WARN_CHECK_PEER_NAME_NOT_SUPPORTED
#define WARN_CHECK_PEER_NAME_NOT_SUPPORTED_size NULL
#define WARN_CHECK_PEER_NAME_NOT_SUPPORTED WARN_CHECK_PEER_NAME_NOT_SUPPORTED__enum,WARN_CHECK_PEER_NAME_NOT_SUPPORTED_size

// ERROR_NONSUPPORT_MSG
#define ERROR_NONSUPPORT_MSG_size "h"
#define ERROR_NONSUPPORT_MSG ERROR_NONSUPPORT_MSG__enum,ERROR_NONSUPPORT_MSG_size

// TLS_TOO_MANY_CIPHERS
#define TLS_TOO_MANY_CIPHERS_size "‚d"
#define TLS_TOO_MANY_CIPHERS TLS_TOO_MANY_CIPHERS__enum,TLS_TOO_MANY_CIPHERS_size

// TLS_INVALID_CIPHER
#define TLS_INVALID_CIPHER_size "‚d"
#define TLS_INVALID_CIPHER TLS_INVALID_CIPHER__enum,TLS_INVALID_CIPHER_size

// TLS_TOO_MANY_CLIENT_AUTH_MODES
#define TLS_TOO_MANY_CLIENT_AUTH_MODES_size "‚d"
#define TLS_TOO_MANY_CLIENT_AUTH_MODES TLS_TOO_MANY_CLIENT_AUTH_MODES__enum,TLS_TOO_MANY_CLIENT_AUTH_MODES_size

// TLS_INVALID_AUTH_MODE
#define TLS_INVALID_AUTH_MODE_size "‚d"
#define TLS_INVALID_AUTH_MODE TLS_INVALID_AUTH_MODE__enum,TLS_INVALID_AUTH_MODE_size

// TLS_ACCESS_INVALID_CTX
#define TLS_ACCESS_INVALID_CTX_size "d"
#define TLS_ACCESS_INVALID_CTX TLS_ACCESS_INVALID_CTX__enum,TLS_ACCESS_INVALID_CTX_size

// TLS_MODULE_NOT_MATCH
#define TLS_MODULE_NOT_MATCH_size "‚h"
#define TLS_MODULE_NOT_MATCH TLS_MODULE_NOT_MATCH__enum,TLS_MODULE_NOT_MATCH_size

// TLS_ACCESS_INVALID_CONN
#define TLS_ACCESS_INVALID_CONN_size "d"
#define TLS_ACCESS_INVALID_CONN TLS_ACCESS_INVALID_CONN__enum,TLS_ACCESS_INVALID_CONN_size

// TLS_ACCESS_INVALID_SOCKET
#define TLS_ACCESS_INVALID_SOCKET_size "d"
#define TLS_ACCESS_INVALID_SOCKET TLS_ACCESS_INVALID_SOCKET__enum,TLS_ACCESS_INVALID_SOCKET_size

// TLS_CERT_XID_NOT_FOUND
#define TLS_CERT_XID_NOT_FOUND_size "d"
#define TLS_CERT_XID_NOT_FOUND TLS_CERT_XID_NOT_FOUND__enum,TLS_CERT_XID_NOT_FOUND_size

// ERROR_NONSUPPORT_CERTMAN_MSG
#define ERROR_NONSUPPORT_CERTMAN_MSG_size "h"
#define ERROR_NONSUPPORT_CERTMAN_MSG ERROR_NONSUPPORT_CERTMAN_MSG__enum,ERROR_NONSUPPORT_CERTMAN_MSG_size

// ERROR_NONSUPPORT_MMI_CERTMAN_MSG
#define ERROR_NONSUPPORT_MMI_CERTMAN_MSG_size "h"
#define ERROR_NONSUPPORT_MMI_CERTMAN_MSG ERROR_NONSUPPORT_MMI_CERTMAN_MSG__enum,ERROR_NONSUPPORT_MMI_CERTMAN_MSG_size

// INVALID_CERT_RSP_MATCH_NO_CONN
#define INVALID_CERT_RSP_MATCH_NO_CONN_size "d"
#define INVALID_CERT_RSP_MATCH_NO_CONN INVALID_CERT_RSP_MATCH_NO_CONN__enum,INVALID_CERT_RSP_MATCH_NO_CONN_size

// CLIENT_AUTH_RSP_MATCH_NO_CONN
#define CLIENT_AUTH_RSP_MATCH_NO_CONN_size "d"
#define CLIENT_AUTH_RSP_MATCH_NO_CONN CLIENT_AUTH_RSP_MATCH_NO_CONN__enum,CLIENT_AUTH_RSP_MATCH_NO_CONN_size

// INVALID_CERT_RSP_WRONG_STATE
#define INVALID_CERT_RSP_WRONG_STATE_size "d"
#define INVALID_CERT_RSP_WRONG_STATE INVALID_CERT_RSP_WRONG_STATE__enum,INVALID_CERT_RSP_WRONG_STATE_size

// CLIENT_AUTH_RSP_WRONG_STATE
#define CLIENT_AUTH_RSP_WRONG_STATE_size "d"
#define CLIENT_AUTH_RSP_WRONG_STATE CLIENT_AUTH_RSP_WRONG_STATE__enum,CLIENT_AUTH_RSP_WRONG_STATE_size

// CERTMAN_MSG_NO_MATCH_CTX
#define CERTMAN_MSG_NO_MATCH_CTX_size "d"
#define CERTMAN_MSG_NO_MATCH_CTX CERTMAN_MSG_NO_MATCH_CTX__enum,CERTMAN_MSG_NO_MATCH_CTX_size

// TLS_NEW_CTX_INVALID_SIDE
#define TLS_NEW_CTX_INVALID_SIDE_size "d"
#define TLS_NEW_CTX_INVALID_SIDE TLS_NEW_CTX_INVALID_SIDE__enum,TLS_NEW_CTX_INVALID_SIDE_size

// TLS_NEW_CTX_INVALID_VER
#define TLS_NEW_CTX_INVALID_VER_size "d"
#define TLS_NEW_CTX_INVALID_VER TLS_NEW_CTX_INVALID_VER__enum,TLS_NEW_CTX_INVALID_VER_size

// TLS_NEW_CTX_ASYM_MEM_CB
#define TLS_NEW_CTX_ASYM_MEM_CB_size "‚d"
#define TLS_NEW_CTX_ASYM_MEM_CB TLS_NEW_CTX_ASYM_MEM_CB__enum,TLS_NEW_CTX_ASYM_MEM_CB_size

// TLS_GET_CTX_SLOT_FAIL
#define TLS_GET_CTX_SLOT_FAIL_size NULL
#define TLS_GET_CTX_SLOT_FAIL TLS_GET_CTX_SLOT_FAIL__enum,TLS_GET_CTX_SLOT_FAIL_size

// TLS_SEC_SSL_CTX_NEW_FAILED
#define TLS_SEC_SSL_CTX_NEW_FAILED_size NULL
#define TLS_SEC_SSL_CTX_NEW_FAILED TLS_SEC_SSL_CTX_NEW_FAILED__enum,TLS_SEC_SSL_CTX_NEW_FAILED_size

// TLS_SEC_SSL_CTX_SET_PRNG_FAILED
#define TLS_SEC_SSL_CTX_SET_PRNG_FAILED_size NULL
#define TLS_SEC_SSL_CTX_SET_PRNG_FAILED TLS_SEC_SSL_CTX_SET_PRNG_FAILED__enum,TLS_SEC_SSL_CTX_SET_PRNG_FAILED_size

// TLS_NEW_CONN_CTX_NO_MEMORY
#define TLS_NEW_CONN_CTX_NO_MEMORY_size "‚d"
#define TLS_NEW_CONN_CTX_NO_MEMORY TLS_NEW_CONN_CTX_NO_MEMORY__enum,TLS_NEW_CONN_CTX_NO_MEMORY_size

// TLS_TASK_NOT_READY
#define TLS_TASK_NOT_READY_size NULL
#define TLS_TASK_NOT_READY TLS_TASK_NOT_READY__enum,TLS_TASK_NOT_READY_size

// TLS_RCVD_ALERT
#define TLS_RCVD_ALERT_size "dcd"
#define TLS_RCVD_ALERT TLS_RCVD_ALERT__enum,TLS_RCVD_ALERT_size

// TLS_LOAD_PERSONAL_CERT_FAIL
#define TLS_LOAD_PERSONAL_CERT_FAIL_size "ƒd"
#define TLS_LOAD_PERSONAL_CERT_FAIL TLS_LOAD_PERSONAL_CERT_FAIL__enum,TLS_LOAD_PERSONAL_CERT_FAIL_size

// TLS_LOAD_ROOT_CA_FAIL
#define TLS_LOAD_ROOT_CA_FAIL_size "‚d"
#define TLS_LOAD_ROOT_CA_FAIL TLS_LOAD_ROOT_CA_FAIL__enum,TLS_LOAD_ROOT_CA_FAIL_size

// TLS_SET_DEFAULT_CIPHER_LIST_FAIL
#define TLS_SET_DEFAULT_CIPHER_LIST_FAIL_size "‚d"
#define TLS_SET_DEFAULT_CIPHER_LIST_FAIL TLS_SET_DEFAULT_CIPHER_LIST_FAIL__enum,TLS_SET_DEFAULT_CIPHER_LIST_FAIL_size

// TLS_USE_PRIVATEKEY_FILE_FAIL
#define TLS_USE_PRIVATEKEY_FILE_FAIL_size "ƒd"
#define TLS_USE_PRIVATEKEY_FILE_FAIL TLS_USE_PRIVATEKEY_FILE_FAIL__enum,TLS_USE_PRIVATEKEY_FILE_FAIL_size

// TLS_OCSP_VERIFY_CERT_FAIL
#define TLS_OCSP_VERIFY_CERT_FAIL_size "d"
#define TLS_OCSP_VERIFY_CERT_FAIL TLS_OCSP_VERIFY_CERT_FAIL__enum,TLS_OCSP_VERIFY_CERT_FAIL_size


#endif // TLS_TRC_GEN.H
