#ifndef _UEM_TRC_GEN_H_
#define _UEM_TRC_GEN_H_

// FUNC_UEM_KEYPAD_POWER_ON_IND
#define FUNC_UEM_KEYPAD_POWER_ON_IND_size NULL
#define FUNC_UEM_KEYPAD_POWER_ON_IND FUNC_UEM_KEYPAD_POWER_ON_IND__enum,FUNC_UEM_KEYPAD_POWER_ON_IND_size

// FUNC_UEM_ALARM_POWER_ON_IND
#define FUNC_UEM_ALARM_POWER_ON_IND_size NULL
#define FUNC_UEM_ALARM_POWER_ON_IND FUNC_UEM_ALARM_POWER_ON_IND__enum,FUNC_UEM_ALARM_POWER_ON_IND_size

// FUNC_UEMRTC_PERIOD_IND
#define FUNC_UEMRTC_PERIOD_IND_size NULL
#define FUNC_UEMRTC_PERIOD_IND FUNC_UEMRTC_PERIOD_IND__enum,FUNC_UEMRTC_PERIOD_IND_size

// FUNC_UEM_PMIC_IND
#define FUNC_UEM_PMIC_IND_size NULL
#define FUNC_UEM_PMIC_IND FUNC_UEM_PMIC_IND__enum,FUNC_UEM_PMIC_IND_size

// FUNC_UEM_WRITE_DATA_CNF
#define FUNC_UEM_WRITE_DATA_CNF_size NULL
#define FUNC_UEM_WRITE_DATA_CNF FUNC_UEM_WRITE_DATA_CNF__enum,FUNC_UEM_WRITE_DATA_CNF_size

// FUNC_UEM_READ_DATA_CNF
#define FUNC_UEM_READ_DATA_CNF_size NULL
#define FUNC_UEM_READ_DATA_CNF FUNC_UEM_READ_DATA_CNF__enum,FUNC_UEM_READ_DATA_CNF_size

// FUNC_UEM_SET_PROFILE_REQ
#define FUNC_UEM_SET_PROFILE_REQ_size NULL
#define FUNC_UEM_SET_PROFILE_REQ FUNC_UEM_SET_PROFILE_REQ__enum,FUNC_UEM_SET_PROFILE_REQ_size

// FUNC_UEM_STARTUP_REQ
#define FUNC_UEM_STARTUP_REQ_size NULL
#define FUNC_UEM_STARTUP_REQ FUNC_UEM_STARTUP_REQ__enum,FUNC_UEM_STARTUP_REQ_size

// FUNC_UEM_LANGUAGE_REQ
#define FUNC_UEM_LANGUAGE_REQ_size NULL
#define FUNC_UEM_LANGUAGE_REQ FUNC_UEM_LANGUAGE_REQ__enum,FUNC_UEM_LANGUAGE_REQ_size

// FUNC_UEM_CURRENT_TIME_REQ
#define FUNC_UEM_CURRENT_TIME_REQ_size NULL
#define FUNC_UEM_CURRENT_TIME_REQ FUNC_UEM_CURRENT_TIME_REQ__enum,FUNC_UEM_CURRENT_TIME_REQ_size

// FUNC_UEM_EM_REQ
#define FUNC_UEM_EM_REQ_size NULL
#define FUNC_UEM_EM_REQ FUNC_UEM_EM_REQ__enum,FUNC_UEM_EM_REQ_size

// FUNC_UEMDRV_CCCI_EM_REQ_HDLR
#define FUNC_UEMDRV_CCCI_EM_REQ_HDLR_size NULL
#define FUNC_UEMDRV_CCCI_EM_REQ_HDLR FUNC_UEMDRV_CCCI_EM_REQ_HDLR__enum,FUNC_UEMDRV_CCCI_EM_REQ_HDLR_size

// FUNC_UEMDRV_CCCI_EM_REQ_HDLR_INFO
#define FUNC_UEMDRV_CCCI_EM_REQ_HDLR_INFO_size "ƒd"
#define FUNC_UEMDRV_CCCI_EM_REQ_HDLR_INFO FUNC_UEMDRV_CCCI_EM_REQ_HDLR_INFO__enum,FUNC_UEMDRV_CCCI_EM_REQ_HDLR_INFO_size

// FUNC_UEM_KEYPAD_ESTIMATE_TIME
#define FUNC_UEM_KEYPAD_ESTIMATE_TIME_size "d"
#define FUNC_UEM_KEYPAD_ESTIMATE_TIME FUNC_UEM_KEYPAD_ESTIMATE_TIME__enum,FUNC_UEM_KEYPAD_ESTIMATE_TIME_size

// FUNC_UEM_AUDIO_PLAY
#define FUNC_UEM_AUDIO_PLAY_size NULL
#define FUNC_UEM_AUDIO_PLAY FUNC_UEM_AUDIO_PLAY__enum,FUNC_UEM_AUDIO_PLAY_size

// FUNC_UEM_AUDIO_STOP
#define FUNC_UEM_AUDIO_STOP_size NULL
#define FUNC_UEM_AUDIO_STOP FUNC_UEM_AUDIO_STOP__enum,FUNC_UEM_AUDIO_STOP_size

// FUNC_UEM_DEMO_EXT_IMELODY_RING
#define FUNC_UEM_DEMO_EXT_IMELODY_RING_size NULL
#define FUNC_UEM_DEMO_EXT_IMELODY_RING FUNC_UEM_DEMO_EXT_IMELODY_RING__enum,FUNC_UEM_DEMO_EXT_IMELODY_RING_size

// FUNC_UEM_POEWR_OFF
#define FUNC_UEM_POEWR_OFF_size NULL
#define FUNC_UEM_POEWR_OFF FUNC_UEM_POEWR_OFF__enum,FUNC_UEM_POEWR_OFF_size

// FUNC_UEM_RTC_GET_TIME
#define FUNC_UEM_RTC_GET_TIME_size NULL
#define FUNC_UEM_RTC_GET_TIME FUNC_UEM_RTC_GET_TIME__enum,FUNC_UEM_RTC_GET_TIME_size

// FUNC_UEM_RTC_SET_TIME
#define FUNC_UEM_RTC_SET_TIME_size NULL
#define FUNC_UEM_RTC_SET_TIME FUNC_UEM_RTC_SET_TIME__enum,FUNC_UEM_RTC_SET_TIME_size

// FUNC_UEM_ALARM_GET_TIME
#define FUNC_UEM_ALARM_GET_TIME_size NULL
#define FUNC_UEM_ALARM_GET_TIME FUNC_UEM_ALARM_GET_TIME__enum,FUNC_UEM_ALARM_GET_TIME_size

// FUNC_UEM_RTC_CNFG_FORMAT
#define FUNC_UEM_RTC_CNFG_FORMAT_size NULL
#define FUNC_UEM_RTC_CNFG_FORMAT FUNC_UEM_RTC_CNFG_FORMAT__enum,FUNC_UEM_RTC_CNFG_FORMAT_size

// FUNC_UEM_RTC_DELETE_DATE_TIME
#define FUNC_UEM_RTC_DELETE_DATE_TIME_size NULL
#define FUNC_UEM_RTC_DELETE_DATE_TIME FUNC_UEM_RTC_DELETE_DATE_TIME__enum,FUNC_UEM_RTC_DELETE_DATE_TIME_size

// FUNC_UEM_SET_MUTE
#define FUNC_UEM_SET_MUTE_size NULL
#define FUNC_UEM_SET_MUTE FUNC_UEM_SET_MUTE__enum,FUNC_UEM_SET_MUTE_size

// FUNC_UEM_GPIO_SET_LEVEL
#define FUNC_UEM_GPIO_SET_LEVEL_size "‚d"
#define FUNC_UEM_GPIO_SET_LEVEL FUNC_UEM_GPIO_SET_LEVEL__enum,FUNC_UEM_GPIO_SET_LEVEL_size

// FUNC_UEM_GPIO_CONTROL_LED
#define FUNC_UEM_GPIO_CONTROL_LED_size "„d"
#define FUNC_UEM_GPIO_CONTROL_LED FUNC_UEM_GPIO_CONTROL_LED__enum,FUNC_UEM_GPIO_CONTROL_LED_size

// FUNC_UEM_GET_EQUIP_ID
#define FUNC_UEM_GET_EQUIP_ID_size NULL
#define FUNC_UEM_GET_EQUIP_ID FUNC_UEM_GET_EQUIP_ID__enum,FUNC_UEM_GET_EQUIP_ID_size

// FUNC_UEM_GET_BATTERY_STATUS
#define FUNC_UEM_GET_BATTERY_STATUS_size NULL
#define FUNC_UEM_GET_BATTERY_STATUS FUNC_UEM_GET_BATTERY_STATUS__enum,FUNC_UEM_GET_BATTERY_STATUS_size

// FUNC_UEM_SET_SILENT_MODE
#define FUNC_UEM_SET_SILENT_MODE_size NULL
#define FUNC_UEM_SET_SILENT_MODE FUNC_UEM_SET_SILENT_MODE__enum,FUNC_UEM_SET_SILENT_MODE_size

// FUNC_UEM_GET_SILENT_MODE
#define FUNC_UEM_GET_SILENT_MODE_size NULL
#define FUNC_UEM_GET_SILENT_MODE FUNC_UEM_GET_SILENT_MODE__enum,FUNC_UEM_GET_SILENT_MODE_size

// FUNC_UEM_SET_ALERT_MODE
#define FUNC_UEM_SET_ALERT_MODE_size NULL
#define FUNC_UEM_SET_ALERT_MODE FUNC_UEM_SET_ALERT_MODE__enum,FUNC_UEM_SET_ALERT_MODE_size

// FUNC_UEM_SET_GREETING_TEXT
#define FUNC_UEM_SET_GREETING_TEXT_size NULL
#define FUNC_UEM_SET_GREETING_TEXT FUNC_UEM_SET_GREETING_TEXT__enum,FUNC_UEM_SET_GREETING_TEXT_size

// FUNC_UEM_GPIO_GET_LEVEL
#define FUNC_UEM_GPIO_GET_LEVEL_size NULL
#define FUNC_UEM_GPIO_GET_LEVEL FUNC_UEM_GPIO_GET_LEVEL__enum,FUNC_UEM_GPIO_GET_LEVEL_size

// FUNC_UEM_EQUIP_SET_CC
#define FUNC_UEM_EQUIP_SET_CC_size NULL
#define FUNC_UEM_EQUIP_SET_CC FUNC_UEM_EQUIP_SET_CC__enum,FUNC_UEM_EQUIP_SET_CC_size

// FUNC_UEM_SET_LANG
#define FUNC_UEM_SET_LANG_size NULL
#define FUNC_UEM_SET_LANG FUNC_UEM_SET_LANG__enum,FUNC_UEM_SET_LANG_size

// FUNC_UEM_GET_LANG
#define FUNC_UEM_GET_LANG_size NULL
#define FUNC_UEM_GET_LANG FUNC_UEM_GET_LANG__enum,FUNC_UEM_GET_LANG_size

// FUNC_UEM_SET_DATE_TIME_FORMAT
#define FUNC_UEM_SET_DATE_TIME_FORMAT_size NULL
#define FUNC_UEM_SET_DATE_TIME_FORMAT FUNC_UEM_SET_DATE_TIME_FORMAT__enum,FUNC_UEM_SET_DATE_TIME_FORMAT_size

// FUNC_UEM_GET_DATE_TIME_FORMAT
#define FUNC_UEM_GET_DATE_TIME_FORMAT_size NULL
#define FUNC_UEM_GET_DATE_TIME_FORMAT FUNC_UEM_GET_DATE_TIME_FORMAT__enum,FUNC_UEM_GET_DATE_TIME_FORMAT_size

// FUNC_UEM_POWER_RESET
#define FUNC_UEM_POWER_RESET_size NULL
#define FUNC_UEM_POWER_RESET FUNC_UEM_POWER_RESET__enum,FUNC_UEM_POWER_RESET_size

// FUNC_UEM_ALARM_DETECT
#define FUNC_UEM_ALARM_DETECT_size NULL
#define FUNC_UEM_ALARM_DETECT FUNC_UEM_ALARM_DETECT__enum,FUNC_UEM_ALARM_DETECT_size

// FUNC_UEM_RTC_PERIOD
#define FUNC_UEM_RTC_PERIOD_size NULL
#define FUNC_UEM_RTC_PERIOD FUNC_UEM_RTC_PERIOD__enum,FUNC_UEM_RTC_PERIOD_size

// FUNC_UEM_KEYPAD_POWER_ON
#define FUNC_UEM_KEYPAD_POWER_ON_size NULL
#define FUNC_UEM_KEYPAD_POWER_ON FUNC_UEM_KEYPAD_POWER_ON__enum,FUNC_UEM_KEYPAD_POWER_ON_size

// FUNC_UEM_PMIC_DETECT
#define FUNC_UEM_PMIC_DETECT_size NULL
#define FUNC_UEM_PMIC_DETECT FUNC_UEM_PMIC_DETECT__enum,FUNC_UEM_PMIC_DETECT_size

// FUNC_UEM_GPIO_DETECT
#define FUNC_UEM_GPIO_DETECT_size NULL
#define FUNC_UEM_GPIO_DETECT FUNC_UEM_GPIO_DETECT__enum,FUNC_UEM_GPIO_DETECT_size

// FUNC_UEM_DRV_PWRON_START
#define FUNC_UEM_DRV_PWRON_START_size NULL
#define FUNC_UEM_DRV_PWRON_START FUNC_UEM_DRV_PWRON_START__enum,FUNC_UEM_DRV_PWRON_START_size

// FUNC_UEM_DRV_PWRON_END
#define FUNC_UEM_DRV_PWRON_END_size NULL
#define FUNC_UEM_DRV_PWRON_END FUNC_UEM_DRV_PWRON_END__enum,FUNC_UEM_DRV_PWRON_END_size

// FUNC_UEM_MMICHECK_LOGOSTART
#define FUNC_UEM_MMICHECK_LOGOSTART_size NULL
#define FUNC_UEM_MMICHECK_LOGOSTART FUNC_UEM_MMICHECK_LOGOSTART__enum,FUNC_UEM_MMICHECK_LOGOSTART_size

// FUNC_UEM_MMICHECK_LOGOEND
#define FUNC_UEM_MMICHECK_LOGOEND_size NULL
#define FUNC_UEM_MMICHECK_LOGOEND FUNC_UEM_MMICHECK_LOGOEND__enum,FUNC_UEM_MMICHECK_LOGOEND_size

// FUNC_UEM_CCCI_ACK_CALLBACK
#define FUNC_UEM_CCCI_ACK_CALLBACK_size NULL
#define FUNC_UEM_CCCI_ACK_CALLBACK FUNC_UEM_CCCI_ACK_CALLBACK__enum,FUNC_UEM_CCCI_ACK_CALLBACK_size

// FUNC_UEM_CCCI_ACK_CAlLBACK_INFO
#define FUNC_UEM_CCCI_ACK_CAlLBACK_INFO_size "d"
#define FUNC_UEM_CCCI_ACK_CAlLBACK_INFO FUNC_UEM_CCCI_ACK_CAlLBACK_INFO__enum,FUNC_UEM_CCCI_ACK_CAlLBACK_INFO_size

// FUNC_UEM_CCCI_EM_REQ_HDLR
#define FUNC_UEM_CCCI_EM_REQ_HDLR_size "d"
#define FUNC_UEM_CCCI_EM_REQ_HDLR FUNC_UEM_CCCI_EM_REQ_HDLR__enum,FUNC_UEM_CCCI_EM_REQ_HDLR_size

// FUNC_UEM_CCCI_EM_REQ_GET_SLEEP_INFO
#define FUNC_UEM_CCCI_EM_REQ_GET_SLEEP_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_GET_SLEEP_INFO FUNC_UEM_CCCI_EM_REQ_GET_SLEEP_INFO__enum,FUNC_UEM_CCCI_EM_REQ_GET_SLEEP_INFO_size

// FUNC_UEM_CCCI_EM_REQ_SLEEP_INFO
#define FUNC_UEM_CCCI_EM_REQ_SLEEP_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_SLEEP_INFO FUNC_UEM_CCCI_EM_REQ_SLEEP_INFO__enum,FUNC_UEM_CCCI_EM_REQ_SLEEP_INFO_size

// FUNC_UEM_CCCI_EM_REQ_GET_DCM_INFO
#define FUNC_UEM_CCCI_EM_REQ_GET_DCM_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_GET_DCM_INFO FUNC_UEM_CCCI_EM_REQ_GET_DCM_INFO__enum,FUNC_UEM_CCCI_EM_REQ_GET_DCM_INFO_size

// FUNC_UEM_CCCI_EM_REQ_DCM_INFO
#define FUNC_UEM_CCCI_EM_REQ_DCM_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_DCM_INFO FUNC_UEM_CCCI_EM_REQ_DCM_INFO__enum,FUNC_UEM_CCCI_EM_REQ_DCM_INFO_size

// FUNC_UEM_CCCI_EM_REQ_GET_MEMDUMP_INFO
#define FUNC_UEM_CCCI_EM_REQ_GET_MEMDUMP_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_GET_MEMDUMP_INFO FUNC_UEM_CCCI_EM_REQ_GET_MEMDUMP_INFO__enum,FUNC_UEM_CCCI_EM_REQ_GET_MEMDUMP_INFO_size

// FUNC_UEM_CCCI_EM_REQ_MEMDUMP_INFO
#define FUNC_UEM_CCCI_EM_REQ_MEMDUMP_INFO_size "d"
#define FUNC_UEM_CCCI_EM_REQ_MEMDUMP_INFO FUNC_UEM_CCCI_EM_REQ_MEMDUMP_INFO__enum,FUNC_UEM_CCCI_EM_REQ_MEMDUMP_INFO_size

// FUNC_UEM_CCCI_EM_REQ_GETUART_INFO
#define FUNC_UEM_CCCI_EM_REQ_GETUART_INFO_size "‚d"
#define FUNC_UEM_CCCI_EM_REQ_GETUART_INFO FUNC_UEM_CCCI_EM_REQ_GETUART_INFO__enum,FUNC_UEM_CCCI_EM_REQ_GETUART_INFO_size

// FUNC_UEM_CCCI_EM_REQ_GETUART_INFO2
#define FUNC_UEM_CCCI_EM_REQ_GETUART_INFO2_size "‚d"
#define FUNC_UEM_CCCI_EM_REQ_GETUART_INFO2 FUNC_UEM_CCCI_EM_REQ_GETUART_INFO2__enum,FUNC_UEM_CCCI_EM_REQ_GETUART_INFO2_size

// FUNC_UEM_CCCI_EM_REQ_SETUART_INFO
#define FUNC_UEM_CCCI_EM_REQ_SETUART_INFO_size "‚d"
#define FUNC_UEM_CCCI_EM_REQ_SETUART_INFO FUNC_UEM_CCCI_EM_REQ_SETUART_INFO__enum,FUNC_UEM_CCCI_EM_REQ_SETUART_INFO_size

// FUNC_UEM_CCCI_EM_UART_PORT_SETTING_INFO
#define FUNC_UEM_CCCI_EM_UART_PORT_SETTING_INFO_size "d"
#define FUNC_UEM_CCCI_EM_UART_PORT_SETTING_INFO FUNC_UEM_CCCI_EM_UART_PORT_SETTING_INFO__enum,FUNC_UEM_CCCI_EM_UART_PORT_SETTING_INFO_size

// FUNC_UEM_CCCI_EM_UART_PORT_READ_INFO
#define FUNC_UEM_CCCI_EM_UART_PORT_READ_INFO_size "ƒd"
#define FUNC_UEM_CCCI_EM_UART_PORT_READ_INFO FUNC_UEM_CCCI_EM_UART_PORT_READ_INFO__enum,FUNC_UEM_CCCI_EM_UART_PORT_READ_INFO_size

// FUNC_UEM_CCCI_EM_UART_PORT_WRITE_INFO
#define FUNC_UEM_CCCI_EM_UART_PORT_WRITE_INFO_size "d"
#define FUNC_UEM_CCCI_EM_UART_PORT_WRITE_INFO FUNC_UEM_CCCI_EM_UART_PORT_WRITE_INFO__enum,FUNC_UEM_CCCI_EM_UART_PORT_WRITE_INFO_size

// FUNC_UEM_CCCI_EM_UART_PORT_CONFLICT_INFO
#define FUNC_UEM_CCCI_EM_UART_PORT_CONFLICT_INFO_size "‚d"
#define FUNC_UEM_CCCI_EM_UART_PORT_CONFLICT_INFO FUNC_UEM_CCCI_EM_UART_PORT_CONFLICT_INFO__enum,FUNC_UEM_CCCI_EM_UART_PORT_CONFLICT_INFO_size

// FUNC_UEM_SEND_MSG_TO_L4C
#define FUNC_UEM_SEND_MSG_TO_L4C_size NULL
#define FUNC_UEM_SEND_MSG_TO_L4C FUNC_UEM_SEND_MSG_TO_L4C__enum,FUNC_UEM_SEND_MSG_TO_L4C_size

// FUNC_UEM_SEND_MSG_TO_NVRAM
#define FUNC_UEM_SEND_MSG_TO_NVRAM_size NULL
#define FUNC_UEM_SEND_MSG_TO_NVRAM FUNC_UEM_SEND_MSG_TO_NVRAM__enum,FUNC_UEM_SEND_MSG_TO_NVRAM_size

// FUNC_UEM_SEND_MSG_TO_SAT
#define FUNC_UEM_SEND_MSG_TO_SAT_size NULL
#define FUNC_UEM_SEND_MSG_TO_SAT FUNC_UEM_SEND_MSG_TO_SAT__enum,FUNC_UEM_SEND_MSG_TO_SAT_size

// FUNC_UEM_SEND_MSG_TO_AUD
#define FUNC_UEM_SEND_MSG_TO_AUD_size NULL
#define FUNC_UEM_SEND_MSG_TO_AUD FUNC_UEM_SEND_MSG_TO_AUD__enum,FUNC_UEM_SEND_MSG_TO_AUD_size

// FUNC_UEM_SEND_MSG_TO_BMT
#define FUNC_UEM_SEND_MSG_TO_BMT_size NULL
#define FUNC_UEM_SEND_MSG_TO_BMT FUNC_UEM_SEND_MSG_TO_BMT__enum,FUNC_UEM_SEND_MSG_TO_BMT_size

// FUNC_UEM_SEND_MSG_TO_UEM
#define FUNC_UEM_SEND_MSG_TO_UEM_size NULL
#define FUNC_UEM_SEND_MSG_TO_UEM FUNC_UEM_SEND_MSG_TO_UEM__enum,FUNC_UEM_SEND_MSG_TO_UEM_size

// INFO_UEM_SPEECH_SET_MODE
#define INFO_UEM_SPEECH_SET_MODE_size "d"
#define INFO_UEM_SPEECH_SET_MODE INFO_UEM_SPEECH_SET_MODE__enum,INFO_UEM_SPEECH_SET_MODE_size

// WARNING_UEM_OUT_OF_RANGE
#define WARNING_UEM_OUT_OF_RANGE_size NULL
#define WARNING_UEM_OUT_OF_RANGE WARNING_UEM_OUT_OF_RANGE__enum,WARNING_UEM_OUT_OF_RANGE_size

// ERROR_UEM_NVRAM_DATA_LEN
#define ERROR_UEM_NVRAM_DATA_LEN_size "‚d"
#define ERROR_UEM_NVRAM_DATA_LEN ERROR_UEM_NVRAM_DATA_LEN__enum,ERROR_UEM_NVRAM_DATA_LEN_size

// FUNC_UEM_AT_EF_PORT_SETTING
#define FUNC_UEM_AT_EF_PORT_SETTING_size "ƒd"
#define FUNC_UEM_AT_EF_PORT_SETTING FUNC_UEM_AT_EF_PORT_SETTING__enum,FUNC_UEM_AT_EF_PORT_SETTING_size

// FUNC_UEM_AT_EF_PORT_SETTING_READ_CNF_HDLR
#define FUNC_UEM_AT_EF_PORT_SETTING_READ_CNF_HDLR_size "d"
#define FUNC_UEM_AT_EF_PORT_SETTING_READ_CNF_HDLR FUNC_UEM_AT_EF_PORT_SETTING_READ_CNF_HDLR__enum,FUNC_UEM_AT_EF_PORT_SETTING_READ_CNF_HDLR_size

// FUNC_UEM_AT_EF_PORT_SETTING_WRITE_CNF_HDLR
#define FUNC_UEM_AT_EF_PORT_SETTING_WRITE_CNF_HDLR_size "d"
#define FUNC_UEM_AT_EF_PORT_SETTING_WRITE_CNF_HDLR FUNC_UEM_AT_EF_PORT_SETTING_WRITE_CNF_HDLR__enum,FUNC_UEM_AT_EF_PORT_SETTING_WRITE_CNF_HDLR_size

// FUNC_UEM_PLAY_PATTERN
#define FUNC_UEM_PLAY_PATTERN_size "‚d"
#define FUNC_UEM_PLAY_PATTERN FUNC_UEM_PLAY_PATTERN__enum,FUNC_UEM_PLAY_PATTERN_size

// FUNC_UEM_VIB
#define FUNC_UEM_VIB_size NULL
#define FUNC_UEM_VIB FUNC_UEM_VIB__enum,FUNC_UEM_VIB_size

// FUNC_UEM_CHECK_VIB_PTN_ID
#define FUNC_UEM_CHECK_VIB_PTN_ID_size "ƒd"
#define FUNC_UEM_CHECK_VIB_PTN_ID FUNC_UEM_CHECK_VIB_PTN_ID__enum,FUNC_UEM_CHECK_VIB_PTN_ID_size

// FUNC_UEM_OTHER_VIB_PTN
#define FUNC_UEM_OTHER_VIB_PTN_size NULL
#define FUNC_UEM_OTHER_VIB_PTN FUNC_UEM_OTHER_VIB_PTN__enum,FUNC_UEM_OTHER_VIB_PTN_size

// FUNC_UEM_CONTINUE_PLAY_VIB
#define FUNC_UEM_CONTINUE_PLAY_VIB_size NULL
#define FUNC_UEM_CONTINUE_PLAY_VIB FUNC_UEM_CONTINUE_PLAY_VIB__enum,FUNC_UEM_CONTINUE_PLAY_VIB_size

// FUNC_UEM_STOP_PATTERN
#define FUNC_UEM_STOP_PATTERN_size "d"
#define FUNC_UEM_STOP_PATTERN FUNC_UEM_STOP_PATTERN__enum,FUNC_UEM_STOP_PATTERN_size

// FUNC_UEM_PLAY_VIB_PATTERN_CALLBACK
#define FUNC_UEM_PLAY_VIB_PATTERN_CALLBACK_size "d"
#define FUNC_UEM_PLAY_VIB_PATTERN_CALLBACK FUNC_UEM_PLAY_VIB_PATTERN_CALLBACK__enum,FUNC_UEM_PLAY_VIB_PATTERN_CALLBACK_size

// FUNC_UEM_PLAY_VIB_PATTERN
#define FUNC_UEM_PLAY_VIB_PATTERN_size NULL
#define FUNC_UEM_PLAY_VIB_PATTERN FUNC_UEM_PLAY_VIB_PATTERN__enum,FUNC_UEM_PLAY_VIB_PATTERN_size

// FUNC_UEM_SET_VIB_LEVEL
#define FUNC_UEM_SET_VIB_LEVEL_size "‚d"
#define FUNC_UEM_SET_VIB_LEVEL FUNC_UEM_SET_VIB_LEVEL__enum,FUNC_UEM_SET_VIB_LEVEL_size

// FUNC_UEM_SET_LED_BACKLIGHT_OFF
#define FUNC_UEM_SET_LED_BACKLIGHT_OFF_size NULL
#define FUNC_UEM_SET_LED_BACKLIGHT_OFF FUNC_UEM_SET_LED_BACKLIGHT_OFF__enum,FUNC_UEM_SET_LED_BACKLIGHT_OFF_size

// FUNC_UEM_PROCESSING
#define FUNC_UEM_PROCESSING_size NULL
#define FUNC_UEM_PROCESSING FUNC_UEM_PROCESSING__enum,FUNC_UEM_PROCESSING_size

// FUNC_UEM_VIB_TIMER_DUR
#define FUNC_UEM_VIB_TIMER_DUR_size "d"
#define FUNC_UEM_VIB_TIMER_DUR FUNC_UEM_VIB_TIMER_DUR__enum,FUNC_UEM_VIB_TIMER_DUR_size

// FUNC_UEM_STOP_LED_BACKLIGHT_OFF
#define FUNC_UEM_STOP_LED_BACKLIGHT_OFF_size "d"
#define FUNC_UEM_STOP_LED_BACKLIGHT_OFF FUNC_UEM_STOP_LED_BACKLIGHT_OFF__enum,FUNC_UEM_STOP_LED_BACKLIGHT_OFF_size

// FUNC_UEM_START_LED_BACKLIGHT_OFF
#define FUNC_UEM_START_LED_BACKLIGHT_OFF_size NULL
#define FUNC_UEM_START_LED_BACKLIGHT_OFF FUNC_UEM_START_LED_BACKLIGHT_OFF__enum,FUNC_UEM_START_LED_BACKLIGHT_OFF_size

// FUNC_UEM_PROCESS_LED_BACKLIGHT_OFF
#define FUNC_UEM_PROCESS_LED_BACKLIGHT_OFF_size "d"
#define FUNC_UEM_PROCESS_LED_BACKLIGHT_OFF FUNC_UEM_PROCESS_LED_BACKLIGHT_OFF__enum,FUNC_UEM_PROCESS_LED_BACKLIGHT_OFF_size

// FUNC_UEM_LED_BACKLIGHT_OFF_TIMER_HDLR
#define FUNC_UEM_LED_BACKLIGHT_OFF_TIMER_HDLR_size "d"
#define FUNC_UEM_LED_BACKLIGHT_OFF_TIMER_HDLR FUNC_UEM_LED_BACKLIGHT_OFF_TIMER_HDLR__enum,FUNC_UEM_LED_BACKLIGHT_OFF_TIMER_HDLR_size

// FUNC_UEM_ADC_MEASURE_DONE_CNF_HDLR
#define FUNC_UEM_ADC_MEASURE_DONE_CNF_HDLR_size "d"
#define FUNC_UEM_ADC_MEASURE_DONE_CNF_HDLR FUNC_UEM_ADC_MEASURE_DONE_CNF_HDLR__enum,FUNC_UEM_ADC_MEASURE_DONE_CNF_HDLR_size

// FUNC_UEM_CUR_VOL
#define FUNC_UEM_CUR_VOL_size "d"
#define FUNC_UEM_CUR_VOL FUNC_UEM_CUR_VOL__enum,FUNC_UEM_CUR_VOL_size

// FUNC_UEM_CUST_SET_LEVEL
#define FUNC_UEM_CUST_SET_LEVEL_size "‚d"
#define FUNC_UEM_CUST_SET_LEVEL FUNC_UEM_CUST_SET_LEVEL__enum,FUNC_UEM_CUST_SET_LEVEL_size


#endif // UEM_TRC_GEN.H
