#ifndef _USB_TRC_GEN_H_
#define _USB_TRC_GEN_H_

// USB_RESET_TIMES
#define USB_RESET_TIMES_size "d"
#define USB_RESET_TIMES USB_RESET_TIMES__enum,USB_RESET_TIMES_size

// USB_IS_SUSPEND
#define USB_IS_SUSPEND_size NULL
#define USB_IS_SUSPEND USB_IS_SUSPEND__enum,USB_IS_SUSPEND_size

// USB_IS_RESUME
#define USB_IS_RESUME_size NULL
#define USB_IS_RESUME USB_IS_RESUME__enum,USB_IS_RESUME_size

// USB_IS_DISCONN
#define USB_IS_DISCONN_size NULL
#define USB_IS_DISCONN USB_IS_DISCONN__enum,USB_IS_DISCONN_size

// USB_IS_CONFIGURE
#define USB_IS_CONFIGURE_size NULL
#define USB_IS_CONFIGURE USB_IS_CONFIGURE__enum,USB_IS_CONFIGURE_size

// USB_CONFIG_NUM
#define USB_CONFIG_NUM_size "‚d"
#define USB_CONFIG_NUM USB_CONFIG_NUM__enum,USB_CONFIG_NUM_size

// USB_CURRENT_TABLE
#define USB_CURRENT_TABLE_size "d"
#define USB_CURRENT_TABLE USB_CURRENT_TABLE__enum,USB_CURRENT_TABLE_size

// USB_EP0_SetFeature
#define USB_EP0_SetFeature_size NULL
#define USB_EP0_SetFeature USB_EP0_SetFeature__enum,USB_EP0_SetFeature_size

// USB_EP0_Clear_Stall
#define USB_EP0_Clear_Stall_size NULL
#define USB_EP0_Clear_Stall USB_EP0_Clear_Stall__enum,USB_EP0_Clear_Stall_size

// USB_EP0_SET_ADDR
#define USB_EP0_SET_ADDR_size NULL
#define USB_EP0_SET_ADDR USB_EP0_SET_ADDR__enum,USB_EP0_SET_ADDR_size

// USB_EP0_GET_DESCRIPT
#define USB_EP0_GET_DESCRIPT_size NULL
#define USB_EP0_GET_DESCRIPT USB_EP0_GET_DESCRIPT__enum,USB_EP0_GET_DESCRIPT_size

// USB_EP0_SET_CONFIG
#define USB_EP0_SET_CONFIG_size NULL
#define USB_EP0_SET_CONFIG USB_EP0_SET_CONFIG__enum,USB_EP0_SET_CONFIG_size

// USB_EP0_GET_CONFIG
#define USB_EP0_GET_CONFIG_size NULL
#define USB_EP0_GET_CONFIG USB_EP0_GET_CONFIG__enum,USB_EP0_GET_CONFIG_size

// USB_EP0_SET_INTER
#define USB_EP0_SET_INTER_size NULL
#define USB_EP0_SET_INTER USB_EP0_SET_INTER__enum,USB_EP0_SET_INTER_size

// USB_EP0_GET_INTER
#define USB_EP0_GET_INTER_size NULL
#define USB_EP0_GET_INTER USB_EP0_GET_INTER__enum,USB_EP0_GET_INTER_size

// USB_EP0_GET_STAT
#define USB_EP0_GET_STAT_size NULL
#define USB_EP0_GET_STAT USB_EP0_GET_STAT__enum,USB_EP0_GET_STAT_size

// USB_EP0_UNSUPPORT
#define USB_EP0_UNSUPPORT_size NULL
#define USB_EP0_UNSUPPORT USB_EP0_UNSUPPORT__enum,USB_EP0_UNSUPPORT_size

// USB_PLUG_OUT
#define USB_PLUG_OUT_size NULL
#define USB_PLUG_OUT USB_PLUG_OUT__enum,USB_PLUG_OUT_size

// USB_GET_MEMORY_ADDR
#define USB_GET_MEMORY_ADDR_size "‚d"
#define USB_GET_MEMORY_ADDR USB_GET_MEMORY_ADDR__enum,USB_GET_MEMORY_ADDR_size

// USB_HISR_State
#define USB_HISR_State_size "„d"
#define USB_HISR_State USB_HISR_State__enum,USB_HISR_State_size

// USB_EP_UNEXPECTED_TX_HISR
#define USB_EP_UNEXPECTED_TX_HISR_size "‚d"
#define USB_EP_UNEXPECTED_TX_HISR USB_EP_UNEXPECTED_TX_HISR__enum,USB_EP_UNEXPECTED_TX_HISR_size

// USB_EP_UNEXPECTED_RX_HISR
#define USB_EP_UNEXPECTED_RX_HISR_size "‚d"
#define USB_EP_UNEXPECTED_RX_HISR USB_EP_UNEXPECTED_RX_HISR__enum,USB_EP_UNEXPECTED_RX_HISR_size

// USB_DRV_IS_ERROR_1
#define USB_DRV_IS_ERROR_1_size "‚d"
#define USB_DRV_IS_ERROR_1 USB_DRV_IS_ERROR_1__enum,USB_DRV_IS_ERROR_1_size

// USB_DRV_IS_ERROR_2
#define USB_DRV_IS_ERROR_2_size NULL
#define USB_DRV_IS_ERROR_2 USB_DRV_IS_ERROR_2__enum,USB_DRV_IS_ERROR_2_size

// USB_DRV_IS_ERROR_3
#define USB_DRV_IS_ERROR_3_size NULL
#define USB_DRV_IS_ERROR_3 USB_DRV_IS_ERROR_3__enum,USB_DRV_IS_ERROR_3_size

// USB_Register
#define USB_Register_size "‚d"
#define USB_Register USB_Register__enum,USB_Register_size

// USB_DRV_RX_ERROR
#define USB_DRV_RX_ERROR_size "‚d"
#define USB_DRV_RX_ERROR USB_DRV_RX_ERROR__enum,USB_DRV_RX_ERROR_size

// USBACM_DMA_Setup
#define USBACM_DMA_Setup_size "‚d"
#define USBACM_DMA_Setup USBACM_DMA_Setup__enum,USBACM_DMA_Setup_size

// USBACM_DMA_Running
#define USBACM_DMA_Running_size "‚d"
#define USBACM_DMA_Running USBACM_DMA_Running__enum,USBACM_DMA_Running_size

// USB_RESET_Data_Toggle
#define USB_RESET_Data_Toggle_size "d"
#define USB_RESET_Data_Toggle USB_RESET_Data_Toggle__enum,USB_RESET_Data_Toggle_size

// USB_HW_State
#define USB_HW_State_size "‚d"
#define USB_HW_State USB_HW_State__enum,USB_HW_State_size

// USB_TX_DEBUG
#define USB_TX_DEBUG_size "‚d"
#define USB_TX_DEBUG USB_TX_DEBUG__enum,USB_TX_DEBUG_size

// USB_RX_DEBUG
#define USB_RX_DEBUG_size "‚d"
#define USB_RX_DEBUG USB_RX_DEBUG__enum,USB_RX_DEBUG_size

// USB_DMA_DEBUG
#define USB_DMA_DEBUG_size "‚d"
#define USB_DMA_DEBUG USB_DMA_DEBUG__enum,USB_DMA_DEBUG_size

// USB_REMOTE_WAKEUP
#define USB_REMOTE_WAKEUP_size "d"
#define USB_REMOTE_WAKEUP USB_REMOTE_WAKEUP__enum,USB_REMOTE_WAKEUP_size

// USB_DMA_HW_Intr
#define USB_DMA_HW_Intr_size "d"
#define USB_DMA_HW_Intr USB_DMA_HW_Intr__enum,USB_DMA_HW_Intr_size

// USBACM_DMA_CALLBACK
#define USBACM_DMA_CALLBACK_size "‚d"
#define USBACM_DMA_CALLBACK USBACM_DMA_CALLBACK__enum,USBACM_DMA_CALLBACK_size

// USBACM_DMA_Setup2
#define USBACM_DMA_Setup2_size "d"
#define USBACM_DMA_Setup2 USBACM_DMA_Setup2__enum,USBACM_DMA_Setup2_size

// USBACM_DMA_Setup0
#define USBACM_DMA_Setup0_size "d"
#define USBACM_DMA_Setup0 USBACM_DMA_Setup0__enum,USBACM_DMA_Setup0_size

// USB_UTMI_SIGNAL
#define USB_UTMI_SIGNAL_size "„d"
#define USB_UTMI_SIGNAL USB_UTMI_SIGNAL__enum,USB_UTMI_SIGNAL_size

// USB_TXCSR_SET2
#define USB_TXCSR_SET2_size NULL
#define USB_TXCSR_SET2 USB_TXCSR_SET2__enum,USB_TXCSR_SET2_size

// USB_TXCSR_SET
#define USB_TXCSR_SET_size NULL
#define USB_TXCSR_SET USB_TXCSR_SET__enum,USB_TXCSR_SET_size

// USBACM_CTRL_DCD
#define USBACM_CTRL_DCD_size "d"
#define USBACM_CTRL_DCD USBACM_CTRL_DCD__enum,USBACM_CTRL_DCD_size

// USBACM_CTRL_BREAK
#define USBACM_CTRL_BREAK_size "d"
#define USBACM_CTRL_BREAK USBACM_CTRL_BREAK__enum,USBACM_CTRL_BREAK_size

// USBACM_SET_BAUDRATE
#define USBACM_SET_BAUDRATE_size "d"
#define USBACM_SET_BAUDRATE USBACM_SET_BAUDRATE__enum,USBACM_SET_BAUDRATE_size

// USBACM_SET_AUTO_BAUDRATE
#define USBACM_SET_AUTO_BAUDRATE_size "d"
#define USBACM_SET_AUTO_BAUDRATE USBACM_SET_AUTO_BAUDRATE__enum,USBACM_SET_AUTO_BAUDRATE_size

// USBACM_CTRL_RI
#define USBACM_CTRL_RI_size "d"
#define USBACM_CTRL_RI USBACM_CTRL_RI__enum,USBACM_CTRL_RI_size

// USBACM_CTRL_DTR
#define USBACM_CTRL_DTR_size "d"
#define USBACM_CTRL_DTR USBACM_CTRL_DTR__enum,USBACM_CTRL_DTR_size

// USBACM_THRESHOLD_ON
#define USBACM_THRESHOLD_ON_size "d"
#define USBACM_THRESHOLD_ON USBACM_THRESHOLD_ON__enum,USBACM_THRESHOLD_ON_size

// USBACM_THRESHOLD_OFF
#define USBACM_THRESHOLD_OFF_size "d"
#define USBACM_THRESHOLD_OFF USBACM_THRESHOLD_OFF__enum,USBACM_THRESHOLD_OFF_size

// USBACM_PC_SENT
#define USBACM_PC_SENT_size "‚d"
#define USBACM_PC_SENT USBACM_PC_SENT__enum,USBACM_PC_SENT_size

// USBACM_RESET_READY_TO_READ_FLAG
#define USBACM_RESET_READY_TO_READ_FLAG_size "d"
#define USBACM_RESET_READY_TO_READ_FLAG USBACM_RESET_READY_TO_READ_FLAG__enum,USBACM_RESET_READY_TO_READ_FLAG_size

// USBACM_INIT_READY_TO_READ_FLAG
#define USBACM_INIT_READY_TO_READ_FLAG_size "d"
#define USBACM_INIT_READY_TO_READ_FLAG USBACM_INIT_READY_TO_READ_FLAG__enum,USBACM_INIT_READY_TO_READ_FLAG_size

// USBACM_OPEN_READY_TO_READ_FLAG
#define USBACM_OPEN_READY_TO_READ_FLAG_size "‚d"
#define USBACM_OPEN_READY_TO_READ_FLAG USBACM_OPEN_READY_TO_READ_FLAG__enum,USBACM_OPEN_READY_TO_READ_FLAG_size

// USBACM_CLEAR_RX_BUF_READY_TO_READ_FLAG
#define USBACM_CLEAR_RX_BUF_READY_TO_READ_FLAG_size "‚d"
#define USBACM_CLEAR_RX_BUF_READY_TO_READ_FLAG USBACM_CLEAR_RX_BUF_READY_TO_READ_FLAG__enum,USBACM_CLEAR_RX_BUF_READY_TO_READ_FLAG_size

// USBACM_CLEAR_TX_BUF_READY_TO_READ_FLAG
#define USBACM_CLEAR_TX_BUF_READY_TO_READ_FLAG_size "‚d"
#define USBACM_CLEAR_TX_BUF_READY_TO_READ_FLAG USBACM_CLEAR_TX_BUF_READY_TO_READ_FLAG__enum,USBACM_CLEAR_TX_BUF_READY_TO_READ_FLAG_size

// USBACM_INTR
#define USBACM_INTR_size "‚d"
#define USBACM_INTR USBACM_INTR__enum,USBACM_INTR_size

// USBACM_CLEAR_TX_ISR_BUF
#define USBACM_CLEAR_TX_ISR_BUF_size "d"
#define USBACM_CLEAR_TX_ISR_BUF USBACM_CLEAR_TX_ISR_BUF__enum,USBACM_CLEAR_TX_ISR_BUF_size

// USBACM_OPEN
#define USBACM_OPEN_size "d"
#define USBACM_OPEN USBACM_OPEN__enum,USBACM_OPEN_size

// USBACM_CLOSE
#define USBACM_CLOSE_size "‚d"
#define USBACM_CLOSE USBACM_CLOSE__enum,USBACM_CLOSE_size

// USBACM_SET_OWNER
#define USBACM_SET_OWNER_size "‚d"
#define USBACM_SET_OWNER USBACM_SET_OWNER__enum,USBACM_SET_OWNER_size

// USBACM_PUT_BYTES
#define USBACM_PUT_BYTES_size "‚d"
#define USBACM_PUT_BYTES USBACM_PUT_BYTES__enum,USBACM_PUT_BYTES_size

// USBACM_PUT_BYTES_FAIL
#define USBACM_PUT_BYTES_FAIL_size NULL
#define USBACM_PUT_BYTES_FAIL USBACM_PUT_BYTES_FAIL__enum,USBACM_PUT_BYTES_FAIL_size

// USBACM_PUT_BYTES_BUF_FULL
#define USBACM_PUT_BYTES_BUF_FULL_size "‚d"
#define USBACM_PUT_BYTES_BUF_FULL USBACM_PUT_BYTES_BUF_FULL__enum,USBACM_PUT_BYTES_BUF_FULL_size

// USBACM_CLEAR_RX_BUF
#define USBACM_CLEAR_RX_BUF_size "d"
#define USBACM_CLEAR_RX_BUF USBACM_CLEAR_RX_BUF__enum,USBACM_CLEAR_RX_BUF_size

// USBACM_GET_BYTES_BUF_EMPTY
#define USBACM_GET_BYTES_BUF_EMPTY_size "‚d"
#define USBACM_GET_BYTES_BUF_EMPTY USBACM_GET_BYTES_BUF_EMPTY__enum,USBACM_GET_BYTES_BUF_EMPTY_size

// USBACM_FAIL_NOT_UNMASK
#define USBACM_FAIL_NOT_UNMASK_size "d"
#define USBACM_FAIL_NOT_UNMASK USBACM_FAIL_NOT_UNMASK__enum,USBACM_FAIL_NOT_UNMASK_size

// USBACM_GET_BYTES
#define USBACM_GET_BYTES_size "‚d"
#define USBACM_GET_BYTES USBACM_GET_BYTES__enum,USBACM_GET_BYTES_size

// USBACM_CLEAR_TX_BUF
#define USBACM_CLEAR_TX_BUF_size "d"
#define USBACM_CLEAR_TX_BUF USBACM_CLEAR_TX_BUF__enum,USBACM_CLEAR_TX_BUF_size

// USBACM_CLEAR_RDY_W
#define USBACM_CLEAR_RDY_W_size "‚d"
#define USBACM_CLEAR_RDY_W USBACM_CLEAR_RDY_W__enum,USBACM_CLEAR_RDY_W_size

// USBACM_EP0_COMMAND
#define USBACM_EP0_COMMAND_size "‚d"
#define USBACM_EP0_COMMAND USBACM_EP0_COMMAND__enum,USBACM_EP0_COMMAND_size

// USBACM_SET_DMA_LIMITER
#define USBACM_SET_DMA_LIMITER_size "ƒd"
#define USBACM_SET_DMA_LIMITER USBACM_SET_DMA_LIMITER__enum,USBACM_SET_DMA_LIMITER_size

// USBACM_CLEAR_DMA_LIMITER
#define USBACM_CLEAR_DMA_LIMITER_size "‚d"
#define USBACM_CLEAR_DMA_LIMITER USBACM_CLEAR_DMA_LIMITER__enum,USBACM_CLEAR_DMA_LIMITER_size

// USBIMAGE_GET
#define USBIMAGE_GET_size "d"
#define USBIMAGE_GET USBIMAGE_GET__enum,USBIMAGE_GET_size

// USBIMAGE_ERROR_CMDS
#define USBIMAGE_ERROR_CMDS_size "d"
#define USBIMAGE_ERROR_CMDS USBIMAGE_ERROR_CMDS__enum,USBIMAGE_ERROR_CMDS_size

// USBMS_RX_WRONG_CBW_LENGTH
#define USBMS_RX_WRONG_CBW_LENGTH_size "d"
#define USBMS_RX_WRONG_CBW_LENGTH USBMS_RX_WRONG_CBW_LENGTH__enum,USBMS_RX_WRONG_CBW_LENGTH_size

// USBMS_RESET
#define USBMS_RESET_size NULL
#define USBMS_RESET USBMS_RESET__enum,USBMS_RESET_size

// USBMS_ERROR_CMD
#define USBMS_ERROR_CMD_size "d"
#define USBMS_ERROR_CMD USBMS_ERROR_CMD__enum,USBMS_ERROR_CMD_size

// USBMS_LOCKFAT_FAIL
#define USBMS_LOCKFAT_FAIL_size NULL
#define USBMS_LOCKFAT_FAIL USBMS_LOCKFAT_FAIL__enum,USBMS_LOCKFAT_FAIL_size

// USBVIDEO_INIT
#define USBVIDEO_INIT_size NULL
#define USBVIDEO_INIT USBVIDEO_INIT__enum,USBVIDEO_INIT_size

// USBVIDEO_RELEASE
#define USBVIDEO_RELEASE_size NULL
#define USBVIDEO_RELEASE USBVIDEO_RELEASE__enum,USBVIDEO_RELEASE_size

// USBVIDEO_VC_ERROR_CMD
#define USBVIDEO_VC_ERROR_CMD_size "d"
#define USBVIDEO_VC_ERROR_CMD USBVIDEO_VC_ERROR_CMD__enum,USBVIDEO_VC_ERROR_CMD_size

// USBVIDEO_VS_ERROR_CMD
#define USBVIDEO_VS_ERROR_CMD_size "d"
#define USBVIDEO_VS_ERROR_CMD USBVIDEO_VS_ERROR_CMD__enum,USBVIDEO_VS_ERROR_CMD_size

// USBVIDEO_STILL_PROBE_NONE
#define USBVIDEO_STILL_PROBE_NONE_size NULL
#define USBVIDEO_STILL_PROBE_NONE USBVIDEO_STILL_PROBE_NONE__enum,USBVIDEO_STILL_PROBE_NONE_size

// USBVIDEO_SET_COMMIT_VIDEO_STATE
#define USBVIDEO_SET_COMMIT_VIDEO_STATE_size "d"
#define USBVIDEO_SET_COMMIT_VIDEO_STATE USBVIDEO_SET_COMMIT_VIDEO_STATE__enum,USBVIDEO_SET_COMMIT_VIDEO_STATE_size

// USBVIDEO_SET_PROB_CONTROL_ERROR
#define USBVIDEO_SET_PROB_CONTROL_ERROR_size "‚d"
#define USBVIDEO_SET_PROB_CONTROL_ERROR USBVIDEO_SET_PROB_CONTROL_ERROR__enum,USBVIDEO_SET_PROB_CONTROL_ERROR_size

// USBVIDEO_STILL_COMMIT_DONE
#define USBVIDEO_STILL_COMMIT_DONE_size "d"
#define USBVIDEO_STILL_COMMIT_DONE USBVIDEO_STILL_COMMIT_DONE__enum,USBVIDEO_STILL_COMMIT_DONE_size

// USBVIDEO_SET_STILL_PROB_CONTROL_ERROR
#define USBVIDEO_SET_STILL_PROB_CONTROL_ERROR_size "‚d"
#define USBVIDEO_SET_STILL_PROB_CONTROL_ERROR USBVIDEO_SET_STILL_PROB_CONTROL_ERROR__enum,USBVIDEO_SET_STILL_PROB_CONTROL_ERROR_size

// USBVIDEO_GET_BUFFER
#define USBVIDEO_GET_BUFFER_size "ƒd"
#define USBVIDEO_GET_BUFFER USBVIDEO_GET_BUFFER__enum,USBVIDEO_GET_BUFFER_size

// USBVIDEO_COMPLETE_BUFFER
#define USBVIDEO_COMPLETE_BUFFER_size "ƒd"
#define USBVIDEO_COMPLETE_BUFFER USBVIDEO_COMPLETE_BUFFER__enum,USBVIDEO_COMPLETE_BUFFER_size

// USBVIDEO_DMA_DONE
#define USBVIDEO_DMA_DONE_size "ƒd"
#define USBVIDEO_DMA_DONE USBVIDEO_DMA_DONE__enum,USBVIDEO_DMA_DONE_size

// USBVIDEO_STILL_ERROR
#define USBVIDEO_STILL_ERROR_size NULL
#define USBVIDEO_STILL_ERROR USBVIDEO_STILL_ERROR__enum,USBVIDEO_STILL_ERROR_size

// USBVIDEO_DCM_FREED
#define USBVIDEO_DCM_FREED_size NULL
#define USBVIDEO_DCM_FREED USBVIDEO_DCM_FREED__enum,USBVIDEO_DCM_FREED_size

// USB_HCD_BABBLE_INTR
#define USB_HCD_BABBLE_INTR_size NULL
#define USB_HCD_BABBLE_INTR USB_HCD_BABBLE_INTR__enum,USB_HCD_BABBLE_INTR_size

// USB_HCD_CONN_INTR
#define USB_HCD_CONN_INTR_size NULL
#define USB_HCD_CONN_INTR USB_HCD_CONN_INTR__enum,USB_HCD_CONN_INTR_size

// USB_HCD_DISCONN_INTR
#define USB_HCD_DISCONN_INTR_size NULL
#define USB_HCD_DISCONN_INTR USB_HCD_DISCONN_INTR__enum,USB_HCD_DISCONN_INTR_size

// USB_HCD_CONN_AND_DISCONN_INTR
#define USB_HCD_CONN_AND_DISCONN_INTR_size NULL
#define USB_HCD_CONN_AND_DISCONN_INTR USB_HCD_CONN_AND_DISCONN_INTR__enum,USB_HCD_CONN_AND_DISCONN_INTR_size

// USB_HCD_TX_EPN_TIMEOUT
#define USB_HCD_TX_EPN_TIMEOUT_size "d"
#define USB_HCD_TX_EPN_TIMEOUT USB_HCD_TX_EPN_TIMEOUT__enum,USB_HCD_TX_EPN_TIMEOUT_size

// USB_HCD_RX_EPN_TIMEOUT
#define USB_HCD_RX_EPN_TIMEOUT_size "d"
#define USB_HCD_RX_EPN_TIMEOUT USB_HCD_RX_EPN_TIMEOUT__enum,USB_HCD_RX_EPN_TIMEOUT_size

// USB_HCD_TX_EPN_ERROR
#define USB_HCD_TX_EPN_ERROR_size "d"
#define USB_HCD_TX_EPN_ERROR USB_HCD_TX_EPN_ERROR__enum,USB_HCD_TX_EPN_ERROR_size

// USB_HCD_RX_EPN_ERROR
#define USB_HCD_RX_EPN_ERROR_size "d"
#define USB_HCD_RX_EPN_ERROR USB_HCD_RX_EPN_ERROR__enum,USB_HCD_RX_EPN_ERROR_size

// USB_HCD_TX_EPN_STALL
#define USB_HCD_TX_EPN_STALL_size "d"
#define USB_HCD_TX_EPN_STALL USB_HCD_TX_EPN_STALL__enum,USB_HCD_TX_EPN_STALL_size

// USB_HCD_RX_EPN_STALL
#define USB_HCD_RX_EPN_STALL_size "d"
#define USB_HCD_RX_EPN_STALL USB_HCD_RX_EPN_STALL__enum,USB_HCD_RX_EPN_STALL_size

// USB_HCD_RX_EPN_PID_ERROR
#define USB_HCD_RX_EPN_PID_ERROR_size "d"
#define USB_HCD_RX_EPN_PID_ERROR USB_HCD_RX_EPN_PID_ERROR__enum,USB_HCD_RX_EPN_PID_ERROR_size

// USB_HCD_EP0
#define USB_HCD_EP0_size "‚d"
#define USB_HCD_EP0 USB_HCD_EP0__enum,USB_HCD_EP0_size

// USB_HCD_EP0_RX
#define USB_HCD_EP0_RX_size "ƒd"
#define USB_HCD_EP0_RX USB_HCD_EP0_RX__enum,USB_HCD_EP0_RX_size

// USB_HCD_RX_DMA_TIMEOUT
#define USB_HCD_RX_DMA_TIMEOUT_size NULL
#define USB_HCD_RX_DMA_TIMEOUT USB_HCD_RX_DMA_TIMEOUT__enum,USB_HCD_RX_DMA_TIMEOUT_size

// USB_HCD_TEST_UN_SUPPORT
#define USB_HCD_TEST_UN_SUPPORT_size NULL
#define USB_HCD_TEST_UN_SUPPORT USB_HCD_TEST_UN_SUPPORT__enum,USB_HCD_TEST_UN_SUPPORT_size

// USB_HCD_RESPONSE_ERROR
#define USB_HCD_RESPONSE_ERROR_size NULL
#define USB_HCD_RESPONSE_ERROR USB_HCD_RESPONSE_ERROR__enum,USB_HCD_RESPONSE_ERROR_size

// USB_HCD_ENUM_FAIL
#define USB_HCD_ENUM_FAIL_size NULL
#define USB_HCD_ENUM_FAIL USB_HCD_ENUM_FAIL__enum,USB_HCD_ENUM_FAIL_size

// USB_HCD_COMMAND_FAIL
#define USB_HCD_COMMAND_FAIL_size NULL
#define USB_HCD_COMMAND_FAIL USB_HCD_COMMAND_FAIL__enum,USB_HCD_COMMAND_FAIL_size

// USB_HCD_UN_SUPPORT
#define USB_HCD_UN_SUPPORT_size NULL
#define USB_HCD_UN_SUPPORT USB_HCD_UN_SUPPORT__enum,USB_HCD_UN_SUPPORT_size

// USB_OTG_SESSION_REQUEST
#define USB_OTG_SESSION_REQUEST_size "„d"
#define USB_OTG_SESSION_REQUEST USB_OTG_SESSION_REQUEST__enum,USB_OTG_SESSION_REQUEST_size

// USB_OTG_VBUS_FALL_DOWN
#define USB_OTG_VBUS_FALL_DOWN_size NULL
#define USB_OTG_VBUS_FALL_DOWN USB_OTG_VBUS_FALL_DOWN__enum,USB_OTG_VBUS_FALL_DOWN_size

// USB_OTG_DMA_STATUS
#define USB_OTG_DMA_STATUS_size "„d"
#define USB_OTG_DMA_STATUS USB_OTG_DMA_STATUS__enum,USB_OTG_DMA_STATUS_size

// USB_HOST_MS_STATE_START_FAIL
#define USB_HOST_MS_STATE_START_FAIL_size NULL
#define USB_HOST_MS_STATE_START_FAIL USB_HOST_MS_STATE_START_FAIL__enum,USB_HOST_MS_STATE_START_FAIL_size

// USB_HOST_MS_STATE_MAIN_FAIL
#define USB_HOST_MS_STATE_MAIN_FAIL_size NULL
#define USB_HOST_MS_STATE_MAIN_FAIL USB_HOST_MS_STATE_MAIN_FAIL__enum,USB_HOST_MS_STATE_MAIN_FAIL_size

// USB_HOST_MS_REQUEST_SENSE_OK
#define USB_HOST_MS_REQUEST_SENSE_OK_size "d"
#define USB_HOST_MS_REQUEST_SENSE_OK USB_HOST_MS_REQUEST_SENSE_OK__enum,USB_HOST_MS_REQUEST_SENSE_OK_size

// USB_HOST_MS_REQUEST_SENSE_MEDIA_CHANGE
#define USB_HOST_MS_REQUEST_SENSE_MEDIA_CHANGE_size "d"
#define USB_HOST_MS_REQUEST_SENSE_MEDIA_CHANGE USB_HOST_MS_REQUEST_SENSE_MEDIA_CHANGE__enum,USB_HOST_MS_REQUEST_SENSE_MEDIA_CHANGE_size

// USB_HOST_MS_REQUEST_SENSE_ABSENT
#define USB_HOST_MS_REQUEST_SENSE_ABSENT_size "d"
#define USB_HOST_MS_REQUEST_SENSE_ABSENT USB_HOST_MS_REQUEST_SENSE_ABSENT__enum,USB_HOST_MS_REQUEST_SENSE_ABSENT_size

// USB_HOST_MS_REQUEST_SENSE_ERROR
#define USB_HOST_MS_REQUEST_SENSE_ERROR_size "d"
#define USB_HOST_MS_REQUEST_SENSE_ERROR USB_HOST_MS_REQUEST_SENSE_ERROR__enum,USB_HOST_MS_REQUEST_SENSE_ERROR_size

// USB_HOST_MS_READ_CAPACITY_FAIL
#define USB_HOST_MS_READ_CAPACITY_FAIL_size "ƒd"
#define USB_HOST_MS_READ_CAPACITY_FAIL USB_HOST_MS_READ_CAPACITY_FAIL__enum,USB_HOST_MS_READ_CAPACITY_FAIL_size

// USB_HOST_MS_READ_CAPACITY_OK
#define USB_HOST_MS_READ_CAPACITY_OK_size "ƒd"
#define USB_HOST_MS_READ_CAPACITY_OK USB_HOST_MS_READ_CAPACITY_OK__enum,USB_HOST_MS_READ_CAPACITY_OK_size

// USB_HOST_MS_CHECK_MEDIA_STATE
#define USB_HOST_MS_CHECK_MEDIA_STATE_size "d"
#define USB_HOST_MS_CHECK_MEDIA_STATE USB_HOST_MS_CHECK_MEDIA_STATE__enum,USB_HOST_MS_CHECK_MEDIA_STATE_size

// USB_HOST_MS_MEDIA_STATE_CHANGE
#define USB_HOST_MS_MEDIA_STATE_CHANGE_size "d"
#define USB_HOST_MS_MEDIA_STATE_CHANGE USB_HOST_MS_MEDIA_STATE_CHANGE__enum,USB_HOST_MS_MEDIA_STATE_CHANGE_size

// USB_HOST_MS_READ_FAIL
#define USB_HOST_MS_READ_FAIL_size "d"
#define USB_HOST_MS_READ_FAIL USB_HOST_MS_READ_FAIL__enum,USB_HOST_MS_READ_FAIL_size

// USB_HOST_MS_WRITE_FAIL
#define USB_HOST_MS_WRITE_FAIL_size "d"
#define USB_HOST_MS_WRITE_FAIL USB_HOST_MS_WRITE_FAIL__enum,USB_HOST_MS_WRITE_FAIL_size

// USB_HOST_MS_READ_SECTOR_FAIL
#define USB_HOST_MS_READ_SECTOR_FAIL_size "„d"
#define USB_HOST_MS_READ_SECTOR_FAIL USB_HOST_MS_READ_SECTOR_FAIL__enum,USB_HOST_MS_READ_SECTOR_FAIL_size

// USB_HOST_MS_READ_SECTOR_OK
#define USB_HOST_MS_READ_SECTOR_OK_size "ƒd"
#define USB_HOST_MS_READ_SECTOR_OK USB_HOST_MS_READ_SECTOR_OK__enum,USB_HOST_MS_READ_SECTOR_OK_size

// USB_HOST_MS_WRITE_SECTOR_FAIL
#define USB_HOST_MS_WRITE_SECTOR_FAIL_size "„d"
#define USB_HOST_MS_WRITE_SECTOR_FAIL USB_HOST_MS_WRITE_SECTOR_FAIL__enum,USB_HOST_MS_WRITE_SECTOR_FAIL_size

// USB_HOST_MS_WRITE_SECTOR_OK
#define USB_HOST_MS_WRITE_SECTOR_OK_size "ƒd"
#define USB_HOST_MS_WRITE_SECTOR_OK USB_HOST_MS_WRITE_SECTOR_OK__enum,USB_HOST_MS_WRITE_SECTOR_OK_size

// USB_HOST_MS_READ_SECTOR_TIMEOUT_FAIL
#define USB_HOST_MS_READ_SECTOR_TIMEOUT_FAIL_size "d"
#define USB_HOST_MS_READ_SECTOR_TIMEOUT_FAIL USB_HOST_MS_READ_SECTOR_TIMEOUT_FAIL__enum,USB_HOST_MS_READ_SECTOR_TIMEOUT_FAIL_size

// USB_HOST_MS_WRITE_SECTOR_TIMEOUT_FAIL
#define USB_HOST_MS_WRITE_SECTOR_TIMEOUT_FAIL_size "d"
#define USB_HOST_MS_WRITE_SECTOR_TIMEOUT_FAIL USB_HOST_MS_WRITE_SECTOR_TIMEOUT_FAIL__enum,USB_HOST_MS_WRITE_SECTOR_TIMEOUT_FAIL_size

// USB_HOST_ICCD_POWER_ON_OK
#define USB_HOST_ICCD_POWER_ON_OK_size NULL
#define USB_HOST_ICCD_POWER_ON_OK USB_HOST_ICCD_POWER_ON_OK__enum,USB_HOST_ICCD_POWER_ON_OK_size

// USB_HOST_ICCD_POWER_ON_Fail
#define USB_HOST_ICCD_POWER_ON_Fail_size NULL
#define USB_HOST_ICCD_POWER_ON_Fail USB_HOST_ICCD_POWER_ON_Fail__enum,USB_HOST_ICCD_POWER_ON_Fail_size

// USB_HOST_ICCD_POWER_OFF_OK
#define USB_HOST_ICCD_POWER_OFF_OK_size NULL
#define USB_HOST_ICCD_POWER_OFF_OK USB_HOST_ICCD_POWER_OFF_OK__enum,USB_HOST_ICCD_POWER_OFF_OK_size

// USB_HOST_ICCD_XFR_BLOCK_OK
#define USB_HOST_ICCD_XFR_BLOCK_OK_size "d"
#define USB_HOST_ICCD_XFR_BLOCK_OK USB_HOST_ICCD_XFR_BLOCK_OK__enum,USB_HOST_ICCD_XFR_BLOCK_OK_size

// USB_HOST_ICCD_DATA_BLOCK_OK
#define USB_HOST_ICCD_DATA_BLOCK_OK_size "d"
#define USB_HOST_ICCD_DATA_BLOCK_OK USB_HOST_ICCD_DATA_BLOCK_OK__enum,USB_HOST_ICCD_DATA_BLOCK_OK_size

// USB_HOST_ICCD_SLOT_STATUS_OK
#define USB_HOST_ICCD_SLOT_STATUS_OK_size "d"
#define USB_HOST_ICCD_SLOT_STATUS_OK USB_HOST_ICCD_SLOT_STATUS_OK__enum,USB_HOST_ICCD_SLOT_STATUS_OK_size

// USB_HOST_EEM_START
#define USB_HOST_EEM_START_size NULL
#define USB_HOST_EEM_START USB_HOST_EEM_START__enum,USB_HOST_EEM_START_size

// USB_HOST_EEM_END
#define USB_HOST_EEM_END_size NULL
#define USB_HOST_EEM_END USB_HOST_EEM_END__enum,USB_HOST_EEM_END_size

// USB_HOST_EEM_SEND_FRAME
#define USB_HOST_EEM_SEND_FRAME_size "d"
#define USB_HOST_EEM_SEND_FRAME USB_HOST_EEM_SEND_FRAME__enum,USB_HOST_EEM_SEND_FRAME_size

// USB_HOST_EEM_SEND_FRAME_BUFFER
#define USB_HOST_EEM_SEND_FRAME_BUFFER_size "‚d"
#define USB_HOST_EEM_SEND_FRAME_BUFFER USB_HOST_EEM_SEND_FRAME_BUFFER__enum,USB_HOST_EEM_SEND_FRAME_BUFFER_size

// USB_HOST_EEM_TX_DMA_Callback
#define USB_HOST_EEM_TX_DMA_Callback_size "‚d"
#define USB_HOST_EEM_TX_DMA_Callback USB_HOST_EEM_TX_DMA_Callback__enum,USB_HOST_EEM_TX_DMA_Callback_size

// USB_HOST_EEM_GET_RX_BUFFER
#define USB_HOST_EEM_GET_RX_BUFFER_size "d"
#define USB_HOST_EEM_GET_RX_BUFFER USB_HOST_EEM_GET_RX_BUFFER__enum,USB_HOST_EEM_GET_RX_BUFFER_size

// USB_HOST_EEM_RECEIVE_DATA
#define USB_HOST_EEM_RECEIVE_DATA_size "d"
#define USB_HOST_EEM_RECEIVE_DATA USB_HOST_EEM_RECEIVE_DATA__enum,USB_HOST_EEM_RECEIVE_DATA_size

// USB_HOST_EEM_RECEIVE_DATA_BUFFER
#define USB_HOST_EEM_RECEIVE_DATA_BUFFER_size "‚d"
#define USB_HOST_EEM_RECEIVE_DATA_BUFFER USB_HOST_EEM_RECEIVE_DATA_BUFFER__enum,USB_HOST_EEM_RECEIVE_DATA_BUFFER_size

// USB_HOST_EEM_RX_DMA_Callback
#define USB_HOST_EEM_RX_DMA_Callback_size "‚d"
#define USB_HOST_EEM_RX_DMA_Callback USB_HOST_EEM_RX_DMA_Callback__enum,USB_HOST_EEM_RX_DMA_Callback_size

// USB_HOST_EEM_RX_FIFO_Read
#define USB_HOST_EEM_RX_FIFO_Read_size "‚d"
#define USB_HOST_EEM_RX_FIFO_Read USB_HOST_EEM_RX_FIFO_Read__enum,USB_HOST_EEM_RX_FIFO_Read_size

// USB_HOST_EEM_RECEIVE_DATA_ERROR
#define USB_HOST_EEM_RECEIVE_DATA_ERROR_size "d"
#define USB_HOST_EEM_RECEIVE_DATA_ERROR USB_HOST_EEM_RECEIVE_DATA_ERROR__enum,USB_HOST_EEM_RECEIVE_DATA_ERROR_size

// USB_PDN_LOOP_FAIL
#define USB_PDN_LOOP_FAIL_size NULL
#define USB_PDN_LOOP_FAIL USB_PDN_LOOP_FAIL__enum,USB_PDN_LOOP_FAIL_size

// USB_HOST_HIGH_RX_WRONG_MAX_PKT_SIZE
#define USB_HOST_HIGH_RX_WRONG_MAX_PKT_SIZE_size NULL
#define USB_HOST_HIGH_RX_WRONG_MAX_PKT_SIZE USB_HOST_HIGH_RX_WRONG_MAX_PKT_SIZE__enum,USB_HOST_HIGH_RX_WRONG_MAX_PKT_SIZE_size

// USB_HOST_FULL_RX_WRONG_MAX_PKT_SIZE
#define USB_HOST_FULL_RX_WRONG_MAX_PKT_SIZE_size NULL
#define USB_HOST_FULL_RX_WRONG_MAX_PKT_SIZE USB_HOST_FULL_RX_WRONG_MAX_PKT_SIZE__enum,USB_HOST_FULL_RX_WRONG_MAX_PKT_SIZE_size

// USB_HOST_HIGH_TX_WRONG_MAX_PKT_SIZE
#define USB_HOST_HIGH_TX_WRONG_MAX_PKT_SIZE_size NULL
#define USB_HOST_HIGH_TX_WRONG_MAX_PKT_SIZE USB_HOST_HIGH_TX_WRONG_MAX_PKT_SIZE__enum,USB_HOST_HIGH_TX_WRONG_MAX_PKT_SIZE_size

// USB_HOST_FULL_TX_WRONG_MAX_PKT_SIZE
#define USB_HOST_FULL_TX_WRONG_MAX_PKT_SIZE_size NULL
#define USB_HOST_FULL_TX_WRONG_MAX_PKT_SIZE USB_HOST_FULL_TX_WRONG_MAX_PKT_SIZE__enum,USB_HOST_FULL_TX_WRONG_MAX_PKT_SIZE_size

// USB_PTP_HREQUEST_ERROR
#define USB_PTP_HREQUEST_ERROR_size NULL
#define USB_PTP_HREQUEST_ERROR USB_PTP_HREQUEST_ERROR__enum,USB_PTP_HREQUEST_ERROR_size

// USB_PTP_DREQUEST_ERROR
#define USB_PTP_DREQUEST_ERROR_size NULL
#define USB_PTP_DREQUEST_ERROR USB_PTP_DREQUEST_ERROR__enum,USB_PTP_DREQUEST_ERROR_size

// USB_MTP_RESPONSE_WARNING
#define USB_MTP_RESPONSE_WARNING_size "d"
#define USB_MTP_RESPONSE_WARNING USB_MTP_RESPONSE_WARNING__enum,USB_MTP_RESPONSE_WARNING_size

// USB_MTP_RESPONSE_UNEXPECTED_ZERO_WARNING
#define USB_MTP_RESPONSE_UNEXPECTED_ZERO_WARNING_size NULL
#define USB_MTP_RESPONSE_UNEXPECTED_ZERO_WARNING USB_MTP_RESPONSE_UNEXPECTED_ZERO_WARNING__enum,USB_MTP_RESPONSE_UNEXPECTED_ZERO_WARNING_size

// USBIMAGE_EP0_RESET
#define USBIMAGE_EP0_RESET_size NULL
#define USBIMAGE_EP0_RESET USBIMAGE_EP0_RESET__enum,USBIMAGE_EP0_RESET_size

// USBIMAGE_EP0_CANCEL
#define USBIMAGE_EP0_CANCEL_size NULL
#define USBIMAGE_EP0_CANCEL USBIMAGE_EP0_CANCEL__enum,USBIMAGE_EP0_CANCEL_size

// USBIMAGE_EP0_GET_STATUS_BUSY
#define USBIMAGE_EP0_GET_STATUS_BUSY_size NULL
#define USBIMAGE_EP0_GET_STATUS_BUSY USBIMAGE_EP0_GET_STATUS_BUSY__enum,USBIMAGE_EP0_GET_STATUS_BUSY_size

// USBIMAGE_EP0_GET_STATUS_OK
#define USBIMAGE_EP0_GET_STATUS_OK_size NULL
#define USBIMAGE_EP0_GET_STATUS_OK USBIMAGE_EP0_GET_STATUS_OK__enum,USBIMAGE_EP0_GET_STATUS_OK_size

// USBIMAGE_EP0_GET_STATUS_CANCEL
#define USBIMAGE_EP0_GET_STATUS_CANCEL_size NULL
#define USBIMAGE_EP0_GET_STATUS_CANCEL USBIMAGE_EP0_GET_STATUS_CANCEL__enum,USBIMAGE_EP0_GET_STATUS_CANCEL_size

// USBIMAGE_EP0_CANCEL_ERROR
#define USBIMAGE_EP0_CANCEL_ERROR_size "‚d"
#define USBIMAGE_EP0_CANCEL_ERROR USBIMAGE_EP0_CANCEL_ERROR__enum,USBIMAGE_EP0_CANCEL_ERROR_size

// USB_MTP_TX_RESPONSE_INVAILD_MTP_MSG
#define USB_MTP_TX_RESPONSE_INVAILD_MTP_MSG_size "‚d"
#define USB_MTP_TX_RESPONSE_INVAILD_MTP_MSG USB_MTP_TX_RESPONSE_INVAILD_MTP_MSG__enum,USB_MTP_TX_RESPONSE_INVAILD_MTP_MSG_size

// USB_MTP_RX_RESPONSE_INVAILD_MTP_MSG
#define USB_MTP_RX_RESPONSE_INVAILD_MTP_MSG_size "‚d"
#define USB_MTP_RX_RESPONSE_INVAILD_MTP_MSG USB_MTP_RX_RESPONSE_INVAILD_MTP_MSG__enum,USB_MTP_RX_RESPONSE_INVAILD_MTP_MSG_size

// USB_MTP_PC_SEND_WRONG_PACKET
#define USB_MTP_PC_SEND_WRONG_PACKET_size "‚d"
#define USB_MTP_PC_SEND_WRONG_PACKET USB_MTP_PC_SEND_WRONG_PACKET__enum,USB_MTP_PC_SEND_WRONG_PACKET_size

// USB_HW_ERROR_STATUS
#define USB_HW_ERROR_STATUS_size "‚d"
#define USB_HW_ERROR_STATUS USB_HW_ERROR_STATUS__enum,USB_HW_ERROR_STATUS_size

// USB_HOST_HW_ERROR
#define USB_HOST_HW_ERROR_size NULL
#define USB_HOST_HW_ERROR USB_HOST_HW_ERROR__enum,USB_HOST_HW_ERROR_size

// USB_PULL_DOWN_DP
#define USB_PULL_DOWN_DP_size NULL
#define USB_PULL_DOWN_DP USB_PULL_DOWN_DP__enum,USB_PULL_DOWN_DP_size

// USBACM_ENABLE_HIGH_SPEED_IF
#define USBACM_ENABLE_HIGH_SPEED_IF_size "d"
#define USBACM_ENABLE_HIGH_SPEED_IF USBACM_ENABLE_HIGH_SPEED_IF__enum,USBACM_ENABLE_HIGH_SPEED_IF_size

// USBACM_DISABLE_HIGH_SPEED_IF
#define USBACM_DISABLE_HIGH_SPEED_IF_size "d"
#define USBACM_DISABLE_HIGH_SPEED_IF USBACM_DISABLE_HIGH_SPEED_IF__enum,USBACM_DISABLE_HIGH_SPEED_IF_size

// USBACM_DISABLE_HIGH_SPEED_IF_TIMEOUT
#define USBACM_DISABLE_HIGH_SPEED_IF_TIMEOUT_size "d"
#define USBACM_DISABLE_HIGH_SPEED_IF_TIMEOUT USBACM_DISABLE_HIGH_SPEED_IF_TIMEOUT__enum,USBACM_DISABLE_HIGH_SPEED_IF_TIMEOUT_size

// USBACM_MOVE_RC_INDEX
#define USBACM_MOVE_RC_INDEX_size "„d"
#define USBACM_MOVE_RC_INDEX USBACM_MOVE_RC_INDEX__enum,USBACM_MOVE_RC_INDEX_size

// USBACM_MOVE_R_INDEX
#define USBACM_MOVE_R_INDEX_size "„d"
#define USBACM_MOVE_R_INDEX USBACM_MOVE_R_INDEX__enum,USBACM_MOVE_R_INDEX_size

// USBACM_MOVE_W_INDEX
#define USBACM_MOVE_W_INDEX_size "„d"
#define USBACM_MOVE_W_INDEX USBACM_MOVE_W_INDEX__enum,USBACM_MOVE_W_INDEX_size

// USBACM_HIGHSPEED_GETBYTES
#define USBACM_HIGHSPEED_GETBYTES_size "‚d"
#define USBACM_HIGHSPEED_GETBYTES USBACM_HIGHSPEED_GETBYTES__enum,USBACM_HIGHSPEED_GETBYTES_size

// USBACM_HIGHSPEED_GETBYTES_NO_DATA
#define USBACM_HIGHSPEED_GETBYTES_NO_DATA_size "‚d"
#define USBACM_HIGHSPEED_GETBYTES_NO_DATA USBACM_HIGHSPEED_GETBYTES_NO_DATA__enum,USBACM_HIGHSPEED_GETBYTES_NO_DATA_size

// USBACM_HIGHSPEED_PUTBYTES
#define USBACM_HIGHSPEED_PUTBYTES_size "‚d"
#define USBACM_HIGHSPEED_PUTBYTES USBACM_HIGHSPEED_PUTBYTES__enum,USBACM_HIGHSPEED_PUTBYTES_size

// USBACM_HIGHSPEED_PUTBYTES_SETUP_DMA
#define USBACM_HIGHSPEED_PUTBYTES_SETUP_DMA_size "‚d"
#define USBACM_HIGHSPEED_PUTBYTES_SETUP_DMA USBACM_HIGHSPEED_PUTBYTES_SETUP_DMA__enum,USBACM_HIGHSPEED_PUTBYTES_SETUP_DMA_size

// USBACM_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING
#define USBACM_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING_size NULL
#define USBACM_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING USBACM_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING__enum,USBACM_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING_size

// USBACM_HIGHSPEED_PUTBYTES_FAIL
#define USBACM_HIGHSPEED_PUTBYTES_FAIL_size NULL
#define USBACM_HIGHSPEED_PUTBYTES_FAIL USBACM_HIGHSPEED_PUTBYTES_FAIL__enum,USBACM_HIGHSPEED_PUTBYTES_FAIL_size

// USB_ISD_ENABLE_HIGH_SPEED_IF
#define USB_ISD_ENABLE_HIGH_SPEED_IF_size "d"
#define USB_ISD_ENABLE_HIGH_SPEED_IF USB_ISD_ENABLE_HIGH_SPEED_IF__enum,USB_ISD_ENABLE_HIGH_SPEED_IF_size

// USB_ISD_DISABLE_HIGH_SPEED_IF
#define USB_ISD_DISABLE_HIGH_SPEED_IF_size "d"
#define USB_ISD_DISABLE_HIGH_SPEED_IF USB_ISD_DISABLE_HIGH_SPEED_IF__enum,USB_ISD_DISABLE_HIGH_SPEED_IF_size

// USB_ISD_DISABLE_HIGH_SPEED_IF_TIMEOUT
#define USB_ISD_DISABLE_HIGH_SPEED_IF_TIMEOUT_size "d"
#define USB_ISD_DISABLE_HIGH_SPEED_IF_TIMEOUT USB_ISD_DISABLE_HIGH_SPEED_IF_TIMEOUT__enum,USB_ISD_DISABLE_HIGH_SPEED_IF_TIMEOUT_size

// USBACM_FLC_MOVE_RC_INDEX
#define USBACM_FLC_MOVE_RC_INDEX_size "„d"
#define USBACM_FLC_MOVE_RC_INDEX USBACM_FLC_MOVE_RC_INDEX__enum,USBACM_FLC_MOVE_RC_INDEX_size

// USBACM_FLC_MOVE_R_INDEX
#define USBACM_FLC_MOVE_R_INDEX_size "„d"
#define USBACM_FLC_MOVE_R_INDEX USBACM_FLC_MOVE_R_INDEX__enum,USBACM_FLC_MOVE_R_INDEX_size

// USBACM_FLC_MOVE_W_INDEX
#define USBACM_FLC_MOVE_W_INDEX_size "„d"
#define USBACM_FLC_MOVE_W_INDEX USBACM_FLC_MOVE_W_INDEX__enum,USBACM_FLC_MOVE_W_INDEX_size

// USBACM_FLC_HIGHSPEED_GETBYTES
#define USBACM_FLC_HIGHSPEED_GETBYTES_size "‚d"
#define USBACM_FLC_HIGHSPEED_GETBYTES USBACM_FLC_HIGHSPEED_GETBYTES__enum,USBACM_FLC_HIGHSPEED_GETBYTES_size

// USBACM_FLC_HIGHSPEED_GETBYTES_NO_DATA
#define USBACM_FLC_HIGHSPEED_GETBYTES_NO_DATA_size "‚d"
#define USBACM_FLC_HIGHSPEED_GETBYTES_NO_DATA USBACM_FLC_HIGHSPEED_GETBYTES_NO_DATA__enum,USBACM_FLC_HIGHSPEED_GETBYTES_NO_DATA_size

// USBACM_FLC_HIGHSPEED_PUTBYTES
#define USBACM_FLC_HIGHSPEED_PUTBYTES_size "‚d"
#define USBACM_FLC_HIGHSPEED_PUTBYTES USBACM_FLC_HIGHSPEED_PUTBYTES__enum,USBACM_FLC_HIGHSPEED_PUTBYTES_size

// USBACM_FLC_HIGHSPEED_PUTBYTES_SETUP_DMA
#define USBACM_FLC_HIGHSPEED_PUTBYTES_SETUP_DMA_size "‚d"
#define USBACM_FLC_HIGHSPEED_PUTBYTES_SETUP_DMA USBACM_FLC_HIGHSPEED_PUTBYTES_SETUP_DMA__enum,USBACM_FLC_HIGHSPEED_PUTBYTES_SETUP_DMA_size

// USBACM_FLC_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING
#define USBACM_FLC_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING_size NULL
#define USBACM_FLC_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING USBACM_FLC_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING__enum,USBACM_FLC_HIGHSPEED_PUTBYTES_DMA_IS_RUNNING_size

// USBACM_FLC_HIGHSPEED_PUTBYTES_FAIL
#define USBACM_FLC_HIGHSPEED_PUTBYTES_FAIL_size NULL
#define USBACM_FLC_HIGHSPEED_PUTBYTES_FAIL USBACM_FLC_HIGHSPEED_PUTBYTES_FAIL__enum,USBACM_FLC_HIGHSPEED_PUTBYTES_FAIL_size

// USBACM_RX_HIGHSPEED_BULK_OUT
#define USBACM_RX_HIGHSPEED_BULK_OUT_size "ƒd"
#define USBACM_RX_HIGHSPEED_BULK_OUT USBACM_RX_HIGHSPEED_BULK_OUT__enum,USBACM_RX_HIGHSPEED_BULK_OUT_size

// USBACM_RX_INDEX
#define USBACM_RX_INDEX_size "„d"
#define USBACM_RX_INDEX USBACM_RX_INDEX__enum,USBACM_RX_INDEX_size

// USBACM_RX_DATA_HEADER
#define USBACM_RX_DATA_HEADER_size "„d"
#define USBACM_RX_DATA_HEADER USBACM_RX_DATA_HEADER__enum,USBACM_RX_DATA_HEADER_size

// USBACM_RX_PUSH
#define USBACM_RX_PUSH_size "d"
#define USBACM_RX_PUSH USBACM_RX_PUSH__enum,USBACM_RX_PUSH_size

// USBACM_RX_POP
#define USBACM_RX_POP_size "d"
#define USBACM_RX_POP USBACM_RX_POP__enum,USBACM_RX_POP_size

// USBACM_RX_NO_BUFFER
#define USBACM_RX_NO_BUFFER_size "d"
#define USBACM_RX_NO_BUFFER USBACM_RX_NO_BUFFER__enum,USBACM_RX_NO_BUFFER_size

// USBACM_RX_FLC_DATA_HEADER
#define USBACM_RX_FLC_DATA_HEADER_size "„d"
#define USBACM_RX_FLC_DATA_HEADER USBACM_RX_FLC_DATA_HEADER__enum,USBACM_RX_FLC_DATA_HEADER_size

// USBACM_RX_FLC_PUSH
#define USBACM_RX_FLC_PUSH_size "d"
#define USBACM_RX_FLC_PUSH USBACM_RX_FLC_PUSH__enum,USBACM_RX_FLC_PUSH_size

// USBACM_RX_FLC_POP
#define USBACM_RX_FLC_POP_size "d"
#define USBACM_RX_FLC_POP USBACM_RX_FLC_POP__enum,USBACM_RX_FLC_POP_size

// USBACM_RX_FLC_NO_BUFFER
#define USBACM_RX_FLC_NO_BUFFER_size "d"
#define USBACM_RX_FLC_NO_BUFFER USBACM_RX_FLC_NO_BUFFER__enum,USBACM_RX_FLC_NO_BUFFER_size

// USBACM_Drop
#define USBACM_Drop_size "‚d"
#define USBACM_Drop USBACM_Drop__enum,USBACM_Drop_size

// USBACM_RX_FLC_HIGHSPEED_BULK_OUT
#define USBACM_RX_FLC_HIGHSPEED_BULK_OUT_size "ƒd"
#define USBACM_RX_FLC_HIGHSPEED_BULK_OUT USBACM_RX_FLC_HIGHSPEED_BULK_OUT__enum,USBACM_RX_FLC_HIGHSPEED_BULK_OUT_size

// USBMS_READ_PERFORMANCE
#define USBMS_READ_PERFORMANCE_size "d"
#define USBMS_READ_PERFORMANCE USBMS_READ_PERFORMANCE__enum,USBMS_READ_PERFORMANCE_size

// USBMS_WRITE_PERFORMANCE
#define USBMS_WRITE_PERFORMANCE_size "d"
#define USBMS_WRITE_PERFORMANCE USBMS_WRITE_PERFORMANCE__enum,USBMS_WRITE_PERFORMANCE_size

// USBMS_CBWCMD
#define USBMS_CBWCMD_size "d"
#define USBMS_CBWCMD USBMS_CBWCMD__enum,USBMS_CBWCMD_size

// USB_TEST_LOAD
#define USB_TEST_LOAD_size NULL
#define USB_TEST_LOAD USB_TEST_LOAD__enum,USB_TEST_LOAD_size


#endif // USB_TRC_GEN.H
