#ifndef _WMT_TRC_GEN_H_
#define _WMT_TRC_GEN_H_

// WMT_INFO_WMT_MODULE_INIT
#define WMT_INFO_WMT_MODULE_INIT_size "d"
#define WMT_INFO_WMT_MODULE_INIT WMT_INFO_WMT_MODULE_INIT__enum,WMT_INFO_WMT_MODULE_INIT_size

// WMT_INFO_COMMON_EVENT_HANDLER
#define WMT_INFO_COMMON_EVENT_HANDLER_size NULL
#define WMT_INFO_COMMON_EVENT_HANDLER WMT_INFO_COMMON_EVENT_HANDLER__enum,WMT_INFO_COMMON_EVENT_HANDLER_size

// WMT_INFO_COMMON_PROC_NEXT_SCRIPT
#define WMT_INFO_COMMON_PROC_NEXT_SCRIPT_size NULL
#define WMT_INFO_COMMON_PROC_NEXT_SCRIPT WMT_INFO_COMMON_PROC_NEXT_SCRIPT__enum,WMT_INFO_COMMON_PROC_NEXT_SCRIPT_size

// WMT_INFO_COMMON_PEND_SCRIPT
#define WMT_INFO_COMMON_PEND_SCRIPT_size NULL
#define WMT_INFO_COMMON_PEND_SCRIPT WMT_INFO_COMMON_PEND_SCRIPT__enum,WMT_INFO_COMMON_PEND_SCRIPT_size

// WMT_INFO_COMMON_SCRIPT_COMPLETE
#define WMT_INFO_COMMON_SCRIPT_COMPLETE_size NULL
#define WMT_INFO_COMMON_SCRIPT_COMPLETE WMT_INFO_COMMON_SCRIPT_COMPLETE__enum,WMT_INFO_COMMON_SCRIPT_COMPLETE_size

// WMT_INFO_CMD_SEND
#define WMT_INFO_CMD_SEND_size "d"
#define WMT_INFO_CMD_SEND WMT_INFO_CMD_SEND__enum,WMT_INFO_CMD_SEND_size

// WMT_INFO_EVENT_RECEIVE
#define WMT_INFO_EVENT_RECEIVE_size "d"
#define WMT_INFO_EVENT_RECEIVE WMT_INFO_EVENT_RECEIVE__enum,WMT_INFO_EVENT_RECEIVE_size

// WMT_INFO_SETUP_GPIO
#define WMT_INFO_SETUP_GPIO_size NULL
#define WMT_INFO_SETUP_GPIO WMT_INFO_SETUP_GPIO__enum,WMT_INFO_SETUP_GPIO_size

// WMT_INFO_POWER_ON_HANDLER
#define WMT_INFO_POWER_ON_HANDLER_size "d"
#define WMT_INFO_POWER_ON_HANDLER WMT_INFO_POWER_ON_HANDLER__enum,WMT_INFO_POWER_ON_HANDLER_size

// WMT_INFO_POWER_OFF_HANDLER
#define WMT_INFO_POWER_OFF_HANDLER_size "d"
#define WMT_INFO_POWER_OFF_HANDLER WMT_INFO_POWER_OFF_HANDLER__enum,WMT_INFO_POWER_OFF_HANDLER_size

// WMT_INFO_COMMON_PWR_CASE
#define WMT_INFO_COMMON_PWR_CASE_size "d"
#define WMT_INFO_COMMON_PWR_CASE WMT_INFO_COMMON_PWR_CASE__enum,WMT_INFO_COMMON_PWR_CASE_size

// WMT_INFO_COMMON_HW_DONE
#define WMT_INFO_COMMON_HW_DONE_size NULL
#define WMT_INFO_COMMON_HW_DONE WMT_INFO_COMMON_HW_DONE__enum,WMT_INFO_COMMON_HW_DONE_size

// WMT_INFO_COMMON_IF_DONE
#define WMT_INFO_COMMON_IF_DONE_size NULL
#define WMT_INFO_COMMON_IF_DONE WMT_INFO_COMMON_IF_DONE__enum,WMT_INFO_COMMON_IF_DONE_size

// WMT_ERR_COMMON_FAIL
#define WMT_ERR_COMMON_FAIL_size "d"
#define WMT_ERR_COMMON_FAIL WMT_ERR_COMMON_FAIL__enum,WMT_ERR_COMMON_FAIL_size

// WMT_ERR_EVENT_FAIL
#define WMT_ERR_EVENT_FAIL_size "d"
#define WMT_ERR_EVENT_FAIL WMT_ERR_EVENT_FAIL__enum,WMT_ERR_EVENT_FAIL_size

// WMT_ERR_PWR_FAIL
#define WMT_ERR_PWR_FAIL_size "d"
#define WMT_ERR_PWR_FAIL WMT_ERR_PWR_FAIL__enum,WMT_ERR_PWR_FAIL_size

// WMT_ERR_HOST_WAKEUP_FAIL
#define WMT_ERR_HOST_WAKEUP_FAIL_size NULL
#define WMT_ERR_HOST_WAKEUP_FAIL WMT_ERR_HOST_WAKEUP_FAIL__enum,WMT_ERR_HOST_WAKEUP_FAIL_size

// WMT_ERR_UART_RX_INVALID
#define WMT_ERR_UART_RX_INVALID_size "d"
#define WMT_ERR_UART_RX_INVALID WMT_ERR_UART_RX_INVALID__enum,WMT_ERR_UART_RX_INVALID_size

// WMT_INFO_HOST_WAKEUP_ISR
#define WMT_INFO_HOST_WAKEUP_ISR_size NULL
#define WMT_INFO_HOST_WAKEUP_ISR WMT_INFO_HOST_WAKEUP_ISR__enum,WMT_INFO_HOST_WAKEUP_ISR_size

// WMT_INFO_PWR_EVENT_HANDLER
#define WMT_INFO_PWR_EVENT_HANDLER_size NULL
#define WMT_INFO_PWR_EVENT_HANDLER WMT_INFO_PWR_EVENT_HANDLER__enum,WMT_INFO_PWR_EVENT_HANDLER_size

// WMT_INFO_HOST_ALLOW_SLEEP
#define WMT_INFO_HOST_ALLOW_SLEEP_size "‚d"
#define WMT_INFO_HOST_ALLOW_SLEEP WMT_INFO_HOST_ALLOW_SLEEP__enum,WMT_INFO_HOST_ALLOW_SLEEP_size

// WMT_INFO_WAKEUP
#define WMT_INFO_WAKEUP_size NULL
#define WMT_INFO_WAKEUP WMT_INFO_WAKEUP__enum,WMT_INFO_WAKEUP_size

// WMT_INFO_HOST_WAKEUP
#define WMT_INFO_HOST_WAKEUP_size NULL
#define WMT_INFO_HOST_WAKEUP WMT_INFO_HOST_WAKEUP__enum,WMT_INFO_HOST_WAKEUP_size

// WMT_INFO_BB_SLEEP
#define WMT_INFO_BB_SLEEP_size "d"
#define WMT_INFO_BB_SLEEP WMT_INFO_BB_SLEEP__enum,WMT_INFO_BB_SLEEP_size

// WMT_INFO_GPIO_EXT_START
#define WMT_INFO_GPIO_EXT_START_size NULL
#define WMT_INFO_GPIO_EXT_START WMT_INFO_GPIO_EXT_START__enum,WMT_INFO_GPIO_EXT_START_size

// WMT_INFO_GPIO_EXT_END
#define WMT_INFO_GPIO_EXT_END_size "‚d"
#define WMT_INFO_GPIO_EXT_END WMT_INFO_GPIO_EXT_END__enum,WMT_INFO_GPIO_EXT_END_size

// WMT_INFO_GPIO_EXT_SETTING
#define WMT_INFO_GPIO_EXT_SETTING_size "ƒd"
#define WMT_INFO_GPIO_EXT_SETTING WMT_INFO_GPIO_EXT_SETTING__enum,WMT_INFO_GPIO_EXT_SETTING_size

// WMT_INFO_GPIO_EXT_INVALID
#define WMT_INFO_GPIO_EXT_INVALID_size "d"
#define WMT_INFO_GPIO_EXT_INVALID WMT_INFO_GPIO_EXT_INVALID__enum,WMT_INFO_GPIO_EXT_INVALID_size

// WMT_INFO_GPIO_EXT_HW_ISSUE
#define WMT_INFO_GPIO_EXT_HW_ISSUE_size NULL
#define WMT_INFO_GPIO_EXT_HW_ISSUE WMT_INFO_GPIO_EXT_HW_ISSUE__enum,WMT_INFO_GPIO_EXT_HW_ISSUE_size

// STP_INFO_ENABLE_STP
#define STP_INFO_ENABLE_STP_size NULL
#define STP_INFO_ENABLE_STP STP_INFO_ENABLE_STP__enum,STP_INFO_ENABLE_STP_size

// STP_TX_TIMEOUT
#define STP_TX_TIMEOUT_size "„d"
#define STP_TX_TIMEOUT STP_TX_TIMEOUT__enum,STP_TX_TIMEOUT_size

// STP_TX_RETRY
#define STP_TX_RETRY_size "d"
#define STP_TX_RETRY STP_TX_RETRY__enum,STP_TX_RETRY_size

// STP_RX_WRONG_TYPE
#define STP_RX_WRONG_TYPE_size "d"
#define STP_RX_WRONG_TYPE STP_RX_WRONG_TYPE__enum,STP_RX_WRONG_TYPE_size

// STP_HDR_CHECKSUM_ERR
#define STP_HDR_CHECKSUM_ERR_size NULL
#define STP_HDR_CHECKSUM_ERR STP_HDR_CHECKSUM_ERR__enum,STP_HDR_CHECKSUM_ERR_size

// STP_PKT_CHECKSUM_ERR
#define STP_PKT_CHECKSUM_ERR_size NULL
#define STP_PKT_CHECKSUM_ERR STP_PKT_CHECKSUM_ERR__enum,STP_PKT_CHECKSUM_ERR_size

// STP_TX_WIN_FULL
#define STP_TX_WIN_FULL_size NULL
#define STP_TX_WIN_FULL STP_TX_WIN_FULL__enum,STP_TX_WIN_FULL_size

// STP_TX_Q_FULL
#define STP_TX_Q_FULL_size NULL
#define STP_TX_Q_FULL STP_TX_Q_FULL__enum,STP_TX_Q_FULL_size

// STP_RX_Q_FULL
#define STP_RX_Q_FULL_size "d"
#define STP_RX_Q_FULL STP_RX_Q_FULL__enum,STP_RX_Q_FULL_size

// STP_TX_VFIFO_FULL
#define STP_TX_VFIFO_FULL_size "‚d"
#define STP_TX_VFIFO_FULL STP_TX_VFIFO_FULL__enum,STP_TX_VFIFO_FULL_size

// STP_TX_RETRY_LIMIT
#define STP_TX_RETRY_LIMIT_size "d"
#define STP_TX_RETRY_LIMIT STP_TX_RETRY_LIMIT__enum,STP_TX_RETRY_LIMIT_size

// STP_TX_SEND_ACK
#define STP_TX_SEND_ACK_size "…d"
#define STP_TX_SEND_ACK STP_TX_SEND_ACK__enum,STP_TX_SEND_ACK_size

// STP_PROC_RX_ACK
#define STP_PROC_RX_ACK_size "ƒd"
#define STP_PROC_RX_ACK STP_PROC_RX_ACK__enum,STP_PROC_RX_ACK_size

// STP_WIN_SPACE
#define STP_WIN_SPACE_size "d"
#define STP_WIN_SPACE STP_WIN_SPACE__enum,STP_WIN_SPACE_size

// STP_RX_PKT_SEQ_CHECK
#define STP_RX_PKT_SEQ_CHECK_size "‚d"
#define STP_RX_PKT_SEQ_CHECK STP_RX_PKT_SEQ_CHECK__enum,STP_RX_PKT_SEQ_CHECK_size

// STP_PARSE_RX_ACK
#define STP_PARSE_RX_ACK_size "ƒd"
#define STP_PARSE_RX_ACK STP_PARSE_RX_ACK__enum,STP_PARSE_RX_ACK_size

// STP_PARSE_RX_DATA
#define STP_PARSE_RX_DATA_size "„d"
#define STP_PARSE_RX_DATA STP_PARSE_RX_DATA__enum,STP_PARSE_RX_DATA_size

// STP_TX_DATA
#define STP_TX_DATA_size "„d"
#define STP_TX_DATA STP_TX_DATA__enum,STP_TX_DATA_size

// STP_TX_RAW_DATA
#define STP_TX_RAW_DATA_size "‡d"
#define STP_TX_RAW_DATA STP_TX_RAW_DATA__enum,STP_TX_RAW_DATA_size

// STP_RX_NAK
#define STP_RX_NAK_size NULL
#define STP_RX_NAK STP_RX_NAK__enum,STP_RX_NAK_size

// STP_INFO_TX_BUFF_LEFT
#define STP_INFO_TX_BUFF_LEFT_size "‚d"
#define STP_INFO_TX_BUFF_LEFT STP_INFO_TX_BUFF_LEFT__enum,STP_INFO_TX_BUFF_LEFT_size

// STP_INFO_EVENT_SET_CHECK
#define STP_INFO_EVENT_SET_CHECK_size "d"
#define STP_INFO_EVENT_SET_CHECK STP_INFO_EVENT_SET_CHECK__enum,STP_INFO_EVENT_SET_CHECK_size

// STP_INFO_TX_RESUME
#define STP_INFO_TX_RESUME_size "d"
#define STP_INFO_TX_RESUME STP_INFO_TX_RESUME__enum,STP_INFO_TX_RESUME_size

// STP_INFO_TX_BLOCK_BY_SLEEP
#define STP_INFO_TX_BLOCK_BY_SLEEP_size "d"
#define STP_INFO_TX_BLOCK_BY_SLEEP STP_INFO_TX_BLOCK_BY_SLEEP__enum,STP_INFO_TX_BLOCK_BY_SLEEP_size

// STP_INFO_TX_BLOCK_BY_WIN_FULL
#define STP_INFO_TX_BLOCK_BY_WIN_FULL_size "d"
#define STP_INFO_TX_BLOCK_BY_WIN_FULL STP_INFO_TX_BLOCK_BY_WIN_FULL__enum,STP_INFO_TX_BLOCK_BY_WIN_FULL_size

// STP_INFO_UART_READY_TO_WRITE
#define STP_INFO_UART_READY_TO_WRITE_size "d"
#define STP_INFO_UART_READY_TO_WRITE STP_INFO_UART_READY_TO_WRITE__enum,STP_INFO_UART_READY_TO_WRITE_size

// STP_INFO_UART_SETUP_SPEED
#define STP_INFO_UART_SETUP_SPEED_size "d"
#define STP_INFO_UART_SETUP_SPEED STP_INFO_UART_SETUP_SPEED__enum,STP_INFO_UART_SETUP_SPEED_size

// BWCS_INFO_BT_EVENT_UPDATE
#define BWCS_INFO_BT_EVENT_UPDATE_size "c"
#define BWCS_INFO_BT_EVENT_UPDATE BWCS_INFO_BT_EVENT_UPDATE__enum,BWCS_INFO_BT_EVENT_UPDATE_size

// BWCS_INFO_BT_AVDTP_UPDATE
#define BWCS_INFO_BT_AVDTP_UPDATE_size "c"
#define BWCS_INFO_BT_AVDTP_UPDATE BWCS_INFO_BT_AVDTP_UPDATE__enum,BWCS_INFO_BT_AVDTP_UPDATE_size

// BWCS_INFO_WIFI_EVENT_UPDATE
#define BWCS_INFO_WIFI_EVENT_UPDATE_size "c"
#define BWCS_INFO_WIFI_EVENT_UPDATE BWCS_INFO_WIFI_EVENT_UPDATE__enum,BWCS_INFO_WIFI_EVENT_UPDATE_size

// BWCS_INFO_BT_UPDATE_IN_QUERY
#define BWCS_INFO_BT_UPDATE_IN_QUERY_size NULL
#define BWCS_INFO_BT_UPDATE_IN_QUERY BWCS_INFO_BT_UPDATE_IN_QUERY__enum,BWCS_INFO_BT_UPDATE_IN_QUERY_size

// BWCS_INFO_WIFI_UPDATE_IN_QUERY
#define BWCS_INFO_WIFI_UPDATE_IN_QUERY_size NULL
#define BWCS_INFO_WIFI_UPDATE_IN_QUERY BWCS_INFO_WIFI_UPDATE_IN_QUERY__enum,BWCS_INFO_WIFI_UPDATE_IN_QUERY_size

// BWCS_INFO_SCO_LINK_WRONG_RECORD
#define BWCS_INFO_SCO_LINK_WRONG_RECORD_size NULL
#define BWCS_INFO_SCO_LINK_WRONG_RECORD BWCS_INFO_SCO_LINK_WRONG_RECORD__enum,BWCS_INFO_SCO_LINK_WRONG_RECORD_size

// BWCS_INFO_ACL_LINK_WRONG_RECORD
#define BWCS_INFO_ACL_LINK_WRONG_RECORD_size NULL
#define BWCS_INFO_ACL_LINK_WRONG_RECORD BWCS_INFO_ACL_LINK_WRONG_RECORD__enum,BWCS_INFO_ACL_LINK_WRONG_RECORD_size

// BWCS_INFO_PROFILE_NOT_DEFINED
#define BWCS_INFO_PROFILE_NOT_DEFINED_size NULL
#define BWCS_INFO_PROFILE_NOT_DEFINED BWCS_INFO_PROFILE_NOT_DEFINED__enum,BWCS_INFO_PROFILE_NOT_DEFINED_size

// BWCS_INFO_CONN_DEC_TOO_EARLY
#define BWCS_INFO_CONN_DEC_TOO_EARLY_size NULL
#define BWCS_INFO_CONN_DEC_TOO_EARLY BWCS_INFO_CONN_DEC_TOO_EARLY__enum,BWCS_INFO_CONN_DEC_TOO_EARLY_size

// BWCS_INFO_UNDEFINED_BWCS_EVENT
#define BWCS_INFO_UNDEFINED_BWCS_EVENT_size NULL
#define BWCS_INFO_UNDEFINED_BWCS_EVENT BWCS_INFO_UNDEFINED_BWCS_EVENT__enum,BWCS_INFO_UNDEFINED_BWCS_EVENT_size

// BWCS_INFO_EXCEED_MAX_QUERY_LINK
#define BWCS_INFO_EXCEED_MAX_QUERY_LINK_size "d"
#define BWCS_INFO_EXCEED_MAX_QUERY_LINK BWCS_INFO_EXCEED_MAX_QUERY_LINK__enum,BWCS_INFO_EXCEED_MAX_QUERY_LINK_size

// BWCS_INFO_WIFI_RSSI_COMPENSATION
#define BWCS_INFO_WIFI_RSSI_COMPENSATION_size "ƒd"
#define BWCS_INFO_WIFI_RSSI_COMPENSATION BWCS_INFO_WIFI_RSSI_COMPENSATION__enum,BWCS_INFO_WIFI_RSSI_COMPENSATION_size

// BWCS_INFO_WIFI_TX_FLOW_CONTRL
#define BWCS_INFO_WIFI_TX_FLOW_CONTRL_size "‚d"
#define BWCS_INFO_WIFI_TX_FLOW_CONTRL BWCS_INFO_WIFI_TX_FLOW_CONTRL__enum,BWCS_INFO_WIFI_TX_FLOW_CONTRL_size

// BWCS_INFO_WIFI_ALREADY_QUERY_RSSI
#define BWCS_INFO_WIFI_ALREADY_QUERY_RSSI_size NULL
#define BWCS_INFO_WIFI_ALREADY_QUERY_RSSI BWCS_INFO_WIFI_ALREADY_QUERY_RSSI__enum,BWCS_INFO_WIFI_ALREADY_QUERY_RSSI_size

// BWCS_INFO_WIFI_START_QUERY
#define BWCS_INFO_WIFI_START_QUERY_size NULL
#define BWCS_INFO_WIFI_START_QUERY BWCS_INFO_WIFI_START_QUERY__enum,BWCS_INFO_WIFI_START_QUERY_size

// BWCS_INFO_BT_NEW_CONN
#define BWCS_INFO_BT_NEW_CONN_size "†d"
#define BWCS_INFO_BT_NEW_CONN BWCS_INFO_BT_NEW_CONN__enum,BWCS_INFO_BT_NEW_CONN_size

// BWCS_INFO_BT_CURRENT_LINK
#define BWCS_INFO_BT_CURRENT_LINK_size "ƒd"
#define BWCS_INFO_BT_CURRENT_LINK BWCS_INFO_BT_CURRENT_LINK__enum,BWCS_INFO_BT_CURRENT_LINK_size

// BWCS_INFO_BT_QUERY_RSSI_RESULT
#define BWCS_INFO_BT_QUERY_RSSI_RESULT_size "†d"
#define BWCS_INFO_BT_QUERY_RSSI_RESULT BWCS_INFO_BT_QUERY_RSSI_RESULT__enum,BWCS_INFO_BT_QUERY_RSSI_RESULT_size

// BWCS_INFO_BT_RSSI_COMPENSATION
#define BWCS_INFO_BT_RSSI_COMPENSATION_size "ƒd"
#define BWCS_INFO_BT_RSSI_COMPENSATION BWCS_INFO_BT_RSSI_COMPENSATION__enum,BWCS_INFO_BT_RSSI_COMPENSATION_size

// BWCS_INFO_BT_ALREADY_QUERY_RSSI
#define BWCS_INFO_BT_ALREADY_QUERY_RSSI_size NULL
#define BWCS_INFO_BT_ALREADY_QUERY_RSSI BWCS_INFO_BT_ALREADY_QUERY_RSSI__enum,BWCS_INFO_BT_ALREADY_QUERY_RSSI_size

// BWCS_INFO_BT_START_QUERY
#define BWCS_INFO_BT_START_QUERY_size "†d"
#define BWCS_INFO_BT_START_QUERY BWCS_INFO_BT_START_QUERY__enum,BWCS_INFO_BT_START_QUERY_size

// BWCS_INTO_BT_AVDTP_STREAMING
#define BWCS_INTO_BT_AVDTP_STREAMING_size NULL
#define BWCS_INTO_BT_AVDTP_STREAMING BWCS_INTO_BT_AVDTP_STREAMING__enum,BWCS_INTO_BT_AVDTP_STREAMING_size

// BWCS_INFO_BT_AVDTP_SUSPEND
#define BWCS_INFO_BT_AVDTP_SUSPEND_size NULL
#define BWCS_INFO_BT_AVDTP_SUSPEND BWCS_INFO_BT_AVDTP_SUSPEND__enum,BWCS_INFO_BT_AVDTP_SUSPEND_size

// BWCS_INFO_BT_MSG_PENDING
#define BWCS_INFO_BT_MSG_PENDING_size "d"
#define BWCS_INFO_BT_MSG_PENDING BWCS_INFO_BT_MSG_PENDING__enum,BWCS_INFO_BT_MSG_PENDING_size

// BWCS_INFO_BT_RESUME_PENDING_MSG
#define BWCS_INFO_BT_RESUME_PENDING_MSG_size "d"
#define BWCS_INFO_BT_RESUME_PENDING_MSG BWCS_INFO_BT_RESUME_PENDING_MSG__enum,BWCS_INFO_BT_RESUME_PENDING_MSG_size

// BWCS_INFO_BT_CURR_UPDATE_PWR_CONN
#define BWCS_INFO_BT_CURR_UPDATE_PWR_CONN_size "d"
#define BWCS_INFO_BT_CURR_UPDATE_PWR_CONN BWCS_INFO_BT_CURR_UPDATE_PWR_CONN__enum,BWCS_INFO_BT_CURR_UPDATE_PWR_CONN_size

// BWCS_INFO_WIFI_SET_BWCS_PROFILE
#define BWCS_INFO_WIFI_SET_BWCS_PROFILE_size "‚c‚d"
#define BWCS_INFO_WIFI_SET_BWCS_PROFILE BWCS_INFO_WIFI_SET_BWCS_PROFILE__enum,BWCS_INFO_WIFI_SET_BWCS_PROFILE_size

// BWCS_INFO_BWCS_PROFILE_NO_CHANGE
#define BWCS_INFO_BWCS_PROFILE_NO_CHANGE_size NULL
#define BWCS_INFO_BWCS_PROFILE_NO_CHANGE BWCS_INFO_BWCS_PROFILE_NO_CHANGE__enum,BWCS_INFO_BWCS_PROFILE_NO_CHANGE_size

// BWCS_INFO_BWCS_PROFILE_DECIDE
#define BWCS_INFO_BWCS_PROFILE_DECIDE_size "dcdcd"
#define BWCS_INFO_BWCS_PROFILE_DECIDE BWCS_INFO_BWCS_PROFILE_DECIDE__enum,BWCS_INFO_BWCS_PROFILE_DECIDE_size

// BWCS_INFO_SET_BT_CH_INFO
#define BWCS_INFO_SET_BT_CH_INFO_size "„d"
#define BWCS_INFO_SET_BT_CH_INFO BWCS_INFO_SET_BT_CH_INFO__enum,BWCS_INFO_SET_BT_CH_INFO_size

// BWCS_INFO_SET_ANT
#define BWCS_INFO_SET_ANT_size "d"
#define BWCS_INFO_SET_ANT BWCS_INFO_SET_ANT__enum,BWCS_INFO_SET_ANT_size

// BWCS_INFO_ANT_SWITCH_TIME
#define BWCS_INFO_ANT_SWITCH_TIME_size "d"
#define BWCS_INFO_ANT_SWITCH_TIME BWCS_INFO_ANT_SWITCH_TIME__enum,BWCS_INFO_ANT_SWITCH_TIME_size

// BWCS_INFO_DEC_SET_CH
#define BWCS_INFO_DEC_SET_CH_size "d"
#define BWCS_INFO_DEC_SET_CH BWCS_INFO_DEC_SET_CH__enum,BWCS_INFO_DEC_SET_CH_size

// BWCS_INFO_DEC_BWCS_PROFILE
#define BWCS_INFO_DEC_BWCS_PROFILE_size "d"
#define BWCS_INFO_DEC_BWCS_PROFILE BWCS_INFO_DEC_BWCS_PROFILE__enum,BWCS_INFO_DEC_BWCS_PROFILE_size

// BWCS_INFO_DEC_RT_CASE_ONE
#define BWCS_INFO_DEC_RT_CASE_ONE_size "‚d"
#define BWCS_INFO_DEC_RT_CASE_ONE BWCS_INFO_DEC_RT_CASE_ONE__enum,BWCS_INFO_DEC_RT_CASE_ONE_size

// BWCS_INFO_DEC_RT_CASE_TWO
#define BWCS_INFO_DEC_RT_CASE_TWO_size "‚d"
#define BWCS_INFO_DEC_RT_CASE_TWO BWCS_INFO_DEC_RT_CASE_TWO__enum,BWCS_INFO_DEC_RT_CASE_TWO_size

// BWCS_INFO_DEC_RT_CASE_THREE
#define BWCS_INFO_DEC_RT_CASE_THREE_size "‚d"
#define BWCS_INFO_DEC_RT_CASE_THREE BWCS_INFO_DEC_RT_CASE_THREE__enum,BWCS_INFO_DEC_RT_CASE_THREE_size

// BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_ENABLE
#define BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_ENABLE_size "‚d"
#define BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_ENABLE BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_ENABLE__enum,BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_ENABLE_size

// BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_DISABLE
#define BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_DISABLE_size NULL
#define BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_DISABLE BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_DISABLE__enum,BWCS_INFO_DEC_WIFI_TX_FLOW_CTRL_DISABLE_size

// BWCS_INFO_DEC_NRT_CASE_ONE
#define BWCS_INFO_DEC_NRT_CASE_ONE_size "‚d"
#define BWCS_INFO_DEC_NRT_CASE_ONE BWCS_INFO_DEC_NRT_CASE_ONE__enum,BWCS_INFO_DEC_NRT_CASE_ONE_size

// BWCS_INFO_DEC_NRT_CASE_TWO
#define BWCS_INFO_DEC_NRT_CASE_TWO_size "‚d"
#define BWCS_INFO_DEC_NRT_CASE_TWO BWCS_INFO_DEC_NRT_CASE_TWO__enum,BWCS_INFO_DEC_NRT_CASE_TWO_size

// BWCS_INFO_DEC_NRT_CASE_THREE
#define BWCS_INFO_DEC_NRT_CASE_THREE_size "‚d"
#define BWCS_INFO_DEC_NRT_CASE_THREE BWCS_INFO_DEC_NRT_CASE_THREE__enum,BWCS_INFO_DEC_NRT_CASE_THREE_size

// BWCS_INFO_DEC_CHECK_ANT_SWITCH_TIME
#define BWCS_INFO_DEC_CHECK_ANT_SWITCH_TIME_size "‚d"
#define BWCS_INFO_DEC_CHECK_ANT_SWITCH_TIME BWCS_INFO_DEC_CHECK_ANT_SWITCH_TIME__enum,BWCS_INFO_DEC_CHECK_ANT_SWITCH_TIME_size

// BWCS_INFO_DEC_MAINTAIN_SETTING_WIFI_TH
#define BWCS_INFO_DEC_MAINTAIN_SETTING_WIFI_TH_size "d"
#define BWCS_INFO_DEC_MAINTAIN_SETTING_WIFI_TH BWCS_INFO_DEC_MAINTAIN_SETTING_WIFI_TH__enum,BWCS_INFO_DEC_MAINTAIN_SETTING_WIFI_TH_size

// BWCS_INFO_DEC_SWITCH_ANT_BT_DIRECT
#define BWCS_INFO_DEC_SWITCH_ANT_BT_DIRECT_size NULL
#define BWCS_INFO_DEC_SWITCH_ANT_BT_DIRECT BWCS_INFO_DEC_SWITCH_ANT_BT_DIRECT__enum,BWCS_INFO_DEC_SWITCH_ANT_BT_DIRECT_size

// BWCS_INFO_DEC_SWITCH_ANT_WIFI_DIRECT
#define BWCS_INFO_DEC_SWITCH_ANT_WIFI_DIRECT_size NULL
#define BWCS_INFO_DEC_SWITCH_ANT_WIFI_DIRECT BWCS_INFO_DEC_SWITCH_ANT_WIFI_DIRECT__enum,BWCS_INFO_DEC_SWITCH_ANT_WIFI_DIRECT_size

// BWCS_INFO_DEC_BWCS_SET_EVENT
#define BWCS_INFO_DEC_BWCS_SET_EVENT_size "c"
#define BWCS_INFO_DEC_BWCS_SET_EVENT BWCS_INFO_DEC_BWCS_SET_EVENT__enum,BWCS_INFO_DEC_BWCS_SET_EVENT_size

// BWCS_INFO_DEC_NO_CHANGE
#define BWCS_INFO_DEC_NO_CHANGE_size NULL
#define BWCS_INFO_DEC_NO_CHANGE BWCS_INFO_DEC_NO_CHANGE__enum,BWCS_INFO_DEC_NO_CHANGE_size

// BWCS_INFO_CHANGE_RT_WIFI_RSSI
#define BWCS_INFO_CHANGE_RT_WIFI_RSSI_size "‚d"
#define BWCS_INFO_CHANGE_RT_WIFI_RSSI BWCS_INFO_CHANGE_RT_WIFI_RSSI__enum,BWCS_INFO_CHANGE_RT_WIFI_RSSI_size

// BWCS_INFO_CHANGE_NRT_WIFI_RSSI
#define BWCS_INFO_CHANGE_NRT_WIFI_RSSI_size "‚d"
#define BWCS_INFO_CHANGE_NRT_WIFI_RSSI BWCS_INFO_CHANGE_NRT_WIFI_RSSI__enum,BWCS_INFO_CHANGE_NRT_WIFI_RSSI_size

// BWCS_INFO_CHANGE_BT_RSSI
#define BWCS_INFO_CHANGE_BT_RSSI_size "‚d"
#define BWCS_INFO_CHANGE_BT_RSSI BWCS_INFO_CHANGE_BT_RSSI__enum,BWCS_INFO_CHANGE_BT_RSSI_size

// BWCS_INFO_RESUME_RSSI_TO_DEFAULT
#define BWCS_INFO_RESUME_RSSI_TO_DEFAULT_size NULL
#define BWCS_INFO_RESUME_RSSI_TO_DEFAULT BWCS_INFO_RESUME_RSSI_TO_DEFAULT__enum,BWCS_INFO_RESUME_RSSI_TO_DEFAULT_size

// BWCS_INFO_CHANGE_WIFI_TX_FLOW_CTRL
#define BWCS_INFO_CHANGE_WIFI_TX_FLOW_CTRL_size "‚d"
#define BWCS_INFO_CHANGE_WIFI_TX_FLOW_CTRL BWCS_INFO_CHANGE_WIFI_TX_FLOW_CTRL__enum,BWCS_INFO_CHANGE_WIFI_TX_FLOW_CTRL_size

// BWCS_INFO_INJECT_QUERY_BT
#define BWCS_INFO_INJECT_QUERY_BT_size NULL
#define BWCS_INFO_INJECT_QUERY_BT BWCS_INFO_INJECT_QUERY_BT__enum,BWCS_INFO_INJECT_QUERY_BT_size

// BWCS_INFO_INJECT_QUERY_WIFI
#define BWCS_INFO_INJECT_QUERY_WIFI_size NULL
#define BWCS_INFO_INJECT_QUERY_WIFI BWCS_INFO_INJECT_QUERY_WIFI__enum,BWCS_INFO_INJECT_QUERY_WIFI_size

// BWCS_INFO_INJECT_SET_CH_INFO
#define BWCS_INFO_INJECT_SET_CH_INFO_size NULL
#define BWCS_INFO_INJECT_SET_CH_INFO BWCS_INFO_INJECT_SET_CH_INFO__enum,BWCS_INFO_INJECT_SET_CH_INFO_size

// BWCS_INFO_INJECT_DISABLE_PTA
#define BWCS_INFO_INJECT_DISABLE_PTA_size NULL
#define BWCS_INFO_INJECT_DISABLE_PTA BWCS_INFO_INJECT_DISABLE_PTA__enum,BWCS_INFO_INJECT_DISABLE_PTA_size

// BWCS_INFO_INJECT_ALL_INBAND
#define BWCS_INFO_INJECT_ALL_INBAND_size NULL
#define BWCS_INFO_INJECT_ALL_INBAND BWCS_INFO_INJECT_ALL_INBAND__enum,BWCS_INFO_INJECT_ALL_INBAND_size

// BWCS_INFO_1
#define BWCS_INFO_1_size NULL
#define BWCS_INFO_1 BWCS_INFO_1__enum,BWCS_INFO_1_size

// BWCS_INFO_2
#define BWCS_INFO_2_size NULL
#define BWCS_INFO_2 BWCS_INFO_2__enum,BWCS_INFO_2_size

// BWCS_INFO_3
#define BWCS_INFO_3_size NULL
#define BWCS_INFO_3 BWCS_INFO_3__enum,BWCS_INFO_3_size

// BWCS_INFO_4
#define BWCS_INFO_4_size "d"
#define BWCS_INFO_4 BWCS_INFO_4__enum,BWCS_INFO_4_size

// BWCS_INFO_5
#define BWCS_INFO_5_size NULL
#define BWCS_INFO_5 BWCS_INFO_5__enum,BWCS_INFO_5_size

// BWCS_INFO_6
#define BWCS_INFO_6_size NULL
#define BWCS_INFO_6 BWCS_INFO_6__enum,BWCS_INFO_6_size

// BWCS_INFO_7
#define BWCS_INFO_7_size "d"
#define BWCS_INFO_7 BWCS_INFO_7__enum,BWCS_INFO_7_size

// BWCS_INFO_8
#define BWCS_INFO_8_size NULL
#define BWCS_INFO_8 BWCS_INFO_8__enum,BWCS_INFO_8_size

// BWCS_INFO_9
#define BWCS_INFO_9_size "d"
#define BWCS_INFO_9 BWCS_INFO_9__enum,BWCS_INFO_9_size

// BWCS_INFO_10
#define BWCS_INFO_10_size "d"
#define BWCS_INFO_10 BWCS_INFO_10__enum,BWCS_INFO_10_size

// BWCS_INFO_11
#define BWCS_INFO_11_size NULL
#define BWCS_INFO_11 BWCS_INFO_11__enum,BWCS_INFO_11_size

// BWCS_INFO_12
#define BWCS_INFO_12_size NULL
#define BWCS_INFO_12 BWCS_INFO_12__enum,BWCS_INFO_12_size

// BWCS_INFO_13
#define BWCS_INFO_13_size NULL
#define BWCS_INFO_13 BWCS_INFO_13__enum,BWCS_INFO_13_size

// BWCS_INFO_14
#define BWCS_INFO_14_size NULL
#define BWCS_INFO_14 BWCS_INFO_14__enum,BWCS_INFO_14_size

// BWCS_INFO_15
#define BWCS_INFO_15_size NULL
#define BWCS_INFO_15 BWCS_INFO_15__enum,BWCS_INFO_15_size

// BWCS_INFO_16
#define BWCS_INFO_16_size NULL
#define BWCS_INFO_16 BWCS_INFO_16__enum,BWCS_INFO_16_size

// BWCS_INFO_17
#define BWCS_INFO_17_size NULL
#define BWCS_INFO_17 BWCS_INFO_17__enum,BWCS_INFO_17_size

// BWCS_INFO_18
#define BWCS_INFO_18_size NULL
#define BWCS_INFO_18 BWCS_INFO_18__enum,BWCS_INFO_18_size

// BWCS_INFO_19
#define BWCS_INFO_19_size "d"
#define BWCS_INFO_19 BWCS_INFO_19__enum,BWCS_INFO_19_size

// BWCS_INFO_20
#define BWCS_INFO_20_size "d"
#define BWCS_INFO_20 BWCS_INFO_20__enum,BWCS_INFO_20_size

// BWCS_INFO_21
#define BWCS_INFO_21_size "d"
#define BWCS_INFO_21 BWCS_INFO_21__enum,BWCS_INFO_21_size

// BWCS_INFO_22
#define BWCS_INFO_22_size NULL
#define BWCS_INFO_22 BWCS_INFO_22__enum,BWCS_INFO_22_size

// BWCS_INFO_23
#define BWCS_INFO_23_size "d"
#define BWCS_INFO_23 BWCS_INFO_23__enum,BWCS_INFO_23_size

// BWCS_INFO_24
#define BWCS_INFO_24_size "d"
#define BWCS_INFO_24 BWCS_INFO_24__enum,BWCS_INFO_24_size

// BWCS_INFO_25
#define BWCS_INFO_25_size "d"
#define BWCS_INFO_25 BWCS_INFO_25__enum,BWCS_INFO_25_size

// BWCS_INFO_26
#define BWCS_INFO_26_size NULL
#define BWCS_INFO_26 BWCS_INFO_26__enum,BWCS_INFO_26_size

// BWCS_INFO_27
#define BWCS_INFO_27_size NULL
#define BWCS_INFO_27 BWCS_INFO_27__enum,BWCS_INFO_27_size

// BWCS_INFO_28
#define BWCS_INFO_28_size NULL
#define BWCS_INFO_28 BWCS_INFO_28__enum,BWCS_INFO_28_size

// BWCS_INFO_29
#define BWCS_INFO_29_size NULL
#define BWCS_INFO_29 BWCS_INFO_29__enum,BWCS_INFO_29_size

// BWCS_INFO_30
#define BWCS_INFO_30_size NULL
#define BWCS_INFO_30 BWCS_INFO_30__enum,BWCS_INFO_30_size

// BWCS_INFO_31
#define BWCS_INFO_31_size "d"
#define BWCS_INFO_31 BWCS_INFO_31__enum,BWCS_INFO_31_size

// BWCS_INFO_32
#define BWCS_INFO_32_size NULL
#define BWCS_INFO_32 BWCS_INFO_32__enum,BWCS_INFO_32_size

// BWCS_INFO_33
#define BWCS_INFO_33_size NULL
#define BWCS_INFO_33 BWCS_INFO_33__enum,BWCS_INFO_33_size

// BWCS_INFO_34
#define BWCS_INFO_34_size NULL
#define BWCS_INFO_34 BWCS_INFO_34__enum,BWCS_INFO_34_size

// BWCS_INFO_35
#define BWCS_INFO_35_size "d"
#define BWCS_INFO_35 BWCS_INFO_35__enum,BWCS_INFO_35_size

// BWCS_INFO_36
#define BWCS_INFO_36_size NULL
#define BWCS_INFO_36 BWCS_INFO_36__enum,BWCS_INFO_36_size

// BWCS_INFO_37
#define BWCS_INFO_37_size "d"
#define BWCS_INFO_37 BWCS_INFO_37__enum,BWCS_INFO_37_size

// BWCS_INFO_38
#define BWCS_INFO_38_size "d"
#define BWCS_INFO_38 BWCS_INFO_38__enum,BWCS_INFO_38_size

// BWCS_INFO_39
#define BWCS_INFO_39_size "d"
#define BWCS_INFO_39 BWCS_INFO_39__enum,BWCS_INFO_39_size

// BWCS_INFO_40
#define BWCS_INFO_40_size "d"
#define BWCS_INFO_40 BWCS_INFO_40__enum,BWCS_INFO_40_size

// BWCS_INFO_41
#define BWCS_INFO_41_size "d"
#define BWCS_INFO_41 BWCS_INFO_41__enum,BWCS_INFO_41_size

// BWCS_INFO_42
#define BWCS_INFO_42_size "d"
#define BWCS_INFO_42 BWCS_INFO_42__enum,BWCS_INFO_42_size

// BWCS_INFO_43
#define BWCS_INFO_43_size NULL
#define BWCS_INFO_43 BWCS_INFO_43__enum,BWCS_INFO_43_size

// BWCS_INFO_44
#define BWCS_INFO_44_size NULL
#define BWCS_INFO_44 BWCS_INFO_44__enum,BWCS_INFO_44_size

// BWCS_INFO_45
#define BWCS_INFO_45_size NULL
#define BWCS_INFO_45 BWCS_INFO_45__enum,BWCS_INFO_45_size

// BWCS_INFO_46
#define BWCS_INFO_46_size NULL
#define BWCS_INFO_46 BWCS_INFO_46__enum,BWCS_INFO_46_size

// BWCS_INFO_47
#define BWCS_INFO_47_size NULL
#define BWCS_INFO_47 BWCS_INFO_47__enum,BWCS_INFO_47_size

// BWCS_INFO_48
#define BWCS_INFO_48_size NULL
#define BWCS_INFO_48 BWCS_INFO_48__enum,BWCS_INFO_48_size

// BWCS_INFO_49
#define BWCS_INFO_49_size NULL
#define BWCS_INFO_49 BWCS_INFO_49__enum,BWCS_INFO_49_size

// BWCS_INFO_50
#define BWCS_INFO_50_size NULL
#define BWCS_INFO_50 BWCS_INFO_50__enum,BWCS_INFO_50_size

// BWCS_INFO_51
#define BWCS_INFO_51_size NULL
#define BWCS_INFO_51 BWCS_INFO_51__enum,BWCS_INFO_51_size

// BWCS_INFO_52
#define BWCS_INFO_52_size NULL
#define BWCS_INFO_52 BWCS_INFO_52__enum,BWCS_INFO_52_size

// BWCS_INFO_53
#define BWCS_INFO_53_size NULL
#define BWCS_INFO_53 BWCS_INFO_53__enum,BWCS_INFO_53_size

// BWCS_INFO_54
#define BWCS_INFO_54_size NULL
#define BWCS_INFO_54 BWCS_INFO_54__enum,BWCS_INFO_54_size

// BWCS_INFO_55
#define BWCS_INFO_55_size NULL
#define BWCS_INFO_55 BWCS_INFO_55__enum,BWCS_INFO_55_size

// BWCS_INFO_56
#define BWCS_INFO_56_size "d"
#define BWCS_INFO_56 BWCS_INFO_56__enum,BWCS_INFO_56_size

// WMT_INFO_UPDATE_SLEEP_TIME
#define WMT_INFO_UPDATE_SLEEP_TIME_size "d"
#define WMT_INFO_UPDATE_SLEEP_TIME WMT_INFO_UPDATE_SLEEP_TIME__enum,WMT_INFO_UPDATE_SLEEP_TIME_size

// WMT_INFO_CHIP_REINIT
#define WMT_INFO_CHIP_REINIT_size NULL
#define WMT_INFO_CHIP_REINIT WMT_INFO_CHIP_REINIT__enum,WMT_INFO_CHIP_REINIT_size

// WMT_INFO_TST_INJECT_STRING_HANDLER
#define WMT_INFO_TST_INJECT_STRING_HANDLER_size NULL
#define WMT_INFO_TST_INJECT_STRING_HANDLER WMT_INFO_TST_INJECT_STRING_HANDLER__enum,WMT_INFO_TST_INJECT_STRING_HANDLER_size

// WMT_INFO_RETRIEVE_EG_EVENT
#define WMT_INFO_RETRIEVE_EG_EVENT_size NULL
#define WMT_INFO_RETRIEVE_EG_EVENT WMT_INFO_RETRIEVE_EG_EVENT__enum,WMT_INFO_RETRIEVE_EG_EVENT_size

// WMT_INFO_WAKEUP_RETRIEVE_EG_EVENT
#define WMT_INFO_WAKEUP_RETRIEVE_EG_EVENT_size NULL
#define WMT_INFO_WAKEUP_RETRIEVE_EG_EVENT WMT_INFO_WAKEUP_RETRIEVE_EG_EVENT__enum,WMT_INFO_WAKEUP_RETRIEVE_EG_EVENT_size

// WMT_INFO_CLRSTATE_RETRIEVE_EG_EVENT
#define WMT_INFO_CLRSTATE_RETRIEVE_EG_EVENT_size NULL
#define WMT_INFO_CLRSTATE_RETRIEVE_EG_EVENT WMT_INFO_CLRSTATE_RETRIEVE_EG_EVENT__enum,WMT_INFO_CLRSTATE_RETRIEVE_EG_EVENT_size

// WMT_INFO_GPIO_RETRIEVE_EG_EVENT
#define WMT_INFO_GPIO_RETRIEVE_EG_EVENT_size NULL
#define WMT_INFO_GPIO_RETRIEVE_EG_EVENT WMT_INFO_GPIO_RETRIEVE_EG_EVENT__enum,WMT_INFO_GPIO_RETRIEVE_EG_EVENT_size

// WMT_INFO_SET_EG_EVENT
#define WMT_INFO_SET_EG_EVENT_size NULL
#define WMT_INFO_SET_EG_EVENT WMT_INFO_SET_EG_EVENT__enum,WMT_INFO_SET_EG_EVENT_size

// WMT_INFO_WAKEUP_SET_EG_EVENT
#define WMT_INFO_WAKEUP_SET_EG_EVENT_size NULL
#define WMT_INFO_WAKEUP_SET_EG_EVENT WMT_INFO_WAKEUP_SET_EG_EVENT__enum,WMT_INFO_WAKEUP_SET_EG_EVENT_size

// WMT_INFO_CLRSTATE_SET_EG_EVENT
#define WMT_INFO_CLRSTATE_SET_EG_EVENT_size NULL
#define WMT_INFO_CLRSTATE_SET_EG_EVENT WMT_INFO_CLRSTATE_SET_EG_EVENT__enum,WMT_INFO_CLRSTATE_SET_EG_EVENT_size

// WMT_INFO_GPIO_SET_EG_EVENT
#define WMT_INFO_GPIO_SET_EG_EVENT_size NULL
#define WMT_INFO_GPIO_SET_EG_EVENT WMT_INFO_GPIO_SET_EG_EVENT__enum,WMT_INFO_GPIO_SET_EG_EVENT_size

// WMT_INFO_CHIP_WAKE_UP
#define WMT_INFO_CHIP_WAKE_UP_size NULL
#define WMT_INFO_CHIP_WAKE_UP WMT_INFO_CHIP_WAKE_UP__enum,WMT_INFO_CHIP_WAKE_UP_size

// WMT_INFO_FM_I2C_ABNORMAL
#define WMT_INFO_FM_I2C_ABNORMAL_size NULL
#define WMT_INFO_FM_I2C_ABNORMAL WMT_INFO_FM_I2C_ABNORMAL__enum,WMT_INFO_FM_I2C_ABNORMAL_size

// WMT_INFO_FM_I2C_POWER_OFF
#define WMT_INFO_FM_I2C_POWER_OFF_size NULL
#define WMT_INFO_FM_I2C_POWER_OFF WMT_INFO_FM_I2C_POWER_OFF__enum,WMT_INFO_FM_I2C_POWER_OFF_size

// WMT_INFO_FM_I2C_POWER_OFF_ABNORMAL
#define WMT_INFO_FM_I2C_POWER_OFF_ABNORMAL_size NULL
#define WMT_INFO_FM_I2C_POWER_OFF_ABNORMAL WMT_INFO_FM_I2C_POWER_OFF_ABNORMAL__enum,WMT_INFO_FM_I2C_POWER_OFF_ABNORMAL_size

// WMT_INFO_RESET_STP_BUF
#define WMT_INFO_RESET_STP_BUF_size "d"
#define WMT_INFO_RESET_STP_BUF WMT_INFO_RESET_STP_BUF__enum,WMT_INFO_RESET_STP_BUF_size

// WMT_INFO_UART_OPEN_FAIL
#define WMT_INFO_UART_OPEN_FAIL_size NULL
#define WMT_INFO_UART_OPEN_FAIL WMT_INFO_UART_OPEN_FAIL__enum,WMT_INFO_UART_OPEN_FAIL_size

// WMT_INFO_UNMASK_WAKEUP_EINT
#define WMT_INFO_UNMASK_WAKEUP_EINT_size NULL
#define WMT_INFO_UNMASK_WAKEUP_EINT WMT_INFO_UNMASK_WAKEUP_EINT__enum,WMT_INFO_UNMASK_WAKEUP_EINT_size

// WMT_INFO_UART_TEST_HANDLER
#define WMT_INFO_UART_TEST_HANDLER_size NULL
#define WMT_INFO_UART_TEST_HANDLER WMT_INFO_UART_TEST_HANDLER__enum,WMT_INFO_UART_TEST_HANDLER_size

// WMT_INFO_SET_UART_TEST_HANDLER
#define WMT_INFO_SET_UART_TEST_HANDLER_size NULL
#define WMT_INFO_SET_UART_TEST_HANDLER WMT_INFO_SET_UART_TEST_HANDLER__enum,WMT_INFO_SET_UART_TEST_HANDLER_size

// WMT_INFO_SET_UART_TEST_HANDLER_STRUCT
#define WMT_INFO_SET_UART_TEST_HANDLER_STRUCT_size "…d"
#define WMT_INFO_SET_UART_TEST_HANDLER_STRUCT WMT_INFO_SET_UART_TEST_HANDLER_STRUCT__enum,WMT_INFO_SET_UART_TEST_HANDLER_STRUCT_size


#endif // WMT_TRC_GEN.H
