/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   camera_af_para.h
 *
 * Project:
 * --------
 *   MT6238
 *
 * Description:
 * ------------
 *   Camera Operation Parameter 
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 ****************************************************************************/
#ifndef _CAMERA_AF_PARA_H_
#define _CAMERA_AF_PARA_H_

#if defined(ISP_SUPPORT)

#include "isp_comm_if.h"

/*Dual camera all combination here*/
#if(defined(ABICO_WZ36A333_OV3640_MD118B))
	#include "camera_af_para_ABICO_WZ36A333_OV3640_MD118B.h"
#endif

#if(defined(ACME_900_0043_00_OV3640_AD5398))
	#include "camera_af_para_ACME_900_0043_00_OV3640_AD5398.h"
#endif	

#if(AKEER_OV5642_AD5820)
        #include "camera_af_para_AKEER_OV5642_AD5820.h"
#endif

#if(defined(FOXCONN_ATCM_5011_MT9P012_AD5820))
	#include "camera_af_para_FOXCONN_ATCM_5011_MT9P012_AD5820.h"
#endif

#if(defined(FOXLINK_FM50AF_04_MT9P012_MD218B))
	#include "camera_af_para_FOXLINK_FM50AF_04_MT9P012_MD218B.h"
#endif	

#if(defined(FOXLINK_M30AF_26_OV3640_MD115))
	#include "camera_af_para_FOXLINK_M30AF_26_OV3640_MD115.h"
#endif	

#if(SUNNY_S5M03G_MT9P012_AD5820)
        #include "camera_af_para_SUNNY_S5M03G_MT9P012_AD5820.h"
#endif

#if(SUNNY_S5S01D_S5K3E2FX_INTERNAL)
        #include "camera_af_para_SUNNY_S5S01D_S5K3E2FX_INTERNAL.h"
#endif

#if(SUNNY_Q5M04B_MT9P015_BH6412GUL)
        #include "camera_af_para_SUNNY_Q5M04B_MT9P015_BH6412GUL.h"
#endif

#if(defined(SUNNY_P5D01A_ET8EV3_AD5820))
        #include "camera_af_para_SUNNY_P5D01A_ET8EV3_AD5820.h"
#endif

#define CAMERA_AF_DEFAULT_VALUE {0}

//
/*all combination here*/
#if (defined(MT9P012_RAW))
#if( defined(FOXLINK_FM50AF_04_MT9P012_MD218B))
 	#define MT9P012_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXLINK_FM50AF_04_MT9P012_MD218B
#elif( defined(FOXCONN_ATCM_5011_MT9P012_AD5820))
 	#define MT9P012_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXCONN_ATCM_5011_MT9P012_AD5820
#elif( defined(SUNNY_S5M03G_MT9P012_AD5820))
        #define MT9P012_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_S5M03G_MT9P012_AD5820
#else 
 	#define MT9P012_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(MT9P013_RAW))
#if( defined(FOXLINK_FM50AF_04_MT9P012_MD218B))
 	#define MT9P013_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXLINK_FM50AF_04_MT9P012_MD218B
#elif( defined(FOXCONN_ATCM_5011_MT9P012_AD5820))
 	#define MT9P013_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXCONN_ATCM_5011_MT9P012_AD5820
#elif( defined(SUNNY_S5M03G_MT9P012_AD5820))
        #define MT9P013_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_S5M03G_MT9P012_AD5820
#else 
 	#define MT9P013_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(MT9P012_MIPI_RAW))
#if( defined(SUNNY_S5M03G_MT9P012_AD5820))
 	#define MT9P012_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_S5M03G_MT9P012_AD5820
#else 
 	#define MT9P012_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(MT9P015_RAW))
#if(defined(SUNNY_Q5M04B_MT9P015_BH6412GUL))
    #define MT9P015_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_Q5M04B_MT9P015_BH6412GUL
#else
    #define MT9P015_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

//add for all raw sensor
#if (defined(OV2640_RAW))
#if( defined(FOXLINK_FO20AF_25_OV2640_MD115))
	#define OV2640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXLINK_FO20AF_25_OV2640_MD115
#elif( defined(ABICO_VQ26A10_OV2640_AD5398))
	#define OV2640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_ABICO_VQ26A10_OV2640_AD5398
#elif( defined(YAHSIN_M20P1A_BGK_OV2640_MD115))
	#define OV2640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_YAHSIN_M20P1A_BGK_OV2640_MD115
#elif( defined(SUNNY_8212E_OV2640_AD5398))
	#define OV2640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_8212E_OV2640_AD5398
#else 
	#define OV2640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(OV3640_RAW))
#if( defined(FOXLINK_M30AF_26_OV3640_MD115))
  	#define OV3640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXLINK_M30AF_26_OV3640_MD115
#elif( defined(ABICO_WZ36A333_OV3640_MD118B))
	#define OV3640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_ABICO_WZ36A333_OV3640_MD118B
#elif( defined(ACME_900_0043_00_OV3640_AD5398))
	#define OV3640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_ACME_900_0043_00_OV3640_AD5398
#else 
	#define OV3640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(OV5650_RAW))
#if( defined(FOXLINK_M30AF_26_OV5650_MD115))
  	#define OV5650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_FOXLINK_M30AF_26_OV5650_MD115
#elif( defined(ABICO_WZ36A333_OV5650_MD118B))
	#define OV5650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_ABICO_WZ36A333_OV5650_MD118B
#elif( defined(ACME_900_0043_00_OV5650_AD5398))
	#define OV5650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_ACME_900_0043_00_OV5650_AD5398
#else 
	#define OV5650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif


#if (defined(OV5642_RAW))
#if ( defined(AKEER_OV5642_AD5820))
 	#define OV5642_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_AKEER_OV5642_AD5820
#else
	#define OV5642_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(OV5642_MIPI_RAW))
#if ( defined(AKEER_OV5642_AD5820))
 	#define OV5642_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_AKEER_OV5642_AD5820
#else
	#define OV5642_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif

#if (defined(ET8EV3_MIPI_RAW))
#if( defined(SUNNY_P5D01A_ET8EV3_AD5820))
 	#define ET8EV3_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE_SUNNY_P5D01A_ET8EV3_AD5820
#else 
 	#define ET8EV3_MIPI_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#endif


//For verify the dual camera.
#ifndef OV3640_CAMERA_AF_DEFAULT_VALUE
	#define OV3640_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif

#ifndef OV5650_CAMERA_AF_DEFAULT_VALUE
	#define OV5650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif

#ifndef OV2650_CAMERA_AF_DEFAULT_VALUE
	#define OV2650_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif

#ifndef S5K3E2FX_CAMERA_AF_DEFAULT_VALUE
	#define S5K3E2FX_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#ifndef OV3647_CAMERA_AF_DEFAULT_VALUE
	#define OV3647_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif
#ifndef MT9T013_CAMERA_AF_DEFAULT_VALUE
	#define MT9T013_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif

#ifndef OV2655_CAMERA_AF_DEFAULT_VALUE
        #define OV2655_CAMERA_AF_DEFAULT_VALUE CAMERA_AF_DEFAULT_VALUE
#endif


#define	AF_SINGLE_MODE_IDX		(0)
#define	AF_MULTI_ZONE_MODE_IDX	(0)
#define	AF_FULL_SEARCH_MODE_IDX	(0)
#define	AF_CONTINUOUS_MODE_IDX	(1)

#endif // _CAMERA_AF_PARA_H_

#endif //#if defined(ISP_SUPPORT)

	
