/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*#80FF80
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   image_sensor.c
 *
 * Project:
 * --------
 *   Maui_sw
 *
 * Description:
 * ------------
 *   Image sensor driver function
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#include "image_sensor.h"
#include "sensor_comm_def.h"

#if defined(__MM_DCM_SUPPORT__)
#pragma arm section code = "DYNAMIC_CODE_CAMCAL_ROCODE", rodata = "DYNAMIC_CODE_CAMCAL_ROCODE"
#endif

// for camera HAL
IMAGE_SENSOR_LIST_STRUCT SensorList[MAX_SENSOR_SUPPORT_NUMBER + 1] =
{
/*RAW SENSOR*/
#if(defined(MT9P012_RAW_MAIN))
	ADD_SENSOR(MT9P012_SENSOR_ID,MT9P012,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9P012_RAW_SUB))
	ADD_SENSOR(MT9P012_SENSOR_ID,MT9P012,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9P012_RAW_BAK1))
	ADD_SENSOR(MT9P012_SENSOR_ID,MT9P012,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9P012_RAW_SUB_BAK1))
	ADD_SENSOR(MT9P012_SENSOR_ID,MT9P012,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9P012_MIPI_RAW_MAIN))
    ADD_SENSOR(MT9P012_MIPI_SENSOR_ID,MT9P012Mipi,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9P012_MIPI_RAW_SUB))
	ADD_SENSOR(MT9P012_MIPI_SENSOR_ID,MT9P012Mipi,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9P012_MIPI_RAW_BAK1))
    ADD_SENSOR(MT9P012_MIPI_SENSOR_ID,MT9P012Mipi,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9P012_MIPI_RAW_SUB_BAK1))
	ADD_SENSOR(MT9P012_MIPI_SENSOR_ID,MT9P012Mipi,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9P013_RAW_MAIN))
	ADD_SENSOR(MT9P013_SENSOR_ID,MT9P013,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9P013_RAW_SUB))
	ADD_SENSOR(MT9P013_SENSOR_ID,MT9P013,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9P013_RAW_BAK1))
	ADD_SENSOR(MT9P013_SENSOR_ID,MT9P013,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9P013_RAW_SUB_BAK1))
	ADD_SENSOR(MT9P013_SENSOR_ID,MT9P013,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9P015_RAW_MAIN))
	ADD_SENSOR(MT9P015_SENSOR_ID,MT9P015,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9P015_RAW_SUB))
	ADD_SENSOR(MT9P015_SENSOR_ID,MT9P015,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9P015_RAW_BAK1))
	ADD_SENSOR(MT9P015_SENSOR_ID,MT9P015,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9P015_RAW_SUB_BAK1))
	ADD_SENSOR(MT9P015_SENSOR_ID,MT9P015,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9T013_RAW_MAIN))
	ADD_SENSOR(MT9T013_SENSOR_ID,MT9T013,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9T013_RAW_SUB))
	ADD_SENSOR(MT9T013_SENSOR_ID,MT9T013,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9T013_RAW_BAK1))
	ADD_SENSOR(MT9T013_SENSOR_ID,MT9T013,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9T013_RAW_SUB_BAK1))
	ADD_SENSOR(MT9T013_SENSOR_ID,MT9T013,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV5642_RAW_MAIN))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5642_RAW_SUB))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5642_RAW_BAK1))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5642_RAW_SUB_BAK1))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV5642_MIPI_RAW_MAIN))
	ADD_SENSOR(OV5642_MIPI_SENSOR_ID,OV5642Mipi,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5642_MIPI_RAW_SUB))
	ADD_SENSOR(OV5642_MIPI_SENSOR_ID,OV5642Mipi,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5642_MIPI_RAW_BAK1))
	ADD_SENSOR(OV5642_MIPI_SENSOR_ID,OV5642Mipi,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5642_MIPI_RAW_SUB_BAK1))
	ADD_SENSOR(OV5642_MIPI_SENSOR_ID,OV5642Mipi,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV5650_RAW_MAIN))
	ADD_SENSOR(OV5650_SENSOR_ID,OV5650,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5650_RAW_SUB))
	ADD_SENSOR(OV5650_SENSOR_ID,OV5650,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5650_RAW_BAK1))
	ADD_SENSOR(OV5650_SENSOR_ID,OV5650,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5650_RAW_SUB_BAK1))
	ADD_SENSOR(OV5650_SENSOR_ID,OV5650,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV5650_MIPI_RAW_MAIN))
	ADD_SENSOR(OV5650_MIPI_SENSOR_ID,OV5650Mipi,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5650_MIPI_RAW_SUB))
	ADD_SENSOR(OV5650_MIPI_SENSOR_ID,OV5650Mipi,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5650_MIPI_RAW_BAK1))
	ADD_SENSOR(OV5650_MIPI_SENSOR_ID,OV5650Mipi,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5650_MIPI_RAW_SUB_BAK1))
	ADD_SENSOR(OV5650_MIPI_SENSOR_ID,OV5650Mipi,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV3640_RAW_MAIN))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV3640_RAW_SUB))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV3640_RAW_BAK1))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV3640_RAW_SUB_BAK1))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV3647_RAW_MAIN))
	ADD_SENSOR(OV3647_SENSOR_ID,OV3647,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV3647_RAW_SUB))
	ADD_SENSOR(OV3647_SENSOR_ID,OV3647,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV3647_RAW_BAK1))
	ADD_SENSOR(OV3647_SENSOR_ID,OV3647,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV3647_RAW_SUB_BAK1))
	ADD_SENSOR(OV3647_SENSOR_ID,OV3647,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV2655_RAW_MAIN))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV2655_RAW_SUB))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV2655_RAW_BAK1))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV2655_RAW_SUB_BAK1))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV2640_RAW_MAIN))
	ADD_SENSOR(OV2640_SENSOR_ID,OV2640,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV2640_RAW_SUB))
	ADD_SENSOR(OV2640_SENSOR_ID,OV2640,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV2640_RAW_BAK1))
	ADD_SENSOR(OV2640_SENSOR_ID,OV2640,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV2640_RAW_SUB_BAK1))
	ADD_SENSOR(OV2640_SENSOR_ID,OV2640,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(S5K3E2FX_RAW_MAIN))
	ADD_SENSOR(S5K3E2FX_SENSOR_ID,S5K3E2FX,IMAGE_SENSOR_MAIN),
#endif
#if(defined(S5K3E2FX_RAW_SUB))
	ADD_SENSOR(S5K3E2FX_SENSOR_ID,S5K3E2FX,IMAGE_SENSOR_SUB),
#endif

#if(defined(S5K3E2FX_RAW_BAK1))
	ADD_SENSOR(S5K3E2FX_SENSOR_ID,S5K3E2FX,IMAGE_SENSOR_BAK1),
#endif
#if(defined(S5K3E2FX_RAW_SUB_BAK1))
	ADD_SENSOR(S5K3E2FX_SENSOR_ID,S5K3E2FX,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SID020A_RAW_MAIN))
	ADD_SENSOR(SID020A_SENSOR_ID,SID020A,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SID020A_RAW_SUB))
	ADD_SENSOR(SID020A_SENSOR_ID,SID020A,IMAGE_SENSOR_SUB),
#endif

#if(defined(SID020A_RAW_BAK1))
	ADD_SENSOR(SID020A_SENSOR_ID,SID020A,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SID020A_RAW_SUB_BAK1))
	ADD_SENSOR(SID020A_SENSOR_ID,SID020A,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(NOON200PC51_RAW_MAIN))
	ADD_SENSOR(NOON200PC51_SENSOR_ID,NOON200PC51,IMAGE_SENSOR_MAIN),
#endif
#if(defined(NOON200PC51_RAW_SUB))
	ADD_SENSOR(NOON200PC51_SENSOR_ID,NOON200PC51,IMAGE_SENSOR_SUB),
#endif

#if(defined(NOON200PC51_RAW_BAK1))
	ADD_SENSOR(NOON200PC51_SENSOR_ID,NOON200PC51,IMAGE_SENSOR_BAK1),
#endif
#if(defined(NOON200PC51_RAW_SUB_BAK1))
	ADD_SENSOR(NOON200PC51_SENSOR_ID,NOON200PC51,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(ET8EV3_MIPI_RAW_MAIN))
	ADD_SENSOR(ET8EV3_MIPI_SENSOR_ID,ET8EV3Mipi,IMAGE_SENSOR_MAIN),
#endif
#if(defined(ET8EV3_MIPI_RAW_SUB))
	ADD_SENSOR(ET8EV3_MIPI_SENSOR_ID,ET8EV3Mipi,IMAGE_SENSOR_SUB),
#endif

/*YUV SENSOR*/
#if(defined(OV5642_YUV_MAIN))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5642_YUV_SUB))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5642_YUV_BAK1))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5642_YUV_SUB_BAK1))
	ADD_SENSOR(OV5642_SENSOR_ID,OV5642,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV5640_YUV_MAIN))
	ADD_SENSOR(OV5640_SENSOR_ID,OV5640,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV5640_YUV_SUB))
	ADD_SENSOR(OV5640_SENSOR_ID,OV5640,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV5640_YUV_BAK1))
	ADD_SENSOR(OV5640_SENSOR_ID,OV5640,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV5640_YUV_SUB_BAK1))
	ADD_SENSOR(OV5640_SENSOR_ID,OV5640,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV3640_YUV_MAIN) || defined(OV3640VGA_YUV_MAIN))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV3640_YUV_SUB) || defined(OV3640VGA_YUV_SUB))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV3640_YUV_BAK1) || defined(OV3640VGA_YUV_BAK1))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV3640_YUV_SUB_BAK1) || defined(OV3640VGA_YUV_SUB_BAK1))
	ADD_SENSOR(OV3640_SENSOR_ID,OV3640,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV2659_YUV_MAIN))
	ADD_SENSOR(OV2659_SENSOR_ID,OV2659,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV2659_YUV_SUB))
	ADD_SENSOR(OV2659_SENSOR_ID,OV2659,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV2659_YUV_BAK1))
	ADD_SENSOR(OV2659_SENSOR_ID,OV2659,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV2659_YUV_SUB_BAK1))
	ADD_SENSOR(OV2659_SENSOR_ID,OV2659,IMAGE_SENSOR_SUB_BAK1),
#endif
#if(defined(OV2655_YUV_MAIN))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV2655_YUV_SUB))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV2655_YUV_BAK1))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV2655_YUV_SUB_BAK1))
	ADD_SENSOR(OV2655_SENSOR_ID,OV2655,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV2650_YUV_MAIN))
	ADD_SENSOR(OV2650_SENSOR_ID,OV2650,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV2650_YUV_SUB))
	ADD_SENSOR(OV2650_SENSOR_ID,OV2650,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV2650_YUV_BAK1))
	ADD_SENSOR(OV2650_SENSOR_ID,OV2650,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV2650_YUV_SUB_BAK1))
	ADD_SENSOR(OV2650_SENSOR_ID,OV2650,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV9665_YUV_MAIN))
	ADD_SENSOR(OV9665_SENSOR_ID,OV9665,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV9665_YUV_SUB))
	ADD_SENSOR(OV9665_SENSOR_ID,OV9665,IMAGE_SENSOR_SUB),
#endif
#if(defined(OV9665_YUV_BAK1))
	ADD_SENSOR(OV9665_SENSOR_ID,OV9665,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV9665_YUV_SUB_BAK1))
	ADD_SENSOR(OV9665_SENSOR_ID,OV9665,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9T113_YUV_MAIN))
	ADD_SENSOR(MT9T113_SENSOR_ID,MT9T113,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9T113_YUV_SUB))
	ADD_SENSOR(MT9T113_SENSOR_ID,MT9T113,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9T113_YUV_BAK1))
	ADD_SENSOR(MT9T113_SENSOR_ID,MT9T113,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9T113_YUV_SUB_BAK1))
	ADD_SENSOR(MT9T113_SENSOR_ID,MT9T113,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(BF3703_YUV_MAIN))
	ADD_SENSOR(BF3703_SENSOR_ID,BF3703,IMAGE_SENSOR_MAIN),
#endif
#if(defined(BF3703_YUV_SUB))
	ADD_SENSOR(BF3703_SENSOR_ID,BF3703,IMAGE_SENSOR_SUB),
#endif

#if(defined(BF3703_YUV_BAK1))
	ADD_SENSOR(BF3703_SENSOR_ID,BF3703,IMAGE_SENSOR_BAK1),
#endif
#if(defined(BF3703_YUV_SUB_BAK1))
	ADD_SENSOR(BF3703_SENSOR_ID,BF3703,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIV121D_YUV_MAIN))
	ADD_SENSOR(SIV121D_SENSOR_ID,SIV121D,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIV121D_YUV_SUB))
	ADD_SENSOR(SIV121D_SENSOR_ID,SIV121D,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIV121D_YUV_BAK1))
	ADD_SENSOR(SIV121D_SENSOR_ID,SIV121D,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIV121D_YUV_SUB_BAK1))
	ADD_SENSOR(SIV121D_SENSOR_ID,SIV121D,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV7675_YUV_MAIN))
	ADD_SENSOR(OV7675_SENSOR_ID,OV7675,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV7675_YUV_SUB))
	ADD_SENSOR(OV7675_SENSOR_ID,OV7675,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV7675_YUV_BAK1))
	ADD_SENSOR(OV7675_SENSOR_ID,OV7675,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV7675_YUV_SUB_BAK1))
	ADD_SENSOR(OV7675_SENSOR_ID,OV7675,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV7670_YUV_MAIN))
	ADD_SENSOR(OV7670_SENSOR_ID,OV7670,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV7670_YUV_SUB))
	ADD_SENSOR(OV7670_SENSOR_ID,OV7670,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV7670_YUV_BAK1))
	ADD_SENSOR(OV7670_SENSOR_ID,OV7670,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV7670_YUV_SUB_BAK1))
	ADD_SENSOR(OV7670_SENSOR_ID,OV7670,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(OV7690_YUV_MAIN))
	ADD_SENSOR(OV7690_SENSOR_ID,OV7690,IMAGE_SENSOR_MAIN),
#endif
#if(defined(OV7690_YUV_SUB))
	ADD_SENSOR(OV7690_SENSOR_ID,OV7690,IMAGE_SENSOR_SUB),
#endif

#if(defined(OV7690_YUV_BAK1))
	ADD_SENSOR(OV7690_SENSOR_ID,OV7690,IMAGE_SENSOR_BAK1),
#endif
#if(defined(OV7690_YUV_SUB_BAK1))
	ADD_SENSOR(OV7690_SENSOR_ID,OV7690,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(S5K5BAFX_YUV_MAIN))
	ADD_SENSOR(S5K5BAFX_SENSOR_ID,S5K5BAFX,IMAGE_SENSOR_MAIN),
#endif
#if(defined(S5K5BAFX_YUV_SUB))
	ADD_SENSOR(S5K5BAFX_SENSOR_ID,S5K5BAFX,IMAGE_SENSOR_SUB),
#endif

#if(defined(S5K5BAFX_YUV_BAK1))
	ADD_SENSOR(S5K5BAFX_SENSOR_ID,S5K5BAFX,IMAGE_SENSOR_BAK1),
#endif
#if(defined(S5K5BAFX_YUV_SUB_BAK1))
	ADD_SENSOR(S5K5BAFX_SENSOR_ID,S5K5BAFX,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(S5KA3DFX_YUV_MAIN))
	ADD_SENSOR(S5KA3DFX_SENSOR_ID,S5KA3DFX,IMAGE_SENSOR_MAIN),
#endif
#if(defined(S5KA3DFX_YUV_SUB))
	ADD_SENSOR(S5KA3DFX_SENSOR_ID,S5KA3DFX,IMAGE_SENSOR_SUB),
#endif

#if(defined(S5K5CAGA_YUV_MAIN))
	ADD_SENSOR(S5K5CAGA_SENSOR_ID,S5K5CAGA,IMAGE_SENSOR_MAIN),
#endif
#if(defined(S5K5CAGA_YUV_SUB))
	ADD_SENSOR(S5K5CAGA_SENSOR_ID,S5K5CAGA,IMAGE_SENSOR_SUB),
#endif
#if(defined(S5KA3DFX_YUV_BAK1))
	ADD_SENSOR(S5KA3DFX_SENSOR_ID,S5KA3DFX,IMAGE_SENSOR_BAK1),
#endif
#if(defined(S5KA3DFX_YUV_SUB_BAK1))
	ADD_SENSOR(S5KA3DFX_SENSOR_ID,S5KA3DFX,IMAGE_SENSOR_SUB_BAK1),
#endif
#if(defined(S5K4ECGX_YUV_MAIN))
	ADD_SENSOR(S5K4ECGX_SENSOR_ID,S5K4ECGX,IMAGE_SENSOR_MAIN),
#endif
#if(defined(S5K4ECGX_YUV_SUB))
	ADD_SENSOR(S5K4ECGX_SENSOR_ID,S5K4ECGX,IMAGE_SENSOR_SUB),
#endif

#if(defined(SID130B_YUV_MAIN))
	ADD_SENSOR(SID130B_SENSOR_ID,SID130B,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SID130B_YUV_SUB))
	ADD_SENSOR(SID130B_SENSOR_ID,SID130B,IMAGE_SENSOR_SUB),
#endif

#if(defined(SID130B_YUV_BAK1))
	ADD_SENSOR(SID130B_SENSOR_ID,SID130B,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SID130B_YUV_SUB_BAK1))
	ADD_SENSOR(SID130B_SENSOR_ID,SID130B,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIM120C_YUV_MAIN))
	ADD_SENSOR(SIM120C_SENSOR_ID,SIM120C,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIM120C_YUV_SUB))
	ADD_SENSOR(SIM120C_SENSOR_ID,SIM120C,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIM120C_YUV_BAK1))
	ADD_SENSOR(SIM120C_SENSOR_ID,SIM120C,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIM120C_YUV_SUB_BAK1))
	ADD_SENSOR(SIM120C_SENSOR_ID,SIM120C,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIV100B_YUV_MAIN))
	ADD_SENSOR(SIV100B_SENSOR_ID,SIV100B,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIV100B_YUV_SUB))
	ADD_SENSOR(SIV100B_SENSOR_ID,SIV100B,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIV100B_YUV_BAK1))
	ADD_SENSOR(SIV100B_SENSOR_ID,SIV100B,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIV100B_YUV_SUB_BAK1))
	ADD_SENSOR(SIV100B_SENSOR_ID,SIV100B,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIV120B_YUV_MAIN))
	ADD_SENSOR(SIV120B_SENSOR_ID,SIV120B,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIV120B_YUV_SUB))
	ADD_SENSOR(SIV120B_SENSOR_ID,SIV120B,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIV120B_YUV_BAK1))
	ADD_SENSOR(SIV120B_SENSOR_ID,SIV120B,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIV120B_YUV_SUB_BAK1))
	ADD_SENSOR(SIV120B_SENSOR_ID,SIV120B,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9D115_YUV_MAIN))
	ADD_SENSOR(MT9D115_SENSOR_ID,MT9D115,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9D115_YUV_SUB))
	ADD_SENSOR(MT9D115_SENSOR_ID,MT9D115,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9D115_YUV_BAK1))
	ADD_SENSOR(MT9D115_SENSOR_ID,MT9D115,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9D115_YUV_SUB_BAK1))
	ADD_SENSOR(MT9D115_SENSOR_ID,MT9D115,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIC110A_YUV_MAIN))
	ADD_SENSOR(SIC110A_SENSOR_ID,SIC110A,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIC110A_YUV_SUB))
	ADD_SENSOR(SIC110A_SENSOR_ID,SIC110A,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIC110A_YUV_BAK1))
	ADD_SENSOR(SIC110A_SENSOR_ID,SIC110A,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIC110A_YUV_SUB_BAK1))
	ADD_SENSOR(SIC110A_SENSOR_ID,SIC110A,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9D112_YUV_MAIN))
	ADD_SENSOR(MT9D112_SENSOR_ID,MT9D112,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9D112_YUV_SUB))
	ADD_SENSOR(MT9D112_SENSOR_ID,MT9D112,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9D112_YUV_BAK1))
	ADD_SENSOR(MT9D112_SENSOR_ID,MT9D112,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9D112_YUV_SUB_BAK1))
	ADD_SENSOR(MT9D112_SENSOR_ID,MT9D112,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(MT9D113_YUV_MAIN))
	ADD_SENSOR(MT9D113_SENSOR_ID,MT9D113,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9D113_YUV_SUB))
	ADD_SENSOR(MT9D113_SENSOR_ID,MT9D113,IMAGE_SENSOR_SUB),
#endif

#if(defined(MT9D113_YUV_BAK1))
	ADD_SENSOR(MT9D113_SENSOR_ID,MT9D113,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MT9D113_YUV_SUB_BAK1))
	ADD_SENSOR(MT9D113_SENSOR_ID,MT9D113,IMAGE_SENSOR_SUB_BAK1),
#endif
#if(defined(MT9P111_YUV_MAIN))
	ADD_SENSOR(MT9P111_SENSOR_ID,MT9P111,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MT9P111_YUV_SUB))
	ADD_SENSOR(MT9P111_SENSOR_ID,MT9P111,IMAGE_SENSOR_SUB),
#endif

#if(defined(HI251_YUV_MAIN))
	ADD_SENSOR(HI251_SENSOR_ID,HI251,IMAGE_SENSOR_MAIN),
#endif
#if(defined(HI251_YUV_SUB))
	ADD_SENSOR(HI251_SENSOR_ID,HI251,IMAGE_SENSOR_SUB),
#endif

#if(defined(HI251_YUV_BAK1))
	ADD_SENSOR(HI251_SENSOR_ID,HI251,IMAGE_SENSOR_BAK1),
#endif
#if(defined(HI251_YUV_SUB_BAK1))
	ADD_SENSOR(HI251_SENSOR_ID,HI251,IMAGE_SENSOR_SUB_BAK1),
#endif
#if(defined(HI253_YUV_MAIN))
	ADD_SENSOR(HI253_SENSOR_ID,HI253,IMAGE_SENSOR_MAIN),
#endif
#if(defined(HI251_YUV_SUB))
	ADD_SENSOR(HI253_SENSOR_ID,HI253,IMAGE_SENSOR_SUB),
#endif

#if(defined(HI253_YUV_BAK1))
	ADD_SENSOR(HI253_SENSOR_ID,HI253,IMAGE_SENSOR_BAK1),
#endif
#if(defined(HI251_YUV_SUB_BAK1))
	ADD_SENSOR(HI253_SENSOR_ID,HI253,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(GT2005_YUV_MAIN))
	ADD_SENSOR(GT2005_SENSOR_ID,GT2005,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GT2005_YUV_SUB))
	ADD_SENSOR(GT2005_SENSOR_ID,GT2005,IMAGE_SENSOR_SUB),
#endif

#if(defined(GT2005_YUV_BAK1))
	ADD_SENSOR(GT2005_SENSOR_ID,GT2005,IMAGE_SENSOR_BAK1),
#endif
#if(defined(GT2005_YUV_SUB_BAK1))
	ADD_SENSOR(GT2005_SENSOR_ID,GT2005,IMAGE_SENSOR_SUB_BAK1),
#endif


#if(defined(HI704_YUV_MAIN))
	ADD_SENSOR(HI704_SENSOR_ID,HI704,IMAGE_SENSOR_MAIN),
#endif
#if(defined(HI704_YUV_SUB))
	ADD_SENSOR(HI704_SENSOR_ID,HI704,IMAGE_SENSOR_SUB),
#endif

#if(defined(HI704_YUV_BAK1))
	ADD_SENSOR(HI704_SENSOR_ID,HI704,IMAGE_SENSOR_BAK1),
#endif
#if(defined(HI704_YUV_SUB_BAK1))
	ADD_SENSOR(HI704_SENSOR_ID,HI704,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(PAS6327_YUV_MAIN))
	ADD_SENSOR(PAS6327_SENSOR_ID,PAS6327,IMAGE_SENSOR_MAIN),
#endif
#if(defined(PAS6327_YUV_SUB))
	ADD_SENSOR(PAS6327_SENSOR_ID,PAS6327,IMAGE_SENSOR_SUB),
#endif

#if(defined(PAS6327_YUV_BAK1))
	ADD_SENSOR(PAS6327_SENSOR_ID,PAS6327,IMAGE_SENSOR_BAK1),
#endif
#if(defined(PAS6327_YUV_SUB_BAK1))
	ADD_SENSOR(PAS6327_SENSOR_ID,PAS6327,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(T8ET2_YUV_MAIN))
	ADD_SENSOR(T8ET2_SENSOR_ID,T8ET2,IMAGE_SENSOR_MAIN),
#endif
#if(defined(T8ET2_YUV_SUB))
	ADD_SENSOR(T8ET2_SENSOR_ID,T8ET2,IMAGE_SENSOR_SUB),
#endif

#if(defined(T8ET2_YUV_BAK1))
	ADD_SENSOR(T8ET2_SENSOR_ID,T8ET2,IMAGE_SENSOR_BAK1),
#endif
#if(defined(T8ET2_YUV_SUB_BAK1))
	ADD_SENSOR(T8ET2_SENSOR_ID,T8ET2,IMAGE_SENSOR_SUB_BAK1),
#endif
#if(defined(GC0308_YUV_MAIN))
  ADD_SENSOR(GC0308_SENSOR_ID,GC0308,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC0308_YUV_SUB))
  ADD_SENSOR(GC0308_SENSOR_ID,GC0308,IMAGE_SENSOR_SUB),
#endif
#if(defined(GC0308_YUV_BAK1))
  ADD_SENSOR(GC0308_SENSOR_ID,GC0308,IMAGE_SENSOR_BAK1),
#endif
#if(defined(GC0308_YUV_SUB_BAK1))
  ADD_SENSOR(GC0308_SENSOR_ID,GC0308,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(GC0307_YUV_MAIN))
	ADD_SENSOR(GC0307_SENSOR_ID,GC0307,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC0307_YUV_SUB))
	ADD_SENSOR(GC0307_SENSOR_ID,GC0307,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC0307_YUV_BAK1))
	ADD_SENSOR(GC0307_SENSOR_ID,GC0307,IMAGE_SENSOR_BAK1),
#endif
#if(defined(GC0307_YUV_SUB_BAK1))
	ADD_SENSOR(GC0307_SENSOR_ID,GC0307,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(GC0329_YUV_MAIN))
	ADD_SENSOR(GC0329_SENSOR_ID,GC0329,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC0329_YUV_SUB))
	ADD_SENSOR(GC0329_SENSOR_ID,GC0329,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC0329_YUV_BAK1))
	ADD_SENSOR(GC0329_SENSOR_ID,GC0329,IMAGE_SENSOR_BAK1),
#endif
#if(defined(GC0329_YUV_SUB_BAK1))
	ADD_SENSOR(GC0329_SENSOR_ID,GC0329,IMAGE_SENSOR_SUB_BAK1),
#endif


#if(defined(MC501CB_YUV_MAIN))
	ADD_SENSOR(MC501CB_SENSOR_ID,MC501CB,IMAGE_SENSOR_MAIN),
#endif
#if(defined(MC501CB_YUV_SUB))
	ADD_SENSOR(MC501CB_SENSOR_ID,MC501CB,IMAGE_SENSOR_SUB),
#endif

#if(defined(MC501CB_YUV_BAK1))
	ADD_SENSOR(MC501CB_SENSOR_ID,MC501CB,IMAGE_SENSOR_BAK1),
#endif
#if(defined(MC501CB_YUV_SUB_BAK1))
	ADD_SENSOR(MC501CB_SENSOR_ID,MC501CB,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(NOON010PC30_YUV_MAIN))
	ADD_SENSOR(NOON010PC30_SENSOR_ID,NOON010PC30,IMAGE_SENSOR_MAIN),
#endif
#if(defined(NOON010PC30_YUV_SUB))
	ADD_SENSOR(NOON010PC30_SENSOR_ID,NOON010PC30,IMAGE_SENSOR_SUB),
#endif

#if(defined(NOON010PC30_YUV_BAK1))
	ADD_SENSOR(NOON010PC30_SENSOR_ID,NOON010PC30,IMAGE_SENSOR_BAK1),
#endif
#if(defined(NOON010PC30_YUV_SUB_BAK1))
	ADD_SENSOR(NOON010PC30_SENSOR_ID,NOON010PC30,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(SIC320A_SERIAL_YUV_MAIN))
	ADD_SENSOR(SIC320A_SERIAL_SENSOR_ID,SIC320A_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(SIC320A_SERIAL_YUV_SUB))
	ADD_SENSOR(SIC320A_SERIAL_SENSOR_ID,SIC320A_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(SIC320A_SERIAL_YUV_BAK1))
	ADD_SENSOR(SIC320A_SERIAL_SENSOR_ID,SIC320A_SERIAL,IMAGE_SENSOR_BAK1),
#endif
#if(defined(SIC320A_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(SIC320A_SERIAL_SENSOR_ID,SIC320A_SERIAL,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(GC6113_SERIAL_YUV_MAIN))
	ADD_SENSOR(GC6113_SERIAL_SENSOR_ID,GC6113_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC6113_SERIAL_YUV_SUB))
	ADD_SENSOR(GC6113_SERIAL_SENSOR_ID,GC6113_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC6113_SERIAL_YUV_BAK1))
	ADD_SENSOR(GC6113_SERIAL_SENSOR_ID,GC6113_SERIAL,IMAGE_SENSOR_BAK1),
#endif
#if(defined(GC6113_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(GC6113_SERIAL_SENSOR_ID,GC6113_SERIAL,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(GC6123_SERIAL_YUV_MAIN))
	ADD_SENSOR(GC6123_SERIAL_SENSOR_ID,GC6123_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC6123_SERIAL_YUV_SUB))
	ADD_SENSOR(GC6123_SERIAL_SENSOR_ID,GC6123_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC6123_SERIAL_YUV_BAK1))
	ADD_SENSOR(GC6123_SERIAL_SENSOR_ID,GC6123_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC6123_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(GC6123_SERIAL_SENSOR_ID,GC6123_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC0310_SERIAL_YUV_MAIN))
	ADD_SENSOR(GC0310_SERIAL_SENSOR_ID,GC0310_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC0310_SERIAL_YUV_SUB))
	ADD_SENSOR(GC0310_SERIAL_SENSOR_ID,GC0310_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(GC0310_SERIAL_YUV_BAK1))
	ADD_SENSOR(GC0310_SERIAL_SENSOR_ID,GC0310_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(GC0310_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(GC0310_SERIAL_SENSOR_ID,GC0310_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(HM0155_SERIAL_YUV_MAIN))
	ADD_SENSOR(HM0155_SERIAL_SENSOR_ID,HM0155_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(HM0155_SERIAL_YUV_SUB))
	ADD_SENSOR(HM0155_SERIAL_SENSOR_ID,HM0155_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(HM0155_SERIAL_YUV_BAK1))
	ADD_SENSOR(HM0155_SERIAL_SENSOR_ID,HM0155_SERIAL,IMAGE_SENSOR_BAK1),
#endif
#if(defined(HM0155_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(HM0155_SERIAL_SENSOR_ID,HM0155_SERIAL,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(PAS6180_SERIAL_YUV_MAIN))
	ADD_SENSOR(PAS6180_SERIAL_SENSOR_ID,PAS6180_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(PAS6180_SERIAL_YUV_SUB))
	ADD_SENSOR(PAS6180_SERIAL_SENSOR_ID,PAS6180_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(PAS6180_SERIAL_YUV_BAK1))
	ADD_SENSOR(PAS6180_SERIAL_SENSOR_ID,PAS6180_SERIAL,IMAGE_SENSOR_BAK1),
#endif
#if(defined(PAS6180_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(PAS6180_SERIAL_SENSOR_ID,PAS6180_SERIAL,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(HIQD1_SERIAL_YUV_MAIN))
	ADD_SENSOR(HIQD1_SERIAL_SENSOR_ID,HIQD1_SERIAL,IMAGE_SENSOR_MAIN),
#endif
#if(defined(HIQD1_SERIAL_YUV_SUB))
	ADD_SENSOR(HIQD1_SERIAL_SENSOR_ID,HIQD1_SERIAL,IMAGE_SENSOR_SUB),
#endif

#if(defined(HIQD1_SERIAL_YUV_BAK1))
	ADD_SENSOR(HIQD1_SERIAL_SENSOR_ID,HIQD1_SERIAL,IMAGE_SENSOR_BAK1),
#endif
#if(defined(HIQD1_SERIAL_YUV_SUB_BAK1))
	ADD_SENSOR(HIQD1_SERIAL_SENSOR_ID,HIQD1_SERIAL,IMAGE_SENSOR_SUB_BAK1),
#endif

#if(defined(__ATV_SUPPORT__))
	ADD_SENSOR(mATV_SENSOR_ID,mATV_,IMAGE_SENSOR_MATV),
#endif
};

// for camera HAL
MM_ERROR_CODE_ENUM GetSensorInitFunc(P_IMAGE_SENSOR_LIST_STRUCT *pSensorList)
{
    *pSensorList=&SensorList[0];

	return MM_ERROR_NONE;
}

#if defined(__MM_DCM_SUPPORT__)
#pragma arm section code, rodata
#endif

