/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6261NP. Copyright MediaTek Inc. (C) 2012.
 * Sat Aug 25 21:26:33 2018
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*   Maui_Software
*
* Description:
* ------------
*   
*
* Author:
* -------
*  dongming.li       Generated By DRV TOOL
*
*============================================================================
****************************************************************************/
#ifdef __CUST_NEW__
#include "kal_release.h"
#include "dcl.h"


const unsigned char ADC_ACCESSORYID = 4;
const unsigned char ADC_PCBTMP = DCL_ADC_ERR_CHANNEL_NO;
const unsigned char ADC_CHR_USB = DCL_ADC_ERR_CHANNEL_NO;
const unsigned char ADC_OTG_VBUS = DCL_ADC_ERR_CHANNEL_NO;
const unsigned char ADC_RFTMP = DCL_ADC_ERR_CHANNEL_NO;
const unsigned char ADC_JACK_TYPE = DCL_ADC_ERR_CHANNEL_NO;
const unsigned char ADC_VBAT = 0;
const unsigned char ADC_VISENSE = 1;
const unsigned char ADC_VCHARGER = 2;
const unsigned char ADC_VBATTMP = 3;


#endif /*__CUST_NEW__ */


