/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6261NP. Copyright MediaTek Inc. (C) 2012.
 * Sat Aug 25 21:26:32 2018
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*   Maui_Software
*
* Description:
* ------------
*   
*
* Author:
* -------
*  dongming.li       Generated By DRV TOOL
*
*============================================================================
****************************************************************************/
#ifndef  _EINT_DRV_H
#define  _EINT_DRV_H


#define EINT0_DEBOUNCE_TIME_DELAY 0
#define EINT1_DEBOUNCE_TIME_DELAY 0
#define EINT2_DEBOUNCE_TIME_DELAY 0
#define EINT3_DEBOUNCE_TIME_DELAY 0
#define EINT4_DEBOUNCE_TIME_DELAY 0
#define EINT5_DEBOUNCE_TIME_DELAY 0
#define EINT6_DEBOUNCE_TIME_DELAY 0
#define EINT7_DEBOUNCE_TIME_DELAY 0
#define EINT8_DEBOUNCE_TIME_DELAY 0
#define EINT9_DEBOUNCE_TIME_DELAY 0
#define EINT10_DEBOUNCE_TIME_DELAY 0
#define EINT11_DEBOUNCE_TIME_DELAY 0
#define EINT12_DEBOUNCE_TIME_DELAY 0
#define EINT13_DEBOUNCE_TIME_DELAY 0
#define EINT14_DEBOUNCE_TIME_DELAY 0
#define EINT15_DEBOUNCE_TIME_DELAY 0
#define EINT16_DEBOUNCE_TIME_DELAY 0
#define EINT17_DEBOUNCE_TIME_DELAY 0
#define EINT18_DEBOUNCE_TIME_DELAY 0
#define EINT19_DEBOUNCE_TIME_DELAY 0
#define EINT20_DEBOUNCE_TIME_DELAY 0
#define EINT21_DEBOUNCE_TIME_DELAY 0
#define EINT22_DEBOUNCE_TIME_DELAY 0
#define EINT23_DEBOUNCE_TIME_DELAY 0
#define EINT24_DEBOUNCE_TIME_DELAY 0
#define EINT25_DEBOUNCE_TIME_DELAY 100
#define EINT33_DEBOUNCE_TIME_DELAY 100


#endif /* _EINT_DRV_H */


