/*
 * Generated by MTK DrvGen Version 10.01.0 for MT6261NP. Copyright MediaTek Inc. (C) 2012.
 * Sat Aug 25 21:26:32 2018
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*   Maui_Software
*
* Description:
* ------------
*  
*
* Author:
* -------
*  dongming.li       Generated By DRV TOOL
*
*============================================================================
****************************************************************************/
#ifdef __CUST_NEW__
#include "eint.h"


const unsigned char MOTION_SENSOR_EINT_NO = 2;
const unsigned char GPS_EINT_NO = 11;
const unsigned char WIFI_EINT_NO = 12;
const unsigned char AUX_EINT_NO = 23;
const unsigned char MSDC_EINT_NO = 24;
const unsigned char KEYPAD_WAKEUP_EINT_NO = 25;
const unsigned char POWER_KEY_EINT_NO = 33;
const unsigned char SWDBG_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char AUX2_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char TOUCH_PANEL_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CHRDET_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char BT_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CLAMDET_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char USB_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CHR_USB_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char WIFI_DCXO_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char MELODY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char OTG_IDPIN_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char EXTRA_A_KEY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char EXTRA_B_KEY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char SYNC_LCM_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char LSD_MSDCCD_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char DCAM_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CMMB_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char JB_UP_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char JB_DOWN_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char JB_RIGHT_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char JB_LEFT_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char FM_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char AUX_HOOK_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CHG_IND_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char BT_CO_CLOCK_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char MUIC_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char MUIC_FAC_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char PXS_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char ALS_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char AST_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char AST_WAKEUP_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char AST_RFCONF_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char SIM_HOT_SWAP_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char SIM_HOT_SWAP_EINT2_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char NFC_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char OFN_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char WAKE_UP_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char NFC_TAG_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char LINE_IN_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char EXTUART_DTR_EINT_NO = EINT_CHANNEL_NOT_EXIST;


#endif /*__CUST_NEW__ */


