@echo off
copy /Y          .\plutommi\mmi\inc\mmi_include.h                                          %1
copy /Y          .\plutommi\mmi\inc\mmi_features.h                                         %1
copy /Y          .\plutommi\mmi\inc\MMI_features_demo_proj_comm_switch.h                   %1
copy /Y          .\plutommi\mmi\inc\mmi_features_switch.h                                  %1
copy /Y          .\plutommi\mmi\inc\mmi_features_type.h                                    %1
copy /Y          .\plutommi\mmi\inc\stdc.h                                                 %1
copy /Y          .\plutommi\Framework\Interface\MMIDataType.h                                          %1
copy /Y          .\kal\include\kal_release.h                                               %1
copy /Y          .\nucleus\inc\nucleus.h                                                   %1
copy /Y          .\nucleus\inc\cs_defs.h                                                   %1
copy /Y          .\nucleus\inc\tm_defs.h                                                   %1
copy /Y          .\nucleus\inc\tc_defs.h                                                   %1
copy /Y          .\nucleus\inc\mb_defs.h                                                   %1
copy /Y          .\nucleus\inc\qu_defs.h                                                   %1
copy /Y          .\nucleus\inc\pi_defs.h                                                   %1
copy /Y          .\nucleus\inc\sm_defs.h                                                   %1
copy /Y          .\nucleus\inc\ev_defs.h                                                   %1
copy /Y          .\nucleus\inc\pm_defs.h                                                   %1
copy /Y          .\nucleus\inc\dm_defs.h                                                   %1
copy /Y          .\config\include\stack_config.h                                           %1
copy /Y          .\kal\include\kal_non_specific_general_types.h                            %1
copy /Y          .\init\include\task_main_func.h                                           %1
copy /Y          .\kal\common\include\kal_common_defs.h                                    %1
copy /Y          .\kal\common\include\kal_error_code.h                                     %1
copy /Y          .\kal\common\include\kal_internal_macros.h                                %1
copy /Y          .\kal\nucleus\include\kal_nucleus_common_defs.h                           %1
copy /Y          .\kal\nucleus\include\kal_nucleus.h                                       %1
copy /Y          .\kal\common\include\kal_internal.h                                       %1
copy /Y          .\stacklib\include\lcd_ip_cqueue.h                                        %1
copy /Y          .\kal\common\include\kal_debug_common_defs.h                              %1
copy /Y          .\kal\nucleus\include\kal_debug_nucleus.h                                 %1
copy /Y          .\kal\include\kal_debug.h                                                 %1
copy /Y          .\kal\include\kal_trace.h                                                 %1
copy /Y          .\kal\common\include\kal_active_module.h                                  %1
copy /Y          .\adaptation\include\stack_common.h                                       %1
copy /Y          .\adaptation\include\stack_msgs.h                                         %1
copy /Y          .\interface\ps\mm_sap.h                                                   %1
copy /Y          .\interface\ps\cc_sap.h                                                   %1
copy /Y          .\interface\ps\dt_sap.h                                                   %1
copy /Y          .\interface\ps\ciss_sap.h                                                 %1
copy /Y          .\interface\ps\sms_sap.h                                                  %1
copy /Y          .\interface\ps\sim_sap.h                                                  %1
copy /Y          .\interface\ps\l4_sap.h                                                   %1
copy /Y          .\interface\mmi\mmi_sap.h                                                 %1
copy /Y          .\interface\ps\rr_sap.h                                                   %1
copy /Y          .\interface\ps\llc_sap.h                                                  %1
copy /Y          .\interface\ps\sndcp_sap.h                                                %1
copy /Y          .\interface\ps\sm_sap.h                                                   %1
copy /Y          .\interface\ps\ppp_sap.h                                                  %1
copy /Y          .\interface\ps\data_sap.h                                                 %1
copy /Y          .\interface\mmi\mmiapi_sap.h                                              %1
copy /Y          .\interface\media\med_sap.h                                               %1
copy /Y          .\interface\ps\abm_sap.h                                                  %1
copy /Y          .\interface\ps\soc_sap.h                                                  %1
copy /Y          .\interface\inet_ps\tcpip_sap.h                                           %1
copy /Y          .\interface\wap\wap_sap.h                                                 %1
copy /Y          .\interface\wap\bam_sap.h                                                 %1
copy /Y          .\interface\wap\pmg_sap.h                                                 %1
copy /Y          .\interface\ps\em_sap.h                                                   %1
copy /Y          .\interface\ps\irda_sap.h                                                 %1
copy /Y          .\interface\ps\obex_sap.h                                                 %1
copy /Y          .\interface\ps\ircomm_sap.h                                               %1
copy /Y          .\interface\media\med_v_sap.h                                             %1
copy /Y          .\j2me\interface\j2me_sap.h                                               %1
copy /Y          .\interface\ps\email_sap.h                                                %1
copy /Y          .\interface\ps\fmt_sap.h                                                  %1
copy /Y          .\interface\hwdrv\drv_sap.h                                               %1
copy /Y          .\interface\ps\nvram_sap.h                                                %1
copy /Y          .\interface\l1interface\l1_sap.h                                          %1
copy /Y          .\interface\l1interface\l1hisr_sap.h                                      %1
copy /Y          .\interface\l1interface\ft_sap.h                                          %1
copy /Y          .\tst\include\tstsap.h                                                    %1
copy /Y          .\interface\os\sysservice_sap.h                                           %1
copy /Y          .\interface\ps\cmux_sap.h                                                 %1
copy /Y          .\interface\ps\imps_sap.h                                                 %1
copy /Y          .\interface\ps\sip_sap.h                                                  %1
copy /Y          .\interface\ps\poc_sap.h                                                  %1
copy /Y          .\interface\bt\bluetooth_sap.h                                            %1
copy /Y          .\interface\ps\xdm_sap.h                                                  %1
copy /Y          .\interface\wifi\wndrv_sap.h                                              %1
copy /Y          .\interface\wifi\supc_sap.h                                               %1
copy /Y          .\interface\inet_ps\dhcp_sap.h                                            %1
copy /Y          .\interface\ps\iperf_sap.h                                                %1
copy /Y          .\interface\ps\tftp_sap.h                                                 %1
copy /Y          .\interface\ps\saf_sap.h                                                  %1
copy /Y          .\interface\ps\voip_sap.h                                                 %1
copy /Y          .\interface\ps\uart_sim_sap.h                                             %1
copy /Y          .\interface\ps\syncml_sap.h                                               %1
copy /Y          .\interface\ps\rtsp_sap.h                                                 %1
copy /Y          .\interface\ps\mexe_sap.h                                                 %1
copy /Y          .\interface\inet_ps\dm_sap.h                                              %1
copy /Y          .\interface\gps\gps_sap.h                                                 %1
copy /Y          .\interface\ps\ratcm_sap.h                                                %1
copy /Y          .\interface\ps\ratdm_sap.h                                                %1
copy /Y          .\adaptation\include\app_ltlcom.h                                         %1
copy /Y          .\adaptation\include\stack_ltlcom.h                                       %1
copy /Y          .\stacklib\include\stacklib.h                                             %1
copy /Y          .\stacklib\include\lcd.h                                                  %1
copy /Y          .\stacklib\include\lcd_cqueue.h                                           %1
copy /Y          .\stacklib\include\lcd_dll.h                                              %1
copy /Y          .\stacklib\include\lcd_lqueue.h                                           %1
copy /Y          .\adaptation\include\app_buff_alloc.h                                     %1
copy /Y          .\adaptation\include\stack_internal_macros.h                              %1
copy /Y          .\stacklib\include\stack_timer.h                                          %1
copy /Y          .\stacklib\include\event_shed.h                                           %1
copy /Y          .\config\include\syscomp_config.h                                         %1
copy /Y          .\adaptation\include\stack_types.h                                        %1
copy /Y          .\init\include\stack_init.h                                               %1
copy /Y          .\config\include\task_config.h                                            %1
copy /Y          .\ps_tdd128\l4\include\l4a.h                                              %1
copy /Y          .\interface\hwdrv\keypad_sw.h                                             %1
copy /Y          .\hal\drv_def\drv_features.h                                              %1
copy /Y          .\interface\ps\nvram_editor_data_item.h                                   %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2uem_struct.h                         %1
copy /Y          .\ps_tdd128\l4\include\device.h                                           %1
copy /Y          .\interface\hwdrv\pmic_features.h                                         %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_l4_common.h                                       %1
copy /Y          .\interface\ps\nvram_data_items.h                                         %1
copy /Y          .\sst\include\ex_item.h                                                   %1
copy /Y          .\adaptation\include\stack_buff_pool.h                                    %1
copy /Y          .\adaptation\include\ctrl_buff_pool.h                                     %1
copy /Y          .\adaptation\include\tst_buff_pool.h                                      %1
copy /Y          .\config\include\sysconf_statistics.h                                     %1
copy /Y          .\interface\ps\nvram_defs.h                                               %1
copy /Y          .\custom\common\nvram_lid_statistics.h                                    %1
copy /Y          .\tst\include\tst.h                                                       %1
copy /Y          .\custom\common\pluto_mmi\common_nvram_editor_data_item.h                 %1
copy /Y          .\custom\common\hal\aud_common_config.h                                   %1
copy /Y          .\custom\common\ps\custom_em.h                                            %1
copy /Y          .\media\camera\include\camera_para.h                                      %1
copy /Y          .\custom\common\pluto_mmi\custom_mmi_default_value.h                      %1
copy /Y          .\custom\common\pluto_mmi\nvram_common_defs.h                             %1
copy /Y          .\custom\common\custom_nvram_sec.h                                        %1
copy /Y          .\interface\hwdrv\uart_sw.h                                               %1
copy /Y          .\interface\hwdrv\bmd.h                                                   %1
copy /Y          .\interface\hwdrv\drv_comm.h                                              %1
copy /Y          .\interface\hwdrv\drvpdn.h                                                %1
copy /Y          .\inc\reg_base.h                                                          %1
copy /Y          .\ps_tdd128\interfaces\local_inc\ps2sat_struct.h                          %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_ps2sat_peer.h                                     %1
copy /Y          .\interface\media\med_struct.h                                            %1
copy /Y          .\ps_tdd128\interfaces\local_inc\ps2sim_struct.h                          %1
copy /Y          .\ps_tdd128\interfaces\enum\sim_common_enums.h                            %1
copy /Y          .\ps_tdd128\l4\include\smu_common_enums.h                                 %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2smu_struct.h                         %1
copy /Y          .\ps_tdd128\l4\include\csmss_common_enums.h                               %1
copy /Y          .\ps_tdd128\l4\include\l4c_common_enum.h                                  %1
copy /Y          .\interface\fs\fs_gprot.h                                                 %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_rspfmttr.h                          %1
copy /Y          .\ps_tdd128\l4\include\l4c_context.h                                      %1
copy /Y          .\ps_tdd128\interfaces\enum\mmi_l3_enums.h                                %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_l3_inc_struct.h                                   %1
copy /Y          .\ps_tdd128\l4\include\l4c_hz_context.h                                   %1
copy /Y          .\ps_tdd128\l4\include\l4c_aux_struct.h                                   %1
copy /Y          .\ps_tdd128\l4\include\l4_defs.h                                          %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_ss_parameters.h                                   %1
copy /Y          .\ps_tdd128\l4\csm\cc\include\csmcc_enums.h                               %1
copy /Y          .\ps_tdd128\l4\include\csmcc_common_enums.h                               %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2csm_cc_struct.h                      %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2csm_ss_struct.h                      %1
copy /Y          .\ps_tdd128\l4\include\csmcc_bc_types.h                                   %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_ss_tcapmessages.h                                 %1
copy /Y          .\ps_tdd128\interfaces\local_inc\mncc_struct.h                            %1
copy /Y          .\ps_tdd128\l4\include\csmcc_defs.h                                       %1
copy /Y          .\ps_tdd128\l4\include\csmcc_types.h                                      %1
copy /Y          .\ps_tdd128\l4\include\csmcc_atfunc.h                                     %1
copy /Y          .\interface\mmi\l4c_cc_cmd.h                                              %1
copy /Y          .\interface\mmi\l4c_ciss_cmd.h                                            %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_ss_parse.h                          %1
copy /Y          .\interface\mmi\l4c_data_cmd.h                                            %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_uem_peer.h                                        %1
copy /Y          .\interface\mmi\l4c_eq_cmd.h                                              %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_tst.h                               %1
copy /Y          .\interface\mmi\l4c_nw_cmd.h                                              %1
copy /Y          .\ps_tdd128\interfaces\enum\l4crac_enums.h                                %1
copy /Y          .\interface\mmi\l4c_phb_cmd.h                                             %1
copy /Y          .\ps_tdd128\interfaces\enum\l4c2phb_enums.h                               %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_l4c2smsal_peer.h                                  %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2smsal_struct.h                       %1
copy /Y          .\ps_tdd128\l4\include\smsal_l4c_defs.h                                   %1
copy /Y          .\ps_tdd128\interfaces\enum\smsal_l4c_enum.h                              %1
copy /Y          .\interface\mmi\l4c_sms_cmd.h                                             %1
copy /Y          .\ps_tdd128\l4\smsal\include\smsal_defs.h                                 %1
copy /Y          .\interface\mmi\l4c_sim_cmd.h                                             %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2abm_struct.h                         %1
copy /Y          .\ps_tdd128\interfaces\local_inc\l4c2tcm_struct.h                         %1
copy /Y          .\ps_tdd128\gen\mcd\mcd_l3_inc_gprs_struct.h                              %1
copy /Y          .\ps_tdd128\interfaces\enum\mmi_sm_enums.h                                %1
copy /Y          .\ps_tdd128\interfaces\enum\l3_inc_enums.h                                %1
copy /Y          .\ps_tdd128\l4\tcm\include\tcm_common_enums.h                             %1
copy /Y          .\ps_tdd128\interfaces\enum\ppp_l4_enums.h                                %1
copy /Y          .\ps_tdd128\l4\tcm\include\tcm_common.h                                   %1
copy /Y          .\ps_tdd128\l4\include\l4c2tcm_func.h                                     %1
copy /Y          .\interface\mmi\l4c_gprs_cmd.h                                            %1
copy /Y          .\ps_tdd128\interfaces\local_inc\em_struct.h                              %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_em.h                                %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_msghdlr.h                           %1
copy /Y          .\ps_tdd128\l4\phb\include\phb_defs.h                                     %1
copy /Y          .\ps_tdd128\l4\include\mmi_msg_struct.h                                   %1
copy /Y          .\ps_tdd128\l4\l4c\include\common\l4c_utility.h                           %1
copy /Y          .\plutommi\mmi\inc\globalconstants.h                                      %1
copy /Y          .\plutommi\Framework\DebugLevels\debuglevelinc\debuginitdef.h                   %1
copy /Y          .\plutommi\mmi\inc\mmi_trc.h                                              %1
copy /Y          .\plutommi\Framework\Interface\mmi_fw_trc.h                                           %1
copy /Y          .\plutommi\mmi\inc\mmi_inet_app_trc.h                                     %1
copy /Y          .\plutommi\mmi\inc\mmi_media_app_trc.h                                    %1
copy /Y          .\plutommi\mmi\inc\mmi_common_app_trc.h                                   %1
copy /Y          .\plutommi\mmi\inc\mmi_conn_app_trc.h                                     %1
copy /Y          .\plutommi\mmi\inc\timerevents.h                                          %1
copy /Y          .\plutommi\mmi\inc\allappgprot.h                                          %1
copy /Y          .\plutommi\mmi\inc\custdatares.h                                          %1
copy /Y          .\plutommi\mmi\inc\custmenures.h                                          %1
copy /Y          .\plutommi\mmi\inc\globalmenuitems.h                                      %1
copy /Y          .\plutommi\mmi\inc\menuid\wapmenuitems.h                                  %1
copy /Y          .\plutommi\mmi\inc\menuid\vmmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\emmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\fmmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\apmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\abmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\srmenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\fmrmenuitems.h                                  %1
copy /Y          .\plutommi\mmi\inc\menuid\fmsrecmenuitems.h                               %1
copy /Y          .\plutommi\mmi\inc\menuid\cameramenuitems.h                               %1
copy /Y          .\plutommi\mmi\inc\menuid\camcordermenuitems.h                            %1
copy /Y          .\plutommi\mmi\inc\menuid\imageviewermenuitems.h                          %1
copy /Y          .\plutommi\mmi\inc\menuid\j2me_menu_items.h                               %1
copy /Y          .\plutommi\mmi\inc\menuid\filemgrmenuitems.h                              %1
copy /Y          .\plutommi\mmi\inc\menuid\filemgrservicemenuitems.h                       %1
copy /Y          .\plutommi\mmi\inc\menuid\connectivitymenuitems.h                         %1
copy /Y          .\plutommi\mmi\inc\menuid\phoedtmenuenum.h                                %1
copy /Y          .\plutommi\mmi\inc\menuid\mmiapi_menu_items.h                             %1
copy /Y          .\plutommi\mmi\inc\menuid\vobjectsmenuitems.h                             %1
copy /Y          .\plutommi\mmi\inc\menuid\vrsdmenuitems.h                                 %1
copy /Y          .\plutommi\mmi\inc\menuid\vrsimenuitems.h                                 %1
copy /Y          .\plutommi\mmi\inc\menuid\motionmenuitems.h                               %1
copy /Y          .\plutommi\mmi\inc\menuid\damenuitems.h                                   %1
copy /Y          .\plutommi\mmi\inc\menuid\devicemanagementitems.h                         %1
copy /Y          .\plutommi\mmi\inc\menuid\csbmenuitems.h                                  %1
copy /Y          .\plutommi\mmi\inc\menuid\bgsoundmenuitems.h                              %1
copy /Y          .\plutommi\mmi\inc\menuid\barcodereadermenuitems.h                        %1
copy /Y          .\plutommi\mmi\inc\menuid\vdoedtmenuitem.h                                %1
copy /Y          .\plutommi\mmi\inc\menuid\avatarmenuitems.h                               %1
copy /Y          .\plutommi\mmi\inc\menuid\mobiletvplayermenuitems.h                       %1
copy /Y          .\plutommi\mmi\inc\custdataprots.h                                        %1
copy /Y          .\plutommi\mmi\inc\buildcfg.h                                             %1
copy /Y          .\plutommi\mmi\inc\custthemesres.h                                        %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_data_types.h                               %1
copy /Y          .\plutommi\Framework\Interface\PixcomFontEngine.h          %1
copy /Y          .\plutommi\Framework\Interface\FontRes.h                                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_config.h                                   %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_switch.h                                   %1
copy /Y          .\plutommi\mmi\inc\fontdcl.h                                              %1
copy /Y          .\plutommi\mmi\inc\globaldefs.h                                           %1
copy /Y          .\plutommi\mmi\inc\globalscrenum.h                                        %1
copy /Y          .\plutommi\mmi\inc\globalstruct.h                                         %1
copy /Y          .\plutommi\mmi\inc\imeres.h                                               %1
copy /Y          .\plutommi\mmi\setting\settinginc\settingdefs.h                           %1
copy /Y          .\plutommi\mmi\setting\settinginc\settingresdef.h                         %1
copy /Y          .\plutommi\Framework\InputMethod\inc\imegprot.h                                 %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_virtual_keyboard.h                         %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gdi_include.h                                %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gdi_features.h                               %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gdi_const.h                                  %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gdi_lcd_config.h                             %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gdi_datatype.h                               %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_theme_struct.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui.h                                         %1
copy /Y          .\plutommi\Framework\Interface\Unicodexdcl.h                                          %1
copy /Y          .\plutommi\mmi\datetime\datetimeinc\datetimetype.h                            %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui.h                                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_resource_type.h                                %1
copy /Y          .\plutommi\customer\customerinc\gui_setting.h                                 %1
copy /Y          .\plutommi\mmi\inc\pixteldatatypes.h                                          %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_windows.h                                      %1
copy /Y          .\plutommi\mmi\inc\mainmenutype.h                                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_custom_menus.h                                 %1
copy /Y          .\plutommi\mmi\inc\statusiconres.h                                            %1
copy /Y          .\applib\mem\include\app_mem.h                                                %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_tab_bars.h                                     %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_buttons.h                                      %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_typedef.h                                      %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_defs.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_res.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_enum.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_title.h                                        %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_title_pre_oem.h                                %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_menu_shortcut.h                                %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_themes.h                                       %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_title_post_oem.h                               %1
copy /Y          .\plutommi\Framework\GDI\gdiinc\gd_include.h                                     %1
copy /Y          .\plutommi\mmi\inc\wguicategorygprot.h                                        %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_util.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_inputs.h                                      %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_inputs.h                                       %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_scrollbars.h                                   %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_scrollbars_pre_oem.h                           %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_scrollbars_post_oem.h                          %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_draw_manager.h                                %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_panel.h                                        %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_inline_edit.h                                 %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories.h                                  %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_menu_shortcuts.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_title.h                                       %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_include.h                                     %1
copy /Y          .\applib\misc\include\app_datetime.h                                          %1
copy /Y          .\interface\hwdrv\rtc_sw.h                                                    %1
copy /Y          .\plutommi\Framework\Interface\ScreenRotationGprot.h           %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_datetime.h                                    %1
copy /Y          .\plutommi\mmi\miscframework\miscframeworkinc\ucs2prot.h                      %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_calendar.h                         %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_cm.h                               %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_email.h                            %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_ems.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_ems.h                                          %1
copy /Y          .\interface\mmi\ems.h                                                         %1
copy /Y          .\custom\common\customer_email_num.h                                          %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_fmgr.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_idlescreen.h                       %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_inputs.h                           %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_fixed_menus.h                                 %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_dynamic_menuitems.h                           %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_fixed_menuitems.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_fixed_menus.h                                  %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\gui_common_menus.h                                 %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_menu_pre_oem.h                                 %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_menu_post_oem.h                                %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_main_menu_post_oem.h                           %1
copy /Y          .\plutommi\Framework\GUI\oem_inc\gui_effect_oem.h                                   %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_asyncdynamic_menuitems.h                      %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_imps.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_tree.h                                        %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_list.h                             %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_mm.h                               %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_mms.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_mms_viewer.h                       %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_multimedia.h                       %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_panel.h                            %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_pe.h                               %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_popup.h                            %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_stopwatch.h                        %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_sublcd.h                           %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_dynamic_menus.h                               %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_tab.h                              %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_uce.h                              %1
copy /Y          .\plutommi\mtkapp\filemgr\filemgrinc\filemgr.h                                %1
copy /Y          .\plutommi\mtkapp\filemgr\filemgrinc\filemgrgprot.h                           %1
copy /Y          .\plutommi\mtkapp\filemgr\filemgrinc\filemgrtype.h                            %1
copy /Y          .\ps_tdd128\l4\atci\include\rmmi_common_enum.h                                %1
copy /Y          .\ps_tdd128\l4\atci\include\rmmi_context.h                                    %1
copy /Y          .\ps_tdd128\l4\atci\include\rmmi_bt.h                                         %1
copy /Y          .\interface\wap\wap_adp_sap.h                                                 %1
copy /Y          .\interface\wap\browser_sap.h                                                 %1
copy /Y          .\interface\wap\profile_sap.h                                                 %1
copy /Y          .\interface\wap\ua_sap.h                                                      %1
copy /Y          .\interface\wap\wps_sap.h                                                     %1
copy /Y          .\interface\wap\das_sap.h                                                     %1
copy /Y          .\interface\wap\mmc_sap.h                                                     %1
copy /Y          .\interface\wap\mma_sap.h                                                     %1
copy /Y          .\interface\wap\mms_adp_sap.h                                                 %1
copy /Y          .\interface\media\vcodec_sap.h                                                %1
copy /Y          .\interface\media\vcodec_sap.h                                                %1
copy /Y          .\interface\media\med_c_sap.h                                                 %1
copy /Y          .\interface\ps\drmt_sap.h                                                     %1
copy /Y          .\interface\gps\mnl_sap.h                                                     %1
copy /Y          .\interface\security\certman_sap.h                                            %1
copy /Y          .\plutommi\mmi\certificatemanager\certificatemanagermmiinc\certmanmmi_sap.h   %1
copy /Y          .\interface\security\tls_sap.h                                                %1
copy /Y          .\interface\ps\ext_modem_sap.h                                                %1
copy /Y          .\interface\security\kmp_sap.h                                                %1
copy /Y          .\plutommi\mmi\inc\mmi_trc_int.h                                              %1
copy /Y          .\plutommi\mmi\inc\MMI_platform.h                                             %1
copy /Y          .\media\camera\include\isp_if.h                                               %1
copy /Y          .\media\camera\include\ae_awb.h                                               %1
copy /Y          .\image_codec\common\include\exif.h                                           %1
copy /Y          .\media\camera\include\af.h                                                   %1
copy /Y          .\media\camera\include\isp_flashlight.h                                       %1
copy /Y          .\interface\hwdrv\adc.h                                                       %1
copy /Y          .\interface\mmi\l4c_ctm_cmd.h                                                 %1
copy /Y          .\plutommi\mmi\inc\menuid\idlehomescreenmenuitems.h                           %1
copy /Y          .\fmt\include\fmt_def.h                                                       %1
copy /Y          .\plutommi\mtkapp\filemgr\filemgrinc\filemgr.h                                %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_behavior_table.h           %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_clipboard_gprot.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_events_gprot.h         %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_gestures_cfg.h         %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_gestures_gprot.h       %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_gprot.h                %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_history_gprot.h        %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_input_gprot.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_mem_gprot.h            %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_nvram_gprot.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_prot.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_queue_gprot.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_frm_timer_gprot.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\CommonInc\mmi_theme_mgr.h                %1
copy /Y          .\plutommi\Framework\DebugLevels\debuglevelinc\debuginitdef_int.h                   %1
copy /Y          .\plutommi\Framework\GUI\gui_inc\wgui_categories_dialer.h                           %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\FrameworkGprot.h               %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\FrameworkProt.h                %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\FrameworkProt_int.h            %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\l4dr.h                         %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\frameworkstruct.h              %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\frameworkstruct_int.h          %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\mmitimer.h                     %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\mmitimer_int.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\keybrd.h                       %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\keybrd_int.h                   %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\eventsdcl.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\eventsdef.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\eventsdef_int.h                %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\eventsgprot.h                  %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\eventsgprot_int.h              %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\touchscreengprot.h             %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\touchscreengprot_int.h         %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\historygprot.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\historygprot_int.h             %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\sublcdhistorygprot.h           %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\sublcdhistorygprot_int.h       %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\queuegprot.h                   %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\queuegprot_int.h               %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\appmemmgrgprot.h               %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\appmemmgrgprot_int.h           %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\scrmemmgrgprot.h               %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\scrmemmgrgprot_int.h           %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\ResMemMgrGprot.h               %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\ResMemMgrGprot_Int.h           %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\oslmemory.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\oslmemory_int.h                %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\thememanager.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\nvramenum.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\nvramtype.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\nvramgprot.h                   %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\nvramprot.h                    %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\WrapperGprot.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\MMITaskGprot.h                 %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\taskinit.h                     %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\mmimemmonitor.h                %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\frameworkbackwardcompatible.h  %1
copy /Y          .\plutommi\Framework\CommonFiles\commoninc\depreciation\frameworkbackwardcompatible_int.h  %1
