/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
#include "custresdef.h"
#if (defined(__TCPIP__) && !defined(__COSMOS_MMI_PACKAGE__))
/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_DATAACCOUNT"
#if defined(__MMI_APP_MANAGER_SUPPORT__)
#ifdef __MMI_WLAN_FEATURES__
     package_name = "native.mtk.wlan"           /* Use "native.mtk." as the prefix of application name */
     name = "STR_ID_APP_DTCNT_WLAN"             /* The string to be displayed under the main menu icon */
#if (defined(__MMI_VUI_LAUNCHER__) || defined(__MMI_MAINMENU_SPREAD_SUPPORT__)) //MM_ICON   
     img = "IMG_ID_APP_DTCNT_WLAN"              /* Main menu icon image */
#endif
     launch = "mmi_wlan_app_launch_func"        /* Launch function of application. When tap on the icon in main menu, the function will be invoked. */
#endif /*__MMI_WLAN_FEATURES__*/
#endif /*__MMI_APP_MANAGER_SUPPORT__*/
>

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,SettingResDef.h"/>

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    <STRING id="STR_ID_DTCNT_RENAME"/>
    <STRING id="STR_ID_DTCNT_ADVANCED_SETTING"/>
    <STRING id="STR_ID_DTCNT_HOME_PAGE"/>
    <STRING id="STR_ID_DTCNT_CONNECTION_TYPE"/>
    <STRING id="STR_ID_DTCNT_USE_PROXY"/>
    <STRING id="STR_ID_DTCNT_PROXY_ADDRESS"/>
    <STRING id="STR_ID_DTCNT_PROXY_PORT"/>
    <STRING id="STR_ID_DTCNT_PROXY_USER_NAME"/>
    <STRING id="STR_ID_DTCNT_PROXY_PASS_WORD"/>
    <STRING id="STR_ID_DTCNT_DNS_ADDRESS1"/>
    <STRING id="STR_ID_DTCNT_DNS_ADDRESS2"/>
    <STRING id="STR_ID_DTCNT_IP_ADDRESS"/>
    <STRING id="STR_ID_DTCNT_SUBNET_MASK"/>
#if defined(__MMI_GPRS_FEATURES__)
    <STRING id="STR_ID_DTCNT_ADD_GPRS"/>
#endif
#ifdef __MMI_WLAN_FEATURES__
    <STRING id="STR_ID_DTCNT_COLON"/>
#endif
    <STRING id="STR_ID_DTCNT_MAX_CSD_ACCOUNT_REACHED"/>
    <STRING id="STR_ID_DTCNT_NOT_ALLOW_DELETE"/>
    <STRING id="STR_ID_DTCNT_NOT_ALLOW_EDIT"/>
    <STRING id="STR_ID_DTCNT_GPRS_CHAP_AUTH"/>
    <STRING id="STR_ID_DTCNT_GPRS_APN"/>
    <STRING id="STR_ID_DTCNT_GPRS_AUTH_TYP"/>
    <STRING id="STR_ID_DTCNT_GPRS_INPUT_LACK"/>
    <STRING id="STR_ID_DTCNT_NAME_INVALID"/>
    <STRING id="STR_ID_DTCNT_CHANGE_DEFAULT"/>
    // csd used only
    #ifdef __TCPIP_OVER_CSD__    
    <STRING id="STR_ID_DTCNT_ADD_CSD"/>    
    <STRING id="STR_ID_DTCNT_DIAL_NUMBER"/>
    <STRING id="STR_ID_DTCNT_CSD_INPUT_LACK"/>
    <STRING id="STR_ID_DTCNT_DIAL_TYPE"/>
    <STRING id="STR_ID_DTCNT_DATA_RATE"/>    
    <STRING id="STR_ID_DTCNT_ANALOGUE_STR"/>
    <STRING id="STR_ID_DTCNT_ISDN_STR"/>
    <STRING id="STR_ID_DTCNT_RATE_STR_ZERO"/>
    <STRING id="STR_ID_DTCNT_RATE_STR_ONE"/>
    <STRING id="STR_ID_DTCNT_RATE_STR_TWO"/>
    <STRING id="STR_ID_DTCNT_RATE_STR_THREE"/>
    <STRING id="STR_ID_DTCNT_RATE_STR_FOUR"/>
    #endif
    #ifndef __MMI_DTCNT_SLIM__
    <STRING id="STR_ID_DTCNT_DELETE_ASK"/>
    #endif
    <STRING id="STR_ID_DTCNT_ERR_MSG_INVALID_PORT"/>
    <STRING id="STR_ID_DTCNT_ERR_MSG_EMPTY_PORT_NUMBER"/>
    <STRING id="STR_ID_DTCNT_NOT_READY"/>
    //UE enhancement
    <STRING id="STR_ID_DATA_CONNECTION_SIM"/>
    <STRING id="STR_ID_DATA_CONNECTION_SIM_NOT_ALLOW_CHANGED"/>
    <STRING id="STR_ID_DTCNT_NO_AVAILABLE_ACCOUNT"/>

	// WLAN String
#ifdef __MMI_WLAN_FEATURES__	
	<STRING id="SERVICES_DATA_CONNECT_WLAN_STRING_ID"/>
	<STRING id="STR_ID_DTCNT_WLAN_MACADDR"/>
	<STRING id="STR_ID_DTCNT_WLAN_BSSID"/>
	<STRING id="STR_ID_DTCNT_WLAN_CHANNEL"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ADHOC_CHANNEL"/>
	<STRING id="STR_ID_DTCNT_WLAN_SIGNAL_STRENGTH"/>
	//<STRING id="STR_ID_DTCNT_WLAN_POWER"/>
	<STRING id="STR_ID_DTCNT_WLAN_POWER_ON"/>
	<STRING id="STR_ID_DTCNT_WLAN_POWER_OFF"/>
	<STRING id="STR_ID_DTCNT_WLAN_CONN_STATUS"/>
	<STRING id="STR_ID_DTCNT_WLAN_SETTINGS"/>
	<STRING id="STR_ID_DTCNT_WLAN_POWER_SAVE"/>	
	//<STRING id="STR_ID_DTCNT_WLAN_CONFIRM"/>	
    <STRING id="STR_GLOBAL_INVALID_PROXY_SERVER"/>
    <STRING id="STR_ID_DTCNT_WLAN_POWER_MODE_CAM"/>
    <STRING id="STR_ID_DTCNT_WLAN_POWER_MODE_FAST_PS"/>
    <STRING id="STR_ID_DTCNT_WLAN_POWER_MODE_MAX_PS"/>
    <STRING id="STR_ID_DTCNT_WLAN_POWER_MODE_CTIA"/>
	
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_SETTINGS"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_SETTING"/>
	<STRING id="STR_ID_DTCNT_WLAN_TCPIP_SETTINGS"/>
	<STRING id="STR_ID_DTCNT_WLAN_FIND_NETWORK"/>
	<STRING id="STR_ID_DTCNT_WLAN_SCAN_RESULT"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_SETTINGS_OPT_PRIORITY"/>
	<STRING id="STR_ID_DTCNT_WLAN_USE_DHCP"/>
	<STRING id="STR_ID_DTCNT_WLAN_IPADDR"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETMASK"/>
	<STRING id="STR_ID_DTCNT_WLAN_GATEWAY"/>
	<STRING id="STR_ID_DTCNT_WLAN_DNS1"/>
	
	<STRING id="STR_ID_DTCNT_WLAN_DNS2"/>
	<STRING id="STR_ID_DTCNT_WLAN_NAME"/>
	<STRING id="STR_ID_DTCNT_WLAN_PHONE_MAC"/>
	<STRING id="STR_ID_DTCNT_WLAN_SSID"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_TYPE"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE"/>
	//<STRING id="STR_ID_DTCNT_WLAN_SECURITY_SETTINGS"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_TYPE_INFRA"/>
	<STRING id="STR_ID_DTCNT_WLAN_NETWORK_TYPE_ADHOC"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_OPEN"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_SHARED"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_IEEE8021X"/>
	//<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_ONLY"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA2_ONLY"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_WPA2_MIX"/>
	//<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_ONLY_PSK"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA2_ONLY_PSK"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_WPA2_MIX_PSK"/>
	<STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPANONE"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_NONE"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_WEP"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_TKIP"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_AES"/>
	//<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_WPI"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ID"/>
	
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ID1"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ID2"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ID3"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ID4"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_SETTINGS"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_64"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_128"/>
	//<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_256"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT_ASCII"/>
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT_HEX"/>
	
	<STRING id="STR_ID_DTCNT_WLAN_WEP_KEY"/>
    //<STRING id="STR_ID_DTCNT_WLAN_OVERWRITE"/>
    //<STRING id="STR_ID_DTCNT_WLAN_OVERWRITE_CONFIRM"/>
    <STRING id="STR_ID_DTCNT_WLAN_CLEAR_CONFIRM"/>
    <STRING id="STR_ID_DTCNT_WLAN_NEW_ACCESS_POINT"/>
    <STRING id="STR_ID_DTCNT_WLAN_DEFINE_ACCESS_POINT"/>
    //<STRING id="STR_ID_DTCNT_WLAN_CONFIGURE"/>
    <STRING id="STR_ID_DTCNT_WLAN_SIGNAL_LEVEL0"/>
    <STRING id="STR_ID_DTCNT_WLAN_SIGNAL_LEVEL1"/>
    <STRING id="STR_ID_DTCNT_WLAN_SIGNAL_LEVEL2"/>
    <STRING id="STR_ID_DTCNT_WLAN_SIGNAL_LEVEL3"/>
    <STRING id="STR_ID_DTCNT_WLAN_SIGNAL_LEVEL4"/>
    <STRING id="STR_ID_DTCNT_WLAN_SECURITY"/>
    <STRING id="STR_ID_DTCNT_WLAN_AP_NUMBER"/>
    <STRING id="STR_ID_DTCNT_WLAN_LINK_SPEED"/>
    

    //<STRING id="STR_ID_DTCNT_WLAN_EAP"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_TYPES"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_TLS"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_MD5"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_PEAP"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_TTLS"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_SIM"/>
    //<STRING id="STR_ID_DTCNT_WLAN_EAP_FAST"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_GTC"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_MSCHAP2"/>
    #ifdef WLAN_EAP_FAST_SUPPORT
    <STRING id="STR_ID_DTCNT_WLAN_EAP_FAST"/>
    #endif
    <STRING id="STR_ID_DTCNT_WLAN_EAP_AKA"/>

    <STRING id="STR_ID_DTCNT_WLAN_PAP"/>
    <STRING id="STR_ID_DTCNT_WLAN_CHAP"/>
    <STRING id="STR_ID_DTCNT_WLAN_MSCHAP"/>
    <STRING id="STR_ID_DTCNT_WLAN_MSCHAP2"/>

    <STRING id="STR_ID_DTCNT_WLAN_WPA_PASSPHRASE"/>
    <STRING id="STR_ID_DTCNT_WLAN_USER_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_CA_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_PRIV_KEY"/>
    <STRING id="STR_ID_DTCNT_WLAN_PRIV_KEY_PASSWD"/>
    <STRING id="STR_ID_DTCNT_WLAN_USER_INFO"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_TLS_SETTINGS"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS"/>
    <STRING id="STR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ALLOW_PEAP_0"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ALLOW_PEAP_1"/>
    //<STRING id="STR_ID_DTCNT_WLAN_USE_ANONYMOUS"/>
    
    <STRING id="STR_ID_DTCNT_WLAN_TUNNELED_AUTH_PROTOCOL"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_GSM_ONLY"/>

    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_KEY"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_SSID"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_ADD_DEFAULT_AP"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_FILE_OPEN_FAILED"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_PASSPHRASE"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_WAI_PSK"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_IP_CONFLICT"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_ONE_EAP_NEEDED"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_NO_AUTH_SETTING"/>
    <STRING id="STR_ID_DTCNT_WLAN_AP_EXISTED"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_AUTH_FAIL"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_CONNECT_FAIL"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_CONNECT_WAPI_NETWORK_FAIL"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_DEFINE_NETWORK_FIRST"/>
    //<STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_NAME"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INIT_FAIL"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_IP_ADDR_ZERO"/>

    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INPUT"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_EAP_TYPE"/>

    <STRING id="STR_ID_WLAN_ERROR_FILE_OPEN_FAIL"/>
    <STRING id="STR_ID_WLAN_ERROR_FILE_TOO_BIG"/>
    <STRING id="STR_ID_DTCNT_WLAN_CHANGE_INFRA_PRIORITY"/>
    <STRING id="STR_ID_DTCNT_WLAN_CHANGE_ADHOC_PRIORITY"/>

    <STRING id="STR_ID_DTCNT_WLAN_CONNECTING_NO_EDIT"/>
    <STRING id="STR_ID_DTCNT_WLAN_CONNECTING_NO_DEL"/>
    //<STRING id="STR_ID_DTCNT_WLAN_COLON"/>
    
    //<STRING id="STR_ID_DTCNT_WLAN_OFF_INFO"/>
    //<STRING id="STR_ID_DTCNT_WLAN_EAP_INPUT_ERROR"/>
    //<STRING id="STR_ID_DTCNT_WLAN_EAP_TYPE_ERROR"/>
    #ifdef __MCAREV31__
    <STRING id="STR_ID_DTCNT_WIFI_SEARCH"/>
    #endif
    //<STRING id="STR_ID_DTCNT_SEARCH"/>
    <STRING id="STR_ID_DTCNT_WLAN_DISCONNECTED"/>
    <STRING id="STR_ID_DTCNT_WLAN_ENABLED_BACKGROUND"/>
    <STRING id="STR_ID_DTCNT_WLAN_TURN_OFF_HOTSPOT_CFM"/>
    <STRING id="STR_ID_DTCNT_WLAN_NO_AVAILABLE_AP"/>
    //<STRING id="STR_ID_APP_DTCNT_WLAN"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_CONNECT"/>
    #ifdef __CBM_BEARER_SWITCH__
    <STRING id="STR_ID_DTCNT_WLAN_NETWORK_SWITCH"/>
    #endif
    <STRING id="STR_ID_DTCNT_POWER_SAVE_SWITCH"/>
    <STRING id="STR_ID_DTCNT_POWER_SAVE_WHEN_OFF"/>
    <STRING id="STR_ID_DTCNT_POWER_SAVE_WHEN_PLUG"/>
    <STRING id="STR_ID_DTCNT_POWER_SAVE_NEVER"/>

	
#if defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__)
    <STRING id="STR_ID_DTCNT_WLAN_COLON"/>
#endif

#if defined(__MMI_OP01_WIFI__) || defined(__WAPI_SUPPORT__)
	<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_NONE"/>
	<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_WPI"/>
#endif

    /* CMCC TD */
#ifdef __MMI_OP01_WIFI__
    <STRING id="STR_ID_DTCNT_WLAN_USER_DEFINE"/>
    <STRING id="STR_ID_DTCNT_WLAN_TRUST_LIST"/>
    <STRING id="STR_ID_DTCNT_WLAN_BLACK_LIST"/>
    <STRING id="STR_ID_DTCNT_WLAN_FIND_AP"/>
    <STRING id="STR_ID_DTCNT_WLAN_ADD_TO_BK"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_SEARCH"/>
    <STRING id="STR_ID_DTCNT_WLAN_INTERVALS"/>
    <STRING id="STR_ID_DTCNT_WLAN_INTERVALS_TEN_SECS"/>
    <STRING id="STR_ID_DTCNT_WLAN_INTERVALS_HALF_MIN"/>
    <STRING id="STR_ID_DTCNT_WLAN_INTERVALS_ONE_MIN"/>
    <STRING id="STR_ID_DTCNT_WLAN_EXCLUSIVE_URL_EMPTY"/>
    <STRING id="STR_ID_DTCNT_WLAN_ALWAYS_ASK"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_SELECT"/>
    <STRING id="STR_ID_DTCNT_WLAN_MANUALLY_SELECT"/>
    <STRING id="STR_ID_DTCNT_WLAN_NO_MORE_ASK"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_CONN"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_RESELECT_AMONG_SSID"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERR_ADD_DEFAULT_AP_TO_BK"/>
    <STRING id="STR_ID_DTCNT_WLAN_SSID_CAN_NOT_EMPTY"/>
    <STRING id="STR_ID_DTCNT_WLAN_TRANSFER_TO_WLAN"/>
    <STRING id="STR_ID_DTCNT_WLAN_NOT_AVAILABLE"/>
    <STRING id="STR_ID_DTCNT_WLAN_CELLULAR_TO_WLAN"/>
    <STRING id="STR_ID_DTCNT_WLAN_NO_WLAN_TO_CELLULAR"/>
    <STRING id="STR_ID_DTCNT_WLAN_PROXY_EXCLUSIVE_LIST"/>
    <STRING id="STR_ID_DTCNT_WLAN_TRANSFER_TO_CELLULAR_NO_MORE_ASK"/>
    <STRING id="STR_ID_DTCNT_WLAN_PORTAL_CERT_SETTING"/>
    <STRING id="STR_ID_DTCNT_WLAN_LOGIN_SUCCESS"/>
    <STRING id="STR_ID_DTCNT_WLAN_LOGIN_FAILED"/>
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_CERT_MGR"/>
    <STRING id="STR_ID_DTCNT_WLAN_LOAD_WAPI_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_UNLOAD_WAPI_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_CONFIRM"/>
    <STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_ONLY"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WPA_ONLY_PSK"/>
    <STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_WEP"/>
	<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_TKIP"/>
	<STRING id="STR_ID_DTCNT_WLAN_ENCRYPT_MODE_AES"/>
	<STRING id="STR_ID_DTCNT_WLAN_ERROR_CONNECT_WAPI_NETWORK_FAIL"/>
	<STRING id="STR_ID_DTCNT_WLAN_ERROR_ADD_DEFAULT_AP"/>
#endif

#ifdef __MMI_OP01_WIFI__
/* CMCC WLAN Portal authenicate */
<STRING id="STR_CMCC_WLAN_EMPTY_USERNAME"/>
<STRING id="STR_CMCC_WLAN_EMPTY_PASSWORD"/>

<STRING id="STR_CMCC_WLAN_SMS_BUSY"/>
<STRING id="STR_CMCC_WLAN_SMS_FAIL"/>

<STRING id="STR_CMCC_WLAN_EMPTY_OLD_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_EMPTY_NEW1_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_EMPTY_NEW2_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_DIFFERENT_NEW_PASSWORD"/>

<STRING id="STR_CMCC_WLAN_AUTH_MAIN"/>

<STRING id="STR_CMCC_WLAN_CONFIRM_SMS"/>
<STRING id="STR_CMCC_WLAN_CONFIRM_AUTH"/>
<STRING id="STR_CMCC_WLAN_AUTH_NOTIFY"/>

<STRING id="STR_CMCC_WLAN_SMS_SEND_LOADING"/>
<STRING id="STR_CMCC_WLAN_HTTP_LOGIN_LOADING"/>

<STRING id="STR_CMCC_WLAN_NOTI_AUTH"/>

<STRING id="STR_CMCC_WLAN_APPLY_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_MODIFY_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_RESET_PASSWORD"/>

<STRING id="STR_CMCC_WLAN_OLD_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_NEW_PASSWORD"/>
<STRING id="STR_CMCC_WLAN_NEW_PASSWORD2"/>

<STRING id="STR_CMCC_WLAN_SEND_SMS_SUCC"/>
<STRING id="STR_CMCC_WLAN_SEND_SMS_FAIL"/>

<STRING id="STR_CMCC_WLAN_HTTP_AUTH_SUCC"/>
<STRING id="STR_CMCC_WLAN_HTTP_AUTH_FAIL"/>

#endif /* __MMI_OP01_WIFI__ */

#ifdef __WAPI_SUPPORT__
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_CERT_SETTINGS"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WAPICERT"/>

    <STRING id="STR_ID_DTCNT_WLAN_WAPI_PSK_SETTINGS"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTH_MODE_WAPIPSK"/>

    <STRING id="STR_ID_DTCNT_WLAN_WAPI_USER_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_ASE_CERT"/>
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_PRIV_KEY_PASSWD"/>
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_PSK_FORMAT"/>
    <STRING id="STR_ID_DTCNT_WLAN_WAPI_PSK"/>
    <STRING id="STR_ID_DTCNT_WLAN_SECURITY_SETTINGS"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_INVALID_WAI_PSK"/>
#endif

#ifdef __WPS_SUPPORT__      /* WPS */
    <STRING id="STR_ID_DTCNT_WLAN_WPS_PBC"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_PIN"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_CONN_HELP_INFO"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_CONN_TIME_LEFT"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_TIME_LEFT_MINS"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_TIME_LEFT_SECS"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_TIME_LEFT_MIN"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_TIME_LEFT_SEC"/>
    <STRING id="STR_ID_DTCNT_WLAN_WPS_AP_OVERLAPPED"/>
#endif

#ifdef __FLIGHT_MODE_SUPPORT__
   <STRING id="STR_ID_DTCNT_WLAN_OPEN_WLAN_UNDER_FLIGHT"/>
#endif

#if defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__)
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_NO_PROFILES"/>
    <STRING id="STR_ID_DTCNT_WLAN_ERROR_PROFILE_IN_USE"/>
    <STRING id="STR_ID_DTCNT_WLAN_SKIP_INVALID_PROFILES"/>
    <STRING id="STR_ID_DTCNT_WLAN_AUTO_RENAME_PROFILE"/>
    <STRING id="STR_ID_DTCNT_WLAN_INSTALL_PROFILE"/>
    <STRING id="STR_ID_DTCNT_WLAN_REPLACE_PROFILE"/>
    <STRING id="STR_ID_DTCNT_WLAN_REPLACE_CONFIRM"/>
#endif /* defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__) */
        
#ifdef __WPS_SUPPORT__ 
    <IMAGE id="WIFI_WPS_CONNECT_TIMER"/>
#endif
    //<IMAGE id="IMG_ID_DTCNT_WLAN_POPUP_CONNECT">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_Connect.gif"</IMAGE>    
#ifndef  WIFI_AUTH_PSK_ONLY
    <IMAGE id="IMG_ID_DTCNT_WLAN_POPUP_SEARCH">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_search.gif"</IMAGE>
    #endif
    <IMAGE id="IMG_ID_DTCNT_WLAN_STATION">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\SB_WiFi.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SECURED_STATION">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_aeria_lock.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_ADHOC">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_access_pc.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_STATION_S">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\SB_WiFi_s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SECURED_STATION_S">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_aeria_lock_s.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_ADHOC_S">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_access_pc_s.bmp"</IMAGE>

    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL0">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal0.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL1">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal1.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL2">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal2.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL3">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal3.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL0_CONNECTED">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal0_connected.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL1_CONNECTED">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal1_connected.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL2_CONNECTED">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal2_connected.bmp"</IMAGE>
    <IMAGE id="IMG_ID_DTCNT_WLAN_SIGNAL3_CONNECTED">CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\WiFi_signal3_connected.bmp"</IMAGE>
#if (defined(__MMI_VUI_LAUNCHER__) || defined(__MMI_MAINMENU_SPREAD_SUPPORT__)) //MM_ICON   
    <IMAGE id="IMG_ID_APP_DTCNT_WLAN"> CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\launcher\\\\Mainmenu\\\\Icons\\\\WiFi.png"</IMAGE>
#endif
#endif /* __MMI_WLAN_FEATURES__ */

    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
#ifdef __FTE_NON_SLIM_RES__
    <IMAGE id="SERVICES_DATA_CONNECT_IMAGE_ID">CUST_IMG_PATH"\\\\MainLCD\\\\submenu\\\\services\\\\DataAccount\\\\SB_DATA.png"</IMAGE>
#else
    <IMAGE id="SERVICES_DATA_CONNECT_IMAGE_ID">CUST_IMG_PATH"\\\\MainLCD\\\\submenu\\\\services\\\\DataAccount\\\\SB_DATA.bmp"</IMAGE>
#endif
#ifdef __MMI_WLAN_FEATURES__
    <IMAGE id="IMG_ID_DTCNT_LSK_EDIT">CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp"</IMAGE>
#endif
    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
    <MENUITEM id="MENU_ID_DTCNT_SIM_1" str="STR_GLOBAL_SIM_1"/>
    #if (MMI_MAX_SIM_NUM >= 2)
    <MENUITEM id="MENU_ID_DTCNT_SIM_2" str="STR_GLOBAL_SIM_2"/>
    #endif
    #if (MMI_MAX_SIM_NUM >= 3)
    <MENUITEM id="MENU_ID_DTCNT_SIM_3" str="STR_GLOBAL_SIM_3"/>
    #endif
    #if (MMI_MAX_SIM_NUM >= 4)
    <MENUITEM id="MENU_ID_DTCNT_SIM_4" str="STR_GLOBAL_SIM_4"/>
    #endif
    
    <MENU id="MENU_ID_DATA_CONNECTION_SIM" str="STR_ID_DATA_CONNECTION_SIM" highlight="mmi_data_connection_sim_hilite_hdlr">
        <MENUITEM_ID>MENU_ID_DTCNT_SIM_1</MENUITEM_ID>
        #if (MMI_MAX_SIM_NUM >= 2)
        <MENUITEM_ID>MENU_ID_DTCNT_SIM_2</MENUITEM_ID>
        #endif
        #if (MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID>MENU_ID_DTCNT_SIM_3</MENUITEM_ID>
        #endif
        #if (MMI_MAX_SIM_NUM >= 4)
        <MENUITEM_ID>MENU_ID_DTCNT_SIM_4</MENUITEM_ID>
        #endif
    </MENU>
    <MENU id="SERVICES_DATA_CONNECT_MAIN_MENU_ID" str="STR_GLOBAL_DATA_ACCOUNTS" img="SERVICES_DATA_CONNECT_IMAGE_ID" highlight="DataConnectHiliteHandler"/>
#if defined(__TCPIP_OVER_CSD__)
	<MENUITEM id="MENU_ID_DTCNT_OPT_ADD_CSD" str="STR_ID_DTCNT_ADD_CSD"/>
#endif

#if defined(__MMI_GPRS_FEATURES__)
	<MENUITEM id="MENU_ID_DTCNT_OPT_ADD_GPRS" str="STR_ID_DTCNT_ADD_GPRS"/>
#endif

	<MENU id="MENU_ID_DTCNT_ACCOUNT_OPTION" type="OPTION" str="STR_GLOBAL_OPTIONS">
	        <MENUITEM id="MENU_ID_DTCNT_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
		<MENUITEM_ID>MENU_ID_DTCNT_OPT_ADD_GPRS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_DTCNT_OPT_ADD_CSD</MENUITEM_ID>
		<MENUITEM id="MENU_ID_DTCNT_OPT_DELETE" str="STR_GLOBAL_DELETE"/>
		<MENUITEM id="MENU_ID_DTCNT_OPT_CHANGE_DEFAULT" str="STR_ID_DTCNT_CHANGE_DEFAULT"/>
	</MENU>
	
#if defined(__TCPIP_OVER_CSD__)
	<MENUITEM id="MENU_ID_DTCNT_OPT2_ADD_CSD" str="STR_ID_DTCNT_ADD_CSD"/>
#endif

#if defined(__MMI_GPRS_FEATURES__)
	<MENUITEM id="MENU_ID_DTCNT_OPT2_ADD_GPRS" str="STR_ID_DTCNT_ADD_GPRS"/>
#endif	
	<MENU id="MENU_ID_DTCNT_ACCOUNT_OPTION2" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_DTCNT_OPT2_ADD_GPRS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_DTCNT_OPT2_ADD_CSD</MENUITEM_ID>
	</MENU>

#if defined(__TCPIP_OVER_CSD__)
	<MENUITEM id="MENU_ID_DTCNT_OPT3_ADD_CSD" str="STR_ID_DTCNT_ADD_CSD"/>
#endif

#if defined(__MMI_GPRS_FEATURES__)
	<MENUITEM id="MENU_ID_DTCNT_OPT3_ADD_GPRS" str="STR_ID_DTCNT_ADD_GPRS"/>
#endif	
	<MENU id="MENU_ID_DTCNT_ACCOUNT_OPTION3" type="OPTION" str="STR_GLOBAL_OPTIONS">
                <MENUITEM id="MENU_ID_DTCNT_OPT3_VIEW" str="STR_GLOBAL_VIEW"/>
		<MENUITEM_ID>MENU_ID_DTCNT_OPT3_ADD_GPRS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_DTCNT_OPT3_ADD_CSD</MENUITEM_ID>
		<MENUITEM id="MENU_ID_DTCNT_OPT3_CHANGE_DEFAULT" str="STR_ID_DTCNT_CHANGE_DEFAULT"/>
	</MENU>	


#ifdef __MMI_WLAN_FEATURES__
	<MENUITEM id="MENU_ID_WLAN_FIND_NETWORK_OPT_CONNECT" str="STR_GLOBAL_CONNECT"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_DISCONNECT" str="STR_GLOBAL_DISCONNECT"/>
	<MENUITEM id="MENU_ID_WLAN_FIND_NETWORK_OPT_DETAILS" str="STR_GLOBAL_DETAILS"/>
	<MENUITEM id="MENU_ID_WLAN_FIND_NETWORK_OPT_REFRESH" str="STR_GLOBAL_REFRESH"/>	
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_CONNECT" str="STR_GLOBAL_CONNECT"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_NEW" str="STR_GLOBAL_ADD"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE" str="STR_GLOBAL_DELETE"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_PRIORITY" str="STR_ID_DTCNT_WLAN_NETWORK_SETTINGS_OPT_PRIORITY"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_DEFINE" str="STR_ID_DTCNT_WLAN_DEFINE_ACCESS_POINT"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS" str="STR_ID_DTCNT_WLAN_CONN_STATUS"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH" str="STR_GLOBAL_REFRESH"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_OFF" str="STR_ID_DTCNT_WLAN_POWER_OFF"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_ON" str="STR_ID_DTCNT_WLAN_POWER_ON"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_POWER_SAVE" str="STR_ID_DTCNT_WLAN_POWER_SAVE"/>
	<MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING" str="STR_GLOBAL_SETTINGS"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_TLS" str="STR_ID_DTCNT_WLAN_EAP_TLS"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_MD5" str="STR_ID_DTCNT_WLAN_EAP_MD5"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_PEAP" str="STR_ID_DTCNT_WLAN_EAP_PEAP"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_TTLS" str="STR_ID_DTCNT_WLAN_EAP_TTLS"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_SIM" str="STR_ID_DTCNT_WLAN_EAP_SIM"/>
    #ifdef WLAN_EAP_FAST_SUPPORT
	<MENUITEM id="MENU_ID_WLAN_EAP_FAST" str="STR_ID_DTCNT_WLAN_EAP_FAST"/>
	#endif
	
	<MENUITEM id="MENU_ID_WLAN_EAP_PEAP_MSCHAP2" str="STR_ID_DTCNT_WLAN_EAP_MSCHAP2"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_PEAP_GTC" str="STR_ID_DTCNT_WLAN_EAP_GTC"/>
	
	<MENUITEM id="MENU_ID_WLAN_PAP" str="STR_ID_DTCNT_WLAN_PAP"/>
	<MENUITEM id="MENU_ID_WLAN_CHAP" str="STR_ID_DTCNT_WLAN_CHAP"/>
	<MENUITEM id="MENU_ID_WLAN_MSCHAP" str="STR_ID_DTCNT_WLAN_MSCHAP"/>
	<MENUITEM id="MENU_ID_WLAN_MSCHAP2" str="STR_ID_DTCNT_WLAN_MSCHAP2"/>
	<MENUITEM id="MENU_ID_WLAN_EAP2_OPT" str="STR_GLOBAL_OPTIONS"/>
	
	<MENUITEM id="MENU_ID_WLAN_EAP2_MSCHAP2" str="STR_ID_DTCNT_WLAN_EAP_MSCHAP2"/>
	<MENUITEM id="MENU_ID_WLAN_EAP2_MD5" str="STR_ID_DTCNT_WLAN_EAP_MD5"/>
	<MENUITEM id="MENU_ID_WLAN_EAP2_SIM" str="STR_ID_DTCNT_WLAN_EAP_SIM"/>
	<MENUITEM id="MENU_ID_WLAN_EAP2_GTC" str="STR_ID_DTCNT_WLAN_EAP_GTC"/>

	<MENUITEM id="MENU_ID_WLAN_EAP_TYPES_OPT_ACTIVATE" str="STR_GLOBAL_ACTIVATE"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_TYPES_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
	
	<MENUITEM id="MENU_ID_WLAN_EAP_PEAP_TYPES_OPT_ACTIVATE" str="STR_GLOBAL_ACTIVATE"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_PEAP_TYPES_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
	
	<MENUITEM id="MENU_ID_WLAN_EAP_TTLS_TYPES_OPT_ACTIVATE" str="STR_GLOBAL_ACTIVATE"/>
	<MENUITEM id="MENU_ID_WLAN_EAP_TTLS_TYPES_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
	
	<MENUITEM id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT_CONNECT" str="STR_GLOBAL_CONNECT"/>
	<MENUITEM id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT_EDIT" str="STR_GLOBAL_EDIT"/>
	<MENUITEM id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT_ADD" str="STR_ID_DTCNT_WLAN_NEW_ACCESS_POINT"/>
	<MENUITEM id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT_DELETE" str="STR_GLOBAL_DELETE"/>
	<MENUITEM id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT_PRIORITY" str="STR_ID_DTCNT_WLAN_NETWORK_SETTINGS_OPT_PRIORITY"/>
	
	<MENU id="MENU_ID_WLAN_NETWORK_SETTINGS_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_NETWORK_SETTINGS_OPT_CONNECT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_NETWORK_SETTINGS_OPT_EDIT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_NETWORK_SETTINGS_OPT_ADD</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_NETWORK_SETTINGS_OPT_DELETE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_NETWORK_SETTINGS_OPT_PRIORITY</MENUITEM_ID>
	</MENU>
	
	<MENU id="MENU_ID_WLAN_FIND_NETWORK_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_CONNECT</MENUITEM_ID>		
		<MENUITEM id="MENU_ID_WLAN_FIND_NETWORK_OPT_DEFINE" str="STR_ID_DTCNT_WLAN_DEFINE_ACCESS_POINT"/>
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_DETAILS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_REFRESH</MENUITEM_ID>
	</MENU>

#ifdef __WPS_SUPPORT__
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_WPS_PBC" str="STR_ID_DTCNT_WLAN_WPS_PBC"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_WPS_PIN" str="STR_ID_DTCNT_WLAN_WPS_PIN"/>
    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_WPS" type="OPTION" str="STR_ID_DTCNT_WLAN_WPS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS_PBC</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS_PIN</MENUITEM_ID>
    </MENU>
#endif

#ifdef __MMI_OP01_WIFI__
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_TRUST_LIST" str="STR_ID_DTCNT_WLAN_TRUST_LIST"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_BLACK_LIST" str="STR_ID_DTCNT_WLAN_BLACK_LIST"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_DETAILS" str="STR_GLOBAL_DETAILS"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_ADD_TO_BK" str="STR_ID_DTCNT_WLAN_ADD_TO_BK"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_FIND_AP" str="STR_ID_DTCNT_WLAN_FIND_AP"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_LOAD_CERT" str="STR_ID_DTCNT_WLAN_LOAD_WAPI_CERT"/>
    <MENUITEM id="MENU_ID_WLAN_WIZARD_LIST_OPT_UNLOAD_CERT" str="STR_ID_DTCNT_WLAN_UNLOAD_WAPI_CERT"/>
    <MENUITEM id="MENU_ID_WLAN_BLACK_LIST_OPT_DELETE" str="STR_GLOBAL_DELETE"/>
    <MENUITEM id="MENU_ID_WLAN_BLACK_LIST_OPT_DELETE_ALL" str="STR_GLOBAL_DELETE_ALL"/>
    <MENUITEM id="MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST" str="STR_ID_DTCNT_WLAN_PROXY_EXCLUSIVE_LIST"/>
    <MENUITEM id="MENU_ID_WLAN_PORTAL_CERT_SETTING" str="STR_ID_DTCNT_WLAN_PORTAL_CERT_SETTING"/>
    
    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE" type="OPTION" str="STR_ID_DTCNT_WLAN_USER_DEFINE">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_TRUST_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_BLACK_LIST</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR" type="OPTION" str="STR_ID_DTCNT_WLAN_WAPI_CERT_MGR">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_LOAD_CERT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_UNLOAD_CERT</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DISCONNECT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_FIND_AP</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ADD_TO_BK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>             
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DETAILS</MENUITEM_ID>
        #ifdef __WPS_SUPPORT__
            <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
        #endif 
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CONNECT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_FIND_AP</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ADD_TO_BK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>             
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DETAILS</MENUITEM_ID>
        #ifdef __WPS_SUPPORT__
            <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
        #endif 
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_3" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CONNECT</MENUITEM_ID>        
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_FIND_AP</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ADD_TO_BK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>             
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DETAILS</MENUITEM_ID>
        #ifdef __WPS_SUPPORT__
            <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
        #endif 
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_4" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_FIND_AP</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>              
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
        #ifdef __WPS_SUPPORT__
            <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
        #endif 
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_SAVE_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ADD_TO_BK</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ON</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DETAILS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_SAVE_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_USER_DEFINE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ON</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PORTAL_CERT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CERT_MGR</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_TRUST_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_EDIT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_PRIORITY</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_TRUST_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_BLACK_LIST_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_BLACK_LIST_OPT_DELETE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_BLACK_LIST_OPT_DELETE_ALL</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_FIND_RESULT_LIST_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
    </MENU>

    <MENU id="MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_PROXY_EXCLUSIVE_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
    </MENU>
#else
	<MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DISCONNECT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_EDIT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_PRIORITY</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>
    <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
	    <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_POWER_SAVE</MENUITEM_ID>
#ifdef __WPS_SUPPORT__
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
#endif        
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
	</MENU>
	
	<MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CONNECT</MENUITEM_ID>		
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_EDIT</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_PRIORITY</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>      
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_POWER_SAVE</MENUITEM_ID>
#ifdef __WPS_SUPPORT__
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
#endif        
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
	</MENU>
	
	<MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_3" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_CONNECT</MENUITEM_ID>		
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DEFINE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>      
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_POWER_SAVE</MENUITEM_ID>
#ifdef __WPS_SUPPORT__      
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
#endif        
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_LIST_OPT_4" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_OFF</MENUITEM_ID>     
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_POWER_SAVE</MENUITEM_ID>
#ifdef __WPS_SUPPORT__
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_WPS</MENUITEM_ID>
#endif        
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_WLAN_WIZARD_SAVE_LIST_OPT_1" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_EDIT</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_DELETE</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_PRIORITY</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ON</MENUITEM_ID>       
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>       
    </MENU>
    
    <MENU id="MENU_ID_WLAN_WIZARD_SAVE_LIST_OPT_2" type="OPTION" str="STR_GLOBAL_OPTIONS">
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_NEW</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ON</MENUITEM_ID>               
        <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_SETTING</MENUITEM_ID>      
    </MENU>
#endif

	
	<MENU id="MENU_ID_WLAN_ALWAYS_ASK_FIND_NETWORK_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_CONNECT</MENUITEM_ID>		
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_DETAILS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_REFRESH</MENUITEM_ID>
	</MENU>
	
	<MENU id="MENU_ID_WLAN_FIND_NETWORK_OPT2" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_FIND_NETWORK_OPT_REFRESH</MENUITEM_ID>
	</MENU>

	
	<MENU id="MENU_ID_WLAN_EAP_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TLS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_MD5</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TTLS</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_SIM</MENUITEM_ID>
    #ifdef WLAN_EAP_FAST_SUPPORT
		<MENUITEM_ID>MENU_ID_WLAN_EAP_FAST</MENUITEM_ID>
    #endif
	</MENU>
	
	<MENU id="MENU_ID_WLAN_PEAP_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP_MSCHAP2</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP_GTC</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_TTLS_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_PAP</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_CHAP</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_MSCHAP</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_MSCHAP2</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP2_OPT</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_EAP2_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">
		<MENUITEM_ID>MENU_ID_WLAN_EAP2_MSCHAP2</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP2_MD5</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP2_SIM</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP2_GTC</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_WPA_PASSPHRASE_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_DONE_OPTION_ID</MENUITEM_ID>
		<MENUITEM_ID>MENU_INPUT_METHOD_OPTION_ID</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_PASSPHRASE_INTPUT_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_DONE_OPTION_ID</MENUITEM_ID>
		<MENUITEM_ID>MENU_INPUT_METHOD_OPTION_ID</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_EAP_TYPES_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TYPES_OPT_ACTIVATE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TYPES_OPT_EDIT</MENUITEM_ID>		
	</MENU>

	<MENU id="MENU_ID_WLAN_EAP_TYPES_OPT2" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TYPES_OPT_ACTIVATE</MENUITEM_ID>		
	</MENU>	

	<MENU id="MENU_ID_WLAN_EAP_PEAP_TYPES_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP_TYPES_OPT_ACTIVATE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP_TYPES_OPT_EDIT</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_EAP_PEAP_TYPES_OPT2" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_PEAP_TYPES_OPT_ACTIVATE</MENUITEM_ID>
	</MENU>
	
	<MENU id="MENU_ID_WLAN_EAP_TTLS_TYPES_OPT" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TTLS_TYPES_OPT_ACTIVATE</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TTLS_TYPES_OPT_EDIT</MENUITEM_ID>		
	</MENU>
	
	<MENU id="MENU_ID_WLAN_EAP_TTLS_TYPES_OPT2" type="OPTION" str="STR_GLOBAL_OPTIONS">		
		<MENUITEM_ID>MENU_ID_WLAN_EAP_TTLS_TYPES_OPT_ACTIVATE</MENUITEM_ID>
	</MENU>		
#endif
     
    <!------------------------------------------------------Events---------------------------------------------------------->
    #ifdef __TCPIP__
    #if defined(__PLUTO_MMI_PACKAGE__) && defined(__DA_SMART_SELECTION_SUPPORT__)
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_HOME_PLMN_CHANGED" proc="mmi_dtcnt_on_home_plmn_changed"/>
//#ifdef __SIM_HOT_SWAP_SUPPORT__
    <RECEIVER id="EVT_ID_SRV_SIM_CTRL_EVENT_DETECTED" proc="mmi_dtcnt_on_sim_detected"/>
    <RECEIVER id="EVT_ID_SRV_CBM_BEARER_INFO" proc="mmi_dtcnt_on_cbm_bearer_info"/>
//#endif
    #endif
    #endif

    <!------------------------------------------------------Other Resource---------------------------------------------------------->
	<SCREEN id="GRP_ID_DTCNT"/>
    <SCREEN id="GRP_ID_DTCNT_PROV"/>
    <SCREEN id="GRP_ID_DATA_CONNECTION_SIM"/>
    <SCREEN id="SCR_ID_DTCNT_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_LIST_OPTION"/>
    <SCREEN id="SCR_ID_DTCNT_CSD_COMMON"/>
    <SCREEN id="SCR_ID_DTCNT_GPRS_COMMON"/>
    <SCREEN id="SCR_ID_DTCNT_ADVANCED"/>
    <SCREEN id="SCR_ID_DTCNT_OTA_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_EDIT"/>
    <SCREEN id="SCR_ID_DTCNT_NOTIFICATION"/>
    <SCREEN id="SCR_ID_DTCNT_MAIN"/>
    <SCREEN id="SCR_ID_DTCNT_GPRS_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_OTA_GPRS_LIST"/>
 
    <SCREEN id="SCR_ID_DTCNT_LIST_ALWAYS_ASK"/>
    <SCREEN id="SCR_ID_DTCNT_LIST_ACCOUNT_SELECTION"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_NORMAL_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_SIM_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_NORMAL_DUAL_ACCT_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_NORMAL_DUAL_ACCT_LIST_EACH"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_CBM_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_WLAN_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_WLAN_SEARCH_PROCESS"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_PASSPHRASE_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_WAPI_PSK_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_WAPI_CERT_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_CSD_COMMON_VIEW"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_GPRS_COMMON_VIEW"/>
    <SCREEN id="SCR_ID_DTCNT_CUI_ADVANCED_VIEW"/>
#ifdef __MMI_CCA_SUPPORT__
    <SCREEN id="SCR_ID_DTCNT_OTA_MAIN"/>
#endif /* __MMI_CCA_SUPPORT__ */ 
    <SCREEN id="SCR_ID_DTCNT_PROGRESSING"/>


#ifdef __MMI_WLAN_FEATURES__
	<SCREEN id="SCR_ID_DTCNT_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_CONN_STATUS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_TCPIP_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_SETTINGS_EXT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_FIND_NETWORK_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_PRIORITY"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_OPERATION_MODE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_AUTH_MODE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_ENCRYPT_MODE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WPA_PASSPHRASE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WPA_PASSPHRASE_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WEP_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WEP_KEY_ID"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WEP_KEY_LEN"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WEP_KEY_FORMAT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_PROCESSING"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_ABORTING"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WPS_PROCESSING"/> 
    <SCREEN id="SCR_ID_DTCNT_WLAN_SCAN_PROCESSING"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_SCAN_RESULT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_NETWORK_DETAILS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TYPE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TYPE_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_USER_INFO"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TLS_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS_EAP_TYPE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS_EAP_TYPE_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS_TUNNELED_AUTH_PROTOCOL"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS_TUNNELED_AUTH_PROTOCOL_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_PASSPHRASE_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_PASSPHRASE_INPUT_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_IPADDR_CONFILICT_IND"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_EMPTY"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WIZARD_SAVED_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WIZARD_MAIN_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WIZARD_SAVED_LIST_OPT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WIZARD_EAP_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WIZARD_CHANGE_PRIORITY_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WAPI_PSK_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WAPI_CERT_INPUT"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WAPI_TEST_MODE_SWITCH"/>
#ifdef __MMI_OP01_WIFI__
    <SCREEN id="SCR_ID_DTCNT_WLAN_TRUST_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_BLACK_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_PROXY_EXCLUSIVE_LIST"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_BEARER_INIT_LIST"/>
#endif /* __MMI_OP01_WIFI__ */
    <SCREEN id="SCR_ID_DTCNT_WLAN_POWER_SAVE_MODE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_POWER_MODE_PROCESSING"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_WPS_CONN_INFO_POPUP"/>
#if defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__)
    <SCREEN id="SCR_ID_DTCNT_WLAN_INSTALL_PROFILE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_REPLACE_PROFILE"/>
    <SCREEN id="SCR_ID_DTCNT_WLAN_SKIP_INSTALL_PROFILE"/>
#endif /* defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__) */

#ifdef __MMI_OP01_WIFI__

<SCREEN id="SCR_ID_CMCC_WLAN_AUTH_LOADING_SCREEN"/>
<SCREEN id="SCR_ID_CMCC_WLAN_AUTH_POPUP_SCREEN"/>
<SCREEN id="SCR_ID_CMCC_WLAN_AUTH_CONFIRM_SCREEN"/>

#endif /* __MMI_OP01_WIFI__ */

#endif  
</APP>
#endif

