/* Needed header files of the compile option in XML files, if you need others need to add here */
#include "mmi_features.h"
#include "custresdef.h"
#ifdef __J2ME__
#include "j2me_custom.h"
#endif
#include "gui_config.h"
/* Need this line to tell parser that XML start, must after all #include. */
<?xml version="1.0" encoding="UTF-8"?>

#ifdef __MMI_VUI_3D_MAINMENU__
/* APP tag, include your app name defined in MMIDataType.h */
<APP id="APP_MAINMENU">

    /* When you use any ID of other module, you need to add
       that header file here, so that Resgen can find the ID */
    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,SettingResDef.h,Extraresdef.h,UcmResdef.h,GlobalMenuItems.h"/>
	<INCLUDE file="CustMenuRes.h"/>
	<INCLUDE file="mmi_rp_all_defs.h"/>

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
    /* String ID of you Application, we will get string from ref_list.txt for all languages */
    <STRING id="MAIN_MENU_TITLE_TEXT"/>
    <STRING id="MAIN_MENU_MENU_TEXT"/>

    <STRING id="MAIN_MENU_PHONEBOOK_TEXT"/>
    <STRING id="MAIN_MENU_MESSAGES_TEXT"/>
    <STRING id="MAIN_MENU_WLAN_TEXT"/>
    <STRING id="MAIN_MENU_FUNANDGAMES_TEXT"/>
    <STRING id="MAIN_MENU_MRE_TEXT"/>     
    <STRING id="MAIN_MENU_ORGANIZER_TEXT"/>
    <STRING id="MAIN_MENU_PROFILES_TEXT"/>
    <STRING id="MAIN_MENU_SETTINGS_TEXT"/>
    <STRING id="MAIN_MENU_SHORTCUTS_TEXT"/>
    <STRING id="MAIN_MENU_SERVICES_TEXT"/>
    <STRING id="MAIN_MENU_CALL_LOG_TEXT"/>
    <STRING id="MAIN_MENU_FILE_MNGR_TEXT"/>
    <STRING id="MAIN_MENU_MMEDIA_TEXT"/>
    <STRING id="MAIN_MENU_EXTRA_TEXT"/>
    <STRING id="MAIN_MENU_DIALER_TEXT"/>
    <STRING id="MAIN_MENU_SAT_TEXT"/>
    <STRING id="MAIN_MENU_SAT1_TEXT"/>
    <STRING id="MAIN_MENU_SAT2_TEXT"/>
    
    <STRING id="MAIN_MENU_FANCY_SETTINGS"/>
    <STRING id="MAIN_MENU_SPACE_BEAM"/>
    <STRING id="MAIN_MENU_TORNADO"/>
<!-----------------------------------------NVRAM CACHE---------------------------------------->
    <CACHEDATA type="byte" id="NVRAM_EF_VENUS_3D_MM_MODE" restore_flag="TRUE">
        <DEFAULT_VALUE> [0x00] </DEFAULT_VALUE>
        <DESCRIPTION> 3d mainmenu mode is Tornado </DESCRIPTION>
    </CACHEDATA>
    
    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>
    <IMAGE id="MAIN_MENU_TITLE_ICON" >CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp"</IMAGE>
#define  IMG_DIR(B)   IMG_DIR_(B)
#define  IMG_DIR_(B)  # B

/* Matrix */
#if defined(__MMI_MAINLCD_240X400__)
    <IMAGE id="MAIN_MENU_CONTROLAREA_IMAGE_BASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MG_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_fun_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_fun_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_OR_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_ST_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_WF_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SC_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SV_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PR_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_CA_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MM_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_FILE_MNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_FM_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_EXTRA_APP_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_CONTROLAREA_MESSAGE_CLUB_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX_page"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
#endif

#ifdef __MMI_MAINMENU_MATRIX_SUPPORT__
#ifdef __MMI_SLIM_IMG_RES__
    <IMAGE id="MAIN_MENU_MATRIX_ICON_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MRE"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_OR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_ST"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_WF"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>     
    <IMAGE id="MAIN_MENU_MATRIX_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SV"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_CA"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FILEMNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_EXTRA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ICON_IMGBASE_MAX" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>

    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PHONEBOOK_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MESSAGES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MG"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FUNANDGAMES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FG"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MRE_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MRE"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ORGANIZER_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_OR"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SETTINGS_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_ST"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_WLAN_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_WF"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SHORTCUTS_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SERVICES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SV"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PROFILES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PR"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_CALL_LOG_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_CA"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MULTIMEDIA_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MM"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FILEMNGR_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FM"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_EXTRA_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE_MAX" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
#else /* __MMI_SLIM_IMG_RES__ */
    <IMAGE id="MAIN_MENU_MATRIX_ICON_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_FG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MRE"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_OR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_ST"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_WF"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>     
    <IMAGE id="MAIN_MENU_MATRIX_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SV"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_CA"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FILEMNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_FM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_EXTRA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ICON_IMGBASE_MAX" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
#ifdef __MMI_UI_MATRIX_MAIN_MENU_SCALING_EFFECT__
    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_PB_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PHONEBOOK_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_PB_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MESSAGES_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_MG_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FUNANDGAMES_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_FG_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MRE_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_MRE_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ORGANIZER_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_OR_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SETTINGS_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_ST_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_WLAN_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_WF_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SHORTCUTS_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_SC_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SERVICES_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_SV_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PROFILES_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_PR_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_CALL_LOG_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_CA_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MULTIMEDIA_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_MM_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FILEMNGR_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_FM_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_EXTRA_ANIMATION" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_EX_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE_MAX" force_type="FORCE_ABM">CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\LARGE\\\\MM_EX_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX_ANI__</IMAGE>
#else /* __MMI_UI_MATRIX_MAIN_MENU_SCALING_EFFECT__ */
    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PHONEBOOK_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PB_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MESSAGES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MG_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FUNANDGAMES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_FG_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MRE_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MRE_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ORGANIZER_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_OR_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SETTINGS_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_ST_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_WLAN_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_WF_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>     
    <IMAGE id="MAIN_MENU_MATRIX_SHORTCUTS_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SC_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_SERVICES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_SV_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_PROFILES_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_PR_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_CALL_LOG_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_CA_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_MULTIMEDIA_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_MM_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_FILEMNGR_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_FM_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_EXTRA_ANIMATION" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MATRIX_ICON_ANI_IMGBASE_MAX" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\MM_EX_ANI"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
#endif /* __MMI_UI_MATRIX_MAIN_MENU_SCALING_EFFECT__ */
#endif /* __MMI_SLIM_IMG_RES__ */
#endif /* __MMI_MAINMENU_MATRIX_SUPPORT__ */

#ifdef __MMI_SLIM_IMG_RES__
    <IMAGE id="MAIN_MENU_ICON_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MRE"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_OR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_ST"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_WF"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_CONNECTIVITY_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_SV"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_PR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_CA"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_MM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_FILEMNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_FM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_EXTRA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\SLIM_MATRIX\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
#else /* __MMI_SLIM_IMG_RES__ */
    <IMAGE id="MAIN_MENU_ICON_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_PB"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_MG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_FG"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_MRE"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_OR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_ST"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_WF"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_SC"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_CONNECTIVITY_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_CN"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_SV"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_PR"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_CA"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_MM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_FILEMNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_FM"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
    <IMAGE id="MAIN_MENU_EXTRA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\"IMG_DIR(__MMI_MAINMENU_TYPE__)"\\\\MM_EX"__MMI_RES_TYPE_MAINMENU_MATRIX__</IMAGE>
#endif /* __MMI_SLIM_IMG_RES__ */

/* List */
#ifdef __MMI_MAINMENU_LIST_SUPPORT__
    <IMAGE id="MAIN_MENU_LIST_ICON_IMGBASE" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_PB.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_PB.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_MG.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_FG.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_MRE.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_CONNECTIVITY_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_CN.gif"</IMAGE>

    <IMAGE id="MAIN_MENU_LIST_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_OR.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_ST.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_WF.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_SC.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_SV.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_PR.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_CA.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_MM.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_FILEMNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_FM.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_EXTRA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_EX.gif"</IMAGE>
    <IMAGE id="MAIN_MENU_LIST_ICON_IMGBASE_MAX" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\LIST\\\\MM_EX.gif"</IMAGE>
#endif /* __MMI_MAINMENU_LIST_SUPPORT__ */

    <IMAGE id="MAIN_MENU_TITLE_EMPTY_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\Titlebar\\\\TB_transparent.bmp"</IMAGE>
/* Title image */
    <IMAGE id="MAIN_MENU_MATRIX_TITLE_BG" >CUST_IMG_PATH"\\\\MainLCD\\\\MainMenu\\\\MATRIX\\\\TB_BG.bmp"</IMAGE>

    <IMAGE id="MAIN_MENU_TITLE_ICON_BASE" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_PB.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_PHONEBOOK_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_PB.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_MESSAGES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_MG.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_FUNANDGAMES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_FG.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_MRE_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_MRE.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_ORGANIZER_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_OR.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_SETTINGS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_ST.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_PROFILES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\tb_pr.bmp"</IMAGE>

    <IMAGE id="MAIN_MENU_TITLE_WLAN_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_WF.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_SHORTCUTS_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_SC.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_SERVICES_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_SV.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_CALL_LOG_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_CA.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_MULTIMEDIA_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_MM.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_FILE_MNGR_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_FM.bmp"</IMAGE>
    <IMAGE id="MAIN_MENU_TITLE_EXTRA_APP_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_EX.bmp"</IMAGE>
    <IMAGE id="IMG_ID_FNG_FMGR_SUB_ICON" >CUST_IMG_PATH"\\\\MainLCD\\\\FileManager\\\\SB_FM.bmp"</IMAGE>
#ifdef __MMI_SUBLCD__
#ifdef __MMI_SLIM_BOOTUP__
    <IMAGE id="IMG_SUBLCD_SYSTEM_SHUTDOWN" >CUST_IMG_PATH"\\\\SubLCD\\\\Active\\\\SB_ON.gif"</IMAGE>
#else
    <IMAGE id="IMG_SUBLCD_SYSTEM_SHUTDOWN" >CUST_IMG_PATH"\\\\SubLCD\\\\Active\\\\SB_OFF.gif"</IMAGE>
#endif
#endif /* __MMI_SUBLCD__ */
    
#define ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\MainMenu\\\\3D\\\\Icons\\\\"
#define ROOT_PATH_B CUST_IMG_PATH"\\\\MainLCD\\\\VUI\\\\MainMenu\\\\3D\\\\BottomBar\\\\"
#ifdef __MMI_FTE_SUPPORT_SLIM__
	#define __3D_IMAGE_TYPE__ ".bmp"
#else
	#define __3D_IMAGE_TYPE__ ".png"
#endif
#if defined(__MMI_FILE_MANAGER__)
    <IMAGE id="MAIN_MENU_3D_FILEMNGR_ICON" >ROOT_PATH"mm_fmgr"__3D_IMAGE_TYPE__</IMAGE>
#endif
    <IMAGE id="MAIN_MENU_3D_PHONEBOOK_ICON" >ROOT_PATH"mm_phbook"__3D_IMAGE_TYPE__</IMAGE>
#if defined(__MRE_AM__)
    <IMAGE id="MAIN_MENU_3D_MRE_ICON" >ROOT_PATH"mm_mre"__3D_IMAGE_TYPE__</IMAGE>
#endif
    <IMAGE id="MAIN_MENU_3D_PROFILE_ICON" >ROOT_PATH"mm_profile"__3D_IMAGE_TYPE__</IMAGE>
#if defined (__WIFI_WIZARD_SUPPORT__) && defined (__MMI_WLAN_FEATURES__)
    <IMAGE id="MAIN_MENU_3D_WIFI_ICON" >ROOT_PATH"mm_wifi"__3D_IMAGE_TYPE__</IMAGE>
#endif
    <IMAGE id="MAIN_MENU_3D_SETTING_ICON" >ROOT_PATH"mm_setting"__3D_IMAGE_TYPE__</IMAGE>
    <IMAGE id="MAIN_MENU_3D_CLOG_ICON" >ROOT_PATH"mm_clog"__3D_IMAGE_TYPE__</IMAGE>
    <IMAGE id="MAIN_MENU_3D_DIALER_ICON" >ROOT_PATH"mm_dialer"__3D_IMAGE_TYPE__</IMAGE>
    <IMAGE id="MAIN_MENU_3D_MESSAGE_ICON" >ROOT_PATH"mm_message"__3D_IMAGE_TYPE__</IMAGE>
    <IMAGE id="MAIN_MENU_3D_CONNECT_ICON" >ROOT_PATH"mm_connect"__3D_IMAGE_TYPE__</IMAGE>
#if defined(__MMI_EMAIL__)
    <IMAGE id="MAIN_MENU_3D_EMAIL_ICON" >ROOT_PATH"mm_email"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_ATV_SUPPORT__)
    <IMAGE id="MAIN_MENU_3D_MOTV_ICON" >ROOT_PATH"mm_motv"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_MOBILE_TV_CMMB_SUPPORT__)
    <IMAGE id="MAIN_MENU_3D_MOTV_ICON" >ROOT_PATH"mm_motv"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined (__MMI_CAMERA__) && !defined(__MMI_CAMCORDER__)
    <IMAGE id="MAIN_MENU_3D_CAMERA_ICON" >ROOT_PATH"mm_camera"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_CAMCORDER__)
    <IMAGE id="MAIN_MENU_3D_CAMCORDER_ICON" >ROOT_PATH"mm_camcorder"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_IMAGE_VIEWER__)
    <IMAGE id="MAIN_MENU_3D_IMAGEVIEWER_ICON" >ROOT_PATH"mm_imageviewer"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_VIDEO_RECORDER__) && !defined(__MMI_CAMCORDER__)
    <IMAGE id="MAIN_MENU_3D_VDOREC_ICON" >ROOT_PATH"mm_vdorec"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_VIDEO_PLAYER__)
    <IMAGE id="MAIN_MENU_3D_VDOPLY_ICON" >ROOT_PATH"mm_vdoply"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_MEDIA_PLAYER__)
    <IMAGE id="MAIN_MENU_3D_MEDPLY_ICON" >ROOT_PATH"mm_medply"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __MMI_MOT_SUPPORT__
    <IMAGE id="MAIN_MENU_3D_MOT_ICON" >ROOT_PATH"mm_mot"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_PHOTOEDITOR__)
    <IMAGE id="MAIN_MENU_3D_PHOEDT_ICON" >ROOT_PATH"mm_phoedt"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_AUDIO_PLAYER__)
    <IMAGE id="MAIN_MENU_3D_ADOPLY_ICON" >ROOT_PATH"mm_adoply"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_SOUND_RECORDER__)
    <IMAGE id="MAIN_MENU_3D_SNDREC_ICON" >ROOT_PATH"mm_sndrec"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_FM_RADIO__)
    <IMAGE id="MAIN_MENU_3D_FMRDO_ICON" >ROOT_PATH"mm_fmrdo"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
    <IMAGE id="MAIN_MENU_3D_FMSR_ICON" >ROOT_PATH"mm_fmsr"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__) 
    <IMAGE id="MAIN_MENU_3D_RINGTONE_ICON" >ROOT_PATH"mm_ringtone"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_SLIDESHOW__)
    <IMAGE id="MAIN_MENU_3D_SLIDSHOW_ICON" >ROOT_PATH"mm_slidshow"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_BCR__)
    <IMAGE id="MAIN_MENU_3D_BCR_ICON" >ROOT_PATH"mm_bcr"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_CALENDAR__)
    <IMAGE id="MAIN_MENU_3D_CLENDAR_ICON" >ROOT_PATH"mm_calendar"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_TODOLIST__)
    <IMAGE id="MAIN_MENU_3D_TASK_ICON" >ROOT_PATH"mm_task"__3D_IMAGE_TYPE__</IMAGE>
#endif
		<IMAGE id="MAIN_MENU_3D_ALARM_ICON" >ROOT_PATH"mm_alarm"__3D_IMAGE_TYPE__</IMAGE>
#if defined(__MMI_AZAAN_ALARM__)
    <IMAGE id="MAIN_MENU_3D_AZZAN_ICON" >ROOT_PATH"mm_azzan"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined (__MMI_WORLD_CLOCK__) || defined (__MMI_MRE_WORLD_CLOCK__)
    <IMAGE id="MAIN_MENU_3D_WCLOCK_ICON" >ROOT_PATH"mm_wclock"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_NOTE_APP__)
    <IMAGE id="MAIN_MENU_3D_NOTE_ICON" >ROOT_PATH"mm_note"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_UDX_SUPPORT__)
    <IMAGE id="MAIN_MENU_3D_UDX_ICON" >ROOT_PATH"mm_udx"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__SYNCML_SUPPORT__)
    <IMAGE id="MAIN_MENU_3D_SYNCML_ICON" >ROOT_PATH"mm_syncml"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined( __MMI_SYNCML_DEVICE_SYNC__)
    <IMAGE id="MAIN_MENU_3D_PSYNC_ICON" >ROOT_PATH"mm_psync"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef BROWSER_SUPPORT
    <IMAGE id="MAIN_MENU_3D_BROWSER_ICON" >ROOT_PATH"mm_browser"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __MMI_SEARCH_WEB_BAIDU__
    <IMAGE id="MAIN_MENU_3D_BSEARCH_ICON" >ROOT_PATH"mm_bsearch"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined (__MMI_CALCULATOR__) || defined (__MMI_MRE_CALCULATOR__)
    <IMAGE id="MAIN_MENU_3D_CALCULATOR_ICON" >ROOT_PATH"mm_calculator"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined (__MMI_UNIT_CONVERTER__) || defined (__MMI_EXTENDED_UNIT_CONVERTER__)
    <IMAGE id="MAIN_MENU_3D_CONVERTER_ICON" >ROOT_PATH"mm_converter"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined (__MMI_CURRENCY_CONVERTER__) || defined (__MMI_EXTENDED_CURRENCY_CONVERTER__)
    <IMAGE id="MAIN_MENU_3D_CURRENCY_ICON" >ROOT_PATH"mm_currency"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_BMI__) || defined(__MMI_MENSTRUAL__) || defined(__MMI_CALORIE__)
    <IMAGE id="MAIN_MENU_3D_BMI_ICON" >ROOT_PATH"mm_bmi"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined( __MMI_STOPWATCH__)
    <IMAGE id="MAIN_MENU_3D_STOPWATCH_ICON" >ROOT_PATH"mm_stopwatch"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_DICTIONARY__)
    <IMAGE id="MAIN_MENU_3D_DICTIONARY_ICON" >ROOT_PATH"mm_dictionary"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_EBOOK_READER__)
    <IMAGE id="MAIN_MENU_3D_EBOOK_ICON" >ROOT_PATH"mm_ebook"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_AUTO_ANSWER_MACHINE__)
    <IMAGE id="MAIN_MENU_3D_AUTOAM_ICON" >ROOT_PATH"mm_autoam"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_ECOMPASS__)
    <IMAGE id="MAIN_MENU_3D_ECOMPASS_ICON" >ROOT_PATH"mm_ecompass"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __MMI_ZAKAT_CALCULATOR__
    <IMAGE id="MAIN_MENU_3D_ZAKAT_ICON" >ROOT_PATH"mm_zakat"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __MMI_VOIP__
    <IMAGE id="MAIN_MENU_3D_VOIP_ICON" >ROOT_PATH"mm_voip"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __MMI_VIDEO_TELEPHONY__
    <IMAGE id="MAIN_MENU_3D_VDOCALL_ICON" >ROOT_PATH"mm_vdocall"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_BT_SUPPORT__) 
    <IMAGE id="MAIN_MENU_3D_BT_ICON" >ROOT_PATH"mm_bt"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__MMI_GAME__)
    <IMAGE id="MAIN_MENU_3D_GAME_ICON" >ROOT_PATH"mm_game"__3D_IMAGE_TYPE__</IMAGE>
#endif
#if defined(__J2ME__)
    <IMAGE id="MAIN_MENU_3D_JAVA_ICON" >ROOT_PATH"mm_java"__3D_IMAGE_TYPE__</IMAGE>
#endif
#ifdef __SAT__
    <IMAGE id="MAIN_MENU_3D_SAT_ICON" >ROOT_PATH"mm_sat"__3D_IMAGE_TYPE__</IMAGE>
#endif
/* 3d mainmenu softkey */
    <IMAGE id="MAIN_MENU_3D_NORMAL_SOTKEY_ICON">ROOT_PATH_B"To_3D_btn.png"</IMAGE>
    <IMAGE id="MAIN_MENU_3D_FANCY_SOTKEY_ICON">ROOT_PATH_B"To_Normal_btn.png"</IMAGE>
    <IMAGE id="MAIN_MENU_3D_CANCEL_SOTKEY_ICON">ROOT_PATH_B"back_btn.png"</IMAGE>
    <IMAGE id="MAIN_MENU_3D_ORGANIZER_SOTKEY_ICON">ROOT_PATH_B"Save_btn.png"</IMAGE>
    <IMAGE id="MAIN_MENU_3D_SOTKEY_BAR_BG">ROOT_PATH_B"bottom_bar.9slice.png"</IMAGE>
    <IMAGE id="MAIN_MENU_3D_SETTING_SOFKTY_ICON">ROOT_PATH_B"3D_Setting_btn.png"</IMAGE>
#ifdef __MMI_FTE_SUPPORT_SLIM__
	<IMAGE id="MAIN_MENU_3D_BG_IMG">ROOT_PATH_B"bg.png"</IMAGE>
#else
    <IMAGE id="MAIN_MENU_3D_BG_IMG">ROOT_PATH_B"bg.jpg"</IMAGE>
#endif


<!------------------------------------------------------Menu Resource Area------------------------------------------------------>
/* File Manager */ 
#if defined(__MMI_FILE_MANAGER__)
    <MENUITEM id="MAIN_MENU_FILE_MNGR_MENUID" str="MAIN_MENU_FILE_MNGR_TEXT" img="MAIN_MENU_FILEMNGR_ICON"
        highlight="highlight_mainmenu_filemngr" shortcut="ON" shortcut_img="IMG_ID_FNG_FMGR_SUB_ICON" launch="mmi_fmgr_launch"/>
    <MAINMENUITEM id="MAIN_MENU_FILE_MNGR_MENUID"
        mm_3d_img="MAIN_MENU_3D_FILEMNGR_ICON"
        mm_launch="mmi_fmgr_launch"
    />
#endif
/* Phone Book */ 
    <MENUITEM id="MAIN_MENU_PHONEBOOK_MENUID" str="MAIN_MENU_PHONEBOOK_TEXT" img="MAIN_MENU_PHONEBOOK_ICON"
        highlight="highlight_mainmenu_phonebook"/>
    <MAINMENUITEM id="MAIN_MENU_PHONEBOOK_MENUID"
        mm_3d_img="MAIN_MENU_3D_PHONEBOOK_ICON"
        mm_launch="mmi_phb_launch"
    />
/* MRE */
#if defined(__MRE_AM__)
    <MENUITEM id="MAIN_MENU_MRE_MENUID" str="MAIN_MENU_MRE_TEXT" img="MAIN_MENU_MRE_ICON"
        highlight="highlight_mainmenu_mre"/>
    <MAINMENUITEM id="MAIN_MENU_MRE_MENUID"
        mm_3d_img="MAIN_MENU_3D_MRE_ICON"
        mm_launch="mmi_mre_start"
    />
#endif 
/* Profile */
    <MAINMENUITEM id="MAIN_MENU_PROFILES_MENUID"
        mm_3d_img="MAIN_MENU_3D_PROFILE_ICON"
        mm_launch="mmi_profiles_entry_main_screen"
    />
/* WIFI */
#if defined (__WIFI_WIZARD_SUPPORT__) && defined (__MMI_WLAN_FEATURES__)
    <MENU id="MAIN_MENU_WLAN_WIZARD_MENUID" type="APP_MAIN" str="MAIN_MENU_WLAN_TEXT" img="MAIN_MENU_WLAN_ICON"
                highlight="highlight_mainmenu_WiFi_wizard" shortcut="ON" shortcut_img="IMG_ID_FNG_FMGR_SUB_ICON" launch="mmi_wlan_entry_wlan_wizard_new">
                <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_ON</MENUITEM_ID>
                <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_STATUS</MENUITEM_ID>
                <MENUITEM_ID>MENU_ID_WLAN_WIZARD_LIST_OPT_REFRESH</MENUITEM_ID>        
    </MENU>

    <MAINMENUITEM id="MAIN_MENU_WLAN_WIZARD_MENUID"
        mm_3d_img="MAIN_MENU_3D_WIFI_ICON"
        mm_launch="mmi_wlan_entry_wlan_wizard_new"
    />
#endif
/* Setting */
		<MENUITEM id="MENU_ID_UCM_CALL_SETTING" str="STR_ID_CALLSET_CALL_SETTING" img="IMG_ID_CALLSET_CALL_SETTING" highlight="mmi_settings_highlight_general_call_setting" shortcut="ON" shortcut_img="IMG_ID_CALLSET_CALL_SETTING" launch="mmi_callset_call_setting_launch"/>
    <MENU id="MAIN_MENU_SETTINGS_MENUID" type="APP_MAIN" str="MAIN_MENU_SETTINGS_TEXT" img="MAIN_MENU_SETTINGS_ICON"
        highlight="highlight_mainmenu_settings" shortcut="ON" shortcut_img="IMG_ID_FNG_FMGR_SUB_ICON" launch="EntryScrSettingMenu">
#if (MMI_MAX_SIM_NUM >= 2) && defined(__MMI_BOOTUP_MODE_SEL_SUPPORT__)
        <MENUITEM_ID>MENU_ID_MODE_SWITCH_TYPE</MENUITEM_ID>
#endif
#if (MMI_MAX_SIM_NUM >= 2)
        <MENUITEM_ID>MENU_ID_MODE_SWITCH_SETTING</MENUITEM_ID>
#endif
#if (defined(__MMI_TOUCH_SCREEN__) || defined(__MMI_HANDWRITING_PAD__)) && (!defined(__TOUCH_PANEL_CAPACITY__)&&!defined(__TOUCH_PANEL_MULTITOUCH__))
        <MENUITEM_ID>MENU_SETTING_CALIBRATION</MENUITEM_ID>
#endif
        <MENUITEM_ID>MENU9102_INITIAL_SETUP</MENUITEM_ID>
	    <MENUITEM_ID>MENU_ID_NETSET_MAIN</MENUITEM_ID>
#if defined(__GPS_SUPPORT__) || defined(__BT_GPS_SUPPORT__)
        <MENUITEM_ID>@OID:MENU_ID_GPS_SETTING</MENUITEM_ID>
#endif
	    <MENUITEM_ID>MENU_ID_SECSET_MAIN_MENU</MENUITEM_ID>
		<MENUITEM_ID>MENU_ID_UCM_CALL_SETTING</MENUITEM_ID>
        <MENUITEM_ID>MENU_SETTING_RESTORE</MENUITEM_ID>
#ifdef __MMI_SOUND_EFFECT__
        <MENUITEM_ID>MENU_SETTING_SOUND_EFFECT</MENUITEM_ID>
#endif
#ifdef __MMI_RMGR__
        <MENUITEM_ID>MENU_ID_RMGR</MENUITEM_ID>
#endif
    </MENU>
    <MAINMENUITEM id="MAIN_MENU_SETTINGS_MENUID"
        mm_3d_img="MAIN_MENU_3D_SETTING_ICON"
        mm_launch="EntryScrSettingMenu"
    />
/* connectivity */
    <MAINMENUITEM id="MENU_ID_CONNECTIVITY"
        mm_3d_img="MAIN_MENU_3D_CONNECT_ICON"
        mm_launch="EntryConnectivityMain"
    /> 
/* Call log */
    <MENU id="MAIN_MENU_CALL_LOG" type = "APP_MAIN"
        str="MAIN_MENU_CALL_LOG_TEXT" 
		img="IMG_ID_CLOG_MAIN_ICON"  
		parent="MAIN_MENU_CALL_CENTER"
		highlight="highlight_mainmenu_calllog">
        <MENUITEM_ID>MENU_ID_CLOG_MISSED_CALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_DIALED_CALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_RECVED_CALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_ALL_CALL</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_DELETE_BOX</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_CALL_TIME</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_CALL_COST</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CLOG_SMS_COUNT</MENUITEM_ID>
#ifdef __MMI_CLOG_GPRS_COUNT__        
        <MENUITEM_ID>MENU_ID_CLOG_GPRS_COUNT</MENUITEM_ID>
#endif 
    </MENU>
    <MAINMENUITEM id="MAIN_MENU_CALL_LOG"
        mm_3d_img="MAIN_MENU_3D_CLOG_ICON"
        mm_launch="mmi_clog_launch"
    />
/* Dialer */
    <MENUITEM id="MENU_ID_DIALER" str="MAIN_MENU_DIALER_TEXT" img="IMG_ID_CLOG_MAIN_ICON"
        highlight="highlight_mainmenu_calllog"/>

    <MAINMENUITEM id="MENU_ID_DIALER"
        mm_3d_img="MAIN_MENU_3D_DIALER_ICON"
        mm_launch="mmi_dialer_launch"
    />
/* Message */
    <MAINMENUITEM id="MAIN_MENU_MESSAGES_MENUID"
        mm_3d_img="MAIN_MENU_3D_MESSAGE_ICON"
        mm_launch="mmi_um_entry_main_message_menu"
    />
/* Email */
#if defined(__MMI_EMAIL__)
    <MAINMENUITEM id="MENU_ID_EMAIL_MAIN"
        mm_3d_img="MAIN_MENU_3D_EMAIL_ICON"
        mm_launch="mmi_email_main_pre_entry_from_menu"
    />
#endif
/* Mobie TV */
#if defined(__MMI_ATV_SUPPORT__)
    <MAINMENUITEM id="MENU_ID_MOBILE_TV_PLAYER_APP"
        mm_3d_img="MAIN_MENU_3D_MOTV_ICON"
        mm_launch="mmi_mtv_player_launch"
    />
#endif
/* CMMB */
#if defined(__MMI_MOBILE_TV_CMMB_SUPPORT__)
    <MAINMENUITEM id="MENU_ID_DTV_PLAYER_APP"
        mm_3d_img="MAIN_MENU_3D_MOTV_ICON"
        mm_launch="mmi_dtv_player_launch"
    />
#endif
/* Camera */
#if defined (__MMI_CAMERA__) && !defined(__MMI_CAMCORDER__)
    <MAINMENUITEM id="MENU_ID_CAMERA_APP"
        mm_3d_img="MAIN_MENU_3D_CAMERA_ICON"
        mm_launch="mmi_camera_lauch"
    />
#endif
/* Camcorder */
#if defined(__MMI_CAMCORDER__)
    <MAINMENUITEM id="MENU_ID_CAMCORDER_APP"
        mm_3d_img="MAIN_MENU_3D_CAMCORDER_ICON"
        mm_launch="mmi_camco_launch"
    />
#endif
/* Image viewer */
#if defined(__MMI_IMAGE_VIEWER__)
    <MAINMENUITEM id="MENU_ID_IMGVIEW_APP"
        mm_3d_img="MAIN_MENU_3D_IMAGEVIEWER_ICON"
        mm_launch="mmi_imgview_launch"
    />
#endif
/* Video Recorder */
#if defined(__MMI_VIDEO_RECORDER__) && !defined(__MMI_CAMCORDER__)
    <MAINMENUITEM id="MENU_ID_VDOREC_APP"
        mm_3d_img="MAIN_MENU_3D_VDOREC_ICON"
        mm_launch="mmi_vdorec_lauch"
    />
#endif
/* Video player */
#if defined(__MMI_VIDEO_PLAYER__)
    <MAINMENUITEM id="MENU_ID_VDOPLY_APP"
        mm_3d_img="MAIN_MENU_3D_VDOPLY_ICON"
        mm_launch="mmi_vdoply_entry_app"
    />
#endif
/* Media player */
#if defined(__MMI_MEDIA_PLAYER__)
    <MAINMENUITEM id="MENU_ID_MEDPLY_MAIN"
        mm_3d_img="MAIN_MENU_3D_MEDPLY_ICON"
        mm_launch="mmi_medply_app_pre_entry"
    />
#endif
/* MOT */
#if defined(__MMI_MOT_SUPPORT__)
    <MAINMENUITEM id="MENU_ID_MOT_APP"
        mm_3d_img="MAIN_MENU_3D_MOT_ICON"
        mm_launch="mmi_mot_launch"
    />
#endif

/* Photo editor */
#if defined(__MMI_PHOTOEDITOR__)
    <MAINMENUITEM id="MENU_ID_PHOEDT_APP"
        mm_3d_img="MAIN_MENU_3D_PHOEDT_ICON"
        mm_launch="mmi_phoedt_launch"
    />
#endif
/* Audio player */
#if defined(__MMI_AUDIO_PLAYER__)
    <MAINMENUITEM id="AUDIO_PLAYER_MAIN_MENUID"
        mm_3d_img="MAIN_MENU_3D_ADOPLY_ICON"
        mm_launch="mmi_audply_entry_main"
    />
#endif
/* Sound recorder */
#if defined(__MMI_SOUND_RECORDER__)
    <MAINMENUITEM id="MENU_ID_SNDREC_MAIN"
        mm_3d_img="MAIN_MENU_3D_SNDREC_ICON"
        mm_launch="mmi_sndrec_pre_entry_main_screen"
    />
#endif
/* Fm radio */
#if defined(__MMI_FM_RADIO__)
   <MAINMENUITEM id="MENU_ID_FMRDO_MAIN"
        mm_3d_img="MAIN_MENU_3D_FMRDO_ICON"
        mm_launch="mmi_fmrdo_run_app"
    />
#endif
/* Fm schedule radio */
#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
   <MAINMENUITEM id="MENU_ID_FMSR_MAIN"
        mm_3d_img="MAIN_MENU_3D_FMSR_ICON"
        mm_launch="mmi_fmsr_pre_entry_main_list"
    />
#endif
/* Ring tone composer */
#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__) 
   <MAINMENUITEM id="MENU3103_RINGTONE_COMPOSER"
        mm_3d_img="MAIN_MENU_3D_RINGTONE_ICON"
        mm_launch="EntryRngcApp"
    />
#endif
/*Slide show */
#if defined(__MMI_SLIDESHOW__)
   <MAINMENUITEM id="MENU_ID_SLIDSHOW_APP"
        mm_3d_img="MAIN_MENU_3D_SLIDSHOW_ICON"
        mm_launch="mmi_slideshow_entry_app"
    />
#endif
/* BCR */
#if defined(__MMI_BCR__)
   <MAINMENUITEM id="MENU_ID_BCR_APP"
        mm_3d_img="MAIN_MENU_3D_BCR_ICON"
        mm_launch="mmi_bcr_enter_app_screen"
    />
#endif
/* Calendar*/
#if defined(__MMI_CALENDAR__)
   <MAINMENUITEM id="ORGANIZER_CALENDER_MENU"
        mm_3d_img="MAIN_MENU_3D_CLENDAR_ICON"
        mm_launch="mmi_clndr_entry_main_menu"
    />
#endif
/*To do list*/
#if defined(__MMI_TODOLIST__)
    <MAINMENUITEM id="ORGANIZER_TODOLIST_MENU"
        mm_3d_img="MAIN_MENU_3D_TASK_ICON"
        mm_launch="mmi_tdl_entry_task_view_all"
    />
#endif
/* alarm */
    <MAINMENUITEM id="ORGANIZER_ALARM_MENU"
        mm_3d_img="MAIN_MENU_3D_ALARM_ICON"
        mm_launch="EntryAlmMenu"
    />
/* Azzan alarm */
#if defined( __MMI_AZAAN_ALARM__)
    <MAINMENUITEM id="MENU_ID_AZAAN_ALARM"
        mm_3d_img="MAIN_MENU_3D_AZZAN_ICON"
        mm_launch="mmi_azaan_entry_main_menu"
    />
#endif
/* World clock */
#if defined (__MMI_WORLD_CLOCK__) || defined (__MMI_MRE_WORLD_CLOCK__)
    <MAINMENUITEM id="ORGANIZER_WORLDCLOCK_MENU"
        mm_3d_img="MAIN_MENU_3D_WCLOCK_ICON"
        mm_launch="EntryWcBrowseCity" 
    />
#endif
/* Note */
#if defined(__MMI_NOTE_APP__)
    <MAINMENUITEM id="MENU_ID_NOTE_APP_MAIN"
        mm_3d_img="MAIN_MENU_3D_NOTE_ICON"
        mm_launch="mmi_note_launch"
    />
#endif
/* UDX */
#if defined(__MMI_UDX_SUPPORT__)
    <MAINMENUITEM id="MENU_ID_UDX_MAIN_MENU"
        mm_3d_img="MAIN_MENU_3D_UDX_ICON"
        mm_launch="mmi_udx_entry_group_main_menu"
    />
#endif
/* SYNCML */
#if defined(__SYNCML_SUPPORT__)
    <MAINMENUITEM id="MENU_ID_SYNCML_MAIN"
        mm_3d_img="MAIN_MENU_3D_SYNCML_ICON"
        mm_launch="mmi_syncml_launch"
    />
#endif
/* PHONE SYNCML */
#if defined(__MMI_SYNCML_DEVICE_SYNC__)
    <MAINMENUITEM id="MENU_ID_SYNCML_DEV_MAIN"
        mm_3d_img="MAIN_MENU_3D_PSYNC_ICON"
        mm_launch="mmi_syncml_device_sync_launch"
    />
#endif

/* Baidu search */
#ifdef __MMI_SEARCH_WEB_BAIDU__
    <MAINMENUITEM id="MENU_ID_SEARCH_WEB_BAIDU_ENTRY"
        mm_3d_img="MAIN_MENU_3D_BSEARCH_ICON"
        mm_launch="mmi_search_web_baidu_open_search_bar"
    />
#endif
/* Calculator */
#if defined (__MMI_CALCULATOR__) || defined (__MMI_MRE_CALCULATOR__)
    <MAINMENUITEM id="EXTRA_CALCULATOR_MENU"
        mm_3d_img="MAIN_MENU_3D_CALCULATOR_ICON"
        mm_launch="CalcPreEntryApp"
    />
#endif
/* Unit converter */
#if defined (__MMI_UNIT_CONVERTER__) || defined (__MMI_EXTENDED_UNIT_CONVERTER__)
    <MAINMENUITEM id="EXTRA_UNITCONVERTOR_MENU"
        mm_3d_img="MAIN_MENU_3D_CONVERTER_ICON"
        mm_launch="mmi_uconv_pre_entry_main_menu"
    />
#endif
/* Currency converter*/
#if defined (__MMI_CURRENCY_CONVERTER__) || defined (__MMI_EXTENDED_CURRENCY_CONVERTER__)
    <MAINMENUITEM id="EXTRA_CURRENCYCONVERTOR_MENU"
        mm_3d_img="MAIN_MENU_3D_CURRENCY_ICON"
        mm_launch="mmi_cconv_pre_entry_app"
    />
#endif
/* BMI*/
#if defined(__MMI_BMI__) || defined(__MMI_MENSTRUAL__) || defined(__MMI_CALORIE__)
    <MAINMENUITEM id="EXTRA_HEALTH_MENU"
        mm_3d_img="MAIN_MENU_3D_BMI_ICON"
        mm_launch="mmi_health_entry_app"
    />
#endif
/* Stopwatch */
#if defined(__MMI_STOPWATCH__)
    <MAINMENUITEM id="MENU_STOPWATCH"
        mm_3d_img="MAIN_MENU_3D_STOPWATCH_ICON"
        mm_launch="mmi_stopwatch_main_entry"
    />
#endif
/* Dictionary */
#if defined(__MMI_DICTIONARY__)
    <MAINMENUITEM id="EXTRA_DICTIONARY_MENU"
        mm_3d_img="MAIN_MENU_3D_DICTIONARY_ICON"
        mm_launch="mmi_stopwatch_main_entry"  // TO DO
    />
#endif
/* Ebook */
#if defined(__MMI_EBOOK_READER__)
    <MAINMENUITEM id="MAIN_MENU_EBOOK_MENUID"
        mm_3d_img="MAIN_MENU_3D_EBOOK_ICON"
        mm_launch="mmi_ebr_pre_entry_book_shel_screen"
    />
#endif
/* Auto answer */
#if defined(__MMI_AUTO_ANSWER_MACHINE__)
    <MAINMENUITEM id="MENU_ID_AUTOAM_MAIN"
        mm_3d_img="MAIN_MENU_3D_AUTOAM_ICON"
        mm_launch="mmi_autoam_entry_main"
    />
#endif
/* Ecompass */
#if defined(__MMI_ECOMPASS__)
    <MAINMENUITEM id="EXTRA_ECOMPASS_MENU"
        mm_3d_img="MAIN_MENU_3D_ECOMPASS_ICON"
        mm_launch="mmi_ecompass_entry_clb_choice_screen"  // to do
    />
#endif
/* Zakat */
#ifdef __MMI_ZAKAT_CALCULATOR__
    <MAINMENUITEM id="MENU_ID_ZAKAT_CALCULATOR"
        mm_3d_img="MAIN_MENU_3D_ZAKAT_ICON"
        mm_launch="mmi_zakat_entry_main"  
    />
#endif
/* VOIP */
#ifdef __MMI_VOIP__
    <MAINMENUITEM id="MENU_ID_VOIP_MAIN"
        mm_3d_img="MAIN_MENU_3D_VOIP_ICON"
        mm_launch="mmi_voip_pre_entry_main_menu"  
    />
#endif
/* Video call */
#ifdef __MMI_VIDEO_TELEPHONY__
    <MAINMENUITEM id="MENU_ID_UCM_VT_MAIN"
        mm_3d_img="MAIN_MENU_3D_VDOCALL_ICON"
        mm_launch="mmi_ucm_vt_app_launch"  
    />
#endif
/* bt */
#if defined(__MMI_BT_SUPPORT__) 
    <MAINMENUITEM id="MENU_CONN_BT_MAIN"
        mm_3d_img="MAIN_MENU_3D_BT_ICON"
        mm_launch="mmi_bt_entry_main_menu"
    />
#endif
/* GAme */
#if defined(__MMI_GAME__)
    <MAINMENUITEM id="MENU3105_GAMES"
        mm_3d_img="MAIN_MENU_3D_GAME_ICON"
        mm_launch="mmi_game_entry_app_screen" 
    />
#endif
/* JAVA */
#if defined(__J2ME__)
    <MAINMENUITEM id="MAIN_MENU_FUNANDGAMES_MENUID"
        mm_3d_img="MAIN_MENU_3D_JAVA_ICON"
        mm_launch="mmi_fng_entry_screen"  
    />
#endif

/* Service */
    <MENU id="MAIN_MENU_SERVICES_MENUID" str="MAIN_MENU_SERVICES_TEXT" img="MAIN_MENU_SERVICES_ICON"
        highlight="highlight_mainmenu_services">

        <MENUITEM_ID> MENU_ID_SAT1_ENTRY </MENUITEM_ID>
   #if (MMI_MAX_SIM_NUM >=2)
        <MENUITEM_ID> MENU_ID_SAT2_ENTRY </MENUITEM_ID>
    #if (MMI_MAX_SIM_NUM >= 3)
        <MENUITEM_ID> MENU_ID_SAT3_ENTRY </MENUITEM_ID>
    #endif
    #if (MMI_MAX_SIM_NUM >= 4)
        <MENUITEM_ID> MENU_ID_SAT4_ENTRY </MENUITEM_ID>
    #endif
    #endif /* __GEMINI__ */
    
    </MENU>
    <MAINMENUITEM id="MAIN_MENU_SERVICES_MENUID"
        mm_3d_img="MAIN_MENU_3D_SAT_ICON"
        mm_launch="GoToServicesMenu"  
    />
/* Main menu tree */
    <MENU id="IDLE_SCREEN_MENU_ID" type="CIRCULAR_3D_MENU" str="MAIN_MENU_MENU_TEXT" img="MAIN_MENU_PHONEBOOK_ICON">
        <MENUITEM_ID>MAIN_MENU_FILE_MNGR_MENUID</MENUITEM_ID>
        <MENUITEM_ID>MAIN_MENU_PHONEBOOK_MENUID</MENUITEM_ID>
#if defined(__MRE_AM__)
        <MENUITEM_ID>MAIN_MENU_MRE_MENUID</MENUITEM_ID>     
#endif
        <MENUITEM_ID>MAIN_MENU_PROFILES_MENUID</MENUITEM_ID>
#if defined (__WIFI_WIZARD_SUPPORT__) && defined (__MMI_WLAN_FEATURES__)
        <MENUITEM_ID>MAIN_MENU_WLAN_WIZARD_MENUID</MENUITEM_ID>
#endif
        <MENUITEM_ID>MAIN_MENU_SETTINGS_MENUID</MENUITEM_ID> 
        <MENUITEM_ID>MAIN_MENU_CALL_LOG</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_DIALER</MENUITEM_ID>
        <MENUITEM_ID>MAIN_MENU_MESSAGES_MENUID</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_CONNECTIVITY</MENUITEM_ID>  
#if defined(__MMI_EMAIL__)
        <MENUITEM_ID>MENU_ID_EMAIL_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_ATV_SUPPORT__)
        <MENUITEM_ID>MENU_ID_MOBILE_TV_PLAYER_APP</MENUITEM_ID>
#endif
#if defined(__MMI_MOBILE_TV_CMMB_SUPPORT__)
        <MENUITEM_ID>MENU_ID_DTV_PLAYER_APP</MENUITEM_ID>
#endif
#if defined (__MMI_CAMERA__) && !defined(__MMI_CAMCORDER__)
				<MENUITEM_ID>MENU_ID_CAMERA_APP</MENUITEM_ID>
#endif
#if defined(__MMI_CAMCORDER__)
				<MENUITEM_ID>MENU_ID_CAMCORDER_APP</MENUITEM_ID>
#endif
#if defined(__MMI_IMAGE_VIEWER__)
				<MENUITEM_ID>MENU_ID_IMGVIEW_APP</MENUITEM_ID>
#endif
#if defined(__MMI_VIDEO_RECORDER__) && !defined(__MMI_CAMCORDER__)
        <MENUITEM_ID>MENU_ID_VDOREC_APP</MENUITEM_ID>
#endif
#if defined(__MMI_VIDEO_PLAYER__)
        <MENUITEM_ID>MENU_ID_VDOPLY_APP</MENUITEM_ID>
#endif
#if defined(__MMI_MEDIA_PLAYER__)
        <MENUITEM_ID>MENU_ID_MEDPLY_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_MOT_SUPPORT__)
        <MENUITEM_ID>MENU_ID_MOT_APP</MENUITEM_ID>
#endif
#if defined(__MMI_PHOTOEDITOR__)
        <MENUITEM_ID>MENU_ID_PHOEDT_APP</MENUITEM_ID>
#endif
#if defined(__MMI_AUDIO_PLAYER__)
        <MENUITEM_ID>AUDIO_PLAYER_MAIN_MENUID</MENUITEM_ID>
#endif
#if defined(__MMI_SOUND_RECORDER__)
        <MENUITEM_ID>MENU_ID_SNDREC_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_FM_RADIO__)
        <MENUITEM_ID>MENU_ID_FMRDO_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
        <MENUITEM_ID>MENU_ID_FMSR_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__) 
        <MENUITEM_ID>MENU3103_RINGTONE_COMPOSER</MENUITEM_ID>
#endif
#if defined(__MMI_SLIDESHOW__)
        <MENUITEM_ID>MENU_ID_SLIDSHOW_APP</MENUITEM_ID>
#endif
#if defined(__MMI_BCR__)
        <MENUITEM_ID>MENU_ID_BCR_APP</MENUITEM_ID>
#endif
#if defined(__MMI_CALENDAR__)
        <MENUITEM_ID>@OID:ORGANIZER_CALENDER_MENU</MENUITEM_ID>
#endif
#if defined(__MMI_TODOLIST__)
        <MENUITEM_ID>ORGANIZER_TODOLIST_MENU</MENUITEM_ID>
#endif
        <MENUITEM_ID>ORGANIZER_ALARM_MENU</MENUITEM_ID>
#if defined( __MMI_AZAAN_ALARM__)
        <MENUITEM_ID>MENU_ID_AZAAN_ALARM</MENUITEM_ID>
#endif
#if defined (__MMI_WORLD_CLOCK__) || defined (__MMI_MRE_WORLD_CLOCK__)
        <MENUITEM_ID>ORGANIZER_WORLDCLOCK_MENU</MENUITEM_ID>
#endif
#if defined( __MMI_NOTE_APP__)
        <MENUITEM_ID>MENU_ID_NOTE_APP_MAIN</MENUITEM_ID>
#endif
#if defined( __MMI_UDX_SUPPORT__)
        <MENUITEM_ID>MENU_ID_UDX_MAIN_MENU</MENUITEM_ID>
#endif
#if defined( __SYNCML_SUPPORT__)
        <MENUITEM_ID>MENU_ID_SYNCML_MAIN</MENUITEM_ID>
#endif
#if defined( __MMI_SYNCML_DEVICE_SYNC__)
        <MENUITEM_ID>MENU_ID_SYNCML_DEV_MAIN</MENUITEM_ID>
#endif
#ifdef BROWSER_SUPPORT
        <MENUITEM_ID>@OID:SERVICES_WAP_MENU_ID</MENUITEM_ID>
#endif
#ifdef __MMI_SEARCH_WEB_BAIDU__
        <MENUITEM_ID>MENU_ID_SEARCH_WEB_BAIDU_ENTRY</MENUITEM_ID>
#endif
#if defined (__MMI_CALCULATOR__) || defined (__MMI_MRE_CALCULATOR__)
        <MENUITEM_ID>EXTRA_CALCULATOR_MENU</MENUITEM_ID>
#endif
#if defined (__MMI_UNIT_CONVERTER__) || defined (__MMI_EXTENDED_UNIT_CONVERTER__)
        <MENUITEM_ID>EXTRA_UNITCONVERTOR_MENU</MENUITEM_ID>
#endif
#if defined (__MMI_CURRENCY_CONVERTER__) || defined (__MMI_EXTENDED_CURRENCY_CONVERTER__)
        <MENUITEM_ID>EXTRA_CURRENCYCONVERTOR_MENU</MENUITEM_ID>
#endif
#if defined(__MMI_BMI__) || defined(__MMI_MENSTRUAL__) || defined(__MMI_CALORIE__)
        <MENUITEM_ID>EXTRA_HEALTH_MENU</MENUITEM_ID>
#endif
#if defined( __MMI_STOPWATCH__)
        <MENUITEM_ID>MENU_STOPWATCH</MENUITEM_ID>
#endif
#if defined(__MMI_DICTIONARY__)
        <MENUITEM_ID>EXTRA_DICTIONARY_MENU</MENUITEM_ID>
#endif
#if defined(__MMI_EBOOK_READER__)
        <MENUITEM_ID>MAIN_MENU_EBOOK_MENUID</MENUITEM_ID>
#endif
#if defined(__MMI_AUTO_ANSWER_MACHINE__)
        <MENUITEM_ID>MENU_ID_AUTOAM_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_ECOMPASS__)
        <MENUITEM_ID>EXTRA_ECOMPASS_MENU</MENUITEM_ID>
#endif
#ifdef __MMI_ZAKAT_CALCULATOR__
        <MENUITEM_ID>MENU_ID_ZAKAT_CALCULATOR</MENUITEM_ID>
#endif
#ifdef __MMI_VOIP__
        <MENUITEM_ID>MENU_ID_VOIP_MAIN</MENUITEM_ID>
#endif
#ifdef __MMI_VIDEO_TELEPHONY__
        <MENUITEM_ID>MENU_ID_UCM_VT_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_BT_SUPPORT__) 
        <MENUITEM_ID>MENU_CONN_BT_MAIN</MENUITEM_ID>
#endif
#if defined(__MMI_GAME__)
        <MENUITEM_ID>MENU3105_GAMES</MENUITEM_ID>
#endif
#if defined(__J2ME__)
        <MENUITEM_ID>MAIN_MENU_FUNANDGAMES_MENUID</MENUITEM_ID>
#endif
				<MENUITEM_ID>MAIN_MENU_SERVICES_MENUID</MENUITEM_ID>
    </MENU>
/* Browser */
#ifdef BROWSER_SUPPORT
    <MAINMENUITEM id="SERVICES_WAP_MENU_ID"
        mm_3d_img="MAIN_MENU_3D_BROWSER_ICON"
        mm_launch="goto_mobile_suite_screen"
    />
#endif
// Avoid build error
    <MENU id="MAIN_MENU_ORGANIZER_MENUID" type="APP_MAIN" str="MAIN_MENU_ORGANIZER_TEXT" img="MAIN_MENU_ORGANIZER_ICON"
        highlight="highlight_mainmenu_organizer" >
    </MENU>
    <MENU id="MAIN_MENU_CALL_CENTER" str="STR_ID_CALLSET_CALL_CENTER" img="MAIN_MENU_CALL_LOG_ICON"
        highlight="highlight_mainmenu_callcenter">
    </MENU>
    <MENU id="MAIN_MENU_SERVICES_MENUID" str="MAIN_MENU_SERVICES_TEXT" img="MAIN_MENU_SERVICES_ICON"
        highlight="highlight_mainmenu_services">
    </MENU>
    <MENU id="MAIN_MENU_MULTIMEDIA_MENUID" str="MAIN_MENU_MMEDIA_TEXT" img="MAIN_MENU_MULTIMEDIA_ICON"
        highlight="highlight_mainmenu_multimedia">
    </MENU>
    #ifdef __J2ME__
    <MENU id="MAIN_MENU_FUNANDGAMES_MENUID" str="MAIN_MENU_FUNANDGAMES_TEXT" img="MAIN_MENU_FUNANDGAMES_ICON"
        highlight="highlight_mainmenu_funandgames">
        <MENUITEM_ID>MENU3108_JAVA</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_FNG_SETTING_JAVA</MENUITEM_ID>
    #ifdef OGDR_SECURITY_SETTING
        <MENUITEM_ID>MENU_ID_FNG_SECURITY_JAVA</MENUITEM_ID>
	#endif
	#if (MAX_VM_INSTANCE_NUM > 1)
        <MENUITEM_ID>MENU_ID_FNG_JAVA_TASK_MANAGER</MENUITEM_ID>
    #endif /*MAX_VM_INSTANCE_NUM > 1*/
    #ifdef __SUPPORT_INFUSIO__
        <MENUITEM_ID>MENU_ID_FNG_JAVA_EUREKA</MENUITEM_ID>
    #endif
    </MENU>
    #else
    <MENU id="MAIN_MENU_FUNANDGAMES_MENUID" str="MAIN_MENU_FUNANDGAMES_TEXT" img="MAIN_MENU_FUNANDGAMES_ICON"
        highlight="highlight_mainmenu_funandgames">
    </MENU>
    #endif
    <MENU id="MAIN_MENU_EXTRA_MENUID" type="APP_MAIN" str="MAIN_MENU_EXTRA_TEXT" img="MAIN_MENU_EXTRA_ICON"
        highlight="highlight_mainmenu_extra">
    </MENU>
    <!------------------------------------------------------Other Resource---------------------------------------------------------->
    <SCREEN id="MAIN_MENU_SCREENID"/>
    <SCREEN id="SCR_ID_FILE_MANAGER"/>
    <SCREEN id="SCR_ID_MMEDIA"/>
    <SCREEN id="SCR_ID_AVZONE"/>
    <SCREEN id="SCR_ID_CAMERA"/>


</APP>

#endif /*__MMI_VUI_3D_MAINMENU__ */