@echo off
copy /Y          .\inc\clib.h   						 %1
copy /Y          .\kal\include\kal_general_types.h   						 %1
copy /Y          .\inc\clib_list.h   						 %1
copy /Y          .\hal\drv_def\drv_features_6251.h   						 %1
copy /Y          .\hal\drv_def\drv_features_chip_select.h   						 %1
copy /Y          .\config\include\app\app_task_config.h   						 %1
copy /Y          .\config\include\hal\hal_task_config.h   						 %1
copy /Y          .\config\include\hal\hisr_config_internal.h   						 %1
copy /Y          .\config\include\hal\stack_config.h   						 %1
copy /Y          .\hal\drv_def\drv_features_g2d.h   						 %1
copy /Y          .\hal\drv_def\drv_features_gif.h   						 %1
copy /Y          .\hal\drv_def\drv_features_jpeg.h   						 %1
copy /Y          .\hal\drv_def\drv_features_kbd.h   						 %1
copy /Y          .\hal\drv_def\drv_features_mdp.h   						 %1
copy /Y          .\hal\drv_def\drv_features_mmsysmisc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_png.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_g2d.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_gif.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_jpeg.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_kbd.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_mmsysmisc.h   						 %1
copy /Y          .\interface\hal\drv_sw_def\drv_sw_features_png.h   						 %1
copy /Y          .\kal\include\kal_public_defs.h   						 %1
copy /Y          .\kal\include\kal_public_api.h   						 %1
copy /Y          .\kal\include\kal_release.h   						 %1
copy /Y          .\config\include\app\user_msgid_app.h   						 %1
copy /Y          .\config\include\hal\stack_msgs.h   						 %1
copy /Y          .\config\include\hal\user_msgid_hal.h   						 %1
copy /Y          .\fmr\inc\fmr_sap.h   						 %1
copy /Y          .\interface\bt\bluetooth_sap.h   						 %1
copy /Y          .\interface\fs\fs_sap.h   						 %1
copy /Y          .\interface\gps\gps_sap.h   						 %1
copy /Y          .\interface\gps\mnl_sap.h   						 %1
copy /Y          .\interface\hal\camera\cal_sap.h   						 %1
copy /Y          .\interface\hal\l1\hal_l1_sap.h   						 %1
copy /Y          .\interface\hwdrv\drv_sap.h   						 %1
copy /Y          .\interface\inet_ps\abm_sap.h   						 %1
copy /Y          .\interface\inet_ps\dhcp_sap.h   						 %1
copy /Y          .\interface\inet_ps\dhcpd_sap.h   						 %1
copy /Y          .\interface\inet_ps\dm_sap.h   						 %1
copy /Y          .\interface\inet_ps\email_sap.h   						 %1
copy /Y          .\interface\inet_ps\emlst_sap.h   						 %1
copy /Y          .\interface\inet_ps\imps_sap.h   						 %1
copy /Y          .\interface\inet_ps\iperf_sap.h   						 %1
copy /Y          .\interface\inet_ps\rtsp_sap.h   						 %1
copy /Y          .\interface\inet_ps\saf_sap.h   						 %1
copy /Y          .\interface\inet_ps\sip_sap.h   						 %1
copy /Y          .\interface\inet_ps\soc_sap.h   						 %1
copy /Y          .\interface\inet_ps\syncml_sap.h   						 %1
copy /Y          .\interface\inet_ps\tcpip_sap.h   						 %1
copy /Y          .\interface\inet_ps\xdm_sap.h   						 %1
copy /Y          .\interface\l1interface\ft_sap.h   						 %1
copy /Y          .\interface\l1interface\l1_sap.h   						 %1
copy /Y          .\interface\l1interface\l1hisr_sap.h   						 %1
copy /Y          .\interface\media\med_sap.h   						 %1
copy /Y          .\interface\media\vcodec_sap.h   						 %1
copy /Y          .\interface\middleware\drmt_sap.h   						 %1
copy /Y          .\interface\middleware\ircomm_sap.h   						 %1
copy /Y          .\interface\middleware\irda_sap.h   						 %1
copy /Y          .\interface\middleware\mexe_sap.h   						 %1
copy /Y          .\interface\middleware\nvram_sap.h   						 %1
copy /Y          .\interface\misc_ps\obex_sap.h   						 %1
copy /Y          .\interface\misc_ps\udx_sap.h   						 %1
copy /Y          .\interface\mmi\mmi_um_sap.h   						 %1
copy /Y          .\interface\mmi\mmiapi_sap.h   						 %1
copy /Y          .\interface\os\sysservice_sap.h   						 %1
copy /Y          .\interface\ps\sap\mmi_sap.h   						 %1
copy /Y          .\interface\ps\sap\ps_public_l4_sap.h   						 %1
copy /Y          .\interface\ps\sap\sim_public_sap.h   						 %1
copy /Y          .\interface\wap\bam_sap.h   						 %1
copy /Y          .\interface\wap\browser_sap.h   						 %1
copy /Y          .\interface\wap\das_sap.h   						 %1
copy /Y          .\interface\wap\mma_sap.h   						 %1
copy /Y          .\interface\wap\mmc_sap.h   						 %1
copy /Y          .\interface\wap\mms_adp_sap.h   						 %1
copy /Y          .\interface\wap\mms_sap.h   						 %1
copy /Y          .\interface\wap\pmg_sap.h   						 %1
copy /Y          .\interface\wap\profile_sap.h   						 %1
copy /Y          .\interface\wap\q03c_mms_v01_adp_sap.h   						 %1
copy /Y          .\interface\wap\ua_sap.h   						 %1
copy /Y          .\interface\wap\wap_adp_sap.h   						 %1
copy /Y          .\interface\wap\wap_sap.h   						 %1
copy /Y          .\interface\wap\wps_sap.h   						 %1
copy /Y          .\interface\wifi\supc_sap.h   						 %1
copy /Y          .\interface\wifi\wndrv_sap.h   						 %1
copy /Y          .\interface\wmt\wmt_sap.h   						 %1
copy /Y          .\j2me\interface\j2me_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\cc_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ciss_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\cmux_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\data_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\dt_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\em_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ext_modem_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\l4_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\llc_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\mm_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ndis_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ppp_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ratcm_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\ratdm_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\rr_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\sim_ps_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\sm_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\sms_sap.h   						 %1
copy /Y          .\ps\interfaces\sap\sndcp_sap.h   						 %1
copy /Y          .\rsva\interfaces\sap\rsva_sap.h   						 %1
copy /Y          .\tst\include\tstsap.h   						 %1
copy /Y          .\adaptation\include\stack_common.h   						 %1
copy /Y          .\adaptation\include\app_ltlcom.h   						 %1
copy /Y          .\hal\system\regbase\inc\reg_base.h   						 %1
copy /Y          .\hal\system\regbase\inc\reg_base_mt6251.h   						 %1
copy /Y          .\kal\include\kal_non_specific_general_types.h   						 %1
copy /Y          .\kal\include\kal_trace.h   						 %1
copy /Y          .\hal\drv_def\drv_features_gpio.h   						 %1
copy /Y          .\hal\drv_def\drv_features_adc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_vcodec.h   						 %1
copy /Y          .\hal\drv_def\drv_features_video.h   						 %1
copy /Y          .\hal\drv_def\drv_features.h   						 %1
copy /Y          .\hal\drv_def\drv_features_accdet.h   						 %1
copy /Y          .\hal\drv_def\drv_features_bmt.h   						 %1
copy /Y          .\hal\drv_def\drv_features_display.h   						 %1
copy /Y          .\hal\drv_def\drv_features_gcu.h   						 %1
copy /Y          .\hal\drv_def\drv_features_gpt.h   						 %1
copy /Y          .\hal\drv_def\drv_features_hif.h   						 %1
copy /Y          .\hal\drv_def\drv_features_i2c.h   						 %1
copy /Y          .\hal\drv_def\drv_features_irda.h   						 %1
copy /Y          .\hal\drv_def\drv_features_isp.h   						 %1
copy /Y          .\hal\drv_def\drv_features_misc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_msdc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_pfc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_pwm.h   						 %1
copy /Y          .\hal\drv_def\drv_features_resizer.h   						 %1
copy /Y          .\hal\drv_def\drv_features_rotator.h   						 %1
copy /Y          .\hal\drv_def\drv_features_rtc.h   						 %1
copy /Y          .\hal\drv_def\drv_features_sim.h   						 %1
copy /Y          .\hal\drv_def\drv_features_spi.h   						 %1
copy /Y          .\hal\drv_def\drv_features_stack_switch.h   						 %1
copy /Y          .\hal\drv_def\drv_features_tp.h   						 %1
copy /Y          .\hal\drv_def\drv_features_uart.h   						 %1
copy /Y          .\hal\drv_def\drv_features_usb.h   						 %1
copy /Y          .\hal\drv_def\drv_features_wdt.h   						 %1
copy /Y          .\interface\ps\local_inc\mcd_l4_common.h   						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_otg_drv.h   						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_usb_drv.h   						 %1
copy /Y          .\interface\hal\connectivity\usb_driver\dcl_usb_hcd.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_adc.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_aux.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_bmt.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_chr_det.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_gpio.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_gpt.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_i2c.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_i2c_owner.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_msdc.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_pfc.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_pmu.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_pw.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_pwm.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_pxs.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_rtc.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_sim.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_sts.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_uart.h   						 %1
copy /Y          .\interface\hal\peripheral\dcl_wdt.h   						 %1
copy /Y          .\interface\hal\peripheral\dclh_kbd.h   						 %1
copy /Y          .\interface\hal\peripheral\dcls_kbd.h   						 %1
copy /Y          .\interface\hwdrv\dcl_irda.h   						 %1
copy /Y          .\interface\ps\enum\ps_public_enum.h   						 %1
copy /Y          .\stacklib\include\lcd_ip_cqueue.h   						 %1
copy /Y          .\ps\interfaces\enum\sim_ps_enum.h   						 %1
copy /Y          .\interface\ps\local_inc\ps_public_struct.h   						 %1
copy /Y          .\lcmmi\mmi\inc\mmi_features.h   						 %1
copy /Y          .\lcmmi\mmi\inc\mmi_features_demo_proj_comm_switch.h   						 %1
copy /Y          .\lcmmi\mmi\inc\mmi_features_switch.h   						 %1
copy /Y          .\lcmmi\mmi\inc\mmi_features_type.h   						 %1
copy /Y          .\fs\common\include\fs_internal_def.h   						 %1
copy /Y          .\interface\common\global_def.h   						 %1
copy /Y          .\interface\fs\fs_gprot.h   						 %1
copy /Y          .\interface\ps\include\tcm_api.h   						 %1
copy /Y          .\interface\fs\fs_type.h   						 %1
copy /Y          .\adaptation\include\stack_ltlcom.h   						 %1
copy /Y          .\interface\middleware\nvram_config.h   						 %1
copy /Y          .\interface\middleware\nvram_enums.h   						 %1
copy /Y          .\interface\middleware\nvram_defs.h   						 %1
copy /Y          .\adaptation\include\stack_types.h   						 %1
copy /Y          .\adaptation\include\stack_buff_pool.h   						 %1
copy /Y          .\nucleus\inc\cs_defs.h   						 %1
copy /Y          .\nucleus\inc\dm_defs.h   						 %1
copy /Y          .\nucleus\inc\ev_defs.h   						 %1
copy /Y          .\nucleus\inc\mb_defs.h   						 %1
copy /Y          .\nucleus\inc\nucleus.h   						 %1
copy /Y          .\nucleus\inc\pi_defs.h   						 %1
copy /Y          .\nucleus\inc\pm_defs.h   						 %1
copy /Y          .\nucleus\inc\qu_defs.h   						 %1
copy /Y          .\nucleus\inc\sm_defs.h   						 %1
copy /Y          .\nucleus\inc\tc_defs.h   						 %1
copy /Y          .\nucleus\inc\tm_defs.h   						 %1
copy /Y          .\adaptation\include\ctrl_buff_pool.h   						 %1
copy /Y          .\ps\interfaces\enum\l3_inc_enums.h   						 %1
copy /Y          .\sst\include\ex_item.h   						 %1
copy /Y          .\interface\ps\enum\sim_public_enum.h   						 %1
copy /Y          .\config\include\sysconf_statistics.h   						 %1
copy /Y          .\interface\ps\include\device.h   						 %1
copy /Y          .\config\include\task_config.h   						 %1
copy /Y          .\stacklib\include\stack_timer.h   						 %1
copy /Y          .\interface\middleware\nvram_data_items.h   						 %1
copy /Y          .\tst\include\tst.h   						 %1
copy /Y          .\interface\hal\video\med_status.h   						 %1
copy /Y          .\media\common\include\fsal.h   						 %1
copy /Y          .\stacklib\include\lcd.h   						 %1
copy /Y          .\interface\hal\peripheral\drv_comm.h   						 %1
copy /Y          .\interface\hal\camera\mm_comm_def.h   						 %1
copy /Y          .\interface\hal\graphics\jpeg_enum.h   						 %1
copy /Y          .\interface\hal\postproc\fd_comm_def.h   						 %1
copy /Y          .\interface\hal\audio\l1audio.h   						 %1
copy /Y          .\media\audio\include\aud_defs.h   						 %1
copy /Y          .\interface\hal\video\mpl_common.h   						 %1
copy /Y          .\interface\hal\video\mpl_player.h   						 %1
copy /Y          .\hal\connectivity\usb_driver\inc\usbvideo_custom.h   						 %1
copy /Y          .\hal\mdp\include\img_common_enum.h   						 %1
copy /Y          .\stacklib\include\lcd_cqueue.h   						 %1
copy /Y          .\interface\hal\camera\cal_comm_def.h   						 %1
copy /Y          .\interface\hal\video\mpl_recorder.h   						 %1
copy /Y          .\interface\media\med_struct.h   						 %1
copy /Y          .\stacklib\include\lcd_lqueue.h   						 %1
copy /Y          .\hal\system\pdn\inc\pdn_def.h   						 %1
copy /Y          .\hal\system\pdn\inc\pdn_def_mt6251_series.h   						 %1
copy /Y          .\hal\system\pdn\inc\pdn_hw_mt6251_series.h   						 %1
copy /Y          .\interface\hal\system\drvpdn.h   						 %1
copy /Y          .\interface\ps\include\sim_public_api.h   						 %1
copy /Y          .\lcmmi\mmi\inc\pixteldatatypes.h   						 %1
copy /Y          .\kal\common\include\kal_debug_common_defs.h   						 %1
copy /Y          .\kal\common\include\kal_error_code.h   						 %1
copy /Y          .\kal\include\kal_debug.h   						 %1
copy /Y          .\kal\include\kal_internal_api.h   						 %1
copy /Y          .\kal\nucleus\include\kal_debug_nucleus.h   						 %1
copy /Y          .\kal\nucleus\include\kal_nucleus.h   						 %1
copy /Y          .\kal\nucleus\include\kal_nucleus_common_defs.h   						 %1
copy /Y          .\hal\system\cirq\inc\intrctrl_mt6251.h   						 %1
copy /Y          .\interface\hal\system\intrctrl.h   						 %1
copy /Y          .\stacklib\include\lcd_dll.h   						 %1
copy /Y          .\stacklib\include\stacklib.h   						 %1
copy /Y          .\stacklib\include\event_shed.h   						 %1
