/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * userprofile_nvram_def.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *    This file contains `vendor' defined logical data items stored in NVRAM.
 *    These logical data items are used in object code of Protocol Stack software.
 *
 *    As for customizable logical data items, they are defined in nvram_user_config.c
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef NVRAM_NOT_PRESENT

#if !defined(EMPTY_MMI) && !defined(NEPTUNE_MMI) && !defined(__IOT__)

/*
 *   Include Headers
 */

#include "kal_general_types.h"

/*
 *   NVRAM Basic Headers
 */
#ifdef NVRAM_AUTO_GEN
#include "nvram_auto_gen.h"
#endif

#include "nvram_enums.h"
#include "nvram_defs.h"
#include "nvram_data_items.h"

#include "mmi_features.h"

/*
 *   User Headers
 */
#ifndef __OPTR_NONE__
#include "op_nvram_common_config.h"
#endif
#include "custom_srv_prof_defs.h"
#include "userprofile_nvram_def.h"



/*
 *   Default value
 */

#ifndef EXTERNAL_MMI
nvram_srv_prof_setting_struct const NVRAM_PROFILES_DEFAULT [NVRAM_SRV_PROF_PROFILES_TOTAL_NUM] =
{
#ifdef CUSTOM_USER_PROFILE_CONTENT_DEFAULT
    CUSTOM_USER_PROFILE_CONTENT_DEFAULT
#else
	{
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
	},
	{
        SRV_PROF_VOL_LEVEL_0, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VOL_LEVEL_0, SRV_PROF_MEDIA_VOL_LEVEL_0, SRV_PROF_ALERT_TYPE_SILENT,KAL_FALSE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_FALSE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_SILENT, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        0, 0, KAL_FALSE, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0
	},
	{
        SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_2, SRV_PROF_MEDIA_VOL_LEVEL_4, SRV_PROF_ALERT_TYPE_VIB_ONLY,KAL_FALSE,KAL_TRUE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_FALSE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        0, 0, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
	},
	{
        SRV_PROF_VOL_LEVEL_6, SRV_PROF_VOL_LEVEL_6, SRV_PROF_VOL_LEVEL_6, SRV_PROF_MEDIA_VOL_LEVEL_13, SRV_PROF_ALERT_TYPE_VIB_AND_RING,KAL_TRUE,KAL_TRUE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
	},
#ifndef __MMI_PROF_ADD_DEL_PROF_SUPPORT__
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    }
#else
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    },
    {
        SRV_PROF_VOL_LEVEL_4, SRV_PROF_VOL_LEVEL_2, SRV_PROF_VOL_LEVEL_4, SRV_PROF_MEDIA_VOL_LEVEL_8, SRV_PROF_ALERT_TYPE_RING,KAL_TRUE,KAL_FALSE,SRV_PROF_RING_TYPE_REPEAT,
        KAL_FALSE, KAL_TRUE, SRV_PROF_LED_PATTERN_1, SRV_PROF_KEYPAD_TONE, SRV_PROF_VOL_LEVEL_0, SRV_PROF_VIB_LEVEL_0,
        SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, KAL_TRUE, SRV_PROF_AUD_TONE1, SRV_PROF_AUD_TONE2, 
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_TONE3, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4, SRV_PROF_AUD_TONE4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4,
        SRV_PROF_AUD_RING1, SRV_PROF_AUD_RING2, SRV_PROF_AUD_RING3, SRV_PROF_AUD_RING4
    }
#endif //__MMI_PROF_ADD_DEL_PROF_SUPPORT__

#endif /*CUSTOM_USER_PROFILE_CONTENT_DEFAULT*/
};
#endif /* !defined(EXTERNAL_MMI)*/



/*
 *   LID table
 */

#ifndef EXTERNAL_MMI
ltable_entry_struct logical_data_item_table_userprofile[] =
{
    {
        NVRAM_EF_SRV_PROF_SETTING_LID,
        NVRAM_SRV_PROF_RECORD_TOTAL,
        NVRAM_SRV_PROF_RECORD_SIZE,
        NVRAM_NORMAL(NVRAM_PROFILES_DEFAULT),
        NVRAM_CATEGORY_USER,
        NVRAM_ATTR_FACTORY_RESET | NVRAM_ATTR_MULTI_DEFAULT | NVRAM_ATTR_MULTIREC_READ | NVRAM_ATTR_NOT_ZIP_DEFAULT,
        "MP1V",
        VER(NVRAM_EF_SRV_PROF_SETTING_LID)
    },
    {
        NVRAM_EF_SRV_PROF_EXT_MELODY_LID,
        NVRAM_EF_SRV_PROF_EXT_MELODY_TOTAL,
        NVRAM_EF_SRV_PROF_EXT_MELODY_SIZE,
        NVRAM_NORMAL(NVRAM_EF_ZERO_DEFAULT),
        NVRAM_CATEGORY_USER,
        NVRAM_ATTR_AVERAGE | NVRAM_ATTR_FACTORY_RESET | NVRAM_ATTR_MULTIREC_READ,
        "MP1K",
        VER(NVRAM_EF_SRV_PROF_EXT_MELODY_LID)
    },
};
#endif /* !defined(EXTERNAL_MMI) */

#endif /* !defined(EMPTY_MMI) && !defined(NEPTUNE_MMI) */

#endif /* NVRAM_NOT_PRESENT */
