/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * Bt_gattc_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to define message of GATT client
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_GATTC_MESSAGE_H__
#define __BT_GATTC_MESSAGE_H__

#ifdef SOURCE_INSIGHT_TRACE
typedef enum
{
#endif
#ifdef BTMTK_ON_MAUI
    MSG_ID_BT_GATTC_REGISTER_REQ,
    MSG_ID_BT_GATTC_GROUP_START = MSG_ID_BT_GATTC_REGISTER_REQ,
#else
    MSG_ID_BT_GATTC_REGISTER_REQ = MSG_ID_BT_GATTC_GROUP_START,
#endif /* BTMTK_ON_MAUI */
    MSG_ID_BT_GATTC_REGISTER_CNF,
    MSG_ID_BT_GATTC_DEREGISTER_REQ,
    MSG_ID_BT_GATTC_DEREGISTER_CNF,
    MSG_ID_BT_GATTC_SCAN_REQ,
    MSG_ID_BT_GATTC_SCAN_RESULT_IND,
    MSG_ID_BT_GATTC_SCAN_CNF,
    MSG_ID_BT_GATTC_SCAN_CANCEL_REQ,
    MSG_ID_BT_GATTC_SCAN_CANCEL_CNF,
    MSG_ID_BT_GATTC_CONNECT_REQ,
    MSG_ID_BT_GATTC_CONNECT_CNF,
    MSG_ID_BT_GATTC_CONNECTED_IND,
    MSG_ID_BT_GATTC_DISCONNECT_REQ,
    MSG_ID_BT_GATTC_DISCONNECT_CNF,
    MSG_ID_BT_GATTC_DISCONNECTED_IND,
    MSG_ID_BT_GATTC_LISTEN_REQ,
    MSG_ID_BT_GATTC_LISTEN_CNF,
    MSG_ID_BT_GATTC_SET_ADV_DATA_REQ,
    MSG_ID_BT_GATTC_SET_ADV_DATA_CNF,
    MSG_ID_BT_GATTC_REFRESH_REQ,
    MSG_ID_BT_GATTC_REFRESH_CNF,
    MSG_ID_BT_GATTC_SEARCH_SERVICE_REQ,
    MSG_ID_BT_GATTC_SEARCH_SERVICE_RESULT_IND,
    MSG_ID_BT_GATTC_SEARCH_SERVICE_CNF,
    MSG_ID_BT_GATTC_GET_INCL_SERVICE_REQ,
    MSG_ID_BT_GATTC_GET_INCL_SERVICE_CNF,
    MSG_ID_BT_GATTC_GET_CHAR_REQ,
    MSG_ID_BT_GATTC_GET_CHAR_CNF,
    MSG_ID_BT_GATTC_GET_DESCR_REQ,
    MSG_ID_BT_GATTC_GET_DESCR_CNF,
    MSG_ID_BT_GATTC_READ_CHAR_REQ,
    MSG_ID_BT_GATTC_READ_CHAR_CNF,
    MSG_ID_BT_GATTC_WRITE_CHAR_REQ,
    MSG_ID_BT_GATTC_WRITE_CHAR_CNF,
    MSG_ID_BT_GATTC_READ_DESCR_REQ,
    MSG_ID_BT_GATTC_READ_DESCR_CNF,
    MSG_ID_BT_GATTC_WRITE_DESCR_REQ,
    MSG_ID_BT_GATTC_WRITE_DESCR_CNF,
    MSG_ID_BT_GATTC_EXEC_WRITE_REQ,
    MSG_ID_BT_GATTC_EXEC_WRITE_CNF,
    MSG_ID_BT_GATTC_REGISTER_NOTIFICATION_REQ,
    MSG_ID_BT_GATTC_REGISTER_NOTIFICATION_CNF,
    MSG_ID_BT_GATTC_DEREGISTER_NOTIFICATION_REQ,
    MSG_ID_BT_GATTC_DEREGISTER_NOTIFICATION_CNF,
    MSG_ID_BT_GATTC_READ_RSSI_REQ,
    MSG_ID_BT_GATTC_READ_RSSI_CNF,
    MSG_ID_BT_GATTC_GET_DEVICE_TYPE_REQ,
    MSG_ID_BT_GATTC_GET_DEVICE_TYPE_CNF,
    MSG_ID_BT_GATTC_CONN_PARAM_UPDATE_REQ,
    MSG_ID_BT_GATTC_CONN_PARAM_UPDATE_CNF,
    MSG_ID_BT_GATTC_SET_ADV_PARAM_REQ,
    MSG_ID_BT_GATTC_SET_ADV_PARAM_CNF,
    MSG_ID_BT_GATTC_START_RESEARCH_SERVICE_IND,
    MSG_ID_BT_GATTC_RESEARCH_SERVICE_IND,
    MSG_ID_BT_GATTC_UPDATE_CONNECTED_INFO,

    MSG_ID_BT_GATTC_NOTIFICATION_IND,
    MSG_ID_BT_GATTC_GROUP_END = MSG_ID_BT_GATTC_NOTIFICATION_IND,

#ifdef SOURCE_INSIGHT_TRACE
} GATTC_MSG_TYPE;
#endif

#endif
