/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * Bt_gatts_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to define message of GATT server
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_GATTS_MESSAGE_H__
#define __BT_GATTS_MESSAGE_H__

#ifdef SOURCE_INSIGHT_TRACE
typedef enum
{
#endif
#ifdef BTMTK_ON_MAUI
    MSG_ID_BT_GATTS_REGISTER_REQ,
    MSG_ID_BT_GATTS_GROUP_START = MSG_ID_BT_GATTS_REGISTER_REQ,
#else
    MSG_ID_BT_GATTS_REGISTER_REQ = MSG_ID_BT_GATTS_GROUP_START,
#endif  /*  BTMTK_ON_MAUI */
    MSG_ID_BT_GATTS_REGISTER_CNF,
    MSG_ID_BT_GATTS_DEREGISTER_REQ,
    MSG_ID_BT_GATTS_DEREGISTER_CNF,
    MSG_ID_BT_GATTS_CONNECT_REQ,
    MSG_ID_BT_GATTS_CONNECT_CNF,
    MSG_ID_BT_GATTS_CONNECTED_IND,
    MSG_ID_BT_GATTS_DISCONNECT_REQ,
    MSG_ID_BT_GATTS_DISCONNECT_CNF,
    MSG_ID_BT_GATTS_DISCONNECTED_IND,
    MSG_ID_BT_GATTS_LISTEN_REQ,
    MSG_ID_BT_GATTS_LISTEN_CNF,
    MSG_ID_BT_GATTS_SET_ADV_DATA_REQ,
    MSG_ID_BT_GATTS_SET_ADV_DATA_CNF,
    MSG_ID_BT_GATTS_ADD_SERVICE_REQ,
    MSG_ID_BT_GATTS_ADD_SERVICE_CNF,
    MSG_ID_BT_GATTS_ADD_INCL_SERVICE_REQ,
    MSG_ID_BT_GATTS_ADD_INCL_SERVICE_CNF,
    MSG_ID_BT_GATTS_ADD_CHAR_REQ,
    MSG_ID_BT_GATTS_ADD_CHAR_CNF,
    MSG_ID_BT_GATTS_ADD_DESCR_REQ,
    MSG_ID_BT_GATTS_ADD_DESCR_CNF,
    MSG_ID_BT_GATTS_START_SERVICE_REQ,
    MSG_ID_BT_GATTS_START_SERVICE_CNF,
    MSG_ID_BT_GATTS_STOP_SERVICE_REQ,
    MSG_ID_BT_GATTS_STOP_SERVICE_CNF,
    MSG_ID_BT_GATTS_DELETE_SERVICE_REQ,
    MSG_ID_BT_GATTS_DELETE_SERVICE_CNF,
    MSG_ID_BT_GATTS_SEND_INDICATION_REQ,
    MSG_ID_BT_GATTS_SEND_INDICATION_CNF,
    MSG_ID_BT_GATTS_SEND_RESPONSE_REQ,
    MSG_ID_BT_GATTS_SEND_RESPONSE_CNF,
    MSG_ID_BT_GATTS_READ_TX_POWER_REQ,
    MSG_ID_BT_GATTS_READ_TX_POWER_CNF,
    MSG_ID_BT_GATTS_UPDATE_CONNECTED_INFO,

    /* Indication messages */
    MSG_ID_BT_GATTS_READ_REQUEST_IND,
    MSG_ID_BT_GATTS_WRITE_REQUEST_IND,
    MSG_ID_BT_GATTS_EXEC_WRITE_REQUEST_IND,
    MSG_ID_BT_GATTS_GET_RANDOM_ADDR_REQ,
    MSG_ID_BT_GATTS_GET_RANDOM_ADDR_CNF,
    MSG_ID_BT_GATTS_GROUP_END = MSG_ID_BT_GATTS_GET_RANDOM_ADDR_CNF,


#ifdef SOURCE_INSIGHT_TRACE
} GATTS_MSG_TYPE;
#endif

#endif
