/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * bluetooth_spp_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_SPP_MESSAGE_H__
#define __BT_SPP_MESSAGE_H__


////////////////////////////////////////////////////////////////
/* external ADP API --> message queue --> internal ADP --> profile API */
/*APP --> SPP, DUN*/
#ifdef BTMTK_ON_MAUI
MSG_ID_BT_SPP_ACTIVATE_REQ,
MSG_ID_BT_SPP_GROUP_START = MSG_ID_BT_SPP_ACTIVATE_REQ,
#else
MSG_ID_BT_SPP_ACTIVATE_REQ = MSG_ID_BT_SPP_GROUP_START,
#endif /* BTMTK_ON_MAUI */
MSG_ID_BT_SPP_CONNECT_REQ, /* Add by stanley to test SPP client: 2007-0313 */
MSG_ID_BT_SPP_SCO_CONNECT_REQ,
MSG_ID_BT_SPP_SEND_DATA_REQ,
MSG_ID_BT_SPP_GET_DATA_REQ,
MSG_ID_BT_SPP_DEACTIVATE_REQ,
MSG_ID_BT_SPP_DISCONNECT_REQ,
MSG_ID_BT_SPP_AUDIO_CONNECT_REQ,
MSG_ID_BT_SPP_AUDIO_DISCONNECT_REQ,
MSG_ID_BT_SPP_CONNECT_IND_RSP,
MSG_ID_BT_SPP_AUTH_RSP,
/* Add by stanley 2007-0402: Notify BT can check if UART_READY_TO_READ_IND is necessary to send or not becasue MMI is owner of port and can receive data */
MSG_ID_BT_SPP_UART_OWNER_CNF,
/* Add by stanley 2007-0402: Notify BT can chage the owner of port and MMI has do something completely for UART_PLUGOUT_IND */
MSG_ID_BT_SPP_UART_PLUGOUT_CNF,
MSG_ID_BT_DUN_CONNECT_REQ,   /* for DUN_CLIENT */
MSG_ID_BT_DUN_ACTIVATE_REQ,
MSG_ID_BT_DUN_DEACTIVATE_REQ,
MSG_ID_BT_DUN_DISCONNECT_REQ,
MSG_ID_BT_DUN_CONNECT_IND_RSP,
MSG_ID_BT_DUN_AUTH_RSP,

/* Add FAX related msg by stanley: 2006-11-22 */
MSG_ID_BT_FAX_ACTIVATE_REQ,
MSG_ID_BT_FAX_DEACTIVATE_REQ,
MSG_ID_BT_FAX_DISCONNECT_REQ,
MSG_ID_BT_FAX_CONNECT_IND_RSP,
MSG_ID_BT_FAX_AUTH_RSP,
MSG_ID_BT_FAX_CONNECT_REQ,   /* for FAX_CLIENT */

/* Bingyi: for SW partition */
MSG_ID_BT_SPP_INITIALIZE_REQ,
MSG_ID_BT_SPP_INITIALIZE_CNF,
MSG_ID_BT_SPP_REGISTER_CALLBACK_REQ,
MSG_ID_BT_SPP_REGISTER_CALLBACK_CNF,

/* Bingyi: UART related API */
MSG_ID_BT_SPP_UART_OPEN_REQ,
MSG_ID_BT_SPP_UART_OPEN_CNF,
MSG_ID_BT_SPP_UART_CLOSE_REQ,
MSG_ID_BT_SPP_UART_CLOSE_CNF,
MSG_ID_BT_SPP_UART_GET_BYTES_REQ,
MSG_ID_BT_SPP_UART_GET_BYTES_CNF,
MSG_ID_BT_SPP_UART_PUT_BYTES_REQ,
MSG_ID_BT_SPP_UART_PUT_BYTES_CNF,
MSG_ID_BT_SPP_UART_GET_BYTES_AVAIL_REQ,
MSG_ID_BT_SPP_UART_GET_BYTES_AVAIL_CNF,
MSG_ID_BT_SPP_UART_GET_TX_ROOM_LEFT_REQ,
MSG_ID_BT_SPP_UART_GET_TX_ROOM_LEFT_CNF,
MSG_ID_BT_SPP_UART_SET_OWNER_REQ,
MSG_ID_BT_SPP_UART_SET_OWNER_CNF,
MSG_ID_BT_SPP_UART_CTRL_DCD_REQ,
MSG_ID_BT_SPP_UART_CTRL_DCD_CNF,
MSG_ID_BT_SPP_UART_CTRL_BREAK_REQ,
MSG_ID_BT_SPP_UART_CTRL_BREAK_CNF,
MSG_ID_BT_SPP_UART_CLR_RX_BUFFER_REQ,
MSG_ID_BT_SPP_UART_CLR_RX_BUFFER_CNF,
MSG_ID_BT_SPP_UART_CLR_TX_BUFFER_REQ,
MSG_ID_BT_SPP_UART_CLR_TX_BUFFER_CNF,
MSG_ID_BT_SPP_UART_GET_OWNER_ID_REQ,
MSG_ID_BT_SPP_UART_GET_OWNER_ID_CNF,

MSG_ID_BT_SPP_UART_PLUGOUT_IND,
MSG_ID_BT_SPP_UART_READY_TO_READ_IND,
MSG_ID_BT_SPP_UART_READY_TO_WRITE_IND,

////////////////////////////////////////////////////////////////
/* ADP API <-- message queue <-- internal ADP <-- profile API */
/*APP <-- SPP*/
MSG_ID_BT_SPP_CONNECT_IND,
MSG_ID_BT_SPP_CONNECT_IND_REQ,
MSG_ID_BT_SPP_SCO_CONNECT_IND,
MSG_ID_BT_SPP_DISCONNECT_IND,
MSG_ID_BT_SPP_ACTIVATE_CNF,
MSG_ID_BT_SPP_DEACTIVATE_CNF,
MSG_ID_BT_SPP_DISCONNECT_CNF,
MSG_ID_BT_SPP_AUTH_REQ,
MSG_ID_BT_SPP_AUDIO_CONNECT_CNF,
MSG_ID_BT_SPP_AUDIO_CONNECT_IND,
MSG_ID_BT_SPP_AUDIO_DISCONNECT_CNF,
MSG_ID_BT_SPP_AUDIO_DISCONNECT_IND,
MSG_ID_BT_SPP_SCO_RSSI_IND,
MSG_ID_BT_SPP_CONNECT_CNF,  /* Add by stanley for SPP client's cnf to MMI */

MSG_ID_BT_SPP_UART_OWNER_IND, /* Add by stanley 2007-0401: to notify SPP server that it is the uart owner now */

/*APP <-- DUN*/
MSG_ID_BT_DUN_CONNECT_IND,
MSG_ID_BT_DUN_CONNECT_IND_REQ,
MSG_ID_BT_DUN_DISCONNECT_IND,
MSG_ID_BT_DUN_ACTIVATE_CNF,
MSG_ID_BT_DUN_DEACTIVATE_CNF,
MSG_ID_BT_DUN_DISCONNECT_CNF,
MSG_ID_BT_DUN_AUTH_REQ,
MSG_ID_BT_DUN_CONNECT_CNF,    /* for DUN_CLIENT */

/*APP <-- FAX: Add by stanley:2006-11-22*/
MSG_ID_BT_FAX_CONNECT_IND,
MSG_ID_BT_FAX_CONNECT_IND_REQ,
MSG_ID_BT_FAX_DISCONNECT_IND,
MSG_ID_BT_FAX_ACTIVATE_CNF,
MSG_ID_BT_FAX_DEACTIVATE_CNF,
MSG_ID_BT_FAX_DISCONNECT_CNF,
MSG_ID_BT_FAX_AUTH_REQ,
MSG_ID_BT_FAX_CONNECT_CNF, 	/* for FAX_CLIENT */

/* Bingyi: Send IND to APP when data is received. APP <-- SPP */
MSG_ID_BT_SPP_UART_DATA_AVAILABLE_IND,
MSG_ID_BT_SPP_UART_DATA_AVAILABLE_IND_RSP,

#ifdef __SPP_SHARED_MEMORY__
MSG_ID_BT_UART_ASSIGN_BUFFER_REQ,
MSG_ID_BT_UART_ASSIGN_BUFFER_CNF,
#endif	/* __SPP_SHARED_MEMORY__ */

/* Customization for WISE */
MSG_ID_BT_SPP_ENABLE_REQ,
MSG_ID_BT_SPP_ENABLE_CNF,
MSG_ID_BT_SPP_DISABLE_REQ,
MSG_ID_BT_SPP_DISABLE_CNF,

MSG_ID_BT_SPP_GROUP_END = MSG_ID_BT_SPP_DISABLE_CNF,


#endif	// __BT_SPP_MESSAGE_H__

