/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * Bt_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_MESSAGE_H__
#define __BT_MESSAGE_H__

#ifndef BTMTK_ON_MAUI
typedef enum
{
    MSG_ID_BT_START = 0,
    MSG_ID_BT_RANGE = 100,

    /* GAP */
    MSG_ID_BT_GAP_GROUP_START = (MSG_ID_BT_START + MSG_ID_BT_RANGE),
    MSG_ID_BT_GAP_GROUP_RANGE = 100,

    /* SDP */
    MSG_ID_BT_SDP_GROUP_START = (MSG_ID_BT_GAP_GROUP_START + MSG_ID_BT_GAP_GROUP_RANGE),
    MSG_ID_BT_SDP_GROUP_RANGE = 100,

    /* A2DP */
    MSG_ID_BT_A2DP_GROUP_START = (MSG_ID_BT_SDP_GROUP_START + MSG_ID_BT_SDP_GROUP_RANGE),
    MSG_ID_BT_A2DP_GROUP_RANGE = 100,

    /* A2DP Data */
    MSG_ID_BT_A2DP_DATA_GROUP_START = (MSG_ID_BT_A2DP_GROUP_START + MSG_ID_BT_A2DP_GROUP_RANGE),
    MSG_ID_BT_A2DP_DATA_GROUP_RANGE = 100,

    /* AVRCP */
    MSG_ID_BT_AVRCP_GROUP_START = (MSG_ID_BT_A2DP_DATA_GROUP_START + MSG_ID_BT_A2DP_DATA_GROUP_RANGE),
    MSG_ID_BT_AVRCP_GROUP_RANGE = 200,

    /* BIPI */
    MSG_ID_BT_BIPI_GROUP_START = (MSG_ID_BT_AVRCP_GROUP_START + MSG_ID_BT_AVRCP_GROUP_RANGE),
    MSG_ID_BT_BIPI_GROUP_RANGE = 100,

    /* BIPIR */
    MSG_ID_BT_BIPR_GROUP_START = (MSG_ID_BT_BIPI_GROUP_START + MSG_ID_BT_BIPI_GROUP_RANGE),
    MSG_ID_BT_BIPR_GROUP_RANGE = 100,

    /* BPP */
    MSG_ID_BT_BPP_GROUP_START = (MSG_ID_BT_BIPR_GROUP_START + MSG_ID_BT_BIPR_GROUP_RANGE),
    MSG_ID_BT_BPP_GROUP_RANGE = 100,

    /* DUN */
    MSG_ID_BT_DUN_GROUP_START = (MSG_ID_BT_BPP_GROUP_START + MSG_ID_BT_BPP_GROUP_RANGE),
    MSG_ID_BT_DUN_GROUP_RANGE = 100,

    /* FAX */
    MSG_ID_BT_FAX_GROUP_START = (MSG_ID_BT_DUN_GROUP_START + MSG_ID_BT_DUN_GROUP_RANGE),
    MSG_ID_BT_FAX_GROUP_RANGE = 100,

    /* FTPC */
    MSG_ID_BT_FTPC_GROUP_START = (MSG_ID_BT_FAX_GROUP_START + MSG_ID_BT_FAX_GROUP_RANGE),
    MSG_ID_BT_FTPC_GROUP_RANGE = 100,

    /* FTPS */
    MSG_ID_BT_FTPS_GROUP_START = (MSG_ID_BT_FTPC_GROUP_START + MSG_ID_BT_FTPC_GROUP_RANGE),
    MSG_ID_BT_FTPS_GROUP_RANGE = 100,

    /* GOEPC */
    MSG_ID_BT_GOEPC_GROUP_START = (MSG_ID_BT_FTPS_GROUP_START + MSG_ID_BT_FTPS_GROUP_RANGE),
    MSG_ID_BT_GOEPC_GROUP_RANGE = 100,

    /* GOEPS */
    MSG_ID_BT_GOEPS_GROUP_START = (MSG_ID_BT_GOEPC_GROUP_START + MSG_ID_BT_GOEPC_GROUP_RANGE),
    MSG_ID_BT_GOEPS_GROUP_RANGE = 100,

    /* HFG */
    MSG_ID_BT_HFG_GROUP_START = (MSG_ID_BT_GOEPS_GROUP_START + MSG_ID_BT_GOEPS_GROUP_RANGE),
    MSG_ID_BT_HFG_GROUP_RANGE = 300,

    /* Handsfree */
    MSG_ID_BT_HF_GROUP_START = (MSG_ID_BT_HFG_GROUP_START + MSG_ID_BT_HFG_GROUP_RANGE),
    MSG_ID_BT_HF_GROUP_RANGE = 100,

    /* HID */
    MSG_ID_BT_HID_GROUP_START = (MSG_ID_BT_HF_GROUP_START + MSG_ID_BT_HF_GROUP_RANGE),
    MSG_ID_BT_HID_GROUP_RANGE = 100,

    /* HSG */
    MSG_ID_BT_HSG_GROUP_START = (MSG_ID_BT_HID_GROUP_START + MSG_ID_BT_HID_GROUP_RANGE),
    MSG_ID_BT_HSG_GROUP_RANGE = 100,

    /* OPPC */
    MSG_ID_BT_OPPC_GROUP_START = (MSG_ID_BT_HSG_GROUP_START + MSG_ID_BT_HSG_GROUP_RANGE),
    MSG_ID_BT_OPPC_GROUP_RANGE = 100,

    /* OPPS */
    MSG_ID_BT_OPPS_GROUP_START = (MSG_ID_BT_OPPC_GROUP_START + MSG_ID_BT_OPPC_GROUP_RANGE),
    MSG_ID_BT_OPPS_GROUP_RANGE = 100,

    /* PBAPC*/
    MSG_ID_BT_PBAPC_GROUP_START = (MSG_ID_BT_OPPS_GROUP_START + MSG_ID_BT_OPPS_GROUP_RANGE),
    MSG_ID_BT_PBAPC_GROUP_RANGE = 50,

    /* PBAP */
    MSG_ID_BT_PBAP_GROUP_START = (MSG_ID_BT_PBAPC_GROUP_START + MSG_ID_BT_PBAPC_GROUP_RANGE),
    MSG_ID_BT_PBAP_GROUP_RANGE = 100,

    /* SIMAP */
    MSG_ID_BT_SIMAP_GROUP_START = (MSG_ID_BT_PBAP_GROUP_START + MSG_ID_BT_PBAP_GROUP_RANGE),
    MSG_ID_BT_SIMAP_GROUP_RANGE = 100,

    /* SPP */
    MSG_ID_BT_SPP_GROUP_START = (MSG_ID_BT_SIMAP_GROUP_START + MSG_ID_BT_SIMAP_GROUP_RANGE),
    MSG_ID_BT_SPP_GROUP_RANGE = 100,

    /* JSR82 */
    MSG_ID_BT_JSR82_GROUP_START = (MSG_ID_BT_SPP_GROUP_START + MSG_ID_BT_SPP_GROUP_RANGE),
    MSG_ID_BT_JSR82_GROUP_RANGE = 100,

    /* CHN */
    MSG_ID_BT_CHN_GROUP_START = (MSG_ID_BT_JSR82_GROUP_START + MSG_ID_BT_JSR82_GROUP_RANGE),
    MSG_ID_BT_CHN_GROUP_RANGE = 100,

    /* MAP */
    MSG_ID_BT_MAP_GROUP_START = (MSG_ID_BT_CHN_GROUP_START + MSG_ID_BT_CHN_GROUP_RANGE),
    MSG_ID_BT_MAP_GROUP_RANGE = 100,

    /* PRX */
    MSG_ID_BT_PRXM_GROUP_START = (MSG_ID_BT_MAP_GROUP_START + MSG_ID_BT_MAP_GROUP_RANGE),
    MSG_ID_BT_PRXM_GROUP_RANGE = 100,
    MSG_ID_BT_PRXR_GROUP_START = (MSG_ID_BT_PRXM_GROUP_START + MSG_ID_BT_PRXM_GROUP_RANGE),
    MSG_ID_BT_PRXR_GROUP_RANGE = 100,

    /* PAN */
    MSG_ID_BT_PAN_GROUP_START = (MSG_ID_BT_PRXR_GROUP_START + MSG_ID_BT_PRXR_GROUP_RANGE),
    MSG_ID_BT_PAN_GROUP_RANGE = 100,

    /* A2DP FM VIA CONTROLLER */
    MSG_ID_BT_A2DP_FM_VIA_CONTROLLER_GROUP_START = (MSG_ID_BT_PAN_GROUP_START + MSG_ID_BT_PAN_GROUP_RANGE),
    MSG_ID_BT_A2DP_FM_VIA_CONTROLLER_GROUP_RANGE = 100,

    /* TIME */
    MSG_ID_BT_TIMEC_GROUP_START = (MSG_ID_BT_A2DP_FM_VIA_CONTROLLER_GROUP_START + MSG_ID_BT_A2DP_FM_VIA_CONTROLLER_GROUP_RANGE),
    MSG_ID_BT_TIMEC_GROUP_RANGE = 100,
    MSG_ID_BT_TIMES_GROUP_START = (MSG_ID_BT_TIMEC_GROUP_START + MSG_ID_BT_TIMEC_GROUP_RANGE),
    MSG_ID_BT_TIMES_GROUP_RANGE = 100,

    /* HDP */
    MSG_ID_BT_HDP_GROUP_START = (MSG_ID_BT_TIMES_GROUP_START + MSG_ID_BT_TIMES_GROUP_RANGE),
    MSG_ID_BT_HDP_GROUP_RANGE = 100,

    /* HTP */
    MSG_ID_BT_HTP_GROUP_START = (MSG_ID_BT_HDP_GROUP_START + MSG_ID_BT_HDP_GROUP_RANGE),
    MSG_ID_BT_HTP_GROUP_RANGE = 100,

    /* FMP */
    MSG_ID_BT_FMP_GROUP_START = (MSG_ID_BT_HTP_GROUP_START + MSG_ID_BT_HTP_GROUP_RANGE),
    MSG_ID_BT_FMP_GROUP_RANGE = 100,

    /* GATTC */
    MSG_ID_BT_GATTC_GROUP_START = (MSG_ID_BT_FMP_GROUP_START + MSG_ID_BT_FMP_GROUP_RANGE),
    MSG_ID_BT_GATTC_GROUP_RANGE = 100,

    /* GATTS */
    MSG_ID_BT_GATTS_GROUP_START = (MSG_ID_BT_GATTC_GROUP_START + MSG_ID_BT_GATTC_GROUP_RANGE),
    MSG_ID_BT_GATTS_GROUP_RANGE = 100,

    CUSTOM_MSG_ID_BEGIN = (MSG_ID_BT_FMP_GROUP_START + MSG_ID_BT_FMP_GROUP_RANGE + 1000),

    /* Below is the message interface for other modules */
    /* PAL */
    MSG_ID_EXT_MSG_CODE_BEGIN = 0x80000000,
    MSG_ID_PAL_MSG_CODE_BEGIN = MSG_ID_EXT_MSG_CODE_BEGIN,
    MSG_ID_PAL_MSG_CODE_RANGE = 300,

    MSG_ID_BT_SDAP_TESTER_GROUP_START = MSG_ID_PAL_MSG_CODE_BEGIN + MSG_ID_PAL_MSG_CODE_RANGE,
    MSG_ID_BT_SDAP_TESTER_GROUP_RANGE = 100,

} MSG_ID_CODE_BEGIN;

typedef enum
{
#include "bluetooth_sap.h"
} msg_type;
#endif  /* BTMTK_ON_MAUI */

#endif
